---
sidebar: sidebar 
permalink: ontap-security-hardening/create-fpolicy.html 
keywords: tr-4569, ontap hardening guide, security, native, external server, file policy, take actions, synchronous, asynchronous, storage workload security 
summary: 為了提供檔案的可見度和存取控制、 ONTAP 解決方案使用 NetApp FPolicy 功能。 
---
= 建立及使用 NetApp FPolicy
:hardbreaks:
:allow-uri-read: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以建立及使用 FPolicy 、這是 ONTAP 解決方案的基礎架構元件、可讓合作夥伴應用程式監控及設定檔案存取權限。其中一個功能更強大的應用程式是儲存工作負載安全、這是 NetApp SaaS 應用程式、可在混合雲環境中集中可見度及控制所有企業資料存取、確保安全性與法規遵循目標得以達成。

存取控制是一項重要的安全概念。可見度和回應檔案存取和檔案作業的能力、對於維持您的安全狀態至關重要。為了提供檔案的可見度和存取控制、 ONTAP 解決方案使用 NetApp FPolicy 功能。

檔案原則可以根據檔案類型來設定。FPolicy 決定儲存系統如何處理個別用戶端系統的要求、以執行建立、開啟、重新命名及刪除等作業。從 ONTAP 9 開始、 FPolicy 檔案存取通知架構就會透過篩選控制和恢復功能來增強、以避免短暫的網路中斷。

.步驟
. 若要使用 FPolicy 功能、您必須先使用命令建立 FPolicy 原則 `vserver fpolicy policy create` 。
+

NOTE: 此外、如果您使用 FPolicy 來查看和收集事件、請使用此 `-events` 參數。ONTAP 提供的額外精細度可讓您篩選及存取控制的使用者名稱層級。若要使用使用者名稱來控制權限和存取、請指定 `-privilege-user-name` 參數。

+
下列文字提供 FPolicy 建立範例：

+
[listing]
----
cluster1::> vserver fpolicy policy create -vserver vs1.example.com -policy-name vs1_pol -events cserver_evt,v1e1 -engine native -is-mandatory true -allow-privileged-access no -is-passthrough-read-enabled false
----
. 建立 FPolicy 原則之後、您必須使用命令加以啟用 `vserver fpolicy enable` 。此命令也會設定 FPolicy 項目的優先順序或順序。
+

NOTE: FPolicy 順序很重要、因為如果多個原則已訂閱相同的檔案存取事件、則順序會指示存取的授與或拒絕順序。

+
下列文字提供啟用 FPolicy 原則和使用命令驗證組態的範例組態 `vserver fpolicy show` ：

+
[listing]
----
cluster1::> vserver fpolicy enable -vserver vs2.example.com -policy-name vs2_pol -sequence-number 5

cluster1::> vserver fpolicy show
Vserver                 Policy Name                    Sequence  Status   Engine
----------------------- ------------------------------ --------  -------  -------
vs1.example.com         vs1_pol
vs2.example.com         vs2_pol
 external
2 entries were displayed.
----




== FPolicy 增強功能

ONTAP 9 包括以下各節所述的 FPolicy 增強功能。



=== 篩選控制項

新的篩選器可用於 `SetAttr` 和移除目錄活動的通知。



=== 非同步恢復能力

如果以非同步模式運作的FPolicy伺服器發生網路中斷、則中斷期間產生的FPolicy通知會儲存在儲存節點上。當FPolicy伺服器重新連線時、系統會警示已儲存的通知、並從儲存節點擷取通知。在停機期間可儲存通知的時間長度可設定為10分鐘。
