---
sidebar: sidebar 
permalink: authentication-access-control/manage-webauthn-settings-credentials.html 
keywords: mfa, multi-factor, authentication, authorization, webauthn, FIDO2, hardware key, credentials, manage, system manager, settings, configuration, credential 
summary: 您可以檢視 WebAuthn MFA 的通用設定，並管理使用者認證。 
---
= 檢視 ONTAP WebAuthn MFA 設定並管理認證
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
身為 ONTAP 管理員，您可以檢視整個叢集的 WebAuthn MFA 設定，並管理 WebAuthn MFA 的使用者和群組認證。



== 檢視 WebAuthn MFA 的叢集設定

您可以使用 ONTAP CLI 檢視 WebAuthn MFA 的叢集設定。

.步驟
. 檢視 WebAuthn MFA 的叢集設定。您可以選擇使用下列引數指定儲存 VM `vserver` ：
+
[source, console]
----
security webauthn show -vserver <storage_vm_name>
----




== 檢視支援的公開金鑰 WebAuthn MFA 演算法

您可以檢視儲存 VM 或叢集所支援的 WebAuthn MFA 公開金鑰演算法。

.步驟
. 列出支援的公開金鑰 WebAuthn MFA 演算法。您可以選擇使用下列引數指定儲存 VM `vserver` ：
+
[source, console]
----
security webauthn supported-algorithms show -vserver <storage_vm_name>
----




== 檢視已註冊的 WebAuthn MFA 認證

身為 ONTAP 管理員，您可以檢視所有使用者的註冊 WebAuthn 認證。使用此程序的非系統管理員使用者只能檢視自己已註冊的 WebAuthn 認證。

.步驟
. 檢視已註冊的 WebAuthn MFA 認證：
+
[source, console]
----
security webauthn credentials show
----




== 移除已註冊的 WebAuthn MFA 認證

您可以移除已註冊的 WebAuthn MFA 認證。當使用者的硬體金鑰遺失，遭竊或不再使用時，此功能非常實用。當使用者仍擁有原始硬體驗證者，但想要以新的驗證者來取代時，您也可以移除已登錄的認證。移除認證之後，系統會提示使用者註冊替換驗證者。


NOTE: 移除使用者的登錄認證並不會停用使用者的 WebAuthn MFA 。如果使用者遺失硬體驗證者，需要先登入再進行更換，您需要使用這些步驟移除認證，也需要針對使用者移除認證link:disable-webauthn-mfa-task.html["停用 WebAuthn MFA"]。

[role="tabbed-block"]
====
.系統管理員
--
. 選擇*叢集>設定*。
. 選取 * 使用者和角色 * 旁邊的箭頭圖示。
. 在使用者和群組清單中，針對您要移除其認證的使用者或群組，選取選項功能表。
. 選取 * 移除 MFA 以取得 HTTP 認證 * 。
. 選擇*移除*。


--
.CLI
--
. 刪除已註冊的認證。請注意下列事項：
+
** 您可以選擇性地指定使用者的儲存 VM 。如果省略，則會在叢集層級移除認證。
** 您可以選擇性地指定要刪除認證的使用者名稱。如果省略，則會移除目前使用者的認證。
+
[source, console]
----
security webauthn credentials delete -vserver <storage_vm_name> -username <username>
----




--
====
如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+webauthn+show["指令參考資料ONTAP"^]需詳細 `security webauthn show`資訊，請參閱。
