---
sidebar: sidebar 
permalink: authentication-access-control/manage-webauthn-settings-credentials.html 
keywords: mfa, multi-factor, multifactor, authentication, authorization, webauthn, FIDO2, hardware key, credentials, manage, system manager, settings, configuration, credential 
summary: 您可以檢視 WebAuthn MFA 的通用設定，並管理使用者認證。 
---
= 檢視 ONTAP WebAuthn MFA 設定並管理認證
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
身為 ONTAP 管理員，您可以檢視整個叢集的 WebAuthn MFA 設定，並管理 WebAuthn MFA 的使用者和群組認證。



[[view-cluster-settings-for-webauthn-mfa]]
== 檢視 WebAuthn MFA 的叢集設定

您可以使用 ONTAP CLI 檢視 WebAuthn MFA 的叢集設定。

.步驟
. 檢視 WebAuthn MFA 的叢集設定。您可以選擇使用下列引數指定儲存 VM `vserver` ：
+
[source, console]
----
security webauthn show -vserver <storage_vm_name>
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+webauthn+show["指令參考資料ONTAP"^]需詳細 `security webauthn show`資訊，請參閱。





[[restrict-the-set-of-permitted-relying-party-rp-domains]]
== 限制允許的信賴方（RP）網域集

從 ONTAP 9.19.1 開始，管理者必須在 WebAuthn 全域設定命令中使用參數 -rp-domains。這允許管理員明確限制在 System Manager 中 WebAuthn （FIDO2）多因素驗證期間接受的允許信賴方 （RP） 網域集。

使用者只能從允許的 RP 網域存取 MFA。


NOTE: 如果您要從 ONTAP 9.16.1 到 9.18.1 升級至 ONTAP 9.19.1，請參閱link:https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-Issues/CONTAP-597688["CONTAP-597688"]以取得更多資訊。

[role="tabbed-block"]
====
.系統管理員
--
. 選取 *Cluster > Settings > Multifactor authentication (MFA)*。
. 新增、刪除或修改允許的 RP 網域。


--
.CLI
--
. 修改允許的 rp 網域。將 -rp-domains 設定為完整的叢集 FQDN：
+
[source, console]
----
security webauthn modify -rp-domains <mycluster.us-east.example.com>
----
+
深入瞭解  `security webauthn modify`，請參閱 link:https://docs.netapp.com/us-en/ontap-cli/security-webauthn-modify.html#parameters["指令參考資料ONTAP"^]。



--
====


[[view-supported-public-key-webauthn-mfa-algorithms]]
== 檢視支援的公開金鑰 WebAuthn MFA 演算法

您可以檢視儲存 VM 或叢集所支援的 WebAuthn MFA 公開金鑰演算法。

.步驟
. 列出支援的公開金鑰 WebAuthn MFA 演算法。您可以選擇使用下列引數指定儲存 VM `vserver` ：
+
[source, console]
----
security webauthn supported-algorithms show -vserver <storage_vm_name>
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/security-webauthn-supported-algorithms-show.html["指令參考資料ONTAP"^]需詳細 `security webauthn supported-algorithms show`資訊，請參閱。





[[view-the-registered-webauthn-mfa-credentials]]
== 檢視已註冊的 WebAuthn MFA 認證

身為 ONTAP 管理員，您可以檢視所有使用者的註冊 WebAuthn 認證。使用此程序的非系統管理員使用者只能檢視自己已註冊的 WebAuthn 認證。

.步驟
. 檢視已註冊的 WebAuthn MFA 認證：
+
[source, console]
----
security webauthn credentials show
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/security-webauthn-credentials-show.html["指令參考資料ONTAP"^]需詳細 `security webauthn credentials show`資訊，請參閱。





[[remove-a-registered-webauthn-mfa-credential]]
== 移除已註冊的 WebAuthn MFA 認證

您可以移除已註冊的 WebAuthn MFA 認證。當使用者的硬體金鑰遺失，遭竊或不再使用時，此功能非常實用。當使用者仍擁有原始硬體驗證者，但想要以新的驗證者來取代時，您也可以移除已登錄的認證。移除認證之後，系統會提示使用者註冊替換驗證者。


NOTE: 移除使用者的登錄認證並不會停用使用者的 WebAuthn MFA 。如果使用者遺失硬體驗證者，需要先登入再進行更換，您需要使用這些步驟移除認證，也需要針對使用者移除認證link:disable-webauthn-mfa-task.html["停用 WebAuthn MFA"]。

[role="tabbed-block"]
====
.系統管理員
--
. 選擇*叢集>設定*。
. 選取 * 使用者和角色 * 旁邊的箭頭圖示。
. 在使用者和群組清單中，針對您要移除其認證的使用者或群組，選取選項功能表。
. 選取 * 移除 MFA 以取得 HTTP 認證 * 。
. 選擇*移除*。


--
.CLI
--
. 刪除已註冊的認證。請注意下列事項：
+
** 您可以選擇性地指定使用者的儲存 VM 。如果省略，則會在叢集層級移除認證。
** 您可以選擇性地指定要刪除認證的使用者名稱。如果省略，則會移除目前使用者的認證。
+
[source, console]
----
security webauthn credentials delete -vserver <storage_vm_name> -username <username>
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/security-webauthn-credentials-delete.html["指令參考資料ONTAP"^]需詳細 `security webauthn credentials delete`資訊，請參閱。





--
====