---
sidebar: sidebar 
permalink: ransomware-solutions/ransomware-fpolicy.html 
keywords: tr-4572, technical report, ransomware, protect, protection, netapp ransomware protection, netapp tr, ontap tr 
summary: NetApp 的勒索軟體保護包括 FPolicy 、可防止不想要的檔案儲存在企業級儲存設備上。 
---
= FPolicy 檔案封鎖
:allow-uri-read: 


[role="lead"]
FPolicy 可防止不想要的檔案儲存在企業級儲存設備上。FPolicy 也可讓您封鎖已知的勒索軟體副檔名。使用者仍擁有主資料夾的完整存取權限、但 FPolicy 不允許使用者儲存管理員標記為封鎖的檔案。無論這些檔案是 MP3 檔案或已知的勒索軟體副檔名、都沒問題。



== 使用 FPolicy 原生模式封鎖惡意檔案

NetApp FPolicy 原生模式（名稱的進化、檔案原則）是檔案副檔名封鎖架構、可讓您封鎖不想要的檔案副檔名、使其無法進入您的環境。這是 ONTAP 十多年來的一部分、在協助您防範勒索軟體方面非常有用。這款 Zero Trust 引擎非常實用、因為除了存取控制清單（ ACL ）權限之外、您還能獲得額外的安全措施。

在 ONTAP 系統管理員和 BlueXP  中、有超過 3000 個副檔名的清單可供參考。


WARNING: 某些擴充功能在您的環境中可能是合法的、而封鎖這些擴充功能可能會導致非預期的問題。在設定原生 FPolicy 之前、請先建立適合您環境的清單。

所有 ONTAP 授權均包含 FPolicy 原生模式。

.深入瞭解
* https://www.netapp.com/blog/fighting-ransomware-tools/["部落格：對抗勒索軟體：第三部分： ONTAP FPolicy 、另一個強大的原生（又稱為免費）工具"^]




== 使用 FPolicy 外部模式啟用使用者和實體行為分析（ UEBA ）

FPolicy 外部模式是檔案活動通知和控制架構、可提供檔案和使用者活動的可見度。外部解決方案可使用這些通知來執行 AI 型分析、以偵測惡意行為。

也可以將 FPolicy 外部模式設定為等待 FPolicy 伺服器核准、再允許特定活動通過。這樣的多個原則可在叢集上進行設定、提供您極大的彈性。


WARNING: 如果設定為提供核准、 FPolicy 伺服器必須回應 FPolicy 要求；否則、儲存系統效能可能會受到負面影響。

FPolicy 外部模式包含在link:../system-admin/manage-licenses-concept.html["所有 ONTAP 授權"]中。

.深入瞭解
* https://www.netapp.com/blog/fighting-ransomware-ontap-fpolicy/["部落格：對抗勒索軟體：第四部分：使用 FPolicy 外部模式的 UBA 和 ONTAP 。"^]

