---
permalink: s3-config/create-data-lifs-task.html 
sidebar: sidebar 
keywords: tr-4814, create, data, lifs 
summary: 如果您建立新的SVM、您為S3存取所建立的專屬lifs應該是資料lifs。 
---
= 為 ONTAP S3 建立資料生命
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您建立新的SVM、您為S3存取所建立的專屬lifs應該是資料lifs。

.開始之前
* 基礎實體或邏輯網路連接埠必須已設定為系統管理 `up` 狀態。
* 如果您打算使用子網路名稱來配置LIF的IP位址和網路遮罩值、則該子網路必須已經存在。
+
子網路包含屬於同一第3層子網路的IP位址集區。它們是使用建立的 `network subnet create` 命令。

* LIF服務原則必須已經存在。
* 最佳實務做法是、用於資料存取（資料 S3 伺服器）的生命體和用於管理作業（管理 https ）的生命體應該分開。不應在相同的 LIF 上啟用這兩項服務。
* DNS 記錄應該只有與之相關聯的資料 S3 伺服器的生命體 IP 位址。如果在 DNS 記錄中指定其他生命的 IP 位址，則其他伺服器可能會為 ONTAP S3 要求提供服務，導致非預期的回應或資料遺失。


.關於這項工作
* 您可以在同一個網路連接埠上同時建立IPV4和IPv6 LIF。
* 如果叢集中有大量的生命、您可以使用來驗證叢集上支援的 LIF 容量 `network interface capacity show` 命令和 LIF 容量、可透過使用在每個節點上支援 `network interface capacity details show` 命令（進階權限層級）。
* 如果您要啟用遠端FabricPool 的靜態容量（雲端）分層、則也必須設定叢集間的LIF。


.步驟
. 建立LIF：
+
`network interface create -vserver _svm_name_ -lif _lif_name_ -service-policy _service_policy_names_ -home-node _node_name_ -home-port _port_name_ {-address _IP_address_ -netmask _IP_address_ | -subnet-name _subnet_name_} -firewall-policy data -auto-revert {true|false}`

+
** `-home-node` 是 LIF 在返回時返回的節點 `network interface revert` 命令會在LIF上執行。
+
您也可以指定 LIF 是否應該使用自動還原至主節點和主連接埠 `-auto-revert` 選項。

** `-home-port` 是 LIF 在時傳回的實體或邏輯連接埠 `network interface revert` 命令會在LIF上執行。
** 您可以使用指定 IP 位址 `-address` 和 `-netmask` 或是您可以使用從子網路進行分配 `-subnet_name` 選項。
** 使用子網路提供IP位址和網路遮罩時、如果子網路是使用閘道定義、則使用該子網路建立LIF時、會自動將通往該閘道的預設路由新增至SVM。
** 如果您手動指派IP位址（不使用子網路）、則在不同IP子網路上有用戶端或網域控制器時、可能需要設定通往閘道的預設路由。在中深入瞭解 `network route create`並建立 SVM 內的靜態路由link:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["指令參考資料ONTAP"^]。
** 適用於 `-firewall-policy` 選項、請使用相同的預設值 `data` 成為 LIF 角色。
+
如果需要、您可以稍後建立並新增自訂防火牆原則。

+

NOTE: 從ONTAP S振 分9.10.1開始、防火牆原則已過時、並完全由LIF服務原則取代。如需詳細資訊、請參閱 link:../networking/configure_firewall_policies_for_lifs.html["設定lifs的防火牆原則"]。

** `-auto-revert` 可讓您指定資料 LIF 是否在啟動、管理資料庫狀態變更或建立網路連線等情況下自動還原至其主節點。預設設定為 `false`但您可以將其設定為 `false` 視環境中的網路管理原則而定。
** 。 `-service-policy` 選項會指定您建立的資料和管理服務原則、以及您需要的任何其他原則。


. 如果您要在中指派 IPv6 位址 `-address` 選項：
+
.. 使用 `network ndp prefix show` 用於查看在各種接口上學習的 RA 前綴列表的命令。
+
。 `network ndp prefix show` 命令可在進階權限層級使用。

.. 使用格式 `prefix:id` 手動建構 IPv6 位址。
+
`prefix` 是在各種介面上學習的首碼。

+
用於導出 `id`，選擇隨機 64 位元十六進位數字。



. 使用確認 LIF 已成功建立 `network interface show` 命令。
. 確認已設定的IP位址可連線：
+
[cols="2*"]
|===
| 若要驗證... | 使用... 


 a| 
IPV4位址
 a| 
`network ping`



 a| 
IPv6位址
 a| 
`network ping6`

|===


.範例
下列命令顯示如何建立指派給的 S3 資料 LIF `my-S3-policy` 服務原則：

[listing]
----
network interface create -vserver svm1.example.com -lif lif2 -home-node node2 -homeport e0d -service-policy my-S3-policy -subnet-name ipspace1
----
下列命令顯示叢集1中的所有LIF。資料生命週期1和資料傳輸3均設定為使用IPv4位址、而資料傳輸4則設定為使用IPv6位址：

[listing]
----
cluster-1::> network interface show

            Logical    Status     Network          Current      Current Is
Vserver     Interface  Admin/Oper Address/Mask     Node         Port    Home
----------- ---------- ---------- ---------------- ------------ ------- ----
cluster-1
            cluster_mgmt up/up    192.0.2.3/24     node-1       e1a     true
node-1
            clus1        up/up    192.0.2.12/24    node-1       e0a     true
            clus2        up/up    192.0.2.13/24    node-1       e0b     true
            mgmt1        up/up    192.0.2.68/24    node-1       e1a     true
node-2
            clus1        up/up    192.0.2.14/24    node-2       e0a     true
            clus2        up/up    192.0.2.15/24    node-2       e0b     true
            mgmt1        up/up    192.0.2.69/24    node-2       e1a     true
vs1.example.com
            datalif1     up/down  192.0.2.145/30   node-1       e1c     true
vs3.example.com
            datalif3     up/up    192.0.2.146/30   node-2       e0c     true
            datalif4     up/up    2001::2/64       node-2       e0c     true
5 entries were displayed.
----