---
permalink: s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html 
sidebar: sidebar 
keywords: create, intercluster, lifs, remote fabricpool, tiering 
summary: 如果FabricPool 您使用ONTAP 支援使用支援的物件S3來啟用遠端的功能（雲端）分層、則必須設定叢集間的生命體。您可以在與資料網路共用的連接埠上設定叢集間的LIF。如此可減少叢集間網路所需的連接埠數量。 
---
= 建立叢集間的生命體、以進行遠端FabricPool 分層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果FabricPool 您使用ONTAP 支援使用支援的物件S3來啟用遠端的功能（雲端）分層、則必須設定叢集間的生命體。您可以在與資料網路共用的連接埠上設定叢集間的LIF。如此可減少叢集間網路所需的連接埠數量。

.您需要的產品
* 基礎實體或邏輯網路連接埠必須設定為管理「up」狀態。
* LIF服務原則必須已經存在。


.關於這項工作
本機Fabric集區分層或外部S3應用程式不需要叢集間生命體。

.步驟
. 列出叢集中的連接埠：
+
「網路連接埠展示」

+
以下範例顯示「cluster01」中的網路連接埠：

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. 在系統SVM上建立叢集間LIF：
+
「網路介面create -vserver cluster -lIF _LIF_name_-service-policy default-intercluster -home-node_node_-home-port _port_-address _port_ip_-netask_netapp__」

+
以下範例建立叢集間的lifs「cluster01_icl01」和「cluster01_icl02」：

+
[listing]
----

cluster01::> network interface create -vserver Cluster -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver Cluster -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. 驗證是否已建立叢集間的LIF：
+
「網路介面show -service-policy default-intercluster」

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. 驗證叢集間的LIF是否為備援：
+
「網路介面show–service-policy default-intercluster -faulty」

+
以下範例顯示、在「e0c」連接埠上的叢集間lifs「cluster01_icl01」和「cluster01_icl02」將會容錯移轉至「e0d」連接埠。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----

