---
permalink: s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html 
sidebar: sidebar 
keywords: create, intercluster, lifs, remote fabricpool, tiering 
summary: 如果FabricPool 您使用ONTAP 支援使用支援的物件S3來啟用遠端的功能（雲端）分層、則必須設定叢集間的生命體。您可以在與資料網路共用的連接埠上設定叢集間的LIF。如此可減少叢集間網路所需的連接埠數量。 
---
= 使用 ONTAP S3 建立叢集間的階層式生命體，以進行遠端 FabricPool 分層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果FabricPool 您使用ONTAP 支援使用支援的物件S3來啟用遠端的功能（雲端）分層、則必須設定叢集間的生命體。您可以在與資料網路共用的連接埠上設定叢集間的LIF。如此可減少叢集間網路所需的連接埠數量。

.開始之前
* 基礎實體或邏輯網路連接埠必須設定為管理 `up`狀態。如link:https://docs.netapp.com/us-en/ontap-cli/up.html["指令參考資料ONTAP"^]需詳細 `up`資訊，請參閱。
* LIF服務原則必須已經存在。


.關於這項工作
本機Fabric集區分層或外部S3應用程式不需要叢集間生命體。

.步驟
. 列出叢集中的連接埠：
+
`network port show`

+
下列範例顯示中的網路連接埠 `cluster01`：

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["指令參考資料ONTAP"^]需詳細 `network port show`資訊，請參閱。

. 在系統SVM上建立叢集間LIF：
+
`network interface create -vserver Cluster -lif _LIF_name_ -service-policy default-intercluster -home-node _node_ -home-port _port_ -address _port_IP_ -netmask _netmask_`

+
以下範例建立叢集間的生命體 `cluster01_icl01` 和 `cluster01_icl02`：

+
[listing]
----

cluster01::> network interface create -vserver Cluster -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver Cluster -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/network-interface-create.html["指令參考資料ONTAP"^]需詳細 `network interface create`資訊，請參閱。

. 驗證是否已建立叢集間的LIF：
+
`network interface show -service-policy default-intercluster`

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. 驗證叢集間的LIF是否為備援：
+
`network interface show -service-policy default-intercluster -failover`

+
以下範例顯示叢集間的生命體 `cluster01_icl01` 和 `cluster01_icl02` 在上 `e0c` 連接埠將容錯移轉至 `e0d` 連接埠。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster -failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["指令參考資料ONTAP"^]需詳細 `network interface show`資訊，請參閱。


