---
permalink: s3-config/create-modify-bucket-policy-task.html 
sidebar: sidebar 
keywords: modify, bucket, policy 
summary: 您可以將存取規則新增至預設的儲存區原則。其存取控制的範圍是包含貯體的範圍、因此當有單一貯體時、最適合使用此功能。 
---
= 修改庫位原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將存取規則新增至預設的儲存區原則。其存取控制的範圍是包含貯體的範圍、因此當有單一貯體時、最適合使用此功能。

已啟用S3的SVM必須已存在S3伺服器和儲存區。

您可以為新使用者和群組新增聲明、也可以修改現有聲明的屬性。如需更多選項、請參閱「vserver object-store-server Bucket policy」手冊頁。

.步驟
. 在庫位政策中加入聲明：
+
「Vserver object-store-server bucket policy add-statement -vserver Svm_name -bucket bucket_name -effect｛allow | deny｝-action object_store_actions -principiple user_and _group _name -RESERY object_store_resources[-sID text][-index integer]"

+
下列參數定義存取權限：

+
[cols="2*"]
|===


 a| 
「效果」
 a| 
此聲明可能允許或拒絕存取



 a| 
「行動」
 a| 
您可以指定「*」表示所有動作、或是下列一或多個清單：「GetObject、PuttObject、刪除物件、清單庫、GetBucketAcl、GetObjectAcl、 listBucketMultiPartUploads、和"listMultpartUploParts"。



 a| 
「校長」
 a| 
一或多個S3使用者或群組的清單。

** 最多可指定10個使用者或群組。
** 如果指定S3群組、則必須使用「群組/群組名稱」格式
** 可以將「*」指定為「公共存取」、也就是「沒有存取金鑰和秘密金鑰的存取」。
** 如果未指定主體、則SVM中的所有S3使用者都會被授予存取權。




 a| 
資源
 a| 
儲存區及其所包含的任何物件。通配字元「*」和「？」 可用於形成規則運算式、以指定資源。

|===
+
您可以選擇使用「-SID'」選項、將文字字串指定為註解。



下列範例為SVM svm1.example.com和Bucket1建立物件存放區伺服器儲存區原則聲明、指定允許存取物件存放區伺服器使用者user1的讀我資料夾。

[listing]
----
cluster1::> vserver object-store-server bucket policy statement create -vserver svm1.example.com -bucket bucket1 -effect allow -action GetObject,PutObject,DeleteObject,ListBucket -principal user1 -resource bucket1/readme/* -sid "fullAccessToReadmeForUser1"
----
下列範例會針對SVM svm1.example.com和Bucket1建立物件存放區伺服器區段原則聲明、指定允許存取物件存放區伺服器群組1的所有物件。

[listing]
----
cluster1::> vserver object-store-server bucket policy statement create -vserver svm1.example.com -bucket bucket1 -effect allow -action GetObject,PutObject,DeleteObject,ListBucket -principal group/group1 -resource bucket1/* -sid "fullAccessForGroup1"
----