---
permalink: s3-config/create-modify-bucket-policy-task.html 
sidebar: sidebar 
keywords: modify, bucket, policy 
summary: 您可以將存取規則新增至預設的儲存區原則。其存取控制的範圍是包含貯體的範圍、因此當有單一貯體時、最適合使用此功能。 
---
= 修改庫位原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將存取規則新增至預設的儲存區原則。其存取控制的範圍是包含貯體的範圍、因此當有單一貯體時、最適合使用此功能。

.開始之前
已啟用S3的SVM必須已存在S3伺服器和儲存區。

在授予權限之前、您必須先建立使用者或群組。

.關於這項工作
您可以為新使用者和群組新增聲明、也可以修改現有聲明的屬性。如需更多選項、請參閱 `vserver object-store-server bucket policy` 手冊頁。

使用者和群組權限可在建立儲存區時或稍後視需要授予。您也可以修改儲存區容量和QoS原則群組指派。

從 ONTAP 9.9.1 及更新版本開始、如果您計畫在 ONTAP S3 伺服器上支援 AWS 用戶端物件標記功能、就會執行這些動作 `GetObjectTagging`、 `PutObjectTagging`和 `DeleteObjectTagging` 需要使用貯體或群組原則來允許。

您遵循的程序取決於您使用的介面- System Manager或CLI：

[role="tabbed-block"]
====
.系統管理員
--
.步驟
. 編輯儲存桶：按一下「*儲存設備>儲存桶*」、按一下所需的儲存桶、然後按一下「*編輯*」。
新增或修改權限時、您可以指定下列參數：
+
** *主要*：授予存取權的使用者或群組。
** * effect*：允許或拒絕存取使用者或群組。
** *動作*：特定使用者或群組的儲存庫允許動作。
** *資源*：儲存區內已授予或拒絕存取的物件路徑和名稱。
+
預設值*_bucketname*和*_bucketname/*會授予儲存區中所有物件的存取權。您也可以授與單一物件的存取權、例如*_Bucketname/_* readme.txt*。

** *條件*（選用）：嘗試存取時會評估的運算式。例如、您可以指定允許或拒絕存取的IP位址清單。




--
.CLI
--
.步驟
. 在庫位政策中加入聲明：
+
`vserver object-store-server bucket policy add-statement -vserver _svm_name_ -bucket _bucket_name_ -effect {allow|deny} -action _object_store_actions_ -principal _user_and_group_names_ -resource _object_store_resources_ [-sid text] [-index integer]`

+
下列參數定義存取權限：

+
[cols="1,3"]
|===


 a| 
`-effect`
 a| 
此聲明可能允許或拒絕存取



 a| 
`-action`
 a| 
您可以指定 `*` 表示所有動作、或是下列一或多個動作清單： `GetObject, PutObject, DeleteObject, ListBucket, GetBucketAcl,GetObjectAcl, ListBucketMultipartUploads,` 和 `ListMultipartUploadParts`。



 a| 
`-principal`
 a| 
一或多個S3使用者或群組的清單。

** 最多可指定10個使用者或群組。
** 如果已指定 S3 群組、則該群組必須採用格式 `group/group_name.`
** `*` 可以指定為公開存取、也就是說、無需存取金鑰和秘密金鑰即可存取。
** 如果未指定主體、則SVM中的所有S3使用者都會被授予存取權。




 a| 
`-resource`
 a| 
儲存區及其所包含的任何物件。萬用字元 `*` 和 `?` 可用於形成用於指定資源的規則運算式。

|===
+
您可以選擇性地指定文字字串做為的註解 `-sid` 選項。



.範例
下列範例為SVM svm1.example.com和Bucket1建立物件存放區伺服器儲存區原則聲明、指定允許存取物件存放區伺服器使用者user1的讀我資料夾。

[listing]
----
cluster1::> vserver object-store-server bucket policy statement create -vserver svm1.example.com -bucket bucket1 -effect allow -action GetObject,PutObject,DeleteObject,ListBucket -principal user1 -resource bucket1/readme/* -sid "fullAccessToReadmeForUser1"
----
下列範例會針對SVM svm1.example.com和Bucket1建立物件存放區伺服器區段原則聲明、指定允許存取物件存放區伺服器群組1的所有物件。

[listing]
----
cluster1::> vserver object-store-server bucket policy statement create -vserver svm1.example.com -bucket bucket1 -effect allow -action GetObject,PutObject,DeleteObject,ListBucket -principal group/group1 -resource bucket1/* -sid "fullAccessForGroup1"
----
--
====