---
permalink: s3-config/create-bucket-task.html 
sidebar: sidebar 
keywords: s3, bucket, system manager, 
summary: S3物件保留在_buckets中-它們不會像其他目錄內的目錄內的檔案一樣嵌套。 
---
= 建立儲存庫
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
S3物件保留在_buckets中-它們不會像其他目錄內的目錄內的檔案一樣嵌套。

.開始之前
包含S3伺服器的SVM必須已經存在。

.關於這項工作
在CLI中、當您建立儲存庫時、有兩種資源配置選項：

* 讓ONTAP Select 底層的集合體和FlexGroup 元件不再存在（預設）
+
** 透過自動選取集合體、即可為第一個儲存區建立及設定一個等量磁碟區。ONTAP FlexGroup它會自動選取適用於您平台的最高服務層級、或是您可以指定儲存服務層級。您稍後在SVM中新增的任何其他儲存區、都會有相同的基礎FlexGroup 版的SVM。
** 或者、您也可以指定是否要使用儲存區進行分層、在這種情況ONTAP 下、VMware會嘗試選擇低成本的媒體、為階層式資料提供最佳效能。


* 您可以選取基礎的Aggregate和FlexGroup 等元件（需要進階權限命令選項）
+
** 您可以選擇手動選取必須FlexGroup 在其中建立貯體和包含此等Volume的集合體、然後在每個集合體上指定成員數目。新增其他庫位時：
+
*** 如果您為新的貯體指定集合體和成員、FlexGroup 將會為新的貯體建立新的功能區。
*** 如果您未指定新儲存區的集合體和成員、則新儲存區將會新增至現有FlexGroup 的版本資訊區。
請參閱 xref:../flexgroup/index.html[資料區管理FlexGroup] 以取得更多資訊。
+
當您在建立貯體時指定集合體和成員時、不會套用預設或自訂的QoS原則群組。您可以稍後使用來執行 `vserver object-store-server bucket modify` 命令。







*附註：*如果您是供應Cloud Volumes ONTAP 來自支援對象的鏟斗、則應使用CLI程序。強烈建議您手動選取基礎Aggregate、以確保它們僅使用一個節點。使用兩個節點的集合體可能會影響效能、因為節點將位於不同地理位置的可用度區域、因此容易受到延遲問題的影響。

儲存服務層級是預先定義的調適性服務品質（QoS）原則群組、具有_value_、_Performance _和_Extreme _預設層級。您也可以定義自訂QoS原則群組、並將其套用至儲存區、而非預設的儲存服務層級之一。

從ONTAP 供應儲存設備開始、預設會啟用QoS。您可以在資源配置程序期間或稍後停用QoS或選擇自訂QoS原則。

link:storage-service-definitions-reference.html["儲存服務定義"]

如果您正在設定本機容量分層、則會在資料SVM中建立儲存區和使用者、而非在S3伺服器所在的系統SVM中建立。

若要進行遠端用戶端存取、您必須在啟用S3的儲存VM中設定儲存區。如果您在未啟用S3的儲存VM中建立儲存貯體、則只能用於本機分層。

link:../performance-admin/index.html["效能管理"]

請參閱 `vserver object-store-server bucket` 手冊頁、瞭解其他組態和顯示選項。



== 建立貯體的程序

[role="tabbed-block"]
====
.系統管理員
--
. 在啟用S3的儲存VM上新增儲存區。
+
.. 按一下「*儲存設備>桶*」、然後按一下「*新增*」。
.. 輸入名稱、選取儲存VM、然後輸入大小。
+
*** 如果您此時按一下*「儲存*」、就會以下列預設設定建立儲存區：
+
**** 除非任何群組原則已經生效、否則不會授予使用者桶的存取權。
+

NOTE: 您不應該使用S3 root使用者來管理ONTAP 物件儲存設備並分享其權限、因為它對物件儲存區的存取權限不受限制。而是使用您指派的管理權限來建立使用者或群組。

**** 服務品質（效能）等級、是您系統可用的最高等級。


*** 您可以按一下*更多選項*來設定使用者權限和效能層級、或是稍後再修改這些設定。
+
**** 您必須先建立使用者和群組、才能使用*其他選項*來設定其權限。
**** 如果您打算使用S3物件存放區FabricPool 來進行分層、請考慮選擇*用於分層*（使用低成本媒體、為階層式資料提供最佳效能）、而非效能服務層級。






. 在S3用戶端應用程式（另一個ONTAP 支援系統或外部協力廠商應用程式）上、輸入下列命令來驗證新儲存庫的存取：
+
** S3伺服器CA憑證。
** 使用者的存取金鑰和秘密金鑰。
** S3伺服器FQDN名稱和儲存區名稱。




--
.CLI
--
. 如果您打算自行選取集合體和 FlexGroup 元件、請將權限等級設為進階（否則管理權限等級就足夠了）： `set -privilege advanced`
. 建立儲存庫：
+
`vserver object-store-server bucket create -vserver _svm_name_ -bucket _bucket_name_ [-size integer[KB|MB|GB|TB|PB]] [-comment text] [additional_options]`

+
SVM 名稱可以是 Data SVM 或 `Cluster` （系統 SVM 名稱）（如果您正在設定本機分層）。

+
如果您未指定任何選項、ONTAP 則會建立一個5GB的儲存區、並將服務層級設為系統可用的最高層級。

+
如果您想ONTAP 要根據效能或使用量來建立儲存庫、請使用下列其中一個選項：

+
** 服務層級
+
包括 `-storage-service-level` 具有下列其中一個值的選項： `value`、 `performance`或 `extreme`。

** 分層
+
包括 `-used-as-capacity-tier true` 選項。



+
如果您要指定要在其上建立基礎FlexGroup 的流通量的集合體、請使用下列選項：

+
** 。 `-aggr-list` 參數指定用於 FlexGroup Volume 組成的集合體清單。
+
清單中的每個項目都會在指定的Aggregate上建立一個組成項目。您可以多次指定集合體、以便在集合上建立多個成員。

+
為了在FlexGroup 整個Singfuse Volume中提供一致的效能、所有的集合體都必須使用相同的磁碟類型和RAID群組組組態。

** 。 `-aggr-list-multiplier` 參數會指定在所列的集合體上重複的次數 `-aggr-list` 建立 FlexGroup Volume 時的參數。
+
的預設值 `-aggr-list-multiplier` 參數為 4 。



. 視需要新增QoS原則群組：
+
`vserver object-store-server bucket modify -bucket _bucket_name_ -qos-policy-group _qos_policy_group_`

. 確認儲存庫建立：
+
`vserver object-store-server bucket show [-instance]`



.範例
下列範例為大小1TB的SVM VS1建立一個儲存區、並指定集合體：

[listing]
----
cluster-1::*> vserver object-store-server bucket create -vserver svm1.example.com -bucket testbucket -aggr-list aggr1 -size 1TB
----
--
====