---
permalink: s3-config/index.html 
sidebar: sidebar 
keywords: decide, s3, configuration, client, access, configure, object, bucket, svm 
summary: 從功能不只9.8開始ONTAP 、您可以在ONTAP 一個叢集中啟用一個功能不易用的儲存服務（S3）物件儲存伺服器ONTAP 。 
---
= S3組態總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9.8 開始、您可以在 ONTAP 叢集中啟用 ONTAP Simple Storage Service （ S3 ）物件儲存伺服器、使用熟悉的管理工具、例如 ONTAP System Manager 、快速配置高效能物件儲存設備、以便在 ONTAP 中進行開發與作業、並充分利用 ONTAP 的儲存效率與安全性。

ONTAP 中 S3 的主要使用案例包括：

* 使用 FabricPool 將非使用中資料分層至 ONTAP 的儲存區、以便進行 ONTAP 對 ONTAP 分層。同時支援分層至中的貯體 link:enable-ontap-s3-access-local-fabricpool-task.html["本機叢集"] 、或分層至上的貯體 link:enable-ontap-s3-access-remote-fabricpool-task.html["遠端叢集"] 。分層至 ONTAP S3 可讓您使用較便宜的 ONTAP 系統來處理非使用中資料、並節省新的 Flash 容量成本、而無需額外的 FabricPool 授權或新技術來管理。
* 從 ONTAP 9.12.1 開始、 S3 傳輸協定也可以在中啟用、而 S3 link:../s3-multiprotocol/index.html["多重傳輸協定 NAS 磁碟區"] 傳輸協定已預先設定為使用 NAS 傳輸協定。當在多重傳輸協定 NAS 磁碟區中啟用 S3 傳輸協定時、用戶端應用程式可以使用 S3 、 NFS 和 SMB 讀取和寫入資料、這會開啟多種其他使用案例。最常見的使用案例之一是 NAS 用戶端將資料寫入磁碟區和 S3 用戶端、讀取相同資料並執行分析、商業智慧、機器學習和光學字元辨識等專業工作。



NOTE: 如果您想在現有的 ONTAP 叢集上啟用 S3 功能、而不需要額外的硬體和管理功能、則 ONTAP S3 是適當的選擇。NetApp StorageGRID 是 NetApp 的物件儲存旗艦解決方案。StorageGRID 建議用於需要充分利用 S3 行動、進階 ILM 功能或 ONTAP 系統無法達到的容量的原生 S3 應用程式。如需詳細資訊，請參閱 link:https://docs.netapp.com/us-en/storagegrid-118/index.html["本文檔StorageGRID"^]。



== S3組態搭配System Manager和ONTAP Stri CLI

您可以使用ONTAP System Manager和ONTAP SURE CLI來設定及管理SS3。當您使用System Manager啟用S3並建立貯體時、ONTAP 會選擇最佳實務預設值以簡化組態。如果您需要指定組態參數、可能需要使用ONTAP CLI。  如果您從CLI設定S3伺服器和儲存區、仍可視需要使用System Manager進行管理、反之亦然。

當您使用System Manager建立S3儲存區時ONTAP 、即可設定系統可用的最高預設效能服務層級。例如AFF 、在某個不完善的系統上、預設設定為*極致*。效能服務層級是預先定義的可調整服務品質（QoS）原則群組。您可以指定自訂QoS原則群組或無原則群組、而非其中一個預設服務層級。

預先定義的調適性QoS原則群組包括：

* *極致*：適用於預期最低延遲和最高效能的應用程式。
* *效能*：適用於效能需求與延遲不佳的應用程式。
* *值*：用於處理量與容量比延遲更重要的應用程式。
* *自訂*：指定自訂QoS原則或無QoS原則。


如果您選擇*用於分層*、則不會選擇效能服務層級、系統會嘗試選擇低成本媒體、並針對階層式資料提供最佳效能。

另請參閱： link:../performance-admin/adaptive-qos-policy-groups-task.html["使用調適性QoS原則群組"]。

嘗試將此儲存庫配置到具有最適當磁碟的本機層、以符合所選的服務層級。ONTAP不過、如果您需要指定要包含在儲存區中的磁碟、請考慮從CLI設定S3物件儲存、方法是指定本機層（Aggregate）。如果您從CLI設定S3伺服器、仍可視需要使用System Manager來管理。

如果您想要指定要用於儲存區的集合體、只能使用CLI來執行此作業。



== 在SS3上設定S3鏟斗Cloud Volumes ONTAP

如果您想要供應Cloud Volumes ONTAP 來自整個部門的庫存箱、強烈建議您手動選取基礎集合體、以確保它們僅使用一個節點。使用兩個節點的集合體可能會影響效能、因為節點將位於不同地理位置的可用度區域、因此容易受到延遲問題的影響。因此Cloud Volumes ONTAP 、在不完善的環境中、您應該 xref:create-bucket-task.html[從CLI設定S3儲存區]。

否則Cloud Volumes ONTAP 、在內部Cloud Volumes ONTAP 部署環境中、將以相同的方式設定和維護位於內部部署環境中的S3伺服器。
