---
permalink: s3-config/ontap-version-support-s3-concept.html 
sidebar: sidebar 
keywords: tr-4814, ontap, version, support, s3, object, storage, AWS S3, Azure S3, cloud volumes ontap, aws, azure 
summary: 支援S3物件儲存、適用於從NetApp 9.8開始的內部部署環境。ONTAP ONTAP支援S3物件式儲存、適用於以支援從Se.9.9.1開始的雲端環境。Cloud Volumes ONTAP ONTAP 
---
= 支援 S3 物件儲存的 ONTAP 版本與平台
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
所有使用 ONTAP 9.8 及更新版本的 AFF 、 FAS 及 ONTAP Select 平台均支援 S3 物件儲存。

如同 FC 、 iSCSI 、 NFS 、 NVMe 、 SMB 等其他通訊協定、 S3 需要先安裝授權、才能在 ONTAP 中使用。S3 授權為零成本授權、但必須安裝在升級至 ONTAP 9.8 的系統上。S3 授權可從 NetApp 支援網站上的下載 link:https://mysupport.netapp.com/site/systems/master-license-keys/ontaps3["主要授權金鑰頁面"^] 。

新的 ONTAP 9.8 及更新版本系統已預先安裝 S3 授權。



== Cloud Volumes ONTAP

除了以下一項之外、在不支援內部部署環境的情況下、將支援的功能與在不支援內部部署環境中相同：ONTAP Cloud Volumes ONTAP

* 在 Cloud Volumes ONTAP 中建立貯體時、應使用 CLI 程序、確保基礎 FlexGroup Volume 僅使用單一節點的集合體。使用來自多個節點的集合體會影響效能、因為節點將位於地理上分離的可用區域、容易發生延遲問題。


|===
| 雲端供應商 | 版本ONTAP 


| Azure | 更新版本ONTAP 


| AWS | 更新版本ONTAP 


| Google Cloud | 更新版本ONTAP 
|===


== Amazon FSX for NetApp ONTAP 產品

使用 ONTAP 9.11 及更新版本的 Amazon FSX for NetApp 服務支援 S3 物件儲存。



== S3 支援 MetroCluster

從 ONTAP 9.14.1 開始、您可以在 MetroCluster IP 和 FC 組態的鏡射集合中、在 SVM 上啟用 S3 物件儲存伺服器。

從ONTAP 《S209.12.1.版」開始、您可以在SVM上啟用S3物件儲存伺服器、並以MetroCluster 無鏡射的Aggregate進行支援、以利執行不鏡射的IP組態。如需 MetroCluster IP 組態中未鏡射集合體限制的詳細資訊，請參閱 link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/considerations_unmirrored_aggrs.html["無鏡射Aggregate的考量"^]。



== S3公有預覽ONTAP 、以供使用。9.7

在S129.7中ONTAP 、S3物件儲存設備是以公開預覽形式推出。該版本不適用於正式作業環境、也不再更新ONTAP 至版本號只有更新版本的支援功能才支援正式作業環境中的S3物件儲存。ONTAP

使用9.7公用預覽建立的S3儲存桶可在ONTAP 更新版本的支援中使用、但無法利用功能增強功能。如果您有使用9.7公用預覽建立的儲存區、則應將這些儲存區的內容移轉至9.8個儲存區、以增強功能支援、安全性及效能。
