---
permalink: snaplock/create-audit-log-task.html 
sidebar: sidebar 
keywords: create, audit, log, snaplock, protected, administrator, accounts 
summary: 您必須先建立受SnapLock保護的稽核記錄、才能執行特殊權限刪除或SnapLock 取消Volume移動。稽核日誌會記錄SnapLock 建立和刪除不支援的管理員帳戶、修改記錄磁碟區、是否啟用特殊權限刪除、特殊權限刪除作業、SnapLock 以及執行不需執行任何資料的Volume搬移作業。 
---
= 在 ONTAP 中建立稽核記錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您使用的是 ONTAP 9.9.1 或更早版本、則必須先建立 SnapLock Aggregate 、然後建立受 SnapLock 保護的稽核記錄、才能執行特殊權限刪除或 SnapLock Volume 搬移。稽核日誌會記錄SnapLock 建立和刪除不支援的管理員帳戶、修改記錄磁碟區、是否啟用特殊權限刪除、特殊權限刪除作業、SnapLock 以及執行不需執行任何資料的Volume搬移作業。

從 ONTAP 9.10.1 開始、您不再建立 SnapLock Aggregate 。您必須link:../snaplock/create-snaplock-volume-task.html["明確建立 SnapLock Volume"]將 Compliance 或 Enterprise 指定為 SnapLock 類型、以使用 SnapLock 類型選項。

.開始之前
如果您使用的是 ONTAP 9.9.1 或更早版本、則必須是叢集管理員才能建立 SnapLock Aggregate 。

.關於這項工作
在記錄檔保留期間結束之前、您無法刪除稽核記錄。即使保留期間已過、您也無法修改稽核記錄。這適用於SnapLock 「不符合需求」和「企業」模式。

[NOTE]
====
在更新版本的版本中、您無法使用無法稽核記錄的「功能不全企業版」磁碟區。ONTAP SnapLock您必須使用SnapLock 「不符合需求」量。在更新版本的版本中、您可以使用「更新版本」或「更新版本」來記錄稽核記錄。ONTAP SnapLock SnapLock在所有情況下、稽核記錄磁碟區都必須掛載在連接路徑上 `/snaplock_audit_log`。沒有其他磁碟區可以使用此交會路徑。

====
您可以在中找到 SnapLock 稽核記錄 `/snaplock_log` 位於稽核記錄磁碟區根目錄下的目錄、位於名為的子目錄中 `privdel_log` （特權刪除作業）和 `system_log` （其他一切）。稽核記錄檔名稱包含第一次記錄作業的時間戳記、可讓您在執行作業的大約時間內輕鬆搜尋記錄。

* 您可以使用 `snaplock log file show` 命令以檢視稽核記錄磁碟區上的記錄檔。
* 您可以使用 `snaplock log file archive` 命令將目前的記錄檔歸檔並建立新的記錄檔、這在您需要將稽核記錄檔資訊記錄在個別檔案中時非常有用。


深入瞭解 `snaplock log file show`及 `snaplock log file archive` link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=snaplock+log+file["指令參考資料ONTAP"^]。

[NOTE]
====
資料保護磁碟區無法用作SnapLock 不完善的稽核記錄磁碟區。

====
.步驟
. 建立SnapLock 一個不只一個的集合體。
+
xref:create-snaplock-aggregate-task.adoc[建立SnapLock 一個不只一個的集合體]

. 在您要設定稽核記錄的SVM上、建立SnapLock 一個SVM Volume。
+
xref:create-snaplock-volume-task.adoc[建立SnapLock 一個流通量]

. 設定SVM進行稽核記錄：
+
`snaplock log create -vserver _SVM_name_ -volume _snaplock_volume_name_ -max-log-size _size_ -retention-period _default_retention_period_`

+
[NOTE]
====
稽核記錄檔的最短預設保留期間為六個月。如果受影響檔案的保留期間比稽核記錄的保留期間長、則記錄的保留期間會繼承檔案的保留期間。因此、如果使用特殊權限刪除刪除的檔案保留期間為10個月、而稽核記錄的保留期間為8個月、則記錄的保留期間將延長至10個月。如需保留時間與預設保留期間的詳細資訊，請參閱link:../snaplock/set-retention-period-task.html["設定保留時間"]。

====
+
下列命令可進行設定 `SVM1` 用於使用 SnapLock Volume 進行稽核記錄 `logVol`。稽核日誌的最大大小為20 GB、保留8個月。

+
[listing]
----
SVM1::> snaplock log create -vserver SVM1 -volume logVol -max-log-size 20GB -retention-period 8months
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snaplock-log-create.html["指令參考資料ONTAP"^]需詳細 `snaplock log create`資訊，請參閱。

. 在您設定用於稽核記錄的 SVM 上、將 SnapLock 磁碟區掛載到連接路徑 `/snaplock_audit_log`。
+
xref:mount-snaplock-volume-task.adoc[掛載SnapLock 一個流通量]


