---
permalink: snaplock/create-audit-log-task.html 
sidebar: sidebar 
keywords: create, audit, log, snaplock, protected, administrator, accounts 
summary: 您必須先建立受SnapLock保護的稽核記錄、才能執行特殊權限刪除或SnapLock 取消Volume移動。稽核日誌會記錄SnapLock 建立和刪除不支援的管理員帳戶、修改記錄磁碟區、是否啟用特殊權限刪除、特殊權限刪除作業、SnapLock 以及執行不需執行任何資料的Volume搬移作業。 
---
= 建立稽核記錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須先建立受SnapLock保護的稽核記錄、才能執行特殊權限刪除或SnapLock 取消Volume移動。稽核日誌會記錄SnapLock 建立和刪除不支援的管理員帳戶、修改記錄磁碟區、是否啟用特殊權限刪除、特殊權限刪除作業、SnapLock 以及執行不需執行任何資料的Volume搬移作業。

您必須是叢集管理員、才能建立SnapLock 一個不實的Aggregate。

在記錄檔保留期間結束之前、您無法刪除稽核記錄。即使保留期間已過、您也無法修改稽核記錄。這適用於SnapLock 「不符合需求」和「企業」模式。

[NOTE]
====
在更新版本的版本中、您無法使用無法稽核記錄的「功能不全企業版」磁碟區。ONTAP SnapLock您必須使用SnapLock 「不符合需求」量。在更新版本的版本中、您可以使用「更新版本」或「更新版本」來記錄稽核記錄。ONTAP SnapLock SnapLock在所有情況下、稽核記錄磁碟區都必須掛載於交會路徑「/SnapLock稽核日誌」。沒有其他磁碟區可以使用此交會路徑。

====
您可以在SnapLock 稽核記錄磁碟區根目錄下的「/SnapLock」目錄中、找到名為「privdel_log」（特殊權限刪除作業）和「system_log」（其他一切）的子目錄中的「/selock」稽核記錄。稽核記錄檔名稱包含第一次記錄作業的時間戳記、可讓您在執行作業的大約時間內輕鬆搜尋記錄。

* 您可以使用「SnapLock flexflog file show」命令來檢視稽核記錄磁碟區上的記錄檔。
* 您可以使用「SnapLock flexflog file archive」命令來歸檔目前的記錄檔、並建立新的記錄檔、這在需要將稽核記錄資訊記錄在個別檔案中的情況下非常有用。


如需詳細資訊、請參閱命令的手冊頁。

[NOTE]
====
資料保護磁碟區無法用作SnapLock 不完善的稽核記錄磁碟區。

====
.步驟
. 建立SnapLock 一個不只一個的集合體。
+
xref:create-snaplock-aggregate-task.adoc[建立SnapLock 一個不只一個的集合體]

. 在您要設定稽核記錄的SVM上、建立SnapLock 一個SVM Volume。
+
xref:create-snaplock-volume-task.adoc[建立SnapLock 一個流通量]

. 設定SVM進行稽核記錄：
+
hy* SnapLock flexlog create -vserver _svm_name_-volume _SnapLock Volume名稱_-max-file-size _size_-retion-period _default_retent_p段_*

+
[NOTE]
====
稽核記錄檔的最短預設保留期間為六個月。如果受影響檔案的保留期間比稽核記錄的保留期間長、則記錄的保留期間會繼承檔案的保留期間。因此、如果使用特殊權限刪除刪除的檔案保留期間為10個月、而稽核記錄的保留期間為8個月、則記錄的保留期間將延長至10個月。

====
+
下列命令會設定「VM1」、以供使用SnapLock VMware Volume「logvol」進行稽核記錄。稽核日誌的最大大小為20 GB、保留8個月。

+
[listing]
----
SVM1::> snaplock log create -vserver SVM1 -volume logVol -max-file-size 20GB -retention-period 8months
----
. 在您設定用於稽核記錄的SVM上、將SnapLock 該SVM掛載到交會路徑「/SnapLock稽核日誌」。
+
xref:mount-snaplock-volume-task.adoc[掛載SnapLock 一個流通量]


