---
permalink: snaplock/event-based-retention-feature-task.html 
sidebar: sidebar 
keywords: event, based, retention, ebr, feature, snaplock, file, snap lock, worm 
summary: 從ONTAP 使用支援功能《支援功能》的《支援功能SnapLock 》（ETR__）開始、您可以定義事件發生後、檔案保留的時間長度。 
---
= 設定事件發生後的檔案保留期間
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP 使用支援功能《支援功能》的《支援功能SnapLock 》（ETR__）開始、您可以定義事件發生後、檔案保留的時間長度。

.您需要的產品
* 您必須SnapLock 是管理員才能執行此工作。
+
link:create-compliance-administrator-account-task.html["建立SnapLock 一個管理員帳戶"]

* 您必須登入安全連線（SSH、主控台或ZAPI）。


.關於這項工作
事件保留原則_定義事件發生後的檔案保留期間。原則可套用至單一檔案或目錄中的所有檔案。

* 如果檔案不是WORM檔案、則會在原則中定義的保留期間內、將其提交至WORM狀態。
* 如果檔案是WORM檔案或WORM可應用檔案、其保留期間將會延長至原則中定義的保留期間。


您可以使用法規遵循模式或企業模式磁碟區。

[NOTE]
====
EBR原則無法套用至合法持有的檔案。

====
如需進階使用方式、請參閱 link:https://www.netapp.com/us/media/tr-4526.pdf["符合法規的WORM儲存設備、採用NetApp SnapLock 技術"]。

|===


| *使用EBR延長現有WORM檔案的保留期間* 


 a| 
當您想要延長現有WORM檔案的保留期間時、EBR非常方便。例如、貴公司的政策可能是在員工變更扣繳選項後、保留未修改的員工W-4記錄三年。另一項公司政策可能要求在員工離職後保留W-4記錄五年。

在此情況下、您可以建立保留五年的EBR原則。員工終止聘僱（「事件」）後、您會將EBR原則套用至員工的W-4記錄、延長其保留期間。這通常比手動延長保留期間更容易、尤其是涉及大量檔案時。

|===
.步驟
. 建立EBR原則：
+
「SnapLock *」指事件保留原則create -vserver _Svm_name_-name _policy_name_-retion-period _retenture_p段_*

+
下列命令會在「VS1（VS1）上建立EBR原則「eneter_exit"、保留期為十年：

+
[listing]
----
cluster1::>snaplock event-retention policy create -vserver vs1 -name employee_exit -retention-period 10years
----
. 套用EBR原則：
+
hy* SnapLock 可套用事件保留功能-vserver _Svm_name_-name _policy_name_-volume _volume _name_-path _path_name_*

+
下列命令會將「VS1」上的EBR原則「ENBER_EXIT」套用至目錄「d1」中的所有檔案：

+
[listing]
----
cluster1::>snaplock event-retention apply -vserver vs1 -name employee_exit -volume vol1 -path /d1
----

