---
permalink: snaplock/initialize-complianceclock-task.html 
sidebar: sidebar 
keywords: snaplock, complianceclock, compliance clock, initialize, worm, retention, period, node, ntp, reset, resynchronize 
summary: SnapLock ComplianceClock 可以防止篡改，從而避免更改 WORM 檔案的保留期限。您必須在每個託管 SnapLock Aggregate 的節點上初始化系統 Compliance Clock 。 
---
= 初始化ONTAP合規性時鐘
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapLock 使用 _Volume Compliance Clock_ 來防止竄改、以免改變 WORM 檔案的保留期。您必須先在裝載 SnapLock Aggregate 的每個節點上初始化 _ 系統整合時鐘 _ 。

從 ONTAP 9.14.1 開始，當系統中沒有 SnapLock 磁碟區或沒有啟用快照鎖定的磁碟區時，您可以初始化或重新初始化系統合規時脈。重新初始化功能使系統管理員能夠在系統合規時脈初始化錯誤或出現時脈漂移時重置它。在 ONTAP 9.13.1 及更早版本中，節點上的合規時脈初始化後，無法再次初始化。

.開始之前
若要重新初始化法規遵循時鐘：

* 叢集中的所有節點都必須處於健全狀態。
* 所有磁碟區都必須處於線上狀態。
* 恢復佇列中不能有任何磁碟區。
* 無法存在 SnapLock 磁碟區。
* 沒有啟用快照鎖定的磁碟區。


初始化法規遵循時鐘的一般需求：

* 您必須是叢集管理員才能執行此工作。
* link:../system-admin/install-license-task.html["SnapLock 授權必須安裝在節點上"]。


.關於這項工作
系統相容時鐘的時間由 _Volume Compliance Clock_ 繼承、後者控制磁碟區上 WORM 檔案的保留時間。當您建立新的 SnapLock Volume 時、 Volume Compliance 時鐘會自動初始化。

[NOTE]
====
系統 Compliance Clock 的初始設定是基於目前的硬體系統時鐘。因此，在每個節點上初始化系統 Compliance Clock 之前，您應該驗證系統時間和時區是否正確。在節點上初始化系統 Compliance Clock 後，當存在 SnapLock 磁碟區或啟用鎖定的磁碟區時，您無法再次初始化。

====
.步驟
您可以使用 ONTAP CLI 初始化法規遵循時鐘、或從 ONTAP 9.12.1 開始、使用系統管理員來初始化法規遵循時鐘。

[role="tabbed-block"]
====
.系統管理員
--
. 瀏覽至*叢集>總覽*。
. 在 *Nodes* 部分中，選取 *Initialize SnapLock Compliance Clock* 。
. 若要顯示 *Compliance Clock* 欄並驗證 Compliance Clock 是否已初始化，請在 *叢集 > 概覽 > 節點* 部分中選擇 *顯示 / 隱藏*，然後選擇 *SnapLock Compliance Clock*。


--
--
.CLI
. 初始化系統相容時鐘：
+
`snaplock compliance-clock initialize -node _node_name_`

+
下列命令會初始化系統的 Compliance Clock On `node1`：

+
[listing]
----
cluster1::> snaplock compliance-clock initialize -node node1
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-initialize.html["指令參考資料ONTAP"^]需詳細 `snaplock compliance-clock initialize`資訊，請參閱。

. 出現提示時、請確認系統時鐘正確、且您想要初始化 Compliance Clock:
+
[listing]
----
Warning: You are about to initialize the secure ComplianceClock of
the node "node1" to the current value of the node's system clock.
This procedure can be performed only once on a given node, so you
should ensure that the system time is set correctly before proceeding.

The current node's system clock is: Mon Apr 25 06:04:10 GMT 2016

Do you want to continue? (y|n): y
----
. 針對裝載SnapLock 一個Eregate的每個節點、重複此程序。


--
====


== 啟用 NTP 組態系統的法規遵循時鐘重新同步

設定 NTP 伺服器後，您可以啟用SnapLock Compliance時脈同步功能。

.開始之前
* 此功能僅適用於進階權限層級。
* 您必須是叢集管理員才能執行此工作。
* link:../system-admin/install-license-task.html["SnapLock 授權必須安裝在節點上"]。
* 此功能僅適用於Cloud Volumes ONTAP Sf/、ONTAP Select Sf/及VSim平台。


.關於這項工作
當 SnapLock 安全時鐘守護程式偵測到超出閾值的時間偏差時、ONTAP 會使用系統時間重置系統時鐘和磁碟區 Compliance Clock。偏差閾值設定為 24 小時。只有當偏差超過一天時、系統 Compliance Clock 才會與系統時鐘同步。

SnapLock 安全時鐘精靈會偵測到偏差、並將法規遵循時鐘變更為系統時間。任何嘗試修改系統時間以強制法規遵循時鐘與系統時間同步的作業都會失敗、因為法規遵循時鐘只有在系統時間與 NTP 時間同步時、才會與系統時間同步。

.步驟
. 配置 NTP 伺服器時啟用SnapLock Compliance時脈同步功能：
+
`snaplock compliance-clock ntp`

+
以下命令啟用系統合規時鐘同步功能：

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp modify -is-sync-enabled true
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-ntp-modify.html["指令參考資料ONTAP"^]需詳細 `snaplock compliance-clock ntp modify`資訊，請參閱。

. 出現提示時、請確認已設定的NTP伺服器是受信任的、而且通訊通道是安全的、以啟用此功能：
. 檢查功能是否已啟用：
+
`snaplock compliance-clock ntp show`

+
以下指令檢查系統合規時鐘同步功能是否啟用：

+
[listing]
----
cluster1::*> snaplock compliance-clock ntp show

Enable clock sync to NTP system time: true
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snaplock-compliance-clock-ntp-show.html["指令參考資料ONTAP"^]需詳細 `snaplock compliance-clock ntp show`資訊，請參閱。


