---
permalink: snaplock/set-default-retention-period-task.html 
sidebar: sidebar 
keywords: snaplock, volume, command, modify, retention, period, file, set, default 
summary: 您可以使用volume SnapLock flexmodify命令、為SnapLock 位於現象區的檔案設定預設保留期間。 
---
= 設定預設保留期間
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「volume SnapLock flexmodify」命令、為SnapLock 位於某個現象區的檔案設定預設保留期間。

此版本必須在線上。SnapLock

下表顯示預設保留期間選項的可能值：

[NOTE]
====
預設保留期間必須大於或等於（>=）最短保留期間、且小於或等於（\<=）最長保留期間。

====
|===
| 價值 | 單位 | 附註 


 a| 
0 - 65535
 a| 
秒
 a| 



 a| 
0 - 24
 a| 
時數
 a| 



 a| 
0 - 365
 a| 
天
 a| 



 a| 
0 - 12
 a| 
數月
 a| 



 a| 
0 - 70
 a| 
年
 a| 



 a| 
最大
 a| 
-
 a| 
使用最長保留期間。



 a| 
最小
 a| 
-
 a| 
使用最短保留期間。



 a| 
無限
 a| 
-
 a| 
永遠保留檔案。



 a| 
未指定
 a| 
-
 a| 
保留檔案、直到設定絕對保留期間為止。

|===
最大和最小保留期間的值和範圍相同、但不適用的「max」和「min」除外。如需此工作的詳細資訊、請參閱 link:set-retention-period-task.html["設定保留時間總覽"]。

您可以使用「volume SnapLock flexshow」命令來檢視Volume的保留期間設定。如需詳細資訊、請參閱命令的手冊頁。

[NOTE]
====
將檔案提交至WORM狀態之後、您可以延長但不能縮短保留期間。

====
.步驟
. 設定SnapLock 適用於現象區上檔案的預設保留期間：
+
「* Volume SnapLock fidmodify -vserver _Svm_name_-volume _volume _name_-default-retention-period _default_retenture_p段_-min-retention_period _min_retent_p段_-max-retent_p段_*」

+
如需選項的完整清單、請參閱命令的手冊頁。

+
[NOTE]
====
下列範例假設先前尚未修改最小和最大保留期間。

====
+
下列命令會將規範或企業Volume的預設保留期間設為20天：

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period 20days
----
+
下列命令會將Compliance Volume的預設保留期間設為70年：

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -maximum-retention-period 70years
----
+
下列命令會將Enterprise Volume的預設保留期間設為10年：

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period max -maximum-retention-period 10years
----
+
下列命令會將Enterprise Volume的預設保留期間設為10天：

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -minimum-retention-period 10days
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period min
----
+
下列命令會將Compliance Volume的預設保留期間設為無限：

+
[listing]
----
cluster1::> volume snaplock modify -vserver vs1 -volume vol1 -default-retention-period infinite -maximum-retention-period infinite
----

