---
permalink: snaplock/snapshot-lock-concept.html 
sidebar: sidebar 
keywords: snaplock, snapshot copy, lock, tamperproof 
summary: 從VMware 9.12.1開始ONTAP 、您可以在非SnapLock Volume上鎖定Snapshot複本、以防止勒索軟體攻擊。鎖定Snapshot複本可確保它們不會意外或惡意刪除。 
---
= 鎖定Snapshot複本以防止勒索軟體攻擊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從VMware 9.12.1開始ONTAP 、您可以在非SnapLock Volume上鎖定Snapshot複本、以防止勒索軟體攻擊。鎖定Snapshot複本可確保不會意外或惡意刪除。

您可以使用SnapLock 「不符法規時鐘」功能、將Snapshot複本鎖定一段特定期間、以便在達到到期時間之前將其刪除。鎖定Snapshot複本可防止資料竄改、避免受到勒索軟體威脅。如果磁碟區受到勒索軟體攻擊、您可以使用鎖定的Snapshot複本來恢復資料。

.防竄改Snapshot複本要求與考量
* 叢集中的所有節點都必須執行ONTAP 不完整的9.12.1或更新版本。
* 必須在叢集上安裝此功能的不必要授權。SnapLock
+
如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/ontap/snaplock/install-license-task.html["安裝SnapLock 不含更新授權的"]。

* 叢集上的法規遵循時鐘必須初始化。
+
如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/ontap/snaplock/initialize-complianceclock-task.html["初始化法規遵循時鐘"]。

* 在磁碟區上啟用Snapshot鎖定功能時、您可以將叢集升級至ONTAP 更新於ONTAP 版本更新至版本更新於版本更新至版本更新的版本。 不過ONTAP 、在所有鎖定的Snapshot複本都達到到期日並刪除、且Snapshot複本鎖定功能已停用之前、您無法還原至舊版的功能。
* 鎖定Snapshot時、磁碟區過期時間會設定為Snapshot複本的過期時間。如果鎖定多個Snapshot複本、則磁碟區過期時間會反映所有Snapshot複本中最長的過期時間。
* 鎖定Snapshot複本的保留期間優先於Snapshot複本保留數、也就是說、如果鎖定Snapshot複本的Snapshot複本保留期間尚未過期、則不會保留保留保留數限制。
* 在SnapMirror關係中、您可以在鏡射儲存庫原則規則上設定保留期間、如果目的地磁碟區已啟用Snapshot複本鎖定功能、則保留期間會套用至複寫至目的地的Snapshot複本。保留期間優先於保留數；例如、即使超過保留數、仍會保留未超過到期日的Snapshot複本。
* 您可以在非SnapLock Volume上重新命名Snapshot複本。僅當原則為MirrorAllSnapshots時、SnapMirror關係的主要磁碟區上的Snapshot重新命名作業才會反映在次要磁碟區上。對於其他原則類型、重新命名的Snapshot複本不會在更新期間傳播。
* 您可以使用還原鎖定的Snapshot複本 `volume snapshot restore` 僅當鎖定的Snapshot複本是最新的時、才會執行命令。如果有任何未過期的Snapshot複本比要還原的複本晚、則Snapshot複本還原作業將會失敗。


.防竄改Snapshot複本支援的功能
* 資料量FlexGroup
+
支援將Snapshot複本鎖定在FlexGroup 不支援的情況下。Snapshot鎖定僅發生在根組成Snapshot複本上。只有在根組成的到期時間已過時、才FlexGroup 允許刪除此功能。

* 從系統轉換為FlexVol FlexGroup
+
您可以使用FlexVol 鎖定的Snapshot複本、將某個不符合需求的Volume轉換成FlexGroup 一個不符合需求的Volume。轉換後、Snapshot複本仍會保持鎖定狀態。

* FabricPool
+
唯有當磁碟區沒有任何階層區塊分層至雲端、而且分層原則設定為「無」時、才能在FabricPool 支援Snapshot Volume上支援Snapshot複製鎖定。啟用Snapshot複本鎖定功能時、不允許將磁碟區上的分層原則設定為「無」以外的原則。

* Volume複製與檔案複製
+
您可以從鎖定的Snapshot複本建立Volume複本和檔案複本。



.不支援的功能
下列功能目前不支援防竄改Snapshot複本：

* 一致性群組
* 資料量FlexCache
* SMtape
* SnapCenter
* SnapMirror營運不中斷（SMBC）
* SnapMirror同步




== 建立磁碟區時啟用Snapshot複本鎖定

從ONTAP 《支援資料9.12.1：建立新磁碟區或使用修改現有磁碟區時、您可以啟用Snapshot複本鎖定功能 `-snapshot-locking-enabled` 選項 `volume create` 和 `volume modify` 命令。

. 若要建立新磁碟區並啟用Snapshot複本鎖定、請輸入下列命令：
+
`volume create -vserver _vserver_name_ -volume _volume_name_ -snapshot-locking-enabled true`

+
下列命令可在名為vol1的新磁碟區上啟用Snapshot複本鎖定：

+
[listing]
----
> volume create -volume vol1 -aggregate aggr1 -size 100m -snapshot-locking-enabled true
Warning: Snapshot copy locking is being enabled on volume “vol1” in Vserver “vs1”. It cannot be disabled until all locked Snapshot copies are past their expiry time. A volume with unexpired locked Snapshot copies cannot be deleted.
Do you want to continue: {yes|no}: y
[Job 32] Job succeeded: Successful
----




== 在現有磁碟區上啟用Snapshot複本鎖定

. 若要修改現有磁碟區以啟用Snapshot複本鎖定、請輸入下列命令：
+
`volume modify -vserver _vserver_name_ -volume _volume_name_ -snapshot-locking-enabled true`





== 建立鎖定的Snapshot複本

從ONTAP 功能表9.12開始、您可以建立Snapshot複本原則、以套用Snapshot複本保留期間、並將原則套用至磁碟區、以便在指定期間鎖定Snapshot複本。您也可以手動設定保留期間、以鎖定Snapshot複本。

.建立Snapshot複本鎖定原則
. 若要建立Snapshot複本原則、請輸入下列命令：
+
`volume snapshot policy create -policy policy_name -enabled true -schedule1 _schedule1_name_ -count1 _maximum_Snapshot_copies -retention-period1 _retention_period_`

+
下列命令會建立Snapshot複本鎖定原則：

+
[listing]
----
cluster1> volume snapshot policy create -policy policy_name -enabled true -schedule1 5min -count1 5 -retention-period1 "1 months"
----


.將鎖定原則套用至磁碟區
. 若要將Snapshot複本鎖定原則套用至現有磁碟區、請輸入下列命令：
+
`volume modify -volume volume_name -vserver vserver_name -snapshot-policy policy_name`



.在手動建立Snapshot複本期間套用保留期間
. 若要手動建立Snapshot複本並套用鎖定保留期間、請輸入下列命令：
+
`volume snapshot create -volume _volume_name_ -snapshot _snapshot_copy_name_ -snaplock-expiry-time _expiration_date_time_`

+
下列命令會建立新的Snapshot複本並設定保留期間：

+
[listing]
----
cluster1> volume snapshot create -vserver vs1 -volume vol1 -snapshot snap1 -snaplock-expiry-time "11/10/2022 09:00:00"
----


.將保留期間套用至現有的Snapshot複本
. 若要手動將保留期間套用至現有的Snapshot複本、請輸入下列命令：
+
`volume snapshot modify-snaplock-expiry-time -volume _volume_name_ -snapshot _snapshot_copy_name_ -expiry-time _expiration_date_time_`

+
以下範例將保留期間套用至現有的Snapshot複本：

+
[listing]
----
cluster1> volume snapshot modify-snaplock-expiry-time -volume vol1 -snapshot snap2 -expiry-time "11/10/2022 09:00:00"
----

