---
permalink: snaplock/snaplock-concept.html 
sidebar: sidebar 
keywords: snaplock, worm, storage, compliance, enterprise, mode, sec, rule, 17a, license 
summary: 對於使用WORM儲存設備、以未經修改的形式保留檔案以供法規遵循和治理之用的組織而言、VMware是高效能的法規遵循解決方案。SnapLock單一授權可讓您SnapLock 在嚴格法規遵循模式下使用SESS庫、以符合SEC Rule 17a-4及較寬鬆的企業模式等外部規定、以符合內部規定的數位資產保護法規。 
---
= 什麼是呢SnapLock
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
對於使用WORM儲存設備、以未經修改的形式保留檔案以供法規遵循和治理之用的組織而言、VMware是高效能的法規遵循解決方案。SnapLock單一授權可讓您SnapLock 在嚴格的法規遵循模式下使用功能、以滿足SEC Rule 17a-4和較為寬鬆的企業模式等外部規定、以符合內部規定的數位資產保護法規。



== 法規遵循與企業模式之間的差異

不一致性與企業模式的差異主要在於每種模式保護WORM檔案的層級：SnapLock

* 法規遵循模式WORM檔案在磁碟層級受到保護。
+
您無法重新初始化包含Compliance模式Aggregate的磁碟。

* 企業模式WORM檔案在檔案層級受到保護。


相關的差異包括每種模式如何嚴格管理檔案刪除：

* 在保留期間內、無法刪除法規遵循模式WORM檔案。
* 企業模式WORM檔案可在保留期間由法規遵循管理員使用稽核的_權限刪除_程序刪除。


保留期間結束後、您必須負責刪除不再需要的任何檔案。一旦檔案已提交至WORM（無論是在「法規遵循」或「企業」模式下）、即使保留期間已過期、也無法加以修改。

您無法在保留期間內或之後移動WORM檔案。您可以複製WORM檔案、但複本不會保留WORM特性。

下表顯示SnapLock 「不一致性」與「企業」模式之間的差異：

|===


| 能力 | 符合法規SnapLock | 企業版SnapLock 


 a| 
特殊權限刪除
 a| 
否
 a| 
是的



 a| 
重新初始化磁碟
 a| 
否
 a| 
是的



 a| 
在SnapLock 保留期間摧毀整個過程
 a| 
否
 a| 
是、SnapLock 除了不包括不含資訊的稽核記錄磁碟區



 a| 
重新命名Aggregate或Volume
 a| 
否
 a| 
是的



 a| 
非NetApp磁碟
 a| 
否
 a| 
是（FlexArray 採用「虛擬化」技術）



 a| 
使用此功能來記錄稽核記錄SnapLock
 a| 
是的
 a| 
是的、從ONTAP SES9.5開始

|===


== 支援且不支援SnapLock 的功能

下表顯示SnapLock 支援的功能、包括「不符合需求」模式SnapLock 、「不符合需求」模式或「不符合需求」模式、或兩者：

|===


| 功能 | 支援SnapLock 不受支援的功能 | 支援SnapLock 支援不受支援的企業 


 a| 
一致性群組
 a| 
否
 a| 
否



 a| 
SAN
 a| 
否
 a| 
否



 a| 
SnapMirror同步
 a| 
否
 a| 
否



 a| 
SnapMirror營運不中斷
 a| 
否
 a| 
否



 a| 
單一檔案SnapRestore 的功能
 a| 
否
 a| 
是的



 a| 
SnapRestore
 a| 
否
 a| 
是的



 a| 
FlexClone
 a| 
您可以複製SnapLock 不全的資料、但無法複製SnapLock 到一個實體磁碟區上的檔案。
 a| 
您可以複製SnapLock 不全的資料、但無法複製SnapLock 到一個實體磁碟區上的檔案。



 a| 
LUN
 a| 
否
 a| 
否



 a| 
SM磁帶
 a| 
否
 a| 
否



 a| 
內部組態MetroCluster
 a| 
支援使用支援支援的支援部門、可在支援的情況下、在各種組態上裝載各種不完整的稽核記錄磁碟區、但有下列限制：SnapLock SnapLock MetroCluster

* 支援鏡射與無鏡射Aggregate上的支援。SnapLock
* 僅在無鏡射的集合體上支援「符合性」SnapLock 。


所有MetroCluster 的支援鏡射Aggregate的組態。請參閱ONTAP 《支援非MetroCluster 鏡射的集合體發行說明」、以判斷您的支援不支援鏡射的組態。

https://library.netapp.com/ecmdocs/ECMLP2492508/html/frameset.html["發行說明ONTAP"^]
 a| 
否



 a| 
支援FabricPools on SnapLock Faggregate
 a| 
否
 a| 
是的、從ONTAP 功能性的問題9.8開始。不過、您的客戶團隊需要開啟產品差異要求、記錄您瞭解FabricPool 到、由於SnapLock 雲端管理員可以刪除這些資料、因此不再以不受保護的方式、將階層至公有雲或私有雲的資料分層。

[NOTE]
====
您應該注意FabricPool 、任何資料若不再受到SnapLock 任何資料的保護、而將其納入公有雲或私有雲、則可由雲端管理員刪除。

====


 a| 
資料量FlexGroup
 a| 
是的、從ONTAP 功能性的問題9.11.1開始、但不支援下列功能：

* 合法持有
* 以事件為基礎的保留
* 適用於本產品的SnapLock SnapVault


您也應該瞭解下列行為：

* 一個現象區的Volume法規遵循時鐘（VCC）FlexGroup 由根部的VCC決定。所有非根成員的VCC都會與根VCC密切同步。
* 僅能在整個的整個過程中設定組態屬性。SnapLock FlexGroup個別成員不能具有不同的組態內容、例如預設保留時間和自動提交期間。

 a| 
是的、從ONTAP 功能性的問題9.11.1開始、但不支援下列功能：

* 合法持有
* 以事件為基礎的保留
* 適用於本產品的SnapLock SnapVault


您也應該瞭解下列行為：

* 一個現象區的Volume法規遵循時鐘（VCC）FlexGroup 由根部的VCC決定。所有非根成員的VCC都會與根VCC密切同步。
* 僅能在整個的整個過程中設定組態屬性。SnapLock FlexGroup個別成員不能具有不同的組態內容、例如預設保留時間和自動提交期間。


|===


== 零售組態與法規遵循時鐘MetroCluster

下列組態使用兩種法規遵循時鐘機制：Volume Compliance Clock(VCC)和System Compliance Clock, SCC)。MetroClusterVCC和SCC適用於所有SnapLock 的各種版本。當您在節點上建立新磁碟區時、其VCC會以該節點上SCC的目前值初始化。建立磁碟區之後、就會一律使用VCC追蹤磁碟區和檔案保留時間。

當磁碟區複寫到另一個站台時、其VCC也會複寫。當發生磁碟區切換時、例如從站台A切換至站台B、VCC會在站台B上繼續更新、而站台A上的SCC會在站台A離線時停止。

當站台A重新上線且執行磁碟區切換時、站台A SCC時鐘會重新啟動、而Volume的VCC則會繼續更新。由於VCC會持續更新、無論切換和切換作業為何、檔案保留時間不取決於SCC時鐘、也不會延展。



== 將檔案提交至 WORM

您可以使用應用程式、透過NFS或CIFS將檔案提交至WORM、或使用SnapLock 「更新」功能、自動將檔案提交至WORM。您可以使用_WORM可應用檔案_來保留遞增寫入的資料、例如記錄資訊。



== 資料保護

支援資料保護方法、可滿足大部分的法規遵循需求：SnapLock

* 您可以在SnapLock 二線儲存設備上使用「以WORM SnapVault 保護Snapshot複本」功能。
* 您可以使用SnapMirror將WORM檔案複寫到另一個地理位置、以便進行災難恢復。




== 儲存效率

從功能支援的支援範圍ONTAP 從支援支援儲存SnapLock 效率的9.9到9.9.1、例如資料壓縮、跨Volume重複資料刪除、SnapLock 以及針對功能區和集合體的調適性壓縮。



== 7-Mode轉換

您可以使用7-Mode Transition Tool的複製型轉換（CBT）功能、將SnapLock VMware Volume從7-Mode移轉至ONTAP VMware。目的地Volume、Compliance或Enterprise的指令檔模式必須符合來源Volume的指令碼模式。SnapLock SnapLock您無法使用無複製轉換（CFT）來移轉SnapLock 版本。



== 加密

支援以軟體和硬體為基礎的加密技術、可確保儲存媒體在重新調整用途、退回、放錯地方或遭竊時、無法讀取閒置的資料。ONTAP

*免責聲明：*如果驗證金鑰遺失、或驗證嘗試失敗次數超過指定限制、導致磁碟機永久鎖定、NetApp無法保證自我加密磁碟機或磁碟區上的SnapLock保護WORM檔案將可擷取。您有責任確保驗證失敗。

[NOTE]
====
從ONTAP 支援支援使用支援功能的支援功能到支援功能SnapLock 的功能、從功能性的9.2開始、

====