---
permalink: cloud/fabricpool-concept.html 
sidebar: sidebar 
keywords: netapp storage grid, fabricpool 
summary: 許多NetApp客戶的儲存資料量相當可觀、很少有人存取。我們稱之為Cold資料。客戶也有經常存取的資料、我們稱為Hot Data。理想情況下、您想要將熱資料保留在最快的儲存設備上、以獲得最佳效能。只要冷資料可在需要時立即使用、就能移至較慢的儲存設備。但您如何知道資料的哪些部分是熱的、哪些是冷的？ 
---
= FabricPool
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
許多NetApp客戶的儲存資料量相當可觀、很少有人存取。我們稱之為_Cold資料。客戶也有經常存取的資料、我們稱之為「_hot_」資料。理想情況下、您想要將熱資料保留在最快的儲存設備上、以獲得最佳效能。只要冷資料可在需要時立即使用、就能移至較慢的儲存設備。但您如何知道資料的哪些部分是熱的、哪些是冷的？

根據存取模式、可自動在高效能的本機層（Aggregate）和雲端層之間移動資料。FabricPool ONTAP分層可釋出昂貴的本機儲存空間來儲存熱資料、同時讓雲端中的低成本物件儲存設備隨時提供冷資料。此功能可持續監控資料存取、並在各層之間移動資料、以獲得最佳效能並實現最大的節約效益。FabricPool

使用功能將冷資料分層至雲端是獲得雲端效率並建立混合雲組態的最簡單方法之一。FabricPool由於可在儲存區塊層級運作、因此可同時處理檔案和LUN資料。FabricPool

但是、不只是將內部部署資料分層到雲端而已。FabricPool許多客戶使用FabricPool 支援功能的支援功能Cloud Volumes ONTAP 、將冷資料從昂貴的雲端儲存設備分層、到雲端供應商內部成本較低的物件式儲存設備。從推出支援FabricPool的磁碟區開始、您可以使用擷取分析資料ONTAP link:../concept_nas_file_system_analytics_overview.html["檔案系統分析"] 或 link:../volumes/enable-temperature-sensitive-efficiency-concept.html["對溫度敏感的儲存效率"]。

使用資料的應用程式並不知道資料是分層的、因此不需要變更應用程式。分層完全自動化、因此不需要持續管理。

您可以將冷資料儲存在主要雲端供應商之一的物件儲存設備中。或者選擇NetApp StorageGRID 解決方案、將您的冷資料保存在私有雲端、以獲得最高效能、並完全掌控您的資料。

.相關資訊
https://["系統管理程式文件FabricPool"]

https://["雲端分層服務"]

https://["NetApp TechCommTV上的播放清單FabricPool"]
