---
permalink: flexcache/create-volume-task.html 
sidebar: sidebar 
keywords: creating, flexcache, volume, flex cache, performance, remote cluster, data access, tls encryption, peer permission, 
summary: 您可以在FlexCache 同一個叢集中建立一個Sfor Volume、以改善存取熱物件時的效能。如果您的資料中心位於不同的位置、您可以在FlexCache 遠端叢集上建立支援區、以加速資料存取。 
---
= 建立FlexCache 一個流通量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在FlexCache 同一個叢集中建立一個Sfor Volume、以改善存取熱物件時的效能。如果您的資料中心位於不同的位置、您可以在FlexCache 遠端叢集上建立支援區、以加速資料存取。

.關於這項工作
這個地方的不只是一個地方、而是一個地方。FlexCache FlexGroup FlexVol

從ONTAP 使用支援的問題9.7開始、FlexGroup 從FlexCache 這個問題的源頭開始、我們也支援這些問題。

.步驟
. 如果FlexCache 要建立的實體磁碟區位於不同的叢集、請建立叢集對等關係：
+
.. 在目的地叢集上、與資料保護來源叢集建立對等關係：
 +
`cluster peer create -generate-passphrase -offer-expiration MM/DD/YYYY HH:MM:SS|1...7days|1...168hours -peer-addrs _peer_LIF_IPs_ -initial-allowed-vserver-peers _svm_name_,..|* -ipspace _ipspace_name_`
+
從ONTAP 功能支援的9.6開始、建立叢集對等關係時、預設會啟用TLS加密。支援TLS加密、以便在來源FlexCache 與實體磁碟區之間進行叢集間通訊。您也可以視需要停用叢集對等關係的TLS加密。

+
[listing]
----
cluster02::> cluster peer create -generate-passphrase -offer-expiration 2days -initial-allowed-vserver-peers *

                     Passphrase: UCa+6lRVICXeL/gq1WrK7ShR
                Expiration Time: 6/7/2017 08:16:10 EST
  Initial Allowed Vserver Peers: *
            Intercluster LIF IP: 192.140.112.101
              Peer Cluster Name: Clus_7ShR (temporary generated)

Warning: make a note of the passphrase - it cannot be displayed again.
----
.. 在來源叢集上、驗證來源叢集到目的地叢集的驗證：
 +
`cluster peer create -peer-addrs _peer_LIF_IPs_ -ipspace _ipspace_`
+
[listing]
----
cluster01::> cluster peer create -peer-addrs 192.140.112.101,192.140.112.102

Notice: Use a generated passphrase or choose a passphrase of 8 or more characters.
        To ensure the authenticity of the peering relationship, use a phrase or sequence of characters that would be hard to guess.

Enter the passphrase:
Confirm the passphrase:

Clusters cluster02 and cluster01 are peered.
----


. 如果 FlexCache 磁碟區與原始磁碟區位於不同的 SVM 、請與建立 SVM 對等關係 `flexcache` 應用程式：
+
.. 如果 SVM 位於不同的叢集中、請為對等 SVM 建立 SVM 權限：
 +
`vserver peer permission create -peer-cluster _cluster_name_ -vserver _svm-name_ -applications flexcache`
+
下列範例說明如何建立適用於所有本機SVM的SVM對等權限：

+
[listing]
----
cluster1::> vserver peer permission create -peer-cluster cluster2 -vserver "*" -applications flexcache

Warning: This Vserver peer permission applies to all local Vservers. After that no explict
"vserver peer accept" command required for Vserver peer relationship creation request
from peer cluster "cluster2" with any of the local Vservers. Do you want to continue? {y|n}: y
----
.. 建立 SVM 對等關係：
 +
`vserver peer create -vserver local_SVM -peer-vserver _remote_SVM_ -peer-cluster _cluster_name_ -applications flexcache`


. 建立FlexCache 一個流通量：
+
`volume flexcache create -vserver _cache_svm_ -volume _cache_vol_name_ -auto-provision-as flexgroup -size _vol_size_ -origin-vserver _origin_svm_ -origin-volume _origin_vol_name_`

+
以下範例建立FlexCache 一個現象區、並自動選取現有的集合體進行資源配置：

+
[listing]
----
cluster1::> volume flexcache create -vserver vs_1 -volume fc1 -auto-provision-as flexgroup -origin-volume vol_1 -size 160MB -origin-vserver vs_1
[Job 443] Job succeeded: Successful
----
+
下列範例建立FlexCache 一個聲音量、並設定交會路徑：

+
[listing]
----
cluster1::> flexcache create -vserver vs34 -volume fc4 -aggr-list aggr34,aggr43 -origin-volume origin1 -size 400m -junction-path /fc4
[Job 903] Job succeeded: Successful
----
. 驗證FlexCache 從「聲音量」和「原始」磁碟區的「聲音」關係FlexCache 。
+
.. 檢視叢集中的 FlexCache 關係：
 +
`volume flexcache show`
+
[listing]
----
cluster1::> volume flexcache show
Vserver Volume      Size       Origin-Vserver Origin-Volume Origin-Cluster
------- ----------- ---------- -------------- ------------- --------------
vs_1    fc1         160MB      vs_1           vol_1           cluster1
----
.. 檢視來源叢集中的所有 FlexCache 關係：
 +
`volume flexcache origin show-caches`
+
[listing]
----
cluster::> volume flexcache origin show-caches
Origin-Vserver Origin-Volume   Cache-Vserver    Cache-Volume   Cache-Cluster
-------------- --------------- ---------------  -------------- ---------------
vs0            ovol1           vs1              cfg1           clusA
vs0            ovol1           vs2              cfg2           clusB
vs_1           vol_1           vs_1             fc1            cluster1
----






== 結果

成功建立了這個功能。FlexCache用戶端可以使用FlexCache 解決方案開發區的交會路徑來掛載磁碟區。

.相關資訊
link:../peering/index.html["叢集與SVM對等關係"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令數ONTAP"^]
