---
permalink: flexcache/create-volume-task.html 
sidebar: sidebar 
keywords: creating, flexcache, volume, flex cache, performance, remote cluster, data access, tls encryption, peer permission, 
summary: 您可以在FlexCache 同一個叢集中建立一個Sfor Volume、以改善存取熱物件時的效能。如果您的資料中心位於不同的位置、您可以在FlexCache 遠端叢集上建立支援區、以加速資料存取。 
---
= 建立FlexCache 一個流通量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在FlexCache 同一個叢集中建立一個Sfor Volume、以改善存取熱物件時的效能。如果您的資料中心位於不同的位置、您可以在FlexCache 遠端叢集上建立支援區、以加速資料存取。

這個地方的不只是一個地方、而是一個地方。FlexCache FlexGroup FlexVol

從ONTAP 使用支援的問題9.7開始、FlexGroup 從FlexCache 這個問題的源頭開始、我們也支援這些問題。

.步驟
. 如果FlexCache 要建立的實體磁碟區位於不同的叢集、請建立叢集對等關係：
+
.. 在目的地叢集上、建立與資料保護來源叢集的對等關係：+「叢集對等端點建立-產生密碼-提供到期日：月/日/年：月：月：月：月1日...7天1 ...168hours-對等 端點_對等 端點_Peer_LIF_IP_-initial-allowed-vserver_Peers _svm_name_、.|IP_space*-name_
+
從ONTAP 功能支援的9.6開始、建立叢集對等關係時、預設會啟用TLS加密。支援TLS加密、以便在來源FlexCache 與實體磁碟區之間進行叢集間通訊。您也可以視需要停用叢集對等關係的TLS加密。

+
[listing]
----
cluster02::> cluster peer create -generate-passphrase -offer-expiration 2days -initial-allowed-vserver-peers *

                     Passphrase: UCa+6lRVICXeL/gq1WrK7ShR
                Expiration Time: 6/7/2017 08:16:10 EST
  Initial Allowed Vserver Peers: *
            Intercluster LIF IP: 192.140.112.101
              Peer Cluster Name: Clus_7ShR (temporary generated)

Warning: make a note of the passphrase - it cannot be displayed again.
----
.. 在來源叢集上、將來源叢集驗證至目的地叢集：+「叢集對等實體create -對等 實體_Peer_LIF_IPS_-IPSpace _IPspace_」
+
[listing]
----
cluster01::> cluster peer create -peer-addrs 192.140.112.101,192.140.112.102

Notice: Use a generated passphrase or choose a passphrase of 8 or more characters.
        To ensure the authenticity of the peering relationship, use a phrase or sequence of characters that would be hard to guess.

Enter the passphrase:
Confirm the passphrase:

Clusters cluster02 and cluster01 are peered.
----


. 如果FlexCache 將SVM磁碟區放在不同於原始磁碟區的SVM中、請建立SVM對等關係、並使用「FlexCache S動說」作為應用程式：
+
.. 如果SVM位於不同的叢集中、請為對等SVM建立SVM權限：+「vserver對等權限create -對等 叢集_cluster name_-vserver _Svm-name_-applics FlexCache finu32」
+
下列範例說明如何建立適用於所有本機SVM的SVM對等權限：

+
[listing]
----
cluster1::> vserver peer permission create -peer-cluster cluster2 -vserver "*" -applications flexcache

Warning: This Vserver peer permission applies to all local Vservers. After that no explict
"vserver peer accept" command required for Vserver peer relationship creation request
from peer cluster "cluster2" with any of the local Vservers. Do you want to continue? {y|n}: y
----
.. 建立SVM對等關係：+「vserver對等端點create -vserver local_SVM -對等 虛擬伺服器_svm_-對等 叢集_cluster name_-applics FlexCache 才能實現。


. 建立FlexCache 一個流通量：
+
「Volume FlexCache flexcreate -vserver _cache _Svm_-volume _cache vol_name_-autoProve-as FlexGroup flex-size _vol_size_-orige-vserver _origine_Svm_-origore-volume _origor_v_name_」

+
以下範例建立FlexCache 一個現象區、並自動選取現有的集合體進行資源配置：

+
[listing]
----
cluster1::> volume flexcache create -vserver vs_1 -volume fc1 -auto-provision-as flexgroup -origin-volume vol_1 -size 160MB -origin-vserver vs_1
[Job 443] Job succeeded: Successful
----
+
下列範例建立FlexCache 一個聲音量、並設定交會路徑：

+
[listing]
----
cluster1::> flexcache create -vserver vs34 -volume fc4 -aggr-list aggr34,aggr43 -origin-volume origin1 -size 400m -junction-path /fc4
[Job 903] Job succeeded: Successful
----
. 驗證FlexCache 從「聲音量」和「原始」磁碟區的「聲音」關係FlexCache 。
+
.. 檢視FlexCache 叢集中的「不一樣」關係：+「Volume FlexCache 不清楚」
+
[listing]
----
cluster1::> volume flexcache show
Vserver Volume      Size       Origin-Vserver Origin-Volume Origin-Cluster
------- ----------- ---------- -------------- ------------- --------------
vs_1    fc1         160MB      vs_1           vol_1           cluster1
----
.. 檢視FlexCache 來源叢集中所有的「不完整」關係：+「Volume FlexCache 不完整的顯示快取」
+
[listing]
----
cluster::> volume flexcache origin show-caches
Origin-Vserver Origin-Volume   Cache-Vserver    Cache-Volume   Cache-Cluster
-------------- --------------- ---------------  -------------- ---------------
vs0            ovol1           vs1              cfg1           clusA
vs0            ovol1           vs2              cfg2           clusB
vs_1           vol_1           vs_1             fc1            cluster1
----






== 結果

成功建立了這個功能。FlexCache用戶端可以使用FlexCache 解決方案開發區的交會路徑來掛載磁碟區。

link:../peering/index.html["叢集與SVM對等關係"]

http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令ONTAP"]
