---
permalink: flexcache/supported-unsupported-features-concept.html 
sidebar: sidebar 
keywords: supported, unsupported, features, flexcache, volumes 
summary: FlexCache 原始磁碟區和 FlexCache 磁碟區支援的功能和傳輸協定會有所不同。 
---
= ONTAP FlexCache Volume 支援和不支援的功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9.5 開始，您可以設定 FlexCache Volume 。支援 FlexVol Volume 做為原始磁碟區、並支援 FlexGroup 磁碟區做為 FlexCache 磁碟區。從 ONTAP 9.7 開始， FlexVol Volume 和 FlexGroup Volume 都支援做為原始 Volume 。來源 Volume 和 FlexCache Volume 支援的功能和傳輸協定會有所不同。


NOTE: 只要快取磁碟區和原始磁碟區都在支援的 ONTAP 版本上執行、就能互通。請記住、只有在快取和原始伺服器至少執行支援所在的 ONTAP 版本或更新的 ONTAP 版本時、才能支援這些功能。



== FlexCache 磁碟區與原始磁碟區之間的 ONTAP 版本支援

原始磁碟區與快取磁碟區之間支援的建議 ONTAP 版本，不超過四個版本的舊版或四個版本。例如，如果快取使用的是 ONTAP 9.14.1 ，則原始伺服器可以使用的最早版本是 ONTAP 9.10.1 。



== 支援的傳輸協定

|===


| 傳輸協定 | 支援來源磁碟區？ | 支援的功能是什麼？FlexCache 


 a| 
NFSv3.
 a| 
是的
 a| 
是的



 a| 
NFSv4.
 a| 
是的

若要使用 NFSv4.x 通訊協定存取快取磁碟區、來源叢集和快取叢集都必須使用 ONTAP 9.10.1 或更新版本。原始叢集和 FlexCache 叢集可以有不同的 ONTAP 版本、但兩者都應該是 ONTAP 9.10.1 和更新版本、例如、原始伺服器可以有 ONTAP 9.10.1 、而且快取可以有 ONTAP 9.11.1 。
 a| 
是的

從 ONTAP 9.10.1 開始支援。

若要使用 NFSv4.x 通訊協定存取快取磁碟區、來源叢集和快取叢集都必須使用 ONTAP 9.10.1 或更新版本。原始叢集和 FlexCache 叢集可以有不同的 ONTAP 版本、但兩者都應該是 ONTAP 9.10.1 和更新版本、例如、原始伺服器可以有 ONTAP 9.10.1 、而且快取可以有 ONTAP 9.11.1 。



 a| 
NFSv4.2
 a| 
是的
 a| 
否



 a| 
中小企業
 a| 
是的
 a| 
是的

支援從ONTAP 功能9.8開始。

|===


== 支援的功能

|===


| 功能 | 支援來源磁碟區？ | 支援的功能是什麼？FlexCache 


 a| 
自主勒索軟體保護
 a| 
是的

支援以 ONTAP 9.10.1 開頭的 FlexVol 原始磁碟區、並支援以 ONTAP 9.13.1 開頭的 FlexGroup 原始磁碟區。請參閱 link:../anti-ransomware/use-cases-restrictions-concept.html#unsupported-configurations["自主勒索軟體保護的使用案例和考量"]。
 a| 
否



 a| 
防毒軟體
 a| 
是的

從 ONTAP 9.7 開始支援。
 a| 
不適用

如果您在原始伺服器上設定防毒掃描、則快取中不需要。無論寫入來源為何、原始防毒掃描都會在寫入前偵測感染病毒的檔案。如需搭配 FlexCache 使用防毒掃描的詳細資訊、請參閱 https://www.netapp.com/media/7336-tr4743.pdf["FlexCache with ONTAP 技術報告"^]。



 a| 
稽核
 a| 
是的

從 ONTAP 9.7 開始支援。
您可以使用原生 ONTAP 稽核來稽核 FlexCache 關聯中的 NFS 檔案存取事件。
如需詳細資訊、請參閱 xref:audit-flexcache-volumes-concept.adoc[稽核FlexCache 功能的考量]
 a| 
是的

從 ONTAP 9.7 開始支援。
您可以使用原生 ONTAP 稽核來稽核 FlexCache 關聯中的 NFS 檔案存取事件。
如需詳細資訊、請參閱 xref:audit-flexcache-volumes-concept.adoc[稽核FlexCache 功能的考量]



 a| 
Cloud Volumes ONTAP
 a| 
是的

支援ONTAP 從支援的功能為從支援的功能9.6開始
 a| 
是的

支援ONTAP 從支援的功能為從支援的功能9.6開始



 a| 
壓實
 a| 
是的

支援ONTAP 從支援的功能為從支援的功能9.6開始
 a| 
是的

支援從ONTAP 支援的功能從支援的功能9.7開始



 a| 
壓縮
 a| 
是的

支援ONTAP 從支援的功能為從支援的功能9.6開始
 a| 
是的

支援ONTAP 從支援的功能為從支援的功能9.6開始



 a| 
重複資料刪除
 a| 
是的
 a| 
是的

從功能支援從功能支援到功能支援到功能的9.6開始、可支援FlexCache 即時重複資料刪除技術。ONTAP從NetApp 9.7開始、支援從各個磁FlexCache 碟區開始的各個磁碟區重複資料刪除技術ONTAP 。



 a| 
FabricPool
 a| 
是的
 a| 
是的

支援從ONTAP 支援的功能從支援的功能9.7開始



 a| 
解決災難恢復問題FlexCache
 a| 
是的
 a| 
是的

僅支援ONTAP 從支援NFSv3傳輸協定的版本S9.9開始。不能將資料區放在獨立的SVM或獨立的叢集內。FlexCache



 a| 
流通量FlexGroup
 a| 
是的

支援從ONTAP 支援的功能從支援的功能9.7開始
 a| 
是的



 a| 
流通量FlexVol
 a| 
是的
 a| 
否



 a| 
FPolicy
 a| 
是的

支援從ONTAP 支援的功能從支援的功能9.7開始
 a| 
是的

從 ONTAP 9.7 開始支援 NFS 。
從 ONTAP 9.14.1 開始支援中小企業。



 a| 
組態MetroCluster
 a| 
是的

支援從ONTAP 支援的功能從支援的功能9.7開始
 a| 
是的

支援從ONTAP 支援的功能從支援的功能9.7開始



 a| 
Microsoft卸載資料傳輸（ODX）
 a| 
是的
 a| 
否



 a| 
NetApp Aggregate Encryption（NAE）
 a| 
是的

支援ONTAP 從支援的功能為從支援的功能9.6開始
 a| 
是的

支援ONTAP 從支援的功能為從支援的功能9.6開始



 a| 
NetApp Volume Encryption（NVE）
 a| 
是的

支援ONTAP 從支援的功能為從支援的功能9.6開始
 a| 
是的

支援ONTAP 從支援的功能為從支援的功能9.6開始



 a| 
ONTAP S3 NAS 貯體
 a| 
是的

從 ONTAP 9.12.1 開始支援
 a| 
否



 a| 
QoS
 a| 
是的
 a| 
是的


NOTE: 不支援FlexCache 檔案層級的QoS以供支援使用。



 a| 
qtree
 a| 
是的

從 ONTAP 9.6 開始、您可以建立和修改 qtree 。在來源上建立的 qtree 可在快取中存取。
 a| 
否



 a| 
配額
 a| 
是的

從 ONTAP 9.6 開始、使用者、群組和 qtree 都支援 FlexCache 原始磁碟區的配額強制。
 a| 
否

使用 FlexCache 寫入模式（預設模式）時、快取上的寫入會轉送到原始磁碟區。配額會在原點強制執行。


NOTE: 從ONTAP 功能支援的不只是功能性的9.6、FlexCache 還能在功能區上支援遠端配額（rquota）。



 a| 
SMB變更通知
 a| 
是的
 a| 
是的

從 ONTAP 9.14.1 開始、快取支援 SMB 變更通知。



 a| 
資料量SnapLock
 a| 
否
 a| 
否



 a| 
SnapMirror 非同步關係 *
 a| 
是的
 a| 
否



 a| 
 a| 
* FlexCache 起源：

* 您可以使用來源 FlexVol 的 FlexCache Volume
* 您可以使用來源 FlexGroup 的 FlexCache Volume
* 您可以在FlexCache SnapMirror關係中、從來源主要Volume取得一個解決功能區。
* 從功能不全的9.8開始ONTAP 、SnapMirror次要Volume可以是FlexCache 一個來源不全的Volume。SnapMirror 次要磁碟區必須閒置、而且沒有主動式 SnapMirror 更新；否則、 FlexCache 建立將會失敗。




 a| 
SnapMirror 同步關係
 a| 
否
 a| 
否



 a| 
SnapRestore
 a| 
是的
 a| 
否



 a| 
快照
 a| 
是的
 a| 
否



 a| 
SVM DR組態
 a| 
是的

從ONTAP 9.5開始支援。SVM DR關係的主要SVM可以是來源Volume、但如果SVM DR關係中斷、FlexCache 則必須使用新的來源Volume重新建立該關聯。
 a| 
否

您可以FlexCache 在主要SVM中使用支援功能、但不能在次要SVM中使用。在主要SVM中的FlexCache 任何一個SVM Volume都不會複寫、因為它是SVM DR關係的一部分。



 a| 
儲存層級存取保護（slag）
 a| 
否
 a| 
否



 a| 
資源隨需配置
 a| 
是的
 a| 
是的

支援從ONTAP 支援的功能從支援的功能9.7開始



 a| 
Volume複製
 a| 
是的

支援從ONTAP 功能上的支援從還原9.6開始、複製來源磁碟區和來源磁碟區中的檔案。
 a| 
否



 a| 
Volume搬移
 a| 
是的
 a| 
是（僅適用於Volume成員）

ONTAP 9.6 及更新版本支援 FlexCache Volume 的移動 Volume 成分。



 a| 
Volume重新裝載
 a| 
否
 a| 
否



 a| 
適用於陣列整合的 VStorage API （ VAAI ）
 a| 
是的
 a| 
否

|===

NOTE: 在9.5版之前的版本中、來源地不僅僅能將資料提供給執行以7-Mode運作的VMware 8.2.x系統上所建立的不實資料。ONTAP FlexVol FlexCache Data ONTAP從推出版的S25 9.5開始ONTAP 、來源FlexVol 地的不穩定區也能在FlexCache 功能區上提供資料給ONTAP 功能區上的不穩定區。有關從 7-Mode FlexCache 移轉至 ONTAP 9 FlexCache 的資訊、請參閱link:https://www.netapp.com/pdf.html?item=/media/7336-tr4743pdf.pdf["NetApp 技術報告 4743 ： FlexCache in ONTAP"^]。
