---
permalink: flexcache/typical-deployments-concept.html 
sidebar: sidebar 
keywords: typical, flexcache, deployments, performance, acceleration, hot volumes, cross-cluster, data, distribution 
summary: 通常將資料區用於讀取密集的工作負載。FlexCache您可以在FlexCache 同一個叢集中擁有一個SfVMware Volume、以加速經常存取資料或「熱物件」的效能。您也可以使用FlexCache 支援功能來將資料分散到多個叢集、以減少WAN延遲。 
---
= 典型FlexCache 的需求部署
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
通常將資料區用於讀取密集的工作負載。FlexCache您可以在FlexCache 同一個叢集中擁有一個Sf2 Volume、以加速經常存取資料或「熱物件」的效能。您也可以使用FlexCache 支援功能來將資料分散到多個叢集、以減少WAN延遲。

您可以使用FlexCache 包含功能不整合的功能、包括功能不整合、功能不整合或不整合。AFF FAS ONTAP Select從功能支援支援的支援功能為從功能支援的功能為32個。ONTAP FlexCache Cloud Volumes ONTAP



== 針對熱磁碟區的效能加速

在LAN部署中FlexCache 、S籍 叢集與原始叢集位於同一個叢集內。此SVM磁碟區可與原點磁碟區位於相同的SVM、或位於不同的SVM中。FlexCache

使用此功能可將大量CPU的工作負載用於卸載忙碌檔案伺服器的工作、以及釋出系統資源。FlexCache您可以使用對應於不同FlexCache 的支援區的多個掛載點來減少網路延遲、因為資料存取負載會在所有的快取系統之間共享。這種LAN部署方式可減少過載儲存系統的工作負載。



== 跨叢集資料發佈

在WAN部署中FlexCache 、從資料中心遠端執行的是一個不同時位於原始磁碟區的叢集。當用戶端要求資料時FlexCache 、此功能會快取常用資料、讓終端使用者更快存取資訊。這類WAN部署可減少遠端用戶端的平均存取時間。

將此功能放在離遠端辦公室越近越好。FlexCache然後、用戶端要求會明確導向FlexCache 到這個功能區。如果快取中存在有效的資料、則該資料會直接提供給用戶端。如果資料不存在於快取中、則會從來源系統透過WAN擷取資料、快取到FlexCache 該資料的整個過程、然後將其送到用戶端。
