---
permalink: volumes/change-maximum-number-files-allowed-concept.html 
sidebar: sidebar 
keywords: considerations, changing, maximum number of files, allowed, flexvol volume 
summary: 包含最多檔案數量的資料。FlexVol您可以變更磁碟區的最大檔案數、但在變更之前、您應該瞭解此變更如何影響磁碟區。 
---
= 變更FlexVol 在某個問題上允許的檔案數量上限的考量事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
包含最多檔案數量的資料。FlexVol您可以變更磁碟區的最大檔案數、但在變更之前、您應該瞭解此變更如何影響磁碟區。

如果您的資料需要大量檔案或非常大的目錄、您可以擴充ONTAP 各種文件或目錄容量。不過、您應該先瞭解相關限制和注意事項、然後再繼續。

磁碟區可以包含的檔案數量取決於它擁有的 inode 數量。_inod__是一種資料結構、包含檔案的相關資訊。Volume具有私有和公有inode。公有inode用於使用者可見的檔案、而私有inode則用於ONTAP 由內部使用的檔案。您只能變更Volume的最大公有inode數量。您不能影響私有inode的數量。

根據磁碟區大小、更新建立的磁碟區可自動設定最大公有inode數量：每32 KB磁碟區大小1個inode。ONTAP當某個磁碟區的大小由管理員直接增加、或ONTAP 由管理員透過自動調整大小功能自動增加時ONTAP 、除了增加（如有必要）公共inode的最大數量、每32 KB的Volume大小至少有1個inode、 直到磁碟區大小達到約680 GB為止。若將容量增加到大於680 GB、並不會自動產生更多inode、因為ONTAP 無法自動建立超過22、369、621個inode。如果任何大小的磁碟區需要的檔案數超過預設值、您可以使用volume modify命令來增加磁碟區的最大inode數。

您也可以減少公共inode的最大數量。這並不會變更目前配置給inode的空間量、但會降低公有inode檔案所能佔用的最大空間量。不過、在空間分配給inode之後、它永遠不會傳回Volume。因此、將最大inode數降至目前配置的inode數以下、並不會將已配置但未使用的inode所使用的空間傳回至該Volume。
