---
permalink: volumes/commands-move-volumes-reference.html 
sidebar: sidebar 
keywords: commands, moving, volumes, to move 
summary: 有特定ONTAP 的功能可用來管理Volume移動。 
---
= 用於移動磁碟區的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
有特定ONTAP 的功能可用來管理Volume移動。

[cols="2*"]
|===
| 如果您想要... | 使用此命令... 


 a| 
中止作用中Volume移動作業。
 a| 
Volume Move Abort.（Volume Move Abort.



 a| 
顯示從一個Aggregate移至另一個Aggregate的磁碟區狀態。
 a| 
《Volume Move Show》（Volume Move Show）



 a| 
開始將磁碟區從一個Aggregate移至另一個Aggregate。
 a| 
Volume Move start（Volume Move start）



 a| 
管理目標Aggregate以進行Volume搬移。
 a| 
「Volume Move target aggr」（Volume Move target aggr）



 a| 
觸發轉換移動工作。
 a| 
「Volume Move觸發轉換」



 a| 
如果預設值不足、請變更用戶端存取被封鎖的時間量。
 a| 
Volume Move start（Volume Move start）或Volume Move modify（Volume Move modify）。「volume move modify」命令是進階命令、而「cover-windows」則是進階參數。



 a| 
判斷當用戶端存取遭封鎖時、如果無法完成Volume Move作業、系統會執行什麼動作。
 a| 
Volume Move start（Volume Move start）或Volume Move modify（Volume Move modify）、使用「cover-action（轉換動作）」參數。「volume move modify」命令是進階命令、而「轉換動作」則是進階參數。

|===
如需詳細資訊、請參閱每個命令的手冊頁。
