---
permalink: volumes/commands-display-quotas-reference.html 
sidebar: sidebar 
keywords: commands for, display, displaying, information about, quotas 
summary: 您可以使用命令來顯示配額報告、其中包含強制配額和資源使用量、顯示配額狀態和錯誤的相關資訊、或是配額原則和配額規則的相關資訊。 
---
= 用於顯示配額相關資訊的 ONTAP 命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用命令來顯示配額報告、其中包含強制配額和資源使用量、顯示配額狀態和錯誤的相關資訊、或是配額原則和配額規則的相關資訊。

您只能在FlexVol 下列指令上執行：

[cols="2*"]
|===
| 如果您想要... | 使用此命令... 


 a| 
檢視強制配額的相關資訊
 a| 
`volume quota report`



 a| 
檢視配額目標的資源使用量（磁碟空間和檔案數）
 a| 
`volume quota report`



 a| 
決定允許寫入檔案時、哪些配額限制會受到影響
 a| 
`volume quota report` 使用 `-path` 參數



 a| 
顯示配額狀態、例如 `on`、 `off`和 `initializing`
 a| 
`volume quota show`



 a| 
檢視配額訊息記錄的相關資訊
 a| 
`volume quota show` 使用 `-logmsg` 參數



 a| 
檢視配額初始化和調整大小期間發生的錯誤
 a| 
`volume quota show` 使用 `-instance` 參數



 a| 
檢視配額原則的相關資訊
 a| 
`volume quota policy show`



 a| 
檢視配額規則的相關資訊
 a| 
`volume quota policy rule show`



 a| 
檢視指派給儲存虛擬機器（SVM、先前稱為Vserver）的配額原則名稱
 a| 
`vserver show` 使用 `-instance` 參數

|===
如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=volume+quota["指令參考資料ONTAP"^]需詳細 `volume quota`資訊，請參閱。



[[when-to-use-ontap-volume-quota-policy-rule-show-and-volume-quota-report-commands]]
== 何時使用 ONTAP volume quota policy rule show 和 volume quota report 命令

雖然這兩個命令都會顯示配額的相關資訊、但是 `volume quota policy rule show` 在期間快速顯示已設定的配額規則 `volume quota report` 命令會消耗更多時間和資源、顯示強制配額和資源使用量。

。 `volume quota policy rule show` 命令可用於下列用途：

* 在啟動配額規則之前、請先檢查配額規則的組態
+
無論配額已初始化或調整大小、此命令都會顯示所有已設定的配額規則。

* 快速檢視配額規則、而不影響系統資源
+
由於此命令不會顯示磁碟和檔案使用量、因此不會像配額報告那樣耗用大量資源。

* 在未指派給SVM的配額原則中顯示配額規則。


如link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["指令參考資料ONTAP"^]需詳細 `volume quota policy rule show`資訊，請參閱。

。 `volume quota report` 命令可用於下列用途：

* 檢視強制配額、包括衍生配額
* 檢視每個有效配額所使用的磁碟空間和檔案數量、包括受衍生配額影響的目標
+
（對於預設配額、使用量會顯示為「0」、因為系統會根據產生的衍生配額來追蹤使用量。）

* 決定哪些配額限制會影響何時允許寫入檔案
+
新增 `-path` 的參數 `volume quota report` 命令。



[NOTE]
====
配額報告是資源密集的作業。如果您在FlexVol 叢集中的許多個資料區上執行、可能需要很長時間才能完成。更有效率的方法是檢視SVM中特定磁碟區的配額報告。

====
如link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["指令參考資料ONTAP"^]需詳細 `volume quota report`資訊，請參閱。
