---
permalink: volumes/configure-flexvol-delete-flexclone-files-luns-task.html 
sidebar: sidebar 
keywords: configure, flexvol volume, automatically, delete, flexclone files, flexclone luns 
summary: 當磁碟區中的可用空間降至特定臨界值以下時、您可以啟用FlexVol 啟用「自動刪除」功能、自動刪除FlexClone檔案和FlexClone LUN。 
---
= 設定FlexVol 一個動態磁碟區、以自動刪除FlexClone檔案和FlexClone LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當磁碟區中的可用空間降至特定臨界值以下時、您可以啟用FlexVol 啟用「自動刪除」功能、自動刪除FlexClone檔案和FlexClone LUN。

.您需要的產品
* 這個流通量必須包含FlexClone檔案和FlexClone LUN、而且必須處於線上狀態。FlexVol
* 不能將此資訊區做為唯讀磁碟區。FlexVol


.步驟
. 使用自動刪除 FlexVol 磁碟區中的 FlexClone 檔案和 FlexClone LUN `volume snapshot autodelete modify` 命令。
+
** 適用於 `-trigger` 參數、您可以指定 `volume` 或 `snap_reserve`。
** 適用於 `-destroy-list` 參數、您必須一律指定 `lun_clone,file_clone` 無論您是否只想刪除一種類型的複本。
以下範例說明如何啟用Volume vol1以觸發自動刪除FlexClone檔案和FlexClone LUN以進行空間回收、直到25%的磁碟區包含可用空間為止：
+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs1 -volume vol1 -enabled true -commitment disrupt -trigger volume -target-free-space 25 -destroy-list lun_clone,file_clone

Volume modify successful on volume:vol1
----
+
[NOTE]
====
如果您設定的值、則在啟用 FlexVol Volume 進行自動刪除的同時 `-commitment` 參數至 `destroy`的所有 FlexClone 檔案和 FlexClone LUN `-autodelete` 參數設為 `true` 當磁碟區的可用空間低於指定臨界值時、可能會刪除。不過、 FlexClone 檔案和 FlexClone LUN 都有 `-autodelete` 參數設為 `false` 不會刪除。

====


. 使用驗證 FlexVol 磁碟區中是否已啟用自動刪除 FlexClone 檔案和 FlexClone LUN `volume snapshot autodelete show` 命令。
+
以下範例顯示已啟用Volume vol1來自動刪除FlexClone檔案和FlexClone LUN：

+
[listing]
----
cluster1::> volume snapshot autodelete show -vserver vs1 -volume vol1

         Vserver Name: vs1
          Volume Name: vol1
          Enabled: true
           Commitment: disrupt
         Defer Delete: user_created
         Delete Order: oldest_first
  Defer Delete Prefix: (not specified)
    Target Free Space: 25%
              Trigger: volume
     *Destroy List: lun_clone,file_clone*
Is Constituent Volume: false
----
. 執行下列步驟、確保您要刪除的磁碟區中的FlexClone檔案和FlexClone LUN已啟用自動刪除：
+
.. 使用自動刪除特定的 FlexClone 檔案或 FlexClone LUN `volume file clone autodelete` 命令。
+
您可以使用強制自動刪除特定的 FlexClone 檔案或 FlexClone LUN `volume file clone autodelete` 命令 `-force` 參數。

+
下列範例顯示已啟用磁碟區vol1中所含的FlexClone LUN lun1_clone自動刪除：

+
[listing]
----
cluster1::> volume file clone autodelete -vserver vs1 -clone-path /vol/vol1/lun1_clone -enabled true
----
+
您可以在建立FlexClone檔案和FlexClone LUN時啟用自動刪除功能。

.. 使用確認已啟用 FlexClone 檔案或 FlexClone LUN 以自動刪除 `volume file clone show-autodelete` 命令。
+
下列範例顯示已啟用FlexClone LUN lun1_clone以自動刪除：

+
[listing]
----
cluster1::> volume file clone show-autodelete -vserver vs1 -clone-path vol/vol1/lun1_clone
Vserver Name: vs1
Clone Path: vol/vol1/lun1_clone
**Autodelete Enabled: true**
----


+
如需使用命令的詳細資訊、請參閱個別的手冊頁。


