---
permalink: volumes/configure-volume-provision-options-task.html 
sidebar: sidebar 
keywords: configure, volume, provisioning, options 
summary: 您可以設定磁碟區以進行精簡配置、完整配置或半密集配置。 
---
= 設定Volume資源配置選項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定磁碟區以進行精簡配置、完整配置或半密集配置。

.關於這項工作
設定 `-space-slo` 選項 `thick` 確保下列事項：

* 整個磁碟區會預先配置在Aggregate中。您無法使用 `volume create` 或 `volume modify` 用於設定 Volume 的命令 `-space-guarantee` 選項。
* 保留覆寫所需的空間100%。您無法使用 `volume modify` 用於設定 Volume 的命令 `-fractional-reserve` 選項


設定 `-space-slo` 選項 `semi-thick` 確保下列事項：

* 整個磁碟區會預先配置在Aggregate中。您無法使用 `volume create` 或 `volume modify` 用於設定 Volume 的命令 `-space-guarantee` 選項。
* 不會保留空間進行覆寫。您可以使用 `volume modify` 用於設定 Volume 的命令 `-fractional-reserve` 選項。
* 已啟用自動刪除Snapshot複本。


.步驟
. 設定Volume資源配置選項：
+
`volume create -vserver _vserver_name_ -volume _volume_name_ -aggregate _aggregate_name_ -space-slo none|thick|semi-thick -space-guarantee none|volume`

+
。 `-space-guarantee` 選項預設為 `none` 適用於 AFF 系統和非 AFF DP 磁碟區。否則、預設為 `volume`。對於現有的 FlexVol 磁碟區、請使用 `volume modify` 用於設定資源配置選項的命令。

+
下列命令可在SVM VS1上設定vol1以進行精簡配置：

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-guarantee none
----
+
下列命令可在SVM VS1上設定vol1以進行完整資源配置：

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-slo thick
----
+
下列命令可在SVM VS1上設定vol1以進行半厚資源配置：

+
[listing]
----
cluster1::> volume create –vserver vs1 -volume vol1 -space-slo semi-thick
----

