---
permalink: volumes/configure-flexvol-delete-flexclone-files-luns-task.html 
sidebar: sidebar 
keywords: configure, flexvol volume, automatically, delete, flexclone files, flexclone luns, flexvol, volume, automatic, file, autodelete 
summary: 當磁碟區的可用空間低於特定臨界值時、您可以讓 FlexVol volume 自動刪除 FlexClone 檔案和 FlexClone LUN 。 
---
= 設定FlexVol 一個動態磁碟區、以自動刪除FlexClone檔案和FlexClone LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將磁碟區設定為在磁碟區的可用空間減少到特定臨界值以下時、自動開始刪除FlexClone檔案和FlexClone LUN、並在回收磁碟區中的目標可用空間量時、自動停止刪除複本。雖然您無法指定開始自動刪除複本的臨界值、但您可以指定複本是否符合刪除資格、也可以指定磁碟區的目標可用空間量。

當磁碟區中的可用空間降至低於特定臨界值、且符合_兩者_的下列需求時、磁碟區會自動刪除FlexClone檔案和FlexClone LUN：

* 自動刪除功能會針對包含FlexClone檔案和FlexClone LUN的磁碟區啟用。
+
您可以使用啟用 FlexVol Volume 的自動刪除功能 `volume snapshot autodelete modify` 命令。您必須設定 `-trigger` 參數至 `volume` 或 `snap_reserve` 讓磁碟區自動刪除 FlexClone 檔案和 FlexClone LUN 。

* FlexClone檔案和FlexClone LUN的自動刪除功能已啟用。
+
您可以使用啟用 FlexClone 檔案或 FlexClone LUN 的自動刪除 `file clone create` 命令 `-autodelete` 參數。因此、您可以停用複本的自動刪除功能、並確保其他Volume設定不會覆寫複本設定、以保留特定的FlexClone檔案和FlexClone LUN。



.開始之前
* 這個流通量必須包含FlexClone檔案和FlexClone LUN、而且必須處於線上狀態。FlexVol
* 不能將此資訊區做為唯讀磁碟區。FlexVol


.步驟
. 使用命令自動刪除 FlexVol volume 中的 FlexClone 檔案和 FlexClone LUN `volume snapshot autodelete modify` 。如link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-modify.html["指令參考資料ONTAP"^]需詳細 `volume snapshot autodelete modify`資訊，請參閱。
+
** 適用於 `-trigger` 參數、您可以指定 `volume` 或 `snap_reserve`。
** 適用於 `-destroy-list` 參數、您必須一律指定 `lun_clone,file_clone` 無論您是否只想刪除一種類型的複本。
以下範例說明如何啟用Volume vol1以觸發自動刪除FlexClone檔案和FlexClone LUN以進行空間回收、直到25%的磁碟區包含可用空間為止：
+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs1 -volume vol1 -enabled true -commitment disrupt -trigger volume -target-free-space 25 -destroy-list lun_clone,file_clone

Volume modify successful on volume:vol1
----
+
[NOTE]
====
如果您設定的值、則在啟用 FlexVol Volume 進行自動刪除的同時 `-commitment` 參數至 `destroy`的所有 FlexClone 檔案和 FlexClone LUN `-autodelete` 參數設為 `true` 當磁碟區的可用空間低於指定臨界值時、可能會刪除。不過、 FlexClone 檔案和 FlexClone LUN 都有 `-autodelete` 參數設為 `false` 不會刪除。

====


. 使用命令驗證 FlexVol volume 中是否已啟用自動刪除 FlexClone 檔案和 FlexClone LUN `volume snapshot autodelete show` 。如link:https://docs.netapp.com/us-en/ontap-cli/volume-snapshot-autodelete-show.html["指令參考資料ONTAP"^]需詳細 `volume snapshot autodelete show`資訊，請參閱。
+
以下範例顯示已啟用Volume vol1來自動刪除FlexClone檔案和FlexClone LUN：

+
[listing]
----
cluster1::> volume snapshot autodelete show -vserver vs1 -volume vol1

         Vserver Name: vs1
          Volume Name: vol1
          Enabled: true
           Commitment: disrupt
         Defer Delete: user_created
         Delete Order: oldest_first
  Defer Delete Prefix: (not specified)
    Target Free Space: 25%
              Trigger: volume
     *Destroy List: lun_clone,file_clone*
Is Constituent Volume: false
----
. 執行下列步驟、確保您要刪除的磁碟區中的FlexClone檔案和FlexClone LUN已啟用自動刪除：
+
.. 使用命令自動刪除特定的 FlexClone 檔案或 FlexClone LUN `volume file clone autodelete` 。如link:https://docs.netapp.com/us-en/ontap-cli/volume-file-clone-autodelete.html["指令參考資料ONTAP"^]需詳細 `volume file clone autodelete`資訊，請參閱。
+
您可以使用強制自動刪除特定的 FlexClone 檔案或 FlexClone LUN `volume file clone autodelete` 命令 `-force` 參數。

+
下列範例顯示已啟用磁碟區vol1中所含的FlexClone LUN lun1_clone自動刪除：

+
[listing]
----
cluster1::> volume file clone autodelete -vserver vs1 -clone-path /vol/vol1/lun1_clone -enabled true
----
+
您可以在建立FlexClone檔案和FlexClone LUN時啟用自動刪除功能。

.. 使用命令確認已啟用 FlexClone 檔案或 FlexClone LUN 以自動刪除 `volume file clone show-autodelete`。如link:https://docs.netapp.com/us-en/ontap-cli/volume-file-clone-show-autodelete.html["指令參考資料ONTAP"^]需詳細 `volume file clone show-autodelete`資訊，請參閱。
+
下列範例顯示已啟用FlexClone LUN lun1_clone以自動刪除：

+
[listing]
----
cluster1::> volume file clone show-autodelete -vserver vs1 -clone-path vol/vol1/lun1_clone
Vserver Name: vs1
Clone Path: vol/vol1/lun1_clone
**Autodelete Enabled: true**
----


+
如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。


