---
permalink: volumes/create-flexclone-file-flexclone-lun-task.html 
sidebar: sidebar 
keywords: create, flexclone file, flexclone lun, efficient, clone 
summary: 您可以在 FlexVol 或 FlexClone 磁碟區中建立檔案和 LUN 的空間效率與時間效率複本。 
---
= 建立FlexClone檔案或FlexClone LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用來建立 FlexVol Volume 或 FlexClone Volume 中檔案和 LUN 的空間效率與時間效率複本 `volume file clone create` 命令。

.您需要的產品
* FlexClone授權必須安裝在叢集上。本授權隨附於 link:https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]。
* 如果將多個區塊範圍用於子LUN複製或子檔案複製、則區塊編號不得重疊。
* 如果您要在啟用調適性壓縮的磁碟區上建立子LUN或子檔案、則區塊範圍不得對齊。
+
這表示來源開始區塊編號和目的地開始區塊編號必須是偶數對齊或是ODD對齊。



.關於這項工作
根據叢集管理員指派的權限、SVM管理員可以建立FlexClone檔案和FlexClone LUN。

您可以在建立及修改複本時、指定FlexClone檔案和FlexClone LUN的自動刪除設定。依預設、自動刪除設定為停用。

使用建立複本時、您可以覆寫現有的 FlexClone 檔案或 FlexClone LUN `volume file clone create` 命令 `-overwrite-destination` 參數。

當節點達到最大分割負載時、節點會暫時停止接受建立 FlexClone 檔案和 FlexClone LUN 的要求、並發出 `EBUSY` 錯誤訊息。當節點的分割負載低於最大值時、節點會再次接受建立FlexClone檔案和FlexClone LUN的要求。再次嘗試建立要求之前、您應該等到節點有建立複本的容量時再進行。

.步驟
. 使用建立 FlexClone 檔案或 FlexClone LUN `volume file clone create` 命令。
+
以下範例說明如何在Volume vol1中建立父檔案file1_source的FlexClone檔案file1_clone：

+
[listing]
----
cluster1::> volume file clone create -vserver vs0 -volume vol1 -source-path /file1_source -destination-path /file1_clone
----
+
如需使用此命令的詳細資訊、請參閱手冊頁。



.相關資訊
link:../concepts/manual-pages.html["指令參考資料ONTAP"]
