---
permalink: volumes/create-efficiency-policy-task.html 
sidebar: sidebar 
keywords: create, volume efficiency policy, run, efficiency, operation, volume, policy 
summary: 您可以建立 Volume 效率原則、在磁碟區上執行效率作業。 
---
= 建立 Volume 效率原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立磁碟區效率原則來執行重複資料刪除或資料壓縮、然後在磁碟區上執行重複資料刪除、並使用指定工作排程 `volume efficiency policy create` 命令。

.開始之前
您必須使用命令建立 cron 排程 `job schedule cron create`。如需管理 cron 排程的詳細資訊，請參閱link:../system-admin/index.html["系統管理參考資料"]。如link:https://docs.netapp.com/us-en/ontap-cli/job-schedule-cron-create.html["指令參考資料ONTAP"^]需詳細 `job schedule cron create`資訊，請參閱。

.關於這項工作
具有預設預先定義角色的SVM管理員無法管理重複資料刪除原則。不過、叢集管理員可以使用任何自訂角色、修改指派給SVM管理員的權限。如需SVM管理員功能的詳細資訊、請參閱 link:../authentication/index.html["系統管理員驗證與RBAC"]。

[NOTE]
====
您可以在排定的時間執行重複資料刪除或資料壓縮作業、或建立具有特定持續時間的排程、或指定臨界值百分比、以等待新資料超過臨界值、然後觸發重複資料刪除或資料壓縮作業。此臨界值是磁碟區中使用之區塊總數的百分比。例如、當磁碟區上使用的區塊總數為50%時、如果您將磁碟區上的臨界值設定為20%、則當寫入磁碟區的新資料達到10%時、資料重複資料刪除或資料壓縮會自動觸發（使用50%區塊的20%）。如有需要、您可以從取得使用的區塊總數 `df` 命令輸出。

====
.步驟
. 使用 `volume efficiency policy create` 命令以建立 Volume 效率原則。


.範例
下列命令會建立名為pol1的Volume Eff效率 原則、每天觸發效率作業：

`volume efficiency policy create -vserver vs1 -policy pol1 -schedule daily`

下列命令會建立名為pol2的Volume Effency原則、在臨界值百分比達到20%時觸發效率作業：

`volume efficiency policy create -vserver vs1 -policy pol2 -type threshold -start-threshold-percent 20%`

如link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-policy-create.html["指令參考資料ONTAP"^]需詳細 `volume efficiency policy create`資訊，請參閱。
