---
permalink: volumes/create-flexclone-file-flexclone-lun-task.html 
sidebar: sidebar 
keywords: create, flexclone file, flexclone lun 
summary: 您FlexVol 可以使用Volume檔案Clone Create命令、為出現在流通於流通於流通量或FlexClone磁碟區的檔案和LUN建立節省空間和時間的複本。 
---
= 建立FlexClone檔案或FlexClone LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您FlexVol 可以使用「Volume file clone creation」命令、為出現在現象的檔案和LUN建立節省空間和時間的複本、並建立這些複本。

.您需要的產品
* FlexClone授權必須安裝在叢集上。
* 如果將多個區塊範圍用於子LUN複製或子檔案複製、則區塊編號不得重疊。
* 如果您要在啟用調適性壓縮的磁碟區上建立子LUN或子檔案、則區塊範圍不得對齊。
+
這表示來源開始區塊編號和目的地開始區塊編號必須是偶數對齊或是ODD對齊。



.關於這項工作
根據叢集管理員指派的權限、SVM管理員可以建立FlexClone檔案和FlexClone LUN。

您可以在建立及修改複本時、指定FlexClone檔案和FlexClone LUN的自動刪除設定。依預設、自動刪除設定為停用。

當您使用「volume file clone create」命令搭配「-Overwrite目的地」參數建立複本時、可以覆寫現有的FlexClone檔案或FlexClone LUN。

當節點達到最大的分割負載時、節點會暫時停止接受建立FlexClone檔案和FlexClone LUN的要求、並發出「EBUSY」錯誤訊息。當節點的分割負載低於最大值時、節點會再次接受建立FlexClone檔案和FlexClone LUN的要求。再次嘗試建立要求之前、您應該等到節點有建立複本的容量時再進行。

.步驟
. 使用「volume file clone cre創作」命令建立FlexClone檔案或FlexClone LUN。
+
以下範例說明如何在Volume vol1中建立父檔案file1_source的FlexClone檔案file1_clone：

+
[listing]
----
cluster1::> volume file clone create -vserver vs0 -volume vol1 -source-path /file1_source -destination-path /file1_clone
----
+
如需使用此命令的詳細資訊、請參閱手冊頁。



.相關資訊
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令數ONTAP"^]
