---
permalink: volumes/delete-snapshot-copies-automatic-task.html 
sidebar: sidebar 
keywords: delete, snapshot, copies, automatically, flexclone luns 
summary: 您可以定義並啟用原則、以自動刪除Snapshot複本和FlexClone LUN。自動刪除Snapshot複本和FlexClone LUN可協助您管理空間使用率。 
---
= 自動刪除Snapshot複本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以定義並啟用原則、以自動刪除Snapshot複本和FlexClone LUN。自動刪除Snapshot複本和FlexClone LUN可協助您管理空間使用率。

.關於這項工作
您可以從讀寫父磁碟區自動刪除Snapshot複本、以及從讀寫父磁碟區刪除FlexClone LUN。您無法設定從唯讀磁碟區自動刪除Snapshot複本、例如SnapMirror目的地磁碟區。

.步驟
. 定義並啟用原則、以使用自動刪除 Snapshot 複本 `volume snapshot autodelete modify` 命令。
+
請參閱 `volume snapshot autodelete modify` 手冊頁、以取得可搭配此命令使用之參數的相關資訊、以定義符合您需求的原則。

+
下列命令可自動刪除 Snapshot 複本、並將觸發器設為 `snap_reserve` 對於屬於 vs0.example.com 儲存虛擬機器（ SVM ）一部分的 vol3 Volume ：

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger snap_reserve
----
+
下列命令可自動刪除標示為自動刪除vol3 Volume（屬於vs0.example.com儲存虛擬機器（SVM）的Snapshot複本和FlexClone LUN：

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger volume -commitment try -delete-order
oldest_first -destroy-list lun_clone,file_clone
----
+
[NOTE]
====
Aggregate層級的Snapshot複本的運作方式與Volume層級的Snapshot複本不同、ONTAP 而且會由NetApp自動管理。刪除Aggregate Snapshot複本的選項一律啟用、有助於管理空間使用率。

如果觸發器參數設為 `snap_reserve` 對於 Aggregate 、 Snapshot 複本會保留到保留空間超過臨界容量為止。因此、即使觸發器參數未設定為 `snap_reserve`，快照複本在命令中使用的空間將列爲 `0` 因為這些 Snapshot 複本會自動刪除。此外、Snapshot複本在Aggregate中所使用的空間會被視為可用空間、並會包含在命令的可用空間參數中。

====

