---
permalink: volumes/delete-snapshot-copies-automatic-task.html 
sidebar: sidebar 
keywords: delete, snapshot, copies, automatically, flexclone luns 
summary: 您可以定義並啟用原則、以自動刪除Snapshot複本和FlexClone LUN。自動刪除Snapshot複本和FlexClone LUN可協助您管理空間使用率。 
---
= 自動刪除Snapshot複本
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以定義並啟用原則、以自動刪除Snapshot複本和FlexClone LUN。自動刪除Snapshot複本和FlexClone LUN可協助您管理空間使用率。

您可以從讀寫父磁碟區自動刪除Snapshot複本、以及從讀寫父磁碟區刪除FlexClone LUN。您無法設定從唯讀磁碟區自動刪除Snapshot複本、例如SnapMirror目的地磁碟區。

.步驟
. 使用「Volume Snapshot autodete modify」命令定義並啟用自動刪除Snapshot複本的原則。
+
請參閱「Volume Snapshot autodete modify」手冊頁、以取得有關此命令可用於定義符合需求之原則的參數的資訊。

+
下列命令可自動刪除Snapshot複本、並將vol3磁碟區的觸發程序設定為「nap_Reserve」、該磁碟區是vs0.example.com儲存虛擬機器（SVM）的一部分：

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger snap_reserve
----
+
下列命令可自動刪除標示為自動刪除vol3 Volume（屬於vs0.example.com儲存虛擬機器（SVM）的Snapshot複本和FlexClone LUN：

+
[listing]
----
cluster1::> volume snapshot autodelete modify -vserver vs0.example.com
-volume vol3 -enabled true -trigger volume -commitment try -delete-order
oldest_first -destroy-list lun_clone,file_clone
----
+
[NOTE]
====
Aggregate層級的Snapshot複本的運作方式與Volume層級的Snapshot複本不同、ONTAP 而且會由NetApp自動管理。刪除Aggregate Snapshot複本的選項一律啟用、有助於管理空間使用率。

如果某個集合體的觸發參數設為「nap_Reserve」、則會保留Snapshot複本、直到保留的空間超過臨界容量為止。因此、即使觸發參數未設定為「nap_Reserve」、Snapshot複本在命令中使用的空間仍會列為「0」、因為這些Snapshot複本會自動刪除。此外、Snapshot複本在Aggregate中所使用的空間會被視為可用空間、並會包含在命令的可用空間參數中。

====

