---
permalink: volumes/df-command-file-size-concept.html 
sidebar: sidebar 
keywords: df, command, file, size, reporting, reports, space, usage, qtree, quota 
summary: df 命令報告空間使用的方式取決於配額組態。 
---
= df命令如何計算檔案大小
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在中的方式 `df` 命令會根據兩種情況報告空間使用量：是否為包含 qtree 的磁碟區啟用或停用配額、以及是否追蹤 qtree 內的配額使用量。

當針對 qtree 內包含 qtree 和配額使用量的磁碟區啟用配額時、會追蹤的空間使用量 `df` 命令等於配額報告指定的值。在這種情況下、配額使用量會排除目錄、ACL、串流目錄和中繼檔所使用的區塊。

當磁碟區上未啟用配額、或qtree未設定配額規則時、報告的空間使用量會包含整個磁碟區（包括磁碟區內的其他qtree）的目錄、ACL、串流目錄和中繼檔所使用的區塊。在這種情況下、會回報的空間使用量 `df` 命令大於追蹤配額時所報告的預期值。

當您執行時 `df` 命令從 qtree 的掛載點追蹤配額使用量、命令輸出會顯示與配額報告指定的值相同的空間使用量。在大多數情況下、當樹狀結構配額規則具有硬碟限制時、會報告總大小 `df` 命令等於磁碟限制、可用空間等於配額磁碟限制與配額使用量之間的差異。

不過、在某些情況下、會報告可用空間 `df` 命令可能等於整個磁碟區的可用空間。如果沒有為qtree設定硬碟限制、就可能發生此問題。從供應到供應的更新版本9.9.1開始ONTAP 、當整個磁碟區的可用空間少於剩餘的樹狀結構配額空間時、也會發生此問題。發生上述任一情況時、會報告總大小 `df` 命令是一個合成數字、等於 qtree 內使用的配額、加上 FlexVol Volume 中的可用空間。

[NOTE]
====
此總大小既不是qtree磁碟限制、也不是Volume設定的大小。它也會因您在其他qtree內的寫入活動或背景儲存效率活動而有所不同。

====
.說明的空間使用範例 `df` 命令和配額報告
下列配額報告顯示qtree Alice1 GB的磁碟限制、qtree bob 2 GB的磁碟限制、qtree project1的磁碟限制為無上限：

[listing]
----
C1_vsim1::> quota report -vserver vs0
Vserver: vs0
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol2     alice     tree    1
                                  502.0MB    1GB       2       -   alice
vol2     bob       tree    2
                                   1003MB    2GB       2       -   bob
vol2     project1  tree    3
                                  200.8MB      -       2       -   project1
vol2               tree    *           0B      -       0       -   *
4 entries were displayed.
----
在下列範例中、的輸出 `df` qtree 上的命令 Alice 和 bob 會報告與配額報告相同的已用空間、以及與磁碟限制相同的總大小（以 1M 區塊為準）。這是因為qtree Aliceand bob的配額規則具有已定義的磁碟限制、而Volume可用空間（1211 MB）大於qtree Alice（523 MB）和qtree bob（1045 MB）的剩餘樹狀配額空間。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/alice
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1024   502       523  50% /mnt/vol2

linux-client1 [~]$ df -m /mnt/vol2/bob
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2048  1004      1045  50% /mnt/vol2
----
在下列範例中、的輸出 `df` qtree project1 上的命令會報告與配額報告相同的已用空間、但總大小會透過將磁碟區中的可用空間（ 1211 MB ）新增至 qtree project1 （ 201 MB ）的配額使用量、以提供總共 1412 MB 的空間來合成。這是因為qtree project1的配額規則沒有磁碟限制。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/project1
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1412   201      1211  15% /mnt/vol2
----
[NOTE]
====
下列範例顯示的輸出方式 `df` 整個捲上的命令會回報與 project1 相同的可用空間。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2919  1709      1211  59% /mnt/vol2
----
====