---
permalink: volumes/disable-deduplication-volume-task.html 
sidebar: sidebar 
keywords: disabling, deduplication, volume 
summary: 您可以在磁碟區上獨立停用後處理重複資料刪除和即時重複資料刪除。 
---
= 停用磁碟區上的重複資料刪除功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在磁碟區上獨立停用後處理重複資料刪除和即時重複資料刪除。

.您需要的產品
停止目前在磁碟區上作用中的任何Volume效率作業： `volume efficiency stop`

如link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-stop.html["指令參考資料ONTAP"^]需詳細 `volume efficiency stop`資訊，請參閱。

.關於這項工作
如果您已在捲上啟用資料壓縮，執行命令會停用資料壓縮 `volume efficiency off`。如link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-off.html["指令參考資料ONTAP"^]需詳細 `volume efficiency off`資訊，請參閱。

.選擇
* 使用 `volume efficiency off` 命令可停用後處理重複資料刪除和內嵌重複資料刪除。
+
下列命令可停用Volume Vola上的後處理重複資料刪除和即時重複資料刪除功能：

+
`volume efficiency off -vserver vs1 -volume VolA`

* 使用 `volume efficiency modify` 命令 `-policy` 選項設為 `inline only` 若要停用後處理重複資料刪除、但即時重複資料刪除功能仍保持啟用狀態。
+
下列命令會停用後處理重複資料刪除、但Volume Vola仍會啟用即時重複資料刪除：

+
`volume efficiency modify -vserver vs1 -volume VolA -policy inline-only`

* 使用 `volume efficiency modify` 命令 `-inline-deduplication` 選項設為 `false` 僅停用即時重複資料刪除。
+
下列命令僅會停用Volume Vola上的即時重複資料刪除功能：

+
`volume efficiency modify -vserver vs1 -volume VolA -inline-deduplication false`

+
如link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["指令參考資料ONTAP"^]需詳細 `volume efficiency modify`資訊，請參閱。


