---
permalink: volumes/enable-storage-efficiency-visualization-concept.html 
sidebar: sidebar 
keywords: storage, efficiency, visualization, storage aggregate 
summary: 顯示系統中所有集合體的儲存效率不同檢視。 
---
= 儲存效率視覺化
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 `storage aggregate show-efficiency`命令顯示有關係統中所有聚合的儲存效率的資訊。

。 `storage aggregate show-efficiency` 命令有三種不同的檢視、可透過傳遞命令選項來叫用。

詳細了解 `storage aggregate show-efficiency`在link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-efficiency.html["指令參考資料ONTAP"^] 。



== 預設檢視

預設檢視會顯示每個集合體的整體比率。

`cluster1::> storage aggregate show-efficiency`



== 詳細檢視

使用叫用詳細檢視 `-details` 命令選項。此檢視會顯示下列項目：

* 每個集合體的整體效率比率。
* 無快照的整體比率。
* 下列效率技術的比率分割： Volume 重複資料刪除， Volume 壓縮，快照，複本，資料壓縮及 Aggregate 內嵌重複資料刪除。


`cluster1::> storage aggregate show-efficiency -details`



== 進階檢視

進階檢視類似於詳細檢視、並同時顯示邏輯和實體使用的詳細資料。

您必須在進階權限層級執行此命令。使用切換至進階權限 `set -privilege advanced` 命令。

命令提示字元會變更為 `cluster::*>`。

`cluster1::> set -privilege advanced`

使用叫用進階檢視 `-advanced` 命令選項。

`cluster1::*> storage aggregate show-efficiency -advanced`

若要個別檢視單一集合體的比率、請叫用 `-aggregate _aggregate_name_` 命令。此命令可在管理層級以及進階權限層級執行。

`cluster1::> storage aggregate show-efficiency -aggregate aggr1`

如link:https://docs.netapp.com/us-en/ontap-cli/set.html["指令參考資料ONTAP"^]需詳細 `set -privilege advanced`資訊，請參閱。
