---
permalink: volumes/enable-deduplication-volume-task.html 
sidebar: sidebar 
keywords: enable, deduplication, volume, FlexVol, postprocess, inline 
summary: 在 FlexVol volume 上啟用重複資料刪除（後處理或內嵌）、以達到儲存效率。 
---
= 在磁碟區上啟用重複資料刪除
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在FlexVol 支援重複資料刪除技術的過程中、在一個支援重複資料刪除的磁碟區上啟用、您可以在所有磁碟區上啟用後處理重複資料刪除功能、並在AFF 駐留在NetApp或Flash Pool Aggregate上的磁碟區上啟用即時重複資料刪除功能。

如果您想在其他類型的磁碟區上啟用即時重複資料刪除、請參閱知識庫文章 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/How_to_enable_volume_inline_deduplication_on_Non-AFF_(All_Flash_FAS)_aggregates["如何在非AFF（All Flash FAS ）集合體上啟用Volume即時重複資料刪除"^]。

.開始之前
對於某個Set功能 磁碟區、您必須已確認磁碟區和集合體中有足夠的可用空間可用於重複資料刪除中繼資料。FlexVol重複資料刪除中繼資料需要集合體中的最小可用空間量。此金額等於FlexVol 所有重複資料刪除的所有非重複資料的實體資料總量的3%、或是集合體內的資料成分。每FlexVol 個實體磁碟區或資料組成部份應佔實體資料總可用空間的4%、總計應佔7%。

[NOTE]
====
從功能支援功能支援功能支援功能9.2開始ONTAP 、AFF 預設會在支援功能的支援系統上啟用即時重複資料刪除功能。

====
.選擇
* 使用 `volume efficiency on`命令啟用後處理重複資料刪除。如link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-on.html["指令參考資料ONTAP"^]需詳細 `volume efficiency on`資訊，請參閱。
+
下列命令可在Volume Vola上啟用後處理重複資料刪除：

+
`volume efficiency on -vserver vs1 -volume VolA`

* 使用 `volume efficiency on`命令後加上 `volume efficiency modify`選項設定為的 `true`命令 `-inline-deduplication`，即可同時啟用後處理重複資料刪除和內嵌重複資料刪除。如link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-modify.html["指令參考資料ONTAP"^]需詳細 `volume efficiency modify`資訊，請參閱。
+
下列命令可在Volume Vola上同時啟用後處理重複資料刪除和即時重複資料刪除：

+
`volume efficiency on -vserver vs1 -volume VolA`

+
`volume efficiency modify -vserver vs1 -volume VolA -inline-dedupe true`

* 使用 `volume efficiency on` 命令後面接著 `volume efficiency modify` 命令 `-inline-deduplication` 選項設為 `true` 和 `-policy` 選項設為 `inline-only` 僅啟用即時重複資料刪除。
+
下列命令僅在Volume Vola上啟用即時重複資料刪除：

+
`volume efficiency on -vserver vs1 -volume VolA`

+
`volume efficiency modify -vserver vs1 -volume VolA -policy inline-only -inline-dedupe true`



.完成後
檢視 Volume EffEffEffEffEff需 的設定、確認設定已變更：
`volume efficiency show -instance`

如link:https://docs.netapp.com/us-en/ontap-cli/volume-efficiency-show.html["指令參考資料ONTAP"^]需詳細 `volume efficiency show -instance`資訊，請參閱。
