---
permalink: volumes/explicit-quotas-concept.html 
sidebar: sidebar 
keywords: how to, use, explicit, quotas 
summary: 您可以使用明確配額來指定特定配額目標的配額、或覆寫特定目標的預設配額。 
---
= 如何使用明確配額
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用明確配額來指定特定配額目標的配額、或覆寫特定目標的預設配額。

明確的配額會指定特定使用者、群組或qtree的限制。明確的配額會取代相同目標的任何預設配額。

針對具有衍生使用者配額的使用者新增明確的使用者配額時、您必須使用與預設使用者配額相同的使用者對應設定。否則、當您調整配額大小時、明確的使用者配額會被拒絕、因為它被視為新的配額。

明確配額只會影響相同層級（Volume或qtree）的預設配額。例如、qtree的明確使用者配額不會影響包含qtree之磁碟區的預設使用者配額。不過、qtree的明確使用者配額會覆寫（取代定義的限制）該qtree的預設使用者配額。

.明確配額範例
下列配額規則定義預設的使用者配額、將 vol1 中的所有使用者限制在 50MB 空間。不過、由於明確的配額（以粗體顯示）、因此允許一個使用者 jsmith 擁有 80MB 的空間：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "" -qtree "" -disk-limit 50m

cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "jsmith" -qtree "" -disk-limit 80m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -          -
user   jsmith    ""      off          80MB        -       -        -          -
----
以下配額規則將指定的使用者（以四個 ID 表示）限制為 550MB 磁碟空間、以及 vol1 磁碟區中的 10,000 個檔案：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target " jsmith,corp\jsmith,engineering\john smith,S-1-5-32-544" -qtree "" -disk-limit 550m -file-limit 10000

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   "jsmith,corp\jsmith,engineering\john smith,S-1-5-32-544"
                 ""      off         550MB        -   10000        -          -
----
下列配額規則將 eng1 群組限制為 150MB 磁碟空間、且 proj1 qtree 中的檔案數量不限：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol2 -policy-name default -type group -target "eng1" -qtree "proj1" -disk-limit 150m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol2

Vserver: vs0               Policy: default           Volume: vol2
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
group  eng1      proj1   off         150MB        -       -        -          -
----
以下配額規則將 vol2 磁碟區中的 proj1 qtree 限制為 750MB 磁碟空間和 75,000 個檔案：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol2 -policy-name default -type tree -target "proj1" -disk-limit 750m -file-limit 75000

cluster1::> volume quota policy rule show -vserver vs0 -volume vol2

Vserver: vs0               Policy: default           Volume: vol2
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
tree   proj1     ""      -           750MB        -   75000        -          -
----