---
permalink: volumes/logical-space-reporting-concept.html 
sidebar: sidebar 
keywords: what, logical, space, reporting, shows 
summary: 當您在磁碟區上啟用邏輯空間報告時、系統會顯示邏輯已用空間和可用空間、以及磁碟區中的總空間。 
---
= 邏輯空間報告
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您在磁碟區上啟用邏輯空間報告時、除了磁碟區的總空間之外、系統還能顯示已使用的邏輯空間量和可用空間量。此外、Linux和Windows用戶端系統上的使用者可以看到已用邏輯和可用空間、而非實體已用空間和實體可用空間。

定義：

* 實體空間是指磁碟區中可用或使用的實體儲存區塊。
* 邏輯空間是指磁碟區中的可用空間。
* 使用的邏輯空間是已使用的實體空間、加上已設定的儲存效率功能（例如重複資料刪除和壓縮）所節省的成本。


從推出支援功能的支援功能支援從功能9.5開始ONTAP 、您就能運用空間報告功能來執行邏輯空間。

啟用時、邏輯空間報告會在中顯示下列參數 `volume show` 命令：

[cols="25%,75%"]
|===
| 參數 | 意義 


 a| 
`-logical-used`
 a| 
僅顯示具有指定邏輯已用大小的磁碟區或磁碟區的相關資訊。此值包括儲存效率功能所節省的所有空間、以及實際使用的空間。這不包括Snapshot保留、但會考慮Snapshot溢位。



 a| 
`-logical-used-by-afs`
 a| 
僅顯示使用中檔案系統所使用之具有指定邏輯大小的磁碟區或磁碟區的相關資訊。此值與不同``-logical-used`` 值：超過 Snapshot 保留空間的 Snapshot 溢漏量。



 a| 
`-logical-available`
 a| 
如果只啟用邏輯空間報告、則只會顯示實體可用空間。啟用空間報告和強制時、會顯示目前可用空間量、並將儲存效率功能所節省的空間視為使用中空間。這不包括Snapshot保留。



 a| 
`-logical-used-percent`
 a| 
顯示目前的百分比 `-logical-used` 使用已配置大小的值（不包括 Volume 的 Snapshot 保留）。

此值可能大於 100% 、因為 `-logical-used-by-afs` 價值包括大量節省的效率。。 `-logical-used-by-afs` Volume 的價值不包括 Snapshot 溢漏作為已用空間。。 `-physical-used` Volume 的價值包括使用空間的 Snapshot 溢漏。



 a| 
`-used`
 a| 
顯示使用者資料和檔案系統中繼資料佔用的空間量。  不同於 `physical-used` 空間的總和、以預留供未來寫入之用的空間、以及以集合式儲存效率所節省的空間。  其中包括Snapshot溢位（Snapshot複本超出Snapshot保留空間的空間量）。不包括Snapshot保留。

|===
在CLI中啟用邏輯空間報告功能、也可在System Manager中顯示「邏輯已用空間」（%）和「邏輯空間」值

用戶端系統會在下列系統顯示器上看到顯示為「已使用」空間的邏輯空間：

* Linux系統上的* df*輸出
* Windows系統上使用Windows檔案總管的內容下的空間詳細資料。


[NOTE]
====
如果啟用邏輯空間報告而不強制使用邏輯空間、則顯示在用戶端系統上的總計可能會高於已配置空間。

====