---
permalink: volumes/logical-space-reporting-concept.html 
sidebar: sidebar 
keywords: what, logical, space, reporting, shows 
summary: 當您在磁碟區上啟用邏輯空間報告時、除了磁碟區的總空間之外、系統還能顯示已使用的邏輯空間量和可用空間量。此外、Linux和Windows用戶端系統上的使用者可以看到已用邏輯和可用空間、而非實體已用空間和實體可用空間。 
---
= 邏輯空間報告顯示的內容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您在磁碟區上啟用邏輯空間報告時、除了磁碟區的總空間之外、系統還能顯示已使用的邏輯空間量和可用空間量。此外、Linux和Windows用戶端系統上的使用者可以看到已用邏輯和可用空間、而非實體已用空間和實體可用空間。

定義：

* 實體空間是指磁碟區中可用或使用的實體儲存區塊。
* 邏輯空間是指磁碟區中的可用空間。
* 使用的邏輯空間是已使用的實體空間、加上已設定的儲存效率功能（例如重複資料刪除和壓縮）所節省的成本。


從推出支援功能的支援功能支援從功能9.5開始ONTAP 、您就能運用空間報告功能來執行邏輯空間。

啟用時、邏輯空間報告會以「volume show」命令顯示下列參數：

[cols="25%,75%"]
|===
| 參數 | 意義 


 a| 
「邏輯使用」
 a| 
僅顯示具有指定邏輯已用大小的磁碟區或磁碟區的相關資訊。此值包括儲存效率功能所節省的所有空間、以及實際使用的空間。這不包括Snapshot保留、但會考慮Snapshot溢位。



 a| 
「邏輯使用者」（按美國的美國）
 a| 
僅顯示使用中檔案系統所使用之具有指定邏輯大小的磁碟區或磁碟區的相關資訊。此值與「邏輯使用」值的差異在於、Snapshot溢漏量超過Snapshot保留量。



 a| 
「邏輯可用」
 a| 
如果只啟用邏輯空間報告、則只會顯示實體可用空間。啟用空間報告和強制時、會顯示目前可用空間量、並將儲存效率功能所節省的空間視為使用中空間。這不包括Snapshot保留。



 a| 
邏輯使用百分比
 a| 
顯示目前「邏輯使用」值的百分比、以及不含磁碟區Snapshot保留的已配置大小。

此值可以大於100%、因為「邏輯使用者」的值包括Volume的效率節約效益。Volume的「邏輯使用者」值不包括「快照溢位」作為已用空間。磁碟區的「實體使用」值包括「快照溢位」作為已用空間。



 a| 
「舊有」
 a| 
顯示已用空間量、而不考慮儲存效率功能所節省的空間。

|===
在CLI中啟用邏輯空間報告功能、也可在System Manager中顯示「邏輯已用空間」（%）和「邏輯空間」值

用戶端系統會在下列系統顯示器上看到顯示為「已使用」空間的邏輯空間：

* Linux系統上的* df*輸出
* Windows系統上使用Windows檔案總管的內容下的空間詳細資料。


[NOTE]
====
如果啟用邏輯空間報告而不強制使用邏輯空間、則顯示在用戶端系統上的總計可能會高於已配置空間。

====