---
permalink: volumes/prevent-flexclone-file-lun-automatic-deleted-task.html 
sidebar: sidebar 
keywords: prevent, specific, flexclone, file, or flexclone, lun, from automatically, deleted 
summary: 如果您有想保留的特定FlexClone檔案或FlexClone LUN、您可以將其排除在自動FlexClone刪除程序之外。 
---
= 防止自動刪除 FlexClone 檔案或 FlexClone LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您將FlexVol 某個實體磁碟區設定為自動刪除FlexClone檔案和FlexClone LUN、則任何符合您指定條件的實體複本都可能會被刪除。如果您有想保留的特定FlexClone檔案或FlexClone LUN、您可以將其排除在自動FlexClone刪除程序之外。

.開始之前
必須安裝FlexClone授權。本授權隨附於link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]。

.關於這項工作
當您建立FlexClone檔案或FlexClone LUN時、預設會停用該實體複本的自動刪除設定。當您設定FlexVol 一個自動刪除磁碟區來自動刪除複本、以回收磁碟區上的空間時、會保留已停用自動刪除的FlexClone檔案和FlexClone LUN。

[NOTE]
====
如果您設定 `commitment` 將磁碟區的層級調整為 `try` 或 `disrupt`，您可以停用這些複本的自動刪除功能，以個別保留特定的 FlexClone 檔案或 FlexClone LUN 。不過、如果您設定 `commitment` 將磁碟區的層級調整為 `destroy` 而銷毀清單則包含在內 `lun_clone,file_clone`、磁碟區設定會覆寫複本設定、而且無論複本的自動刪除設定為何、都可以刪除所有 FlexClone 檔案和 FlexClone LUN 。

====
.步驟
. 防止使用自動刪除特定的 FlexClone 檔案或 FlexClone LUN `volume file clone autodelete` 命令。
+
以下範例說明如何停用vol1中所含的FlexClone LUN lun1_clone自動刪除：

+
[listing]
----
cluster1::> volume file clone autodelete -vserver vs1 -volume vol1 -clone-path lun1_clone -enable false
----
+
無法自動刪除已停用自動刪除的FlexClone檔案或FlexClone LUN、以回收磁碟區上的空間。

. 使用確認已停用 FlexClone 檔案或 FlexClone LUN 的自動刪除功能 `volume file clone show-autodelete` 命令。
+
以下範例顯示FlexClone LUN lun1_clone的自動刪除為假：

+
[listing]
----
cluster1::> volume file clone show-autodelete -vserver vs1 -clone-path vol/vol1/lun1_clone
															Vserver Name: vs1
															Clone Path: vol/vol1/lun1_clone
															Autodelete Enabled: false
----

