---
permalink: volumes/quota-report-quotas-effect-concept.html 
sidebar: sidebar 
keywords: how, quota report, quotas in effect 
summary: 由於配額互動的方式各不相同、因此與您明確建立的配額相比、配額效果更高。若要查看哪些配額有效、您可以檢視配額報告。 
---
= 如何使用配額報告來查看哪些配額有效
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
由於配額互動的方式各不相同、因此與您明確建立的配額相比、配額效果更高。若要查看哪些配額有效、您可以檢視配額報告。

下列範例顯示FlexVol 套用在某個範圍Vol1上的不同配額類型、以及該磁碟區中所含qtree Q1的配額報告：

.範例：未針對qtree指定使用者配額
在此範例中、磁碟區vol1包含一個qtree、即Q1。系統管理員已建立三個配額：

* vol1 的預設樹狀目錄配額上限為 400MB
* vol1 的預設使用者配額上限為 100MB
* 使用者 jsmith 的 vol1 為 200MB 的明確使用者配額限制


這些配額的配額規則類似於下列範例：

[listing]
----
cluster1::*> volume quota policy rule show -vserver vs1 -volume vol1

Vserver: vs1               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
tree   ""        ""      -           400MB        -       -        -          -
user   ""        ""      off         100MB        -       -        -          -
user   jsmith    ""      off         200MB        -       -        -          -
----
這些配額的配額報告類似於下列範例：

[listing]
----
cluster1::> volume quota report
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     -          tree   *           0B  400MB       0       -   *
vol1     -          user   *           0B  100MB       0       -   *
vol1     -          user   jsmith    150B  200MB       7       -   jsmith
vol1     q1         tree   1           0B  400MB       6       -   q1
vol1     q1         user   *           0B  100MB       0       -
vol1     q1         user   jsmith      0B  100MB       5       -
vol1     -          user   root        0B    0MB       1       -
vol1     q1         user   root        0B    0MB       8       -
----
配額報告的前三行顯示系統管理員指定的三個配額。由於其中兩個配額是預設配額、ONTAP 所以不只是由NetApp自動建立衍生配額。

第四行顯示從vol1中每個qtree的預設樹狀結構配額衍生的樹狀結構配額（在此範例中、僅Q1）。

第五行顯示為qtree建立的預設使用者配額、這是因為磁碟區上存在預設使用者配額和qtree配額。

第六行顯示在qtree上為jsmith建立的衍生使用者配額、因為qtree（第5行）有預設的使用者配額、而使用者jsmith擁有該qtree上的檔案。請注意、 qtree Q1 中套用至使用者 jsmith 的限制、並不是由明確的使用者配額限制（ 200MB ）所決定。這是因為磁碟區上有明確的使用者配額限制、所以不會影響qtree的限制。而是由 qtree 的預設使用者配額（ 100MB ）來決定 qtree 的衍生使用者配額限制。

最後兩行會顯示更多使用者配額、這些配額是從磁碟區和qtree上的預設使用者配額衍生而來。在Volume和qtree上為root使用者建立了衍生的使用者配額、因為root使用者在Volume和qtree上擁有檔案。由於root使用者在配額方面獲得特殊處理、因此其衍生配額僅會追蹤配額。

.範例：為qtree指定使用者配額
此範例與上一個範例類似、只是系統管理員在qtree上新增了兩個配額。

還有一個Volume、vol1和qtree、Q1。系統管理員已建立下列配額：

* vol1 的預設樹狀目錄配額上限為 400MB
* vol1 的預設使用者配額上限為 100MB
* 對於 200MB 的用戶 jsmith 而言、 vol1 的明確使用者配額限制
* qtree Q1 的預設使用者配額上限為 50MB
* 對於 75MB 的使用者 jsmith 、 qtree Q1 的明確使用者配額限制


這些配額的配額規則如下所示：

[listing]
----
cluster1::> volume quota policy rule show -vserver vs1 -volume vol1

Vserver: vs1               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
tree   ""        ""      -           400MB        -       -        -          -
user   ""        ""      off         100MB        -       -        -          -
user   ""        q1      off          50MB        -       -        -          -
user   jsmith    ""      off         200MB        -       -        -          -
user   jsmith    q1      off          75MB        -       -        -          -
----
這些配額的配額報告如下所示：

[listing]
----

cluster1::> volume quota report
Vserver: vs1
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     -          tree   *           0B  400MB       0       -   *
vol1     -          user   *           0B  100MB       0       -   *
vol1     -          user   jsmith   2000B  200MB       7       -   jsmith
vol1     q1         user   *           0B   50MB       0       -   *
vol1     q1         user   jsmith      0B   75MB       5       -   jsmith
vol1     q1         tree   1           0B  400MB       6       -   q1
vol1     -          user   root        0B    0MB       2       -
vol1     q1         user   root        0B    0MB       1       -
----
配額報告的前五行會顯示系統管理員所建立的五個配額。由於其中有些配額是預設配額、ONTAP 所以不只是使用者配額、所以會自動建立衍生配額。

第六行顯示從vol1中每個qtree的預設樹狀結構配額衍生的樹狀結構配額（在此範例中、僅Q1）。

最後兩行顯示從磁碟區和qtree上的預設使用者配額衍生的使用者配額。在Volume和qtree上為root使用者建立了衍生的使用者配額、因為root使用者在Volume和qtree上擁有檔案。由於root使用者在配額方面獲得特殊處理、因此其衍生配額僅會追蹤配額。

由於下列原因、未建立其他預設配額或衍生配額：

* 雖然使用者同時擁有磁碟區和qtree上的檔案、但並未為jsmith使用者建立衍生的使用者配額、因為使用者在這兩個層級都有明確的配額。
* 沒有為其他使用者建立衍生的使用者配額、因為其他使用者在磁碟區或qtree上都沒有擁有檔案。
* 磁碟區上的預設使用者配額並未在qtree上建立預設使用者配額、因為qtree已有預設的使用者配額。

