---
permalink: volumes/rehost-san-task.html 
sidebar: sidebar 
keywords: rehost, san volumes 
summary: 重新託管透過對應 LUN 提供資料的 SAN 磁碟區。 
---
= 重新裝載 SAN 磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以重新託管 SAN 磁碟區、透過對應的 LUN 來提供資料。在目的地 SVM 中重新建立啟動器群組（ igroup ）之後、 Volume 重組作業可以自動重新對應同一 SVM 上的磁碟區。

.關於這項工作
* 重新託管是一項顛覆性的作業。
* 如果重新託管作業失敗、您可能需要重新設定來源Volume上的Volume原則和相關規則。
* 從 ONTAP 9.8 開始、支援使用 NetApp Volume Encryption （ NVE ）重新裝載 Volume 。如果您使用內建金鑰管理程式、加密的中繼資料將會在重新主機作業期間修改。使用者資料不會變更。
+
如果您使用的是 ONTAP 9.8 或更早版本、則必須在執行重新託管作業之前先取消對磁碟區的加密。



* 重新裝載作業之後、下列Volume原則、原則規則和組態會從來源Volume遺失、必須在重新裝載的Volume上手動重新設定：
+
** 防毒原則
** Volume效率原則
** 服務品質（QoS）原則
** Snapshot原則
** NS-SWITCH與名稱服務組態匯出原則與規則
** 使用者和群組ID




.開始之前
* Volume必須處於線上狀態。
* Volume管理作業（例如Volume搬移或LUN搬移）不得執行。
* 磁碟區或LUN上不得有作用中的I/O。
* 您必須確認目的地SVM沒有名稱相同但啟動器不同的igroup。
+
如果igroup的名稱相同、則您必須在任一SVM（來源或目的地）中重新命名igroup。

* 您必須已啟用 `force-unmap-luns` 選項。
+
** 的預設值 `force-unmap-luns` 選項是 `false`。
** 設定時不會顯示警告或確認訊息 `force-unmap-luns` 選項 `true`。




.步驟
. 記錄目標Volume上的LUN對應資訊：
+
`lun mapping show volume _volume_ vserver _source_svm_`

+
這是一個預防步驟、可避免在磁碟區重組失敗時遺失LUN對應的相關資訊。

. 刪除與目標Volume相關的igroup。
. 將目標磁碟區重新裝載至目的地SVM：
+
`volume rehost -vserver _source_svm_ -volume _volume_name_ -destination-vserver _destination_svm_`

. 將目標磁碟區上的 LUN 對應至適當的 igroup ：
+
** Volume rehost 會在目標磁碟區上保留 LUN 、但 LUN 仍未對應。
** 在對應LUN時使用目的地SVM連接埠集。
** 如果是 `auto-remap-luns` 選項設定為 `true`， LUN 會在重新主機後自動對應。



