---
permalink: volumes/san-volumes-concept.html 
sidebar: sidebar 
keywords: understand, san volumes 
summary: 瞭解 SAN Volume 資源配置的基本選項、以及每個選項如何管理 ONTAP 區塊共享技術的磁碟區空間和空間需求。 
---
= SAN Volume 資源配置總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 提供數種基本選項來進行 SAN Volume 資源配置。每個選項都使用不同的方法來管理 ONTAP 區塊共用技術的磁碟區空間和空間需求。您應該瞭解每個資源配置選項的運作方式、以便為您的環境選擇最佳選項。

[TIP]
====
不建議將 SAN LUN 和 NAS 共用放在同一個 FlexVol volume 上。您應該為 SAN LUN 和 NAS 共用區個別配置 FlexVol 磁碟區。如此可簡化管理與複寫部署。它也與 Active IQ Unified Manager （前身為 OnCommand Unified Manager ）支援 FlexVol 磁碟區的方式相似。

====


== 資源隨需配置

建立精簡配置的磁碟區時ONTAP 、建立磁碟區時、不需要保留任何額外空間。當資料寫入磁碟區時、磁碟區會從Aggregate要求所需的儲存設備、以配合寫入作業。使用精簡配置的磁碟區可讓您過度使用Aggregate、這可能會導致磁碟區無法在Aggregate用盡可用空間時、保護所需的空間。

您可以透過設定精簡配置的 FlexVol Volume 來建立它 `-space-guarantee` 選項 `none`。



== 為磁碟區進行完整資源配置

建立完整資源配置的Volume時ONTAP 、功能組會從集合區中保留足夠的儲存空間、以確保磁碟區中的任何區塊都能隨時寫入。當您將磁碟區設定為使用完整資源配置時、您可以運用ONTAP 任何一套功能（例如壓縮和重複資料刪除）來抵銷較大的前置儲存需求。

您可以透過設定完整佈建的 FlexVol Volume 來建立它 `-space-slo` （服務層級目標）選項 `thick`。



== 磁碟區的半厚資源配置

建立使用半厚資源配置的磁碟區時ONTAP 、由集合區中的儲存空間來考慮磁碟區大小。如果磁碟區因為區塊共用技術使用區塊而耗盡可用空間， ONTAP 會盡力刪除保護資料物件（快照， FlexClone 檔案和 LUN ），以釋放它們所擁有的空間。只要ONTAP 用足夠快的速度刪除保護資料物件、以跟上覆寫所需的空間、寫入作業就會繼續成功。這稱為「盡力」寫入保證。

[NOTE]
====
您無法在使用半厚資源配置的磁碟區上採用重複資料刪除、壓縮及壓縮等儲存效率技術。

====
您可以透過設定半完整佈建的 FlexVol Volume 來建立它 `-space-slo` （服務層級目標）選項 `semi-thick`。



== 與空間保留檔案和LUN搭配使用

空間保留檔案或LUN是在建立儲存設備時配置的檔案或LUN。過去、NetApp使用「精簡配置LUN」一詞來表示停用空間保留的LUN（非空間保留LUN）。

[NOTE]
====
非空間保留的檔案一般不會稱為「精簡配置的檔案」。

====
下表摘要說明三種Volume資源配置選項如何搭配空間保留檔案和LUN使用的主要差異：

[cols="5*"]
|===
| Volume資源配置 | LUN /檔案空間保留 | 覆寫 | 保護資料 | 儲存效率^3^ 


 a| 
厚
 a| 
支援
 a| 
保證為1^
 a| 
保證
 a| 
支援



 a| 
精簡
 a| 
無效果
 a| 
無
 a| 
保證
 a| 
支援



 a| 
半厚
 a| 
支援
 a| 
盡力量：1^
 a| 
盡最大努力
 a| 
不支援

|===
*附註*

. 若要保證覆寫或提供盡力覆寫保證、必須在LUN或檔案上啟用空間保留。
. 保護資料包括快照，標記為自動刪除的 FlexClone 檔案和 LUN （備份複本）。
. 儲存效率包括重複資料刪除、壓縮、任何未標示為自動刪除（作用中複本）的FlexClone檔案和LUN、以及FlexClone子檔案（用於複本卸載）。




== 支援SCSI精簡配置LUN

支援T10 SCSI精簡配置LUN、以及NetApp精簡配置LUN。ONTAPT10 SCSI精簡配置可讓主機應用程式支援SCSI功能、包括用於區塊環境的LUN空間回收和LUN空間監控功能。您的SCSI主機軟體必須支援T10 SCSI精簡配置。

您使用的是 ONTAP `space-allocation` 設定以啟用 / 停用 LUN 上 T10 精簡配置的支援。您使用的是 ONTAP `space-allocation enable` 在 LUN 上啟用 T10 SCSI 精簡配置的設定。

這 `[-space-allocation {enabled|disabled}]`命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]有更多資訊來啟用/停用對 T10 精簡配置的支援以及如何在 LUN 上啟用 T10 SCSI 精簡配置。
