---
permalink: volumes/set-fractional-reserve-concept.html 
sidebar: sidebar 
keywords: considerations, setting, fractional, reserve, lun overwrite reserve 
summary: 部分保留可讓您關閉 FlexVol volume 中空間保留 LUN 和檔案的覆寫保留、以協助最大化儲存使用率。 
---
= 設定部分保留時的考量事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
部分保留（也稱為_LUN覆寫保留區_）可讓您關閉FlexVol 針對空間保留LUN和位於一個實體磁碟區中檔案的覆寫保留。這有助於最大化儲存使用率。


CAUTION: 如果您的環境因空間不足而導致寫入作業失敗而受到負面影響、您必須瞭解此組態可能會造成的需求。

百分比保留設定是以百分比表示 `0`、唯一有效的值是和 `100`百分比。「部分保留」設定是Volume的屬性。設定部分保留以 `0`提高儲存使用率。然而、如果磁碟區的可用空間不足、存取位於磁碟區中資料的應用程式可能會發生資料中斷、即使將磁碟區保證設定為 `volume`。不過、只要有適當的Volume組態和使用、就能將寫入失敗的機率降至最低。ONTAP 為部分保留設定為 `0`達到下列要求時的磁碟區提供「盡力」寫入保證：

* 重複資料刪除功能未在使用中
* 壓縮未在使用中
* FlexClone子檔案未在使用中
* 所有FlexClone檔案和FlexClone LUN均已啟用自動刪除功能
+
這不是預設設定。您必須明確啟用自動刪除功能、無論是在建立時或是在建立FlexClone檔案或FlexClone LUN之後加以修改。

* 不使用ODX和FlexClone複本卸載
* Volume 擔保設為 `volume`
* 檔案或 LUN 空間保留為 `enabled`
* Volume Snapshot 保留區設為 `0`
* Volume Snapshot 自動刪除的 `enabled`承諾層級為 `destroy`，的銷毀清單， `lun_clone,vol_clone,cifs_share,file_clone,sfsr`以及觸發程序 `volume`
+
此設定也可確保在必要時刪除FlexClone檔案和FlexClone LUN。



[NOTE]
====
* 如果滿足上述所有要求，但變更率很高，在極少數情況下，快照自動刪除可能會落後，導致磁碟區空間不足。
* 如果滿足上述所有要求，且未使用快照，則磁碟區寫入保證不會用盡空間。


====
此外，您也可以選擇使用 Volume 自動擴充功能來降低自動刪除磁碟區快照的可能性。如果啟用自動擴充功能、則必須監控相關聯Aggregate中的可用空間。如果 Aggregate 已滿，而磁碟區無法成長，則可能會在磁碟區的可用空間耗盡時刪除更多快照。

如果您無法滿足上述所有組態需求、而且需要確保磁碟區不會用盡空間、則必須將磁碟區的「部分保留」設定設為 `100`。這需要更多的可用空間、但保證資料修改作業即使在使用上述技術時仍能順利完成。

「部分保留」設定的預設值和允許值取決於Volume的保證：

[cols="3*"]
|===
| Volume保證 | 預設的部分保留 | 允許的值 


 a| 
Volume
 a| 
100
 a| 
0 、 100



 a| 
無
 a| 
0%
 a| 
0 、 100

|===