---
permalink: volumes/space-display-quota-report-unix-client-concept.html 
sidebar: sidebar 
keywords: difference, space usage, displayed, quota report, unix client 
summary: FlexVol volume 或 qtree 配額報告中顯示的已用磁碟空間值、可能與 UNIX 用戶端針對相同磁碟區或 qtree 顯示的值不同。 
---
= ONTAP 配額報告和 UNIX 用戶端顯示的空間使用差異
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexVol volume 或 qtree 配額報告中顯示的已用磁碟空間值、可能與 UNIX 用戶端針對相同磁碟區或 qtree 顯示的值不同。這些值的差異在於配額報告後面的方法不同、以及用於計算 Volume 或 qtree 中資料區塊的 UNIX 命令。

例如、如果磁碟區包含含有空白資料區塊（未寫入資料）的檔案、則磁碟區的配額報告不會在報告空間使用量時計算空白資料區塊。不過、當磁碟區掛載到 UNIX 用戶端時、檔案會顯示為的輸出 `ls` 命令時、空間使用中也會包含空的資料區塊。因此 `ls` 與配額報告所顯示的空間使用量相比、命令會顯示較大的檔案大小。

同樣地、配額報告中顯示的空間使用值也可能與 UNIX 命令（例如）所顯示的值不同 `df` 和 `du`。



== 配額報告如何計算磁碟空間和檔案使用量

使用的檔案數量、以及配額報告中針對FlexVol 某個相依磁碟區或qtree所指定的磁碟空間量、取決於該磁碟區或qtree中每個inode對應的已使用資料區塊數。

區塊數包括用於一般和串流檔案的直接和間接區塊。用於目錄、存取控制清單（ACL）、串流目錄和中繼檔案的區塊、在配額報告中並未列入考量。如果是UNIX的稀疏檔案、配額報告中不會包含空白資料區塊。

配額子系統是專為考量及僅包含檔案系統的使用者可控制面向而設計。目錄、ACL和快照空間都是配額計算中排除的空間範例。配額用於強制執行限制、而非保證、而且僅在作用中檔案系統上運作。配額會計不會計算某些檔案系統架構、也不會考慮儲存效率（例如壓縮或重複資料刪除）。

如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。



== ls 命令與配額報告之間的空間使用差異

當您使用 `ls`命令來檢視安裝在 UNIX 用戶端上的 FlexVol volume 內容時、輸出中顯示的檔案大小可能會與磁碟區配額報告中顯示的空間使用量不同、視檔案的資料區塊類型而定。

的輸出 `ls` 命令僅顯示檔案大小、不包含檔案使用的間接區塊。檔案的任何空白區塊也會包含在命令的輸出中。

因此、如果檔案沒有空白區塊、則會顯示的大小 `ls` 命令可能小於配額報告所指定的磁碟使用量、因為配額報告中包含間接區塊。相反地、如果檔案有空白區塊、則會顯示的大小 `ls` 命令可能超過配額報告所指定的磁碟使用量。

的輸出 `ls` 命令僅顯示檔案大小、不包含檔案使用的間接區塊。檔案的任何空白區塊也會包含在命令的輸出中。

.ls命令和配額報告所說明的空間使用量差異範例
[%collapsible]
====
下列配額報告顯示qtree Q1的上限為10 MB：

[listing]
----

                                      ----Disk----  ----Files-----   Quota
  Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
  -------  --------  ------  -------  -----  -----  ------  ------   ---------
  vol1     q1          tree    user1   10MB  10MB        1       -   q1

...
----
從 UNIX 用戶端使用檢視時、同一 qtree 中的檔案大小可能超過配額限制 `ls` 命令、如下列範例所示：

[listing]
----
[user1@lin-sys1 q1]$ ls -lh
-rwxr-xr-x  1 user1 nfsuser  **27M** Apr 09  2013 file1
----
====
如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=ls["指令參考資料ONTAP"^]需詳細 `ls`資訊，請參閱。



== 了解 df 指令如何處理檔案大小

在中的方式 `df` 命令會根據兩種情況報告空間使用量：是否為包含 qtree 的磁碟區啟用或停用配額、以及是否追蹤 qtree 內的配額使用量。

當針對 qtree 內包含 qtree 和配額使用量的磁碟區啟用配額時、會追蹤的空間使用量 `df` 命令等於配額報告指定的值。在這種情況下、配額使用量會排除目錄、ACL、串流目錄和中繼檔所使用的區塊。

當磁碟區上未啟用配額、或qtree未設定配額規則時、報告的空間使用量會包含整個磁碟區（包括磁碟區內的其他qtree）的目錄、ACL、串流目錄和中繼檔所使用的區塊。在這種情況下、會回報的空間使用量 `df` 命令大於追蹤配額時所報告的預期值。

當您執行時 `df` 命令從 qtree 的掛載點追蹤配額使用量、命令輸出會顯示與配額報告指定的值相同的空間使用量。在大多數情況下、當樹狀結構配額規則具有硬碟限制時、會報告總大小 `df` 命令等於磁碟限制、可用空間等於配額磁碟限制與配額使用量之間的差異。

不過、在某些情況下、會報告可用空間 `df` 命令可能等於整個磁碟區的可用空間。如果沒有為qtree設定硬碟限制、就可能發生此問題。從供應到供應的更新版本9.9.1開始ONTAP 、當整個磁碟區的可用空間少於剩餘的樹狀結構配額空間時、也會發生此問題。發生上述任一情況時、會報告總大小 `df` 命令是一個合成數字、等於 qtree 內使用的配額、加上 FlexVol Volume 中的可用空間。

[NOTE]
====
此總大小既不是qtree磁碟限制、也不是Volume設定的大小。它也會因您在其他qtree內的寫入活動或背景儲存效率活動而有所不同。

====
.<code>df</code> 指令統計的空間使用範例及配額報告
[%collapsible]
====
下列配額報告顯示qtree Alice1 GB的磁碟限制、qtree bob 2 GB的磁碟限制、qtree project1的磁碟限制為無上限：

[listing]
----
C1_vsim1::> quota report -vserver vs0
Vserver: vs0
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol2     alice     tree    1
                                  502.0MB    1GB       2       -   alice
vol2     bob       tree    2
                                   1003MB    2GB       2       -   bob
vol2     project1  tree    3
                                  200.8MB      -       2       -   project1
vol2               tree    *           0B      -       0       -   *
4 entries were displayed.
----
在下列範例中、的輸出 `df` qtree 上的命令 Alice 和 bob 會報告與配額報告相同的已用空間、以及與磁碟限制相同的總大小（以 1M 區塊為準）。這是因為qtree Aliceand bob的配額規則具有已定義的磁碟限制、而Volume可用空間（1211 MB）大於qtree Alice（523 MB）和qtree bob（1045 MB）的剩餘樹狀配額空間。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/alice
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1024   502       523  50% /mnt/vol2

linux-client1 [~]$ df -m /mnt/vol2/bob
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2048  1004      1045  50% /mnt/vol2
----
在下列範例中、的輸出 `df` qtree project1 上的命令會報告與配額報告相同的已用空間、但總大小會透過將磁碟區中的可用空間（ 1211 MB ）新增至 qtree project1 （ 201 MB ）的配額使用量、以提供總共 1412 MB 的空間來合成。這是因為qtree project1的配額規則沒有磁碟限制。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2/project1
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      1412   201      1211  15% /mnt/vol2
----
下列範例顯示的輸出方式 `df` 整個捲上的命令會回報與 project1 相同的可用空間。

[listing]
----
linux-client1 [~]$ df -m /mnt/vol2
Filesystem          1M-blocks  Used Available Use% Mounted on
172.21.76.153:/vol2      2919  1709      1211  59% /mnt/vol2
----
====
如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。



== du 命令與配額報告之間的空間使用差異

當您執行時 `du` 命令若要檢查掛載於 UNIX 用戶端的 qtree 或 FlexVol 磁碟區的磁碟空間使用量、使用值可能會高於 qtree 或磁碟區配額報告所顯示的值。

的輸出 `du` 命令包含從發出命令的目錄層級開始、透過目錄樹狀結構的所有檔案的組合空間使用量。因為使用率值是由所顯示 `du` 命令也包含目錄的資料區塊、比配額報告所顯示的值還要高。

.DU命令與配額報告所說明的空間使用量差異範例
[%collapsible]
====
下列配額報告顯示qtree Q1的上限為10 MB：

[listing]
----

                                      ----Disk----  ----Files-----   Quota
  Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
  -------  --------  ------  -------  -----  -----  ------  ------   ---------
  vol1     q1        tree    user1    10MB   10MB   1       -        q1

...
----
在下列範例中、磁碟空間使用量是的輸出 `du` 命令會顯示超過配額限制的較高值：

[listing]
----
[user1@lin-sys1 q1]$ du -sh
**11M**     q1
----
====
如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。
