---
permalink: volumes/tree-quotas-concept.html 
sidebar: sidebar 
keywords: how, tree, quotas, work 
summary: 您可以使用qtree作為目標來建立配額、以限制目標qtree的大小。這些配額也稱為樹狀結構配額。 
---
= 了解 ONTAP 樹狀配額
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用qtree作為目標來建立配額、以限制目標qtree的大小。這些配額也稱為_tree配額_。


NOTE: 您也可以為特定qtree建立使用者和群組配額。此外FlexVol 、有時該磁碟區所包含的qtree會繼承一個適用於該磁碟區的配額。

當您將配額套用至qtree時、結果與磁碟分割區類似、只不過您可以隨時變更配額、以變更qtree的最大大小。套用樹狀結構配額時ONTAP 、無論擁有者為何、均會限制qtree中的磁碟空間和檔案數量。如果寫入作業導致超過樹狀結構配額、則任何使用者（包括root和BUILTIN\Administrator群組的成員）都無法寫入qtree。

配額大小並不保證有任何特定的可用空間量。配額的大小可以大於qtree可用的可用空間量。您可以使用 `volume quota report` 命令來確定 qtree 中的實際可用空間量。

如link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-report.html["指令參考資料ONTAP"^]需詳細 `volume quota report`資訊，請參閱。



[[learn-how-ontap-user-and-group-quotas-work-with-qtrees]]
== 了解 ONTAP 使用者和群組配額如何與 qtree 協同工作

樹狀結構配額會限制qtree的整體大小。若要防止個別使用者或群組佔用整個qtree、請為該qtree指定使用者或群組配額。

.qtree中的使用者配額範例
[%collapsible]
====
假設您有下列配額規則：

[listing]
----
cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -       45MB
user   jsmith    ""      off          80MB        -       -        -       75MB
----
您注意到某位使用者 kjones 佔用大量空間、位於 vol1 中的關鍵 qtree （ project1 ）。您可以新增下列配額規則來限制此使用者的空間：

[listing]
----
cluster1::> volume quota policy rule create -vserver vs0 -volume vol1 -policy-name default -type user -target "kjones" -qtree "proj1" -disk-limit 20m -threshold 15m

cluster1::> volume quota policy rule show -vserver vs0 -volume vol1

Vserver: vs0               Policy: default           Volume: vol1
                                               Soft             Soft
                         User         Disk     Disk   Files    Files
Type   Target    Qtree   Mapping     Limit    Limit   Limit    Limit  Threshold
-----  --------  ------- -------  --------  -------  ------  -------  ---------
user   ""        ""      off          50MB        -       -        -       45MB
user   jsmith    ""      off          80MB        -       -        -       75MB
user   kjones    proj1   off          20MB        -       -        -       15MB
----
====


[[learn-how-default-tree-quotas-on-an-ontap-flexvol-volume-create-derived-tree-quotas]]
== 了解 ONTAP FlexVol 磁碟區上的預設樹狀結構配額如何建立衍生樹狀結構配額

當您在FlexVol 某個流通量上建立預設的樹狀結構配額時、系統會自動為該磁碟區中的每個qtree建立對應的衍生樹狀結構配額。

這些衍生樹狀結構配額的限制與預設樹狀結構配額相同。如果不存在其他配額、則限制會產生下列影響：

* 使用者可以在qtree中使用與分配給整個磁碟區相同的空間（前提是使用根目錄或其他qtree中的空間不會超過磁碟區的限制）。
* 每個qtree都可以擴充以使用整個Volume。


在磁碟區上存在預設的樹狀結構配額、仍會影響所有新增至磁碟區的qtree。每次建立新的qtree時、也會建立衍生的樹狀結構配額。

如同所有衍生配額、衍生樹狀結構配額會顯示下列行為：

* 只有在目標尚未有明確配額時才會建立。
* 會顯示在配額報告中，但當您使用命令顯示配額規則時不會顯示 `volume quota policy rule show`。如link:https://docs.netapp.com/us-en/ontap-cli/volume-quota-policy-rule-show.html["指令參考資料ONTAP"^]需詳細 `volume quota policy rule show`資訊，請參閱。


.衍生樹狀結構配額範例
[%collapsible]
====
您的磁碟區有三個qtree（proj1、proj2和proj3）、唯一的樹狀結構配額是proj1 qtree上的明確配額、限制其磁碟大小為10 GB。如果您在磁碟區上建立預設樹狀結構配額、並重新初始化磁碟區上的配額、配額報告現在會包含四個樹狀結構配額：

[listing]
----
                                    ----Disk----  ----Files-----   Quota
Volume   Tree      Type    ID        Used  Limit    Used   Limit   Specifier
-------  --------  ------  -------  -----  -----  ------  ------   ---------
vol1     proj1     tree    1           0B   10GB       1       -   proj1
vol1               tree    *           0B   20GB       0       -   *
vol1     proj2     tree    2           0B   20GB       1       -   proj2
vol1     proj3     tree    3           0B   20GB       1       -   proj3
...
----
第一行顯示proj1 qtree上的原始明確配額。此配額維持不變。

第二行顯示磁碟區上的新預設樹狀結構配額。星號（*）Quota說明符表示它是預設配額。此配額是您所建立配額規則的結果。

最後兩行顯示專案2和專案3 qtree的新衍生樹狀結構配額。由於磁碟區上的預設樹狀結構配額、所以系統會自動建立這些配額。ONTAP這些衍生的樹狀結構配額具有與磁碟區上預設樹狀結構配額相同的20-GB磁碟限制。由於proj1 qtree已經有明確的配額、所以無法為proj1 qtree建立衍生的樹狀結構配額。ONTAP

====


[[learn-how-default-user-quotas-on-an-ontap-flexvol-volume-affect-quotas-for-qtrees]]
== 了解 ONTAP FlexVol Volume 上的預設使用者配額如何影響 qtree 的配額

如果針對FlexVol 某個現象磁碟區定義了預設的使用者配額、則會針對該磁碟區所包含的每個qtree、自動建立一個預設的使用者配額、其中存在明確或衍生的樹狀結構配額。

如果qtree上的預設使用者配額已存在、則在建立磁碟區上的預設使用者配額時、該配額不會受到影響。

在qtree上自動建立的預設使用者配額、其限制與您為磁碟區建立的預設使用者配額相同。

qtree的明確使用者配額會覆寫（取代自動建立的限制）自動建立的預設使用者配額、其方式與覆寫系統管理員在該qtree上建立的預設使用者配額相同。
