---
permalink: encryption-at-rest/change-key-management-passphrase-task.html 
sidebar: sidebar 
keywords: changing, onboard, key, management, passphrase 
summary: 定期更改板載密鑰管理密碼。將新密碼儲存在儲存系統之外的安全位置。 
---
= 更改ONTAP板載密鑰管理密碼
:allow-uri-read: 


[role="lead"]
NetApp建議您定期變更板載金鑰管理密碼。您必須將新密碼短語儲存在儲存系統之外的安全位置。

.開始之前
* 您必須是叢集或SVM管理員、才能執行此工作。
* 此工作需要進階權限。
* 在MetroCluster環境中，在本地叢集上更新密碼短語後，同步夥伴叢集上的密碼短語更新。


.步驟
. 變更為進階權限層級：
+
`set -privilege advanced`

. 更改機載密鑰管理密碼。您使用的命令取決於您執行的ONTAP版本。
+
[role="tabbed-block"]
====
.更新版本ONTAP
--
`security key-manager onboard update-passphrase`

--
.不含更新版本ONTAP
--
`security key-manager update-passphrase`

--
====
. 輸入一個介於 32 到 256 個字元之間的密碼，或對於“`cc-mode`”，輸入一個介於 64 到 256 個字元之間的密碼。
+
如果指定的"'cc-mode"通關密碼少於64個字元、則在金鑰管理程式設定作業再次顯示通關密碼提示之前、會有五秒鐘的延遲。

. 在通關密碼確認提示下、重新輸入通關密碼。
. 如果您使用的是MetroCluster配置，請在夥伴叢集上同步更新後的密碼短語。
+
.. 透過選擇適合您ONTAP版本的正確指令，在夥伴叢集上同步密碼短語：
+
[role="tabbed-block"]
====
.更新版本ONTAP
--
`security key-manager onboard sync`

--
.不含更新版本ONTAP
--
*** 在ONTAP 9.5 中，運行：
+
`security key-manager setup -sync-metrocluster-config`

*** 在ONTAP 9.4 及更早版本中，更新本機叢集上的密碼短語後，等待 20 秒，然後在夥伴叢集上執行以下命令：
+
`security key-manager setup`



--
====
.. 出現提示時，請輸入新的密碼短語。
+
兩個群集必須使用相同的密碼短語。





.完成後
將板載金鑰管理密碼短語複製到儲存系統外部的安全位置，以備將來使用。

每次變更機載金鑰管理密碼時，請手動備份金鑰管理資訊。

.相關資訊
* link:backup-key-management-information-manual-task.html["手動備份內建金鑰管理資訊"]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-update-passphrase.html["安全金鑰管理程式內建更新密碼"^]

