---
permalink: encryption-at-rest/change-encryption-key-volume-92-earlier-task.html 
sidebar: sidebar 
keywords: changing, encryption key, volume, volume move start, command 
summary: 定期變更磁碟區的加密金鑰是安全性最佳做法。您可以使用Volume Move start命令來變更加密金鑰。您必須在ONTAP 不包含更新版本的版本中使用Volume Move start。移動的磁碟區可以位於相同的集合體或不同的集合體上。 
---
= 使用 ONTAP 的 Volume Move start 命令變更磁碟區的加密金鑰
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
定期變更磁碟區的加密金鑰是安全性最佳做法。您可以使用 `volume move start` 變更加密金鑰的命令。您必須使用 `volume move start` 在 ONTAP 9.2 及更早版本中。移動的磁碟區可以位於相同的集合體或不同的集合體上。

.關於這項工作
您無法使用 `volume move start` 重新輸入 SnapLock 或 FlexGroup 磁碟區。

.開始之前
您必須是叢集管理員才能執行此工作。或者、您也可以是叢集管理員委派權限的 SVM 管理員。如需詳細資訊、請參閱 link:delegate-volume-encryption-svm-administrator-task.html["委派執行 Volume Move 命令的權限"]。

.步驟
. 移動現有磁碟區並變更加密金鑰：
+
`volume move start -vserver _SVM_name_ -volume _volume_name_ -destination-aggregate _aggregate_name_ -generate-destination-key true`

+
如link:https://docs.netapp.com/us-en/ontap-cli/volume-move-start.html["指令參考資料ONTAP"^]需詳細 `volume move start`資訊，請參閱。

+
下列命令會移動名為的現有 Volume `*vol1*` 至目的地 Aggregate `*aggr2*` 並變更加密金鑰：

+
[listing]
----
cluster1::> volume move start -vserver vs1 -volume vol1 -destination-aggregate aggr2 -generate-destination-key true
----
+
系統會為磁碟區建立新的加密金鑰。磁碟區上的資料仍保持加密狀態。

. 確認磁碟區已啟用加密：
+
`volume show -is-encrypted true`

+
如link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["指令參考資料ONTAP"^]需詳細 `volume show`資訊，請參閱。

+
下列命令會顯示上的加密磁碟區 `cluster1`：

+
[listing]
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr2     online    RW  200GB    160.0GB  20%
----

