---
permalink: encryption-at-rest/destroy-nse-disks-task.html 
sidebar: sidebar 
keywords: destroy, fips, drive, sed, psid, physical secure ID, nrd plus 
summary: 如果您想要使FIPS磁碟機或SED上的資料永遠無法存取、而且不需要重複使用磁碟機、可以使用儲存加密磁碟銷毀命令來銷毀磁碟。 
---
= 銷毀FIPS磁碟機或SED
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要使FIPS磁碟機或SED上的資料永遠無法存取、而且不需要重複使用磁碟機、可以使用「儲存加密磁碟銷毀」命令來銷毀磁碟。

.您需要的產品
您必須是叢集管理員才能執行此工作。

.關於這項工作
當您銷毀FIPS磁碟機或SED時、系統會將磁碟加密金鑰設為未知的隨機值、並以不可扭轉的方式鎖定磁碟機。這樣做會使磁碟幾乎無法使用、且上的資料永遠無法存取。不過、您可以使用印在磁碟標籤上的實體安全ID（PSID）、將磁碟重設為原廠設定的設定。如需詳細資訊、請參閱 link:return-self-encrypting-disks-keys-not-available-task.html["當驗證金鑰遺失時、將FIPS磁碟機或SED恢復服務"]。

[NOTE]
====
除非您擁有不可傳的Disk Plus服務（NRD Plus）、否則請勿銷毀FIPS磁碟機或SED。銷毀磁碟會使其保固失效。

====
.步驟
. 將任何需要保留的資料移轉到另一個不同磁碟上的集合體。
. 刪除FIPS磁碟機或SED上要銷毀的Aggregate：
+
'儲存Aggregate刪除-Aggregate Aggregate名稱'

+
如需完整的命令語法、請參閱手冊頁。

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
. 識別要銷毀的FIPS磁碟機或SED的磁碟ID：
+
「torage加密磁碟顯示」

+
如需完整的命令語法、請參閱手冊頁。

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.2  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
[...]
----
. 銷毀磁碟：
+
'磁碟加密磁碟銷毀-disk disk_id'

+
如需完整的命令語法、請參閱手冊頁。

+
[NOTE]
====
系統會提示您輸入確認短句、然後再繼續。輸入完全如畫面所示的詞彙。

====
+
[listing]
----
cluster1::> storage encryption disk destroy -disk 1.10.2

Warning: This operation will cryptographically destroy 1 spare or broken
         self-encrypting disks on 1 node.
         You cannot reuse destroyed disks unless you revert
         them to their original state using the PSID value.
         To continue, enter
          destroy disk
         :destroy disk

Info: Starting destroy on 1 disk.
      View the status of the operation by using the
      "storage encryption disk show-status" command.
----

