---
permalink: encryption-at-rest/emergency-shred-data-disks-storage-encryption-task.html 
sidebar: sidebar 
keywords: emergency, shred, data, fips, drive, sed, disk encrypt sanitize, disk encrypt destroy 
summary: 發生安全性緊急情況時、即使儲存系統或KMIP伺服器無法使用電源、您仍可立即防止存取FIPS磁碟機或SED。 
---
= 緊急銷毀FIPS磁碟機或SED上的資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
發生安全性緊急情況時、即使儲存系統或KMIP伺服器無法使用電源、您仍可立即防止存取FIPS磁碟機或SED。

.您需要的產品
* 如果您使用的KMIP伺服器沒有可用的電源、則KMIP伺服器必須設定容易銷毀的驗證項目（例如智慧卡或USB磁碟機）。
* 您必須是叢集管理員才能執行此工作。


.步驟
. 緊急銷毀FIPS磁碟機或SED上的資料：
+
|===


| 如果... 2+| 然後... 


 a| 
儲存系統可提供電力、您也有時間讓儲存系統正常離線
 a| 
.. 如果儲存系統設定為HA配對、請停用接管功能。
.. 使所有集合體離線並加以刪除。
.. 將權限層級設為進階：
 +
`set -privilege advanced`
.. 如果磁碟機處於FIPS相容模式、請將節點的FIPS驗證金鑰ID設回預設MSID：
 +
`storage encryption disk modify -disk * -fips-key-id 0x0`
.. 停止儲存系統。
.. 開機進入維護模式。
.. 清理或銷毀磁碟：
+
*** 如果您想讓磁碟上的資料無法存取、但仍能重複使用磁碟、請清理磁碟：
 +
`disk encrypt sanitize -all`
*** 如果您想讓磁碟上的資料無法存取、而且不需要儲存磁碟、請銷毀磁碟：
 +
`disk encrypt destroy disk_id1 disk_id2 …`


+
[NOTE]
====
。 `disk encrypt sanitize` 和 `disk encrypt destroy` 命令僅保留用於維護模式。這些命令必須在每個HA節點上執行、而且無法用於中斷的磁碟。

====
.. 針對合作夥伴節點重複這些步驟。
如此一來、儲存系統就會處於永久停用狀態、並清除所有資料。若要再次使用系統、您必須重新設定。




 a| 
儲存系統可提供電力、您必須立即切斷資料
 a| 
.. *如果您想要使磁碟上的資料無法存取且仍能重複使用磁碟、請清理磁碟：*
.. 如果儲存系統設定為HA配對、請停用接管功能。
.. 將權限層級設為進階：
+
`set -privilege advanced`

.. 如果磁碟機處於FIPS相容模式、請將節點的FIPS驗證金鑰ID設回預設MSID：
+
`storage encryption disk modify -disk * -fips-key-id 0x0`

.. 清理磁碟：
+
`storage encryption disk sanitize -disk * -force-all-states true`


 a| 
.. *如果您想要使磁碟上的資料無法存取、而且不需要儲存磁碟、請銷毀磁碟：*
.. 如果儲存系統設定為HA配對、請停用接管功能。
.. 將權限層級設為進階：
+
`set -privilege advanced`

.. 銷毀磁碟：
`storage encryption disk destroy -disk * -force-all-states true`




 a| 
儲存系統會出現問題、使系統處於永久停用狀態、並清除所有資料。若要再次使用系統、您必須重新設定。



 a| 
KMIP伺服器可供電、但儲存系統無法供電
 a| 
.. 登入 KMIP 伺服器。
.. 銷毀與FIPS磁碟機或SED相關的所有金鑰、這些金鑰包含您要防止存取的資料。
如此可防止儲存系統存取磁碟加密金鑰。




 a| 
KMIP伺服器或儲存系統無法使用電源
 a| 
銷毀KMIP伺服器的驗證項目（例如智慧卡）。如此可防止儲存系統存取磁碟加密金鑰。

|===
+
如需完整的命令語法、請參閱手冊頁。


