---
permalink: encryption-at-rest/enable-cluster-fips-compliant-mode-task.html 
sidebar: sidebar 
keywords: enabling, cluster-wide, fips-compliant mode, kmip, server, connections 
summary: 您可以使用安全性組態修改命令搭配啟用-is FIPS的選項、為傳輸中的資料啟用全叢集FIPS相容模式。如此會強制叢集在連接KMIP伺服器時、以FIPS模式使用OpenSSL。 
---
= 為KMIP伺服器連線啟用全叢集FIPS相容模式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「安全性組態修改」命令搭配「啟用FIPS的」選項、為傳輸中的資料啟用全叢集FIPS相容模式。如此會強制叢集在連接KMIP伺服器時、以FIPS模式使用OpenSSL。

.開始之前
* 儲存控制器必須設定為FIPS相容模式。
* 所有KMIP伺服器都必須支援TLSv1.2。啟用叢集範圍FIPS相容模式時、系統需要TLSv1.2才能完成KMIP伺服器的連線。


當您啟用全叢集FIPS相容模式時、叢集將只自動使用TLS1.2和FIPS驗證的密碼套件。預設會停用全叢集FIPS相容模式。

您必須在修改整個叢集的安全性組態之後、手動重新開機叢集節點。



== 零點9.11.1RC1考量ONTAP

由於修訂版9.11.1RC1、FIPS 140-2法規遵循管理模式不再使用FIPS 140-2驗證的軟體模組。ONTAP

適用於HTTPS的管理與控制面板連線的OpenSSL版本升級為《The OpenSSL version for Management and Control Plane connections for HTTPS（ONTAP此版本的OpenSSL（OpenSSL 3.x FIPS Provider）尚未完成FIPS 140-2密碼模組驗證方案（CMVP）驗證程序。

啟用FIPS相容模式時、用於HTTPS連線的加密演算法會與在密碼編譯演算法驗證方案（CA1938）憑證中發行的OpenSSL Project OpenSSL 3.x FIPS Provider演算法相同。*此變更僅影響ONTAP FIPS相容模式下設定的所有系統。*

一旦更新版的OpenSSL模組ONTAP 在更新版的更新版本中、完成FIPS 140-2與NIST的驗證、就能解決此問題。如果您的環境需要ONTAP 以FIPS 140-2 CMVP驗證模組執行叢集管理控制面板、則建議您不要升級至9.11.1RC1。

這並不會影響NetApp在REST時的加密技術、例如NSE、NVE和NAE、因為這些功能使用的密碼編譯模組與在ONTAP 還原中由OpenSSL提供的模組不同。

如需詳細資訊、請參閱 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Upgrading_to_ONTAP_9.11.1RC1_results_in_FIPS_140-2_compliance_management_configuration_that_is_not_validated["升級ONTAP 至RC1RC1會產生FIPS 140-2法規遵循管理組態、但尚未驗證"^]

.步驟
. 將權限層級設為進階：
+
"進階權限"

. 驗證是否支援TLSv1.2：
+
「安全性組態顯示支援的傳輸協定」

+
如需完整的命令語法、請參閱手冊頁。

+
[listing]
----
cluster1::> security config show
          Cluster                                              Cluster Security
Interface FIPS Mode  Supported Protocols     Supported Ciphers Config Ready
--------- ---------- ----------------------- ----------------- ----------------
SSL       false      TLSv1.2, TLSv1.1, TLSv1 ALL:!LOW:         yes
                                             !aNULL:!EXP:
                                             !eNULL
----
. 啟用全叢集FIPS相容模式：
+
「安全性組態修改-is：啟用FIPS的真介面SSL」

+
如需完整的命令語法、請參閱手冊頁。

. 手動重新啟動叢集節點。
. 確認已啟用全叢集FIPS相容模式：
+
「安全組態顯示」

+
[listing]
----
cluster1::> security config show
          Cluster                                              Cluster Security
Interface FIPS Mode  Supported Protocols     Supported Ciphers Config Ready
--------- ---------- ----------------------- ----------------- ----------------
SSL       true       TLSv1.2, TLSv1.1        ALL:!LOW:         yes
                                             !aNULL:!EXP:
                                             !eNULL:!RC4
----

