---
permalink: encryption-at-rest/enable-encryption-existing-volume-93-later-task.html 
sidebar: sidebar 
keywords: enabling, encryption, existing, volume encryption conversion start, command 
summary: 從ONTAP 功能介紹9.3開始、您可以使用Volume Encryption Conversion start命令來「就地」加密現有磁碟區、而不需要將磁碟區移到其他位置。 
---
= 使用Volume Encryption Conversion start命令、在現有磁碟區上啟用加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從功能介紹9.3開始ONTAP 、您可以使用「Volume Encryption Conversion start」命令來「原地」加密現有的Volume、而不需要將磁碟區移到其他位置。

一旦開始轉換作業、就必須完成。如果您在作業期間遇到效能問題、可以執行「Volume Encryption Conversion Pause」命令來暫停作業、然後執行「Volume Encryption Conversion resume」命令來恢復作業。

[NOTE]
====
您無法使用「Volume加密轉換開始」來轉換SnapLock 一個現象。

====
.步驟
. 在現有磁碟區上啟用加密：
+
「Volume加密轉換開始於-vserver Svm_name -volume volume volume volume名稱」

+
如需完整的命令語法、請參閱命令的手冊頁。

+
下列命令可在現有磁碟區「vol1」上啟用加密：

+
[listing]
----
cluster1::> volume encryption conversion start -vserver vs1 -volume vol1
----
+
系統會為磁碟區建立加密金鑰。磁碟區上的資料已加密。

. 確認轉換作業的狀態：
+
「Volume加密轉換顯示」

+
如需完整的命令語法、請參閱命令的手冊頁。

+
下列命令會顯示轉換作業的狀態：

+
[listing]
----
cluster1::> volume encryption conversion show

Vserver   Volume   Start Time           Status
-------   ------   ------------------   ---------------------------
vs1       vol1     9/18/2017 17:51:41   Phase 2 of 2 is in progress.
----
. 完成轉換作業後、請確認磁碟區已啟用加密：
+
「Volume show -is加密true」

+
如需完整的命令語法、請參閱命令的手冊頁。

+
下列命令會顯示「cluster1」上的加密磁碟區：

+
[listing]
----
cluster1::> volume show -is-encrypted true

Vserver  Volume  Aggregate  State  Type  Size  Available  Used
-------  ------  ---------  -----  ----  -----  --------- ----
vs1      vol1    aggr2     online    RW  200GB    160.0GB  20%
----


如果您使用KMIP伺服器來儲存節點的加密金鑰、ONTAP 則當您加密磁碟區時、會自動將加密金鑰「推送」至伺服器。
