---
permalink: encryption-at-rest/enable-encryption-new-volume-task.html 
sidebar: sidebar 
keywords: encryption, new volume, NAE, NVE, volume create 
summary: 您可以使用volume create命令、在新的Volume上啟用加密功能。 
---
= 在 ONTAP 的新磁碟區上啟用加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `volume create` 在新磁碟區上啟用加密的命令。

.關於這項工作
您可以使用NetApp Volume Encryption（NVE）加密磁碟區、從ONTAP NetApp Aggregate Encryption（NAE）開始加密磁碟區。若要深入瞭解NAE和NVE、請參閱 xref:configure-netapp-volume-encryption-concept.html[Volume加密總覽]。

如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。

啟用更新版本的加密程序ONTAP 會因ONTAP 您使用的版本和您的特定組態而有所不同：

* 如果ONTAP 啟用、請從支援的問題9.4開始 `cc-mode` 設定Onboard Key Manager時、您可以使用建立的磁碟區 `volume create` 無論您是否指定、命令都會自動加密 `-encrypt true`。
* 在更新版本的版本中、您必須使用ONTAP `-encrypt true` 與 `volume create` 啟用加密的命令（前提是您未啟用 `cc-mode`）。
* 如果您想要在ONTAP 32位址9.6中建立NAE Volume、則必須在Aggregate層級啟用NAE。請參閱 xref:enable-aggregate-level-encryption-nve-license-task.html[使用VE授權啟用Aggregate層級加密] 以取得此工作的詳細資料。
* 從 ONTAP 9 7 開始link:../encryption-at-rest/install-license-task.html["VE 授權"]、新建立的磁碟區會在您擁有和內建或外部金鑰管理時、依預設進行加密。根據預設、在NAE Aggregate中建立的新磁碟區將為NAE類型、而非NVE。
+
** 如有新增、請參閱ONTAP 更新版本的 `-encrypt true` 至 `volume create` 命令若要在NAE Aggregate中建立磁碟區、該磁碟區將採用NVE加密、而非NAE。NAE Aggregate中的所有磁碟區都必須使用NVE或NAE進行加密。





NOTE: NAE集合體不支援純文字磁碟區。

.步驟
. 建立新磁碟區、並指定是否在磁碟區上啟用加密。如果新磁碟區位於NAE Aggregate中、則根據預設、該磁碟區將是NAE磁碟區：
+
[cols="25,75"]
|===


| 若要建立... | 使用此命令... 


 a| 
NAE Volume
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_`



 a| 
NVE Volume
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt true` +


NOTE: 在不支援NAE的情況下、使用支援的版本為ONTAP `-encrypt true` 指定應使用NVE加密磁碟區。在以NAE集合體建立Volume的版本中ONTAP 、 `-encrypt true` 取代預設的NAE加密類型、改為建立NVE Volume。



 a| 
純文字Volume
 a| 
`volume create -vserver _SVM_name_ -volume _volume_name_ -aggregate _aggregate_name_ -encrypt false`

|===
+
如link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["指令參考資料ONTAP"^]需詳細 `volume create`資訊，請參閱。

. 確認已啟用磁碟區進行加密：
+
`volume show -is-encrypted true`

+
如link:https://docs.netapp.com/us-en/ontap-cli/volume-show.html["指令參考資料ONTAP"^]需詳細 `volume show`資訊，請參閱。



.結果
如果您使用KMIP伺服器來儲存節點的加密金鑰、ONTAP 則當您加密磁碟區時、會自動將加密金鑰「推送」至伺服器。
