---
permalink: encryption-at-rest/enable-onboard-key-management-96-later-nve-task.html 
sidebar: sidebar 
keywords: enabling, onboard key management, ontap 9.6, later, nve 
summary: 您可以使用Onboard Key Manager來保護叢集用來存取加密資料的金鑰。您必須在每個存取加密磁碟區或自我加密磁碟的叢集上啟用Onboard Key Manager。 
---
= 啟用ONTAP 更新版本（NVE）的內建金鑰管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Onboard Key Manager來保護叢集用來存取加密資料的金鑰。您必須在存取加密磁碟區或自我加密磁碟的每個叢集上啟用 Onboard Key Manager 。

.您需要的產品
* 您必須是叢集管理員才能執行此工作。
* 在設定Onboard Key Manager之前、您必須先設定MetroCluster 這個靜態環境。


.關於這項工作
每次將節點新增至叢集時、您都必須執行「安全金鑰管理程式內建同步」命令。

如果您有 MetroCluster 組態、則必須執行 `security key-manager onboard enable` 先在本機叢集上執行 `security key-manager onboard sync` 在遠端叢集上、使用相同的複雜密碼。

根據預設、當節點重新開機時、您不需要輸入金鑰管理程式密碼。您可以使用「cc-mode-enable=yes」選項、要求使用者在重新開機後輸入通關密碼。

對於NVE、如果您設定「cc-mode-enabled=yes」、則使用「volume create」和「volume move start」命令所建立的磁碟區會自動加密。對於「Volume create」、您不需要指定「-加密true」。對於「Volume Move start」（磁碟區移動開始）、您不需要指定「-加密-目的地true」。

設定ONTAP 靜止資料加密時、若要符合商業分類解決方案（CSfC）的要求、您必須搭配NVE使用NSE、並確保在「一般條件」模式中啟用「內建金鑰管理程式」。請參閱 link:https://assets.netapp.com/m/128a1e9f4b5d663/original/Commercial-Solutions-for-Classified.pdf["CSfC解決方案簡介"^] 如需CSfC的詳細資訊、

[NOTE]
====
在「Common Criteria（一般條件）」模式中啟用「Onboard Key Manager（機載金鑰管理程式）」（「cc-mode enabled=yes（啟用cc-mode-enable=yes）」）時、系統行為會以下列方式變更：

* 系統會監控在「一般準則」模式下運作時、連續嘗試失敗的叢集密碼。
+
如果您在開機時未輸入正確的叢集密碼、則不會掛載加密的磁碟區。若要修正此問題、您必須重新啟動節點、然後輸入正確的叢集密碼。一旦開機、系統最多可連續5次嘗試在24小時內、針對任何需要叢集密碼作為參數的命令、正確輸入叢集密碼。如果達到限制（例如、您連續5次未正確輸入叢集密碼）、則必須等待24小時逾時期間、或是重新啟動節點、才能重設限制。

* 系統映像更新會使用NetApp RSA-3072程式碼簽署憑證搭配SHA-384程式碼簽署摘要、來檢查映像完整性、而非一般的NetApp RSA-2048程式碼簽署憑證和SHA-256程式碼簽署摘要。
+
升級命令會檢查各種數位簽章、以確認映像內容未遭竄改或毀損。如果驗證成功、映像更新程序會繼續下一步；否則映像更新會失敗。請參閱「叢集映像」手冊頁、以取得系統更新的相關資訊。



====
[NOTE]
====
Onboard Key Manager可將金鑰儲存在揮發性記憶體中。當系統重新開機或停止時、揮發性記憶體內容會被清除。在正常操作條件下、系統停止時、揮發性記憶體內容將在30秒內清除。

====
.步驟
. 啟動金鑰管理程式設定：
+
「安全金鑰管理程式已內建啟用-cc-mode啟用yes | no」

+
[NOTE]
====
設定「cc-mode-enable=yes」、要求使用者在重新開機後輸入金鑰管理程式密碼。對於NVE、如果您設定「cc-mode-enabled=yes」、則使用「volume create」和「volume move start」命令所建立的磁碟區會自動加密。支援cc-mode-enabled的選項MetroCluster 不支援在各種組態中。「安全金鑰管理程式內建啟用」命令取代了「安全金鑰管理程式設定」命令。

====
+
下列範例會在叢集1上啟動金鑰管理程式設定命令、而不要求在每次重新開機後輸入通關密碼：

+
[listing]
----
cluster1::> security key-manager onboard enable

Enter the cluster-wide passphrase for onboard key management in Vserver "cluster1"::    <32..256 ASCII characters long text>
Reenter the cluster-wide passphrase:    <32..256 ASCII characters long text>
----
. 在通關密碼提示字元中、輸入32到256個字元之間的通關密碼、或輸入「'cc-mode'」（64到256個字元之間的通關密碼）。
+
[NOTE]
====
如果指定的"'cc-mode"通關密碼少於64個字元、則在金鑰管理程式設定作業再次顯示通關密碼提示之前、會有五秒鐘的延遲。

====
. 在通關密碼確認提示下、重新輸入通關密碼。
. 確認已建立驗證金鑰：
+
「安全金鑰管理程式金鑰查詢-金鑰類型NSE-AK」

+
[NOTE]
====
「安全金鑰管理程式金鑰查詢」命令會取代「安全金鑰管理程式查詢金鑰」命令。如需完整的命令語法、請參閱手冊頁。

====
+
下列範例可驗證是否已為「cluster1（叢集1）”建立驗證金鑰：

+
[listing]
----
cluster1::> security key-manager key query -key-type NSE-AK
               Node: node1
            Vserver: cluster1
        Key Manager: onboard
   Key Manager Type: OKM
 Key Manager Policy: -

 Key Tag                               Key Type Encryption   Restored

------------------------------------  -------- ------------ --------

node1                                 NSE-AK   AES-256      true

    Key ID: 00000000000000000200000000000100056178fc6ace6d91472df8a9286daacc0000000000000000

node1                                 NSE-AK   AES-256      true

    Key ID: 00000000000000000200000000000100df1689a148fdfbf9c2b198ef974d0baa0000000000000000

2 entries were displayed.
----
. 也可以將純文字磁碟區轉換為加密磁碟區。
+
`volume encryption conversion start`

+
在轉換磁碟區之前、必須先完整設定 Onboard Key Manager 。在 MetroCluster 環境中、兩個站台都必須設定內建金鑰管理員。



.完成後
將通關密碼複製到儲存系統外部的安全位置、以供未來使用。

每當您設定Onboard Key Manager複雜密碼時、也應該手動將資訊備份到儲存系統外部的安全位置、以便在發生災難時使用。請參閱 link:backup-key-management-information-manual-task.html["手動備份內建金鑰管理資訊"]。
