---
permalink: encryption-at-rest/enable-onboard-key-management-new-nodes-concept.html 
sidebar: sidebar 
keywords: onboard key management, onboard new nodes, okm, encrypt 
summary: 您可以使用Onboard Key Manager來保護叢集用來存取加密資料的金鑰。您必須在每個存取加密磁碟區或自我加密磁碟的叢集上啟用Onboard Key Manager。 
---
= 在新新增的ONTAP節點中啟用板載金鑰管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用Onboard Key Manager來保護叢集用來存取加密資料的金鑰。您必須在每個存取加密磁碟區或自我加密磁碟的叢集上啟用Onboard Key Manager。

[NOTE]
====
對於ONTAP 9.6 及更高版本，您必須執行 `security key-manager onboard sync` 每次向叢集新增節點時執行此命令。

若為 ONTAP 9.5 或更早版本、您必須執行 `security key-manager setup` 每次將節點新增至叢集時的命令。

如果您將節點新增至具有板載金鑰管理的集群，請執行此命令來刷新遺失的金鑰。

====
如果您使用MetroCluster 的是「不確定」組態、請參閱下列準則：

* 從 ONTAP 9.6 開始、您必須執行 `security key-manager onboard enable` 先在本機叢集上執行 `security key-manager onboard sync` 在遠端叢集上、使用相同的複雜密碼。
+
深入瞭解 `security key-manager onboard enable`及 `security key-manager onboard sync` link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+key-manager+onboard["指令參考資料ONTAP"^]。

* 在 ONTAP 9.5 中、您必須執行 `security key-manager setup` 在本機叢集和上 `security key-manager setup -sync-metrocluster-config yes` 在遠端叢集上、使用相同的複雜密碼。
* 在 ONTAP 9.5 之前、您必須執行 `security key-manager setup` 在本機叢集上、等待大約 20 秒、然後執行 `security key-manager setup` 在遠端叢集上、使用相同的複雜密碼。


根據預設、當節點重新開機時、您不需要輸入金鑰管理程式密碼。從 ONTAP 9.4 開始、您可以使用 `-enable-cc-mode yes` 選項要求使用者在重新開機後輸入複雜密碼。

如果您已設定、則適用於 NVE `-enable-cc-mode yes`、您使用建立的磁碟區 `volume create` 和 `volume move start` 命令會自動加密。適用於 `volume create`，您不需要指定 `-encrypt true`。適用於 `volume move start`，您不需要指定 `-encrypt-destination true`。

[NOTE]
====
如果密碼嘗試失敗，請重新啟動節點。重新啟動後，您可以再次嘗試輸入密碼。

====
.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=cluster+image["叢集影像命令"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-external-enable.html["安全金鑰管理員外部啟用"^]
* link:https://docs.netapp.com/us-en/ontap-cli//security-key-manager-onboard-enable.html["安全金鑰管理員板載啟用"^]

