---
permalink: encryption-at-rest/enable-external-key-management-96-later-nve-task.html 
sidebar: sidebar 
keywords: enabling, external key management, ontap 9.6, later, nve 
summary: 您可以使用一或多個KMIP伺服器來保護叢集用來存取加密資料的金鑰。從ONTAP Sesk9.6開始、您可以使用一或多個KMIP伺服器來保護特定SVM用來存取加密資料的金鑰。 
---
= 在ONTAP 支援外部金鑰管理的過程中、於支援內部金鑰管理功能的版本（NVE）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用一或多個KMIP伺服器來保護叢集用來存取加密資料的金鑰。從ONTAP Sesk9.6開始、您可以使用一或多個KMIP伺服器來保護特定SVM用來存取加密資料的金鑰。

.您需要的是 #8217 ；需要的是什麼
* KMIP SSL用戶端和伺服器憑證必須已安裝。
* 您必須是叢集或SVM管理員、才能執行此工作。
* 如果您想要啟用MetroCluster 外部金鑰管理功能來管理整個環境、MetroCluster 則必須先完整設定好、才能啟用外部金鑰管理。


您最多可將四個KMIP伺服器連線至叢集或SVM。建議至少使用兩部伺服器來進行備援和災難恢復。

外部金鑰管理的範圍決定了金鑰管理伺服器是保護叢集中的所有SVM、還是僅保護選取的SVM：

* 您可以使用_叢集範圍_來設定叢集中所有SVM的外部金鑰管理。叢集管理員可以存取儲存在伺服器上的每個金鑰。
* 從ONTAP 功能表9.6開始、您可以使用_SVM範圍來設定叢集中資料SVM的外部金鑰管理。這最適合多租戶環境、每個租戶使用不同的SVM（或一組SVM）來提供資料。只有特定租戶的SVM管理員可以存取該租戶的金鑰。
* 對於多租戶環境、請使用下列命令安裝_MT_EK-Mgmt_的授權：
+
「系統授權新增授權代碼<MT_EK-Mgmt授權代碼>」

+
如需完整的命令語法、請參閱命令的手冊頁。



您可以在同一個叢集中使用這兩個範圍。如果SVM已設定金鑰管理伺服器、ONTAP 則僅使用這些伺服器來保護金鑰。否則ONTAP 、利用為叢集設定的金鑰管理伺服器來保護金鑰。

您可以在叢集範圍設定內建金鑰管理、並在SVM範圍設定外部金鑰管理。您可以使用「安全金鑰管理程式金鑰移轉」命令、將金鑰從叢集範圍內的內建金鑰管理移轉至SVM範圍內的外部金鑰管理程式。

.步驟
. 設定叢集的金鑰管理程式連線：
+
「安全金鑰管理程式外部啟用-vserver admin_SVM -key-servers host_name | ip_address:連接埠、... -client-cert client_Certificate -server_cert server_ca_certificates

+
[NOTE]
====
「安全金鑰管理程式外部啟用」命令取代了「安全金鑰管理程式設定」命令。如果您在叢集登入提示字元中執行命令、則預設為目前叢集的管理SVM。您必須是叢集管理員、才能設定叢集範圍。您可以執行「安全金鑰管理程式外部修改」命令來變更外部金鑰管理組態。

====
+
下列命令可在三個外部金鑰伺服器上、為「cluster1」啟用外部金鑰管理。第一個金鑰伺服器是使用其主機名稱和連接埠來指定、第二個金鑰伺服器是使用IP位址和預設連接埠來指定、第三個金鑰伺服器則是使用IPv6位址和連接埠來指定：

+
[listing]
----
clusterl::> security key-manager external enable -vserver cluster1 -key-servers ks1.local:15696,10.0.0.10,[fd20:8b1e:b255:814e:32bd:f35c:832c:5a09]:1234 -client-cert AdminVserverClientCert -server-ca-certs AdminVserverServerCaCert
----
. 設定SVM的金鑰管理程式：
+
「安全金鑰管理程式外部啟用-vserver SVM -key-servers host_name | ip_address:連接埠、... -client-cert client_Certificate -server_cert server_ca_certificates

+
[NOTE]
====
如果您在SVM登入提示字元中執行命令、則「VM」預設為目前的SVM。您必須是叢集或SVM管理員、才能設定SVM範圍。您可以執行「安全金鑰管理程式外部修改」命令來變更外部金鑰管理組態。

====
+
下列命令可在預設連接埠5696上偵聽單一金鑰伺服器、為「vm1」啟用外部金鑰管理：

+
[listing]
----
svm1l::> security key-manager external enable -vserver svm1 -key-servers keyserver.svm1.com -client-cert SVM1ClientCert -server-ca-certs SVM1ServerCaCert
----
. 針對任何其他SVM重複最後一個步驟。
+
[NOTE]
====
您也可以使用「安全金鑰管理程式外部附加伺服器」命令來設定其他SVM。「安全金鑰管理程式外部附加伺服器」命令取代了「安全金鑰管理程式附加」命令。如需完整的命令語法、請參閱手冊頁。

====
. 確認所有已設定的KMIP伺服器均已連線：
+
「安全金鑰管理程式外部顯示狀態-node_name」

+
[NOTE]
====
Check Alignment of PHs>安全密鑰管理器external show-STATUS'命令取代了"安全 密鑰管理器show -STATUS"命令。如需完整的命令語法、請參閱手冊頁。

====
+
[listing]
----
cluster1::> security key-manager external show-status

Node  Vserver  Key Server                                     Status
----  -------  ---------------------------------------        -------------
node1
      svm1
               keyserver.svm1.com:5696                        available
      cluster1
               10.0.0.10:5696                                 available
               fd20:8b1e:b255:814e:32bd:f35c:832c:5a09:1234   available
               ks1.local:15696                                available
node2
      svm1
               keyserver.svm1.com:5696                        available
      cluster1
               10.0.0.10:5696                                 available
               fd20:8b1e:b255:814e:32bd:f35c:832c:5a09:1234   available
               ks1.local:15696                                available

8 entries were displayed.
----

