---
permalink: encryption-at-rest/key-management-servers-not-reachable-boot-concept.html 
sidebar: sidebar 
keywords: what, happens, key management servers, not reachable, boot, process 
summary: 在開機期間、若為NSE設定的儲存系統無法觸及任何指定的金鑰管理伺服器、則執行某些預防措施以避免不必要的行為。ONTAP 
---
= 在開機程序期間無法連線到金鑰管理伺服器時會發生什麼情況
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在開機期間、若為NSE設定的儲存系統無法觸及任何指定的金鑰管理伺服器、則執行某些預防措施以避免不必要的行為。ONTAP

如果儲存系統已設定為使用NSE、系統會重新鎖定SED、並開啟SED電源、則儲存系統必須從金鑰管理伺服器擷取所需的驗證金鑰、以驗證自己是否能存取資料。

儲存系統會嘗試聯絡指定的金鑰管理伺服器、最多三小時。如果之後儲存系統仍無法連絡到任何儲存系統、則開機程序會停止、儲存系統也會停止。

如果儲存系統成功連絡任何指定的金鑰管理伺服器、則會嘗試建立長達15分鐘的SSL連線。如果儲存系統無法與任何指定的金鑰管理伺服器建立SSL連線、開機程序會停止、儲存系統也會停止。

當儲存系統嘗試聯絡並連線至主要管理伺服器時、會在CLI中顯示失敗聯絡嘗試的詳細資訊。您可以隨時按Ctrl-C中斷聯絡活動嘗試

為了安全起見、SED僅允許有限數量的未授權存取嘗試、之後會停用對現有資料的存取。如果儲存系統無法連絡任何指定的金鑰管理伺服器以取得適當的驗證金鑰、則只能嘗試使用預設金鑰進行驗證、導致嘗試失敗並造成恐慌。如果儲存系統設定為在發生緊急情況時自動重新開機、則會進入開機迴圈、導致SED持續嘗試驗證失敗。

在這些情況下停止儲存系統的設計、是為了防止儲存系統進入開機迴圈、以及可能因超過某個連續驗證嘗試失敗次數的安全限制而永久鎖定的SED而導致意外的資料遺失。鎖定保護的限制和類型取決於製造規格和SED類型：

[cols="30,15,55"]
|===


| SED類型 | 導致鎖定的連續驗證嘗試失敗次數 | 達到安全限制時的鎖定保護類型 


 a| 
HDD
 a| 
1024.
 a| 
永久。即使適當的驗證金鑰再次可用、也無法還原資料。



 a| 
X440_PHM2800MCTO 800GB NSE SSD搭配韌體版本NA00或NA01
 a| 
5.
 a| 
暫時性。鎖定功能只會在磁碟重新開機之前生效。



 a| 
具有韌體版本NA00或NA01的X577_PHM2800MCTO 800GB NSE SSD
 a| 
5.
 a| 
暫時性。鎖定功能只會在磁碟重新開機之前生效。



 a| 
X440_PHM2800MCTO 800GB NSE SSD、韌體版本更高
 a| 
1024.
 a| 
永久。即使適當的驗證金鑰再次可用、也無法還原資料。



 a| 
具有較高韌體版本的X577_PHM2800MCTO 800GB NSE SSD
 a| 
1024.
 a| 
永久。即使適當的驗證金鑰再次可用、也無法還原資料。



 a| 
所有其他SSD機型
 a| 
1024.
 a| 
永久。即使適當的驗證金鑰再次可用、也無法還原資料。

|===
對於所有SED類型、成功驗證會將試用數重設為零。

如果您遇到儲存系統因為無法連線至任何指定的金鑰管理伺服器而停止運作的情況、則必須先識別並修正通訊故障的原因、然後再嘗試繼續開機儲存系統。
