---
permalink: encryption-at-rest/purge-data-encrypted-volume-synchronous-snapmirror-task.html 
sidebar: sidebar 
keywords: secure, purge, scrub, data, encrypted, volume, nve, netapp, volume encryption, snapmirror, synchronous 
summary: 從ONTAP 9.8 開始，您可以使用安全清除功能以無中斷方式清理具有SnapMirror同步關係的啟用 NVE 的磁碟區上的資料。 
---
= 從具有SnapMirror同步關係的加密ONTAP磁碟區中清理數據
:allow-uri-read: 


[role="lead"]
從 ONTAP 9 8 開始、您可以使用安全清除功能、在具有 SnapMirror 同步關係的 NVE 磁碟區上、不中斷地「清理」資料。

.關於這項工作
視刪除檔案中的資料量而定、安全清除可能需要數分鐘到數小時才能完成。您可以使用 `volume encryption secure-purge show` 檢視作業狀態的命令。您可以使用 `volume encryption secure-purge abort` 命令以終止作業。


NOTE: 若要在SAN主機上執行安全清除、您必須刪除包含您要清除之檔案的整個LUN、或者您必須能夠在LUN上為屬於您要清除之檔案的區塊鑽孔。如果您無法刪除LUN或主機作業系統不支援在LUN上打孔、則無法執行安全清除。

.開始之前
* 您必須是叢集管理員才能執行此工作。
* 此工作需要進階權限。


.步驟
. 在儲存系統上、變更為進階權限層級：
+
`set -privilege advanced`

. 刪除您要安全清除的檔案或LUN。
+
** 在NAS用戶端上、刪除您要安全清除的檔案。
** 在SAN主機上、針對屬於您要清除之檔案的區塊、刪除您要安全清除LUN上的LUN或在LUN上鑽孔。


. 在非同步關係中準備好要安全清除的目的地Volume：
+
`volume encryption secure-purge start -vserver <SVM_name> -volume <volume_name> -prepare true`

+
針對 SnapMirror 同步關係中的其他磁碟區重複此步驟。

. 如果您要安全清除的檔案位於快照中、請刪除快照：
+
`snapshot delete -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot>`

. 如果安全清除檔案位於基礎快照或一般快照中，請更新 SnapMirror 以將一般快照向前移：
+
`snapmirror update -source-snapshot <snapshot_name> -destination-path <destination_path>`

+
共有兩個常用快照，因此必須發出兩次此命令。

. 如果安全清除檔案位於應用程式一致的快照中，請刪除 SnapMirror 同步關係中兩個磁碟區上的快照：
+
`snapshot delete -vserver <SVM_name> -volume <volume_name> -snapshot <snapshot>`

+
在兩個磁碟區上執行此步驟。

. 安全地清除刪除的檔案：
+
`volume encryption secure-purge start -vserver <SVM_name> -volume <volume_name>`

+
在 SnapMirror 同步關係中的每個磁碟區上重複此步驟。

+
下列命令可安全清除SVM「'VS1'」上「'vol1'」上的刪除檔案。

+
[listing]
----
cluster1::> volume encryption secure-purge start -vserver vs1 -volume vol1
----
. 確認安全清除作業的狀態：
+
`volume encryption secure-purge show`



.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["SnapMirror 更新"^]

