---
permalink: encryption-at-rest/restore-onboard-key-management-encryption-keys-task.html 
sidebar: sidebar 
keywords: restoring, onboard, key management encryption 
summary: 有時候、您可能需要還原內建金鑰管理加密金鑰。一旦您確認需要還原金鑰、就可以設定Onboard Key Manager來還原金鑰。 
---
= 在 ONTAP 中還原內建金鑰管理加密金鑰
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
有時，您可能需要恢復板載金鑰管理加密金鑰。確認需要恢復密鑰後，您可以設定板載密鑰管理器來恢復密鑰。恢復板載金鑰管理加密金鑰所遵循的步驟因ONTAP版本的不同而不同。

.開始之前
* 如果您將 NSE 與外部 KMIP 伺服器一起使用，請刪除外部金鑰管理員資料庫。有關詳細信息，請參閱link:delete-key-management-database-task.html["從外部金鑰管理過渡到ONTAP板載金鑰管理"]。
* 您必須是叢集管理員才能執行此工作。



NOTE: 如果您在具有 Flash Cache 模組的系統上使用 NSE 、您也應該啟用 NVE 或 NAE 。NSE 不會加密位於 Flash Cache 模組上的資料。



== 更新版本ONTAP


IMPORTANT: 如果您執行的是 ONTAP 9.8 或更新版本、而且根磁碟區已加密、請遵循的程序 <<ontap-9-8>>。

. 確認金鑰需要還原： +
`security key-manager key query -node _node_`
+
如link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-query.html["指令參考資料ONTAP"^]需詳細 `security key-manager key query`資訊，請參閱。

. 還原金鑰： +
`security key-manager onboard sync`
+
如link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-onboard-sync.html["指令參考資料ONTAP"^]需詳細 `security key-manager onboard sync`資訊，請參閱。

. 在通關密碼提示字元下、輸入叢集的內建金鑰管理通關密碼。




== ONTAP 9.8 或更新版本、含加密的根磁碟區

如果您執行ONTAP 的是更新版本的版本、而且根磁碟區已加密、則必須使用開機功能表設定內建金鑰管理還原密碼。如果您要更換開機媒體、也必須執行此程序。

. 將節點開機至開機功能表、然後選取選項 `(10) Set onboard key management recovery secrets`。
. 輸入 `y` 以使用此選項。
. 出現提示時、輸入叢集的內建金鑰管理通關密碼。
. 出現提示時、輸入備份金鑰資料。
+
輸入備份金鑰資料後，節點返回啟動選單。

. 從開機功能表中、選取選項 `(1) Normal Boot`。




== 不含更新版本ONTAP

. 確認金鑰需要還原： +
`security key-manager key show`
. 還原金鑰： +
`security key-manager setup -node _node_`
+
詳細了解 `security key-manager setup`在link:https://docs.netapp.com/us-en/ontap-cli-9161/security-key-manager-setup.html["指令參考資料ONTAP"^]。

. 在通關密碼提示字元下、輸入叢集的內建金鑰管理通關密碼。

