---
permalink: encryption-at-rest/restore-external-encryption-keys-93-later-task.html 
sidebar: sidebar 
keywords: restoring, external key management, encryption keys 
summary: 您可以手動還原外部金鑰管理加密金鑰、並將其「推送」至不同的節點。如果您重新啟動的節點在建立叢集的金鑰時暫時停機、您可能會想要這麼做。 
---
= 還原外部金鑰管理加密金鑰
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以手動還原外部金鑰管理加密金鑰、並將其推送到不同的節點。如果您重新啟動的節點在建立叢集的金鑰時暫時停機、您可能會想要這麼做。

.關於這項工作
在 ONTAP 9.6 及更新版本中、您可以使用 `security key-manager key query -node node_name` 命令以驗證金鑰是否需要還原。

在 ONTAP 9.5 或更早版本中、您可以使用 `security key-manager key show` 命令以驗證金鑰是否需要還原。


NOTE: 如果您在具有 Flash Cache 模組的系統上使用 NSE 、您也應該啟用 NVE 或 NAE 。NSE 不會加密位於 Flash Cache 模組上的資料。

.開始之前
您必須是叢集或SVM管理員、才能執行此工作。

.步驟
. 如果您執行ONTAP 的是更新版本的版本、且根磁碟區已加密、請執行下列步驟：
+
如果您執行ONTAP 的是更新版本的版本、或是執行ONTAP 的是版本不加密的版本、請跳過此步驟。

+
.. 設定 bootargs ：
 +
`setenv kmip.init.ipaddr <ip-address>`
 +
`setenv kmip.init.netmask <netmask>`
 +
`setenv kmip.init.gateway <gateway>`
 +
`setenv kmip.init.interface e0M`
 +
`boot_ontap`
.. 將節點開機至開機功能表、然後選取選項 `(11) Configure node for external key management`。
.. 依照提示輸入管理憑證。
+
輸入所有管理憑證資訊後、系統會返回開機功能表。

.. 從開機功能表中、選取選項 `(1) Normal Boot`。


. 還原金鑰：
+
[cols="35,65"]
|===


| 此版本... ONTAP | 使用此命令... 


 a| 
更新版本ONTAP
 a| 
`security key-manager external restore -vserver SVM -node node -key-server host_name|IP_address:port -key-id key_id -key-tag key_tag`



 a| 
不含更新版本ONTAP
 a| 
`security key-manager restore -node node -address IP_address -key-id key_id -key-tag key_tag`

|===
+
[NOTE]
====
`node`預設為所有節點。

如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。啟用內建金鑰管理時、不支援此命令。

====
+
下列 ONTAP 9.6 命令可將外部金鑰管理驗證金鑰還原至中的所有節點 `cluster1`：

+
[listing]
----
clusterl::> security key-manager external restore
----

