---
permalink: encryption-at-rest/return-self-encrypting-disks-keys-not-available-task.html 
sidebar: sidebar 
keywords: returning, fips, drive, sed, service, authentication, keys, lost 
summary: 如果您永久遺失FIPS磁碟機或SED的驗證金鑰、而且無法從KMIP伺服器擷取、系統會將其視為中斷。雖然您無法存取或恢復磁碟上的資料、但您可以採取步驟、讓SED的未使用空間再次可供資料使用。 
---
= 當驗證金鑰遺失時、請將FIPS磁碟機或SED送回服務
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您永久遺失FIPS磁碟機或SED的驗證金鑰、而且無法從KMIP伺服器擷取、系統會將其視為中斷。雖然您無法存取或恢復磁碟上的資料、但您可以採取步驟、讓SED的未使用空間再次可供資料使用。

您必須是叢集管理員才能執行此工作。

只有當您確定FIPS磁碟機或SED的驗證金鑰已永久遺失、而且無法還原時、才應使用此程序。

如果磁碟已分割、則必須先取消磁碟分割、才能開始此程序。包括：.//_include/undpartition-disk.ado[]

.步驟
. 將FIPS磁碟機或SED送回服務：
+
[cols="25,75"]
|===


| 如果SED是... | 請使用下列步驟... 


 a| 
未處於FIPS相容模式、或處於FIPS相容模式、且FIPS金鑰可供使用
 a| 
.. 將權限等級設為進階：「et -priv榮幸advanc進 階」
.. 將FIPS金鑰重設為預設製造商安全ID：「torage加密磁碟modify -fIPS-key-id x0 -disk _disk_id_」
.. 驗證作業是否成功：「儲存加密磁碟顯示狀態」如果作業失敗、請使用本主題中的PSID程序。
.. 清理毀損的磁碟：「儲存加密磁碟清理磁碟_disk _id_」繼續下一步之前、請先使用命令「儲存加密磁碟顯示狀態」驗證作業是否成功。
.. 將已消毒的磁碟取消容錯：「torage disk unfail -spare true -disk _disk_id_」
.. 檢查磁碟是否有擁有者：「torage disk show -disk _disk_id_」
.. 如果磁碟沒有擁有者、請指派一個擁有者、然後再次取消磁碟故障：「torage disk assign -OnerNode -disk _disk_id_」（磁碟故障恢復-備用true -disk _disk_id_）
.. 驗證磁碟現在是否為備用磁碟、並準備好在Aggregate中重複使用：「torage disk show -disk _disk_id_」




 a| 
在FIPS相容模式中、FIPS金鑰無法使用、且SED標籤上印有PSID
 a| 
.. 從磁碟標籤取得磁碟的PSID。
.. 將權限等級設為進階：「et -priv榮幸advanc進 階」
.. 將磁碟重設為原廠設定的設定：「磁碟加密磁碟還原為原始狀態-磁碟_disk_id_-PSID _disk_fort_secure_id_」繼續下一步之前、請先使用命令「儲存加密磁碟顯示狀態」驗證作業是否成功。
.. 將已消毒的磁碟取消容錯：「torage disk unfail -spare true -disk _disk_id_」
.. 檢查磁碟是否有擁有者：「torage disk show -disk _disk_id_」
.. 如果磁碟沒有擁有者、請指派一個擁有者、然後再次取消磁碟故障：「torage disk assign -OnerNode -disk _disk_id_」（磁碟故障恢復-備用true -disk _disk_id_）
.. 驗證磁碟現在是否為備用磁碟、並準備好在Aggregate中重複使用：「torage disk show -disk _disk_id_」


|===


如需完整的命令語法、請參閱手冊頁。
