---
permalink: encryption-at-rest/return-self-encrypting-disks-keys-not-available-task.html 
sidebar: sidebar 
keywords: returning, fips, drive, sed, service, authentication, keys, lost 
summary: 如果您永久遺失FIPS磁碟機或SED的驗證金鑰、而且無法從KMIP伺服器擷取、系統會將其視為中斷。雖然您無法存取或恢復磁碟上的資料、但您可以採取步驟、讓SED的未使用空間再次可供資料使用。 
---
= 當驗證金鑰遺失時、請將FIPS磁碟機或SED送回服務
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您永久遺失FIPS磁碟機或SED的驗證金鑰、而且無法從KMIP伺服器擷取、系統會將其視為中斷。雖然您無法存取或恢復磁碟上的資料、但您可以採取步驟、讓SED的未使用空間再次可供資料使用。

.開始之前
您必須是叢集管理員才能執行此工作。

.關於這項工作
只有當您確定FIPS磁碟機或SED的驗證金鑰已永久遺失、而且無法還原時、才應使用此程序。

如果磁碟已分割、則必須先取消磁碟分割、才能開始此程序。


NOTE: 取消磁碟分割的命令只能在診斷層級使用、而且只能在NetApp支援監督下執行。** 強烈建議您在繼續之前聯絡 NetApp 支援中心。 ** 您也可以參閱知識庫文件 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["如何在ONTAP 支援的情況下取消磁碟分割"^]。

.步驟
. 將FIPS磁碟機或SED送回服務：
+
[cols="25,75"]
|===


| 如果SED是... | 請使用下列步驟... 


 a| 
未處於FIPS相容模式、或處於FIPS相容模式、且FIPS金鑰可供使用
 a| 
.. 將權限層級設為進階：
`set -privilege advanced`
.. 將 FIPS 金鑰重設為預設製造安全 ID 0x0 ：
`storage encryption disk modify -fips-key-id 0x0 -disk _disk_id_`
.. 確認作業成功：
`storage encryption disk show-status`
如果作業失敗、請使用本主題中的 PSID 程序。
.. 清理損壞的磁碟：
`storage encryption disk sanitize -disk _disk_id_`
使用命令驗證作業是否成功 `storage encryption disk show-status` 繼續下一步之前。
.. 解除清理磁碟故障：
`storage disk unfail -spare true -disk _disk_id_`
.. 檢查磁碟是否擁有擁有者：
`storage disk show -disk _disk_id_`
 +
 如果磁碟沒有擁有者、請指派一個擁有者。
`storage disk assign -owner node -disk _disk_id_`
+
... 輸入要清理磁碟的節點節點節點的節點節點節點：
+
`system node run -node _node_name_`

+
執行 `disk sanitize release` 命令。



.. 離開 nodesdroand 。再次解除磁碟故障：
`storage disk unfail -spare true -disk _disk_id_`
.. 確認磁碟現在已成為備援磁碟、並可在集合體中重複使用：
`storage disk show -disk _disk_id_`




 a| 
在FIPS相容模式中、FIPS金鑰無法使用、且SED標籤上印有PSID
 a| 
.. 從磁碟標籤取得磁碟的PSID。
.. 將權限層級設為進階：
`set -privilege advanced`
.. 將磁碟重設為原廠設定的設定：
`storage encryption disk revert-to-original-state -disk _disk_id_ -psid _disk_physical_secure_id_`
使用命令驗證作業是否成功 `storage encryption disk show-status` 繼續下一步之前。
.. 如果您執行的是 ONTAP 9.8P5 或更早版本、請跳至下一步。如果您執行的是 ONTAP 9.8P6 或更新版本、請將已清理的磁碟恢復故障。
`storage disk unfail -disk _disk_id_`
.. 檢查磁碟是否擁有擁有者：
`storage disk show -disk _disk_id_`
 +
 如果磁碟沒有擁有者、請指派一個擁有者。
`storage disk assign -owner node -disk _disk_id_`
+
... 輸入要清理磁碟的節點節點節點的節點節點節點：
+
`system node run -node _node_name_`

+
執行 `disk sanitize release` 命令。



.. 離開 nodesdroe ..再次解除磁碟故障：
`storage disk unfail -spare true -disk _disk_id_`
.. 確認磁碟現在已成為備援磁碟、並可在集合體中重複使用：
`storage disk show -disk _disk_id_`


|===


如需完整的命令語法、請參閱 link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["命令參考資料"^]。
