---
permalink: encryption-at-rest/sanitize-fips-drive-sed-task.html 
sidebar: sidebar 
keywords: sanitize, fips, drive, sed, inaccessible, psid, physical secure ID, nrd plus, encrypt 
summary: '如果您想讓 FIPS 磁碟機或 SED 上的資料永遠無法存取、並將磁碟機用於新資料、您可以使用 `storage encryption disk sanitize` 用於清理磁碟機的命令。' 
---
= 清除FIPS磁碟機或SED
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想讓 FIPS 磁碟機或 SED 上的資料永遠無法存取、並將磁碟機用於新資料、您可以使用 `storage encryption disk sanitize` 用於清理磁碟機的命令。

.您需要的產品
您必須是叢集管理員才能執行此工作。

.關於這項工作
當您清理自我加密磁碟機時、系統會將磁碟加密金鑰變更為新的隨機值、將開機鎖定狀態重設為假、並將金鑰ID設為預設值、例如製造商安全ID 0x0（SAS磁碟機）或null金鑰（NVMe磁碟機）。這樣做會使磁碟上的資料無法存取、而且無法擷取。您可以將已消毒的磁碟重複使用為非零備援磁碟。

.步驟
. 將任何需要保留的資料移轉到另一個磁碟上的集合體。
. 刪除FIPS磁碟機或SED上要消毒的Aggregate：
+
`storage aggregate delete -aggregate _aggregate_name_`

+
如需完整的命令語法、請參閱手冊頁。

+
[listing]
----
cluster1::> storage aggregate delete -aggregate aggr1
----
. 識別要消毒的FIPS磁碟機或SED的磁碟ID：
+
`storage encryption disk show -fields data-key-id,fips-key-id,owner`

+
如需完整的命令語法、請參閱手冊頁。

+
[listing]
----
cluster1::> storage encryption disk show
Disk    Mode Data Key ID
-----   ---- ----------------------------------------------------------------
0.0.0   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
0.0.1   data F1CB30AFF1CB30B00101000000000000A68B167F92DD54196297159B5968923C
1.10.2  data F1CB30AFF1CB30B00101000000000000CF0EFD81EA9F6324EA97B369351C56AC
[...]
----
. 如果FIPS磁碟機以FIPS相容模式執行、請將節點的FIPS驗證金鑰ID設回預設的MSID 0x0：
+
`storage encryption disk modify -disk _disk_id_ -fips-key-id 0x0`

+
您可以使用 `security key-manager query` 檢視金鑰ID的命令。

+
[listing]
----
cluster1::> storage encryption disk modify -disk 1.10.2 -fips-key-id 0x0

Info: Starting modify on 1 disk.
      View the status of the operation by using the
      storage encryption disk show-status command.
----
. 為磁碟機消毒：
+
`storage encryption disk sanitize -disk _disk_id_`

+
您只能使用此命令來清除熱備援磁碟或中斷的磁碟。若要清理所有磁碟、無論其類型為何、請使用 `-force-all-state` 選項。如需完整的命令語法、請參閱手冊頁。

+
[NOTE]
====
系統會提示您輸入確認短句、然後再繼續。輸入完全如畫面所示的詞彙。

====
+
[listing]
----
cluster1::> storage encryption disk sanitize -disk 1.10.2

Warning: This operation will cryptographically sanitize 1 spare or broken self-encrypting disk on 1 node.
         To continue, enter sanitize disk: sanitize disk

Info: Starting sanitize on 1 disk.
      View the status of the operation using the
      storage encryption disk show-status command.
----

