---
sidebar: sidebar 
permalink: s3-snapshots/index.html 
keywords: s3 snapshots, S3 Snapshot copy overview, what is S3 snapshot, can you create S3 snapshots 
summary: 使用 S3 快照技術，為 S3 儲存貯體建立時間點備份。 
---
= 瞭解 ONTAP S3 快照
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9 開始。 16.1 開始，您可以使用 ONTAP 快照技術來產生 ONTAP S3 儲存區的唯讀時間點影像。

使用 S3 快照功能，您可以手動建立快照，或透過快照原則自動產生快照。S3 快照會以 S3 儲存區的形式呈現給 S3 用戶端。您可以透過 S3 用戶端，從快照瀏覽及還原內容。

在 ONTAP 9 。 16.1 中， S3 快照僅擷取 S3 儲存區中物件的目前版本。S3 快照不會擷取非目前版本的版本版本版本的版本儲存區。此外，如果在拍攝快照之後修改物件標籤，則時間點物件標籤不會擷取在快照中。


TIP: S3 快照仰賴叢集時間。您應該設定叢集中的 NTP 伺服器來同步時間。如需詳細資訊、請 link:../system-admin/manage-cluster-time-concept.html["管理叢集時間"]參閱。

.配額與空間使用量
配額會追蹤 S3 儲存區中使用的物件數量和邏輯大小。建立 S3 快照後， S3 快照中擷取的物件會計入所使用的儲存區物件數和大小，直到從檔案系統刪除快照為止。

.多部分物件
對於多部分物件，快照中只會擷取最終物件。多部分物件的部分上傳不會擷取在快照中。



== 在版本化和非版本化的貯體上建立快照

您可以在版本控制和非版本控制的貯體上建立快照。快照一次只包含擷取快照時的目前物件版本。

.版本化的儲存區和快照
在啟用物件版本控制的貯體中，快照會保留擷取快照後最新物件版本的內容。不包括貯體中的非最新版本。

請考慮以下範例：在已啟用物件版本設定的儲存區中，物件 `obj1`有版本 v1 ， v2 ， v3 ， v4 ， v5 。您從 `obj1` v3 建立了快照 `snap1`（擷取點的最新版本）。瀏覽 `snap1`時， `obj1`將顯示爲在 v3 中創建內容的對象。將不會傳回舊版的內容。


NOTE: 非目前版本會保留在檔案系統中，直到刪除快照為止。

.非版本化的儲存區和快照
在非版本化的貯體中， S3 快照會保留建立快照之前最新提交的內容。

請考慮以下範例：在無法使用物件版本管理的儲存區中，物件 `obj1`已在（ T1 ， T2 ， T3 ， T4 和 T5 ）上覆寫數次。您在 T3 和 T4 之間建立了 S3 快照 `snap1`。瀏覽 `snap1`時 `obj1`，會顯示在 T3 建立的內容。



== 物件過期與快照

ONTAP S3 物件過期和 S3 快照功能彼此獨立運作。ONTAP 物件過期功能會根據 S3 儲存區定義的生命週期管理規則，使物件版本過期。S3 快照是在建立快照時的某個時間點，貯體物件的靜態複本。

如果在貯體中啟用物件版本設定，當某個物件的特定版本因針對該貯體定義的到期規則而遭到刪除時，如果某個或多個 S3 快照中的版本已擷取為目前版本，則過期物件版本的內容會繼續保留在檔案系統中。只有刪除該快照時，該物件版本才會停止存在於檔案系統中。

同樣地，在停用版本設定的儲存區中，如果根據到期規則刪除物件，但物件仍在部分現有的 S3 快照中擷取，則該物件將保留在檔案系統中。刪除擷取的快照時，物件將從檔案系統中永久移除。

如需 S3 物件到期與生命週期管理的相關資訊link:../s3-config/create-bucket-lifecycle-rule-task.html["建立貯體生命週期管理規則"]，請參閱。



== S3 快照的限制

請注意 ONTAP 9 中的下列功能排除項目和案例：

* 您最多可以為 S3 儲存區產生 1023 個快照。
* 將叢集還原為 ONTAP 9 之前的 ONTAP 版本之前，必須先刪除叢集中所有儲存區中的所有 S3 快照和中繼資料。
* 如果您需要刪除包含快照物件的 S3 儲存區，請確定已刪除該儲存區中所有物件的所有對應快照。
* 以下組態不支援 S3 快照：
+
** SnapMirror 關係中的庫存箱
** 在已啟用物件鎖定的貯體上
** 在NetApp控制台上
** 在 System Manager 上
** 在 ONTAP MetroCluster 組態中


* 不建議在用作本機或遠端FabricPool容量層的儲存桶上使用 S3 快照。

