---
permalink: s3-multiprotocol/index.html 
sidebar: sidebar 
keywords: multiprotocol, s3, configuration, overview, nfs, smb 
summary: 從ONTAP S廳9.12.1開始、您可以讓執行S3傳輸協定的用戶端存取使用NFS和SMB傳輸協定的用戶端所獲得的相同資料、而無需重新格式化。 
---
= S3多重傳輸協定總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP S廳9.12.1開始、您可以讓執行S3傳輸協定的用戶端存取使用NFS和SMB傳輸協定的用戶端所獲得的相同資料、而無需重新格式化。這項功能可讓NAS資料繼續提供給NAS用戶端、同時將物件資料呈現給執行S3應用程式（例如資料採礦和人工智慧）的S3用戶端。

S3多重傳輸協定功能可解決兩種使用案例：

. 使用S3用戶端存取現有的NAS資料
+
如果您現有的資料是使用傳統NAS用戶端（NFS或SMB）建立、而且位於NAS磁碟區（FlexVol VMware FlexGroup 或VMware Volume）上、您現在可以使用S3用戶端上的分析工具來存取這些資料。

. 後端儲存設備、適用於能夠使用NAS和S3傳輸協定執行I/O的現代化用戶端
+
您現在可以為Spark和Kafka等應用程式提供整合式存取、這些應用程式可以使用NAS和S3傳輸協定來讀取和寫入相同的資料。





== S3多重傳輸協定的運作方式

使用支援多重傳輸協定、您可以將相同的資料集呈現為檔案階層或儲存庫中的物件。ONTAP為達成此目的ONTAP 、此功能會建立「S3 NAS桶」、讓S3用戶端能夠使用S3物件要求、在NAS儲存設備中建立、讀取、刪除及列舉檔案。此對應符合NAS安全組態、可觀察檔案和目錄存取權限、並視需要寫入安全性稽核記錄。

這項對應是透過將指定的NAS目錄階層呈現為S3儲存區來完成。目錄階層中的每個檔案都會以S3物件表示、其名稱會相對於對應的目錄向下、而目錄邊界則以斜槓字元（'/'）表示。

一般ONTAP定義的S3使用者可存取此儲存設備、此儲存設備受為對應至NAS目錄的儲存區所定義的儲存區原則所規範。若要達到此目的、必須在S3使用者和SMB/NFS使用者之間定義對應。SMB/NFS使用的認證將用於NAS權限檢查、並包含在這些存取所產生的任何稽核記錄中。

當SMB或NFS用戶端建立時、檔案會立即放在目錄中、因此在寫入任何資料之前、用戶端可以看到。S3用戶端會預期不同的語義、在寫入新物件的所有資料之前、新物件不會顯示在命名空間中。S3與NAS儲存設備之間的這種對應會使用S3語義建立檔案、在S3建立命令完成之前、將檔案保持在外部不可見的狀態。



== S3 NAS儲存區的資料保護

S3 NAS「桶」只是S3用戶端NAS資料的對應、並非標準S3桶。因此、您不需要使用NetApp S3 SnapMirror功能來保護S3 NAS儲存區。您可以改用標準SnapMirror資料保護關係來複寫包含S3 NAS儲存區的來源SVM、並與目的地SVM建立關係。

深入瞭解 link:../data-protection/snapmirror-svm-replication-concept.html["SnapMirror SVM複寫"]。



== 稽核S3 NAS儲存區

由於S3 NAS儲存區並非傳統的S3儲存區、因此無法將S3稽核設定為稽核其存取。深入瞭解 link:../s3-audit/index.html["S3稽核"]。

不過、在S3 NAS儲存區中對應的NAS檔案和目錄、仍可使用傳統ONTAP 的還原稽核程序來稽核存取事件。因此S3作業可觸發NAS稽核事件、但有下列例外：

* 如果S3原則組態（群組或儲存區原則）拒絕S3用戶端存取、則不會啟動事件的NAS稽核。這是因為在進行SVM稽核檢查之前、會先檢查S3權限。
* 如果S3 Get要求的目標檔案大小為0、0內容會傳回Get要求、而且不會記錄讀取存取權。
* 如果S3 Get要求的目標檔案位於使用者沒有周遊權限的資料夾中、則存取嘗試會失敗、而且不會記錄事件。


深入瞭解 link:../nas-audit/auditing-events-concept.html["稽核SVM上的NAS事件"]。



== S3與NAS互通性

除了此處列出的項目、不支援標準NAS和S3功能。ONTAP



=== S3 NAS儲存區目前不支援NAS功能

資料層FabricPool:: S3 NAS貯體無法設定為FabricPool 容量層級以供實現效能不敷使用。




=== S3 NAS儲存區目前不支援S3功能

AWS使用者中繼資料::
+
--
* S3使用者中繼資料一部分收到的金鑰值配對、不會連同目前版本中的物件資料一起儲存在磁碟上。
* 會忽略開頭為「x-amz-meta」的要求標頭。


--
AWS標籤::
+
--
* 在PUT物件和Multifart初始化要求上、會忽略前置詞為「x-amz-tagging」的標頭。
* 系統會拒絕更新現有檔案上的標記要求（例如使用「標記查詢字串」的PUT、Get和Delete要求）、並顯示錯誤訊息。


--
版本管理:: 無法在庫位對應組態中指定版本管理。
+
--
* 包含非null版本規格（版本Id=xyz query-string）的要求會收到錯誤回應。
* 系統會拒絕影響儲存區版本設定狀態的要求、但會顯示錯誤。


--
多部份作業:: 不支援下列作業：
+
--
* AbortMultiPart上 傳
* 完成多個部分上傳
* 建立多個部分上傳
* 清單多個部分上傳


--

