---
permalink: consistency-groups/clone-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, clone 
summary: 從 ONTAP 9.12.1 開始、您可以複製一致性群組、以建立一致性群組組組態和磁碟區的複本。 
---
= 複製一致性群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9.12.1 開始、您可以複製一致性群組、以建立一致性群組及其內容的複本。複製一致性群組會建立一致性群組組態的複本、其中繼資料（例如應用程式類型）、以及所有磁碟區及其內容（例如檔案、目錄、LUN或NVMe命名空間）。

.關於這項工作
複製一致性群組時，您可以使用其目前組態來複製，但可以使用現有的一致性群組快照來複製磁碟區內容。

只有整個一致性群組才支援複製一致性群組。您無法在階層關係中複製個別子一致性群組：只能複製完整的一致性群組組態。

當您複製一致性群組時、不會複製下列元件：

* igroup
* LUN對應
* NVMe子系統
* NVMe命名空間子系統對應


.開始之前
* 當您複製一致性群組時、ONTAP 如果未指定共用名稱、則不會為複製的磁碟區建立SMB共用區。* 如果未指定連接路徑、則不會掛載複製的一致性群組。
* 如果您嘗試根據不反映一致性群組目前組成磁碟區的快照來複製一致性群組，作業將會失敗。
* 複製一致性群組之後、您需要執行適當的對應作業。
+
請參閱 xref:../task_san_map_igroups_to_multiple_luns.html[將igroup對應至多個LUN] 或 xref:../san-admin/map-nvme-namespace-subsystem-task.html[將NVMe命名空間對應至子系統] 以取得更多資訊。

* SnapMirror 主動式同步關係中的一致性群組或任何相關的 DP 磁碟區不支援複製一致性群組。


[role="tabbed-block"]
====
.系統管理員
--
.步驟
. 選擇*儲存>一致性群組*。
. 從「*一致性群組*」功能表中選取您要複製的一致性群組。
. 在一致性群組的總覽頁面右上角、選取* Clone（複製）*。
. 輸入新的複製一致性群組名稱、或接受預設名稱。
+
.. 如果您要啟用、請選擇 link:../concepts/thin-provisioning-concept.html["*精簡配置*"^]。
.. 如果您要將一致性群組與其來源分離、並為複製的一致性群組分配額外的磁碟空間、請選擇*分割Clone（分割複製）*。


. 若要以目前狀態複製一致性群組、請選擇*新增Snapshot複本*。
+
若要根據快照複製一致性群組，請選擇 * 使用現有的 SnapShot * 。選取此選項將會開啟新的子功能表。選擇您要作為複製作業基礎的快照。

. 選擇* Clone（克隆）*。
. 返回「*一致性群組*」功能表、確認您的一致性群組已複製完成。


--
.CLI
--
從 ONTAP 9.14.1 開始、您可以使用具有叢集管理認證的 CLI 來複製一致性群組。

.開始之前
* 您必須處於管理權限層級、才能執行此工作。
* 在 ONTAP 9.14.1 中、您必須是叢集或 SVM 管理員、才能執行此工作。從 ONTAP 9.15.1 開始、任何管理權限層級的使用者都可以執行此工作。


.複製一致性群組
. 命令會 `consistency-group clone create`以目前的時間點狀態複製一致性群組。若要以快照作為複製作業的基礎，請加入 `-source-snapshot`參數。
+
`consistency-group clone create -vserver _svm_name_ -consistency-group _clone_name_ -source-consistency-group _consistency_group_name_ [-source-snapshot _snapshot_name_]`

+
如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=consistency-group+clone+create["指令參考資料ONTAP"^]需詳細 `consistency-group clone create`資訊，請參閱。



--
====
.後續步驟
* xref:../task_san_map_igroups_to_multiple_luns.html[將igroup對應至多個LUN]
* xref:../san-admin/map-nvme-namespace-subsystem-task.html[將NVMe命名空間對應至子系統]

