---
permalink: consistency-groups/clone-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, clone 
summary: 從ONTAP 功能表9.12開始、您可以複製一致性群組、以建立一致性群組組組態和磁碟區與其內容的複本。 
---
= 複製一致性群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP 功能表9.12開始、您可以複製一致性群組、以建立一致性群組及其內容的複本。複製一致性群組會建立一致性群組組態的複本、其中繼資料（例如應用程式類型）、以及所有磁碟區及其內容（例如檔案、目錄、LUN或NVMe命名空間）。

複製一致性群組時、您可以使用目前的組態來複製、但可以使用現有的磁碟區內容、或是根據現有的一致性群組Snapshot來複製。

複製一致性群組僅支援整個一致性群組。您無法在階層關係中複製個別子一致性群組：只能複製完整的一致性群組組態。

當您複製一致性群組時、不會複製下列元件：

* igroup
* LUN對應
* NVMe子系統
* NVMe命名空間子系統對應


當您複製一致性群組時、ONTAP 如果未指定共用名稱、則不會為複製的磁碟區建立SMB共用區。如果未指定交會路徑、將不會掛載複製的一致性群組。如果您嘗試根據未反映一致性群組目前組態的Snapshot來複製一致性群組、則作業將會失敗。

複製一致性群組之後、您需要執行適當的對應作業。請參閱 xref:../task_san_map_igroups_to_multiple_luns.html[將igroup對應至多個LUN] 或 xref:../san-admin/map-nvme-namespace-subsystem-task.html[將NVMe命名空間對應至子系統] 以取得更多資訊。

SnapMirror營運不中斷關係中的一致性群組或任何相關的DP磁碟區不支援複製一致性群組。

.步驟
. 從「*一致性群組*」功能表中選取您要複製的一致性群組。
. 在一致性群組的總覽頁面右上角、選取* Clone（複製）*。
. 輸入新的複製一致性群組名稱、或接受預設名稱。
+
.. 如果您要啟用*精簡配置*、請選擇。
.. 如果您要將一致性群組與其來源分離、並為複製的一致性群組分配額外的磁碟空間、請選擇*分割Clone（分割複製）*。


. 若要以目前狀態複製一致性群組、請選擇*新增Snapshot複本*。
+
若要根據快照複製一致性群組、請選擇*使用現有的Snapshot複本*。選取此選項將會開啟新的子功能表。選擇您要做為複製作業基礎的Snapshot。

. 選擇* Clone（克隆）*。
. 返回「*一致性群組*」功能表、確認您的一致性群組已複製完成。

