---
permalink: consistency-groups/configure-hierarchy-task.html 
sidebar: sidebar 
keywords: consistency groups, application protection, parent, child, hierarchy 
summary: 建立階層式一致性群組、以進行大型應用程式工作負載管理和資料保護。 
---
= 設定階層式一致性群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的應用程式工作負載由多個子集的磁碟區組成、其中每個子集在其各自的關聯磁碟區之間保持一致、ONTAP 則可使用VMware功能建立階層式一致性群組。

階層式一致性群組具有父群組、最多可包含五個個別的一致性群組。階層式一致性群組可跨一致性群組或個別磁碟區支援不同的本機Snapshot原則。如果您使用遠端SMBC原則、則會套用整個階層式一致性群組（父和子群組）。

如需一致性群組的物件限制、請參閱 xref:index.html#consistency-group-object-limits[一致性群組的物件限制]。



== 使用新的磁碟區建立階層式一致性群組

.步驟
. 選擇*儲存>一致性群組*。
. 選擇「*+ Add *」、然後選擇「* Using New LUN*（*使用新LUN *）」。
. 命名一致性群組。指定每個LUN的LUN數量和容量。
+
.. **應用程式類型*：如果您使用ONTAP 的是更新版本的版本、請選取應用程式類型。如果未選取任何值、系統將預設指派類型為「**其他*」。深入瞭解中的標記一致性 xref:index.html#application-and-component-tags[應用程式與元件標籤]。如果您打算建立SMBC關係、則必須使用*其他*。


. 選取主機作業系統和LUN格式。輸入主機啟動器資訊。
. 若要設定保護原則、新增子一致性群組或顯示更多有關主機啟動器的選項、請選取*更多選項*。
. 若要新增子一致性群組、請選取*+新增子一致性群組*。
. 選取效能層級、LUN數量及每個LUN的容量。指定主機作業系統、LUN格式、然後選取新的或現有的主機啟動器群組。
. *選用*：選取本機快照原則。
. 重複最多五個子一致性群組。
. 選擇*保存*。
. 請返回主一致性群組功能表、確認您的一致性群組已建立、ONTAP 一旦完成此工作、就會顯示在該功能表中。如果您設定保護原則、請查看適當的原則（遠端或本機）、此原則應會顯示綠色的遮罩、並勾選其中的核取符號。




== 使用現有的磁碟區建立階層式一致性群組

.步驟
. 選擇*儲存>一致性群組*。
. 選擇「*+ Add *（+新增*）」、然後選擇「* Using existing volumes（*使用現有
. 選取儲存VM。
. 選取要納入的現有磁碟區。只有尚未納入一致性群組的磁碟區可供選擇。
. 若要新增子一致性群組、請選取*+新增子一致性群組*。建立必要的一致性群組、並自動命名。
+
.. **元件類型*：如果您使用ONTAP 的是更新版本的版本、請選取「資料」、「記錄」或「其他」等元件類型。如果未選取任何值、系統將預設指派類型為「**其他*」。深入瞭解中的標記一致性 xref:index.html#application-and-component-tags[應用程式與元件標籤]。如果您打算建立SMBC關係、則必須使用*其他*。


. 將現有磁碟區指派給每個一致性群組。
+
.. *選用*：選取本機Snapshot原則。


. 重複最多五個子一致性群組。
. 選擇*保存*。
. 請返回主一致性群組功能表、確認您的一致性群組已建立、ONTAP 一旦完成此工作、就會顯示在該功能表中。如果您已選擇保護原則、請從功能表中選取您的一致性群組、以確認該原則已正確設定。如果您設定保護原則、請查看適當的原則（遠端或本機）、此原則應會顯示綠色的遮罩、並勾選其中的核取符號。

