---
permalink: consistency-groups/configure-hierarchy-task.html 
sidebar: sidebar 
keywords: consistency groups, application protection, parent, child, hierarchy 
summary: 建立階層式一致性群組、以進行大型應用程式工作負載管理和資料保護。 
---
= 配置分層ONTAP一致性組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
階層式一致性群組可讓您管理跨越多個磁碟區的大型工作負載、建立父一致性群組、作為子一致性群組的保護傘。

階層式一致性群組具有父群組、最多可包含五個個別的一致性群組。階層式一致性群組可支援跨一致性群組或個別磁碟區的不同本機快照原則。如果您使用遠端保護原則、則會套用至整個階層式一致性群組（父和子）。

從 ONTAP 9.13.1 開始、您就可以 xref:modify-geometry-task.html[修改一致性群組的幾何] 和 xref:modify-task.html[在子一致性群組之間移動磁碟區]。

如需一致性群組的物件限制、請參閱 xref:limits.html[一致性群組的物件限制]。



== 使用新的 LUN 或磁碟區建立階層式一致性群組

建立階層式一致性群組時、您可以使用新的LUN來填入群組。從 ONTAP 9.13.1 開始、您也可以使用新的 NVMe 命名空間和 NAS 磁碟區。

[role="tabbed-block"]
====
.系統管理員
--
.步驟
. 選擇*儲存>一致性群組*。
. 選取 *+Add* 、然後選取儲存物件的傳輸協定。
+
在 ONTAP 9.10.1 至 9.12.1 中、新儲存物件的唯一選項是 ** 使用新的 LUN** 。從 ONTAP 9.13.1 開始、 System Manager 支援使用新的 NVMe 命名空間和新的 NAS 磁碟區來建立一致性群組。

. 命名一致性群組。指定磁碟區或 LUN 的數量、以及每個磁碟區或 LUN 的容量。
+
.. **應用程式類型*：如果您使用ONTAP 的是更新版本的版本、請選取應用程式類型。如果未選取任何值、系統將預設指派類型為「**其他*」。深入瞭解中的標記一致性 xref:modify-tags-task.html[應用程式與元件標籤]。如果您打算使用遠端保護原則、則必須選擇 * 其他 * 。


. 選取主機作業系統和LUN格式。輸入主機啟動器資訊。
+
.. 對於 ** 新 LUN** ：選擇主機作業系統和 LUN 格式。輸入主機啟動器資訊。
.. 對於 ** 新 NAS Volume ** ：根據 SVM 的 NAS 組態、選擇適當的匯出選項（ NFS 或 SMB/CIFS ）。
.. 對於 ** 新的 NVMe 命名空間 ** ：選取主機作業系統和 NVMe 子系統。


. 若要新增子一致性群組、請選取 * 更多選項 * 、然後選取 *+ 新增子一致性群組 * 。
. 選取效能層級、 LUN 或磁碟區數量、以及每個 LUN 或磁碟區的容量。根據您使用的傳輸協定、指定適當的匯出組態或作業系統資訊。
. 您也可以選擇本機快照原則、並設定存取權限。
. 重複最多五個子一致性群組。
. 選擇*保存*。
. 請返回主一致性群組功能表、確認您的一致性群組已建立、ONTAP 一旦完成此工作、就會顯示在該功能表中。如果您設定保護原則、請查看適當的原則（遠端或本機）、此原則應會顯示綠色的遮罩、並勾選其中的核取符號。


--
.CLI
--
.開始之前
* 您必須處於管理權限層級、才能執行此工作。
* 從ONTAP 9.15.1 開始，任何具有管理員權限等級的使用者都可以執行此任務。在ONTAP 9.14.1 中，您必須是叢集或 SVM 管理員才能執行此任務。


在 CLI 中建立具有新磁碟區的階層式一致性群組時、您必須個別建立每個子一致性群組。

.步驟
. 使用建立新的一致性群組 `consistency-group create` 命令。
+
`consistency-group create -vserver <SVM_name> -consistency-group <consistency_group_name> -parent-consistency-group <parent_consistency_group_name> -volume-prefix <volume_prefix> -volume-count <number_of_volumes> -size <size>`

. 當 CLI 提示時、請確認您要建立新的父一致性群組。輸入。 `y`
. 或者、重複步驟 1 以建立更多子一致性群組。
+
如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=consistency-group+create["指令參考資料ONTAP"^]需詳細 `consistency-group create`資訊，請參閱。



--
====


== 使用現有的磁碟區建立階層式一致性群組

您可以將現有的磁碟區組織成階層式一致性群組。

[role="tabbed-block"]
====
.系統管理員
--
.步驟
. 選擇*儲存>一致性群組*。
. 選擇「*+新增*」、然後選擇「*使用現有磁碟區*」。
. 選取儲存VM。
. 選取要納入的現有磁碟區。只有尚未納入一致性群組的磁碟區可供選擇。
. 若要新增子一致性群組、請選取*+新增子一致性群組*。建立必要的一致性群組、並自動命名。
+
.. **元件類型*：如果您使用ONTAP 的是更新版本的版本、請選取「資料」、「記錄」或「其他」等元件類型。如果未選取任何值、系統將預設指派類型為「**其他*」。深入瞭解中的標記一致性 xref:modify-tags-task.html[應用程式與元件標籤]。如果您打算使用遠端保護原則、則必須使用 * 其他 * 。


. 將現有磁碟區指派給每個一致性群組。
. 您也可以選擇本機快照原則。
. 重複最多五個子一致性群組。
. 選擇*保存*。
. 請返回主一致性群組功能表、確認您的一致性群組已建立、ONTAP 一旦完成此工作、就會顯示在該功能表中。如果您已選擇保護原則、請從功能表中選取一致性群組、以確認其設定正確；在適當的原則類型下、您會看到一個綠色的遮罩、其中會有核取符號。


--
.CLI
--
從 ONTAP 9.14.1 開始、您可以使用 CLI 建立階層式一致性群組。

.開始之前
* 您必須處於管理權限層級、才能執行此工作。
* 從ONTAP 9.15.1 開始，任何具有管理員權限等級的使用者都可以執行此任務。在ONTAP 9.14.1 中，您必須是叢集或 SVM 管理員才能執行此任務。


.步驟
. 配置新的父一致性群組、並將磁碟區指派給新的子一致性群組：
+
`consistency-group create -vserver <svm_name> -consistency-group <child_consistency_group_name> -parent-consistency-group <parent_consistency_group_name> -volumes <volume_names>`

. 輸入 `y` 確認您要建立新的父和子一致性群組。
+
如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=consistency-group+create["指令參考資料ONTAP"^]需詳細 `consistency-group create`資訊，請參閱。



--
====
.後續步驟
* xref:xref:modify-geometry-task.html[修改一致性群組的幾何]
* xref:modify-task.html[修改一致性群組]
* xref:protect-task.html[保護一致性群組]

