---
permalink: consistency-groups/configure-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, application protection, parent, child, configure 
summary: 建立單一一致性群組以進行應用程式工作負載管理和資料保護。 
---
= 設定單一一致性群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
可以使用現有的磁碟區或新的 LUN 或磁碟區來建立一致性群組（視 ONTAP 版本而定）。磁碟區或 LUN 一次只能與一個一致性群組建立關聯。

.開始之前
* 在 ONTAP 9.10.1 至 9.11.1 中、不支援在建立一致性群組之後修改其成員磁碟區。
+
從ONTAP 功能更新至功能更新版本9.12.1開始、您可以修改一致性群組的成員磁碟區。如需此程序的詳細資訊、請參閱 xref:modify-task.html[修改一致性群組]。





== 使用新的 LUN 或磁碟區建立一致性群組

在 ONTAP 9.10.1 至 9.12.1 中、您可以使用新的 LUN 建立一致性群組。從 ONTAP 9.13.1 開始、 System Manager 也支援使用新的 NVMe 命名空間或新的 NAS 磁碟區來建立一致性群組。（從 ONTAP 9.12.1 開始、 ONTAP REST API 也支援此功能。）

.步驟
. 選擇*儲存>一致性群組*。
. 選取 *+Add* 、然後選取儲存物件的傳輸協定。
+
在 ONTAP 9.10.1 至 9.12.1 中、新儲存物件的唯一選項是 ** 使用新的 LUN** 。從 ONTAP 9.13.1 開始、 System Manager 支援使用新的 NVMe 命名空間和新的 NAS 磁碟區來建立一致性群組。

. 命名一致性群組。指定磁碟區或 LUN 的數量、以及每個磁碟區或 LUN 的容量。
+
.. **應用程式類型*：如果您使用ONTAP 的是更新版本的版本、請選取應用程式類型。如果未選取任何值、系統將預設指派類型為「**其他*」。深入瞭解中的標記一致性 xref:index.html#application-and-component-tags[應用程式與元件標籤]。如果您打算使用遠端保護原則建立一致性群組、則必須使用 * 其他 * 。
.. 對於 ** 新 LUN** ：選擇主機作業系統和 LUN 格式。輸入主機啟動器資訊。
.. 對於 ** 新 NAS Volume ** ：根據 SVM 的 NAS 組態、選擇適當的匯出選項（ NFS 或 SMB/CIFS ）。
.. 對於 ** 新的 NVMe 命名空間 ** ：選取主機作業系統和 NVMe 子系統。


. 若要設定保護原則、新增子一致性群組或存取權限、請選取 * 更多選項 * 。
. 選擇*保存*。
. 請返回工作完成後顯示的主要一致性群組功能表、確認您的一致性群組已建立。如果您設定了保護原則、當您在適當的原則（遠端或本機）下看到綠色保護罩時、就會知道它已套用。




== 使用現有磁碟區建立一致性群組

您可以使用現有的磁碟區來建立一致性群組。

.步驟
. 選擇*儲存>一致性群組*。
. 選擇「*+新增*」、然後選擇「*使用現有磁碟區*」。
. 命名一致性群組、然後選取儲存VM。
+
.. **應用程式類型*：如果您使用ONTAP 的是更新版本的版本、請選取應用程式類型。如果未選取任何值、系統將預設指派類型為「**其他*」。深入瞭解中的標記一致性 xref:index.html#application-and-component-tags[應用程式與元件標籤]。如果一致性群組具有SMBC關係、您必須使用*其他*。


. 選取要納入的現有磁碟區。只有尚未納入一致性群組的磁碟區可供選擇。
+

NOTE: 如果使用現有磁碟區建立一致性群組、一致性群組就會支援FlexVol 使用各種功能。具有非同步或同步SnapMirror關係的磁碟區可以新增至一致性群組、但它們無法感知一致性群組。一致性群組不支援 S3 儲存區、也不支援具有 SVMDR 關係的儲存 VM 。

. 選擇*保存*。
. 請返回主一致性群組功能表、確認您的一致性群組已建立、ONTAP 一旦完成此工作、就會顯示在該功能表中。如果您已選擇保護原則、請從功能表中選取您的一致性群組、以確認該原則已正確設定。如果您設定了保護原則、當您在適當的原則（遠端或本機）下看到綠色保護罩時、就會知道它已套用。


.後續步驟
* xref:protect-task.html[保護一致性群組]
* xref:modify-task.html[修改一致性群組]
* xref:clone-task.html[複製一致性群組]

