---
permalink: consistency-groups/configure-task.html 
sidebar: sidebar 
keywords: consistency groups, consistency group, application protection, parent, child, configure 
summary: 建立單一一致性群組以進行應用程式工作負載管理和資料保護。 
---
= 設定單一一致性群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用現有的磁碟區或新的磁碟區來建立一致性群組。一旦將磁碟區新增至一致性群組、就無法將其新增至其他一致性群組。

在《》（修訂版）9.10.1至9.11.1中、您無法修改一致性群組的組成磁碟區。ONTAP從ONTAP S廳9.12.1開始、您可以在建立一致性群組之後、新增或移除該磁碟區。如需此程序的詳細資訊、請參閱 xref:modify-task.html[修改一致性群組]。



== 使用新的磁碟區建立一致性群組

.步驟
. 選擇*儲存>一致性群組*。
. 選擇「*+ Add *」、然後選擇「* Using New LUN*（*使用新LUN *）」。
. 命名一致性群組。指定每個LUN的LUN數量和容量。
+
.. **應用程式類型*：如果您使用ONTAP 的是更新版本的版本、請選取應用程式類型。如果未選取任何值、系統將預設指派類型為「**其他*」。深入瞭解中的標記一致性 xref:index.html#application-and-component-tags[應用程式與元件標籤]。如果您打算建立SMBC關係、則必須使用*其他*。


. 選取主機作業系統和LUN格式。輸入主機啟動器資訊。
. 若要設定保護原則、新增子一致性群組或顯示更多有關主機啟動器的選項、請選取*更多選項*
. 選擇*保存*。
. 請返回主一致性群組功能表、確認您的一致性群組已建立、ONTAP 一旦完成此工作、就會顯示在該功能表中。如果您設定保護原則、請查看適當的原則（遠端或本機）、此原則應會顯示綠色的遮罩並勾選核取符號。




== 使用現有磁碟區建立一致性群組

.步驟
. 選擇*儲存>一致性群組*。
. 選擇「*+ Add *（+新增*）」、然後選擇「* Using existing volumes（*使用現有
. 命名一致性群組、然後選取儲存VM。
+
.. **應用程式類型*：如果您使用ONTAP 的是更新版本的版本、請選取應用程式類型。如果未選取任何值、系統將預設指派類型為「**其他*」。深入瞭解中的標記一致性 xref:index.html#application-and-component-tags[應用程式與元件標籤]。如果一致性群組具有SMBC關係、您必須使用*其他*。


. 選取要納入的現有磁碟區。只有尚未納入一致性群組的磁碟區可供選擇。
+

NOTE: 如果使用現有磁碟區建立一致性群組、一致性群組就會支援FlexVol 使用各種功能。具有非同步或同步SnapMirror關係的磁碟區可以新增至一致性群組、但它們無法感知一致性群組。一致性群組不支援具有MetroCluster SVMDR關係的S3庫存箱、VMware或儲存VM。

. 選擇*保存*。
. 請返回主一致性群組功能表、確認您的一致性群組已建立、ONTAP 一旦完成此工作、就會顯示在該功能表中。如果您已選擇保護原則、請從功能表中選取您的一致性群組、以確認該原則已正確設定。如果您設定保護原則、請查看適當的原則（遠端或本機）、此原則應會顯示綠色的遮罩並勾選核取符號。


.後續步驟
* xref:protect-task.html[保護一致性群組]
* xref:modify-task.html[修改一致性群組]
* xref:clone-task.html[複製一致性群組]

