---
sidebar: sidebar 
permalink: consistency-groups/modify-geometry-task.html 
keywords: consistency group geometry, promote consistency group, demote, add consistency group 
summary: 從 ONTAP 9.13.1 開始、您可以修改一致性群組的幾何、同時中斷 IO 作業。 
---
= 修改ONTAP一致性組幾何結構
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9.13.1 開始、您可以修改一致性群組的幾何。修改一致性群組的幾何可讓您變更子或父一致性群組的組態、而不會中斷進行中的 IO 作業。

修改一致性群組幾何資料會影響一致性群組的現有快照。如需詳細資訊、請參閱您要執行的幾何特定修改。


NOTE: 您無法修改以遠端保護原則設定的一致性群組幾何。您必須先中斷保護關係、修改幾何、然後還原遠端保護。



== 新增子一致性群組

從 ONTAP 9.13.1 開始、您可以將新的子一致性群組新增至現有的父一致性群組。

.關於這項工作
* 父一致性群組最多可包含五個子一致性群組。請參閱 xref:limits.html[一致性群組限制] 其他限制。
* 您無法將子一致性群組新增至單一一致性群組。您必須優先 <<促銷>> 接著您可以新增子一致性群組。
* 在展開作業之前擷取的一致性群組現有快照將視為部分快照。任何以該快照為基礎的還原作業，都會在快照的時間點反映一致性群組。


.步驟
[role="tabbed-block"]
====
.系統管理員
--
從 ONTAP 9.13.1 開始、您可以使用系統管理員執行此作業。

.新增子一致性群組
. 選擇*儲存>一致性群組*。
. 選取您要新增子一致性群組的父一致性群組。
. 在父一致性群組名稱旁、選取「 ** 更多 ** 」、然後選擇「新增子一致性群組」。
. 輸入一致性群組的名稱。
. 選擇您要新增或現有的磁碟區。
+
.. 如果您要新增現有的磁碟區、請選取 ** 現有的磁碟區 ** 、然後從下拉式功能表中選擇磁碟區。
.. 如果您要新增新的磁碟區、請選取 ** 新的磁碟區 ** 、然後指定磁碟區數量及其大小。


. 選取 ** 新增 ** 。


--
.CLI
--
從 ONTAP 9.14.1 開始、您可以使用 ONTAP CLI 新增子一致性群組。

.開始之前
* 您必須處於管理權限層級、才能執行此工作。
* 從ONTAP 9.15.1 開始，任何具有管理員權限等級的使用者都可以執行此任務。在ONTAP 9.14.1 中，您必須是叢集或 SVM 管理員才能執行此任務。


.新增具有新磁碟區的子一致性群組
. 建立新的一致性群組。提供一致性群組名稱、磁碟區首碼、磁碟區數量、磁碟區大小、儲存服務、 和匯出原則名稱：
+
`consistency-group create -vserver _SVM_name_ -consistency-group _consistency_group_ -parent-consistency-group _parent_consistency_group_ -volume-prefix _prefix_ -volume-count _number_ -size _size_ -storage-service _service_ -export-policy _policy_name_`



.新增具有現有磁碟區的子一致性群組
. 建立新的一致性群組。。 `volumes` 參數接受以逗號分隔的磁碟區名稱清單。
+
`consistency-group create -vserver _SVM_name_ -consistency-group _new_consistency_group_ -parent-consistency-group _parent_consistency_group_ -volumes _volume_`



--
====


== 分離子一致性群組

從 ONTAP 9.13.1 開始、您可以將子一致性群組從其父群組中移除、將其轉換為個別一致性群組。

.關於這項工作
* 分離子一致性群組會導致父一致性群組的快照無效且無法存取。Volume 精細快照仍有效。
* 個別一致性群組的現有快照仍然有效。
* 如果現有的單一一致性群組名稱與您要分離的子一致性群組名稱相同、則此作業將會失敗。如果您遇到此案例、則在中斷連線時必須重新命名一致性群組。


.步驟
[role="tabbed-block"]
====
.系統管理員
--
從 ONTAP 9.13.1 開始、您可以使用系統管理員執行此作業。

.分離子一致性群組
. 選擇*儲存>一致性群組*。
. 選取包含要分離之子系的父一致性群組。
. 在要分離的子一致性組旁邊，選擇 ** 更多 ** ，然後選擇 ** 分離父級 ** 。
. 您也可以重新命名一致性群組、然後選取應用程式類型。
. 選擇 ** 分離 ** 。


--
.CLI
--
從 ONTAP 9.14.1 開始、您可以使用 ONTAP CLI 分離子一致性群組。

.開始之前
* 您必須處於管理權限層級、才能執行此工作。
* 從ONTAP 9.15.1 開始，任何具有管理員權限等級的使用者都可以執行此任務。在ONTAP 9.14.1 中，您必須是叢集或 SVM 管理員才能執行此任務。


.分離子一致性群組
. 分離一致性群組。您也可以使用重新命名分離的一致性群組 `-new-name` 參數。
+
`consistency-group detach -vserver _SVM_name_ -consistency-group _child_consistency_group_ -parent-consistency-group _parent_consistency_group_ [-new-name _new_name_]`



--
====


== 將現有的單一一致性群組移至父一致性群組下

從 ONTAP 9.13.1 開始、您可以將現有的單一一致性群組轉換成子一致性群組。您可以將一致性群組移至現有父一致性群組之下、或在移動作業期間建立新的父一致性群組。

.關於這項工作
* 父一致性群組必須有四個或更少的子項目。父一致性群組最多可包含五個子一致性群組。請參閱 xref:limits.html[一致性群組限制] 其他限制。
* 在此作業之前擷取的 _父 / 母一致性群組現有快照視為部分快照。任何以其中一個快照為基礎的還原作業，都會反映快照時間點的一致性群組。
* 單一一致性群組的現有一致性群組快照仍然有效。


.步驟
[role="tabbed-block"]
====
.系統管理員
--
從 ONTAP 9.13.1 開始、您可以使用系統管理員執行此作業。

.將現有的單一一致性群組移至父一致性群組下
. 選擇*儲存>一致性群組*。
. 選取您要轉換的一致性群組。
. 選擇「 ** 更多 ** 」、然後選擇「在不同一致性群組下移動」 ** 。
. 您也可以輸入一致性群組的新名稱、然後選取元件類型。根據預設、元件類型為其他。
. 選擇是否要移轉至現有的父一致性群組、或建立新的父一致性群組：
+
.. 若要移轉至現有的父一致性群組、請選取 ** 現有一致性群組 ** 、然後從下拉式功能表中選擇一致性群組。
.. 若要建立新的父一致性群組、請選取 ** 新一致性群組 ** 、然後提供新一致性群組的名稱。


. 選擇 ** 移動 ** 。


--
.CLI
--
從 ONTAP 9.14.1 開始、您可以使用 ONTAP CLI 將單一一致性群組移至父一致性群組下。

.開始之前
* 您必須處於管理權限層級、才能執行此工作。
* 從ONTAP 9.15.1 開始，任何具有管理員權限等級的使用者都可以執行此任務。在ONTAP 9.14.1 中，您必須是叢集或 SVM 管理員才能執行此任務。


.將一致性群組移至新的父一致性群組下
. 建立新的父一致性群組。。 `-consistency-groups` 參數會將任何現有的一致性群組移轉至新父群組。
+
`consistency-group attach -vserver _svm_name_ -consistency-group _parent_consistency_group_ -consistency-groups _child_consistency_group_`



.將一致性群組移至現有一致性群組下
. 移動一致性群組：
+
`consistency-group add -vserver _SVM_name_ -consistency-group _consistency_group_ -parent-consistency-group _parent_consistency_group_`



--
====


== 推廣子項一致性群組

從 ONTAP 9.13.1 開始、您可以將單一一致性群組升級為父一致性群組。當您將單一一致性群組提升為父群組時、也會建立新的子一致性群組、繼承原始單一一致性群組中的所有磁碟區。

.關於這項工作
* 如果您想要將子一致性群組轉換成父一致性群組、則必須先將其轉換成父一致性群組 <<detach>> 然後，子一致性群組會遵循此程序。
* 在您提升一致性群組之後，一致性群組的現有快照仍有效。


[role="tabbed-block"]
====
.系統管理員
--
從 ONTAP 9.13.1 開始、您可以使用系統管理員執行此作業。

.推廣子項一致性群組
. 選擇*儲存>一致性群組*。
. 選取您要升級的一致性群組。
. 選擇「 ** 更多 ** 」、然後選擇「升級至父一致性群組」。
. 輸入一個 ** 名稱 ** ，然後爲子一致性組選擇一個 ** 組件類型 ** 。
. 選擇 ** 升級 ** 。


--
.CLI
--
從 ONTAP 9.14.1 開始、您可以使用 ONTAP CLI 將單一一致性群組移至父一致性群組下。

.開始之前
* 您必須處於管理權限層級、才能執行此工作。
* 從ONTAP 9.15.1 開始，任何具有管理員權限等級的使用者都可以執行此任務。在ONTAP 9.14.1 中，您必須是叢集或 SVM 管理員才能執行此任務。


.推廣子項一致性群組
. 推廣一致性群組。此命令會建立一個父一致性群組和一個子一致性群組。
+
`consistency-group promote -vserver _SVM_name_ -consistency-group _existing_consistency_group_ -new-name _new_child_consistency_group_`



--
====


== 將父實體降級為單一一致性群組

從 ONTAP 9.13.1 開始、您可以將父一致性群組降級為單一一致性群組。降級父級會展平一致性群組的階層、移除所有相關的子一致性群組。一致性群組中的所有磁碟區將保留在新的單一一致性群組之下。

.關於這項工作
* 將 _父子 一致性群組的現有快照降級為單一一致性後，這些快照仍然有效。該父實體的任何相關 _Chive_ 一致性群組的現有快照，在降級時即失效。子一致性群組中的個別磁碟區快照仍可作為磁碟區精細快照存取。


.步驟
[role="tabbed-block"]
====
.系統管理員
--
從 ONTAP 9.13.1 開始、您可以使用系統管理員執行此作業。

.降級一致性群組
. 選擇*儲存>一致性群組*。
. 選取您要降級的父一致性群組。
. 選擇「 ** 更多 ** 」、然後選擇「降級為單一一致性群組」 ** 。
. 系統將會發出警告訊息、告知您所有相關的子一致性群組都將被刪除、而其磁碟區將移至新的單一一致性群組之下。選擇 ** 降級 ** 以確認您瞭解其影響。


--
.CLI
--
從 ONTAP 9.14.1 開始、您可以使用 ONTAP CLI 降級一致性群組。

.開始之前
* 您必須處於管理權限層級、才能執行此工作。
* 從ONTAP 9.15.1 開始，任何具有管理員權限等級的使用者都可以執行此任務。在ONTAP 9.14.1 中，您必須是叢集或 SVM 管理員才能執行此任務。


.降級一致性群組
. 降級一致性群組。使用選用功能 `-new-name` 重新命名一致性群組的參數。
+
`consistency-group demote -vserver _SVM_name_ -consistency-group _parent_consistency_group_ [-new-name _new_consistency_group_name_]`



--
====