---
sidebar: sidebar 
permalink: concept_metrocluster_manage_nodes.html 
keywords: system manager, manage, metrocluster, clusters, nodes, mcc, HA, config, peering, peers, pairing, pairs 
summary: 從功能性的9.8開始ONTAP 、您可以MetroCluster 使用System Manager來管理功能性的運作。 
---
= 使用System Manager進行現場管理總覽MetroCluster
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
從功能介紹9.8開始ONTAP 、您可以使用System Manager作為簡化介面、來管理MetroCluster 功能介紹的設定。

支援的支援功能可讓兩個叢集彼此鏡射資料、因此當一個叢集當機時、資料不會遺失。MetroCluster

通常、組織會在兩個不同的地理位置設定叢集。每個位置的系統管理員都會設定叢集並加以設定。然後、其中一位系統管理員可以在叢集之間設定對等關係、以便共用資料。

該組織也可以在ONTAP 第三個位置安裝一個「不知道」。此功能可監控每個叢集的狀態。ONTAP當其中一個叢集偵測到無法與合作夥伴叢集通訊時、它會查詢監視器、以判斷錯誤是叢集系統或網路連線的問題。

如果網路連線發生問題、系統管理員會執行疑難排解方法來修正錯誤並重新連線。如果合作夥伴叢集關閉、另一個叢集會啟動切換程序、以控制兩個叢集的資料I/O。

您也可以執行切換、將其中一個叢集系統關閉以進行計畫性維護。合作夥伴叢集會處理兩個叢集的所有資料I/O作業、直到您啟動執行維護作業的叢集、然後執行切換作業為止。

您可以管理下列作業：

* link:task_metrocluster_setup.html["設定IP MetroCluster 站台"]
* link:task_metrocluster_peering.html["設定IP MetroCluster 速度"]
* link:task_metrocluster_configure.html["設定IP MetroCluster 站台"]
* link:task_metrocluster_switchover_switchback.html["執行IP MetroCluster 位址切換和切換"]
* link:task_metrocluster_troubleshooting.html["疑難排解IP MetroCluster 位址組態的問題"]
* link:task_metrocluster_ANDU_upgrade.html["在ONTAP 叢集上升級功能MetroCluster"]

