---
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  search: ontap, ontap-metrocluster, ontap-sm-classic, ontap-fli, ontap-flexarray,
    ontap-automation
  langs: zh-tw,us-en,ja-jp,zh-cn,ko-kr
sidebar:
  entries:
  - title: 文件ONTAP
    url: "/index.html"
  - title: 版本資訊
    url: https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508
  - section: introduction-concepts
  - section: setup-upgrade
  - section: cluster-admin
  - section: volume-admin
  - section: network-management
  - section: nas-management
  - section: san-management
  - section: object-storage-management
  - section: security-encryption
  - section: data-protection-disaster-recovery
  - section: event-performance-monitoring
  - title: 手冊頁ONTAP
    url: https://docs.netapp.com/us-en/ontap-cli-9111/index.html
  - title: 法律聲明
    url: "/reference_legal_notices.html"
