---
settings:
  name: ONTAP 9
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
    lipi_enabled: false
  search: ontap, ontap-metrocluster, ontap-sm-classic, ontap-fli, ontap-automation,
    ontap-cli-9141
  langs: zh-tw,us-en,ja-jp,ko-kr,zh-cn,de-de,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: 文件ONTAP
    url: "/index.html"
  - section: release-notes
  - title: System Manager與BlueXP整合
    url: "/sysmgr-integration-bluexp-concept.html"
  - section: introduction-concepts
  - section: setup-upgrade
  - section: cluster-admin
  - section: volume-admin
  - section: network-management
  - section: nas-management
  - section: san-management
  - section: object-storage-management
  - section: authentication-access-control
  - section: security-encryption
  - section: data-protection-disaster-recovery
  - section: event-performance-monitoring
  - title: 手冊頁ONTAP
    url: "/concepts/manual-pages.html"
  - title: 法律聲明
    url: "/legal-notices.html"
product-family:
  name: ONTAP
  repo: ontap-family
