---
sidebar: sidebar 
permalink: sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: 從功能更新至功能更新至功能更新至功能更新、系統管理程式與BlueXP完全整合ONTAP 。  有了BlueXP、您可以從單一控制面板管理混合式多雲端基礎架構、同時保留熟悉的System Manager儀表板。 
---
= System Manager與BlueXP整合
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
從功能更新至功能更新至功能更新至功能更新、系統管理程式與BlueXP完全整合ONTAP 。  有了BlueXP、您可以從單一控制面板管理混合式多雲端基礎架構、同時保留熟悉的System Manager儀表板。



== 整合概述

當您在內部部署ONTAP 的執行ONTAP 支援功能的叢集上存取System Manager時、系統會提示您直接從BlueXP管理叢集。從BlueXP開始、您將可存取您常用的System Manager介面、以及BlueXP功能的存取權限。

BlueXP可讓您建立及管理雲端儲存設備（例如Cloud Volumes ONTAP 、還原）、使用NetApp的資料服務（例如Cloud Backup）、以及控制許多內部部署和邊緣儲存設備。



== 從ONTAP BlueXP管理您的叢集

當您準備好從ONTAP BlueXP管理您的支援叢集時、您可以點選當您嘗試存取System Manager時出現的連結、或直接前往BlueXP。如果您想要使用BlueXP的資料服務來備份資料、掃描及分類資料等、直接前往BlueXP將會帶來一項優勢。



=== 使用System Manager的連結

當您從 Web 瀏覽器連線至叢集管理網路介面時，系統會提示您使用 BlueXP 中的系統管理員或 ONTAP 系統安裝的系統管理員版本來管理叢集。

若要在BlueXP中使用System Manager、請執行下列步驟：

.步驟
. 開啟網頁瀏覽器、然後輸入叢集管理網路介面的IP位址。
+
如果叢集已連線至BlueXP、則會顯示登入提示。

. 按一下*繼續至藍圖XP*以追蹤至藍圖XP的連結。
+

NOTE: 如果您的系統設定已封鎖外部網路、您將無法存取 BlueXP 。  若要使用 BlueXP 存取 System Manager 、您必須確定系統可以存取位址「 cloudmanager.cloud.netapp.com`" 」。  否則、您可以在提示時選擇使用 ONTAP 系統隨附的系統管理員版本。

. 在BlueXP登入頁面上、選取* NetApp 支援網站 使用您的支援中心認證登入*、然後輸入您的認證資料。
+
如果您已經使用過BlueXP並使用電子郵件和密碼登入、則需要繼續使用該登入選項。

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["深入瞭解如何登入BlueXP"^]。

. 如果出現提示、請輸入新的BlueXP帳戶名稱。
+
在大多數情況下、BlueXP會根據叢集的資料自動為您建立帳戶。

. 輸入叢集的叢集管理員認證。


.結果
System Manager隨即顯示、您現在可以從BlueXP管理叢集。



=== 直接從BlueXP探索叢集

BlueXP提供兩種探索和管理叢集的方法：

* 透過System Manager直接探索以進行管理
+
這與您追蹤重新導向的前一節所述的探索選項相同。

* 透過連接器探索
+
Connector是安裝在您環境中的軟體、可讓您透過System Manager存取管理功能、並存取提供資料複寫、備份與還原、資料分類、資料分層等功能的BlueXP雲端服務。



前往 https://docs.netapp.com/us-en/cloud-manager-family/index.html["BlueXP文件"^] 以深入瞭解這些探索與管理選項。



== 深入瞭解BlueXP

* https://docs.netapp.com/us-en/cloud-manager-family/concept-overview.html["藍圖XP總覽"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["透過BlueXP管理您的NetApp AFF 產品和FAS 功能"^]

