---
sidebar: sidebar 
permalink: task_metrocluster_troubleshooting.html 
keywords: system manager, troubleshoot, error, event, problem, metrocluster, maintenance, fix, correction, health, check 
summary: 您可以從MetroCluster 一個站台切換至另一個站台、以執行維護或從問題中恢復。 
---
= 疑難排解IP MetroCluster 位址組態的問題
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
從功能性的問題9.8開始ONTAP 、System Manager會監控IP MetroCluster 位址組態的健全狀況、並協助您找出並修正可能發生的問題。



== 《不健全狀況檢查》總覽MetroCluster

System Manager會定期檢查您IP MetroCluster 位址組態的健全狀況。  當您在MetroCluster 儀表板中檢視「介紹」區段時、通常會出現「MetroCluster 介紹系統狀況良好」的訊息。

不過、發生問題時、訊息會顯示事件數量。您可以按一下該訊息、檢視下列元件的健全狀況檢查結果：

* 節點
* 網路介面
* 階層（儲存設備）
* 叢集
* 連線
* Volume
* 組態複寫


「*狀態*」欄會指出哪些元件有問題、「*詳細資料*」欄則會建議您如何修正問題。



== 故障排除MetroCluster

.步驟
. 在System Manager中、選取* Dashboard *。
. 在* MetroCluster 《*》一節中、請注意訊息。
+
.. 如果訊息顯示MetroCluster 您的「不健全」組態、且叢集與ONTAP 「不健全」（以核取符號顯示）之間的連線正常、則您沒有問題可以修正。
.. 如果訊息中列出事件數目、或連線中斷（顯示為「X」）、請繼續下一步。


. 按一下顯示事件數目的訊息。
+
畫面上會顯示「系統健全狀況報告」MetroCluster 。

. 使用「*詳細資料*」欄中的建議、疑難排解報告中出現的問題。
. 當所有問題都已修正後、請按一下*檢查MetroCluster 「不健全狀況」*。
+

NOTE: 《不健全狀況檢查》MetroCluster 使用大量資源、因此建議您在執行檢查之前先執行所有疑難排解工作。

+
執行「系統健全狀況檢查」的背景。MetroCluster  您可以在等待其他工作完成的同時、處理其他工作。


