---
sidebar: sidebar 
permalink: task_cp_monitor_cluster_performance_ci.html 
keywords: netapp, ontap, cluster, performance, monitor, monitoring, headroom, cpu, cpus, data infrastructure insights, troubleshoot, optimize, private data center, Kafka, MongoDB, Nginx, Active IQ Unified Manager, cluster performance, monitor performance 
summary: 透過資料基礎設施洞察，您可以監控、排除故障並優化所有資源，包括公有雲和私有資料中心。 
---
= 使用 ONTAP 資料基礎架構洞察監控叢集效能
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp 資料基礎架構洞察是一款監控工具，可讓您深入了解整個基礎架構。透過資料基礎架構洞察，您可以監控、排除故障並優化所有資源，包括公有雲和私有資料中心。



== 數據基礎設施洞察有兩個版本

資料基礎架構洞察基礎版專為監控和最佳化您的 NetApp Data Fabric 資產而設計。它提供進階分析功能、可在FAS 環境中免費連接所有NetApp資源、包括HCI和All Flash更新（AFF 例如、英文）。

資料基礎設施洞察標準版不僅關注支援 NetApp Data Fabric 的基礎架構元件，還關注多供應商和多雲環境。有了豐富的功能、您就能獲得超過100項服務與資源的支援。

在當今的世界中、從內部部署資料中心到多個公有雲的資源都能發揮效用、因此從應用程式本身到儲存陣列後端磁碟的完整畫面是非常重要的。對應用程式監控的額外支援（例如Kafka、MongoDB和Ngin像）可提供您在最佳使用率和最佳風險緩衝區下運作所需的資訊和知識。

這兩種版本（基本版和標準版）都能與NetApp Active IQ Unified Manager 產品整合。使用 Active IQ Unified Manager 的客戶可以在資料基礎架構洞察使用者介面中查看加入資訊。 ActiveIQ Unified Manager 上發布的通知不會被忽略，並且可以與資料基礎架構洞察中的事件關聯。換句話說、您將獲得兩全其美的優勢。



== 監控、疑難排解及最佳化所有資源

數據基礎設施洞察可協助您大幅減少解決問題的時間並防止問題影響最終用戶。它也能協助您降低雲端基礎架構成本。透過可據以行動的情報來保護資料、可降低內部威脅的曝險。

資料基礎設施洞察讓您可以在一個地方查看整個混合基礎設施 - 從公有雲到資料中心。您可以立即建立相關的儀表板、以便根據您的特定需求進行自訂。您也可以建立特定且符合組織需求的目標式和條件式警示。

進階異常偵測功能可協助您在問題發生之前主動修正問題。  您可以自動檢視資源爭用和降級、以快速還原受影響的工作負載。  透過自動建立的階層關係、您堆疊中不同元件之間的疑難排解速度更快。

您可以在整個環境中找出未使用或已放棄的資源、協助您找出適當規模調整基礎架構並最佳化整體支出的機會。

資料基礎設施洞察可視化您的系統拓撲，以了解您的 Kubernetes 架構。您可以監控Kubernetes叢集的健全狀況、包括發生問題的節點、並在發現問題時放大。

資料基礎設施洞察透過先進的機器學習和異常檢測為您提供有關內部威脅的可操作情報，幫助您保護組織資料免受惡意或受感染用戶的濫用。

資料基礎設施洞察可協助您視覺化 Kubernetes 指標，以便您可以充分了解 pod、節點和叢集之間的關係。您可以評估叢集或正常運作的Pod的健全狀況、以及目前正在處理的負載、讓您能夠掌控K8S叢集、同時控制部署的健全狀況和成本。

.相關連結
* link:https://docs.netapp.com/us-en/cloudinsights/task_cloud_insights_onboarding_1.html["開始使用數據基礎設施洞察"^]

