---
sidebar: sidebar 
permalink: task_san_provision_vmware.html 
keywords: 'netapp, ontap, SAN, provisioning, provision, vmware, datastore, add lun, create, fc, iscsi, zone switches, storage, esxi host, Virtual Storage Console (VSC), vmware, vsphere' 
summary: 使用FC或iSCSI SAN傳輸協定搭配ONTAP 使用VMware System Manager（9.7及更新版本）、建立LUN、為ESXi主機提供儲存設備。LUN在ESXi主機上顯示為磁碟。 
---
= 為VMware資料存放區配置SAN儲存設備
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
此程序會在已設定FC或iSCSI傳輸協定的現有儲存VM上建立新的LUN。

如果您需要建立新的儲存VM並設定FC或iSCSI傳輸協定、請參閱 link:san-admin/configure-svm-fc-task.html["設定SVM for FC"] 或 link:san-admin/configure-svm-iscsi-task.html["設定SVM for iSCSI"]。


NOTE: 在LUN建立期間、一律會啟用非對稱邏輯單元存取（ALUA）。您無法變更ALUA設定。

從ONTAP 供應儲存設備開始、預設會啟用QoS。您可以在資源配置程序期間或稍後停用QoS或選擇自訂QoS原則。

完成此程序之後、您就可以使用VMware vSphere的虛擬儲存主控台（VSC）來管理VMware資料存放區。從VSC 7.0開始、VSC就是的一部分 https://docs.netapp.com/us-en/ontap-tools-vmware-vsphere/index.html["VMware vSphere虛擬應用裝置適用的工具ONTAP"^]包括VSC、用於儲存感知（VASA）供應商的vStorage API、以及用於VMware vSphere功能的儲存複寫介面卡（SRA）。

請務必檢查 https://imt.netapp.com/matrix/["NetApp 互通性對照表"^] 以確認您目前ONTAP 的更新版本與VSC版本之間的相容性。

如需詳細資訊、請參閱 https://docs.netapp.com/us-en/netapp-solutions/virtualization/vsphere_ontap_ontap_for_vsphere.html["TR-4597：VMware vSphere ONTAP for VMware"^] 以及VSC版本的文件。

[role="tabbed-block"]
====
.系統管理員
--
建立LUN、以提供ONTAP 適用於更新版本的System Manager儲存設備。

LUN在ESXi主機上顯示為磁碟。

若要使用System Manager Classic（ONTAP 適用於VMware 9.7及更早版本）設定ESXi主機對資料存放區的SAN傳輸協定存取、請參閱下列主題：

* https://docs.netapp.com/us-en/ontap-sm-classic/fc-config-esxi/index.html["使用VSC的ESXi FC組態總覽"^]
* https://docs.netapp.com/us-en/ontap-sm-classic/iscsi-config-esxi/index.html["使用VSC的ESXi iSCSI組態總覽"^]



NOTE: 在LUN建立期間、一律會啟用非對稱邏輯單元存取（ALUA）。您無法變更ALUA設定。

.步驟
. 在System Manager中、按一下* Storage > LUN*、然後按一下* Add*。
. 輸入建立LUN所需的資訊。
. 視ONTAP 您的版本而定、您可以按一下*更多選項*來執行下列任何一項。
+
[cols="80,20"]
|===


| 選項 | 從開始提供 


 a| 
** 將QoS原則指派給LUN、而非父Volume
+
*** *更多選項>儲存與最佳化*
*** 選擇*效能服務層級*。
*** 若要將QoS原則套用至個別LUN而非整個磁碟區、請選取*將這些效能限制強制套用至每個LUN*。
+
根據預設、效能限制會套用至Volume層級。




| 零點9.10.1 ONTAP 


 a| 
** 使用現有的啟動器群組建立新的啟動器群組
+
*** *更多選項>主機資訊*
*** 使用現有的啟動器群組*選取*新的啟動器群組。
+
*附註*：包含其他igroup的igroup的OS類型無法在建立之後變更。




| 部分9.9.1 ONTAP 


 a| 
** 將說明新增至igroup或主機啟動器
+
此說明可做為igroup或主機啟動器的別名。

+
*** *更多選項>主機資訊*



| 部分9.9.1 ONTAP 


 a| 
** 在現有磁碟區上建立LUN
+
根據預設、新的LUN會建立在新的Volume中。

+
*** *更多選項>新增LUN*
*** 選擇*組相關LUN*。



| 部分9.9.1 ONTAP 


 a| 
** 停用QoS或選擇自訂QoS原則
+
*** *更多選項>儲存與最佳化*
*** 選擇*效能服務層級*。
+
*附註*：ONTAP 在S209.9.1及更新版本中、如果您選取自訂QoS原則、也可以選取手動放置在指定的本機層。




| 部分9.8 ONTAP 
|===


. 對於FC、請根據WWPN對FC交換器進行分區。每個啟動器使用一個區域、並在每個區域中包含所有目標連接埠。
. 使用VMware vSphere的虛擬儲存主控台（VSC）來探索及初始化LUN。
. 確認ESXi主機可在LUN上寫入和讀取資料。


--
.CLI
--
建立LUN、以ONTAP 利用NetApp CLI提供儲存設備。

. 使用「系統授權show」命令來驗證您是否擁有FC或iSCSI的授權。
+
「系統授權展示」

+
[listing]
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----
. 如果您沒有FC或iSCSI的授權、請使用「license add」命令。
+
「license add -license code-code-_y_your less_code_」

. 在SVM上啟用您的傳輸協定服務：
+
*對於iSCSI：*「vserver iSCSI create -vserver _vserver_name_-target別名_vserver_name_」

+
*對於FC：*「vserver FCP create -vserver _vserver_name_-stue-admin up」

. 在每個節點上為SVM建立兩個生命期：
+
「網路介面create -vserver _vserver_name_-lif_lif_name_-role data -data傳輸協定iscsiSCSI|fc-home-node_node_name_-home-port _port_name_-address_ip_address_-netmask_`

+
NetApp為每個SVM服務資料的每個節點至少支援一個iSCSI或FC LIF。不過、備援需要每個節點兩個生命期。

. 確認您的生命已建立、且其作業狀態為「線上」：
+
「網路介面show -vserver _vserver_name__lif_name_」

. 建立LUN：
+
「LUN create -vserver vserver_name -volume _volume _name_-LUN _lun_name_-size _lun_size_-osttype Linux -space-Reserve enabled| disabled'

+
您的LUN名稱不得超過255個字元、且不得包含空格。

+

NOTE: 在磁碟區中建立LUN時、NVFIL選項會自動啟用。

. 建立您的igroup：
+
"igroup create -vserver _vserver_name_-igroup _igroup_name_-protocol FCP | iscs|混合類型Linux -initiator _name_"

. 將LUN對應至igroup：
+
"LUN對應會建立-vserver _vserver_name_-volume _volume _name_-LUN _lun_name_-igroup _igroup_name_"

. 驗證LUN的設定是否正確：
+
「LUN show -vserver _vserver_name_」

. link:san-admin/create-port-sets-binding-igroups-task.html["建立連接埠集並繫結至igroup"] （選用）。
. 請遵循主機文件中的步驟、在特定主機上啟用區塊存取。
. 使用主機公用程式完成FC或iSCSI對應、並探索主機上的LUN。


--
====
https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN主機組態ONTAP"]
link:./san-admin/index.html["SAN管理總覽"]
https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["在System Manager中檢視及管理SAN啟動器群組"]
http://www.netapp.com/us/media/tr-4017.pdf["NetApp技術報告4017：Fibre Channel SAN最佳實務做法"]
