---
sidebar: sidebar 
permalink: task_san_configure_protection_for_business_continuity.html 
keywords: SM-BC, snapmirror business continuity, consistency group, remote protection, 9.8, 9.9.1, destination 
summary: 設定業務持續性保護包括在ONTAP 來源叢集上選取LUN、然後將其新增至一致性群組。 
---
= 使用 SnapMirror 業務持續運作來保護
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用 SnapMirror Business Continuity 設定保護包括在 ONTAP 來源叢集上選取 LUN 、並將其新增至一致性群組。

.開始之前
* 您必須擁有 SnapMirror Synchronous 授權。
* 您必須是叢集或儲存VM管理員。
* 一致性群組中的所有組成磁碟區都必須位於單一儲存 VM （ SVM ）中。
+
** LUN可位於不同的磁碟區。


* 來源與目的地叢集不能相同。
* 您無法在 ASA 叢集和非 ASA 叢集之間建立 SM-BC 一致性群組關係。
* SM-BC需要預設IPspace才能建立叢集對等關係。不支援自訂IPspace。
* 一致性群組的名稱必須是唯一的。
* 次要（目的地）叢集上的磁碟區必須是 DP 類型。
* 主要和次要 SVM 必須處於對等關係中。


.步驟
您可以使用 ONTAP CLI 或系統管理員來設定一致性群組。

從 ONTAP 9.10.1 開始、 ONTAP 在 System Manager 中提供一致性群組端點和功能表、提供額外的管理公用程式。如果您使用的是 ONTAP 9.10.1 或更新版本、請參閱 link:./consistency-groups/configure-task.html["設定一致性群組"] 然後 link:./consistency-groups/protect-task.html["設定保護"] 建立 SM-BC 關係。

[role="tabbed-block"]
====
.系統管理員
--
. 在主叢集上、瀏覽至 * 保護 > 總覽 > 保護業務持續運作 > 保護 LUN* 。
. 選取您要保護的 LUN 、並將其新增至保護群組。
. 選取目的地叢集和SVM。
. *依預設會選取「初始化關係」*。按一下「*儲存*」開始保護。
. 請前往*儀表板>效能*以驗證LUN的IOPS活動。
. 在目的地叢集上、使用System Manager驗證是否已同步保護營運不中斷關係：*保護>關係*。


--
.CLI
--
. 從目的地叢集建立一致性群組關係。
「目的地：： > SnapMirror 建立來源路徑 _ 來源路徑 _ 目的地路徑 _ 目的地路徑 _ -CM-item - 對應 _ Volume 路徑 _ - 原則 _ 原則名稱 _
+
您可以使用對應最多 12 個組成 Volume `cg-item-mappings` 上的參數 `snapmirror create` 命令。

+
以下範例建立兩個一致性群組： `cg_src_ on the source with `vol1` 和 `vol2` 以及鏡射目的地一致性群組、 `cg_dst`。

+
`destination::> snapmirror create -source-path vs1_src:/cg/cg_src -destination-path vs1_dst:/cg/cg_dst -cg-item-mappings vol_src1:@vol_dst1,vol_src2:@vol_dst2 -policy AutomatedFailOver`

. 從目的地叢集初始化一致性群組。
+
`destination::>snapmirror initialize -destination-path _destination-consistency-group_`

. 確認初始化作業已成功完成。狀態應為 `InSync`。
+
`snapmirror show`

. 在每個叢集上建立一個 igroup 、以便將 LUN 對應至應用程式主機上的啟動器。
`lun igroup create -igroup _name_ -protocol _fcp|iscsi_ -ostype _os_ -initiator _initiator_name_`
. 在每個叢集上、將 LUN 對應至 igroup ：
+
`lun map -path _path_name_ -igroup _igroup_name_`

. 使用驗證 LUN 對應是否成功完成 `lun map` 命令。然後、您可以在應用程式主機上探索新的 LUN 。


--
====