---
sidebar: sidebar 
permalink: task_metrocluster_setup.html 
keywords: system manager, metrocluster, set up, setup, start, initialize, cluster, config, nodes 
summary: 從功能介紹9.8開始ONTAP 、您可以使用System Manager設定MetroCluster 一個站台的IP組態。 
---
= 設定IP MetroCluster 站台
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
從功能介紹9.8開始ONTAP 、您可以使用System Manager設定MetroCluster 一個站台的IP組態。

一個由兩個叢集組成的站台。MetroCluster通常、叢集位於不同的地理位置。

.開始之前
* 您的系統應已依照安裝和纜線連接 https://["安裝與設定指示"^] 系統隨附的。
* 應在每個叢集的每個節點上設定叢集網路介面、以進行叢集內通訊。




== 指派節點管理IP位址



=== Windows系統

您應該將Windows電腦連線至與控制器相同的子網路。這會自動將節點管理IP位址指派給您的系統。

.步驟
. 從Windows系統中、開啟*網路*磁碟機以探索節點。
. 按兩下節點以啟動叢集設定精靈。




=== 其他系統

您應該為叢集中的其中一個節點設定節點管理IP位址。您可以使用此節點管理IP位址來啟動叢集設定精靈。

請參閱 link:./software_setup/task_create_the_cluster_on_the_first_node.html["在第一個節點上建立叢集"] 以取得指派節點管理IP位址的相關資訊。



== 初始化及設定叢集

您可以設定叢集的管理密碼、並設定叢集管理和節點管理網路、以初始化叢集。您也可以設定DNS伺服器等服務來解析主機名稱、以及設定NTP伺服器來同步時間。

.步驟
. 在網頁瀏覽器上、輸入您已設定的節點管理IP位址： "https://[]
+
System Manager會自動探索叢集中的其餘節點。

. 在*初始化儲存系統*視窗中、執行下列步驟：
+
.. 輸入叢集管理網路組態資料。
.. 輸入所有節點的節點管理IP位址。
.. 提供網域名稱伺服器（DNS）詳細資料。
.. 在*其他*區段中、選取標有*使用時間服務（NTP）*的核取方塊以新增時間伺服器。




按一下「*提交*」時、請等待叢集的建立與設定。然後進行驗證程序。

.接下來呢？
設定、初始化及設定兩個叢集之後、請執行下列程序：

* link:task_metrocluster_peering.html["設定IP MetroCluster 速度"]




== 在ONTAP 新的叢集影片上設定功能

video::PiX41bospbQ[youtube,width=848,height=480]