---
sidebar: sidebar 
permalink: task_admin_view_submit_support_cases.html 
keywords: support, case, view, submit, active iq, telemetry, log, logging 
summary: 從更新版9.9開始ONTAP 、您可以檢視Active IQ 與叢集相關的支援案例、並檢視提交新支援案例所需的資訊。從ONTAP 功能支援部門9.10.1開始、您可以啟用遙測記錄功能、協助支援人員疑難排解問題。 
---
= 檢視並提交支援案例
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
從ONTAP 功能支援9.9.1開始、您可以檢視Active IQ 與叢集相關的支援案例。您也可以複製叢集詳細資料，以便在 NetApp 支援網站上提交新的支援案例。從ONTAP 功能支援部門9.10.1開始、您可以啟用遙測記錄功能、協助支援人員疑難排解問題。


NOTE: 若要接收韌體更新的相關警示、您必須向Active IQ Unified Manager NetApp註冊。請參閱 link:https://netapp.com/support-and-training/documentation/active-iq-unified-manager["支援的文件資源Active IQ Unified Manager"^]。

.步驟
. 在System Manager中、選取* Support*。
+
隨即顯示與此叢集相關的開放式支援案例清單。

. 按一下下列連結以執行程序：
+
** *案例編號*：請參閱案例詳細資料。
** *移至NetApp支援網站*：瀏覽AutoSupport 至NetApp支援網站上的* My示例*頁面、以檢視知識庫文章或提交新的支援案例。
** *查看我的案例*：瀏覽至NetApp支援網站上的*我的案例*頁面。
** *檢視叢集詳細資料*：檢視並複製提交新案例時所需的資訊。






== 啟用遙測記錄

從ONTAP 《支援資料》9.10.1開始、您可以使用System Manager來啟用遙測記錄功能。當允許遙測記錄時、系統管理員所記錄的訊息會指定特定的遙測識別碼、指出觸發訊息的確切程序。與該程序相關的所有訊息都有相同的識別碼、其中包含作業工作流程名稱和編號（例如「add-volume -1941290」）。

如果遇到效能問題、您可以啟用遙測記錄、讓支援人員更容易識別發出訊息的特定程序。將遙測識別碼新增至訊息時、記錄檔只會稍微放大。

.步驟
. 在System Manager中、選取*叢集>設定*。
. 在「* UI設定*」區段中、按一下「允許遙測記錄*」核取方塊。

