---
sidebar: sidebar 
permalink: task_asa_software_configuration.html 
keywords: all san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: 請使用下列程序、使用System Manager來設定All SAN Array。 
---
= 所有SAN陣列軟體組態
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
請使用下列程序、使用System Manager來設定All SAN Array。



== 支援所有SAN陣列組態

NetApp All SAN Array（ASA）是以獲證實AFF 的NetApp平台為基礎、打造的純Flash SAN解決方案。

此功能可在雙節點交換式或無交換式叢集上使用、也可針對FC或iSCSI進行設定、並可針對多重路徑使用對稱雙主動式。ASA所有路徑都是主動/最佳化的、因此在發生儲存容錯移轉時、主機不需要等待容錯移轉路徑的ALUA轉換、即可恢復I/O如此可縮短容錯移轉的時間。


NOTE: 有了NetApp 9.9、客戶現在可以擴充多達12個節點的支援功能。ONTAP AFF ASAASA在ONTAP 更新版本的更新版本中受到支援。支援的組態列於 link:http://mysupport.netapp.com/matrix/["NetApp 互通性對照表工具"^]。

link:http://www.netapp.com/us/media/tr-4515.pdf["NetApp技術報告4515：ONTAP AFF 《全SAN陣列系統》"^]
 link:http://www.netapp.com/us/media/tr-4080.pdf["NetApp技術報告4080：可擴充SAN ONTAP 的最佳實務做法9"^]



== 設定ASA 一個功能完善的

所有SAN陣列（ASA）的設定程序與非ASA系統相同。

System Manager會引導您完成初始化叢集、建立本機層級、設定通訊協定、以及為ASA 您的支援資源配置儲存設備所需的程序。請參閱的步驟 xref:task_configure_ontap.html[設定ONTAP 功能]。



== 部分組態限制ASA

您應該使用AFF 針對「完整的SAN陣列ASA （ESCSI）」控制器所建立的已測試及支援的最大組態限制。為確保可靠作業、您不應超過中所列的目前已測試及支援限制 link:https://hwu.netapp.com/["NetApp Hardware Universe"^]。

從推出支援非MetroCluster IP組態的ONTAP 版本起、最多AFF ASA 可支援12個節點、MetroCluster 而支援多達8個節點、以利進行支援。

此外ONTAP 、從支援支援NVM9.9.1開始、所有AFF ASA 的支援都支援NVMe傳輸協定、但不支援MetroCluster 針對功能進行設定的控制器。不支援NVMe組態。MetroCluster



== 支援持續連接埠

從功能部件號9.8開始ONTAP 、所有配置為使用FC傳輸協定的SAN陣列（ASA）、預設會啟用持續連接埠。持續連接埠僅適用於FC、且需要由全球連接埠名稱（WWPN）識別的區域成員資格。

持續連接埠可在HA合作夥伴的對應實體連接埠上建立陰影LIF、藉此降低接管的影響。接管節點時、合作夥伴節點上的陰影LIF會採用原始LIF的身分識別、包括WWPNe。在將接管節點的路徑狀態變更為故障之前、陰影LIF會顯示為通往主機MPIO堆疊的主動/最佳化路徑、並會移動I/O。如此可減少I/O中斷、因為即使在儲存容錯移轉作業期間、主機仍會看到相同數量的目標路徑。

對於持續連接埠、HA配對內的下列FCP連接埠特性應該相同：

* FCP連接埠數
* FCP連接埠名稱
* FCP連接埠速度
* FCP LIF WWPN型分區


如果HA配對中有任何特性不相同、就會產生下列EMS訊息：

《EMS：scsiblade.lif.persistent.ports.fcp.init.error`》

如需持續連接埠的詳細資訊、請參閱 link:http://www.netapp.com/us/media/tr-4080.pdf["NetApp技術報告4080：可擴充SAN ONTAP 的最佳實務做法9"^]。



== 支援主機設定與公用程式ASA

設定所有SAN陣列（ASA）的主機設定與所有其他SAN主機的設定相同。

您可以下載 link:https://mysupport.netapp.com/NOW/cgi-bin/software["NetApp主機公用程式軟體"^] 支援網站上的特定主機。



== 辨ASA 識出一套系統的方法

您可以ASA 使用System Manager或ONTAP 使用指令行介面（CLI）來識別出一個無法辨識的系統。

在System Manager儀表板中、按一下*叢集>總覽*、然後選取系統節點。*特性*顯示為*所有SAN陣列*。

在CLI中、您可以使用「shan config show」命令。「All SAN Array（所有SAN陣列）」的值會傳回ASA 為「true（真實）」的不實。
