---
sidebar: sidebar 
permalink: task_nas_provision_flexgroup.html 
keywords: netapp, ontap, provision, provisioning, nas, large file systems, using, FlexGroup, windows, servers, cifs, smb, FlexVol volume limits, load distribution, work load, workload, balancing, data 
summary: 這個可擴充的NAS容器可提供高效能、並可自動分配負載。FlexGroup支援大量容量（以PB為單位）、大幅超越了整個流程的範圍、而且不會增加任何管理成本。FlexGroup FlexVol 
---
= 為使用FlexGroup 「供應」功能的大型檔案系統配置NAS儲存設備
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
這個可擴充的NAS容器可提供高效能、並可自動分配負載。FlexGroup支援大量容量（以PB為單位）、大幅超越了整個流程的範圍、而且不會增加任何管理成本。FlexGroup FlexVol

本節主題說明如何使用FlexGroup 系統管理ONTAP 程式來管理更新版本中的更新版本。如果您使用的是經典系統管理程式（僅ONTAP 適用於更新版本的版本）、請參閱本主題：

* https://docs.netapp.com/us-en/ontap-sm-classic/online-help-96-97/task_creating_flexgroup_volumes.html["建立FlexGroup 功能區"^]


從ONTAP 支援的範圍僅為0.9.9.1開始、SnapMirror會展開兩FlexGroup 個以上的支援範圍、最多可支援八個扇形區。System Manager不支援SnapMirror串聯FlexGroup 式的等量資料磁碟區關係。

自動選擇建立此功能所需的本機層級。ONTAP FlexGroup


NOTE: 從ONTAP 供應儲存設備開始、預設會啟用QoS。您可以在資源配置程序期間或稍後停用QoS或選擇自訂QoS原則。

.步驟
. 按一下「*儲存設備>磁碟區*」。
. 按一下「 * 新增 * 」。
. 按一下*「更多選項」*、然後選取*跨叢集散佈磁碟區資料*。
+
.. 如果您執行ONTAP 的是支援功能的9.8或更新版本、而您想要停用QoS或選擇自訂QoS原則、請按一下*更多選項*、然後在*儲存與最佳化*下選取*效能服務層級*。






== 影片



=== 建立及管理FlexGroup 一份功能不全的磁碟區

video::gB-yF1UTv2I[youtube, width=848,height=480]


== FlexGrop Volume：事半功倍

video::0B4nlChf0b4[youtube, width=848,height=480]