---
sidebar: sidebar 
permalink: task_metrocluster_peering.html 
keywords: metrocluster, peer, peering, pair, pairing, configuration, config, mcc, HA 
summary: 從功能上說起ONTAP 、您可以MetroCluster 使用System Manager來管理IP站台的作業。  設定兩個叢集之後、您可以在它們之間設定對等關係。 
---
= 設定IP MetroCluster 速度
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
從功能上說ONTAP 起、您可以使用MetroCluster System Manager來管理整個作業系統的IP組態。設定兩個叢集之後、您可以在它們之間設定對等關係。

.開始之前
您應該已完成下列程序、以設定兩個叢集：

* link:task_metrocluster_setup.html["設定IP MetroCluster 站台"]


此程序的某些步驟是由位於每個叢集地理站台的不同系統管理員執行。  為了說明此程序、叢集稱為「站台A叢集」和「站台B叢集」。



== 從站台A執行對等程序

此程序由站台A的系統管理員執行

.步驟
. 登入站台A叢集。
. 在System Manager中、從左導覽欄中選取*儀表板*、以顯示叢集概觀。
+
儀表板會顯示此叢集（站台A）的詳細資料。  在* MetroCluster 《*》（*《*》）區段中、左側會顯示站台叢集。

. 按一下*附加合作夥伴叢集*。
. 輸入網路介面的詳細資料、讓站台A叢集中的節點能夠與站台B叢集中的節點通訊。
. 按一下*儲存並繼續*。
. 在「*附加合作夥伴叢集*」視窗中、選取「*我沒有密碼*」、即可產生密碼。
. 複製產生的通關密碼、並與站台B的系統管理員分享
. 選擇*關閉*。




== 從站台B執行對等程序

此程序由站台B的系統管理員執行

.步驟
. 登入站台B叢集。
. 在System Manager中、選取* Dashboard *以顯示叢集總覽。
+
儀表板會顯示此叢集（站台B）的詳細資料。  在「功能表」區段中、站台B叢集會顯示在左側。MetroCluster

. 按一下*附加合作夥伴叢集*以開始對等處理程序。
. 輸入網路介面的詳細資料、以允許站台B叢集中的節點與站台A叢集中的節點進行通訊。
. 按一下*儲存並繼續*。
. 在「*附加合作夥伴叢集*」視窗中、選取「*我有通關密碼*」、即可輸入您從站台A的系統管理員處收到的通關密碼
. 選取* Pee*以完成對等程序。


.接下來呢？
當對等程序成功完成之後、您就可以設定叢集。  請參閱 link:task_metrocluster_configure.html["設定IP MetroCluster 站台"]。
