---
sidebar: sidebar 
permalink: task_san_provision_windows.html 
keywords: netapp, ontap, san, provisioning, windows, servers, provision, create, add, lun, fc, iscsi, san, zone switches, storage, windows mpio, disk 
summary: 建立LUN以使用FC或iSCSI SAN傳輸協定為Windows伺服器提供儲存設備。LUN在Windows主機上顯示為磁碟 
---
= 為Windows伺服器配置SAN儲存設備
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
此程序會在已設定FC或iSCSI傳輸協定的現有儲存VM上建立新的LUN。

如果您需要建立新的儲存VM並設定FC或iSCSI傳輸協定、請參閱 link:san-admin/configure-svm-fc-task.html["設定SVM for FC"] 或 link:san-admin/configure-svm-iscsi-task.html["設定SVM for iSCSI"]。

LUN在Windows主機上顯示為磁碟。


NOTE: 在LUN建立期間、一律會啟用非對稱邏輯單元存取（ALUA）。您無法變更ALUA設定。

從ONTAP 供應儲存設備開始、預設會啟用QoS。您可以在資源配置程序期間或稍後停用QoS或選擇自訂QoS原則。

[role="tabbed-block"]
====
.系統管理員
--
使用FC或iSCSI SAN傳輸協定搭配ONTAP 使用《支援更新版本的系統管理程式》（9.7及更新版本）、建立LUN、為Windows伺服器提供儲存設備。

若要使用System Manager Classic（9.7及更早版本提供）完成此工作、請參閱 https://docs.netapp.com/us-en/ontap-sm-classic/iscsi-config-windows/index.html["適用於Windows的iSCSI組態"^]

.步驟
. 在Windows伺服器上、安裝原生的DSM for Windows MPIO。
. 在System Manager中、按一下* Storage > LUN*、然後按一下* Add*。
. 輸入建立LUN所需的資訊。
. 視ONTAP 您的版本而定、您可以按一下*更多選項*來執行下列任何一項。
+
[cols="80,20"]
|===


| 選項 | 從開始提供 


 a| 
** 將QoS原則指派給LUN、而非父Volume
+
*** *更多選項>儲存與最佳化*
*** 選擇*效能服務層級*。
*** 若要將QoS原則套用至個別LUN而非整個磁碟區、請選取*將這些效能限制強制套用至每個LUN*。
+
根據預設、效能限制會套用至Volume層級。




| 零點9.10.1 ONTAP 


 a| 
** 使用現有的啟動器群組建立新的啟動器群組
+
*** *更多選項>主機資訊*
*** 使用現有的啟動器群組*選取*新的啟動器群組。
+
*附註*：包含其他igroup的igroup的OS類型無法在建立之後變更。




| 部分9.9.1 ONTAP 


 a| 
** 將說明新增至igroup或主機啟動器
+
此說明可做為igroup或主機啟動器的別名。

+
*** *更多選項>主機資訊*



| 部分9.9.1 ONTAP 


 a| 
** 在現有磁碟區上建立LUN
+
根據預設、新的LUN會建立在新的Volume中。

+
*** *更多選項>新增LUN*
*** 選擇*組相關LUN*。



| 部分9.9.1 ONTAP 


 a| 
** 停用QoS或選擇自訂QoS原則
+
*** *更多選項>儲存與最佳化*
*** 選擇*效能服務層級*。
+
*附註*：ONTAP 在S209.9.1及更新版本中、如果您選取自訂QoS原則、也可以選取手動放置在指定的本機層。




| 部分9.8 ONTAP 
|===


. 對於FC、請根據WWPN對FC交換器進行分區。每個啟動器使用一個區域、並在每個區域中包含所有目標連接埠。
. 在Windows伺服器上探索新的LUN。
. 初始化LUN、並選擇性地使用檔案系統進行格式化。
. 確認Windows伺服器可在LUN上寫入和讀取資料。


--
.CLI
--
使用FC或iSCSI SAN傳輸協定搭配ONTAP 使用CLI建立LUN、為Windows伺服器提供儲存設備。

. 使用「系統授權show」命令來驗證您是否擁有FC或iSCSI的授權。
+
「系統授權展示」

+
[listing]
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----
. 如果您沒有FC或iSCSI的授權、請使用「license add」命令。
+
「license add -license code-code-_y_your less_code_」

. 在SVM上啟用您的傳輸協定服務：
+
*對於iSCSI：*「vserver iSCSI create -vserver _vserver_name_-target別名_vserver_name_」

+
*對於FC：*「vserver FCP create -vserver _vserver_name_-stue-admin up」

. 在每個節點上為SVM建立兩個生命期：
+
「網路介面create -vserver _vserver_name_-lif_lif_name_-role data -data傳輸協定iscsiSCSI|fc-home-node_node_name_-home-port _port_name_-address_ip_address_-netmask_`

+
NetApp為每個SVM服務資料的每個節點至少支援一個iSCSI或FC LIF。不過、備援需要每個節點兩個生命期。

. 確認您的生命已建立、且其作業狀態為「線上」：
+
「網路介面show -vserver _vserver_name__lif_name_」

. 建立LUN：
+
「LUN create -vserver vserver_name -volume _volume _name_-LUN _lun_name_-size _lun_size_-osttype Linux -space-Reserve enabled| disabled'

+
您的LUN名稱不得超過255個字元、且不得包含空格。

+

NOTE: 在磁碟區中建立LUN時、NVFIL選項會自動啟用。

. 建立您的igroup：
+
"igroup create -vserver _vserver_name_-igroup _igroup_name_-protocol FCP | iscs|混合類型Linux -initiator _name_"

. 將LUN對應至igroup：
+
"LUN對應會建立-vserver _vserver_name_-volume _volume _name_-LUN _lun_name_-igroup _igroup_name_"

. 驗證LUN的設定是否正確：
+
「LUN show -vserver _vserver_name_」

. link:san-admin/create-port-sets-binding-igroups-task.html["建立連接埠集並繫結至igroup"] （選用）。
. 請遵循主機文件中的步驟、在特定主機上啟用區塊存取。
. 使用主機公用程式完成FC或iSCSI對應、並探索主機上的LUN。


--
====
.相關資訊
https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN主機組態ONTAP"]
link:./san-admin/index.html["SAN管理總覽"]
https://docs.netapp.com/us-en/ontap/san-admin/manage-san-initiators-task.html["在System Manager中檢視及管理SAN啟動器群組"]
http://www.netapp.com/us/media/tr-4017.pdf["NetApp技術報告4017：Fibre Channel SAN最佳實務做法"]
