---
permalink: element-replication/create-replication-relationship-task.html 
sidebar: sidebar 
keywords: create, relationship, element, source, ontap, destination 
summary: 您可以使用SnapMirror將元素Volume的Snapshot複本複製到ONTAP 一個目的地系統。萬一Element站台發生災難、您可以從ONTAP 該系統將資料提供給用戶端、然後在恢復服務時重新啟動Element來源Volume。 
---
= 建立從元素來源到ONTAP 目的地的關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
一線儲存設備中的來源磁碟區與二線儲存設備中的目的地磁碟區之間的關係稱為_DATA保護關係_。您可以使用「napmirror create」命令、從元素來源建立資料保護關係、從ONTAP 元素來源建立資料保護關係、到目的地、ONTAP 或從來源到元素目的地。

您可以使用SnapMirror將元素Volume的Snapshot複本複製到ONTAP 一個目的地系統。萬一Element站台發生災難、您可以從ONTAP 該系統將資料提供給用戶端、然後在恢復服務時重新啟動Element來源Volume。

.開始之前
* 包含要複寫之磁碟區的元素節點必須可供ONTAP 支援的項目。
* 必須已啟用元素Volume才能進行SnapMirror複寫。
* 如果您使用的是「鏡射-保存庫」原則類型、則必須設定SnapMirror標籤、以便複寫元素Snapshot複本。
+
[NOTE]
====
您只能在Element軟體Web UI中執行此工作。如需詳細資訊、請參閱 https://docs.netapp.com/us-en/element-software/index.html["元素文件"]。

====


您必須以「_hostip：_/LUN/_name_」格式指定元素來源路徑、其中「LUN」是實際字串「LUN」、而「名稱」是元素Volume的名稱。

元素Volume大致相當ONTAP 於一個實體LUN。當元素軟體與ONTAP SnapMirror之間的資料保護關係初始化時、SnapMirror會建立一個名稱為Element Volume的LUN。如果LUN符合從Element軟體複製到ONTAP SnapMirror的要求、SnapMirror會將資料複寫到現有LUN。

複寫規則如下：

* 僅一個元素磁碟區的資料可包含在其中。ONTAP
* 您無法將資料從ONTAP 一個現象磁碟區複製到多個元素磁碟區。


在不含更新版本的版本中、目的地Volume最多可包含251個Snapshot複本。ONTAP在0、9.4及更新版本中、目的地Volume最多可包含1019個Snapshot複本。ONTAP

.步驟
. 從目的地叢集建立從元素來源到ONTAP 目的地的複寫關係：
+
「napmirror create -source-path _hostip:_/LUN/名稱-dite-path _svm:volume _|_cluster：//Svm/volume _-輸入XDP -schedule schedule -policy _'

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例使用預設的「鏡像Latest（鏡像最新）原則建立SnapMirror DR關係：

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorLatest
----
+
以下範例使用預設的「鏡像AndVault（鏡像AndVault）原則建立統一化複寫關係：

+
[listing]
----
cluster_dst:> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy MirrorAndVault
----
+
以下範例使用「Unified7fay（統一7年））原則建立統一化的複寫關係：

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy Unified7year
----
+
以下範例使用自訂的「my_Unified」原則建立統一化複寫關係：

+
[listing]
----
cluster_dst::> snapmirror create -source-path 10.0.0.11:/lun/0005 -destination-path svm_backup:volA_dst -type XDP -schedule my_daily -policy my_unified
----


使用「napmirror show」命令來驗證SnapMirror關係是否已建立。如需完整的命令語法、請參閱手冊頁。
