---
permalink: tape-backup/assign-tape-aliases-concept.html 
sidebar: sidebar 
keywords: aliasing, ppn, physical, path, name, sn, serial, number, medium, changer, alias, name 
summary: 混疊可簡化裝置識別程序。別名會將磁帶或媒體更換器的實體路徑名稱（PPN）或序號（SN）連結至持續但可修改的別名。 
---
= 磁帶別名總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
混疊可簡化裝置識別程序。別名會將磁帶或媒體更換器的實體路徑名稱（PPN）或序號（SN）連結至持續但可修改的別名。

下表說明磁帶別名如何讓您確保磁帶機（或磁帶庫或媒體交換器）永遠與單一別名相關聯：

|===
| 案例 | 重新指派別名 


 a| 
系統重新開機時
 a| 
磁帶機會自動重新指派先前的別名。



 a| 
當磁帶設備移至另一個連接埠時
 a| 
別名可調整為指向新位址。



 a| 
當多個系統使用特定的磁帶設備時
 a| 
使用者可將所有系統的別名設定為相同。

|===
[NOTE]
====
當您從Data ONTAP f2 8.1.x升級Data ONTAP 至f2 8.2.x時、Data ONTAP 使用的磁帶別名功能會修改現有的磁帶別名。在這種情況下、您可能必須更新備份應用程式中的磁帶別名。

====
指派磁帶別名可在備份裝置（例如st0或mc1）的邏輯名稱與永久指派給連接埠、磁帶機或媒體更換器的名稱之間提供對應關係。

[NOTE]
====
st0和st00是不同的邏輯名稱。

====
[NOTE]
====
邏輯名稱和序號僅用於存取裝置。存取裝置之後、它會使用實體路徑名稱傳回所有錯誤訊息。

====
有兩種名稱可供別名使用：實體路徑名稱和序號。



== 了解物理路徑名

實體路徑名稱（PPN）是ONTAP 根據連接至儲存系統的SCSI-2/3介面卡或交換器（特定位置）、將資料指派給磁帶機和磁帶庫的數字位址順序。PPNS也稱為電子名稱。

直接附加裝置的 PPNS 使用下列格式： `host_adapter`。 `device_id_lun`

[NOTE]
====
LUN 值只會顯示於 LUN 值不是零的磁帶與媒體交換器裝置、也就是 LUN 值為零的情況下 `lun` 不顯示 PPN 的一部分。

====
例如、PPN 8.6表示主機介面卡編號為8、裝置ID為6、邏輯單元編號（LUN）為0。

SAS磁帶設備也是直接附加的設備。例如、PPN 5c-4表示在儲存系統中、SAS HBA連接至插槽5、SAS磁帶連接至SAS HBA的連接埠C、且裝置ID為4。

連接光纖通道交換器的裝置 PPNS 使用下列格式： `switch:port_id`。 `device_id_lun`

例如、PPN my_switch:5.3L2表示連接至名為my_switch3之交換器連接埠5的磁帶機已設定裝置ID 3、且具有LUN 2。

LUN（邏輯單元編號）由磁碟機決定。Fibre Channel、SCSI磁帶機和程式庫、以及磁碟均具有PPN。

除非交換器名稱變更、磁帶機或磁帶庫移動、或磁帶機或磁帶庫重新設定、否則磁帶機和磁帶庫的PPNS不會變更。PPNS在重新開機後維持不變。例如、如果移除名為my_switch:5.3L2的磁帶機、並將具有相同裝置ID和LUN的新磁帶機連接至交換器my_switch5的連接埠、則可使用my_switch:5.3L2存取新的磁帶機。



== 了解序號

序號（SN）是磁帶機或媒體轉換器的唯一識別碼。根據SN（而非WWN）產生別名。ONTAP

由於SN是磁帶機或媒體更換器的唯一識別碼、因此無論磁帶機或媒體更換器的多個連線路徑為何、別名都會保持不變。這有助於儲存系統在磁帶庫組態中追蹤相同的磁帶機或媒體更換器。

即使您重新命名磁帶機或媒體轉換器所連接的Fibre Channel交換器、磁帶機或媒體轉換器的SN也不會變更。不過、如果您在磁帶庫中以新的磁帶機取代現有的磁帶機、ONTAP 則由於磁帶機的SN變更、所以會產生新的別名。此外、如果您將現有的磁帶機移至磁帶庫中的新插槽、或重新對應磁帶機的LUN、ONTAP 則會針對該磁帶機產生新的別名。

[NOTE]
====
您必須使用新產生的別名來更新備份應用程式。

====
磁帶設備的 SN 使用下列格式： `SN[xxxxxxxxxx]L[X]`

`x` 為英數字元和 L``X`` 為磁帶裝置的 LUN 。如果 LUN 為 0 、則為 L``X`` 字串的一部分不會顯示。

每個SN最多包含32個字元；SN的格式不區分大小寫。
