---
permalink: tape-backup/before-restoring-data-concept.html 
sidebar: sidebar 
keywords: considerations, restore, file, data, original, path, destination, operation, required, space 
summary: 您可以將備份的資料還原至其原始路徑或其他目的地。如果您要將備份資料還原至不同目的地、則必須準備好目的地以進行還原作業。 
---
= 還原資料前的考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將備份的資料還原至其原始路徑或其他目的地。如果您要將備份資料還原至不同目的地、則必須準備好目的地以進行還原作業。

在將資料還原至原始路徑或其他目的地之前、您必須具備下列資訊、並符合下列需求：

* 還原層級
* 還原資料的路徑
* 備份期間使用的封鎖因素
* 如果您要進行遞增還原、則所有磁帶都必須位於備份鏈中
* 可與要還原之磁帶相容的磁帶機


將資料還原至其他目的地之前、您必須執行下列作業：

* 如果要還原Volume、您必須建立新的Volume。
* 如果您要還原qtree或目錄、則必須重新命名或移動可能與還原檔案名稱相同的檔案。


[NOTE]
====
在支援統一碼格式的過程中、qtree名稱可支援ONTAP 使用統一碼格式。舊版ONTAP 的不支援此格式。如果使用將 ONTAP 9 中具有 Unicode 名稱的 qtree 複製到舊版 ONTAP `ndmpcopy` 命令或從磁帶中的備份映像還原、 qtree 會還原為一般目錄、而非以 Unicode 格式還原為 qtree 。

====
[NOTE]
====
如果還原的檔案名稱與現有檔案相同、則現有檔案會被還原的檔案覆寫。不過、目錄不會被覆寫。

====
若要在還原期間重新命名檔案、目錄或 qtree 而不使用 DAR 、您必須將 Extract 環境變數設為 `E`。



== 目的地儲存系統上所需的空間

目的地儲存系統所需的空間、比要還原的資料量多出約100 MB。

[NOTE]
====
還原作業會在還原作業開始時、檢查目的地磁碟區上的磁碟區空間和inode可用度。將強制環境變數設定為 `Y` 使還原作業略過檢查目的地路徑上的磁碟區空間和 inode 可用度。如果目的地Volume上沒有足夠的磁碟區空間或inode可用、還原作業會恢復目的地Volume空間和inode可用度所允許的資料量。當沒有更多磁碟區空間或inode時、還原作業會停止。

====