---
permalink: tape-backup/commands-manage-drives-media-changers-reference.html 
sidebar: sidebar 
keywords: manage, tape, drive, media, changer, operation, cluster, cartridge, position, online, offline, reset, clear 
summary: 您可以使用命令來檢視叢集中磁帶機和媒體更換器的相關資訊、將磁帶機上線並離線、修改磁帶機匣位置、設定及清除磁帶機別名、以及重設磁帶機。您也可以檢視及重設磁帶機統計資料。 
---
= 管理磁帶機、媒體更換器及磁帶機作業的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用命令來檢視叢集中磁帶機和媒體更換器的相關資訊、將磁帶機上線並離線、修改磁帶機匣位置、設定及清除磁帶機別名、以及重設磁帶機。您也可以檢視及重設磁帶機統計資料。

|===
| 如果您想要... | 使用此命令... 


 a| 
將磁帶機上線
 a| 
《網路磁帶》



 a| 
清除磁帶機或媒體更換器的別名
 a| 
《torage tape alias Clear》（磁帶別名清除）



 a| 
啟用或停用磁帶機的磁帶追蹤作業
 a| 
《torage tape trace》（磁帶追蹤）



 a| 
修改磁帶機匣的位置
 a| 
《磁帶位置》



 a| 
重設磁帶機
 a| 
"torage tape RESET"（磁帶重設）

[NOTE]
====
此命令僅適用於進階權限層級。

====


 a| 
設定磁帶機或媒體更換器的別名
 a| 
「torage tape alias set」



 a| 
使磁帶機離線
 a| 
《torage tape offline》（磁帶離線）



 a| 
檢視所有磁帶機和媒體更換器的相關資訊
 a| 
《torage tape show》



 a| 
檢視連接至叢集的磁帶機相關資訊
 a| 
* 「torage tape show-tape drive」
* 「系統節點硬體磁帶機顯示」




 a| 
檢視連接至叢集的媒體更換器相關資訊
 a| 
《torage tape show-media-changer》



 a| 
檢視有關連接至叢集之磁帶機的錯誤資訊
 a| 
「torage tape show-errors」



 a| 
查看ONTAP 連接至叢集中每個節點的所有支援且符合資格的磁帶機
 a| 
「torage tape show-support-STATUS」（磁帶顯示支援狀態）



 a| 
檢視連接至叢集中每個節點的所有磁帶機和媒體更換器別名
 a| 
「torage tape alias show」



 a| 
將磁帶機的統計資料讀取重設為零
 a| 
"torage stats tape零"（磁帶名稱）

您必須在節點下使用此命令。



 a| 
檢視ONTAP 支援的磁帶機
 a| 
「torage show tape supported（-v]）」

您必須在節點下使用此命令。您可以使用「-v」選項來檢視每個磁帶機的詳細資料。



 a| 
檢視磁帶設備統計資料、瞭解磁帶效能並檢查使用模式
 a| 
"torage stats tape（磁帶名稱）"

您必須在節點下使用此命令。

|===
如需這些命令的詳細資訊、請參閱手冊頁。
