---
permalink: tape-backup/manage-node-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, node, scope, ndmp, mode, flexvol, volume, command, option, backup, restore 
summary: 您可以使用NDMP選項和命令、在節點層級管理NDMP。您可以使用options命令修改NDMP選項。您必須使用NDMP專屬的認證資料來存取儲存系統、才能執行磁帶備份與還原作業。 
---
= 了解如何管理FlexVol磁碟區的ONTAP節點範圍 NDMP 模式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用NDMP選項和命令、在節點層級管理NDMP。您可以使用修改 NDMP 選項 `options` 命令。您必須使用NDMP專屬的認證資料來存取儲存系統、才能執行磁帶備份與還原作業。

如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=options["指令參考資料ONTAP"^]需詳細 `options`資訊，請參閱。



== 用於管理ONTAP節點範圍 NDMP 模式的命令

您可以使用 `system services ndmp` 用於在節點層級管理 NDMP 的命令。其中有些命令已過時、將在未來的重大版本中移除。

您只能在進階權限層級使用下列NDMP命令：

* `system services ndmp service terminate`
* `system services ndmp service start`
* `system services ndmp service stop`
* `system services ndmp log start`
* `system services ndmp log stop`


|===
| 如果您想要... | 使用此命令... 


 a| 
啟用NDMP服務
 a| 
`system services ndmp on`*



 a| 
停用NDMP服務
 a| 
`system services ndmp off`*



 a| 
顯示 NDMP 組態
 a| 
`system services ndmp show`*



 a| 
修改 NDMP 組態
 a| 
`system services ndmp modify`*



 a| 
顯示預設NDMP版本
 a| 
`system services ndmp version`*



 a| 
顯示NDMP服務組態
 a| 
`system services ndmp service show`



 a| 
修改NDMP服務組態
 a| 
`system services ndmp service modify`



 a| 
顯示所有NDMP工作階段
 a| 
`system services ndmp status`



 a| 
顯示所有NDMP工作階段的詳細資訊
 a| 
`system services ndmp probe`



 a| 
終止指定的NDMP工作階段
 a| 
`system services ndmp kill`



 a| 
終止所有NDMP工作階段
 a| 
`system services ndmp kill-all`



 a| 
變更NDMP密碼
 a| 
`system services ndmp password`*



 a| 
啟用節點範圍的NDMP模式
 a| 
`system services ndmp node-scope-mode on`*



 a| 
停用節點範圍的NDMP模式
 a| 
`system services ndmp node-scope-mode off`*



 a| 
顯示節點範圍的NDMP模式狀態
 a| 
`system services ndmp node-scope-mode status`*



 a| 
強制終止所有NDMP工作階段
 a| 
`system services ndmp service terminate`



 a| 
啟動NDMP服務精靈
 a| 
`system services ndmp service start`



 a| 
停止NDMP服務精靈
 a| 
`system services ndmp service stop`



 a| 
開始記錄指定的NDMP工作階段
 a| 
`system services ndmp log start`*



 a| 
停止記錄指定的NDMP工作階段
 a| 
`system services ndmp log stop`*

|===
* 這些命令已過時、將在未來的重大版本中移除。


如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+services+ndmp["指令參考資料ONTAP"^]需詳細 `system services ndmp`資訊，請參閱。



== 節點範圍NDMP模式中的使用者驗證

在節點範圍的NDMP模式中、您必須使用NDMP專屬認證來存取儲存系統、才能執行磁帶備份與還原作業。

預設使用者ID為「root」。在節點上使用NDMP之前、您必須先確定變更與NDMP使用者相關的預設NDMP密碼。您也可以變更預設的NDMP使用者ID。

.相關資訊
xref:commands-manage-node-scoped-ndmp-reference.adoc[管理節點範圍NDMP模式的命令]

xref:node-scoped-ndmp-mode-concept.adoc[什麼是節點範圍的NDMP模式]
