---
permalink: tape-backup/manage-svm-scoped-ndmp-mode-concept.html 
sidebar: sidebar 
keywords: manage, svm, scope, ndmp, flexvol, volumes, vserver, modify 
summary: 您可以使用NDMP選項和命令、以每個SVM為基礎來管理NDMP。您可以使用vserver services NDMP modify命令來修改NDMP選項。在SVM範圍的NDMP模式中、使用者驗證會與角色型存取控制機制整合。 
---
= 管理SVM範圍的NDMP模式FlexVol 、以利實現不限數量的概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用NDMP選項和命令、以每個SVM為基礎來管理NDMP。您可以使用「vserver services NDMP modify」命令來修改NDMP選項。在SVM範圍的NDMP模式中、使用者驗證會與角色型存取控制機制整合。

您可以使用「vserver modify」命令、將NDMP新增至「允許或不允許的傳輸協定」清單中。根據預設、NDMP位於允許的傳輸協定清單中。如果將NDMP新增至不允許的傳輸協定清單、就無法建立NDMP工作階段。

您可以使用「慣用的介面角色」選項來控制建立NDMP資料連線的LIF類型。在建立NDMP資料連線期間、NDMP會選擇屬於此選項指定之LIF類型的IP位址。如果IP位址不屬於上述LIF類型、則無法建立NDMP資料連線。如需更多有關「慣用介面角色」選項的資訊、請參閱手冊頁。

如需「vserver services NDMP modify」命令的詳細資訊、請參閱手冊頁。

xref:commands-manage-svm-scoped-ndmp-reference.adoc[管理SVM範圍NDMP模式的命令]

xref:cluster-aware-backup-extension-concept.adoc[叢集感知備份擴充的功能]

link:../concepts/index.html["概念ONTAP"]

xref:svm-scoped-ndmp-mode-concept.adoc[SVM範圍的NDMP模式是什麼]

link:../system-admin/index.html["系統管理"]
