---
permalink: tape-backup/transfer-data-ndmpcopy-task.html 
sidebar: sidebar 
keywords: transfer, data, ndmpcopy, incremental, full, qtree, directory, files, v4, ndmp 
summary: ndmpcopy命令可在支援NDMP v4的儲存系統之間傳輸資料。您可以執行完整和遞增資料傳輸。您可以傳輸完整或部分磁碟區、qtree、目錄或個別檔案。 
---
= 使用 ndmpcopy 傳輸ONTAP數據
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
。 `ndmpcopy` Nodesdesh 命令會在支援 NDMP v4 的儲存系統之間傳輸資料。您可以執行完整和遞增資料傳輸。您可以傳輸完整或部分磁碟區、qtree、目錄或個別檔案。

.關於這項工作
使用發行版本的不限次數地進行遞增傳輸（一次完整備份、最多兩次遞增備份）ONTAP 。

從發行版的更新版本開始、遞增式傳輸最多只能有九個層級（一個完整備份、最多九個遞增備份）ONTAP 。

您可以執行 `ndmpcopy` 在來源與目的地儲存系統的 nodesdesh 命令列、或是既不是資料傳輸來源也不是目的地的儲存系統。您也可以執行 `ndmpcopy` 在單一儲存系統上、同時是資料傳輸的來源和目的地。

您可以使用中來源和目的地儲存系統的 IPv4 或 IPv6 位址 `ndmpcopy` 命令。路徑格式為 `/vserver_name/volume_name \[path\]`。



.步驟
. 在來源與目的地儲存系統上啟用NDMP服務：
+
|===


| 如果您要在下列位置的來源或目的地執行資料傳輸： | 使用下列命令... 


 a| 
SVM範圍的NDMP模式
 a| 
`vserver services ndmp on`

[NOTE]
====
對於管理 SVM 中的 NDMP 驗證、使用者帳戶是 `admin` 而且使用者角色是 `admin` 或 `backup`。在資料 SVM 中、使用者帳戶是 `vsadmin` 而且使用者角色是 `vsadmin` 或 `vsadmin-backup` 角色：

====


 a| 
節點範圍的NDMP模式
 a| 
`system services ndmp on`

|===
. 使用在儲存系統內或儲存系統之間傳輸資料 `ndmpcopy` Nodesdesh以下 的命令：
+
`::> system node run -node <node_name> < ndmpcopy [options] source_IP:source_path destination_IP:destination_path [-mcs {inet|inet6}] [-mcd {inet|inet6}] [-md {inet|inet6}]`

+
[NOTE]
====
在ndmpcopy中不支援DNS名稱。您必須提供來源和目的地的IP位址。來源IP位址或目的地IP位址不支援回送位址（127.0.0.1）。

====
+
** 。 `ndmpcopy` 命令會決定控制連線的位址模式、如下所示：
+
*** 控制連線的位址模式會對應所提供的IP位址。
*** 您可以使用來覆寫這些規則 `-mcs` 和 `-mcd` 選項：


** 如果來源或目的地是ONTAP 指不支援的系統、則視NDMP模式（節點範圍或SVM範圍）而定、請使用允許存取目標Volume的IP位址。
** `source_path` 和 `destination_path` 是磁碟區、 qtree 、目錄或檔案精細層級之前的絕對路徑名稱。
** `-mcs` 指定與來源儲存系統的控制連線的慣用定址模式。
+
`inet` 表示 IPv4 位址模式和 `inet6` 表示 IPv6 位址模式。

** `-mcd` 指定與目的地儲存系統的控制連線的慣用定址模式。
+
`inet` 表示 IPv4 位址模式和 `inet6` 表示 IPv6 位址模式。

** `-md` 指定來源與目的地儲存系統之間資料傳輸的慣用定址模式。
+
`inet` 表示 IPv4 位址模式和 `inet6` 表示 IPv6 位址模式。

+
如果您不使用 `-md` 中的選項 `ndmpcopy` 命令時、資料連線的定址模式如下所示：

+
*** 如果為控制連線指定的任一位址是IPv6位址、則資料連線的位址模式為IPv6。
*** 如果控制連線指定的兩個位址都是 IPv4 位址、則為 `ndmpcopy` 命令會先嘗試資料連線的 IPv6 位址模式。
+
如果失敗、命令會使用IPv4位址模式。

+
[NOTE]
====
如果指定IPv6位址、則必須以方括弧括住。

====
+
此範例命令會從來源路徑移轉資料 (`source_path`）到目的地路徑 (`destination_path`）。

+
[listing]
----
> ndmpcopy -sa admin:<ndmp_password> -da admin:<ndmp_password>
 -st md5 -dt md5 192.0.2.129:/<src_svm>/<src_vol> 192.0.2.131:/<dst_svm>/<dst_vol>
----
+
此命令範例明確設定控制連線和資料連線、以使用IPv6位址模式：

+
[listing]
----
> ndmpcopy -sa admin:<ndmp_password> -da admin:<ndmp_password> -st md5 -dt md5 -mcs inet6 -mcd inet6 -md
 inet6 [2001:0db8:1:1:209:6bff:feae:6d67]:/<src_svm>/<src_vol> [2001:0ec9:1:1:200:7cgg:gfdf:7e78]:/<dst_svm>/<dst_vol>
----






如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。



== ndmpcopy命令的選項

您應該瞭解 Nodesdesh 命令可用於成功的選項 `ndmpcopy`link:transfer-data-ndmpcopy-task.html["傳輸資料"]。

下表列出可用的選項。

|===
| 選項 | 說明 


 a| 
`-sa` `username`：[`password`]
 a| 
此選項可設定來源驗證使用者名稱和密碼、以連線至來源儲存系統。這是必填選項。

對於沒有管理權限的使用者、您必須指定使用者系統產生的NDMP專屬密碼。系統產生的密碼對管理員和非管理員使用者都是必填的。



 a| 
`-da` `username`：[`password`]
 a| 
此選項可設定用於連線至目的地儲存系統的目的地驗證使用者名稱和密碼。這是必填選項。



 a| 
`-st` {`md5`|`text`}
 a| 
此選項可設定連線至來源儲存系統時所使用的來源驗證類型。這是必要選項、因此使用者應提供 `text` 或 `md5` 選項。



 a| 
`-dt` {`md5`|`text`}
 a| 
此選項可設定連線至目的地儲存系統時要使用的目的地驗證類型。



 a| 
`-l`
 a| 
此選項會將用於傳輸的傾印層級設定為指定的層級值。有效值為 `0`、 `1`、至 `9`、其中 `0` 表示完整傳輸和 `1` 至 `9` 指定遞增傳輸。預設值為 `0`。



 a| 
`-d`
 a| 
此選項可產生ndmpcopy除錯記錄訊息。ndmpcopy 除錯記錄檔位於中 `/mroot/etc/log` 根 Volume 。ndmpcopy 除錯記錄檔名稱位於中 `ndmpcopy.yyyymmdd` 格式。



 a| 
`-f`
 a| 
此選項可啟用強制模式。此模式可在中覆寫系統檔案 `/etc` 位於 7-Mode 磁碟區根目錄的目錄。



 a| 
`-h`
 a| 
此選項會列印說明訊息。



 a| 
`-p`
 a| 
此選項會提示您輸入來源和目的地授權的密碼。此密碼會覆寫指定的密碼 `-sa` 和 `-da` 選項：

[NOTE]
====
只有當命令在互動式主控台中執行時、才能使用此選項。

====


 a| 
`-exclude`
 a| 
此選項會將指定的檔案或目錄排除在資料傳輸所指定的路徑之外。該值可以是以逗號分隔的目錄或檔案名稱清單，例如 `*.pst`或 `*.txt`。支援的最大排除模式數為 32 ，支援的最大字元數為 255 。

|===