---
permalink: software_setup/concept_set_up_the_cluster.html 
sidebar: sidebar 
keywords: ontap, software, setup, cluster, worksheets 
summary: 設定叢集時、需要收集所需的資訊、以設定每個節點的設定、在第一個節點上建立叢集、以及將任何剩餘節點加入叢集。 
---
= 收集叢集設定的叢集資訊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定叢集時、需要收集所需的資訊、以設定每個節點的設定、在第一個節點上建立叢集、以及將任何剩餘節點加入叢集。

請先從叢集設定工作表中收集所有相關資訊開始著手。

叢集設定工作表可讓您記錄叢集設定程序所需的值。如果提供預設值、您可以使用該值、或輸入自己的值。



== 系統預設值

系統預設值為私有叢集網路的預設值。最好使用這些預設值。不過、如果它們不符合您的要求、您可以使用表格記錄自己的值。


NOTE: 對於設定為使用網路交換器的叢集、每個叢集交換器都必須使用9000 MTU大小。

[cols="2*"]
|===
| 資訊類型 | 您的價值 


| 私有叢集網路連接埠 |  


| 叢集網路遮罩 |  


| 叢集介面IP位址（每個節點上的每個叢集網路連接埠）每個節點的IP位址必須位於同一個子網路上。 |  
|===


== 叢集資訊

[cols="2*"]
|===
| 資訊類型 | 您的價值 


| 叢集名稱名稱必須以字母開頭、且必須少於44個字元。名稱可以包含下列特殊字元：「.」 ” |  
|===


== 功能授權金鑰

您可以在NetApp支援網站的* My Support*>* Software Licenses*下找到初始或附加軟體訂單的授權金鑰。

[cols="2*"]
|===
| 資訊類型 | 您的價值 


| 功能授權金鑰 |  
|===


== 管理儲存虛擬機器（SVM）

[cols="2*"]
|===
| 資訊類型 | 您的價值 


 a| 
叢集管理員密碼

叢集在授予叢集管理員存取主控台或透過安全傳輸協定的權限之前所需的管理員帳戶密碼。


NOTE: 為了安全起見、不建議在此工作表中記錄密碼。

密碼的預設規則如下：

* 密碼長度必須至少八個字元。
* 密碼必須包含至少一個字母和一個數字。

 a| 



 a| 
叢集管理介面連接埠

連線至資料網路的實體連接埠、可讓叢集管理員管理叢集。
 a| 



 a| 
叢集管理介面IP位址

叢集管理介面的獨特IPv6位址。叢集管理員使用此位址來存取管理SVM並管理叢集。通常、此位址應位於資料網路上。

您可以向負責指派組織IP位址的管理員取得此IP位址。

範例：192.0.2.66
 a| 



 a| 
叢集管理介面網路遮罩（IPv4）

定義叢集管理網路上有效的IPv4位址範圍的子網路遮罩。

範例：255：255：255
 a| 



 a| 
叢集管理介面網路遮罩長度（IPv6）

如果叢集管理介面使用IPv6位址、則此值代表定義叢集管理網路上有效IPv6位址範圍的字首長度。

範例：64
 a| 



 a| 
叢集管理介面預設閘道

叢集管理網路上路由器的IP位址。
 a| 



 a| 
DNS網域名稱

網路DNS網域的名稱。

網域名稱必須包含英數字元。若要輸入多個DNS網域名稱、請以一個逗號或空格分隔每個名稱。
 a| 



 a| 
名稱伺服器IP位址

DNS名稱伺服器的IP位址。以一個逗號或空格分隔每個位址。
 a| 

|===


== 節點資訊（適用於叢集中的每個節點）

[cols="2*"]
|===
| 資訊類型 | 您的價值 


 a| 
控制器的實體位置（選用）

控制器實體位置的說明。請使用說明來識別叢集中的此節點位置（例如「Lab 5、第7列、Rack B」）。
 a| 



 a| 
節點管理介面連接埠

連接至節點管理網路的實體連接埠、並可讓叢集管理員管理節點。
 a| 



 a| 
節點管理介面IP位址

管理網路上節點管理介面的唯一IPV4或IPv6位址。如果您將節點管理介面連接埠定義為資料連接埠、則此IP位址應該是資料網路上的唯一IP位址。

您可以向負責指派組織IP位址的管理員取得此IP位址。

範例：192.0.2.66
 a| 



 a| 
節點管理介面網路遮罩（IPv4）

定義節點管理網路上有效IP位址範圍的子網路遮罩。

如果將節點管理介面連接埠定義為資料連接埠、則網路遮罩應該是資料網路的子網路遮罩。

範例：255：255：255
 a| 



 a| 
節點管理介面網路遮罩長度（IPv6）

如果節點管理介面使用IPv6位址、則此值代表定義節點管理網路上有效IPv6位址範圍的前置碼長度。

範例：64
 a| 



 a| 
節點管理介面預設閘道

節點管理網路上路由器的IP位址。
 a| 

|===


== NTP伺服器資訊

[cols="2*"]
|===
| 資訊類型 | 您的價值 


 a| 
NTP伺服器位址

站台上網路時間傳輸協定（NTP）伺服器的IP位址。這些伺服器可用來同步整個叢集的時間。
 a| 

|===