---
permalink: software_setup/task_create_an_svm_using_ontap_template.html 
sidebar: sidebar 
keywords: ontap, software, setup, provision, svm, preconfigured, template 
summary: 從使用Sf9.3開始ONTAP 、您可以使用預先設定的範本來建立及配置SVM。您必須為範本中定義的參數提供值。 
---
= 使用預先設定ONTAP 的SVM範本來配置SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從使用Sf9.3開始ONTAP 、您可以使用預先設定的範本來建立及配置SVM。您必須為範本中定義的參數提供值。

所有必要的功能授權都必須安裝在叢集上。

VserverEnvironment設定範本是預先設定的範本、可用於設定SVM。VserverEnvironment設定範本可讓您設定下列組態：

* SVM的安全樣式、語言設定及IPspace
* 通訊協定
* 資料生命量
* 網路路由
* DNS組態
* Active Directory組態
* NIS組態
* LDAP用戶端和伺服器組態
* CIFS伺服器


VserverEnvironment安裝範本為唯讀範本。您無法修改此範本的預設參數值。若要修改範本中任何參數的預設值、您必須複製範本、然後修改參數的預設值。

.步驟
. 檢視並記下範本中定義的參數值、以建立及設定SVM：「範本參數顯示」
+
[listing]
----
cluster1::> template parameter show

  Template: VserverEnvironmentSetup
Permission: readonly
                                 Default      Read
Parameter           Type         Value        Only Description
------------------- ------------ ------------ ---- ----------------------------
vserver             string       -            no   Vserver Name
security_style      string       unix         no   Vserver Security Style
language            string       C.UTF-8      no   Vserver Language
ipspace             string       Default      no   Vserver IPSpace
protocols           enum         -            no   Protocols to configure
   Allowed Values: nfs, cifs, iscsi, fcp
data_lif            array of lifInfoStruct
                                 -            yes  Data LIF Info Struct
data_lif[#].ipaddr  IPAddress    -            no   IP Addr
data_lif[#].netmask IPAddress    -            no   NetMask
data_lif[#].protocol
                    string       -            no   LIF Protocol
data_lif[#].homenode
                    string       -            no   Node Name
data_lif[#].homeport
                    string       -            no   Port
gateway             array of IPAddress
                                 -            yes  Gateway
gateway[#]          IPAddress                 no   Gateway
search_domain       string       -            no   Search Domain
dns_server          string       -            no   DNS IP Addresses List
ad_admin_name       string       -            no   AD Admin Name
ad_admin_passwd     string       ***          no   AD Admin Passwd
ad_domain           string       -            no   AD Domain
ad_ou               string       CN=Computers no   Organizational Name
wg_name             string       -            no   WG Name
nis_domain          string       -            no   NIS Domains
nis_ipaddr          string       -            no   NIS IP Address
ldap_server         string       -            no   LDAP Server IP
ldap_base_dn        string       -            no   LDAP Base DN
client_config       string       -            no   LDAP Client Config
cifs_server         string       -            no   CIFS Server Name
26 entries were displayed.
----
. 如果您要修改範本中任何參數的預設值、請自訂現有的範本：
+
.. 複製範本：
+
'範本複本-name template名稱-destination_name new_timent_name

+
[listing]
----
cluster1::> template copy -name VserverEnvironmentSetup -destination-name template1
----
+
新範本為讀寫範本。

.. 修改您要變更之參數的預設值：
+
「範本參數修改-範本範本名稱-名稱參數名稱-預設值new_default_value'

+
[listing]
----
cluster1::> template parameter modify -template template1 -name security_style -default-value ntfs
----


. 指定範本中參數的值來配置SVM：
+
範本資源配置-name template_name

+
[listing]
----
cluster-1::> template provision -name template1
	    Press Ctrl+C to abort.
	    ********************
	    * Setup of vserver *
	    ********************
	    Vserver Name: vs0
	    Vserver Language [C.UTF-8]:
	    Vserver Security Style [ntfs]:
	    Vserver IPSpace [Default]:

	    ******************************
	    * Setup of network.interface *
	    ******************************
	    Enter number of instances for object network.interface: 2
	    (1/2)LIF Protocol: nfs
	    (1/2)IP Addr: 1.1.1.1
	    (1/2)NetMask: 255.255.255.0
	    (1/2)Node Name: node1-vsim1
	    (1/2)Port: e0c
	    (2/2)LIF Protocol: nfs
	    (2/2)IP Addr: 1.1.1.1
	    (2/2)NetMask: 255.255.255.0
	    (2/2)Node Name: node1-vsim1
	    (2/2)Port: e0c

	    ***************************
	    * Setup of network.routes *
	    ***************************
	    Enter number of instances for object network.routes: 1
	    (1/1)Gateway: 1.1.1.1

	    ***********************
	    * Setup of access.dns *
	    ***********************
	    Search Domain: netapp.com
	    DNS IP Addresses List: 1.1.1.1

	    *************************
	    * Setup of security.nis *
	    *************************
	    NIS Domains: netapp.com
	    NIS IP Address: 1.1.1.1

	    *********************
	    * Setup of security *
	    *********************
	    LDAP Client Config: ldapconfig
	    LDAP Server IP: 1.1.1.1
	    LDAP Base DN: dc=examplebasedn

	    **********************
	    * Setup of protocols *
	    **********************
	    Protocols to configure: nfs
	    [Job 15] Configuring vserver for vs0 (100%)
----

