---
permalink: software_setup/task_join_remaining_nodes_to_the_cluster.html 
sidebar: sidebar 
keywords: ontap, software, setup, join, remaining, nodes, cluster, HA, high availability, autosupport 
summary: 建立新叢集之後、您可以使用叢集設定精靈、一次將每個剩餘節點加入一個叢集。精靈可協助您設定每個節點的節點管理介面。 
---
= 將其餘節點加入 ONTAP 中的叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立新叢集之後、您可以使用叢集設定精靈、一次將每個剩餘節點加入一個叢集。精靈可協助您設定每個節點的節點管理介面。


NOTE: 此程序適用於 FAS 、 AFF 和目前的 ASA 系統。如果您有 ASA R2 系統（ ASA A1K 、 ASA A70 或 ASA A90 ）、請遵循link:https://docs.netapp.com/us-en/asa-r2/install-setup/initialize-ontap-cluster.html["這些步驟"^]使用系統管理員來設定 ONTAP 叢集。ASA R2 系統提供專為僅限 SAN 的客戶所提供的簡化 ONTAP 體驗。

當您在叢集中加入兩個節點時、就會建立高可用度（HA）配對。如果您加入4個節點、就會建立兩個HA配對。若要深入瞭解 HA ，請參閱link:../high-availability/index.html["瞭解HA"]。

您一次只能將一個節點加入叢集。當您開始將節點加入叢集時、必須完成該節點的加入作業、而且節點必須是叢集的一部分、才能開始加入下一個節點。

*最佳實務做法：*如果您的FAS2720配備24個或更少NL-SAS磁碟機、您應該確認儲存組態預設值設定為主動/被動、以最佳化效能。如需詳細資訊，請參閱的文件 link:../disks-aggregates/setup-active-passive-config-root-data-task.html["在使用根資料分割的節點上設定主動被動式組態"]。

. 登入您打算加入叢集的節點。
+
叢集設定精靈會在主控台上啟動。

+
[listing]
----
Welcome to the cluster setup wizard....
----
. 認可AutoSupport 此聲明。
+

NOTE: 根據預設會啟用支援。AutoSupport

+
[listing]
----
Type yes to confirm and continue {yes}: yes
----
. 請依照畫面上的指示、將IP位址指派給節點。
+
從 ONTAP 9.13.1 開始，您可以為 A800 和 FAS8700 平台上的管理階層指派 IPv6 位址。對於早於 9.13.1 的 ONTAP 版本、或是在其他平台上的 9.13.1 及更新版本、您必須指派管理階層的 IPv4 位址、然後在完成叢集設定後轉換為 IPv6 。

. 按* Enter鍵*繼續。
+
[listing]
----
Do you want to create a new cluster or join an existing cluster? {create, join}:
----
. 將節點加入叢集： `join`
. 依照畫面上的指示設定節點、並將其加入叢集。
. 安裝完成後、請確認節點狀況良好、符合參加叢集的資格： `cluster show`
+
以下範例顯示第二個節點（cluster1-02）加入叢集之後的叢集：

+
[listing]
----
cluster1::> cluster show
Node                  Health  Eligibility
--------------------- ------- ------------
cluster1-01           true    true
cluster1-02           true    true
----
+
您可以使用叢集設定命令、存取叢集設定精靈、變更您為管理SVM或節點SVM輸入的任何值。

. 對其餘每個節點重複此工作。


.完成後
如有需要、 link:convert-ipv4-to-ipv6-task.html["從 IPv4 轉換為 IPv6"]。
