---
permalink: asa/overview.html 
sidebar: sidebar 
keywords: all flash san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: NetApp All Flash SAN Array （ ASA ）從 ONTAP 9.7 開始提供。  ASA是純Flash SAN解決方案、以獲證實AFF 的NetApp平台為建置基礎。 
---
= All Flash SAN Array 軟體組態概觀
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
NetApp All Flash SAN Array （ ASA ）從 ONTAP 9.7 開始提供。  ASA是純Flash SAN解決方案、以獲證實AFF 的NetApp平台為建置基礎。

ASA 平台使用對稱的雙主動式多重路徑。所有路徑都是主動/最佳化的、因此在發生儲存容錯移轉時、主機不需要等待容錯移轉路徑的ALUA轉換、即可恢復I/O如此可縮短容錯移轉的時間。



== 設定ASA 一個功能完善的

All Flash SAN Arrays （ ASA ）的設定程序與非 ASA 系統相同。

System Manager會引導您完成初始化叢集、建立本機層級、設定通訊協定、以及為ASA 您的支援資源配置儲存設備所需的程序。

xref:../software_setup/concept_decide_whether_to_use_ontap_cli.html[開始設定 ONTAP 叢集]。



== 支援主機設定與公用程式ASA

設定 All Flash SAN Array （ ASA ）的主機設定與所有其他 SAN 主機的主機設定相同。

您可以下載 link:https://mysupport.netapp.com/NOW/cgi-bin/software["NetApp主機公用程式軟體"^] 支援網站上的特定主機。



== 辨ASA 識出一套系統的方法

您可以ASA 使用System Manager或ONTAP 使用指令行介面（CLI）來識別出一個無法辨識的系統。

* * 從 System Manager 儀表板 * ：按一下 * 叢集 > 總覽 * 、然後選取系統節點。
+
* 特性 * 會顯示為 * All Flash SAN Array * 。

* * 從 CLI * ：輸入 `san config show` 命令。
+
對於 ASA 系統、「 All Flash SAN Array 」值會傳回為 TRUE 。



.相關資訊
* link:https://www.netapp.com/pdf.html?item=/media/85671-tr-4968.pdf["技術報告 4968 ： NetApp All SAN 陣列資料可用度與完整性"^]
* link:https://www.netapp.com/pdf.html?item=/media/10680-tr4080pdf.pdf["NetApp 技術報告 4080 ：現代 SAN 的最佳實務做法"^]

