---
permalink: asa/support-limitations.html 
sidebar: sidebar 
keywords: all flash san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: All Flash SAN Array （ ASA ）組態限制與支援因 ONTAP 版本而異。 
---
= All Flash SAN Array 組態限制與支援
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
All Flash SAN Array （ ASA ）組態限制與支援因 ONTAP 版本而異。

如需支援組態限制的最新詳細資料、請參閱 link:https://hwu.netapp.com/["NetApp Hardware Universe"^]。



== 每個叢集的 SAN 通訊協定和節點

ASA 支援每個叢集的 SAN 通訊協定和節點如下：

[cols="3*"]
|===


| 從ONTAP 無到無...開始 | 傳輸協定支援 | 每個叢集的最大節點數 


| 9.12.1  a| 
* NVMe （支援 4 節點 MetroCluster IP 組態和非 MetroCluster IP 組態）
* FC
* iSCSI

| 12. 


| 9.9.1  a| 
* NVMe （非 MetroCluster IP 組態支援）
* FC
* iSCSI

 a| 
* 12 個節點（適用於非 MetroCluster IP 組態）
* 8 個節點（適用於 MetroCluster IP 組態）




| 9.7%  a| 
* FC
* iSCSI

| 4. 
|===


== 支援持續連接埠

從 ONTAP 9.8 開始、在設定為使用 FC 傳輸協定的 All Flash SAN 陣列（ ASA ）上、預設會啟用持續連接埠。持續連接埠僅適用於FC、且需要由全球連接埠名稱（WWPN）識別的區域成員資格。

持續連接埠可在HA合作夥伴的對應實體連接埠上建立陰影LIF、藉此降低接管的影響。接管節點時、合作夥伴節點上的陰影LIF會採用原始LIF的身分識別、包括WWPNe。在將接管節點的路徑狀態變更為故障之前、陰影LIF會顯示為通往主機MPIO堆疊的主動/最佳化路徑、並會移動I/O。如此可減少I/O中斷、因為即使在儲存容錯移轉作業期間、主機仍會看到相同數量的目標路徑。

對於持續連接埠、HA配對內的下列FCP連接埠特性應該相同：

* FCP連接埠數
* FCP連接埠名稱
* FCP連接埠速度
* FCP LIF WWPN型分區


如果HA配對中有任何特性不相同、就會產生下列EMS訊息：

`EMS : scsiblade.lif.persistent.ports.fcp.init.error`

如需持續連接埠的詳細資訊、請參閱 link:http://www.netapp.com/us/media/tr-4080.pdf["NetApp 技術報告 4080 ：現代 SAN 的最佳實務做法"^]。
