---
permalink: asa/support-limitations.html 
sidebar: sidebar 
keywords: all san array, asa, san, array, software, configuration, configure, configuring, setup, set up, limitations, restrictions, nvme, mcc ip, persistent ports, host, settings, utilities, ways to identify 
summary: 請使用下列程序、使用System Manager來設定All SAN Array。 
---
= 所有SAN陣列組態限制與支援
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您應該使用AFF 針對「完整的SAN陣列ASA （ESCSI）」控制器所建立的已測試及支援的最大組態限制。

為確保可靠作業、您不應超過中所列的目前已測試及支援限制 link:https://hwu.netapp.com/["NetApp Hardware Universe"^]。



== 部分組態限制ASA

從推出支援非MetroCluster IP組態的ONTAP 版本起、最多AFF ASA 可支援12個節點、MetroCluster 而支援多達8個節點、以利進行支援。

此外ONTAP 、從支援支援NVM9.9.1開始、所有AFF ASA 的支援都支援NVMe傳輸協定、但不支援MetroCluster 針對功能進行設定的控制器。不支援NVMe組態。MetroCluster



== 支援持續連接埠

從功能部件號9.8開始ONTAP 、所有配置為使用FC傳輸協定的SAN陣列（ASA）、預設會啟用持續連接埠。持續連接埠僅適用於FC、且需要由全球連接埠名稱（WWPN）識別的區域成員資格。

持續連接埠可在HA合作夥伴的對應實體連接埠上建立陰影LIF、藉此降低接管的影響。接管節點時、合作夥伴節點上的陰影LIF會採用原始LIF的身分識別、包括WWPNe。在將接管節點的路徑狀態變更為故障之前、陰影LIF會顯示為通往主機MPIO堆疊的主動/最佳化路徑、並會移動I/O。如此可減少I/O中斷、因為即使在儲存容錯移轉作業期間、主機仍會看到相同數量的目標路徑。

對於持續連接埠、HA配對內的下列FCP連接埠特性應該相同：

* FCP連接埠數
* FCP連接埠名稱
* FCP連接埠速度
* FCP LIF WWPN型分區


如果HA配對中有任何特性不相同、就會產生下列EMS訊息：

《EMS：scsiblade.lif.persistent.ports.fcp.init.error`》

如需持續連接埠的詳細資訊、請參閱 link:http://www.netapp.com/us/media/tr-4080.pdf["NetApp技術報告4080：可擴充SAN ONTAP 的最佳實務做法9"^]。



== 支援NVMe傳輸協定

從支援支援NVMe.9.9.1開始ONTAP 、所有SAN陣列都支援NVMe傳輸協定。

從功能完整的支援支援支援NVMe/FC的4節點之「靜態IP」組態、從ONTAP 功能完整的版本9.12.1開始MetroCluster 。NVMe不支援9.12.1之前的版本。MetroCluster
