---
sidebar: sidebar 
permalink: high-availability/ha_automatic_giveback_commands.html 
keywords: ontap, high, availability, ha, pair, automatic, giveback, commands 
summary: 自動恢復命令 
---
= 自動恢復命令
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
依預設、當離線節點恢復連線時、接管合作夥伴節點會自動提供儲存設備、進而還原高可用度配對關係。在大多數情況下、這是理想的行為。如果您需要停用自動恢復功能（例如、如果您想要在歸還之前調查接管原因）、您需要注意非預設設定的互動。

|===


| 如果您想要... | 使用此命令... 


 a| 
啟用自動恢復功能、以便在接管節點開機、到達「等待歸還」狀態、以及「自動歸還之前的延遲」過期之後、立即進行恢復。

預設設定為true。
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback true`



 a| 
停用自動還原。預設設定為true。

* 附註： * 將此參數設為 false 、並不會在發生緊急情況時自動恢復、而在發生緊急情況時自動恢復必須透過設定來停用 `‑auto‑giveback‑after‑panic` 參數為 FALSE 。
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback false`



 a| 
在發生緊急情況時停用接管後自動恢復（此設定預設為啟用）。
 a| 
`storage failover modify ‑node _nodename_ ‑auto‑giveback‑after‑panic false`



 a| 
延遲自動恢復指定秒數（預設值為600）。此選項可決定在執行自動恢復之前、節點仍處於接管狀態的最短時間。
 a| 
`storage failover modify ‑node _nodename_ ‑delay‑seconds _seconds_`

|===


== 儲存容錯移轉修改命令的變化如何影響自動恢復

自動恢復的操作取決於您如何設定儲存容錯移轉修改命令的參數。

下表列出的預設設定 `storage failover modify` 套用至接管事件的命令參數、不是因恐慌所造成。

|===


| 參數 | 預設設定 


 a| 
`-auto-giveback _true_ | _false_`
 a| 
`_true_`



 a| 
`-delay-seconds _integer_ (seconds)`
 a| 
600



 a| 
`-onreboot _true_ | _false_`
 a| 
`_true_`

|===
下表說明的組合方式 `-onreboot` 和 `-auto-giveback` 參數會影響自動恢復接管事件的恢復、而非因恐慌而造成的。

|===


| `storage failover modify` 使用的參數 | 接管原因 | 是否會自動還原？ 


 a| 
`-onreboot _true_`

`-auto-giveback _true_`
| 重新開機命令 | 是的 


| 停止命令、或從服務處理器發出的關機後再開機 | 是的 


 a| 
`-onreboot _true_`

`-auto-giveback _false_`
| 重新開機命令 | 是的 


| 停止命令、或從服務處理器發出的關機後再開機 | 否 


 a| 
`-onreboot _false_`

`-auto-giveback _true_`
| 重新開機命令 | 不適用
在這種情況下、不會發生接管 


| 停止命令、或從服務處理器發出的關機後再開機 | 是的 


 a| 
`-onreboot _false_`

`-auto-giveback _false_`
| 重新開機命令 | 否 


| 停止命令、或從服務處理器發出的關機後再開機 | 否 
|===
。 `-auto-giveback` 參數可控制緊急狀況後的恢復和所有其他自動接管。如果是 `-onreboot` 參數設定為 `true` 而且由於重新開機而發生接管、無論是否執行自動恢復、都會執行自動恢復 `-auto-giveback` 參數設定為 `true`。

。 `-onreboot` 此參數適用於從 ONTAP 發出的重新開機和停止命令。當 `-onreboot` 參數設為 false 、節點重新開機時不會發生接管。因此、無論是否執行、都無法自動恢復 `-auto-giveback` 參數設為 true 。發生用戶端中斷。



== 自動還原參數組合的效果、適用於緊急情況。

下表列出 `storage failover modify` 適用於緊急情況的命令參數：

|===


| 參數 | 預設設定 


 a| 
`-onpanic _true | false_`
 a| 
`_true_`



 a| 
`-auto-giveback-after-panic _true | false_`

（權限：進階）
 a| 
`_true_`



 a| 
`-auto-giveback _true | false_`
 a| 
`_true_`

|===
下表說明的參數組合方式 `storage failover modify` 命令會在緊急情況下影響自動恢復。

[cols="60,40"]
|===


| `storage failover` 使用的參數 | 發生緊急狀況後、是否會自動還原？ 


| `-onpanic true`
`-auto-giveback true`
`-auto-giveback-after-panic true` | 是的 


| `-onpanic true`
`-auto-giveback true`
`-auto-giveback-after-panic false` | 是的 


| `-onpanic true`
`-auto-giveback false`
`-auto-giveback-after-panic true` | 是的 


| `-onpanic true`
`-auto-giveback false`
`-auto-giveback-after-panic false` | 否 


| `-onpanic false`
如果 `-onpanic` 設為 `false`、無論設定的值為何、都不會執行接管 / 恢復作業 `-auto-giveback` 或 `-auto-giveback-after-panic` | 否 
|===

NOTE: 接管可能是因為故障與恐慌無關。  當節點與其合作夥伴之間的通訊中斷時、也稱為「_活動訊號遺失_」、就會發生_故障_。如果因故障而發生接管、則會由控制恢復 `-onfailure` 參數而非 `-auto-giveback-after-panic parameter`。


NOTE: 當節點出現緊急情況時、它會將緊急情況封包傳送至其合作夥伴節點。  如果合作夥伴節點因為任何原因而未收到緊急封包、則該緊急情況可能會被誤解為故障。  如果沒有收到緊急封包、合作夥伴節點就只知道通訊已中斷、而且不知道發生了恐慌。  在這種情況下、合作夥伴節點會將失去通訊視為失敗而非恐慌處理、而傳回則由控制 `-onfailure` 參數（而非 `-auto-giveback-after-panic parameter`）。

以取得詳細資訊 `storage failover modify` 參數、請參閱 link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-modify.html["手冊頁ONTAP"]。
