---
sidebar: sidebar 
permalink: high-availability/ha_how_hardware-assisted_takeover_works.html 
keywords: ontap, high, availability, hwassist, hardware-assisted, hardware, assisted, takeovers 
summary: 依預設、硬體輔助接管功能可使用節點的遠端管理裝置（服務處理器）來加速接管程序。 
---
= 了解 ONTAP 叢集中的硬體輔助接管
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
依預設、硬體輔助接管功能可使用節點的遠端管理裝置（服務處理器）來加速接管程序。

當遠端管理裝置偵測到故障時、它會快速啟動接管、而非等待ONTAP 看到合作夥伴的活動訊號已經停止。如果在未啟用此功能的情況下發生故障、合作夥伴會等待直到發現節點不再發出活動訊號、確認活動訊號遺失、然後啟動接管。

硬體輔助接管功能使用下列程序來避免此類等待：

. 遠端管理裝置會監控本機系統是否發生特定類型的故障。
. 如果偵測到故障、遠端管理裝置會立即傳送警示給合作夥伴節點。
. 收到警示後、合作夥伴便會啟動接管。




== 觸發硬體輔助接管的系統事件

視合作夥伴節點從遠端管理裝置（服務處理器）接收到的警示類型而定、合作夥伴節點可能會產生接管。

[cols="30,20,50"]
|===


| 警示 | 接收時開始接管？ | 說明 


| 異常_重新開機 | 否 | 節點發生異常重新開機。 


| L2_Watchder_RESET | 是的 | 系統監督硬體偵測到L2重設。
遠端管理裝置偵測到系統CPU沒有回應、並重新設定系統。 


| Loss of活動訊號 | 否 | 遠端管理裝置不再從節點接收到活動訊號訊息。
此警示並非指HA配對中節點之間的活動訊號訊息、而是指節點與其本機遠端管理裝置之間的活動訊號。 


| 週期性訊息 | 否 | 在正常的硬體輔助接管作業期間、會傳送定期訊息。 


| 關機後再開機 | 是的 | 遠端管理裝置已關閉並開啟系統電源。 


| 電力損失 | 是的 | 節點發生電力中斷。
遠端管理裝置的電源供應器可在電力中斷後的一段短時間內維持電力、讓它向合作夥伴報告電力中斷。 


| 關機透過sp | 是的 | 遠端管理裝置已關閉系統電源。 


| 重設_via sp | 是的 | 遠端管理裝置會重設系統。 


| 測試 | 否 | 系統會傳送測試訊息、以驗證硬體輔助接管作業。 
|===
.相關資訊
https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/Hardware-assisted_%28HWassist%29_takeover_-_Resolution_guide["硬體輔助（ HWAssist ）接管 - 解析指南"^]
