---
sidebar: sidebar 
permalink: high-availability/ha_manual_takeover.html 
keywords: ontap, high, availability, ha, pair, manual, takeover, moving, move, epislon, manually, initiated 
summary: 您可以在合作夥伴需要維護時、以及在其他類似情況下、手動執行接管作業。 
---
= 手動接管命令
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在合作夥伴需要維護時、以及在其他類似情況下、手動執行接管作業。視合作夥伴的狀態而定、您用來執行接管的命令會有所不同。

|===


| 如果您想要... | 使用此命令... 


| 接管合作夥伴節點 | "容錯移轉接管" 


| 當合作夥伴的集合體移至執行接管的節點時、請監控接管的進度 | 「容錯移轉show takeover」 


| 顯示叢集中所有節點的儲存容錯移轉狀態 | 「容錯移轉顯示」 


| 接管合作夥伴節點、而不移轉lifs | 《儲存容錯移轉接管設定（SKIP‑LIF）移轉設定（在接管之前）》（true） 


| 即使磁碟不相符、也要接管合作夥伴節點 | 《儲存容錯移轉接管設定（SKIP‑LIF）移轉設定（在接管之前）》（true） 


| 接管合作夥伴節點、即使ONTAP 存在不相符的版本*注意：*此選項僅在不中斷營運ONTAP 的更新程序中使用。 | "torage容錯移轉接管選項允許版本不符" 


| 接管合作夥伴節點、而不執行Aggregate重新配置 | “torage容錯移轉接管-跳過最佳化為真的” 


| 在合作夥伴有時間正常關閉其儲存資源之前、請接管合作夥伴節點 | "torage容錯移轉接管'選項Immediate（立即） 
|===
[NOTE]
====
在您使用immediate選項發出儲存容錯移轉命令之前、您必須使用下列命令將資料l區 移轉到另一個節點：「network interface mall-all -node-nodE_」

如果您指定了「儲存容錯移轉接管」選項immediate」命令、但未先移轉資料生命週期、即使未指定「在接管之前移轉」選項、從節點移轉資料LIF的作業也會大幅延遲。

同樣地、如果您指定「立即」選項、即使「略過最佳化」選項設定為_fals__、也會略過協調的接管最佳化。

====


== 移動epsilon以進行某些手動啟動的接管

如果您預期任何手動啟動的移轉作業都可能導致儲存系統發生一個非預期的節點故障、而不會造成整個叢集的仲裁損失、則應移除epsilon。

若要執行計畫性維護、您必須接管HA配對中的其中一個節點。必須維持整個叢集的仲裁、以防止其餘節點發生非計畫性的用戶端資料中斷。在某些情況下、執行接管可能會導致叢集發生一個非預期的節點故障、而不會造成整個叢集的仲裁遺失。

如果正在接管的節點保留了epsilon、或使用epsilon的節點不健全、就可能發生這種情況。若要維護更具恢復能力的叢集、您可以將epsilon傳輸至未接管的正常節點。通常這是HA合作夥伴。

只有健全且符合資格的節點才會參與仲裁投票。若要維持整個叢集的仲裁人數、則需要超過N/2的票數（其中_N_代表健全、符合資格的線上節點總和）。在具有偶數個線上節點的叢集中、epsilon會增加額外的投票權重、以維持指派給該節點的仲裁。


NOTE: 雖然可使用「叢集修改資格為假」命令來修改叢集形成投票、但除非是還原節點組態或延長節點維護等情況、否則您應該避免這樣做。如果您將節點設為「不合格」、它會停止提供SAN資料、直到節點重設為符合資格且重新開機為止。當節點不符合資格時、對節點的NAS資料存取也可能受到影響。

.步驟
. 驗證叢集狀態、並確認epsilon是由未接管的健全節點所保留：
+
.. 變更為進階權限層級、確認您想要在進階模式提示出現時繼續（*>）：
+
"進階權限"

.. 判斷哪個節點擁有epsilon：
+
「叢集展示」

+
--
在下列範例中、Node1包含epsilon：

|===


| 節點 | 健全狀況 | 資格 | Epsilon 


| 節點1節點2  a| 
真的
 a| 
真的
 a| 
真假

|===
如果您要接管的節點不保留epsilon、請繼續執行步驟4。

--


. 從您要接管的節點移除epsilon：
+
「cluster modify -Node Node1 -epsilon假」

. 將epsilon指派給合作夥伴節點（在此範例中為Node2）：
+
「cluster modify -Node Node2 -epsilon true」

. 執行接管作業：
+
'容錯移轉接管-節點_node_name_'

. 返回管理權限層級：
+
「et -priv. admin」


