---
sidebar: sidebar 
permalink: high-availability/ha_manual_giveback.html 
keywords: ontap, high, availability, ha, pair, manual, giveback, interrupted, vetoed, veto, commands, performing, perform 
summary: 您可以執行一般的恢復、在合作夥伴節點上終止程序的恢復、或是強制恢復。 
---
= 手動恢復命令
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以執行一般的恢復、在合作夥伴節點上終止程序的恢復、或是強制恢復。


NOTE: 在執行恢復之前、您必須先移除接管系統中故障的磁碟機、如所述 link:../disks-aggregates/index.html["磁碟與集合體管理"]。



== 如果恢復中斷

如果接管節點在恢復程序期間發生故障或停電、則該程序會停止、接管節點會返回接管模式、直到故障修復或電力恢復為止。

不過、這取決於故障發生的還原階段。如果節點在部分恢復狀態期間（在將根Aggregate提供給它之後）遇到故障或停電、就不會返回接管模式。相反地、節點會返回部分恢復模式。  如果發生這種情況、請重複恢復作業來完成程序。



== 如果已遭否決

如果已遭否決、您必須檢查EMS訊息、以判斷原因。視原因而定、您可以決定是否可以安全地置換否決。

。 `storage failover show-giveback` 命令會顯示恢復進度、並顯示哪個子系統曾否決恢復（如果有）。軟性的否決可以被取代、而硬的否決也無法取代、即使強制使用也一樣。下表摘要說明不應覆寫的軟式使用方式、以及建議的因應措施。

您可以使用下列命令、檢閱任何恢復使用的EMS詳細資料：

`event log show -node * -event gb*`



== 根Aggregate的GiveBack

這些否決不適用於集合體重新配置作業：

[cols="35,65"]
|===


| 否決子系統模組 | 因應措施 


 a| 
vFiler_Low_Level
 a| 
終止導致否決的SMB工作階段、或關閉建立開放工作階段的SMB應用程式。

如果使用SMB來取代此類使用權、可能會導致應用程式突然中斷連線並遺失資料。



 a| 
磁碟檢查
 a| 
在嘗試恢復之前、應先移除所有故障或跳過的磁碟。如果磁碟正在消毒、您應該等到作業完成。

覆寫此否決可能會因為保留衝突或無法存取的磁碟而導致集合體或磁碟區離線而導致中斷運作。

|===


== SFO Aggregate的GiveBack

這些否決不適用於集合體重新配置作業：

[cols="35,65"]
|===


| 否決子系統模組 | 因應措施 


 a| 
鎖定管理程式
 a| 
正常關閉具有開啟檔案的SMB應用程式、或將這些磁碟區移至不同的Aggregate。

如果忽略此項否決、將會導致SMB鎖定狀態遺失、進而造成中斷和資料遺失。



 a| 
鎖定管理程式不需要
 a| 
等待鎖定鏡射。

如果忽略此項限制、將會導致Microsoft Hyper-V虛擬機器中斷運作。



| RAID  a| 
檢查EMS訊息、以判斷使用者是否因為下列原因而遭到使用：

如果因nvfile而導致使用者遭到使用、請將離線磁碟區和集合體上線。

如果正在進行磁碟新增或磁碟所有權重新指派作業、請等到作業完成後再進行。

如果因Aggregate名稱或UUID衝突而導致使用者遭到使用、請進行疑難排解並解決問題。

如果因為鏡射重新同步、鏡射驗證或離線磁碟而導致使用者使用此功能、則可覆寫使用者使用的功能、並在還原後重新啟動作業。



| 磁碟資源清冊  a| 
疑難排解以找出並解決問題的原因。

目的地節點可能無法看到屬於正在移轉之集合體的磁碟。

無法存取的磁碟可能導致無法存取的集合體或磁碟區。



| Volume Move操作  a| 
疑難排解以找出並解決問題的原因。

這種否決可防止磁碟區移動作業在重要的轉換階段中止。如果工作在轉換期間中止、則磁碟區可能無法存取。

|===


=== 執行手動恢復的命令

您可以手動在 HA 配對中的節點上啟動恢復、以便在完成維護或解決之後、將儲存設備歸還給原始擁有者
導致接管的任何問題。

|===


| 如果您想要... | 使用此命令... 


 a| 
將儲存設備交回合作夥伴節點
| `storage failover giveback ‑ofnode _nodename_` 


 a| 
即使合作夥伴未處於等待恢復模式、仍可歸還儲存設備
 a| 
`storage failover giveback ‑ofnode _nodename_`
`‑require‑partner‑waiting false`

除非可以接受較長的用戶端停機時間、否則請勿使用此選項。



| 即使程序正在否決恢復作業、也要歸還儲存設備（強制歸還）  a| 
`storage failover giveback ‑ofnode _nodename_`
`‑override‑vetoes true`

使用此選項可能會導致用戶端停機時間延長、或是在恢復後無法上線的集合體和磁碟區。



| 僅回饋CFO集合體（根集合體）  a| 
`storage failover giveback ‑ofnode _nodename_`

`‑only‑cfo‑aggregates true`



| 發出「恢復」命令後、請監控還原進度 | `storage failover show‑giveback` 
|===