---
sidebar: sidebar 
permalink: high-availability/halt-reboot-node-wo-takeover-task.html 
keywords: high availability pair, hair, inhibit-takeover, reboot, epsilon, HA 
summary: 當您在節點或機櫃上執行特定的硬體維護、並想要保持合作夥伴節點正常運作、以限制停機時間時、您無需啟動接管、即可停止或重新啟動雙節點叢集中的節點、 或是當發生無法手動接管的問題、而您想要讓合作夥伴節點的集合體維持正常運作並提供資料時。此外、如果技術支援正在協助您疑難排解問題、他們可能會請您執行此程序、做為這些工作的一部分。 
---
= 停止或重新開機節點、而不在雙節點叢集中啟動接管
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
當您在節點或機櫃上執行特定的硬體維護、並想要保持合作夥伴節點正常運作、以限制停機時間時、您無需啟動接管、即可停止或重新啟動雙節點叢集中的節點、 或是當發生無法手動接管的問題、而您想要讓合作夥伴節點的集合體維持正常運作並提供資料時。此外、如果技術支援正在協助您疑難排解問題、他們可能會請您執行此程序、做為這些工作的一部分。

.關於這項工作
* 禁止接管之前（使用 `-inhibit-takeover true` 參數）、您可以停用叢集 HA 。


[CAUTION]
====
* 在雙節點叢集中、叢集HA可確保一個節點的故障不會停用叢集。不過、如果您在使用之前未停用叢集 HA  `-inhibit-takeover true` 參數、兩個節點都會停止提供資料。
* 如果您在停用叢集HA之前嘗試停止或重新開機節點、ONTAP 則會發出警告並指示您停用叢集HA。


====
* 您可以將LIF（邏輯介面）移轉至想要保持連線的合作夥伴節點。
* 如果您要停止或重新開機的節點上有您要保留的集合體、請將其移至您要保持連線的節點。


.步驟
. 確認兩個節點都正常：
`cluster show`
+
對於兩個節點、 `true` 會出現在中 `Health` 欄位。

+
[listing]
----
cluster::> cluster show
Node         Health  Eligibility
------------ ------- ------------
node1        true     true
node2        true     true
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["指令參考資料ONTAP"^]需詳細 `cluster show`資訊，請參閱。

. 將所有生命從您要停止或重新開機的節點移轉至合作夥伴節點：
`network interface migrate-all -node _node_name_`
. 如果您要在節點上停止或重新開機、當節點當機時、有您想要保持線上狀態的集合體、請將它們重新放置到合作夥伴節點；否則、請執行下一步。
+
.. 在您要停止或重新開機的節點上顯示集合體：
`storage aggregates show -node _node_name_`
+
例如、node1是要暫停或重新開機的節點：

+
[listing]
----
cluster::> storage aggregates show -node node1
Aggregate  Size  Available  Used%  State  #Vols   Nodes   RAID  Status
---------  ----  ---------  -----  -----  -----   -----   ----  ------
aggr0_node_1_0
           744.9GB   32.68GB   96% online       2 node1    raid_dp,
                                                                normal
aggr1       2.91TB    2.62TB   10% online       8 node1    raid_dp,
                                                                normal
aggr2
            4.36TB    3.74TB   14% online      12 node1    raid_dp,
                                                                normal
test2_aggr  2.18TB    2.18TB    0% online       7 node1    raid_dp,
                                                                normal
4 entries were displayed.
----
.. 將集合體移至合作夥伴節點：
`storage aggregate relocation start -node _node_name_ -destination _node_name_ -aggregate-list _aggregate_name_`
+
例如、Agggr1、aggr2和test2_aggr正在從節點1移至節點2：

+
`storage aggregate relocation start -node _node1_ -destination _node2_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`



. 停用叢集 HA ：
`cluster ha modify -configured false`
+
傳回輸出會確認 HA 已停用： `Notice: HA is disabled`

+

NOTE: 此作業不會停用儲存容錯移轉。

. 使用適當的命令來停止或重新開機、並禁止接管目標節點：
+
** `system node halt -node _node_name_ -inhibit-takeover true`
** `system node reboot -node _node_name_ -inhibit-takeover true`
+

NOTE: 在命令輸出中、您會看到一則警告、詢問您是否要繼續、請輸入 `y`。



. 確認仍在線上的節點處於正常狀態（當合作夥伴關機時）：
`cluster show`
+
對於線上節點、 `true` 會出現在中 `Health` 欄位。

+

NOTE: 在命令輸出中、您會看到叢集HA未設定的警告。此時您可以忽略此警告。

. 執行必要的動作、以停止或重新啟動節點。
. 從載入程式提示字元啟動離線節點：
`boot_ontap`
. 確認兩個節點都正常：
`cluster show`
+
對於兩個節點、 `true` 會出現在中 `Health` 欄位。

+

NOTE: 在命令輸出中、您會看到叢集HA未設定的警告。此時您可以忽略此警告。

. 重新啟用叢集 HA ：
`cluster ha modify -configured true`
. 如果您在本程序稍早將集合體重新定位至合作夥伴節點、請將它們移回其主節點；否則、請移至下一步：
`storage aggregate relocation start -node _node_name_ -destination _node_name_ -aggregate-list _aggregate_name_`
+
例如、 Aggr1 、 aggr2 和 test2_aggr 正從節點 node2 移至節點 node1 ：
`storage aggregate relocation start -node _node2_ -destination _node1_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`

. 將LIF還原至其主連接埠：
+
.. 檢視不在家裡的生命：
`network interface show -is-home false`
.. 如果沒有從下一節點移轉的非主系LIF、請在還原之前確認是否可以安全地移動它們。
.. 如果安全的話、請將所有LIF回復到主目錄。
`network interface revert *`




.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-ha-modify.html["叢集ha修改"^]

