---
sidebar: sidebar 
permalink: high-availability/halt-reboot-node-wo-takeover-task.html 
keywords: high availability pair, hair, inhibit-takeover, reboot, epsilon, HA 
summary: 當您在節點或機櫃上執行特定的硬體維護、並想要保持合作夥伴節點正常運作、以限制停機時間時、您無需啟動接管、即可停止或重新啟動雙節點叢集中的節點、 或是當發生無法手動接管的問題、而您想要讓合作夥伴節點的集合體維持正常運作並提供資料時。此外、如果技術支援正在協助您疑難排解問題、他們可能會請您執行此程序、做為這些工作的一部分。 
---
= 在雙節點叢集中，無需啟動接管即可暫停或重新啟動 ONTAP 節點
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
當您在節點或機櫃上執行特定的硬體維護、並想要保持合作夥伴節點正常運作、以限制停機時間時、您無需啟動接管、即可停止或重新啟動雙節點叢集中的節點、 或是當發生無法手動接管的問題、而您想要讓合作夥伴節點的集合體維持正常運作並提供資料時。此外、如果技術支援正在協助您疑難排解問題、他們可能會請您執行此程序、做為這些工作的一部分。

.關於這項工作
* 禁止接管之前（使用 `-inhibit-takeover true` 參數）、您可以停用叢集 HA 。


[CAUTION]
====
* 在雙節點叢集中、叢集HA可確保一個節點的故障不會停用叢集。不過、如果您在使用之前未停用叢集 HA  `-inhibit-takeover true` 參數、兩個節點都會停止提供資料。
* 如果您在停用叢集HA之前嘗試停止或重新開機節點、ONTAP 則會發出警告並指示您停用叢集HA。


====
* 您可以將LIF（邏輯介面）移轉至想要保持連線的合作夥伴節點。
* 如果您要停止或重新開機的節點上有您要保留的集合體、請將其移至您要保持連線的節點。


.步驟
. 確認兩個節點均運作正常：
+
[source, cli]
----
cluster show
----
+
對於兩個節點、 `true` 會出現在中 `Health` 欄位。

+
[listing]
----
cluster::> cluster show
Node         Health  Eligibility
------------ ------- ------------
node1        true     true
node2        true     true
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/cluster-show.html["指令參考資料ONTAP"^]需詳細 `cluster show`資訊，請參閱。

. 將要停止或重新啟動的節點上的所有 LIF 遷移到合作夥伴節點：
+
[source, cli]
----
network interface migrate-all -node <node_name>
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/network-interface-migrate-all.html["指令參考資料ONTAP"^]需詳細 `network interface migrate-all`資訊，請參閱。

. 如果您要停止或重新開機的節點上有您想要在節點關閉時保持線上的集合體，請將它們重新配置到合作夥伴節點。
+
.. 顯示將要停止或重新啟動的節點上的 Aggregate ：
+
[source, cli]
----
storage aggregates show -node <node_name>
----
+
例如、node1是要暫停或重新開機的節點：

+
[listing]
----
cluster::> storage aggregates show -node node1
Aggregate  Size  Available  Used%  State  #Vols   Nodes   RAID  Status
---------  ----  ---------  -----  -----  -----   -----   ----  ------
aggr0_node_1_0
           744.9GB   32.68GB   96% online       2 node1    raid_dp,
                                                                normal
aggr1       2.91TB    2.62TB   10% online       8 node1    raid_dp,
                                                                normal
aggr2
            4.36TB    3.74TB   14% online      12 node1    raid_dp,
                                                                normal
test2_aggr  2.18TB    2.18TB    0% online       7 node1    raid_dp,
                                                                normal
4 entries were displayed.
----
.. 將 aggregate 移至合作夥伴節點：
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
例如、Agggr1、aggr2和test2_aggr正在從節點1移至節點2：

+
`storage aggregate relocation start -node _node1_ -destination _node2_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`



. 停用叢集 HA ：
+
[source, cli]
----
cluster ha modify -configured false
----
+
當叢集 HA 停用時，epsilon 會自動移至節點 1。傳回輸出確認 HA 已停用： `Notice: HA is disabled`

+

NOTE: 此作業不會停用儲存容錯移轉。

. 如果要停止或重新啟動的節點是節點 1、請將 epsilon 移至節點 2：
+
.. 將權限層級設為進階：
+
[source, cli]
----
set -privilege advanced
----
.. 驗證節點 2 是否健全且符合 epsilon 資格：
+
[source, cli]
----
cluster show
----
.. 從節點 1 移除 epsilon：
+
[source, cli]
----
cluster modify -node <node1_name> -epsilon false
----
.. 將 epsilon 指派給節點 2：
+
[source, cli]
----
cluster modify -node <node2_name> -epsilon true
----
.. 確認 epsilon 是否位於節點 2 上：
+
[source, cli]
----
cluster show
----


. 停止或重新啟動目標節點、並阻止其被接管：
+
[cols="1h,1h"]
|===


 a| 
停止節點而不啟動接管：
 a| 
[source, cli]
----
system node halt -node _node_name_ -inhibit-takeover true
----


 a| 
重新啟動節點而不啟動接管：
 a| 
[source, cli]
----
system node reboot -node _node_name_ -inhibit-takeover true
----
|===
+

NOTE: 在命令輸出中、您會看到一則警告、詢問您是否要繼續、請輸入 `y`。

. 確認仍在線上的節點處於健康狀態（當合作夥伴節點當機時）：
+
[source, cli]
----
cluster show
----
+
對於線上節點、 `true` 會出現在中 `Health` 欄位。

+

NOTE: 在命令輸出中，您會看到叢集 HA 未配置的警告。您可以忽略此警告。

. 執行必要的動作、以停止或重新啟動節點。
. 從 LOADER 提示符號啟動離線節點：
+
[source, cli]
----
boot_ontap
----
. 確認兩個節點均運作正常：
+
[source, cli]
----
cluster show
----
+
對於兩個節點、 `true` 會出現在中 `Health` 欄位。

+

NOTE: 在命令輸出中、您會看到叢集HA未設定的警告。此時您可以忽略此警告。

. 重新啟用叢集 HA：
+
[source, cli]
----
cluster ha modify -configured true
----
. 如果在此程序的早期階段，您已將 Aggregate 重新配置到合作夥伴節點，請將它們移回其主節點。
+
[source, cli]
----
storage aggregate relocation start -node <node_name> -destination <node_name> -aggregate-list <aggregate_name>
----
+
例如、 Aggr1 、 aggr2 和 test2_aggr 正從節點 node2 移至節點 node1 ：
`storage aggregate relocation start -node _node2_ -destination _node1_ -aggregate-list _aggr1_,_aggr2_,_test2_aggr_`

. 將LIF還原至其主連接埠：
+
.. 檢視不在主節點的 LIF：
+
[source, cli]
----
network interface show -is-home false
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["指令參考資料ONTAP"^]需詳細 `network interface show`資訊，請參閱。

.. 如果沒有從下一節點移轉的非主系LIF、請在還原之前確認是否可以安全地移動它們。
.. 如果這樣做安全，請將所有 LIF 還原。
+
[source, cli]
----
 network interface revert *
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/network-interface-revert.html["指令參考資料ONTAP"^]需詳細 `network interface revert`資訊，請參閱。





.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-ha-modify.html["叢集ha修改"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-relocation-start.html["儲存聚合遷移開始"^]

