---
sidebar: sidebar 
permalink: high-availability/index.html 
keywords: high availability, ha, overview 
summary: 接管是指節點接管其合作夥伴儲存設備的程序。GiveBack是將儲存設備歸還給合作夥伴的程序。 
---
= HA配對管理總覽
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
叢集節點是以高可用度（HA）配對配置、以提供容錯能力和不中斷營運。如果某個節點發生故障、或是您需要關閉節點以進行例行維護、其合作夥伴可以接管其儲存設備、並繼續從其中提供資料。當節點恢復連線時、合作夥伴會將儲存設備提供給您。

HA配對控制器組態包含一對相符的FAS/AFF儲存控制器（本機節點和合作夥伴節點）。每個節點都連接到對方的磁碟櫃。當HA配對中的某個節點發生錯誤並停止處理資料時、其合作夥伴會偵測合作夥伴的失敗狀態、並接管該控制器的所有資料處理。

_Takeove_是節點控制其合作夥伴儲存設備的程序。

_Giveback _是將儲存設備歸還給合作夥伴的程序。

根據預設、在下列任一情況下、移轉都會自動發生：

* 軟體或系統故障發生在導致恐慌的節點上。HA配對控制器會自動容錯移轉至其合作夥伴節點。當合作夥伴從恐慌中恢復並開機後、節點會自動執行恢復、讓合作夥伴恢復正常運作。
* 節點發生系統故障、節點無法重新開機。例如、當某個節點因停電而故障時、HA配對控制器會自動容錯移轉至其合作夥伴節點、並從存續的儲存控制器提供資料。



NOTE: 如果節點的儲存設備同時斷電、則無法進行標準接管。

* 不會從節點的合作夥伴收到活動訊息。如果合作夥伴遇到硬體或軟體故障（例如互連故障）、但並未造成恐慌、但仍無法正常運作、就可能發生這種情況。
* 您可以停止其中一個節點、而不使用「-f」或「-禁止 接管true」參數。



NOTE: 在已啟用叢集HA的雙節點叢集中、使用「-INITRO-takeover true」參數停止或重新啟動節點、會導致兩個節點停止提供資料、除非您先停用叢集HA、然後將epsilon指派給要保持連線的節點。

* 您可以重新啟動其中一個節點、而不使用「-IN禁止 接管」true參數。（預設會啟用「儲存容錯移轉」命令的「onboot」參數。）
* 遠端管理裝置（服務處理器）會偵測到合作夥伴節點故障。如果您停用硬體輔助接管、則不適用此選項。


您也可以使用「儲存容錯移轉接管」命令手動啟動接管。
