---
permalink: nas-audit/cli-change-events-concept.html 
sidebar: sidebar 
keywords: cli change events, audited 
summary: 可稽核某些CLI變更事件、包括特定SMB共用事件、特定稽核原則事件、特定本機安全性群組事件、本機使用者群組事件、以及授權原則事件。ONTAP瞭解哪些變更事件可稽核、有助於解讀事件記錄的結果。 
---
= 可稽核的CLI變更事件總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
可稽核某些CLI變更事件、包括特定SMB共用事件、特定稽核原則事件、特定本機安全性群組事件、本機使用者群組事件、以及授權原則事件。ONTAP瞭解哪些變更事件可稽核、有助於解讀事件記錄的結果。

您可以手動旋轉稽核記錄、啟用或停用稽核、顯示稽核變更事件的相關資訊、修改稽核變更事件、以及刪除稽核變更事件、藉此管理儲存虛擬機器（SVM）稽核CLI變更事件。

身為系統管理員、如果您執行任何命令來變更SMB共用區、本機使用者群組、本機安全性群組、授權原則及稽核原則事件的相關組態、 產生記錄並稽核相應的事件：

|===


| 稽核類別 | 活動 | 事件ID | 執行此命令... 


 a| 
主機稽核
 a| 
原則變更
 a| 
[4719]稽核組態已變更
 a| 
`vserver audit disable|enable|modify`



 a| 
檔案共用
 a| 
已新增[5142]網路共用
 a| 
`vserver cifs share create`



 a| 
[5143]網路共用區已修改
 a| 
`vserver cifs share modify` `vserver cifs share create|modify|delete` `vserver cifs share add|remove`



 a| 
[5144]網路共用區已刪除
 a| 
`vserver cifs share delete`



 a| 
稽核
 a| 
使用者帳戶
 a| 
[4720]本機使用者已建立
 a| 
`vserver cifs users-and-groups local-user create` `vserver services name-service unix-user create`



 a| 
[4722]本機使用者已啟用
 a| 
`vserver cifs users-and-groups local-user create|modify`



 a| 
[4724]本機使用者密碼重設
 a| 
`vserver cifs users-and-groups local-user set-password`



 a| 
[4725]本機使用者已停用
 a| 
`vserver cifs users-and-groups local-user create|modify`



 a| 
[4726]本機使用者已刪除
 a| 
`vserver cifs users-and-groups local-user delete` `vserver services name-service unix-user delete`



 a| 
[4738]本機使用者變更
 a| 
`vserver cifs users-and-groups local-user modify` `vserver services name-service unix-user modify`



 a| 
[4781]本機使用者重新命名
 a| 
`vserver cifs users-and-groups local-user rename`



 a| 
安全性群組
 a| 
[4731]已建立本機安全性群組
 a| 
`vserver cifs users-and-groups local-group create` `vserver services name-service unix-group create`



 a| 
[4734]本機安全性群組已刪除
 a| 
`vserver cifs users-and-groups local-group delete` `vserver services name-service unix-group delete`



 a| 
[4735]本機安全性群組已修改
 a| 
`vserver cifs users-and-groups local-group rename|modify` `vserver services name-service unix-group modify`



 a| 
[4732]使用者已新增至本機群組
 a| 
`vserver cifs users-and-groups local-group add-members` `vserver services name-service unix-group adduser`



 a| 
[4733]使用者已從本機群組中移除
 a| 
`vserver cifs users-and-groups local-group remove-members` `vserver services name-service unix-group deluser`



 a| 
授權原則變更
 a| 
[4704]已指派使用者權限
 a| 
`vserver cifs users-and-groups privilege add-privilege`



 a| 
[4705]使用者權限已移除
 a| 
`vserver cifs users-and-groups privilege remove-privilege|reset-privilege`

|===
.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver["Vserver"^]

