---
permalink: nas-audit/display-security-trace-results-task.html 
sidebar: sidebar 
keywords: display, security trace results 
summary: 您可以顯示針對符合安全性追蹤篩選器的檔案作業所產生的安全性追蹤結果。您可以使用結果來驗證檔案存取安全性組態、或疑難排解SMB和NFS檔案存取問題。 
---
= 顯示安全性追蹤結果
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以顯示針對符合安全性追蹤篩選器的檔案作業所產生的安全性追蹤結果。您可以使用結果來驗證檔案存取安全性組態、或疑難排解SMB和NFS檔案存取問題。

.您需要的產品
啟用的安全性追蹤篩選器必須存在、而且必須從SMB或NFS用戶端執行作業、且該用戶端必須符合安全性追蹤篩選器、才能產生安全性追蹤結果。

.關於這項工作
您可以顯示所有安全性追蹤結果的摘要、也可以指定選用參數來自訂輸出中顯示的資訊。當安全性追蹤結果包含大量記錄時、這一點很有幫助。

如果您未指定任何選用參數、則會顯示下列項目：

* 儲存虛擬機器（SVM）名稱
* 節點名稱
* 安全性追蹤索引編號
* 安全風格
* 路徑
* 理由
* 使用者名稱
+
使用者名稱會根據追蹤篩選器的設定方式顯示：

+
[cols="40,60"]
|===


| 如果篩選器已設定... | 然後... 


 a| 
使用UNIX使用者名稱
 a| 
安全性追蹤結果會顯示UNIX使用者名稱。



 a| 
使用Windows使用者名稱
 a| 
安全性追蹤結果會顯示Windows使用者名稱。



 a| 
沒有使用者名稱
 a| 
安全性追蹤結果會顯示Windows使用者名稱。

|===


您可以使用選用參數來自訂輸出。您可以使用某些選用參數來縮小命令輸出中傳回的結果範圍、其中包括：

[cols="35,65"]
|===


| 選用參數 | 說明 


 a| 
`-fields` `field_name`、 ...
 a| 
在您選擇的欄位上顯示輸出。您可以單獨使用此參數、也可以搭配其他選用參數一起使用。



 a| 
`-instance`
 a| 
顯示安全性追蹤事件的詳細資訊。此參數可搭配其他選用參數使用、以顯示特定篩選結果的詳細資訊。



 a| 
`-node` `node_name`
 a| 
僅顯示有關指定節點上事件的資訊。



 a| 
`-vserver` `vserver_name`
 a| 
僅顯示指定SVM上事件的相關資訊。



 a| 
`-index` `integer`
 a| 
顯示與指定索引編號對應之篩選器所產生之事件的相關資訊。



 a| 
`-client-ip` `IP_address`
 a| 
顯示從指定用戶端IP位址存取檔案所發生事件的相關資訊。



 a| 
`-path` `path`
 a| 
顯示因檔案存取指定路徑而發生事件的相關資訊。



 a| 
`-user-name` `user_name`
 a| 
顯示指定Windows或UNIX使用者存取檔案時所發生事件的相關資訊。



 a| 
`-security-style` `security_style`
 a| 
顯示在具有指定安全樣式的檔案系統上發生事件的相關資訊。

|===
請參閱手冊頁、以取得可搭配命令使用的其他選用參數資訊。

.步驟
. 使用顯示安全性追蹤篩選結果 `vserver security trace trace-result show` 命令。
+
`vserver security trace trace-result show -user-name domain\user`

+
[listing]
----
Vserver: vs1

Node     Index   Filter Details         Reason
-------- ------- ---------------------  -----------------------------
node1    3       User:domain\user       Access denied by explicit ACE
                 Security Style:mixed
                 Path:/dir1/dir2/

node1    5       User:domain\user       Access denied by explicit ACE
                 Security Style:unix
                 Path:/dir1/
----

