---
permalink: nas-audit/display-audit-policies-windows-security-tab-task.html 
sidebar: sidebar 
keywords: display, information, audit policies, windows security tab 
summary: 您可以使用「Windows內容」視窗中的「安全性」索引標籤、顯示已套用至檔案和目錄的稽核原則相關資訊。這種方法與存放在Windows伺服器上的資料相同、可讓客戶使用慣用的GUI介面。 
---
= 使用Windows安全性索引標籤顯示稽核原則的相關資訊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「Windows內容」視窗中的「安全性」索引標籤、顯示已套用至檔案和目錄的稽核原則相關資訊。這種方法與存放在Windows伺服器上的資料相同、可讓客戶使用慣用的GUI介面。

.關於這項工作
顯示套用至檔案和目錄的稽核原則相關資訊、可讓您驗證是否已在指定的檔案和資料夾上設定適當的系統存取控制清單（SACL）。

若要顯示已套用至NTFS檔案和資料夾的SACL相關資訊、請在Windows主機上完成下列步驟。

.步驟
. 從Windows檔案總管的*工具*功能表中、選取*對應網路磁碟機*。
. 完成*對應網路磁碟機*對話方塊：
+
.. 選取*磁碟機*字母。
.. 在「*資料夾*」方塊中、輸入儲存虛擬機器（SVM）的IP位址或SMB伺服器名稱、其中包含要稽核的資料及共用名稱。
+
如果您的 SMB 伺服器名稱為「 ShMB_Server 」、而您的共用名稱為「 shahre1 」、則您應該輸入 `\\SMB_SERVER\share1`。

+
[NOTE]
====
您可以指定 SMB 伺服器的資料介面 IP 位址、而非 SMB 伺服器名稱。

====
.. 單擊*完成*。


+
您選取的磁碟機會掛載、並在Windows檔案總管視窗中顯示共用區中包含的檔案和資料夾、做好準備。

. 選取您要顯示稽核資訊的檔案或目錄。
. 在檔案或目錄上按一下滑鼠右鍵、然後選取*內容*。
. 選取*安全性*索引標籤。
. 按一下*進階*。
. 選取*稽核*索引標籤。
. 按一下 * 繼續 * 。
+
稽核方塊隨即開啟。「*稽核項目*」方塊會顯示套用SACL的使用者和群組摘要。

. 在「*稽核項目*」方塊中、選取您要顯示其SACL項目的使用者或群組。
. 按一下 * 編輯 * 。
+
隨即開啟<object>的稽核項目方塊。

. 在「*存取*」方塊中、檢視套用至所選物件的目前SACL。
. 按一下*取消*以關閉*稽核項目*方塊。
. 單擊*取消*關閉*稽核*方塊。

