---
permalink: nas-audit/fpolicy-config-types-concept.html 
sidebar: sidebar 
keywords: fpolicy, configuration types 
summary: 有兩種基本的FPolicy組態類型。其中一個組態使用外部FPolicy伺服器來處理通知並根據通知採取行動。另一個組態不使用外部FPolicy伺服器、而是使用ONTAP 內部的、原生的FPolicy伺服器、根據副檔名來進行簡單的檔案封鎖。 
---
= FPolicy組態類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
有兩種基本的FPolicy組態類型。其中一個組態使用外部FPolicy伺服器來處理通知並根據通知採取行動。另一個組態不使用外部FPolicy伺服器、而是使用ONTAP 內部的、原生的FPolicy伺服器、根據副檔名來進行簡單的檔案封鎖。

* *外部FPolicy伺服器組態*
+
通知會傳送至FPolicy伺服器、該伺服器會篩選要求並套用規則、以判斷節點是否應允許要求的檔案操作。對於同步原則、FPolicy伺服器接著會傳送回應給節點、以允許或封鎖要求的檔案作業。

* *原生FPolicy伺服器組態*
+
通知會在內部篩選。根據在FPolicy範圍中設定的副檔名設定、允許或拒絕要求。





== 何時建立原生FPolicy組態

原生FPolicy組態使用ONTAP 內部的FPolicy引擎、根據檔案副檔名來監控及封鎖檔案作業。此解決方案不需要外部FPolicy伺服器（FPolicy伺服器）。當這個簡單的解決方案只是需要的時候、使用原生檔案封鎖組態是適當的做法。

原生檔案封鎖功能可讓您監控符合設定作業和篩選事件的任何檔案作業、然後拒絕存取具有特定副檔名的檔案。這是預設組態。

此組態可讓您僅根據檔案副檔名來封鎖檔案存取。例如、若要封鎖包含「mP3」副檔名的檔案、您可以設定原則、針對目標副檔名為「mP3」的特定作業提供通知。此原則設定為拒絕「mp3」檔案要求、以便執行產生通知的作業。

下列項目適用於原生FPolicy組態：

* FPolicy伺服器型檔案篩選所支援的相同篩選器和傳輸協定集、也支援原生檔案封鎖。
* 您可以同時設定原生檔案封鎖和FPolicy伺服器型檔案篩選應用程式。
+
若要這麼做、您可以針對儲存虛擬機器（SVM）設定兩個獨立的FPolicy原則、其中一個設定為原生檔案封鎖、另一個設定為FPolicy伺服器型檔案篩選。

* 原生檔案封鎖功能只會根據副檔名而非檔案內容來篩選檔案。
* 在符號連結的情況下、原生檔案封鎖會使用根檔案的副檔名。




== 何時建立使用外部FPolicy伺服器的組態

使用外部FPolicy伺服器來處理及管理通知的FPolicy組態、可針對需要根據副檔名進行簡單檔案封鎖的使用案例、提供健全的解決方案。

當您想要執行監控及記錄檔案存取事件、提供配額服務、根據簡單副檔名以外的條件執行檔案封鎖、使用階層式儲存管理應用程式提供資料移轉服務等作業時、應建立使用外部FPolicy伺服器的組態、 或是提供一組精細的原則、僅監控儲存虛擬機器（SVM）中的資料子集。
