---
permalink: nas-audit/persistent-stores.html 
sidebar: sidebar 
keywords: overview, persistent store, fpolicy 
summary: 從 ONTAP 9.14.1 開始、 FPolicy 可讓您設定持續儲存區、以擷取 SVM 中非強制性非非同步原則的檔案存取事件。持續儲存區可協助將用戶端 I/O 處理與 FPolicy 通知處理分離、以減少用戶端延遲。不支援同步和非同步強制組態。 
---
= FPolicy 永續性儲存區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9.14.1 開始、 FPolicy 可讓您設定持續儲存區、以擷取 SVM 中非強制性非非同步原則的檔案存取事件。持續儲存區可協助將用戶端 I/O 處理與 FPolicy 通知處理分離、以減少用戶端延遲。不支援同步（強制或非強制）和非同步強制組態。

此功能僅適用於 FPolicy 外部模式。您使用的合作夥伴應用程式需要支援此功能。您應與合作夥伴合作、確保支援此 FPolicy 組態。



== 最佳實務做法

叢集管理員必須在啟用 FPolicy 的每個 SVM 上、為持續儲存區設定磁碟區。設定後、持續儲存區會擷取所有符合的 FPolicy 事件、這些事件會在 FPolicy 管道中進一步處理、並傳送至外部伺服器。

當發生非預期的重新開機或停用 FPolicy 並再次啟用時、持續儲存區仍會保持上次收到事件的狀態。在接管作業之後、新事件將會由合作夥伴節點儲存及處理。恢復作業完成後、持續儲存區會繼續處理任何未處理的事件、這些事件可能會在節點接管發生時保留。即時事件將優先於未處理的事件。

如果持續儲存區磁碟區在同一個 SVM 中從一個節點移至另一個節點、則尚未處理的通知也會移至新節點。您需要重新執行 `fpolicy persistent-store create` 在磁碟區移動之後、在任一節點上執行命令、以確保擱置的通知會傳送至外部伺服器。

持續儲存區 Volume 是以每個 SVM 為基礎進行設定。對於每個啟用 FPolicy 的 SVM 、您都需要建立持續儲存區 Volume 。

在具有預期由 Fpolicy 監控最大流量的生命期的節點上建立持續儲存區磁碟區。

如果持續儲存區中累積的通知超過已配置的磁碟區大小、 FPolicy 將開始丟棄傳入通知、並顯示適當的 EMS 訊息。

在建立磁碟區時指定的持續儲存區磁碟區名稱和交會路徑應相符。

將 Snapshot 原則設為 `none` 而非 `default`。這是為了確保不會意外還原快照而導致目前事件遺失、並防止可能的重複事件處理。

讓外部使用者傳輸協定存取（ CIFS/NFS ）無法存取持續儲存區磁碟區、以避免意外毀損或刪除持續存在的事件記錄。為達成此目的、在啟用 FPolicy 之後、請在 ONTAP 中卸載磁碟區以移除連接路徑、這會使使用者傳輸協定存取無法存取。

如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/ontap/nas-audit/create-persistent-stores.html["建立持續儲存區"]。
