---
permalink: nas-audit/plan-fpolicy-scope-config-concept.html 
sidebar: sidebar 
keywords: plan, fpolicy, scope, configuration 
summary: 在設定FPolicy範圍之前、您必須先瞭解建立範圍的意義。您必須瞭解範圍組態包含哪些內容。您也需要瞭解優先順序的範圍規則。此資訊可協助您規劃要設定的值。 
---
= 規劃FPolicy範圍組態總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在設定FPolicy範圍之前、您必須先瞭解建立範圍的意義。您必須瞭解範圍組態包含哪些內容。您也需要瞭解優先順序的範圍規則。此資訊可協助您規劃要設定的值。



== 建立FPolicy範圍的意義

建立FPolicy範圍是指定義套用FPolicy原則的界限。儲存虛擬機器（SVM）是基本邊界。當您建立FPolicy原則的範圍時、必須定義要套用該原則的FPolicy原則、而且必須指定要套用範圍的SVM。

有許多參數會進一步限制指定SVM內的範圍。您可以指定要納入範圍的內容、或指定要從範圍中排除的項目、來限制範圍。將範圍套用至已啟用的原則之後、原則事件檢查就會套用至此命令所定義的範圍。

系統會針對檔案存取事件產生通知、其中「include'」選項中有相符項目。不會針對檔案存取事件產生通知、其中「exclude」選項中有相符項目。

FPolicy範圍組態定義下列組態資訊：

* SVM名稱
* 原則名稱
* 要納入或排除的共享區
* 匯出原則、以納入或排除受監控的內容
* 要納入或排除的磁碟區
* 要納入或排除的檔案副檔名
* 是否對目錄物件進行檔案副檔名檢查


[NOTE]
====
叢集FPolicy原則的範圍有特殊考量。叢集FPolicy原則是叢集管理員為管理SVM所建立的原則。如果叢集管理員也為該叢集FPolicy原則建立範圍、則SVM管理員無法為該相同原則建立範圍。但是、如果叢集管理員未建立叢集FPolicy原則的範圍、則任何SVM管理員都可以建立該叢集原則的範圍。如果SVM管理員為該叢集FPolicy原則建立範圍、叢集管理員便無法隨後為該相同的叢集原則建立叢集範圍。這是因為叢集管理員無法覆寫同一個叢集原則的範圍。

====


== 優先順序的範圍規則為何

下列優先規則適用於範圍組態：

* 如果共享區包含在「共享區至包含區」參數中、且共享區的父Volume包含在「至排除區」參數中、則「至排除區」優先於「共享區至包含區」。
* 如果匯出原則包含在「-exper-policies to include-included」參數中、而且匯出原則的父Volume包含在「-volume to exclude」參數中、則「-volume to exclude」優先於「expexper-policies to include-included」。
* 系統管理員可以指定「副檔名」與「副檔名至排除」清單。
+
檢查「副檔名至排除」參數之前、會先檢查「副檔名至包含」參數。





== FPolicy範圍組態包含的內容

您可以使用下列可用的FPolicy範圍組態參數清單來協助規劃組態：

[NOTE]
====
當設定要納入或排除範圍的共用、匯出原則、磁碟區及副檔名時、包含和排除參數可以包含像是「」之類的元元符號?`" and "`*。不支援使用規則運算式。

====
[cols="70,30"]
|===


| 資訊類型 | 選項 


 a| 
_SVM_

指定您要在其中建立FPolicy範圍的SVM名稱。

每個FPolicy組態都是在單一SVM中定義。為了建立FPolicy原則組態、而將外部引擎、原則事件、原則範圍和原則結合在一起的原則、都必須與相同的SVM建立關聯。
 a| 
vserver的「vserver_name」



 a| 
_原則名稱_

指定要附加範圍的FPolicy原則名稱。FPolicy原則必須已經存在。
 a| 
政策名稱「policy_name」



 a| 
要納入的共享_

指定以逗號分隔的共用清單、以監控套用範圍的FPolicy原則。
 a| 
共享區至包含區的「shhare名稱」、...



 a| 
要排除的共享_

指定要從套用範圍之FPolicy原則的監控中排除的以逗號分隔的共用清單。
 a| 
共享區至排除區的「share名稱」、...



 a| 
_要包含的磁碟區_指定以逗號分隔的磁碟區清單、以監控套用範圍的FPolicy原則。
 a| 
'包括的磁碟區' Volume名稱'、...



 a| 
要排除的磁碟區_

指定要從套用範圍之FPolicy原則的監控中排除的以逗號分隔的磁碟區清單。
 a| 
'要排除的磁碟區'、' Volume名稱'、...



 a| 
匯出要納入的原則_

指定以逗號分隔的匯出原則清單、以監控套用範圍的FPolicy原則。
 a| 
「匯出原則」至「包含」、「匯出原則名稱」、...



 a| 
匯出要排除的原則_

指定要從套用範圍之FPolicy原則的監控中排除的匯出原則清單（以英文分隔）。
 a| 
-`-exapper-policies to -exclude’"exappe_policy_name"、...



 a| 
_要包括的副檔名_

指定要監控套用範圍之FPolicy原則的檔案副檔名以逗號分隔的清單。
 a| 
副檔名：副檔名：「file_extensions...」、...



 a| 
要排除的檔案副檔名_

指定要從套用範圍之FPolicy原則的監控中排除的檔案副檔名以逗號分隔的清單。
 a| 
-`-file-extensions-te-exclude’"file_extensions"、...



 a| 
_檔案副檔名檢查是否已啟用目錄？_

指定副檔名檢查是否也適用於目錄物件。如果此參數設為「true」、則目錄物件會受到與一般檔案相同的副檔名檢查。如果此參數設為「假」、則目錄名稱不會與副檔名相符、即使其副檔名不符、也會針對目錄傳送通知。

如果指派範圍的FPolicy原則設定為使用原生引擎、則此參數必須設定為「true」。
 a| 
啟用目錄檢查功能的「is副檔名」（we-file-extens-check on）｛'true'（真）|「假」（假）|｝

|===