---
permalink: nas-audit/plan-auditing-config-concept.html 
sidebar: sidebar 
keywords: plan, audit, configuration, svm, rotate, logs, size, schedule, rotation, dr, disaster recovery 
summary: 在儲存虛擬機器（SVM）上設定稽核之前、您必須先瞭解可用的組態選項、並針對每個選項規劃您要設定的值。此資訊可協助您設定稽核組態、以滿足您的業務需求。 
---
= 規劃稽核組態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在儲存虛擬機器（SVM）上設定稽核之前、您必須先瞭解可用的組態選項、並針對每個選項規劃您要設定的值。此資訊可協助您設定稽核組態、以滿足您的業務需求。

所有稽核組態都有一些通用的組態參數。

此外、您也可以使用某些參數來指定在旋轉合併和轉換的稽核記錄時使用哪些方法。您可以在設定稽核時指定下列三種方法之一：

* 根據記錄大小來旋轉記錄
+
這是用來旋轉記錄的預設方法。

* 根據排程來旋轉記錄
* 根據記錄大小和排程來旋轉記錄（以先發生的事件為準）


[NOTE]
====
至少應設定一種記錄輪調方法。

====


== 所有稽核組態的通用參數

建立稽核組態時、必須指定兩個必要參數。您也可以指定三個選用參數：

[cols="40,30,10,10,10"]
|===


| 資訊類型 | 選項 | 必要 | 包括 | 您的價值 


 a| 
_SVM名稱_

要在其中建立稽核組態的SVM名稱。SVM必須已經存在。
 a| 
vserver的「vserver_name」
 a| 
是的
 a| 
是的
 a| 



 a| 
_記錄目的地路徑_

指定儲存已轉換稽核記錄的目錄、通常是專屬磁碟區或qtree。路徑必須已存在於SVM命名空間中。

路徑長度最多可達864個字元、且必須具有讀寫權限。

如果路徑無效、稽核組態命令就會失敗。

如果SVM是SVM災難恢復來源、則記錄目的地路徑無法位於根磁碟區上。這是因為根磁碟區內容並未複寫到災難恢復目的地。

您無法將FlexCache 無法使用的功能區當成記錄目的地ONTAP （例如、更新版本的更新版本）。
 a| 
「目的地」的「文字」
 a| 
是的
 a| 
是的
 a| 



 a| 
要稽核的事件類別_

指定要稽核的事件類別。您可以稽核下列事件類別：

* 檔案存取事件（SMB和NFSv4）
* SMB登入和登出事件
* 集中存取原則執行事件
+
集中存取原則執行事件是Windows 2012 Active Directory網域開始提供的新進階稽核事件。集中存取原則執行事件記錄有關Active Directory中設定之集中存取原則變更的資訊。

* 檔案共用類別事件
* 稽核原則變更事件
* 本機使用者帳戶管理事件
* 安全性群組管理事件
* 授權原則變更事件


預設為稽核檔案存取和SMB登入及登出事件。

*附註：*在您指定「cap接移」為事件類別之前、SVM上必須有SMB伺服器。雖然您可以在稽核組態中啟用集中存取原則接移功能、但不會在SMB伺服器上啟用動態存取控制、但只有啟用動態存取控制時、才會產生集中存取原則接移事件。動態存取控制是透過SMB伺服器選項來啟用。預設不會啟用此功能。
 a| 
「-'events」（事件）｛'file-ops'|'CIFs-login'（CIFS登入登出）|'cap-stage'（cap-stage'）|'file-share'（檔案共用）|'capvite-police-change'（稽核原則變更）|'user-account'（使用者帳戶）|「安全群組
 a| 
否
 a| 
 a| 



 a| 
_記錄檔案輸出格式_

決定稽核記錄的輸出格式。輸出格式可以是ONTAP專屬的「XML」或Microsoft Windows「evtx」記錄格式。依預設、輸出格式為「evtx」。
 a| 
「-'format」（格式）｛'xml（格式）|'evtx'｝
 a| 
否
 a| 
 a| 



 a| 
_記錄檔案旋轉限制_

決定要保留多少稽核記錄檔、然後再將最舊的記錄檔轉出。例如、如果您輸入「5」值、則會保留最後五個記錄檔。

值「0」表示保留所有記錄檔。預設值為0。
 a| 
"integer"（整數）
 a| 
否
 a| 
 a| 

|===


== 用於判斷何時旋轉稽核事件記錄的參數

*根據記錄大小旋轉記錄*

預設值是根據大小來旋轉稽核記錄。

* 預設記錄大小為100 MB
* 如果您要使用預設的記錄檔旋轉方法和預設的記錄檔大小、則不需要設定任何特定的記錄檔旋轉參數。
* 如果您只想根據記錄大小來旋轉稽核記錄、請使用下列命令來取消設定「-rote-schedule-minute」參數：「vserver稽核修改-vserver vs0 -destination/-rote-schedule-minute」（vserver稽核修改-vserver vs0 -目的地/-rote-schedule-minute）


如果您不想使用預設的記錄大小、可以設定「-rote-Size-」參數來指定自訂的記錄大小：

[cols="40,30,10,10,10"]
|===


| 資訊類型 | 選項 | 必要 | 包括 | 您的價值 


 a| 
_記錄檔案大小限制_

決定稽核記錄檔大小限制。
 a| 
「-w旋轉 大小」｛'integere'[kb|MB| GB| TB|PB]｝
 a| 
否
 a| 
 a| 

|===
*根據排程旋轉記錄*

如果您選擇根據排程來旋轉稽核記錄、您可以使用任何組合的時間型旋轉參數來排程記錄輪調。

* 如果您使用時間型旋轉、則必須使用「-rote-schedule-minute-minute」參數。
* 所有其他的時間型旋轉參數都是選用的。
* 旋轉排程是使用所有與時間相關的值來計算。
+
例如、如果您只指定「-rote-schedule-minutes'」參數、稽核記錄檔就會根據一週中所有天、一年中所有月份的所有小時所指定的分鐘數來旋轉。

* 如果您只指定一或兩個時間型旋轉參數（例如、「-rote-schedule-month」和「-rote-schedule-minutes... minutes...」）、則記錄檔會根據您在一週的所有日子、所有時間、但僅在指定月份內所指定的分鐘值來旋轉。
+
例如、您可以指定稽核日誌在一月、三月和八月的所有週一、週三和週六上午10：30進行輪調

* 如果您同時指定「週日」和「週日」的值、就會視為獨立的。
+
例如、如果您將「週五週五」指定為「週五」、「週五週日」指定為「週日」、「週日」則稽核記錄會在每週五和指定月份的第13天、而不只是每週五的第13天。

* 如果您只想根據排程來旋轉稽核記錄、請使用下列命令取消設定「-rote-size」參數：「vserver稽核修改-vserver vs0 -destination /-rote-size -」


您可以使用下列可用稽核參數清單、來決定要使用哪些值來設定稽核事件記錄輪調的排程：

[cols="40,30,10,10,10"]
|===


| 資訊類型 | 選項 | 必要 | 包括 | 您的價值 


 a| 
_記錄輪調排程：月_

決定每月循環稽核記錄的排程。

有效值是「1月」到「12月」、「全部」。例如、您可以指定稽核日誌在1月、3月和8月期間輪調。
 a| 
《旋轉排程月》（chron月）
 a| 
否
 a| 
 a| 



 a| 
_記錄輪調排程：週中日_

決定每日（一週中的某天）排程以循環稽核記錄。

有效值為「unDay」到「aturDay」、以及「all」。例如、您可以指定稽核日誌在週二和週五、或一週中的所有日子循環顯示。
 a| 
週末的週日、週日、週日、週日、週日、週日、週日、週日、週日
 a| 
否
 a| 
 a| 



 a| 
_記錄輪調排程：天_

決定每月的日期排程、以循環稽核記錄。

有效值範圍從「1」到「31」。例如、您可以指定稽核日誌在每月的第10天和第20天、或每月的所有天進行旋轉。
 a| 
《旋轉排程日》（chron _dayofmonth）
 a| 
否
 a| 
 a| 



 a| 
_記錄輪調排程：hour _

決定每小時循環稽核記錄的排程。

有效值範圍從「0」（午夜）到「23」（晚上11：00）。指定「ALL」會每小時旋轉稽核記錄。例如、您可以指定稽核日誌的旋轉時間為6（上午6點）和18（下午6點）。
 a| 
「週轉-排程-小時」、「chron小時」
 a| 
否
 a| 
 a| 



 a| 
_記錄輪調排程：分_

決定稽核日誌的分鐘排程。

有效值範圍從「0」到「59」。例如、您可以指定稽核日誌在30分鐘內旋轉。
 a| 
「旋轉排程-分鐘」、「chron分鐘」
 a| 
是、如果設定排程型記錄輪調、則為否
 a| 
 a| 

|===
*根據記錄大小和排程來旋轉記錄*

您可以選擇根據記錄大小和排程來旋轉記錄檔、方法是在任何組合中設定「-旋轉 大小」參數和時間型旋轉參數。例如：如果將「-rote-size」設為10 MB、而「-rote-schedule-minute」設為15、則記錄檔會在記錄檔大小達到10 MB或每小時15分鐘（以先發生的事件為準）時旋轉。
