---
permalink: nas-audit/plan-fpolicy-event-config-concept.html 
sidebar: sidebar 
keywords: plan, fpolicy event configuration 
summary: 在設定FPolicy事件之前、您必須先瞭解建立FPolicy事件的意義。您必須決定要監控事件的傳輸協定、要監控的事件、以及要使用的事件篩選器。此資訊可協助您規劃要設定的值。 
---
= 規劃FPolicy事件組態總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在設定FPolicy事件之前、您必須先瞭解建立FPolicy事件的意義。您必須決定要監控事件的傳輸協定、要監控的事件、以及要使用的事件篩選器。此資訊可協助您規劃要設定的值。



== 建立FPolicy事件的意義

建立FPolicy事件是指定義FPolicy程序所需的資訊、以決定要監控的檔案存取作業、以及應將哪些受監控事件通知傳送至外部FPolicy伺服器。FPolicy事件組態定義下列組態資訊：

* 儲存虛擬機器（SVM）名稱
* 事件名稱
* 要監控的傳輸協定
+
FPolicy可以監控SMB、NFSv3和NFSv4檔案存取作業。

* 要監控的檔案作業
+
並非所有檔案作業都適用於每個傳輸協定。

* 要設定哪些檔案篩選器
+
只有特定的檔案作業與篩選組合有效。每個傳輸協定都有自己的一組支援組合。

* 是否要監控磁碟區掛載和卸載作業


[NOTE]
====
有三個參數（`-Protocol、`-file-operations、`-filers'）相依。下列組合對三個參數有效：

* 您可以指定「-Protocol」和「-file-operations」參數。
* 您可以指定全部三個參數。
* 您不能指定任何參數。


====


== FPolicy事件組態包含的內容

您可以使用下列可用的FPolicy事件組態參數清單來協助規劃組態：

[cols="70,30"]
|===


| 資訊類型 | 選項 


 a| 
_SVM_

指定您要與此FPolicy事件相關聯的SVM名稱。

每個FPolicy組態都是在單一SVM中定義。為了建立FPolicy原則組態、而將外部引擎、原則事件、原則範圍和原則結合在一起的原則、都必須與相同的SVM建立關聯。
 a| 
vserver的「vserver_name」



 a| 
事件名稱_

指定要指派給FPolicy事件的名稱。當您建立FPolicy原則時、會使用事件名稱將FPolicy事件與原則建立關聯。

名稱最長可達256個字元。

[NOTE]
====
如果在MetroCluster 還原或SVM災難恢復組態中設定事件、名稱最長應為200個字元。

====
名稱可以包含下列任何Ascii範圍字元的組合：

* 從A到Z
* 從「Z」到「A」
* 從0到9
* 「_」、「-」及「」。

 a| 
事件名稱「EVAT_NAME」



 a| 
_傳輸協定_

指定要為FPolicy事件設定的傳輸協定。「-Protocol」清單可包含下列其中一個值：

* 《CIFS》
* 《NFSv3》
* 《NFSv4》


[NOTE]
====
如果您指定了「-Protocol」、則必須在「-file-operations」參數中指定有效值。隨著傳輸協定版本變更、有效值可能會變更。

==== a| 
「傳輸協定」



 a| 
_File operations _

指定FPolicy事件的檔案作業清單。

事件會使用「-Protocol」參數中指定的傳輸協定、從所有用戶端要求中檢查此清單中指定的作業。您可以使用以逗號分隔的清單來列出一或多個檔案作業。「-file-operations」清單可包含下列一或多個值：

* 關閉檔案以進行檔案關閉作業
* 建立檔案以建立檔案
* 用於目錄建立作業的「cree-dir」
* 檔案刪除作業的刪除功能
* 目錄刪除作業的"Delete_dir"
* ggetattr用於獲取屬性操作
* 連結作業的連結
* 查閱作業的查詢
* 「開放」檔案開啟作業
* 檔案讀取作業的"read"
* 用於檔案寫入作業的寫入功能
* 檔案重新命名作業的名稱
* 目錄重新命名作業的"REname_dir"
* 「etattr」用於設定屬性作業
* 符號連結作業的「symlink」


[NOTE]
====
如果您指定了「-file-operations」、則必須在「-protocol」參數中指定有效的傳輸協定。

==== a| 
「檔案作業」「file_operations」、...



 a| 
_篩選_

指定指定傳輸協定之特定檔案作業的篩選器清單。「-filters」參數中的值用於篩選用戶端要求。清單可包含下列一項或多項內容：

[NOTE]
====
如果您指定了「-filers'參數、則也必須為「-file-operations」和「-Protocol」參數指定有效值。

====
* 「監視者廣告」選項可篩選用戶端的替代資料串流要求。
* 「近距離修改」選項可篩選用戶端要求以進行修改。
* 「關閉而不修改」選項、可在不修改的情況下、篩選用戶端的關閉要求。
* 第一讀取選項可篩選用戶端的第一讀取要求。
* 「first-write」選項可篩選用戶端的初次寫入要求。
* 「離線位元」選項可篩選用戶端的離線位元集要求。
+
設定此篩選器後、FPolicy伺服器只會在存取離線檔案時收到通知。

* 「以刪除方式開啟」選項可篩選出用戶端的開啟要求、並具有刪除意圖。
+
設定此篩選器後、FPolicy伺服器只會在嘗試開啟檔案以刪除檔案時收到通知。當指定「file_delete_on_close」旗標時、檔案系統會使用此功能。

* 「以寫入方式開啟」選項可篩選出用戶端要求以寫入方式開啟。
+
設定此篩選器後、FPolicy伺服器只會在嘗試開啟檔案時收到通知、以便在其中寫入內容。

* "write with size-chang"選項可在大小變更時篩選用戶端寫入要求。

 a| 
篩選器的「篩選器」、...



 a| 
_Filters"（續）

* 「etattr-with -Owner-change」選項可篩選用戶端設定屬性要求、以變更檔案或目錄的擁有者。
* 「etattr-with group變更」選項可篩選用戶端設定屬性要求、以變更檔案或目錄的群組。
* 「etattr-with -SACL-changing」選項可篩選用戶端設定屬性要求、以變更檔案或目錄上的SACL。
+
此篩選器僅適用於SMB和NFSv4傳輸協定。

* 「etattr-with -Dacl-change」選項可篩選用戶端設定屬性要求、以變更檔案或目錄的DACL。
+
此篩選器僅適用於SMB和NFSv4傳輸協定。

* 「etattr-with modify-time-changing」選項可篩選用戶端設定屬性要求、以變更檔案或目錄的修改時間。
* 「etattr-with存取時間變更」選項可篩選用戶端設定屬性要求、以變更檔案或目錄的存取時間。
* 「etattr-with creation-time-changing」選項可篩選用戶端設定屬性要求、以變更檔案或目錄的建立時間。
+
此選項僅適用於SMB傳輸協定。

* 「etattr-with mode變更」選項可篩選用戶端設定屬性要求、以變更檔案或目錄上的模式位元。
* "ettr-with size-chang"選項可篩選用戶端設定屬性要求、以變更檔案大小。
* 「etattr-with all撥款 大小變更」選項可篩選用戶端設定屬性要求、以變更檔案的分配大小。
+
此選項僅適用於SMB傳輸協定。

* 「exclude目錄」選項可篩選用戶端對目錄作業的要求。
+
指定此篩選器時、不會監控目錄作業。


 a| 
篩選器的「篩選器」、...



 a| 
_需要磁碟區作業_

指定磁碟區掛載和卸載作業是否需要監控。預設值為「假」。
 a| 
大容量作業模式：｛'true'|'fals'｝

|===