---
permalink: nas-audit/plan-fpolicy-policy-config-concept.html 
sidebar: sidebar 
keywords: plan, fpolicy, policy, configuration 
summary: 設定 FPolicy 原則之前、您必須先瞭解需要哪些參數、以及為何可以設定某些選用參數。 
---
= 規劃FPolicy原則組態總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在設定FPolicy原則之前、您必須先瞭解建立原則時需要哪些參數、以及設定某些選用參數的原因。此資訊可協助您判斷要為每個參數設定哪些值。

建立FPolicy原則時、您會將原則與下列項目建立關聯：

* 儲存虛擬機器（SVM）
* 一或多個FPolicy事件
* FPolicy外部引擎


您也可以設定多個選用的原則設定。



== FPolicy原則組態包含的內容

您可以使用下列可用的必要FPolicy原則清單和選用參數來協助規劃組態：

[cols="40,20,20,20"]
|===


| 資訊類型 | 選項 | 必要 | 預設 


 a| 
_SVM名稱_

指定您要在其中建立FPolicy原則的SVM名稱。
 a| 
`-vserver` `vserver_name`
 a| 
是的
 a| 
無



 a| 
_原則名稱_

指定FPolicy原則的名稱。

名稱最長可達256個字元。

[NOTE]
====
如果在MetroCluster 還原或SVM災難恢復組態中設定原則、名稱最長應為200個字元。

====
名稱可以包含下列任何Ascii範圍字元的組合：

* `a` 透過 `z`
* `A` 透過 `Z`
* `0` 透過 `9`
* "`_`" 、 "`-`", and "`.`"

 a| 
`-policy-name` `policy_name`
 a| 
是的
 a| 
無



 a| 
事件名稱_

指定要與FPolicy原則相關聯的以逗號分隔的事件清單。

* 您可以將多個事件與原則建立關聯。
* 事件是特定於傳輸協定的事件。
* 您可以使用單一原則來監控多個傳輸協定的檔案存取事件、方法是針對您要原則監控的每個傳輸協定建立事件、然後將事件與原則建立關聯。
* 事件必須已經存在。

 a| 
`-events` `event_name`、 ...
 a| 
是的
 a| 
無



 a| 
_Persistent stority_

從 ONTAP 9.14.1 開始、此參數會指定持續儲存區、以擷取 SVM 中非強制性非非同步原則的檔案存取事件。
 a| 
`-persistent-store` `persistent_store_name`
 a| 
否
 a| 
無



 a| 
外部引擎名稱_

指定要與FPolicy原則關聯的外部引擎名稱。

* 外部引擎包含節點傳送通知至FPolicy伺服器所需的資訊。
* 您可以將FPolicy設定為使用ONTAP 靜態原生外部引擎來進行簡單的檔案封鎖、或是使用外部引擎來設定使用外部FPolicy伺服器（FPolicy伺服器）來進行更精密的檔案封鎖和檔案管理。
* 如果您想要使用原生外部引擎、則無法指定此參數的值、也可以指定 `native` 做為價值。
* 如果您要使用FPolicy伺服器、則外部引擎的組態必須已經存在。

 a| 
`-engine` `engine_name`
 a| 
是（除非原則使用內部ONTAP 的非原生引擎）
 a| 
`native`



 a| 
_是必填篩選_

指定是否需要強制檔案存取篩選。

* 強制篩選設定可決定當所有主要和次要伺服器都當機、或在指定的逾時期間內未收到FPolicy伺服器的回應時、檔案存取事件會採取什麼行動。
* 設定為時 `true`、檔案存取事件遭拒。
* 設定為時 `false`，允許檔案存取事件。

 a| 
`-is-mandatory` {`true`|`false`}
 a| 
否
 a| 
`true`



 a| 
允許權限存取_

指定您是否要FPolicy伺服器使用權限資料連線、以具有存取受監控檔案和資料夾的權限。

如果設定、FPolicy伺服器可以使用權限資料連線、從SVM的根目錄存取包含受監控資料的檔案。

若要進行特殊權限的資料存取、必須在叢集上授權 SMB 、且必須將用於連線至 FPolicy 伺服器的所有資料生命體設定為具有 `cifs` 作為其中一種允許的通訊協定。

如果您想要設定原則以允許權限存取、也必須為您想要FPolicy伺服器用於權限存取的帳戶指定使用者名稱。
 a| 
`-allow-privileged-access` {`yes`|`no`}
 a| 
否（除非啟用Passthrough-read）
 a| 
`no`



 a| 
_特殊權限使用者名稱_

指定FPolicy伺服器用來存取特殊權限資料的帳戶使用者名稱。

* 此參數的值應使用「'domain\username'」格式。
* 如果 `-allow-privileged-access` 設為 `no`，將忽略爲此參數設置的任何值。

 a| 
`-privileged-user-name` `user_name`
 a| 
否（除非已啟用權限存取）
 a| 
無



 a| 
允許Passthrough-read_

指定FPolicy伺服器是否能為FPolicy伺服器歸檔至次要儲存設備（離線檔案）的檔案提供Passter-Read服務：

* Passthsther-read是一種讀取離線檔案資料的方法、無需將資料還原至主要儲存設備。
+
Passthroh-read可減少回應延遲、因為在回應讀取要求之前、不需要將檔案重新叫用回主要儲存設備。此外、Passthrough-read可免除使用僅為了滿足讀取要求而回收的檔案來耗用主要儲存空間的需求、藉此優化儲存效率。

* 啟用時、FPolicy伺服器會透過專為Passthrough-Reads所開啟的個別特殊權限資料通道、提供檔案的資料。
* 如果您想要設定Passthrough-read、也必須將原則設定為允許權限存取。

 a| 
`-is-passthrough-read-enabled` {`true`|`false`}
 a| 
否
 a| 
`false`

|===