---
permalink: nas-audit/requirements-considerations-concept.html 
sidebar: sidebar 
keywords: audit, requirements, considerations 
summary: 在儲存虛擬機器（SVM）上設定及啟用稽核之前、您必須瞭解特定的需求和考量。 
---
= ONTAP 稽核的必要條件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在儲存虛擬機器（SVM）上設定及啟用稽核之前、您必須瞭解特定的需求和考量。

* NFS 和 S3 稽核啟用 SVM 的合併限制取決於您的 ONTAP 版本：
+
|===


| 版本ONTAP | 最大值 


| 9.8 及更早版本 | 50 


| 9.9.1及更新版本 | 400 
|===
* 稽核不受限於SMB或NFS授權。
+
即使叢集上未安裝SMB與NFS授權、您仍可設定及啟用稽核。

* NFS稽核支援安全性ACE（類型U）。
* 對於NFS稽核、模式位元與稽核ACE之間沒有對應關係。
+
將ACL轉換為模式位元時、會跳過稽核ACE。將模式位元轉換為ACL時、不會產生稽核ACE。

* 稽核組態中指定的目錄必須存在。
+
如果不存在、建立稽核組態的命令就會失敗。

* 稽核組態中指定的目錄必須符合下列需求：
+
** 目錄不得包含符號連結。
+
如果稽核組態中指定的目錄包含符號連結、建立稽核組態的命令就會失敗。

** 您必須使用絕對路徑來指定目錄。
+
您不應指定相對路徑、例如 `/vs1/../`。



* 稽核取決於暫存磁碟區中是否有可用空間。
+
您必須瞭解並制定計畫、確保集合體中含有稽核磁碟區的暫存磁碟區有足夠的空間。

* 稽核取決於磁碟區中是否有可用空間、其中包含儲存轉換事件記錄的目錄。
+
您必須注意並制定計畫、確保用於儲存事件記錄的磁碟區有足夠的空間。您可以使用指定要保留在稽核目錄中的事件記錄數目 `-rotate-limit` 建立稽核組態時的參數、有助於確保磁碟區中有足夠的可用空間用於事件記錄。

* 雖然您可以在稽核組態中啟用集中存取原則接移、而不需在SMB伺服器上啟用動態存取控制、但必須啟用動態存取控制、才能產生集中存取原則接移事件。
+
預設不會啟用動態存取控制。





== 啟用稽核時的Aggregate space考量

建立稽核組態並在叢集中至少一個儲存虛擬機器（SVM）上啟用稽核時、稽核子系統會在所有現有的集合體和所有建立的新集合體上建立暫存磁碟區。在叢集上啟用稽核時、您必須注意特定的Aggregate空間考量。

由於Aggregate中的空間不可用、所以暫存磁碟區建立可能會失敗。如果您建立稽核組態、而現有的Aggregate沒有足夠的空間來容納接移磁碟區、就可能發生這種情況。

在SVM上啟用稽核之前、您應該先確定現有集合體上有足夠的空間可用於暫存磁碟區。
