---
permalink: nas-audit/steps-setup-fpolicy-config-concept.html 
sidebar: sidebar 
keywords: steps, setting, fpolicy configuration 
summary: 在 FPolicy 能夠監控檔案存取之前、必須在需要 FPolicy 服務的 SVM 上建立並啟用 FPolicy 組態。 
---
= 設定 ONTAP FPolicy 配置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在FPolicy能夠監控檔案存取之前、必須先在需要FPolicy服務的儲存虛擬機器（SVM）上建立並啟用FPolicy組態。

在SVM上設定及啟用FPolicy組態的步驟如下：

. 建立FPolicy外部引擎。
+
FPolicy外部引擎可識別與特定FPolicy組態相關聯的外部FPolicy伺服器（FPolicy伺服器）。如果使用內部的「原生」FPolicy引擎來建立原生檔案封鎖組態、則不需要建立FPolicy外部引擎。

+
從 ONTAP 9.15.1 開始、您可以使用 `protobuf` 引擎格式。設定為時 `protobuf`、通知訊息會使用Google Prototbuf以二進位格式編碼。將引擎格式設定為之前 `protobuf`，請確保 FPolicy 伺服器也支援 `protobuf` 反序列化。如需詳細資訊、請參閱 link:plan-fpolicy-external-engine-config-concept.html["規劃FPolicy外部引擎組態"]

. 建立FPolicy事件。
+
FPolicy事件說明FPolicy原則應監控的項目。事件包括要監控的傳輸協定和檔案作業、並可包含篩選器清單。事件使用篩選器來縮小FPolicy外部引擎必須傳送通知的受監控事件清單。事件也會指定原則是否監控Volume作業。

. 建立 FPolicy 持續儲存區（選用）。
+
從 ONTAP 9.14.1 開始、 FPolicy 可讓您進行設定 link:persistent-stores.html["持續儲存區"] 擷取 SVM 中非強制性非非同步原則的檔案存取事件。不支援同步（強制或非強制）和非同步強制組態。

+
持續儲存區可協助將用戶端 I/O 處理與 FPolicy 通知處理分離、以減少用戶端延遲。

+
從 ONTAP 9.15.1 開始、 FPolicy 永續性儲存區組態已簡化。。 `persistent-store-create` 命令可自動建立 SVM 的 Volume 、並設定持續儲存區的 Volume 。

. 建立FPolicy原則。
+
FPolicy原則負責將需要監控的一組事件與適當範圍相關聯、以及哪些受監控的事件通知必須傳送至指定的FPolicy伺服器（若未設定FPolicy伺服器、則會傳送至原生引擎）。該原則也定義是否允許FPolicy伺服器以權限存取其接收通知的資料。如果伺服器需要存取資料、FPolicy伺服器就需要存取權限。需要存取權限的典型使用案例包括檔案封鎖、配額管理及階層式儲存管理。您可以在原則中指定此原則的組態是使用FPolicy伺服器、還是使用內部的「原生」FPolicy伺服器。

+
原則會指定是否必須篩選。如果篩選是強制性的、且所有FPolicy伺服器都關閉、或在定義的逾時期間內、未從FPolicy伺服器收到任何回應、則檔案存取將遭拒。

+
原則的界限是SVM。原則無法套用至多個SVM。不過、特定SVM可以有多個FPolicy原則、每個原則的範圍、事件和外部伺服器組態組合相同或不同。

. 設定原則範圍。
+
FPolicy範圍決定原則在哪些磁碟區、共享區或匯出原則上執行、或排除在監控範圍之外。範圍也會決定哪些副檔名應納入或排除在FPolicy監控範圍之外。

+
[NOTE]
====
排除清單優先於包含清單。

====
. 啟用FPolicy原則。
+
啟用原則時、會連接控制通道和（可選）特殊權限資料通道。SVM參與之節點上的FPolicy程序會開始監控檔案和資料夾存取、若事件符合設定的條件、則會將通知傳送至FPolicy伺服器（若未設定FPolicy伺服器、則會傳送至原生引擎）。



[NOTE]
====
如果原則使用原生檔案封鎖、則不會設定外部引擎、也不會與原則建立關聯。

====