---
permalink: nas-audit/supported-file-operation-filter-fpolicy-smb-concept.html 
sidebar: sidebar 
keywords: list, supported file operation, filter combinations, fpolicy, monitor, smb 
summary: 設定FPolicy事件時、您必須注意、監控SMB檔案存取作業時、僅支援特定的檔案作業和篩選器組合。 
---
= FPolicy可監控SMB的支援檔案操作和篩選器組合清單
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定FPolicy事件時、您必須注意、監控SMB檔案存取作業時、僅支援特定的檔案作業和篩選器組合。

下表提供了用於監控SMB檔案存取事件的FPolicy支援檔案操作和篩選器組合清單：

[cols="30,70"]
|===


| 支援的檔案作業 | 支援的篩選器 


 a| 
關閉
 a| 
監控廣告、離線位元、近距離修改、近距離不需修改、近距離讀取、 exclude目錄



 a| 
建立
 a| 
監控廣告、離線位元



 a| 
create_dir
 a| 
目前此檔案作業不支援篩選器。



 a| 
刪除
 a| 
監控廣告、離線位元



 a| 
刪除目錄
 a| 
目前此檔案作業不支援篩選器。



 a| 
GetAttr
 a| 
離線位元、exclude目錄



 a| 
開啟
 a| 
監控廣告、離線位元、開放刪除意圖、開放寫入目的、排除目錄



 a| 
讀取
 a| 
監控廣告、離線位元、第一讀取



 a| 
寫入
 a| 
監控廣告、離線位元、第一寫入、大小變更寫入



 a| 
重新命名
 a| 
監控廣告、離線位元



 a| 
重新命名目錄
 a| 
目前此檔案作業不支援篩選器。



 a| 
設定
 a| 
監控廣告、離線位元、設定ATtr_with _Owner_change、設定ATr_with _group_change、設定ATtr_with _mode_change、 setattr_with _SACL_change、setattr_with _dacl_change、setattr_with _dmodify_time_change、setattr_with _access_time_change、setattr_with creation_time_change、 setattr_with _size_change、setattr_with _all撥款_size_change、exclude目錄

|===