---
permalink: nas-audit/view-audit-event-logs-concept.html 
sidebar: sidebar 
keywords: view, audit event logs 
summary: 您可以使用稽核事件記錄來判斷是否有足夠的檔案安全性、以及是否有不當的檔案和資料夾存取嘗試。您可以檢視及處理以evtx或XML檔案格式儲存的稽核事件記錄。 
---
= 檢視稽核事件記錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用稽核事件記錄來判斷是否有足夠的檔案安全性、以及是否有不當的檔案和資料夾存取嘗試。您可以檢視及處理儲存在中的稽核事件記錄 `EVTX` 或 `XML` 檔案格式。

* `EVTX` 檔案格式
+
您可以開啟已轉換的 `EVTX` 使用 Microsoft 事件檢視器將事件記錄稽核為儲存的檔案。

+
使用「事件檢視器」檢視事件記錄時、您可以使用兩種選項：

+
** 一般檢視
+
所有事件的通用資訊都會顯示在事件記錄中。在此版本ONTAP 的資訊不顯示事件記錄的事件特定資料。您可以使用詳細檢視來顯示特定事件的資料。

** 詳細檢視
+
提供友善的檢視和XML檢視。易記檢視和XML檢視會同時顯示所有事件通用的資訊、以及事件記錄的事件特定資料。



* `XML` 檔案格式
+
您可以檢視及處理 `XML` 稽核支援的協力廠商應用程式上的事件記錄 `XML` 檔案格式。XML檢視工具可用於檢視稽核記錄、前提是您必須具備XML架構和XML欄位定義的相關資訊。如需XML架構和定義的詳細資訊、請參閱 https://library.netapp.com/ecm/ecm_get_file/ECMLP2875022["《稽核架構參考》ONTAP"]。





== 使用事件檢視器檢視作用中稽核記錄的方式

如果稽核整合程序正在叢集上執行、則整合程序會將新記錄附加到啟用稽核的儲存虛擬機器（SVM）作用中稽核記錄檔。此作用中稽核記錄可透過Microsoft事件檢視器中的SMB共用區存取及開啟。

除了檢視現有的稽核記錄之外、「事件檢視器」還提供重新整理選項、可讓您重新整理主控台視窗中的內容。新附加的記錄是否可在事件檢視器中檢視、取決於是否在用來存取作用中稽核記錄的共用區上啟用oplocks。

[cols="30,70"]
|===


| 共享區上的oplocks設定 | 行為 


 a| 
已啟用
 a| 
「事件檢視器」會開啟記錄、其中包含寫入到該時間點的事件。重新整理作業不會以合併程序附加的新事件來重新整理記錄。



 a| 
已停用
 a| 
「事件檢視器」會開啟記錄、其中包含寫入到該時間點的事件。重新整理作業會以合併程序附加的新事件來重新整理記錄。

|===
[NOTE]
====
此資訊僅適用於 `EVTX` 事件記錄。 `XML` 事件記錄可以透過 SMB 瀏覽器或 NFS 、使用任何 XML 編輯器或檢視器來檢視。

====