---
permalink: san-config/benefits-vlans-iscsi-concept.html 
sidebar: sidebar 
keywords: benefits, vlans, iscsi, configurations, static, dynamic, security, limit, available, paths 
summary: VLAN由一組交換器連接埠組成、這些交換器連接埠集合在一個廣播網域中。VLAN可以位於單一交換器上、也可以橫跨多個交換器機箱。靜態和動態VLAN可讓您提高安全性、隔離問題、並限制IP網路基礎架構內的可用路徑。 
---
= 在 iSCSI 組態中搭配 ONTAP 系統使用 VLAN 的優點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VLAN由一組交換器連接埠組成、這些交換器連接埠集合在一個廣播網域中。VLAN可以位於單一交換器上、也可以橫跨多個交換器機箱。靜態和動態VLAN可讓您提高安全性、隔離問題、並限制IP網路基礎架構內的可用路徑。

當您在大型IP網路基礎架構中實作VLAN時、會獲得下列效益：

* 提高安全性。
+
VLAN可讓您善用現有的基礎架構、同時仍能提供更高的安全性、因為它們會限制乙太網路或IP SAN的不同節點之間的存取。

* 隔離問題、改善乙太網路和IP SAN的可靠性。
* 限制問題空間、縮短問題解決時間。
* 減少通往特定iSCSI目標連接埠的可用路徑數量。
* 減少主機使用的最大路徑數。
+
路徑過多會減慢重新連線的速度。如果主機沒有多重路徑解決方案、您可以使用VLAN只允許一條路徑。





== 動態VLAN

動態VLAN是以MAC位址為基礎的。您可以指定要包含的成員的MAC位址、來定義VLAN。

動態VLAN提供靈活度、不需要對應至裝置實體連接至交換器的實體連接埠。您可以在不重新設定VLAN的情況下、將纜線從一個連接埠移至另一個連接埠。



== 靜態VLAN

靜態VLAN是以連接埠為基礎的。交換器和交換器連接埠用於定義VLAN及其成員。

靜態VLAN提供更高的安全性、因為使用媒體存取控制（MAC）偽造不可能違反VLAN。但是、如果有人能夠實體存取交換器、更換纜線並重新設定網路位址、則可以允許存取。

在某些環境中、建立和管理靜態VLAN比動態VLAN更容易。這是因為靜態VLAN只需要指定交換器和連接埠識別碼、而非48位元的MAC位址。此外、您也可以使用VLAN識別碼來標示交換器連接埠範圍。
