---
permalink: san-config/commands-manage-fc-adapters-reference.html 
sidebar: sidebar 
keywords: commands, managing, fc adapters 
summary: 您可以使用FC命令來管理儲存控制器的FC目標介面卡、FC啟動器介面卡和內建FC介面卡。相同的命令也用於管理FC傳輸協定和FC-NVMe傳輸協定的FC介面卡。 
---
= 用於管理FC介面卡的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用FC命令來管理儲存控制器的FC目標介面卡、FC啟動器介面卡和內建FC介面卡。相同的命令也用於管理FC傳輸協定和FC-NVMe傳輸協定的FC介面卡。

FC啟動器介面卡命令只能在節點層級運作。您必須先使用「run -node_node_name_」命令、才能使用FC啟動器介面卡命令。



== 用於管理FC目標介面卡的命令

[cols="2*"]
|===
| 如果您想要... | 使用此命令... 


 a| 
在節點上顯示FC介面卡資訊
 a| 
「網路FCP介面卡顯示」



 a| 
修改FC目標介面卡參數
 a| 
網路FCP介面卡修改



 a| 
顯示FC傳輸協定流量資訊
 a| 
「run -node_node_name_ systat -f'



 a| 
顯示FC傳輸協定已執行多久
 a| 
"run -node_node_name_ uptime（執行節點節點節點名稱_正常運作時間）"



 a| 
顯示介面卡組態與狀態
 a| 
"run -node_node_name_ sysconfig -v _adapter_"



 a| 
驗證安裝了哪些擴充卡、以及是否有任何組態錯誤
 a| 
"run -node_node_name_ sysconfig -ac"



 a| 
查看命令的手冊頁
 a| 
「我的命令名稱」

|===


== 用於管理FC啟動器介面卡的命令

[cols="2*"]
|===
| 如果您想要... | 使用此命令... 


 a| 
顯示節點中所有啟動器及其介面卡的資訊
 a| 
「run -node_node_name_ storage show介面卡」



 a| 
顯示介面卡組態與狀態
 a| 
"run -node_node_name_ sysconfig -v _adapter_"



 a| 
驗證安裝了哪些擴充卡、以及是否有任何組態錯誤
 a| 
"run -node_node_name_ sysconfig -ac"

|===


== 用於管理內建FC介面卡的命令

[cols="2*"]
|===
| 如果您想要... | 使用此命令... 


 a| 
顯示內建FC連接埠的狀態
 a| 
「系統節點硬體統一連線展示」

|===