---
permalink: san-config/host-support-multipathing-concept.html 
sidebar: sidebar 
keywords: host, support, multipathing 
summary: 支援FC和iSCSI路徑時、務必使用非對稱邏輯單元存取（ALUA）ONTAP 。請務必使用支援ALUA的主機組態來執行FC和iSCSI傳輸協定。 
---
= ONTAP 支援 SAN 主機多重路徑功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP 使用非對稱式邏輯單元存取（ ALUA ）軟體來處理 FC 和 iSCSI 主機的多重路徑。

從 ONTAP 9.5 多重路徑高可用度（ HA ）配對容錯移轉 / 恢復開始，就支援使用非同步命名空間存取（ ANA ）的 NVMe 主機。在 ONTAP 9.4 中， NVMe 只支援從主機到目標的一條路徑，因此應用程式主機必須管理通往 HA 合作夥伴的路徑容錯移轉。

如需哪些特定主機組態支援ALUA或ANA的相關資訊、請參閱 https://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"^] 和 https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN主機組態ONTAP"] 適用於您的主機作業系統。

多路徑軟體，也稱為 MPIO（多路徑 I/O）軟體，在 HA 組態中建議使用。您的 SAN 主機需要多路徑軟體，才能透過多個路徑存取 LUN 或 NVMe 命名空間。它會將 LUN 或 NVMe 命名空間的所有路徑呈現為作業系統的單一磁碟。如果沒有多路徑軟體，作業系統可能會將每個路徑視為獨立的磁碟，從而導致資料毀損。

如果您有下列任一項、您的解決方案就會被視為具有多個路徑：

* 主機中的單一啟動器連接埠、連接到SVM中的多個SAN LIF
* 多個啟動器連接埠、連接至SVM中的單一SAN LIF
* 多個啟動器連接埠連接至SVM中的多個SAN LIF


您應該使用選擇性 LUN 對映、FC 交換器分區或連接埠集來限制存取 LUN 和命名空間的路徑。

.相關資訊
深入瞭解link:../san-admin/multipath-automatic-lif-failover-support.html["ONTAP 支援的 SAN 多路徑組態"]。



== 從主機到叢集中節點的建議路徑數

從主機到叢集中每個節點的路徑不得超過八條。您也不應超過主機作業系統可支援的路徑總數，以及主機上使用的多重路徑。

如果叢集中有四個以上的節點、或是任一節點中的SVM使用四個以上的目標連接埠、 您可以使用下列方法來限制可用於存取節點上LUN的路徑數目、以避免超過建議的八個路徑上限。

* link:../san-admin/selective-lun-map-concept.html["選擇性LUN對應（SLM)"]
+
SLM 將主機到 LUN 的路徑數量減少到僅包含擁有該 LUN 的節點及其高可用性 (HA) 夥伴節點上的路徑。SLM 預設啟用。叢集中的儲存虛擬機器 (SVM) 應至少為每個 LUN 透過 SLM 連接到每個報告節點建立兩條路徑。這可以消除單點故障，使系統能夠在組件發生故障時繼續運作。

* link:../san-admin/limit-lun-access-portsets-igroups-concept.html["PortSets"]
+
PortSet可與SLA搭配使用、進一步限制特定目標對特定啟動器的存取。當使用具有連接埠集的SLM, LUN將可在擁有LUN的節點及該節點的HA合作夥伴的連接埠集中的一組lifs上存取。

* 來自主機的啟動器群組 (igroup) 對應
+
您可以定義 igroup 並將其對應至 LUN，以控制哪些啟動器可以存取 LUN。

* link:../san-config/fc-fcoe-recommended-zoning-configuration.html["FC交換器分區"]
+
如果您的主機未安裝多重路徑解決方案、有四個或更多主機連線至您的 SAN 或叢集中的節點未實作 SLM，則應建立分區組態。


