---
permalink: upgrade/concept_upgrade_requirements_for_metrocluster_configurations.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, requirements, metrocluster, configuration, mcc, general, normal, operations, switchover 
summary: 在 MetroCluster 組態上升級 ONTAP 軟體之前，叢集必須符合特定需求。 
---
= 檢查 ONTAP 升級需求以取得 MetroCluster 組態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 MetroCluster 組態上升級 ONTAP 軟體之前，叢集必須符合特定需求。

* 兩個叢集都必須執行相同版本ONTAP 的支援。
+
您ONTAP 可以使用version命令來驗證此版本。

* 如果您正在執行重大 ONTAP 升級、 MetroCluster 組態必須處於正常模式。
* 如果您正在執行修補程式 ONTAP 升級、 MetroCluster 組態可以是正常模式或切換模式。
* 除了雙節點叢集之外、您可以在不中斷營運的情況下、同時升級兩個叢集。
+
若要在雙節點叢集中進行不中斷升級、叢集必須一次升級一個節點。

* 兩個叢集中的集合體不得處於重新同步RAID狀態。
+
在MetroCluster修復期間，鏡像聚合會重新同步。您可以使用以下方式驗證MetroCluster配置是否處於此狀態 `storage aggregate plex show -in-progress true`命令。如果正在同步任何聚合，則不應執行升級，直到重新同步完成。

+
詳細了解 `storage aggregate plex show`在link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-plex-show.html["指令參考資料ONTAP"^] 。

* 在升級進行期間、議定的切換作業將會失敗。
+
為了避免升級或還原作業發生問題、請勿在升級或還原作業期間嘗試非計畫性的切換、除非兩個叢集上的所有節點都執行相同版本ONTAP 的故障恢復。





== MetroCluster 正常作業的組態需求

* 來源SVM LIF必須在其主節點上處於開啟狀態。
+
目的地SVM的資料生命期不需要達到或位於其主節點上。

* 本機站台上的所有集合體都必須在線上。
* 本機叢集的SVM所擁有的所有根磁碟區和資料磁碟區都必須處於線上狀態。




== MetroCluster 的組態需求

* 所有生命都必須在其主節點上處於正常工作狀態。
* 所有的集合體都必須在線上、但DR站台的根集合體除外。
+
DR站台的根集合體在切換的特定階段處於離線狀態。

* 所有磁碟區都必須處於線上狀態。


.相關資訊
link:task_verifying_the_networking_and_storage_status_for_metrocluster_cluster_is_ready.html["驗MetroCluster 證網路和儲存設備的資訊不完整組態狀態"]
