---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, requirements 
summary: 從使用支援功能的版本9.3開始ONTAP 、您預設無法將執行ONTAP 版本不同於現有節點上執行版本的更新節點新增至叢集。 
---
= 混合版本需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從使用支援功能的版本9.3開始ONTAP 、您預設無法將執行ONTAP 版本不同於現有節點上執行版本的更新節點新增至叢集。

如果您計畫在叢集中新增比ONTAP 現有叢集中節點更快的執行版本的更新節點、則應先將叢集中的節點升級至較新版本、然後再新增節點。

不建議使用混合版本叢集、但在某些情況下、您可能需要暫時進入混合版本狀態。例如、如果您要升級至ONTAP 更新版本的、但現有叢集中的某些節點不支援的版本、則需要輸入混合版本狀態。在這種情況ONTAP 下、您應該升級支援更新版本之支援的節點、然後ONTAP 使用下列命令移除不支援升級至版本之更新版本的節點：

[cols="2"]
|===
| 版本ONTAP | 命令 


 a| 
部分9.3 ONTAP
 a| 
`cluster unjoin -skip-last-low-version-node-check`



 a| 
ONATP 9.4及更新版本
 a| 
`cluster remove-node -skip-last-low-version-node-check`

|===
您可能還需要輸入混合版本狀態、才能進行技術更新或中斷升級。在這種情況下、您可以覆寫ONTAP 「支援」的預設行為、並使用新增不同版本的節點 `cluster add-node -allow-mixed-version-join` 進階權限命令。

當您必須進入混合版本狀態時、應該儘快完成升級。HA 配對不得從與叢集中其他 HA 配對不同的版本執行 ONTAP 版本超過 90 天。若要正確執行叢集作業、叢集處於混合版本狀態的期間應儘可能短。

當叢集處於混合版本狀態時、除了必要時、您不應輸入任何變更叢集作業或組態的命令、以滿足升級需求。
