---
permalink: upgrade/concept_upgrade_paths.html 
sidebar: sidebar 
keywords: ontap, upgrade, paths 
summary: 您可以升級的版本取決於節點上目前執行的版本、而有所不同。ONTAP ONTAP 
---
= 我可以升級到哪個版本ONTAP 的呢？
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以升級的版本會因硬體平台和節點上目前執行的版本而異。ONTAP ONTAP請參閱 https://hwu.netapp.com["NetApp Hardware Universe"^] 驗證您的平台是否支援目標升級版本。

*附註：*這些準則僅指內部部署ONTAP 的版本。如需在ONTAP 雲端升級功能的相關資訊、請參閱 https://docs.netapp.com/us-en/occm/task_updating_ontap_cloud.html["升級 Cloud Volumes ONTAP 軟體"^]。

若要判斷您目前ONTAP 的版本：

* 在System Manager中、按一下*叢集>總覽*。
* 在命令列介面（CLI）中、使用「cluster image show」命令。+您也可以在進階權限層級中使用「系統節點映像show」命令來顯示詳細資料。


建議盡可能自動進行不中斷升級（andu）。視您目前的版本和目標版本而定、您的升級途徑將是_DIRECT、_DIRECT多重躍點或_Multi-stop_。除非另有說明、否則這些路徑適用於所有人 link:concept_upgrade_methods.html["升級方法"]；不中斷營運或中斷營運、自動化或手動。

* _Direct_+您可以使用ONTAP 單一軟體映像、直接升級至下一個鄰近的版本系列。對於大多數版本、您也可以安裝軟體映像、讓您直接升級至比執行中版本高兩個版本的版本。例如、您可以使用從9.8到9.9.1或從9.8到9.10.1的直接更新路徑。
* _Direct Multi-Hop_+若為非鄰近版本的自動不中斷升級（andu）、您可以安裝中介版本和目標版本的軟體映像。自動化升級程序會使用背景中的中繼映像來完成目標版本的更新。您應預期在程序期間會有多個接管/恢復作業及相關的重新開機。+此更新路徑僅適用於從9.3到9.6或9.7的andu更新、以及從9.5到9.8或9.9.1的andu更新。例如、如果叢集執行9.3且您想升級至9.7、則會載入ONTAP 9.5和9.7的版次安裝套件、然後啟動andu至9.7。然後、將叢集先自動升級至9.5、再升級至9.7。ONTAP
* _Multi-stop_+如果您的非鄰近目標版本無法使用直接或直接的多躍點路徑、您必須先升級至支援的中繼版本、然後再升級至目標版本。例如、如果您目前正在執行9.7且想要升級至9.10.1、則必須先完成多階段升級：從9.7升級至9.9.1、再從9.9.1升級至9.10.1。從舊版升級可能需要三個或更多階段、並提供多個中級升級。+*附註：*開始進行多階段升級之前、請確定您的硬體平台支援您的目標版本。


如果您打算ONTAP 從舊ONTAP 版的版本（例如9.3）進行更新、最好先將同ONTAP 一版本的更新版本升級至同一版本的更新版本、然後再升級至下一個支援的主要版本。這可確保在升級之前、舊版本中的任何問題都能獲得解決。

例如、如果您的系統執行ONTAP 的是32個P9、而您打算升級至9.9個版本、請遵循此升級途徑：9.3P9 -> 9.3P21 -> 9.7 -> 9.9.1在ONTAP 所有主要的版本中、使用最新的可用修補程式版本。



== 升級途徑ONTAP

下表列出所有支援的升級路徑。除了某些需要中斷升級的系統組態、以及如表所示、所有路徑都可以使用自動化和手動不中斷升級方法。部分舊版的升級映像已不再提供。

[cols="3*"]
|===
| 如果您目前ONTAP 的版本是… | 而您的目標ONTAP 版本是… | 您的升級途徑是… 


| 9.9.1 | 9.10.1 | 直接 


.2+| 9.8 | 9.10.1 | 直接 


| 9.9.1 | 直接 


.3+| 9.7 | 9.10.1 | 直接多跳（僅限andu、9.8和9.10.1P2或更新版本P版本需要影像）+其他多重階段（透過9.9.1） 


| 9.9.1 | 直接 


| 9.8 | 直接 


.4+| 9.6 | 9.10.1 | 多階段（透過9.8） 


| 9.9.1 | 多階段（透過9.8） 


| 9.8 | 直接 


| 9.7 | 直接 


.5+| 9.5. | 9.10.1 | 多階段（透過9.8） 


| 9.9.1 | 直接多跳（僅限andu、9.7和9.9.1需要影像）+其他多重階段（透過9.7） 


| 9.8 | 直接多跳（僅限andu、9.7和9.8需要影像）+其他多重階段（透過9.7） 


| 9.7 | 直接 


| 9.6 | 直接 


.6+| 9.4 | 9.10.1 | 多階段（透過9.5和9.8） 


| 9.9.1 | 多階段（透過9.5和9.8） 


| 9.8 | 多階段（透過9.5） 


| 9.7 | 多階段（透過9.5） 


| 9.6 | 多階段（透過9.5） 


| 9.5. | 直接 


.7+| 9.3 | 9.10.1 | 多階段（透過9.7和9.9.1） 


| 9.9.1 | 多階段（透過9.8） 


| 9.8 | 多階段（透過9.7） 


| 9.7 | 直接多跳（僅限andu、9.5和9.7需影像）+其他多重階段（透過9.5） 


| 9.6 | 直接多跳、僅限andu（9.5和9.6需要影像）+其他多階段（透過9.5） 


| 9.5. | 直接 


| 9.4 | 無法使用 


.8+| 9.2 | 9.10.1 | 多階段（透過9.3、9.7和9.9.1） 


| 9.9.1 | 多階段（透過9.3和9.7） 


| 9.8 | 多階段（透過9.7） 


| 9.7 | 多階段（透過9.3） 


| 9.6 | 多階段（透過9.3） 


| 9.5. | 多階段（透過9.3） 


| 9.4 | 無法使用 


| 9.3 | 直接 


.9+| 9.1 | 9.10.1 | 多階段（透過9.3、9.7和9.9.1） 


| 9.9.1 | 多階段（透過9.3和9.7） 


| 9.8 | 多階段（透過9.3和9.7） 


| 9.7 | 多階段（透過9.3） 


| 9.6 | 多階段（透過9.3） 


| 9.5. | 多階段（透過9.3） 


| 9.4 | 無法使用 


| 9.3 | 直接 


| 9.2 | 無法使用 


.10+| 9.0 | 9.10.1 | 多階段（透過9.1、9.3、9.7和9.9.1） 


| 9.9.1 | 多階段（透過9.1、9.3和9.7） 


| 9.8 | 多階段（透過9.1、9.3和9.7） 


| 9.7 | 多階段（透過9.1和9.3） 


| 9.6 | 多階段（透過9.1和9.3） 


| 9.5. | 多階段（透過9.1和9.3） 


| 9.4 | 無法使用 


| 9.3 | 多階段（透過9.1） 


| 9.2 | 無法使用 


| 9.1 | 直接 
|===


== 將路徑從Data ONTAP 版本號的更新到ONTAP 版本號的更新到版本號的更新

請務必使用ONTAP 「請參閱NetApp Hardware Universe 」驗證您的平台是否能執行目標版本的更新。

*注意：* Data ONTAP 《Sept.8.3升級指南》錯誤地指出、在四節點叢集中、您應該規劃升級最後保留epsilon的節點。這不再是Data ONTAP 升級的必要條件、從版本號為32的版本開始。如需詳細資訊、請參閱 https://mysupport.netapp.com/site/bugs-online/product/ONTAP/BURT/805277["NetApp錯誤線上錯誤編號805277"^]。

來自於Data ONTAP:: 您可以直接升級ONTAP 至版本更新、然後依照所述升級至更新版本 <<ontap9_paths>>。
發行早於8.3.x的版本、包括8.2.x Data ONTAP:: 您必須先升級Data ONTAP 至se.3.x、然後升級ONTAP 至se.9.1、再升級至中所述的更新版本 <<ontap9_paths>>。

