---
permalink: upgrade/concept_mixed_version_requirements.html 
sidebar: sidebar 
keywords: ontap, upgrade, mixed, version, clusters, mixed-version nodes, requirements 
summary: 混合版本的 ONTAP 叢集由執行兩個不同主要 ONTAP 版本的節點所組成、例如 ONTAP 9.8 和 9.12.1 。NetApp 僅在特定案例中支援混合版本的 ONTAP 叢集。 
---
= 混合版本 ONTAP 叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
混合版本的 ONTAP 叢集由節點組成、在有限時間內執行兩個不同的主要 ONTAP 版本。  例如、如果叢集是由執行 ONTAP 9.8 和 9.12.1 的節點所組成、則叢集是混合版本的叢集。  同樣地、節點執行 ONTAP 9.9.1 和 9.13.1 的叢集也會是混合版本的叢集。  NetApp 在有限的時間內和特定案例中支援混合版本的 ONTAP 叢集。

以下是 ONTAP 叢集處於混合版本狀態的最常見案例：

* 大型叢集中的 ONTAP 軟體升級
* 當您計畫將新節點新增至叢集時、需要進行 ONTAP 軟體升級


此資訊適用於支援 NetApp 平台系統的 ONTAP 版本、例如 AFF A 系列和 C 系列、 ASA 和 FAS 、以及 C 系列系統。這些資訊不適用於 ONTAP 雲端版本（ 9.x ）、例如 9.12.0 。



== 混合版本 ONTAP 叢集的需求

如果您的叢集需要進入混合式 ONTAP 版本狀態、您必須注意重要的要求和限制。

* 在任何指定時間、叢集中都不能有兩個以上不同的主要 ONTAP 版本。如果節點執行的是相同 ONTAP 版本的不同 P 或 D 修補層級、例如 ONTAP 9.9.9.1 和 9.9.9.1P5 、則叢集將不視為混合版本的 ONTAP 叢集。
* 當叢集處於混合版本狀態時、除了升級或資料移轉程序所需的命令外、您不應輸入任何會改變叢集作業或組態的命令。  例如、在升級和資料移轉完成之前、不應執行 LIF 移轉、規劃的儲存容錯移轉作業或大規模物件建立或銷毀等活動。
* 為了達到最佳叢集作業、叢集處於混合版本狀態的時間長度應儘可能短。  叢集在混合版本狀態下的最大持續時間長度取決於叢集中最低的 ONTAP 版本。
+
[cols="2*"]
|===
| 如果在混合版本叢集中執行的 ONTAP 最低版本為： | 然後您最多可以保持在混合版本狀態 


| ONTAP 9.8 或更高版本 | 90 天 


| ONTAP 9.7 或更低 | 7 天 
|===
* 從 ONTAP 9.8 開始、混合版本的 ONTAP 叢集最多可跨越 4 個主要版本。例如、混合版本的 ONTAP 叢集可能會有執行 ONTAP 9.8 和 9.12.1 的節點、或者可能有執行 ONTAP 9.9.1 和 9.13.1 的節點。由於混合版本的 ONTAP 叢集橫跨 5 個主要版本、因此不支援節點執行 ONTAP 9.8 和 9.13.1 的混合版本叢集。




== 更新大型叢集的 ONTAP 版本

進入混合版本叢集狀態的一個案例、是升級具有多個節點的叢集 ONTAP 版本、以利用 ONTAP 9 更新版本中提供的功能。當您需要升級較大叢集的 ONTAP 版本時、當您升級叢集中的每個節點時、將會進入混合版本叢集狀態一段時間。



== 將新節點新增至叢集

另一個進入混合版本叢集狀態的案例是將新節點新增至叢集。您可以將新節點新增至叢集以擴充其容量、或是在完全取代控制器的過程中新增節點。無論是哪種情況、您都需要啟用資料從現有控制器移轉至新系統中的新節點。

如果您打算將新節點新增至叢集、而這些節點需要比叢集目前執行版本更高的最低 ONTAP 版本、則在新增節點之前、您必須在叢集中現有節點上執行任何支援的軟體升級。

理想情況下、您可以將所有現有節點升級至您計畫新增至叢集的節點所需的最低 ONTAP 版本。不過、如果由於部分現有節點不支援較新版本的 ONTAP 、因此無法執行此動作、則在升級程序中、您必須在有限的時間內輸入混合版本狀態。如果節點不支援新控制器所需的最低 ONTAP 版本、您應該執行下列動作：

. link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_methods.html["升級"] 叢集中支援新控制器所需最低 ONTAP 版本的任何節點。
. 將新節點新增至叢集。
+
使用 ONTAP 命令叢集 `add-node -allow-mixed-version-join` 在進階權限層級加入新節點。

. 將資料從任何無法升級的節點移轉至執行較高 ONTAP 版本的節點。
. link:https://docs.netapp.com/us-en/ontap/system-admin/remov-nodes-cluster-concept.html["從叢集中移除不支援的節點"^]。
+
使用 ONTAP 命令叢集 `remove-node -skip-last-low-version-node-check` 移除這些節點。（在 ONTAP 9.3 及更早版本中、請使用 `cluster unjoin -skip-last-low-version-node-check` 命令。）



如需資料移轉的詳細資訊、請參閱：

* link:https://docs.netapp.com/us-en/ontap-systems-upgrade/upgrade/upgrade-create-aggregate-move-volumes.html["建立Aggregate並將磁碟區移至新節點"^]
* link:https://docs.netapp.com/us-en/ontap-metrocluster/transition/task_move_linux_iscsi_hosts_from_mcc_fc_to_mcc_ip_nodes.html#setting-up-new-iscsi-connections["設定新的 iSCSI 連線以進行 SAN 磁碟區移動"^]
* link:https://docs.netapp.com/us-en/ontap/encryption-at-rest/encrypt-existing-volume-task.html["使用加密來移動磁碟區"^]

