---
permalink: upgrade/considerations-authenticate-ssh-public-key-fips-concept.html 
sidebar: sidebar 
keywords: ontap, upgrade, update, considerations, ssl, fips mode, host key algorithm 
summary: 如果在系統管理員帳戶使用SSH公開金鑰進行驗證的叢集上啟用SSL FIPS模式、您必須先確定目標版本支援主機金鑰演算法、然後再升級ONTAP 。 
---
= 工作階段導向傳輸協定的考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果在系統管理員帳戶使用SSH公開金鑰進行驗證的叢集上啟用SSL FIPS模式、您必須先確定目標版本支援主機金鑰演算法、然後再升級ONTAP 。

*附註：* ONTAP 主機金鑰演算法支援已在更新版本的版本中變更。

[cols="30,30,30"]
|===


| 發行版ONTAP | 支援的金鑰類型 | 不支援的金鑰類型 


 a| 
9.11.1及更新版本
 a| 
ECDSA-SHA2-nistp256
 a| 
RSA-SHA2-512 + RSA-SHA2-256 + ssh - ed25519 + ssh - DSS + ssh - RSA



 a| 
9.10.1及更早版本
 a| 
ECDSA-SHA2-nistp256 + ssh編輯25519
 a| 
SSH-DSS + SSH-RSA

|===
在啟用升級之前、必須使用支援的金鑰類型重新設定現有SSH公開金鑰帳戶、否則系統管理員驗證將會失敗。

link:../authentication/enable-ssh-public-key-accounts-task.html["深入瞭解如何啟用SSH公開金鑰帳戶。"]



== 零點9.11.1RC1考量ONTAP

由於修訂版9.11.1RC1、FIPS 140-2法規遵循管理模式不再使用FIPS 140-2驗證的軟體模組。ONTAP

適用於HTTPS的管理與控制面板連線的OpenSSL版本升級為《The OpenSSL version for Management and Control Plane connections for HTTPS（ONTAP此版本的OpenSSL（OpenSSL 3.x FIPS Provider）尚未完成FIPS 140-2密碼模組驗證方案（CMVP）驗證程序。

啟用FIPS相容模式時、用於HTTPS連線的加密演算法會與在密碼編譯演算法驗證方案（CA1938）憑證中發行的OpenSSL Project OpenSSL 3.x FIPS Provider演算法相同。*此變更僅影響ONTAP FIPS相容模式下設定的所有系統。*

一旦更新版的OpenSSL模組ONTAP 在更新版的更新版本中、完成FIPS 140-2與NIST的驗證、就能解決此問題。如果您的環境需要ONTAP 以FIPS 140-2 CMVP驗證模組執行叢集管理控制面板、則建議您不要升級至9.11.1RC1。

這並不會影響NetApp在REST時的加密技術、例如NSE、NVE和NAE、因為這些功能使用的密碼編譯模組與在ONTAP 還原中由OpenSSL提供的模組不同。

如需詳細資訊、請參閱 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Upgrading_to_ONTAP_9.11.1RC1_results_in_FIPS_140-2_compliance_management_configuration_that_is_not_validated["升級ONTAP 至RC1RC1會產生FIPS 140-2法規遵循管理組態、但尚未驗證"^]。
