---
permalink: upgrade/create-upgrade-plan.html 
sidebar: sidebar 
keywords: ontap, upgrade, plan, planning, upgrade advisor, advisor, digital advisor, active iq, create an upgrade plan, estimate upgrade, 
summary: Digital Advisor 的 Upgrade Advisor 服務提供智慧功能、協助您規劃升級、並將不確定性和風險降至最低。 
---
= 使用升級建議程式準備 ONTAP 升級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您有的有效link:https://www.netapp.com/us/services/support-edge.aspx["部門服務SupportEdge"^]合約link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["數位顧問"^]、建議您使用 Upgrade Advisor 來產生升級計畫。

Digital Advisor 的 Upgrade Advisor 服務提供智慧功能、協助您規劃升級、並將不確定性和風險降至最低。

數位顧問可識別環境中的問題、這些問題可透過升級至較新版本的 ONTAP 來解決。Upgrade Advisor服務可協助您規劃成功升級、並提供升級ONTAP 時可能需要注意的問題報告。


NOTE: 升級建議程式需要 AutoSupport 記錄才能建立報告。如果您已啟用 AutoSupport ，升級建議程式就能存取記錄檔，並能成功建立報告。如果您尚未啟用 AutoSupport ，您可以 https://kb.netapp.com/on-prem/ontap/Ontap_OS/OS-KBs/How_to_manually_upload_AutoSupport_messages_to_NetApp_in_ONTAP_9["手動上傳 AutoSupport 檔案"^]。

如果您沒有適用於 Digital Advisor 的 Active Support Edge Services 合約link:prepare.html["準備升級、無需升級顧問"]、您應該。

.步驟
. https://aiq.netapp.com/["啟動 Active IQ 數位顧問"^]
. 在 Digital Advisor 中link:https://docs.netapp.com/us-en/active-iq/task_view_risk_and_take_action.html["檢視與叢集相關的任何風險、並手動採取修正行動"^]。
+
執行 ONTAP 升級之前、 * 軟體組態變更 * 、 * 硬體組態變更 * 和 * 硬體更換 * 類別所包含的風險必須先解決。

. 檢閱建議的升級路徑和 link:https://docs.netapp.com/us-en/active-iq/upgrade_advisor_overview.html["產生您的升級計畫"^]。


.下一步
* 您應該檢閱 link:../release-notes/index.html["發行說明ONTAP"] 對於 Upgrade Advisor 建議用於叢集的目標 ONTAP 版本、您應該遵循 Upgrade Advisor 所產生的計畫來升級叢集。
* 您應該 link:reboot-sp-bmc.html["重新啟動 SP 或 BMC"] 升級開始之前。

