---
permalink: upgrade/index.html 
sidebar: sidebar 
keywords: upgrade overview, upgrade, digital advisor, summary, upgrade ontap, upgrading ontap, upgrade, upgrading, ontap, software, on-premise, prepare, preparation, major upgrade, minor upgrade, patch upgrade, upgrade assistance, upgrade help, upgrade technical support 
summary: ONTAP 升級可讓您充分利用新的增強功能。在開始之前、請依照建議的步驟準備升級。 
---
= ONTAP 升級總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您升級 ONTAP 軟體時、您可以利用新的增強 ONTAP 功能、協助您降低成本、加速關鍵工作負載、改善安全性、並擴大組織可用的資料保護範圍。

重大 ONTAP 升級包括從較低的 ONTAP 編號版本移至較高的版本。例如、將叢集從 ONTAP 9.8 升級至 ONTAP 9.12.1 。  次要（或修補程式）升級包括從較低的 ONTAP 版本移至相同編號版本中較高的 ONTAP 版本。例如、將叢集從 ONTAP 9.12.1P1 升級至 9.12.1P4 。

若要開始使用link:prepare.html["準備升級"]、您應該：如果您有 Active IQ 數位顧問（也稱為數位顧問）的有效 SupportEdge 合約、您應該link:create-upgrade-plan.html["使用 Upgrade Advisor 規劃升級"]。升級顧問提供的智慧功能可協助您評估叢集並建立專屬組態的升級計畫、以將不確定性和風險降至最低。

準備好升級之後、建議您使用執行升級 link:task_upgrade_andu_sm.html["從 System Manager 自動進行不中斷升級（ andu ）"]。  ANDU 利用 ONTAP 的高可用度（ HA ）容錯移轉技術、確保叢集在升級期間能持續提供資料、而不會中斷。


NOTE: 從功能更新至功能更新至功能更新至功能更新、系統管理程式與BlueXP完全整合ONTAP 。如果系統上已設定 BlueXP 、您可以透過 BlueXP 工作環境進行升級。

如果您需要升級 ONTAP 軟體的協助、 NetApp 專業服務提供 link:https://www.netapp.com/pdf.html?item=/media/8144-sd-managed-upgrade-service.pdf["託管升級服務"^]。如果您有興趣使用此服務、請聯絡您的 NetApp 銷售代表或 link:https://www.netapp.com/forms/sales-contact/["提交 NetApp 的銷售查詢表"^]。託管升級服務以及其他類型的升級支援、均提供給客戶 link:https://www.netapp.com/pdf.html?item=/media/8845-supportedge-expert-service.pdf["SupportEdge Expert 服務"^] 無需額外成本。
