---
permalink: upgrade/prepare.html 
sidebar: sidebar 
keywords: upgrade, ontap, prepare, digital advisor, preparation, before you upgrade, plan, upgrade overview, upgrade summary, upgrade health checker 
summary: 準備 ONTAP 升級有助於識別並減輕升級風險或封鎖程式、並考慮適用於您組態的特殊考量。 
---
= 手動準備 ONTAP 軟體升級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您選擇手動準備升級，則需要完成多項任務，以檢查是否有任何已知問題或障礙，並確保您的叢集符合升級的必要要求。例如，如果您的叢集啟用了 SSL FIPS 模式，且管理員帳戶使用 SSH 公鑰進行驗證，則需要驗證目標 ONTAP 版本是否支援主機金鑰演算法。


NOTE: 使用 Active IQ Digital Advisor 中的 Upgrade Advisor 或 Upgrade Health Checker 時，無需手動準備。這兩款工具都能提供智慧訊息，幫助您規劃升級、識別障礙和警告，並最大限度地降低不確定性和風險。了解更多有關link:create-upgrade-plan.html["使用 Upgrade Advisor 或 Upgrade Health Checker 準備升級"]的資訊。

.步驟
. link:choose-target-version.html["選擇您的目標 ONTAP 版本"]。
. 請參閱目標版本中的 _ 升級注意事項 _ 和 _ 已知問題和限制 _ 章節link:https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["發行說明ONTAP"]。
+
_ 升級注意事項 _ 說明您在升級前應注意的潛在問題。_ 已知的問題和限制 _ 說明您在升級後可能會遇到的潛在非預期系統行為。

+
您必須使用 NetApp 帳戶登入、或建立帳戶才能存取版本資訊。

. link:confirm-configuration.html["確認 ONTAP 支援您的硬體組態"]。
+
您的硬體平台、叢集管理交換器和 MetroCluster IP 交換器必須支援目標版本。  如果您的叢集是針對 SAN 進行設定、則必須完全支援 SAN 組態。

. link:task_check_for_common_configuration_errors_using_config_advisor.html["使用 Active IQ Config Advisor 驗證您沒有常見的組態錯誤。"]
. 檢閱支援的 ONTAP link:concept_upgrade_paths.html#supported-upgrade-paths["升級途徑"] 判斷您是否可以執行直接升級、或是否需要分階段完成升級。
. link:task_verifying_the_lif_failover_configuration.html["驗證 LIF 容錯移轉組態"]。
+
在執行升級之前、您需要確認叢集的容錯移轉原則和容錯移轉群組已正確設定。

. link:concept_verify_svm_routing.html["驗證 SVM 路由組態"]。
. link:special-considerations.html["驗證特殊考量"] 適用於您的叢集。
+
如果叢集上有特定組態、則在開始 ONTAP 軟體升級之前、您需要採取特定行動。

. link:reboot-sp-bmc.html["重新啟動 SP 或 BMC"]。

