---
permalink: upgrade/task_preparing_snapmirror_relationships_for_a_nondisruptive_upgrade_or_downgrade.html 
sidebar: sidebar 
keywords: ontap, upgrade, snapmirror, operations, quisce 
summary: 建議您在執行ONTAP 不中斷營運的更新之前、先停止SnapMirror作業。 
---
= 準備SnapMirror關係以進行不中斷營運的升級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建議您在執行ONTAP 不中斷營運的更新之前、先停止SnapMirror作業。

.步驟
. 使用 `snapmirror show` 命令來判斷每個SnapMirror關係的目的地路徑。
. 針對每個目的地Volume、暫停未來的SnapMirror傳輸：
+
`snapmirror quiesce -destination-path destination`

+
如果SnapMirror關係沒有作用中的傳輸、此命令會將其狀態設為「靜止」。如果關係有作用中的傳輸、狀態會設定為「靜止」、直到傳輸完成為止、然後狀態會變成「靜止」。

+
此範例會停止從「SVMvs0.example.com":」傳送涉及目的地Volume「vol1」的傳輸

+
[listing]
----
cluster1::> snapmirror quiesce -destination-path vs0.example.com:vol1
----
. 確認所有SnapMirror關係均已靜止：
+
`snapmirror show -status !Quiesced`

+
此命令會顯示任何非靜止的SnapMirror關係。

+
此範例顯示所有SnapMirror關係均已靜止：

+
[listing]
----
cluster1::> snapmirror show -status !Quiesced
There are no entries matching your query.
----
. 如果目前正在傳輸任何SnapMirror關係、請執行下列其中一個選項：
+
[cols="2*"]
|===
| 選項 | 說明 


 a| 
等待傳輸完成、再執行ONTAP 更新。
 a| 
每次傳輸完成後、關係會變更為「靜止」狀態。



 a| 
停止傳輸：

`snapmirror abort -destination-path destination -h`

*注意：*您必須使用 `-foreground true` 如果您正在中止負載共用鏡射傳輸、則為參數。
 a| 
此命令會停止SnapMirror傳輸、並將目的地磁碟區還原至上次成功傳輸的Snapshot複本。關係設定為「靜止」狀態。

|===


.相關資訊
xref:concept_upgrade_requirements_for_snapmirror.adoc[SnapMirror的升級需求]
