---
permalink: upgrade/task_enabling_and_reverting_lifs_to_home_ports_preparing_the_ontap_software_for_the_update.html 
sidebar: sidebar 
keywords: ontap, upgrade, enabling, enable, revert, reverting, lifs, home, ports, 
summary: 在重新開機期間、部分LIF可能已移轉至指派的容錯移轉連接埠。在升級叢集之前和之後、您必須啟用並還原任何不在其主連接埠上的生命。 
---
= 在升級之前、請先確認所有生命體均位於主連接埠上
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在重新開機期間、部分LIF可能已移轉至指派的容錯移轉連接埠。在升級叢集之前和之後、您必須啟用並還原任何不在其主連接埠上的生命。

如果主連接埠正常運作、網路介面還原命令會將目前不在主連接埠上的LIF還原回主連接埠。LIF的主連接埠是在建立LIF時指定、您可以使用network interface show命令來判斷LIF的主連接埠。

. 顯示所有生命的狀態：「網路介面顯示」
+
此範例顯示儲存虛擬機器（SVM）的所有LIF狀態。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001    down/down  192.0.2.120/24     node0         e0e     true
            data002    down/down  192.0.2.121/24     node0         e0f     true
            data003    down/down  192.0.2.122/24     node0         e2a     true
            data004    down/down  192.0.2.123/24     node0         e2b     true
            data005    down/down  192.0.2.124/24     node0         e0e     false
            data006    down/down  192.0.2.125/24     node0         e0f     false
            data007    down/down  192.0.2.126/24     node0         e2a     false
            data008    down/down  192.0.2.127/24     node0         e2b     false
8 entries were displayed.
----
+
如果任何生命週期顯示的狀態為「狀態管理」狀態為「關閉」或「為主目錄」狀態為「假」、請繼續下一步。

. 啟用資料LIF：「網路介面修改｛-role data｝-STATUS-admin up」
+
[listing]
----
cluster1::> network interface modify {-role data} -status-admin up
8 entries were modified.
----
. 將LIF還原至其主連接埠：「網路介面回復*」
+
此命令會將所有LIF還原回其主連接埠。

+
[listing]
----
cluster1::> network interface revert *
8 entries were acted on.
----
. 驗證所有生命設備是否都在其主端口上：「network interface show」（網路介面顯示）
+
此範例顯示SVM vs0的所有lifs都位於其主連接埠上。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001      up/up    192.0.2.120/24     node0         e0e     true
            data002      up/up    192.0.2.121/24     node0         e0f     true
            data003      up/up    192.0.2.122/24     node0         e2a     true
            data004      up/up    192.0.2.123/24     node0         e2b     true
            data005      up/up    192.0.2.124/24     node1         e0e     true
            data006      up/up    192.0.2.125/24     node1         e0f     true
            data007      up/up    192.0.2.126/24     node1         e2a     true
            data008      up/up    192.0.2.127/24     node1         e2b     true
8 entries were displayed.
----

