---
sidebar: sidebar 
permalink: upgrade/task_upgrade_andu_cli.html 
keywords: netapp, ontap, automate, automatic, automated, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: 您可以在不中斷營運的情況下更新ONTAP 叢集上的版本。 
---
= 使用CLI自動進行不中斷ONTAP 的升級
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
對於自動升級、 ONTAP 會自動在每個節點上安裝目標 ONTAP 映像、驗證叢集元件、確保叢集可以不中斷地升級、然後執行 xref:concept_upgrade_methods.html[批次或循環升級] 在背景中、根據節點數量。

您可以使用命令列介面（CLI）來驗證叢集是否可在不中斷營運的情況下升級、在ONTAP 每個節點上安裝目標的版本資訊、然後在背景執行升級。


NOTE: 如果您不打算監控升級程序的進度、這是很好的做法 link:task_requesting_notification_of_issues_encountered_in_nondisruptive_upgrades.html["要求EMS通知可能需要手動介入的錯誤"]。

.開始之前
* 您應該 link:prepare.html["準備升級"]。
* 您應該 link:download-software-image.html["下載 ONTAP 軟體映像"] 適用於您的目標 ONTAP 版本。
* 對於每個HA配對、每個節點應在同一個廣播網域上有一個或多個連接埠。
+
如果您有8個以上的節點、批次升級方法將用於自動不中斷升級。  在更新的版本中、如果使用批次方法、則會將LIF移轉至要升級之節點的HA合作夥伴。ONTAP  如果合作夥伴在同一個廣播網域中沒有任何連接埠、則LIF移轉會失敗。

+
在更新的版本中、如果使用批次方法、則會將lifs移轉至其他批次群組。ONTAP

* 如果您執行的是 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["直接多跳升級"]、您必須同時取得ONTAP 您所需的兩個正確的資訊影像 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#supported-upgrade-paths["升級途徑"]。
* 如果您要在 MetroCluster FC 組態中升級 ONTAP 、則應該啟用叢集、以便自動進行非計畫性切換。



NOTE: 修改的設定 `storage failover modify-auto-giveback` 在自動不中斷升級（ andu ）開始之前的命令選項、不會影響升級程序。在更新所需的接管/恢復期間、andu程序會忽略此選項的任何預設值。例如、設定 `-autogiveback` 如果在開始之前為 FALSE 、則不會在恢復之前中斷自動升級。



== 步驟 1 ：將目標 ONTAP 軟體映像載入叢集套件儲存庫

若要開始 ONTAP 軟體升級程序、您必須在叢集套件儲存庫中提供目標 ONTAP 軟體映像。

.步驟
. 刪除先前ONTAP 的版本：
+
[source, cli]
----
cluster image package delete -version previous_ONTAP_Version
----
. 將目標 ONTAP 軟體映像載入叢集套件儲存庫：
+
[source, cli]
----
cluster image package get -url location
----
+
[listing]
----
cluster1::> cluster image package get -url http://www.example.com/software/9.13.1/image.tgz

Package download completed.
Package processing completed.
----
+
如果您執行的是 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["直接多跳升級"]，您也需要載入升級所需的 ONTAP 中間版本的軟體套件。例如、如果您要從 9.8 升級至 9.13.1 、則需要載入 ONTAP 9.12.1 的軟體套件、然後使用相同的命令載入 9.13.1 的軟體套件。

. 驗證叢集套件儲存庫中是否有可用的軟體套件：
+
[source, cli]
----
cluster image package show-repository
----
+
[listing]
----
cluster1::> cluster image package show-repository
Package Version  Package Build Time
---------------- ------------------
9.13.1              MM/DD/YYYY 10:32:15
----




== 步驟 2 ：執行自動升級前檢查

您也可以選擇在執行 ONTAP 軟體的自動升級之前、使用 `cluster image validate` 用於驗證叢集是否能成功升級的命令。  。 `cluster image validate` 命令會針對叢集元件執行一系列檢查、然後提供已執行的特定驗證清單、以及在繼續升級之前必須採取的任何修正動作清單。

. 執行自動升級前檢查：
+
[source, cli]
----
cluster image validate -version package_version_number
----
+
** 如果您執行的是 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["直接多跳升級"]、使用目標 ONTAP 套件進行驗證。  您不需要個別驗證中間升級映像。  例如、如果您要從 9.8 升級至 9.13.1 、則應使用 9.13.1 套件進行驗證。您不需要個別驗證 9.12.1 套件。
** 如果您要升級雙節點或四節點MetroCluster 的支援、則必須在兩個叢集上執行此命令、才能繼續進行。
+
[listing]
----
cluster1::> cluster image validate -version 9.13.1

WARNING: There are additional manual upgrade validation checks that must be performed after these automated validation checks have completed...
----


. 監控驗證進度：
+
[source, cli]
----
cluster image show-update-progress
----
. 完成驗證所識別的所有必要行動。




== 步驟 3 ：升級 ONTAP 軟體

. 產生軟體升級預估：
+
[source, cli]
----
cluster image update -version package_version_number -estimate-only
----
+
軟體升級預估會顯示每個要更新元件的詳細資料、以及預估的升級期間。

. 執行軟體升級：
+
[source, cli]
----
cluster image update -version package_version_number
----
+
** 如果您執行的是 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["直接多跳升級"]，請將目標 ONTAP 版本用於 package_version_number 。例如、如果您要從 ONTAP 9.8 升級至 9.13.1 、請使用 9.13.1 做為 package_version_number 。
** 如果叢集由2至6個節點組成、則會執行循環升級。如果叢集由8個以上的節點組成、預設會執行批次升級。如有需要、您可以使用 `-force-rolling` 指定循環升級的參數。
** 完成每次接管與恢復之後、升級會等待8分鐘、讓用戶端應用程式從接管與恢復期間發生的I/O暫停中恢復。如果您的環境需要更多或更少的時間來穩定用戶端、您可以使用 `-stabilize-minutes` 指定不同穩定時間量的參數。
** 對於MetroCluster 任何不含雙節點MetroCluster 的支援功能組態、ONTAP 在使用者啟動並在命令列上提供確認之後、即可在兩個站台（本機站台和災難恢復站台）的HA配對上同時開始執行升級程序。若為雙節點MetroCluster 的作業系統、更新會先在災難恢復站台（即未啟動升級的站台）上啟動。在災難恢復站點上完成更新後，升級將從本地站點開始。
+
[listing]
----
cluster1::> cluster image update -version 9.13.1

Starting validation for this update. Please wait..

It can take several minutes to complete validation...

WARNING: There are additional manual upgrade validation checks...

Pre-update Check      Status     Error-Action
--------------------- ---------- --------------------------------------------
...
20 entries were displayed

Would you like to proceed with update ? {y|n}: y
Starting update...

cluster-1::>
----


. 顯示叢集更新進度：
+
[source, cli]
----
cluster image show-update-progress
----
+
如果您要升級 4 節點或 8 節點 MetroCluster 組態、請使用 `cluster image show-update-progress` 命令只會顯示您執行命令所在節點的進度。您必須在每個節點上執行命令、才能查看個別節點的進度。

. 驗證是否已在每個節點上成功完成升級。
+
[source, cli]
----
cluster image show-update-progress
----
+
[listing]
----
cluster1::> cluster image show-update-progress

                                             Estimated         Elapsed
Update Phase         Status                   Duration        Duration
-------------------- ----------------- --------------- ---------------
Pre-update checks    completed                00:10:00        00:02:07
Data ONTAP updates   completed                01:31:00        01:39:00
Post-update checks   completed                00:10:00        00:02:00
3 entries were displayed.

Updated nodes: node0, node1.
----
. 觸發AutoSupport 功能不支援通知：
+
[source, cli]
----
autosupport invoke -node * -type all -message "Finishing_NDU"
----
+
如果您的叢集未設定為傳送AutoSupport 功能性訊息、則會在本機儲存通知複本。

. 確認叢集已啟用自動非計畫性切換：
+

NOTE: 此步驟僅適用於 MetroCluster FC 組態。  如果您使用的是 MetroCluster IP 組態、則不需要執行此步驟。

+
.. 檢查是否已啟用自動非計畫性切換：
+
[source, cli]
----
metrocluster show
----
+
如果啟用自動非計畫性切換、命令輸出中會出現下列陳述：

+
....
AUSO Failure Domain    auso-on-cluster-disaster
....
.. 如果輸出中未顯示該陳述、請啟用自動非計畫性切換：
+
[source, cli]
----
metrocluster modify -auto-switchover-failure-domain auso-on-cluster-disaster -overide-vetoes true
----
+

NOTE: 在自動不中斷升級完成之前、您無法執行切換作業。

.. 確認已啟用自動非計畫性切換：
+
[source, cli]
----
metrocluster show
----




.相關資訊
* https://aiq.netapp.com/["產品Active IQ 發表"]
* https://docs.netapp.com/us-en/active-iq/["本文檔Active IQ"]

