---
sidebar: sidebar 
permalink: upgrade/task_upgrade_andu_cli.html 
keywords: netapp, ontap, automate, automatic, automated, upgrade, nondisruptive, nondisruptively, non-disruptive update, nondisruptive upgrade, upgrade a cluster, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: 您可以在不中斷營運的情況下更新ONTAP 叢集上的版本。 
---
= 使用CLI自動進行不中斷ONTAP 的升級
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
您可以使用命令列介面（CLI）來驗證叢集是否可在不中斷營運的情況下升級、在ONTAP 每個節點上安裝目標的版本資訊、然後在背景執行升級。

升級之後、您應該確認叢集版本、叢集健全狀況和儲存健全狀況。


NOTE: 如果您使用MetroCluster 的是SFC組態、您也需要確認叢集已啟用自動非計畫性切換功能。

如果您不打算監控升級程序的進度、這是很好的做法 link:task_requesting_notification_of_issues_encountered_in_nondisruptive_upgrades.html["要求EMS通知可能需要手動介入的錯誤"]。

.開始之前
* 您應該啟動Active IQ 「We Digital Advisor」。
+
「升級顧問Active IQ 」元件可協助您規劃成功升級。

+
所有擁有有效*《*》*《*》*《*》*合約的NetApp客戶、均可從Active IQ 《支援資料》中獲得資料導向的洞見與建議SupportEdge （功能因產品與支援層而異）。

* 您必須符合升級準備要求。
* 對於每個HA配對、每個節點應在同一個廣播網域上有一個或多個連接埠。
+
如果您有8個以上的節點、批次升級方法將用於自動不中斷升級。在更新的版本中、如果使用批次方法、則會將LIF移轉至要升級之節點的HA合作夥伴。ONTAP如果合作夥伴在同一個廣播網域中沒有任何連接埠、則LIF移轉會失敗。

+
在更新的版本中、如果使用批次方法、則會將lifs移轉至其他批次群組。ONTAP

* 如果您執行的是 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#types-of-upgrade-paths["直接多跳升級"]、您必須同時取得ONTAP 您所需的兩個正確的資訊影像 link:https://docs.netapp.com/us-en/ontap/upgrade/concept_upgrade_paths.html#supported-upgrade-paths["升級途徑"]。


.關於這項工作
「叢集映像驗證」命令會檢查叢集元件、以驗證升級是否可在不中斷營運的情況下完成、然後提供每項檢查的狀態、以及執行軟體升級之前必須採取的任何必要行動。


NOTE: 在開始自動不中斷升級（andu）之前、修改「儲存容錯移轉modify-automatic f恢復」命令選項的設定、對升級程序沒有任何影響。在更新所需的接管/恢復期間、andu程序會忽略此選項的任何預設值。例如、在開始前將「自動恢復」設定為「假」、不會在還原之前中斷自動升級。

. 刪除先前ONTAP 的版本：
+
叢集映像套件刪除-version pre_onta_Version

. 下載目標ONTAP 版的更新軟體套件：
+
叢集映像套件Get -URL位置

+

NOTE: 如果您要從ONTAP 版本資訊9.3升級至9.7、請下載ONTAP 適用於版本資訊的軟體套件、然後使用相同的命令下載適用於9.7的軟體套件。如果您要從ONTAP 版本資訊9.5升級至9.9.1、請下載ONTAP 適用於版本資訊的軟體套件、然後使用相同的命令下載9.9.1的軟體套件。

+
[listing]
----
cluster1::> cluster image package get -url http://www.example.com/software/9.7/image.tgz

Package download completed.
Package processing completed.
----
. 驗證叢集套件儲存庫中是否有可用的軟體套件：
+
「叢集映像套件show-repository」

+
[listing]
----
cluster1::> cluster image package show-repository
Package Version  Package Build Time
---------------- ------------------
9.7              MM/DD/YYYY 10:32:15
----
. 確認叢集已準備好在不中斷營運的情況下升級：
+
叢集映像validate -version套件版本號碼

+
** 如果您要升級雙節點或四節點MetroCluster 的支援、則必須在兩個叢集上執行此命令、才能繼續進行。
** 如果您要從ONTAP 0版9.3升級至9.7版、請使用9.7套件進行驗證。您不需要個別驗證9.5套件。
** 如果您要從ONTAP S209.5升級至9.9.1、請使用9.9.1套件進行驗證。您不需要分別驗證9.7套件。


+
[listing]
----
cluster1::> cluster image validate -version 9.7

WARNING: There are additional manual upgrade validation checks that must be performed after these automated validation checks have completed...
----
. 監控驗證進度：
+
「叢集映像顯示更新進度」

. 完成驗證所識別的所有必要行動。
. 產生軟體升級預估：
+
「叢集映像更新-version套件版本編號-estim-only」

+
軟體升級預估會顯示每個要更新元件的詳細資料、以及預估的升級期間。

. 執行軟體升級：
+
叢集映像更新-version套件版本編號

+
** 如果您要從ONTAP 版本資訊9.3升級至9.7、請使用上述命令中的9.7套件版本編號。
** 如果您要從ONTAP Sets9.5升級至9.9.1、請使用上述命令中的9.9.1套件版本編號。
** 對於MetroCluster 任何不含雙節點MetroCluster 的支援功能組態、ONTAP 在使用者啟動並在命令列上提供確認之後、即可在兩個站台（本機站台和災難恢復站台）的HA配對上同時開始執行升級程序。若為雙節點MetroCluster 的作業系統、更新會先在災難恢復站台（即未啟動升級的站台）上啟動。在災難恢復站點上完成更新後，升級將從本地站點開始。
** 如果叢集由2至6個節點組成、則會執行循環升級。如果叢集由8個以上的節點組成、預設會執行批次升級。如果需要、您可以使用「-force-rolling」參數來指定循環升級。
** 完成每次接管與恢復之後、升級會等待8分鐘、讓用戶端應用程式從接管與恢復期間發生的I/O暫停中恢復。如果您的環境需要更多或更少的時間來穩定用戶端、您可以使用「穩定分鐘數」參數來指定不同的穩定時間量。
+
[listing]
----
cluster1::> cluster image update -version 9.7

Starting validation for this update. Please wait..

It can take several minutes to complete validation...

WARNING: There are additional manual upgrade validation checks...

Pre-update Check      Status     Error-Action
--------------------- ---------- --------------------------------------------
...
20 entries were displayed

Would you like to proceed with update ? {y|n}: y
Starting update...

cluster-1::>
----


. 顯示叢集更新進度：
+
「叢集映像顯示更新進度」

+

NOTE: 如果您要升級4節點或8節點MetroCluster 的BIOS組態、「cluster image show-update-progress」命令只會顯示執行命令之節點的進度。您必須在每個節點上執行命令、才能查看個別節點的進度。

. 驗證是否已在每個節點上成功完成升級。
+
[listing]
----
cluster1::> cluster image show-update-progress

                                             Estimated         Elapsed
Update Phase         Status                   Duration        Duration
-------------------- ----------------- --------------- ---------------
Pre-update checks    completed                00:10:00        00:02:07
Data ONTAP updates   completed                01:31:00        01:39:00
Post-update checks   completed                00:10:00        00:02:00
3 entries were displayed.

Updated nodes: node0, node1.

cluster1::>
----
. 觸發AutoSupport 功能不支援通知：
+
「AutoSupport 叫用節點*-輸入all -messing_NDU」訊息

+
如果您的叢集未設定為傳送AutoSupport 功能性訊息、則會在本機儲存通知複本。

. 確認叢集已啟用自動非計畫性切換：
+

NOTE: 此程序僅適用於MetroCluster 不含功能的FC組態。如果您使用MetroCluster 的是一套靜態IP組態、請跳過此程序。

+
.. 檢查是否已啟用自動非計畫性切換：
+
《不看》MetroCluster

+
如果啟用自動非計畫性切換、命令輸出中會出現下列陳述：

+
....
AUSO Failure Domain    auso-on-cluster-disaster
....
.. 如果輸出中未顯示該陳述、請啟用自動非計畫性切換：
+
《MetroCluster 關於在叢集上發生auso-on叢集災難的迴轉自動切換失敗網域》

.. 重複步驟1、確認已啟用自動非計畫性切換。






== 在自動升級程序發生錯誤後、繼續升級（使用CLI）

如果因為錯誤而導致自動升級暫停、您可以解決錯誤並恢復自動升級、也可以取消自動升級並手動完成程序。如果您選擇繼續自動升級、請勿手動執行任何升級步驟。

.關於這項工作
如果您想要手動完成升級、請使用「cluster image cance-update」命令取消自動化程序、然後手動繼續。如果您要繼續自動升級、請完成下列步驟。

.步驟
. 檢視升級錯誤：
+
「叢集映像顯示更新進度」

. 解決錯誤。
. 繼續更新：
+
「叢集映像恢復更新」



.相關資訊
https://["產品Active IQ 發表"]

https://["本文檔Active IQ"]
