---
permalink: upgrade/task-prep-node-upgrade-nse-with-ext-kmip-servers.html 
sidebar: sidebar 
keywords: ontap, upgrade, prepare, preparing, nodes, netapp, storage, encryption, nse, external, key management, servers 
summary: 如果您在 ONTAP 9.2 或更早版本上使用 NetApp 儲存加密、並升級至 9.3 或更高版本、請在升級之前刪除外部金鑰管理伺服器連線。 
---
= 在升級 ONTAP 之前刪除現有的外部金鑰管理伺服器連線
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
升級 ONTAP 之前、如果您使用 NetApp 儲存加密（ NSE ）執行 ONTAP 9.2 或更早版本、並升級至 ONTAP 9.3 或更新版本、則必須使用命令列介面（ CLI ）刪除任何現有的外部金鑰管理（ KMIP ）伺服器連線。

.步驟
. 確認NSE磁碟機已解除鎖定、開啟並設定為預設製造商安全ID 0x0：
+
[source, cli]
----
storage encryption disk show -disk *
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["指令參考資料ONTAP"^]需詳細 `storage encryption disk show`資訊，請參閱。

. 進入進階權限模式：
+
[source, cli]
----
set -privilege advanced
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/set.html["指令參考資料ONTAP"^]需詳細 `set`資訊，請參閱。

. 使用預設製造安全 ID 0x0 將 FIPS 金鑰指派給自我加密磁碟（ SED ）：
+
[source, cli]
----
storage encryption disk modify -fips-key-id 0x0 -disk *
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-modify.html["指令參考資料ONTAP"^]需詳細 `storage encryption disk modify`資訊，請參閱。

. 確認指派 FIPS 金鑰給所有磁碟已完成：
+
[source, cli]
----
storage encryption disk show-status
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show-status.html["指令參考資料ONTAP"^]需詳細 `storage encryption disk show-status`資訊，請參閱。

. 驗證所有磁碟的 * 模式 * 是否已設定為資料
+
[source, cli]
----
storage encryption disk show
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-show.html["指令參考資料ONTAP"^]需詳細 `storage encryption disk show`資訊，請參閱。

. 檢視已設定的 KMIP 伺服器：
+
[source, cli]
----
security key-manager keystore show
----
+
詳細了解 `security key-manager keystore show`在link:https://docs.netapp.com/us-en/ontap-cli//security-key-manager-keystore-show.html["指令參考資料ONTAP"^]。

. 刪除已設定的 KMIP 伺服器：
+
[source, cli]
----
security key-manager delete -address <kmip_ip_address>
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/security-key-manager-key-delete.html["指令參考資料ONTAP"^]需詳細 `security key-manager delete`資訊，請參閱。

. 刪除外部金鑰管理程式組態：
+
[source, cli]
----
security key-manager external disable
----
+
詳細了解 `security key-manager external disable`在link:https://docs.netapp.com/us-en/ontap-cli//security-key-manager-external-disable.html["指令參考資料ONTAP"^]。

+

NOTE: 此步驟不會刪除 NSE 憑證。



.下一步
升級完成後、您必須 xref:task_reconfiguring_kmip_servers_connections_after_upgrading_to_ontap_9_3_or_later.adoc[重新設定 KMIP 伺服器連線]。
