---
sidebar: sidebar 
permalink: upgrade/task_upgrade_nondisruptive_manual_cli.html 
keywords: upgrade, nondisruptive, , non-disruptive update, nondisruptive upgrade, shift workload between clusters, hardware platform, configuration, software image, update, update ONTAP, update software, ndu 
summary: 使用 System Manager 自動升級是首選的升級方法。  如果 System Manger 不支援您的組態、您可以使用 CLI 執行手動不中斷的升級。 
---
= 使用 CLI 手動進行不中斷的 ONTAP 升級（標準組態）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用 System Manager 自動升級是首選的升級方法。  如果系統管理員不支援您的組態、您可以使用 ONTAP 命令列介面（ CLI ）來執行手動不中斷的升級。  若要使用手動不中斷的方法升級兩個或多個節點的叢集、您必須在HA配對中的每個節點上啟動容錯移轉作業、更新「失敗」節點、啟動還原、然後針對叢集中的每個HA配對重複此程序。

.開始之前
您必須已滿意升級 link:prepare.html["準備"] 要求。



== 更新HA配對中的第一個節點

您可以啟動節點合作夥伴的接管、以更新HA配對中的第一個節點。當第一個節點升級時、合作夥伴會提供節點的資料。

如果您要執行重大升級、第一個要升級的節點必須與您設定外部連線資料生命期的節點相同、並安裝第一個ONTAP 版本的圖片。

升級第一個節點之後、您應該盡快升級合作夥伴節點。請勿讓兩個節點留在中 link:concept_mixed_version_requirements.html["混合版本"] 狀態時間超過所需時間。

.步驟
. 透過調用 AutoSupport 訊息來更新叢集中的第一個節點：
+
[source, cli]
----
autosupport invoke -node * -type all -message "Starting_NDU"
----
+
本資訊通知包含更新前的系統狀態記錄。AutoSupport如果更新程序發生問題、它會儲存有用的疑難排解資訊。

+
如果叢集未設定為傳送AutoSupport 功能性訊息、則會在本機儲存通知複本。

. 將權限等級設為「進階」、在提示繼續時輸入 * y* ：
+
[source, cli]
----
set -privilege advanced
----
+
進階提示 (`*>`）。

. 將新的 ONTAP 軟體映像設為預設映像：
+
[source, cli]
----
system image modify {-node nodenameA -iscurrent false} -isdefault true
----
+
系統映像修改命令會使用延伸查詢、將新ONTAP 的更新版軟體映像（安裝為替代映像）變更為節點的預設映像。

. 監控更新進度：
+
[source, cli]
----
system node upgrade-revert show
----
. 確認新的 ONTAP 軟體映像已設為預設映像：
+
[source, cli]
----
system image show
----
+
在下列範例中、image2是新ONTAP 的版本、並設為節點0上的預設映像：

+
[listing]
----
cluster1::*> system image show
                 Is      Is                Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------- -------------------
node0
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
node1
         image1  true    true    X.X.X     MM/DD/YYYY TIME
         image2  false   false   Y.Y.Y     MM/DD/YYYY TIME
4 entries were displayed.
----
. 如果合作夥伴節點已啟用自動恢復功能、請停用該功能：
+
[source, cli]
----
storage failover modify -node nodenameB -auto-giveback false
----
+
如果叢集是雙節點叢集、則會顯示一則訊息、警告您停用自動恢復功能、可在發生其他故障情況時、防止管理叢集服務上線。輸入 `y` 以繼續。

. 確認已停用節點合作夥伴的自動恢復功能：
+
[source, cli]
----
storage failover show -node nodenameB -fields auto-giveback
----
+
[listing]
----
cluster1::> storage failover show -node node1 -fields auto-giveback
node     auto-giveback
-------- -------------
node1    false
1 entry was displayed.
----
. 執行下列命令兩次、以判斷要更新的節點目前是否正在服務任何用戶端
+
[source, cli]
----
system node run -node nodenameA -command uptime
----
+
正常運作時間命令會顯示節點自上次開機以來、針對NFS、SMB、FC和iSCSI用戶端執行的作業總數。對於每個傳輸協定、您必須執行兩次命令、以判斷作業計數是否增加。如果數量不斷增加、則節點目前正在為該傳輸協定的用戶端提供服務。如果不增加、則節點目前不會為該傳輸協定的用戶端提供服務。

+

NOTE: 您應該記下每個增加用戶端作業的傳輸協定、以便在節點更新之後、您可以確認用戶端流量已恢復。

+
以下範例顯示一個節點、其執行NFS、SMB、FC和iSCSI作業。不過、節點目前僅提供NFS和iSCSI用戶端服務。

+
[listing]
----
cluster1::> system node run -node node0 -command uptime
  2:58pm up  7 days, 19:16 800000260 NFS ops, 1017333 CIFS ops, 0 HTTP ops, 40395 FCP ops, 32810 iSCSI ops

cluster1::> system node run -node node0 -command uptime
  2:58pm up  7 days, 19:17 800001573 NFS ops, 1017333 CIFS ops, 0 HTTP ops, 40395 FCP ops, 32815 iSCSI ops
----
. 將所有資料生命從節點移轉至其他位置：
+
[source, cli]
----
network interface migrate-all -node nodenameA
----
. 驗證您移轉的任何生命：
+
[source, cli]
----
network interface show
----
+
如需可用於驗證LIF狀態的參數相關資訊、請參閱網路介面show手冊頁。

+
以下範例顯示node0的資料lifs已成功移轉。對於每個LIF、本範例中所包含的欄位可讓您驗證LIF的主節點和連接埠、LIF移轉的目前節點和連接埠、以及LIF的作業和管理狀態。

+
[listing]
----
cluster1::> network interface show -data-protocol nfs|cifs -role data -home-node node0 -fields home-node,curr-node,curr-port,home-port,status-admin,status-oper
vserver lif     home-node home-port curr-node curr-port status-oper status-admin
------- ------- --------- --------- --------- --------- ----------- ------------
vs0     data001 node0     e0a       node1     e0a       up          up
vs0     data002 node0     e0b       node1     e0b       up          up
vs0     data003 node0     e0b       node1     e0b       up          up
vs0     data004 node0     e0a       node1     e0a       up          up
4 entries were displayed.
----
. 啟動接管：
+
[source, cli]
----
storage failover takeover -ofnode nodenameA
----
+
請勿指定-option Immediate參數、因為要將節點接管以開機至新的軟體映像時、需要正常接管。如果您未手動將l生命 從節點移轉至其他節點、則會自動移轉至節點的HA合作夥伴、以確保不會發生服務中斷。

+
第一個節點會開機、直到等待恢復狀態。

+

NOTE: 如果啟用 AutoSupport 、則會傳送一則 AutoSupport 訊息、指出節點已超出叢集仲裁。您可以忽略此通知並繼續更新。

. 確認接管成功：
+
[source, cli]
----
storage failover show
----
+
您可能會看到錯誤訊息、指出版本不相符和信箱格式問題。這是預期的行為、在重大且不中斷營運的升級中、這是暫時性的狀態、而且不會造成傷害。

+
以下範例顯示接管作業成功。節點節點0處於等待恢復狀態、其合作夥伴處於接管狀態。

+
[listing]
----
cluster1::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node0          node1          -        Waiting for giveback (HA mailboxes)
node1          node0          false    In takeover
2 entries were displayed.
----
. 至少等待八分鐘、讓下列情況生效：
+
** 用戶端多重路徑（若已部署）會穩定下來。
** 在接管期間執行I/O作業時、用戶端會從暫停狀態中恢復。
+
還原時間是用戶端特有的、可能需要八分鐘以上的時間、視用戶端應用程式的特性而定。



. 將集合體傳回第一個節點：


[listing]
----
storage failover giveback –ofnode nodenameA
----
+
恢復會先將根Aggregate傳回合作夥伴節點、然後在該節點完成開機之後、傳回非根Aggregate及任何設定為自動還原的LIF。新開機的節點會在傳回Aggregate後、立即開始從每個Aggregate向用戶端提供資料。

. 驗證是否已傳回所有的集合體：
+
[source, cli]
----
storage failover show-giveback
----
+
如果「歸還狀態」欄位指出沒有要歸還的集合體、則會傳回所有集合體。如果恢復被否決、命令會顯示恢復進度、以及哪個子系統已對恢復執行了指令。

. 如果尚未傳回任何Aggregate、請執行下列步驟：
+
.. 請檢閱「否決因應措施」、以判斷您是否想要處理「『直接』條件、或是要撤銷「否決」。
.. 如有必要、請解決錯誤訊息中所述的「『驗證』條件、確保所有已識別的作業都能正常終止。
.. 重新執行儲存容錯移轉恢復命令。
+
如果您決定覆寫「vito'」條件、請將-overre-etoes參數設為true。



. 至少等待八分鐘、讓下列情況生效：
+
** 用戶端多重路徑（若已部署）會穩定下來。
** 用戶端會從還原期間執行的I/O作業暫停中恢復。
+
還原時間是用戶端特有的、可能需要八分鐘以上的時間、視用戶端應用程式的特性而定。



. 驗證是否已成功完成節點的更新：
+
.. 進入進階權限等級：
+
[source, cli]
----
set -privilege advanced
----
.. 確認節點的更新狀態為完成：
+
[source, cli]
----
system node upgrade-revert show -node nodenameA
----
+
狀態應列示為「完成」。

+
如果狀態不完整、請聯絡技術支援部門。

.. 返回管理權限層級：
+
[source, cli]
----
set -privilege admin
----


. 驗證節點的連接埠是否正常運作：
+
[source, cli]
----
network port show -node nodenameA
----
+
您必須在升級至ONTAP 更新版本的更新版本的節點上執行此命令。

+
下列範例顯示節點的所有連接埠都已啟動：

+
[listing]
----
cluster1::> network port show -node node0
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node0
       e0M       Default      -                up       1500  auto/100
       e0a       Default      -                up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
5 entries were displayed.
----
. 將生命恢復到節點：
+
[source, cli]
----
network interface revert *
----
+
此命令會傳回從節點移轉的LIF。

+
[listing]
----
cluster1::> network interface revert *
8 entries were acted on.
----
. 驗證節點的資料生命是否已成功還原至節點、以及它們是否正常運作：
+
[source, cli]
----
network interface show
----
+
下列範例顯示節點所主控的所有資料生命期已成功還原至節點、而且其作業狀態為「up」（開機）：

+
[listing]
----
cluster1::> network interface show
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001      up/up    192.0.2.120/24     node0         e0a     true
            data002      up/up    192.0.2.121/24     node0         e0b     true
            data003      up/up    192.0.2.122/24     node0         e0b     true
            data004      up/up    192.0.2.123/24     node0         e0a     true
4 entries were displayed.
----
. 如果您先前已確定此節點為用戶端提供服務、請確認節點為其先前所服務的每個傳輸協定提供服務：
+
[source, cli]
----
system node run -node nodenameA -command uptime
----
+
更新期間、作業數會重設為零。

+
下列範例顯示更新的節點已恢復為其NFS和iSCSI用戶端提供服務：

+
[listing]
----
cluster1::> system node run -node node0 -command uptime
  3:15pm up  0 days, 0:16 129 NFS ops, 0 CIFS ops, 0 HTTP ops, 0 FCP ops, 2 iSCSI ops
----
. 如果合作夥伴節點先前已停用、請重新啟用自動恢復功能：
+
[source, cli]
----
storage failover modify -node nodenameB -auto-giveback true
----


您應該盡快更新節點的HA合作夥伴。如果您因為任何原因必須暫停更新程序、HA配對中的兩個節點都應該執行相同ONTAP 的版本。



== 更新HA配對中的合作夥伴節點

更新HA配對中的第一個節點之後、您可以在其上啟動接管、藉此更新其合作夥伴。第一個節點會在合作夥伴節點升級時、為合作夥伴的資料提供服務。

. 將權限等級設為「進階」、在提示繼續時輸入 * y* ：
+
[source, cli]
----
set -privilege advanced
----
+
進階提示 (`*>`）。

. 將新的 ONTAP 軟體映像設為預設映像：
+
[source, cli]
----
system image modify {-node nodenameB -iscurrent false} -isdefault true
----
+
系統映像修改命令會使用延伸查詢、將新ONTAP 的Imagesoftware映像（安裝為替代映像）變更為節點的預設映像。

. 監控更新進度：
+
[source, cli]
----
system node upgrade-revert show
----
. 確認新的 ONTAP 軟體映像已設為預設映像：
+
[source, cli]
----
system image show
----
+
在下列範例中、 `image2` 是 ONTAP 的新版本、設定為節點上的預設映像：

+
[listing]
----
cluster1::*> system image show
                 Is      Is                Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------- -------------------
node0
         image1  false   false   X.X.X     MM/DD/YYYY TIME
         image2  true    true    Y.Y.Y     MM/DD/YYYY TIME
node1
         image1  false   true    X.X.X     MM/DD/YYYY TIME
         image2  true    false   Y.Y.Y     MM/DD/YYYY TIME
4 entries were displayed.
----
. 如果合作夥伴節點已啟用自動恢復功能、請停用該功能：
+
[source, cli]
----
storage failover modify -node nodenameA -auto-giveback false
----
+
如果叢集是雙節點叢集、則會顯示一則訊息、警告您停用自動恢復功能、可在發生其他故障情況時、防止管理叢集服務上線。輸入 `y` 以繼續。

. 確認已停用合作夥伴節點的自動恢復功能：
+
[source, cli]
----
storage failover show -node nodenameA -fields auto-giveback
----
+
[listing]
----
cluster1::> storage failover show -node node0 -fields auto-giveback
node     auto-giveback
-------- -------------
node0    false
1 entry was displayed.
----
. 執行下列命令兩次、判斷要更新的節點目前是否正在服務任何用戶端：
+
[source, cli]
----
system node run -node nodenameB -command uptime
----
+
正常運作時間命令會顯示節點自上次開機以來、針對NFS、SMB、FC和iSCSI用戶端執行的作業總數。對於每個傳輸協定、您必須執行兩次命令、以判斷作業計數是否增加。如果數量不斷增加、則節點目前正在為該傳輸協定的用戶端提供服務。如果不增加、則節點目前不會為該傳輸協定的用戶端提供服務。

+
*附註*：您應該記下每個正在增加用戶端作業的傳輸協定、以便在節點更新後、確認用戶端流量已恢復。

+
以下範例顯示一個節點、其執行NFS、SMB、FC和iSCSI作業。不過、節點目前僅提供NFS和iSCSI用戶端服務。

+
[listing]
----
cluster1::> system node run -node node1 -command uptime
  2:58pm up  7 days, 19:16 800000260 NFS ops, 1017333 CIFS ops, 0 HTTP ops, 40395 FCP ops, 32810 iSCSI ops

cluster1::> system node run -node node1 -command uptime
  2:58pm up  7 days, 19:17 800001573 NFS ops, 1017333 CIFS ops, 0 HTTP ops, 40395 FCP ops, 32815 iSCSI ops
----
. 將所有資料生命從節點移轉至其他位置：
+
[source, cli]
----
network interface migrate-all -node nodenameB
----
. 確認您移轉的任何生命的狀態：
+
[source, cli]
----
network interface show
----
+
如需可用於驗證LIF狀態的參數相關資訊、請參閱網路介面show手冊頁。

+
以下範例顯示節點1的資料生命量已成功移轉。對於每個LIF、本範例中所包含的欄位可讓您驗證LIF的主節點和連接埠、LIF移轉的目前節點和連接埠、以及LIF的作業和管理狀態。

+
[listing]
----
cluster1::> network interface show -data-protocol nfs|cifs -role data -home-node node1 -fields home-node,curr-node,curr-port,home-port,status-admin,status-oper
vserver lif     home-node home-port curr-node curr-port status-oper status-admin
------- ------- --------- --------- --------- --------- ----------- ------------
vs0     data001 node1     e0a       node0     e0a       up          up
vs0     data002 node1     e0b       node0     e0b       up          up
vs0     data003 node1     e0b       node0     e0b       up          up
vs0     data004 node1     e0a       node0     e0a       up          up
4 entries were displayed.
----
. 啟動接管：
+
[source, cli]
----
storage failover takeover -ofnode nodenameB -option allow-version-mismatch
----
+
請勿指定-option Immediate參數、因為要將節點接管以開機至新的軟體映像時、需要正常接管。如果您未手動將l生命 從節點移轉至其他節點、則會自動移轉至節點的HA合作夥伴、以避免服務中斷。

+
畫面會顯示警告。  您必須輸入 `y` 以繼續。

+
接管的節點會開機至等待恢復狀態。

+

NOTE: 如果啟用 AutoSupport 、則會傳送一則 AutoSupport 訊息、指出節點已超出叢集仲裁。您可以忽略此通知並繼續更新。

. 確認接管成功：
+
[source, cli]
----
storage failover show
----
+
以下範例顯示接管作業成功。節點節點1處於等待恢復狀態、其合作夥伴處於接管狀態。

+
[listing]
----
cluster1::> storage failover show
                              Takeover
Node           Partner        Possible State Description
-------------- -------------- -------- -------------------------------------
node0          node1          -        In takeover
node1          node0          false    Waiting for giveback (HA mailboxes)
2 entries were displayed.
----
. 至少等待八分鐘、讓下列情況生效：
+
+
** 用戶端多重路徑（若已部署）會穩定下來。
** 用戶端會從接管期間發生的I/O暫停中恢復。
+
還原時間是用戶端專屬的、可能需要八分鐘以上的時間、視用戶端應用程式的特性而定。



. 將集合體傳回合作夥伴節點：
+
[source, cli]
----
storage failover giveback -ofnode nodenameB
----
+
恢復作業會先將根Aggregate傳回合作夥伴節點、然後在該節點完成開機之後、傳回非根Aggregate及任何設定為自動還原的LIF。新開機的節點會在傳回Aggregate後、立即開始從每個Aggregate向用戶端提供資料。

. 驗證是否已傳回所有的集合體：
+
[source, cli]
----
storage failover show-giveback
----
+
如果「歸還狀態」欄位指出沒有要歸還的集合體、則會傳回所有集合體。如果恢復被否決、命令會顯示恢復進度、以及哪些子系統已對恢復作業進行了否決。

. 如果未傳回任何集合體、請執行下列步驟：
+
.. 請檢閱「否決因應措施」、以判斷您是否想要處理「『直接』條件、或是要撤銷「否決」。
.. 如有必要、請解決錯誤訊息中所述的「『驗證』條件、確保所有已識別的作業都能正常終止。
.. 重新執行儲存容錯移轉恢復命令。
+
如果您決定覆寫「vito'」條件、請將-overre-etoes參數設為true。



. 至少等待八分鐘、讓下列情況生效：
+
** 用戶端多重路徑（若已部署）會穩定下來。
** 用戶端會從還原期間執行的I/O作業暫停中恢復。
+
還原時間是用戶端特有的、可能需要八分鐘以上的時間、視用戶端應用程式的特性而定。



. 驗證是否已成功完成節點的更新：
+
.. 進入進階權限等級：
+
[source, cli]
----
set -privilege advanced
----
.. 確認節點的更新狀態為完成：
+
[source, cli]
----
system node upgrade-revert show -node nodenameB
----
+
狀態應列示為「完成」。

+
如果狀態不完整、請從節點執行系統節點升級還原升級命令。如果命令未完成更新、請聯絡技術支援部門。

.. 返回管理權限層級：
+
[source, cli]
----
set -privilege admin
----


. 驗證節點的連接埠是否正常運作：
+
[source, cli]
----
network port show -node nodenameB
----
+
您必須在已升級ONTAP 至flex9.4的節點上執行此命令。

+
下列範例顯示節點的所有資料連接埠都已啟動：

+
[listing]
----
cluster1::> network port show -node node1
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
node1
       e0M       Default      -                up       1500  auto/100
       e0a       Default      -                up       1500  auto/1000
       e0b       Default      -                up       1500  auto/1000
       e1a       Cluster      Cluster          up       9000  auto/10000
       e1b       Cluster      Cluster          up       9000  auto/10000
5 entries were displayed.
----
. 將生命恢復到節點：
+
[source, cli]
----
network interface revert *
----
+
此命令會傳回從節點移轉的LIF。

+
[listing]
----
cluster1::> network interface revert *
8 entries were acted on.
----
. 驗證節點的資料生命是否已成功還原至節點、以及它們是否正常運作：
+
[source, cli]
----
network interface show
----
+
以下範例顯示、節點所主控的所有資料生命期都會成功還原回節點、而且其作業狀態為「up」（開機）：

+
[listing]
----
cluster1::> network interface show
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001      up/up    192.0.2.120/24     node1         e0a     true
            data002      up/up    192.0.2.121/24     node1         e0b     true
            data003      up/up    192.0.2.122/24     node1         e0b     true
            data004      up/up    192.0.2.123/24     node1         e0a     true
4 entries were displayed.
----
. 如果您先前已確定此節點為用戶端提供服務、請確認節點為其先前所服務的每個傳輸協定提供服務：
+
[source, cli]
----
system node run -node nodenameB -command uptime
----
+
更新期間、作業數會重設為零。

+
下列範例顯示更新的節點已恢復為其NFS和iSCSI用戶端提供服務：

+
[listing]
----
cluster1::> system node run -node node1 -command uptime
  3:15pm up  0 days, 0:16 129 NFS ops, 0 CIFS ops, 0 HTTP ops, 0 FCP ops, 2 iSCSI ops
----
. 如果這是要更新叢集中的最後一個節點、請觸發 AutoSupport 通知：
+
[source, cli]
----
autosupport invoke -node * -type all -message "Finishing_NDU"
----
+
本資訊通知包含更新前的系統狀態記錄。AutoSupport如果更新程序發生問題、它會儲存有用的疑難排解資訊。

+
如果叢集未設定為傳送AutoSupport 功能性訊息、則會在本機儲存通知複本。

. 確認新的 ONTAP 軟體正在 HA 配對的兩個節點上執行：
+
[source, cli]
----
set -privilege advanced
----
+
[source, cli]
----
system node image show
----
+
在下列範例中、image2是ONTAP 更新版的支援功能、是兩個節點上的預設版本：

+
[listing]
----
cluster1::*> system node image show
                 Is      Is                Install
Node     Image   Default Current Version    Date
-------- ------- ------- ------- --------- -------------------
node0
         image1  false   false   X.X.X     MM/DD/YYYY TIME
         image2  true    true    Y.Y.Y     MM/DD/YYYY TIME
node1
         image1  false   false   X.X.X     MM/DD/YYYY TIME
         image2  true    true    Y.Y.Y     MM/DD/YYYY TIME
4 entries were displayed.
----
. 如果合作夥伴節點先前已停用、請重新啟用自動恢復功能：
+
[source, cli]
----
storage failover modify -node nodenameA -auto-giveback true
----
. 使用驗證叢集是否已達到仲裁、以及是否正在執行服務 `cluster show` 和 `cluster ring show` （進階權限等級）命令。
+
在升級任何其他HA配對之前、您必須先執行此步驟。

. 返回管理權限層級：
+
[source, cli]
----
set -privilege admin
----
. 升級任何其他HA配對。

