---
permalink: upgrade/task_setting_the_desired_nt_acl_permissions_display_level_for_nfs_clients.html 
sidebar: sidebar 
keywords: ontap, upgrade, setting, set, desired, nt, acl, permissions, display, level, nfs, clients 
summary: 從ONTAP Se.8.3.0升級之後、將NT ACL權限顯示給NFS用戶端的預設處理方式已變更。您應該檢查設定、並視需要將其變更為您環境的所需設定。如果您要從ONTAP 還原8.3.1或更新版本升級、則此工作不適用。 
---
= 設定所需的NT ACL權限會顯示NFS用戶端的層級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP Se.8.3.0升級之後、將NT ACL權限顯示給NFS用戶端的預設處理方式已變更。您應該檢查設定、並視需要將其變更為您環境的所需設定。如果您要從ONTAP 還原8.3.1或更新版本升級、則此工作不適用。

在多重傳輸協定環境中、ONTAP 根據NT ACL授予任何使用者的存取權限、將NTFS安全型檔案和目錄的權限顯示給NFS用戶端。在S28.3.0中ONTAP 、ONTAP 根據預設、將權限根據NT ACL授予的最大存取權限顯示給NFS用戶端。升級後、預設設定會根據NT ACL所授與的最低存取權限而變更、以顯示權限。此變更適用於新的和現有的儲存虛擬機器（SVM）。

. 將權限層級設為進階： `set -privilege advanced`
. 檢查 NFS 用戶端的 NT ACL 權限顯示設定： `vserver nfs show -vserver vserver_name -fields ntacl-display-permissive-perms`
+
從8.3.0升級後、此新參數的值會停用、亦即ONTAP 會顯示最低權限。

. 如果您偏好顯示最大權限、請視需要個別變更每個 SVM 的設定： `vserver nfs modify -vserver vserver_name -ntacl-display-permissive-perms enabled`
. 驗證變更是否生效： `vserver nfs show -vserver vserver_name -fields ntacl-display-permissive-perms`
. 返回管理權限層級： `set -privilege admin`

