---
permalink: upgrade/when-to-upgrade.html 
sidebar: sidebar 
keywords: upgrade, ontap, when to upgrade, major upgrade, feature upgrade, minor upgrade, patch release, patch upgrade, service upgrade, service update, critical, patch, release dates, support levels, full support, limited, support, self-service support 
summary: 定期升級 ONTAP 。升級可讓您充分利用新增和增強的功能、並針對已知問題實作目前的修正。 
---
= 我應該何時升級 ONTAP ？
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該定期升級 ONTAP 軟體。升級 ONTAP 可讓您充分利用新增和增強的功能、並針對已知問題實作目前的修正。



== 重大 ONTAP 升級

主要的 ONTAP 升級或功能版本通常包括：

* 全新 ONTAP 功能
* 關鍵基礎架構變更、例如 NetApp WAFL 作業或 RAID 作業的基本變更
* 支援 NetApp 設計的新硬體系統
* 支援更換硬體元件、例如較新的網路介面卡或主機匯流排介面卡


全新 ONTAP 版本享有 3 年完整支援。NetApp 建議您在一般供應（ GA ）之後、執行最新版本一年、然後在完整支援期間內使用剩餘時間來規劃如何移轉至較新的 ONTAP 版本。



== ONTAP 修補程式升級

修補程式升級可及時修正關鍵錯誤、而這些錯誤無法等待下一次重大的 ONTAP 功能版本發佈。非關鍵修補程式升級應每 3 至 6 個月套用一次。應盡快套用重要的修補程式升級。

深入瞭解 link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["建議的最低修補程式層級"^] 適用於 ONTAP 版本。



== ONTAP 發行日期

從 ONTAP 9.8 版本開始、 NetApp 每個日曆年度提供 ONTAP 版本兩次。雖然計畫可能會有所變更、但其目的是在每個日曆年度的第二季和第四季推出新的 ONTAP 版本。使用此資訊規劃升級的時間範圍、以充分利用最新的 ONTAP 版本。

[cols="50,50"]
|===
| 版本 | 發行日期 


 a| 
9.16.1.
 a| 
2025 年 1 月



 a| 
9.15.1..
 a| 
2024 年 7 月



 a| 
9.14.1.
 a| 
2024 年 1 月



 a| 
9.13.1.12.9.12.9.
 a| 
2023 年 6 月



 a| 
9.12.1
 a| 
2023 年 2 月



 a| 
9.11.1.
 a| 
2022 年 7 月



 a| 
9.10.1
 a| 
2022 年 1 月



 a| 
9.9.1
 a| 
2021 年 6 月



 a| 

NOTE: 如果您執行的 ONTAP 版本早於 9.10.1 、則可能是「有限支援」或「自助服務支援」。請考慮升級至完全支援的版本。您可以在上驗證 ONTAP 版本的支援層級 https://mysupport.netapp.com/site/info/version-support#ontap_svst["NetApp 支援網站"^]。

|===


== ONTAP 支援層級

特定 ONTAP 版本可用的支援層級會因軟體發行時間而異。

[cols="20,10,10,10,10,10,10,10,10"]
|===
| 支援層級 3+| 完全支援 2+| 有限支援 3+| 自助服務支援 


 a| 
年
 a| 
1.
 a| 
2.
 a| 
3.
 a| 
4.
 a| 
5.
 a| 
6.
 a| 
7.
 a| 
8.



 a| 
存取線上文件
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的



 a| 
技術支援
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
 a| 
 a| 



 a| 
根本原因分析
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
 a| 
 a| 



 a| 
軟體下載
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
 a| 
 a| 



 a| 
服務更新（修補程式版本 [P-版本 ] ）
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
 a| 
 a| 
 a| 
 a| 



 a| 
有關弱點的警示
 a| 
是的
 a| 
是的
 a| 
是的
 a| 
 a| 
 a| 
 a| 
 a| 

|===
.相關資訊
* 瞭解 link:../release-notes/index.html["目前支援的 ONTAP 版本有哪些新功能"^]。
* 深入瞭解 link:https://kb.netapp.com/Support_Bulletins/Customer_Bulletins/SU2["建議的最低 ONTAP 版本"^]。
* 深入瞭解 link:https://mysupport.netapp.com/site/info/version-support["ONTAP 軟體版本支援"^]。
* 深入瞭解 link:https://mysupport.netapp.com/site/info/ontap-release-model["ONTAP 版本模式"^]。

