---
permalink: zero-trust/zero-trust-overview.html 
sidebar: sidebar 
keywords: tr-4829, zero trust, netapp, ontap, architect, data centric, fpolicy 
summary: 零信任傳統上是一種以網路為中心的方法、用於建構微核心和周邊（ MCAP ）、以控制區段閘道的方式來保護資料、服務、應用程式或資產 
---
= NetApp 與 Zero Trust
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
零信任傳統上是一種以網路為中心的方法、用於建構微核心和周邊（ MCAP ）、以控制區段閘道的方式來保護資料、服務、應用程式或資產。NetApp ONTAP 採用以資料為中心的 Zero Trust 方法、將儲存管理系統變成區段閘道、以保護及監控客戶資料的存取。特別是、 FPolicy Zero Trust 引擎和 FPolicy 合作夥伴生態系統成為控制中心、可深入瞭解正常和異常的資料存取模式、並識別內部威脅。


NOTE: 自 2024 年 7 月起、技術報告 _TR-4829 的內容： NetApp 與 Zero Trust ：啟用以資料為中心的 Zero Trust 模式 _ 、此模式先前以 PDF 格式發佈、已與 ONTAP 產品文件的其他部分整合。

資料是貴組織最重要的資產。根據 2022 年的資料外洩、內部威脅是 18% 資料外洩的原因 https://enterprise.verizon.com/resources/reports/dbir/["Verizon 資料外洩調查報告"^]。組織可以利用 NetApp ONTAP 資料管理軟體、針對資料部署領先業界的 Zero Trust 控管措施、提高警覺性。



== 什麼是 Zero Trust ？

Zero Trust 模式是由 Forrester Research 首次開發 https://www.brighttalk.com/webcast/10903/235239/how-to-enable-zero-trust-security-for-your-data-center["John Kindervag"^] 。它從內到外都能實現網路安全性、而非從外到外。 「內到外零信任」方法可識別微核心和周邊（ MCAP ）。MCAP 是資料、服務、應用程式和資產的內部定義、可透過一套完整的控制功能加以保護。安全外部邊界的概念已經過時。受信任且允許透過周邊環境成功驗證的實體、可能會使組織容易遭受攻擊。根據定義、內部人員已經在安全的邊界內。員工、承包商和合作夥伴都是內部人員、他們必須能夠在組織基礎架構中執行職務時、以適當的控管方式運作。

零信任被視為一項技術、可在 2019 年 9 月向 DoD 提供承諾 https://media.defense.gov/2019/Jul/12/2002156622/-1/-1/1/DOD-DIGITAL-MODERNIZATION-STRATEGY-2019.PDF["FY19-23 DoD 數位現代化策略"^]。它將 Zero Trust 定義為「一種網路安全策略、可在整個架構內嵌安全性、以阻止資料外洩。這種以資料為中心的安全模式消除了受信任或不受信任的網路、裝置、角色或程序的概念、並移轉到多屬性型信任層級、以在最低權限存取概念下啟用驗證和授權原則。實作零信任需要重新思考我們如何利用現有基礎架構、以更簡單、更有效率的方式設計安全性、同時實現不受阻礙的作業。」

2020 年 8 月、 NIST 發佈 https://csrc.nist.gov/publications/detail/sp/800-207/final["Special Pub 800-207 Zero Trust Architecture"^] （ ZTA ）。ZTA 著重於保護資源、而非網路區段、因為網路位置不再被視為資源安全狀態的主要元件。資源是資料和運算。ZTA 策略適用於企業網路架構設計師。ZTA 引進了一些來自 Forrester 原創概念的新術語。稱為原則決策點（ PDP ）和原則執行點（ PEP ）的保護機制、類似於 Forrester 分割閘道。ZTA 推出四種部署模式：

* 裝置代理程式或閘道型部署
* 以飛地為基礎的部署（有點類似於 Forrester MCAP ）
* 資源入口網站型部署
* 裝置應用程式沙箱


就本文件而言、我們使用 Forrester Research 的概念和術語、而非 NIST ZTA 。



== 安全資源

有關報告漏洞和事件、 NetApp 安全響應和客戶機密性的信息，請參閱 https://www.netapp.com/company/trust-center/security/["NetApp 安全入口網站"^]。
