---
permalink: performance-admin/adaptive-qos-policy-groups-task.html 
sidebar: sidebar 
keywords: use, adaptive, qos, policy, groups 
summary: 您可以使用調適性QoS原則群組、自動將處理量上限或樓層調整為Volume大小、並在磁碟區大小變更時、維持IOPS與TBs的比率。當您在大型部署中管理數百或數千個工作負載時、這是一項重大優勢。 
---
= 使用調適性QoS原則群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用_Adaptive QoS_原則群組、自動調整處理量上限或樓層與磁碟區大小、並在磁碟區大小變更時、維持IOPS與TBs的比率。當您在大型部署中管理數百或數千個工作負載時、這是一項重大優勢。

.開始之前
* 您必須執行 ONTAP 9.3 或更新版本。自ONTAP 功能性QoS原則群組開始提供、從功能性的9.3開始提供。
* 您必須是叢集管理員、才能建立原則群組。


.關於這項工作
儲存物件可以是調適性原則群組或非調適性原則群組的成員、但不能同時是兩者。儲存物件的SVM和原則必須相同。儲存物件必須處於線上狀態。

調適性QoS原則群組永遠不會共用：定義的處理量上限或樓層會個別套用至每個成員的工作負載。

處理量限制與儲存物件大小的比率、取決於下列欄位的互動：

* `expected-iops` 是每個配置的 TB|GB 的最低預期 IOPS 。
+
[NOTE]
====
 `expected-iops`僅在 AFF 平台上保證。 `expected-iops`只有當分層原則設定為「無」且雲端中沒有區塊時、 FabricPool 才保證適用。 `expected-iops`保證不屬於 SnapMirror 同步關係的磁碟區。

====
* `peak-iops` 是每個已分配或已使用的最大可能 IOPS TB|GB 。
* `expected-iops-allocation` 指定是將分配的空間（預設）還是已使用的空間用於預期的 IOPS 。
+
[NOTE]
====
`expected-iops-allocation` 可在 ONTAP 9.5 或更新版本中取得。不支援ONTAP 此功能。

====
* `peak-iops-allocation` 指定是使用分配的空間還是使用的空間（預設） `peak-iops`。
*  `absolute-min-iops` 為 IOPS 的絕對最小值。您可以將此欄位用於非常小的儲存物件。它會同時取代兩者 `peak-iops` 和/或 `expected-iops` 何時 `absolute-min-iops` 大於計算值 `expected-iops`。
+
例如、如果您設定 `expected-iops` 以 1 、 000 IOPS / TB 為單位、且磁碟區大小小於 1 GB `expected-iops` 將為分數 IOP 。計算所得的 `peak-iops` 將會是更小的一部分。您可以透過設定來避免這種情況 `absolute-min-iops` 至實際值。

* `block-size` 指定應用程式 I/O 區塊大小。預設值為 32K 。有效值為8K、16K、32K、64K、any。任何表示不會強制執行區塊大小。


有三個預設的調適性QoS原則群組可供使用、如下表所示。您可以將這些原則群組直接套用至磁碟區。

|===


| 預設原則群組 | 預期IOPS / TB | IOPS / TB尖峰 | 絕對最小IOPS 


 a| 
`extreme`
 a| 
6 、 144
 a| 
12288/3
 a| 
1000



 a| 
`performance`
 a| 
2 、 048
 a| 
4 、 096
 a| 
500



 a| 
`value`
 a| 
128/128
 a| 
512
 a| 
75

|===
如果儲存物件包含物件或其子物件屬於原則群組、則無法將其指派給原則群組。下表列出限制。

|===
| 如果您指派... | 然後您就無法指派... 


 a| 
SVM到原則群組
 a| 
SVM所包含的任何儲存物件至原則群組



 a| 
磁碟區至原則群組
 a| 
磁碟區包含SVM或任何子LUN至原則群組



 a| 
LUN至原則群組
 a| 
LUN包含磁碟區或SVM至原則群組



 a| 
檔案至原則群組
 a| 
檔案包含磁碟區或SVM至原則群組

|===
.步驟
. 建立可調適的QoS原則群組：
+
`qos adaptive-policy-group create -policy group _policy_group_ -vserver _SVM_ -expected-iops _number_of_iops_/TB|GB -peak-iops _number_of_iops_/TB|GB -expected-iops-allocation-space|used-space -peak-iops-allocation allocated-space|used-space -absolute-min-iops _number_of_iops_ -block-size 8K|16K|32K|64K|ANY`

+
如需完整的命令語法、請參閱手冊頁。

+
[NOTE]
====
`-expected-iops-allocation` 和 `-block-size` 可在 ONTAP 9.5 或更新版本中取得。上述選項不受ONTAP 支援於支援的版本不包括在內。

====
+
下列命令會建立調適性 QoS 原則群組 `adpg-app1` 與 `-expected-iops` 設為 300 IOPS / TB 、 `-peak-iops` 設為 1 、 000 IOPS / TB 、 `-peak-iops-allocation` 設定為 `used-space`和 `-absolute-min-iops` 設為 50 IOPS ：

+
[listing]
----
cluster1::> qos adaptive-policy-group create -policy group adpg-app1 -vserver vs2 -expected-iops 300iops/tb -peak-iops 1000iops/TB -peak-iops-allocation used-space -absolute-min-iops 50iops
----
. 將調適性QoS原則群組套用至磁碟區：
+
`volume create -vserver SVM -volume _volume_ -aggregate _aggregate_ -size _number_of_ TB|GB -qos-adaptive-policy-group _policy_group_`

+
如需完整的命令語法、請參閱手冊頁。

+
下列命令會套用調適性 QoS 原則群組 `adpg-app1` 至 Volume `app1`：

+
[listing]
----
cluster1::> volume create -vserver vs1 -volume app1 -aggregate aggr1 -size 2TB -qos-adaptive-policy-group adpg-app1
----
+
下列命令會套用預設的調適性 QoS 原則群組 `extreme` 到新的 Volume `app4` 和現有的 Volume `app5`。為原則群組定義的處理量上限會套用至磁碟區 `app4` 和 `app5` 個別：

+
[listing]
----
cluster1::> volume create -vserver vs4 -volume app4 -aggregate aggr4 -size 2TB -qos-adaptive-policy-group extreme
----
+
[listing]
----
cluster1::> volume modify -vserver vs5 -volume app5 -qos-adaptive-policy-group extreme
----

