---
permalink: performance-admin/identify-remaining-performance-capacity-task.html 
sidebar: sidebar 
keywords: identify, remaining, performance, capacity 
summary: 效能容量或預留空間可測量在資源上的工作負載效能開始受到延遲影響之前、您可以在節點或集合體上放置多少工作。瞭解叢集上可用的效能容量、有助於您配置及平衡工作負載。 
---
= 識別 ONTAP 中的剩餘效能容量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
效能容量（或稱「_E餘 量」）會測量在資源上的工作負載效能開始受到延遲影響之前、您可以在節點或集合體上放置多少工作。瞭解叢集上可用的效能容量、有助於您配置及平衡工作負載。

.您需要的產品
此工作需要進階權限層級命令。

.關於這項工作
您可以將下列值用於 `-object` 用於收集和顯示保留空間統計資料的選項：

* 對於 CPU 、 `resource_headroom_cpu`。
* 對於集合體、 `resource_headroom_aggr`。


您也可以使用System Manager和Active IQ Unified Manager 整套功能來完成這項工作。

.步驟
. 變更為進階權限層級：
+
`set -privilege advanced`

. 開始即時保留空間統計資料收集：
+
`statistics start –object resource_headroom_cpu|aggr`

+
如link:https://docs.netapp.com/us-en/ontap-cli/statistics-start.html["指令參考資料ONTAP"^]需詳細 `statistics start`資訊，請參閱。

. 顯示即時保留空間統計資訊：
+
`statistics show -object resource_headroom_cpu|aggr`

+
如link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["指令參考資料ONTAP"^]需詳細 `statistics show`資訊，請參閱。

. 返回管理權限：
+
`set -privilege admin`



.範例
下列範例顯示叢集節點的平均每小時保留空間統計資料。

您可以透過減去來計算節點的可用效能容量 `current_utilization` 來自的計數器 `optimal_point_utilization` 計數器。在此範例中、是的使用率容量 `CPU_sti2520-213` 為 -14% （ 72% 至 86% ）、表示過去一小時的 CPU 平均利用率過高。

您可以指定 `ewma_daily`、 `ewma_weekly`或 `ewma_monthly` 以獲得較長時間內的相同資訊平均值。

[listing]
----
sti2520-2131454963690::*> statistics show -object resource_headroom_cpu -raw -counter ewma_hourly
  (statistics show)

Object: resource_headroom_cpu
Instance: CPU_sti2520-213
Start-time: 2/9/2016 16:06:27
End-time: 2/9/2016 16:06:27
Scope: sti2520-213

    Counter                                                     Value
    -------------------------------- --------------------------------
    ewma_hourly                                                     -
                         current_ops                             4376
                     current_latency                            37719
                 current_utilization                               86
                   optimal_point_ops                             2573
               optimal_point_latency                             3589
           optimal_point_utilization                               72
     optimal_point_confidence_factor                                1

Object: resource_headroom_cpu
Instance: CPU_sti2520-214
Start-time: 2/9/2016 16:06:27
End-time: 2/9/2016 16:06:27
Scope: sti2520-214

    Counter                                                     Value
    -------------------------------- --------------------------------
    ewma_hourly                                                     -
                         current_ops                                0
                     current_latency                                0
                 current_utilization                                0
                   optimal_point_ops                                0
               optimal_point_latency                                0
           optimal_point_utilization                               71
     optimal_point_confidence_factor                                1
2 entries were displayed.
----