---
permalink: performance-admin/set-throughput-floor-qos-task.html 
sidebar: sidebar 
keywords: setting, throughput, floor, qos 
summary: QoS 最低標準或吞吐量下限保證工作負載的吞吐量不會低於最低 IOPS 或 MBps 值，或無論是否存在競爭工作負載，IOPS 和 MBps 值都不會低於最低值。設定吞吐量下限可確保關鍵工作負載獲得優先處理，並滿足最低效能要求。 
---
= 使用 ONTAP QoS 原則群組設定處理量下限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
QoS 最低標準或吞吐量下限保證工作負載的吞吐量不會低於最低 IOPS 或 MBps 值，或無論是否存在競爭工作負載，IOPS 和 MBps 值都不會低於最低值。設定吞吐量下限可確保關鍵工作負載獲得優先處理，並滿足最低效能要求。

您可以使用 `min-throughput`欄位來定義策略群組的儲存物件工作負載吞吐量下限（QoS Min）。您可以在建立或修改儲存物件時套用該策略群組。

.開始之前
* 您必須是叢集管理員、才能建立原則群組。


.關於這項工作
* 從 ONTAP 9.13.1 開始，您可以使用在 SVM 層級強制執行處理量層級xref:adaptive-policy-template-task.html[調適性原則群組範本]。您無法在具有 QoS 原則群組的 SVM 上設定調適性原則群組範本。
* 從 ONTAP 9.8 開始、您可以指定 IOPS 或 MBps 或 IOPS 和 MBps 的處理量下限。
* 從ONTAP S得9.4開始、您可以使用非共享的QoS原則群組來指定要個別套用定義的處理量層級至每個成員工作負載。這是處理量層的原則群組可套用至多個工作負載的唯一條件。
+
設定 `-is-shared=false` 適用於 `qos policy-group create` 指定非共用原則群組的命令。

* 如果節點或Aggregate上的效能容量（保留空間）不足、則工作負載的處理量可能會低於指定樓層。
* 受QoS限制的儲存物件必須由原則群組所屬的SVM所包含。多個原則群組可以屬於同一個SVM。
* 將原則群組套用至相同類型的儲存物件、是QoS最佳實務做法。
* 定義處理量層的原則群組無法套用至SVM。


.步驟
. 如所述、檢查節點或集合體上是否有足夠的效能容量 link:identify-remaining-performance-capacity-task.html["識別剩餘的效能容量"]。
. 建立原則群組：
+
[source, cli]
----
qos policy-group create -policy-group <policy_group> -vserver <SVM> -min-throughput <qos_target> -is-shared <true|false>
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-create.html["指令參考資料ONTAP"^]需詳細 `qos policy-group create`資訊，請參閱。

+
以下範例建立共享策略群組 `pg-vs2`，其最小吞吐量為 1,000 IOPS：

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs2 -vserver vs2 -min-throughput 1000iops -is-shared true
----
+
以下範例建立無吞吐量限制的非共用策略群組 `pg-vs4`：

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs4 -vserver vs4 -is-shared false
----
+
您可以使用 `qos policy-group modify` 指令來調整吞吐量下限。在 `qos policy-group modify` 中深入了解 link:https://docs.netapp.com/us-en/ontap-cli/qos-policy-group-modify.html["指令參考資料ONTAP"^]。

. 將原則群組套用至磁碟區或LUN：
+
[source, cli]
----
vserver create -vserver <SVM> -qos-policy-group <policy_group>
----
+
您可以使用  `vserver modify` 指令將不同的策略群組套用到儲存物件。

+
以下範例將策略群組  `pg-app2` 應用於磁碟區  `app2`：

+
[listing]
----
cluster1::> volume create -vserver vs2 -volume app2 -aggregate aggr1 -qos-policy-group pg-app2
----
. 監控原則群組效能：
+
[source, cli]
----
qos statistics performance show
----
+
[NOTE]
====
監控叢集的效能。請勿使用主機上的工具來監控效能。

====
+
以下範例顯示原則群組效能：

+
[listing]
----
cluster1::> qos statistics performance show
Policy Group           IOPS      Throughput   Latency
-------------------- -------- --------------- ----------
-total-                 12316       47.76MB/s  1264.00us
pg_app2                  7216       28.19MB/s   420.00us
_System-Best-Effort        62       13.36KB/s     4.13ms
_System-Background         30           0KB/s        0ms
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-performance-show.html["指令參考資料ONTAP"^]需詳細 `qos statistics performance show`資訊，請參閱。

. 監控工作負載效能：
+
[source, cli]
----
qos statistics workload performance show
----
+
[NOTE]
====
監控叢集的效能。請勿使用主機上的工具來監控效能。

====
+
以下範例展示了工作負載效能：

+
[listing]
----
cluster1::> qos statistics workload performance show
Workload          ID     IOPS      Throughput    Latency
--------------- ------ -------- ---------------- ----------
-total-              -    12320        47.84MB/s  1215.00us
app2-wid7967      7967     7219        28.20MB/s   319.00us
vs1-wid12279     12279     5026        19.63MB/s     2.52ms
_USERSPACE_APPS     14       55        10.92KB/s   236.00us
_Scan_Backgro..   5688       20            0KB/s        0ms
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-workload-performance-show.html["指令參考資料ONTAP"^]需詳細 `qos statistics workload performance show`資訊，請參閱。



您可以使用 `qos statistics workload latency show`命令來檢視 QoS 工作負載的詳細延遲統計資料。如link:https://docs.netapp.com/us-en/ontap-cli/qos-statistics-workload-latency-show.html["指令參考資料ONTAP"^]需詳細 `qos statistics workload latency show`資訊，請參閱。
