---
permalink: peering/configure-intercluster-lifs-use-ports-own-networks-task.html 
sidebar: sidebar 
keywords: configure, intercluster, LIFs  custom, ipspaces 
summary: 您可以在自訂IPspaces中設定叢集間LIF。如此可讓您隔離多租戶環境中的複寫流量。 
---
= 在自訂IPspaces中設定叢集間LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在自訂IPspaces中設定叢集間LIF。如此可讓您隔離多租戶環境中的複寫流量。

建立自訂IPspace時、系統會建立系統儲存虛擬機器（SVM）、做為該IPspace中系統物件的容器。您可以使用新的SVM作為新IPspace中任何叢集間LIF的容器。新的SVM名稱與自訂IPspace名稱相同。

.步驟
. 列出叢集中的連接埠：
+
「網路連接埠展示」

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例顯示「cluster01」中的網路連接埠：

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
       e0e       Default      Default          up     1500   auto/1000
       e0f       Default      Default          up     1500   auto/1000
----
. 在叢集上建立自訂IPspaces：
+
網路IPSpace建立-IPSpace _IPspacity_

+
以下範例建立自訂IPspace「IPspace-IC1（IPspace-IC1））：

+
[listing]
----
cluster01::> network ipspace create -ipspace ipspace-IC1
----
. 判斷哪些連接埠可用於叢集間通訊：
+
「網路介面show -field home-port、curr-port」

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例顯示連接埠「e0e」和「e0f」尚未指派生命權：

+
[listing]
----

cluster01::> network interface show -fields home-port,curr-port
vserver lif                  home-port curr-port
------- -------------------- --------- ---------
Cluster cluster01_clus1   e0a       e0a
Cluster cluster01_clus2   e0b       e0b
Cluster cluster02_clus1   e0a       e0a
Cluster cluster02_clus2   e0b       e0b
cluster01
        cluster_mgmt         e0c       e0c
cluster01
        cluster01-01_mgmt1   e0c       e0c
cluster01
        cluster01-02_mgmt1   e0c       e0c
----
. 從預設廣播網域移除可用的連接埠：
+
「網路連接埠廣播網域移除連接埠-broadcast網域預設連接埠」

+
連接埠一次不能位於多個廣播網域中。如需完整的命令語法、請參閱手冊頁。

+
以下範例會從預設廣播網域中移除連接埠「e0e（e0e）”和「e0f（e0f））：

+
[listing]
----
cluster01::> network port broadcast-domain remove-ports -broadcast-domain Default -ports
cluster01-01:e0e,cluster01-01:e0f,cluster01-02:e0e,cluster01-02:e0f
----
. 確認已從預設廣播網域移除連接埠：
+
「網路連接埠展示」

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例顯示、連接埠「e0e」和「e0f」已從預設廣播網域中移除：

+
[listing]
----
cluster01::> network port show
                                                       Speed (Mbps)
Node   Port    IPspace   Broadcast Domain Link   MTU    Admin/Oper
------ ------- --------- --------------- ----- ------- ------------
cluster01-01
       e0a     Cluster    Cluster          up    9000  auto/1000
       e0b     Cluster    Cluster          up    9000  auto/1000
       e0c     Default    Default          up    1500  auto/1000
       e0d     Default    Default          up    1500  auto/1000
       e0e     Default    -                up    1500  auto/1000
       e0f     Default    -                up    1500  auto/1000
       e0g     Default    Default          up    1500  auto/1000
cluster01-02
       e0a     Cluster    Cluster          up    9000  auto/1000
       e0b     Cluster    Cluster          up    9000  auto/1000
       e0c     Default    Default          up    1500  auto/1000
       e0d     Default    Default          up    1500  auto/1000
       e0e     Default    -                up    1500  auto/1000
       e0f     Default    -                up    1500  auto/1000
       e0g     Default    Default          up    1500  auto/1000
----
. 在自訂IPspace中建立廣播網域：
+
「網路連接埠廣播網域建立-IPSpace _IPspace_-broadcast網域_broadcast網域_-MTU _MTU -連接埠_ports_」

+
以下範例在IPspace「IPspace-IC1（IPspace-IC1-BD）中建立廣播網域：

+
[listing]
----
cluster01::> network port broadcast-domain create -ipspace ipspace-IC1 -broadcast-domain
ipspace-IC1-bd -mtu 1500 -ports cluster01-01:e0e,cluster01-01:e0f,
cluster01-02:e0e,cluster01-02:e0f
----
. 確認已建立廣播網域：
+
「網路連接埠廣播網域節目」

+
如需完整的命令語法、請參閱手冊頁。

+
[listing]
----
cluster01::> network port broadcast-domain show
IPspace Broadcast                                         Update
Name    Domain Name    MTU  Port List                     Status Details
------- ----------- ------  ----------------------------- --------------
Cluster Cluster       9000
                            cluster01-01:e0a              complete
                            cluster01-01:e0b              complete
                            cluster01-02:e0a              complete
                            cluster01-02:e0b              complete
Default Default       1500
                            cluster01-01:e0c              complete
                            cluster01-01:e0d              complete
                            cluster01-01:e0f              complete
                            cluster01-01:e0g              complete
                            cluster01-02:e0c              complete
                            cluster01-02:e0d              complete
                            cluster01-02:e0f              complete
                            cluster01-02:e0g              complete
ipspace-IC1
        ipspace-IC1-bd
                      1500
                            cluster01-01:e0e              complete
                            cluster01-01:e0f              complete
                            cluster01-02:e0e              complete
                            cluster01-02:e0f              complete
----
. 在系統SVM上建立叢集間LIF、並將它們指派給廣播網域：
+
|===
| 選項 | 說明 


 a| 
* ONTAP 在S69.6及更新版本中：*
 a| 
「網路介面create -vserver _system_Svm_-lif_lif_name_-service-policy default-intercluster -home-node_-home-port _port_-address_port_ip_-netask _netask_」



 a| 
* ONTAP 在《S19.5及更早版本》中：*
 a| 
「網路介面create -vserver _system_Svm_-lif_lif_name_-role inter-cluster -home-node_node_-home-port _port_-address_port_ip_-netask_netask_」

|===
+
LIF是在主連接埠指派給的廣播網域中建立。廣播網域具有預設的容錯移轉群組、其名稱與廣播網域相同。如需完整的命令語法、請參閱手冊頁。

+
以下範例會在廣播網域「IPspace-IC1-BD」中建立叢集間LIF「cluster01_icl01」和「cluster01_icl02」：

+
[listing]
----
cluster01::> network interface create -vserver ipspace-IC1 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0e -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver ipspace-IC1 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0e -address 192.168.1.202
-netmask 255.255.255.0
----
. 驗證是否已建立叢集間的LIF：
+
|===
| 選項 | 說明 


 a| 
* ONTAP 在S69.6及更新版本中：*
 a| 
「網路介面show -service-policy default-intercluster」



 a| 
* ONTAP 在《S19.5及更早版本》中：*
 a| 
「網路介面show -role intercluster」

|===
+
如需完整的命令語法、請參閱手冊頁。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
ipspace-IC1
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0e     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0f     true
----
. 驗證叢集間的LIF是否為備援：
+
|===
| 選項 | 說明 


 a| 
* ONTAP 在S69.6及更新版本中：*
 a| 
「網路介面show -service-policy default-intercluster -容 錯移轉」



 a| 
* ONTAP 在《S19.5及更早版本》中：*
 a| 
「網路介面show -role intercluster -容 錯移轉」

|===
+
如需完整的命令語法、請參閱手冊頁。

+
以下範例顯示SVM「e0e」連接埠上的叢集間LIF「cluster01_icl01」和「cluster01_icl02」容錯移轉至「e0f'port」：

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
ipspace-IC1
         cluster01_icl01 cluster01-01:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-01:e0e,
                                               cluster01-01:e0f
         cluster01_icl02 cluster01-02:e0e   local-only      intercluster01
                            Failover Targets:  cluster01-02:e0e,
                                               cluster01-02:e0f
----

