---
permalink: peering/configure-intercluster-lifs-share-data-ports-task.html 
sidebar: sidebar 
keywords: configure, intercluster, lifs, shared, data, ports 
summary: 您可以在與資料網路共用的連接埠上設定叢集間的LIF。如此可減少叢集間網路所需的連接埠數量。 
---
= 在共享的資料連接埠上設定叢集間LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在與資料網路共用的連接埠上設定叢集間的LIF。如此可減少叢集間網路所需的連接埠數量。

.步驟
. 列出叢集中的連接埠：
+
「網路連接埠展示」

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例顯示「cluster01」中的網路連接埠：

+
[listing]
----

cluster01::> network port show
                                                             Speed (Mbps)
Node   Port      IPspace      Broadcast Domain Link   MTU    Admin/Oper
------ --------- ------------ ---------------- ----- ------- ------------
cluster01-01
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
cluster01-02
       e0a       Cluster      Cluster          up     1500   auto/1000
       e0b       Cluster      Cluster          up     1500   auto/1000
       e0c       Default      Default          up     1500   auto/1000
       e0d       Default      Default          up     1500   auto/1000
----
. 在系統SVM上建立叢集間LIF：
+
|===
| 選項 | 說明 


 a| 
* ONTAP 在S69.6及更新版本中：*
 a| 
「網路介面create -vserver _system_Svm_-lif_lif_name_-service-policy default-intercluster -home-node_-home-port port -address _port_ip_-netask_km



 a| 
* ONTAP 在《S19.5及更早版本》中：*
 a| 
「網路介面create -vserver _system_Svm_-lif_lif_name_-role inter-cluster -home-node_node_-home-port _port_-address_port_ip_-netask_netask_」

|===
+
如需完整的命令語法、請參閱手冊頁。

+
以下範例建立叢集間的lifs「cluster01_icl01」和「cluster01_icl02」：

+
[listing]
----

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl01 -service-
policy default-intercluster -home-node cluster01-01 -home-port e0c -address 192.168.1.201
-netmask 255.255.255.0

cluster01::> network interface create -vserver cluster01 -lif cluster01_icl02 -service-
policy default-intercluster -home-node cluster01-02 -home-port e0c -address 192.168.1.202
-netmask 255.255.255.0
----
. 驗證是否已建立叢集間的LIF：
+
|===
| 選項 | 說明 


 a| 
* ONTAP 在S69.6及更新版本中：*
 a| 
「網路介面show -service-policy default-intercluster」



 a| 
* ONTAP 在《S19.5及更早版本》中：*
 a| 
「網路介面show -role intercluster」

|===
+
如需完整的命令語法、請參閱手冊頁。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
cluster01
            cluster01_icl01
                       up/up      192.168.1.201/24   cluster01-01  e0c     true
            cluster01_icl02
                       up/up      192.168.1.202/24   cluster01-02  e0c     true
----
. 驗證叢集間的LIF是否為備援：
+
|===
| 選項 | 說明 


 a| 
* ONTAP 在S69.6及更新版本中：*
 a| 
「網路介面show–service-policy default-intercluster -faulty」



 a| 
* ONTAP 在《S19.5及更早版本》中：*
 a| 
「網路介面show -role intercluster -容 錯移轉」

|===
+
如需完整的命令語法、請參閱手冊頁。

+
以下範例顯示、在「e0c」連接埠上的叢集間lifs「cluster01_icl01」和「cluster01_icl02」將會容錯移轉至「e0d」連接埠。

+
[listing]
----
cluster01::> network interface show -service-policy default-intercluster –failover
         Logical         Home                  Failover        Failover
Vserver  Interface       Node:Port             Policy          Group
-------- --------------- --------------------- --------------- --------
cluster01
         cluster01_icl01 cluster01-01:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-01:e0c,
                                              cluster01-01:e0d
         cluster01_icl02 cluster01-02:e0c   local-only      192.168.1.201/24
                            Failover Targets: cluster01-02:e0c,
                                              cluster01-02:e0d
----

