---
permalink: peering/prerequisites-cluster-peering-reference.html 
sidebar: sidebar 
keywords: prerequisites, cluster, peering. connectivity, requirements, port, firewall 
summary: 在設定叢集對等之前、您應該確認連線能力、連接埠、IP位址、子網路、防火牆、 並符合叢集命名需求。 
---
= 叢集對等關係的先決條件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在設定叢集對等之前、您應該確認連線能力、連接埠、IP位址、子網路、防火牆、 並符合叢集命名需求。



== 連線需求

本機叢集上的每個叢集間LIF都必須能夠與遠端叢集上的每個叢集間LIF通訊。

雖然不需要、但一般而言、設定用於同一子網路中叢集間LIF的IP位址較為簡單。IP位址可以與資料生命體位於同一個子網路中、也可以位於不同的子網路中。每個叢集所使用的子網路必須符合下列需求：

* 子網路必須屬於廣播網域、其中包含用於叢集間通訊的連接埠。
* 子網路必須有足夠的IP位址、才能為每個節點分配一個叢集間LIF。
+
例如、在四節點叢集中、用於叢集間通訊的子網路必須有四個可用的IP位址。每個節點都必須具有叢集間LIF、並在叢集間網路上具有IP位址。



叢集間LIF可以有一個IPv4位址或IPv6位址。

[NOTE]
====
藉由支援兩種傳輸協定同時出現在叢集間的LIF上、藉由使用支援功能、即可將對等網路從IPv4移轉至IPv6。ONTAP在早期版本中、整個叢集的所有叢集間關係都是IPV4或IPV6。這表示變更傳輸協定可能會造成中斷。

====


== 連接埠需求

您可以使用專用連接埠進行叢集間通訊、或共用資料網路所使用的連接埠。連接埠必須符合下列需求：

* 用於與指定遠端叢集通訊的所有連接埠必須位於相同的IPspace中。
+
您可以使用多個IPspace與多個叢集對等。只有在IPspace內才需要配對全網狀網路連線。

* 用於叢集間通訊的廣播網域必須包含每個節點至少兩個連接埠、以便叢集間通訊能夠從一個連接埠容錯移轉到另一個連接埠。
+
新增至廣播網域的連接埠可以是實體網路連接埠、VLAN或介面群組（ifgrps）。

* 所有連接埠都必須以纜線連接。
* 所有連接埠都必須處於正常狀態。
* 連接埠的MTU設定必須一致。




== 防火牆需求

防火牆和叢集間防火牆原則必須允許下列傳輸協定：

* ICMP服務
* TCP傳輸到連接埠10000、11104和11105上所有叢集間LIF的IP位址
* 叢集間LIF之間的雙向HTTPS
+
雖然使用CLI設定叢集對等功能時不需要HTTPS、但如果您使用System Manager來設定資料保護、稍後仍需要HTTPS。



預設的「叢集間」防火牆原則允許透過HTTPS傳輸協定和所有IP位址（0.00.0.0/0）進行存取。如有必要、您可以修改或取代原則。



== 叢集需求

叢集必須符合下列需求：

* 叢集不能與超過255個叢集處於對等關係中。

