---
permalink: san-admin/asa-iscsi-lif-fo-task.html 
sidebar: sidebar 
keywords: failover, iscsi, all san array, cli, system manager, auto-revert, revert network interface 
summary: 升級至 ONTAP 9.11.1 或更新版本後、您應該手動在 ONTAP 9.10.1 或更新版本中建立的所有 iSCSI 生命體上啟用自動 LIF 容錯移轉。 
---
= 啟用或停用自動 iSCSI LIF 容錯移轉
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
升級至 ONTAP 9.11.1 或更新版本後、您應該手動在 ONTAP 9.10.1 或更新版本中建立的所有 iSCSI 生命體上啟用自動 LIF 容錯移轉。

從 ONTAP 9.11.1 開始、您可以在 All Flash SAN Array 平台上、為 iSCSI 生命週期啟用自動 LIF 容錯移轉。如果發生儲存設備容錯移轉、 iSCSI LIF 會自動從其主節點或連接埠移轉至其 HA 合作夥伴節點或連接埠、然後在容錯移轉完成後再移回。  或者、如果 iSCSI LIF 連接埠變得不正常、 LIF 會自動移轉至目前主節點的健全連接埠、然後在連接埠再次正常運作後、再移回原始連接埠。  可讓在 iSCSI 上執行的 SAN 工作負載在發生容錯移轉後更快恢復 I/O 服務。

在 ONTAP 9.11.1 及更新版本中、如果符合下列其中一項條件、則預設會針對自動 LIF 容錯移轉啟用新建立的 iSCSI 生命體：

* SVM 上沒有 iSCSI 生命
* SVM 上的所有 iSCSI 生命都已啟用、可自動進行 LIF 容錯移轉




== 啟用自動 iSCSI LIF 容錯移轉

根據預設、在 ONTAP 9.10.1 及更早版本中建立的 iSCSI 生命權不會啟用自動 LIF 容錯移轉。  如果 SVM 上的 iSCSI 生命期未啟用自動 LIF 容錯移轉、則新建立的生命期也不會啟用自動 LIF 容錯移轉。  如果未啟用自動 LIF 容錯移轉、且發生容錯移轉事件、則 iSCSI 生命將不會移轉。

深入瞭解 link:../networking/configure_lifs_@cluster_administrators_only@_overview.html#lif-failover-and-giveback["LIF 容錯移轉與恢復"]。

.步驟
. 啟用 iSCSI LIF 的自動容錯移轉：
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <iscsi_lif> -failover-policy sfo-partner-only -auto-revert true
----
+
若要更新 SVM 上的所有 iSCSI 生命期、請使用 `-lif*` 而非 `lif`。





== 停用自動 iSCSI LIF 容錯移轉

如果您先前已在 ONTAP 9.10.1 或更早版本所建立的 iSCSI 生命負載上啟用自動 iSCSI LIF 容錯移轉、您可以選擇將其停用。

.步驟
. 停用 iSCSI LIF 的自動容錯移轉：
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <iscsi_lif> -failover-policy disabled -auto-revert false
----
+
若要更新 SVM 上的所有 iSCSI 生命期、請使用 `-lif*` 而非 `lif`。



.相關資訊
* link:../networking/create_a_lif.html["建立LIF"]
* 手動 link:../networking/migrate_a_lif.html["移轉 LIF"]
* 手動 link:../networking/revert_a_lif_to_its_home_port.html["將 LIF 還原至其主連接埠"]
* link:../networking/configure_failover_settings_on_a_lif.html["在LIF上設定容錯移轉設定"]

