---
permalink: san-admin/commands-manage-fc-adapters-reference.html 
sidebar: sidebar 
keywords: commands, managing, fc, adapters 
summary: 您可以使用FC命令來管理儲存控制器的FC目標介面卡、FC啟動器介面卡和內建FC介面卡。相同的命令也用於管理FC傳輸協定和FC-NVMe傳輸協定的FC介面卡。 
---
= 用於管理FC介面卡的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用FC命令來管理儲存控制器的FC目標介面卡、FC啟動器介面卡和內建FC介面卡。相同的命令也用於管理FC傳輸協定和FC-NVMe傳輸協定的FC介面卡。

FC啟動器介面卡命令只能在節點層級運作。您必須使用 `run -node _node_name_` 使用 FC 啟動器介面卡命令之前的命令。



== 用於管理FC目標介面卡的命令

[cols="2*"]
|===
| 如果您想要... | 使用此命令... 


 a| 
在節點上顯示FC介面卡資訊
 a| 
`network fcp adapter show`



 a| 
修改FC目標介面卡參數
 a| 
`network fcp adapter modify`



 a| 
顯示FC傳輸協定流量資訊
 a| 
`run -node _node_name_ sysstat -f`



 a| 
顯示FC傳輸協定已執行多久
 a| 
`run -node _node_name_ uptime`



 a| 
顯示介面卡組態與狀態
 a| 
`run -node _node_name_ sysconfig -v _adapter_`



 a| 
驗證安裝了哪些擴充卡、以及是否有任何組態錯誤
 a| 
`run -node _node_name_ sysconfig -ac`



 a| 
查看命令的手冊頁
 a| 
`man _command_name_`

|===


== 用於管理FC啟動器介面卡的命令

[cols="2*"]
|===
| 如果您想要... | 使用此命令... 


 a| 
顯示節點中所有啟動器及其介面卡的資訊
 a| 
`run -node _node_name_ storage show adapter`



 a| 
顯示介面卡組態與狀態
 a| 
`run -node _node_name_ sysconfig -v _adapter_`



 a| 
驗證安裝了哪些擴充卡、以及是否有任何組態錯誤
 a| 
`run -node _node_name_ sysconfig -ac`

|===


== 用於管理內建FC介面卡的命令

[cols="2*"]
|===
| 如果您想要... | 使用此命令... 


 a| 
顯示內建FC連接埠的狀態
 a| 
`run -node _node_name_ system hardware unified-connect show`

|===