---
permalink: san-admin/create-nvme-namespace-subsystem-task.html 
sidebar: sidebar 
keywords: create, nvme, namespace, subsystem 
summary: 對於使用NVMe傳輸協定的系統、您必須建立一或多個NVMe命名空間和子系統。然後、每個命名空間都可以對應至NVMe子系統、以便從主機系統存取資料。 
---
= 配置NVMe儲存設備
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的特定主機程序無法使用、您可以使用這些步驟來建立命名空間、並為任何NVMe支援的主機配置儲存設備。

Linux的命名空間似乎是SCSI磁碟裝置。

此程序會在現有的儲存VM上建立新的命名空間。您的儲存VM必須設定為NVMe、而且您的FC或TCP傳輸應該已經設定完成。

從ONTAP 供應儲存設備開始、預設會啟用QoS。您可以在資源配置程序期間或稍後停用QoS或選擇自訂QoS原則。

.步驟
[role="tabbed-block"]
====
.系統管理員
--
建立命名空間、以搭配ONTAP 使用NVMe傳輸協定與《支援不支援的系統管理程式》（9.7及更新版本）來提供儲存設備。

. 在系統管理員中、按一下*儲存設備> NVMe命名空間*、然後按一下*新增*。
+
如果您需要建立新的子系統、請按一下*「更多選項」*。

+
.. 如果您執行ONTAP 的是支援功能的9.8或更新版本、而您想要停用QoS或選擇自訂QoS原則、請按一下*更多選項*、然後在*儲存與最佳化*下選取*效能服務層級*。




. 將FC交換器分區至WWPN。每個啟動器使用一個區域、並在每個區域中包含所有目標連接埠。
. 在主機上探索新命名空間。
. 初始化命名空間並使用檔案系統進行格式化。
. 確認主機可以在命名空間上寫入和讀取資料。


--
.CLI
--
使用NVMe傳輸協定搭配ONTAP 使用支援功能的CLI建立命名空間、以提供儲存設備。

此程序會在已針對NVMe傳輸協定設定的現有儲存VM上建立NVMe命名空間和子系統、然後將命名空間對應至子系統、以便從主機系統存取資料。

如果您需要設定NVMe的儲存VM、請參閱 link:configure-svm-nvme-task.html["設定NVMe的SVM"]。

.步驟
. 確認SVM已設定為NVMe：
+
「vserver show -vserver _svm_name_-Fields allowed-protocols」

+
「NVMe」應顯示在「允許的傳輸協定」欄下。

. 建立NVMe命名空間：
+
「Vserver NVMe命名空間create -vserver _Svm_name_-path _path_-size _size__of_namest_-ostype_os_type_」

. 建立NVMe子系統：
+
「Vserver NVMe子系統會建立-vserver _svm_name_-subsystem _name_of_subsystem_-osttype _os_type_」

+
NVMe子系統名稱區分大小寫。必須包含1到96個字元。允許使用特殊字元。

. 驗證子系統是否已建立：
+
「Vserver NVMe子系統顯示-vserver _Svm_name_」

+
「NVMe」子系統應顯示在「Subsystem」（子系統）欄下。

. 從主機取得NQN。
. 將主機NQN新增至子系統：
+
「Vserver NVMe子系統主機add -vserver _Svm_name_-subsystem _subsystem_name_-host-nqn _Host_NQN_：subsystem._subsystem_name_」

. 將命名空間對應至子系統：
+
「Vserver NVMe子系統對應add -vserver _svm_name_-subsystem _subsystem_name_-path _path_」

+
命名空間只能對應至單一子系統。

. 確認命名空間已對應至子系統：
+
「Vserver NVMe命名空間show -vserver _svm_name_-instance」

+
子系統應列為「附加子系統」。



--
=關於NVMe子系統

NVMe子系統包含一個或多個控制器、一個或多個命名空間、一個或多個非揮發性記憶體（NVM）子系統連接埠（FC-NVMe或RDMA傳輸連接埠）、NVM儲存媒體、以及控制器與NVM儲存媒體之間的介面。對於控制器對應和管理、NVM子系統會對應ONTAP 至位於整個過程的Vserver。

NVMe over Fabric（NVMeoF）子系統是位於FreeBSD核心中的獨立核心物件。NVMeoF子系統與下列元件介面：

* SAN元件、例如BCOMKA、FCT和VDOM
* WAFL
* RAS元件、例如CM、ASUP和EMS


所有與NVMeoF子系統的介面均符合ONTAP 目前在介紹中所找到的定義和模式。

====