---
permalink: san-admin/create-flexclone-luns-snapshot-copy-volume-task.html 
sidebar: sidebar 
keywords: create, flexclone, luns, snapshot, copy, volume 
summary: 您可以在磁碟區中使用快照來建立 LUN 的 FlexClone 複本。LUN的FlexClone複本可讀取且可寫入。 
---
= 從磁碟區中的快照建立 FlexClone LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在磁碟區中使用快照來建立 LUN 的 FlexClone 複本。LUN的FlexClone複本可讀取且可寫入。

.您需要的產品
必須安裝FlexClone授權。本授權隨附於link:../system-admin/manage-licenses-concept.html#licenses-included-with-ontap-one["ONTAP One"]。

.關於這項工作
FlexClone LUN繼承父LUN的空間保留屬性。空間保留的FlexClone LUN所需空間與空間保留的父LUN相同。如果FlexClone LUN未保留空間、則磁碟區必須有足夠的空間來容納對實體複本所做的變更。

.步驟
. 確認LUN未對應或寫入。
. 建立包含 LUN 的磁碟區快照：
+
`volume snapshot create -vserver _vserver_name_ -volume _volume_name_ -snapshot _snapshot_name_`

+
您必須為要複製的 LUN 建立快照（備份快照）。

. 從快照建立 FlexClone LUN ：
+
`file clone create -vserver _vserver_name_ -volume _volume_name_ -source-path _source_path_ -snapshot-name _snapshot_name_ -destination-path _destination_path_`

+
如果您需要 FlexClone LUN 才能自動刪除、請加入 `-autodelete true`。如果您使用半厚資源配置在磁碟區中建立此FlexClone LUN、則必須啟用所有FlexClone LUN的自動刪除功能。

. 驗證FlexClone LUN是否正確：
+
`lun show -vserver _vserver_name_`

+
[listing]
----

Vserver Path                      State    Mapped    Type     Size
------- ----------------------    -------- --------- -------- -------
vs1     /vol/vol1/lun1_clone      online   unmapped windows   47.07MB
vs1     /vol/vol1/lun1_snap_clone online   unmapped windows   47.07MB
----

