---
permalink: san-admin/data-protection-methods-reference.html 
sidebar: sidebar 
keywords: data, protection, methods, san, environments, snapmirror business continuity, smbc, snapshot copy, mirror, update, flexclone luns, license required, snapvault, backups, snapdrive, windows, unix 
summary: 您可以製作資料複本來保護資料、以便在意外刪除、應用程式當機、資料毀損或災難發生時、能夠進行還原。根據您的資料保護和備份需求、ONTAP 支援各種方法來保護資料。 
---
= SAN環境中的資料保護方法總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以製作資料複本來保護資料、以便在意外刪除、應用程式當機、資料毀損或災難發生時、能夠進行還原。根據您的資料保護和備份需求、ONTAP 支援各種方法來保護資料。



== SnapMirror 主動同步

從通用供應ONTAP 功能的支援範圍而言、從提供零恢復時間目標（零RTO）或透明應用程式容錯移轉（TAF）開始、即可在SAN環境中自動容錯移轉業務關鍵應用程式。SnapMirror 主動同步需要在具有兩個 AFF 叢集或兩個 All Flash SAN Array （ ASA ）叢集的組態中安裝 ONTAP Mediator 1.2 。

link:../snapmirror-active-sync/index.html["SnapMirror 主動同步"^]



== Snapshot複本

可讓您手動或自動建立、排程及維護LUN的多個備份。Snapshot複本僅使用最少的額外磁碟區空間、而且不會產生效能成本。如果您的LUN資料遭到意外修改或刪除、則可從最新的Snapshot複本輕鬆快速地還原該資料。



== FlexClone LUN（需要FlexClone授權）

在作用中磁碟區或Snapshot複本中、提供其他LUN的時間點可寫入複本。可以獨立修改實體複本及其父複本、而不會影響彼此。



== （需要授權）SnapRestore

可讓您從整個磁碟區的Snapshot複本執行快速、節省空間的應要求資料還原。無需重新啟動儲存系統、您就可以使用SnapRestore 效益管理功能將LUN還原至先前保留的狀態。



== 資料保護鏡射複本（需要SnapMirror授權）

提供非同步災難恢復功能、方法是讓您定期在磁碟區上建立資料的Snapshot複本；將這些Snapshot複本透過區域或廣域網路複製到合作夥伴磁碟區、通常是在另一個叢集上；並保留這些Snapshot複本。如果來源磁碟區上的資料毀損或遺失、合作夥伴磁碟區上的鏡射複本可提供從上次Snapshot複本開始的快速可用度和資料還原。



== 還原備份（需要SnapMirror授權）SnapVault

提供儲存效率與長期保留備份的功能。利用此關係、您可以將所選的Volume Snapshot複本備份到目的地Volume、並保留備份。SnapVault

如果您執行磁帶備份和歸檔作業、您可以對SnapVault 已備份到該二線磁碟區的資料執行備份。



== 適用於Windows或UNIX（需取得授權）SnapDrive SnapDrive

直接從Windows或UNIX主機設定LUN存取權、管理LUN及管理儲存系統Snapshot複本。



== 原生磁帶備份與還原

支援大部分現有的磁帶機、ONTAP 以及磁帶廠商動態新增新裝置支援的方法。此外、支援遠端磁磁帶（RMT）傳輸協定、可將備份與還原功能備份至任何功能強大的系統。ONTAP

.相關資訊
http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30050["NetApp文件：SnapDrive 適用於UNIX的解決方案"^]

http://mysupport.netapp.com/documentation/productlibrary/index.html?productID=30049["NetApp文件：SnapDrive 適用於Windows（目前版本）"^]

link:../tape-backup/index.html["使用磁帶備份來保護資料"]
