---
permalink: san-admin/flexclone-luns-protect-your-data-concept.html 
sidebar: sidebar 
keywords: use, flexclone, luns, protect, your, data 
summary: FlexClone LUN 是作用中磁碟區或快照中另一個 LUN 的時間點可寫入複本。可獨立修改實體複本及其父複本、而不會影響彼此。 
---
= 使用 ONTAP FlexClone LUN 保護您的資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexClone LUN 是作用中磁碟區或快照中另一個 LUN 的時間點可寫入複本。可獨立修改實體複本及其父複本、而不會影響彼此。

您可以使用FlexClone LUN來建立LUN的多個讀寫複本。

.建立 FlexClone LUN 的理由
* 您需要建立LUN的暫用複本、以供測試之用。
* 您必須為其他使用者提供一份資料複本、而不讓他們存取正式作業資料。
* 您想要建立資料庫的複本、以便進行操作和投影作業、同時以未變更的形式保留原始資料。
* 您希望存取 LUN 資料的特定子集（磁碟區群組中的特定邏輯磁碟區或檔案系統，或檔案系統中的特定檔案或檔案集），並將其複製到原始 LUN，而無需還原原始 LUN 中的其餘資料。此操作適用於支援同時掛載 LUN 及其複本的作業系統。
* 您需要使用相同作業系統的多個SAN開機主機。


FlexClone LUN最初與其父LUN共享空間。根據預設、FlexClone LUN會繼承父LUN的空間保留屬性。例如、如果父LUN為非保留空間、則FlexClone LUN預設也不會保留空間。不過、您可以從父LUN（空間保留LUN）建立非空間保留的FlexClone LUN。

當您複製 LUN 時，會在背景中進行區塊共用，而且在區塊共用完成之前，您無法建立磁碟區快照。

您必須設定磁碟區、才能使用啟用 FlexClone LUN 自動刪除功能 `volume snapshot autodelete modify` 命令。否則、如果您想要自動刪除FlexClone LUN、但未將該磁碟區設定為FlexClone自動刪除、則不會刪除任何FlexClone LUN。

當您建立FlexClone LUN時、FlexClone LUN自動刪除功能預設為停用。您必須在每個FlexClone LUN上手動啟用、才能自動刪除FlexClone LUN。如果您使用半厚磁碟區資源配置、且想要此選項提供「最佳努力」寫入保證、則必須讓_all_ FlexClone LUN可供自動刪除。

[NOTE]
====
當您從快照建立 FlexClone LUN 時， LUN 會使用節省空間的背景程序，自動從快照分割，使 LUN 不會繼續依賴快照或佔用任何額外空間。如果此背景分割尚未完成，而且此快照會自動刪除，即使您已停用該 FlexClone LUN 的 FlexClone 自動刪除功能，該 FlexClone LUN 也會被刪除。背景分割完成後，即使刪除了 FlexClone LUN ，也不會刪除該快照。

====
.相關資訊
* link:../volumes/create-flexclone-file-flexclone-lun-task.html["建立 FlexClone LUN"]
* link:../volumes/configure-flexvol-delete-flexclone-files-luns-task.html["設定 FlexVol volume 以自動刪除 FlexClone LUN"]
* link:../volumes/prevent-flexclone-file-lun-automatic-deleted-task.html["防止自動刪除 FlexClone LUN"]

