---
permalink: san-admin/host-side-management-concept.html 
sidebar: sidebar 
keywords: understand, host-side, space, management 
summary: 在精簡配置的環境中，主機端空間管理可完成從主機檔案系統中釋放的儲存系統管理空間的程序。 
---
= SAN 主機端空間管理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在精簡配置的環境中，主機端空間管理可完成從主機檔案系統中釋放的儲存系統管理空間的程序。

主機檔案系統包含中繼資料、可追蹤哪些區塊可用於儲存新資料、哪些區塊包含不可覆寫的有效資料。此中繼資料儲存在 LUN 或命名空間內。在主機檔案系統中刪除檔案時、檔案系統中繼資料會更新、以將該檔案的區塊標示為可用空間。接著會重新計算檔案系統可用空間總計、以納入新釋出的區塊。對儲存系統而言、這些中繼資料更新與主機執行的任何其他寫入內容沒有任何不同。因此、儲存系統並未察覺有任何刪除作業。

這會在主機報告的可用空間量與基礎儲存系統報告的可用空間量之間產生差異。例如、假設您的儲存系統已將新配置的200-GB LUN指派給您的主機。主機和儲存系統都會報告200 GB的可用空間。然後、您的主機會寫入100 GB的資料。此時、主機和儲存系統都會報告100 GB的已用空間和100 GB的未使用空間。

然後從主機刪除50 GB的資料。此時、您的主機會回報50 GB的已用空間和150 GB的未使用空間。不過、您的儲存系統會回報100 GB的已用空間和100 GB的未使用空間。

主機端空間管理使用各種方法來協調主機與儲存系統之間的空間差異。



== 利用支援功能簡化主機管理SnapCenter

您可以使用SnapCenter 支援功能的支援軟體來簡化與iSCSI和FC儲存設備相關的部分管理和資料保護工作。適用於Windows和UNIX主機的選用管理套件。SnapCenter

您可以使用 SnapCenter 軟體，從儲存資源池輕鬆建立虛擬磁碟，這些資源池可分散於多個儲存系統，並可自動化儲存資源配置工作，並簡化從快照建立快照和複本的程序，使其與主機資料一致。

如需詳細資訊、請參閱NetApp產品文件 https://docs.netapp.com/us-en/snapcenter/index.html["SnapCenter"]。

.相關連結
link:enable-space-allocation-scsi-thin-provisioned-luns-task.html["啟用 SAN 通訊協定的 ONTAP 空間分配"]
