---
permalink: san-admin/manage-nvme-concept.html 
sidebar: sidebar 
keywords: manage, nvme, overview, license 
summary: 您可以使用非揮發性記憶體Express（NVMe）傳輸協定、在SAN環境中提供儲存設備。NVMe傳輸協定已針對固態儲存設備的效能最佳化。 
---
= NVMe總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用非揮發性記憶體Express（NVMe）傳輸協定、在SAN環境中提供儲存設備。NVMe傳輸協定已針對固態儲存設備的效能最佳化。

對於NVMe、儲存目標稱為命名空間。NVMe命名空間是一組非揮發性儲存設備、可格式化為邏輯區塊、並以標準區塊裝置呈現給主機。您可以建立命名空間和子系統、然後將命名空間對應至子系統、就像是將LUN配置及對應至FC和iSCSI的igroup一樣。

NVMe目標是透過使用FC交換器的標準FC基礎架構、或使用乙太網路交換器和主機端介面卡的標準TCP基礎架構、連線至網路。

NVMe支援會因ONTAP 您的版本的不相同而有所差異。請參閱 link:../nvme/support-limitations.html["NVMe支援與限制"] 以取得詳細資料。



== 什麼是NVMe

非揮發性記憶體Express（NVMe）傳輸協定是用於存取非揮發性儲存媒體的傳輸協定。

NVMe over Fabrics（NVMeoF）是NVMe規格定義的延伸、可透過PCIe以外的連線進行NVMe型通訊。此介面可讓外部儲存機箱連線至伺服器。

NVMe的設計可讓您有效率地存取以非揮發性記憶體建置的儲存裝置、從Flash技術到效能更高的持續記憶體技術、都能輕鬆存取。因此、它的限制與專為硬碟機設計的儲存傳輸協定並不相同。Flash和固態裝置（SSD）是一種非揮發性記憶體（NVM）。NVM是一種記憶體類型、可在停電期間保留內容。NVMe是存取該記憶體的方法。

NVMe的優點包括提升資料傳輸的速度、生產力、處理量和容量。具體特性包括：

* NVMe的設計可容納多達64、000個佇列。
+
每個佇列最多可有64000個並行命令。

* NVMe由多家硬體與軟體廠商支援
* NMVe採用Flash技術、可加快回應時間、提高生產力
* NVMe可針對傳送至SSD的每個「REquest」、要求多個資料要求。
+
NVMe解碼「資源要求」所需的時間較短、而且不需要在多執行緒程式中鎖定執行緒。

* NVMe支援的功能可防止CPU層級出現瓶頸、並可在系統擴充時提供大幅擴充性。




== 關於NVMe命名空間

NVMe命名空間是一組可格式化為邏輯區塊的非揮發性記憶體（NVM）。當儲存虛擬機器設定為使用NVMe傳輸協定、且相當於FC和iSCSI傳輸協定的LUN時、就會使用命名空間。

一個或多個命名空間已配置並連線至NVMe主機。每個命名空間都可支援不同的區塊大小。

NVMe傳輸協定可透過多個控制器存取命名空間。使用大多數作業系統都支援的NVMe驅動程式、固態磁碟機（SSD）命名空間會顯示為標準區塊裝置、可在不做任何修改的情況下部署檔案系統和應用程式。

命名空間ID（NSID）是控制器用來提供命名空間存取權的識別碼。設定主機或主機群組的NSID時、您也可以設定主機存取磁碟區的功能。邏輯區塊一次只能對應至單一主機群組、而指定的主機群組沒有任何重複的NSs。



== 關於NVMe子系統

NVMe子系統包含一或多個NVMe控制器、命名空間、NVM子系統連接埠、NVM儲存媒體、以及控制器與NVM儲存媒體之間的介面。建立NVMe命名空間時、預設不會對應至子系統。您也可以選擇將其對應為新的或現有的子系統。

.相關資訊
* link:../task_nvme_provision_suse_linux.html["為SUSE Linux配置NVMe儲存設備"]
* link:../create-nvme-namespace-subsystem-task.html["為其他主機提供NVMe儲存資源"]
* link:san-admin/map-nvme-namespace-subsystem-task.html["將NVMe命名空間對應至子系統"]

