---
permalink: san-admin/manage-nvme-concept.html 
sidebar: sidebar 
keywords: manage, nvme, overview, license 
summary: 支援從支援的是NVMe/FC、從支援的問題開始ONTAP 就是支援的問題。從支援NVMe 9.5開始ONTAP 需要授權。如果ONTAP NVMe是在更新至ONTAP 版本號9.5之後啟用、系統會給予90天的寬限期以取得授權。 
---
= NVMe總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP 推出支援NVM9.4的NVMe/FC開始、支援非MetroCluster AFF 的各種組態。所有非MetroCluster支援所有非MetroCluster完整SAN陣列（簡稱「支援」）組態、也ONTAP 支援從《支援使用支援的支援範本》（以《支援使用支援的支援範本》為開頭）AFF ASA

您可以使用非揮發性記憶體Express（NVMe）傳輸協定、在SAN環境中提供儲存設備。NVMe傳輸協定已針對固態儲存設備的效能最佳化。

對於NVMe、儲存目標稱為命名空間。NVMe命名空間是一組非揮發性儲存設備、可格式化為邏輯區塊、並以標準區塊裝置呈現給主機。您可以建立命名空間和子系統、然後將命名空間對應至子系統、就像是將LUN配置及對應至FC和iSCSI的igroup一樣。

NVMe目標是透過使用FC交換器的標準FC基礎架構、或使用乙太網路交換器和主機端介面卡的標準TCP基礎架構、連線至網路。

支援下列NVMe傳輸協定：

[cols="3*"]
|===


| 傳輸協定 | 開始於... | 允許者... 


| TCP | 零點9.10.1 ONTAP | 預設 


| FCP | 部分9.4 ONTAP | 預設 
|===


== NVMe授權需求

從支援NVMe 9.5開始ONTAP 需要授權。如果ONTAP NVMe是在更新至ONTAP 版本號9.5之後啟用、系統會給予90天的寬限期以取得授權。

您可以使用下列命令來啟用授權：

「系統授權新增-授權碼_nvm_less_key_」



== 什麼是NVMe

非揮發性記憶體Express（NVMe）傳輸協定是用於存取非揮發性儲存媒體的傳輸協定。

NVMe over Fabrics（NVMeoF）是NVMe規格定義的延伸、可透過PCIe以外的連線進行NVMe型通訊。此介面可讓外部儲存機箱連線至伺服器。

NVMe的設計可讓您有效率地存取以非揮發性記憶體建置的儲存裝置、從Flash技術到效能更高的持續記憶體技術、都能輕鬆存取。因此、它的限制與專為硬碟機設計的儲存傳輸協定並不相同。Flash和固態裝置（SSD）是一種非揮發性記憶體（NVM）。NVM是一種記憶體類型、可在停電期間保留內容。NVMe是存取該記憶體的方法。

NVMe的優點包括提升資料傳輸的速度、生產力、處理量和容量。具體特性包括：

* NVMe的設計可容納多達64、000個佇列。
+
每個佇列最多可有64000個並行命令。

* NVMe由多家硬體與軟體廠商支援
* NMVe採用Flash技術、可加快回應時間、提高生產力
* NVMe可針對傳送至SSD的每個「REquest」、要求多個資料要求。
+
NVMe解碼「資源要求」所需的時間較短、而且不需要在多執行緒程式中鎖定執行緒。

* NVMe支援的功能可防止CPU層級出現瓶頸、並可在系統擴充時提供大幅擴充性


.相關資訊
* link:../task_nvme_provision_suse_linux.html["為SUSE Linux配置NVMe儲存設備"]
* link:san-admin/configure-svm-nvme-task.html["設定NVMe的儲存VM"]

