---
permalink: san-admin/map-nvme-namespace-subsystem-task.html 
sidebar: sidebar 
keywords: map, nvme, namespace, subsystem 
summary: 使用NVMe時、您必須將命名空間對應至子系統。 
---
= 將NVMe命名空間對應至子系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將 NVMe 命名空間對應至子系統可讓您從主機存取資料。  您可以在佈建儲存設備時、將 NVMe 命名空間對應至子系統、也可以在儲存設備佈建之後進行。

從ONTAP 9.17.1 開始，如果您使用SnapMirror主動同步配置，則可以在將主機新增至 NVMe 子系統時，將 SVM 新增至主機作為近端虛擬伺服器。 NVMe子系統中命名空間的主動最佳化路徑僅從配置為近端虛擬伺服器的 SVM 發佈到主機。

從 ONTAP 9.14.1 開始、您可以優先分配特定主機的資源。根據預設、當主機新增至 NVMe 子系統時、會給予一般優先順序。您可以使用 ONTAP 命令列介面（ CLI ）手動將預設優先順序從一般變更為高。  指派高優先順序的主機會分配較大的 I/O 佇列數和佇列深度。


NOTE: 如果您想要將 ONTAP 9.13.1 或更早版本中新增至子系統的主機設為高優先順序、您可以 xref:../nvme/change-host-priority-nvme-task.html[變更主機優先順序]。

.開始之前
您的命名空間和子系統應該已經建立。如果您需要建立命名空間和子系統、請參閱 link:create-nvme-namespace-subsystem-task.html["配置NVMe儲存設備"]。



== 映射 NVMe 命名空間

.步驟
. 從主機取得NQN。
. 將主機NQN新增至子系統：
+
[source, cli]
----
vserver nvme subsystem host add -vserver <SVM_name> -subsystem <subsystem_name> -host-nqn <Host_NQN_:subsystem._subsystem_name>
----
+
如果您要將主機的預設優先順序從一般變更為高，請使用 `-priority high`選項。此選項從 ONTAP 9.14.1 開始提供。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-host-add.html["指令參考資料ONTAP"^]需詳細 `vserver nvme subsystem host add`資訊，請參閱。

+
如果您想要新增 SVM 作為 `proximal-vserver`在將主機新增至SnapMirror主動同步設定中的 NVMe 子系統時，您可以使用 `-proximal-vservers`選項。此選項從ONTAP 9.17.1 開始可用。您可以新增來源 SVM 或目標 SVM，或同時新增兩者。執行此命令的 SVM 是預設 SVM。

. 將命名空間對應至子系統：
+
[source, cli]
----
vserver nvme subsystem map add -vserver <SVM_name> -subsystem <subsystem_name> -path <path>
----
+
命名空間只能對應至單一子系統。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-subsystem-map-add.html["指令參考資料ONTAP"^]需詳細 `vserver nvme subsystem map add`資訊，請參閱。

. 確認命名空間已對應至子系統：
+
[source, cli]
----
vserver nvme namespace show -vserver <SVM_name> -instance
----
+
子系統應列示為 `Attached subsystem`。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-nvme-namespace-show.html["指令參考資料ONTAP"^]需詳細 `vserver nvme namespace show`資訊，請參閱。


