---
permalink: san-admin/move-san-lifs-task.html 
sidebar: sidebar 
keywords: move, san, lifs 
summary: 如果需要將某個節點離線、您可以移動 SAN LIF 以保留其組態資訊（例如 WWPN）、並避免重新分區交換器架構。 
---
= 移動 ONTAP SAN LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果需要將某個節點離線，您可以移動 SAN LIF 以保留其組態資訊，例如其 WWPN。移動 LIF 不需要重新劃分 FC 光纖通道網路區域，也不需要在叢集主機和目標介面之間建立新的 iSCSI 工作階段。您可以將 SAN LIF 移至叢集中的任何節點，但不能在儲存虛擬機器（SVM）之間移動。

您可以移動 LIF 以不中斷地執行下列作業：

* 以對存取 LUN 或命名空間資料的主機透明的方式，將叢集中的一個 HA 配對替換為升級後的 HA 配對
* 升級目標介面卡
* 將儲存虛擬機器（SVM）的資源從叢集中的一組節點移至叢集中的另一組節點


您無法使用  `network interface move` 命令移動 SAN LIF。要移動 SAN LIF，必須先將其離線，然後將其移至新的歸屬節點或連接埠，最後再將其重新上線。由於 SAN LIF 必須先離線才能移動，因此主機流量必須依賴主機多重路徑軟體來提供對 LUN 的不中斷存取，以避免 I/O 中斷。

.開始之前
如果LIF是連接埠集的成員、則LIF必須已從連接埠集移除、才能將LIF移至其他節點。

.關於這項工作
您要移動之LIF的目的地節點和實體連接埠必須位於相同的FC架構或乙太網路上。如果您將LIF移至尚未適當分區的其他Fabric、或將LIF移至iSCSI啟動器與目標之間沒有連線的乙太網路網路、則當您將LUN重新連線時、LUN將無法存取。

.步驟
. 檢視LIF的管理和作業狀態：
+
[source, cli]
----
network interface show -vserver <SVM_name>
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/network-interface-show.html["指令參考資料ONTAP"^]需詳細 `network interface show`資訊，請參閱。

. 將 LIF 的狀態變更為 `down` （離線）：
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin down
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["指令參考資料ONTAP"^]需詳細 `network interface modify`資訊，請參閱。

. 為LIF指派新的節點和連接埠：
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -home-node <node_name> -home-port <port_name>
----
. 將 LIF 的狀態變更為 `up` （線上）：
+
[source, cli]
----
network interface modify -vserver <SVM_name> -lif <LIF_name> -status-admin up
----
. 驗證您的變更：
+
[source, cli]
----
network interface show -vserver <SVM_name>
----

