---
permalink: san-admin/nvme-namespaces-considerations-concept.html 
sidebar: sidebar 
keywords: nvme, namespaces, considerations, provisioning 
summary: 若要在SAN環境中設定NVMe傳輸協定、您必須設定NVMe的SVM、建立命名空間和子系統、設定NVMe/FC LIF、然後將命名空間對應至子系統。 
---
= NVMe命名空間考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要在SAN環境中設定NVMe傳輸協定、您必須設定NVMe的SVM、建立命名空間和子系統、設定NVMe/FC LIF、然後將命名空間對應至子系統。使用NVMe命名空間時、您應該注意某些考量事項。

* 如果LUN中的資料遺失、則無法從命名空間還原資料、反之亦然。
* 命名空間的空間保證與所含磁碟區的空間保證相同。
* 從ONTAP 功能區9.6開始、命名空間支援512位元組區塊和96位元組區塊。
+
預設值為4096。只有當主機作業系統不支援4096位元組區塊時、才應使用512。

* 命名空間不支援下列項目：
+
** 重新命名
+
您無法重新命名命名命名空間。

** 跨Volume移動
** 跨Volume複本




從功能升級到功能升級到ONTAP 功能升級 xref:../nvme/resize-namespace-task.html[調整命名空間大小]。不支援ONTAP 在發行版不支援重新調整命名空間大小。



== 關於NVMe命名空間

NVMe命名空間是一組可格式化為邏輯區塊的非揮發性記憶體（NVM）。當儲存虛擬機器設定為使用NVMe傳輸協定、且相當於FC和iSCSI傳輸協定的LUN時、就會使用命名空間。

一個或多個命名空間已配置並連線至NVMe主機。每個命名空間都可支援不同的區塊大小。

NVMe傳輸協定可透過多個控制器存取命名空間。使用大多數作業系統都支援的NVMe驅動程式、固態磁碟機（SSD）命名空間會顯示為標準區塊裝置、可在不做任何修改的情況下部署檔案系統和應用程式。

命名空間ID（NSID）是控制器用來提供命名空間存取權的識別碼。設定主機或主機群組的NSID時、您也可以設定主機存取磁碟區的功能。邏輯區塊一次只能對應至單一主機群組、而指定的主機群組沒有任何重複的NSs。



=== NVMe命名空間的NVMe子系統資源配置

NVMe子系統包含一或多個NVMe控制器、命名空間、NVM子系統連接埠、NVM儲存媒體、以及控制器與NVM儲存媒體之間的介面。建立NVMe命名空間時、您可以選擇將NVMe子系統對應至命名空間、如下所示：

* *無（預設）*
+
沒有NVMe子系統對應至命名空間。

* *現有子系統*
+
您可以選取現有的NVMe子系統來對應至命名空間。NVMe子系統會根據主機OS和SVM欄位列出。當您將指標移到NVMe子系統名稱上時、會顯示有關子系統的更多詳細資料。

* *新子系統*
+
您可以建立新的NVMe子系統、並將其對應至命名空間。子系統是在主機作業系統和SVM上建立。



您可以提供下列詳細資料來配置子系統：

* * NVMe子系統名稱*
+
NVMe子系統名稱區分大小寫。必須包含1到96個字元、且允許使用特殊字元。

* *主機作業系統*
+
子系統所建立的主機作業系統類型。

* *主機NQN*
+
附加至控制器的主機NVMe資格名稱。此欄可以包含以逗號分隔的值、因為子系統可以連接一到多個主機。


