---
sidebar: sidebar 
permalink: san-admin/provision-storage.html 
keywords: netapp, ontap, san, provisioning, linux, servers, provision, storage, create lun, fc, iscsi, zone switches, scsi disk, iscsi 
summary: 建立LUN、以使用FC或iSCSI SAN傳輸協定為主機提供儲存設備。LUN在主機上顯示為磁碟。 
---
= 配置SAN儲存設備
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
此程序會在已設定FC或iSCSI傳輸協定的現有儲存VM上建立新的LUN。

如果您需要建立新的儲存VM並設定FC或iSCSI傳輸協定、請參閱 link:configure-svm-fc-task.html["設定SVM for FC"] 或 link:configure-svm-iscsi-task.html["設定SVM for iSCSI"]。

如果未啟用FC授權、則LIF和SVM似乎處於線上狀態、但作業狀態為停機。

LUN在您的主機上顯示為磁碟裝置。


NOTE: 在LUN建立期間、一律會啟用非對稱邏輯單元存取（ALUA）。您無法變更ALUA設定。

您必須為SVM中的所有FC LIF使用單一啟動器分區、才能裝載啟動器。

從ONTAP 供應儲存設備開始、預設會啟用QoS。您可以在資源配置程序期間或稍後時間停用 QoS 、或選擇自訂 QoS 原則。

.步驟
[role="tabbed-block"]
====
.系統管理員
--
使用FC或iSCSI傳輸協定搭配ONTAP 使用支援《支援系統管理程式》（9.7及更新版本）、建立LUN、為SAN主機提供儲存設備。

若要使用 System Manager Classic （ 9.7 及更早版本提供）完成此工作、請參閱 https://docs.netapp.com/us-en/ontap-system-manager-classic/iscsi-config-rhel/index.html["適用於Red Hat Enterprise Linux的iSCSI組態"^]

.步驟
. 安裝適當的 link:https://docs.netapp.com/us-en/ontap-sanhost/["SAN主機公用程式"] 在您的主機上。
. 在System Manager中、按一下* Storage > LUN*、然後按一下* Add*。
. 輸入建立LUN所需的資訊。
. 視ONTAP 您的版本而定、您可以按一下*更多選項*來執行下列任何一項。
+
[cols="80,20"]
|===


| 選項 | 從開始提供 


 a| 
** 將QoS原則指派給LUN、而非父Volume
+
*** *更多選項>儲存與最佳化*
*** 選擇*效能服務層級*。
*** 若要將QoS原則套用至個別LUN而非整個磁碟區、請選取*將這些效能限制強制套用至每個LUN*。
+
根據預設、效能限制會套用至Volume層級。




| 零點9.10.1 ONTAP 


 a| 
** 使用現有的啟動器群組建立新的啟動器群組
+
*** *更多選項>主機資訊*
*** 使用現有的啟動器群組*選取*新的啟動器群組。
+

NOTE: 包含其他 igroup 的 igroup 作業系統類型在建立之後無法變更。




| 部分9.9.1 ONTAP 


 a| 
** 將說明新增至igroup或主機啟動器
+
此說明可做為igroup或主機啟動器的別名。

+
*** *更多選項>主機資訊*



| 部分9.9.1 ONTAP 


 a| 
** 在現有磁碟區上建立LUN
+
根據預設、新的LUN會建立在新的Volume中。

+
*** *更多選項>新增LUN*
*** 選擇*組相關LUN*。



| 部分9.9.1 ONTAP 


 a| 
** 停用QoS或選擇自訂QoS原則
+
*** *更多選項>儲存與最佳化*
*** 選擇*效能服務層級*。
+

NOTE: 在 ONTAP 9.9.1 及更新版本中、如果您選取自訂 QoS 原則、也可以選取手動放置在指定的本機層。




| 部分9.8 ONTAP 
|===


. 對於FC、請根據WWPN對FC交換器進行分區。每個啟動器使用一個區域、並在每個區域中包含所有目標連接埠。
. 探索主機上的LUN。
+
對於 VMware vSphere 、請使用虛擬儲存主控台（ VSC ）來探索及初始化 LUN 。

. 初始化 LUN 並選擇性建立檔案系統。
. 確認主機可以在LUN上寫入和讀取資料。


--
.CLI
--
使用FC或iSCSI傳輸協定搭配ONTAP 使用CLI建立LUN、為SAN主機提供儲存空間。

. 確認您擁有 FC 或 iSCSI 的授權。
+
[source, cli]
----
system license show
----
+
[listing]
----

Package           Type    Description           Expiration
 ----------------- ------- --------------------- --------------------
 Base              site    Cluster Base License  -
 NFS               site    NFS License           -
 CIFS              site    CIFS License          -
 iSCSI             site    iSCSI License         -
 FCP               site    FCP License           -
----
. 如果您沒有 FC 或 iSCSI 授權、請使用 `license add` 命令。
+
[source, cli]
----
license add -license-code <your_license_code>
----
. 在SVM上啟用您的傳輸協定服務：
+
* iSCSI ： *

+
[source, cli]
----
vserver iscsi create -vserver <svm_name> -target-alias <svm_name>
----
+
* 代表 FC ： *

+
[source, cli]
----
vserver fcp create -vserver <svm_name> -status-admin up
----
. 在每個節點上為SVM建立兩個生命期：
+
[source, cli]
----
network interface create -vserver <svm_name> -lif <lif_name> -role data -data-protocol <iscsi|fc> -home-node <node_name> -home-port <port_name> -address <ip_address> -netmask <netmask>
----
+
NetApp為每個SVM服務資料的每個節點至少支援一個iSCSI或FC LIF。不過、備援需要每個節點兩個生命期。對於 iSCSI 、建議您在不同的乙太網路中、每個節點至少設定兩個生命期。

. 確認您的生命已建立、且其操作狀態為 `online`：
+
[source, cli]
----
network interface show -vserver <svm_name> <lif_name>
----
. 建立LUN：
+
[source, cli]
----
lun create -vserver <svm_name> -volume <volume_name> -lun <lun_name> -size <lun_size> -ostype linux -space-reserve <enabled|disabled>
----
+
您的LUN名稱不得超過255個字元、且不得包含空格。

+

NOTE: 在磁碟區中建立LUN時、NVFIL選項會自動啟用。

. 建立您的igroup：
+
[source, cli]
----
igroup create -vserver <svm_name> -igroup <igroup_name> -protocol <fcp|iscsi|mixed> -ostype linux -initiator <initiator_name>
----
. 將LUN對應至igroup：
+
[source, cli]
----
lun mapping create -vserver <svm_name> -volume <volume_name> -lun <lun_name> -igroup <igroup_name>
----
. 驗證LUN的設定是否正確：
+
[source, cli]
----
lun show -vserver <svm_name>
----
. （可選） link:create-port-sets-binding-igroups-task.html["建立連接埠集並繫結至igroup"]。
. 請遵循主機文件中的步驟、在特定主機上啟用區塊存取。
. 使用主機公用程式完成FC或iSCSI對應、並探索主機上的LUN。


--
====
.相關資訊
* link:index.html["SAN管理總覽"]
* https://docs.netapp.com/us-en/ontap-sanhost/index.html["SAN主機組態ONTAP"]
* link:../san-admin/manage-san-initiators-task.html["在System Manager中檢視及管理SAN啟動器群組"]
* http://www.netapp.com/us/media/tr-4017.pdf["NetApp技術報告4017：Fibre Channel SAN最佳實務做法"]

