---
permalink: san-admin/restore-single-lun-snapvault-backup-task.html 
sidebar: sidebar 
keywords: restore, single, lun, snapvault backup 
summary: 您可以將單一LUN還原至新位置或原始位置。您可以從 SnapVault 次要 Volume 中的任何快照還原。若要將LUN還原至原始位置、請先將其還原至新位置、然後再將其複製。 
---
= 從 ONTAP SnapVault 備份還原單一 LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將單一LUN還原至新位置或原始位置。您可以從 SnapVault 次要 Volume 中的任何快照還原。若要將LUN還原至原始位置、請先將其還原至新位置、然後再將其複製。

.開始之前
* 必須初始化 SnapVault 關係，且 SnapVault 次要 Volume 必須包含適當的快照才能還原。
* 包含SnapVault 不支援的二線磁碟區的儲存虛擬機器（SVM）必須具有一個或多個具備所需SAN傳輸協定的LIF、才能從用於存取LUN複本的主機存取。
* igroup必須已存在SnapVault 於SVM上。


.關於這項工作
此程序包括從 SnapVault 次要 Volume 中的快照建立讀寫磁碟區複本。您可以直接從實體複本使用LUN、也可以選擇將LUN內容複製回原始LUN位置。

實體複本中的LUN路徑和序號與原始LUN不同。不保留持續保留。

.步驟
. 驗證包含 SnapVault 備份的次要磁碟區。
+
[source, cli]
----
snapmirror show
----
+
[listing]
----
cluster::> snapmirror show

Source         Dest     Mirror  Relation  Total             Last
Path     Type  Path     State   Status    Progress  Healthy Updated
-------- ---- --------- ------- --------- --------- ------- -------
vserverA:srcvolA
         XDP  vserverB:dstvolB
                        Snapmirrored
                                Idle       -         true    -
----
. 識別您要從其中還原 LUN 的快照。
+
[source, cli]
----
volume snapshot show
----
+
[listing]
----
cluster::> volume snapshot show

Vserver  Volume  Snapshot               State Size   Total% Used%
-------- ------- ---------------------- ----- ------ ------ -----
vserverB
         dstvolB
                 snap2.2013-02-10_0010  valid  124KB     0%    0%
                 snap1.2013-02-10_0015 valid  112KB     0%    0%
                 snap2.2013-02-11_0010  valid  164KB     0%    0%
----
. 從所需的快照建立讀寫複本
+
[source, cli]
----
volume clone create -vserver <SVM_name> -flexclone <flexclone_name> -type <type> -parent-volume <parent_volume_name> -parent-snapshot <snapshot_name>
----
+
磁碟區複製是以SnapVault 相同的Aggregate建立、如同使用支援功能進行備份。集合體中必須有足夠的空間來儲存實體複本。

+
[listing]
----
cluster::> volume clone create -vserver vserverB
  -flexclone dstvolB_clone -type RW -parent-volume dstvolB
  -parent-snapshot daily.2013-02-10_0010
[Job 108] Job succeeded: Successful
----
. 列出磁碟區複製中的 LUN 。
+
[source, cli]
----
lun show -vserver <SVM_name> -volume <flexclone_volume_name>
----
+
[listing]
----
cluster::> lun show -vserver vserverB -volume dstvolB_clone

Vserver   Path                      State   Mapped   Type
--------- ------------------------  ------- -------- --------
vserverB  /vol/dstvolB_clone/lun_A  online  unmapped windows
vserverB  /vol/dstvolB_clone/lun_B  online  unmapped windows
vserverB  /vol/dstvolB_clone/lun_C  online  unmapped windows

3 entries were displayed.
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/lun-show.html["指令參考資料ONTAP"^]需詳細 `lun show`資訊，請參閱。

. 如果包含 SnapVault 備份的 SVM 上尚未存在所需主機的 igroup ，請建立 igroup 。
+
[source, cli]
----
igroup create -vserver <SVM_name> -igroup <igroup_name> -protocol <protocol> -ostype <os_type> -initiator <initiator_name>
----
+
此範例為使用iSCSI傳輸協定的Windows主機建立igroup：

+
[listing]
----
cluster::> igroup create -vserver vserverB -igroup temp_igroup
  -protocol iscsi -ostype windows
  -initiator iqn.1991-05.com.microsoft:hostA
----
. 將所需的 LUN 複本對應至 igroup 。
+
[source, cli]
----
lun mapping create -vserver <SVM_name> -path <lun_path> -igroup <igroup_name>
----
+
[listing]
----
cluster::> lun mapping create -vserver vserverB
  -path /vol/dstvolB_clone/lun_C -igroup temp_igroup
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/lun-mapping-create.html["指令參考資料ONTAP"^]需詳細 `lun mapping create`資訊，請參閱。

. 將主機連接至LUN、並視需要存取LUN的內容。
+
LUN為讀寫、可用於取代原始LUN。由於LUN序號不同、因此主機會將其解譯為與原始LUN不同的LUN。

. 使用主機上的複製程式、將LUN內容複製回原始LUN。


.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["SnapMirror 顯示"^]

