---
permalink: san-admin/restore-all-luns-volume-snapvault-backup-task.html 
sidebar: sidebar 
keywords: restore, luns, in a volume, snapvault, backup 
summary: 如果一個磁碟區中的一個或多個LUN需要從SnapVault 還原備份、您可以還原整個磁碟區。還原磁碟區會影響磁碟區中的所有LUN。 
---
= 從 ONTAP SnapVault 備份還原磁碟區中的所有 LUN
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果一個磁碟區中的一個或多個LUN需要從SnapVault 還原備份、您可以還原整個磁碟區。還原磁碟區會影響磁碟區中的所有LUN。

.開始之前
必須初始化 SnapVault 關係，且 SnapVault 次要 Volume 必須包含適當的快照才能還原。

.關於這項工作
還原整個磁碟區會將磁碟區恢復到建立快照時的狀態。如果在快照之後將 LUN 新增至磁碟區，則會在還原程序期間移除該 LUN 。

還原磁碟區之後、LUN會保留對應至還原前所對應的igroup。LUN 對應可能與快照時的對應不同。保留來自主機叢集之LUN的持續保留。

.步驟
. 停止磁碟區中所有LUN的I/O。
. 驗證包含 SnapVault 次要 Volume 的次要 Volume 。
+
[source, cli]
----
snapmirror show
----
+
[listing]
----
cluster::> snapmirror show

Source         Dest     Mirror  Relation  Total             Last
Path     Type  Path     State   Status    Progress  Healthy Updated
-------- ---- --------- ------- --------- --------- ------- -------
vserverA:srcvolA
         XDP  vserverB:dstvolB
                        Snapmirrored
                                Idle       -         true    -
----
. 識別您要還原的快照。
+
[source, cli]
----
volume snapshot show
----
+
[listing]
----
cluster::> volume snapshot show

Vserver  Volume  Snapshot               State Size   Total% Used%
-------- ------- ---------------------- ----- ------ ------ -----
vserverB
         dstvolB
                 snap2.2013-02-10_0010  valid  124KB     0%    0%
                 snap1.2013-02-10_0015 valid  112KB     0%    0%
                 snap2.2013-02-11_0010  valid  164KB     0%    0%
----
. 指定要使用的快照。
+
[source, cli]
----
snapmirror restore -destination-path <destination_path> -source-path <source_path> -source-snapshot <snapshot_name>
----
+
您指定的還原目的地是您要還原的原始Volume。

+
[listing]
----
cluster::> snapmirror restore -destination-path vserverA:srcvolA
  -source-path vserverB:dstvolB -source-snapshot daily.2013-02-10_0010

Warning: All data newer than Snapshot copy hourly.2013-02-11_1205 on
volume vserverA:src_volA will be deleted.
Do you want to continue? {y|n}: y
[Job 98] Job is queued: snapmirror restore from source
"vserverB:dstvolB" for the snapshot daily.2013-02-10_0010.
----
. 如果您要在主機叢集之間共用LUN、請從受影響的主機還原LUN上的持續保留。




== 從SnapVault 無法還原的備份還原磁碟區

在以下範例中，名為 LUN_D 的 LUN 會在建立快照後新增至磁碟區。從快照還原整個磁碟區之後，就不會再顯示 LUN_D 。

在中 `lun show` 命令輸出中、您可以在主磁碟區 srcvolA 中看到 LUN 、以及在 SnapVault 次要磁碟區 dstvolB 中看到這些 LUN 的唯讀複本。在不支援支援的情況下、沒有LUN_D的複本SnapVault 。

[listing]
----
cluster::> lun show
Vserver   Path                State   Mapped   Type          Size
--------- ------------------  ------- -------- --------      -------
vserverA  /vol/srcvolA/lun_A  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_B  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_C  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_D  online  mapped   windows  250.0GB
vserverB  /vol/dstvolB/lun_A  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_B  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_C  online  unmapped windows  300.0GB

7 entries were displayed.

cluster::>snapmirror restore -destination-path vserverA:srcvolA
  -source-path vserverB:dstvolB
  -source-snapshot daily.2013-02-10_0010

Warning: All data newer than snapshot hourly.2013-02-11_1205
on volume vserverA:src_volA will be deleted.
Do you want to continue? {y|n}: y
[Job 98] Job is queued: snapmirror restore from source
"vserverB:dstvolB" for the snapshot daily.2013-02-10_0010.

cluster::> lun show
Vserver   Path                State   Mapped   Type          Size
--------- ------------------  ------- -------- --------      -------
vserverA  /vol/srcvolA/lun_A  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_B  online  mapped   windows  300.0GB
vserverA  /vol/srcvolA/lun_C  online  mapped   windows  300.0GB
vserverB  /vol/dstvolB/lun_A  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_B  online  unmapped windows  300.0GB
vserverB  /vol/dstvolB/lun_C  online  unmapped windows  300.0GB

6 entries were displayed.
----
從SnapVault 還原次要Volume還原磁碟區之後、來源Volume不再包含LUN_D還原之後、您不需要重新對應來源磁碟區中的LUN、因為它們仍會對應。

.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-restore.html["SnapMirror還原"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["SnapMirror 顯示"^]

