---
permalink: san-admin/set-fractional-reserve-concept.html 
sidebar: sidebar 
keywords: considerations, setting, fractional, reserve 
summary: 部分保留（也稱為LUN覆寫保留）可讓您關閉FlexVol 對空間保留LUN和文件的覆寫保留（Overwrite Reserve）。這有助於將儲存使用率最大化、但如果您的環境因為空間不足而導致寫入作業失敗、則必須瞭解此組態所帶來的需求。 
---
= 設定部分保留的考量事項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
部分保留（也稱為_LUN覆寫保留區_）可讓您關閉FlexVol 針對空間保留LUN和位於一個實體磁碟區中檔案的覆寫保留。這有助於將儲存使用率最大化、但如果您的環境因為空間不足而導致寫入作業失敗、則必須瞭解此組態所帶來的需求。

百分比保留設定是以百分比表示、唯一有效的值是 `0` 和 `100` 百分比。「部分保留」設定是Volume的屬性。

將部分保留設為 `0` 提高儲存使用率。然而、如果磁碟區的可用空間不足、存取位於磁碟區中資料的應用程式可能會發生資料中斷、即使將磁碟區保證設定為 `volume`。不過、只要有適當的Volume組態和使用、就能將寫入失敗的機率降至最低。ONTAP 為將部分保留設為的磁碟區提供「盡力」寫入保證 `0` 當滿足下列所有要求時：

* 重複資料刪除功能未在使用中
* 壓縮未在使用中
* FlexClone子檔案未在使用中
* 所有FlexClone檔案和FlexClone LUN均已啟用自動刪除功能
+
這不是預設設定。您必須明確啟用自動刪除功能、無論是在建立時或是在建立FlexClone檔案或FlexClone LUN之後加以修改。

* 不使用ODX和FlexClone複本卸載
* Volume 擔保設為 `volume`
* 檔案或 LUN 空間保留為 `enabled`
* Volume Snapshot 保留已設定為 `0`
* Volume Snapshot 自動刪除的 `enabled`承諾層級為 `destroy`，的銷毀清單， `lun_clone,vol_clone,cifs_share,file_clone,sfsr`以及觸發程序 `volume`
+
此設定也可確保在必要時刪除FlexClone檔案和FlexClone LUN。



請注意，如果您的變更率很高，在極少數情況下，快照自動刪除可能會落後，導致磁碟區空間不足，即使使用上述所有必要的組態設定亦然。

此外，您也可以選擇使用 Volume 自動擴充功能來降低自動刪除磁碟區快照的可能性。如果啟用自動擴充功能、則必須監控相關聯Aggregate中的可用空間。如果 Aggregate 已滿，而磁碟區無法成長，則可能會在磁碟區的可用空間耗盡時刪除更多快照。

如果您無法滿足上述所有組態需求、而且需要確保磁碟區不會用盡空間、則必須將磁碟區的「部分保留」設定設為 `100`。這需要更多的可用空間、但保證資料修改作業即使在使用上述技術時仍能順利完成。

「部分保留」設定的預設值和允許值取決於Volume的保證：

[cols="3*"]
|===
| Volume保證 | 預設的部分保留 | 允許的值 


 a| 
Volume
 a| 
100
 a| 
0 、 100



 a| 
無
 a| 
0%
 a| 
0 、 100

|===