---
permalink: san-admin/volume-config-options-concept.html 
sidebar: sidebar 
keywords: san, volume, configuration, options 
summary: 您必須在包含LUN的磁碟區上設定各種選項。設定Volume選項的方式、決定了Volume中LUN可用的空間量。 
---
= SAN Volume組態選項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須在包含LUN的磁碟區上設定各種選項。設定Volume選項的方式、決定了Volume中LUN可用的空間量。



== 自動擴充

您可以啟用或停用自動擴充。如果啟用、則AutoGROW可ONTAP 自動將磁碟區大小增加至您預先決定的最大大小。包含的Aggregate中必須有可用空間、才能支援Volume的自動成長。因此、如果您啟用自動擴充、則必須監控內含Aggregate中的可用空間、並視需要新增更多空間。

無法觸發自動擴充以支援建立快照。如果您嘗試建立快照，但磁碟區空間不足，即使啟用自動擴充功能，快照建立也會失敗。

如果停用自動擴充、磁碟區的大小將維持不變。



== 自動縮小

您可以啟用或停用自動縮小。如果您啟用、當ONTAP 磁碟區的空間用量減少預先決定的臨界值時、自動縮小功能可讓流通量自動減少磁碟區的整體大小。如此可觸發磁碟區、自動釋放未使用的可用空間、進而提高儲存效率。



== Snapshot自動刪除

發生下列其中一種情況時， Snapshot 自動刪除會自動刪除快照：

* 磁碟區幾乎已滿。
* 快照保留空間即將滿。
* 覆寫保留空間已滿。


您可以設定快照自動刪除，將快照從最舊到最新，或從最新到最舊刪除。Snapshot 自動刪除不會刪除與複製磁碟區或 LUN 中快照連結的快照。

如果您的磁碟區需要額外空間，而且您已啟用自動擴充和快照自動刪除功能，則根據預設， ONTAP 會先觸發自動擴充來嘗試取得所需空間。如果沒有透過自動擴充取得足夠的空間，則會觸發快照自動刪除。



== Snapshot保留

Snapshot Reserve 定義磁碟區中保留給快照的空間量。分配給快照保留的空間不可用於任何其他用途。如果已使用分配給快照保留的所有空間，則快照會開始佔用磁碟區上的額外空間。
