---
permalink: smb-config/configure-ntfs-windows-security-tab-task.html 
sidebar: sidebar 
keywords: enable, file, access, user, group, share, configure, ntfs, permission, directories, directory, share, windows, client, configure ntfs file permissions in a share 
summary: 若要讓具有共用存取權的使用者或群組能夠存取檔案、您必須從Windows用戶端設定該共用區中檔案和目錄的NTFS檔案權限。 
---
= 設定共用區中的NTFS檔案權限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要讓具有共用存取權的使用者或群組能夠存取檔案、您必須從Windows用戶端設定該共用區中檔案和目錄的NTFS檔案權限。

執行此工作的系統管理員必須擁有足夠的NTFS權限、才能變更所選物件的權限。

link:../smb-admin/index.html["中小企業管理"] 而您的Windows文件則包含如何設定標準和進階NTFS權限的相關資訊。

.步驟
. 以系統管理員身分登入Windows用戶端。
. 從Windows檔案總管的*工具*功能表中、選取*對應網路磁碟機*。
. 填寫*對應網路磁碟機*方塊：
+
.. 選取*磁碟機*字母。
.. 在「*資料夾*」方塊中、輸入SMB伺服器名稱、其中包含您要套用權限的資料及共用名稱。
+
如果您的SMB伺服器名稱為SMB_server01、且您的共用名稱為「'DARE1'」、您可以輸入「\SMB_server01\share1」。

+
[NOTE]
====
您可以指定SMB伺服器的資料介面IP位址、而非SMB伺服器名稱。

====
.. 單擊*完成*。


+
您選取的磁碟機會掛載、並在Windows檔案總管視窗中顯示共用區中包含的檔案和資料夾、做好準備。

. 選取您要設定NTFS檔案權限的檔案或目錄。
. 以滑鼠右鍵按一下檔案或目錄、然後選取*內容*。
. 選取*安全性*索引標籤。
+
「安全性」索引標籤會顯示已設定NTFS權限的使用者和群組清單。「物件的權限」方塊會顯示所選使用者或群組有效的「允許」和「拒絕」權限清單。

. 按一下 * 編輯 * 。
+
「物件的權限」方塊隨即開啟。

. 執行所需的動作：
+
|===
| 如果你想… | 請執行下列動作... 


 a| 
設定新使用者或群組的標準NTFS權限
 a| 
.. 按一下「 * 新增 * 」。
+
「選取使用者、電腦、服務帳戶或群組」視窗即會開啟。

.. 在「*輸入要選取的物件名稱*」方塊中、輸入您要新增NTFS權限的使用者或群組名稱。
.. 按一下「*確定*」。




 a| 
變更或移除使用者或群組的標準NTFS權限
 a| 
在*群組或使用者名稱*方塊中、選取您要變更或移除的使用者或群組。

|===
. 執行所需的動作：
+
|===
| 如果您想要... | 請執行下列動作 


 a| 
為新的或現有的使用者或群組設定標準NTFS權限
 a| 
在「*物件權限>*」方塊中、針對您要允許或不允許選取的使用者或群組存取的類型、選取*允許*或*拒絕*方塊。



 a| 
移除使用者或群組
 a| 
按一下「*移除*」。

|===
+
[NOTE]
====
如果部分或全部的標準權限方塊無法選取、這是因為權限是從父物件繼承而來。*特殊權限*方塊無法選取。如果選取此選項、表示已為選取的使用者或群組設定一或多個精細的進階權限。

====
. 在您完成新增、移除或編輯該物件的NTFS權限之後、請按一下「*確定*」。

