---
permalink: smb-config/create-local-groups-task.html 
sidebar: sidebar 
keywords: create, local, group, authorize, authorizing, access, data, associate, svm, smb, connection, assign, privilege, define, right, capabilities, capability, member, create local groups 
summary: 您可以建立本機群組、以便透過SMB連線授權存取與SVM相關的資料。您也可以指派權限來定義群組成員擁有的使用者權限或功能。 
---
= 建立本機群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立本機群組、以便透過SMB連線授權存取與SVM相關的資料。您也可以指派權限來定義群組成員擁有的使用者權限或功能。

.關於這項工作
建立SVM時、預設會啟用本機群組功能。

當您建立本機群組時、必須為群組指定名稱、而且必須指定要與群組建立關聯的SVM。您可以使用或不使用本機網域名稱來指定群組名稱、也可以選擇性地指定本機群組的說明。您無法將本機群組新增至其他本機群組。

。 `vserver cifs users-and-groups local-group` 手冊頁包含有關可選參數和命名要求的詳細信息。

.步驟
. 建立本機群組： `vserver cifs users-and-groups local-group create -vserver vserver_name -group-name group_name`
+
下列選用參數可能很有用：

+
** `-description`
+
本機群組的說明。



. 確認已成功建立群組： `vserver cifs users-and-groups local-group show -vserver vserver_name`


.範例
下列範例建立與SVM VS1相關的本機群組「'Smb_server01\Engineering」：

[listing]
----
cluster1::> vserver cifs users-and-groups local-group create -vserver vs1.example.com -group-name SMB_SERVER01\engineering

cluster1::> vserver cifs users-and-groups local-group show -vserver vs1.example.com
Vserver          Group Name                   Description
---------------- ---------------------------- ----------------------------
vs1.example.com  BUILTIN\Administrators       Built-in Administrators group
vs1.example.com  BUILTIN\Backup Operators     Backup Operators group
vs1.example.com  BUILTIN\Power Users          Restricted administrative privileges
vs1.example.com  BUILTIN\Users                All users
vs1.example.com  SMB_SERVER01\engineering
vs1.example.com  SMB_SERVER01\sales
----
.完成後
您必須將成員新增至新群組。
