---
permalink: smb-config/create-lif-task.html 
sidebar: sidebar 
keywords: lif, ip, address, associate, physical, logical, port, component, failure, migrate, communicate, network, create a lif 
summary: LIF是與實體或邏輯連接埠相關聯的IP位址。如果元件發生故障、LIF可能會容錯移轉至不同的實體連接埠、或移轉至不同的實體連接埠、進而繼續與網路通訊。 
---
= 建立LIF
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
LIF是與實體或邏輯連接埠相關聯的IP位址。如果元件發生故障、LIF可能會容錯移轉至不同的實體連接埠、或移轉至不同的實體連接埠、進而繼續與網路通訊。

.開始之前
* 基礎實體或邏輯網路連接埠必須設定為管理 `up`狀態。如link:https://docs.netapp.com/us-en/ontap-cli/up.html["指令參考資料ONTAP"^]需詳細 `up`資訊，請參閱。
* 如果您打算使用子網路名稱來配置LIF的IP位址和網路遮罩值、則該子網路必須已經存在。
+
子網路包含屬於同一第3層子網路的IP位址集區。它們是使用建立的 `network subnet create` 命令。

* 指定LIF處理之流量類型的機制已變更。對於僅適用於更新版本的版本、LIF會使用角色來指定其處理的流量類型。ONTAP從ONTAP Sf6開始、l生命 就會使用服務原則來指定處理的流量類型。


.關於這項工作
* 您可以在同一個網路連接埠上同時建立IPV4和IPv6 LIF。
* 如果叢集中有大量的生命、您可以使用來驗證叢集上支援的 LIF 容量 `network interface capacity show` 命令和 LIF 容量、可透過使用在每個節點上支援 `network interface capacity details show` 命令（進階權限層級）。
* 從ONTAP NetApp 9.7開始、如果相同子網路中的SVM已存在其他LIF、您就不需要指定LIF的主連接埠。在相同的廣播網域中、系統會自動在指定的主節點上選擇隨機連接埠、如同在同一個子網路中設定的其他LIF。ONTAP


.步驟
. 建立LIF：
+
`network interface create -vserver _vserver_name_ -lif _lif_name_ -role data -data-protocol cifs -home-node _node_name_ -home-port _port_name_ {-address _IP_address_ -netmask IP_address | -subnet-name _subnet_name_} -firewall-policy data -auto-revert {true|false}`

+
|===


| *《*》第9.5版及更早版本* ONTAP 


 a| 
`network interface create -vserver _vserver_name_ -lif _lif_name_ -role data -data-protocol cifs -home-node _node_name_ -home-port _port_name_ {-address _IP_address_ -netmask _IP_address_ | -subnet-name _subnet_name_} -firewall-policy data -auto-revert {true|false}`

|===
+
|===


| *版本9.6及更新版本* ONTAP 


 a| 
`network interface create -vserver _vserver_name_ -lif _lif_name_ -service-policy _service_policy_name_ -home-node _node_name_ -home-port _port_name_ {-address _IP_address_ -netmask _IP_address_ | -subnet-name _subnet_name_} -firewall-policy data -auto-revert {true|false}`

|===
+
** 。 `-role` 使用服務原則建立 LIF 時不需要參數（從 ONTAP 9.6 開始）。
** 。 `-data-protocol` 使用服務原則建立 LIF 時不需要參數（從 ONTAP 9.6 開始）。使用 ONTAP 9.5 或更早版本時 `-data-protocol` 必須在建立 LIF 時指定參數、而且必須在稍後修改、才能銷毀及重新建立資料 LIF 。
** `-home-node` 是 LIF 在返回時返回的節點 `network interface revert` 命令會在LIF上執行。
+
您也可以指定 LIF 是否應該使用自動還原至主節點和主連接埠 `-auto-revert` 選項。

** `-home-port` 是 LIF 在時傳回的實體或邏輯連接埠 `network interface revert` 命令會在LIF上執行。
** 您可以使用指定 IP 位址 `-address` 和 `-netmask` 或是您可以使用從子網路進行分配 `-subnet_name` 選項。
** 使用子網路提供IP位址和網路遮罩時、如果子網路是使用閘道定義、則使用該子網路建立LIF時、會自動將通往該閘道的預設路由新增至SVM。
** 如果您手動指派IP位址（不使用子網路）、則在不同IP子網路上有用戶端或網域控制器時、可能需要設定通往閘道的預設路由。在中深入瞭解 `network route create`並建立 SVM 內的靜態路由link:https://docs.netapp.com/us-en/ontap-cli/network-route-create.html["指令參考資料ONTAP"^]。
** 適用於 `-firewall-policy` 選項、請使用相同的預設值 `data` 成為 LIF 角色。
+
如果需要、您可以稍後建立並新增自訂防火牆原則。

+

NOTE: 從ONTAP S振 分9.10.1開始、防火牆原則已過時、並完全由LIF服務原則取代。如需詳細資訊、請參閱 link:../networking/configure_firewall_policies_for_lifs.html["設定lifs的防火牆原則"]。

** `-auto-revert` 可讓您指定資料 LIF 是否在啟動、管理資料庫狀態變更或建立網路連線等情況下自動還原至其主節點。預設設定為 `false`但您可以將其設定為 `false` 視環境中的網路管理原則而定。


. 確認LIF已成功建立：
+
`network interface show`

. 確認已設定的IP位址可連線：
+
|===


| 若要驗證... | 使用... 


 a| 
IPV4位址
 a| 
`network ping`



 a| 
IPv6位址
 a| 
`network ping6`

|===


.範例
下列命令會建立 LIF 並使用指定 IP 位址和網路遮罩值 `-address` 和 `-netmask` 參數：

[listing]
----
network interface create -vserver vs1.example.com -lif datalif1 -role data -data-protocol cifs -home-node node-4 -home-port e1c -address 192.0.2.145 -netmask 255.255.255.0 -firewall-policy data -auto-revert true
----
下列命令會建立LIF、並從指定的子網路（名為client1_sub）指派IP位址和網路遮罩值：

[listing]
----
network interface create -vserver vs3.example.com -lif datalif3 -role data -data-protocol cifs -home-node node-3 -home-port e1c -subnet-name client1_sub -firewall-policy data -auto-revert true
----
下列命令顯示叢集1中的所有LIF。資料生命週期1和資料傳輸3均設定為使用IPv4位址、而資料傳輸4則設定為使用IPv6位址：

[listing]
----
network interface show

            Logical    Status     Network          Current      Current Is
Vserver     Interface  Admin/Oper Address/Mask     Node         Port    Home
----------- ---------- ---------- ---------------- ------------ ------- ----
cluster-1
            cluster_mgmt up/up    192.0.2.3/24     node-1       e1a     true
node-1
            clus1        up/up    192.0.2.12/24    node-1       e0a     true
            clus2        up/up    192.0.2.13/24    node-1       e0b     true
            mgmt1        up/up    192.0.2.68/24    node-1       e1a     true
node-2
            clus1        up/up    192.0.2.14/24    node-2       e0a     true
            clus2        up/up    192.0.2.15/24    node-2       e0b     true
            mgmt1        up/up    192.0.2.69/24    node-2       e1a     true
vs1.example.com
            datalif1     up/down  192.0.2.145/30   node-1       e1c     true
vs3.example.com
            datalif3     up/up    192.0.2.146/30   node-2       e0c     true
            datalif4     up/up    2001::2/64       node-2       e0c     true
5 entries were displayed.
----
下列命令顯示如何建立指派給的 NAS 資料 LIF `default-data-files` 服務原則：

[listing]
----
network interface create -vserver vs1 -lif lif2 -home-node node2 -homeport e0d -service-policy default-data-files -subnet-name ipspace1
----
.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/network-ping.html["網路ping"^]

