---
permalink: smb-config/create-volume-task.html 
sidebar: sidebar 
keywords: create, volume, junction, point, properties, property, command, create a volume 
summary: 您可以使用volume create命令來建立磁碟區、並指定其交會點和其他屬性。 
---
= 建立Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用建立 Volume 並指定其連接點和其他屬性 `volume create` 命令。

.關於這項工作
磁碟區必須包含_交會路徑_、才能讓用戶端使用其資料。您可以在建立新磁碟區時指定交會路徑。如果您在建立磁碟區時未指定連接路徑、則必須使用 _ 掛載 _ SVM 命名空間中的磁碟區 `volume mount` 命令。

.開始之前
* 應設定並執行 SMB 。
* SVM 安全樣式必須是 NTFS 。
* 從 ONTAP 9.13.1 開始、您可以使用容量分析和活動追蹤功能來建立 Volume 。若要啟用容量或活動追蹤、請核發 `volume create` 命令 `-analytics-state` 或 `-activity-tracking-state` 設定為 `on`。
+
若要深入瞭解容量分析和活動追蹤、請參閱 https://docs.netapp.com/us-en/ontap/task_nas_file_system_analytics_enable.html["啟用檔案系統分析"]。



.步驟
. 建立具有交會點的Volume： `volume create -vserver _svm_name_ -volume _volume_name_ -aggregate _aggregate_name_ -size {integer[KB|MB|GB|TB|PB]} -security-style ntfs -junction-path _junction_path_]`
+
的選擇 `-junction-path` 以下是：

+
** 直接位於根目錄下、例如 `/new_vol`
+
您可以建立新磁碟區、並指定將其直接掛載到SVM根磁碟區。

** 在現有目錄下、例如 `/existing_dir/new_vol`
+
您可以建立新磁碟區、並指定將其掛載至現有磁碟區（在現有階層架構中）、以目錄形式表示。



+
如果您想在新目錄中建立磁碟區（在新磁碟區下的新階層中）、例如： `/new_dir/new_vol`接著、您必須先建立與 SVM 根 Volume 相關的新父 Volume 。接著、您會在新父Volume（新目錄）的交會路徑中建立新的子Volume。

. 確認已使用所需的交會點建立磁碟區： `volume show -vserver _svm_name_ -volume _volume_name_ -junction`


.範例
下列命令會在SVM vs1.example.com和Aggr1上建立名為user1的新磁碟區。新的 Volume 可在取得 `/users`。磁碟區大小為750 GB、磁碟區保證為磁碟區類型（預設）。

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume users -aggregate aggr1 -size 750g -junction-path /users
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume users -junction
                          Junction                 Junction
Vserver           Volume  Active   Junction Path   Path Source
----------------- ------- -------- --------------- -----------
vs1.example.com   users1  true     /users          RW_volume
----
下列命令會在SVM上建立一個名為「'home4'」的新磁碟區：vs1.example.com`"和Aggr1'集合體。目錄 `/eng/` VS1 SVM 的命名空間已存在、新的 Volume 可從取得 `/eng/home`、成為的主目錄 `/eng/` 命名空間。磁碟區大小為 750 GB 、其磁碟區保證屬於類型 `volume` （預設）。

[listing]
----
cluster1::> volume create -vserver vs1.example.com -volume home4 -aggregate aggr1 -size 750g -junction-path /eng/home
[Job 1642] Job succeeded: Successful

cluster1::> volume show -vserver vs1.example.com -volume home4 -junction
                         Junction                 Junction
Vserver          Volume  Active   Junction Path   Path Source
---------------- ------- -------- --------------- -----------
vs1.example.com  home4   true     /eng/home       RW_volume
----