---
permalink: smb-config/index.html 
sidebar: sidebar 
keywords:  
summary: 您可以使用ONTAP 支援功能支援功能支援支援功能、以設定SMB用戶端存取新磁碟區或新SVM或現有SVM中qtree中所含的檔案。 
---
= 使用CLI進行SMB組態總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用ONTAP 支援功能支援功能支援支援功能、以設定SMB用戶端存取新磁碟區或新SVM或現有SVM中qtree中所含的檔案。

[NOTE]
====
_SMB_（伺服器訊息區塊）是指通用網際網路檔案系統（CIFS）傳輸協定的現代語言。您仍會在ONTAP VMware的指令行介面（CLI）和OnCommand VMware的管理工具中看到_CIFS_。

====
如果您想要以下列方式設定SMB對磁碟區或qtree的存取權、請使用下列程序：

* 您想要使用SMB第2版或更新版本。
* 您只想為SMB用戶端服務、而非NFS用戶端（而非多重傳輸協定組態）。
* NTFS檔案權限將用於保護新磁碟區。
* 您擁有叢集管理員權限、而非SVM管理員權限。
+
建立SVM和LIF需要叢集管理員權限。SVM管理員權限足以執行其他SMB組態工作。

* 您想要使用CLI、而非System Manager或自動化指令碼工具。
+
若要使用System Manager設定NAS多重傳輸協定存取、請參閱 link:https://docs.netapp.com/us-en/ontap/task_nas_provision_nfs_and_smb.html["同時使用NFS和SMB為Windows和Linux配置NAS儲存設備"]。

* 您想要使用最佳實務做法、而非探索每個可用選項。
+
如需命令語法的詳細資料、請參閱CLI說明和ONTAP 支援手冊頁。



如果您想要瞭解ONTAP 有關各項功能的詳細資訊、請參閱 link:../smb-admin/index.html["SMB參考總覽"]。



== 其他方法可在ONTAP 不一樣的情況下執行

|===


| 若要執行這些工作... | 請參閱... 


| 重新設計的System Manager（ONTAP 提供更新版本的更新版本） | link:../task_nas_provision_windows_smb.html["使用SMB為Windows伺服器配置NAS儲存設備"] 


| System Manager Classic（ONTAP 適用於更新版本的更新版本） | link:https://docs.netapp.com/us-en/ontap-sm-classic/smb-config/index.html["SMB組態總覽"^] 
|===