---
permalink: smb-config/verify-protocol-enabled-task.html 
sidebar: sidebar 
keywords: configure, smb, svm, verify, protocol, enable, verify that the smb protocol is enabled on the svm 
summary: 在 SVM 上設定和使用 SMB 之前、您必須先確認已啟用傳輸協定。 
---
= 確認 SVM 上已啟用 SMB 傳輸協定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在 SVM 上設定和使用 SMB 之前、您必須先確認已啟用傳輸協定。

.關於這項工作
這通常是在 SVM 設定期間完成、但如果您在設定期間未啟用傳輸協定、您可以稍後使用加以啟用 `vserver add-protocols` 命令。

[NOTE]
====
一旦建立LIF、您就無法從其新增或移除通訊協定。

====
您也可以使用停用 SVM 上的通訊協定 `vserver remove-protocols` 命令。

.步驟
. 檢查SVM目前啟用和停用的傳輸協定： `vserver show -vserver vserver_name -protocols`
+
您也可以使用 `vserver show-protocols` 用於檢視叢集中所有 SVM 上目前啟用的通訊協定的命令。

. 如有必要、請啟用或停用傳輸協定：
+
** 若要啟用 SMB 傳輸協定： `vserver add-protocols -vserver vserver_name -protocols cifs`
** 若要停用通訊協定： `+vserver remove-protocols -vserver vserver_name -protocols protocol_name[,protocol_name,...]+`


. 確認已啟用和停用的傳輸協定已正確更新： `vserver show -vserver vserver_name -protocols`


.範例
下列命令顯示名為VS1的SVM上目前啟用和停用（允許和不允許）的傳輸協定：

[listing]
----
vs1::> vserver show -vserver vs1.example.com -protocols
Vserver           Allowed Protocols         Disallowed Protocols
-----------       ----------------------    -----------------------
vs1.example.com   cifs                       nfs, fcp, iscsi, ndmp
----
下列命令可透過新增來存取 SMB `cifs` 到名為 VS1 的 SVM 上已啟用的通訊協定清單：

[listing]
----
vs1::> vserver add-protocols -vserver vs1.example.com -protocols cifs
----