---
permalink: smb-config/worksheet-reference.html 
sidebar: sidebar 
keywords: smb, configuration, worksheet, enable, collect, require, information, access, client, worksheet, gather, cifs, worksheet for gathering SMB configuration information 
summary: SMB 組態工作表可讓您收集設定用戶端 SMB 存取所需的資訊。 
---
= ONTAP SMB 組態工作表
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB 組態工作表可讓您收集設定用戶端 SMB 存取所需的資訊。

您應該完成工作表的一或兩個區段、視您對儲存資源配置的決策而定：

* 如果您要設定SMB存取SVM、請完成這兩個部分。
+
xref:configure-access-svm-task.adoc[設定SMB存取SVM]

+
xref:configure-client-access-shared-storage-concept.adoc[設定SMB用戶端存取共享儲存設備]

* 如果您要將儲存容量新增至啟用 SMB 的 SVM 、則只需完成第二節。
+
xref:configure-client-access-shared-storage-concept.adoc[設定SMB用戶端存取共享儲存設備]



深入瞭解中的參數link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]。



== 設定SMB存取SVM

*用於建立SVM*的參數

如果您要建立新的 SVM ，請使用命令提供這些值 `vserver create`。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-create.html["指令參考資料ONTAP"^]需詳細 `vserver create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
您為新SVM提供的名稱、可以是完整網域名稱（FQDN）、也可以遵循另一種在叢集內強制執行唯一SVM名稱的慣例。
 a| 



 a| 
`-aggregate`
 a| 
叢集中有足夠空間容納新SMB儲存容量的集合體名稱。
 a| 



 a| 
`-rootvolume`
 a| 
您為SVM根磁碟區提供的唯一名稱。
 a| 



 a| 
`-rootvolume-security-style`
 a| 
使用 SVM 的 NTFS 安全樣式。
 a| 
`ntfs`



 a| 
`-language`
 a| 
使用此工作流程中的預設語言設定。
 a| 
`C.UTF-8`



 a| 
`ipspace`
 a| 
選用：IPspaces是SVM所在的不同IP位址空間。
 a| 

|===
*用於建立LIF*的參數

建立生命時，您可以使用命令來提供這些值 `network interface create`。如link:https://docs.netapp.com/us-en/ontap-cli/network-interface-create.html["指令參考資料ONTAP"^]需詳細 `network interface create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-lif`
 a| 
您為新LIF提供的名稱。
 a| 



 a| 
`-role`
 a| 
在此工作流程中使用資料LIF角色。
 a| 
`data`



 a| 
`-data-protocol`
 a| 
在此工作流程中、請僅使用 SMB 傳輸協定。
 a| 
`cifs`



 a| 
`-home-node`
 a| 
LIF 在返回時返回的節點 `network interface revert` 命令會在LIF上執行。

如link:https://docs.netapp.com/us-en/ontap-cli/network-interface-revert.html["指令參考資料ONTAP"^]需詳細 `network interface revert`資訊，請參閱。
 a| 



 a| 
`-home-port`
 a| 
LIF 在返回時傳回的連接埠或介面群組 `network interface revert` 命令會在LIF上執行。
 a| 



 a| 
`-address`
 a| 
叢集上的IPV4或IPv6位址、用於新LIF的資料存取。
 a| 



 a| 
`-netmask`
 a| 
LIF的網路遮罩和閘道。
 a| 



 a| 
`-subnet`
 a| 
IP位址集區。改用 `-address` 和 `-netmask` 自動指派位址和網路遮罩。
 a| 



 a| 
`-firewall-policy`
 a| 
在此工作流程中使用預設的資料防火牆原則。
 a| 
`data`



 a| 
`-auto-revert`
 a| 
選用：指定資料LIF在啟動時或其他情況下是否自動還原至主節點。預設設定為 `false`。
 a| 

|===
* DNS主機名稱解析參數*

當您設定 DNS 時，您可以使用命令來提供這些值 `vserver services name-service dns create`。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-services-name-service-dns-create.html["指令參考資料ONTAP"^]需詳細 `vserver services name-service dns create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-domains`
 a| 
最多五個DNS網域名稱。
 a| 



 a| 
`-name-servers`
 a| 
每個DNS名稱伺服器最多三個IP位址。
 a| 

|===


== 在Active Directory網域中設定SMB伺服器

*時間服務組態的參數*

您可以在設定時間服務時，使用命令提供這些值 `cluster time-service ntp server create`。如link:https://docs.netapp.com/us-en/ontap-cli/cluster-time-service-ntp-server-create.html["指令參考資料ONTAP"^]需詳細 `cluster time-service ntp server create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-server`
 a| 
Active Directory網域的NTP伺服器主機名稱或IP位址。
 a| 

|===
*在Active Directory網域中建立SMB伺服器的參數*

當您建立新的 SMB 伺服器並指定網域資訊時，可以使用命令提供這些值 `vserver cifs create`。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-create.html["指令參考資料ONTAP"^]需詳細 `vserver cifs create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
要在其中建立SMB伺服器的SVM名稱。
 a| 



 a| 
`-cifs-server`
 a| 
SMB伺服器名稱（最多15個字元）。
 a| 



 a| 
`-domain`
 a| 
要與SMB伺服器建立關聯的Active Directory網域完整網域名稱（FQDN）。
 a| 



 a| 
`-ou`
 a| 
選用：Active Directory網域中與SMB伺服器相關聯的組織單位。依預設、此參數設為「CN=電腦」。
 a| 



 a| 
`-netbios-aliases`
 a| 
選用：NetBios別名清單、是SMB伺服器名稱的替代名稱。
 a| 



 a| 
`-comment`
 a| 
選用：伺服器的文字註解。瀏覽網路上的伺服器時、Windows用戶端可以看到此SMB伺服器說明。
 a| 

|===


== 在工作群組中設定SMB伺服器

*在工作群組中建立SMB伺服器的參數*

當您建立新的 SMB 伺服器並指定支援的 SMB 版本時，可以使用命令提供這些值 `vserver cifs create`。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-create.html["指令參考資料ONTAP"^]需詳細 `vserver cifs create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
要在其中建立SMB伺服器的SVM名稱。
 a| 



 a| 
`-cifs-server`
 a| 
SMB伺服器名稱（最多15個字元）。
 a| 



 a| 
`-workgroup`
 a| 
工作群組名稱（最多15個字元）。
 a| 



 a| 
`-comment`
 a| 
選用：伺服器的文字註解。瀏覽網路上的伺服器時、Windows用戶端可以看到此SMB伺服器說明。
 a| 

|===
*建立本機使用者的參數*

您可以在使用命令建立本機使用者時提供這些值 `vserver cifs users-and-groups local-user create`。工作群組中的SMB伺服器和AD網域中的選用伺服器都需要這些伺服器。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-users-and-groups-local-user-create.html["指令參考資料ONTAP"^]需詳細 `vserver cifs users-and-groups local-user create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
要在其中建立本機使用者的SVM名稱。
 a| 



 a| 
`-user-name`
 a| 
本機使用者名稱（最多20個字元）。
 a| 



 a| 
`-full-name`
 a| 
選用：使用者的全名。如果全名包含空格、請將全名括在雙引號內。
 a| 



 a| 
`-description`
 a| 
選用：本機使用者的說明。如果說明包含空格、請將參數括在引號中。
 a| 



 a| 
`-is-account-disabled`
 a| 
選用：指定使用者帳戶是啟用還是停用。如果未指定此參數、則預設為啟用使用者帳戶。
 a| 

|===
*建立本機群組的參數*

您可以在使用命令建立本機群組時提供這些值 `vserver cifs users-and-groups local-group create`。對於AD網域和工作群組中的SMB伺服器而言、它們是選用的。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-users-and-groups-local-group-create.html["指令參考資料ONTAP"^]需詳細 `vserver cifs users-and-groups local-group create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
要在其中建立本機群組的SVM名稱。
 a| 



 a| 
`-group-name`
 a| 
本機群組名稱（最多256個字元）。
 a| 



 a| 
`-description`
 a| 
選用：本機群組的說明。如果說明包含空格、請將參數括在引號中。
 a| 

|===


== 將儲存容量新增至啟用 SMB 的 SVM

*建立Volume的參數*

如果您要建立的是 Volume 而非 qtree ，則可以使用命令來提供這些值 `volume create`。如link:https://docs.netapp.com/us-en/ontap-cli/volume-create.html["指令參考資料ONTAP"^]需詳細 `volume create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
將裝載新磁碟區的新SVM或現有SVM名稱。
 a| 



 a| 
`-volume`
 a| 
您為新磁碟區提供的唯一描述性名稱。
 a| 



 a| 
`-aggregate`
 a| 
叢集中有足夠空間可容納新SMB Volume的集合體名稱。
 a| 



 a| 
`-size`
 a| 
您為新磁碟區大小所提供的整數。
 a| 



 a| 
`-security-style`
 a| 
此工作流程使用NTFS安全樣式。
 a| 
`ntfs`



 a| 
`-junction-path`
 a| 
要掛載新磁碟區的根目錄（/）下的位置。
 a| 

|===
*用於建立qtree的參數*

如果您要建立 qtree 而非 Volume ，請使用命令提供這些值 `volume qtree create`。如link:https://docs.netapp.com/us-en/ontap-cli/volume-qtree-create.html["指令參考資料ONTAP"^]需詳細 `volume qtree create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
包含qtree之磁碟區所在的SVM名稱。
 a| 



 a| 
`-volume`
 a| 
將包含新qtree的磁碟區名稱。
 a| 



 a| 
`-qtree`
 a| 
您為新qtree提供的唯一描述性名稱、64個字元或更少。
 a| 



 a| 
`-qtree-path`
 a| 
格式中的 qtree path 引數 `/vol/volume_name/qtree_name\>` 可以指定、而非將 Volume 和 qtree 指定為個別的引數。
 a| 

|===
*建立SMB共用的參數*

您可以使用命令提供這些值 `vserver cifs share create`。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["指令參考資料ONTAP"^]需詳細 `vserver cifs share create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
要在其中建立SMB共用區的SVM名稱。
 a| 



 a| 
`-share-name`
 a| 
您要建立的SMB共用區名稱（最多256個字元）。
 a| 



 a| 
`-path`
 a| 
SMB共用區路徑名稱（最多256個字元）。此路徑必須存在於磁碟區中、才能建立共用區。
 a| 



 a| 
`-share-properties`
 a| 
選用：共用內容清單。預設設定為 `oplocks`、 `browsable`、 `changenotify`和 `show-previous-versions`。
 a| 



 a| 
`-comment`
 a| 
選用：伺服器的文字註解（最多256個字元）。在網路上瀏覽時、Windows用戶端可以看到此SMB共用說明。
 a| 

|===
*建立SMB共用存取控制清單（ACL）的參數*

您可以使用命令提供這些值 `vserver cifs share access-control create`。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-access-control-create.html["指令參考資料ONTAP"^]需詳細 `vserver cifs share access-control create`資訊，請參閱。

|===
| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
要在其中建立SMB ACL的SVM名稱。
 a| 



 a| 
`-share`
 a| 
要在其中建立的SMB共用區名稱。
 a| 



 a| 
`-user-group-type`
 a| 
要新增至共用ACL的使用者或群組類型。預設類型為 `windows`
 a| 
`windows`



 a| 
`-user-or-group`
 a| 
要新增至共用ACL的使用者或群組。如果您指定使用者名稱、則必須使用「domain\userName」格式來包含使用者的網域。
 a| 



 a| 
`-permission`
 a| 
指定使用者或群組的權限。
 a| 
`[ No_access | Read | Change | Full_Control ]`

|===