---
permalink: disks-aggregates/add-disks-node-task.html 
sidebar: sidebar 
keywords: add, drives, node, shelf 
summary: 您可以將磁碟機新增至節點或磁碟櫃、以增加熱備援磁碟機的數量、或將空間新增至集合體。 
---
= 將磁碟機新增至節點或機櫃
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將磁碟機新增至節點或磁碟櫃、以增加熱備援磁碟機的數量、或將空間新增至集合體。

您的平台必須支援您要新增的磁碟機。

https://hwu.netapp.com/["NetApp Hardware Universe"^]

在單一程序中應新增的磁碟機數量下限為六個。新增單一磁碟機可能會降低效能。

.步驟
. 請查看NetApp支援網站、以取得較新的磁碟機和機櫃韌體及磁碟認證套件檔案。
+
如果您的節點或機櫃沒有最新版本、請在安裝新磁碟機之前先進行更新。

+
磁碟機韌體會在沒有目前韌體版本的新磁碟機上自動更新（不中斷營運）。

. 請妥善接地。
. 從平台正面輕移擋板。
. 識別新磁碟機的正確插槽。
+
[NOTE]
====
新增磁碟機的正確插槽視平台機型和ONTAP 版本而定。在某些情況下、您需要依序將磁碟機新增至特定插槽。例如AFF 、在某個範例中、您可以在特定的時間間隔新增磁碟機、使叢集內的插槽閒置。而AFF 在功能不全的A220中、您可以將新的磁碟機新增至從外側到磁碟櫃中央的下一個空插槽。

====
+
請參閱 https://hwu.netapp.com/["NetApp Hardware Universe"^] 找出適合您組態的正確插槽。

. 插入新磁碟機：
+
.. 在CAM握把處於開啟位置時、請用手插入新的磁碟機。
.. 推動直到磁碟機停止。
.. 合上CAM握把、讓磁碟機完全插入中間平面、並將握把卡入定位。請務必緩慢關閉CAM握把、使其與磁碟機正面正確對齊。


. 確認磁碟機的活動LED（綠色）亮起。
+
當磁碟機的活動LED持續亮起時、表示磁碟機已有電力。當磁碟機的活動LED燈在閃爍時、表示磁碟機已開機且I/O正在進行中。如果磁碟機韌體正在自動更新、LED會開始閃爍。

. 若要新增其他磁碟機、請重複步驟4至6。
+
新磁碟機必須指派給節點、才能被辨識。您可以手動指派新磁碟機、或者、如果ONTAP 您的節點遵循磁碟機自動指派的規則、您也可以等待停止自動指派新磁碟機。

. 確認所有新磁碟機之後、請確認新增磁碟機及其擁有權資訊：
+
「torage Aggregate show-spare磁碟」

+
您應該會看到新的磁碟機、這些磁碟機屬於正確的節點。

. 將新增的磁碟機歸零：
+
'磁碟零備援磁碟機'

+
先前在ONTAP 某個不景區中使用的磁碟機必須先歸零、才能新增至另一個集合體。磁碟機零位調整現在可防止延遲、以便在需要快速增加集合體的大小時使用。磁碟機零位調整命令會在背景執行、視節點中的非零位磁碟機大小而定、可能需要數小時才能完成。



新磁碟機已準備好新增至Aggregate、放入熱備援磁碟機清單、或是建立新的Aggregate。
