---
permalink: disks-aggregates/commands-manage-disks-reference.html 
sidebar: sidebar 
keywords: commands, manage, disks 
summary: 您可以使用儲存磁碟和儲存Aggregate命令來管理磁碟。 
---
= 用於管理磁碟的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「儲存磁碟」和「儲存Aggregate」命令來管理磁碟。

|===


| 如果您想要... | 使用此命令... 


 a| 
依擁有者顯示備用磁碟清單、包括分割磁碟
 a| 
「torage Aggregate show-spare磁碟」



 a| 
依Aggregate顯示磁碟RAID類型、目前使用量及RAID群組
 a| 
「torage Aggregate show-Status」



 a| 
顯示RAID類型、目前使用量、Aggregate及RAID群組、包括備援磁碟機、 適用於實體磁碟
 a| 
「torage disk show -RAID」



 a| 
顯示故障磁碟的清單
 a| 
「torage disk show -dis中斷」



 a| 
顯示磁碟的叢集前（節點）磁碟機名稱
 a| 
「torage disk show -prime-paths」（進階）



 a| 
照亮特定磁碟或磁碟櫃的LED
 a| 
"torage disk set-led（磁碟設定導向）"



 a| 
顯示特定磁碟的Checksum類型
 a| 
「torage disk show -功能 變數checksum相容性」



 a| 
顯示所有備用磁碟的Checksum類型
 a| 
「torage disk show -功能 變數checksum相容性-container類型spare」



 a| 
顯示磁碟連線與放置資訊
 a| 
「torage disk show -功能 變數disk、primary連接埠、二線名稱、二線連接埠、機櫃、Bay」



 a| 
顯示特定磁碟的叢集前磁碟名稱
 a| 
「torage disk show -disk diskname -功能 變數diskpathnames」



 a| 
顯示維護中心的磁碟清單
 a| 
「torage disk show -maintenance」



 a| 
顯示SSD的耗損壽命
 a| 
「torage disk show -ssd耗損」



 a| 
取消共用磁碟的分割
 a| 
「torage disk undpartition]（診斷層級提供）



 a| 
將所有非零磁碟歸零
 a| 
'磁碟零備援磁碟機'



 a| 
停止在一或多個指定磁碟上進行中的資料抹除程序
 a| 
'系統節點執行節點節點節點節點節點名稱-命令磁碟清理'



 a| 
顯示儲存設備加密磁碟資訊
 a| 
「torage加密磁碟顯示」



 a| 
從所有連結的金鑰管理伺服器擷取驗證金鑰
 a| 
「安全金鑰管理程式還原」

|===
.相關資訊
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令數ONTAP"^]
