---
permalink: disks-aggregates/commands-manage-aggregates-reference.html 
sidebar: sidebar 
keywords: commands, manage, aggregates 
summary: 您可以使用儲存Aggregate命令來管理Aggregate。 
---
= 管理Aggregate的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `storage aggregate` 管理集合體的命令。

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示所有Flash Pool Aggregate的快取大小
 a| 
`storage aggregate show -fields hybrid-cache-size-total -hybrid-cache-size-total >0`



 a| 
顯示Aggregate的磁碟資訊和狀態
 a| 
`storage aggregate show-status`



 a| 
依節點顯示備用磁碟
 a| 
`storage aggregate show-spare-disks`



 a| 
顯示叢集中的根集合體
 a| 
`storage aggregate show -has-mroot true`



 a| 
顯示Aggregate的基本資訊和狀態
 a| 
`storage aggregate show`



 a| 
顯示集合體中使用的儲存類型
 a| 
`storage aggregate show -fields storage-type`



 a| 
讓Aggregate上線
 a| 
`storage aggregate online`



 a| 
刪除 Aggregate
 a| 
`storage aggregate delete`



 a| 
將Aggregate置於受限狀態
 a| 
`storage aggregate restrict`



 a| 
重新命名Aggregate
 a| 
`storage aggregate rename`



 a| 
使Aggregate離線
 a| 
`storage aggregate offline`



 a| 
變更Aggregate的RAID類型
 a| 
`storage aggregate modify -raidtype`

|===
.相關資訊
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令數ONTAP"^]
