---
permalink: disks-aggregates/commands-manage-disks-reference.html 
sidebar: sidebar 
keywords: commands, manage, disks 
summary: 您可以使用儲存磁碟和儲存Aggregate命令來管理磁碟。 
---
= 用於管理磁碟的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `storage disk` 和 `storage aggregate` 管理磁碟的命令。

|===


| 如果您想要... | 使用此命令... 


 a| 
依擁有者顯示備用磁碟清單、包括分割磁碟
 a| 
`storage aggregate show-spare-disks`



 a| 
依Aggregate顯示磁碟RAID類型、目前使用量及RAID群組
 a| 
`storage aggregate show-status`



 a| 
顯示RAID類型、目前使用量、Aggregate及RAID群組、包括備援磁碟機、 適用於實體磁碟
 a| 
`storage disk show -raid`



 a| 
顯示故障磁碟的清單
 a| 
`storage disk show -broken`



 a| 
顯示磁碟的叢集前（節點）磁碟機名稱
 a| 
`storage disk show -primary-paths` （進階）



 a| 
照亮特定磁碟或磁碟櫃的LED
 a| 
`storage disk set-led`



 a| 
顯示特定磁碟的Checksum類型
 a| 
`storage disk show -fields checksum-compatibility`



 a| 
顯示所有備用磁碟的Checksum類型
 a| 
`storage disk show -fields checksum-compatibility -container-type spare`



 a| 
顯示磁碟連線與放置資訊
 a| 
`storage disk show -fields disk,primary-port,secondary-name,secondary-port,shelf,bay`



 a| 
顯示特定磁碟的叢集前磁碟名稱
 a| 
`storage disk show -disk diskname -fields diskpathnames`



 a| 
顯示維護中心的磁碟清單
 a| 
`storage disk show -maintenance`



 a| 
顯示SSD的耗損壽命
 a| 
`storage disk show -ssd-wear`



 a| 
取消共用磁碟的分割
 a| 
`storage disk unpartition` （可在診斷層級取得）



 a| 
將所有非零磁碟歸零
 a| 
`storage disk zerospares`



 a| 
停止在一或多個指定磁碟上進行中的資料抹除程序
 a| 
`system node run -node nodename -command disk sanitize`



 a| 
顯示儲存設備加密磁碟資訊
 a| 
`storage encryption disk show`



 a| 
從所有連結的金鑰管理伺服器擷取驗證金鑰
 a| 
`security key-manager restore`

|===
.相關資訊
* https://docs.netapp.com/us-en/ontap-cli["指令參考資料ONTAP"^]

