---
permalink: disks-aggregates/convert-raid-dp-tec-task.html 
sidebar: sidebar 
keywords: convert, raid-dp, raid-tec, raid policy 
summary: 如果您想要增加三同位元檢查的保護、可以從RAID-DP轉換為RAID-TEC如果本機層中使用的磁碟大小大於 4 TiB ，則建議使用 RAID-TEC 。 
---
= 從 ONTAP RAID-DP 轉換為 RAID-TEC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想要增加三同位元檢查的保護、可以從RAID-DP轉換為RAID-TEC如果本機層中使用的磁碟大小大於 4 TiB ，則建議使用 RAID-TEC 。


NOTE: 在 ONTAP 9.7 之前，系統管理員使用術語 _Aggregate _ 來描述 _ 本機層 _ 。無論您的 ONTAP 版本為何， ONTAP CLI 都會使用術語 _Aggregate 。若要深入瞭解本機階層，請參閱link:../disks-aggregates/index.html["磁碟和本機層"]。

.開始之前
要轉換的本機層必須至少有七個磁碟。

.關於這項工作
* 硬碟機（HDD）本機層可從RAID-DP轉換為RAID-TEC這包括Flash Pool本機層中的HDD層級。


.對於快閃記憶體池 / 混合聚合，需要使用 -disktype 參數來變更每個磁碟類型的流程
[-T, -disktype {ATA | BSAS | FCAL | FSAS | LUN | MSATA | SAS | SSD | VMDISK | SSD-NVM | SSD-CAP | SSD-ZNS | VMLUN | VMLUN-SSD}] - 磁碟類型

此參數指定要修改的 RAID 群組的磁碟類型。對於 Flash Pool，它可以指定 HDD 層或 SSD 層。如果 HDD 層由多種類型的磁碟組成，則指定其中任何一種正在使用的磁碟類型都會導致該層被修改。如果目前 Aggregate RAID 類型為 mixed_raid_type，則此參數為必填項。

.步驟
. 確認本機層已上線，且至少有六個磁碟：
+
`storage aggregate show-status -aggregate _aggregate_name_`

. 將本機層從 RAID-DP 轉換為 RAID-TEC ：
+
`storage aggregate modify -aggregate _aggregate_name_ -raidtype raid_tec`

. 驗證本機層 RAID 原則是否為 RAID-TEC ：
+
`storage aggregate show _aggregate_name_`



.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-modify.html["儲存聚合修改"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-status.html["儲存聚合顯示狀態"^]

