---
permalink: disks-aggregates/create-ssd-storage-pool-task.html 
sidebar: sidebar 
keywords: create, provision, ssd, storage, flash, pool, add, cache, local tier, aggregate 
summary: 您可以建立固態硬碟（ SSD ）儲存池，為兩至四個 Flash Pool 本機層提供 SSD 快取。 
---
= 建立 SSD 儲存池，將快取新增至 ONTAP 本機層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以透過新增固態硬碟（ SSD ），將現有的本機層轉換為 Flash Pool 本機層，來配置快取。

您可以建立固態硬碟（ SSD ）儲存池，為兩至四個 Flash Pool 本機層提供 SSD 快取。Flash Pool 本機層可讓您將 Flash 部署為工作資料集的高效能快取，同時使用成本較低的 HDD 來處理存取頻率較低的資料。

.關於這項工作
* 在建立磁碟或將磁碟新增至儲存資源池時、您必須提供磁碟清單。
+
儲存資源池不支援 `diskcount` 參數。

* 儲存資源池中使用的SSD大小應相同。


[role="tabbed-block"]
====
.系統管理員
--
.使用System Manager新增SSD快取（ONTAP 更新版本：《》、《》、《》、《》、《》、《》、《
[%collapsible%open]
=====
從功能完整的9.12.1開始ONTAP 、您可以使用System Manager來新增SSD快取。


NOTE: 儲存資源池選項不適用於AFF 不適用的系統。

.步驟
. 按一下「*叢集>磁碟*」、然後按一下「*顯示/隱藏*」。
. 選取*類型*並確認叢集上是否有備用SSD。
. 按一下「to * Storage > Tiers*」、然後按一下「* Add Storage Pool*」。
. 選取磁碟類型。
. 輸入磁碟大小。
. 選取要新增至儲存資源池的磁碟數目。
. 檢閱預估的快取大小。


=====
.使用系統管理程式新增SSD快取（ONTAP 僅限用率為9.7）
[%collapsible%open]
=====

NOTE: 如果您使用ONTAP 的是更新於ONTAP 版本更新於版本號的版本、或是ONTAP 更新於版本號不超過版本號的版本號、請使用CLI程序。

.步驟
. 按一下*（返回傳統版本）*。
. 按一下「 * 儲存設備 > 集合體與磁碟 > Aggregate * 」。
. 選取本機層，然後按一下 * 動作 > 新增快取 * 。
. 選取快取來源為「儲存資源池」或「專用SSD」。
. 按一下*（切換至新體驗）*。
. 按一下 * 儲存 > Tiers* ，確認新本機層的大小。


=====
--
.CLI
--
*使用CLI建立SSD儲存資源池*

.步驟
. 判斷可用的備用SSD名稱：
+
`storage aggregate show-spare-disks -disk-type SSD`

+
儲存資源池中使用的SSD可由HA配對的任一節點擁有。

. 建立儲存資源池：
+
`storage pool create -storage-pool _sp_name_ -disk-list _disk1_,_disk2_,...`

. *選用：*驗證新建立的儲存資源池：
+
`storage pool show -storage-pool _sp_name_`



--
====
.結果
將SSD放入儲存資源池之後、即使儲存資源池所提供的儲存設備尚未分配給任何Flash資源池快取、SSD仍不會在叢集上顯示為備援磁碟。您無法將SSD新增至RAID群組做為獨立磁碟機；只能使用SSD所屬儲存資源池的配置單元來配置其儲存設備。

.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["儲存Aggregate顯示"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-create.html["儲存池創建"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-pool-show.html["儲水池展示"^]

