---
permalink: disks-aggregates/decide-aggregate-creation-method-concept.html 
sidebar: sidebar 
keywords: decide, aggregate, create, add, method, local tier 
summary: 雖然 ONTAP 提供自動建立本機階層的最佳實務建議，但您必須判斷您的環境是否支援建議的組態。如果不是、您必須決定RAID原則和磁碟組態、然後手動建立本機層級。 
---
= 決定要使用哪種方法來建立 ONTAP 本機階層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
雖然 ONTAP 提供自動新增本機層的最佳實務建議，但您必須判斷您的環境是否支援建議的組態。如果不是、您必須決定RAID原則和磁碟組態、然後手動建立本機層級。

自動建立本機層時ONTAP 、即可分析叢集中可用的備用磁碟、並根據最佳實務做法、提出如何使用備用磁碟來新增本機層的建議。顯示建議的組態。ONTAP  您可以接受建議、或手動新增本機層級。


NOTE: 在 ONTAP 9.7 之前，系統管理員使用術語 _Aggregate _ 來描述 _ 本機層 _ 。無論您的 ONTAP 版本為何， ONTAP CLI 都會使用術語 _Aggregate 。若要深入瞭解本機階層，請參閱link:../disks-aggregates/index.html["磁碟和本機層"]。



== 在您接受ONTAP 不推薦的功能之前

如果出現下列任一磁碟情況、則必須先解決這些問題、再接受ONTAP 來自下列的建議：

* 遺失磁碟
* 備用磁碟編號的波動
* 未指派的磁碟
* 非零備援
* 正在進行維護測試的磁碟


如link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-auto-provision.html["指令參考資料ONTAP"^]需詳細 `storage aggregate auto-provision`資訊，請參閱。



== 當您必須使用手動方法時

在許多情況下、建議的本機層配置最適合您的環境。不過，如果您的環境包含下列組態，則必須使用手動方法建立本機層。


NOTE: 從《局部9.11.1》開始ONTAP 、您可以使用System Manager手動新增本機層級。

* 使用第三方陣列 LUN 的本機層
* 虛擬磁碟Cloud Volumes ONTAP 搭配不一樣或ONTAP Select 不一樣的功能
* 系統MetroCluster
* SyncMirror
* MSATA磁碟
* Flash Pool 階層
* 多種磁碟類型或大小會連接至節點




== 選取建立本機階層的方法

選擇您要使用的方法：

* link:create-aggregates-auto-provision-task.html["自動新增（建立）本機層"]
* link:create-aggregates-manual-task.html["手動新增（建立）本機層"]


.相關資訊
* https://docs.netapp.com/us-en/ontap-cli["指令參考資料ONTAP"^]

