---
permalink: disks-aggregates/determine-modify-caching-policy-flash-pool-task.html 
sidebar: sidebar 
keywords: modify, cache, policy, flash pool, aggregate, local tier 
summary: 您可以將快取保留原則指派給Flash Pool本機層（Aggregate）中的磁碟區、以決定磁碟區資料在Flash Pool快取中保留的時間。不過、在某些情況下、變更快取保留原則可能不會影響磁碟區資料保留在快取中的時間量。 
---
= 判斷是否要修改Flash Pool本機層（Aggregate）的快取原則
:allow-uri-read: 


[role="lead"]
您可以將快取保留原則指派給Flash Pool本機層（Aggregate）中的磁碟區、以決定磁碟區資料在Flash Pool快取中保留的時間。不過、在某些情況下、變更快取保留原則可能不會影響磁碟區資料保留在快取中的時間量。

.關於這項工作
如果您的資料符合下列任一條件、變更快取保留原則可能不會造成影響：

* 您的工作負載是連續的。
* 您的工作負載不會重新讀取固態硬碟（SSD）中快取的隨機區塊。
* 磁碟區的快取大小太小。


.步驟
下列步驟會檢查資料必須符合的條件。工作必須在進階權限模式下使用CLI來完成。

. 使用CLI檢視工作負載Volume：
+
「開始統計資料-物件工作負載磁碟區」

. 判斷Volume的工作負載模式：
+
「tnetfitical show -object Workload Volume -instance _Volume -Workload _-counter連續讀取」

. 判斷Volume的命中率：
+
「tstatisticsshow -object WAFL_hya_VVOL -instance _volume _-counter read_ops_replace_pwer百分 點」

. 確定磁碟區的「可快取讀取」和「專案快取分配」：
+
'System節點執行節點node_name WAFL flexawa start _agger_name_'

. 顯示AWA摘要：
+
'System節點執行節點node_name WAFL flexawa print _agger_name_'

. 比較Volume的命中率與「可快取讀取」。
+
如果磁碟區的命中率大於「可快取的讀取」、則工作負載不會重新讀取快取到SSD中的隨機區塊。

. 將磁碟區目前的快取大小與「Project Cache Alloc'」進行比較。
+
如果磁碟區目前的快取大小大於「Project Cache Alloc」、則磁碟區快取的大小太小。


