---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html 
sidebar: sidebar 
keywords: space, usage, aggregate, local tier, volume 
summary: 您可以檢視一或多個本機層（Aggregate）中所有磁碟區所使用的空間量、以便採取行動來釋出更多空間。 
---
= 判斷本機層中的空間使用量（Aggregate）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢視一或多個本機層（Aggregate）中所有磁碟區所使用的空間量、以便採取行動來釋出更多空間。

支援整合層級中繼資料和效能的資料空間佔總磁碟空間的10% WAFL 。  用於維護集合體中磁碟區的空間來自WAFL 於此保護區、因此無法變更。

從VMware版9.12.1及更新版本開始ONTAP 、針對All Flash FAS 更新版本（AFF VMware）和FAS500f平台、WAFL 30TB以上的集合體的VMware保留資源將從10%降至5%、進而增加集合體的可用空間。

您可以使用檢視一個或多個集合體中所有磁碟區的空間使用量 `aggregate show-space` 命令。這有助於您查看哪些磁碟區在其內含的集合體中佔用的空間最大、以便您採取行動來釋出更多空間。

Aggregate中已用空間會直接受FlexVol 其包含的各種空間所影響。您為了增加磁碟區空間而採取的措施、也會影響集合體中的空間。

下列資料列會包含在中 `aggregate show-space` 命令輸出：

* * Volume Footprints *
+
集合體內所有Volume佔用空間的總計。其中包含所有資料所使用或保留的空間、以及包含Aggregate中所有磁碟區的中繼資料。

* * Aggregate中繼資料*
+
Aggregate所需的檔案系統中繼資料總數、例如分配點陣圖和inode檔案。

* * Snapshot保留*
+
根據磁碟區大小、保留給Aggregate Snapshot複本的空間量。它被視為已用空間、無法用於磁碟區或集合體資料或中繼資料。

* * Snapshot保留不可用*
+
最初分配給Aggregate Snapshot保留的空間量、由於與Aggregate相關聯的磁碟區正在使用此空間、因此無法用於Aggregate Snapshot複本。僅適用於具有非零集合體Snapshot保留的集合體。

* *使用總數*
+
集合體中所有已用或保留空間的總和（依磁碟區、中繼資料或Snapshot複本）。

* *實際使用總量*
+
目前用於資料的空間量（而非保留供未來使用）。包括Aggregate Snapshot複本所使用的空間。



下列範例顯示 `aggregate show-space` Snapshot 保留為 5% 的 Aggregate 命令輸出。如果Snapshot保留為0、則不會顯示該列。

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....
.相關資訊
link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["知識型文章：空間使用"]

link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["升級ONTAP 至更新版的更新版、即可釋放5%的儲存容量"]
