---
permalink: disks-aggregates/determine-control-volume-space-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, control. volume, space usage, aggregate 
summary: 您可以判斷哪些FlexVol 等量磁碟區使用的是本機層（Aggregate）中最大的空間、以及磁碟區內的哪些功能。 
---
= 判斷及控制本機層中的磁碟區空間使用量（Aggregate）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以判斷哪些FlexVol 等量磁碟區使用的是本機層（Aggregate）中最大的空間、以及磁碟區內的哪些功能。

。 `volume show-footprint` 命令提供有關卷佔用空間或其在包含的 Aggregate 中的空間使用情況的信息。

。 `volume show-footprint` 命令會顯示集合體中每個磁碟區（包括離線磁碟區）的空間使用量詳細資料。此命令可橋接的輸出之間的間距 `volume show-space` 和 `aggregate show-space` 命令。所有百分比均以Aggregate大小的百分比計算。

下列範例顯示 `volume show-footprint` 稱為 testvol 的 Volume 命令輸出：

....
cluster1::> volume show-footprint testvol

      Vserver : thevs
      Volume  : testvol

      Feature                                   Used    Used%
      --------------------------------    ----------    -----
      Volume Data Footprint                  120.6MB       4%
      Volume Guarantee                        1.88GB      71%
      Flexible Volume Metadata               11.38MB       0%
      Delayed Frees                           1.36MB       0%
      Total Footprint                         2.01GB      76%
....
下表說明的輸出部分主要列 `volume show-footprint` 命令以及您可以採取哪些行動來嘗試利用該功能來減少空間使用量：

|===


| 列/功能名稱 | 列的說明/內容 | 減少的方法 


 a| 
`Volume Data Footprint`
 a| 
包含 Aggregate 中使用的總空間量，依據作用中檔案系統中的磁碟區資料，以及磁碟區快照所使用的空間。此列不包含保留空間。
 a| 
* 從磁碟區刪除資料。
* 從磁碟區刪除快照。




 a| 
`Volume Guarantee`
 a| 
磁碟區在Aggregate中保留的空間量、以供未來寫入。保留的空間量取決於磁碟區的保證類型。
 a| 
將磁碟區的保證類型變更為 `none`。



 a| 
`Flexible Volume Metadata`
 a| 
磁碟區中繼資料檔案在集合中使用的空間總量。
 a| 
沒有直接的控制方法。



 a| 
`Delayed Frees`
 a| 
用於ONTAP 效能的區塊、無法立即釋出。對於 SnapMirror 目的地、此列的值為 `0` 且不會顯示。
 a| 
沒有直接的控制方法。



 a| 
`File Operation Metadata`
 a| 
保留給檔案作業中繼資料的空間總量。
 a| 
沒有直接的控制方法。



 a| 
`Total Footprint`
 a| 
磁碟區在集合體中使用的空間總量。這是所有列的總和。
 a| 
用於減少磁碟區所用空間的任何方法。

|===
.相關資訊
https://www.netapp.com/pdf.html?item=/media/19670-tr-3483.pdf["NetApp技術報告3483：NetApp SAN或IP SAN企業環境中的精簡配置"^]
