---
permalink: disks-aggregates/determine-space-usage-aggregate-concept.html 
sidebar: sidebar 
keywords: space, usage, aggregate, local tier, volume 
summary: 您可以檢視一或多個本機層中所有磁碟區使用的空間量，以便採取行動釋放更多空間。 
---
= 判斷 ONTAP 本機層中的空間使用量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢視一或多個本機層中所有磁碟區使用的空間量，以便採取行動釋放更多空間。


NOTE: 在 ONTAP 9.7 之前，系統管理員使用術語 _Aggregate _ 來描述 _ 本機層 _ 。無論您的 ONTAP 版本為何， ONTAP CLI 都會使用術語 _Aggregate 。若要深入瞭解本機階層，請參閱link:../disks-aggregates/index.html["磁碟和本機層"]。

WAFL 會保留本機層級中繼資料和效能所需的磁碟空間總量百分比。用於維護本端層中磁碟區的空間來自 WAFL 保留區，無法變更。

在小於 30 TB 的本機層中， WAFL 保留了 10% 的磁碟空間，以供本機層級的中繼資料和效能使用。

從 ONTAP 9.12.1 開始，在 30 TB 或更大的本機階層中，用於本機層級中繼資料和效能的保留磁碟空間量將會減少，導致本機層級的可用空間增加 5% 。此空間節約的可用度會因您的平台和 ONTAP 版本而異。

[cols="30,30,40"]
|===
| 由 ONTAP 在本機層中保留 30 TB 以上的磁碟空間 | 適用於平台 | 在 ONTAP 版本中 


| 5% | 所有 AFF 和 FAS 平台 | ONTAP 9.14.1 及更新版本 


| 5% | AFF 平台與 FAS500f 平台 | 更新版本ONTAP 


| 10% | 所有平台 | 更新版本ONTAP 
|===
您可以使用命令檢視一個或多個本機層中所有磁碟區的空間使用量 `aggregate show-space`。這有助於您瞭解哪些磁碟區佔用其包含的本機層中最大的空間，以便您採取行動釋放更多空間。

本機層中的已用空間會直接受到其所包含 FlexVol 磁碟區中所用空間的影響。增加磁碟區空間時所採取的措施，也會影響本機層的空間。


NOTE: 從 ONTAP 9.15.1 開始、有兩個新的中繼資料計數器可供使用。加上對多個現有計數器所做的變更、您可以更清楚地瞭解分配的使用者資料量。如需詳細資訊、請參閱 link:../volumes/determine-space-usage-volume-aggregate-concept.html["判斷磁碟區或本機層的空間使用量"] 。

下列資料列會包含在中 `aggregate show-space` 命令輸出：

* * Volume Footprints *
+
本端層內所有磁碟區佔用空間的總計。它包含所有由包含本端層中所有磁碟區的所有資料和中繼資料所使用或保留的空間。

* * Aggregate中繼資料*
+
本機層所需的檔案系統中繼資料總數，例如分配點陣圖和 inode 檔案。

* * Snapshot保留*
+
根據磁碟區大小，保留給本機層快照的空間量。它被視為已用空間，無法用於 Volume 或本機層資料或中繼資料。

* * Snapshot保留不可用*
+
原本分配給本機層快照保留區的空間量，因為與本機層相關聯的磁碟區正在使用，因此無法用於本機層快照。只有在具有非零本機層快照保留的本機層才會發生。

* *使用總數*
+
依磁碟區，中繼資料或快照，在本機層中使用或保留的所有空間總和。

* *實際使用總量*
+
目前用於資料的空間量（而非保留供未來使用）。包括本機層快照所使用的空間。



以下範例顯示 `aggregate show-space`快照保留為 5% 之本機層的命令輸出。如果快照保留為 0 ，則不會顯示該列。

....
cluster1::> storage aggregate show-space

						Aggregate : wqa_gx106_aggr1

      Feature                                   Used      Used%
      --------------------------------    ----------     ------
      Volume Footprints                      101.0MB         0%
      Aggregate Metadata                       300KB         0%
      Snapshot Reserve                        5.98GB         5%

      Total Used                              6.07GB         5%
      Total Physical Used                    34.82KB         0%
....
.相關資訊
* link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Space_Usage["知識庫文章：空間使用"^]
* link:https://www.netapp.com/blog/free-up-storage-capacity-upgrade-ontap/["升級ONTAP 至更新版的更新版、即可釋放5%的儲存容量"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-space.html["儲存聚合展示空間"^]

