---
permalink: disks-aggregates/determine-control-volume-space-aggregate-concept.html 
sidebar: sidebar 
keywords: determine, control. volume, space usage, aggregate 
summary: 您可以判斷哪些FlexVol 等量磁碟區使用的是本機層（Aggregate）中最大的空間、以及磁碟區內的哪些功能。 
---
= 判斷及控制本機層中的磁碟區空間使用量（Aggregate）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以判斷哪些FlexVol 等量磁碟區使用的是本機層（Aggregate）中最大的空間、以及磁碟區內的哪些功能。

「Volume show-finage」命令提供磁碟區佔用空間或其在包含Aggregate內的空間使用量資訊。

「Volume show-f足跡」命令會顯示集合體中每個磁碟區的空間使用量詳細資料、包括離線磁碟區。此命令可彌補「Volume show-space"和「Aggregate show-space"命令的輸出之間的落差。所有百分比均以Aggregate大小的百分比計算。

以下範例顯示名為testvol.的Volume「Volume show-fout跡」命令輸出：

....
cluster1::> volume show-footprint testvol

      Vserver : thevs
      Volume  : testvol

      Feature                                   Used    Used%
      --------------------------------    ----------    -----
      Volume Data Footprint                  120.6MB       4%
      Volume Guarantee                        1.88GB      71%
      Flexible Volume Metadata               11.38MB       0%
      Delayed Frees                           1.36MB       0%
      Total Footprint                         2.01GB      76%
....
下表說明「Volume show-famage」命令輸出的一些關鍵列、以及您可以採取哪些行動來降低該功能的空間使用量：

|===


| 列/功能名稱 | 列的說明/內容 | 減少的方法 


 a| 
「Volume Data Footprint」
 a| 
使用中包含Aggregate的空間總量（依作用中檔案系統中的磁碟區資料）、以及磁碟區Snapshot複本所使用的空間。此列不包含保留空間。
 a| 
* 從磁碟區刪除資料。
* 從磁碟區刪除Snapshot複本。




 a| 
「Volume保證」
 a| 
磁碟區在Aggregate中保留的空間量、以供未來寫入。保留的空間量取決於磁碟區的保證類型。
 a| 
將磁碟區的保證類型變更為「無」。



 a| 
「彈性Volume中繼資料」
 a| 
磁碟區中繼資料檔案在集合中使用的空間總量。
 a| 
沒有直接的控制方法。



 a| 
《解放》
 a| 
用於ONTAP 效能的區塊、無法立即釋出。對於SnapMirror目的地、此列的值為「0」、不會顯示。
 a| 
沒有直接的控制方法。



 a| 
「檔案作業中繼資料」
 a| 
保留給檔案作業中繼資料的空間總量。
 a| 
沒有直接的控制方法。



 a| 
「總佔用空間」
 a| 
磁碟區在集合體中使用的空間總量。這是所有列的總和。
 a| 
用於減少磁碟區所用空間的任何方法。

|===
.相關資訊
http://["NetApp技術報告3483：NetApp SAN或IP SAN企業環境中的精簡配置"^]
