---
permalink: disks-aggregates/determine-modify-caching-policy-flash-pool-task.html 
sidebar: sidebar 
keywords: modify, cache, policy, flash pool, aggregate, local tier 
summary: 您可以將快取保留原則指派給 Flash Pool 本機層中的磁碟區，以決定磁碟區資料在 Flash Pool 快取中保留的時間長度。不過、在某些情況下、變更快取保留原則可能不會影響磁碟區資料保留在快取中的時間量。 
---
= 判斷是否要修改 Flash Pool 本機層的 ONTAP 快取原則
:allow-uri-read: 


[role="lead"]
您可以將快取保留原則指派給 Flash Pool 本機層中的磁碟區，以決定磁碟區資料在 Flash Pool 快取中保留的時間長度。不過、在某些情況下、變更快取保留原則可能不會影響磁碟區資料保留在快取中的時間量。

.關於這項工作
如果您的資料符合下列任一條件、變更快取保留原則可能不會造成影響：

* 您的工作負載是連續的。
* 您的工作負載不會重新讀取固態硬碟（SSD）中快取的隨機區塊。
* 磁碟區的快取大小太小。


.步驟
下列步驟會檢查資料必須符合的條件。工作必須在進階權限模式下使用CLI來完成。

. 使用CLI檢視工作負載Volume：
+
`statistics start -object workload_volume`

. 判斷Volume的工作負載模式：
+
`statistics show -object workload_volume -instance _volume-workload_ -counter sequential_reads`

. 判斷Volume的命中率：
+
`statistics show -object wafl_hya_vvol -instance _volume_ -counter read_ops_replaced_pwercent|wc_write_blks_overwritten_percent`

. 確定 `Cacheable Read` 和 `Project Cache Alloc` 磁碟區數量：
+
`system node run -node node_name wafl awa start _aggr_name_`

. 顯示AWA摘要：
+
`system node run -node node_name wafl awa print _aggr_name_`

. 將 Volume 的命中率與進行比較 `Cacheable Read`。
+
如果 Volume 的命中率大於 `Cacheable Read`然後、您的工作負載不會重新讀取 SSD 中快取的隨機區塊。

. 比較磁碟區目前的快取大小與 `Project Cache Alloc`。
+
如果磁碟區目前的快取大小大於 `Project Cache Alloc`，則您的磁碟區快取大小太小。



.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["統計數據顯示"^]

