---
permalink: disks-aggregates/disk-autoassignment-policy-concept.html 
sidebar: sidebar 
keywords: disk, auto-assign, spare, policy, automatic, assignment, disk ownership 
summary: 預設會啟用自動指派非擁有磁碟。自動磁碟擁有權指派會在系統初始化10分鐘後進行、在正常系統作業期間每5分鐘進行一次。 
---
= 關於自動指派磁碟擁有權
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
預設會啟用自動指派非擁有磁碟。自動磁碟擁有權指派會在系統初始化10分鐘後進行、在正常系統作業期間每5分鐘進行一次。

當您將新磁碟新增至系統時（例如、當更換故障磁碟、回應低備援訊息或新增容量時）、預設的自動指派原則會將磁碟的擁有權指派給節點作為備援磁碟。您可以停用自動指派、或使用選取不同的自動指派原則 `storage disk option modify` 命令。

預設的自動指派原則是根據平台特定的特性、但它使用下列其中一種方法來指派磁碟擁有權：

|===


| 指派方法 | 對節點指派的影響 | 平台 


 a| 
Bay
 a| 
偶數的磁碟槽會指派給節點A、而零編號的磁碟槽則指派給節點B
 a| 
HA組態中的入門級系統、搭配單一共享機櫃。



 a| 
機櫃
 a| 
磁碟櫃中的所有磁碟都會指派給節點A
 a| 
HA組態中的入門級系統、其中一堆是兩個或多個機櫃、MetroCluster 而每個節點有一個堆疊、兩個或多個機櫃則有一個堆疊的整套組態。



 a| 
分割機櫃
 a| 
機櫃左側的磁碟會指派給節點A、右側的磁碟則指派給節點B新系統上的部分磁碟櫃會從原廠出貨、並從磁碟櫃邊緣向中心裝入磁碟。
 a| 
不再需要使用某些功能組態MetroCluster AFF 。



 a| 
堆疊
 a| 
堆疊中的所有磁碟都會指派給節點A
 a| 
獨立式入門級系統及所有其他組態。

|===
如果您的環境不需要預設的指派方法、您可以使用指定機櫃、機櫃或堆疊指派方法 `-autoassign-policy` 的參數 `storage disk option modify` 命令。請注意下列規則：

* 如果您嘗試使用 `bay autoassign-policy` 對於非入門級平台、將會失敗。
* 沒有對應的非預設原則可用來指定分割機櫃方法。


您也可以使用手動管理磁碟指派 `storage disk assign` 命令。

* 如果停用自動指派、則新磁碟在指派給具有的節點之前、將無法作為備援磁碟使用 `storage disk assign` 命令。
* 如果您想要自動指派磁碟、而且您有多個堆疊或磁碟櫃必須擁有不同的擁有權、則必須在每個堆疊或磁碟櫃上手動指派一個磁碟、才能在每個堆疊或磁碟櫃上自動指派擁有權。
* 如果已啟用自動指派、且您手動將單一磁碟機指派給未在作用中原則中指定的節點、則自動指派會停止運作、並顯示EMS訊息。


深入瞭解 link:manual-assign-ownership-partitioned-disks-task.html["手動指派磁碟擁有權"]。

您可以使用顯示目前的自動指派設定 `storage disk option show` 命令。
