---
permalink: disks-aggregates/flash-pool-aggregate-caching-policies-concept.html 
sidebar: sidebar 
keywords: cache, flash pool, policy, local tier, aggregate 
summary: 快取原則會套用至位於Flash Pool本機層的磁碟區。您應該先瞭解快取原則的運作方式、再進行變更。 
---
= Flash Pool ONTAP 本機層快取原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Flash Pool 本機層中磁碟區的快取原則可讓您將 Flash 部署為高效能快取，以用於工作資料集，同時使用成本較低的 HDD 來處理較不常存取的資料。如果您要將快取提供給兩個以上的Flash Pool本機層、則應該使用Flash Pool SSD分割區、在Flash Pool的本機層級之間共用SSD。

快取原則會套用至位於Flash Pool本機層的磁碟區。您應該先瞭解快取原則的運作方式、再進行變更。

在大多數情況下，的預設快取原則 `auto`是要使用的最佳快取原則。只有在不同的原則為您的工作負載提供更好的效能時、才應該變更快取原則。設定錯誤的快取原則可能會嚴重降低磁碟區效能、效能降級可能會隨著時間逐漸增加。

快取原則結合了讀取快取原則和寫入快取原則。原則名稱會串連讀取快取原則和寫入快取原則的名稱、並以連字號分隔。如果原則名稱中沒有連字號，則寫入快取原則為 `none`，原則除外 `auto`。

除了HDD上儲存的資料、讀取快取原則也會在快取中放置資料複本、以最佳化未來的讀取效能。對於將資料插入快取以進行寫入作業的讀取快取原則、快取會以寫入快取的形式運作。

使用寫入快取原則插入快取的資料僅存在於快取中、HDD中沒有複本。Flash Pool快取受到RAID保護。啟用寫入快取可讓寫入作業中的資料立即從快取讀取、同時將資料延後寫入HDD、直到資料逾時離開快取為止。

如果您將磁碟區從 Flash Pool 本機層移至單一層本機層，它會遺失其快取原則；如果您稍後將其移回 Flash Pool 本機層，則會將預設的快取原則指派給該磁碟區 `auto`。如果您在兩個Flash Pool本機層之間移動磁碟區、快取原則會保留下來。



== 變更快取原則

您可以使用 CLI 來變更位於 Flash Pool 本機層的磁碟區快取原則 `-caching-policy` 參數 `volume create` 命令。

當您在 Flash Pool 本機層上建立磁碟區時，預設 `auto`會將快取原則指派給該磁碟區。
