---
permalink: disks-aggregates/manual-assign-ownership-partitioned-disks-task.html 
sidebar: sidebar 
keywords: manual, assign, disk, ownership, partition, disks 
summary: 您可以手動或使用自動指派來設定容器磁碟或分割區的擁有權、如同對未分割磁碟一樣。 
---
= 手動指派分割磁碟的擁有權總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用CLI、您可以手動或使用自動指派來設定容器磁碟或分割區的擁有權、就像對未分割磁碟一樣。

[NOTE]
====
如果容器磁碟在半滿的磁碟櫃中故障並被更換、ONTAP 則不會自動指派擁有權。在此情況下、任何新磁碟的指派都必須手動完成。若要在半滿的磁碟櫃上執行自動指派作業、請將磁碟平均放置在下半和6的最右側磁碟櫃上、以開始進行。也就是6個磁碟從托架0-5、以及6個磁碟從托架18-23。在配置了ADP的系統中指派容器磁碟之後、ONTAP軟體將會處理所需的任何分割區和分割區指派、而無需使用者介入。

====
您可以在CLI中執行下列工作：

.使用根資料分割區手動指派磁碟
====
對於根資料分割、HA配對共有三個擁有實體（容器磁碟和兩個分割區）。

只要所有容器磁碟和兩個分割區都是由HA配對中的其中一個節點所擁有、HA配對中的所有節點就不一定都需要由同一個節點擁有。但是、當您在本機層（Aggregate）中使用分割區時、它必須由擁有本機層的同一個節點擁有。

.步驟
. 使用CLI顯示分割磁碟的目前擁有權：
+
「torage disk show -disk _disk_name_-partition-Ouge」

. 將CLI權限等級設為進階：
+
"進階權限"

. 根據您要指派所有權的所有權實體、輸入適當的命令：
+
[cols="25,75"]
|===


| 如果您要指派...的擁有權 | 使用此命令... 


 a| 
Container磁碟
 a| 
'磁碟指派磁碟磁碟_disk_name_-Owner_Owner_name_'



 a| 
資料分割區
 a| 
'磁碟指派磁碟磁碟_disk_name_-Owner_Owner_name_-data true'



 a| 
根分割區
 a| 
'磁碟指派磁碟磁碟_disk_name_-Owner_Owner_name_-root true '

|===
+
如果任何所有權實體已經擁有、則必須包含「-force」選項。



====
.使用root資料資料分割區手動指派磁碟
====
對於根資料資料分割、HA配對共有四個擁有實體（容器磁碟和三個分割區）。

根資料資料分割會建立一個小型分割區做為根分割區、並建立兩個較大、大小相同的資料分割區。

參數必須與「磁碟指派」命令搭配使用、才能指派根資料分割磁碟的適當分割區。這些參數無法搭配儲存資源池中的磁碟使用。預設值為「'假'」。

* data1 true參數會指派root資料a1資料2分割磁碟的「dataa1」分割區。
* data2 true'參數會指派根資料a1資料2分割磁碟的「data 2」分割區。


.步驟
. 使用CLI顯示分割磁碟的目前擁有權：
+
「torage disk show -disk _disk_name_-partition-Ouge」

. 將CLI權限等級設為進階：
+
"進階權限"

. 根據您要指派所有權的所有權實體、輸入適當的命令：
+
[cols="25,75"]
|===


| 如果您要指派...的擁有權 | 使用此命令... 


 a| 
Container磁碟
 a| 
'磁碟指派磁碟磁碟_disk_name_-Owner_Owner_name_'



 a| 
Data1分割區
 a| 
"torage disk assign -disk _disk_name_-Owner_Owner_name_-data1 true（磁碟指派-disk _disk_name_-Owner_name_-data1真）"



 a| 
Data2分割區
 a| 
「torage disk assign -disk _disk_name_-Owner_Owner_name_-data2 true」



 a| 
根分割區
 a| 
'磁碟指派磁碟磁碟_disk_name_-Owner_Owner_name_-root true '

|===


如果任何所有權實體已經擁有、則必須包含「-force」選項。

====