---
permalink: disks-aggregates/relocate-aggregate-ownership-task.html 
sidebar: sidebar 
keywords: relocate, aggregate, ownership, local tier 
summary: 您只能在 HA 配對內的節點之間變更本機層的擁有權。 
---
= 在 HA 配對中重新配置 ONTAP 本機層的擁有權
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在 HA 配對中的節點之間變更本機層的擁有權，而不會中斷本機層的服務。


NOTE: 在 ONTAP 9.7 之前，系統管理員使用術語 _Aggregate _ 來描述 _ 本機層 _ 。無論您的 ONTAP 版本為何， ONTAP CLI 都會使用術語 _Aggregate 。若要深入瞭解本機階層，請參閱link:../disks-aggregates/index.html["磁碟和本機層"]。

HA配對中的兩個節點均實體連線至彼此的磁碟或陣列LUN。每個磁碟或陣列LUN均由其中一個節點擁有。

當接管發生時，本機層內所有磁碟或陣列 LUN 的擁有權會暫時從一個節點變更為另一個節點。不過、本地層的重新配置作業也可能永久變更擁有權（例如、如果已完成負載平衡）。所有權會在不進行任何資料複製程序或實體移動磁碟或陣列LUN的情況下變更。

.關於這項工作
* 由於磁碟區數限制是在本機層重新配置作業期間以程式設計方式驗證、因此不需要手動檢查。
+
如果Volume數超過支援的上限、則本機層重新配置作業會失敗、並顯示相關的錯誤訊息。

* 當來源節點或目的地節點上的系統層級作業正在進行時、您不應該啟動本機層重新配置；同樣地、您也不應該在本機層重新配置期間啟動這些作業。
+
這些作業包括：

+
** 接管
** GiveBack
** 關機
** 另一個本地層重新配置作業
** 磁碟擁有權變更
** 本機層級或磁碟區組態作業
** 更換儲存控制器
** 升級ONTAP
** 還原ONTAP


* 如果您有MetroCluster 一個支援功能組態、則不應在災難恢復作業（_switchover、_rec修復_或_switchback）進行期間、啟動本機層重新配置。
* 如果您有MetroCluster 一個不穩定組態、並在交換式本機層上啟動本機層重新配置、則作業可能會失敗、因為它超過DR合作夥伴的Volume限制數。
* 您不應在毀損或正在進行維護的本機層上啟動本機層重新定位。
* 在初始化本機層重新配置之前、您應該先在來源和目的地節點上儲存任何核心傾印。


.步驟
. 檢視節點上的本機層，以確認要移動的本機層，並確保它們處於線上狀態且狀況良好：
+
`storage aggregate show -node _source-node_`

+
下列命令顯示叢集中四個節點上的六個本機層。所有本地層都在線上。node1和node3形成HA配對、Node2和Node4形成HA配對。

+
[listing]
----
cluster::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes  RAID Status
--------- -------- --------- ----- ------- ------ ------ -----------
aggr_0     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_1     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_2     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_3     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_4     239.0GB   238.9GB    0% online       5 node3  raid_dp,
                                                         normal
aggr_5     239.0GB   239.0GB    0% online       4 node4  raid_dp,
                                                         normal
6 entries were displayed.
----
. 發出命令以啟動本機層重新定位：
+
`storage aggregate relocation start -aggregate-list _aggregate-1_, _aggregate-2_... -node _source-node_ -destination _destination-node_`

+
以下命令將本地層 agger_1 和 agger_2 從 Node1 移至 node3 。node3是Node1的HA合作夥伴。只能在 HA 配對中移動本機層。

+
[listing]
----
cluster::> storage aggregate relocation start -aggregate-list aggr_1, aggr_2 -node node1 -destination node3
Run the storage aggregate relocation show command to check relocation status.
node1::storage aggregate>
----
. 使用命令監控本地層重新定位的進度 `storage aggregate relocation show`：
+
`storage aggregate relocation show -node _source-node_`

+
以下命令顯示要移至 node3 的本地層的進度：

+
[listing]
----
cluster::> storage aggregate relocation show -node node1
Source Aggregate   Destination    Relocation Status
------ ----------- -------------  ------------------------
node1
       aggr_1      node3          In progress, module: wafl
       aggr_2      node3          Not attempted yet
2 entries were displayed.
node1::storage aggregate>
----
+
重新定位完成後，此命令的輸出會顯示每個本機層的重新定位狀態為「 Done 」。



.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-relocation-show.html["儲存聚合搬遷展示"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-relocation-start.html["儲存聚合遷移開始"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show.html["儲存Aggregate顯示"^]

