---
permalink: disks-aggregates/relocate-aggregate-ownership-task.html 
sidebar: sidebar 
keywords: relocate, aggregate, ownership 
summary: 您只能在HA配對內的節點之間變更Aggregate的擁有權。 
---
= 重新配置Aggregate所有權
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以變更HA配對中節點之間的集合體擁有權、而不中斷集合體的服務。

HA配對中的兩個節點均實體連線至彼此的磁碟或陣列LUN。每個磁碟或陣列LUN均由其中一個節點擁有。雖然在發生接管時、磁碟的擁有權會暫時變更、但集合重新配置作業可能會永久（例如、如果是為了負載平衡而執行）、也可能會暫時（例如、如果是在接管過程中執行）。 將集合體內所有磁碟或陣列LUN的擁有權從一個節點變更為另一個節點。所有權會在不進行任何資料複製程序或實體移動磁碟或陣列LUN的情況下變更。

.關於這項工作
* 由於磁碟區數限制是在集合體重新配置作業期間以程式設計方式驗證、因此不需要手動檢查。
+
如果磁碟區數超過支援的上限、則Aggregate重新配置作業會失敗、並顯示相關的錯誤訊息。

* 當來源節點或目的地節點上的系統層級作業正在進行時、您不應該啟動集合體重新配置；同樣地、您也不應該在集合體重新配置期間啟動這些作業。
+
這些作業包括：

+
** 接管
** GiveBack
** 關機
** 另一個Aggregate重新配置作業
** 磁碟擁有權變更
** Aggregate或Volume組態作業
** 更換儲存控制器
** 升級ONTAP
** 還原ONTAP


* 如果您使用MetroCluster 的是支援的組態、則不應在災難恢復作業（_switchover、_rec修復_或_switchback）進行期間啟動集合體重新配置。
* 如果您擁有MetroCluster 一個不穩定組態、並在交換式Aggregate上起始集合體重新配置、則作業可能會因為超出DR合作夥伴的Volume限制數而失敗。
* 您不應在毀損或正在進行維護的集合體上啟動集合體重新配置。
* 在初始化Aggregate重新配置之前、您應該先在來源和目的地節點上儲存任何核心傾印。


.步驟
. 檢視節點上的集合體、確認要移動哪些集合體、並確保它們處於線上狀態且狀況良好：
+
「torage Aggregate show -node-nodE_」

+
下列命令顯示叢集中四個節點上的六個集合體。所有的集合體都在線上。node1和node3形成HA配對、Node2和Node4形成HA配對。

+
[listing]
----
cluster::> storage aggregate show
Aggregate     Size Available Used% State   #Vols  Nodes  RAID Status
--------- -------- --------- ----- ------- ------ ------ -----------
aggr_0     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_1     239.0GB   11.13GB   95% online       1 node1  raid_dp,
                                                         normal
aggr_2     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_3     239.0GB   11.13GB   95% online       1 node2  raid_dp,
                                                         normal
aggr_4     239.0GB   238.9GB    0% online       5 node3  raid_dp,
                                                         normal
aggr_5     239.0GB   239.0GB    0% online       4 node4  raid_dp,
                                                         normal
6 entries were displayed.
----
. 發出命令以啟動Aggregate重新配置：
+
「torage aggregate regate regate regate regate regate start -gregate list _gregate 1 _、_gregate 2」... -node-source-nod__-destination _destination-nod__

+
下列命令可將Agggr_1和aggr_2從Node1移至node3。node3是Node1的HA合作夥伴。只能在HA配對內移動集合體。

+
[listing]
----
cluster::> storage aggregate relocation start -aggregate-list aggr_1, aggr_2 -node node1 -destination node3
Run the storage aggregate relocation show command to check relocation status.
node1::storage aggregate>
----
. 使用「shorage aggregate regate reg搬 移show」命令來監控集合體重新配置的進度：
+
「torage Aggregate or搬 移顯示-node/source-nodE_」

+
以下命令顯示要移至節點3的集合體進度：

+
[listing]
----
cluster::> storage aggregate relocation show -node node1
Source Aggregate   Destination    Relocation Status
------ ----------- -------------  ------------------------
node1
       aggr_1      node3          In progress, module: wafl
       aggr_2      node3          Not attempted yet
2 entries were displayed.
node1::storage aggregate>
----
+
重新配置完成後、此命令的輸出會顯示每個Aggregate的重新配置狀態為「Done」。


