---
permalink: disks-aggregates/sanitize-disk-maintenance-mode-task.html 
sidebar: sidebar 
keywords: sanitize, disk, maintenance mode, nodeshell, node shell, sanitization 
summary: 從功能支援支援的9.6開始ONTAP 、您可以在維護模式下執行磁碟資料抹除。這可讓您從已停用或無法運作的系統上的磁碟或磁碟集移除資料、使資料永遠無法恢復。 
---
= 清理 ONTAP 磁碟
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
清理磁碟可讓您從已停用或無法運作的系統上的磁碟或磁碟集移除資料、使資料永遠無法恢復。

有兩種方法可以使用CLI對磁碟進行資料抹除：

.使用 &#8220; 維護模式 &#8221; 命令清理磁碟
[%collapsible]
====
從功能支援支援的9.6開始ONTAP 、您可以在維護模式下執行磁碟資料抹除。

.開始之前
* 磁碟不能是自我加密磁碟（SED）。
+
您必須使用 `storage encryption disk sanitize` 用於清理 SED 的命令。

+
link:../encryption-at-rest/index.html["加密閒置的資料"]

+
如link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-sanitize.html["指令參考資料ONTAP"^]需詳細 `storage encryption disk sanitize`資訊，請參閱。



.步驟
. 開機進入維護模式。
+
.. 輸入結束目前的Shell `halt`。
+
隨即顯示載入程式提示。

.. 進入維護模式 `boot_ontap maint`。
+
顯示部分資訊後、會顯示維護模式提示。



. 如果您要清理的磁碟已分割、請取消分割每個磁碟：
+

NOTE: 取消磁碟分割的命令只能在診斷層級使用、而且只能在NetApp支援監督下執行。強烈建議您先聯絡NetApp支援部門、再繼續進行。
您也可以參閱知識庫文章 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["如何在ONTAP 支援的情況下取消磁碟分割"^]

+
`disk unpartition <disk_name>`

. 清除指定的磁碟：
+
`disk sanitize start [-p <pattern1>|-r [-p <pattern2>|-r [-p <pattern3>|-r]]] [-c <cycle_count>] <disk_list>`

+

NOTE: 切勿關閉節點的電源、中斷儲存連線、或是在清理時移除目標磁碟。如果在格式化階段中斷掃毒、則必須重新啟動格式化階段、並允許在磁碟經過消毒並準備好返回備用集區之前完成。如果您需要中止清理程序、可以使用來中止 `disk sanitize abort` 命令。如果指定的磁碟正在進行資料抹除的格式化階段、則在該階段完成之前不會發生中止。

+
 `-p` `<pattern1>` `-p` `<pattern2>` `-p` `<pattern3>`指定一個由一到三個使用者定義的十六進位位位元組覆寫模式的週期，可連續套用至正在進行清理的磁碟。預設模式為三次通過、第一次使用的是0x55、第二次使用的是0xAA、第三次使用的是0x3c。

+
`-r` 以隨機覆寫取代任何或所有 Pass 的模式覆寫。

+
`-c` `<cycle_count>`指定套用指定覆寫模式的次數。預設值為一個週期。最大值為七個週期。

+
`<disk_list>`指定要清理的備用磁碟 ID 的空間分隔清單。

. 如有需要、請檢查磁碟清理程序的狀態：
+
`disk sanitize status [<disk_list>]`

. 在資料抹除程序完成後、將每個磁碟的磁碟恢復為備援狀態：
+
`disk sanitize release <disk_name>`

. 結束維護模式。


====
.使用&#8220清理磁碟；節點和#8221；命令（所有ONTAP 版本均為9）
[%collapsible]
====
在節點上使用 nodesdesh 命令啟用磁碟清理功能之後，就無法停用該功能。

.開始之前
* 磁碟必須是備用磁碟；它們必須由節點擁有，但不能用於本機層。
+
如果磁碟已分割，則兩個磁碟分割都不能在本機層中使用。

* 磁碟不能是自我加密磁碟（SED）。
+
您必須使用 `storage encryption disk sanitize` 用於清理 SED 的命令。

+
link:../encryption-at-rest/index.html["加密閒置的資料"]

* 磁碟不能是儲存資源池的一部分。


.步驟
. 如果您要清理的磁碟已分割、請取消分割每個磁碟：
+
--

NOTE: 取消磁碟分割的命令只能在診斷層級使用、而且只能在NetApp支援監督下執行。** 強烈建議您在繼續之前聯絡 NetApp 支援中心。 ** 您也可以參閱知識庫文件 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Systems/FAS_Systems/How_to_unpartition_a_spare_drive_in_ONTAP["如何在ONTAP 支援的情況下取消磁碟分割"^]。

--
+
`disk unpartition <disk_name>`

. 輸入要清理磁碟的節點節點節點的節點節點節點：
+
`system node run -node <node_name>`

. 啟用磁碟資料抹除：
+
`options licensed_feature.disk_sanitization.enable on`

+
系統會要求您確認命令、因為命令無法還原。

. 切換至節點的進階權限層級：
+
`priv set advanced`

. 清除指定的磁碟：
+
`disk sanitize start [-p <pattern1>|-r [-p <pattern2>|-r [-p <pattern3>|-r]]] [-c <cycle_count>] <disk_list>`

+

NOTE: 請勿關閉節點電源、中斷儲存連線或移除目標
磁碟正在進行掃毒。如果在格式化階段中斷清理、則會中斷格式化
必須重新啟動階段、並允許在磁碟進行清理並準備就緒之前完成
已返回備援集區。如果您需要中止清理程序、您可以使用磁碟清理來進行
中止命令。如果指定的磁碟正在進行資料清理的格式化階段、則會執行
在階段完成之前不會發生中止。

+
`-p <pattern1> -p <pattern2> -p <pattern3>`指定一個由一到三個使用者定義的十六進位位位元組覆寫模式的週期，可連續套用至正在進行清理的磁碟。預設模式為三次通過、第一次使用的是0x55、第二次使用的是0xAA、第三次使用的是0x3c。

+
`-r` 以隨機覆寫取代任何或所有 Pass 的模式覆寫。

+
`-c <cycle_count>`指定套用指定覆寫模式的次數。

+
預設值為一個週期。最大值為七個週期。

+
`<disk_list>`指定要清理的備用磁碟 ID 的空間分隔清單。

. 若要檢查磁碟資料抹除程序的狀態：
+
`disk sanitize status [<disk_list>]`

. 在資料抹除程序完成後、將磁碟恢復為備援狀態：
+
`disk sanitize release <disk_name>`

. 返回nodesdro重 管理權限層級：
+
`priv set admin`

. 返回ONTAP 到CLI：
+
`exit`

. 確定所有磁碟是否都返回到備援狀態：
+
`storage aggregate show-spare-disks`

+
[cols="1,2"]
|===


| 如果... | 然後... 


| 所有已消毒的磁碟均列為備援磁碟 | 您已完成。磁碟已消毒且處於備援狀態。 


| 部分已消毒的磁碟並未列為備援磁碟  a| 
完成下列步驟：

.. 進入進階權限模式：
+
`set -privilege advanced`

.. 將未指派的已消毒磁碟指派給每個磁碟的適當節點：
+
`storage disk assign -disk <disk_name> -owner <node_name>`

.. 將每個磁碟的磁碟恢復為備援狀態：
+
`storage disk unfail -disk <disk_name> -s -q`

.. 返回管理模式：
+
`set -privilege admin`



|===
+
如link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-show-spare-disks.html["指令參考資料ONTAP"^]需詳細 `storage aggregate show-spare-disks`資訊，請參閱。



====
.結果
指定的磁碟會經過消毒並指定為熱備援磁碟。已清理磁碟的序號會寫入 `/etc/log/sanitized_disks`。

指定磁碟的清理記錄會寫入，顯示每個磁碟上完成的內容 `/mroot/etc/log/sanitization.log`。

.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=storage+aggregate+show["儲存Aggregate顯示"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-assign.html["儲存磁碟分配"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-disk-unfail.html["儲存磁碟未故障"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-encryption-disk-sanitize.html["儲存加密磁碟清理"^]

