---
permalink: disks-aggregates/set-cache-data-retention-policy-flash-pool-task.html 
sidebar: sidebar 
keywords: set, cache-retention policy, flash pool 
summary: 您可以將快取保留原則指派給Flash Pool本機層（Aggregate）中的磁碟區。具有高快取保留原則的磁碟區中的資料會保留在快取中的時間更長、而具有低快取保留原則的磁碟區中的資料會更快移除。如此可讓高優先順序的資訊以更快的速度存取更長的時間、進而提升關鍵工作負載的效能。 
---
= 設定Flash Pool本機層（Aggregate）的快取保留原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將快取保留原則指派給Flash Pool本機層（Aggregate）中的磁碟區。具有高快取保留原則的磁碟區中的資料會保留在快取中的時間更長、而具有低快取保留原則的磁碟區中的資料會更快移除。如此可讓高優先順序的資訊以更快的速度存取更長的時間、進而提升關鍵工作負載的效能。

.開始之前
您應該知道您的系統是否有任何可能妨礙快取保留原則影響資料保留在快取中的時間長度的情況。

.步驟
以進階權限模式使用CLI執行下列步驟：

. 將權限設定變更為進階：
+
`set -privilege advanced`

. 驗證磁碟區的快取保留原則：
+
根據預設、快取保留原則為「正常」。

. 設定快取保留原則：
+
|===


| 版本ONTAP | 命令 


 a| 
版本9.0、ONTAP 9.1
 a| 
`priority hybrid-cache set volume_name read-cache=read_cache_value write-cache=write_cache_value cache-retention-priority=cache_retention_policy`

設定 `cache_retention_policy` 至 `high` 適用於您想要在快取中保留更久的資料。設定 `cache_retention_policy` 至 `low` 適用於您想要更快從快取移除的資料。



 a| 
0 ： 2 或更新版本 ONTAP
 a| 
`volume modify -volume volume_name -vserver vserver_name -caching-policy policy_name.`

|===
. 確認磁碟區的快取保留原則已變更為您選取的選項。
. 將權限設定傳回給admin：
+
`set -privilege admin`


