---
permalink: flexgroup/convert-flexvol-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: convert, flexvol, volume, snapmirror, relation, flexgroup 
summary: 若要將FlexVol 位於FlexGroup SnapMirror中的SnapMirror與不景區的SnapMirror關係轉換成不景區的SnapMirror關係ONTAP 、您必須先轉換目的地FlexVol 的SnapMirror Volume、再轉換來源FlexVol 的不景區。 
---
= 將 ONTAP FlexVol volume SnapMirror 關係轉換為 ONTAP FlexGroup Volume SnapMirror 關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要將FlexVol 位於FlexGroup SnapMirror中的SnapMirror與不景區的SnapMirror關係轉換成不景區的SnapMirror關係ONTAP 、您必須先轉換目的地FlexVol 的SnapMirror Volume、再轉換來源FlexVol 的不景區。

.關於這項工作
* 在SnapMirror/ SnapVault關係中，除了轉換流程之外，不支援將 FlexGroups 與FlexVol磁碟區混合使用。
* FlexGroup 轉換僅支援 SnapMirror 非同步關係。
* SnapMirror雲端關係不支援FlexGroup轉換。
* 轉換時間取決於多個變數。其中一些變數包括：
+
** 控制器的 CPU
** 其他應用程式 CPU 的使用率
** 初始快照中的資料量
** 網路頻寬
** 其他應用程式使用的頻寬




.開始之前
* 正在轉換的這個版本必須在線上。FlexVol
* SnapMirror關係中的來源FlexVol 供應區不可以是多個SnapMirror關係的來源磁碟區。
+
從ONTAP 支援的範圍僅為0.9.1.1開始、FlexGroup 即可支援針對SnapMirror的範圍。如需更多資訊、請參閱 link:../flexgroup/create-snapmirror-cascade-fanout-reference.html#considerations-for-creating-cascading-relationships["為 FlexGroup 磁碟區建立 SnapMirror 串聯和展開關係的考量事項"]。

* 在這個過程中、執行的操作和設定FlexVol 必須與轉換程序相容。
+
如果FlexVol 現象不一致、而且中止了Volume轉換、就會產生錯誤訊息。您可以採取修正行動、然後重試轉換。



.步驟
. 驗證 SnapMirror 關係是否健全：
+
[source, cli]
----
snapmirror show
----
+
只能轉換XDP類型的鏡射關係。

+
範例：

+
[listing]
----
cluster2::> snapmirror show
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:src_dpv DP   vs2:dst_dpv  Snapmirrored
                                      Idle           -         true    -
vs0:src_xdp XDP  vs2:dst_xdp  Snapmirrored
                                      Idle           -         true    -
----
. 確認來源Volume是否相容於轉換：
+
.. 登入進階權限模式：
+
[source, cli]
----
set -privilege advanced
----
.. 驗證轉換程序：
+
[source, cli]
----
volume conversion start -vserver <src_svm_name> -volume <src_vol> -check-only true
----
+
範例：

+
[listing]
----
volume conversion start -vserver vs1 -volume src_vol -check-only true
----
+
在轉換磁碟區之前、您必須先修正所有錯誤。



. 將目的地FlexVol 的聲音量轉換為FlexGroup 聲音量。
+
.. 使 FlexVol SnapMirror 關係不再運作：
+
[source, cli]
----
snapmirror quiesce -destination-path <dest_svm:dest_volume>
----
+
範例：

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs2:dst_xdp
----
.. 開始轉換：
+
[source, cli]
----
volume conversion start -vserver <dest_svm> -volume <dest_volume>
----
+
範例：

+
[listing]
----
cluster-1::> volume conversion start -vserver vs2 -volume dst_xdp

Warning: After the volume is converted to a FlexGroup, it will not be possible
to change it back to a flexible volume.
Do you want to continue? {y|n}: y

[Job 510] Job succeeded: SnapMirror destination volume "dst_xdp" has been successfully converted to a FlexGroup volume.
You must now convert the relationship's source volume, "vs0:src_xdp", to a FlexGroup.
Then, re-establish the SnapMirror relationship using the "snapmirror resync" command.
----


. 將來源 FlexVol Volume 轉換為 FlexGroup Volume ： `
+
[source, cli]
----
volume conversion start -vserver <src_svm_name> -volume <src_vol_name>
----
+
範例：

+
[listing]
----
cluster-1::> volume conversion start -vserver vs0 -volume src_xdp

Warning: Converting flexible volume "src_xdp" in Vserver "vs0" to a FlexGroup
         will cause the state of all Snapshot copies from the volume to be set
         to "pre-conversion". Pre-conversion snapshots cannot be
         restored.
Do you want to continue? {y|n}: y
[Job 57] Job succeeded: success
----
. 重新同步關係：
+
[source, cli]
----
snapmirror resync -destination-path dest_svm_name:dest_volume
----
+
範例：

+
[listing]
----
cluster2::> snapmirror resync -destination-path vs2:dst_xdp
----


.完成後
您必須確保當來源FlexGroup 的供應區擴大以包含更多成分時、目的地Volume也會隨之擴充。

.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["SnapMirror靜止"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["SnapMirror 重新同步"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["SnapMirror 顯示"^]

