---
permalink: flexgroup/convert-flexvol-svm-dr-relationship-task.html 
sidebar: sidebar 
keywords: convert, flexvol, flexgroup, svm-dr 
summary: 從ONTAP SVM-DR FlexVol 來源開始、您可以將一個Svm-DR Volume轉換成FlexGroup 一個Svm-DR Volume。 
---
= 將 ONTAP FlexVol Volume 轉換為 SVM-DR 關係中的 FlexGroup Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP SVM-DR FlexVol 來源開始、您可以將一個Svm-DR Volume轉換成FlexGroup 一個Svm-DR Volume。

.開始之前
* 正在轉換的這個版本必須在線上。FlexVol
* 在這個過程中、執行的操作和設定FlexVol 必須與轉換程序相容。
+
如果FlexVol 現象不一致、而且取消了Volume轉換、就會產生錯誤訊息。您可以採取修正行動、然後重試轉換。
如需詳細資料、請參閱 link:convert-flexvol-concept.html["將FlexVol 功能區轉換FlexGroup 為功能區的考量事項"]



.步驟
. 使用進階權限模式登入： `set -privilege advanced`
. 從目的地更新SVM-DR關係：
+
[source, cli]
----
snapmirror update -destination-path <destination_svm_name>: -source-path <source_svm_name>:
----
+
[NOTE]
====
您必須在選項中的 SVM 名稱之後輸入一個冒號（：） `-destination-path` 。

====
. 確保SVM-DR關係處於Snapor不可 中斷的狀態：
+
[source, cli]
----
snapmirror show
----
. 從目的地SVM、確認FlexVol 支援的不只是支援轉換的功能：
+
[source, cli]
----
volume conversion start -vserver <svm_name> -volume <vol_name> -check-only true
----
+
如果此命令產生「這是目的地SVMDR Volume」以外的任何錯誤、您可以採取適當的修正行動、再次執行命令、然後繼續轉換。

. 從目的地停用SVM-DR關係上的傳輸：
+
[source, cli]
----
snapmirror quiesce -destination-path <dest_svm>:
----
+
[NOTE]
====
您必須在選項中的 SVM 名稱之後輸入一個冒號（：） `-destination-path` 。

====
. 從來源叢集開始轉換：
+
[source, cli]
----
volume conversion start -vserver <svm_name> -volume <vol_name>
----
. 確認轉換成功：
+
[source, cli]
----
volume show <vol_name> -fields volume-style-extended,state
----
+
[listing]
----
cluster-1::*> volume show my_volume -fields volume-style-extended,state

vserver  volume     state    volume-style-extended
-------  ---------  ------   ---------------------
vs0      my_volume  online   flexgroup
----
. 從目的地叢集繼續傳輸關係：
+
[source, cli]
----
snapmirror resume -destination-path <dest_svm>:
----
+
[NOTE]
====
您必須在選項中的 SVM 名稱之後輸入一個冒號（：） `-destination-path` 。

====
. 從目的地叢集執行更新、將轉換傳播到目的地：
+
[source, cli]
----
snapmirror update -destination-path <dest_svm>:
----
+
[NOTE]
====
您必須在選項中的 SVM 名稱之後輸入一個冒號（：） `-destination-path` 。

====
. 確保SVM-DR關係處於Snap/快照狀態、且不會中斷：
+
[source, cli]
----
snapmirror show
----
. 確保轉換發生在目的地：
+
[source, cli]
----
volume show <vol_name> -fields volume-style-extended,state
----
+
[listing]
----
cluster-2::*> volume show my_volume -fields volume-style-extended,state

vserver  volume     state   volume-style-extended
-------  -------    ------  ---------------------
vs0_dst  my_volume  online  flexgroup
----


.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resume.html["SnapMirror 履歷"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["SnapMirror靜止"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["SnapMirror 顯示"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["SnapMirror 更新"^]

