---
permalink: flexgroup/create-snapvault-relationship-task.html 
sidebar: sidebar 
keywords: create, snapvault, relationship, flexgroup, volumes 
summary: 您可以設定SnapVault 一個靜態關係、並為SnapVault 該關係指派一個不支援的原則、以建立SnapVault 一個不支援的備份。 
---
= 為 ONTAP FlexGroup 磁碟區建立 SnapVault 關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定SnapVault 一個靜態關係、並為SnapVault 該關係指派一個不支援的原則、以建立SnapVault 一個不支援的備份。

.開始之前
您必須瞭解建立SnapVault 有關本區的不景點關係的考量FlexGroup 事項。

.步驟
. 建立類型的目的地 FlexGroup Volume `DP` 其組成數量與來源 FlexGroup Volume 的組成數量相同：
+
.. 從來源叢集中、判斷來源 FlexGroup Volume 中的組成數量： `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster1::> volume show  -volume src* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vss       src          -            online     RW         400TB   172.86GB  56%
vss       src__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vss       src__0002    aggr1        online     RW         25TB    10.86TB   56%
vss       src__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vss       src__0004    aggr1        online     RW         25TB    10.73TB   57%
vss       src__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vss       src__0006    aggr1        online     RW         25TB    10.64TB   57%
vss       src__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----
.. 從目的地叢集建立類型的目的地 FlexGroup Volume `DP` 其組成數量與來源 FlexGroup Volume 相同。
+
[listing]
----
cluster2::> volume create -vserver vsd -aggr-list aggr1,aggr2 -aggr-list-multiplier 8 -size 400TB -type DP dst

Warning: The FlexGroup volume "dst" will be created with the following number of constituents of size 25TB: 16.
Do you want to continue? {y|n}: y
[Job 766] Job succeeded: Successful
----
.. 從目的地叢集、確認目的地 FlexGroup Volume 中的組成數量： `volume show -volume volume_name* -is-constituent true`
+
[listing]
----
cluster2::> volume show  -volume dst* -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vsd       dst          -            online     RW         400TB   172.86GB  56%
vsd       dst__0001    Aggr_cmode   online     RW         25GB    10.86TB   56%
vsd       dst__0002    aggr1        online     RW         25TB    10.86TB   56%
vsd       dst__0003    Aggr_cmode   online     RW         25TB    10.72TB   57%
vsd       dst__0004    aggr1        online     RW         25TB    10.73TB   57%
vsd       dst__0005    Aggr_cmode   online     RW         25TB    10.67TB   57%
vsd       dst__0006    aggr1        online     RW         25TB    10.64TB   57%
vsd       dst__0007    Aggr_cmode   online     RW         25TB    10.63TB   57%
...
----


. 建立工作排程： `job schedule cron create -name job_name -month month -dayofweek day_of_week -day day_of_month -hour hour -minute minute`
+
適用於 `-month`、 `-dayofweek`和 `-hour`，您可以指定 `all` 可分別在每月、每週的某一天和每小時運行作業。

+
以下範例建立名為的工作排程 `my_weekly` 週六上午 3 ： 00 開始：

+
[listing]
----
cluster1::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. 建立SnapVault 一套不規則的原則、然後定義SnapVault 一套適用於該決策的規則：
+
.. 建立類型的自訂原則 `vault` 對於 SnapVault 關係： `snapmirror policy create -vserver svm_name -policy policy_name -type vault`
.. 為 SnapVault 原則定義規則，以決定在初始化和更新作業期間傳輸哪些快照： `snapmirror policy add-rule -vserver svm_name -policy policy_for_rule - snapmirror-label snapmirror-label -keep retention_count -schedule schedule`


+
如果您未建立自訂原則、則應指定 `XDPDefault` SnapVault 關係原則。

. 建立 SnapVault 關係： `snapmirror create -source-path src_svm:src_flexgroup -destination-path dest_svm:dest_flexgroup -type XDP -schedule schedule_name -policy XDPDefault`
+
在 ONTAP 9.4 及更早版本中、如果原則未使用指定 `snapmirror create` 命令 `MirrorAllSnapshots` 原則預設為使用。在 ONTAP 9.5 中、如果原則未使用指定 `snapmirror create` 命令 `MirrorAndVault` 原則預設為使用。

+
[listing]
----
cluster2::> snapmirror create -source-path vss:srcFG -destination-path vsd:dstFG -type XDP -schedule Daily -policy XDPDefault
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["指令參考資料ONTAP"^]需詳細 `snapmirror create`資訊，請參閱。

. 從目的地叢集執行基準傳輸來初始化 SnapVault 關係： `snapmirror initialize -destination-path dest_svm:dest_flexgroup`
+
[listing]
----
cluster2::> snapmirror initialize -destination-path vsd:dst
Operation is queued: snapmirror initialize of destination "vsd:dst".
----


.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror建立"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["SnapMirror初始化"^]

