---
permalink: flexgroup/fast-directory-delete-asynchronous-task.html 
sidebar: sidebar 
keywords: perform, directory, delete, files, asynchronous, share, flexvol, flex vol, flexgroup, flex group, cancel 
summary: 從ONTAP 功能表9.8開始、您可以使用Volume檔案as同步 刪除命令、從Linux和Windows用戶端共用的背景中刪除檔案和目錄。您可以在FlexVol 支援的功能區和FlexGroup 功能區上執行非同步刪除。 
---
= 以非同步方式刪除叢集上的目錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9 8 開始、您可以使用非同步刪除功能、以非同步方式（也就是背景）刪除 Linux 和 Windows 用戶端共用的目錄。叢集與SVM管理員可以在FlexVol 支援的功能區執行非同步刪除作業FlexGroup 、包括在內。

如果您使用的 ONTAP 版本早於 ONTAP 9 。 11.1 、則必須是使用進階權限模式的叢集管理員或 SVM 管理員。

從功能更新9.11.1開始ONTAP 、儲存管理員可以授予磁碟區的權限、讓NFS和SMB用戶端執行非同步刪除作業。如需更多資訊、請參閱 link:manage-client-async-dir-delete-task.html["管理用戶端權限、以非同步方式刪除目錄"]。

從 ONTAP 9 8 開始、您可以使用 ONTAP CLI 使用非同步刪除功能。從功能支援的9.9開始ONTAP 、您可以搭配System Manager使用此功能。如需此程序的詳細資訊，請參閱link:../task_nas_file_system_analytics_take_corrective_action.html["根據分析採取修正行動"]。

[role="tabbed-block"]
====
.系統管理員
--
. 按一下「*儲存設備>磁碟區*」、然後按一下「*檔案總管*」。
+
當您將游標暫留在檔案或資料夾上時、會出現刪除選項。一次只能刪除一個物件。




NOTE: 刪除目錄和檔案時、新的儲存容量值不會立即顯示。

--
.CLI
--
* 使用 CLI 執行非同步刪除 *

. 進入進階權限模式：
+
`-privilege advance`

. 刪除 FlexVol 或 FlexGroup 磁碟區上的目錄：
+
`volume file async-delete start -vserver vserver_name -volume volume_name -path file_path -throttle throttle`

+
最小節流值為10、最大值為100、000、預設值為5000。

+
下列範例會刪除名為D2的目錄、該目錄位於名為D1的目錄中。

+
....
cluster::*>volume file async-delete start -vserver vs1 -volume vol1 -path d1/d2
....
. 確認目錄已刪除：
+
`event log show`

+
下列範例顯示成功刪除目錄時事件記錄的輸出。

+
....
cluster-cli::*> event log show
Time                 Node             Severity      Event
-------------------  ---------------- ------------- --------------------
MM/DD/YYYY 00:11:11  cluster-vsim     INFORMATIONAL asyncDelete.message.success: Async delete job on path d1/d2 of volume (MSID: 2162149232) was completed.
....


*取消目錄刪除工作*

. 進入進階權限模式：
+
`set -privilege advanced`

. 確認正在刪除目錄：
+
`volume file async-delete show`

+
如果顯示SVM、Volume、JobID和目錄路徑、您可以取消工作。

. 取消目錄刪除：
+
`volume file async-delete cancel -vserver _SVM_name_ -volume _volume_name_ -jobid _job_id_`



--
====