---
permalink: flexgroup/manage-client-async-dir-delete-task.html 
sidebar: sidebar 
keywords: perform, directory, enable, delete, files, asynchronous, client rights, SMB, NFS, share, flexvol, flex vol, flexgroup, flex group 
summary: '從 ONTAP 9 ． 11.1 開始、儲存管理員可以在磁碟區上授予權限、以允許 NFS 和 SMB 用戶端執行非同步刪除作業。啟用非同步刪除時、 NFS 用戶端可以使用 `mv`命令、 SMB 用戶端可以使用 `rename`命令刪除指定磁碟區上的目錄、並將目錄移至預設名稱為 .ontaptrashbin 的隱藏目錄。' 
---
= 管理用戶端權限以使用 FlexGroups 非同步刪除 ONTAP 目錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9 ． 11.1 開始、儲存管理員可以在磁碟區上授予權限、以允許 NFS 和 SMB 用戶端自行執行非同步刪除作業。當叢集上啟用非同步刪除時、 Linux 用戶端使用者可以使用 `mv`命令、 Windows 用戶端使用者可以使用 `rename`命令刪除指定磁碟區上的目錄、方法是將目錄移至預設為 .ontaptrashbin 的隱藏目錄。



== 啟用用戶端非同步目錄刪除

.步驟
. 從叢集 CLI 進入進階權限模式： `-privilege advance`
. 啟用用戶端非同步刪除、並視需要提供trashbin目錄的替代名稱：
+
`volume file async-delete client enable volume _volname_ vserver _vserverName_ trashbinname _name_`

+
使用預設垃圾桶名稱的範例：

+
[listing]
----
cluster1::*> volume file async-delete client enable -volume v1 -vserver  vs0

Info: Async directory delete from the client has been enabled on volume "v1" in
      Vserver "vs0".
----
+
指定替代垃圾桶名稱的範例：

+
[listing]
----
cluster1::*> volume file async-delete client enable -volume test -trashbin .ntaptrash -vserver vs1

Success: Async directory delete from the client is enabled on volume "v1" in
      Vserver "vs0".
----
. 確認已啟用用戶端非同步刪除：
+
`volume file async-delete client show`

+
範例：

+
[listing]
----
cluster1::*> volume file async-delete client show

Vserver Volume      async-delete client TrashBinName
------------ ------------ ----------------------- -------------
vs1          vol1         Enabled          .ntaptrash
vs2          vol2         Disabled          -

2 entries were displayed.
----




== 停用用戶端非同步目錄刪除

.步驟
. 在叢集CLI中、停用用戶端非同步目錄刪除：
+
`volume file async-delete client disable volume _volname_ vserver _vserverName_`

+
範例：

+
[listing]
----
cluster1::*> volume file async-delete client disable -volume vol1 -vserver vs1

       Success: Asynchronous directory delete client disabled successfully on volume.
----
. 確認用戶端非同步刪除已停用：
+
`volume file async-delete client show`

+
範例：

+
[listing]
----
cluster1::*> volume file async-delete client show

Vserver      Volume      async-delete client      TrashBinName
------------ ------------ ----------------------- -------------
vs1          vol1         Disabled                -
vs2          vol2         Disabled                -

2 entries were displayed.
----

