---
permalink: flexgroup/monitor-snapmirror-data-transfers-task.html 
sidebar: sidebar 
keywords: monitor, snapmirror, data, transfer, flexgroup, volumes 
summary: 您應該定期監控FlexGroup 「SnapMirror Volume」關係的狀態、以確認目的地FlexGroup 的VMware磁碟區會根據指定的排程定期更新。 
---
= 監控FlexGroup SnapMirror資料傳輸、以利實現資料的不容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該定期監控FlexGroup 「SnapMirror Volume」關係的狀態、以確認目的地FlexGroup 的VMware磁碟區會根據指定的排程定期更新。

您必須從目的地叢集執行此工作。

.步驟
. 檢視所有FlexGroup 的SnapMirror磁碟區關係狀態：「napmirror show -n影片-關係-群組類型FlexGroup 」
+
[listing]
----
cluster2::> snapmirror show -relationship-group-type flexgroup
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vss:s       XDP  vsd:d        Snapmirrored
                                      Idle           -         true    -
vss:s2      XDP  vsd:d2       Uninitialized
                                      Idle           -         true    -
2 entries were displayed.
----
. 查看FlexGroup 《關於各個因素的SnapMirror關係狀態：Snapshot show -expand》（鏡像顯示-expand）
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vss:s       XDP  vsd:d        Snapmirrored
                                      Idle           -         true    -
vss:s__0001 XDP  vsd:d__0001  Snapmirrored
                                      Idle           -         true    -
vss:s__0002 XDP  vsd:d__0002  Snapmirrored
                                      Idle           -         true    -
vss:s__0003 XDP  vsd:d__0003  Snapmirrored
                                      Idle           -         true    -
vss:s__0004 XDP  vsd:d__0004  Snapmirrored
                                      Idle           -         true    -
vss:s__0005 XDP  vsd:d__0005  Snapmirrored
                                      Idle           -         true    -
vss:s__0006 XDP  vsd:d__0006  Snapmirrored
                                      Idle           -         true    -
vss:s__0007 XDP  vsd:d__0007  Snapmirrored
                                      Idle           -         true    -
vss:s__0008 XDP  vsd:d__0008  Snapmirrored
                                      Idle           -         true    -
...
----
. 如果SnapMirror傳輸失敗、請找出FlexGroup 傳輸失敗的現象所在的現象、以及錯誤原因：「napmirror show -Fields last transfer-f誤差-expand」（napmirror show -Fields last transfer-f誤差-expand）
+
[listing]
----
cluster2::> snapmirror show -fields last-transfer-error -expand
source-path destination-path last-transfer-error
----------- ---------------- -----------------------------------------------
vss:s       vsd:d            Group Update failed (Failed to complete update operation on one or more item relationships.)
vss:s__0001 vsd:d__0001      -
vss:s__0002 vsd:d__0002      -
vss:s__0003 vsd:d__0003      Failed to get information for source volume "vss:s__0003" for setup of transfer. (Failed to get volume attributes for e2de028c-8049-11e6-96ea-005056851ca2:s__0003. (Volume is offline))
vss:s__0004 vsd:d__0004      -
vss:s__0005 vsd:d__0005      -
vss:s__0006 vsd:d__0006      -
vss:s__0007 vsd:d__0007      -
vss:s__0008 vsd:d__0008      -
9 entries were displayed.
----
+
解決此問題之後、您必須重新執行SnapMirror作業。


