---
permalink: flexgroup/move-constituents-task.html 
sidebar: sidebar 
keywords: constituents, flexgroup, volume, flex group, balancing, balance, traffic, free, space, aggregate, snapmirror, snap mirror, 
summary: 您可以將 FlexGroup Volume 的組成要素從一個集合移到另一個集合、以便在某些組成要素遇到更多流量時、平衡負載。移動成員也有助於釋出集合體上的空間、以調整現有成員的大小。 
---
= 移動FlexGroup 一個聲音區的組成部分
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將 FlexGroup Volume 的組成要素從一個集合移到另一個集合、以便在某些組成要素遇到更多流量時、平衡負載。移動成員也有助於釋出集合體上的空間、以調整現有成員的大小。

.您需要的產品
若要移動FlexGroup SnapMirror關係中的某個部分、您必須已初始化SnapMirror關係。

.關於這項工作
當擴充了整個過程的內容時、您無法執行Volume Move作業FlexGroup 。

.步驟
. 識別您要移動的 FlexGroup Volume 組成：
+
`volume show -vserver svm_name -is-constituent true`

+
[listing]
----
cluster1::> volume show -vserver vs2 -is-constituent true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs2       fg1          -            online     RW        400TB    15.12TB   62%
vs2       fg1__0001    aggr1        online     RW         25TB     8.12MB   59%
vs2       fg1__0002    aggr2        online     RW         25TB     2.50TB   90%
...
----
. 識別可將 FlexGroup Volume 組成移至的集合體：
+
`volume move target-aggr show -vserver svm_name -volume vol_constituent_name`

+
您選取的Aggregate中的可用空間必須大於FlexGroup 您正在移動的各個版本的大小。

+
[listing]
----
cluster1::> volume move target-aggr show -vserver vs2 -volume fg1_0002
Aggregate Name   Available Size   Storage Type
--------------   --------------   ------------
aggr2            467.9TB          hdd
node12a_aggr3    100.34TB         hdd
node12a_aggr2    100.36TB         hdd
node12a_aggr1    100.36TB         hdd
node12a_aggr4    100.36TB         hdd
5 entries were displayed.
----
. 驗證 FlexGroup Volume 組成是否可以移至預期的 Aggregate ：
+
`volume move start -vserver svm_name -volume vol_constituent_name -destination-aggregate aggr_name -perform-validation-only true`

+
[listing]
----
cluster1::> volume move start -vserver vs2 -volume fg1_0002 -destination-aggregate node12a_aggr3 -perform-validation-only true
Validation succeeded.
----
. 移動 FlexGroup Volume 組成：
+
`volume move start -vserver svm_name -volume vol_constituent_name -destination-aggregate aggr_name [-allow-mixed-aggr-types {true|false}]`

+
磁碟區移動作業會以背景程序的形式執行。

+
從支援的9.5版開始ONTAP 、您可以將FlexGroup 支援的不支援磁碟區從Fabric集區移至非Fabric集區、或是將「允許混合型」參數設為「真」、將兩者移至非Fabric集區。默認情況下，"-allow-come-agg-types（允許混合型）"選項設置爲"假"。

+
[NOTE]
====
您無法使用「Volume Move」命令來啟用FlexGroup 對現象區的加密。

====
+
[listing]
----
cluster1::> volume move start -vserver vs2 -volume fg1_002 -destination-aggregate node12a_aggr3
----
+
[NOTE]
====
如果磁碟區移動作業因為主動式SnapMirror作業而失敗、您應該使用「napmirror abort-h」命令來中止SnapMirror作業。在某些情況下、SnapMirror中止作業也可能失敗。在這種情況下、您應該中止Volume Move作業、然後稍後再試一次。

====
. 驗證Volume Move作業的狀態：
+
`volume move show -volume vol_constituent_name`

+
以下範例顯示FlexGroup 完成複寫階段且處於Volume Move作業轉換階段的各個不完整磁碟區狀態：

+
[listing]
----
cluster1::> volume move show -volume fg1_002
Vserver   Volume     State    Move Phase  Percent-Complete Time-To-Complete
--------- ---------- -------- ----------  ---------------- ----------------
vs2       fg1_002    healthy  cutover     -                -
----

