---
permalink: flexgroup/provision-automatically-task.html 
sidebar: sidebar 
keywords: provision, flexgroup, volume, automatic, create, flex group, aggregate, space 
summary: 建立 FlexGroup Volume 時、您可以選擇讓 ONTAP 自動選取集合體來配置 FlexGroup Volume 。根據最佳實務做法來選擇集合體、以獲得最佳效能。 
---
= 自動配置 ONTAP FlexGroup Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立 FlexGroup Volume 時、您可以選擇讓 ONTAP 透過選取集合體來自動佈建 FlexGroup Volume 。集合體是根據最佳實務做法來選取、以達到最佳效能和容量。

.開始之前
叢集中的每個節點必須至少有一個Aggregate。

[NOTE]
====
若要建立FlexGroup 適用於FabricPool 支援支援的支援功能、ONTAP 每個節點必須至少有一個FabricPool 支援功能的Aggregate。

====
.關於這項工作
在每個節點上、利用最多可用空間選取兩個集合體、以建立此現象。ONTAP FlexGroup如果兩個集合體無法使用、ONTAP 則每個節點選擇一個集合體來建立FlexGroup 這個卷。

從 ONTAP 9.15.1 開始、當您自動佈建 FlexGroup Volume 時、 ONTAP 會使用平衡放置（ BP ）來選擇集合體和 FlexGroup 組成配置。BP 的一個層面是在建立「無」保證的 FlexGroup Volume 時、它如何限制過度資源配置的集合體。整體 FlexGroup 磁碟區的大小受限於集合體上的可用空間量、但限制高於「 Volume 」保證的 FlexGroup 磁碟區。當您使用 REST API 或 ONTAP CLI 建立 FlexGroup Volume `auto-provision-as` 時、資源配置可能會因為空間不足而失敗、因為這種限制。您可以建立較小的 FlexGroup 磁碟區、或使用參數來避免這種 link:create-task.html["建立 FlexGroup Volume 並手動選取集合體"] `aggr-list` 情況。

.步驟
. 配置FlexGroup 供應功能：
+
`volume create -vserver svm_name -volume fg_vol_name –auto-provision-as flexgroup -size fg_size [–encrypt true] [-qos-policy-group qos_policy_group_name] [-support-tiering true]`

+
從功能性的9.5開始ONTAP 、您就能建立FlexGroup 適用於FabricPool 功能性的若要在 FabricPool 上自動佈建 FlexGroup 磁碟區、您必須設定 `-support-tiering` 參數至 `true`。Volume 保證一律必須設定為 `none` 適用於 FabricPool 。您也可以指定FlexGroup 針對該卷的分層原則和分層最低冷卻期。

+
link:../disks-aggregates/index.html["磁碟與Aggregate管理"]

+
您可以指定 FlexGroup 磁碟區的處理量上限（ QoS 上限）。這會限制 FlexGroup 磁碟區所能耗用的效能資源。從ONTAP S得9.4開始、您可以指定處理量層（QoS下限）和適用於FlexGroup 整個過程的調適QoS。

+
link:../performance-admin/index.html["效能管理"]

+
如果您想要在 FlexGroup 磁碟區上啟用加密，可以將參數設定 `-encrypt`為 `true`。若要建立加密磁碟區、您必須安裝Volume加密授權和金鑰管理程式。

+

NOTE: 您必須在FlexGroup 建立時啟用對靜止磁碟區的加密。您無法在現有FlexGroup 的支援資料區啟用加密功能。

+
link:../encryption-at-rest/index.html["加密閒置的資料"]

+
。 `size` 參數指定 FlexGroup 磁碟區大小、單位為 KB 、 MB 、 GB 、 TB 或 PB 。

+
以下範例說明如何配置大小為 400 TB 的 FlexGroup Volume ：

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
以下範例說明如何建立QoS原則群組、以利處理量上限、以及如何將其套用FlexGroup 至某個流通量：

+
[listing]
----
cluster1::> qos policy-group create -policy group pg-vs1 -vserver vs1 -max-throughput 5000iops
----
+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -qos-policy-group pg-vs1
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
以下範例說明如何將FlexGroup 尺寸400 TB的S25 Volume配置到FabricPool 位在畫面上的整個畫面ONTAP 上、以供參考。

+
[listing]
----
cluster-1::> volume create -vserver vs0 -volume fg –auto-provision-as flexgroup -size 400TB -support-tiering true -tiering-policy auto
Warning: The FlexGroup "fg" will be created with the following number of constituents of size 25TB: 16.
The constituents will be created on the following aggregates: aggr1,aggr2
Do you want to continue? {y|n}: y
[Job 34] Job succeeded: Successful
----
+
建立此解決方案時、叢集中的每個節點都會有八個組成要素。FlexGroup這些成員會平均分散在每個節點上兩個最大的集合體之間。

+
根據預設、 FlexGroup Volume 是使用建立的 `volume` 空間保證設定、 AFF 系統除外。對於 AFF 系統、依預設會使用建立 FlexGroup Volume `none` 空間保證。

. 使用連接路徑掛載 FlexGroup Volume ：
+
`volume mount -vserver vserver_name -volume vol_name -junction-path junction_path`

+
[listing]
----
cluster1::> volume mount -vserver vs0 -volume fg2 -junction-path /fg2
----


.完成後
您應該從FlexGroup 用戶端掛載此功能。

如果您執行ONTAP 的是32位或更早版本的版本、而且儲存虛擬機器（SVM）同時設定了NFSv3和NFSv4、FlexGroup 則從用戶端安裝此支援卷可能會失敗。在這種情況FlexGroup 下、您必須在從用戶端掛載完這個版本時、明確指定NFS版本。

[listing]
----
# mount -t nfs -o vers=3 192.53.19.64:/fg2 /mnt/fg2
# ls /mnt/fg2
file1  file2
----