---
permalink: flexgroup/restore-snapvault-backup-task.html 
sidebar: sidebar 
keywords: restore, flexgroup, volume, snapvault, backup 
summary: 您可以從 SnapVault 次要 Volume 中的快照，執行 FlexGroup Volume 的完整磁碟區還原作業。您可以將FlexGroup 還原成原始來源Volume或新FlexGroup 的還原成新的版本。 
---
= 從FlexGroup 還原功能的支援中還原一個支援功能SnapVault
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從 SnapVault 次要 Volume 中的快照，執行 FlexGroup Volume 的完整磁碟區還原作業。您可以將FlexGroup 還原成原始來源Volume或新FlexGroup 的還原成新的版本。

.開始之前
當您從SnapVault 還原為FlexGroup 還原為還原為資料的功能時、必須注意某些考量事項。

* 只有 SnapVault 備份的部分快照才支援基礎還原。目的地 Volume 中的組成數量必須符合擷取快照時來源 Volume 中的組成數量。
* 如果還原作業失敗、則在還原作業完成之前、不允許執行其他作業。
您可以重試還原作業、或使用執行還原作業 `cleanup` 參數。
* 一個支援區只能是一個備份關係或還原關係的來源磁碟區。FlexGroup
不能將一個資料區做為兩個相依關係的來源、兩個還原關係、或是一個相依關係與還原關係。FlexGroup SnapVault SnapVault
* 無法並行執行還原與備份作業。SnapVault
當正在執行基準還原作業或遞增還原作業時、您應該停止備份作業。
* 您必須從目的地 FlexGroup Volume 中止部分快照的還原作業。您無法從來源磁碟區中止部分快照的還原作業。
* 如果您中止還原作業，則必須使用先前還原作業所使用的相同快照來重新啟動還原作業。


.關於這項工作
在執行FlexGroup 還原之前、會停用目的地聲音區上的任何作用中配額規則。

您可以使用 `volume quota modify` 還原作業完成後重新啟動配額規則的命令。

.步驟
. 還原 FlexGroup Volume ： `snapmirror restore -source-path _src_svm:src_flexgroup_ -destination-path _dest_svm:dest_flexgroup_ -snapshot _snapshot_name_`
`snapshot_name`是要從來源磁碟區還原至目的地磁碟區的快照。如果未指定快照，則會從最新的快照還原目的地磁碟區。
+
[listing]
----
vserverA::> snapmirror restore -source-path vserverB:dstFG -destination-path vserverA:newFG -snapshot daily.2016-07-15_0010
Warning: This is a disruptive operation and the volume vserverA:newFG will be read-only until the operation completes
Do you want to continue? {y|n}: y
----

