---
permalink: flexgroup/reverse-snapmirror-relationship-task.html 
sidebar: sidebar 
keywords: reverse, snapmirror, relation, flexgroup, volume, disaster, recovery 
summary: 當災難停用FlexGroup SnapMirror關係的來源等量資料時、您可以在FlexGroup 修復或更換來源FlexGroup 的等量資料時、使用目的地的等量資料。在來源FlexGroup 供應資料的來源供應上線後、您可以將原始來源FlexGroup 供應資料的來源供應區變成唯讀目的地、並反轉SnapMirror關係。 
---
= 在災難恢復期間，反轉 ONTAP FlexGroup 磁碟區之間的 SnapMirror 關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當災難停用FlexGroup SnapMirror關係的來源等量資料時、您可以在FlexGroup 修復或更換來源FlexGroup 的等量資料時、使用目的地的等量資料。在來源FlexGroup 供應資料的來源供應上線後、您可以將原始來源FlexGroup 供應資料的來源供應區變成唯讀目的地、並反轉SnapMirror關係。

.關於這項工作
目的地磁碟區上的任何作用中配額規則都會停用、而且配額規則會在執行重新同步之前刪除。

您可以使用 `volume quota policy rule create` 和 `volume quota modify` 在重新同步作業完成後建立及重新啟動配額規則的命令。

.步驟
. 在原始目的地 FlexGroup 磁碟區上、移除來源 FlexGroup 磁碟區與目的地 FlexGroup 磁碟區之間的資料保護鏡射關係： `snapmirror delete -destination-path svm_name:volume_name`
+
[listing]
----
cluster2::> snapmirror delete -destination-path vsd:dst
----
. 在原始來源 FlexGroup 磁碟區上、從來源 FlexGroup 磁碟區移除關係資訊： `snapmirror release -destination-path svm_name:volume_name -relationship-info-only`
+
刪除SnapMirror關係之後、您必須先從來源FlexGroup 的SnapMirror Volume移除關係資訊、然後再嘗試重新同步作業。

+
[listing]
----
cluster1::> snapmirror release -destination-path vsd:dst -relationship-info-only true
----
. 在新的目的地 FlexGroup 磁碟區上、建立鏡射關係： `snapmirror create -source-path src_svm_name:volume_name -destination-path dst_svm_name:volume_name -type XDP -policy MirrorAllSnapshots`
+
[listing]
----
cluster1::> snapmirror create -source-path vsd:dst -destination-path vss:src -type XDP -policy MirrorAllSnapshots
----
. 在新的目的地 FlexGroup 磁碟區上、重新同步來源 FlexGroup ： `snapmirror resync -source-path svm_name:volume_name`
+
[listing]
----
cluster1::> snapmirror resync -source-path vsd:dst
----
. 監控 SnapMirror 傳輸： `snapmirror show -expand`
+
[listing]
----
cluster2::> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vsd:dst       XDP  vss:src        Snapmirrored
                                      Idle           -         true    -
vss:dst__0001 XDP  vss:src__0001  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0002 XDP  vss:src__0002  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0003 XDP  vss:src__0003  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0004 XDP  vss:src__0004  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0005 XDP  vss:src__0005  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0006 XDP  vss:src__0006  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0007 XDP  vss:src__0007  Snapmirrored
                                      Idle           -         true    -
vsd:dst__0008 XDP  vss:src__0008  Snapmirrored
                                      Idle           -         true    -
...
----
+
每個成分的 SnapMirror 關係狀態顯示為 `Snapmirrored` 這表示重新同步已成功。



.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror建立"^]

