---
permalink: flexgroup/transition-snapmirror-relationship-svm-dr-task.html 
sidebar: sidebar 
keywords: transition, flexgroup, snapmirror, relationship, svm, dr 
summary: 您可以FlexGroup 轉換現有FlexGroup 的SnapMirror磁碟區關係、建立一套SVM DR關係。 
---
= 將 ONTAP FlexGroup SnapMirror 關係移轉至 SVM DR
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以FlexGroup 轉換現有FlexGroup 的SnapMirror磁碟區關係、建立一套SVM DR關係。

.開始之前
* 此功能與本系統的SnapMirror關係狀況良好。FlexGroup
* 來源FlexGroup 和目的地的不一致名稱。


.步驟
. 從 SnapMirror 目的地重新同步 FlexGroup 層級的 SnapMirror 關係： `snapmirror resync`
. 建立FlexGroup SVM DR SnapMirror關係。使用在 FlexGroup Volume SnapMirror 關係上設定的相同 SnapMirror 原則： `snapmirror create -destination-path dest_svm: -source-path src_svm: -identity-preserve true -policy MirrorAllSnapshots`
+
[NOTE]
====
您必須使用 `-identity-preserve true` 的選項 `snapmirror create` 建立複寫關係時的命令。

====
. 確認關係已中斷： `snapmirror show -destination-path dest_svm: -source-path src_svm:`
+
[listing]
----
snapmirror show -destination-path fg_vs_renamed: -source-path fg_vs:

                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
fg_vs:        XDP  fg_vs1_renamed:     Broken-off
                                      Idle           -         true   -
----
. 停止目的地SVM： `vserver stop -vserver vs_name`
+
[listing]
----
vserver stop -vserver fg_vs_renamed
[Job 245] Job is queued: Vserver Stop fg_vs_renamed.
[Job 245] Done
----
. 重新同步 SVM SnapMirror 關係： `snapmirror resync -destination-path dest_svm: -source-path src_svm:`
+
[listing]
----
snapmirror resync -destination-path fg_vs_renamed: -source-path fg_vs:
Warning: This Vserver has volumes which are the destination of FlexVol or FlexGroup SnapMirror relationships. A resync on the Vserver SnapMirror relationship will cause disruptions in data access
----
. 確認 SVM DR 層級 SnapMirror 關係達到健全的閒置狀態： `snapmirror show -expand`
. 驗證 FlexGroup SnapMirror 關係是否處於正常狀態： `snapmirror show`

