---
permalink: flexcache-writeback/flexcache-write-back-guidelines.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, flexcache, write-back, write back, guidelines, best practices, performance, ontap tr, netapp tr 
summary: 使用 FlexCache 回寫時，請遵循以下準則以確保最佳效能。 
---
= ONTAP FlexCache 回寫準則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexCache 回寫會涉及來源與快取之間的許多複雜互動。為了達到最佳效能，您應確保環境遵循這些準則。這些準則是以最新的主要 ONTAP 版本（ ONTAP 9.15.1 ）為基礎，可在內容建立時取得。

最佳實務做法是在非正式作業環境中測試您的正式作業工作負載。如果您在這些準則之外實作 FlexCache 回寫，這就更重要了。

以下準則已在 NetApp 內部經過充分測試。建議您留在這些範圍內。否則可能會發生非預期的行為。

* ONTAP 9.15.1P5 大幅增強了 FlexCache 回寫功能。建議您在原始叢集和快取叢集上執行 9.15.1P5 之後的目前建議版本。
* 在目前的迭代中， FlexCache 回寫式快取應設定為整個 FlexCache Volume 的單一組成要素。多成分 FlexCaches 可能會導致不必要的資料從快取區移出。
* 已針對快取與來源之間小於 100GB 的檔案和 WAN 往返時間，執行測試，但不超過 100ms 。超出這些限制的任何工作負載都可能導致非預期的效能特性。
* 寫入 SMB 替代資料串流會導致主檔案被從快取中移出。主檔案的所有髒資料都必須先清除至來源，才能在該檔案上執行任何其他作業。替代資料串流也會轉送至來源。
* 重新命名檔案會使檔案從快取中移出。檔案的所有髒資料都必須先清除至來源，才能在該檔案上執行任何其他作業。
* 目前，唯一可在啟用回寫的 FlexCache 磁碟區上變更或設定的屬性為：
+
** 時間戳記
** 模式位元
** NT ACL
** 擁有者
** 群組
** 尺寸
+
任何其他變更或設定的屬性都會轉寄至原始伺服器，這可能會導致檔案從快取中移除。如果您需要在快取中變更或設定其他屬性，請要求您的帳戶團隊開啟 PVR 。



* 在來源處拍攝的快照會叫出與來源磁碟區相關聯的每個啟用回寫快取中所有未處理的髒資料。如果有大量的回寫活動正在進行中，這可能需要多次重試作業，因為這些髒檔案的移轉可能需要一些時間。
* 原點必須保持在 80% 的滿量以下。如果原始磁碟區中沒有至少 20% 的剩餘空間，則不會授予快取磁碟區獨佔鎖定委派。在這種情況下，對啟用回寫式快取的通話會轉接至來源。這有助於防止來源空間不足，導致在啟用回寫的快取中留下髒資料孤立。

