---
permalink: flexcache-writeback/flexcache-write-back-guidelines.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, flexcache, write-back, write back, guidelines, best practices, performance, ontap tr, netapp tr 
summary: 使用 FlexCache 回寫時，請遵循以下準則以確保最佳效能。 
---
= ONTAP FlexCache 回寫準則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FlexCache寫回涉及來源伺服器和快取伺服器之間的許多複雜互動。為了獲得最佳效能，您應該確保您的環境遵循以下準則。這些指南是基於內容創建時可用的最新主要ONTAP版本（ONTAP 9.17.1）。

最佳實務做法是在非正式作業環境中測試您的正式作業工作負載。如果您在這些準則之外實作 FlexCache 回寫，這就更重要了。

以下準則已在 NetApp 內部經過充分測試。建議您留在這些範圍內。否則可能會發生非預期的行為。

* ONTAP 9.17.1P1 引進了對FlexCache回寫功能的重大增強。強烈建議您在來源叢集和快取叢集上，在 9.17.1P1 版本之後運行目前建議版本。如果您無法執行 9.17.1 程式碼線，建議使用最新的 P 版本 9.16.1。ONTAP 9.15.1 尚未包含FlexCache回寫所需的全部修復和改進，因此不建議用於生產工作負載。
* 在目前的迭代中， FlexCache 回寫式快取應設定為整個 FlexCache Volume 的單一組成要素。多成分 FlexCaches 可能會導致不必要的資料從快取區移出。
* 測試針對小於 100GB 的檔案進行，快取和來源之間的 WAN 往返時間不超過 200ms。超出這些限制的任何工作負載都可能導致意想不到的效能特性。
* 寫入 SMB 替代資料串流會導致主檔案被從快取中移出。主檔案的所有髒資料都必須先清除至來源，才能在該檔案上執行任何其他作業。替代資料串流也會轉送至來源。
* 重新命名檔案會使檔案從快取中移出。檔案的所有髒資料都必須先清除至來源，才能在該檔案上執行任何其他作業。
* 目前，唯一可在啟用回寫的 FlexCache 磁碟區上變更或設定的屬性為：
+
** 時間戳記
** 模式位元
** NT ACL
** 擁有者
** 群組
** 尺寸
+
任何其他變更或設定的屬性都會轉寄至原始伺服器，這可能會導致檔案從快取中移除。如果您需要在快取中變更或設定其他屬性，請要求您的帳戶團隊開啟 PVR 。



* 在來源處拍攝的快照會叫出與來源磁碟區相關聯的每個啟用回寫快取中所有未處理的髒資料。如果有大量的回寫活動正在進行中，這可能需要多次重試作業，因為這些髒檔案的移轉可能需要一些時間。
* 啟用回寫功能的FlexCache磁碟區不支援 SMB 機會鎖（Oplocks）寫入。
* 原點必須保持在 80% 的滿量以下。如果原始磁碟區中沒有至少 20% 的剩餘空間，則不會授予快取磁碟區獨佔鎖定委派。在這種情況下，對啟用回寫式快取的通話會轉接至來源。這有助於防止來源空間不足，導致在啟用回寫的快取中留下髒資料孤立。
* 低頻寬和/或有損的群集間網路會對FlexCache寫回效能產生顯著的負面影響。雖然沒有特定的頻寬要求，因為它很大程度上取決於您的工作負載，但強烈建議您確保快取和來源之間的叢集間連結的健康狀況。

