---
permalink: flexcache-writeback/flexcache-write-back-overview.html 
sidebar: sidebar 
keywords: tr-4743, flexcache writeback, flexcache write-back, overview, technical report, netapp tr, ontap tr 
summary: FlexCache 回寫是 ONTAP 9.15.1 推出的另一種寫入快取的作業模式。 
---
= 瞭解 ONTAP FlexCache 回寫功能
:allow-uri-read: 


[role="lead"]
FlexCache 回寫是 ONTAP 9.15.1 推出的另一種寫入快取的作業模式。回寫功能可將寫入內容提交至快取的穩定儲存設備、並將其確認給用戶端、而無需等待資料傳送至原始伺服器。資料會以非同步方式重新排清回來源。因此、全球分散式檔案系統可讓寫入作業以接近本機的速度執行特定工作負載和環境、提供顯著的效能效益。


NOTE: ONTAP 9.12.1 推出回寫功能作為公開預覽。這稱為回寫版本 1 （ wbv1 ）、不應視為 ONTAP 9.15.1 中的回寫版本 2 （ wbv2 ）。



== 回寫與回寫

自從 ONTAP 9.5 引進 FlexCache 以來、它一直是可讀寫的快取、但卻是以寫入模式運作。快取中的寫入資料會傳送至原始伺服器、以用於穩定儲存設備。原始伺服器成功將寫入內容提交至穩定儲存設備後、就會確認寫入快取。然後快取會確認寫入用戶端。如此一來、每次寫入都會被罰在快取和原始伺服器之間穿越網路。FlexCache 回寫會變更此項目。


NOTE: 升級至 ONTAP 9.15.1 之後、您可以將傳統的繞過寫入快取轉換為回寫快取、並在必要時回復為回寫式快取。不過、如果發生問題、讀取診斷記錄可能會更困難。

|===
|  | 繞過寫入 | 回寫 


| 版本ONTAP | 超過 9.6 個 | 9.15.1+ 


| 使用案例 | 讀取繁重的工作負載 | 大量寫入工作負載 


| 資料提交時間 | 來源 | 快取 


| 客戶體驗 | 類似 WAN | 類似 LAN 


| 限制 | 每個來源 100 個 | 每個來源 10 個 


| https://en.wikipedia.org/wiki/CAP_theorem["CAP Theorem"^] | 可用且可容錯分割區 | 可用且一致 
|===


== FlexCache 回寫詞彙

瞭解使用 FlexCache 回寫功能的關鍵概念和詞彙。

[cols="12%,88%"]
|===
| 期限 | 定義 


| [[OUTM-data]]*O變 髒的資料 * | 已提交至快取穩定儲存區、但尚未排清至來源區的資料。 


| * 獨家鎖定委派（ XLD ） * | 以每個檔案為基礎、授予快取的通訊協定層級鎖定權限。此權限可讓快取將專屬寫入鎖定交給用戶端、而無需聯絡來源。 


| * 共用鎖定委派（ SLD ） * | 以每個檔案為基礎、授予快取的通訊協定層級鎖定權限。此權限可讓快取將共用讀取鎖定分發給用戶端、而無需聯絡原始伺服器。 


| * 回寫式 * | 一種 FlexCache 作業模式、寫入快取的資料會被提交至該快取的穩定儲存設備、並立即確認給用戶端。資料會以非同步方式寫入來源。 


| * 繞過寫入 * | 一種 FlexCache 作業模式、將寫入快取的資料轉送至原始伺服器、以提交至穩定的儲存設備。提交後、原始伺服器會確認寫入快取、快取會確認寫入用戶端。 


| * 不良資料記錄系統（ DDR ） * | 一種專屬機制、可針對每個檔案、追蹤啟用回寫式快取中的髒資料。 


| * 來源 * | 包含所有 FlexCache 快取磁碟區之來源資料的 FlexGroup 或 FlexVol 。它是唯一的事實來源、協調鎖定、並確保 100% 資料一致性、貨幣和一致性。 


| * 快取 * | FlexGroup 、 FlexCache 原始伺服器的稀疏快取磁碟區。 
|===


=== 一致、最新且一致的

FlexCache 是 NetApp 的解決方案、可隨時隨地擁有正確的資料。FlexCache 100% 一致、即時且一致的 100% 時間：

* * 一致： * 無論資料在何處存取、資料都是相同的。
* * 目前： * 資料永遠保持在最新狀態。
* * 一致： * 資料正確 / 未毀損。

