---
sidebar: sidebar 
permalink: smbc/smbc_troubleshoot_link_between_site_a_and_mediator_down.html 
keywords: SM-BC, SMBC, troubleshooting, connectivity, consensus 
summary: 疑難排解站台A與調壓器之間的連結中斷、站台B關閉。 
---
= 站台A與調壓器向下連結、站台B向下連結
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
使用SMBC時、可能會失去中介器或連接叢集的連線。您可以檢查SMBC關係不同部分的連線、可用度和共識狀態、然後強制恢復連線、藉此診斷問題。

使用「napmirror中介者show」命令、從站台A檢查「協調器」的狀態。

....
C1_cluster::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.237.86.17     C2_cluster       unreachable       true

C1_cluster::*> snapmirror list-destinations
                                                  Progress
Source             Destination         Transfer   Last         Relationship
Path         Type  Path         Status Progress   Updated      Id
----------- ----- ------------ ------- --------- ------------ ---------------
vs0:/cg/src_cg_1  XDP   vs1:/cg/dst_cg_1  OutOfSync  -         -            bba7d354-06f6-11eb-9138-005056acec19
....
使用「cluster對等show」命令檢查站台B的連線能力：

....
C1_sti78-vsim-ucs188a_cluster::*> cluster peer show
Peer Cluster Name         Cluster Serial Number Availability   Authentication
------------------------- --------------------- -------------- --------------
C2_cluster                1-80-000011           Unavailable    ok
....
使用命令「volume show _volume name_-功能 變數smbc-Consensus」檢查SM磁碟區的協商一致狀態：

....
C1_cluster::*> volume show zrto_cg_894191_188b_RW1 -fields smbc-consensus
vserver volume                  smbc-consensus
------- ----------------------- ------------------
vs0     zrto_cg_894191_188b_RW1 Awaiting-consensus
....
請完成下列步驟、以取代SMBC共識、並在站台A上強制恢復I/O：


NOTE: 此解決方案使用「diag」層級命令、您必須聯絡NetApp支援部門。

. 在站台A上取消對應LUN
. 在站點A上使用「-force」和「overre-smbc-Consensus」選項發出「napmirror release」命令
. 重新對應LUN。
. 首先、叫出「資訊器」、然後叫出站台B節點。
. 使用「napmirror resSync」重新同步一致性群組關係。
. 站台B啟動後、請確認一致性群組關係已啟動且處於同步狀態。
. 在主機上執行LUN重新掃描、以還原LUN的所有路徑。

