---
sidebar: sidebar 
permalink: smbc/smbc_admin_monitoring.html 
keywords: SM-BC, SMBC, monitoring, Mediator status, EMS, errors, planned failover status, automatic unplanned failover status, SM-BC status 
summary: 您可以監控數個SM至BC元件和作業。 
---
= 基本監控
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以監控數個SM至BC元件和作業。



== 中間器ONTAP

在正常操作期間、應連接「中保」狀態。如果處於任何其他狀態、可能表示發生錯誤。您可以檢閱 link:https://docs.netapp.com/us-en/ontap-ems-9131/sm-mediator-events.html["事件管理系統（EMS）訊息"^] 以判斷錯誤及適當的修正行動。



== 計畫性容錯移轉作業

您可以使用「napmirror fover show」命令來監控計畫性容錯移轉作業的狀態和進度。例如：

....
ClusterB::> snapmirror failover start -destination-path vs1:/cg/dcg1
....
一旦完成容錯移轉作業、您就能從新的目的地叢集監控同步SnapMirror保護狀態。例如：

....
ClusterA::> snapmirror show
....
請參閱 link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-pfo-events.html["EMS參考資料"^] 以瞭解事件訊息和修正行動。



== 自動非計畫性容錯移轉作業

在非計畫性自動容錯移轉期間、您可以使用「napmirror Failover show」命令來監控作業狀態。例如：

....
ClusterB::> snapmirror failover show -instance
Start Time: 9/23/2020 22:03:29
         Source Path: vs1:/cg/scg3
    Destination Path: vs3:/cg/dcg3
     Failover Status: completed
        Error Reason:
            End Time: 9/23/2020 22:03:30
Primary Data Cluster: cluster-2
Last Progress Update: -
       Failover Type: unplanned
  Error Reason codes: -
....
請參閱 link:https://docs.netapp.com/us-en/ontap-ems-9131/smbc-aufo-events.html["EMS參考資料"^] 以瞭解事件訊息及修正行動。



== SM至BC可用度

您可以使用一系列命令來檢查SM-BC關係的可用度、無論是在主叢集、次要叢集或兩者。

您使用的命令包括主叢集和次叢集上的「napmirror中介show」命令、以檢查連線和仲裁狀態、「napmirror show」命令和「volume show」命令。例如：

....
SMBC_A::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_B           connected         true

SMBC_B::*> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.236.172.86    SMBC_A           connected         true

SMBC_B::*> snapmirror show -expand
                                                                       Progress
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/cg1 XDP  vs1:/cg/cg1_dp Snapmirrored InSync  -         true    -
vs0:vol1    XDP  vs1:vol1_dp  Snapmirrored InSync    -         true    -
2 entries were displayed.

SMBC_A::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1
vserver volume is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------ -------------- ------------------------ --------------
vs0     vol1   true           false                    Consensus

SMBC_B::*> volume show -fields is-smbc-master,smbc-consensus,is-smbc-failover-capable -volume vol1_dp
vserver volume  is-smbc-master is-smbc-failover-capable smbc-consensus
------- ------- -------------- ------------------------ --------------
vs1     vol1_dp false          true                     No-consensus
....