---
permalink: s3-audit/index.html 
sidebar: sidebar 
keywords: S3, audit, management events 
summary: 本文說明如何稽核ONTAP 資料與管理事件、以供在SS3環境中使用。 
---
= 稽核S3事件
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從功能完善的S59.10.1開始ONTAP 、您可以在ONTAP 支援功能完善的支援環境中稽核資料與管理事件。S3稽核功能類似於現有的NAS稽核功能、S3和NAS稽核可共存於叢集內。

當您在SVM上建立及啟用S3稽核組態時、S3事件會記錄在記錄檔中。您可以指定要記錄的下列事件：



== 物件存取（資料）事件（依版本）

9.11.1 ：

* listBucketVerions
* ListBucket （ 9.10.1 的 ListObjects 已重新命名為此項目）
* ListAllMyb鏟 斗（已將 9.10.1 的清單鏟斗重新命名為此）


9.10.1 ：

* 標題物件
* GetObject
* PuttObject
* 刪除物件
* 列表桶
* 清單物件
* MPUpload
* MPUploadPart
* MPComplete
* MPAbort
* GetObjectTagging
* 刪除ObjectTagging
* PuttObjectTagging
* ListUploads
* 清單零件




== 依版本管理事件

9.15.1 ：

* GetBucketCORS
* PuttBucketCORS
* DeleteBucketCORS


9.14.1 ：

* GetObjectRetention
* PutObjectRetention
* PutBucketObjectLockConfiguration
* GetBucketObjectLockConfiguration


9.13.1 ：

* PutBucketLifecycle
* 刪除 BucketLifecycle
* GetBucketLifecycle


9.12.1 ：

* GetBucketPolicy
* CopyObject
* 上傳PartCopy
* PuttBucketPolicy
* 刪除BucketPolicy


9.11.1 ：

* GetBucketVersion
* PuttBucketVersion


9.10.1 ：

* 標題庫
* GetBucketAcl
* GetObjectAcl
* 推桿
* 刪除Bucket
* ModifyObjectTagging
* GetBucketLocation


記錄格式為JavaScript物件標記法（Json）。

S3和NFS稽核組態的總限制為每個叢集50個SVM。

需要下列授權：

* ONTAP One （原為核心產品組合的一部分）、適用於 ONTAP S3 傳輸協定和儲存設備


如需詳細資訊、請參閱 link:../nas-audit/auditing-process-concept.html["如何執行不稽核程序ONTAP"]。



== 保證稽核

根據預設、S3和NAS稽核是保證的。即使節點無法使用、也能保證記錄所有可稽核的儲存貯體存取事件。ONTAP在將該作業的稽核記錄儲存至持續儲存設備上的接移磁碟區之前、無法完成要求的儲存區作業。如果因為空間不足或其他問題而無法在暫存檔案中提交稽核記錄、則會拒絕用戶端作業。



== 稽核所需的空間

在不稽核系統中ONTAP 、稽核記錄一開始會儲存在個別節點的二進位暫存檔案中。這些記錄會定期整合並轉換成使用者可讀取的事件記錄、這些記錄會儲存在SVM的稽核事件記錄目錄中。

暫存檔案儲存在專屬的暫存磁碟區中、ONTAP 此磁碟區是由建立稽核組態時由支援所建立。每個Aggregate有一個接移磁碟區。

您必須在稽核組態中規劃足夠的可用空間：

* 適用於集合體中包含稽核桶的暫存磁碟區。
* 用於儲存已轉換事件記錄之目錄的磁碟區。


建立S3稽核組態時、您可以使用下列兩種方法之一來控制事件記錄的數量、以及磁碟區中的可用空間：

* 數值限制 `-rotate-limit` 參數控制必須保留的稽核檔案數量下限。
* 時間限制 `-retention-duration` 參數控制檔案可保留的最長期間。


在這兩個參數中、一旦超過設定、就能刪除較舊的稽核檔案、為較新的稽核檔案留出空間。這兩個參數的值都是0、表示必須維護所有檔案。因此、為了確保有足夠空間、最佳做法是將其中一個參數設定為非零值。

由於稽核保證、如果稽核資料的可用空間在旋轉限制之前用盡、就無法建立較新的稽核資料、導致用戶端無法存取資料。因此、您必須謹慎選擇此值及分配給稽核的空間、而且必須回應稽核系統中有關可用空間的警告。

如需詳細資訊、請參閱 link:../nas-audit/basic-auditing-concept.html["基本稽核概念"]。
