---
permalink: s3-audit/plan-config-task.html 
sidebar: sidebar 
keywords: s3, audit, create, configure s3 audit 
summary: 此工作說明S3稽核所使用的參數。 
---
= 規劃S3稽核組態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須為S3稽核組態指定多個參數、或接受預設值。特別是、您應該考慮哪些記錄旋轉參數有助於確保有足夠的可用空間。

請參閱 *`vserver object-store-server audit create`* 語法詳細資料請參閱手冊頁。



== 一般參數

建立稽核組態時、必須指定兩個必要參數。您也可以指定三個選用參數。

[cols="4,2,1"]
|===


| 資訊類型 | 選項 | 必要 


 a| 
_SVM名稱_

要在其中建立稽核組態的SVM名稱。

SVM必須已經存在、且已啟用S3。
 a| 
`-verserver _svm_name_`
 a| 
是的



 a| 
_記錄目的地路徑_

指定轉換後的稽核記錄儲存位置。路徑必須已存在於SVM上。

路徑長度最多可達864個字元、且必須具有讀寫權限。

如果路徑無效、稽核組態命令就會失敗。
 a| 
`-destination _text_`
 a| 
是的



 a| 
要稽核的事件類別_

您可以稽核下列事件類別：

* 資料
GetObject 、 PutObject 和 DeleteObject 事件
* 管理
PutBucket 和 DeleteBucket 活動


預設為僅稽核資料事件。
 a| 
`-events {data{vbar}management}, ...`
 a| 
否

|===
您可以輸入下列其中一個參數、以控制稽核記錄檔的數量。如果未輸入任何值、則會保留所有記錄檔。

[cols="4,2,1"]
|===


| 資訊類型 | 選項 | 必要 


 a| 
_記錄檔案旋轉限制_

決定要保留多少稽核記錄檔、然後再將最舊的記錄檔轉出。例如、如果您輸入值5、則會保留最後五個記錄檔。

值0表示保留所有記錄檔。預設值為 0 。
 a| 
`-rotate-limit _integer_`
 a| 
否



 a| 
_記錄檔案持續時間限制_

決定在刪除記錄檔之前可以保留多久。例如、如果您輸入5d0h0m的值、超過5天的記錄就會刪除。

值0表示保留所有記錄檔。預設值為 0 。
 a| 
`-retention duration _integer_time_`
 a| 
否

|===


== 稽核記錄輪調的參數

您可以根據大小或排程來旋轉稽核記錄。預設值是根據大小來旋轉稽核記錄。



=== 根據記錄大小來旋轉記錄

如果您要使用預設的記錄檔旋轉方法和預設的記錄檔大小、則不需要設定任何特定的記錄檔旋轉參數。預設記錄大小為100 MB。

如果您不想使用預設記錄大小、可以設定 `-rotate-size` 指定自訂記錄大小的參數。

如果您想要僅根據記錄大小重設旋轉、請使用下列命令取消設定 `-rotate-schedule-minute` 參數：

`vserver audit modify -vserver _svm_name_ -destination / -rotate-schedule-minute -`



=== 根據排程來旋轉記錄

如果您選擇根據排程來旋轉稽核記錄、您可以使用任何組合的時間型旋轉參數來排程記錄輪調。

* 如果您使用時間型旋轉、則會使用 `-rotate-schedule-minute` 參數為必填。
* 所有其他的時間型旋轉參數都是選用的。
+
** `-rotate-schedule-month`
** `-rotate-schedule-dayofweek`
** `-rotate-schedule-day`
** `-rotate-schedule-hour`


* 旋轉排程是使用所有與時間相關的值來計算。
例如、如果您只指定 `-rotate-schedule-minute` 參數時、稽核記錄檔會根據一週中所有天所指定的分鐘數、在一年中所有月份的所有小時內進行旋轉。
* 如果只指定一或兩個時間型旋轉參數（例如、 `-rotate-schedule-month` 和 `-rotate-schedule-minutes`）、記錄檔會根據您在一週的所有天、所有時間、但僅在指定的月份內所指定的分鐘值來旋轉。
+
例如、您可以指定稽核日誌在一月、三月和八月的所有週一、週三和週六上午10：30進行輪調

* 如果您同時指定兩者的值 `-rotate-schedule-dayofweek` 和 `-rotate-schedule-day`的問題。
+
例如、如果您指定 `-rotate-schedule-dayofweek` 星期五和 `-rotate-schedule-day` 截至 13 日、稽核記錄將會在每週五和指定月份的第 13 天、而不只是在每週五的第 13 天輪調。

* 如果您想要僅根據排程重設旋轉、請使用下列命令取消設定 `-rotate-size parameter`：
+
`vserver audit modify -vserver _svm_name_ -destination / -rotate-size -`





=== 根據記錄大小和排程來旋轉記錄

您可以選擇根據記錄大小和排程來旋轉記錄檔、方法是在任何組合中設定-rote-size參數和時間型旋轉參數。例如： IF `-rotate-size` 設為 10 MB 、且 `-rotate-schedule-minute` 設為 15 、當記錄檔大小達到 10 MB 或每小時 15 分鐘（以先發生的事件為準）時、記錄檔會旋轉。
