---
sidebar: sidebar 
permalink: s3-snapmirror/index.html 
keywords: snapmirror s3 buckets, snapmirror buckets SVM, snapmirror s3 data protection, hybrid cloud bundle, snapmirror s3 relationship, VM peering, cluster and storage VM peering, Fan-in deployments, data protection, snapmirror s3 policy, peering 
summary: 從S59.10.1開始ONTAP 、ONTAP 您可以使用熟悉的SnapMirror鏡射與備份功能、來保護位於S3物件儲存區的貯體。 
---
= SnapMirror S3 概述
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9.10.1 開始、您可以使用 SnapMirror 鏡射和備份功能、保護 ONTAP S3 物件儲存區中的貯體。與標準 SnapMirror 不同、 SnapMirror S3 可將鏡像與備份複製到非 NetApp 目的地、例如 AWS S3 。

SnapMirror S3 支援從 ONTAP S3 儲存區到下列目的地的主動鏡射和備份層：

[cols="50,25,25"]
|===
| 目標 | 支援作用中鏡像和接管？ | 支援備份與還原？ 


 a| 
SS3 ONTAP

* 相同SVM中的儲存區
* 位於同一個叢集上不同SVM中的儲存區
* 不同叢集上的SVM儲存區

| 是的 | 是的 


| StorageGRID | 否 | 是的 


| AWS S3 | 否 | 是的 


| 適用於 Azure Cloud Volumes ONTAP | 是的 | 是的 


| AWS 適用的 Cloud Volumes ONTAP | 是的 | 是的 


| 適用於 Google Cloud Cloud Volumes ONTAP | 是的 | 是的 
|===
您可以保護ONTAP 現有的SS3伺服器庫位、也可以立即啟用資料保護功能、建立新的庫位。



== SnapMirror S3 要求

* 版本ONTAP
+
ONTAP 9.10.1 或更新版本必須在來源叢集和目的地叢集上執行。

* 授權
+
中提供下列授權 link:../system-admin/manage-licenses-concept.html["ONTAP One"] ONTAP 來源和目的地系統需要軟體套件、才能提供下列存取：

+
** ONTAP S3 傳輸協定與儲存設備
** SnapMirror S3 目標為其他 NetApp 物件存放區目標（ ONTAP S3 、 StorageGRID 和 Cloud Volumes ONTAP ）
** SnapMirror S3 目標協力廠商物件儲存區、包括 AWS S3 （可在中取得link:../data-protection/install-snapmirror-cloud-license-task.html["ONTAP One 相容性套件"]）
** 如果您的叢集執行的是 ONTAP 9.10.1 ，則需要 A link:../fabricpool/install-license-aws-azure-ibm-task.html["不含授權FabricPool"]。


* SS3 ONTAP
+
** SS3伺服器必須執行來源和目的地SVM。ONTAP
** 建議但不需要在裝載S3伺服器的系統上安裝TLS存取的CA憑證。
+
*** 用於簽署 S3 伺服器憑證的 CA 憑證必須安裝在主控 S3 伺服器之叢集的管理儲存 VM 上。
*** 您可以使用自我簽署的CA憑證或外部CA廠商所簽署的憑證。
*** 如果來源或目的地儲存VM未使用HTTPS接聽、則不需要安裝CA憑證。




* 對等（ONTAP 適用於S3目標）
+
** 必須設定叢集間的生命體（用於遠端 ONTAP 目標）、來源叢集和目的地叢集的叢集間生命體可連線至來源和目的地 S3 伺服器資料生命體。
** 來源和目的地叢集會被處理（用於遠端ONTAP 的不確定目標）。
** 來源和目的地儲存VM都會被處理（適用於所有ONTAP 的物件）。


* SnapMirror原則
+
** 所有 SnapMirror S3 關係都需要 S3 專屬的 SnapMirror 原則、但您可以針對多個關係使用相同的原則。
** 您可以建立自己的原則或接受預設的*連續*原則、其中包含下列值：
+
*** 節流（處理量/頻寬上限）-無限。
*** 恢復點目標時間：1小時（3、600秒）。







NOTE: 請注意、當兩個 S3 儲存區處於 SnapMirror 關係中時、如果設定了生命週期原則、使物件的目前版本過期（刪除）、則會將相同的動作複寫到合作夥伴儲存區。即使合作夥伴儲存庫為唯讀或被動式、也會發生這種情況。

* 根使用者金鑰 SnapMirror S3 關係需要 Storage VM 根使用者存取金鑰； ONTAP 預設不會指派這些金鑰。第一次建立 SnapMirror S3 關係時、您必須驗證來源與目的地儲存 VM 上是否存在金鑰、如果沒有、請重新產生金鑰。如果您需要重新產生這些金鑰、您必須確保使用存取和秘密金鑰配對的所有用戶端和SnapMirror物件儲存組態、都會以新的金鑰更新。


如需S3伺服器組態的相關資訊、請參閱下列主題：

* link:../task_object_provision_enable_s3_server.html["在儲存VM上啟用S3伺服器"]
* link:../s3-config/index.html["關於 ONTAP S3 組態程序"]


如需叢集與儲存VM對等關係的相關資訊、請參閱下列主題：

* link:../task_dp_prepare_mirror.html["準備鏡射與保存（System Manager、步驟1至6）"]
* link:../peering/index.html["叢集與SVM對等（CLI）"]




== 支援的 SnapMirror 關係

SnapMirror S3 支援扇出和串聯關係。如需總覽link:../data-protection/supported-deployment-config-concept.html["橫向和串聯資料保護部署"]、請參閱。

SnapMirror S3 不支援以風扇方式部署（多個來源貯體和單一目的地貯體之間的資料保護關係）。SnapMirror S3 可支援從多個叢集到單一次要叢集的多個儲存區鏡像、但每個來源儲存區都必須在次要叢集上擁有自己的目的地儲存區。



== 控制對 S3 儲存區的存取

建立新的儲存庫時、您可以建立使用者和群組來控制存取。

雖然 SnapMirror S3 會將物件從來源貯體複寫到目的地貯體，但不會將群組和貯體原則從來源物件存放區複寫到目的地物件存放區。

必須在目的地物件存放區上設定使用者，群組原則，權限及類似元件，以便用戶端在容錯移轉事件期間存取目的地儲存區。

如需詳細資訊、請參閱下列主題：

* link:../task_object_provision_add_s3_users_groups.html["新增S3使用者和群組（系統管理員）"]
* link:../s3-config/create-s3-user-task.html["建立S3使用者（CLI）"]
* link:../s3-config/create-modify-groups-task.html["建立或修改S3群組（CLI）"]




== 將 S3 物件鎖定及版本設定搭配 SnapMirror S3 使用

您可以在啟用物件鎖定和版本設定的 ONTAP 儲存區上使用 SnapMirror S3 ，但需注意以下幾點：

* 若要在啟用物件鎖定的情況下複寫來源貯體，目的地貯體也必須啟用物件鎖定。此外，來源和目的地都必須啟用版本設定。如此可避免在兩個貯體都有不同的預設保留原則時，將刪除鏡射到目的地貯體。
* S3 SnapMirror 不會複寫物件的歷史版本。只會複寫物件的目前版本。


當物件鎖定物件鏡射至目的地儲存區時，它們會維持其原始保留時間。如果複寫未鎖定的物件，則會採用目的地儲存區的預設保留期間。例如：

* 貯體 A 的預設保留期間為 30 天，而貯體 B 的預設保留期間為 60 天。從 Bucket A 複製到 Bucket B 的物件將維持其 30 天的保留期間，即使它低於 Bucket B 的預設保留期間
* 貯體 A 沒有預設保留期間，而貯體 B 的預設保留期間為 60 天。將解除鎖定的物件從儲存區 A 複寫至儲存區 B 時，將採用 60 天的保留期間。如果物件是在 Bucket A 中手動鎖定，則當複寫到 Bucket B 時，它會維持其原始保留期間
* 貯體 A 的預設保留期間為 30 天，而貯體 B 則沒有預設保留期間。從 Bucket A 複製到 Bucket B 的物件將維持其 30 天的保留期間。

