---
permalink: nvme/support-limitations.html 
sidebar: sidebar 
keywords: nvme, namespaces, considerations, provisioning 
summary: NVMe支援會因ONTAP 您的版本的支援、平台和組態而異。 
---
= NVMe 組態、支援和限制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9.4 開始 link:https://docs.netapp.com/us-en/ontap/san-admin/manage-nvme-concept.html["非揮發性記憶體高速（ NVMe ）"] 傳輸協定適用於 SAN 環境。FC-NVMe採用與傳統FC網路相同的實體設定和分區實務做法、但相較於FC-SCSI、可提供更高的頻寬、增加IOPs並縮短延遲。

NVMe 支援和限制會因您的 ONTAP 版本、平台和組態而異。如需特定組態的詳細資訊、請參閱 link:https://imt.netapp.com/matrix/["NetApp 互通性對照表工具"]。



== 組態

* 您可以使用單一架構或 Multifabric 、透過單一節點或 HA 配對來設定 NVMe 組態。
* 您應該為每個支援SAN的SVM設定一個管理LIF。
* 不支援使用異質FC交換器架構、但內嵌刀鋒交換器除外。
+
上會列出特定例外狀況 link:https://mysupport.netapp.com/matrix["NetApp 互通性對照表工具"^]。

* 串聯、部分網狀、全網狀、核心邊緣和導向架構都是將FC交換器連接至光纖的業界標準方法、而且都受到支援。
+
一個網路可由一或多個交換器組成、而且儲存控制器可連接至多個交換器。





== 功能

您的 ONTAP 版本支援下列 NVMe 功能。

[cols="2*"]
|===


| 從ONTAP 無到無...開始 | NVMe 支援 


| 9.12.1  a| 
NVMe / FC 上的 4 節點 MetroCluster IP 組態。
* 在 9.12.1 之前的 NVMe 不支援 MetroCluster 組態。
* NVMe / TCP 不支援 MetroCluster 組態。



| 9.10.1 | xref:../nvme/resize-namespace-task.html[調整命名空間大小] 


| 9.9.1  a| 
* 命名空間與 LUN 共存於同一個磁碟區。




| 9.8  a| 
* 協定共存
+
SCSI 、 NAS 和 NVMe 通訊協定可以存在於同一個儲存虛擬機器（ SVM ）上。

+
在 ONTAP 9.8 之前、 NVMe 可以是 SVM 上唯一的傳輸協定。
*





| 9.6%  a| 
* 512 位元組區塊和 4096 位元組區塊用於命名空間
+
預設值為4096。只有當主機作業系統不支援4096位元組區塊時、才應使用512。

* 使用對應命名空間來移動 Volume




| 9.5. | 多重路徑 HA 配對容錯移轉 / 恢復。 
|===


== 通訊協定

支援下列 NVMe 通訊協定。

[cols="3*"]
|===


| 傳輸協定 | 從ONTAP 無到無...開始 | 允許者... 


| TCP | 9.10.1 | 預設 


| FC | 9.4. | 預設 
|===
從 ONTAP 9.8 開始、您可以在同一個儲存虛擬機器（ SVM ）上設定 SCSI 、 NAS 和 NVMe 通訊協定。
在 ONTAP 9.7 及更早版本中、 NVMe 可能是 SVM 上唯一的傳輸協定。



== 每個叢集的平台和節點

NVMe / FC 和 NVMe / TCP 通訊協定支援如下。


NOTE: 下列採用 32GB FC HBA 的平台支援 NVMe / FC 。

[cols="3*"]
|===


| 從ONTAP 無到無...開始 | 平台 | 每個叢集的最大節點數 


| 9.12.1  a| 
* AFF
* ASA

| 12. 


| 9.9.1  a| 
* AFF
* ASA

| 4. 


| 9.4. | 僅限 AFF | 4. 
|===


== 命名空間

使用 NVMe 命名空間時、您應該注意下列事項：

* 如果LUN中的資料遺失、則無法從命名空間還原資料、反之亦然。
* 命名空間的空間保證與所含磁碟區的空間保證相同。
* 您無法在磁碟區上建立命名空間、從以 7-mode 運作的 Data ONTAP 轉換。
* 命名空間不支援下列項目：
+
** 重新命名
** 跨Volume移動
** 跨Volume複本
** 隨需複製






== 其他限制

.NVMe組態不支援下列ONTAP 功能：
* 同步
* 虛擬儲存主控台
+
.. 下列項目僅適用於執行ONTAP 下列功能的節點：


* NVMe LIF和命名空間必須裝載在同一個節點上。
* NVMe服務必須在建立NVMe LIF之前建立。


請參閱 https://hwu.netapp.com["NetApp Hardware Universe"^] 以取得NVMe限制的完整清單。

.相關資訊
link:https://www.netapp.com/pdf.html?item=/media/10680-tr4080.pdf["現代 SAN 的最佳實務做法"]
