---
sidebar: sidebar 
permalink: networking/add_or_remove_ports_from_a_broadcast_domain97.html 
keywords: adding, add, create, creating, remove, removing, delete, deleting, port, broadcast, domain, reachability, repair, physical, switch, configuration, manually add or remove ports from a broadcast domain, network port broadcast-domain add-ports, network port broadcast-domain remove-ports, examples of adding and removing ports, move, moving, broadcast, domain, ipspace, remove ports from a broadcast domain, broadcast-domain remove-ports 
summary: 不需要或建議從廣播網域手動新增和移除連接埠 
---
= 從廣播網域新增或移除連接埠（ ONTAP 9.7 及更早版本）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以在最初建立廣播網域時新增網路連接埠、或是在現有的廣播網域中新增或移除連接埠。這可讓您有效率地使用叢集中的所有連接埠。

如果您要新增至新廣播網域的連接埠已經在另一個廣播網域中、則必須先從該廣播網域移除連接埠、然後再將它們指派給新的廣播網域。


NOTE: 這項工作與ONTAP 不ONTAP 適用於《產品介紹》9.0 - 9.7、而非《產品介紹》9.8有關。

.開始之前
* 您必須是叢集管理員才能執行此工作。
* 您打算新增至廣播網域的連接埠不得屬於其他廣播網域。
* 已屬於介面群組的連接埠無法個別新增至廣播網域。


.關於這項工作
新增和移除網路連接埠時、適用下列規則：

|===


| 新增連接埠時... | 移除連接埠時... 


| 連接埠可以是網路連接埠、VLAN或介面群組（ifgrps）。 | 不適用 


| 這些連接埠會新增至廣播網域的系統定義容錯移轉群組。 | 這些連接埠會從廣播網域中的所有容錯移轉群組中移除。 


| 連接埠的MTU會更新為廣播網域中設定的MTU值。 | 連接埠的MTU不變。 


| 連接埠的IPspace會更新為廣播網域的IPspace值。 | 這些連接埠會移至「預設」IPspace、且不含廣播網域屬性。 
|===

NOTE: 如果您使用移除介面群組的最後一個成員連接埠 `network port ifgrp remove-port` 命令時、會導致介面群組連接埠從廣播網域中移除、因為廣播網域中不允許使用空的介面群組連接埠。

.步驟
. 使用顯示目前指派或未指派給廣播網域的連接埠 `network port show` 命令。
. 從廣播網域新增或移除網路連接埠：
+
[cols="40,60"]
|===


| 如果您想要... | 使用... 


 a| 
新增連接埠至廣播網域
 a| 
`network port broadcast-domain add-ports`



 a| 
從廣播網域移除連接埠
 a| 
`network port broadcast-domain remove-ports`

|===
. 確認已從廣播網域新增或移除連接埠：
+
`network port show`



如需這些命令的詳細資訊、請參閱 link:http://docs.netapp.com/us-en/ontap-cli["ONTAP 9 命令參照"^]。



== 新增和移除連接埠的範例

下列命令會將節點叢集上的連接埠e0g與節點叢集上的連接埠e0g新增至預設IPspace中的廣播網域bcast1：

`cluster-1::> network port broadcast-domain add-ports -broadcast-domain bcast1 -ports cluster-1-01:e0g,cluster1-02:e0g`

下列命令會在叢集IPspace中新增兩個叢集連接埠以廣播網域叢集：

`cluster-1::> network port broadcast-domain add-ports -broadcast-domain Cluster -ports cluster-2-03:e0f,cluster2-04:e0f -ipspace Cluster`

下列命令會從預設IPspace的廣播網域bcast1中移除節點叢集1上的連接埠e0e：

`cluster-1::> network port broadcast-domain remove-ports -broadcast-domain bcast1 -ports cluster-1-01:e0e`
