---
sidebar: sidebar 
permalink: networking/commands_for_managing_snmp.html 
keywords: snmp, traps, traphosts, trap, traphost, manage, managing, users, user, configure, configuring, modify, modifying, set, setting, event, command, system snmp, security, options -option-name snmp.enable -option-value on, options -option-name snmp.enable -option-value off, commands for managing snmp, commands for managing snmp v1, v2c, and v3 users, commands for providing contact and location information, commands for managing SNMP communities, command for displaying snmp option values, commands for managing snmp traps and traphosts, commands for managing events related to snmp traps, system snmp, security login create, security snmpusers and security login show -application snmp, security login create, security login delete, security snmpusers and security login show -application snmp, security login modify, system snmp contact, system snmp location, system snmp community add, system snmp community delete, system snmp community show, system snmp show 
summary: 管理SNMP、SNMP使用者、設陷、設陷事件及traphosts 
---
= 管理SNMP的命令
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以使用「系統SNMP」命令來管理SNMP、設陷和traphosts。您可以使用「安全性」命令來管理每個SVM的SNMP使用者。您可以使用「EVENT」命令來管理與SNMP設陷相關的事件。



== 設定SNMP的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
在叢集上啟用SNMP
 a| 
「options -option-name SNMP。enable -option-value on」

SNMP服務必須符合管理（管理）防火牆原則。您可以使用系統服務防火牆原則show命令來驗證是否允許SNMP。



 a| 
停用叢集上的SNMP
 a| 
「options -option-name SNMP。enable -option-value Off」（選項-option-name SNMP。請啟用-option-Value Off）

|===


== 用於管理SNMP v1、v2c和v3使用者的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
設定SNMP使用者
 a| 
《安全登入建立》



 a| 
顯示SNMP使用者
 a| 
「安全性的SNMP使用者與安全性登入顯示-應用程式SNMP」



 a| 
刪除SNMP使用者
 a| 
'安全登入刪除'



 a| 
修改SNMP使用者登入方法的存取控制角色名稱
 a| 
"ecurity登入修改"

|===


== 提供聯絡人和位置資訊的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
顯示或修改叢集的聯絡詳細資料
 a| 
"System SNMP contact"（系統SNMP聯絡人）



 a| 
顯示或修改叢集的位置詳細資料
 a| 
系統SNMP位置

|===


== 管理SNMP社群的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
為SVM或叢集中的所有SVM新增唯讀（RO）社群
 a| 
"System SNMP community add"（系統SNMP社群新增



 a| 
刪除社群或所有社群
 a| 
系統SNMP社群刪除



 a| 
顯示所有社群的清單
 a| 
「系統SNMP社群展示」

|===
由於SVM並非SNMP標準的一部分、因此資料LIF上的查詢必須包含NetApp根ID（1.3.6.1.4.1.789）、例如「snmpwalk-v 2c -c snmpNFS 10.238.19.14 1.3.6.1.4.1.789」。



== 用於顯示SNMP選項值的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
顯示所有SNMP選項的目前值、包括叢集聯絡人、聯絡人位置、叢集是否設定為傳送陷阱、traphosts清單、以及社群和存取控制類型清單
 a| 
「System SNMP show」

|===


== 用於管理SNMP陷阱和traphosts的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
啟用從叢集傳送的SNMP設陷
 a| 
'系統SNMP INIT -INIT 1'



 a| 
停用從叢集傳送的SNMP設陷
 a| 
'系統SNMP INIT -INIT 0'



 a| 
新增接收叢集中特定事件SNMP通知的traphost
 a| 
"System SNMP traphost add"



 a| 
刪除traphost
 a| 
"System SNMP traphost delet"（系統SNMP traphost刪除）



 a| 
顯示traphosts清單
 a| 
「System SNMP traphost show」

|===


== 用於管理與SNMP陷阱相關的事件的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
顯示產生SNMP陷阱（內建）的事件
 a| 
「活動路線展」

使用「-snmp-supporttrue」參數、只檢視與SNMP相關的事件。

使用「instance -messagename <message>」參數來檢視事件發生原因的詳細說明、以及任何修正行動。

不支援將個別SNMP設陷事件路由傳送至特定的traphost目的地。所有SNMP設陷事件都會傳送至所有的traphost目的地。



 a| 
顯示SNMP設陷記錄清單、這是已傳送至SNMP設陷的事件通知
 a| 
《事件零食秀》



 a| 
刪除SNMP設陷歷程記錄
 a| 
事件記錄刪除

|===
如需「系統SNMP」、「安全性」及「事件」命令的詳細資訊、請參閱手冊頁： http://["指令ONTAP"^]
