---
sidebar: sidebar 
permalink: networking/commands_for_managing_firewall_service_and_policies.html 
keywords: manage, managing, firewall, fire, wall, service, policy, policies, commands for managing firewall service and policies, system services firewall, system services firewall policy, network interface modify, system services firewall modify, system services firewall show, system services firewall policy create, network interface modify -lif lifname -firewall-policy, system services firewall policy modify, system services firewall policy show, system services firewall policy clone, system services firewall policy delete 
summary: 管理防火牆服務 
---
= 用於管理 ONTAP 中防火牆服務和原則的命令
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用 `system services firewall` 管理防火牆服務的命令 `system services firewall policy` 管理防火牆原則的命令、以及 `network interface modify` 管理生命的防火牆設定的命令。

|===


| 如果您想要... | 使用此命令... 


 a| 
啟用或停用防火牆服務
 a| 
`system services firewall modify`



 a| 
顯示目前的防火牆服務組態
 a| 
`system services firewall show`



 a| 
建立防火牆原則或新增服務至現有的防火牆原則
 a| 
`system services firewall policy create`



 a| 
將防火牆原則套用至LIF
 a| 
`network interface modify -lif lifname -firewall-policy`



 a| 
修改與防火牆原則相關的IP位址和網路遮罩
 a| 
`system services firewall policy modify`



 a| 
顯示防火牆原則的相關資訊
 a| 
`system services firewall policy show`



 a| 
建立一個新的防火牆原則、該原則是現有原則的確切複本
 a| 
`system services firewall policy clone`



 a| 
刪除LIF未使用的防火牆原則
 a| 
`system services firewall policy delete`

|===
深入瞭解 `system services firewall`， `system services firewall policy`和 `network interface modify` link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]。
