---
sidebar: sidebar 
permalink: networking/commands_for_managing_snmp.html 
keywords: snmp, traps, traphosts, trap, traphost, manage, managing, users, user, configure, configuring, modify, modifying, set, setting, event, command, system snmp, security, options -option-name snmp.enable -option-value on, options -option-name snmp.enable -option-value off, commands for managing snmp, commands for managing snmp v1, v2c, and v3 users, commands for providing contact and location information, commands for managing SNMP communities, command for displaying snmp option values, commands for managing snmp traps and traphosts, commands for managing events related to snmp traps, system snmp, security login create, security snmpusers and security login show -application snmp, security login create, security login delete, security snmpusers and security login show -application snmp, security login modify, system snmp contact, system snmp location, system snmp community add, system snmp community delete, system snmp community show, system snmp show 
summary: 管理SNMP、SNMP使用者、設陷、設陷事件及traphosts 
---
= 用於管理 SNMP ，設陷和 traphosts 的 ONTAP 命令
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用 `system snmp` 用於管理 SNMP 、設陷和 traphosts 的命令。您可以使用 `security` 用於管理每個 SVM 的 SNMP 使用者的命令。您可以使用 `event` 管理與 SNMP 設陷相關事件的命令。



== 設定SNMP的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
在叢集上啟用SNMP
 a| 
`options -option-name snmp.enable -option-value on`

SNMP服務必須符合管理（管理）防火牆原則。您可以使用系統服務防火牆原則show命令來驗證是否允許SNMP。



 a| 
停用叢集上的SNMP
 a| 
`options -option-name snmp.enable -option-value off`

|===


== 用於管理SNMP v1、v2c和v3使用者的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
設定SNMP使用者
 a| 
`security login create`



 a| 
顯示SNMP使用者
 a| 
`security snmpusers and security login show -application snmp`



 a| 
刪除SNMP使用者
 a| 
`security login delete`



 a| 
修改SNMP使用者登入方法的存取控制角色名稱
 a| 
`security login modify`

|===


== 提供聯絡人和位置資訊的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
顯示或修改叢集的聯絡詳細資料
 a| 
`system snmp contact`



 a| 
顯示或修改叢集的位置詳細資料
 a| 
`system snmp location`

|===


== 管理SNMP社群的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
為SVM或叢集中的所有SVM新增唯讀（RO）社群
 a| 
`system snmp community add`



 a| 
刪除社群或所有社群
 a| 
`system snmp community delete`



 a| 
顯示所有社群的清單
 a| 
`system snmp community show`

|===
由於 SVM 不是 SNMP 標準的一部分、因此資料生命體的查詢必須包含 NetApp 根 OID （ 1.3.6.1.4.1.789 ）、例如 `snmpwalk -v 2c -c snmpNFS 10.238.19.14 1.3.6.1.4.1.789`。



== 用於顯示SNMP選項值的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
顯示所有SNMP選項的目前值、包括叢集聯絡人、聯絡人位置、叢集是否設定為傳送陷阱、traphosts清單、以及社群和存取控制類型清單
 a| 
`system snmp show`

|===


== 用於管理SNMP陷阱和traphosts的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
啟用從叢集傳送的SNMP設陷
 a| 
`system snmp init -init 1`



 a| 
停用從叢集傳送的SNMP設陷
 a| 
`system snmp init -init 0`



 a| 
新增接收叢集中特定事件SNMP通知的traphost
 a| 
`system snmp traphost add`



 a| 
刪除traphost
 a| 
`system snmp traphost delete`



 a| 
顯示traphosts清單
 a| 
`system snmp traphost show`

|===


== 用於管理與SNMP陷阱相關的事件的命令

|===


| 如果您想要... | 使用此命令... 


 a| 
顯示產生SNMP陷阱（內建）的事件
 a| 
`event route show`

使用 `-snmp-support true` 僅檢視 SNMP 相關事件的參數。

使用 `instance -messagename <message>` 此參數可檢視事件發生原因的詳細說明、以及任何修正動作。

不支援將個別SNMP設陷事件路由傳送至特定的traphost目的地。所有SNMP設陷事件都會傳送至所有的traphost目的地。



 a| 
顯示SNMP設陷記錄清單、這是已傳送至SNMP設陷的事件通知
 a| 
`event snmphistory show`



 a| 
刪除SNMP設陷歷程記錄
 a| 
`event snmphistory delete`

|===
.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+snmp["系統 SNMP"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-snmpusers.html["安全性"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security["安全性"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=event["活動"^]

