---
sidebar: sidebar 
permalink: networking/commands_for_managing_failover_groups_and_policies.html 
keywords: manage, managing, failover, fail, over, group, policy, policies, groups, commands for managing failover groups and policies, network interface failover-groups, network interface modify, network interface failover-groups add-targets, network interface failover-groups remove-targets, network interface failover-groups modify, network interface modify -failover-group -failover-policy, network interface failover-groups show, rename, delete 
summary: 管理容錯移轉群組 
---
= 用於管理容錯移轉群組和原則的 ONTAP 命令
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用 `network interface failover-groups` 管理容錯移轉群組的命令。您可以使用 `network interface modify` 用於管理套用至 LIF 的容錯移轉群組和容錯移轉原則的命令。

|===


| 如果您想要... | 使用此命令... 


 a| 
將網路連接埠新增至容錯移轉群組
 a| 
`network interface failover-groups add-targets`



 a| 
從容錯移轉群組移除網路連接埠
 a| 
`network interface failover-groups remove-targets`



 a| 
修改容錯移轉群組中的網路連接埠
 a| 
`network interface failover-groups modify`



 a| 
顯示目前的容錯移轉群組
 a| 
`network interface failover-groups show`



 a| 
在LIF上設定容錯移轉
 a| 
`network interface modify -failover-group -failover-policy`



 a| 
顯示每個LIF所使用的容錯移轉群組和容錯移轉原則
 a| 
`network interface show -fields failover-group, failover-policy`



 a| 
重新命名容錯移轉群組
 a| 
`network interface failover-groups rename`



 a| 
刪除容錯移轉群組
 a| 
`network interface failover-groups delete`

|===

NOTE: 修改容錯移轉群組、使其無法為叢集中的任何LIF提供有效的容錯移轉目標、可能會在LIF嘗試容錯移轉時造成中斷。

.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network-interface-failover["網路介面容錯移轉"^]
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-modify.html["修改網路介面"^]

