---
sidebar: sidebar 
permalink: networking/configure_lif_service_policies.html 
keywords: create service policy, assign service policy, service policy commands, configure lif service policies, create and assign a service policy for lifs, configure lif service policies, create a service policy for lifs, network interface service show, service-policy create, assign a service policy to a lif, examples, commands for managing lif service policies 
summary: 建立及指派LIF的服務原則 
---
= 設定 ONTAP 叢集的 LIF 服務原則
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以設定LIF服務原則、以識別將使用LIF的單一服務或服務清單。



== 為lifs建立服務原則

您可以為lifs建立服務原則。您可以將服務原則指派給一或多個LIF、讓LIF能夠傳輸單一服務或服務清單的流量。

您需要進階權限才能執行 `network interface service-policy create` 命令。

.關於這項工作
內建的服務和服務原則可用於管理資料和系統SVM上的資料和管理流量。大部分的使用案例都是使用內建服務原則而非建立自訂服務原則來滿足。

您可以視需要修改這些內建服務原則。

.步驟
. 檢視叢集中可用的服務：
+
....
network interface service show
....
+
服務代表LIF存取的應用程式、以及叢集所服務的應用程式。每項服務都包含零個或多個應用程式正在偵聽的TCP和udp連接埠。

+
提供下列額外的資料與管理服務：

+
....
cluster1::> network interface service show

Service                     Protocol:Ports
-------                     --------------
cluster-core                -
data-cifs                   -
data-core                   -
data-flexcache              -
data-iscsi                  -
data-nfs                    -
intercluster-core           tcp:11104-11105
management-autosupport      -
management-bgp              tcp:179
management-core             -
management-https            tcp:443
management-ssh              tcp:22
12 entries were displayed.
....
. 檢視叢集中的服務原則：
+
....
cluster1::> network interface service-policy show

Vserver   Policy                     Service: Allowed Addresses
--------- -------------------------- ----------------------------------------
cluster1
          default-intercluster       intercluster-core: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

          default-management         management-core: 0.0.0.0/0
                                     management-autosupport: 0.0.0.0/0
                                     management-ssh: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

          default-route-announce     management-bgp: 0.0.0.0/0

Cluster
          default-cluster            cluster-core: 0.0.0.0/0

vs0
          default-data-blocks        data-core: 0.0.0.0/0
                                     data-iscsi: 0.0.0.0/0

          default-data-files         data-core: 0.0.0.0/0
                                     data-nfs: 0.0.0.0/0
                                     data-cifs: 0.0.0.0/0
                                     data-flexcache: 0.0.0.0/0

          default-management         data-core: 0.0.0.0/0
                                     management-ssh: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

7 entries were displayed.
....
. 建立服務原則：
+
....
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them only when directed to do so by technical support.
Do you wish to continue? (y or n): y

cluster1::> network interface service-policy create -vserver <svm_name> -policy <service_policy_name> -services <service_name> -allowed-addresses <IP_address/mask,...>
....
+
** 「service_name」指定應包含在原則中的服務清單。
** "ip_address/mask"指定允許存取服務原則中服務之位址的子網路遮罩清單。根據預設、所有指定的服務都會新增預設允許位址清單0.00.0.0/0、以允許來自所有子網路的流量。如果提供了非預設允許的位址清單、則使用該原則的LIF會設定為封鎖所有來源位址不符合任何指定遮罩的要求。
+
下列範例說明如何針對包含_NFS_和_SMB_服務的SVM建立資料服務原則（_svm1_data_policy__）：

+
....
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them only when directed to do so by technical support.
Do you wish to continue? (y or n): y

cluster1::> network interface service-policy create -vserver svm1 -policy svm1_data_policy -services data-nfs,data-cifs,data-core
....
+
下列範例顯示如何建立叢集間服務原則：

+
....
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them only when directed to do so by technical support.
Do you wish to continue? (y or n): y

cluster1::> network interface service-policy create -vserver cluster1 -policy intercluster1 -services intercluster-core
....


. 確認已建立服務原則。
+
....
cluster1::> network interface service-policy show
....
+
下列輸出顯示可用的服務原則：

+
....
cluster1::> network interface service-policy show

Vserver   Policy                     Service: Allowed Addresses
--------- -------------------------- ----------------------------------------
cluster1
          default-intercluster       intercluster-core: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

          intercluster1              intercluster-core: 0.0.0.0/0

          default-management         management-core: 0.0.0.0/0
                                     management-autosupport: 0.0.0.0/0
                                     management-ssh: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

          default-route-announce     management-bgp: 0.0.0.0/0

Cluster
          default-cluster            cluster-core: 0.0.0.0/0

vs0
          default-data-blocks        data-core: 0.0.0.0/0
                                     data-iscsi: 0.0.0.0/0

          default-data-files         data-core: 0.0.0.0/0
                                     data-nfs: 0.0.0.0/0
                                     data-cifs: 0.0.0.0/0
                                     data-flexcache: 0.0.0.0/0

          default-management         data-core: 0.0.0.0/0
                                     management-ssh: 0.0.0.0/0
                                     management-https: 0.0.0.0/0

          svm1_data_policy           data-core: 0.0.0.0/0
                                     data-nfs: 0.0.0.0/0
                                     data-cifs: 0.0.0.0/0

9 entries were displayed.
....


.完成後
在建立時或修改現有LIF、將服務原則指派給LIF。



== 將服務原則指派給LIF

您可以在建立LIF時或修改LIF、將服務原則指派給LIF。服務原則會定義可與LIF搭配使用的服務清單。

.關於這項工作
您可以在管理VM和資料SVM中指派生命權的服務原則。

.步驟
視您要將服務原則指派給LIF的時間而定、請執行下列其中一項動作：

[cols="25,75"]
|===
| 如果您... | 指派服務原則... 


| 建立LIF | 網路介面create -vserver Svm_name -lIF <lif_name>-home-node<node_name>-home-port <port_name>｛（-address <ip_address>-netMask<ip_address>）-subnet-name <subnet_name>-service-policy <service_policy_name> 


| 修改LIF | 網路介面修改-vserver <Svm_name>-lif<lif_name>-service-policy <service_policy_name> 
|===
當您為LIF指定服務原則時、不需要指定LIF的資料傳輸協定和角色。也支援透過指定角色和資料傳輸協定來建立LIF。


NOTE: 服務原則只能由建立服務原則時所指定之相同SVM中的LIF使用。



=== 範例

下列範例說明如何修改LIF的服務原則、以使用預設管理服務原則：

....
cluster1::> network interface modify -vserver cluster1 -lif lif1 -service-policy default-management
....


== 管理LIF服務原則的命令

使用 `network interface service-policy` 管理 LIF 服務原則的命令。

如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface+service-policy["指令參考資料ONTAP"^]需詳細 `network interface service-policy`資訊，請參閱。

.開始之前
在主動 SnapMirror 關係中修改 LIF 的服務原則會中斷複寫排程。如果您將 LIF 從叢集間轉換為非叢集間（反之亦然）、則這些變更不會複寫至對等叢集。若要在修改 LIF 服務原則之後更新對等叢集、請先執行 `snapmirror abort` 然後操作 xref:../data-protection/resynchronize-relationship-task.html[重新同步複寫關係]。

|===
| 如果您想要... | 使用此命令... 


 a| 
建立服務原則（需要進階權限）
 a| 
`network interface service-policy create`



 a| 
新增其他服務項目至現有的服務原則（需要進階權限）
 a| 
`network interface service-policy add-service`



 a| 
複製現有的服務原則（需要進階權限）
 a| 
`network interface service-policy clone`



 a| 
修改現有服務原則中的服務項目（需要進階權限）
 a| 
`network interface service-policy modify-service`



 a| 
從現有的服務原則移除服務項目（需要進階權限）
 a| 
`network interface service-policy remove-service`



 a| 
重新命名現有的服務原則（需要進階權限）
 a| 
`network interface service-policy rename`



 a| 
刪除現有的服務原則（需要進階權限）
 a| 
`network interface service-policy delete`



 a| 
將內建服務原則還原為原始狀態（需要進階權限）
 a| 
`network interface service-policy restore-defaults`



 a| 
顯示現有的服務原則
 a| 
`network interface service-policy show`

|===
.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/network-interface-service-show.html["網路介面服務展示"^]
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface+service-policy["網路介面服務原則"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-abort.html["SnapMirror中止"^]

