---
sidebar: sidebar 
permalink: networking/configure_dns_services_auto.html 
keywords: dns, service, services, configuration, configure, configuring, set, up, setup, nfs, smb, cifs, active, directory, statistics, configure dns services, configure dns services for the svm before creating an nfs or smb server, vserver services name-service, configure dynamic dns on the svm, vserver-fqdn 
summary: 在建立NFS或SMB伺服器之前、請先設定SVM的DNS服務 
---
= 設定 DNS 服務（ ONTAP 9.8 及更新版本）
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
在建立NFS或SMB伺服器之前、您必須先為SVM設定DNS服務。一般而言、DNS名稱伺服器是NFS或SMB伺服器要加入之網域的Active Directory整合式DNS伺服器。

.關於這項工作
Active Directory整合式DNS伺服器包含網域LDAP和網域控制器伺服器的服務位置記錄（SRV),如果SVM找不到Active Directory LDAP伺服器和網域控制器、NFS或SMB伺服器設定就會失敗。

SVM使用主機名稱服務ns-交換器資料庫來判斷要使用哪些名稱服務、以及在查詢主機資訊時的順序。主機資料庫支援的兩種名稱服務為檔案和DNS。

在建立SMB伺服器之前、您必須確定DNS是其中一個來源。


NOTE: 若要檢視mgwd程序和SecD程序的DNS名稱服務統計資料、請使用統計資料UI。

.步驟
. 判斷主機名稱服務資料庫目前的組態為何。在此範例中、主機名稱服務資料庫會使用預設設定。
+
`vserver services name-service _ns-switch_ show -vserver _vs1_ -database _hosts_`

+
....
Vserver: vs1
Name Service Switch Database: hosts
Vserver: vs1 Name Service Switch Database: hosts
Name Service Source Order: files, dns
....
. 如有必要、請執行下列動作。
+
.. 依所需順序將DNS名稱服務新增至主機名稱服務資料庫、或重新排序來源。
+
在此範例中、主機資料庫會設定為依該順序使用DNS和本機檔案。

+
`vserver services name-service _ns-switch_ modify -vserver _vs1_ -database _hosts_ -sources _dns,files_`

.. 驗證名稱服務組態是否正確。
+
`vserver services name-service _ns-switch_ show -vserver _vs1_ -database _hosts_`

+
....
Vserver: vs1
Name Service Switch Database: hosts
Name Service Source Order: dns, files
....


. 設定DNS服務。
+
`vserver services name-service dns create -vserver _vs1_ -domains _example.com,example2.com_ -name-servers _10.0.0.50,10.0.0.51_`

+

NOTE: vserver services name-service DNS create命令會執行自動組態驗證、並在ONTAP 無法聯絡名稱伺服器時回報錯誤訊息。

. 確認DNS組態正確、且服務已啟用。
+
....
Vserver: vs1
Domains: example.com, example2.com Name Servers: 10.0.0.50, 10.0.0.51
Enable/Disable DNS: enabled Timeout (secs): 2
Maximum Attempts: 1
....
. 驗證名稱伺服器的狀態。
+
`vserver services name-service dns check -vserver _vs1_`



....
Vserver  Name Server  Status  Status Details
vs1      10.0.0.50    up      Response time (msec): 2
vs1      10.0.0.51    up      Response time (msec): 2
....


== 在SVM上設定動態DNS

如果您想要Active Directory整合式DNS伺服器在DNS中動態登錄NFS或SMB伺服器的DNS記錄、則必須在SVM上設定動態DNS（DDNS）。

.開始之前
必須在SVM上設定DNS名稱服務。如果您使用的是安全的DDNS、則必須使用Active Directory整合的DNS名稱伺服器、而且必須為SVM建立NFS或SMB伺服器或Active Directory帳戶。

.關於這項工作
指定的完整網域名稱（FQDN）必須是唯一的：

指定的完整網域名稱（FQDN）必須是唯一的：

* 若為 NFS 、則為中指定的值 `-vserver-fqdn` 作為的一部分 `vserver services name-service dns dynamic-update` 命令會成為已註冊的 FQDN 。
* 對於SMB、指定為CIFS伺服器的NetBios名稱和CIFS伺服器完整網域名稱的值、會成為該LIF的註冊FQDN。這在ONTAP 不進行設定的情況下無法進行。在下列案例中、LIF FQDN為「CIFS_VS1.EXAMPLE.COM":」
+
....
cluster1::> cifs server show -vserver vs1

                                          Vserver: vs1
                         CIFS Server NetBIOS Name: CIFS_VS1
                    NetBIOS Domain/Workgroup Name: EXAMPLE
                      Fully Qualified Domain Name: EXAMPLE.COM
                              Organizational Unit: CN=Computers
Default Site Used by LIFs Without Site Membership:
                                   Workgroup Name: -
                                   Kerberos Realm: -
                             Authentication Style: domain
                CIFS Server Administrative Status: up
                          CIFS Server Description:
                          List of NetBIOS Aliases: -
....



NOTE: 若要避免SVM FQDN組態失敗、但不符合DDNS更新的RFC規則、請使用符合RFC規範的FQDN名稱。如需詳細資訊、請參閱 link:https://tools.ietf.org/html/rfc1123["RFC 1123"]。

.步驟
. 在SVM上設定DDNS：
+
`vserver services name-service dns dynamic-update modify -vserver _vserver_name_ -is- enabled _true_ [-use-secure {true|false} -vserver-fqdn _FQDN_used_for_DNS_updates_`

+
`vserver services name-service dns dynamic-update modify -vserver _vs1_ -is-enabled _true_ - use-secure _true_ -vserver-fqdn _vs1.example.com_`

+
星號無法作為自訂FQDN的一部分使用。例如、 `*.netapp.com` 無效。

. 確認DDNS組態正確：
+
`vserver services name-service dns dynamic-update show`

+
....
Vserver  Is-Enabled Use-Secure Vserver FQDN      TTL
-------- ---------- ---------- ----------------- -------
vs1      true       true       vs1.example.com   24h
....

