---
sidebar: sidebar 
permalink: networking/configure_network_security_using_federal_information_processing_standards_@fips@.html 
keywords: 'federal, information, processing, standards, fips, 140-2, compliant, ssl, connections, tlsv1.2, tlsv1.1, tlsv1, enable, enabling, disable, disabling, view, status, federal information processing standards (fips) 140-2 compliant for all ssl connections, configure network security using federal information processing standards (fips), enable fips, disable fips, view fips compliance status' 
summary: 所有SSL連線均符合聯邦資訊處理標準（FIPS）140-2 
---
= 使用聯邦資訊處理標準（FIPS）設定網路安全性
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
所有SSL連線均符合聯邦資訊處理標準（FIPS）140-2。ONTAP您可以開啟和關閉SSL FIPS模式、全域設定SSL傳輸協定、以及關閉ONTAP 任何弱密碼、例如RC4 in整套功能。

根據預設、ONTAP 將「SSL on支援」設為停用FIPS規範、並啟用SSL傳輸協定、提供下列功能：

* TLSv1.3（從ONTAP 功能9.11.1開始）
* TLSv1.2
* TLSv1.1
* TLSv1


啟用SSL FIPS模式時、ONTAP 從靜止到外部用戶端或ONTAP 伺服器元件的SSL通訊、將使用FIPS相容的SSL加密。

如果您想要系統管理員帳戶使用SSH公開金鑰來存取SVM、則必須先確認主機金鑰演算法受到支援、才能啟用SSL FIPS模式。

*附註：* ONTAP 主機金鑰演算法支援已在更新版本的版本中變更。

[cols="30,30,30"]
|===


| 發行版ONTAP | 支援的金鑰類型 | 不支援的金鑰類型 


 a| 
9.11.1及更新版本
 a| 
ECDSA-SHA2-nistp256
 a| 
RSA-SHA2-512 + RSA-SHA2-256 + ssh - ed25519 + ssh - DSS + ssh - RSA



 a| 
9.10.1及更早版本
 a| 
ECDSA-SHA2-nistp256 + ssh編輯25519
 a| 
SSH-DSS + SSH-RSA

|===
沒有支援金鑰演算法的現有SSH公開金鑰帳戶、必須先以支援的金鑰類型重新設定、才能啟用FIPS、否則系統管理員驗證將會失敗。

如需詳細資訊、請參閱 link:../authentication/enable-ssh-public-key-accounts-task.html["啟用SSH公開金鑰帳戶"]。

如需SSL FIPS模式組態的詳細資訊、請參閱「安全性組態修改」手冊頁。



== 零點9.11.1RC1考量ONTAP

由於修訂版9.11.1RC1、FIPS 140-2法規遵循管理模式不再使用FIPS 140-2驗證的軟體模組。ONTAP

適用於HTTPS的管理與控制面板連線的OpenSSL版本升級為《The OpenSSL version for Management and Control Plane connections for HTTPS（ONTAP此版本的OpenSSL（OpenSSL 3.x FIPS Provider）尚未完成FIPS 140-2密碼模組驗證方案（CMVP）驗證程序。

啟用FIPS相容模式時、用於HTTPS連線的加密演算法會與在密碼編譯演算法驗證方案（CA1938）憑證中發行的OpenSSL Project OpenSSL 3.x FIPS Provider演算法相同。*此變更僅影響ONTAP FIPS相容模式下設定的所有系統。*

一旦更新版的OpenSSL模組ONTAP 在更新版的更新版本中、完成FIPS 140-2與NIST的驗證、就能解決此問題。如果您的環境需要ONTAP 以FIPS 140-2 CMVP驗證模組執行叢集管理控制面板、則建議您不要升級至9.11.1RC1。

這並不會影響NetApp在REST時的加密技術、例如NSE、NVE和NAE、因為這些功能使用的密碼編譯模組與在ONTAP 還原中由OpenSSL提供的模組不同。

如需詳細資訊、請參閱 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Upgrading_to_ONTAP_9.11.1RC1_results_in_FIPS_140-2_compliance_management_configuration_that_is_not_validated["升級ONTAP 至RC1RC1會產生FIPS 140-2法規遵循管理組態、但尚未驗證"^]。



== 啟用FIPS

建議所有安全的使用者在系統安裝或升級之後、立即調整其安全組態。啟用SSL FIPS模式時、ONTAP 從靜止到外部用戶端或ONTAP 伺服器元件的SSL通訊、將使用FIPS相容的SSL加密。

.步驟
. 變更為進階權限層級：
+
"進階權限"

. 啟用FIPS：
+
「安全性組態修改介面SSL -is - FIPS啟用true」

. 當系統提示您繼續時、請輸入「y」
. 如果您執行ONTAP 的是效能不正常的9.8或更早版本、請逐一手動重新開機叢集中的每個節點。從功能支援的9.9.1開始ONTAP 、不需要重新開機。


如果您執行ONTAP 的是更新版本的版本、則不會看到警告訊息。

....
security config modify -interface SSL -is-fips-enabled true

Warning: This command will enable FIPS compliance and can potentially cause some non-compliant components to fail. MetroCluster and Vserver DR require FIPS to be enabled on both sites in order to be compatible.
Do you want to continue? {y|n}: y

Warning: When this command completes, reboot all nodes in the cluster. This is necessary to prevent components from failing due to an inconsistent security configuration state in the cluster. To avoid a service outage, reboot one node at a time and wait for it to completely initialize before rebooting the next node. Run "security config status show" command to monitor the reboot status.
Do you want to continue? {y|n}: y
....


== 停用FIPS

如果您仍在執行較舊的系統組態、並想要設定ONTAP 具有向下相容性的功能、則只有在FIPS停用時、才能開啟SSLv3。

.步驟
. 變更為進階權限層級：
+
"進階權限"

. 輸入下列命令來停用FIPS：
+
「安全性組態修改介面SSL -is - FIPS -啟用假」

. 當系統提示您繼續時、請輸入「y」。
. 如果您執行ONTAP 的是更新版本的版本、請手動重新啟動叢集中的每個節點。從功能支援的9.9.1開始ONTAP 、不需要重新開機。


如果您執行ONTAP 的是更新版本的版本、則不會看到警告訊息。

....
security config modify -interface SSL -supported-protocols SSLv3

Warning: Enabling the SSLv3 protocol may reduce the security of the interface, and is not recommended.
Do you want to continue? {y|n}: y

Warning: When this command completes, reboot all nodes in the cluster. This is necessary to prevent components from failing due to an inconsistent security configuration state in the cluster. To avoid a service outage, reboot one node at a time and wait for it to completely initialize before rebooting the next node. Run "security config status show" command to monitor the reboot status.
Do you want to continue? {y|n}: y
....


== 檢視FIPS法規遵循狀態

您可以查看整個叢集是否正在執行目前的安全性組態設定。

.步驟
. 逐一重新啟動叢集中的每個節點。
+
請勿同時重新啟動所有叢集節點。必須重新開機、才能確保叢集中的所有應用程式都執行新的安全組態、以及FIPS開/關模式、傳輸協定和密碼的所有變更。

. 檢視目前的法規遵循狀態：
+
「安全組態顯示」



....
security config show

          Cluster                                              Cluster Security
Interface FIPS Mode  Supported Protocols     Supported Ciphers Config Ready
--------- ---------- ----------------------- ----------------- ----------------
SSL       false      TLSv1_2, TLSv1_1, TLSv1 ALL:!LOW:!aNULL:  yes
                                             !EXP:!eNULL
....