---
sidebar: sidebar 
permalink: networking/create_an_snmp_community_and_assigning_it_to_a_lif.html 
keywords: create, creation, creating, add, adding, snmp, community, assign, assigning, lif, logical, interface, create an snmp community and assigning it to a lif, snmpwalk, snmpget, snmp community add 
summary: 建立SNMP社群、做為管理站與SVM之間的驗證機制 
---
= 建立SNMP社群並將其指派給LIF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用SNMP v1和SNMP v2c時、您可以建立SNMP社群、做為管理站與儲存虛擬機器（SVM）之間的驗證機制。

透過在資料SVM中建立SNMP社群、您可以在資料生命體上執行諸如「mpdwing」和「snmpGet」等命令。

.關於這項工作
* 在全新安裝ONTAP 的功能中、預設會停用SNMPv1和SNMPv2c。
+
在建立SNMP社群之後、會啟用SNMP v1和SNMP v2c。

* 支援唯讀社群。ONTAP
* 根據預設、指派給資料生命期的「資料」防火牆原則會將SNMP服務設為「deny」。
+
為資料SVM建立SNMP使用者時、您必須建立新的防火牆原則、並將SNMP服務設為「允許」。

+

NOTE: 從ONTAP S振 分9.10.1開始、防火牆原則已過時、並完全由LIF服務原則取代。如需詳細資訊、請參閱 link:../networking/configure_firewall_policies_for_lifs.html["設定lifs的防火牆原則"]。

* 您可以為管理SVM和資料SVM的SNMP v1和SNMP v2c使用者建立SNMP社群。
* 由於SVM並非SNMP標準的一部分、因此資料LIF上的查詢必須包含NetApp root oID（1.3.6.1.4.1.789）、例如「snmpwalk-v 2c -c snmpNFS 10.238.19.14 1.3.6.1.4.1.789」。


.步驟
. 使用「System SNMP community add」命令建立SNMP社群。下列命令顯示如何在管理SVM叢集1中建立SNMP社群：
+
....
system snmp community add -type ro -community-name comty1 -vserver cluster-1
....
+
下列命令顯示如何在資料SVM VS1中建立SNMP社群：

+
....
system snmp community add -type ro -community-name comty2 -vserver vs1
....
. 使用系統SNMP community show命令來驗證是否已建立社群。
+
下列命令顯示為SNMP v1和SNMP v2c所建立的兩個社群：

+
....
system snmp community show
cluster-1
rocomty1
vs1
rocomty2
....
. 使用「系統服務防火牆原則」「show」命令、檢查「資料」防火牆原則中是否允許SNMP作為服務。
+
下列命令顯示預設的「資料」防火牆原則不允許SNMP服務（僅「管理」防火牆原則允許SNMP服務）：

+
....
system services firewall policy show
Vserver Policy       Service    Allowed
------- ------------ ---------- -------------------
cluster-1
        data
                     dns        0.0.0.0/0
                     ndmp       0.0.0.0/0
                     ndmps      0.0.0.0/0
cluster-1
        intercluster
                     https      0.0.0.0/0
                     ndmp       0.0.0.0/0
                     ndmps      0.0.0.0/0
cluster-1
        mgmt
                     dns        0.0.0.0/0
                     http       0.0.0.0/0
                     https      0.0.0.0/0
                     ndmp       0.0.0.0/0
                     ndmps      0.0.0.0/0
                     ntp        0.0.0.0/0
                     snmp       0.0.0.0/0
                     ssh        0.0.0.0/0
....
. 使用「系統服務防火牆原則create」命令建立新的防火牆原則、以允許使用「nMP」服務進行存取。
+
下列命令會建立名為「data1」的新資料防火牆原則、以允許使用「shnMP」

+
....
system services firewall policy create -policy data1 -service snmp -vserver  vs1 -allow-list 0.0.0.0/0

cluster-1::> system services firewall policy show -service snmp
Vserver  Policy       Service    Allowed
-------  ------------ ---------- -------------------
cluster-1
         mgmt
                      snmp       0.0.0.0/0
vs1
         data1
                      snmp       0.0.0.0/0
....
. 使用「network interface modify」命令搭配-firewall-policy參數、將防火牆原則套用至資料LIF。
+
下列命令會將新的「data1」防火牆原則指派給LIF「dataif1」：

+
....
network interface modify -vserver vs1 -lif datalif1 -firewall-policy data1
....

