---
sidebar: sidebar 
permalink: networking/create_a_broadcast_domain_reference.html 
keywords: create, creation, creating, add, adding, broadcast, domain, create a broadcast domain, broadcast domains group network ports in the cluster that belong to the same layer 2 network, network port broadcast-domain remove-ports 
summary: 廣播網域會將叢集中屬於同一個第2層網路的網路連接埠分組 
---
= 建立廣播網域
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
建立廣播網域、將叢集中屬於同一層2網路的網路連接埠分組。然後、SVM便可使用這些連接埠。

.開始之前
您打算新增至廣播網域的連接埠不得屬於其他廣播網域。

.關於這項工作
* 所有廣播網域名稱在IPspace內必須是唯一的。
* 新增至廣播網域的連接埠可以是實體網路連接埠、VLAN或介面群組（ifgrps）。
* 如果您要使用的連接埠屬於另一個廣播網域、但未使用、請使用 `network port broadcast-domain remove-ports` 從現有廣播網域移除連接埠的命令。
* 新增至廣播網域之連接埠的MTU會更新為廣播網域中設定的MTU值。
* MTU值必須符合連接至該層2網路的所有裝置、但e0M連接埠處理管理流量除外。
* 如果您未指定IPspace名稱、則會在「預設」IPspace中建立廣播網域。


為了簡化系統組態、系統會自動建立同名的容錯移轉群組、其中包含相同的連接埠。

.步驟
. 檢視目前未指派給廣播網域的連接埠：
+
`network port show`

+
如果顯示器很大、請使用 `network port show -broadcast-domain` 僅檢視未指派連接埠的命令。

. 建立廣播網域：
+
`network port broadcast-domain create -broadcast-domain _broadcast_domain_name_ -mtu _mtu_value_ [-ipspace _ipspace_name_] [-ports _ports_list_]`

+
** `_broadcast_domain_name_` 是您要建立的廣播網域名稱。
** `_mtu_value_` 為 IP 封包的 MTU 大小； 1500 和 9000 為典型值。
+
此值會套用至新增至此廣播網域的所有連接埠。

** `_ipspace_name_` 是要新增此廣播網域的 IPspace 名稱。
+
除非您指定此參數的值、否則會使用「預設」IPspace。

** `_ports_list_` 是要新增至廣播網域的連接埠清單。
+
連接埠會以格式新增 `_node_name:port_number_`例如、 `node1:e0c`。



. 確認已視需要建立廣播網域：
`network port show -instance -broadcast-domain _new_domain_`


.範例
下列命令會在預設IPspace中建立廣播網域bcast1、將MTU設為1500、並新增四個連接埠：

`network port broadcast-domain create -broadcast-domain _bcast1_ -mtu _1500_ -ports _cluster1-01:e0e,cluster1-01:e0f,cluster1-02:e0e,cluster1-02:e0f_`

.完成後
您可以透過建立子網路來定義廣播網域中可用的IP位址集區、或是現在可以將SVM和介面指派給IPspace。如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/ontap-sm-classic/peering/index.html["叢集與SVM對等關係"]。

如果您需要變更現有廣播網域的名稱、請使用 `network port broadcast-domain rename` 命令。
