---
sidebar: sidebar 
permalink: networking/determine_which_ports_can_be_used_for_a_broadcast_domains.html 
keywords: move, moving, broadcast, domain, ipspace, determining which ports can be used for a broadcast domain, before you can configure a broadcast domain to add to the new ipspace, you must determine what ports are available for the broadcast domain 
summary: 您必須先判斷哪些連接埠可用於廣播網域、才能設定廣播網域以新增IPspace 
---
= 判斷哪些連接埠可用於廣播網域
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您必須先判斷哪些連接埠可用於廣播網域、才能設定廣播網域以新增IPspace。


NOTE: 這項工作與ONTAP 不ONTAP 適用於《產品介紹》9.0 - 9.7、而非《產品介紹》9.8有關。

您必須是叢集管理員才能執行此工作。

.關於這項工作
* 連接埠可以是實體連接埠、VLAN或介面群組（ifGroups）。
* 您要新增至新廣播網域的連接埠無法指派給現有的廣播網域。
* 如果您要新增至廣播網域的連接埠已經在其他廣播網域中（例如、預設IPspace中的預設廣播網域）、則您必須先從該廣播網域移除連接埠、再將它們指派給新的廣播網域。
* 無法從廣播網域中移除已指派生命量的連接埠。
* 由於叢集管理和節點管理生命期會指派給預設IPspace中的預設廣播網域、因此無法從預設廣播網域移除指派給這些生命期的連接埠。


.步驟
. 確定目前的連接埠指派。
+
「網路連接埠展示」

+
[listing]
----
Node   Port IPspace  Broadcast Domain Link   MTU  Admin/Oper
------ ---- -------  ---------------- ----- ----  ------------
node1
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
node2
       e0a  Cluster  Cluster          up    9000  auto/1000
       e0b  Cluster  Cluster          up    9000  auto/1000
       e0c  Default  Default          up    1500  auto/1000
       e0d  Default  Default          up    1500  auto/1000
       e0e  Default  Default          up    1500  auto/1000
       e0f  Default  Default          up    1500  auto/1000
       e0g  Default  Default          up    1500  auto/1000
----
+
在此範例中、命令的輸出會提供下列資訊：

+
** 每個節點上的連接埠「e0c」、「e0d」、「e0e」、「e0f」和「e0g」都會指派給預設的廣播網域。
** 這些連接埠可能可用於您要建立的IPspace廣播網域。


. 判斷預設廣播網域中的哪些連接埠已指派給LIF介面、因此無法移至新的廣播網域。
+
「網路介面展示」

+
[listing]
----
         Logical      Status     Network         Current   Current Is
Vserver  Interface    Admin/Oper Address/Mask    Node      Port    Home
-------  ----------   ---------- ------------   --------- -------  ----
Cluster
         node1_clus1  up/up       10.0.2.40/24   node1     e0a     true
         node1_clus2  up/up       10.0.2.41/24   node1     e0b     true
         node2_clus1  up/up       10.0.2.42/24   node2     e0a     true
         node2_clus2  up/up       10.0.2.43/24   node2     e0b     true

cluster1
         cluster_mgmt up/up       10.0.1.41/24   node1     e0c     true
         node1_mgmt   up/up       10.0.1.42/24   node1     e0c     true
         node2_mgmt   up/up       10.0.1.43/24   node2     e0c     true
----
+
在下列範例中、命令的輸出會提供下列資訊：

+
** 節點連接埠會指派給每個節點上的連接埠「e0c」、而叢集管理LIF的主節點則位於「node1」上的「e0c」。
** 每個節點上的連接埠「e0d」、「e0e」、「e0f」和「e0g」均未裝載lifs、可從預設廣播網域中移除、然後新增至新IPspace的新廣播網域。



