---
sidebar: sidebar 
permalink: networking/display_cluster_connections.html 
keywords: 'display, view, show, cluster, connections, active, client, listening, lif, protocol, service, display cluster connections, view all the active or listening connections in the cluster or a count of active connections on the node by client, lif, protocol, or service, display active connections by client (cluster administrators only), network connections active show-clients, display active connections by protocol (cluster administrators only), network connections active show-protocols, display active connections by service (cluster administrators only), network connections active show-services, display active connections by lif on a node and svm, network connections active show-lifs, display active connections in a cluster, network connections active show, display listening connections in a cluster, network connections listening show' 
summary: 依用戶端、LIF、傳輸協定或服務、檢視叢集中的所有作用中或聆聽連線、或節點上的作用中連線數 
---
= 顯示叢集連線
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
您可以依用戶端、邏輯介面、傳輸協定或服務、顯示叢集中的所有作用中連線、或節點上的作用中連線數。您也可以顯示叢集中的所有聆聽連線。



== 依用戶端顯示作用中連線（僅限叢集管理員）

您可以檢視用戶端的作用中連線、以驗證特定用戶端所使用的節點、並檢視每個節點的用戶端計數之間可能存在的不平衡。

.關於這項工作
用戶端的作用中連線數在下列案例中很有用：

* 尋找忙碌或過載的節點。
* 判斷特定用戶端存取磁碟區的速度緩慢的原因。
+
您可以檢視用戶端正在存取之節點的詳細資料、然後將其與磁碟區所在的節點進行比較。如果存取磁碟區需要周遊叢集網路、用戶端可能會因為遠端存取超額訂閱的遠端節點上的磁碟區而遇到效能降低的問題。

* 驗證是否所有節點都能用於資料存取。
* 尋找連線數量異常高的用戶端。
* 驗證特定用戶端是否有連線至節點。


.步驟
使用顯示節點上用戶端的作用中連線計數 `network connections active show-clients` 命令。

如需此命令的詳細資訊、請參閱手冊頁： http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令ONTAP"^]

....
network connections active show-clients
Node    Vserver Name    Client IP Address     Count
------  --------------  -----------------     ------
node0   vs0             192.0.2.253                1
        vs0             192.0.2.252                2
        Cluster         192.10.2.124               5
node1   vs0             192.0.2.250                1
        vs0             192.0.2.252                3
        Cluster         192.10.2.123               4
node2   vs1             customer.example.com       1
        vs1             192.0.2.245                3
        Cluster         192.10.2.122               4
node3   vs1             customer.example.org       1
        vs1             customer.example.net       3
        Cluster         192.10.2.121               4
....


== 依傳輸協定顯示作用中連線（僅限叢集管理員）

您可以依節點上的傳輸協定（TCP或udp）顯示作用中連線的計數、以比較叢集內的傳輸協定使用量。

.關於這項工作
依傳輸協定的作用中連線數在下列案例中很有用：

* 尋找正在失去連線的udp用戶端。
+
如果某個節點接近其連線限制、則會先捨棄UDP用戶端。

* 驗證是否未使用其他通訊協定。


.步驟
使用在節點上依通訊協定顯示作用中連線的計數 `network connections active show-protocols` 命令。

如需此命令的詳細資訊、請參閱手冊頁。

....
network connections active show-protocols
Node     Vserver Name  Protocol   Count
-------  ------------  ---------  ------
node0
         vs0           UDP            19
         Cluster       TCP            11
node1
         vs0           UDP            17
         Cluster       TCP             8
node2
         vs1           UDP            14
         Cluster       TCP            10
node3
         vs1           UDP            18
         Cluster       TCP             4
....


== 依服務顯示作用中連線（僅限叢集管理員）

您可以針對叢集中的每個節點、依服務類型（例如NFS、SMB、掛載等）顯示作用中連線的計數。這對於比較叢集內的服務使用量很有用、因為這有助於判斷節點的主要工作負載。

.關於這項工作
依服務列出的作用中連線數在下列案例中非常實用：

* 驗證所有節點是否用於適當的服務、以及該服務的負載平衡是否正常運作。
* 驗證是否未使用其他服務。使用顯示節點上依服務顯示作用中連線的計數 `network connections active show-services` 命令。


如需此命令的詳細資訊、請參閱手冊頁： http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令ONTAP"^]

....
network connections active show-services
Node       Vserver Name    Service    Count
---------  --------------  ---------  ------
node0
           vs0             mount           3
           vs0             nfs            14
           vs0             nlm_v4          4
           vs0             cifs_srv        3
           vs0             port_map       18
           vs0             rclopcp        27
           Cluster         ctlopcp        60
node1
           vs0             cifs_srv        3
           vs0             rclopcp        16
           Cluster         ctlopcp        60
node2
           vs1             rclopcp        13
           Cluster         ctlopcp        60
node3
           vs1             cifs_srv        1
           vs1             rclopcp        17
           Cluster         ctlopcp        60
....


== 在節點和SVM上顯示LIF的作用中連線

您可以依節點和儲存虛擬機器（SVM）顯示每個LIF的作用中連線數、以檢視叢集內LIF之間的連線不平衡。

.關於這項工作
LIF的作用中連線數在下列案例中很有用：

* 比較每個LIF上的連線數目、找出過載的LIF。
* 驗證DNS負載平衡是否適用於所有資料LIF。
* 比較不同SVM的連線數目、找出使用最多的SVM。


.步驟
使用顯示 SVM 和節點每個 LIF 的作用中連線計數 `network connections active show-lifs` 命令。

如需此命令的詳細資訊、請參閱手冊頁： http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令ONTAP"^]

....
network connections active show-lifs
Node      Vserver Name  Interface Name  Count
--------  ------------  --------------- ------
node0
          vs0           datalif1             3
          Cluster       node0_clus_1         6
          Cluster       node0_clus_2         5
node1
          vs0           datalif2             3
          Cluster       node1_clus_1         3
          Cluster       node1_clus_2         5
node2
          vs1           datalif2             1
          Cluster       node2_clus_1         5
          Cluster       node2_clus_2         3
node3
          vs1           datalif1             1
          Cluster       node3_clus_1         2
          Cluster       node3_clus_2         2
....


== 顯示叢集中的作用中連線

您可以顯示叢集中作用中連線的相關資訊、以檢視個別連線所使用的LIF、連接埠、遠端主機、服務、儲存虛擬機器（SVM）和傳輸協定。

.關於這項工作
在下列情況下、檢視叢集中的作用中連線十分有用：

* 驗證個別用戶端是否在正確的節點上使用正確的傳輸協定和服務。
* 如果用戶端無法使用特定的節點、傳輸協定和服務組合來存取資料、您可以使用此命令來尋找類似的用戶端來進行組態或封包追蹤比較。


.步驟
使用顯示叢集中的作用中連線 `network connections active show` 命令。

如需此命令的詳細資訊、請參閱手冊頁： http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令ONTAP"^]

下列命令顯示節點節點節點1上的作用中連線：

....
network connections active show -node node1
Vserver  Interface           Remote
Name     Name:Local Port     Host:Port           Protocol/Service
-------  ------------------  ------------------  ----------------
Node: node1
Cluster  node1_clus_1:50297  192.0.2.253:7700    TCP/ctlopcp
Cluster  node1_clus_1:13387  192.0.2.253:7700    TCP/ctlopcp
Cluster  node1_clus_1:8340   192.0.2.252:7700    TCP/ctlopcp
Cluster  node1_clus_1:42766  192.0.2.252:7700    TCP/ctlopcp
Cluster  node1_clus_1:36119  192.0.2.250:7700    TCP/ctlopcp
vs1      data1:111           host1.aa.com:10741  UDP/port-map
vs3      data2:111           host1.aa.com:10741  UDP/port-map
vs1      data1:111           host1.aa.com:12017  UDP/port-map
vs3      data2:111           host1.aa.com:12017  UDP/port-map
....
下列命令顯示SVM VS1上的作用中連線：

....
network connections active show -vserver vs1
Vserver  Interface           Remote
Name     Name:Local Port     Host:Port           Protocol/Service
-------  ------------------  ------------------  ----------------
Node: node1
vs1      data1:111           host1.aa.com:10741  UDP/port-map
vs1      data1:111           host1.aa.com:12017  UDP/port-map
....


== 顯示叢集中的接聽連線

您可以顯示叢集中偵聽連線的相關資訊、以檢視接受特定傳輸協定和服務連線的生命與連接埠。

.關於這項工作
檢視叢集中的聆聽連線在下列情況下非常有用：

* 如果與LIF的用戶端連線持續失敗、請確認所需的傳輸協定或服務正在聆聽LIF。
* 如果透過另一個節點上的LIF遠端資料存取某個節點上的磁碟區失敗、請驗證是否在每個叢集LIF上開啟UP/rclipcp接聽程式。
* 如果SnapMirror在同一叢集中的兩個節點之間傳輸失敗、請驗證是否在每個叢集LIF上開啟UP/rclipcp接聽程式。
* 如果SnapMirror在不同叢集的兩個節點之間傳輸失敗、請驗證是否在每個叢集間的LIF上開啟了TCP/IP接聽程式。


.步驟
使用顯示每個節點的聆聽連線 `network connections listening show` 命令。

....
network connections listening show
Vserver Name     Interface Name:Local Port        Protocol/Service
---------------- -------------------------------  ----------------
Node: node0
Cluster          node0_clus_1:7700                TCP/ctlopcp
vs1              data1:4049                       UDP/unknown
vs1              data1:111                        TCP/port-map
vs1              data1:111                        UDP/port-map
vs1              data1:4046                       TCP/sm
vs1              data1:4046                       UDP/sm
vs1              data1:4045                       TCP/nlm-v4
vs1              data1:4045                       UDP/nlm-v4
vs1              data1:2049                       TCP/nfs
vs1              data1:2049                       UDP/nfs
vs1              data1:635                        TCP/mount
vs1              data1:635                        UDP/mount
Cluster          node0_clus_2:7700                TCP/ctlopcp
....