---
sidebar: sidebar 
permalink: networking/ontap_internal_ports.html 
keywords: port, tcp, udp, ontap, internal, internally, ontap internal ports, port list, tcp ports, udp ports, port to establish intracluster lif communication, syslog, port 514, rpc, port 900, port 902, port 904, port 905, port 910, port 911, port 913, port 914, port 915, port 918, port 920, port 921, port 924, port 925, port 927, port 928, port 929, port 931, port 932, port 933, port 934, port 935, port 936, port 937, port 939, port 940, port 951, port 954, port 955, port 956, port 958, port 961, port 963, port 964, port 966, port 967, port 5125, alternate control port, port 5133, port 5144, node scope ssh, port 65502, port 65503, lif sharing, port 7810, port 7811, port 7812, port 7813, port 7814, port 7815, port 7816, port 7817, port 7818, port 7819, port 7820, port 7821, port 7822, port 7823, port 7824, port 8023, node scope telnet, node scope rsh, port 8514, kmip client port, port 9877 
summary: 由內部使用的TCP連接埠和udp連接埠ONTAP 
---
= 內部連接埠ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
下表列出ONTAP 了供內部使用的TCP連接埠和UDP連接埠。這些連接埠用於建立叢集內LIF通訊：

[cols="30,70"]
|===


| 連接埠/傳輸協定 | 說明 


| 514 | 系統記錄 


| 900 | NetApp叢集RPC 


| 902. | NetApp叢集RPC 


| 904 | NetApp叢集RPC 


| 905 | NetApp叢集RPC 


| 910 | NetApp叢集RPC 


| 911 | NetApp叢集RPC 


| 913 | NetApp叢集RPC 


| 914 | NetApp叢集RPC 


| 159.15 | NetApp叢集RPC 


| 918 | NetApp叢集RPC 


| 920 | NetApp叢集RPC 


| 921 | NetApp叢集RPC 


| 924 | NetApp叢集RPC 


| 925 | NetApp叢集RPC 


| 927 | NetApp叢集RPC 


| 928 | NetApp叢集RPC 


| 929 | NetApp叢集RPC 


| 931 | NetApp叢集RPC 


| 932 | NetApp叢集RPC 


| 933 | NetApp叢集RPC 


| 934 | NetApp叢集RPC 


| 935 | NetApp叢集RPC 


| 936 | NetApp叢集RPC 


| 937 | NetApp叢集RPC 


| 939 | NetApp叢集RPC 


| 940 | NetApp叢集RPC 


| 951. | NetApp叢集RPC 


| 954 | NetApp叢集RPC 


| 95 | NetApp叢集RPC 


| 956. | NetApp叢集RPC 


| 958 | NetApp叢集RPC 


| 961. | NetApp叢集RPC 


| 963, | NetApp叢集RPC 


| 964.. | NetApp叢集RPC 


| 9666 | NetApp叢集RPC 


| 967 | NetApp叢集RPC 


| 5125. | 磁碟的備用控制連接埠 


| 5133 | 磁碟的備用控制連接埠 


| 51444. | 磁碟的備用控制連接埠 


| 65502 | 節點範圍SSH 


| 65503 | LIF共用 


| 7810 | NetApp叢集RPC 


| 7811. | NetApp叢集RPC 


| 7812 | NetApp叢集RPC 


| 7813 | NetApp叢集RPC 


| 7814 | NetApp叢集RPC 


| 7815 | NetApp叢集RPC 


| 7816 | NetApp叢集RPC 


| 7817 | NetApp叢集RPC 


| 7818 | NetApp叢集RPC 


| 7819 | NetApp叢集RPC 


| 7820 | NetApp叢集RPC 


| 7821 | NetApp叢集RPC 


| 7822 | NetApp叢集RPC 


| 7823 | NetApp叢集RPC 


| 7824 | NetApp叢集RPC 


| 8023 | 節點範圍Telnet 


| 8514 | 節點範圍RSH 


| 9877 | KMIP用戶端連接埠（僅限內部本機主機） 
|===