---
sidebar: sidebar 
permalink: networking/recover_from_an_incorrectly_configured_cluster_lif.html 
keywords: misconfigured, misconfigurations, incorrect, incorrectly, switch, switches, switched, cable, physical, wiring, wired, reachability, port, cluster, ontap 9.8 and later, recover from an incorrectly configured cluster lif, how to identify and correct a cluster that has been misconfigured, cluster create, network port, reachability show -detail, reset the home port 
summary: 如何識別及修正設定錯誤的叢集 
---
= 恢復設定不正確的 ONTAP LIF
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
叢集網路連線至交換器時、無法建立叢集、但叢集IPspace中設定的所有連接埠、都無法連線至叢集IPspace中設定的其他連接埠。

.關於這項工作
在交換式叢集中、如果叢集網路介面（ LIF ）設定在錯誤的連接埠上、或是叢集連接埠連接到錯誤的網路、則為 `cluster create` 命令可能會失敗、並出現下列錯誤：

....
Not all local cluster ports have reachability to one another.
Use the "network port reachability show -detail" command for more details.
....
如link:https://docs.netapp.com/us-en/ontap-cli/cluster-create.html["指令參考資料ONTAP"^]需詳細 `cluster create`資訊，請參閱。

的結果 `network port show` 命令可能會顯示數個連接埠已新增至叢集 IPspace 、因為這些連接埠已連線至已設定叢集 LIF 的連接埠。不過、的結果 `network port` `reachability show -detail` 命令會顯示哪些連接埠無法彼此連線。

如link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["指令參考資料ONTAP"^]需詳細 `network port show`資訊，請參閱。

若要從連接埠上設定的叢集LIF還原、而該連接埠無法連線至使用叢集lifs設定的其他連接埠、請執行下列步驟：

.步驟
. 將叢集LIF的主連接埠重設為正確的連接埠：
+
....
network port modify -home-port
....
+
如link:https://docs.netapp.com/us-en/ontap-cli/network-port-modify.html["指令參考資料ONTAP"^]需詳細 `network port modify`資訊，請參閱。

. 從叢集廣播網域中移除未設定叢集lifs的連接埠：
+
....
network port broadcast-domain remove-ports
....
. 建立叢集：
+
....
cluster create
....


.結果
當您完成叢集建立時、系統會偵測到正確的組態、並將連接埠放入正確的廣播網域。
