---
sidebar: sidebar 
permalink: networking/use_lldp_to_detect_network_connectivity.html 
keywords: display, view, show, network, connectivity, neighbor, discovery, protocol, ndp, link, layer, lldp, use lldp to detect network connectivity, enable or disable lldp, view lldp neighbor information, adjust the interval for transmitting lldp advertisements 
summary: 使用LLDP偵測網路連線能力包括審查部署考量、在所有連接埠上啟用、檢視鄰近裝置、以及視需要調整LLDP組態值。 
---
= 使用 LLDP 來偵測網路連線
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
使用LLDP偵測網路連線能力包括審查部署考量、在所有連接埠上啟用、檢視鄰近裝置、以及視需要調整LLDP組態值。

在顯示鄰近裝置的相關資訊之前、也必須在任何交換器和路由器上啟用LLDP。

目前可報告下列類型長度值結構（TLV）ONTAP ：

* 機箱ID
* 連接埠ID
* 存留時間（TTL）
* 系統名稱
+
系統名稱TLV不會傳送至CNA裝置。



某些整合式網路介面卡（CNA）、例如X1143介面卡和UTA2內建連接埠、包含LLDP的卸載支援：

* LLDP卸載用於資料中心橋接（DCB）。
* 叢集與交換器之間顯示的資訊可能有所不同。
+
交換器所顯示的機箱ID和連接埠ID資料、可能與CNA和非CNA連接埠不同。



例如：

* 對於非CNA連接埠：
+
** 機箱ID是節點上其中一個連接埠的固定MAC位址
** 連接埠ID是節點上個別連接埠的連接埠名稱


* 對於CNA連接埠：
+
** 機箱ID和連接埠ID是節點上個別連接埠的MAC位址。




不過、叢集所顯示的資料對於這些連接埠類型而言是一致的。


NOTE: LLDP規格定義透過SNMP mib存取所收集的資訊。不過ONTAP 、目前不支援LLDP MIB.



== 啟用或停用 LLDP

若要探索及傳送通告給符合LLDP的鄰近裝置、必須在叢集的每個節點上啟用LLDP。從ONTAP 推出支援支援支援的支援方案開始、在節點的所有連接埠上預設都會啟用LLDP。

.關於這項工作
對於 ONTAP 9.10.1 及更早版本、 `lldp.enable` 選項可控制是否在節點的連接埠上啟用或停用 LLDP ：

* `on` 在所有連接埠上啟用 LLDP 。
* `off` 停用所有連接埠上的 LLDP 。


對於 ONTAP 9.11.1 及更新版本、 `lldp.enable` 選項可控制在節點的非叢集和非儲存連接埠上啟用或停用 LLDP ：

* `on` 在所有非叢集和非儲存連接埠上啟用 LLDP 。
* `off` 在所有非叢集和非儲存連接埠上停用 LLDP 。


.步驟
. 顯示節點或叢集中所有節點的目前 LLDP 設定：
+
** 單一節點： `run -node node_name options lldp.enable`
** 所有節點：選項 `lldp.enable`


. 在節點的所有連接埠或叢集中所有節點的所有連接埠上啟用或停用 LLDP ：
+
[cols="30,70"]
|===


| 若要在 ... 上啟用或停用 LLDP | 輸入... 


 a| 
節點
 a| 
`run -node node_name options lldp.enable {on|off}`



 a| 
叢集中的所有節點
 a| 
`options lldp.enable {on|off}`

|===
+
** 單一節點：
+
....
run -node node_name options lldp.enable {on|off}
....
** 所有節點：
+
....
options lldp.enable {on|off}
....






== 檢視 LLDP 鄰近區域資訊

只要連接埠連接至符合LLDP標準的裝置、即可檢視連接至叢集節點每個連接埠的鄰近裝置相關資訊。您可以使用network device-dinDiscovery show命令來檢視鄰近資訊。

.步驟
. 顯示所有與LLDP相容裝置連線至叢集中節點上之連接埠的相關資訊：
+
....
network device-discovery show -node node -protocol lldp
....
+
下列命令顯示連接至節點叢集-1_01上連接埠的鄰近節點。輸出會列出連線至指定節點每個連接埠的啟用LLDP的裝置。如果是 `-protocol` 省略選項、輸出也會列出啟用 CDP 的裝置。

+
....
network device-discovery show -node cluster-1_01 -protocol lldp
Node/       Local  Discovered
Protocol    Port   Device                    Interface         Platform
----------- ------ ------------------------- ----------------  ----------------
cluster-1_01/lldp
            e2a    0013.c31e.5c60            GigabitEthernet1/36
            e2b    0013.c31e.5c60            GigabitEthernet1/35
            e2c    0013.c31e.5c60            GigabitEthernet1/34
            e2d    0013.c31e.5c60            GigabitEthernet1/33
....




== 調整傳輸LLDP廣告的時間間隔

LLDP廣告會定期傳送給LLDP鄰近裝置。您可以根據網路流量和網路拓撲的變更、增加或減少傳送 LLDP 通告的時間間隔。

.關於這項工作
IEEE建議的預設時間間隔為30秒、但您可以輸入5秒到300秒之間的值。

.步驟
. 顯示節點或叢集中所有節點目前的LLDP通告時間間隔：
+
** 單一節點：
+
....
run -node <node_name> options lldp.xmit.interval
....
** 所有節點：
+
....
options lldp.xmit.interval
....


. 調整為節點的所有連接埠或叢集中所有節點的所有連接埠傳送LLDP通告的時間間隔：
+
** 單一節點：
+
....
run -node <node_name> options lldp.xmit.interval <interval>
....
** 所有節點：
+
....
options lldp.xmit.interval <interval>
....






== 調整LLDP廣告的即時時間值

存留時間（TTL）是LLDP廣告儲存在鄰近的LLDP相容裝置快取中的一段時間。TTL會在每個LLDP封包中通告、並在節點收到LLDP封包時進行更新。TTL可在傳出的LLDP框架中修改。

.關於這項工作
* TTL 是計算值、即傳輸間隔的乘積 (`lldp.xmit.interval`）和保留倍數 (`lldp.xmit.hold`）再加上一項。
* 預設的保留倍數值為4、但您可以輸入1到100之間的值。
* 因此、根據IEEE的建議、預設TTL為121秒、但調整傳輸時間間隔並保留倍頻值、即可指定傳出訊框的值、從6秒到30001秒。
* 如果在TTL過期之前移除IP位址、則會快取LLDP資訊、直到TTL過期為止。


.步驟
. 顯示節點或叢集中所有節點的目前保留倍數值：
+
** 單一節點：
+
....
run -node <node_name> options lldp.xmit.hold
....
** 所有節點：
+
....
options lldp.xmit.hold
....


. 調整節點的所有連接埠或叢集中所有節點的所有連接埠上的保留倍頻值：
+
** 單一節點：
+
....
run -node <node_name> options lldp.xmit.hold <hold_value>
....
** 所有節點：
+
....
options lldp.xmit.hold <hold_value>
....






== 檢視或清除 LLDP 統計資料

您可以檢視每個節點上叢集和非叢集連接埠的 LLDP 統計資料、以偵測潛在的網路連線問題。LLDP 統計資料是從上次清除時開始累積的。

.關於這項工作
對於版本9.10.1及更早版本、由於LLDP一律啟用叢集連接埠、因此會針對這些連接埠上的流量顯示LLDP統計資料。ONTAP必須在非叢集連接埠上啟用 LLDP 、這些連接埠的統計資料才會顯示出來。

對於版本僅9.11.1及更新版本、因為LLDP一律啟用叢集與儲存連接埠、因此會針對這些連接埠上的流量顯示LLDP統計資料。ONTAP必須在非叢集和非儲存連接埠上啟用LLDP、才能顯示這些連接埠的統計資料。

.步驟
顯示或清除節點上所有連接埠的目前 LLDP 統計資料：

[cols="40,60"]
|===


| 如果您想要... | 輸入... 


 a| 
檢視 LLDP 統計資料
 a| 
`run -node node_name lldp stats`



 a| 
清除 LLDP 統計資料
 a| 
`run -node node_name lldp stats -z`

|===


=== 顯示及清除統計資料範例

下列命令會在 LLDP 統計資料被清除之前顯示這些統計資料。輸出會顯示自上次清除統計資料以來、已傳送和接收的封包總數。

....
cluster-1::> run -node vsim1 lldp stats

RECEIVE
 Total frames:     190k  | Accepted frames:   190k | Total drops:         0
TRANSMIT
 Total frames:     5195  | Total failures:      0
OTHER
 Stored entries:      64
....
下列命令會清除LLDP統計資料。

....
cluster-1::> The following command clears the LLDP statistics:
run -node vsim1 lldp stats -z
run -node node1 lldp stats

RECEIVE
 Total frames:        0  | Accepted frames:     0  | Total drops:         0
TRANSMIT
 Total frames:        0  | Total failures:      0
OTHER
 Stored entries:      64
....
清除統計資料後、會在傳送或接收下一個LLDP廣告之後開始累積。
