---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload, aff a1k, aff a90, aff a70, fas90, fas70, aff a50, aff a30 
summary: 某些 AFF 和 FAS 系統支援專用卸載處理器儲存效率。這些系統不使用溫度敏感型儲存效率。壓縮無需等待資料冷卻即可開始，並由專用卸載處理器執行。 
---
= 了解ONTAP專用卸載處理器的儲存效率
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
專用卸載處理器儲存效率對鄰近的實體區塊進行連續的打包，並使用專用卸載處理器進行 32k 資料壓縮。與使用 8k 具調適能力的壓縮的系統（後者在 Volume 層級實現空間節約效益）不同，32k 壓縮在彙總層級實現空間節約效益。使用專用卸載處理器儲存效率的系統不使用溫度敏感儲存效率 （TSSE），這意味著壓縮不基於熱資料或冷資料。這可立即實現空間節約效益，且不會產生任何效能影響。

以下系統支援專用卸載處理器儲存效率。在所列的 AFF 系統中，此功能預設為啟用。


NOTE: AFF A20 平台不支援專用卸載處理器儲存效率。對於 AFF A20 系統，使用 SnapMirror 技術遷移的資料會由主 CPU 自動轉換為 32k 即時壓縮。

* AFF A 系列系統：AFF A90、AFF A70、AFF A50、AFF A30
* AFF A1K
* AFF C 系列系統：AFF C80、AFF C60、AFF C30
* FAS 系統：FAS90、FAS70、FAS50


對於以下系統，儲存效率將自動啟用，無需任何組態。這適用於所有新建的精簡配置 Volume 和現有資料，包括從其他系統移動的 Volume。無論空間保證設定為何，重複資料刪除功能都會啟用。壓縮和資料精簡均要求將空間保證設為「無」。使用 Volume 移動或 SnapMirror 技術遷移的資料將自動轉換為 32k 即時壓縮。

* AFF A 系列系統：AFF A90、AFF A70、AFF A50、AFF A30
* AFF A1K
* AFF C 系列系統：AFF C80、AFF C60、AFF C30


對於下列系統，預設情況下，僅對升級至 ONTAP 9.15.1 或更新版本之前已啟用儲存效率的現有精簡配置 Volume 啟用儲存效率。您可以使用 ONTAP CLI 或 ONTAP REST API 方法對新建立的 Volume 啟用儲存效率。使用 Volume 移動或 SnapMirror 技術遷移的資料，僅當原始平台啟用了壓縮時，才會轉換為 32k 即時壓縮。

* FAS90
* FAS70
* FAS50


有關將控制器升級至其中一個受支援系統的相關資訊，請參閱 https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["ONTAP 硬體升級文件"^]。
