---
permalink: concepts/builtin-storage-efficiency-concept.html 
sidebar: sidebar 
keywords: storage efficiency, built-in, platform, controller, offload, aff a1k, aff a90, aff a70, fas90, fas70, aff a50, aff a30 
summary: 某些AFF和FAS平台預設啟用專用卸載處理器儲存效率。這些平台不使用對溫度敏感的儲存效率。壓縮無需等待資料冷卻即可開始，並使用專用的卸載處理器執行。 
---
= 了解ONTAP專用卸載處理器的儲存效率
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
專用卸載處理器儲存效率執行連續實體區塊的順序打包，並使用專用卸載處理器進行 32k 資料壓縮。使用 32k 壓縮可以在聚合層級實現空間節省，這與使用 8k 自適應壓縮的平台不同，後者在磁碟區層級實現空間節省。使用專用卸載處理器儲存效率的平台不使用溫度敏感儲存效率 (TSSE)，這意味著壓縮不是基於熱資料或冷資料。這樣可以立即節省空間，而不會對性能產生任何影響。

以下平台和ONTAP版本預設啟用專用卸載處理器儲存效率。


NOTE: AFF A20 平台不支援專用卸載處理器的儲存效率。對於AFF A20 平台，使用SnapMirror技術遷移的資料會使用主 CPU 自動轉換為 32k 內聯壓縮。

[cols="2"]
|===
| 平台 | 版本ONTAP 


 a| 
* AFF A1K
* AFF A90
* AFF A70
* FAS90
* FAS70

| 9.15.1 或更新版本 


 a| 
* AFF C80
* AFF C60
* AFF C30
* AFF A50
* AFF A30

| 9.16.1 或更新版本 
|===
對於以下平台，儲存效率會自動啟用，無需配置。這適用於所有新建立的精簡配置磁碟區和現有數據，包括從其他平台移動的磁碟區。無論空間保證設定如何，都會啟用重複資料刪除。壓縮和資料壓縮都要求將空間保證設為無。使用磁碟區移動或SnapMirror技術遷移的資料會自動轉換為 32k 內聯壓縮。

* AFF C80
* AFF C60
* AFF C30
* AFF A1K
* AFF A90
* AFF A70
* AFF A50
* AFF A30


對於下列平台，預設僅在升級至ONTAP 9.15.1 或更高版本之前已啟用儲存效率的現有精簡配置磁碟區上啟用儲存效率。您可以使用 CLI 或 REST API 方法在新建立的磁碟區上啟用儲存效率。只有在原始平台上啟用了壓縮時，使用磁碟區移動或SnapMirror技術遷移的資料才會轉換為 32k 內聯壓縮。

* FAS90
* FAS70


有關將控制器升級到受支援平台之一的信息，請參閱 https://docs.netapp.com/us-en/ontap-systems-upgrade/choose_controller_upgrade_procedure.html["ONTAP 硬體升級文件"^]。
