---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-console-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, netapp console, console, hybrid, cloud, dashboard, multicloud 
summary: 您可以使用NetApp控制台中的系統管理員管理ONTAP 9.10.1 及更高版本。透過這種集成，您可以使用統一的控制平面有效地監督混合多雲基礎設施，同時保留熟悉的系統管理器使用者介面。 
---
= 將ONTAP系統管理器與NetApp控制台集成
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用NetApp控制台中的系統管理員管理ONTAP 9.10.1 及更高版本。透過這種集成，您可以使用統一的控制平面有效地監督混合多雲基礎設施，同時保留熟悉的系統管理器使用者介面。

透過控制台，您可以建立和管理雲端儲存（例如， Cloud Volumes ONTAP）、使用NetApp資料服務（例如，Cloud Backup）以及控制許多內部部署和邊緣儲存設備。

控制台提供了兩種發現和管理叢集的方法：

* 透過系統管理器直接發現並進行管理（ONTAP 9.12.1 及更高版本）
* 透過控制台代理發現。


控制台代理程式是安裝在您的環境中的軟體。這使您可以透過系統管理器存取管理功能，並存取提供資料複製、備份和復原、資料分類、資料分層等功能的NetApp雲端服務。

詳細了解link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/index.html["使用NetApp控制台進行本機ONTAP叢集管理"^] 。

.步驟
. 登入NetApp控制台。
+
.. 如果您有控制台登錄，請使用它。
.. 如果這是您第一次，請選擇使用您的NetApp支援網站憑證登錄，然後在控制台登入頁面上輸入您的憑證。


. 使用控制台代理程式或直接發現在控制台中發現您的本機叢集。了解更多有關連結的資訊： https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html [發現本地ONTAP集群^]。
+
.. 了解如何link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-direct.html["管理直接發現的集群"^] 。
.. 了解如何link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-connector.html["管理使用控制台代理發現的集群"^] 。


. 使用系統管理員管理您的內部部署叢集。在我的工作環境系統頁面上，選擇集群，然後按一下服務清單中的系統管理員。
+
.. 詳細了解link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-direct.html["管理直接發現的集群"^] 。
.. 了解如何link:https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-manage-ontap-connector.html["管理使用控制台代理發現的集群"^] 。






== NetApp控制台和ONTAP 9.12.1

注意：如果您使用的是ONTAP 9.12.1，則會出現一則訊息提示您試用NetApp控制台。

+ 如果叢集已連線至NetApp控制台，則會顯示登入提示。

. 按一下「繼續到NetApp控制台」**** 以依照連結進入控制台。
+

NOTE: 如果您的系統設定阻止了外部網絡，您將無法存取控制台。若要使用控制台存取系統管理員，您必須確保您的系統可以存取位址「cloudmanager.cloud.netapp.com」。否則，在提示字元下，您可以選擇使用隨ONTAP系統一起安裝的系統管理員版本。

. 在控制台登入頁面上，選擇*使用您的NetApp支援網站憑證登入*並輸入您的憑證。
+
如果您已經使用過控制台並使用電子郵件和密碼登錄，那麼您需要繼續使用該登入選項。

+
https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["了解有關登入NetApp控制台的更多信息"^] 。

. 如果出現提示，請輸入新的NetApp控制台帳號的名稱。
+
大多數情況下，控制台會根據您的叢集資料自動為您建立帳戶。

. 輸入叢集的叢集管理員認證。


.結果
系統管理器顯示，您現在可以從控制台管理叢集。



== 了解有關NetApp控制台的更多信息

* https://docs.netapp.com/us-en/console-setup-admin/concept-overview.html["NetApp控制台概述"^]
* https://docs.netapp.com/us-en/storage-management-ontap-onprem/index.html["透過NetApp控制台管理您的NetApp AFF和FAS系統"^]

