---
sidebar: sidebar 
permalink: concepts/sysmgr-integration-bluexp-concept.html 
keywords: netapp, ontap, system manager, experience, integrate, integration, bluexp, hybrid, cloud, dashboard, multicloud 
summary: 您可以使用 BlueXP 中的 System Manager 管理 ONTAP 9.10.1 及更高版本。這種整合讓您可以使用統一的控制平面來有效地監管混合多雲基礎架構，同時保留熟悉的 System Manager 使用者介面。 
---
= 將 ONTAP 系統管理器與 BlueXP 集成
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
您可以使用 BlueXP 中的 System Manager 管理 ONTAP 9.10.1 及更高版本。這種整合讓您可以使用統一的控制平面來有效地監管混合多雲基礎架構，同時保留熟悉的 System Manager 使用者介面。

BlueXP 可讓您建立和管理雲端儲存（例如，Cloud Volumes ONTAP）、使用 NetApp 資料服務（例如，Cloud Backup）以及控制許多內部部署和邊緣儲存裝置。

BlueXP提供兩種探索和管理叢集的方法：

* 透過系統管理器直接發現並進行管理（ONTAP 9.12.1 及更高版本）
* 透過連接器探索


連接器是安裝在您環境中的軟體。它允許您透過系統管理員存取管理功能，並存取提供資料複製、備份和復原、資料分類、資料分層等功能的 BlueXP 雲端服務。

深入瞭解 link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["使用 BlueXP 進行內部部署 ONTAP 叢集管理"^]。

.步驟
. 登入 BlueXP。
+
.. 如果您有 BlueXP 登入名，請使用它。
.. 如果這是您第一次，請選擇使用您的 NetApp 支援網站憑證登錄，然後在 BlueXP 登入頁面上輸入您的憑證。


. 使用連接器或直接發現功能在 BlueXP 中發現您的本機叢集。了解更多信息，請訪問：https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-discovering-ontap.html[發現本地 ONTAP 集群^]。
+
.. 瞭解如何link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["管理直接發現的集群"^]。
.. 瞭解如何link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["管理使用連接器發現的集群"^]。


. 使用系統管理員管理您的本機叢集。在「我的工作環境」畫布上，選擇集群，然後在「服務」清單中點擊「系統管理員」。
+
.. 深入瞭解 link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-direct.html["管理直接發現的集群"^]。
.. 瞭解如何link:https://docs.netapp.com/us-en/bluexp-ontap-onprem/task-manage-ontap-connector.html["管理使用連接器發現的集群"^]。






== BlueXP 和 ONTAP 9.12.1

注意：如果您使用的是 ONTAP 9.12.1，則會出現一則訊息提示您試用 BlueXP。

+ 如果叢集已連線至 BlueXP，則會顯示登入提示。

. 按一下*繼續至藍圖XP*以追蹤至藍圖XP的連結。
+

NOTE: 如果您的系統設定已封鎖外部網路、您將無法存取 BlueXP 。  若要使用 BlueXP 存取 System Manager 、您必須確定系統可以存取位址「 cloudmanager.cloud.netapp.com`" 」。  否則、您可以在提示時選擇使用 ONTAP 系統隨附的系統管理員版本。

. 在BlueXP登入頁面上、選取* NetApp 支援網站 使用您的支援中心認證登入*、然後輸入您的認證資料。
+
如果您已經使用過 BlueXP 並使用電子郵件和密碼登錄，那麼您需要繼續使用該登入選項。

+
https://docs.netapp.com/us-en/cloud-manager-setup-admin/task-logging-in.html["深入瞭解如何登入BlueXP"^]。

. 如果出現提示，請輸入新 BlueXP 帳號的名稱。
+
在大多數情況下、BlueXP會根據叢集的資料自動為您建立帳戶。

. 輸入叢集的叢集管理員認證。


.結果
System Manager隨即顯示、您現在可以從BlueXP管理叢集。



== 深入瞭解BlueXP

* https://docs.netapp.com/us-en/bluexp-setup-admin/concept-overview.html["藍圖XP總覽"^]
* https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/index.html["透過BlueXP管理您的NetApp AFF 產品和FAS 功能"^]

