---
permalink: nfs-rdma/configure-nics-task.html 
sidebar: sidebar 
keywords: networking, NICs, NFS over RDMA, NVIDIA, NFS, system manager, ports, ethernet ports 
summary: 本文說明用戶端系統和儲存平台組態程序，以及 NIC 在 ONTAP 中使用 NFS over RDMA 的需求。 
---
= 透過RDMA設定NFS的NIC
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS over RDMA需要用戶端系統和儲存平台的NIC組態。



== 儲存平台組態

有關目標 RNIC 支持的信息，請參閱 https://hwu.netapp.com/["NetApp Hardware Universe"^]。

如果您使用高可用度（ HA ）組態，兩個節點都必須使用相同的 RNIC 來支援 RDMA 容錯移轉。NIC 必須具備 ROCE 功能。

* 從 ONTAP 9.10.1 開始、您可以使用命令檢視 RDMA 卸載通訊協定清單：
+
[source, cli]
----
network port show -rdma-protocols roce
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["指令參考資料ONTAP"^]需詳細 `network port show`資訊，請參閱。

* 從 ONTAP 9.16.1 開始，建議使用優先流量控制（ PFC ）。使用命令設定 PFC `network port modify` ：
+
[source, cli]
----
network port modify -node <nodename> -port <portname> -flowcontrol-admin pfc -pfc-queues-admin 3
----
* 在 ONTAP 9.16.1 之前，建議您使用預設的全域流程控制（ GFC ）。如果流程控制設定已變更，請使用命令來設定 GFC `network port modify` ：
+
[source, cli]
----
network port modify -node <nodename> -port <portname> -flowcontrol-admin full
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/network-port-modify.html["指令參考資料ONTAP"^]需詳細 `network port modify`資訊，請參閱。





== 用戶端系統組態

如需有關支援的 Client 作業系統 for NFS over RDMA 的資訊，請參閱 https://imt.netapp.com/matrix/["NetApp互通性對照表IMT （僅限部分）"^]。如需 Roce v2 支援的 RNIC ，請參閱各自的 RNIC 廠商文件。

雖然用戶端和伺服器可以直接連線，但建議使用交換器來改善容錯移轉效能。

必須使用巨型框架來設定用戶端，伺服器，任何交換器和交換器上的所有連接埠。用戶端和交換器上的流程控制組態應符合 ONTAP 的流程控制組態。從 ONTAP 9.16.1 開始，最佳做法是在 ONTAP ，交換器和用戶端上啟用和設定優先順序流程控制。在 ONTAP 9.16.1 之前，建議使用全域流程控制。

確認此組態之後，您可以使用 RDMA 掛載 NFS 匯出。

[role="tabbed-block"]
====
.系統管理員
--
您必須使用ONTAP S廳9.12.1或更新版本、才能使用System Manager透過RDMA設定網路介面與NFS。

.步驟
. 檢查是否支援RDMA。瀏覽至*「網路」>「乙太網路連接埠」*、然後在群組檢視中選取適當的節點。展開節點時、請查看指定連接埠的 * RDMA 傳輸協定 * 欄位：值 * roce* 表示支援 RDMA ；破折號（ * - * ）表示不支援。
. 若要新增VLAN、請選取*+ VLAN*。選取適當的節點。在 *Port* 下拉式功能表中、如果可用連接埠支援 RDMA 、則會顯示文字 * roce Enabled* 。如果不支援 RDMA 、則不會顯示任何文字。
. 遵循中的工作流程 xref:../task_nas_enable_linux_nfs.html[使用NFS為Linux伺服器啟用NAS儲存設備] 設定新的NFS伺服器。
+
新增網路介面時、您可以選擇*使用roce連接埠*。對於任何想要透過RDMA使用NFS的網路介面、請選取此選項。



--
.CLI
--
. 使用下列命令檢查NFS伺服器上是否已啟用RDMA存取：
+
`vserver nfs show-vserver <SVM_name>`

+
根據預設、 `-rdma` 應啟用。如果不是、請在NFS伺服器上啟用RDMA存取：

+
`vserver nfs modify -vserver <SVM_name> -rdma enabled`

. 透過NFSv4.0透過RDMA掛載用戶端：
+
.. proto參數的輸入取決於伺服器IP傳輸協定版本。如果是IPV4、請使用 `proto=rdma`。如果是IPv6、請使用 `proto=rdma6`。
.. 將NFS目標連接埠指定為 `port=20049` 而非標準連接埠2049：
+
`mount -o vers=4,minorversion=0,proto=rdma,port=20049 <Server_IP_address>:/<volume_path> <mount_point>`



. * 選用 * ：如果您需要卸載用戶端，請執行命令 `unmount <mount_path>`


--
====
.更多資訊
* xref:../nfs-config/create-server-task.html[建立NFS伺服器]
* xref:../task_nas_enable_linux_nfs.html[使用NFS為Linux伺服器啟用NAS儲存設備]

