---
permalink: nfs-rdma/index.html 
sidebar: sidebar 
keywords: NFS over RDMA, GPU, NVIDIA GDX 
summary: NFS over RDMA採用RDMA介面卡、可在儲存系統記憶體與主機系統記憶體之間直接複製資料、避免CPU中斷與負荷。 
---
= NFS over RDMA
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
NFS over RDMA採用RDMA介面卡、可在儲存系統記憶體與主機系統記憶體之間直接複製資料、避免CPU中斷與負荷。

NFS over RDMA組態是專為具有延遲敏感或高頻寬工作負載（例如機器學習和分析）的客戶所設計。NVIDIA已透過RDMA延伸NFS、以啟用GPU Direct Storage（GDS）。GDS會繞過CPU和主記憶體、使用RDMA直接在儲存系統和GPU記憶體之間傳輸資料、進一步加速啟用GPU的工作負載。

支援從ONTAP S209.10.1開始的NFS over RDMA。NFSv4.0傳輸協定僅支援NFS over RDMA組態、搭配Mellanox CX-5或CX-6介面卡使用時、此介面卡使用RoCE傳輸協定第2版支援RDMA。GDS僅支援使用NVIDIA Tesla和Ampere-Family GPU搭配Mellanox NIC卡和MOFED軟體。NFS over RDMA支援僅限於節點本機流量。支援所有成員位於同一個節點的標準FlexVols或FlexGroups、且必須從同一個節點上的LIF存取。NFS掛載大小超過64k、導致NFS在RDMA組態上的效能不穩定。

.需求
* 儲存系統必須執行ONTAP 的是版本不含更新版本的版本
+
** 您可以使用System Manager從ONTAP 版本S59.12.1開始、透過RDMA設定NFS。在《S209.10.1》和《9.11.1》中ONTAP 、您需要使用CLI透過RDMA來設定NFS。


* HA配對中的兩個節點都必須是相同版本。
* 儲存系統控制器必須支援RDMA（目前為A400、A700和A800）。
* 儲存應用裝置已設定RDMA支援的硬體（例如 Mellanox CX-5或CX-6）。
* 資料生命期必須設定為支援RDMA。
* 用戶端必須使用支援Mellanox RDMA的NIC卡和Mellanox OFED（MOFED）網路軟體。



NOTE: 透過RDMA的NFS不支援介面群組。

.下一步
* xref:./configure-nics-task.adoc[透過RDMA設定NFS的NIC]
* xref:./configure-lifs-task.adoc[透過RDMA設定NFS的LIF]
* xref:./configure-nfs-task.adoc[NFS over RDMA的NFS設定]


.相關資訊
* link:../concepts/rdma-concept.html["RDMA"]
* xref:../nfs-trunking/index.html[NFS 主幹總覽]
* link:https://datatracker.ietf.org/doc/html/rfc7530["RFC 7530：NFS版本4傳輸協定"]
* link:https://datatracker.ietf.org/doc/html/rfc8166["RFC 8166：遠端程序呼叫版本1的遠端直接記憶體存取傳輸"]
* link:https://datatracker.ietf.org/doc/html/rfc8167["RFC 8167：雙向遠端程序呼叫RFC-over RDMA傳輸"]
* link:https://datatracker.ietf.org/doc/html/rfc8267["RFC 8267：NFS上層繫結至RPC-over RDMA版本1"]

