---
permalink: error-messages/configure-ems-events-notifications-syslog-task.html 
sidebar: sidebar 
keywords: configuring, important, ems, events, forward, notifications, syslog, server 
summary: 若要在syslog伺服器上記錄最嚴重事件的通知、您必須將EMS設定為轉送重要活動訊號的事件通知。 
---
= 設定重要的EMS事件、將通知轉送到syslog伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要在syslog伺服器上記錄最嚴重事件的通知、您必須將EMS設定為轉送重要活動訊號的事件通知。

.開始之前
必須在叢集上設定DNS、才能解析syslog伺服器名稱。

.關於這項工作
如果您的環境尚未包含用於事件通知的syslog伺服器、您必須先建立一個。如果您的環境中已包含用於記錄其他系統事件的syslog伺服器、您可能會想要使用該伺服器來處理重要的事件通知。

您可以在ONTAP 叢集執行時、在CLI輸入命令來執行此工作。

從S廳9.12.1開始ONTAP 、可透過傳輸層安全（TLS）傳輸協定、將EMS事件傳送至遠端syslog伺服器上的指定連接埠。有兩個新參數可供使用：

`tcp-encrypted`:: 何時 `tcp-encrypted` 為指定 `syslog-transport`、ONTAP 驗證目的地主機的憑證來驗證其身分。預設值為 `udp-unencrypted`。
`syslog-port`:: 預設值 `syslog-port` 參數取決於的設定 `syslog-transport` 參數。如果 `syslog-transport` 設為 `tcp-encrypted`、 `syslog-port` 預設值為6514。


.步驟
. 建立重要事件的syslog伺服器目的地：
+
`event notification destination create -name _syslog-ems_ -syslog _syslog-server-address_ -syslog-transport {udp-unencrypted|tcp-unencrypted|tcp-encrypted}`

+
從ONTAP 功能變數9.12.1開始、可以指定下列值 `syslog-transport`：

+
** `udp-unencrypted` 無安全性的使用者資料包傳輸協定
** `tcp-unencrypted` 無安全性的傳輸控制傳輸協定
** `tcp-encrypted` -傳輸層安全性（TLS）的傳輸控制傳輸協定


+
預設傳輸協定為 `udp-unencrypted`。

. 設定重要事件以將通知轉送到syslog伺服器：
+
`event notification create -filter-name _important-events_ -destinations _syslog-ems_`



如link:https://docs.netapp.com/us-en/ontap-cli/event-notification-destination-create.html["指令參考資料ONTAP"^]需詳細 `event notification destination create`資訊，請參閱。
