---
permalink: error-messages/configure-webhooks-event-notifications-task.html 
sidebar: sidebar 
keywords: configure, important, ems, events, receive, email, notifications, forward, rest, api, webhook 
summary: 若要在REST API伺服器上接收事件通知、您必須設定REST API Webhook支援。 
---
= 設定重要的EMS事件、將通知轉送至REST API伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要在REST API伺服器上接收事件通知、您必須設定REST API Webhook支援。

.開始之前
* 您需要支援REST API/Webhook的伺服器、才能接收EMS事件。
* REST API伺服器可以使用伺服器端或用戶端的安全性憑證。
* 憑證的組態由目的地決定。請參閱下列內容、以瞭解根據目的地的憑證組態總覽：
+
** * http *：-不含憑證
** * https *：-伺服器憑證已由ONTAP 整個系統驗證。或者、也可以設定用戶端憑證、由ONTAP 作業系統傳送、讓伺服器進行驗證。


* 用戶端憑證需要在來源ONTAP 版系統上安裝可用的私密金鑰和憑證。



NOTE: 如果您同時設定用戶端和伺服器憑證REST API轉送、則需要伺服器端憑證才能使用用戶端憑證。因此、您必須遵循用戶端指示、才能使用這兩種驗證方法。



== 設定HTTP REST API轉送

您可以在ONTAP 叢集執行時、在指令行輸入命令來執行此工作。

.步驟
. 為篩選器「重要事件（Importation-events）：
+
「事件通知目的地create -name restapi-EMS -REST -API-URL \http://<url_to_rest_api_server>`」

. 建立通知、將「重要事件（Important）”篩選器連結至新的「REstapi-EMS（REstapi-EMS）目的地：
+
「事件通知會建立-filter名稱Important事件-destinations restapi-EMS」





== 設定伺服器憑證HTTPS REST API轉送

此程序假設您先前已產生伺服器端的私密金鑰和公開憑證。它也假設您有根憑證可供安裝在ONTAP 整個過程中。

.步驟
. 在REST API伺服器中安裝適當的伺服器私密金鑰和公開憑證。
+

NOTE: 具體指示取決於伺服器。

. 將伺服器根憑證安裝在ONTAP
+
「安全憑證安裝類型：server、ca」

+
命令會查詢公用憑證。

. 為篩選器「重要事件」建立「REstapi-EMS」目的地。
+
您必須使用HTTPS配置才能使用伺服器端憑證。

+
「事件通知目的地create -name restapi-EMS -REST -API-URL \https://<url_to_rest_api_server>`」

. 建立通知、將「重要事件》篩選器連結至新的「REstapi-EMS（回條路徑）目的地：
+
「事件通知會建立-filter名稱Important事件-destinations restapi-EMS」





== 設定用戶端憑證HTTPS REST API轉送

用戶端憑證的使用是選用的、只有在需要伺服器進行用戶端驗證時才需要。此程序假設您先前已產生用戶端私密金鑰和公開憑證。

.步驟
. 在REST API伺服器中安裝適當的根和中繼憑證、以驗證您的用戶端憑證。
. 將用戶端憑證安裝在ONTAP
+
「安全憑證安裝類型用戶端」

+
命令會查詢私密金鑰和公開憑證。

. 為篩選器「重要事件」建立「REstapi-EMS」目的地。
+
「事件通知目的地create -name restapi-EMS -REST -API-URL」 https://<url_to_rest_api_server>[] -Certificate -authority <用戶端憑證的發行者>-Certificate serial <用戶端憑證的序列>'

. 建立通知、將「重要事件」篩選器連結至新的「REstapi-EMS」目的地。
+
「事件通知會建立-filter名稱Important事件-destinations restapi-EMS」


