---
permalink: error-messages/convert-ems-routing-to-notifications-task.html 
sidebar: sidebar 
keywords: update, ems, mapping, notification, filter, event 
summary: 使用ONTAP 命令列、更新已過時的Eflexec命令 所對應的EMS事件。 
---
= 更新EMS事件對應、以取代過時ONTAP 的EISO命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您的EMS事件對應目前使用過時ONTAP 的支援功能（「EVENT Destination'、「EVENT Route」）進行設定、您應該依照此程序來更新對應、以使用「事件篩選器」、「事件通知」和「事件通知目的地」命令集。

.步驟
. 使用「EVENT DEST目的地show」命令、列出系統中的所有事件目的地。
+
[listing]
----
cluster-1::event*> destination show
                                                                         Hide
Name             Mail Dest.        SNMP Dest.         Syslog Dest.       Params
---------------- ----------------- ------------------ ------------------ ------
allevents        -                 -                  -                  false
asup             -                 -                  -                  false
criticals        -                 -                  -                  false
pager            -                 -                  -                  false
test             test@xyz.com      -                  -                  false
traphost         -                 -                  -                  false
6 entries were displayed.
----
. 對於每個目的地、請使用「EVENT Route show -destinations <目的地名稱>」命令列出對應到它的事件。
+
[listing]
----
cluster-1::event*> route show -destinations test
                                                               Freq    Time
Message                          Severity       Destinations   Threshd Threshd
-------------------------------- -------------- -------------- ------- -------
raid.aggr.autoGrow.abort         NOTICE         test           0       0
raid.aggr.autoGrow.success       NOTICE         test           0       0
raid.aggr.lock.conflict          INFORMATIONAL  test           0       0
raid.aggr.log.CP.count           DEBUG          test           0       0
4 entries were displayed.
----
. 建立對應的「事件篩選器」、其中包含所有這些事件子集。例如、如果您只想要包含「RAID.aggr」*事件、請在建立篩選時使用萬用字元作為「message-name」參數。您也可以為單一事件建立篩選器。
+

NOTE: 您最多可以建立50個事件篩選器。

+
[listing]
----
cluster-1::event*> filter create -filter-name test_events

cluster-1::event*> filter rule add -filter-name test_events -type include -message-name raid.aggr.*

cluster-1::event*> filter show -filter-name test_events
Filter Name Rule     Rule      Message Name           SNMP Trap Type  Severity
            Position Type
----------- -------- --------- ---------------------- --------------- --------
test_events
            1        include   raid.aggr.*            *               *
            2        exclude   *                      *               *
2 entries were displayed.
----
. 為每個「事件目的地」端點（例如SMTP/SNP/syslog）建立「事件通知目的地」
+
[listing]
----
cluster-1::event*> notification destination create -name dest1 -email test@xyz.com

cluster-1::event*> notification destination show
Name            Type        Destination
--------------  ----------  ---------------------
dest1           email       test@xyz.com (via "localhost" from "admin@localhost", configured in "event config")
snmp-traphost   snmp        - (from "system snmp traphost")
2 entries were displayed.
----
. 將事件篩選器對應至事件通知目的地、以建立事件通知。
+
[listing]
----
cluster-1::event*> notification create -filter-name asup_events -destinations dest1

cluster-1::event*> notification show
ID   Filter Name                     Destinations
---- ------------------------------  -----------------
1    default-trap-events             snmp-traphost
2    asup_events                     dest1
2 entries were displayed.
----
. 對每個具有「事件路由」對應的「事件目的地」重複步驟1-5。
+

NOTE: 路由至SNMP目的地的事件應對應至「傳送至傳送主機」事件通知目的地。SNMP traphost目的地使用系統設定的SNMP traphost。

+
[listing]
----
cluster-1::event*> system snmp traphost add 10.234.166.135

cluster-1::event*> system snmp traphost show
        scspr2410142014.gdl.englab.netapp.com (scspr2410142014.gdl.englab.netapp.com) <10.234.166.135>    Community: public

cluster-1::event*> notification destination show -name snmp-traphost

                Destination Name: snmp-traphost
             Type of Destination: snmp
                     Destination: 10.234.166.135 (from "system snmp traphost")
 Server CA Certificates Present?: -
   Client Certificate Issuing CA: -
Client Certificate Serial Number: -
       Client Certificate Valid?: -
----

