---
permalink: error-messages/decide-send-event-notifications-task.html 
sidebar: sidebar 
keywords: deciding, send, important, event notifications 
summary: 在設定重要的EMS事件通知之前、您必須決定要將通知傳送至電子郵件地址、syslog伺服器或SNMP traphost。 
---
= 決定要傳送重要事件通知的位置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在設定重要的EMS事件通知之前、您必須決定是否要將通知傳送至電子郵件地址、syslog伺服器、SNMP traphost或REST API伺服器。

如果您的環境已包含syslog伺服器、可用來彙總來自其他系統（例如伺服器和應用程式）的記錄事件、那麼使用syslog伺服器也能更輕鬆地從儲存系統發出重要的事件通知。

如果您的環境尚未包含syslog伺服器、則使用電子郵件進行重要事件通知會更容易。

如果您已將事件通知轉送到SNMP traphost、則可能需要監控該traphost是否有重要事件。

.選擇
* 設定EMS以傳送事件通知。
+
|===


| 如果您需要... | 請參閱此... 


 a| 
將重要事件通知傳送至電子郵件地址的EMS
 a| 
xref:configure-ems-events-send-email-task.adoc[設定重要的EMS事件以傳送電子郵件通知]



 a| 
EMS可將重要事件通知轉送至syslog伺服器
 a| 
xref:configure-ems-events-notifications-syslog-task.adoc[設定重要的EMS事件、將通知轉送到syslog伺服器]



 a| 
如果您想要EMS將事件通知轉送到SNMP traphost
 a| 
xref:configure-snmp-traphosts-event-notifications-task.adoc[設定SNMP traphosts以接收事件通知]



 a| 
如果您想要EMS將事件通知轉送到REST API伺服器
 a| 
xref:configure-webhooks-event-notifications-task.adoc[設定重要的EMS事件、將通知轉送至REST API伺服器]

|===

