---
permalink: nfs-admin/commands-manage-nis-domain-config-reference.html 
sidebar: sidebar 
keywords: command, manage, nis, domain, configuration 
summary: 管理ONTAP NIS網域組態時、會有特定的功能不完整的指令。 
---
= 用於管理 ONTAP 中 NIS 網域組態的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
管理ONTAP NIS網域組態時、會有特定的功能不完整的指令。

[cols="35,65"]
|===


| 如果您想要... | 使用此命令... 


 a| 
建立NIS網域組態
 a| 
`vserver services name-service nis-domain create`



 a| 
顯示 NIS 網域組態
 a| 
`vserver services name-service nis-domain show`



 a| 
顯示NIS網域組態的繫結狀態
 a| 
`vserver services name-service nis-domain show-bound`



 a| 
顯示 NIS 統計資料
 a| 
`vserver services name-service nis-domain show-statistics` 可在進階權限層級或更高層級使用。



 a| 
清除NIS統計資料
 a| 
`vserver services name-service nis-domain clear-statistics` 可在進階權限層級或更高層級使用。



 a| 
修改NIS網域組態
 a| 
`vserver services name-service nis-domain modify`



 a| 
刪除NIS網域組態
 a| 
`vserver services name-service nis-domain delete`



 a| 
啟用網路群組各主機搜尋的快取
 a| 
`vserver services name-service nis-domain netgroup-database config modify` 可在進階權限層級或更高層級使用。

|===
如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+services+name-service+nis-domain["指令參考資料ONTAP"^]需詳細 `vserver services name-service nis-domain`資訊，請參閱。
