---
permalink: nfs-admin/configure-number-group-ids-allowed-nfs-users-task.html 
sidebar: sidebar 
keywords: ontap, authentication, nfs, group id, rpcsec_gss 
summary: 增加群組 ID 的數量、以便使用 Kerberos 驗證來處理 NFS 使用者認證、以供成員超過預設群組的使用者使用。 
---
= 配置 ONTAP SVM 的 NFS 使用者允許的群組 ID 數量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根據預設、ONTAP 使用Kerberos（RPCSEC_GSS）驗證處理NFS使用者認證時、支援最多32個群組ID。使用AUTH_SYS驗證時、預設的群組ID最大數量為16、如RFC 5531所定義。如果您的使用者成員超過預設群組數、則最多可增加1,024個。

.關於這項工作
如果使用者的認證中有超過預設的群組ID數目、則其餘的群組ID會被刪減、而且使用者在嘗試從儲存系統存取檔案時可能會收到錯誤訊息。您應該將每個SVM的最大群組數設定為代表環境中最大群組數的數字。


NOTE: 若要瞭解啟用延伸(`-auth-sys-extended-groups`群組的 AUTH_SYS 驗證必要條件），請參閱本知識庫文件： https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/What_are_the_prerequisites_for_enabling_auth_sys_extended_groups#["啟用驗證系統擴充群組的必要條件為何？"^]

下表顯示的兩個參數 `vserver nfs modify` 決定三個範例組態中群組 ID 最大數目的命令：

[cols="40,30,30"]
|===


| 參數 | 設定 | 產生的群組ID限制 


 a| 
`-extended-groups-limit`

`-auth-sys-extended-groups`
 a| 
`32`

`disabled`

這些是預設設定。
 a| 
RPCSEC_GSS：32

AUTH_SYS：16



 a| 
`-extended-groups-limit`

`-auth-sys-extended-groups`
 a| 
`256`

`disabled`
 a| 
RPCSEC_GSS ： 256

AUTH_SYS：16



 a| 
`-extended-groups-limit`

`-auth-sys-extended-groups`
 a| 
`512`

`enabled`
 a| 
RPCSEC_GSS ： 512

驗證系統： 512

|===
.步驟
. 將權限層級設為進階：
+
`set -privilege advanced`

. 執行所需的動作：
+
|===


| 如果您要設定允許的輔助群組數目上限... | 輸入命令... 


 a| 
僅適用於RPCSEC_GSS、並將AUTH_SYS設為預設值16
 a| 
`+vserver nfs modify -vserver vserver_name -extended-groups-limit {32-1024} -auth-sys-extended-groups disabled+`



 a| 
適用於RPCSEC_GSS和AUTH_SYS
 a| 
`+vserver nfs modify -vserver vserver_name -extended-groups-limit {32-1024} -auth-sys-extended-groups enabled+`

|===
. 驗證 `-extended-groups-limit` 並驗證 AUTH_SYS 是否使用延伸群組： `vserver nfs show -vserver vserver_name -fields auth-sys-extended-groups,extended-groups-limit`
. 返回管理權限層級：
+
`set -privilege admin`



.範例
下列範例可啟用AUTH_SYS驗證的延伸群組、並將AUTH_SYS和RPCSEC_GSS驗證的延伸群組數目上限設為512。這些變更僅適用於存取名為VS1的SVM的用戶端：

[listing]
----
vs1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use
         them only when directed to do so by NetApp personnel.
Do you want to continue? {y|n}: y

vs1::*> vserver nfs modify -vserver vs1 -auth-sys-extended-groups enabled -extended-groups-limit 512

vs1::*> vserver nfs show -vserver vs1 -fields auth-sys-extended-groups,extended-groups-limit
vserver auth-sys-extended-groups extended-groups-limit
------- ------------------------ ---------------------
vs1     enabled                  512

vs1::*> set -privilege admin
----
.相關資訊
* 知識庫文章： https://kb.netapp.com/on-prem/ontap/da/NAS/NAS-KBs/How_does_AUTH_SYS_Extended_Groups_change_NFS_authentication["驗證 ONTAP 9 的 NFS 驗證延伸群組變更"^]

