---
permalink: nfs-admin/config-options-ldap-directory-searches-concept.html 
sidebar: sidebar 
keywords: LDAP referral chasing 
summary: 您可以設定ONTAP 支援使用者、群組和netgroup資訊等方式、將LDAP用戶端設定為以最適合您環境的方式連線至LDAP伺服器、藉此最佳化LDAP目錄搜尋。您需要瞭解預設的LDAP基礎和範圍搜尋值何時足夠、以及指定自訂值何時更合適的參數。 
---
= LDAP目錄搜尋的組態選項
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定ONTAP 支援使用者、群組和netgroup資訊等方式、將LDAP用戶端設定為以最適合您環境的方式連線至LDAP伺服器、藉此最佳化LDAP目錄搜尋。您需要瞭解預設的LDAP基礎和範圍搜尋值何時足夠、以及指定自訂值何時更合適的參數。

使用者、群組和netgroup資訊的LDAP用戶端搜尋選項、有助於避免LDAP查詢失敗、進而避免用戶端無法存取儲存系統。它們也有助於確保搜尋作業盡可能有效率、以避免用戶端效能問題。



== 預設基礎和範圍搜尋值

LDAP基礎是LDAP用戶端用來執行LDAP查詢的預設基礎DN。所有搜尋、包括使用者、群組和網路群組搜尋、都是使用基礎DN來完成。當您的LDAP目錄相對較小、且所有相關項目都位於相同的DN中時、此選項是適當的。

如果未指定自訂基礎 DN 、則預設值為 `root`。這表示每個查詢都會搜尋整個目錄。雖然如此一來、LDAP查詢的成功機會就會最大化、但效率卻會降低、而且大型LDAP目錄的效能也會大幅降低。

LDAP基礎範圍是LDAP用戶端用來執行LDAP查詢的預設搜尋範圍。所有搜尋、包括使用者、群組和netgroup搜尋、都是使用基礎範圍來完成。它決定LDAP查詢只搜尋命名項目、DN下一層的項目、或DN下的整個子樹狀結構。

如果未指定自訂基礎範圍、則預設為 `subtree`。這表示每個查詢都會搜尋DN下方的整個子樹狀結構。雖然如此一來、LDAP查詢的成功機會就會最大化、但效率卻會降低、而且大型LDAP目錄的效能也會大幅降低。



== 自訂基礎和範圍搜尋值

您也可以為使用者、群組和netgroup搜尋指定個別的基礎和範圍值。以這種方式限制搜尋基礎和查詢範圍、可大幅提升效能、因為它會將搜尋範圍限制在LDAP目錄的較小子部分。

如果指定自訂基礎和範圍值、則會覆寫一般預設搜尋基礎和範圍、以供使用者、群組和netgroup搜尋。可在進階權限層級使用指定自訂基礎和範圍值的參數。

[cols="35,65"]
|===


| LDAP用戶端參數... | 指定自訂... 


 a| 
`-base-dn`
 a| 
所有 LDAP 搜尋的基準 DN。如果需要，可以輸入多個值（例如，如果在 ONTAP 9.5 及更高版本中啟用了 LDAP 引用追蹤）。



 a| 
`-base-scope`
 a| 
所有 LDAP 搜尋的基本範圍。



 a| 
`-user-dn`
 a| 
所有 LDAP 使用者搜尋的基本 DN。此參數也適用於使用者名稱映射搜尋。



 a| 
`-user-scope`
 a| 
所有 LDAP 使用者搜尋的基本範圍。此參數也適用於使用者名稱映射搜尋。



 a| 
`-group-dn`
 a| 
所有 LDAP 群組搜尋的基本 DN。



 a| 
`-group-scope`
 a| 
所有 LDAP 群組搜尋的基本範圍。



 a| 
`-netgroup-dn`
 a| 
所有 LDAP 網路群組搜尋的基本 DN。



 a| 
`-netgroup-scope`
 a| 
所有 LDAP 網路組搜尋的基本範圍。

|===


== 多個自訂基礎DN值

如果您的LDAP目錄結構較為複雜、您可能需要指定多個基礎DNS、以搜尋LDAP目錄的多個部分以取得特定資訊。您可以為使用者、群組和netgroup DN參數指定多個DNS、方法是以分號（；）分隔這些DNS、並以雙引號（"）括住整個DN搜尋清單。如果DN包含分號、您必須在DN中的分號前面新增轉義字元（\）。

請注意、此範圍適用於為對應參數指定的整個DNS清單。例如、如果您為使用者範圍指定三個不同使用者DNS和子樹狀結構的清單、則LDAP使用者會搜尋三個指定DNS中的每個子樹狀結構。

從ONTAP 功能介紹9.5開始、您也可以指定LDAP _Referring Chasing _、以便ONTAP 在主要LDAP伺服器未傳回LDAP參照回應時、讓該支援功能可將查詢要求參照到其他LDAP伺服器。用戶端會使用該參照資料、從參照資料中所述的伺服器擷取目標物件。若要搜尋參照LDAP伺服器中的物件、可將參照物件的基礎DN新增至基礎DN、做為LDAP用戶端組態的一部分。不過、只有在啟用參照追蹤（使用 `-referral-enabled true` 選項）。



== 自訂 LDAP 搜尋篩選器

您可以使用 LDAP 組態選項參數來建立自訂搜尋篩選器。此 `-group-membership-filter`參數指定從 LDAP 伺服器查詢群組成員資格時所使用的搜尋篩選器。

有效篩選的範例包括：

[listing]
----
(cn=*99), (cn=1*), (|(cn=*22)(cn=*33))
----
深入瞭解 link:https://www.netapp.com/media/19423-tr-4835.pdf["如何在 ONTAP 中設定 LDAP"^]。
