---
permalink: nfs-admin/enable-or-disable-nfs-over-tls-cli.html 
sidebar: sidebar 
keywords: enable, tls, data, lif 
summary: 您可以使用 ONTAP CLI 在 NFS 用戶端的資料 LIF 上啟用 TLS 。這可讓 SVM 使用 TLS 安全服務 for NFS 。 
---
= 在 ONTAP 中啟用或停用 TLS for NFS 用戶端
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定 NFS over TLS 來加密所有透過網路在 NFS 用戶端和 ONTAP 之間傳送的資料、藉此改善 NFS 連線的安全性。如此可提高 NFS 連線的安全性。您可以在已啟用 NFS 的現有儲存 VM 上進行設定。


NOTE: 9.15.1 提供 ONTAP over TLS 的公開預覽功能。ONTAP 9.15.1 的正式作業工作負載不支援 NFS over TLS 作為預覽產品。



== 啟用 TLS

您可以為 NFS 用戶端啟用 TLS 加密、以提高傳輸中資料的安全性。

.開始之前
* 請參閱 link:tls-nfs-strong-security-concept.html["需求"] 在開始之前使用 NFS over TLS 。
* 如需此程序中命令的詳細資訊、請參閱 ONTAP 手冊頁。
* 深入瞭解 ONTAP 命令參照中的連結： https://docs 。 NetApp 。 ONTAP - CLI/vserver-nfs-tls-interface-enable.html[`vserver nfs tls interface show`^] 命令。


.步驟
. 選擇要啟用 TLS 的儲存 VM 和邏輯介面（ LIF ）。
. 在該儲存 VM 和介面上啟用 TLS for NFS 連線。
+
[source, console]
----
vserver nfs tls interface enable -vserver <STORAGE_VM> -lif <LIF_NAME> -certificate-name <CERTIFICATE_NAME>
----
. 使用 `vserver nfs tls interface show` 檢視結果的命令：
+
[source, console]
----
vserver nfs tls interface show
----


.範例
下列命令可在上啟用 NFS over TLS `data1` 的 LIF `vs1` 儲存 VM ：

[source, console]
----
vserver nfs tls interface enable -vserver vs1 -lif data1 -certificate-name cert_vs1
----
[source, console]
----
vserver nfs tls interface show
----
....
               Logical
Vserver        Interface     Address         TLS Status TLS Certificate Name
-------------- ------------- --------------- ---------- -----------------------
vs1            data1         10.0.1.1        enabled    cert_vs1
vs2            data2         10.0.1.2        disabled   -
2 entries were displayed.
....


== 停用 TLS

如果不再需要傳輸中資料的增強安全性、您可以停用 TLS for NFS Client 。

.開始之前
深入瞭解 ONTAP 命令參照中的連結： https://docs 。 NetApp 。 ONTAP - CLI/vserver-nfs-tls-interface-disable.html[`vserver nfs tls interface disable`^] 命令。

.步驟
. 選擇要停用 TLS 的儲存 VM 和邏輯介面（ LIF ）。
. 在該儲存 VM 和介面上停用 TLS for NFS 連線。
+
[source, console]
----
vserver nfs tls interface disable -vserver <STORAGE_VM> -lif <LIF_NAME>
----
. 使用 `vserver nfs tls interface show` 檢視結果的命令：
+
[source, console]
----
vserver nfs tls interface show
----


.範例
下列命令會停用上的 NFS over TLS `data1` 的 LIF `vs1` 儲存 VM ：

[source, console]
----
vserver nfs tls interface disable -vserver vs1 -lif data1
----
[source, console]
----
vserver nfs tls interface show
----
....
               Logical
Vserver        Interface     Address         TLS Status TLS Certificate Name
-------------- ------------- --------------- ---------- -----------------------
vs1            data1         10.0.1.1        disabled   -
vs2            data2         10.0.1.2        disabled   -
2 entries were displayed.
....


== 編輯 TLS 組態

您可以變更現有 NFS over TLS 組態的設定。例如、您可以使用此程序來更新 TLS 憑證。

.開始之前
深入瞭解 ONTAP 命令參照中的連結： https://docs 。 NetApp 。 ONTAP - CLI/vserver-nfs-tls-interface-modify.html[`vserver nfs tls interface modify`^] 命令。

.步驟
. 選擇要修改 NFS 用戶端 TLS 組態的儲存 VM 和邏輯介面（ LIF ）。
. 修改組態。如果您指定 `status` 的 `enable`、您也需要指定 `certificate-name` 參數。以您環境的資訊取代括弧 <> 中的值：
+
[source, console]
----
vserver nfs tls interface modify -vserver <STORAGE_VM> -lif <LIF_NAME> -status <STATUS> -certificate-name <CERTIFICATE_NAME>
----
. 使用 `vserver nfs tls interface show` 檢視結果的命令：
+
[source, console]
----
vserver nfs tls interface show
----


.範例
下列命令會修改上的 NFS over TLS 組態 `data2` 的 LIF `vs2` 儲存 VM ：

[source, console]
----
vserver nfs tls interface modify -vserver vs2 -lif data2 -status enable -certificate-name new_cert
----
[source, console]
----
vserver nfs tls interface show
----
....
               Logical
Vserver        Interface     Address         TLS Status TLS Certificate Name
-------------- ------------- --------------- ---------- -----------------------
vs1            data1         10.0.1.1        disabled   -
vs2            data2         10.0.1.2        enabled    new_cert
2 entries were displayed.
....
.相關資訊
link:../task_nas_enable_linux_nfs.html["使用NFS為Linux伺服器啟用NAS儲存設備"]。
