---
permalink: nfs-admin/export-rules-concept.html 
sidebar: sidebar 
keywords: export, rule, work 
summary: 匯出規則是匯出原則的功能要素。匯出規則會根據您設定的特定參數、將用戶端存取要求與磁碟區相符、以決定如何處理用戶端存取要求。 
---
= 匯出規則的運作方式
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
匯出規則是匯出原則的功能要素。匯出規則會根據您設定的特定參數、將用戶端存取要求與磁碟區相符、以決定如何處理用戶端存取要求。

匯出原則必須包含至少一個匯出規則、才能允許存取用戶端。如果匯出原則包含多個規則、則會依照規則在匯出原則中的顯示順序來處理這些規則。規則順序由規則索引編號決定。如果規則符合用戶端、則會使用該規則的權限、而且不會再處理其他規則。如果沒有符合的規則、用戶端就會被拒絕存取。

您可以使用下列準則來設定匯出規則、以決定用戶端存取權限：

* 傳送要求的用戶端所使用的檔案存取傳輸協定、例如NFSv4或SMB。
* 用戶端識別碼、例如主機名稱或IP位址。
+
「-clientMATCH」欄位的大小上限為4096個字元。

* 用戶端用來驗證的安全性類型、例如Kerberos v5, NTL,或AUTH_SYS。


如果規則指定多個準則、用戶端必須符合所有準則、才能套用規則。

[NOTE]
====
從ONTAP 功能表支援的支援範例9.3開始、您可以啟用匯出原則組態檢查、做為背景工作、將任何違反規則的行為記錄在錯誤規則清單中。「vserver ex遵循 原則組態檢查程式」命令會叫用檢查程式和顯示結果、您可以使用這些檢查程式來驗證組態、並從原則中刪除錯誤的規則。

這些命令只會驗證主機名稱、網路群組和匿名使用者的匯出組態。

====
.範例
匯出原則包含具有下列參數的匯出規則：

* 「nfs3」
* -'用戶端配對'「10.1.16.0/255．255．255．0」
* 《任何》
* 《任何》


用戶端存取要求是使用NFSv3傳輸協定傳送、用戶端的IP位址為10.1.17.37。

即使用戶端存取傳輸協定相符、用戶端的IP位址仍位於與匯出規則中指定的子網路不同的子網路中。因此、用戶端比對失敗、此規則不適用於此用戶端。

.範例
匯出原則包含具有下列參數的匯出規則：

* 這是一種「NFS」傳輸協定
* -'用戶端配對'「10.1.16.0/255．255．255．0」
* 《任何》
* 《任何》


用戶端存取要求是使用NFSv4傳輸協定傳送、用戶端的IP位址為10.1.16.54。

用戶端存取傳輸協定相符、用戶端的IP位址位於指定的子網路中。因此、用戶端配對成功、此規則適用於此用戶端。無論用戶端的安全類型為何、都能取得讀寫存取權。

.範例
匯出原則包含具有下列參數的匯出規則：

* 「nfs3」
* -'用戶端配對'「10.1.16.0/255．255．255．0」
* 《任何》
* 《rwrRule》《krb5、NTLM'》


用戶端#1的IP位址為10.1.16.207、使用NFSv3傳輸協定傳送存取要求、並使用Kerberos v5進行驗證。

用戶端#2的IP位址為10.1.16.211、使用NFSv3傳輸協定傳送存取要求、並透過AUTH_SYS進行驗證。

兩個用戶端的用戶端存取傳輸協定和IP位址都相符。唯讀參數允許所有用戶端的唯讀存取權、無論其驗證的安全類型為何。因此這兩個用戶端都能取得唯讀存取權。但是、只有用戶端#1會取得讀寫存取權、因為它使用核准的安全性類型Kerberos v5.x進行驗證。用戶端#2無法取得讀寫存取權。
