---
permalink: nfs-admin/flush-export-policy-caches-task.html 
sidebar: sidebar 
keywords: flush, export, policy, cache 
summary: 手動排清匯出原則快取（vserver匯出原則快取排清）會移除可能過時的資訊、並強制ONTAP 使用適當的外部資源擷取目前資訊。這有助於解決與用戶端存取NFS匯出相關的各種問題。 
---
= 排清匯出原則快取
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
使用多個匯出原則快取來儲存匯出原則相關資訊、以加快存取速度。ONTAP手動排清匯出原則快取（「vserver匯出原則快取排清」）會移除可能過時的資訊、迫使ONTAP 效益分析從適當的外部資源擷取目前資訊。這有助於解決與用戶端存取NFS匯出相關的各種問題。

匯出原則快取資訊可能因為下列原因而過期：

* 最近對匯出原則規則所做的變更
* 最近變更名稱伺服器中的主機名稱記錄
* 最近在名稱伺服器中變更netgroup項目
* 從網路中斷中恢復、避免網路群組完全載入


.步驟
. 如果您未啟用名稱服務快取、請在預先權限模式中執行下列其中一項動作：
+
[cols="2*"]
|===
| 如果您想要清除... | 輸入命令... 


 a| 
所有匯出原則快取（showmount除外）
 a| 
「vserver匯出原則快取flush -vserver vserver_name」



 a| 
匯出原則規則存取快取
 a| 
「vserver匯出原則快取排清-vserver vserver_name -快取存取」可以包含選用的「節點」參數、以指定您要排清存取快取的節點。



 a| 
主機名稱快取
 a| 
「vserver匯出原則快取flush -vserver vserver_name -cache host」



 a| 
netgroup快取
 a| 
「vserver匯出原則快取排清-vserver vserver_name -cache netgroup」網路群組的處理作業需要大量資源。如果您嘗試解決由舊網路群組所造成的用戶端存取問題、則只能清除網路群組快取。



 a| 
showmount快取
 a| 
「vserver匯出原則快取flush -vserver vserver_name -cache showmount」

|===
. 如果已啟用名稱服務快取、請執行下列其中一項動作：
+
[cols="2*"]
|===
| 如果您想要清除... | 輸入命令... 


 a| 
匯出原則規則存取快取
 a| 
「vserver匯出原則快取排清-vserver vserver_name -快取存取」可以包含選用的「節點」參數、以指定您要排清存取快取的節點。



 a| 
主機名稱快取
 a| 
「Vserver服務名稱服務快取主機轉送查詢刪除全部」



 a| 
netgroup快取
 a| 
「Vserver服務名稱服務快取網路群組IP對網路群組刪除所有」「Vserver服務名稱服務快取網路群組成員刪除所有」網路群組的處理作業需要大量資源。如果您嘗試解決由舊網路群組所造成的用戶端存取問題、則只能清除網路群組快取。



 a| 
showmount快取
 a| 
「vserver匯出原則快取flush -vserver vserver_name -cache showmount」

|===

