---
permalink: nfs-admin/handle-superuser-access-requests-concept.html 
sidebar: sidebar 
keywords: how, handle, superuser, access, request 
summary: 設定匯出原則時、您必須考量儲存系統收到使用者ID為0的用戶端存取要求（表示以超級使用者身分）時、會發生什麼情況、並據此設定匯出規則。 
---
= 管理超級使用者存取要求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
設定匯出原則時、您必須考量儲存系統收到使用者ID為0的用戶端存取要求（表示以超級使用者身分）時、會發生什麼情況、並據此設定匯出規則。

在UNIX世界中、使用者ID為0的使用者稱為超級使用者、通常稱為root、在系統上擁有無限存取權限。使用進階使用者權限可能會有危險、原因包括系統和資料安全性遭到破壞。

根據預設ONTAP 、功能表會將使用者ID為0的用戶端對應至匿名使用者。不過、您可以在匯出規則中指定「超級使用者」參數、以決定如何處理顯示使用者ID 0的用戶端、視其安全類型而定。以下是"-root"參數的有效選項：

* 「任何」
* 無
+
如果您未指定「超級使用者」參數、則此為預設設定。

* 《KRB5》
* "NTLM"
* 《時代》


視「超級使用者」參數組態而定、以使用者ID 0呈現的用戶端有兩種不同的處理方式：

[cols="2*"]
|===
| 如果"*超級使用者*"參數和用戶端的安全類型... | 然後用戶端... 


 a| 
相符
 a| 
以使用者ID 0取得超級使用者存取權。



 a| 
不相符
 a| 
以匿名使用者身分取得存取權、其使用者ID由「-anon'參數指定、並具有指派的權限。無論唯讀或讀寫參數是否指定選項「無」、都是如此。

|===
如果用戶端顯示使用者ID 0以存取NTFS安全樣式的磁碟區、而「超級使用者」參數設為「無」、ONTAP 則會使用匿名使用者的名稱對應來取得適當的認證。

.範例
匯出原則包含具有下列參數的匯出規則：

* 「nfs3」
* -'用戶端配對'「10.1.16.0/255．255．255．0」
* 《任何》
* 《rwrRule》《krb5、NTLM'》
* 《127》


用戶端#1的IP位址為10.1.16.207、使用者ID為746、使用NFSv3傳輸協定傳送存取要求、並使用Kerberos v5進行驗證。

用戶端#2的IP位址為10.1.16.211、使用者ID為0、使用NFSv3傳輸協定傳送存取要求、並以AUTH_SYS驗證。

兩個用戶端的用戶端存取傳輸協定和IP位址都相符。唯讀參數允許所有用戶端的唯讀存取權、無論其驗證的安全類型為何。但是、只有用戶端#1會取得讀寫存取權、因為它使用核准的安全性類型Kerberos v5.x進行驗證。

用戶端#2無法取得超級使用者存取權。相反地、它會對應至匿名、因為未指定「超級使用者」參數。這表示它預設為「無」、並自動將使用者ID 0對應至匿名。用戶端#2也只會取得唯讀存取權、因為其安全性類型與讀寫參數不符。

.範例
匯出原則包含具有下列參數的匯出規則：

* 「nfs3」
* -'用戶端配對'「10.1.16.0/255．255．255．0」
* 《任何》
* 《rwrRule》《krb5、NTLM'》
* 超級使用者的「krb5」
* 「0」


用戶端#1的IP位址為10.1.16.207、使用者ID為0、使用NFSv3傳輸協定傳送存取要求、並使用Kerberos v5進行驗證。

用戶端#2的IP位址為10.1.16.211、使用者ID為0、使用NFSv3傳輸協定傳送存取要求、並以AUTH_SYS驗證。

兩個用戶端的用戶端存取傳輸協定和IP位址都相符。唯讀參數允許所有用戶端的唯讀存取權、無論其驗證的安全類型為何。但是、只有用戶端#1會取得讀寫存取權、因為它使用核准的安全性類型Kerberos v5.x進行驗證。用戶端#2無法取得讀寫存取權。

匯出規則可讓使用者ID為0的用戶端擁有超級使用者存取權。用戶端#1會取得超級使用者存取權、因為它符合唯讀和「超級使用者」參數的使用者ID和安全性類型。由於用戶端#2的安全性類型與讀寫參數或「超級使用者」參數不符、因此無法取得讀寫或超級使用者存取權。而是將用戶端#2對應至匿名使用者、在此案例中、該使用者ID為0。
