---
permalink: nfs-admin/handle-clients-unlisted-security-type-concept.html 
sidebar: sidebar 
keywords: handle, client, unlist, security, type 
summary: 當用戶端呈現的安全性類型未列在匯出規則的存取參數中時、您可以選擇拒絕存取用戶端、或是使用存取參數中的選項NONE將其對應至匿名使用者ID。 
---
= 管理具有未列出的安全性類型的 NFS 用戶端的 ONTAP SVM 訪問
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當用戶端呈現未列在匯出規則存取參數中的安全性類型時、您可以選擇拒絕用戶端存取、或改用選項將其對應至匿名使用者 ID `none` 在存取參數中。

用戶端可能會出現未列在存取參數中的安全性類型、因為它是以不同的安全性類型驗證、或根本未驗證（安全性類型AUTH_NONE）。根據預設、用戶端會自動拒絕存取該層級。不過、您可以新增選項 `none` 存取參數。因此、具有未列出安全性樣式的用戶端會對應至匿名使用者ID。。 `-anon` 參數決定指派給這些用戶端的使用者 ID 。為指定的使用者 ID `-anon` 參數必須是有效的使用者、且必須設定您認為適合匿名使用者的權限。

的有效值 `-anon` 參數範圍從 `0` 至 `65535`。

[cols="2*"]
|===
| 指派給的使用者 ID `-anon` | 最終處理用戶端存取要求 


 a| 
`0` - `65533`
 a| 
用戶端存取要求會對應至匿名使用者ID、並根據為此使用者設定的權限而取得存取權。



 a| 
`65534`
 a| 
用戶端存取要求會對應至使用者nobody、並根據為此使用者設定的權限而取得存取權。這是預設值。



 a| 
`65535`
 a| 
任何用戶端的存取要求都會在對應至此ID時遭到拒絕、而用戶端會顯示安全性類型AUTH_NONE。當用戶ID為0的用戶端對應至此ID時、會拒絕該用戶端的存取要求、而用戶端會顯示任何其他安全類型。

|===
使用選項時 `none`請務必記住、唯讀參數會先處理。針對未列出的安全性類型用戶端設定匯出規則時、請考慮下列準則：

[cols="3*"]
|===
| 唯讀包含 `none` | 讀寫包括 `none` | 產生未列出安全性類型之用戶端的存取權 


 a| 
否
 a| 
否
 a| 
已拒絕



 a| 
否
 a| 
是的
 a| 
因為先處理唯讀而遭拒



 a| 
是的
 a| 
否
 a| 
唯讀為匿名



 a| 
是的
 a| 
是的
 a| 
匿名讀寫

|===
.範例
匯出原則包含具有下列參數的匯出規則：

* `-protocol` `nfs3`
* `-clientmatch` `10.1.16.0/255.255.255.0`
* `-rorule` `sys,none`
* `-rwrule` `any`
* `-anon` `70`


用戶端#1的IP位址為10.1.16.207、使用NFSv3傳輸協定傳送存取要求、並使用Kerberos v5進行驗證。

用戶端#2的IP位址為10.1.16.211、使用NFSv3傳輸協定傳送存取要求、並透過AUTH_SYS進行驗證。

用戶端#3的IP位址為10.1.16.234、使用NFSv3傳輸協定傳送存取要求、但未驗證（亦即安全性類型AUTH_NONE）。

這三個用戶端的用戶端存取傳輸協定和IP位址都相符。唯讀參數允許以驗證為AUTH_SYS的自有使用者ID來唯讀存取用戶端。唯讀參數允許匿名使用者以使用者ID 70的身分存取使用任何其他安全性類型驗證的用戶端。讀寫參數允許對任何安全類型進行讀寫存取、但在這種情況下、僅適用於已由唯讀規則篩選的用戶端。

因此、用戶端#1和#3只能以使用者ID 70的匿名使用者身分取得讀寫存取權。用戶端#2使用自己的使用者ID取得讀寫存取權。

.範例
匯出原則包含具有下列參數的匯出規則：

* `-protocol` `nfs3`
* `-clientmatch` `10.1.16.0/255.255.255.0`
* `-rorule` `sys,none`
* `-rwrule` `none`
* `-anon` `70`


用戶端#1的IP位址為10.1.16.207、使用NFSv3傳輸協定傳送存取要求、並使用Kerberos v5進行驗證。

用戶端#2的IP位址為10.1.16.211、使用NFSv3傳輸協定傳送存取要求、並透過AUTH_SYS進行驗證。

用戶端#3的IP位址為10.1.16.234、使用NFSv3傳輸協定傳送存取要求、但未驗證（亦即安全性類型AUTH_NONE）。

這三個用戶端的用戶端存取傳輸協定和IP位址都相符。唯讀參數允許以驗證為AUTH_SYS的自有使用者ID來唯讀存取用戶端。唯讀參數允許匿名使用者以使用者ID 70的身分存取使用任何其他安全性類型驗證的用戶端。讀寫參數只允許匿名使用者進行讀寫存取。

因此、用戶端#1和用戶端#3只能以使用者ID 70的匿名使用者身分取得讀寫存取權。用戶端#2使用自己的使用者ID取得唯讀存取權、但拒絕讀寫存取。
