---
permalink: nfs-admin/multidomain-searches-unix-windows-user-concept.html 
sidebar: sidebar 
keywords:  
summary: 將UNIX使用者對應至Windows使用者時、支援多網域搜尋。ONTAP在傳回相符結果之前、會搜尋所有探索到的信任網域是否符合取代模式。或者、您也可以設定偏好的信任網域清單、以取代探索到的信任網域清單、並依序搜尋、直到傳回相符的結果為止。 
---
= 多網域會搜尋UNIX使用者對Windows使用者名稱對應
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將UNIX使用者對應至Windows使用者時、支援多網域搜尋。ONTAP在傳回相符結果之前、會搜尋所有探索到的信任網域是否符合取代模式。或者、您也可以設定偏好的信任網域清單、以取代探索到的信任網域清單、並依序搜尋、直到傳回相符的結果為止。



== 網域信任如何影響UNIX使用者對Windows使用者名稱對應搜尋

若要瞭解多網域使用者名稱對應的運作方式、您必須瞭解網域信任如何搭配ONTAP 使用。Active Directory與SMB伺服器主網域的信任關係可以是雙向信任關係、也可以是兩種單向信任關係之一、即傳入信任關係或傳出信任關係。主網域是SVM上SMB伺服器所屬的網域。

* _雙向信任_
+
透過雙向信任、這兩個網域彼此信任。如果SMB伺服器的主網域與另一個網域具有雙向信任、主網域可以驗證及授權屬於信任網域的使用者、反之亦然。

+
UNIX使用者對Windows使用者名稱對應搜尋只能在主網域與其他網域之間具有雙向信任的網域上執行。

* 傳出信任_
+
透過傳出信任、主網域信任其他網域。在此情況下、主網域可以驗證及授權屬於傳出信任網域的使用者。

+
執行UNIX使用者對Windows使用者名稱對應搜尋時、會搜尋具有主網域外傳信任的網域。

* 傳入信任_
+
在傳入信任的情況下、其他網域會信任SMB伺服器的主網域。在此情況下、主網域無法驗證或授權屬於傳入信任網域的使用者。

+
在執行UNIX使用者對Windows使用者名稱對應搜尋時、會搜尋具有主網域傳入信任的網域。





== 如何使用萬用字元（*）來設定多網域搜尋名稱對應

在Windows使用者名稱的網域區段中使用萬用字元、可協助進行多網域名稱對應搜尋。下表說明如何在名稱對應項目的網域部分使用萬用字元來啟用多網域搜尋：

[cols="3*"]
|===
| 模式 | 更換 | 結果 


 a| 
根
 a| 
｛星號｝｛反斜槓｝｛反斜槓｝管理員
 a| 
UNIX使用者「root」會對應至名為「Administrator」的使用者。搜尋所有信任的網域、直到找到第一個相符的使用者「'Administrator」為止。



 a| 
*
 a| 
｛星號｝｛反斜槓｝｛反斜槓｝｛星號｝
 a| 
有效的UNIX使用者會對應至對應的Windows使用者。會依序搜尋所有信任的網域、直到找到第一個與該名稱相符的使用者為止。

[NOTE]
====
模式｛星號｝｛反斜槓｝｛反斜槓｝｛星號｝僅適用於從UNIX到Windows的名稱對應、而非其他方式。

====
|===


== 執行多網域名稱搜尋的方式

您可以選擇兩種方法之一來決定用於多網域名稱搜尋的信任網域清單：

* 使用ONTAP 由資訊更新所編譯的自動探索雙向信任清單
* 使用您所編譯的慣用信任網域清單


如果UNIX使用者以萬用字元對應至使用者名稱的網域區段、則Windows使用者會在所有信任的網域中查詢、如下所示：

* 如果已設定慣用的信任網域清單、則對應的Windows使用者只會依序在搜尋清單中查詢。
* 如果未設定信任網域的慣用清單、則會在主網域的所有雙向信任網域中查詢Windows使用者。
* 如果主網域沒有雙向信任的網域、則會在主網域中查詢該使用者。


如果UNIX使用者對應至使用者名稱中沒有網域區段的Windows使用者、則會在主網域中查詢Windows使用者。
