---
permalink: nfs-admin/nfs-credential-cache-concept.html 
sidebar: sidebar 
keywords: nfs, credential, cache 
summary: 當NFS使用者要求存取儲存系統上的NFS匯出時、ONTAP 必須從外部名稱伺服器或從本機檔案擷取使用者認證資料、才能驗證使用者。然後將這些認證資料儲存在內部認證快取中、以供日後參考。ONTAP瞭解NFS認證快取的運作方式、可讓您處理潛在的效能和存取問題。 
---
= ONTAP NFS 憑證快取的工作原理
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當NFS使用者要求存取儲存系統上的NFS匯出時、ONTAP 必須從外部名稱伺服器或從本機檔案擷取使用者認證資料、才能驗證使用者。然後將這些認證資料儲存在內部認證快取中、以供日後參考。ONTAP瞭解NFS認證快取的運作方式、可讓您處理潛在的效能和存取問題。

如果沒有認證快取、ONTAP 每當NFS使用者要求存取時、就必須查詢名稱服務。在許多使用者存取的忙碌儲存系統上、這很快就會導致嚴重的效能問題、造成不必要的延遲、甚至使NFS用戶端存取遭到拒絕。

利用認證快取功能、ONTAP 當NFS用戶端傳送另一個要求時、將會擷取使用者認證資料、然後儲存預先決定的時間量、以便快速輕鬆地存取。此方法具有下列優點：

* 它可處理較少的外部名稱伺服器（例如NIS或LDAP）要求、進而減輕儲存系統的負載。
* 它能減少傳送要求給外部名稱伺服器的次數、進而減輕其負載。
* 它可免除從外部來源取得認證的等待時間、以便驗證使用者、進而加速使用者存取。


支援將正面和負面的認證資料儲存在認證快取中。ONTAP正向認證表示使用者已通過驗證並獲得存取權。負面認證表示使用者未通過驗證、因此被拒絕存取。

根據預設、ONTAP 將正向認證資料儲存24小時；也就是ONTAP 在初始驗證使用者之後、將快取認證資料用於該使用者24小時內的任何存取要求。如果使用者在24小時後要求存取、週期就會開始：ONTAP 由下列項目開始：循環捨棄快取的認證資料、並從適當的名稱服務來源再次取得認證資料。如果在過去24小時內、名稱伺服器上的認證有所變更、ONTAP 則會快取更新的認證資料、以供未來24小時使用。

根據預設、ONTAP 功能不正常的情況下、將負面認證資料儲存兩小時；也就是ONTAP 在一開始拒絕使用者存取之後、該使用者在兩小時內仍拒絕任何存取要求。如果使用者在2小時後要求存取、則週期將從下列項目開始：ONTAP 再次從適當的名稱服務來源取得認證。如果在過去兩小時內、名稱伺服器上的認證資料有所變更、ONTAP 則會快取更新的認證資料、以供未來兩小時使用。
