---
permalink: nfs-admin/nfsv3-nfsv4-performance-tcp-transfer-size-concept.html 
sidebar: sidebar 
keywords: nfsv3, nfsv4, performance, improvement, modify, tcp, transfer, size 
summary: 您可以修改TCP最大傳輸大小、藉此改善透過高延遲網路連線至儲存系統的NFSv3和NFSv4用戶端效能。 
---
= 透過修改TCP傳輸大小、可改善NFSv3和NFSv3效能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以修改TCP最大傳輸大小、藉此改善透過高延遲網路連線至儲存系統的NFSv3和NFSv4用戶端效能。

當用戶端透過延遲時間超過10毫秒的廣域網路（WAN）或城域網路（MAN）存取儲存系統時、您可能可以修改TCP最大傳輸大小來改善連線效能。在低延遲網路（例如區域網路（LAN））中存取儲存系統的用戶端、可能無法從修改這些參數中獲益。如果處理量改善並不超過延遲影響、則不應使用這些參數。

若要判斷您的儲存環境是否能從修改這些參數中獲益、您應該先對效能不佳的NFS用戶端進行全面的效能評估。檢閱低效能是否是因為用戶端的往返延遲過大和要求較少。在這些情況下、用戶端和伺服器無法完全使用可用頻寬、因為他們大部分的工作週期都在等待透過連線傳輸的小要求和回應。

藉由增加NFSv3和NFSv4要求大小、用戶端和伺服器可以更有效地使用可用頻寬、以每單位時間移動更多資料、進而提高連線的整體效率。

請記住、儲存系統與用戶端之間的組態可能有所不同。儲存系統和用戶端支援最大1 MB的傳輸作業大小。不過、如果您將儲存系統設定為支援1 MB的最大傳輸大小、但用戶端僅支援64 KB、則掛載傳輸大小限制為64 KB或更小。

在修改這些參數之前、您必須注意、這會在組裝和傳輸大量回應所需的一段時間內、在儲存系統上產生額外的記憶體使用量。與儲存系統的高延遲連線越多、額外的記憶體使用量就越高。高記憶體容量的儲存系統可能因為這項變更而幾乎沒有任何影響。記憶體容量過低的儲存系統可能會發生明顯的效能降低。

成功使用這些參數取決於從叢集的多個節點擷取資料的能力。叢集網路固有的延遲可能會增加回應的整體延遲。使用這些參數時、整體延遲通常會增加。因此、對延遲敏感的工作負載可能會產生負面影響。
