---
permalink: nfs-admin/ontap-export-policy-caches-concept.html 
sidebar: sidebar 
keywords: ontap, use, export, policy, cache 
summary: 為了提升系統效能、ONTAP 此功能使用本機快取來儲存主機名稱和網路群組等資訊。相較於從外部來源擷取資訊、這樣的功能可讓ONTAP 支援部門更快處理匯出原則規則。瞭解快取內容及其功能有助於疑難排解用戶端存取問題。 
---
= 如何使用匯出原則快取ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了提升系統效能、ONTAP 此功能使用本機快取來儲存主機名稱和網路群組等資訊。相較於從外部來源擷取資訊、這樣的功能可讓ONTAP 支援部門更快處理匯出原則規則。瞭解快取內容及其功能有助於疑難排解用戶端存取問題。

您可以設定匯出原則來控制用戶端對NFS匯出的存取。每個匯出原則都包含規則、而且每個規則都包含參數、可讓規則符合要求存取的用戶端。有些參數需要ONTAP 使用支援功能來聯絡外部來源、例如DNS或NIS伺服器、才能解析網域名稱、主機名稱或網路群組等物件。

這些與外部來源的通訊只需要很短的時間。為了提升效能ONTAP 、利用將資訊儲存在多個快取的每個節點上、藉此減少解析匯出原則規則物件所需的時間。

[cols="2*"]
|===
| 快取名稱 | 儲存的資訊類型 


 a| 
存取
 a| 
用戶端對應至對應的匯出原則



 a| 
名稱
 a| 
UNIX使用者名稱對應至對應的UNIX使用者ID



 a| 
ID
 a| 
UNIX使用者ID對應至對應的UNIX使用者ID和延伸UNIX群組ID



 a| 
主機
 a| 
將主機名稱對應至對應的IP位址



 a| 
網路群組
 a| 
網路群組對應至成員對應的IP位址



 a| 
showmount
 a| 
從SVM命名空間匯出的目錄清單

|===
如果在擷取並儲存於本機之後、變更環境中外部名稱伺服器的資訊ONTAP 、快取現在可能會包含過時的資訊。雖然在特定時間段後、會自動重新整理快取、但不同的快取會有不同的過期時間、重新整理時間和演算法。ONTAP

另一個快取包含過時資訊的可能原因是ONTAP 、當某些人嘗試重新整理快取的資訊、但嘗試與名稱伺服器通訊時卻遭遇失敗。如果發生這種情況、ONTAP 則會繼續使用目前儲存在本機快取中的資訊、以防止用戶端中斷運作。

因此、原本應該成功的用戶端存取要求可能會失敗、而原本應該失敗的用戶端存取要求可能會成功。疑難排解此類用戶端存取問題時、您可以檢視並手動清除部分匯出原則快取。
