---
permalink: nfs-admin/troubleshoot-name-service-issues-task.html 
sidebar: sidebar 
keywords: troubleshoot, name, service, issue 
summary: 當用戶端因為名稱服務問題而遭遇存取失敗時、您可以使用vserver服務名稱服務getxxbyyy命令系列手動執行各種名稱服務查詢、並檢查查詢的詳細資料和結果、以協助疑難排解。 
---
= 疑難排解名稱服務問題
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當用戶端因為名稱服務問題而發生存取失敗時、您可以使用 `vserver services name-service getxxbyyy` 命令系列可手動執行各種名稱服務查詢、並檢查查詢的詳細資料和結果、以協助進行疑難排解。

.關於這項工作
* 您可以針對每個命令指定下列項目：
+
** 執行查詢的節點或儲存虛擬機器（SVM）名稱。
+
這可讓您測試特定節點或SVM的名稱服務查詢、以縮小搜尋名稱服務組態問題的範圍。

** 是否顯示用於查詢的來源。
+
這可讓您檢查是否使用了正確的來源。



* 根據設定的名稱服務交換器訂單、選擇執行查詢的服務。ONTAP
* 這些命令可在進階權限層級使用。


.步驟
. 執行下列其中一項動作：


|===


| 若要擷取... | 使用命令... 


 a| 
主機名稱的IP位址
 a| 
`vserver services name-service getxxbyyy getaddrinfo`     `vserver services name-service getxxbyyy gethostbyname` （僅限 IPv4 位址）



 a| 
依群組ID的群組成員
 a| 
`vserver services name-service getxxbyyy getgrbygid`



 a| 
群組成員（依群組名稱）
 a| 
`vserver services name-service getxxbyyy getgrbyname`



 a| 
使用者所屬的群組清單
 a| 
`vserver services name-service getxxbyyy getgrlist`



 a| 
IP位址的主機名稱
 a| 
`vserver services name-service getxxbyyy getnameinfo`     `vserver services name-service getxxbyyy gethostbyaddr` （僅限 IPv4 位址）



 a| 
使用者名稱的使用者資訊
 a| 
`vserver services name-service getxxbyyy getpwbyname`     您可以指定來測試 RBAC 使用者的名稱解析 `-use-rbac` 參數為 `true`。



 a| 
使用者ID的使用者資訊
 a| 
`vserver services name-service getxxbyyy getpwbyuid`
您可以指定來測試 RBAC 使用者的名稱解析 `-use-rbac` 參數為 `true`。



 a| 
用戶端的網路群組成員資格
 a| 
`vserver services name-service getxxbyyy netgrp`



 a| 
使用netgroup by host搜尋的用戶端網路群組成員資格
 a| 
`vserver services name-service getxxbyyy netgrpbyhost`

|===
下列範例顯示SVM VS1的DNS查詢測試、嘗試取得主機acast1.eng.example.com的IP位址：

[listing]
----
cluster1::*> vserver services name-service getxxbyyy getaddrinfo -vserver vs1 -hostname acast1.eng.example.com -address-family all -show-source true
Source used for lookup: DNS
Host name: acast1.eng.example.com
Canonical Name: acast1.eng.example.com
IPv4: 10.72.8.29
----
下列範例顯示SVM VS1的NIS查詢測試、嘗試擷取使用者的UID 501768使用者資訊：

[listing]
----
cluster1::*> vserver services name-service getxxbyyy getpwbyuid -vserver vs1 -userID 501768 -show-source true
Source used for lookup: NIS
pw_name: jsmith
pw_passwd: $1$y8rA4XX7$/DDOXAvc2PC/IsNFozfIN0
pw_uid: 501768
pw_gid: 501768
pw_gecos:
pw_dir: /home/jsmith
pw_shell: /bin/bash
----
下列範例顯示SVM VS1的LDAP查詢測試、嘗試擷取名稱為LDAP1之使用者的使用者資訊：

[listing]
----
cluster1::*> vserver services name-service getxxbyyy getpwbyname -vserver vs1 -username ldap1 -use-rbac false -show-source true
Source used for lookup: LDAP
pw_name: ldap1
pw_passwd: {crypt}JSPM6yc/ilIX6
pw_uid: 10001
pw_gid: 3333
pw_gecos: ldap1 user
pw_dir: /u/ldap1
pw_shell: /bin/csh
----
下列範例顯示SVM VS1的網路群組查詢測試、嘗試找出用戶端dnshost0是否為netgroup lnetgroup 136的成員：

[listing]
----
cluster1::*> vserver services name-service getxxbyyy netgrp -vserver vs1 -netgroup lnetgroup136 -client dnshost0 -show-source true
Source used for lookup: LDAP
dnshost0 is a member of lnetgroup136
----
. 分析您執行的測試結果、並採取必要行動。
+
[cols="2*"]
|===
| 如果... | 請查看... 


 a| 
主機名稱或IP位址查詢失敗或產生不正確的結果
 a| 
DNS 組態



 a| 
查詢查詢的來源不正確
 a| 
名稱服務交換器組態



 a| 
使用者或群組查詢失敗或產生不正確的結果
 a| 
** 名稱服務交換器組態
** 來源組態（本機檔案、 NIS 網域、 LDAP 用戶端）
** 網路組態（例如、LIF和Routes）




 a| 
主機名稱查詢失敗或逾時、而且DNS伺服器不會解析DNS短名稱（例如host1）
 a| 
頂層網域（頂級域）查詢的DNS組態。您可以使用停用 TLD 查詢 `-is-tld-query-enabled false` 選項 `vserver services name-service dns modify` 命令。

|===


.相關資訊
https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["NetApp技術報告4668：名稱服務最佳實務做法指南"^]
