---
sidebar: sidebar 
permalink: anti-ransomware/enable-arp-ai-with-au.html 
keywords: ransomware, arp, enable, ai, automatic, update, upgrade, autonomous ransomware protection 
summary: 從 ONTAP 9 。 16.1 開始，您可以自動啟用 ARP/AI 以進行 FlexVol 安裝，並啟用 ARP ，或在符合先決條件後手動啟用。 
---
= 使用自動更新來啟用 ONTAP ARP/AI
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9 。 16.1 開始， ARP 採用人工智慧（ ARP/AI ）的自動勒索軟體保護，以改善威脅偵測和回應。將叢集升級至 ONTAP 9 。 16.1 之後，如果已針對這些磁碟區啟用 ARP ，則會自動啟用 FlexVol 磁碟區的 ARP/AI 。如果您尚未啟用 ARP 或未啟用叢集的自動更新，則應遵循本程序中所述的其中一個案例。


IMPORTANT: 升級至 ONTAP 9 之前，請參閱link:../upgrade/arp-warning-clear.html["關閉任何現有的 ARP 偵測"]。

.開始之前
* 您必須有 FlexVol 磁碟區才能使用 ARP/AI 。如果您有 FlexGroup 磁碟區，則在升級至 ONTAP 9 。 16.1 之後， ARP/AI 之前使用的 ARP 模型會繼續運作。



NOTE: 當您升級至 ONTAP 9.16.1 時，會啟用 ARP ，並自動對任何現有的 FlexVol 磁碟區 ARP 執行個體啟用 ARP 。由於 ARP/AI 受過廣泛機器學習模式的訓練，因此不再需要學習期間。任何在升級之前尚未完成的學習期間，都會自動結束，並將磁碟區轉換為使用中的 ARP/AI 。

.步驟
. 請遵循您的組態所特有的案例：
+
** * 對於運行 ONTAP 9 ． 16.1 的新羣集 * ：link:enable-task.html["啟用 ARP"]。預設不會啟用 ARP 。啟用 ARP 之後，您選擇保護的磁碟區上會自動啟用 ARP/AI 功能，並啟用此功能。
** * 對於最近升級到 ONTAP 9 的現有叢集，已啟用 ARP * ：不需要採取任何行動。ARP/AI 將自動成為您選擇保護的 FlexVol 磁碟區上的新 ARP 威脅保護方法。
** * 對於最近升級到 ONTAP 9 的現有叢集，若沒有啟用 ARP * ：link:enable-task.html["啟用 ARP"]。ARP/AI 會在您啟用 ARP 之後，自動成為新的 ARP 威脅保護方法。


. 啟用 ARP/AI 之後，決定是否要傳送和安裝 ARP/AI 保護更新link:arp-ai-automatic-updates.html["自動或手動"]。


.相關資訊
* link:arp-ai-automatic-updates.html["更新 ARP/AI"]

