---
sidebar: sidebar 
permalink: anti-ransomware/enable-task.html 
keywords: anti-ransomware overview, ransomware, security, introduce, protection, detection, threat, attack, suspect, what ontap anti-ransomware detects, entropy, abnormal volume activity, extension conformity, how to recover data in after a ransomware attack, ransomware protection strategy 
summary: 您可以在新的或現有的磁碟區上啟用勒索軟體。您先在學習模式中啟用反勒索軟體、系統會分析工作負載以呈現正常行為、然後切換至主動模式、在該模式中會標示異常活動以供評估。 
---
= 啟用反勒索軟體
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
從ONTAP 功能更新至功能更新至功能更新至功能更新或現有的磁碟區、均可啟用勒索軟體保護功能。您先在學習模式中啟用反勒索軟體、系統會分析工作負載以呈現正常行為、然後切換至主動模式、在該模式中會標示異常活動以供評估。

.您需要的是 #8217 ；需要的是什麼
* 啟用NFS或SMB（或兩者）的儲存VM。
* 已針對ONTAP 您的版本安裝正確的授權。
+
[cols="2*"]
|===
| 發行版ONTAP | 授權 


 a| 
部分9.89.10.1 ONTAP
 a| 
Mt_E_Mgmt（多租戶金鑰管理）



 a| 
更新版本ONTAP
 a| 
anti-勒索 軟體

|===
* 已設定用戶端的NAS工作負載。
* 要保護的磁碟區必須有作用中的交會路徑。
* 選用但建議使用：EMS系統已設定為傳送電子郵件通知、其中包含反勒索軟體活動通知。如需詳細資訊、請參閱 link:../error-messages/configure-ems-events-send-email-task.html["設定EMS事件以傳送電子郵件通知"]。


NetApp反勒索軟體功能包含初始學習期間（也稱為「演習」）、ONTAP 其中一個由VMware系統學習哪些副檔名有效、並使用分析的資料來開發警示設定檔。在學習模式中執行勒索軟體足夠時間來評估工作負載特性之後、您可以切換至作用中模式、並開始保護資料。反勒索軟體繼續收集和分析資料、以精簡警示設定檔。

在學習期間、系統會自動學習已設定Volume的工作負載特性、並執行特殊觀察和模式分析。

建議使用30天的學習期間。雖然您可以隨時從學習模式切換至主動模式、但提早切換可能會導致太多誤報。

在VMware CLI中、您可以使用Security anti-勒索 軟體Volume工作負載行為show命令來顯示目前偵測到的副檔名。ONTAP不過、建議您不要使用此工具來縮短學習期間。

您可以在現有磁碟區上啟用勒索軟體保護、也可以建立新的磁碟區、從頭開始啟用勒索軟體保護。


NOTE: 在現有磁碟區中、學習和作用中模式僅適用於新寫入的資料、而不適用於磁碟區中已存在的資料。因為在啟用Volume的勒索軟體功能之後、會根據新資料來假設先前一般資料流量的特性、因此不會掃描和分析現有資料。

在VMware CLI中、我們引進了新的命令系列來管理這項功能：「安全性反勒索軟體磁碟區」ONTAP 。您也可以使用「volume modify」命令搭配「-anti-勒索 軟體」參數來管理功能。



== System Manager程序

. 按一下「*儲存設備>磁碟區*」、然後選取您要保護的磁碟區。
. 在「Volumes（磁碟區）」總覽的「Security（安全性）」索引標籤中、按一下「* Status（狀態）」、即可在「反勒索軟體」方塊的學習模式中、從「Disabled（已停用）」切換
. 學習期間結束時、請將勒索軟體切換至作用中模式。
+
.. 按一下「*儲存設備>磁碟區*」、然後選取已準備好進入作用中模式的磁碟區。
.. 在「Volumes（磁碟區）」總覽的「Security（安全性）」索引標籤中、按一下「反勒索軟體」方塊中的「* Switch* to active mode（切換*至作用


. 您可以隨時在「反勒索軟體」方塊中驗證Volume的防勒索軟體狀態。若要顯示所有磁碟區的反勒索軟體狀態：在「Volumes（磁碟區）」窗格中、按一下「* Show/Hide*（顯示/隱藏）」、然後確認已核取「反勒索軟體」狀態。




== CLI程序

. 修改現有磁碟區以在學習模式中啟用勒索軟體保護：
+
「安全性防勒索軟體磁碟區乾式執行-volume _vol_name_-vserver _Svm_name_」

+
您也可以使用「volume modify」命令來啟用勒索軟體：

+
「Volume modify -volume _vol_name_-vserver _svm_name_-anti-勒索 軟體狀態drain-run」

+
在CLI中、您也可以在資源配置資料之前、先建立啟用反勒索軟體保護的新磁碟區。

+
「Volume create -volume _vol_name_-vserver _Svm_name_-Aggregate _aggregate _name_-size _n_-anti-勒索 軟體狀態dle-run -jeter-path //path_name_`

+

NOTE: 您應該一開始就在乾燥執行狀態啟用勒索軟體。從使用中狀態開始、可能會導致過多的誤報。

. 當學習期間結束時、請修改受保護的Volume以切換至作用中模式：
+
「安全性防勒索軟體磁碟區可啟用-volume _vol_name_-vserver _svm_name_」

+
您也可以使用modify volume命令切換至作用中模式：

+
「Volume modify -volume _vol_name_-vserver _Svm_name_-anti-勒索 軟體狀態active」

. 驗證磁碟區的勒索軟體狀態。
+
「安全性反勒索軟體量顯示」


