---
sidebar: sidebar 
permalink: anti-ransomware/modify-automatic-shapshot-options-task.html 
keywords: anti-ransomware, automatic Snapshot copy, suspected attack, vserver options command 
summary: 從VMware 9.11.1開始ONTAP 、您可以控制反勒索軟體（ARW）Snapshot複本的數量和保留期間、這些複本會自動產生以回應可疑的勒索軟體攻擊。 
---
= 修改自動Snapshot複本的選項
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
從VMware 9.11.1開始ONTAP 、您可以控制反勒索軟體（ARW）Snapshot複本的數量和保留期間、這些複本會自動產生以回應可疑的勒索軟體攻擊。

*附註*：「vserver options」命令為隱藏命令。若要檢視手冊頁、請在ONTAP CLI輸入「man vserver options」。

下列自動Snapshot複本選項可供修改：

ARW.snap.max.count:: 指定在任何指定時間內、磁碟區中可存在的ARW Snapshot複本數目上限。刪除較舊的複本、以確保ARW Snapshot複本的總數符合此指定限制。
arw.snap.create.interval.hours:: 指定ARW Snapshot複本之間的時間間隔（以小時為單位）。如果懷疑有攻擊、而且先前建立的複本早於指定的時間間隔、就會建立新的Snapshot複本。
arw.snap.normal.retain.interval.hours:: 指定保留ARW Snapshot複本的持續時間（小時）。當ARW Snapshot複本變成舊版本時、會刪除在最新複本之前建立的任何其他ARW Snapshot複本、以達到此年齡。沒有任何ARW Snapshot複本可以超過此持續時間。
arw.snap.max.retain.interval.days:: 指定可保留ARW Snapshot複本的最長持續時間（以天為單位）。如果磁碟區上未報告任何攻擊、則會刪除任何早於此期間的ARW Snapshot複本。
arw.snap.create.interval.hours.post.max.count:: 指定當磁碟區已包含ARW Snapshot複本的最大數量時、ARW Snapshot複本之間的時間間隔（以小時為單位）。當達到最大數量時、將會刪除ARW Snapshot複本、以保留新複本的空間。使用此選項可降低新的ARW Snapshot複本建立速度、以保留舊版複本。如果磁碟區已包含ARW Snapshot複本的最大數量、則此選項中指定的時間間隔將用於下一次建立ARW Snapshot複本、而非arw.snap.create.interval.hours。
arw.surge.snap.interval.days:: 指定ARW突增Snapshot複本之間的時間間隔（以天為單位）。當IO流量激增、且上次建立的ARW Snapshot複本早於此指定時間間隔時、就會建立新的ARW Snapshot突波複本。此選項也會指定保留ARW突波Snapshot複本的持續時間（以天為單位）。




== CLI程序

若要顯示所有目前的ARW Snapshot複本設定、請輸入：「vserver options -vserver _svm_name_arw*」

若要顯示所選的目前ARW Snapshot複本設定、請輸入：「vserver options -vserver _Svm_name_-option-name _arw_setting_name_」

若要修改ARW Snapshot複本設定、請輸入：「vserver options -vserver _Svm_name_-option-name _arw_setting_name_-option-value _arw_setting_value_`
