---
sidebar: sidebar 
permalink: anti-ransomware/modify-automatic-shapshot-options-task.html 
keywords: anti-ransomware, automatic Snapshot copy, suspected attack, vserver options, autonomous ransomware protection, arp 
summary: 修改自動勒索軟體保護 Snapshot 複本的設定、這些複本會自動產生、以因應可疑的勒索軟體攻擊。 
---
= 修改自動Snapshot複本的選項
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
從 ONTAP 9.11.1 開始、您可以使用 CLI 來控制自動產生的勒索軟體保護（ ARP ） Snapshot 複本數量和保留期、以因應可疑的勒索軟體攻擊。



== 可修改的 Snapshot 選項

下列自動Snapshot複本選項可供修改：

ARW.snap.max.count:: 指定在任何指定時間內、磁碟區中可存在的最大ARP Snapshot複本數。系統會刪除較舊的複本、以確保「ARP Snapshot複本」的總數達到此指定限制。
arw.snap.create.interval.hours:: 指定「ARP Snapshot複本」之間的時間間隔（以小時為單位）。如果懷疑有攻擊、而且先前建立的複本早於指定的時間間隔、就會建立新的Snapshot複本。
arw.snap.normal.retain.interval.hours:: 指定保留一份「ARP Snapshot複本」的持續時間（以小時為單位）。當某個「ARP Snapshot複本」變舊時、會刪除在最新複本之前建立的任何其他「ARP Snapshot複本」複本、以達到此年齡。任何一個「ARP Snapshot複本」都不能超過此持續時間。
arw.snap.max.retain.interval.days:: 指定可保留一份「ARP Snapshot複本」的最長持續時間（以天為單位）。如果磁碟區上未報告任何攻擊、則會刪除此期間之前的任何「ARP Snapshot複本」。



NOTE: 如果偵測到中度威脅、就會忽略 ARP Snapshot 的最大保留時間間隔。在威脅發生之前建立的 Snapshot 會一直保留、直到威脅被標示為誤報。一旦標記為誤報、磁碟區上的所有其他 ARP 快照也會刪除。

arw.snap.create.interval.hours.post.max.count:: 指定當磁碟區已包含最大數量的Arp Snapshot複本時、每個Arp Snapshot複本之間的時間間隔（以小時為單位）。當達到最大數量時、系統會刪除一個「ARP Snapshot複本」、以便為新的複本預作空間。使用此選項可降低新的「ARP Snapshot複本」複本建立速度、以保留舊版複本。如果該磁碟區已包含最大數量的Arp Snapshot複本、則此選項中指定的時間間隔將用於下一次建立Arp Snapshot複本、而非arw.snap.create.interval.hours。
arw.surge.snap.interval.days:: 指定每個ARP突波Snapshot複本之間的時間間隔（以天為單位）。當IO流量激增、且上次建立的Arp Snapshot複本早於指定的時間間隔時、就會建立新的「Arp Snapshot突波複本」。此選項也會指定保留「ARP突波Snapshot複本」的持續時間（以天為單位）。




== CLI 命令

您只能修改節點 SVM 上的選項。


NOTE: 。 `vserver options` 命令是隱藏的命令。若要檢視手冊頁、請輸入 `man vserver options` 在 ONTAP CLI 中。

若要顯示所有目前的 ARP Snapshot 複本設定、請輸入：
`vserver options -vserver _svm_name_ arw*`

若要顯示選取的目前 ARP Snapshot 複本設定、請輸入：
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_`

若要修改 ARP Snapshot 複本設定、請輸入：
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_ -option-value _arw_setting_value_`
