---
sidebar: sidebar 
permalink: anti-ransomware/modify-automatic-shapshot-options-task.html 
keywords: anti-ransomware, automatic Snapshot copy, suspected attack, vserver options, autonomous ransomware protection, arp 
summary: 修改自動勒索軟體保護 Snapshot 複本的設定、這些複本會自動產生、以因應可疑的勒索軟體攻擊。 
---
= 修改自動Snapshot複本的選項
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
從 ONTAP 9.11.1 開始、您可以使用 CLI 來控制自動勒索軟體保護（ ARP ） Snapshot 複本的保留設定、這些複本會自動產生、以因應可疑的勒索軟體攻擊。

.開始之前
您只能修改節點 SVM 上的 ARP Snapshots 選項。

.步驟
. 若要顯示所有目前的 ARP Snapshot 複本設定、請輸入：
`vserver options -vserver _svm_name_ arw*`
+

NOTE: 。 `vserver options` 命令是隱藏的命令。若要檢視手冊頁、請輸入 `man vserver options` 在 ONTAP CLI 中。

. 若要顯示選取的目前 ARP Snapshot 複本設定、請輸入：
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_`
. 若要修改 ARP Snapshot 複本設定、請輸入：
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_ -option-value _arw_setting_value_`
+
可修改下列設定：

+
[cols="1,3"]
|===
| ARW 設定 | 說明 


| * arw.snap.max.count* | 指定在任何指定時間內、磁碟區中可存在的最大ARP Snapshot複本數。系統會刪除較舊的複本、以確保「ARP Snapshot複本」的總數達到此指定限制。 


| * arw.snap.create.interval.hours* | 指定 ARP Snapshot 複本之間的時間間隔（以小時計）。當懷疑有攻擊時會建立新的 Snapshot 複本、而先前建立的複本早於此指定時間間隔。 


| * arw.snap.normal.retain.interval.hours* | 指定保留 ARP Snapshot 複本的持續時間（以小時計）。當某個「ARP Snapshot複本」變舊時、會刪除在最新複本之前建立的任何其他「ARP Snapshot複本」複本、以達到此年齡。任何一個「ARP Snapshot複本」都不能超過此持續時間。 


| * arw.snap.max.retain.interval.days*  a| 
指定可以保留 ARP Snapshot 複本的最長持續時間（以天為單位）。如果磁碟區上未報告任何攻擊、則會刪除此期間之前的任何「ARP Snapshot複本」。

+


NOTE: 如果偵測到中度威脅、就會忽略 ARP Snapshot 複本的最大保留時間間隔。針對威脅所建立的 ARP Snapshot 複本會保留、直到您回應威脅為止。將威脅標示為誤報、刪除磁碟區上的 ARP Snapshot 複本。



| * arw.snap.create.interval.hours.post.max.count* | 指定當磁碟區已包含最大 ARP Snapshot 複本數時、每個 ARP Snapshot 複本之間的時間間隔（以小時為單位）。當達到最大數量時、系統會刪除一個「ARP Snapshot複本」、以便為新的複本預作空間。使用此選項可降低新的「ARP Snapshot複本」複本建立速度、以保留舊版複本。如果該磁碟區已包含最大數量的Arp Snapshot複本、則此選項中指定的時間間隔將用於下一次建立Arp Snapshot複本、而非arw.snap.create.interval.hours。 


| * arw.surge.snap.interval.days* | 指定 ARP 突波 Snapshot 複本之間的間隔（以天為單位）。當 IO 流量激增且上次建立的 ARP Snapshot 複本早於此指定時間間隔時、 ONTAP 會建立 ARP Snapshot 突波複本。此選項也會指定 ARP 喘振快照的保留期間（以天為單位）。 
|===

