---
sidebar: sidebar 
permalink: anti-ransomware/modify-automatic-snapshot-options-task.html 
keywords: anti-ransomware, automatic Snapshot copy, suspected attack, vserver options, autonomous ransomware protection, arp 
summary: 修改自動勒索軟體保護 Snapshot 複本的設定、這些複本會自動產生、以因應可疑的勒索軟體攻擊。 
---
= 修改自動Snapshot複本的選項
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
從 ONTAP 9.11.1 開始、您可以使用 CLI 來控制自動勒索軟體保護（ ARP ） Snapshot 複本的保留設定、這些複本會自動產生、以因應可疑的勒索軟體攻擊。

.開始之前
您只能修改節點 SVM 上的 ARP Snapshots 選項。

.步驟
. 若要顯示所有目前的 ARP Snapshot 複本設定、請輸入：
`vserver options -vserver _svm_name_ arw*`
+

NOTE: 。 `vserver options` 命令是隱藏的命令。若要檢視手冊頁、請輸入 `man vserver options` 在 ONTAP CLI 中。

. 若要顯示選取的目前 ARP Snapshot 複本設定、請輸入：
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_`
. 若要修改 ARP Snapshot 複本設定、請輸入：
`vserver options -vserver _svm_name_ -option-name _arw_setting_name_ -option-value _arw_setting_value_`
+
可修改下列設定：

+
[cols="1,3"]
|===
| ARW 設定 | 說明 


| `arw.snap.max.count`  a| 
指定在任何指定時間內、磁碟區中可存在的最大ARP Snapshot複本數。系統會刪除較舊的複本、以確保「ARP Snapshot複本」的總數達到此指定限制。
。 `-option-value` 參數接受介於 3 和 8 之間的整數（含 3 和 8 ）。預設值為 6 。



| `arw.snap.create.interval.hours`  a| 
指定 ARP Snapshot 複本之間的時間間隔（以小時計）。當懷疑資料 Entropy 型攻擊、且最近建立的 ARP Snapshot 複本早於指定時間間隔時、就會建立新的 ARP Snapshot 複本。
。 `-option-value` 參數接受 1 到 48 之間的整數（含 1 到 48 ）。預設值為 4 。



| `arw.snap.normal.retain.interval.hours`  a| 
指定保留 ARP Snapshot 複本的持續時間（以小時計）。當 ARP Snapshot 複本達到保留臨界值時、會在刪除之前建立任何其他 ARP Snapshot 複本。超過保留臨界值的 ARP Snapshot 複本不可能有多個。
。 `-option-value` 參數接受介於 4 到 96 之間的整數（含 4 到 96 ）。預設值為 48 。



| `arw.snap.max.retain.interval.days`  a| 
指定可以保留 ARP Snapshot 複本的最長持續時間（以天為單位）。如果磁碟區未回報任何攻擊、則會刪除任何早於此持續時間的 ARP Snapshot 複本。


NOTE: 如果偵測到中度威脅、就會忽略 ARP Snapshot 複本的最大保留時間間隔。針對威脅所建立的 ARP Snapshot 複本會保留、直到您回應威脅為止。將威脅標示為誤報、刪除磁碟區上的 ARP Snapshot 複本。
。 `-option-value` 參數接受 1 到 365 之間的整數（含 1 到 365 ）。預設值為 5 。



| `arw.snap.create.interval.hours.post.max.count`  a| 
指定當磁碟區已包含最大 ARP Snapshot 複本數時、每個 ARP Snapshot 複本之間的時間間隔（以小時為單位）。當達到最大數量時、系統會刪除一個「ARP Snapshot複本」、以便為新的複本預作空間。使用此選項可降低新的「ARP Snapshot複本」複本建立速度、以保留舊版複本。如果磁碟區已包含 ARP Snapshot 複本的最大數量、則此選項中指定的時間間隔將用於下一次建立 ARP Snapshot 複本、而非 `arw.snap.create.interval.hours`。
。 `-option-value` 參數接受 4 到 48 之間的整數（含 4 到 48 ）。預設值為 8 。



| `arw.surge.snap.interval.days`  a| 
指定為回應 IO 突波而建立的 ARP Snapshot 複本之間的間隔（以天為單位）。當 IO 流量激增且上次建立的 ARP Snapshot 複本早於此指定時間間隔時、 ONTAP 會建立 ARP Snapshot 突波複本。此選項也會指定 ARP 喘振 Snapshot 複本的保留期間（以天為單位）。
。 `-option-value` 參數接受 1 到 365 之間的整數（含 1 到 365 ）。預設值為 5 。



| `arw.snap.new.extns.interval.hours`  a| 
此選項指定偵測到新副檔名時所建立的 ARP Snapshot 複本之間的時間間隔（小時）。新的 ARP Snapshot 複本會在何時建立
會觀察到新的副檔名；觀察到新副檔名時所建立的上一個 Snapshot 會比這個指定的時間間隔還要舊。在經常建立新副檔名的工作負載上、此時間間隔有助於控制 ARP Snapshot 複本的頻率。此選項不受影響 `arw.snap.create.interval.hours`，指定資料 Entropy 型 ARP Snapshot 複本的時間間隔。
。 `-option-value` 參數接受介於 24 和 8760 之間的整數。預設值為 48 。

|===

