---
sidebar: sidebar 
permalink: anti-ransomware/respond-abnormal-task.html 
keywords: Respond to abnormal activity, anti-ransomware abnormal activity, data entropy, unusual file extensions, potential ransomware attack, false positive, suspected ransomware attack, abnormal activity notification, security, ransomware alert message, detected abnormal volume, suspected file types, attack report, anti-ransomware attack 
summary: 當反勒索軟體偵測到受保護Volume中的異常活動時、就會發出警告。您應該評估通知、以判斷活動是否預期且可接受、或是攻擊是否正在進行。 
---
= 回應異常活動。
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
當反勒索軟體偵測到受保護Volume中的異常活動時、就會發出警告。您應該評估通知、以判斷活動是否預期且可接受、或是攻擊是否正在進行。

.您的需求
* 反勒索軟體正在作用中模式中執行。


當反勒索軟體偵測到高資料Entropy、異常Volume活動與資料加密、以及異常檔案副檔名的任何組合時、會顯示可疑檔案的清單。

發出警告時、您可以透過下列兩種方式之一來標記檔案活動：

* 誤判
+
識別的檔案類型應在您的工作負載中使用、而且可以忽略。

* 可能的勒索軟體攻擊
+
識別出的檔案類型在您的工作負載中是非預期的、應該視為潛在攻擊。



在這兩種情況下、正常監控會在更新及清除通知後恢復；反勒索軟體會記錄您的評估、以新檔案類型更新記錄、並使用這些記錄進行未來分析。不過、若發生可疑的攻擊、您必須先判斷是否為攻擊、如果是攻擊、請加以回應、然後在清除通知之前還原受保護的資料。如需詳細資訊、請參閱 link:index.html#how-to-recover-data-in-ontap-after-a-ransomware-attack["如何從勒索軟體攻擊中恢復"]。



== System Manager程序

. 當您收到「異常活動」通知時、請按一下連結、或瀏覽至* Volumes *總覽的* Security（安全性）*標籤。
+
警告會顯示在「事件」視窗的「總覽」窗格中。

. 顯示「偵測到異常Volume活動」訊息時、請檢視可疑檔案。
+
在「*安全性*」索引標籤中、按一下「檢視*可疑的檔案類型*」。

. 在「*可疑的檔案類型*」對話方塊中、檢查每種檔案類型、並將其標示為「誤判」或「潛在勒索軟體攻擊」。


[cols="25,75"]
|===


| 如果您選取此值... | 請採取此行動… 


| 誤判 | 按一下「*更新*」和「*清除可疑的檔案類型*」以記錄您的決策、並恢復正常的勒索軟體監控。 


| 可能的勒索軟體攻擊 | 回應攻擊並還原受保護的資料。然後按一下*更新*和*清除可疑的檔案類型*、以記錄您的決策、並恢復正常的勒索軟體監控。 
|===


== CLI程序

. 當您收到可疑勒索軟體攻擊的通知時、請確認攻擊的時間和嚴重性：
+
「安全性防勒索軟體Volume show -vserver _svm_name_-volume _vol_name_」

+
範例輸出：

+
....
Vserver Name: vs0
Volume Name: vol1
State: enabled
Attack Probability: moderate
Attack Timeline: 9/14/2021 01:03:23
Number of Attacks: 1
....
+
您也可以檢查EMS訊息：

+
「事件記錄檔顯示-message-name callhome.arw.activity.seen`

. 產生攻擊報告並記下輸出位置：
+
「安全性反勒索軟體磁碟區攻擊會產生報告-volume _vol_name_-dest-path _file_port_/」

+
範例輸出：

+
「Report "report_file_vs0_vol1_14-09-2021_01-21-08"（報告「report_file_vs0_vol1_14-09-2021_08-08」）、可在路徑「vs0：vol1/」取得

. 在管理用戶端系統上檢視報告。例如：
+
....
[root@rhel8 mnt]# cat report_file_vs0_vol1_14-09-2021_01-21-08

19  "9/14/2021 01:03:23"   test_dir_1/test_file_1.jpg.lckd
20  "9/14/2021 01:03:46"   test_dir_2/test_file_2.jpg.lckd
21  "9/14/2021 01:03:46"   test_dir_3/test_file_3.png.lckd`
....
. 根據您對副檔名的評估、採取下列其中一項行動：
+
** 誤判
+
輸入下列命令以記錄您的決定：將新的副檔名新增至允許的清單、並恢復正常的反勒索軟體監控：「反勒索軟體Volume攻擊清除可疑的-vserver _Svm_name_-volume _vol_name_[_exteNids__-falge-true]

+
使用下列參數之一來識別副檔名：可疑清單中檔案的「[-seq-no _integer_]」序號。[`-exte_text_,… 檔案副檔名為「mm/DD/YYYY hh：mm:SS」、格式為「-start-time_time_-tend-time_]、檔案範圍的開始和結束時間。

** 可能的勒索軟體攻擊
+
回應攻擊並還原資料。然後輸入下列命令、記錄您的決定並恢復正常的勒索軟體監控：

+
「反勒索軟體磁碟區攻擊清除可疑的-vserver _Svm_name_-volume _vol_name_[_extension identids_]-假 正假」

+
使用下列參數之一來識別副檔名：可疑清單中檔案的「[-seq-no _integer_]順序編號「[-extension_text_、…」 檔案副檔名為「mm/DD/YYYY hh：mm:SS」、「開始時間_date時間_-結束時間_date時間_」、格式為「mm/DD/YYYY hh：MM：SS」。




