---
sidebar: sidebar 
permalink: anti-ransomware/switch-learning-to-active-mode.html 
keywords: ransomware, arp, mode, switch, active, learning, autonomous ransomware protection 
summary: 對於 NAS 環境中的 ARP 9.15.1 及更早版本，手動或自動將啟用 ARP 的捲從學習模式切換到活動模式。 
---
= 在學習期間之後，在 ONTAP ARP 中切換至作用中模式
:allow-uri-read: 


[role="lead"]
對於 NAS 環境，手動或自動將啟用 ARP 的磁碟區從學習模式切換到活動模式。如果您在ONTAP 9.15.1 及更早版本中使用 ARP，或在ONTAP 9.17.1 及更早版本的FlexGroup區上執行 ARP，則需要切換模式。

ARP 完成建議至少 30 天的學習模式運作後，您可以手動切換到活動模式。從ONTAP 9.13.1 開始，ARP 會自動確定最佳學習週期間隔並自動切換，切換可能在 30 天之前發生。

如果您將 ARP 與 ARP/AI 保護結合使用，則 ARP 會自動啟動。無需學習期。


NOTE: 在現有的磁碟區中、學習和作用中模式僅適用於新寫入的資料、而不適用於磁碟區中現有的資料。不會掃描和分析現有資料、因為在啟用Volume以進行Arp之後、會根據新資料來假設先前一般資料流量的特性。



== 在學習期間後手動切換至使用中模式

對於ONTAP 9.10.1 至 9.15.1（ONTAP 9.17.1 及更早版本，帶FlexGroup卷），學習期結束後，您可以使用系統管理器或ONTAP CLI 手動將 ARP 學習模式轉換為活動模式。

.關於這項工作
本過程中所描述的學習期後手動過渡到主動模式特定於 NAS 環境。

.步驟
您可以使用系統管理員或ONTAP CLI 從學習模式切換到主動模式。

[role="tabbed-block"]
====
.系統管理員
--
. 選取 * 儲存 > 磁碟區 * 、然後選取已準備好用於作用中模式的磁碟區。
. 在 * Volumes * （卷）總覽的 * Security （安全性） * 標籤中，在 Anti-勒索 軟體方塊中選取 * Switch to active mode* （切換至作用中模式）。
. 您可以在 * 反勒索軟體 * 方塊中驗證磁碟區的 ARP 狀態。


--
.CLI
--
. 如果尚未自動完成，則修改受保護的磁碟區以切換到活動模式：
+
[source, cli]
----
security anti-ransomware volume enable -volume <vol_name> -vserver <svm_name>
----
+
您也可以使用modify volume命令切換至作用中模式：

+
[source, cli]
----
volume modify -volume <vol_name> -vserver <svm_name> -anti-ransomware-state enabled
----
. 驗證磁碟區的ARP狀態。
+
[source, cli]
----
security anti-ransomware volume show
----


--
====


== 自動從學習模式切換至使用中模式

從ONTAP 9.13.1 開始，自適應學習已新增至 ARP 分析中，並且可以自動從學習模式切換到主動模式。 ARP自動從學習模式切換到主動模式的自主決策基於以下選項的配置設定：

[listing]
----
 -anti-ransomware-auto-switch-minimum-incoming-data-percent
 -anti-ransomware-auto-switch-duration-without-new-file-extension
 -anti-ransomware-auto-switch-minimum-learning-period
 -anti-ransomware-auto-switch-minimum-file-count
 -anti-ransomware-auto-switch-minimum-file-extension
----
如果啟用自動切換功能，即使未滿足所有條件，磁碟區也會在最多 30 天後自動切換到活動模式。此 30 天的限制是固定的，無法更改。

如需 ARP 組態選項（包括預設值）的詳細資訊、請參閱 link:https://docs.netapp.com/us-en/ontap-cli/security-anti-ransomware-volume-auto-switch-to-enable-mode-show.html["指令參考資料ONTAP"^]。

.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+anti-ransomware+volume["安全反勒索軟體量"^]

