---
sidebar: sidebar 
permalink: anti-ransomware/use-cases-restrictions-concept.html 
keywords: anti-ransomware workloads, anti-ransomware requirements, anti-ransomware performance, volumes, anti-ransomware encryption, anti-ransomware system configurations, arp 
summary: 在目前的版本中、勒索軟體保護最適合NAS環境。未來版本將提供對其他環境的支援。 
---
= 自主勒索軟體保護的使用案例和考量
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
自主勒索軟體保護功能的可用度取決於您使用的 ONTAP 版本。



== 支援和不支援的組態

支援的平台：ONTAP

* 所有內部部署ONTAP 的VMware系統從ONTAP 版本號9.10.1開始、都可使用「自發勒索軟體保護（Arp）」功能。


適合的工作負載：

* NFS儲存設備上的資料庫
* Windows或Linux主目錄
+
由於使用者可以建立在學習期間未偵測到的副檔名檔案、因此此工作負載更有可能發生誤報。

* 影像與影片
+
例如、醫療記錄和電子設計自動化（EDA）資料。



從ONTAP 功能完整的版本9.12.1開始、下列組態均可使用Arp：

* 受SnapMirror保護的磁碟區
* SnapMirror保護SVM
* 已啟用移轉的SVM（SVM資料移動性）


不適當的工作負載：

* 檔案建立或刪除頻率高的工作負載（數秒內有數十萬個檔案、例如測試/開發工作負載）
* ARP 取決於辨識檔案建立、重新命名或刪除活動中異常激增的能力。如果應用程式本身是檔案活動的來源、就無法有效區分它與勒索軟體活動
* 應用程式或主機加密資料Arp的工作負載、取決於將傳入資料區分為加密或未加密。如果應用程式本身正在加密資料、則此功能的有效性將會降低。不過、此功能仍可根據檔案活動（刪除、覆寫或建立、或以新副檔名建立或重新命名）和檔案類型運作。


不支援的系統組態：

* SAN環境
* 不支援的S3環境ONTAP
* NFS上的VMDK


Volume需求：

* 容量不足100%
* 交會路徑必須為作用中


不支援的Volume類型：

* 離線磁碟區
* 受限磁碟區
* 資料量SnapLock
* FlexGroup Volume （從 ONTAP 9.13.1 開始、支援 FlexGroup Volume ）
* FlexCache Volume （原始 FlexVol 磁碟區支援 ARP 、快取磁碟區則不支援）
* 純SAN磁碟區
* 已停止儲存VM的磁碟區
* 儲存VM的根磁碟區




== SnapMirror與ARP互通性

從ONTAP 功能支援的版本為2。9.12開始、SnapMirror目的地磁碟區支援使用Arp。如果SnapMirror來源磁碟區已啟用Arp、SnapMirror目的地磁碟區會自動取得來源磁碟區的Arp組態狀態（學習、啟用等）、Arp訓練資料、以及由Arp建立的Snapshot快照。不需要明確啟用。

雖然目的地Volume是由唯讀（RO）Snapshot複本所組成、但不會對其資料進行任何ARP處理。不過、當SnapMirror目的地Volume轉換為讀寫（RW）時、會自動在RW-轉換的目的地Volume上啟用ARP。除了已記錄在來源Volume上的內容、目的地Volume不需要任何額外的學習程序。

在版本號9.10.1和9.11.1中ONTAP 、SnapMirror不會將Arp組態狀態、訓練資料和Snapshot複本從來源磁碟區傳輸到目的地磁碟區。因此、當SnapMirror目的地Volume轉換為RW時、在轉換後、必須在學習模式中明確啟用目的地Volume上的ARP。



== ARP效能和頻率考量

以處理量和尖峰IOPS來衡量、ARP功能對系統效能的影響最小。ARP 功能的影響與 Volume 工作負載有很大的影響。對於大多數一般或一般工作負載、建議使用下列組態限制：

[cols="30,20,30"]
|===
| 工作負載特性 | 每個節點的建議Volume限制 | 超過每節點磁碟區限制時效能降低：[*] 


| 讀取密集或資料可以壓縮。 | 150 | 最高IOPS的4% 


| 寫入密集、資料無法壓縮。 | 60 | IOPS上限的10% 
|===
通過：[*]無論新增的磁碟區數量超過建議的限制、系統效能不會超過這些百分比。

由於根據優先順序執行Arp分析、當受保護的磁碟區數量增加時、分析作業就會減少在每個磁碟區上執行的頻率。



== 使用受自動勒索軟體保護（ ARP ）保護的磁碟區進行多重管理驗證

從 ONTAP 9.13.1 開始、您可以啟用多重管理驗證（ MAV ）、以提高 ARP 的安全性。MAV 可確保至少有兩位或多位通過驗證的系統管理員必須關閉 ARP 、暫停 ARP 、或將可疑攻擊標示為受保護磁碟區上的誤報。瞭解操作方法 link:../multi-admin-verify/enable-disable-task.html["為受 ARP 保護的磁碟區啟用 MAV"^]。

您需要定義 MAV 群組的管理員、並為建立 MAV 規則 `security anti-ransomware volume disable`、 `security anti-ransomware volume pause`和 `security anti-ransomware volume attack clear-suspect` 您要保護的 ARP 命令。MAV 群組中的每位管理員都必須核准每個新的規則要求和 link:../multi-admin-verify/enable-disable-task.html["再次新增 MAV 規則"^] 在 MAV 設定中。
