---
sidebar: sidebar 
permalink: anti-ransomware/use-cases-restrictions-concept.html 
keywords: anti-ransomware use cases and restrictions, anti-ransomware performance and frequency considerations, anti-ransomware workloads, anti-ransomware volume requirements, anti-ransomware performance, volumes, anti-ransomware encryption, anti-ransomware system configurations, autonomous ransomware protection, arp 
summary: 在目前的版本中、勒索軟體保護最適合NAS環境。未來版本將提供對其他環境的支援。 
---
= 自主勒索軟體保護的使用案例和考量
:toc: macro
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toc: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/
:toc-position: content


[role="lead"]
支援的平台：ONTAP

* 所有內部部署ONTAP 的VMware系統從ONTAP 版本號9.10.1開始、都可使用「自發勒索軟體保護（Arp）」功能。
* 此功能不適用於Cloud Volumes ONTAP 任何環境。


適合的工作負載：

* NFS儲存設備上的資料庫
* Windows或Linux主目錄
+
因為使用者可以建立在學習期間未偵測到副檔名的檔案、因此這項工作負載可能會有更多誤判的可能性。

* 影像與影片
+
例如、醫療記錄和電子設計自動化（EDA）資料。



不適當的工作負載：

* 檔案建立或刪除頻率高的工作負載（數秒內有數十萬個檔案、例如測試/開發工作負載）
* ARP取決於辨識檔案建立或刪除活動中異常激增的能力。如果應用程式本身是檔案活動的來源、就無法有效區分它與勒索軟體活動
* 應用程式或主機加密資料Arp的工作負載、取決於將傳入資料區分為加密或未加密。如果應用程式本身正在加密資料、則此功能的有效性將會降低。不過、此功能仍可根據檔案活動（建立、刪除及覆寫）和檔案類型來運作。


不支援的系統組態：

* SAN環境
* 不支援的S3環境ONTAP
* NFS上的VMDK


Volume需求：

* 容量不足100%
* 交會路徑必須為作用中


不支援的Volume類型：

* 離線磁碟區
* 受限磁碟區
* 資料量SnapLock
* 資料量FlexGroup
* 支援的資料區（來源地的不支援勒索軟體功能、但不支援快取磁碟區）FlexCache FlexVol
* 純SAN磁碟區
* 已停止儲存VM的磁碟區
* 儲存VM的根磁碟區
* 資料保護磁碟區




== ARP效能和頻率考量

以處理量和尖峰IOPS來衡量、ARP功能對系統效能的影響最小。反勒索軟體功能的影響、高度取決於Volume工作負載。對於大多數一般或一般工作負載、建議使用下列組態限制：

[cols="30,20,30"]
|===
| 工作負載特性 | 每個節點的建議Volume限制 | 超過每節點磁碟區限制時效能降低：[*] 


| 讀取密集或資料可以壓縮。 | 150 | 最高IOPS的4% 


| 寫入密集、資料無法壓縮。 | 60 | IOPS上限的10% 
|===
通過：[*]無論新增的磁碟區數量超過建議的限制、系統效能不會超過這些百分比。

由於根據優先順序執行Arp分析、當受保護的磁碟區數量增加時、分析作業就會減少在每個磁碟區上執行的頻率。



== 偵測到勒索軟體時、自動Snapshot複本的運作方式

為了獲得最佳的恢復點、當發現異常檔案活動時、Arp會盡快建立自動Snapshot複本。不過、Arp並不會立即標記警示、而是需要執行分析、確認可疑活動符合勒索軟體設定檔、才能產生警示。此程序可能需要60分鐘。如果分析判斷活動並不可疑、則不會產生警示、但自動建立的Snapshot複本會在檔案系統上保留至少兩天。

從ONTAP VMware 9.11.1開始、您可以控制因應可疑勒索軟體攻擊而自動產生的「ARP Snapshot複本」數量和保留期間。瞭解操作方法 link:modify-automatic-shapshot-options-task.html["修改自動Snapshot複本的選項"]。
