---
sidebar: sidebar 
permalink: snapmirror-active-sync/index.html 
keywords: SM-BC, SMBC, failover, terms, benefits, snapmirror active sync, TR-4878 
summary: 使用 SnapMirror 主動式同步功能來保護應用程式與 LUN 、讓應用程式能以透明方式容錯移轉、確保在發生災難時營運不中斷。 
---
= 了解ONTAP SnapMirror主動同步
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
SnapMirror主動同步，也稱為SnapMirror業務連續性 (SM-BC)，可讓業務服務在整個網站發生故障時繼續運作。該技術使應用程式能夠無縫地故障轉移到輔助副本，而無需人工幹預或自訂腳本。

NetApp SnapMirror主動同步 (SM-as) 旨在提供更細微、更低成本、更易於使用的應用程式層級保護，並具有自動故障轉移功能。 SnapMirror主動同步使關鍵任務業務服務即使在整個站點發生故障時也能繼續運作。借助SnapMirror主動同步，您現在可以在不同地理位置的網站之間同步複製應用程式的多個磁碟區（透過將它們新增至一致性群組）。當主副本發生中斷時，您可以自動故障轉移到輔助副本，從而實現第一層應用程式的業務連續性。

一些國家針對金融機構的規定要求企業定期從其二級資料中心提供服務。  SnapMirror主動同步及其高可用性叢集可實現這些資料中心切換，從而實現業務連續性。

從ONTAP 9.9.1 開始， SnapMirror主動同步在AFF和全快閃 SAN 陣列 (ASA) 叢集上支援。主群集和輔助群集必須是同一種類型： ASA、 ASA r2 或AFF。  SnapMirror主動同步使用 iSCSI 或 FCP LUN 或 NVMe 命名空間保護應用程式。

SnapMirror主動同步支援對稱和非對稱配置。 ONTAP 9.15.1 中引入了對對稱主動/主動的支援。對稱主動/主動配置允許受保護 LUN 的兩個副本透過雙向同步複製執行讀寫 I/O 操作，從而使每個 LUN 副本能夠滿足本地 I/O 請求。


NOTE: 自 2024 年 7 月起、先前以 PDF 格式發佈的技術報告內容已與 ONTAP 產品文件整合。ONTAP SnapMirror 主動式同步文件現在包含來自 _TR-4878 的內容： SnapMirror 主動式同步。



== 效益

SnapMirror 主動式同步提供下列優點：

* 業務關鍵應用程式的持續可用度。
* 能夠從主要和次要站台交替主控關鍵應用程式。
* 使用一致性群組來簡化應用程式管理、以確保依寫入順序的一致性。
* 測試每個應用程式的容錯移轉功能。
* 即時建立鏡射複本、不會影響應用程式可用度。
* 能夠在同一個 ONTAP 叢集中部署受保護和不受保護的工作負載。
* LUN、NVMe 命名空間、NVMe 子系統或儲存單元身分保持不變，因此應用程式將它們視為共用虛擬裝置。
* 能夠靈活地重複使用次叢集、為開發測試、 UAT 或報告用途建立即時複本、而不影響應用程式效能或可用度。


SnapMirror主動同步功能可保護您的資料 LUN 或 NVMe 命名空間，使應用程式能夠透明地進行故障轉移，從而在災難發生時保持業務連續性。有關更多信息，請參閱link:use-cases-concept.html["使用案例"] 。



== 主要概念

SnapMirror主動同步使用一致性群組來確保您的資料被複製。 SnapMirror主動同步使用ONTAP Mediator，或從ONTAP 9.17.1 開始使用 Cloud Mediator 進行自動故障轉移，確保在災難發生時能夠提供資料。在規劃SnapMirror主動同步部署時，請務必了解SnapMirror主動同步及其架構中的基本概念。

.不對稱性和對稱性
在對稱主動/主動配置中，兩個站點均可存取本地儲存以進行主動 I/O。對稱主動/主動配置針對叢集應用程式進行了最佳化，包括 VMware vMSC、Windows 故障轉移叢集（含 SQL）以及 Oracle RAC。

在非對稱主動/主動配置中，輔助站點上的資料被代理到 LUN、命名空間或儲存單元。

如需詳細資訊、請參閱 xref:architecture-concept.html[SnapMirror 主動同步架構]。

.一致性群組
對於AFF和ASA系統link:../consistency-groups/index.html["一致性群組"]是FlexVol磁碟區的集合，為必須保護以確保業務連續性的應用程式工作負載提供一致性保證。在ASA r2 系統中，一致性群組是儲存單元的集合。

一致性組的目的是同時對磁碟區或儲存單元集合進行快照，從而確保在某個時間點集合的崩潰一致性副本。一致性組確保資料集的所有磁碟區都處於靜止狀態，然後在同一時間點進行快照。這為支援資料集的磁碟區或儲存單元提供了資料一致的還原點。因此，一致性組可以維護相關的寫入順序一致性。如果您決定保護應用程式以實現業務連續性，則必須將與此應用程式對應的磁碟區或儲存單元群組新增至一致性群組中，以便在來源一致性群組和目標一致性群組之間建立資料保護關係。來源一致性群組和目標一致性群組必須包含相同數量和類型的磁碟區。

.組成
單一磁碟區、LUN 或 NVMe 命名空間（從ONTAP 9.17.1 開始），是SnapMirror活動同步關係中受保護的一致性群組的一部分。

.資訊媒體ONTAP
這link:../mediator/index.html["資訊媒體ONTAP"]接收有關對等ONTAP叢集和節點的運行狀況信息，在兩者之間進行協調，並確定每個節點/叢集是否運行正常且正在運行。 ONTAP調解ONTAP提供以下方面的運作狀況資訊：

* 對等 ONTAP 叢集
* 對等 ONTAP 叢集節點
* 一致性群組（定義 SnapMirror 主動式同步關係中的容錯移轉單元）；針對每個一致性群組、會提供下列資訊：
+
** 複寫狀態：未初始化、同步或不同步
** 主複本所在的叢集
** 作業內容（用於規劃的容錯移轉）




透過此 ONTAP Mediator 健全狀況資訊、叢集可以區分不同類型的故障、並判斷是否要執行自動容錯移轉。ONTAP 調解器是 SnapMirror 主動同步仲裁中的三方之一，同時具有兩個 ONTAP 叢集（主要和次要）。要達成共識、法定人數中至少有兩方必須同意某項作業。


NOTE: 從 ONTAP 9.15.1 開始，系統管理員會顯示任一叢集的 SnapMirror 作用中同步關係狀態。您也可以從系統管理員的任一叢集監控 ONTAP Mediator 的狀態。在早期版本的 ONTAP 中、系統管理員會顯示來源叢集的 SnapMirror 主動式同步關係狀態。

.ONTAP雲端調解器
ONTAP Cloud Mediator 從ONTAP 9.17.1 開始可用。 ONTAPONTAP Mediator 提供與ONTAP Mediator 相同的服務，不同之處在於它使用BlueXP託管在雲端。

.規劃的容錯移轉
一種手動操作、可變更 SnapMirror 主動式同步關係中的複本角色。主要站台會變成次要站台、次要站台則成為主要站台。

.自動非計畫性容錯移轉（AUFO）
一種自動操作、可執行容錯移轉至鏡射複本。此作業需要 ONTAP Mediator 協助、以偵測主要複本是否無法使用。

.一級和一級偏差
SnapMirror 主動式同步採用一項主要原則、優先選用主要複本、以便在網路分割區中提供 I/O 服務。

primer-bias 是一種特殊的仲裁實作、可改善 SnapMirror 主動式同步保護資料集的可用度。如果主複本可用、當 ONTAP Mediator 無法從兩個叢集連線時、主偏置即會生效。

從 ONTAP 9.15.1 開始、 SnapMirror 主動同步支援主要優先與主要偏置。主要複本會在 System Manager 中指定、並以 REST API 和 CLI 輸出。

.不同步（OOS）
當應用程式 I/O 未複寫到次要儲存系統時、會報告為 ** 不同步 ** 。不同步狀態表示次要磁碟區不會與主要（來源）同步、也不會發生 SnapMirror 複寫。

如果鏡像狀態是 `Snapmirrored`，這表明SnapMirror關係已建立且資料傳輸已完成，這意味著目標磁碟區與來源磁碟區保持同步。

SnapMirror 主動式同步支援自動重新同步、讓複本恢復至不同步狀態。

從 ONTAP 9.15.1 開始、 SnapMirror 主動式同步支援 link:interoperability-reference.html#fan-out-configurations["自動重新設定排風扇組態"]。

.統一且不一致的組態
* ** 統一主機存取 ** 表示兩個站台的主機都會連線到兩個站台上儲存叢集的所有路徑。跨站台路徑會跨越距離延伸。
* ** 非統一主機存取 ** 表示每個站台中的主機僅連線至同一個站台中的叢集。不連接跨站台路徑和延伸路徑。



NOTE: 任何 SnapMirror 主動式同步部署都支援統一的主機存取；非統一的主機存取僅支援對稱式主動 / 主動式部署。

.零RPO
RPO 是指恢復點目標、這是指在指定期間內可接受的資料遺失量。零 RPO 表示無法接受資料遺失。

.零RTO
RTO 是指恢復時間目標、這是應用程式在中斷、故障或其他資料遺失事件後、在不中斷營運的情況下、恢復正常作業所能接受的時間量。零 RTO 表示無法接受停機時間量。



== ONTAP版本支援的SnapMirror主動同步配置

對SnapMirror主動同步的支援因ONTAP版本的不同而有所差異：

[cols="4*"]
|===


| 版本ONTAP | 支援的集群 | 支援的傳輸協定 | 支援的組態 


| 9.17.1 及更高版本  a| 
* AFF
* ASA
* C 系列
* ASA r2

 a| 
* iSCSI
* FC
* 適用於 VMware 工作負載的 NVMe

 a| 
* 非對稱主動/主動



NOTE: 非對稱主動/主動不支援ASA r2 和 NVMe。有關 NVMe 支援的更多信息，請參閱link:../nvme/support-limitations.html["NVMe 組態、支援和限制"] 。

* 對稱式主動 / 主動式




| 9.16.1 及更新版本  a| 
* AFF
* ASA
* C 系列
* ASA r2

 a| 
* iSCSI
* FC

 a| 
* 非對稱主動/主動
* 對稱主動/主動 對稱主動/主動配置支援ONTAP 9.16.1 及更高版本中的 4 節點叢集。對於ASA r2，僅支援 2 節點叢集。




| 9.15.1 及更高版本  a| 
* AFF
* ASA
* C 系列

 a| 
* iSCSI
* FC

 a| 
* 非對稱主動/主動
* 對稱主動/主動 對稱主動/主動配置支援ONTAP 9.15.1 中的 2 節點叢集。 ONTAPONTAP及更高版本支援 4 節點叢集。




| 9.9.1及更新版本  a| 
* AFF
* ASA
* C 系列

 a| 
* iSCSI
* FC

 a| 
非對稱主動/主動

|===
主集群和輔助集群必須是同一種類型： link:../san-admin/learn-about-asa.html["ASA"] ， link:https://docs.netapp.com/us-en/asa-r2/get-started/learn-about.html["ASA r2"^]或AFF。
