---
sidebar: sidebar 
permalink: snapmirror-active-sync/site-b-mediator-troubleshoot-task.html 
keywords: SM-BC, SMBC, troubleshooting, link down, Mediator, Cloud Mediator, snapmirror active sync 
summary: 站台B的中介連線顯示無法連線。 
---
= 站點 B 與ONTAP調解器之間的連結以及站點 A 之間的連結均發生故障
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
若要檢查ONTAP調解器或ONTAP Cloud 調解器的連接，請使用 `snapmirror mediator show`命令。如果連線狀態為“不可達”，且網站 B 無法存取網站 A，您將看到類似以下的輸出。請依照解決方案中的步驟恢復連接

.範例：
使用ONTAP Cloud Mediator 輸出“snapmirror mediator show”指令：

....
cluster::> snapmirror mediator show
Mediator Address Peer Cluster    Connection Status Quorum Status Type
---------------- ---------------- ----------------- ------------- -------
0.0.0.0          C1_cluster       unreachable       true          cloud
....
使用ONTAP Mediator 輸出“snapmirror mediator show”指令：

....
cluster::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
10.237.86.17     C1_cluster       unreachable       true
SnapMirror consistency group relationship status is out of sync.

C2_cluster::> snapmirror show -expand
Source            Destination Mirror  Relationship   Total             Last
Path        Type  Path        State   Status         Progress  Healthy Updated
----------- ---- ------------ ------- -------------- --------- ------- --------
vs0:/cg/src_cg_1 XDP vs1:/cg/dst_cg_1 Snapmirrored OutOfSync - false   -
vs0:zrto_cg_655724_188a_RW1 XDP vs1:zrto_cg_655755_188c_DP1 Snapmirrored OutOfSync - false -
vs0:zrto_cg_655733_188a_RW2 XDP vs1:zrto_cg_655762_188c_DP2 Snapmirrored OutOfSync - false -
vs0:zrto_cg_655739_188b_RW1 XDP vs1:zrto_cg_655768_188d_DP1 Snapmirrored OutOfSync - false -
vs0:zrto_cg_655748_188b_RW2 XDP vs1:zrto_cg_655776_188d_DP2 Snapmirrored OutOfSync - false -
5 entries were displayed.

Site B cluster is unable to reach Site A.
C2_cluster::> cluster peer show
Peer Cluster Name         Cluster Serial Number Availability   Authentication
------------------------- --------------------- -------------- --------------
C1_cluster 			  1-80-000011           Unavailable    ok
....
.解決方案
強制容錯移轉以啟用站台B的I/O、然後建立從站台B到站台A的零RTO關係請完成下列步驟、在站台B上執行強制容錯移轉

. 從站台B取消對應屬於一致性群組的所有LUN
. 使用force選項刪除SnapMirror一致性群組關係。
. 輸入 SnapMirror Break 命令 (`snapmirror break -destination_path _svm_:_volume_`）在一致性群組組成的磁碟區上、將磁碟區從 DP 轉換為 RW 、以從站台 B 啟用 I/O
+
您必須針對一致性群組中的每個關係發出 SnapMirror 中斷命令。例如、如果一致性群組中有三個磁碟區、您就會針對每個磁碟區發出命令。

. 啟動站台A節點、以建立從站台B到站台A的零RTO關係
. 在站台 A 上以僅限關係資訊來釋放一致性群組，以保留通用快照，並取消對應屬於一致性群組的 LUN 。
. 使用同步原則或非同步原則設定磁碟區層級關係、將站台A上的磁碟區從RW轉換為DP。
. 發行 `snapmirror resync` 同步關係的命令。
. 刪除站台A上的SnapMirror與同步原則的關係
. 在站台B上使用僅限關係資訊的true、以Sync原則釋放SnapMirror關係
. 在站台 B 與站台 A 之間建立一致性群組關係
. 從來源叢集重新同步一致性群組。驗證一致性群組狀態是否同步。
. 重新掃描主機 LUN I/O 路徑、以還原 LUN 的所有路徑。


.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["SnapMirror中斷"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-show.html["SnapMirror 中介顯示"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["SnapMirror 重新同步"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["SnapMirror 顯示"^]

