---
sidebar: sidebar 
permalink: snapmirror-active-sync/use-cases-concept.html 
keywords: SM-BC, SMBC, overview, benefits, use cases, architecture, snapmirror active sync 
summary: 使用 SnapMirror 主動式同步功能、以 LUN 保護應用程式、讓應用程式能以透明方式容錯移轉、確保災難發生時的營運持續性。 
---
= ONTAP SnapMirror主動同步的用例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
全球連線的商業環境要求快速恢復業務關鍵應用程式資料、並在網路攻擊、停電或自然災害等中斷時、避免資料遺失。這些要求在財務和遵守一般資料保護規範（ GDPR ）等法規要求等領域都有所提升。

SnapMirror 主動同步提供下列使用案例：

.零恢復時間目標（ RTO ）的應用程式部署
在SnapMirror主動同步部署中，您有一個主叢集和一個輔助叢集。主集群中的 LUN  `L1P` ) 有一面鏡子 `L1S` )；兩個 LUN 共享相同的序號，並向主機報告為讀寫 LUN。然而，在非對稱配置中，讀寫操作僅對主 LUN 進行。  `L1P` .任何寫入鏡像 `L1S`由代理商提供服務。

.應用程式部署，實現零 RTO 或透明應用程式容錯移轉（ TAF ）
TAF 基於主機 MPIO 軟體的路徑故障轉移，以實現對儲存的無中斷存取。兩個 LUN 副本（例如，主磁碟區 (L1P) 和鏡像副本 (L1S)）具有相同的標識（序號），並向主機報告為可讀寫。然而，在非對稱配置中，讀寫操作僅由主磁碟區提供。傳送到鏡像副本的 I/O 會被代理到主副本。根據非對稱邏輯單元存取 (ALUA) 的存取狀態「主動最佳化」(A/O)，主機到 L1 的首選路徑是 VS1:N1。 ONTAPONTAP是部署的一部分，主要用於在主磁碟區發生儲存中斷時執行故障轉移（計劃內或計劃外）。

TAF 有兩種運作模式：自動故障轉移和自動故障轉移雙工。在自動故障轉移模式下，讀寫作業僅由主磁碟區處理，因此傳送至鏡像副本（鏡像副本無法自行處理寫入作業）的 IO 會被代理到主副本。在自動故障轉移雙工模式下，主副本和輔助副本均可處理 IO，因此無需代理。

如果您使用 NVMe 透過ONTAP 9.17.1 進行主機訪問，則僅支援自動故障轉移雙工。

SnapMirror Active Sync 使用 ALUA 、這種機制可讓應用程式主機多重路徑軟體、其路徑會通告優先順序、並可讓應用程式主機與儲存陣列進行通訊。ALUA 會將擁有 LUN 的控制器和其他控制器的作用中最佳化路徑標記為非最佳化路徑、只有在主要路徑故障時才會使用。

採用 NVMe 協定的SnapMirror主動同步使用 ANA，這使得應用程式主機能夠發現通往受保護的 NVMe 命名空間的最佳化路徑和非最佳化路徑。 ONTAPONTAP目標會發佈對應的路徑狀態，以使應用程式主機能夠使用受保護 NVMe 命名空間的最佳路徑。

.叢集式應用程式
包括 VMware Metro Storage Cluster 、 Oracle RAC 和 Windows 容錯移轉叢集（含 SQL ）在內的叢集式應用程式需要同時存取、因此 VM 可以容錯移轉至其他站台、而不會產生任何效能負擔。SnapMirror Active Sync 對稱式雙主動式 / 主動式可在本機上使用雙向複寫來服務 IO 、以滿足叢集式應用程式的需求。從 ONTAP 9.16.1 開始，四節點叢集的組態支援對稱式雙節點主動 / 主動式，並從 ONTAP 9.15.1 的雙節點叢集限制擴充。

.災難案例
在地理位置分散的站台之間、同步複寫多個磁碟區以供應用程式使用。當主應用程式中斷時、您可以自動容錯移轉至次複本、從而為第一層應用程式提供營運持續性。當主叢集所在的站台發生災難時、主機多重路徑軟體會將叢集的所有路徑標記為關閉、並使用來自次叢集的路徑。結果是 ONTAP Mediator 啟用的無中斷容錯移轉功能、可移轉至鏡像複本。

.Windows 容錯移轉
SnapMirror 主動式同步提供靈活度、應用程式層級精細度易於使用、並可自動容錯移轉。SnapMirror 主動式同步功能使用經實證的 SnapMirror 同步複寫功能、透過 IP 網路以高速複寫 LAN 或 WAN 上的資料、在虛擬和實體環境中、為業務關鍵應用程式（例如 Oracle 、 Microsoft SQL Server 等）實現高資料可用度和快速資料複寫。

SnapMirror 主動式同步功能可讓關鍵任務業務服務持續運作、即使整個站台發生故障、 TAF 也能繼續運作至次要複本。無需手動介入、或無需額外指令碼即可觸發此容錯移轉。
