---
sidebar: sidebar 
permalink: snapmirror-active-sync/use-cases-concept.html 
keywords: SM-BC, SMBC, overview, benefits, use cases, architecture, snapmirror active sync 
summary: 使用 SnapMirror 主動式同步功能、以 LUN 保護應用程式、讓應用程式能以透明方式容錯移轉、確保災難發生時的營運持續性。 
---
= SnapMirror 主動同步的使用案例
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
全球連線的商業環境要求快速恢復業務關鍵應用程式資料、並在網路攻擊、停電或自然災害等中斷時、避免資料遺失。這些要求在財務和遵守一般資料保護規範（ GDPR ）等法規要求等領域都有所提升。

SnapMirror 主動同步提供下列使用案例：

.零恢復時間目標（ RTO ）的應用程式部署
在 SnapMirror 主動同步部署中、您有一個主要和次要叢集。主叢集中的 LUN  `1LP`）有鏡像 (`L1s`）；兩個 LUN 共用相同的序列 ID 、並報告為對主機的讀寫 LUN 。但是、讀寫作業只會服務至主要 LUN 、 `1LP`。對鏡像的任何寫入 `L1S` 由代理服務。

.應用程式部署，實現零 RTO 或透明應用程式容錯移轉（ TAF ）
TAF 是以主機 MPIO 軟體型路徑容錯移轉為基礎、以實現不中斷的儲存存取。LUN 複本（例如、主要（ L1P ）和鏡像複本（ L1S ））都具有相同的身分識別（序號）、並報告為可寫入主機的讀取。但是、讀取和寫入只能由主要磁碟區提供服務。發佈到鏡像複本的I/O會代理到主要複本。根據非對稱式邏輯單元存取（ ALUA ）存取狀態主動最佳化（ A/O ）、主機首選的 L1 路徑為 VS1:N1 。ONTAP Mediator 是部署的一部分、主要是在主設備發生儲存設備故障時、執行容錯移轉（計畫性或非計畫性）。

SnapMirror Active Sync 使用 ALUA 、這種機制可讓應用程式主機多重路徑軟體、其路徑會通告優先順序、並可讓應用程式主機與儲存陣列進行通訊。ALUA 會將擁有 LUN 的控制器和其他控制器的作用中最佳化路徑標記為非最佳化路徑、只有在主要路徑故障時才會使用。

.叢集式應用程式
包括 VMware Metro Storage Cluster 、 Oracle RAC 和 Windows 容錯移轉叢集（含 SQL ）在內的叢集式應用程式需要同時存取、因此 VM 可以容錯移轉至其他站台、而不會產生任何效能負擔。SnapMirror Active Sync 對稱式雙主動式 / 主動式可在本機上使用雙向複寫來服務 IO 、以滿足叢集式應用程式的需求。從 ONTAP 9.16.1 開始，四節點叢集的組態支援對稱式雙節點主動 / 主動式，並從 ONTAP 9.15.1 的雙節點叢集限制擴充。

.災難案例
在地理位置分散的站台之間、同步複寫多個磁碟區以供應用程式使用。當主應用程式中斷時、您可以自動容錯移轉至次複本、從而為第一層應用程式提供營運持續性。當主叢集所在的站台發生災難時、主機多重路徑軟體會將叢集的所有路徑標記為關閉、並使用來自次叢集的路徑。結果是 ONTAP Mediator 啟用的無中斷容錯移轉功能、可移轉至鏡像複本。

.Windows 容錯移轉
SnapMirror 主動式同步提供靈活度、應用程式層級精細度易於使用、並可自動容錯移轉。SnapMirror 主動式同步功能使用經實證的 SnapMirror 同步複寫功能、透過 IP 網路以高速複寫 LAN 或 WAN 上的資料、在虛擬和實體環境中、為業務關鍵應用程式（例如 Oracle 、 Microsoft SQL Server 等）實現高資料可用度和快速資料複寫。

SnapMirror 主動式同步功能可讓關鍵任務業務服務持續運作、即使整個站台發生故障、 TAF 也能繼續運作至次要複本。無需手動介入、或無需額外指令碼即可觸發此容錯移轉。
