---
permalink: smb-hyper-v-sql/configure-shares-continuous-availability-task.html 
sidebar: sidebar 
keywords: configure, shares, continuous, availability, hyper, v, sql, server, virutal, machine, database, file 
summary: 修改共用以持續可用的共用 Hyper-V 和 SQL Server 應用程式伺服器、以進行不中斷的存取 
---
= 設定現有共用以確保持續可用度
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以修改現有的共用區、使其成為持續可用的共用區、讓Hyper-V和SQL Server應用程式伺服器在不中斷營運的情況下存取Hyper-V虛擬機器和組態檔、以及SQL Server資料庫檔案。

.關於這項工作
如果共用具有下列特性、您就無法將現有共用區用作持續可用的共用區、以便透過SMB與應用程式伺服器進行不中斷營運：

* 如果是 `homedirectory` 共用屬性是在該共用上設定
* 如果共用包含已啟用的symlink或wdelinks
* 如果共用區包含位於共用根目錄下方的輔助磁碟區


您必須確認下列兩個共用參數設定正確：

* 。 `-offline-files` 參數設為任一 `manual` （預設）或 `none`。
* 必須停用symlink。


必須設定下列共用內容：

* `continuously-available`
* `oplocks`


不得設定下列共用內容。如果目前共用內容清單中有這些內容、則必須從持續可用的共用區中移除：

* `attributecache`
* `branchcache`


.步驟
. 顯示目前的共用參數設定和目前設定的共用內容清單：
+
[source, cli]
----
vserver cifs share show -vserver <vserver_name> -share-name <share_name>
----
. 如有必要、請使用命令修改共用參數以停用 symlink 、並將離線檔案設為手動 `vserver cifs share modify` 。
+
** 您可以設定的值來停用符號連結 `-symlink` 參數至 `""`。
** 您可以設定 `-offline-files` 指定參數至正確的設定 `manual`。


. 新增 Share 屬性、並視需要新增 `continuously-available` `oplocks` Share 屬性：
+
[source, cli]
----
vserver cifs share properties add -vserver <vserver_name> -share-name <share_name> -share-properties continuously-available[,oplock]
----
+
如果是 `oplocks` 尚未設定共用屬性、您必須將其與一起新增 `continuously-available` 共用屬性。

. 移除持續可用共用區上不支援的任何共用內容：
+
[source, cli]
----
vserver cifs share properties remove -vserver <vserver_name> -share-name <share_name> -share-properties properties[,...]
----
+
您可以使用以逗號分隔的清單來指定共用屬性、以移除一或多個共用屬性。

. 確認 `-symlink` 和 `-offline-files` 參數設定正確：
+
[source, cli]
----
vserver cifs share show -vserver <vserver_name> -share-name <share_name> -fields symlink-properties,offline-files
----
. 確認已設定的共用內容清單正確無誤：
+
[source, cli]
----
vserver cifs share properties show -vserver <vserver_name> -share-name <share_name>
----


.範例
以下範例說明如何在儲存虛擬機器（ SVM ）「 VS1 」上、針對 NDOS 設定名為「 share1 」的現有共享區、並透過 SMB 設定應用程式伺服器：

* 將參數設定為、即可在共用區上停用 symlinks `-symlink` `""`。
* 。 `-offline-file` 參數已修改並設為 `manual`。
* 。 `continuously-available` 共用屬性即會新增至共用。
* 。 `oplocks` 共用屬性已在共用屬性清單中、因此不需要新增。
* 。 `attributecache` 共用內容即會從共用中移除。
* 。 `browsable` 對於透過 SMB 與應用程式伺服器使用的 NDOS 持續可用共用區、則可選用 Share 屬性、並保留為其中一個共用屬性。


[listing]
----
cluster1::> vserver cifs share show -vserver vs1 -share-name share1

                      Vserver: vs1
                        Share: share1
     CIFS Server NetBIOS Name: vs1
                         Path: /data
             Share Properties: oplocks
                               browsable
                               attributecache
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: 10s
                  Volume Name: data
                Offline Files: documents
Vscan File-Operations Profile: standard

cluster1::> vserver cifs share modify -vserver vs1 -share-name share1 -offline-file manual -symlink ""

cluster1::> vserver cifs share properties add -vserver vs1 -share-name share1 -share-properties continuously-available

cluster1::> vserver cifs share properties remove -vserver vs1 -share-name share1 -share-properties attributecache

cluster1::> vserver cifs share show -vserver vs1 -share-name share1 -fields symlink-properties,offline-files
vserver  share-name symlink-properties offline-files
-------- ---------- ------------------ -------------
vs1      share1    -                  manual

cluster1::> vserver cifs share properties show -vserver vs1 -share-name share1

         Vserver: vs1
           Share: share1
Share Properties: oplocks
                  browsable
                  continuously-available
----