---
permalink: smb-hyper-v-sql/display-nondisruptive-status-health-task.html 
sidebar: sidebar 
keywords: display, nondisruptive, operation, status, system, health, monitor, cifs, ndo, alert 
summary: 您可以使用系統健全狀況命令來顯示有關叢集整體系統健全狀況和CIFS/n子系統健全狀況的資訊、回應警示、設定未來警示、以及顯示如何設定健全狀況監控的資訊。 
---
= 使用系統健全狀況監控來顯示不中斷營運狀態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「系統健全狀況」命令來顯示有關叢集整體系統健全狀況和CIFS/n子系統健全狀況的資訊、回應警示、設定未來警示、以及顯示如何設定健全狀況監控的資訊。

.步驟
. 執行適當的動作來監控健全狀況：
+
|===
| 如果您要顯示... | 輸入命令... 


 a| 
系統的健全狀況、反映個別健全狀況監視器的整體狀態
 a| 
系統健全狀況顯示*



 a| 
CIFS/NDO子系統健全狀況的相關資訊
 a| 
系統健全狀況子系統顯示-Subsystem CIFS/n -instance*

|===
. 顯示有關CIFS/n警示監控如何設定的資訊、方法是執行適當的動作：
+
|===
| 如果您想要顯示有關...的資訊 | 輸入命令... 


 a| 
CIFS/NDO子系統的健全狀況監視器組態與狀態、例如受監控的節點、初始化狀態和狀態
 a| 
系統健全狀況組態顯示-子系統Cs-NDo*



 a| 
CIF-NDO會發出健全狀況監視器可能產生的警示
 a| 
系統健全狀況警示定義顯示-子系統CIFS/NDO *



 a| 
CIF-NDO健全狀況監視原則、可決定何時發出警示
 a| 
系統健全狀況原則定義show -監 控節點連線*

|===
+
[NOTE]
====
使用「-instance」參數來顯示詳細資訊。

====


.範例
下列輸出顯示有關叢集和CIFS/n子系統整體健全狀況狀態的資訊：

[listing]
----
cluster1::> system health status show
Status
---------------
ok

cluster1::> system health subsystem show -instance -subsystem CIFS-NDO

                   Subsystem: CIFS-NDO
                      Health: ok
        Initialization State: initialized
Number of Outstanding Alerts: 0
 Number of Suppressed Alerts: 0
                        Node: node2
  Subsystem Refresh Interval: 5m
----
下列輸出顯示CIFS/n子系統健全狀況監視器的組態與狀態詳細資訊：

[listing]
----
cluster1::> system health config show -subsystem CIFS-NDO -instance

                           Node: node1
                        Monitor: node-connect
                      Subsystem: SAS-connect, HA-health, CIFS-NDO
                         Health: ok
                Monitor Version: 2.0
            Policy File Version: 1.0
                        Context: node_context
                     Aggregator: system-connect
                       Resource: SasAdapter, SasDisk, SasShelf, HaNodePair,
                                 HaICMailbox, CifsNdoNode, CifsNdoNodeVserver
Subsystem Initialization Status: initialized
    Subordinate Policy Versions: 1.0 SAS, 1.0 SAS multiple adapters, 1.0, 1.0

                           Node: node2
                        Monitor: node-connect
                      Subsystem: SAS-connect, HA-health, CIFS-NDO
                         Health: ok
                Monitor Version: 2.0
            Policy File Version: 1.0
                        Context: node_context
                     Aggregator: system-connect
                       Resource: SasAdapter, SasDisk, SasShelf, HaNodePair,
                                 HaICMailbox, CifsNdoNode, CifsNdoNodeVserver
Subsystem Initialization Status: initialized
    Subordinate Policy Versions: 1.0 SAS, 1.0 SAS multiple adapters, 1.0, 1.0
----