---
permalink: smb-hyper-v-sql/odx-copy-offload-concept.html 
sidebar: sidebar 
keywords: offload, data, transfer, odx, copy, application, server, copy, operation 
summary: 卸載式資料傳輸（ODX）也稱為複本卸載、可在相容儲存裝置內或之間直接傳輸資料、而無需透過主機電腦傳輸資料。透過SMB安裝、在應用程式伺服器上執行複製作業時、利用VMware版複製卸載功能可為您帶來效能優勢。ONTAP 
---
= ODX複製卸載如何透過SMB共用搭配Hyper-V和SQL Server使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
卸載資料傳輸（ODX）也稱為_copy offload_、可在相容儲存裝置內或之間直接傳輸資料、而無需透過主機電腦傳輸資料。透過SMB安裝、在應用程式伺服器上執行複製作業時、利用VMware版複製卸載功能可為您帶來效能優勢。ONTAP

在非ODX檔案傳輸中、資料會從來源CIFS伺服器讀取、並透過網路傳輸至用戶端電腦。用戶端電腦會透過網路將資料傳輸回目的地CIFS伺服器。總而言之、用戶端電腦會從來源讀取資料、然後寫入目的地。使用ODX檔案傳輸時、資料會直接從來源複製到目的地。

由於ODX卸載複本是直接在來源與目的地儲存設備之間執行、因此效能優勢顯著。實現的效能效益包括加快來源與目的地之間的複製時間、降低用戶端上的資源使用率（CPU、記憶體）、以及降低網路I/O頻寬使用率。

此功能可在Windows Server 2012伺服器上使用。SAN LUN和SMB 3.0持續可用的連線均支援使用ODX複製卸載。ONTAP

下列使用案例支援使用ODX複本和移動：

* Volume內
+
來源與目的地檔案或LUN位於同一個磁碟區內。

* 磁碟區間、相同節點、相同儲存虛擬機器（SVM）
+
來源與目的地檔案或LUN位於同一個節點上的不同磁碟區。資料歸同一個SVM所有。

* 磁碟區間、不同節點、相同SVM
+
來源與目的地檔案或LUN位於不同節點上的不同磁碟區。資料歸同一個SVM所有。

* SVM之間、相同節點
+
來源與目的地檔案或LUN位於同一個節點上的不同磁碟區。資料由不同的SVM擁有。

* SVM之間、不同節點
+
來源與目的地檔案或LUN位於不同節點上的不同磁碟區。資料由不同的SVM擁有。



Hyper-V解決方案的ODX複製卸載特定使用案例包括：

* 您可以使用ODX複本卸載傳遞搭配Hyper-V、在虛擬硬碟（VHD）檔案內或之間複製資料、或在同一個叢集內的對應SMB共用區和連接的iSCSI LUN之間複製資料。
+
如此一來、從客體作業系統的複本就能傳遞到基礎儲存設備。

* 建立固定大小的VHD時、ODX會使用已知的零權杖、以零初始化磁碟。
* 如果來源與目的地儲存設備位於同一個叢集、則ODX複本卸載可用於虛擬機器儲存移轉。


[NOTE]
====
若要利用ODX複本卸載傳遞與Hyper-V的使用案例、來賓作業系統必須支援ODX、而來賓作業系統的磁碟必須是支援ODX的儲存設備（SMB或SAN）所支援的SCSI磁碟。客體作業系統上的IDE磁碟不支援ODX傳遞。

====
SQL Server解決方案的ODX複製卸載特定使用案例包括：

* 您可以使用ODX複製卸載、在對應的SMB共用區之間、或是在同一個叢集內的SMB共用區與連線的iSCSI LUN之間匯出及匯入SQL Server資料庫。
* 如果來源與目的地儲存設備位於同一個叢集、則ODX複製卸載可用於資料庫匯出與匯入。

