---
permalink: smb-hyper-v-sql/remote-vss-considerations-concept.html 
sidebar: sidebar 
keywords: remote, vss, consideration, hyper, v, smb, configuration, backup, solution, automatic, recovery, shadow, copy 
summary: 在使用支援遠端VSS的備份解決方案進行Hyper-V over SMB組態時、您必須注意某些考量事項。 
---
= 基於SMB組態的Hyper-V遠端VSS考量
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在使用支援遠端VSS的備份解決方案進行Hyper-V over SMB組態時、您必須注意某些考量事項。



== 一般遠端VSS考量

* 每個Microsoft應用程式伺服器最多可設定64個共用區。
+
如果陰影複製集中有超過64個共用區、陰影複製作業就會失敗。這是Microsoft的要求。

* 每部CIFS伺服器只允許一個作用中的陰影複製集。
+
如果在同一部CIFS伺服器上持續執行陰影複製作業、陰影複製作業將會失敗。這是Microsoft的要求。

* 在遠端VSS建立陰影複製的目錄結構中、不允許任何交會。
+
** 在自動還原案例中、如果在瀏覽共用區時遇到交會、陰影複製建立將會失敗。
** 在非自動還原案例中、陰影複製建立並不會失敗、但交會不會指向任何內容。






== 遠端VSS考量、僅適用於具有自動還原功能的陰影複製

某些限制僅適用於具有自動還原功能的陰影複製。

* 建立陰影複製時、最多可允許五個子目錄的目錄深度。
+
這是陰影複製服務建立陰影複製備份集的目錄深度。如果包含虛擬機器檔案的目錄巢狀深於五個層級、陰影複製建立就會失敗。這是為了限制複製共用時的目錄周遊。您可以使用CIFS伺服器選項來變更最大目錄深度。

* 磁碟區上的可用空間量必須足夠。
+
可用空間必須至少與陰影複製備份集中所含共用區內的所有檔案、目錄及子目錄所使用的總空間相同。

* 在遠端VSS建立陰影複製的目錄結構中、不允許任何連結或非一般檔案。
+
如果共用區中有任何連結或非一般檔案到陰影複製、陰影複製建立就會失敗。複製程序不支援。

* 目錄不允許使用NFSv4 ACL。
+
雖然建立陰影複製會保留檔案上的NFSv4 ACL、但目錄上的NFSv4 ACL會遺失。

* 建立陰影複製集的時間上限為60秒。
+
Microsoft規格允許建立陰影複製集的時間上限為60秒。如果VSS用戶端在此時間內無法建立陰影複製集、陰影複製作業將會失敗、因此會限制陰影複製集中的檔案數量。備份集中可包含的檔案或虛擬機器實際數量各不相同、這個數目取決於許多因素、而且必須針對每個客戶環境來決定。


