---
permalink: file-system-analytics/activity-tracking-task.html 
sidebar: sidebar 
keywords: monitor, volume, ontap, FSA, File System Analytics, 
summary: 活動追蹤：檢視指定Volume中的常用檔案、目錄、用戶端和使用者、以進行即時效能疑難排解 
---
= 啟用「活動追蹤」
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
檔案系統分析從ONTAP 《支援範圍》9.10.1開始、包含「活動追蹤」功能、可讓您識別熱門物件並將其下載為CSV檔案。從《S209.11.1活動ONTAP 追蹤（Activ練習 追蹤）」開始、活動追蹤已擴大至SVM範圍。此外、從《系統管理程式》（System Manager）的《活動追蹤》（Activicity Tracking, System Manager）也開始提供活動追蹤的時間表、讓您最多可以查看五分鐘的「活動追蹤」資料。ONTAP

「活動追蹤」可監控四種類別：

* 目錄
* 檔案
* 用戶端
* 使用者


對於每個受監控的類別、「活動追蹤」會顯示讀取IOPs、寫入IOPs、讀取流量和寫入流量。「活動追蹤」查詢每10到15秒會重新整理一次、以說明系統在前五秒間隔內出現的熱點。

活動追蹤資訊是大約的、資料的準確度取決於傳入I/O流量的分配。

在Volume層級的System Manager中檢視「活動追蹤」時、只有展開Volume的功能表會主動重新整理。如果任何磁碟區的檢視都已收合、則在展開磁碟區顯示之前、這些磁碟區不會重新整理。您可以使用*暫停重新整理*按鈕來停止重新整理。活動資料可以CSV格式下載、以顯示所選磁碟區擷取的所有時間點資料。

從《支援資料時程表ONTAP 》9.11.1開始、您可以將熱點活動記錄在磁碟區或SVM上、每五秒持續更新一次、並保留前五分鐘的資料。時間軸資料只會保留給頁面可見區域的欄位。如果您摺疊追蹤類別或捲動、使時間表不在檢視範圍內、時間表將停止收集資料。根據預設、當您離開「活動」索引標籤時、時間表會停用、並自動停用。



== 針對單一Volume啟用「活動追蹤」

您可以使用ONTAP 支援「活動追蹤」功能的支援功能、以支援使用「支援系統管理程式」或ONTAP 「支援CLI」功能。

.關於這項工作
如果您搭配ONTAP 使用RBAC搭配使用REST API或System Manager、則必須建立自訂角色、才能管理「活動追蹤」的存取權限。請參閱 <<角色型存取控制（RBAC）和活動追蹤>> 此程序。

[role="tabbed-block"]
====
.系統管理員
--
.步驟
. 選擇*儲存>磁碟區*。選取所需的Volume。從個別Volume功能表中、選取File System（檔案系統）、然後選取「活動」索引標籤。
. 確保*活動追蹤*已開啟、以檢視熱門目錄、檔案、用戶端和使用者的個別報告。
. 若要在不重新整理的情況下更深入地分析資料、請選取*暫停重新整理*。您也可以下載資料以取得報告的CSV記錄。


--
.CLI
--
.步驟
. 啟用活動追蹤：
+
「Volume activity追蹤：-vsver_Svm_name_-volume _volume _name_」

. 您可以使用下列命令來檢查磁碟區的「活動追蹤」狀態是開啟還是關閉：
+
「Volume activity追蹤show -vsver_Svm_name_-volume _volume名稱_-stu態」

. 啟用後、請使用ONTAP 「靜態系統管理程式」或ONTAP 「靜態API」來顯示「活動追蹤」資料。


--
====


== 啟用多個磁碟區的「活動追蹤」

您可以使用System Manager一次啟用多個磁碟區的「活動追蹤」。

.關於這項工作
如果您搭配ONTAP 使用RBAC搭配使用REST API或System Manager、則必須建立自訂角色、才能管理「活動追蹤」的存取權限。請參閱 <<角色型存取控制（RBAC）和活動追蹤>> 此程序。

[role="tabbed-block"]
====
.適用於特定磁碟區
--
.步驟
. 選擇*儲存>磁碟區*。選取所需的Volume。從個別Volume功能表中、選取File System（檔案系統）、然後選取「活動」索引標籤。
. 選取您要啟用「活動追蹤」的磁碟區。在Volume清單頂端、選取*更多選項*按鈕。選取*啟用活動追蹤*。
. 若要在SVM層級檢視「活動追蹤」、請從*儲存設備> Volumes *選取您要檢視的特定SVM。導覽至「檔案系統」索引標籤、接著是「活動」、您會看到已啟用「活動追蹤」的磁碟區資料。


--
.適用於SVM中的所有Volume
--
.步驟
. 選擇*儲存>磁碟區*。從功能表中選取SVM。
. 瀏覽至*檔案系統*索引標籤、選擇*更多*索引標籤、即可在SVM中的所有磁碟區上啟用「活動追蹤」。


--
====


== 角色型存取控制（RBAC）和活動追蹤

如果您使用 xref:../concepts/administrator-authentication-rbac-concept.html[角色型存取控制] （RBAC）ONTAP 在System Manager或R靜止API中、您需要建立專屬角色、以便在檔案系統分析中適度存取「活動追蹤」。

.步驟
. 建立預設角色以存取所有功能。
+
在建立限制角色之前、必須先完成這項作業、以確保「活動追蹤」上的角色僅受到限制：

+
「安全登入角色create -cmd目錄名稱預設-access all -role storageAdmin」

. 建立限制角色：
+
「安全性登入角色create -cmd目錄名稱"volume file show-disk-usage"-access nONE -role storageadmin"

. 授權角色存取SVM的Web服務：
+
** 用於REST API呼叫的"REst"
** 密碼保護的安全性
** 「ysmgr"」存取系統管理程式
+
「vserver services web存取create -vserver _svm-name_-name_-name rest -role storageAdmin」

+
「Vserver服務網路存取create -vserver _svm-name_-name安全性-role storageAdmin」

+
「vserver services web存取create -vserver _svm-name_-name sysmgr -role storageAdmin」



. 建立使用者。
+
您必須針對要套用至使用者的每個應用程式、發出不同的create命令。在同一位使用者上多次呼叫建立、只會將所有應用程式套用至該位使用者、而不會每次都建立新的使用者。應用程式類型的「http」參數適用於ONTAP 「靜態API」和「系統管理程式」。

+
「安全登入create -user-or group名稱storageUser -authentation-method password -applicationhttp -role storageAdmin」

. 有了新的使用者認證資料、您現在可以登入System Manager、或使用ONTAP REST API來存取檔案系統分析資料。


link:https://docs.netapp.com/us-en/ontap-automation/rest/rbac_overview.html["深入瞭解RBAC角色和ONTAP REST API"^]
