---
permalink: antivirus/apply-scanner-policies-disaster-recovery-mcc-task.html 
sidebar: sidebar 
keywords: apply, scanner policies, metrocluster, configurations 
summary: 掃描器原則會決定掃描器集區是否處於作用中狀態。您必須將掃描儀原則套用至MetroCluster 每個叢集上的主掃描儀資源池和次掃描儀資源池、以供選擇。 
---
= 將掃描器原則套用MetroCluster 至各種組態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
掃描器原則會決定掃描器集區是否處於作用中狀態。您必須將掃描儀原則套用至MetroCluster 每個叢集上的主掃描儀資源池和次掃描儀資源池、以供選擇。

.關於這項工作
* 您只能將一個掃描器原則套用至掃描器集區。
* 如果您為叢集中的所有SVM建立了掃描程式集區、則必須分別在每個SVM上套用掃描程式原則。


.步驟
. 套用掃描器原則：
+
「vserver vscan ScANer-Pool apple-policy -vserver _data_svm_-staer-pool _staiper-policy primary| secondary | idle -cluster _the_apply_policy_on_」

+
掃描器原則可以具有下列其中一個值：

+
** 「主要」指定掃描器集區為作用中狀態。
** 「次要」指定只有在主要掃描器集區中沒有任何VScan伺服器連線時、才會啟用掃描器集區。
** 「閒置」表示掃描器資源池處於非使用中狀態。


+
[NOTE]
====
您必須套用包含主要SVM之叢集的所有掃描器原則。

====
+
下列命令會將掃描儀原則套用至MetroCluster 每個叢集上的主掃描儀集區和次掃描儀集區、以供選擇：

+
[listing]
----
cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool1_for_site1 -scanner-policy primary -cluster cluster1

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool2_for_site1 -scanner-policy secondary -cluster cluster1

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool1_for_site2 -scanner-policy primary -cluster cluster2

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool2_for_site2 -scanner-policy secondary -cluster cluster2
----
. 確認掃描器集區處於作用中狀態：
+
「vserver vscan ScANer-Pool show -vserver data_SVM |叢集管理SVM -ScANer-Pool ScAN_Pool」

+
如需選項的完整清單、請參閱命令的手冊頁。

+
下列命令會顯示掃描器集區「Pool1」的詳細資料：

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver cifssvm1 -scanner-pool pool1_for_site1

                                    Vserver: cifssvm1
                               Scanner Pool: pool1_for_site1
                             Applied Policy: primary
                             Current Status: on
         Cluster on Which Policy Is Applied: cluster1
                  Scanner Pool Config Owner: vserver
       List of IPs of Allowed Vscan Servers:
List of Host Names of Allowed Vscan Servers: scan1
                   List of Privileged Users: cifs\u1,cifs\u2
----
+
您可以使用「vserver vscan ScANer-Pool show-active」命令來檢視SVM上的作用中掃描器集區。如需完整的命令語法、請參閱命令的手冊頁。


