---
permalink: antivirus/apply-scanner-policy-pool-task.html 
sidebar: sidebar 
keywords: apply, scanner policy, single, cluster 
summary: 掃描器原則會決定掃描器集區是否處於作用中狀態。您必須先啟動掃瞄器集區、其定義的 VScan 伺服器才能連線至 SVM 。 
---
= 在單一叢集上套用掃描器原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
掃描器原則會決定掃描器集區是否處於作用中狀態。您必須先啟動掃瞄器集區、其定義的 VScan 伺服器才能連線至 SVM 。

.關於這項工作
* 您只能將一個掃描器原則套用至掃描器集區。
* 如果您為叢集中的所有 SVM 建立了掃瞄器集區、則必須個別在每個 SVM 上套用掃瞄器原則。


.步驟
. 套用掃描器原則：
+
`vserver vscan scanner-pool apply-policy -vserver data_SVM -scanner-pool scanner_pool -scanner-policy primary|secondary|idle -cluster cluster_to_apply_policy_on`

+
掃描器原則可以具有下列其中一個值：

+
** `Primary` 指定掃描儀池處於活動狀態。
** `Secondary` 指定只有在沒有連接主要掃描器集區中的 VScan 伺服器時、掃描器集區才為作用中。
** `Idle` 指定掃描器集區為非作用中。
+
以下範例顯示掃描器集區的名稱 `SP` 在上 `vs1` SVM 處於作用中狀態：

+
[listing]
----
cluster1::> vserver vscan scanner-pool apply-policy -vserver vs1 -scanner-pool SP  -scanner-policy primary
----


. 確認掃描器集區處於作用中狀態：
+
`vserver vscan scanner-pool show -vserver data_SVM|cluster_admin_SVM -scanner-pool scanner_pool`

+
如需選項的完整清單、請參閱命令的手冊頁。

+
下列命令會顯示的詳細資料 `SP` 掃描器集區：

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver vs1 -scanner-pool SP

                                    Vserver: vs1
                               Scanner Pool: SP
                             Applied Policy: primary
                             Current Status: on
         Cluster on Which Policy Is Applied: cluster1
                  Scanner Pool Config Owner: vserver
       List of IPs of Allowed Vscan Servers: 1.1.1.1, 10.72.204.27
List of Host Names of Allowed Vscan Servers: 1.1.1.1, vmwin204-27.fsct.nb
                   List of Privileged Users: cifs\u1, cifs\u2
----
+
您可以使用 `vserver vscan scanner-pool show-active` 用於查看 SVM 上活動掃描儀池的命令。如需完整的命令語法、請參閱命令的手冊頁。


