---
permalink: antivirus/apply-scanner-policies-disaster-recovery-mcc-task.html 
sidebar: sidebar 
keywords: apply, scanner policies, metrocluster, configurations 
summary: 掃描器原則會決定掃描器集區是否處於作用中狀態。您必須將掃描儀原則套用至MetroCluster 每個叢集上的主掃描儀資源池和次掃描儀資源池、以供選擇。 
---
= 將掃描器原則套用MetroCluster 至各種組態
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
掃描器原則會決定掃描器集區是否處於作用中狀態。您必須將掃描儀原則套用至MetroCluster 每個叢集上的主掃描儀資源池和次掃描儀資源池、以供選擇。

.關於這項工作
* 您只能將一個掃描器原則套用至掃描器集區。
* 如果您為叢集中的所有 SVM 建立了掃瞄器集區、則必須個別在每個 SVM 上套用掃瞄器原則。
* 對於災難恢復和 MetroCluster 組態、您必須將掃描器原則套用至本機叢集和遠端叢集中的每個掃描器集區。
* 在您為本機叢集建立的原則中、您必須在中指定本機叢集 `cluster` 參數。在您為遠端叢集建立的原則中、您必須在中指定遠端叢集 `cluster` 參數。接著、遠端叢集便可在發生災難時接管病毒掃描作業。


.步驟
. 套用掃描器原則：
+
`vserver vscan scanner-pool apply-policy -vserver _data_SVM_ -scanner-pool _scanner_pool_ -scanner-policy primary|secondary|idle -cluster _cluster_to_apply_policy_on_`

+
掃描器原則可以具有下列其中一個值：

+
** `Primary` 指定掃描儀池處於活動狀態。
** `Secondary` 指定只有在沒有連接主要掃描器集區中的 VScan 伺服器時、掃描器集區才為作用中。
** `Idle` 指定掃描器集區為非作用中。
+
[NOTE]
====
您必須套用包含主要SVM之叢集的所有掃描器原則。

====
+
下列命令會將掃描儀原則套用至MetroCluster 每個叢集上的主掃描儀集區和次掃描儀集區、以供選擇：

+
[listing]
----
cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool1_for_site1 -scanner-policy primary -cluster cluster1

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool2_for_site1 -scanner-policy secondary -cluster cluster1

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool2_for_site2 -scanner-policy primary -cluster cluster2

cluster1::>vserver vscan scanner-pool apply-policy -vserver cifssvm1
-scanner-pool pool1_for_site2 -scanner-policy secondary -cluster cluster2
----


. 確認掃描器集區處於作用中狀態：
+
`vserver vscan scanner-pool show -vserver data_SVM|cluster_admin_SVM -scanner-pool scanner_pool`

+
如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。

+
下列命令會顯示掃描器集區的詳細資料 `pool1`：

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver cifssvm1 -scanner-pool pool1_for_site1

                                    Vserver: cifssvm1
                               Scanner Pool: pool1_for_site1
                             Applied Policy: primary
                             Current Status: on
         Cluster on Which Policy Is Applied: cluster1
                  Scanner Pool Config Owner: vserver
       List of IPs of Allowed Vscan Servers:
List of Host Names of Allowed Vscan Servers: scan1
                   List of Privileged Users: cifs\u1,cifs\u2
----
+
您可以使用 `vserver vscan scanner-pool show-active`命令來檢視 SVM 上的作用中掃描器集區。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-scanner-pool-show-active.html["指令參考資料ONTAP"^]需詳細 `vserver vscan scanner-pool show-active`資訊，請參閱。


