---
permalink: antivirus/commands-manage-on-access-policies-reference.html 
sidebar: sidebar 
keywords: commands, manage, on-access, policies 
summary: 您可以修改、停用或刪除存取時原則。您可以檢視原則的摘要和詳細資料。 
---
= 管理 ONTAP 中存取原則的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以修改、停用或刪除存取時原則。您可以檢視原則的摘要和詳細資料。

|===


| 如果您想要... | 輸入下列命令... 


 a| 
建立存取時原則
 a| 
`vserver vscan on-access-policy create`



 a| 
修改存取時原則
 a| 
`vserver vscan on-access-policy modify`



 a| 
啟用存取原則
 a| 
`vserver vscan on-access-policy enable`



 a| 
停用存取原則
 a| 
`vserver vscan on-access-policy disable`



 a| 
刪除存取時原則
 a| 
`vserver vscan on-access-policy delete`



 a| 
檢視存取原則的摘要和詳細資料
 a| 
`vserver vscan on-access-policy show`



 a| 
新增至要排除的路徑清單
 a| 
`vserver vscan on-access-policy paths-to-exclude add`



 a| 
從要排除的路徑清單中刪除
 a| 
`vserver vscan on-access-policy paths-to-exclude remove`



 a| 
檢視要排除的路徑清單
 a| 
`vserver vscan on-access-policy paths-to-exclude show`



 a| 
新增至要排除的副檔名清單
 a| 
`vserver vscan on-access-policy file-ext-to-exclude add`



 a| 
從要排除的副檔名清單中刪除
 a| 
`vserver vscan on-access-policy file-ext-to-exclude remove`



 a| 
檢視要排除的副檔名清單
 a| 
`vserver vscan on-access-policy file-ext-to-exclude show`



 a| 
新增至要包含的副檔名清單
 a| 
`vserver vscan on-access-policy file-ext-to-include add`



 a| 
從要包含的副檔名清單中刪除
 a| 
`vserver vscan on-access-policy file-ext-to-include remove`



 a| 
檢視要包含的副檔名清單
 a| 
`vserver vscan on-access-policy file-ext-to-include show`

|===
如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。
