---
permalink: antivirus/create-scanner-pool-single-cluster-task.html 
sidebar: sidebar 
keywords: create, scanner pool, single cluster 
summary: 掃描器集區會定義VScan伺服器和可連線至SVM的授權使用者。您可以為個別 SVM 或叢集中的所有 SVM 建立掃描器集區。 
---
= 在單一叢集上建立掃描器集區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
掃描器集區會定義VScan伺服器和可連線至SVM的授權使用者。您可以為個別 SVM 或叢集中的所有 SVM 建立掃描器集區。

.您需要的產品
* SVM和VScan伺服器必須位於同一個網域或信任的網域中。
* 針對為個別 SVM 定義的掃描器集區、您必須使用 SVM 管理 LIF 或 SVM 資料 LIF 來設定 ONTAP 防毒連接器。
* 針對叢集中所有 SVM 定義的掃描器集區、您必須使用叢集管理 LIF 來設定 ONTAP 防毒連接器。
* 授權使用者清單必須包含VScan伺服器用來連線至SVM的網域使用者帳戶。
* 設定掃描器集區後、請檢查伺服器的連線狀態。


.步驟
. 建立掃描器集區：
+
`vserver vscan scanner-pool create -vserver data_SVM|cluster_admin_SVM -scanner-pool scanner_pool -hostnames Vscan_server_hostnames -privileged-users privileged_users`

+
** 為個別SVM定義的資源池指定資料SVM、並為叢集中所有SVM定義的資源池指定叢集管理SVM。
** 為每個VScan伺服器主機名稱指定IP位址或FQDN。
** 指定每個授權使用者的網域和使用者名稱。
如需選項的完整清單、請參閱命令的手冊頁。


+
下列命令會建立名為的掃描器集區 `SP` 在上 `vs1` SVM ：

+
[listing]
----
cluster1::> vserver vscan scanner-pool create -vserver vs1 -scanner-pool SP -hostnames 1.1.1.1,vmwin204-27.fsct.nb -privileged-users cifs\u1,cifs\u2
----
. 確認已建立掃描器集區：
+
`vserver vscan scanner-pool show -vserver _data_SVM|cluster_admin_SVM_ -scanner-pool _scanner_pool_`

+
如需選項的完整清單、請參閱命令的手冊頁。

+
下列命令會顯示的詳細資料 `SP` 掃描器集區：

+
[listing]
----
cluster1::> vserver vscan scanner-pool show -vserver vs1 -scanner-pool SP

                                    Vserver: vs1
                               Scanner Pool: SP
                             Applied Policy: idle
                             Current Status: off
         Cluster on Which Policy Is Applied: -
                  Scanner Pool Config Owner: vserver
       List of IPs of Allowed Vscan Servers: 1.1.1.1, 10.72.204.27
List of Host Names of Allowed Vscan Servers: 1.1.1.1, vmwin204-27.fsct.nb
                   List of Privileged Users: cifs\u1, cifs\u2
----
+
您也可以使用 `vserver vscan scanner-pool show` 命令以檢視 SVM 上的所有掃描器集區。如需完整的命令語法、請參閱命令的手冊頁。


