---
permalink: antivirus/create-on-demand-task-task.html 
sidebar: sidebar 
keywords: create, on-demand, task, vserver vscan, wildcards 
summary: 隨需工作可定義隨需掃描的範圍。您可以指定要掃描的檔案大小上限、要包含在掃描中的檔案副檔名和路徑、以及要從掃描中排除的檔案副檔名和路徑。 
---
= 使用 ONTAP Vscan 建立按需任務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
隨選工作會定義隨選病毒掃描的範圍。您可以指定要掃描的檔案大小上限、要包含在掃描中的檔案副檔名和路徑、以及要從掃描中排除的檔案副檔名和路徑。依預設會掃描子目錄中的檔案。

.關於這項工作
* 每個 SVM 最多可有十（ 10 ）個隨選工作、但只有一個可以使用中。
* 隨選工作會建立報告、其中包含與掃描相關的統計資料資訊。您可以使用命令或下載工作在定義位置所建立的報告檔案、來存取此報告。
* 從 ONTAP 9.14.1 開始，您可以使用萬用字元來指定要排除的隨選路徑。


.開始之前
* 您必須擁有 xref:create-on-access-policy-task.html[已建立存取原則]。原則可以是預設原則或使用者建立的原則。如果沒有存取原則、就無法啟用掃描。


.步驟
. 建立隨需工作：
+
`vserver vscan on-demand-task create -vserver _data_SVM_ -task-name _task_name_ -scan-paths _paths_of_files_to_scan_ -report-directory _report_directory_path_ -report-expiry-time _expiration_time_for_report_ -schedule cron_schedule -max-file-size _max_size_of_files_to_scan_ -paths-to-exclude _paths_ -file-ext-to-exclude _file_extensions_ -file-ext-to-include _file_extensions_ -scan-files-with-no-ext true|false -directory-recursion true|false`

+
** 。 `-file-ext-to-exclude` 設定會覆寫 `-file-ext-to-include` 設定：
** 設定 `-scan-files-with-no-ext` 至 true 可掃描不含副檔名的檔案。
+
如link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-create.html["指令參考資料ONTAP"^]需詳細 `vserver vscan on-demand-task create`資訊，請參閱。



+
下列命令會建立名為的隨選工作 `Task1` 在「 VS1 ’ shVM ：

+
[listing]
----
cluster1::> vserver vscan on-demand-task create -vserver vs1 -task-name Task1 -scan-paths "/vol1/","/vol2/cifs/" -report-directory "/report" -schedule daily -max-file-size 5GB -paths-to-exclude "/vol1/cold-files/" -file-ext-to-include "vmdk?","mp*" -file-ext-to-exclude "mp3","mp4" -scan-files-with-no-ext false
[Job 126]: Vscan On-Demand job is queued. Use the "job show -id 126" command to view the status.
----
+

NOTE: 您可以使用 `job show`命令來檢視工作的狀態。您可以使用 `job pause`和 `job resume`命令暫停和重新啟動工作，或使用 `job stop`命令結束工作。如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=job["指令參考資料ONTAP"^]需詳細 `job`資訊，請參閱。

. 確認已建立隨選工作：
+
`vserver vscan on-demand-task show -instance data_SVM -task-name task_name`

+
如link:https://docs.netapp.com/us-en/ontap-cli/vserver-vscan-on-demand-task-show.html["指令參考資料ONTAP"^]需詳細 `vserver vscan on-demand-task show`資訊，請參閱。

+
下列命令會顯示的詳細資料 `Task1` 工作：

+
[listing]
----
cluster1::> vserver vscan on-demand-task show -instance vs1 -task-name Task1

                           Vserver: vs1
                         Task Name: Task1
                List of Scan Paths: /vol1/, /vol2/cifs/
             Report Directory Path: /report
                      Job Schedule: daily
Max File Size Allowed for Scanning: 5GB
            File Paths Not to Scan: /vol1/cold-files/
       File Extensions Not to Scan: mp3, mp4
           File Extensions to Scan: vmdk?, mp*
      Scan Files with No Extension: false
           Request Service Timeout: 5m
                    Cross Junction: true
               Directory Recursion: true
                     Scan Priority: low
                  Report Log Level: info
        Expiration Time for Report: -
----


.完成後
您必須先在SVM上啟用掃描、工作才會排程執行。
