---
permalink: revert/concept_revert_process_considerations.html 
sidebar: sidebar 
keywords: ontap, revert, limitations, issues 
summary: 在開始ONTAP 還原之前、您必須先考量還原問題和限制。 
---
= ONTAP 回復問題和限制
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
還原 ONTAP 叢集之前，您必須先考慮還原問題和限制。

* 還原會中斷營運。
+
還原期間無法進行用戶端存取。如果您要還原正式作業叢集、請務必將此中斷納入規劃。

* 還原會影響叢集中的所有節點。
+
還原作業會影響叢集中的所有節點、但是還原作業必須在每個HA配對上執行並完成、才能還原其他HA配對。

+
link:https://docs.netapp.com/us-en/ontap-afx/administer/revert-ontap.html["AFX 儲存系統"^]不支援回滾。

* 當所有節點都執行新的目標版本時、還原即告完成。
+
當叢集處於混合版本狀態時、您不應輸入任何變更叢集作業或組態的命令、除非是為了滿足還原需求；允許監控作業。

+

IMPORTANT: 如果您已經還原了部分節點，但並非全部節點，請不要嘗試將叢集升級回來源版本。

* 當您還原節點時、節點會清除Flash Cache模組中的快取資料。
+
由於Flash Cache模組中沒有快取資料、因此該節點可處理磁碟的初始讀取要求、因此在此期間會降低讀取效能。節點會在處理讀取要求時重新填入快取。

* 備份到ONTAP 執行於還原作業系統上的磁帶的LUN、只能還原至9.x版及更新版本、而不能還原至較早版本。
* 如果您目前版本ONTAP 的支援頻內ACP（IBACP）功能、而且您回復ONTAP 到不支援IBACP的版本、則磁碟櫃的替代路徑將會停用。
* 如果您的任何儲存虛擬機器（SVM）使用LDAP、則必須在還原之前停用LDAP參照。
* 在使用符合MetroCluster標準但未經MetroCluster驗證的交換器的MetroCluster IP 系統中，從ONTAP 9.7 回滾到 9.6 會造成乾擾，因為不支援使用ONTAP 9.6 及更早版本的系統。
* 在將節點還原為 ONTAP 9.13.1 或更早版本之前、您必須先將加密的 SVM 根 Volume 轉換為未加密的 Volume
+
如果您嘗試還原到不支援 SVM 根磁碟區加密的ONTAP版本，系統將發出警告並阻止復原。


