---
permalink: revert/task_enabling_and_reverting_lifs_to_home_ports_completing_post_reversion_tasks.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, downgrade, downgrading, enable, enabling, lifs, home, ports 
summary: 在重新開機期間、部分LIF可能已移轉至指派的容錯移轉連接埠。還原叢集之後、您必須啟用及還原任何不在主連接埠上的生命。 
---
= 在 ONTAP 還原後，啟用並還原至主連接埠
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在重新開機期間、部分LIF可能已移轉至指派的容錯移轉連接埠。還原 ONTAP 叢集之後，您必須啟用並還原不在其主連接埠上的任何生命。

如果主連接埠正常運作、網路介面還原命令會將目前不在主連接埠上的LIF還原回主連接埠。LIF的主連接埠是在建立LIF時指定、您可以使用network interface show命令來判斷LIF的主連接埠。

.步驟
. 顯示所有生命的狀態：
+
[source, cli]
----
network interface show
----
+
此範例顯示儲存虛擬機器（SVM）的所有LIF狀態。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001    down/down  192.0.2.120/24     node0         e0e     true
            data002    down/down  192.0.2.121/24     node0         e0f     true
            data003    down/down  192.0.2.122/24     node0         e2a     true
            data004    down/down  192.0.2.123/24     node0         e2b     true
            data005    down/down  192.0.2.124/24     node0         e0e     false
            data006    down/down  192.0.2.125/24     node0         e0f     false
            data007    down/down  192.0.2.126/24     node0         e2a     false
            data008    down/down  192.0.2.127/24     node0         e2b     false
8 entries were displayed.
----
+
如果任何生命週期顯示的狀態為「狀態管理」狀態為「關閉」或「為主目錄」狀態為「假」、請繼續下一步。

. 啟用資料生命：
+
[source, cli]
----
network interface modify {-role data} -status-admin up
----
. 將LIF還原至其主連接埠：
+
[source, cli]
----
network interface revert *
----
. 確認所有的生命都在其主連接埠中：
+
[source, cli]
----
network interface show
----
+
此範例顯示SVM vs0的所有lifs都位於其主連接埠上。

+
[listing]
----
cluster1::> network interface show -vserver vs0
            Logical    Status     Network            Current       Current Is
Vserver     Interface  Admin/Oper Address/Mask       Node          Port    Home
----------- ---------- ---------- ------------------ ------------- ------- ----
vs0
            data001      up/up    192.0.2.120/24     node0         e0e     true
            data002      up/up    192.0.2.121/24     node0         e0f     true
            data003      up/up    192.0.2.122/24     node0         e2a     true
            data004      up/up    192.0.2.123/24     node0         e2b     true
            data005      up/up    192.0.2.124/24     node1         e0e     true
            data006      up/up    192.0.2.125/24     node1         e0f     true
            data007      up/up    192.0.2.126/24     node1         e2a     true
            data008      up/up    192.0.2.127/24     node1         e2b     true
8 entries were displayed.
----


.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+interface["網路介面"^]

