---
permalink: revert/task_disabling_qtrees_in_flexgroup_volumes_before_reverting.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, disable, disabling, qtree, functionality, function, flexgroup, volumes 
summary: 不支援使用qtree for FlexGroup 0的ONTAP 功能、不支援使用於支援不支援使用的功能。您必須先停用FlexGroup 完所有的qtree功能、才能從ONTAP 還原9.3還原至ONTAP 舊版的畫面。 
---
= 還原之前、請先停用FlexGroup 完所有的qtree功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
不支援使用qtree for FlexGroup 0的ONTAP 功能、不支援使用於支援不支援使用的功能。您必須先停用FlexGroup 完所有的qtree功能、才能從ONTAP 還原9.3還原至ONTAP 舊版的畫面。

在您建立qtree或修改預設qtree的安全性樣式和oplock-mode屬性時、都會啟用qtree功能。

. 識別並刪除FlexGroup 每個啟用qtree功能的各個支援功能的所有非預設qtree：
+
.. 登入進階權限層級： `set -privilege advanced`
.. 驗證FlexGroup 是否已啟用任何具有qtree功能的支援功能。
+
對於 ONTAP 9.6 或更新版本、請使用： `volume show -is-qtree-caching-enabled true`

+
若為 ONTAP 9.5 或更早版本、請使用： `volume show -is-flexgroup-qtree-enabled true`

+
[listing]
----
cluster1::*> volume show -is-flexgroup-qtree-enabled true
Vserver   Volume       Aggregate    State      Type       Size  Available Used%
--------- ------------ ------------ ---------- ---- ---------- ---------- -----
vs0       fg           -            online     RW        320MB    220.4MB   31%
----
.. 刪除每個啟用 qtree 功能的 FlexGroup Volume 中的所有非預設 qtree ： `volume qtree delete -vserver svm_name -volume volume_name -qtree qtree_name`
+
如果qtree功能已啟用、因為您修改了預設qtree的屬性、而且沒有任何qtree、則可以跳過此步驟。

+
[listing]
----
cluster1::*> volume qtree delete -vserver vs0 -volume fg -qtree qtree4
WARNING: Are you sure you want to delete qtree qtree4 in volume fg vserver vs0?  {y|n}: y
[Job 38] Job is queued: Delete qtree qtree4 in volume fg vserver vs0.
----


. 停用每個 FlexGroup 磁碟區上的 qtree 功能： `volume flexgroup qtree-disable -vserver svm_name -volume volume_name`
+
[listing]
----
cluster1::*> volume flexgroup qtree-disable -vserver vs0 -volume fg
----
. 識別並刪除已啟用qtree功能的任何Snapshot複本。
+
.. 驗證是否已使用 qtree 功能啟用任何 Snapshot 複本： `volume snapshot show -vserver vserver_name -volume volume_name -fields is-flexgroup-qtree-enabled`
+
[listing]
----
cluster1::*> volume snapshot show -vserver vs0 -volume fg -fields is-flexgroup-qtree-enabled
vserver volume snapshot is-flexgroup-qtree-enabled
------- ------ -------- --------------------------
vs0     fg     fg_snap1 true
vs0     fg     daily.2017-09-27_0010 true
vs0     fg     daily.2017-09-28_0010 true
vs0     fg     snapmirror.0241f354-a865-11e7-a1c0-00a098a71764_2147867740.2017-10-04_124524 true
----
.. 刪除使用 qtree 功能啟用的所有 Snapshot 複本： `volume snapshot delete -vserver svm_name -volume volume_name -snapshot snapshot_name -force true -ignore-owners true`
+
必須刪除的Snapshot複本包括為SnapMirror關係所建立的一般Snapshot複本和Snapshot複本。如果FlexGroup 您已針對執行ONTAP 支援qtree FlexGroup 功能的來源供應用來源供應的來源供應區叢集、為其建立任何SnapMirror關係、則必須刪除所有在啟用此功能時所取得的Snapshot複本。

+
[listing]
----
cluster1::> volume snapshot delete -vserver vs0 -volume fg -snapshot daily.2017-09-27_0010 -force true -ignore-owners true
----




.相關資訊
link:../flexgroup/index.html["資料區管理FlexGroup"]
