---
permalink: revert/task_reverting_systems_with_deduplicated_volumes.html 
sidebar: sidebar 
keywords: ontap, revert, reverting, reversion, systems, deduplication, deduplicated, volumes 
summary: 從ONTAP 任何版本的更新版本還原之前、您必須先確保磁碟區內有足夠的可用空間、以便進行還原作業。 
---
= 驗證已刪除重複資料的磁碟區是否有足夠的可用空間、再進行還原
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP 任何版本的更新版本還原之前、您必須先確保磁碟區內有足夠的可用空間、以便進行還原作業。

磁碟區必須有足夠的空間來容納透過內嵌偵測零區塊所達成的節約效益。如需所需空間的相關資訊、請聯絡技術支援部門。

在ONTAP 啟用重複資料刪除功能的系統上、從支援功能的支援功能中恢復功能、包括執行進階模式命令。您必須聯絡技術支援部門以取得協助。

如果您已在要還原的磁碟區上啟用重複資料刪除和資料壓縮、則必須在還原重複資料刪除之前還原資料壓縮。

. 使用Volume Eff效率show命令搭配-Fields選項、即可檢視在磁碟區上執行的效率作業進度。
+
下列命令會顯示效率作業的進度：「Volume Eff期間 效率顯示-Fields vserver、volume、progress」

. 使用Volume Eff效率Stop命令搭配-all選項、即可停止所有作用中和佇列中的重複資料刪除作業。
+
下列命令會停止Volume Vola上的所有作用中和佇列的重複資料刪除作業：「Volume Effim兼 具停止功能-vserver VS1 -volume Vola -all」

. 使用set -priv榮幸 進階命令、以進階權限層級登入。
. 使用Volume Eff效率Revete-to命令搭配-version選項、將Volume的效率中繼資料降級為ONTAP 特定版本的支援。
+
下列命令會將Volume Vola上的效率中繼資料還原ONTAP 為指令檔9.x：「Volume Effive-f還原 為-vserver VS1 -volume Vola -version 9.x」

+

NOTE: Volume Eff效率Rever-to命令會還原執行此命令之節點上的磁碟區。此命令不會還原節點之間的磁碟區。

. 使用Volume Eff效率show命令搭配-op-STATUS選項、即可監控降級進度。
+
下列命令會監控並顯示降級狀態：「Volume Eff期間 效率顯示-vserver VS1 -op-Status降級」

. 如果還原失敗、請使用Volume Eff效率show命令搭配-instance選項、瞭解還原失敗的原因。
+
下列命令會顯示所有欄位的詳細資訊：「Volume Eff高效show -vserver VS1 -volume vol1 - instance」

. 還原作業完成後、請返回管理權限層級：「et -priv榮幸admin」
+
link:../volumes/index.html["邏輯儲存管理"]


