---
permalink: revert/task_download_and_install_ontap_software_image.html 
sidebar: sidebar 
keywords: ontap, software, revert, image, download, downloading, install, installing 
summary: 在恢復目前ONTAP軟體之前，您必須先下載軟體，然後安裝它。 
---
= 下載並安裝ONTAP 更新版的軟體映像
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在還原目前的 ONTAP 軟體之前，您必須先從 NetApp 支援網站下載目標軟體版本，然後再進行安裝。



== 下載 ONTAP 軟體映像

軟體映像是特定於平台機型。您必須取得適用於叢集的正確映像。NetApp 支援網站上提供適用於您平台機型的軟體映像檔、韌體版本資訊及最新韌體。軟體映像包含ONTAP 系統韌體的最新版本、在發佈特定版本的資訊時、即可取得此版本。


NOTE: 如果您要從 ONTAP 9.5 或更新版本還原具有 NetApp Volume Encryption 的系統，則必須為非受限國家 / 地區下載 ONTAP 軟體映像，其中包括 NetApp Volume Encryption 。如果您將 ONTAP 軟體映像用於受限國家 / 地區，以還原採用 NetApp Volume Encryption 的系統，系統會出現問題，您將無法存取您的磁碟區。

.步驟
. 在 link:http://mysupport.netapp.com/NOW/cgi-bin/software["軟體下載"^]NetApp 支援網站的區域中找到目標 ONTAP 軟體。
. 複製軟體映像（例如，  `97_q_image.tgz` ）來自NetApp支援站點
+
您可以將映像複製到 HTTP 伺服器或 FTP 伺服器上要提供映像的目錄，或是複製到本機資料夾。





== 安裝 ONTAP 軟體映像

從 NetApp 支援網站下載目標 ONTAP 軟體映像之後，請將其安裝在叢集節點上。

.步驟
. 將權限層級設為進階：
+
[source, cli]
----
set -privilege advanced
----
+
進階提示 (`*>`）。

. 出現提示時，輸入 `y`以繼續。
. 安裝軟體映像：
+
** 對於標準組態或雙節點 MetroCluster 組態，請輸入下列命令：
+
[source, cli]
----
system node image update -node * -package <http://example.com/downloads/image.tgz> -replace-package true -replace {image1|image2} -background true -setdefault true
----
+
此命令可同時下載並安裝所有節點上的軟體映像。若要在每個節點上一次下載並安裝映像，請勿指定 `-background`參數。此命令也會使用延伸查詢，將安裝為替代映像的目標軟體映像變更為節點的預設映像。

** 對於四節點或八節點 MetroCluster 組態，請在兩個叢集上輸入下列命令：
+
[source, cli]
----
system node image update -node * -package <http://example.com/downloads/image.tgz> -replace-package true -replace {image1|image2} -background true -setdefault false
----
+
此命令可同時下載並安裝所有節點上的軟體映像。若要在每個節點上一次下載並安裝映像，請勿指定 `-background`參數。此命令也會使用延伸查詢來變更目標軟體映像，該映像會安裝為每個節點上的替代映像。



. 輸入 `y` 以在出現提示時繼續。
. 確認軟體映像已下載並安裝在每個節點上：
+
[source, cli]
----
system node image show-update-progress -node *
----
+
此命令會顯示軟體映像下載與安裝的目前狀態。您應該繼續執行此命令，直到所有節點報告“運行狀態”為“退出”，並且“退出狀態”為“成功”。

+
系統節點映像更新命令可能會失敗、並顯示錯誤或警告訊息。解決任何錯誤或警告之後、您可以再次執行命令。

+
此範例顯示兩個節點的叢集、其中軟體映像會下載並成功安裝在兩個節點上：

+
[listing]
----
cluster1::*> system node image show-update-progress -node *
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node0.
There is no update/install in progress
Status of most recent operation:
        Run Status:     Exited
        Exit Status:    Success
        Phase:          Run Script
        Exit Message:   After a clean shutdown, image2 will be set as the default boot image on node1.
2 entries were acted on.
----


.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/system-node-image-update.html["系統節點映像更新"^]

