---
permalink: smb-admin/access-snapshot-directories-clients-smb2-concept.html 
sidebar: sidebar 
keywords: method, access, snapshot, directory, windows, client, smb, data, store, copies, copy, how to access the snapshot directory from windows clients using smb 2.x 
summary: 您使用SMB 2.x從Windows用戶端存取~snapshot目錄的方法、與SMB 1.0使用的方法不同。使用SMB 2.x連線成功存取儲存在Snapshot複本中的資料時、您必須瞭解如何存取~Snapshot目錄。 
---
= 使用SMB 2.x從Windows用戶端存取~snapshot目錄
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您用來存取的方法 `~snapshot` 使用 SMB 2.x 的 Windows 用戶端目錄與 SMB 1.0 使用的方法不同。您必須瞭解如何存取 `~snapshot` 使用 SMB 2.x 連線成功存取 Snapshot 複本中儲存的資料時的目錄。

SVM 管理員可控制 Windows 用戶端上的使用者是否可以檢視及存取 `~snapshot` 啟用或停用、即可在共用上建立目錄 `showsnapshot` 使用 vserver CIFS 共用內容系列中的命令來共用內容。

當 `showsnapshot` 共用內容已停用、使用 SMB 2.x 的 Windows 用戶端上的使用者無法檢視 `~snapshot` 目錄、無法存取中的 Snapshot 複本 `~snapshot` 目錄、即使手動輸入的路徑也沒問題 `~snapshot` 目錄或目錄中的特定 Snapshot 複本。

當 `showsnapshot` 共用內容已啟用、使用 SMB 2.x 的 Windows 用戶端上的使用者仍無法檢視 `~snapshot` 目錄位於共享區的根目錄、或位於共享區根目錄下的任何交會或目錄內。不過、連線至共用之後、使用者就可以存取隱藏的 `~snapshot` 手動附加目錄 `\~snapshot` 至共用路徑的結尾。隱藏的 `~snapshot` 目錄可從兩個入口點存取：

* 位於共用區的根目錄
* 在共享空間的每個交會點


隱藏的 `~snapshot` 無法從共享區內的非連接子目錄存取目錄。

.範例
使用下列範例所示的組態、 Windows 用戶端上有 SMB 2.x 連線至「 'eng' 」共用的使用者可以存取 `~snapshot` 手動附加目錄 `\~snapshot` 到共享區根目錄和路徑中每個連接點的共享路徑。隱藏的 `~snapshot` 目錄可從下列三個路徑存取：

* `\\vs1\eng\~snapshot`
* `\\vs1\eng\projects1\~snapshot`
* `\\vs1\eng\projects2\~snapshot`


[listing]
----
cluster1::> volume show -vserver vs1 -fields volume,junction-path
vserver volume       junction-path
------- ------------ ----------------------------------------
vs1     vs1_root      /
vs1     vs1_vol1      /eng
vs1     vs1_vol2      /eng/projects1
vs1     vs1_vol3      /eng/projects2

cluster1::> vserver cifs share show
Vserver  Share   Path     Properties    Comment  ACL
-------- ------  -------  ----------    -------- ----------
vs1      eng     /eng     oplocks       -        Everyone / Full Control
                          changenotify
                          browsable
                          showsnapshot
----