---
permalink: smb-admin/add-remove-share-properties-existing-share-task.html 
sidebar: sidebar 
keywords: customize, exist, smb, share, add, remove, removing, properties, useful, configuration, changing, change, requirement, environment, add or remove share properties on an existing smb share 
summary: 您可以新增或移除共用內容、來自訂現有的SMB共用區。如果您想要變更共用組態以符合環境中不斷變化的需求、這項功能就很有用。 
---
= 新增或移除現有 ONTAP SMB 共用上的共用內容
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以透過新增或移除共用內容來自訂現有的 SMB 共用。

可用的共用內容如下：

[cols="2,4"]
|===
| 共用內容 | 說明 


 a| 
`oplocks`
 a| 
此內容會指定共用區使用投機性鎖定、也稱為用戶端快取。



 a| 
`browsable`
 a| 
此內容可讓Windows用戶端瀏覽共用區。



 a| 
`showsnapshot`
 a| 
此內容指定用戶端可以檢視及周遊快照。



 a| 
`changenotify`
 a| 
此內容指定共用區支援變更通知要求。對於SVM上的共用、這是預設的初始屬性。



 a| 
`attributecache`
 a| 
此屬性可讓SMB共用區上的檔案屬性快取、以提供更快速的屬性存取。預設為停用屬性快取。只有當用戶端透過SMB 1.0連線至共用時、才應啟用此屬性。如果用戶端透過SMB 2.x或SMB 3.0連線至共用區、則此共用內容不適用。



 a| 
`continuously-available`
 a| 
此內容可讓支援此功能的SMB用戶端持續開啟檔案。以這種方式開啟的檔案可避免發生中斷事件、例如容錯移轉和還原。



 a| 
`branchcache`
 a| 
此內容指定共用區可讓用戶端要求此共用區內檔案的BranchCache雜湊。只有在CIFS BranchCache組態中指定「每個共用區」作為作業模式時、此選項才有用。



 a| 
`access-based-enumeration`
 a| 
此內容指定在此共用區上啟用_Access Based Enumeration_（ABE）。根據個別使用者的存取權限、使用者可以看到經過Abe篩選的共用資料夾、因此無法顯示使用者無權存取的資料夾或其他共用資源。



 a| 
`namespace-caching`
 a| 
此內容指定連線至此共用區的SMB用戶端可快取CIFS伺服器傳回的目錄列舉結果、以提供更好的效能。根據預設、SMB 1用戶端不會快取目錄列舉結果。由於SMB 2和SMB 3用戶端預設會快取目錄列舉結果、因此指定此共用內容只能為SMB 1用戶端連線提供效能優勢。



 a| 
`encrypt-data`
 a| 
此內容指定存取此共用時必須使用SMB加密。存取SMB資料時不支援加密的SMB用戶端將無法存取此共用區。

|===


[[add-share-properties-on-existing-ontap-smb-shares]]
== 在現有 ONTAP SMB 共用上新增共用內容

您可以透過新增共用屬性來自訂現有的 SMB 共用。如果您想要變更共用組態以符合環境中不斷變化的需求、這將非常實用。

.開始之前
您要修改其內容的共用區必須存在。

.關於這項工作
* 您可以使用以逗號分隔的清單來新增一或多個共用屬性。
* 您先前指定的任何共用內容都會維持有效。
+
新增的內容會附加到現有的共用內容清單中。

* 如果您為已套用至共用區的共用屬性指定新值、則新指定的值會取代原始值。
* 您無法使用移除共用內容 `vserver cifs share properties add` 命令。
+
您可以使用 `vserver cifs share properties remove` 移除共用內容的命令。



.步驟
. 新增共用內容：
+
[source, cli]
----
vserver cifs share properties add -vserver <SVM_name> -share-name <share_name> -share-properties <properties>,...
----
. 驗證共用屬性設定：
+
[source, cli]
----
vserver cifs share show -vserver vserver_name -share-name share_name
----


.範例
下列命令會新增 `showsnapshot` 在 SVM VS1 上、將屬性共用至名為「 shahre1 」的共享區：

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name share1 -share-properties showsnapshot

cluster1::> vserver cifs share show -vserver vs1
Vserver    Share   Path      Properties   Comment    ACL
---------  ------  --------  ----------   --------   -----------
vs1        share1  /share1   oplocks      -          Everyone / Full Control
                             browsable
                             changenotify
                             showsnapshot
----


[[remove-share-properties-on-existing-ontap-smb-shares]]
== 移除現有 ONTAP SMB 共用的共用內容

您可以透過移除共用屬性來自訂現有的 SMB 共用。如果您想要變更共用組態以符合環境中不斷變化的需求、這將非常實用。

.關於這項工作
* 您可以使用以逗號分隔的清單來移除一或多個共用屬性。
* 您先前已指定但未移除的任何共用內容都會維持有效。


.步驟
. 移除共用內容：
+
[source, cli]
----
vserver cifs share properties remove -vserver <SVM_name> -share-name <share_name> -share-properties <properties>,...
----
. 驗證共用屬性設定：
+
[source, cli]
----
vserver cifs share show -vserver <SVM_name> -share-name <share_name>
----


.範例
下列命令會移除 `browsable` 在 SVM VS1 上共享名爲 "shahre2" 的共享區的屬性：

[listing]
----
cluster1::> vserver cifs share properties remove -vserver vs1 -share-name share2 -share-properties browsable

cluster1::> vserver cifs share show -vserver vs1
Vserver    Share   Path      Properties   Comment    ACL
---------  ------  --------  ----------   --------   -----------
vs1        share2  /share2   oplocks      -          Everyone / Full Control
                             changenotify
----
.相關資訊
xref:commands-manage-shares-reference.adoc[管理共享的命令]
