---
permalink: smb-admin/add-ntfs-dacl-entries-security-descriptor-task.html 
sidebar: sidebar 
keywords: add, dacl, discretionary, access, control, list, access, control, entries, aces, ntfs, security, descriptor, acls, add ntfs dacl access control entries to the ntfs security 
summary: 將DACL（判別存取控制清單）存取控制項目（ACE）新增至NTFS安全性描述元、是設定及套用NTFS ACL至檔案或資料夾的第二步驟。每個項目都會識別允許或拒絕存取的物件、並定義物件可以或無法對ACE中定義的檔案或資料夾執行的操作。 
---
= 將 NTFS DACL 存取控制項目新增至 ONTAP 中的 NTFS 安全性描述元
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將DACL（判別存取控制清單）存取控制項目（ACE）新增至NTFS安全性描述元、是設定及套用NTFS ACL至檔案或資料夾的第二步驟。每個項目都會識別允許或拒絕存取的物件、並定義物件可以或無法對ACE中定義的檔案或資料夾執行的操作。

.關於這項工作
您可以將一或多個 ACE 新增至安全性描述元的 DACL 。

如果安全性描述元包含具有現有 ACE 的 DACL 、則命令會將新的 ACE 新增至 DACL 。如果安全性描述元不包含DACL、則命令會建立DACL並新增新的ACE。

您可以選擇自訂 DACL 項目、方法是指定要允許或拒絕中指定之帳戶的權限 `-account` 參數。有三種互不相容的方法可以指定權限：

* 權利
* 進階權限
* 原始權限（進階權限）


[NOTE]
====
如果您未指定 DACL 項目的權限、則預設會將權限設定為 `Full Control`。

====
您可以指定如何套用繼承、以選擇性地自訂DACL項目。

儲存層級存取保護會忽略任何選用參數的值。如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。

.步驟
. 將 DACL 項目新增至安全性描述元： `vserver security file-directory ntfs dacl add -vserver vserver_name -ntfs-sd SD_name -access-type {allow|deny} -account name_or_SIDoptional_parameters`
+
`vserver security file-directory ntfs dacl add -ntfs-sd sd1 -access-type deny -account domain\joe -rights full-control -apply-to this-folder -vserver vs1`

. 驗證 DACL 項目是否正確： `vserver security file-directory ntfs dacl show -vserver vserver_name -ntfs-sd SD_name -access-type {allow|deny} -account name_or_SID`
+
`vserver security file-directory ntfs dacl show -vserver vs1 -ntfs-sd sd1 -access-type deny -account domain\joe`

+
[listing]
----
                       Vserver: vs1
             Security Descriptor Name: sd1
                        Allow or Deny: deny
                  Account Name or SID: DOMAIN\joe
                        Access Rights: full-control
               Advanced Access Rights: -
                             Apply To: this-folder
                        Access Rights: full-control
----


如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+security+file-directory+ntfs+dacl["指令參考資料ONTAP"^]需詳細 `vserver security file-directory ntfs dacl`資訊，請參閱。
