---
permalink: smb-admin/case-sensitivity-file-directory-multiprotocol-concept.html 
sidebar: sidebar 
keywords: file, directory, name, case-sensitive, nfs, client, case-preserving, preserve, implication, multiprotocol, environment, action, case-sensitivity of file and directory names in a multiprotocol environment 
summary: 檔案和目錄名稱對NFS用戶端區分大小寫、對SMB用戶端則不區分大小寫、但大小寫保留。您必須瞭解多重傳輸協定環境的影響、以及在建立SMB共用區時指定路徑以及存取共用區內資料時、可能需要採取的行動。 
---
= 多重傳輸協定環境中檔案和目錄名稱的區分大小寫
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
檔案和目錄名稱對NFS用戶端區分大小寫、對SMB用戶端則不區分大小寫、但大小寫保留。您必須瞭解多重傳輸協定環境的影響、以及在建立SMB共用區時指定路徑以及存取共用區內資料時、可能需要採取的行動。

如果 SMB 用戶端建立名為的目錄 `testdir`， SMB 和 NFS 用戶端都會將檔案名稱顯示為 `testdir`。不過、如果 SMB 使用者稍後嘗試建立目錄名稱 `TESTDIR`，不允許使用該名稱，因爲對於 SMB 客戶端，該名稱當前存在。如果 NFS 使用者稍後建立名為的目錄 `TESTDIR`NFS 和 SMB 用戶端會以不同方式顯示目錄名稱、如下所示：

* 例如、在 NFS 用戶端上、您會看到兩個目錄名稱都是建立的 `testdir` 和 `TESTDIR`，因爲目錄名稱區分大小寫。
* SMB用戶端使用8.3名稱來區分這兩個目錄。一個目錄有基礎檔案名稱。其他目錄會指派8.3檔名。
+
** 在 SMB 用戶端上、您會看到 `testdir` 和 `TESTDI~1`。
** ONTAP 會建立 `TESTDI~1` 用於區分兩個目錄的目錄名稱。
+
在這種情況下、您必須在建立或修改儲存虛擬機器（SVM）上的共用區時、使用8.3名稱來指定共用路徑。





同樣地、如果 SMB 用戶端建立檔案 `test.txt`， SMB 和 NFS 用戶端都會將檔案名稱顯示為 `text.txt`。不過、如果 SMB 使用者稍後嘗試建立 `Test.txt`，不允許使用該名稱，因爲對於 SMB 客戶端，該名稱當前存在。如果 NFS 使用者稍後建立名為的檔案 `Test.txt`NFS 和 SMB 用戶端會以不同方式顯示檔案名稱、如下所示：

* 在 NFS 用戶端上、您會看到兩個檔案名稱都是建立的、 `test.txt` 和 `Test.txt`，因爲文件名區分大小寫。
* SMB用戶端使用8.3名稱來區分這兩個檔案。一個檔案有基礎檔案名稱。其他檔案會指派8.3檔名。
+
** 在 SMB 用戶端上、您會看到 `test.txt` 和 `TEST~1.TXT`。
** ONTAP 會建立 `TEST~1.TXT` 檔案名稱可區分這兩個檔案。




[NOTE]
====
如果您已使用vserver CIFS字元對應命令啟用或修改字元對應、則通常不區分大小寫的Windows查詢會變成區分大小寫。

====