---
permalink: smb-admin/commands-manage-servers-reference.html 
sidebar: sidebar 
keywords: command, creating, create, display, modify, stop, start, deleting, delete 
summary: 您需要知道建立、顯示、修改、停止、啟動、 和刪除SMB伺服器。也有命令可重設和重新探索伺服器、變更或重設機器帳戶密碼、排程機器帳戶密碼變更、以及新增或移除NetBios別名。 
---
= 管理 SMB 伺服器的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您需要知道建立、顯示、修改、停止、啟動、 和刪除SMB伺服器。也有命令可重設和重新探索伺服器、變更或重設機器帳戶密碼、排程機器帳戶密碼變更、以及新增或移除NetBios別名。

|===


| 如果您想要... | 使用此命令... 


 a| 
建立 SMB 伺服器
 a| 
`vserver cifs create`



 a| 
顯示SMB伺服器的相關資訊
 a| 
`vserver cifs show`



 a| 
修改 SMB 伺服器
 a| 
`vserver cifs modify`



 a| 
將SMB伺服器移至其他網域
 a| 
`vserver cifs modify`



 a| 
停止SMB伺服器
 a| 
`vserver cifs stop`



 a| 
啟動SMB伺服器
 a| 
`vserver cifs start`



 a| 
刪除 SMB 伺服器
 a| 
`vserver cifs delete`



 a| 
重設並重新探索SMB伺服器的伺服器
 a| 
`vserver cifs domain discovered-servers reset-servers`



 a| 
變更SMB伺服器的機器帳戶密碼
 a| 
`vserver cifs domain password change`



 a| 
重設SMB伺服器的機器帳戶密碼
 a| 
`vserver cifs domain password change`



 a| 
排程SMB伺服器機器帳戶的自動密碼變更
 a| 
`vserver cifs domain password schedule modify`



 a| 
新增SMB伺服器的NetBios別名
 a| 
`vserver cifs add-netbios-aliases`



 a| 
移除SMB伺服器的NetBios別名
 a| 
`vserver cifs remove-netbios-aliases`

|===
如需詳細資訊、請參閱每個命令的手冊頁。

.相關資訊
link:local-users-groups-when-deleting-servers-concept.html["刪除 SMB 伺服器時、本機使用者和群組會發生什麼情況"]
