---
permalink: smb-admin/configure-required-encryption-concept.html 
sidebar: sidebar 
keywords: smb, encryption, data, transfer, security, enhancement, enable, disable, server, configure, desire, share-by-share, basis, property, setting, configure, configure required smb encryption on smb servers for data transfer over smb 
summary: SMB加密可在SMB伺服器上啟用或停用SMB資料傳輸功能、是一項安全性增強功能。您也可以透過共用內容設定、逐一設定所需的SMB加密設定。 
---
= 瞭解 ONTAP SMB 加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SMB加密可在SMB伺服器上啟用或停用SMB資料傳輸功能、是一項安全性增強功能。您也可以透過共用內容設定、逐一設定所需的SMB加密設定。

根據預設、當您在儲存虛擬機器（ SVM ）上建立 SMB 伺服器時、 SMB 加密會停用。您必須讓IT能夠充分利用SMB加密所提供的增強安全性。

若要建立加密的SMB工作階段、SMB用戶端必須支援SMB加密。從Windows Server 2012和Windows 8開始的Windows用戶端支援SMB加密。

SVM上的SMB加密可透過兩種設定加以控制：

* SMB 伺服器安全選項、可在 SVM 上啟用功能
* SMB 共用屬性，可依每個共用區設定 SMB 加密設定


您可以決定是否要求對 SVM 上的所有資料進行加密存取，或僅要求對選定共享中的資料進行 SMB 加密存取。 `encrypt-data` 共享屬性要求 SMB 加密以存取共享。從 ONTAP 9.11.1 開始， `allow-unencrypted-access` 共享屬性允許 SMB2 用戶端在不加密的情況下存取共享，而當啟用  `encrypt-data` 時，SMB3 用戶端會繼續使用加密。

SVM 層級的設定優先於共享層級的設定。

有效的SMB加密組態取決於兩項設定的組合、如下表所述：

|===
| 啟用SMB伺服器SMB加密 | 共用加密資料設定已啟用 | 已啟用共享 allow-unencrypted-access 設定 | 伺服器端加密行為 


 a| 
是的
 a| 
錯
 a| 
錯
 a| 
SVM中的所有共用都啟用伺服器層級加密。有了這項組態、整個SMB工作階段就會進行加密。



 a| 
是的
 a| 
是的
 a| 
錯
 a| 
無論共用層級加密為何、SVM中的所有共用都會啟用伺服器層級加密。有了這項組態、整個SMB工作階段就會進行加密。



 a| 
錯
 a| 
是的
 a| 
錯
 a| 
已為特定共享啟用共享層級加密。SMB3 用戶端使用加密，但 SMB2 用戶端可以不加密存取共享，因為已啟用  `allow-unencrypted-access` 屬性。



 a| 
錯
 a| 
錯
 a| 
錯
 a| 
未啟用加密。



 a| 
錯
 a| 
錯
 a| 
是的
 a| 
未啟用任何加密。 `allow-unencrypted-access` 屬性必須在啟用 `encrypt-data` 的情況下才會生效。

|===
不支援加密的 SMB 用戶端無法連線至需要加密的 SMB 伺服器或共用區。

對加密設定的變更會對新連線生效。現有連線不受影響。


NOTE: 從 ONTAP 9.11.1 開始支援  `allow-unencrypted-access` 屬性。


NOTE: SVM 層級的 SMB 加密會覆寫共享層級的設定。
