---
permalink: smb-admin/configure-nis-ldap-name-services-svm-task.html 
sidebar: sidebar 
keywords: smb, access, map, unix, user, perform, data, ntfs, security-style, volume, windows, correspond, unix, information, nis, ldap, directory, store, name, configure nis or ldap name services on the svm 
summary: 透過SMB存取、即使存取NTFS安全型磁碟區中的資料、也會一律執行與UNIX使用者的使用者對應。如果您將Windows使用者對應至儲存在NIS或LDAP目錄存放區中的對應UNIX使用者、或是使用LDAP進行名稱對應、則應該在SMB設定期間設定這些名稱服務。 
---
= 在SVM上設定NIS或LDAP名稱服務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
透過SMB存取、即使存取NTFS安全型磁碟區中的資料、也會一律執行與UNIX使用者的使用者對應。如果您將Windows使用者對應至儲存在NIS或LDAP目錄存放區中的對應UNIX使用者、或是使用LDAP進行名稱對應、則應該在SMB設定期間設定這些名稱服務。

.開始之前
您必須自訂名稱服務資料庫組態、以符合您的名稱服務基礎架構。

.關於這項工作
SVM會使用名稱服務ns-交換器資料庫來決定查詢指定名稱服務資料庫來源的順序。ns 交換器來源可以是、 `nis`或 `ldap`的任意組合 `files`。針對Groups資料庫、ONTAP Ses庫 會嘗試從所有已設定的來源取得群組成員資格、然後使用整合的群組成員資格資訊進行存取檢查。如果其中一個來源在取得UNIX群組資訊時無法使用、ONTAP 則無法取得完整的UNIX認證、後續的存取檢查可能會失敗。因此、您必須一律在ns交換器設定中、檢查是否已針對群組資料庫設定所有的ns交換器來源。

預設是讓 SMB 伺服器將所有 Windows 使用者對應至儲存在本機中的預設 UNIX 使用者 `passwd` 資料庫。如果您想要使用預設組態、則可選擇設定NIS或LDAP UNIX使用者與群組名稱服務或LDAP使用者對應、以供SMB存取。

.步驟
. 如果UNIX使用者、群組及netgroup資訊是由NIS名稱服務管理、請設定NIS名稱服務：
+
.. 使用判斷名稱服務的目前順序 `vserver services name-service ns-switch show` 命令。
+
在此範例中、這三個資料庫 (`group`、 `passwd`和 `netgroup`） `nis` 因為名稱服務來源僅在使用中 `files` 做為來源。

+
`vserver services name-service ns-switch show -vserver vs1`

+
[listing]
----

                                               Source
Vserver         Database       Enabled         Order
--------------- ------------   ---------       ---------
vs1             hosts          true            dns,
                                               files
vs1             group          true            files
vs1             passwd         true            files
vs1             netgroup       true            files
vs1             namemap        true            files
----
+
您必須新增 `nis` 的來源 `group` 和 `passwd` 資料庫、或是選擇性的 `netgroup` 資料庫。

.. 使用調整名稱服務 nS-switch 資料庫的順序 `vserver services name-service ns-switch modify` 命令。
+
為獲得最佳效能、除非您計畫在SVM上設定名稱服務、否則不應將名稱服務新增至名稱服務資料庫。

+
如果您修改多個名稱服務資料庫的組態、則必須針對每個要修改的名稱服務資料庫分別執行命令。

+
在此範例中、 `nis` 和 `files` 設定為的來源 `group` 和 `passwd` 資料庫、依此順序。其餘的名稱服務資料庫則維持不變。

+
`vserver services name-service ns-switch modify -vserver vs1 -database group -sources nis,files` `vserver services name-service ns-switch modify -vserver vs1 -database passwd -sources nis,files`

.. 使用確認名稱服務的順序正確無誤 `vserver services name-service ns-switch show` 命令。
+
`vserver services name-service ns-switch show -vserver vs1`

+
[listing]
----

                                               Source
Vserver         Database       Enabled         Order
--------------- ------------   ---------       ---------
vs1             hosts          true            dns,
                                               files
vs1             group          true            nis,
                                               files
vs1             passwd         true            nis,
                                               files
vs1             netgroup       true            files
vs1             namemap        true            files
----
.. 建立 NIS 名稱服務組態： +
`vserver services name-service nis-domain create -vserver <vserver_name> -domain <NIS_domain_name> -servers <NIS_server_IPaddress>,...`
+
`vserver services name-service nis-domain create -vserver vs1 -domain example.com -servers 10.0.0.60`

+
[NOTE]
====
從 ONTAP 9.2 開始 `-nis-servers` 取代欄位 `-servers`。此新欄位可取得 NIS 伺服器的主機名稱或 IP 位址。

====
.. 確認 NIS 名稱服務已正確設定： `vserver services name-service nis-domain show vserver <vserver_name>`
+
`vserver services name-service nis-domain show vserver vs1`

+
[listing]
----

Vserver       Domain              Server
------------- ------------------- ---------------
vs1           example.com         10.0.0.60
----


. 如果UNIX使用者、群組及netgroup資訊或名稱對應是由LDAP名稱服務管理、請使用所在的資訊來設定LDAP名稱服務 link:../nfs-admin/index.html["NFS管理"]。

