---
permalink: smb-admin/configure-storage-level-access-guard-task.html 
sidebar: sidebar 
keywords: level, storage, access, security, provide, guard, applies, access, apply, object, protocol, volume, qtree 
summary: 在Volume或qtree上設定儲存層級存取保護時、您需要遵循許多步驟。儲存層級的存取保護可提供在儲存層級設定的存取安全性層級。它提供的安全性適用於從所有NAS傳輸協定到套用它的儲存物件的所有存取。 
---
= 在 ONTAP SMB 伺服器上設定儲存層級存取防護
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在Volume或qtree上設定儲存層級存取保護時、您需要遵循許多步驟。儲存層級的存取保護可提供在儲存層級設定的存取安全性層級。它提供的安全性適用於從所有NAS傳輸協定到套用它的儲存物件的所有存取。

.步驟
. 使用建立安全性描述元 `vserver security file-directory ntfs create` 命令。
+
`vserver security file-directory ntfs create -vserver vs1 -ntfs-sd sd1` `vserver security file-directory ntfs show -vserver vs1`

+
[listing]
----

Vserver: vs1

   NTFS Security    Owner Name
   Descriptor Name
   ------------     --------------
   sd1              -
----
+
安全性描述元會以下列四個預設DACL存取控制項目（ACE）建立：

+
[listing]
----

Vserver: vs1
  NTFS Security Descriptor Name: sd1

    Account Name     Access   Access          Apply To
                     Type     Rights
    --------------   -------  -------         -----------
    BUILTIN\Administrators
                     allow    full-control   this-folder, sub-folders, files
    BUILTIN\Users    allow    full-control   this-folder, sub-folders, files
    CREATOR OWNER    allow    full-control   this-folder, sub-folders, files
    NT AUTHORITY\SYSTEM
                     allow    full-control   this-folder, sub-folders, files
----
+
如果您不想在設定儲存層級存取保護時使用預設項目、可以在建立及新增自己的ACE至安全性描述元之前將其移除。

. 從安全性描述元中移除任何您不想設定儲存層級存取保護安全性的預設DACL ACE：
+
.. 使用移除任何不想要的 DACL ACE `vserver security file-directory ntfs dacl remove` 命令。
+
在此範例中、安全性描述元中會移除三個預設的DACL ACE：BUILTIN\Administrator、BUILTIN\Users和Creator Owners。

+
`vserver security file-directory ntfs dacl remove -vserver vs1 -ntfs-sd sd1 -access-type allow -account builtin\users` `vserver security file-directory ntfs dacl remove -vserver vs1 -ntfs-sd sd1 -access-type allow -account builtin\administrators` `vserver security file-directory ntfs dacl remove -vserver vs1 -ntfs-sd sd1 -access-type allow -account "creator owner"`

.. 請使用確認您不想用於儲存層級存取保護安全性的 DACL ACE 已從安全性描述元中移除 `vserver security file-directory ntfs dacl show` 命令。
+
在此範例中、命令的輸出會驗證安全性描述元中是否已移除三個預設的DACL ACE、只留下NT AUTORITY\SYSTEM預設的DACL ACE項目：

+
`vserver security file-directory ntfs dacl show -vserver vs1`

+
[listing]
----

Vserver: vs1
  NTFS Security Descriptor Name: sd1

    Account Name     Access   Access          Apply To
                     Type     Rights
    --------------   -------  -------         -----------
    NT AUTHORITY\SYSTEM
                     allow    full-control   this-folder, sub-folders, files
----


. 使用將一或多個 DACL 項目新增至安全性描述元 `vserver security file-directory ntfs dacl add` 命令。
+
在此範例中、安全性描述元中會新增兩個DACL ACE：

+
`vserver security file-directory ntfs dacl add -vserver vs1 -ntfs-sd sd1 -access-type allow -account example\engineering -rights full-control -apply-to this-folder,sub-folders,files` `vserver security file-directory ntfs dacl add -vserver vs1 -ntfs-sd sd1 -access-type allow -account "example\Domain Users" -rights read -apply-to this-folder,sub-folders,files`

. 使用將一或多個 SACL 項目新增至安全性描述元 `vserver security file-directory ntfs sacl add` 命令。
+
在此範例中、兩個 SACL ACE 會新增至安全性描述元：

+
`vserver security file-directory ntfs sacl add -vserver vs1 -ntfs-sd sd1 -access-type failure -account "example\Domain Users" -rights read -apply-to this-folder,sub-folders,files` `vserver security file-directory ntfs sacl add -vserver vs1 -ntfs-sd sd1 -access-type success -account example\engineering -rights full-control -apply-to this-folder,sub-folders,files`

. 使用確認 DACL 和 SACL ACE 已正確設定 `vserver security file-directory ntfs dacl show` 和 `vserver security file-directory ntfs sacl show` 命令。
+
在此範例中、下列命令會顯示安全性描述元「'shd1」的DACL項目資訊：

+
`vserver security file-directory ntfs dacl show -vserver vs1 -ntfs-sd sd1`

+
[listing]
----

Vserver: vs1
  NTFS Security Descriptor Name: sd1

    Account Name     Access   Access          Apply To
                     Type     Rights
    --------------   -------  -------         -----------
    EXAMPLE\Domain Users
                     allow    read           this-folder, sub-folders, files
    EXAMPLE\engineering
                     allow    full-control   this-folder, sub-folders, files
    NT AUTHORITY\SYSTEM
                     allow    full-control   this-folder, sub-folders, files
----
+
在此範例中、下列命令會顯示安全性描述元「'shd1'」的SACL項目相關資訊：

+
`vserver security file-directory ntfs sacl show -vserver vs1 -ntfs-sd sd1`

+
[listing]
----

Vserver: vs1
  NTFS Security Descriptor Name: sd1

    Account Name     Access   Access          Apply To
                     Type     Rights
    --------------   -------  -------         -----------
    EXAMPLE\Domain Users
                     failure  read           this-folder, sub-folders, files
    EXAMPLE\engineering
                     success  full-control   this-folder, sub-folders, files
----
. 使用建立安全性原則 `vserver security file-directory policy create` 命令。
+
以下範例建立名為「policy1'」的原則：

+
`vserver security file-directory policy create -vserver vs1 -policy-name policy1`

. 使用確認原則已正確設定 `vserver security file-directory policy show` 命令。
+
`vserver security file-directory policy show`

+
[listing]
----

   Vserver          Policy Name
   ------------     --------------
   vs1              policy1
----
. 使用將具有相關安全性描述元的工作新增至安全性原則 `vserver security file-directory policy task add` 命令 `-access-control` 參數設為 `slag`。
+
即使原則可以包含多個儲存層級的存取保護工作、您也無法將原則設定為同時包含檔案目錄和儲存層級的存取保護工作。原則必須包含所有儲存層級的存取保護工作或所有檔案目錄工作。

+
在此範例中、工作會新增至名為「policy1」的原則、該原則會指派給安全性描述元「shD1」。它會指派給 `/datavol1` 存取控制類型設為「 lag 」的路徑。

+
`vserver security file-directory policy task add -vserver vs1 -policy-name policy1 -path /datavol1 -access-control slag -security-type ntfs -ntfs-mode propagate -ntfs-sd sd1`

. 使用確認工作已正確設定 `vserver security file-directory policy task show` 命令。
+
`vserver security file-directory policy task show -vserver vs1 -policy-name policy1`

+
[listing]
----

 Vserver: vs1
  Policy: policy1

   Index  File/Folder  Access           Security  NTFS       NTFS Security
          Path         Control          Type      Mode       Descriptor Name
   -----  -----------  ---------------  --------  ---------- ---------------
   1      /datavol1    slag             ntfs      propagate  sd1
----
. 使用套用儲存層級存取保護安全性原則 `vserver security file-directory apply` 命令。
+
`vserver security file-directory apply -vserver vs1 -policy-name policy1`

+
已排程要套用安全性原則的工作。

. 使用驗證套用的儲存層級存取保護安全性設定是否正確 `vserver security file-directory show` 命令。
+
在此範例中、命令的輸出顯示儲存層級存取保護安全性已套用至 NTFS 磁碟區 `/datavol1`。即使預設的DACL允許「所有人」完全控制、儲存層級的存取保護安全性仍會限制（及稽核）存取儲存層級存取保護設定中定義的群組。

+
`vserver security file-directory show -vserver vs1 -path /datavol1`

+
[listing]
----

                Vserver: vs1
              File Path: /datavol1
      File Inode Number: 77
         Security Style: ntfs
        Effective Style: ntfs
         DOS Attributes: 10
 DOS Attributes in Text: ----D---
Expanded Dos Attributes: -
           Unix User Id: 0
          Unix Group Id: 0
         Unix Mode Bits: 777
 Unix Mode Bits in Text: rwxrwxrwx
                   ACLs: NTFS Security Descriptor
                         Control:0x8004
                         Owner:BUILTIN\Administrators
                         Group:BUILTIN\Administrators
                         DACL - ACEs
                           ALLOW-Everyone-0x1f01ff
                           ALLOW-Everyone-0x10000000-OI|CI|IO


                         Storage-Level Access Guard security
                         SACL (Applies to Directories):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                         DACL (Applies to Directories):
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-NT AUTHORITY\SYSTEM-0x1f01ff
                         SACL (Applies to Files):
                           AUDIT-EXAMPLE\Domain Users-0x120089-FA
                           AUDIT-EXAMPLE\engineering-0x1f01ff-SA
                         DACL (Applies to Files):
                           ALLOW-EXAMPLE\Domain Users-0x120089
                           ALLOW-EXAMPLE\engineering-0x1f01ff
                           ALLOW-NT AUTHORITY\SYSTEM-0x1f01ff
----


.相關資訊
xref:manage-ntfs-security-audit-policies-slag-concept.adoc[使用CLI在SVM上管理NTFS檔案安全性、NTFS稽核原則及儲存層級存取保護]

xref:workflow-config-storage-level-access-guard-concept.adoc[設定儲存層級存取保護的工作流程]

xref:display-storage-level-access-guard-task.adoc[顯示儲存層級存取保護的相關資訊]

xref:remove-storage-level-access-guard-task.adoc[移除儲存層級存取保護]
