---
permalink: smb-admin/create-branchcache-enabled-share-task.html 
sidebar: sidebar 
keywords: enable, branchcache, smb, create, share, setting, property, create a bracnhcache-enabled smb share 
summary: 您可以設定「BranchCache共用區」屬性、在建立共用區時、在SMB共用區上啟用「BranchCache」。 
---
= 建立啟用BranchCache的SMB共用區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
建立共用區時、您可以設定「BranchCache」共用區內容、在SMB共用區上啟用「BranchCache」。

.關於這項工作
* 如果在SMB共用區上啟用了BranchCache、則共用區必須將離線檔案組態設定為手動快取。
+
這是您建立共用時的預設設定。

* 您也可以在建立啟用了BranchCache的共用時指定其他選用的共用參數。
* 即使儲存虛擬機器（SVM）上未設定及啟用BranchCache、您仍可在共用區上設定「BranchCache」（BranchCache）屬性。
+
不過、如果您想要共用區提供快取內容、則必須在SVM上設定及啟用BranchCache。

* 由於使用「-share-properties」參數時、沒有套用到共用區的預設共用屬性、因此除了使用以逗號分隔的清單來指定「BranchCache」共用屬性之外、您還必須指定要套用到共用區的所有其他共用屬性。
* 如需詳細資訊、請參閱「vserver CIFS共用create」命令的手冊頁。


.步驟
. 建立啟用了BranchCache的SMB共用區：+「vserver CIFS共用區create -vserver _vserver_name_-share-name _share_name_-path _path_-share-properties BranchCache、...]
. 使用「vserver CIFS共用show」命令、確認在SMB共用區上設定了「BranchCache共用區」屬性。


下列命令會在SVM VS1上建立一個名為「dATA」的啟用了BranchCache的SMB共用區、路徑為「/data」。根據預設、離線檔案設定設為「手動」：

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name data -path /data -share-properties branchcache,oplocks,browsable,changenotify

cluster1::> vserver cifs share show -vserver vs1 -share-name data
                      Vserver: vs1
                        Share: data
     CIFS Server NetBIOS Name: VS1
                         Path: /data
             Share Properties: branchcache
                               oplocks
                               browsable
                               changenotify
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: data
                Offline Files: manual
Vscan File-Operations Profile: standard
----
xref:disable-branchcache-single-share-task.adoc[在單一SMB共用區上停用BranchCache]
