---
permalink: smb-admin/create-branchcache-enabled-share-task.html 
sidebar: sidebar 
keywords: enable, branchcache, smb, create, share, setting, property, create a bracnhcache-enabled smb share 
summary: 您可以設定「BranchCache共用區」屬性、在建立共用區時、在SMB共用區上啟用「BranchCache」。 
---
= 建立啟用 BranchCache 的 ONTAP SMB 共享
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在建立共用時、透過設定在 SMB 共用上啟用 BranchCache `branchcache` 共用屬性。

.關於這項工作
* 如果在SMB共用區上啟用了BranchCache、則共用區必須將離線檔案組態設定為手動快取。
+
這是您建立共用時的預設設定。

* 您也可以在建立啟用了BranchCache的共用時指定其他選用的共用參數。
* 您可以設定 `branchcache` 即使在儲存虛擬機器（ SVM ）上未設定和啟用 BranchCache 、也會在共用上顯示內容。
+
不過、如果您想要共用區提供快取內容、則必須在SVM上設定及啟用BranchCache。

* 因為使用時並未套用預設共用屬性至共用 `-share-properties` 參數、除了、您還必須指定要套用至共用的所有其他共用屬性 `branchcache` 使用以逗號分隔的清單來共用屬性。
* 如link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-share-create.html["指令參考資料ONTAP"^]需詳細 `vserver cifs share create`資訊，請參閱。


.步驟
. 建立啟用 BranchCache 的 SMB 共用區： +
`vserver cifs share create -vserver _vserver_name_ -share-name _share_name_ -path _path_ -share-properties branchcache[,...]`
. 使用確認 SMB 共用上的 BranchCache 共用屬性已設定 `vserver cifs share show` 命令。


.範例
下列命令會建立一個已啟用 BranchCache 的 SMB 共用，名稱為「 dATA 」，路徑為 `/data` 在 SVM VS1 上。根據預設，離線檔案設定為 `manual`：

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name data -path /data -share-properties branchcache,oplocks,browsable,changenotify

cluster1::> vserver cifs share show -vserver vs1 -share-name data
                      Vserver: vs1
                        Share: data
     CIFS Server NetBIOS Name: VS1
                         Path: /data
             Share Properties: branchcache
                               oplocks
                               browsable
                               changenotify
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: data
                Offline Files: manual
Vscan File-Operations Profile: standard
----
.相關資訊
xref:disable-branchcache-single-share-task.adoc[在單一共用上停用 BranchCache]
