---
permalink: smb-admin/determine-sessions-signed-task.html 
sidebar: sidebar 
keywords: display, information, connect, smb, session, cifs, server, sign, helpful, determining, determine, smb, client, security, setting, determine whether smb sessions are signed 
summary: 您可以在CIFS伺服器上顯示連線SMB工作階段的相關資訊。您可以使用此資訊來判斷SMB工作階段是否已簽署。這有助於判斷SMB用戶端工作階段是否與所需的安全性設定連線。 
---
= 判斷SMB工作階段是否已簽署
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在CIFS伺服器上顯示連線SMB工作階段的相關資訊。您可以使用此資訊來判斷SMB工作階段是否已簽署。這有助於判斷SMB用戶端工作階段是否與所需的安全性設定連線。

.步驟
. 執行下列其中一項動作：
+
|===
| 如果您想要顯示有關...的資訊 | 輸入命令... 


 a| 
指定儲存虛擬機器（SVM）上的所有簽署工作階段
 a| 
`vserver cifs session show -vserver _vserver_name_ -is-session-signed true`



 a| 
在SVM上具有特定工作階段ID的已簽署工作階段詳細資料
 a| 
`vserver cifs session show -vserver _vserver_name_ -session-id integer -instance`

|===


.範例
下列命令會顯示SVM VS1上已簽署工作階段的相關工作階段資訊。預設的摘要輸出不會顯示「Is Session Signed」（已簽署的工作階段）輸出欄位：

[listing]
----
cluster1::> vserver cifs session show -vserver vs1 -is-session-signed true
Node:    node1
Vserver: vs1
Connection Session                                    Open         Idle
ID          ID      Workstation      Windows User    Files         Time
----------  ------- ---------------- ------------- ------- ------------
3151272279  1       10.1.1.1         DOMAIN\joe          2          23s
----
下列命令會在工作階段ID為2的SMB工作階段上顯示詳細的工作階段資訊、包括工作階段是否已簽署：

[listing]
----
cluster1::> vserver cifs session show -vserver vs1 -session-id 2 -instance
                        Node: node1
                     Vserver: vs1
                  Session ID: 2
               Connection ID: 3151274158
Incoming Data LIF IP Address: 10.2.1.1
                 Workstation: 10.1.1.2
    Authentication Mechanism: Kerberos
                Windows User: DOMAIN\joe
                   UNIX User: pcuser
                 Open Shares: 1
                  Open Files: 1
                  Open Other: 0
              Connected Time: 10m 43s
                   Idle Time: 1m 19s
            Protocol Version: SMB3
      Continuously Available: No
           Is Session Signed: true
       User Authenticated as: domain-user
                NetBIOS Name: CIFS_ALIAS1
       SMB Encryption Status: Unencrypted
----
.相關資訊
xref:monitor-signed-session-statistics-task.adoc[監控SMB簽署的工作階段統計資料]
