---
permalink: smb-admin/determine-snapshot-copies-available-task.html 
sidebar: sidebar 
keywords: view, snapshot, copies, copy, previous, version, enable, policy, applied, apply, contain, share, previous, version, access, determine whether snapshot copies are available for previous versions use 
summary: 只有在已啟用的快照原則套用至包含共用的磁碟區，且磁碟區組態允許存取快照時，才能從「舊版」索引標籤檢視快照。判斷快照可用度有助於協助使用者存取舊版。 
---
= 確定 ONTAP SMB 快照是否可供先前版本使用
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
只有在已啟用的快照原則套用至包含共用的磁碟區，且磁碟區組態允許存取快照時，才能從「舊版」索引標籤檢視快照。判斷快照可用度有助於協助使用者存取舊版。

.步驟
. 判斷共用資料所在的磁碟區是否已啟用自動快照，以及用戶端是否可存取快照目錄： `volume show -vserver vserver-name -volume volume-name -fields vserver,volume,snapdir-access,snapshot-policy,snapshot-count`
+
輸出會顯示與磁碟區相關的快照原則，是否啟用用戶端快照目錄存取，以及可用快照的數量。

. 判斷是否已啟用相關的快照原則： `volume snapshot policy show -policy policy-name`
. 列出可用的快照： `volume snapshot show -volume volume_name`
+
如需設定及管理快照原則和快照排程的詳細資訊，請參閱link:../data-protection/index.html["資料保護"]。



.範例
以下範例顯示與名為「 data1 」的磁碟區相關的快照原則資訊，該磁碟區包含「 data1 」上的共用資料和可用快照。

[listing]
----
cluster1::> volume show -vserver vs1 -volume data1 -fields vserver,volume,snapshot-policy,snapdir-access,snapshot-count
vserver  volume snapdir-access snapshot-policy snapshot-count
-------- ------ -------------- --------------- --------------
vs1      data1  true           default         10

cluster1::> volume snapshot policy show -policy default
Vserver: cluster1
                   Number of Is
Policy Name        Schedules Enabled Comment
------------------ --------- ------- ----------------------------------
default                    3 true    Default policy with hourly, daily & weekly schedules.
    Schedule         Count     Prefix                 SnapMirror Label
    ---------------- -----     ---------------------- -------------------
    hourly               6     hourly                 -
    daily                2     daily                  daily
    weekly               2     weekly                 weekly

cluster1::> volume snapshot show -volume data1
                                                             ---Blocks---
Vserver  Volume  Snapshot                  State        Size Total% Used%
-------- ------- ------------------------- -------- -------- ------ -----
vs1      data1
                 weekly.2012-12-16_0015    valid       408KB     0%    1%
                 daily.2012-12-22_0010     valid       420KB     0%    1%
                 daily.2012-12-23_0010     valid       192KB     0%    0%
                 weekly.2012-12-23_0015    valid       360KB     0%    1%
                 hourly.2012-12-23_1405    valid       196KB     0%    0%
                 hourly.2012-12-23_1505    valid       196KB     0%    0%
                 hourly.2012-12-23_1605    valid       212KB     0%    0%
                 hourly.2012-12-23_1705    valid       136KB     0%    0%
                 hourly.2012-12-23_1805    valid       200KB     0%    0%
                 hourly.2012-12-23_1905    valid       184KB     0%    0%
----
.相關資訊
xref:create-snapshot-config-previous-versions-access-task.adoc[建立快照組態以啟用舊版存取]

link:../data-protection/index.html["資料保護"]
