---
permalink: smb-admin/disallow-users-groups-bypass-directory-traverse-task.html 
sidebar: sidebar 
keywords: user, traverse, directories, directory, path, file, permission, sechangenotifyprivilege, privilege, local, smb, group, storage, virtual, machine, svm, disallow users or groups from bypassing directory traverse checking 
summary: 如果您不希望使用者周遊檔案路徑中的所有目錄、因為使用者對周遊目錄沒有權限、您可以從儲存虛擬機器（SVM）上的本機SMB使用者或群組中移除SeChangelNotifyPrivilege權限。 
---
= 不允許使用者或群組繞過目錄周遊檢查
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您不想讓使用者周遊檔案路徑中的所有目錄、因為使用者對周遊目錄沒有權限、您可以從儲存虛擬機器（SVM）上的本機SMB使用者或群組中移除「eChangeleNotifyPrivilege」權限。

將從中移除權限的本機或網域使用者或群組必須已經存在。

當移除網域使用者或群組的權限時、ONTAP 可能會聯絡網域控制器來驗證網域使用者或群組。如果無法聯絡網域控制器、則指令可能會失敗ONTAP 。

.步驟
. 不允許略過周遊檢查：「vserver CIFS user-and -group priv榮幸remove-priv榮幸-vserver _vserver_name_-user-or -group name _name_-priv家sseChangelNotifypriv
+
此命令會將「eChangepalNotifyPrivilege」權限從本機或網域使用者或群組中移除、並以「-user-or group - name _」參數的值指定。

. 確認指定的使用者或群組已停用略過周遊檢查：「vserver CIFS user-and Groups priv榮幸 地顯示-vserver _vserver_name_（vserver CIFS使用者與群組權限）」


下列命令會禁止屬於「'example\eng'」群組的使用者略過目錄周遊檢查：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege remove-privilege -vserver vs1 -user-or-group-name EXAMPLE\eng -privileges SeChangeNotifyPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -----------------------
vs1       EXAMPLE\eng           -
----
xref:allow-users-groups-bypass-directory-traverse-task.adoc[允許使用者或群組略過目錄周遊檢查]
