---
permalink: smb-admin/display-statistics-task.html 
sidebar: sidebar 
keywords: display, various, statistic, cifs, smb, audit, branchcache, has, monitor, performance, diagnose, issue 
summary: 您可以顯示各種統計資料、包括CIFS和SMB、稽核和BranchCache雜湊的統計資料、以監控效能並診斷問題。 
---
= 顯示 ONTAP SMB 統計資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以顯示各種統計資料、包括CIFS和SMB、稽核和BranchCache雜湊的統計資料、以監控效能並診斷問題。

.開始之前
您必須使用收集資料樣本 `statistics start` 和 `statistics stop` 顯示物件相關資訊之前的命令。

詳細了解 `statistics start`和 `statistics stop`在link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=statistics["指令參考資料ONTAP"^] 。

.步驟
. 將權限層級設為進階： `set -privilege advanced`
. 執行下列其中一項動作：
+
|===
| 如果您要顯示下列項目的統計資料... | 輸入... 


 a| 
SMB的所有版本
 a| 
`statistics show -object cifs`



 a| 
SMB 1.0
 a| 
`statistics show -object smb1`



 a| 
SMB 2.x和SMB 3.0
 a| 
`statistics show -object smb2`



 a| 
節點的CIFS子系統
 a| 
`statistics show -object nblade_cifs`



 a| 
多重傳輸協定稽核
 a| 
`statistics show -object audit_ng`



 a| 
BranchCache雜湊服務
 a| 
`statistics show -object hashd`



 a| 
動態DNS
 a| 
`statistics show -object ddns_update`

|===
+
如link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["指令參考資料ONTAP"^]需詳細 `statistics show`資訊，請參閱。

. 返回管理權限層級： `set -privilege admin`


.相關資訊
* xref:determine-statistics-objects-counters-available-task.adoc[確定伺服器上可用的統計資料、物件和計數器]
* xref:monitor-signed-session-statistics-task.adoc[監控SMB簽署的工作階段統計資料]
* xref:display-branchcache-statistics-task.adoc[顯示BranchCache統計資料]
* xref:statistics-monitor-automatic-node-referral-task.adoc[使用統計資料來監控自動節點參照活動]
* link:../smb-hyper-v-sql/index.html["Microsoft Hyper-V和SQL Server的SMB組態"]
* link:../performance-config/index.html["效能監控設定"]

