---
permalink: smb-admin/enable-disable-password-complexity-local-users-task.html 
sidebar: sidebar 
keywords: password, complex, enhance, security, local, smb, user, storage, virtual, machine, svm, reenable, enable, disable, enable or disable required password complexity for local smb users 
summary: 所需的密碼複雜度可為儲存虛擬機器（SVM）上的本機SMB使用者提供更高的安全性。預設會啟用所需的密碼複雜度功能。您可以隨時停用並重新啟用。 
---
= 啟用或停用本機SMB使用者所需的密碼複雜度
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
所需的密碼複雜度可為儲存虛擬機器（SVM）上的本機SMB使用者提供更高的安全性。預設會啟用所需的密碼複雜度功能。您可以隨時停用並重新啟用。

必須在CIFS伺服器上啟用本機使用者、本機群組和本機使用者驗證。

[NOTE]
.關於這項工作
====
在工作群組模式中、您不得對CIFS伺服器使用「vserver CIFS安全性修改」命令、因為某些選項無效。

====
.步驟
. 執行下列其中一項動作：
+
|===
| 如果您想讓本機SMB使用者的密碼複雜度達到所需... | 輸入命令... 


 a| 
已啟用
 a| 
「Vserver CIFS安全性修改-vserver _vserver_name_-is密碼複雜度-required true」



 a| 
已停用
 a| 
「Vserver CIFS安全性修改-vserver _vserver_name_-is密碼複雜度-required假」

|===
. 驗證所需密碼複雜度的安全性設定：「vserver CIFS安全性show -vserver _vserver_name_」


以下範例顯示、SVM VS1的本機SMB使用者已啟用必要的密碼複雜度：

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -is-password-complexity-required true

cluster1::> vserver cifs security show -vserver vs1 -fields is-password-complexity-required
vserver is-password-complexity-required
------- -------------------------------
vs1     true
----
xref:display-server-security-settings-task.adoc[顯示有關CIFS伺服器安全性設定的資訊]

xref:local-users-groups-concepts-concept.adoc[使用本機使用者和群組進行驗證和授權]

xref:requirements-local-user-passwords-concept.adoc[本機使用者密碼需求]

xref:change-local-user-account-passwords-task.adoc[變更本機使用者帳戶密碼]
