---
permalink: smb-admin/enable-smb2-connections-domain-controllers-task.html 
sidebar: sidebar 
keywords: ontap, enable, smb, version, connect, domain, controller, default, smb2, enable smb2 connections to domain controllers 
summary: 從ONTAP 推出支援支援功能的支援功能支援使用SMB 2.0版連線至網域控制器。如果您已在網域控制器上停用SMB 1.0、就必須這麼做。從功能9.2開始ONTAP 、預設會啟用SMB2。 
---
= 啟用與網域控制器的SMB2連線
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP 推出支援支援功能的支援功能支援使用SMB 2.0版連線至網域控制器。如果您已在網域控制器上停用SMB 1.0、就必須這麼做。從功能9.2開始ONTAP 、預設會啟用SMB2。

「shMB2-enable-to-DC-connections」命令選項可讓您使用ONTAP 的版本顯示系統預設值。系統預設ONTAP 值為支援SMB 1.0、而SMB 2.0則停用。系統預設ONTAP 為適用於SMB 1.0的系統預設值為啟用、並啟用SMB 2.0。如果網域控制器一開始無法協調SMB 2.0、則會使用SMB 1.0。

SMB 1.0可從ONTAP 功能區停用至網域控制器。在支援功能9.1中ONTAP 、如果SMB 1.0已停用、則必須啟用SMB 2.0才能與網域控制器通訊。

[NOTE]
====
如果將「-SMB1-enabled for DC-connections」設為「假」、而「-SMB1-enabled」設為「真」、ONTAP 則不允許SMB 1.0連線做為用戶端、但仍接受傳入SMB 1.0連線做為伺服器。請參閱本指南中的主題_啟用和停用SMB版本_。

====
.步驟
. 在變更SMB安全性設定之前、請先確認已啟用哪些SMB版本：「vserver CIFS安全性顯示」
. 向下捲動清單以查看SMB版本。
. 使用「shMB2-enable-to-DC-connections」選項執行適當的命令。
+
|===
| 如果您想要SMB2為... | 輸入命令... 


 a| 
已啟用
 a| 
「Vserver CIFS安全性修改-vserver _vserver_name_-smb2-enable-for-DC-connections true」



 a| 
已停用
 a| 
「Vserver CIFS安全性修改-vserver _vserver_name_-smb2-enable-for-DC-connections fals'

|===


xref:supported-versions-functionality-concept.adoc[支援的SMB版本與功能]
