---
permalink: smb-admin/enable-disable-access-based-enumeration-task.html 
sidebar: sidebar 
keywords: enable, disable, access-based, enumeration, abe, smb, allow, prevent, user, permission, access, enable or disable access-based enumeration on smb shares 
summary: 您可以在SMB共用區上啟用或停用存取型列舉（ABE）、以允許或防止使用者看到他們無權存取的共用資源。 
---
= 啟用或停用SMB共用區上的存取型列舉
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在SMB共用區上啟用或停用存取型列舉（ABE）、以允許或防止使用者看到他們無權存取的共用資源。

.關於這項工作
依預設、ABE為停用狀態。

.步驟
. 執行下列其中一項動作：
+
|===
| 如果您想要... | 輸入命令... 


 a| 
在新共用區上啟用ABE
 a| 
`vserver cifs share create -vserver vserver_name -share-name share_name -path path -share-properties access-based-enumeration`     建立 SMB 共用時、您可以指定其他選用的共用設定和其他共用內容。如需詳細資訊、請參閱的手冊頁 `vserver cifs share create` 命令。



 a| 
在現有共用區上啟用ABE
 a| 
`vserver cifs share properties add -vserver vserver_name -share-name share_name -share-properties access-based-enumeration`     保留現有的共用內容。ABE共用屬性會新增至現有的共用屬性清單。



 a| 
停用現有共用區上的ABE
 a| 
`vserver cifs share properties remove -vserver vserver_name -share-name share_name -share-properties access-based-enumeration`     其他共用內容將會保留。只有ABE共用內容會從共用內容清單中移除。

|===
. 使用確認共用組態正確無誤 `vserver cifs share show` 命令。


.範例
以下範例建立名為「銷售」的 ABE SMB 共用、路徑為 `/sales` 在 SVM VS1 上。共用即會建立於 `access-based-enumeration` 做為共享內容：

[listing]
----
cluster1::> vserver cifs share create -vserver vs1 -share-name sales -path /sales  -share-properties access-based-enumeration,oplocks,browsable,changenotify

cluster1::> vserver cifs share show -vserver vs1 -share-name sales

                      Vserver: vs1
                        Share: sales
     CIFS Server NetBIOS Name: VS1
                         Path: /sales
             Share Properties: access-based-enumeration
                               oplocks
                               browsable
                               changenotify
           Symlink Properties: enable
      File Mode Creation Mask: -
 Directory Mode Creation Mask: -
                Share Comment: -
                    Share ACL: Everyone / Full Control
File Attribute Cache Lifetime: -
                  Volume Name: -
                Offline Files: manual
Vscan File-Operations Profile: standard
----
下列範例新增 `access-based-enumeration` 將內容共用至名為「 data2 」的 SMB 共用區：

[listing]
----
cluster1::> vserver cifs share properties add -vserver vs1 -share-name data2 -share-properties access-based-enumeration

cluster1::> vserver cifs share show -vserver vs1 -share-name data2 -fields share-name,share-properties
server  share-name share-properties
------- ---------- -------------------------------------------------------
vs1     data2      oplocks,browsable,changenotify,access-based-enumeration
----
.相關資訊
xref:add-remove-share-properties-existing-share-task.adoc[新增或移除現有SMB共用區上的共用內容]
