---
permalink: smb-admin/enable-disable-required-signing-incoming-traffic-task.html 
sidebar: sidebar 
keywords: enforce, requirement, client, smb, message, enabling, enable, require, sign, disable, enable or disable require smb signing for incoming smb traffic 
summary: 您可以啟用必要的SMB簽署、強制要求用戶端簽署SMB訊息。如果啟用ONTAP 、僅當SMB訊息具有有效的簽名時、才會接受該訊息。如果您想要允許SMB簽署、但不需要SMB簽署、可以停用必要的SMB簽署。 
---
= 為傳入的 SMB 流量設定 ONTAP 簽署
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以啟用必要的SMB簽署、強制要求用戶端簽署SMB訊息。如果啟用ONTAP 、僅當SMB訊息具有有效的簽名時、才會接受該訊息。如果您想要允許SMB簽署、但不需要SMB簽署、可以停用必要的SMB簽署。

.關於這項工作
預設會停用必要的SMB簽署。您可以隨時啟用或停用所需的SMB簽署。

[NOTE]
====
在下列情況下、預設不會停用SMB簽署：

. 啟用必要的SMB簽署、叢集將還原為ONTAP 不支援SMB簽署的版本。
. 叢集隨後會升級至ONTAP 支援SMB簽署的版本的支援。
+
在這種情況下、原本設定在支援版本ONTAP 的支援版本上的SMB簽署組態會透過還原及後續升級來保留。



====
當您設定儲存虛擬機器（ SVM ）災難恢復關係時、您為選取的值 `-identity-preserve` 的選項 `snapmirror create` 命令可決定在目的地 SVM 中複寫的組態詳細資料。

如果您設定 `-identity-preserve` 選項 `true` （ ID-preserve ）、 SMB 簽署安全性設定會複寫到目的地。

如果您設定 `-identity-preserve` 選項 `false` （非 ID-preserve ）、 SMB 簽署安全性設定不會複寫到目的地。在此情況下、目的地上的CIFS伺服器安全性設定會設為預設值。如果您已在來源SVM上啟用必要的SMB簽署、則必須在目的地SVM上手動啟用必要的SMB簽署。

.步驟
. 執行下列其中一項動作：
+
|===
| 如果您想要SMB簽署... | 輸入命令... 


 a| 
已啟用
 a| 
`vserver cifs security modify -vserver _vserver_name_ -is-signing-required true`



 a| 
已停用
 a| 
`vserver cifs security modify -vserver _vserver_name_ -is-signing-required false`

|===
. 判斷中的值是否已啟用或停用必要的 SMB 簽署 `Is Signing Required` 下列命令輸出中的欄位設定為所需的值： `vserver cifs security show -vserver _vserver_name_ -fields is-signing-required`


.範例
下列範例可為SVM VS1啟用必要的SMB簽署：

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -is-signing-required true

cluster1::> vserver cifs security show -vserver vs1 -fields is-signing-required
vserver  is-signing-required
-------- -------------------
vs1      true
----
[NOTE]
====
對加密設定的變更會對新連線生效。現有連線不受影響。

====