---
permalink: smb-admin/enable-disable-export-policies-task.html 
sidebar: sidebar 
keywords: enable, disable, export, policies, policy, smb, access, storage, virtual, machine, svm, control, resource, enable or disable export policies for smb access 
summary: 您可以在儲存虛擬機器（SVM）上啟用或停用SMB存取的匯出原則。您可以選擇使用匯出原則來控制SMB對資源的存取。 
---
= 啟用或停用 ONTAP 匯出策略以進行 SMB 訪問
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在儲存虛擬機器（SVM）上啟用或停用SMB存取的匯出原則。您可以選擇使用匯出原則來控制SMB對資源的存取。

.開始之前
以下是啟用SMB匯出原則的需求：

* 在您為該用戶端建立匯出規則之前，用戶端必須在 DNS 中有「 PTR 」記錄。
* 如果 SVM 提供對 NFS 用戶端的存取，而您要用於 NFS 存取的主機名稱與 CIFS 伺服器名稱不同，則需要額外的一組主機名稱「 A 」和「 PTR 」記錄。


.關於這項工作
在SVM上設定新的CIFS伺服器時、預設會停用SMB存取的匯出原則。如果您想要根據驗證傳輸協定或用戶端IP位址或主機名稱來控制存取、可以啟用SMB存取的匯出原則。您可以隨時啟用或停用SMB存取的匯出原則。


NOTE: 在啟用 NFS 的 SVM 中啟用 CIFS/SMB 的匯出原則，可讓 Linux 用戶端使用 `showmount -e` SVM 上的命令，檢視所有 SMB 磁碟區的交會路徑及相關的匯出原則規則。

.步驟
. 將權限層級設為進階： `set -privilege advanced`
. 啟用或停用匯出原則：
+
** 啟用匯出原則： `vserver cifs options modify -vserver _vserver_name_ -is-exportpolicy-enabled true`
** 停用匯出原則： `vserver cifs options modify -vserver _vserver_name_ -is-exportpolicy-enabled false`


. 返回管理權限層級： `set -privilege admin`


.範例
下列範例可讓您使用匯出原則來控制SMB用戶端對SVM VS1上資源的存取：

[listing]
----
cluster1::> set -privilege advanced
Warning: These advanced commands are potentially dangerous; use them
only when directed to do so by technical support personnel.
Do you wish to continue? (y or n): y

cluster1::*> vserver cifs options modify -vserver vs1 -is-exportpolicy-enabled true

cluster1::*> set -privilege admin
----