---
permalink: smb-admin/enable-disable-aes-encryption-kerberos-task.html 
sidebar: sidebar 
keywords: advantage, security, kerberos-based, communication, aes-256, aes-128, aes, encryption, active, directory, ad, kdc, cifs, smb 
summary: 若要利用Kerberos型通訊的最強安全性、您可以在SMB伺服器上啟用AES-256和AES-128加密。如果您不希望SMB伺服器選取AES加密類型、以便與Active Directory（AD）kdc進行Kerberos型通訊、您可以停用AES加密。預設會停用AES加密。 
---
= 啟用或停用Kerberos型通訊的AES加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要利用Kerberos型通訊的最強安全性、您可以在SMB伺服器上啟用AES-256和AES-128加密。如果您不希望SMB伺服器選取AES加密類型、以便與Active Directory（AD）kdc進行Kerberos型通訊、您可以停用AES加密。預設會停用AES加密。

.關於這項工作
從ONTAP 功能支援的9.12.1開始、AES加密會使用啟用和停用 `-advertised-enc-types` 選項、可讓您指定通告給AD Kdc的加密類型。預設設定為 `rc4` 和 `des`，但當指定AES類型時，將會啟用AES加密。您也可以使用選項來明確停用較弱的RC4和DES加密類型。在早期ONTAP 版本的版本中、您必須使用 `-is-aes-encryption-enabled` 啟用和停用AES加密的選項、無法指定加密類型。

為了增強安全性、儲存虛擬機器（SVM）會在每次修改AES安全性選項時、變更AD中的機器帳戶密碼。變更密碼可能需要包含機器帳戶的組織單位（OU）的系統管理AD認證。

如果SVM設定為無法保留身分識別的災難恢復目的地（SnapMirror組態中的「identity-preserve」選項設為「假」）、則非預設的SMB伺服器安全性設定不會複寫到目的地。如果您已在來源SVM上啟用AES加密、則必須在目的地SVM上手動啟用AES加密（在SnapMirror關係中斷後）、使目的地變成讀寫狀態。

.步驟
[role="tabbed-block"]
====
.更新版本ONTAP
--
. 執行下列其中一項動作：
+
|===
| 如果您希望Kerberos通訊的AES加密類型... | 輸入命令... 


 a| 
已啟用
 a| 
`vserver cifs security modify -vserver vserver_name -advertised-enc-types aes-128,aes-256`



 a| 
已停用
 a| 
`vserver cifs security modify -vserver vserver_name -advertised-enc-types des,rc4`

|===
+
*附註：* The `-is-aes-encryption-enabled` 選項在ONTAP 更新版本中已過時、可能會在更新版本中移除。

. 確認已視需要啟用或停用AES加密： `vserver cifs security show -vserver vserver_name -fields advertised-enc-types`


.範例
下列範例可為SVM VS1上的SMB伺服器啟用AES加密類型：

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -advertised-enc-types aes-128,aes-256

cluster1::> vserver cifs security show -vserver vs1 -fields advertised-enc-types

vserver  advertised-enc-types
-------- --------------------
vs1      aes-128,aes-256
----
下列範例可為SVM VS2上的SMB伺服器啟用AES加密類型。系統會提示系統管理員輸入包含SMB伺服器之OU的管理AD認證。

[listing]
----
cluster1::> vserver cifs security modify -vserver vs2 -advertised-enc-types aes-128,aes-256

Info: In order to enable SMB AES encryption, the password for the SMB server
machine account must be reset. Enter the username and password for the
SMB domain "EXAMPLE.COM".

Enter your user ID: administrator

Enter your password:

cluster1::> vserver cifs security show -vserver vs2 -fields advertised-enc-types

vserver  advertised-enc-types
-------- --------------------
vs2      aes-128,aes-256


----
--
.更新版本ONTAP
--
. 執行下列其中一項動作：
+
|===
| 如果您希望Kerberos通訊的AES加密類型... | 輸入命令... 


 a| 
已啟用
 a| 
「Vserver CIFS安全性修改-vserver vserver_name -is -AES-加密 啟用true」



 a| 
已停用
 a| 
「vserver CIFS安全性修改-vserver vserver_name -is -AES-加密 啟用假」

|===
. 確認已視需要啟用或停用AES加密：「vserver CIFS安全性show -vserver vserver_name -Fields is -AES-加密 啟用」
+
如果啟用AES加密、「is -AES-加密 啟用」欄位會顯示「true」、如果停用、則顯示「假」。



.範例
下列範例可為SVM VS1上的SMB伺服器啟用AES加密類型：

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -is-aes-encryption-enabled true

cluster1::> vserver cifs security show -vserver vs1 -fields is-aes-encryption-enabled

vserver  is-aes-encryption-enabled
-------- -------------------------
vs1      true
----
下列範例可為SVM VS2上的SMB伺服器啟用AES加密類型。系統會提示系統管理員輸入包含SMB伺服器之OU的管理AD認證。

[listing]
----
cluster1::> vserver cifs security modify -vserver vs2 -is-aes-encryption-enabled true

Info: In order to enable SMB AES encryption, the password for the CIFS server
machine account must be reset. Enter the username and password for the
SMB domain "EXAMPLE.COM".

Enter your user ID: administrator

Enter your password:

cluster1::> vserver cifs security show -vserver vs2 -fields is-aes-encryption-enabled

vserver  is-aes-encryption-enabled
-------- -------------------------
vs2      true
----
--
====