---
permalink: smb-admin/enable-disable-aes-encryption-kerberos-task.html 
sidebar: sidebar 
keywords: advantage, security, kerberos-based, communication, aes-256, aes-128, aes, encryption, active, directory, ad, kdc, cifs, smb 
summary: 若要利用Kerberos型通訊的最強安全性、您可以在SMB伺服器上啟用AES-256和AES-128加密。如果您不希望SMB伺服器選取AES加密類型、以便與Active Directory（AD）kdc進行Kerberos型通訊、您可以停用AES加密。預設會停用AES加密。 
---
= 啟用或停用Kerberos型通訊的AES加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要利用Kerberos型通訊的最強安全性、您可以在SMB伺服器上啟用AES-256和AES-128加密。如果您不希望SMB伺服器選取AES加密類型、以便與Active Directory（AD）kdc進行Kerberos型通訊、您可以停用AES加密。預設會停用AES加密。

.關於這項工作
為了增強安全性、儲存虛擬機器（SVM）會在每次修改AES安全性選項時、變更AD中的機器帳戶密碼。變更密碼可能需要包含機器帳戶的組織單位（OU）的系統管理AD認證。

如果SVM設定為無法保留身分識別的災難恢復目的地（SnapMirror組態中的「identity-preserve」選項設為「假」）、則非預設的SMB伺服器安全性設定不會複寫到目的地。如果您已在來源SVM上啟用AES加密、則必須在目的地SVM上手動啟用AES加密（在SnapMirror關係中斷後）、使目的地變成讀寫狀態。

.步驟
. 執行下列其中一項動作：
+
|===
| 如果您希望Kerberos通訊的AES加密類型... | 輸入命令... 


 a| 
已啟用
 a| 
「Vserver CIFS安全性修改-vserver vserver_name -is -AES-加密 啟用true」



 a| 
已停用
 a| 
「vserver CIFS安全性修改-vserver vserver_name -is -AES-加密 啟用假」

|===
. 確認已視需要啟用或停用AES加密：「vserver CIFS安全性show -vserver vserver_name -Fields is -AES-加密 啟用」
+
如果啟用AES加密、「is -AES-加密 啟用」欄位會顯示「true」、如果停用、則顯示「假」。



.範例
下列範例可為SVM VS1上的CIFS伺服器啟用AES加密類型：

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -is-aes-encryption-enabled true

cluster1::> vserver cifs security show -vserver vs1 -fields is-aes-encryption-enabled
vserver  is-aes-encryption-enabled
-------- -------------------------
vs1      true
----
下列範例可為SVM VS2上的SMB伺服器啟用AES加密類型。系統會提示系統管理員輸入包含SMB伺服器之OU的管理AD認證。

[listing]
----
cluster1::> vserver cifs security modify -vserver vs2 -is-aes-encryption-enabled true

Info: In order to enable SMB AES encryption, the password for the SMB server
machine account must be reset. Enter the username and password for the
SMB domain "EXAMPLE.COM".

Enter your user ID: administrator

Enter your password:


cluster1::> vserver cifs security show -vserver vs2 -fields is-aes-encryption-enabled
vserver  is-aes-encryption-enabled
-------- -------------------------
vs2      true
----