---
permalink: smb-admin/enable-disable-encryption-incoming-traffic-task.html 
sidebar: sidebar 
keywords: require, smb, encryption, traffic, enable, cifs, server, share, level, default, enable or disable required smb encyrption for incoming smb traffic 
summary: 如果您想為傳入的SMB流量要求SMB加密、可以在CIFS伺服器或共用層級啟用SMB加密。根據預設、不需要SMB加密。 
---
= 啟用或停用傳入流量的 ONTAP SMB 加密
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您想為傳入的SMB流量要求SMB加密、可以在CIFS伺服器或共用層級啟用SMB加密。根據預設、不需要SMB加密。

.關於這項工作
您可以在CIFS伺服器上啟用SMB加密、此功能適用於CIFS伺服器上的所有共用。如果您不希望CIFS伺服器上的所有共用都需要SMB加密、或是想要針對每個共用區的傳入SMB流量啟用必要的SMB加密、可以停用CIFS伺服器上所需的SMB加密。

當您設定儲存虛擬機器（ SVM ）災難恢復關係時、您為選取的值 `-identity-preserve` 的選項 `snapmirror create` 命令可決定在目的地 SVM 中複寫的組態詳細資料。

如果您設定 `-identity-preserve` 選項 `true` （ ID-preserve ）、 SMB 加密安全性設定會複寫到目的地。

如果您設定 `-identity-preserve` 選項 `false` （非 ID-preserve ）、 SMB 加密安全性設定不會複寫到目的地。在此情況下、目的地上的CIFS伺服器安全性設定會設為預設值。如果您已在來源SVM上啟用SMB加密、則必須在目的地上手動啟用CIFS伺服器SMB加密。

.步驟
. 執行下列其中一項動作：
+
|===
| 如果您想要CIFS伺服器上傳入SMB流量的SMB加密功能... | 輸入命令... 


 a| 
已啟用
 a| 
`vserver cifs security modify -vserver _vserver_name_ -is-smb-encryption-required true`



 a| 
已停用
 a| 
`vserver cifs security modify -vserver _vserver_name_ -is-smb-encryption-required false`

|===
. 確認 CIFS 伺服器上所需的 SMB 加密已視需要啟用或停用： `vserver cifs security show -vserver _vserver_name_ -fields is-smb-encryption-required`
+
。 `is-smb-encryption-required` 欄位隨即顯示 `true` 如果需要、會在 CIFS 伺服器和上啟用 SMB 加密 `false` 如果已停用。



.範例
下列範例為SVM VS1上的CIFS伺服器啟用必要的SMB加密功能：

[listing]
----
cluster1::> vserver cifs security modify -vserver vs1 -is-smb-encryption-required true

cluster1::> vserver cifs security show -vserver vs1 -fields is-smb-encryption-required
vserver  is-smb-encryption-required
-------- -------------------------
vs1      true
----