---
permalink: smb-admin/ipv6-connect-external-servers-concept.html 
sidebar: sidebar 
keywords: create, configuration, requirement, aware, cifs, server, ipv6, connection, external, server, how cifs servers use ipv6 to connect to external servers 
summary: 若要建立符合需求的組態、您必須瞭解CIFS伺服器在連線至外部伺服器時如何使用IPv6。 
---
= CIFS伺服器如何使用IPv6連線至外部伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要建立符合需求的組態、您必須瞭解CIFS伺服器在連線至外部伺服器時如何使用IPv6。

* 來源位址選擇
+
如果嘗試連線至外部伺服器、則選取的來源位址必須與目的地位址的類型相同。例如、如果連線至IPv6位址、則託管CIFS伺服器的儲存虛擬機器（SVM）必須具有IPv6位址的資料LIF或管理LIF、才能作為來源位址。同樣地、如果連線至IPV4位址、SVM必須具有資料LIF或管理LIF、且該資料具有可作為來源位址的IPV4位址。

* 對於使用DNS動態探索的伺服器、伺服器探索的執行方式如下：
+
** 如果叢集上停用IPv6、則只會探索到IPv6伺服器位址。
** 如果叢集上已啟用IPv6、則會同時探索IPv4和IPv6伺服器位址。視位址所屬伺服器的適用性、以及IPv6或IPv4資料或管理生命期的可用度而定、可能會使用這兩種類型。動態伺服器探索可用於探索網域控制器及其相關服務、例如LSA、NETLOGON、Kerberos及LDAP。


* DNS伺服器連線能力
+
SVM在連線至DNS伺服器時是否使用IPv6、取決於DNS名稱服務組態。如果DNS服務設定為使用IPv6位址、則會使用IPv6建立連線。如果需要、DNS名稱服務組態可以使用IPV4位址、讓DNS伺服器的連線繼續使用IPV4位址。設定DNS名稱服務時、可以指定同時使用的IPv6位址和IPv6位址。

* LDAP伺服器連線能力
+
SVM在連線至LDAP伺服器時是否使用IPv6、取決於LDAP用戶端組態。如果LDAP用戶端設定為使用IPv6位址、則會使用IPv6建立連線。如果需要、LDAP用戶端組態可以使用IPv4位址、以便連線至LDAP伺服器、繼續使用IPv4位址。設定LDAP用戶端組態時、可指定IPv6位址的組合。

+
[NOTE]
====
LDAP用戶端組態用於設定LDAP以供UNIX使用者、群組及netgroup名稱服務使用。

====
* NIS伺服器連線能力
+
SVM在連線至NIS伺服器時是否使用IPv6、取決於NIS名稱服務組態。如果NIS服務設定為使用IPv6位址、則會使用IPv6建立連線。如果需要、NIS名稱服務組態可以使用IPv4位址、以便連線至NIS伺服器時、繼續使用IPv4位址。設定NIS名稱服務時、可指定IPv6位址的組合。

+
[NOTE]
====
NIS名稱服務用於儲存及管理UNIX使用者、群組、netgroup及主機名稱物件。

====


.相關資訊
xref:enable-ipv6-task.adoc[啟用SMB的IPv6（僅限叢集管理員）]

xref:monitor-display-ipv6-sessions-task.adoc[監控及顯示IPv6 SMB工作階段的相關資訊]
