---
permalink: smb-admin/join-svm-active-directory-domain-task.html 
sidebar: sidebar 
keywords: join, storage, virtual, machine, svm, active, directory, domain, delete, deleting, exist, smb, cifs, server, modify, domain, vserver, cifs, rejoin, join a svm to an active directory domain 
summary: 您可以使用vserver CIFS modify命令修改網域、將儲存虛擬機器（SVM）加入Active Directory網域、而不刪除現有的SMB伺服器。您可以重新加入目前的網域、或加入新的網域。 
---
= 將SVM加入Active Directory網域
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用修改網域、將儲存虛擬機器（ SVM ）加入 Active Directory 網域、而無需刪除現有的 SMB 伺服器 `vserver cifs modify` 命令。您可以重新加入目前的網域、或加入新的網域。

.開始之前
* SVM必須已有DNS組態。
* SVM的DNS組態必須能夠為目標網域提供服務。
+
DNS伺服器必須包含網域LDAP和網域控制器伺服器的服務位置記錄（SRV),



.關於這項工作
* CIFS伺服器的管理狀態必須設定為「主動」、才能繼續修改Active Directory網域。
* 如果命令成功完成、系統管理狀態會自動設為「up」。
* 加入網域時、此命令可能需要幾分鐘的時間才能完成。


.步驟
. 將 SVM 加入 CIFS 伺服器網域： `vserver cifs modify -vserver _vserver_name_ -domain _domain_name_ -status-admin down`
+
如需詳細資訊、請參閱的手冊頁 `vserver cifs modify` 命令。如果您需要重新設定新網域的 DNS 、請參閱的手冊頁 `vserver dns modify` 命令。

+
若要為 SMB 伺服器建立 Active Directory 機器帳戶、您必須提供具有足夠權限的 Windows 帳戶名稱和密碼、以便將電腦新增至 `ou= _example_ ou` 中的容器 `_example_`.com 網域。

+
從ONTAP 功能更新9.7開始、AD管理員可以提供Keytab檔案的URI、作為提供權限Windows帳戶名稱和密碼的替代方案。當您收到 URI 時、請將其加入 `-keytab-uri` 參數 `vserver cifs` 命令。

. 確認 CIFS 伺服器位於所需的 Active Directory 網域： `vserver cifs show`


.範例
在下列範例中、SVM VS1上的SMB伺服器「'CIFSSERVER1'」會使用Keytab驗證加入example.com網域：

[listing]
----

cluster1::> vserver cifs modify -vserver vs1 -domain example.com -status-admin down -keytab-uri http://admin.example.com/ontap1.keytab

cluster1::> vserver cifs show

          Server       Status       Domain/Workgroup  Authentication
Vserver   Name         Admin        Name              Style
--------- -----------  ---------    ----------------  --------------
vs1       CIFSSERVER1  up           EXAMPLE          domain
----