---
permalink: smb-admin/join-svm-active-directory-domain-task.html 
sidebar: sidebar 
keywords: join, storage, virtual, machine, svm, active, directory, domain, delete, deleting, exist, smb, cifs, server, modify, domain, vserver, cifs, rejoin, join a svm to an active directory domain 
summary: 您可以使用vserver CIFS modify命令修改網域、將儲存虛擬機器（SVM）加入Active Directory網域、而不刪除現有的SMB伺服器。您可以重新加入目前的網域、或加入新的網域。 
---
= 將SVM加入Active Directory網域
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「vserver CIFS modify」命令修改網域、將儲存虛擬機器（SVM）加入Active Directory網域、而不需刪除現有的SMB伺服器。您可以重新加入目前的網域、或加入新的網域。

.開始之前
* SVM必須已有DNS組態。
* SVM的DNS組態必須能夠為目標網域提供服務。
+
DNS伺服器必須包含網域LDAP和網域控制器伺服器的服務位置記錄（SRV),



.關於這項工作
* CIFS伺服器的管理狀態必須設定為「主動」、才能繼續修改Active Directory網域。
* 如果命令成功完成、系統管理狀態會自動設為「up」。
* 加入網域時、此命令可能需要幾分鐘的時間才能完成。


.步驟
. 將SVM加入CIFS伺服器網域：「vserver CIFS modify -vserver _vserver_name_-domain_name_-stue-admin down」
+
如需詳細資訊、請參閱「vserver CIFS modify」命令的手冊頁。如果您需要重新設定新網域的DNS、請參閱「vserver DNS modify」命令的手冊頁。

+
若要建立SMB伺服器的Active Directory機器帳戶、您必須提供Windows帳戶的名稱和密碼、並具有足夠的權限、以便將電腦新增至「_example _」（範例_）.com網域內的「ou=_example _ ou」（範例_）容器。

+
從ONTAP 功能更新9.7開始、AD管理員可以提供Keytab檔案的URI、作為提供權限Windows帳戶名稱和密碼的替代方案。當您收到URI時、請在「-keytab-uri」參數中加入「vserver CIFS」命令。

. 確認CIFS伺服器位於所需的Active Directory網域：「vserver CIFS show」


在下列範例中、SVM VS1上的SMB伺服器「'CIFSSERVER1'」會使用Keytab驗證加入example.com網域：

[listing]
----

cluster1::> vserver cifs modify -vserver vs1 -domain example.com -status-admin down -keytab-uri http://admin.example.com/ontap1.keytab

cluster1::> vserver cifs show

          Server       Status       Domain/Workgroup  Authentication
Vserver   Name         Admin        Name              Style
--------- -----------  ---------    ----------------  --------------
vs1       CIFSSERVER1  up           EXAMPLE          domain
----