---
permalink: smb-admin/local-users-groups-concepts-concept.html 
sidebar: sidebar 
keywords: local, user, group, basic, information, determine, determining, configure, environment, local users and groups concepts 
summary: 您應該先知道哪些是本機使用者和群組、以及這些使用者和群組的一些基本資訊、然後再決定是否要在環境中設定及使用本機使用者和群組。 
---
= 了解本機 ONTAP SMB 使用者和群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該先知道哪些是本機使用者和群組、以及這些使用者和群組的一些基本資訊、然後再決定是否要在環境中設定及使用本機使用者和群組。

* *本機使用者*
+
具有唯一安全性識別碼（SID）的使用者帳戶、只有在建立該帳戶的儲存虛擬機器（SVM）上才具有可見度。本機使用者帳戶具有一組屬性、包括使用者名稱和SID。本機使用者帳戶會使用NTLM驗證、在CIFS伺服器上進行本機驗證。

+
使用者帳戶有多種用途：

+
** 用於授予_使用者權限管理_權限給使用者。
** 用於控制SVM擁有之檔案和資料夾資源的共用層級和檔案層級存取。


* *本機群組*
+
具有唯一SID的群組只能在建立該群組的SVM上看到。群組包含一組成員。成員可以是本機使用者、網域使用者、網域群組和網域機器帳戶。可以建立、修改或刪除群組。

+
群組有多種用途：

+
** 用於授予_使用者權限管理_權限給其成員。
** 用於控制SVM擁有之檔案和資料夾資源的共用層級和檔案層級存取。


* *本機網域*
+
具有本機範圍的網域、受SVM限制。本機網域名稱為CIFS伺服器名稱。本機使用者和群組包含在本機網域內。

* *安全性識別碼（SID*）
+
SID是可識別Windows型安全性主體的可變長度數值。例如、一般的SID格式如下：s-1-5-21-3136354847-3130905135-2517279418-123456。

* * NTLM驗證*
+
一種Microsoft Windows安全性方法、用於驗證CIFS伺服器上的使用者。

* *叢集複寫資料庫（RDB）*
+
叢集中每個節點上都有執行個體的複寫資料庫。本機使用者和群組物件會儲存在RDB中。





[[reasons-for-creating-local-ontap-smb-users-and-local-groups]]
== 建立本機 ONTAP SMB 使用者和本機群組的原因

在您的儲存虛擬機器（SVM）上建立本機使用者和本機群組的理由有好幾種。例如、如果網域控制器（DC）無法使用、您可能想要使用本機群組來指派權限、或SMB伺服器位於工作群組中、您可以使用本機使用者帳戶來存取SMB伺服器。

您可以基於下列理由建立一或多個本機使用者帳戶：

* 您的SMB伺服器位於工作群組中、網域使用者無法使用。
+
工作群組組組態需要本機使用者。

* 如果網域控制器無法使用、您希望能夠驗證並登入SMB伺服器。
+
本機使用者可以在網域控制器當機或網路問題使SMB伺服器無法連絡網域控制器時、使用NTLM驗證來驗證SMB伺服器。

* 您想要指派_使用者權限管理_權限給本機使用者。
+
_使用者權限管理_是SMB伺服器管理員控制使用者和群組在SVM上擁有哪些權限的能力。您可以將權限指派給使用者帳戶、或是將使用者設為具有這些權限的本機群組成員、藉此指派權限給使用者。



您可以基於下列理由建立一或多個本機群組：

* 您的SMB伺服器位於工作群組中、而且網域群組無法使用。
+
工作群組組組態不需要本機群組、但這些群組對於管理本機工作群組使用者的存取權限非常有用。

* 您想要使用本機群組來控制檔案和資料夾資源的存取、以進行共用和檔案存取控制。
* 您想要使用自訂的_使用者權限管理_權限來建立本機群組。
+
某些內建使用者群組具有預先定義的權限。若要指派一組自訂的權限、您可以建立本機群組、並將必要的權限指派給該群組。然後您可以將本機使用者、網域使用者和網域群組新增至本機群組。



.相關資訊
* xref:local-user-authentication-concept.adoc[了解本地用戶身份驗證]
* xref:list-supported-privileges-reference.html[支援的權限清單]

