---
permalink: smb-admin/manage-local-privileges.html 
sidebar: sidebar 
keywords: manage, right, user, local, domain, add, privilege, override, default, object, enhance, customize, user, group, add privileges to local or domain users or groups 
summary: 您可以新增權限來管理本機或網域使用者或群組的使用者權限。新增的權限會覆寫指派給任何這些物件的預設權限。這可讓您自訂使用者或群組擁有的權限、進而增強安全性。 
---
= 管理 ONTAP SMB 本機或網域使用者或群組的權限
:allow-uri-read: 
:icons: font
:imagesdir: ../media/




[[add-privileges-to-ontap-smb-local-or-domain-users-or-groups]]
== 向 ONTAP SMB 本機或網域使用者或群組新增權限

您可以新增權限來管理本機或網域使用者或群組的使用者權限。新增的權限會覆寫指派給任何這些物件的預設權限。這可讓您自訂使用者或群組擁有的權限、進而增強安全性。

.開始之前
要新增權限的本機或網域使用者或群組必須已經存在。

.關於這項工作
新增權限至物件會覆寫該使用者或群組的預設權限。新增權限並不會移除先前新增的權限。

新增權限給本機或網域使用者或群組時、必須謹記下列事項：

* 您可以新增一或多個權限。
* 將權限新增至網域使用者或群組時ONTAP 、可能會聯絡網域控制器來驗證網域使用者或群組。
+
如果無法聯絡網域控制器、則指令可能會失敗ONTAP 。



.步驟
. 將一或多個權限新增至本機或網域使用者或群組：
+
[source, cli]
----
vserver cifs users-and-groups privilege add-privilege -vserver <SVM_name> -user-or-group-name <name> -privileges <privilege>[,...]
----
. 確認所需的權限已套用至該物件：
+
[source, cli]
----
vserver cifs users-and-groups privilege show -vserver <SVM_name> -user-or-group-name <name>
----


.範例
以下範例將「'eTcbprivre'」和「'eTakeOwnershipprivatef'」權限新增至儲存虛擬機器（SVM、先前稱為Vserver）VS1上的使用者「'CIFs_Server\sue'」：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege add-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue -privileges SeTcbPrivilege,SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege
----


[[remove-privileges-from-ontap-smb-local-or-domain-users-or-groups]]
== 刪除 ONTAP SMB 本機或網域使用者或群組的權限

您可以移除權限、來管理本機或網域使用者或群組的使用者權限。這可讓您自訂使用者和群組擁有的最大權限、進而增強安全性。

.開始之前
將從中移除權限的本機或網域使用者或群組必須已經存在。

.關於這項工作
在移除本機或網域使用者或群組的權限時、您必須謹記下列事項：

* 您可以移除一或多個權限。
* 當移除網域使用者或群組的權限時、ONTAP 可能會聯絡網域控制器來驗證網域使用者或群組。
+
如果無法聯絡網域控制器、則指令可能會失敗ONTAP 。



.步驟
. 從本機或網域使用者或群組移除一或多個權限：
+
[source, cli]
----
vserver cifs users-and-groups privilege remove-privilege -vserver <SVM_name> -user-or-group-name <name> -privileges <privilege>[,...]
----
. 確認已從物件中移除所需的權限：
+
[source, cli]
----
vserver cifs users-and-groups privilege show -vserver <SVM_name> -user-or-group-name <name>
----


.範例
下列範例移除儲存虛擬機器（SVM、前身為Vserver）VS1上使用者「'CIFs_Server\sue」的「'eTcbprivre'」和「'eTakeOwnershipprivatef'」權限：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege remove-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue -privileges SeTcbPrivilege,SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver   User or Group Name    Privileges
--------- --------------------- -------------------
vs1       CIFS_SERVER\sue       -
----


[[reset-privileges-for-ontap-smb-local-or-domain-users-and-groups]]
== 重設 ONTAP SMB 本機或網域使用者和群組的權限

您可以重設本機或網域使用者和群組的權限。當您已修改本機或網域使用者或群組的權限、而且不再需要或需要這些修改時、此功能就很有用。

.關於這項工作
重設本機或網域使用者或群組的權限、會移除該物件的任何權限項目。

.步驟
. 重設本機或網域使用者或群組的權限：
+
[source, cli]
----
vserver cifs users-and-groups privilege reset-privilege -vserver <SVM_name> -user-or-group-name <name>
----
. 確認物件的權限已重設：
+
[source, cli]
----
vserver cifs users-and-groups privilege show -vserver <SVM_name> -user-or-group-name <name>
----


.範例
下列範例會重設儲存虛擬機器（SVM、先前稱為Vserver）VS1上使用者「'CIFs_Server\sue」的權限。根據預設、一般使用者沒有與其帳戶相關的權限：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show
Vserver   User or Group Name    Privileges
--------- --------------------- ---------------
vs1       CIFS_SERVER\sue       SeTcbPrivilege
                                SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege reset-privilege -vserver vs1 -user-or-group-name CIFS_SERVER\sue

cluster1::> vserver cifs users-and-groups privilege show
This table is currently empty.
----
下列範例會重設群組「'BUILTIN\管理員'」的權限、有效移除權限項目：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show
Vserver   User or Group Name       Privileges
--------- ------------------------ -------------------
vs1       BUILTIN\Administrators   SeRestorePrivilege
                                   SeSecurityPrivilege
                                   SeTakeOwnershipPrivilege

cluster1::> vserver cifs users-and-groups privilege reset-privilege -vserver vs1 -user-or-group-name BUILTIN\Administrators

cluster1::> vserver cifs users-and-groups privilege show
This table is currently empty.
----


[[display-information-about-ontap-smb-privilege-overrides]]
== 顯示有​​關 ONTAP SMB 權限覆蓋的信息

您可以顯示指派給網域或本機使用者帳戶或群組的自訂權限相關資訊。此資訊可協助您判斷是否套用所需的使用者權限。

.步驟
. 執行下列其中一項動作：
+
|===
| 如果您想要顯示有關...的資訊 | 輸入此命令... 


 a| 
儲存虛擬機器（SVM）上所有網域和本機使用者和群組的自訂權限
 a| 
`vserver cifs users-and-groups privilege show -vserver <SVM_name>`



 a| 
自訂SVM上特定網域或本機使用者和群組的權限
 a| 
`vserver cifs users-and-groups privilege show -vserver <SVM_name> -user-or-group-name <name>`

|===
+
您可以在執行此命令時選擇其他選用參數。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-cifs-users-and-groups-privilege-show.html["指令參考資料ONTAP"^]需詳細 `vserver cifs users-and-groups privilege show`資訊，請參閱。



.範例
下列命令會顯示明確與SVM VS1的本機或網域使用者和群組相關聯的所有權限：

[listing]
----
cluster1::> vserver cifs users-and-groups privilege show -vserver vs1
Vserver    User or Group Name     Privileges
--------- ---------------------   ---------------
vs1       BUILTIN\Administrators  SeTakeOwnershipPrivilege
                                  SeRestorePrivilege
vs1       CIFS_SERVER\sue         SeTcbPrivilege
                                  SeTakeOwnershipPrivilege
----