---
permalink: smb-admin/manage-local-user-accounts.html 
sidebar: sidebar 
keywords: modify, local, user, account, change, exist, name, description, enable, disable, rename, compromise, administrative, modify local user accounts 
summary: 您可以啟用本機使用者帳戶以允許透過 SMB 存取 SVM 資料，或停用該帳戶以阻止存取。您也可以修改帳戶以更新使用者的全名、描述或啟用狀態。如有需要，您可以出於管理原因（例如使用者名稱外洩）重新命名帳戶。您還可以查看使用者所屬的本機群組，這有助於確定檔案和資料夾存取並排查存取問題。 
---
= 管理本機 ONTAP SMB 使用者帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以啟用本機使用者帳戶以允許透過 SMB 存取 SVM 資料，或停用該帳戶以阻止存取。您也可以修改帳戶以更新使用者的全名、描述或啟用狀態。如有需要，您可以出於管理原因（例如使用者名稱外洩）重新命名帳戶。您還可以查看使用者所屬的本機群組，這有助於確定檔案和資料夾存取並排查存取問題。

|===
| 如果您想要... | 輸入命令... 


 a| 
變更本機使用者的密碼
 a| 
`vserver cifs users-and-groups local-user set-password -vserver <SVM_name> -user-name <user_name>`



 a| 
啟用或停用本機使用者帳戶
 a| 
`vserver cifs users-and-groups local-user modify -vserver <SVM_name> -user-name <user_name> -is-account-disabled {true|false}`



 a| 
顯示使用者的詳細帳戶資訊
 a| 
`vserver cifs users-and-groups local-user show -instance -vserver <SVM_name> -user-name <user_name>`



 a| 
顯示指定本機使用者的本機使用者成員資格資訊
 a| 
`vserver cifs users-and-groups local-user show-membership -user-name <user_name>`



 a| 
顯示本機使用者所屬本機群組的本機使用者成員資格資訊
 a| 
`vserver cifs users-and-groups local-user show-membership -membership _group_name_`



 a| 
顯示與指定儲存虛擬機器（SVM）相關聯之本機使用者的使用者成員資格資訊
 a| 
`vserver cifs users-and-groups local-user show-membership -vserver <SVM_name>`



 a| 
顯示指定SVM上所有本機使用者的詳細資訊
 a| 
`vserver cifs users-and-groups local-user show-membership -instance -vserver <SVM_name>`



 a| 
顯示儲存虛擬機器（SVM）上所有使用者的相關資訊
 a| 
`vserver cifs users-and-groups local-user show -vserver <SVM_name>`



 a| 
修改本機使用者的說明
 a| 
`vserver cifs users-and-groups local-user modify -vserver <SVM_name> -user-name <user_name> -description text`

如果說明包含空格，則必須用雙引號括住。



 a| 
修改本機使用者的全名
 a| 
`vserver cifs users-and-groups local-user modify -vserver <SVM_name> -user-name <user_name> -full-name text`

如果全名包含空格，則必須用雙引號括起來。



 a| 
重新命名本機使用者帳戶
 a| 
`vserver cifs users-and-groups local-user rename -vserver <SVM_name> -user-name <user_name> -new-user-name <new_user_name>`

重新命名本機使用者時，新使用者名稱必須與舊使用者名稱關聯到同一個 CIFS 伺服器。

|===
.範例
下列範例將儲存虛擬機器（SVM、先前稱為Vserver）VS1上的本機使用者「'CIFs_Server\sue」重新命名為「'CIFS伺服器\ sue新'」：

[listing]
----
cluster1::> vserver cifs users-and-groups local-user rename -user-name CIFS_SERVER\sue -new-user-name CIFS_SERVER\sue_new -vserver vs1
----
.範例
下列範例顯示SVM VS1上所有本機使用者的相關資訊：

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver  User Name                   Full Name     Description
-------- --------------------------- ------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith   Built-in administrator account
vs1      CIFS_SERVER\sue             Sue   Jones
----
.範例
下列範例設定與儲存虛擬機器（SVM、先前稱為Vserver）VS1相關之本機使用者「'CIFS/Server\sue」的密碼：

[listing]
----
cluster1::> vserver cifs users-and-groups local-user set-password -user-name CIFS_SERVER\sue -vserver vs1

Enter the new password:
Confirm the new password:
----
.範例
以下範例顯示SVM VS1上所有本機使用者的成員資格資訊；使用者「CIFS伺服器管理員」是「BUILTIN\Administrators」群組的成員、而「CIFS伺服器\ sue」是「CIFS伺服器\ g1`」群組的成員：

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show-membership -vserver vs1
Vserver    User Name                    Membership
---------- ---------------------------- ------------------------
vs1        CIFS_SERVER\Administrator    BUILTIN\Administrators
           CIFS_SERVER\sue              CIFS_SERVER\g1
----
.相關資訊
* 如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs["指令參考資料ONTAP"^]需詳細 `vserver cifs`資訊，請參閱。
* xref:enable-disable-password-complexity-local-users-task.adoc[設定本地用戶的密碼複雜度]
* xref:display-server-security-settings-task.adoc[顯示有​​關伺服器安全設定的信息]




[[delete-local-ontap-smb-user-accounts]]
== 刪除本機 ONTAP SMB 使用者帳戶

如果不再需要本機SMB驗證CIFS伺服器、或決定SVM所含資料的存取權限、您可以從儲存虛擬機器（SVM）刪除本機使用者帳戶。

.關於這項工作
刪除本機使用者時、請謹記下列事項：

* 檔案系統不會變更。
+
不會調整參照此使用者之檔案和目錄上的Windows安全性描述元。

* 所有對本機使用者的參照都會從成員資格和權限資料庫中移除。
* 標準且知名的使用者（例如Administrator）無法刪除。


.步驟
. 確定要刪除的本機使用者帳戶名稱：
+
[source, cli]
----
vserver cifs users-and-groups local-user show -vserver <SVM_name>
----
. 刪除本機使用者：
+
[source, cli]
----
vserver cifs users-and-groups local-user delete -vserver <SVM_name> -user-name <user_name>
----
. 確認使用者帳戶已刪除：
+
[source, cli]
----
vserver cifs users-and-groups local-user show -vserver <SVM_name>
----


下列範例會刪除與SVM VS1相關聯的本機使用者「'CIFS/Server\sue」：

[listing]
----
cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver  User Name                   Full Name      Description
-------- --------------------------- -------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith    Built-in administrator account
vs1      CIFS_SERVER\sue             Sue   Jones


cluster1::> vserver cifs users-and-groups local-user delete -vserver vs1 -user-name CIFS_SERVER\sue

cluster1::> vserver cifs users-and-groups local-user show -vserver vs1
Vserver      User Name                   Full Name      Description
-------- --------------------------- -------------- -------------
vs1      CIFS_SERVER\Administrator   James Smith    Built-in administrator account
----