---
permalink: smb-admin/monitor-signed-session-statistics-task.html 
sidebar: sidebar 
keywords: monitor, smb, session, statistic, establish, sign, monitor smb signed session statistics 
summary: 您可以監控SMB工作階段統計資料、並判斷哪些已建立的工作階段已簽署、哪些尚未簽署。 
---
= 監控 ONTAP SMB 簽署的工作階段統計資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以監控SMB工作階段統計資料、並判斷哪些已建立的工作階段已簽署、哪些尚未簽署。

.關於這項工作
。 `statistics` 進階權限層級的命令提供 `signed_sessions` 可用來監控已簽署 SMB 工作階段數量的計數器。。 `signed_sessions` 下列統計資料物件可使用計數器：

* `cifs` 可讓您監控所有 SMB 工作階段的 SMB 簽署。
* `smb1` 可讓您監控 SMB 1.0 工作階段的 SMB 簽署。
* `smb2` 可讓您監控 SMB 2.x 和 SMB 3.0 工作階段的 SMB 簽署。
+
的輸出中包含 SMB 3.0 統計資料 `smb2` 物件：



如果您想要比較已簽署工作階段的數目與工作階段總數、您可以比較的輸出 `signed_sessions` 以的輸出進行計數 `established_sessions` 計數器。

您必須先開始收集統計資料樣本、才能檢視結果資料。如果不停止資料收集、您可以檢視範例中的資料。停止資料收集可提供固定的範例。不停止資料收集可讓您取得更新的資料、以便與先前的查詢進行比較。這項比較可協助您識別趨勢。

.步驟
. 將權限等級設為進階： +
`set -privilege advanced`
. 開始資料收集：+
`statistics start -object {cifs|smb1|smb2} -instance instance -sample-id _sample_ID_ [-node _node_name_]`
+
如果您未指定 `-sample-id` 參數、命令會為您產生範例識別碼、並將此範例定義為 CLI 工作階段的預設範例。的價值 `-sample-id` 為文字字串。如果您在相同的CLI工作階段中執行此命令、但未指定 `-sample-id` 參數時、命令會覆寫先前的預設範例。

+
您可以選擇性地指定要收集統計資料的節點。如果您未指定節點、範例會收集叢集中所有節點的統計資料。

. 使用 `statistics stop` 停止收集樣本資料的命令。
. 檢視SMB簽署統計資料：
+
|===
| 如果您要檢視下列項目的資訊... | 輸入... 


 a| 
已簽署的工作階段
 a| 
`show -sample-id sample_ID -counter signed_sessions|_node_name_ [-node _node_name_]`



 a| 
已簽署的工作階段和已建立的工作階段
 a| 
`show -sample-id _sample_ID_ -counter signed_sessions|established_sessions|_node_name_ [-node node_name]`

|===
+
如果您只想顯示單一節點的資訊、請指定選用項目 `-node` 參數。

. 返回管理權限層級： +
`set -privilege admin`


.範例
[%collapsible]
====
以下範例說明如何監控儲存虛擬機器（SVM）VS1上的SMB 2.x和SMB 3.0簽署統計資料。

下列命令會移至進階權限層級：

[listing]
----
cluster1::> set -privilege advanced

Warning: These advanced commands are potentially dangerous; use them only when directed to do so by support personnel.
Do you want to continue? {y|n}: y
----
下列命令會啟動新範例的資料收集：

[listing]
----
cluster1::*> statistics start -object smb2 -sample-id smbsigning_sample -vserver vs1
Statistics collection is being started for Sample-id: smbsigning_sample
----
下列命令會停止範例的資料收集：

[listing]
----
cluster1::*> statistics stop -sample-id smbsigning_sample
Statistics collection is being stopped for Sample-id: smbsigning_sample
----
下列命令會顯示已簽署的SMB工作階段、以及範例中各節點所建立的SMB工作階段：

[listing]
----
cluster1::*> statistics show -sample-id smbsigning_sample -counter signed_sessions|established_sessions|node_name

Object: smb2
Instance: vs1
Start-time: 2/6/2013 01:00:00
End-time: 2/6/2013 01:03:04
Cluster: cluster1

    Counter                                              Value
    -------------------------------- -------------------------
    established_sessions                                     0
    node_name                                           node1
    signed_sessions                                          0
    established_sessions                                     1
    node_name                                           node2
    signed_sessions                                          1
    established_sessions                                     0
    node_name                                           node3
    signed_sessions                                          0
    established_sessions                                     0
    node_name                                           node4
    signed_sessions                                          0
----
以下命令顯示節點2的簽署SMB工作階段：

[listing]
----
cluster1::*> statistics show -sample-id smbsigning_sample -counter signed_sessions|node_name -node node2

Object: smb2
Instance: vs1
Start-time: 2/6/2013 01:00:00
End-time: 2/6/2013 01:22:43
Cluster: cluster1

    Counter                                              Value
    -------------------------------- -------------------------
    node_name                                            node2
    signed_sessions                                          1
----
下列命令會移回管理權限層級：

[listing]
----
cluster1::*> set -privilege admin
----
====
.相關資訊
* xref:determine-sessions-signed-task.adoc[判斷SMB工作階段是否已簽署]
* link:../performance-admin/index.html["效能監控與管理總覽"]
* link:https://docs.netapp.com/us-en/ontap-cli/statistics-show.html["統計數據顯示"^]

