---
permalink: smb-admin/mount-unmount-existing-volumes-nas-namespace-task.html 
sidebar: sidebar 
keywords: volume, mount, nas, namespace, configure, client, access, data, contain, storage, virtual, machine, svm, junction, point, mount, unmount, mount or unmount existing volumes in the nas namespace 
summary: 磁碟區必須先掛載到NAS命名空間、才能設定NAS用戶端存取儲存虛擬機器（SVM）磁碟區中所含的資料。如果目前未掛載磁碟區、您可以將其掛載至交會點。您也可以卸載Volume。 
---
= 掛載或卸載NAS命名空間中的現有磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
磁碟區必須先掛載到NAS命名空間、才能設定NAS用戶端存取儲存虛擬機器（SVM）磁碟區中所含的資料。如果目前未掛載磁碟區、您可以將其掛載至交會點。您也可以卸載Volume。

.關於這項工作
如果您卸載磁碟區並離線、則NAS用戶端將無法存取連接點內的所有資料、包括位於已卸載磁碟區命名空間內的連接點磁碟區中的資料。

[NOTE]
====
若要停止NAS用戶端對磁碟區的存取、只是卸載磁碟區是不夠的。您必須離線磁碟區、或採取其他步驟、以確保用戶端檔案處理快取無效。如需更多資訊、請參閱下列知識庫文章：https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/NFSv3_clients_still_have_access_to_a_volume_after_being_removed_from_the_namespace_in_ONTAP[NFSv3用戶端仍可存取從ONTAP 更新名稱空間移除後的Volume。

====
當您卸載磁碟區並離線時、磁碟區內的資料不會遺失。此外、在磁碟區或未掛載磁碟區內的目錄和交會點上建立的現有磁碟區匯出原則和SMB共用也會保留下來。如果您重新掛載未掛載的Volume、NAS用戶端可以使用現有的匯出原則和SMB共用來存取磁碟區內的資料。

.步驟
. 執行所需的動作：
+
|===
| 如果您想要... | 輸入命令... 


 a| 
掛載Volume
 a| 
「Volume mount -vserver _Svm_name_-volume _volume _name_-jeter-path _jeting_path_」



 a| 
卸載Volume
 a| 
「Volume unmount -vserver _Svm_name_-volume _volume _name_ volume offline -vserver _Svm_name_-volume _Volume _name_`

|===
. 驗證磁碟區是否處於所需的掛載狀態：「volume show -vserver _vserver_name_-volume _volume _name_-Fields stue-path、jete-active」


.範例
以下範例將SVM VS1上名為「shes」的磁碟區掛載到交會點「/sales」：

[listing]
----
cluster1::> volume mount -vserver vs1 -volume sales -junction-path /sales

cluster1::> volume show -vserver vs1 state,junction-path,junction-active

vserver   volume     state     junction-path   junction-active
--------- ---------- -------- --------------- ----------------
vs1       data       online    /data           true
vs1       home4      online    /eng/home       true
vs1       sales      online    /sales          true
----
以下範例會卸載並卸載SVM VS1上名為「dATA」的磁碟區：

[listing]
----
cluster1::> volume unmount -vserver vs1 -volume data
cluster1::> volume offline -vserver vs1 -volume data

cluster1::> volume show -vserver vs1 -fields state,junction-path,junction-active

vserver   volume     state     junction-path   junction-active
--------- ---------- --------- --------------- ---------------
vs1       data       offline   -               -
vs1       home4      online    /eng/home       true
vs1       sales      online    /sales          true
----