---
permalink: smb-admin/previous-versions-view-manage-snapshot-data-task.html 
sidebar: sidebar 
keywords: windows, client, machine, previous, version, tab, properties, restore, data, store, snapshot, copies, copy, storage, virtual, machine, svm, administrator, use the previous versions tab to view and manage snapshot copy data 
summary: Windows用戶端機器上的使用者可以使用「Windows內容」視窗上的「舊版」索引標籤、還原儲存在Snapshot複本中的資料、而不需要讓儲存虛擬機器（SVM）管理員介入。 
---
= 使用「舊版」索引標籤可檢視及管理Snapshot複本資料
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows用戶端機器上的使用者可以使用「Windows內容」視窗上的「舊版」索引標籤、還原儲存在Snapshot複本中的資料、而不需要讓儲存虛擬機器（SVM）管理員介入。

只有當系統管理員在包含共用的磁碟區上啟用Snapshot複本、且系統管理員設定共用區以顯示Snapshot複本時、您才能使用「舊版」索引標籤來檢視及管理儲存在SVM上之資料的Snapshot複本中的資料。

.步驟
. 在Windows檔案總管中、顯示儲存在CIFS伺服器上之資料對應磁碟機的內容。
. 在您要檢視或管理其Snapshot複本的對應網路磁碟機中、於檔案或資料夾上按一下滑鼠右鍵。
. 按一下*「內容」*。
+
隨即顯示所選檔案或資料夾的內容。

. 按一下*舊版*索引標籤。
+
所選檔案或資料夾的可用Snapshot複本清單會顯示在「資料夾版本：」方塊中。列出的Snapshot複本會以Snapshot複本名稱前置碼和建立時間戳記來識別。

. 在「*資料夾版本：*」方塊中、以滑鼠右鍵按一下您要管理的檔案或資料夾複本。
. 執行適當的行動：
+
|===
| 如果您想要... | 請執行下列動作... 


 a| 
檢視該Snapshot複本的資料
 a| 
按一下「*開啟*」。



 a| 
從該Snapshot複本建立資料複本
 a| 
按一下 * 複本 * 。

|===
+
Snapshot複本中的資料為唯讀。如果您想要修改「舊版」索引標籤中所列的檔案和資料夾、則必須將您要修改的檔案和資料夾複本儲存到可寫入的位置、並對複本進行修改。

. 完成Snapshot資料的管理之後、按一下「*確定*」來關閉「*內容*」對話方塊。
+
如需使用「舊版」索引標籤來檢視及管理Snapshot資料的詳細資訊、請參閱Microsoft TechNet資源庫。



http://technet.microsoft.com/en-us/library/["Microsoft TechNet程式庫：technet.microsoft.com/en-us/library/"]
