---
permalink: smb-admin/security-styles-their-effects-concept.html 
sidebar: sidebar 
keywords: unix, ntfs, mixed, unified, security, style, effect, permission, handle, data, what the security styles and their effects are 
summary: 安全風格分為四種：UNIX、NTFS、混合和統一。每種安全風格對資料權限的處理方式都有不同的影響。您必須了解這些不同影響，才能確保選擇適合您需求的安全風格。 
---
= 瞭解 ONTAP SMB 安全風格及其影響
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead lead"]
共有四種不同的安全型態：UNIX、NTFS、混合式及統一化。每種安全樣式對資料權限的處理方式都有不同的影響。您必須瞭解不同的影響、以確保為您的目的選擇適當的安全型態。

請務必瞭解、安全樣式並未決定哪些用戶端類型可以或無法存取資料。安全樣式只會決定ONTAP 用來控制資料存取的權限類型、以及哪些用戶端類型可以修改這些權限。

例如、如果某個磁碟區使用UNIX安全型態、則SMB用戶端仍可存取資料（前提是他們必須正確驗證及授權）、因為ONTAP 此為多重傳輸協定的本質。不過ONTAP 、VMware使用UNIX權限、只有UNIX用戶端可以使用原生工具進行修改。

[cols="5"]
|===
| 安全風格 | 可以修改權限的用戶端 | 用戶端可以使用的權限 | 打造出有效的安全風格 | 可存取檔案的用戶端 


| UNIX | NFS  a| 
* NFSv3模式位元
* NFSv4.x ACL

| UNIX | NFS與SMB 


| NTFS | 中小企業 | NTFS ACL | NTFS | NFS與SMB 


| 混合 | NFS或SMB  a| 
* NFSv3模式位元
* NFSv4.x ACL
* NTFS ACL

 a| 
* UNIX（用於 NFSv3 模式位元和 NFSv4.x ACL）
* NTFS（用於 NTFS ACL）

| NFS與SMB 


| 統一化
（僅適用於 Infinite Volume 、 ONTAP 9.4 及更早版本。） | NFS或SMB  a| 
* NFSv3模式位元
* NFSv4.1 ACL
* NTFS ACL

 a| 
* UNIX （適用於 NFSv3 模式位元和 NFSv4.1 ACL）
* NTFS（用於 NTFS ACL）

| NFS與SMB 
|===
支援UNIX、NTFS和混合式安全型態的支援。FlexVol當安全性樣式混合或統一化時、有效權限取決於上次修改權限的用戶端類型、因為使用者是個別設定安全性樣式。如果上次修改權限的用戶端是NFSv3用戶端、則權限為UNIX NFSv3模式位元。如果最後一個用戶端是NFSv4用戶端、則權限為NFSv4 ACL。如果最後一個用戶端是SMB用戶端、則權限為Windows NTFS ACL。

統一化的安全風格僅適用於無限個Volume、ONTAP 而不再支援於更新版本的版本。如需詳細資訊、請參閱 xref:../flexgroup/index.html[介紹Volume管理總覽FlexGroup]。

這 `show-effective-permissions`參數 `vserver security file-directory`命令可讓您顯示授予 Windows 或 UNIX 使用者在指定檔案或資料夾路徑上的有效權限。此外，選用參數 `-share-name`可讓您顯示有效共用權限。如link:https://docs.netapp.com/us-en/ontap-cli/vserver-security-file-directory-show-effective-permissions.html["指令參考資料ONTAP"^]需詳細 `vserver security file-directory show-effective-permissions`資訊，請參閱。

[NOTE]
====
最初設定部分預設檔案權限。ONTAP根據預設、UNIX、混合式及統一化安全樣式磁碟區中所有資料的有效安全樣式為UNIX、有效權限類型為UNIX模式位元（0755、除非另有說明）、直到用戶端依照預設安全性樣式所允許的方式進行設定為止。根據預設、NTFS安全型磁碟區中所有資料的有效安全樣式為NTFS、並具有ACL、可讓所有人完全掌控。

====
.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]



NOTE: 安全樣式可以設定在 FlexVol 磁碟區（根磁碟區或資料磁碟區）以及 qtree 上。安全樣式可以在建立時手動設定、自動繼承，或於日後變更。== 決定在 ONTAP SVM 上使用哪些 SMB 安全樣式

為了協助您決定要在磁碟區上使用哪種安全樣式、您應該考慮兩個因素。主要因素是管理檔案系統的系統管理員類型。次要因素是存取磁碟區上資料的使用者或服務類型。

在Volume上設定安全樣式時、您應該考慮環境的需求、以確保您選擇最佳的安全樣式、並避免管理權限時發生問題。下列考量事項可協助您決定：

[cols="2,4"]
|===
| 安全風格 | 選擇是否... 


 a| 
UNIX
 a| 
* 檔案系統由UNIX管理員管理。
* 大多數使用者是NFS用戶端。
* 存取資料的應用程式會使用UNIX使用者做為服務帳戶。




 a| 
NTFS
 a| 
* 檔案系統由Windows管理員管理。
* 大多數使用者是 SMB 用戶端。
* 存取資料的應用程式會使用Windows使用者做為服務帳戶。




 a| 
混合
 a| 
檔案系統由UNIX和Windows系統管理員管理、使用者同時由NFS和SMB用戶端組成。

|===


== 瞭解 ONTAP SMB 安全風格的繼承

如果您在建立新FlexVol 的流通量或qtree時未指定安全樣式、它會以不同的方式繼承其安全風格。

安全樣式會以下列方式繼承：

* 此功能會繼承包含SVM的根磁碟區安全樣式。FlexVol
* qtree會繼承其包含FlexVol 的不穩定區的安全樣式。
* 檔案或目錄會繼承其包含FlexVol 的不穩定磁碟區或qtree的安全樣式。

