---
permalink: smb-admin/set-server-minimum-authentication-security-level-task.html 
sidebar: sidebar 
keywords: cifs, server, minimum, security, level, lmcompatibilitylevel, smb, token, set the cifs server minimum authentication security level 
summary: 您可以在SMB伺服器上設定SMB伺服器的最低安全性層級（也稱為LMCompatibilityLevel）、以符合SMB存取的企業安全性需求。最低安全層級是SMB伺服器從SMB用戶端接受的安全性權杖最低層級。 
---
= 設定SMB伺服器的最低驗證安全性層級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在SMB伺服器上設定SMB伺服器的最低安全性層級（也稱為_LMCompatibilityLevel）、以符合SMB用戶端存取的企業安全性需求。最低安全層級是SMB伺服器從SMB用戶端接受的安全性權杖最低層級。

[NOTE]
.關於這項工作
====
* 工作群組模式中的SMB伺服器僅支援NTLM驗證。不支援Kerberos驗證。
* LMCompatibilityLevel僅適用於SMB用戶端驗證、不適用於管理驗證。


====
您可以將最低驗證安全性層級設為四種支援的安全性層級之一。

|===
| 價值 | 說明 


 a| 
「lm-NTLM-NTLMv-krb」（預設）
 a| 
儲存虛擬機器（SVM）接受LM、NTLM、NTLMv2及Kerberos驗證安全性。



 a| 
「NTLM-NTLMv-krb」
 a| 
SVM接受NTLM、NTLMv2及Kerberos驗證安全性。SVM拒絕LM驗證。



 a| 
「vbvbe-krb」
 a| 
SVM接受NTLMv2和Kerberos驗證安全性。SVM拒絕LM和NTLM驗證。



 a| 
「KRB'」
 a| 
SVM僅接受Kerberos驗證安全性。SVM會拒絕LM、NTLM及NTLMv2驗證。

|===
.步驟
. 設定最低驗證安全性層級：「vserver CIFS安全性修改-vserver _vserver_name_-lm相容性層級｛lm -NTLM-NTLMv-krb | NTLM-NTLMv-krb | krb｝」
. 驗證驗證安全性層級是否設為所需層級：「vserver CIFS安全性show -vserver _vserver_name_」


xref:enable-disable-aes-encryption-kerberos-task.adoc[啟用或停用AES加密以進行Kerberos型通訊]
