---
permalink: smb-admin/storage-system-provides-null-session-access-concept.html 
sidebar: sidebar 
keywords: null, session, share, require, authentication, client, ip, address, map, storage, system, how the storage system provides null session access 
summary: 由於null工作階段共用不需要驗證、因此需要null工作階段存取的用戶端必須在儲存系統上對應其IP位址。 
---
= 瞭解 ONTAP SMB 儲存系統如何提供 Null 工作階段存取
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
由於null工作階段共用不需要驗證、因此需要null工作階段存取的用戶端必須在儲存系統上對應其IP位址。

根據預設、未對應的null工作階段用戶端可以存取某些ONTAP 功能不全的系統服務、例如共用列舉、但它們受到限制、無法存取任何儲存系統資料。

[NOTE]
====
ONTAP 支援使用選項的 Windows RestrictAnonymous 登錄設定值 `–restrict-anonymous`。這可讓您控制未對應的null使用者檢視或存取系統資源的程度。例如、您可以停用共用列舉並存取IPC$共用區（隱藏的命名管道共用區）。深入瞭解 `vserver cifs options modify`及 `vserver cifs options show` `–restrict-anonymous`中的選項link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=vserver+cifs+options["指令參考資料ONTAP"^]。

====
除非另有設定、否則執行本機處理程序的用戶端透過null工作階段要求存取儲存系統、只是不受限制群組的成員、例如「'ee任何人'」。若要限制對所選儲存系統資源的null工作階段存取、您可能需要建立一個所有null工作階段用戶端所屬的群組；建立此群組可讓您限制儲存系統存取、並設定專屬於null工作階段用戶端的儲存系統資源權限。

ONTAP 在中提供對應語法 `vserver name-mapping` 命令集可指定允許使用 null 使用者工作階段存取儲存系統資源的用戶端 IP 位址。為null使用者建立群組之後、您可以針對僅適用於null工作階段的儲存系統資源和資源權限、指定存取限制。null使用者被識別為匿名登入。null使用者無法存取任何主目錄。

從對應IP位址存取儲存系統的任何null使用者、都會被授予對應的使用者權限。請考量適當的預防措施、以防止未獲授權存取與null使用者對應的儲存系統。為獲得最大保護、請將儲存系統和所有需要null使用者儲存系統存取的用戶端放在獨立的網路上、以避免IP位址「欺詐」的可能性。

.相關資訊
xref:configure-access-restrictions-anonymous-users-task.adoc[設定匿名使用者的存取限制]
