---
permalink: mediator/host-maintenance-task.html 
sidebar: sidebar 
keywords: mediator, maintain, host, maintenance, package update, kernal upgrade, change hostname, change IP, self-signed certificate, self signed certificate 
summary: 為了達到最佳效能、您應該定期維護 ONTAP Mediator 的主機 OD 。 
---
= 維護 ONTAP Mediator 的主機作業系統
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
為了獲得最佳效能、您應該定期維護 ONTAP Mediator 的主機作業系統。



== 重新啟動主機

叢集正常運作時、請重新啟動主機。當 ONTAP 調解器處於離線狀態時，叢集可能無法正確應對故障。如果需要重新開機、建議您使用服務時段。

ONTAP Mediator 會在重新開機期間自動恢復、並重新輸入先前使用 ONTAP 叢集設定的關係。



== 主機套件更新

任何程式庫或 yum 套件（核心除外）均可安全更新、但可能需要重新開機才能生效。   如果需要重新開機、建議您使用服務時段。

如果您安裝 `yum-utils` 套件中、請使用 `needs-restarting` 偵測是否有任何套件變更需要重新開機的命令。

如果更新了任何 ONTAP Mediator 相依性、您應該重新開機、因為它們不會立即影響執行中的程序。



== 主機作業系統次要核心升級

SCST 必須針對正在使用的核心進行編譯。  若要更新作業系統、需要維護時間。

.步驟
請執行下列步驟來升級主機作業系統核心。

. 停止 ONTAP 調解器。
. 解除安裝 SCST 套件。  （ SCST 不提供升級機制。）
. 升級作業系統、然後重新開機。
. 重新安裝 SCST 套件。
. 重新啟用 ONTAP 調解器。




== 主機變更為主機名稱或 IP

.關於這項工作
* 在安裝了 ONTAP Mediator 的 Linux 主機上執行此任務。
* 只有安裝 ONTAP 調解器後，由於主機的主機名稱或 IP 位址發生變更而導致產生的自簽章憑證已過時時，您才可以執行此任務。
* 當暫時自我簽署的憑證已由信任的協力廠商憑證取代之後、您不會使用此工作來重新產生憑證。  如果沒有自我簽署的憑證、將導致此程序失敗。


.步驟
若要為目前主機重新產生新的暫時自我簽署憑證、請執行下列步驟：

. 重新啟動 ONTAP 調解器：
+
`./make_self_signed_certs.sh overwrite`

+
[listing]
----
[root@xyz000123456 ~]# cd /opt/netapp/lib/ontap_mediator/ontap_mediator/server_config
[root@xyz000123456 server_config]# ./make_self_signed_certs.sh overwrite

Adding Subject Alternative Names to the self-signed server certificate
#
# OpenSSL example configuration file.
Generating self-signed certificates
Generating RSA private key, 4096 bit long modulus (2 primes)
..................................................................................................................................................................++++
........................................................++++
e is 65537 (0x010001)
Generating a RSA private key
................................................++++
.............................................................................................................................................++++
writing new private key to 'ontap_mediator_server.key'
-----
Signature ok
subject=C = US, ST = California, L = San Jose, O = "NetApp, Inc.", OU = ONTAP Core Software, CN = ONTAP Mediator, emailAddress = support@netapp.com
Getting CA Private Key

[root@xyz000123456 server_config]# systemctl restart ontap_mediator
----

