---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: 若要安裝ONTAP 《支援程式》服務、您必須確保符合所有先決條件、取得安裝套件、並在主機上執行安裝程式。 
---
= 安裝或升級ONTAP 《不知道如何使用》服務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要安裝ONTAP 《支援程式》服務、您必須確保符合所有先決條件、取得安裝套件、並在主機上執行安裝程式。此程序用於安裝或升級現有安裝。

您必須符合下列先決條件。

[cols="30,70"]
|===


| 中介版本 | 支援的Linux版本 


 a| 
1.4
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4、8.5
* CentOS：7.6、7.7、7.8、7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3
* CentOS：7.6、7.7、7.8、7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、8.1
* CentOS：7.6、7.7、7.8%


|===

NOTE: 核心版本必須符合作業系統版本。

* 64位元實體安裝或虛擬機器
* 8 GB RAM
* 使用者：root存取權




== 升級主機作業系統、然後升級「媒體資訊器」

下表提供升級準則、適用於從RHEL/CentOS 7.6升級至較新版本的RHEL/CentOS版本、以及升級Medator版本。

[cols="20,20,60"]
|===


| 目標Linux版本 | 目標媒體器版本 | 升級附註 


 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、8.1
* CentOS：7.6、7.7、7.8%

 a| 
1.2
 a| 
* 升級必須依照下列順序執行：
+
.. 從RHEL/CentOS版本升級作業系統。
.. 重新啟動主機以套用核心模組變更。
.. 將媒體器從先前的版本升級至目前的版本。


* 適用於下列項目：MetroCluster
+
.. 儲存設備iscsi啟動器show命令會報告、在升級期間、與媒體服務的連線中斷。
.. 此作業系統將產生下列EMS事件：ONTAP
+
... 升級期間的cf.mccip.med.auso.stDisabled
... 當自動非計畫性切換重新啟用時、請參閱cf.mccip.med.auso.stEnabled








 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3
* CentOS：7.6、7.7、7.8、7.9

 a| 
1.3
 a| 
. 從RHEL/CentOS版本升級作業系統。
. 重新啟動主機以套用核心模組變更。
. 將媒體器從先前的版本升級至目前的版本。




 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4
* CentOS：7.6、7.7、7.8、7.9

 a| 
1.4
 a| 
. 從RHEL/CentOS版本升級作業系統。
. 重新啟動主機以套用核心模組變更。
. 將媒體器從先前的版本升級至目前的版本。


|===
以下列出安裝Red Hat Enterprise Linux或CentOS以及系統上相關儲存庫的最佳實務做法。安裝或設定不同的系統可能需要額外的步驟。

* 您必須根據Red Hat最佳實務做法來安裝Red Hat Enterprise Linux或CentOS。由於CentOS 8.x版本的生命週期結束支援、因此不建議使用CentOS 8.x的相容版本。
* 在ONTAP Red Hat Enterprise Linux或CentOS上安裝支援程式服務時、系統必須能夠存取適當的儲存庫、以便安裝程式存取及安裝所有必要的軟體相依性。
* 為了讓yum安裝程式在Red Hat Enterprise Linux儲存庫中找到相依軟體、您必須在Red Hat Enterprise Linux安裝期間或之後使用有效的Red Hat訂閱來註冊系統。
+
如需Red Hat訂購管理程式的相關資訊、請參閱Red Hat說明文件。

* 下列連接埠必須未使用、且可用於資訊管理器：
+
** 31784年
** 3260


* 如果使用協力廠商防火牆：請參閱 link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html#firewall-requirements-for-ontap-mediator["防火牆需求ONTAP"^]
* 如果Linux主機位於無法存取網際網路的位置、您必須確保所需的套件可在本機儲存庫中使用。
+
您可以使用下列連結取得設定儲存庫的相關資訊。

+
如果您在Linux環境中使用連結集合控制傳輸協定（LACP）、則必須正確設定核心、並確定「seyscll net.ipv4.conf.all.arp_ignore」設為「2」。

+
下列套件是ONTAP 由《不知道的》服務所要求的：

+
[cols="25,35,40"]
|===


| 所有RHEL/CentOS版本 | RHEL / CentOS 7.x的其他套件 | RHEL 8.x的其他套件 


 a| 
** OpenSSL
** OpenSSL
** kernel-devel
** 海灣合作委員會
** libselinux-utils
** 製造
** RedHat-lsb核心
** 修補程式
** bzip2.
** 熱36
** python36- devel
** Perl-Data-Dumper
** Perl-ExtUtils-MakeMaker..
** python3-pip

 a| 
** policycoreutils-python
** python36- pip

 a| 
** elfutils-libelf-devel
** policycoreutils-python公用程式


|===


該媒體夾安裝套件是一個自我解壓縮的tar檔案、其中包括：

* 一種RPM檔案、內含無法從支援版本儲存庫取得的所有相依性。
* 安裝指令碼。


建議使用有效的SSL認證、如本程序所述。



== 啟用儲存庫存取

|===


| 如果您的作業系統是... | 您必須提供這些儲存庫的存取權限... 


 a| 
RHEL 7.x
 a| 
RHEL-7-server選用-rpms



 a| 
CentOS 7.x
 a| 
C7.6.1810 -基礎儲存庫



 a| 
RHEL 8.x
 a| 
* RHEL-8-for-x86_64：basos-rpms
* RHEL-8-for-x86_64：AppStream：rpms


|===
啟用對上述儲存庫的存取、以便媒體資訊員在安裝程序期間存取所需的套件。請針對您的作業系統使用下列程序。

* 的程序 <<rhel7x,RHEL 7.x>> 作業系統：
* 的程序 <<rhel8x,RHEL 8.x>> 作業系統：
* 的程序 <<centos7x,CentOS 7.x>> 作業系統：




=== RHEL 7.x作業系統的程序

如果您的作業系統是* RHEL 7.x*：

.步驟
. 訂閱所需的儲存庫：
+
「Subscape-manager reposs -啟用RHEL-7-server選用-rpms」

+
下列範例顯示此命令的執行：

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-7-server-optional-rpms
Repository 'rhel-7-server-optional-rpms' is enabled for this system.
----
. 執行「yum repolist」命令。
+
下列範例顯示此命令的執行。清單中應會顯示「RHEL-7-server選擇性-rpms」儲存庫。

+
[listing]
----
[root@localhost ~]# yum repolist
Loaded plugins: product-id, search-disabled-repos, subscription-manager
rhel-7-server-optional-rpms | 3.2 kB  00:00:00
rhel-7-server-rpms | 3.5 kB  00:00:00
(1/3): rhel-7-server-optional-rpms/7Server/x86_64/group                                               |  26 kB  00:00:00
(2/3): rhel-7-server-optional-rpms/7Server/x86_64/updateinfo                                          | 2.5 MB  00:00:00
(3/3): rhel-7-server-optional-rpms/7Server/x86_64/primary_db                                          | 8.3 MB  00:00:01
repo id                                      repo name                                             status
rhel-7-server-optional-rpms/7Server/x86_64   Red Hat Enterprise Linux 7 Server - Optional (RPMs)   19,447
rhel-7-server-rpms/7Server/x86_64            Red Hat Enterprise Linux 7 Server (RPMs)              26,758
repolist: 46,205
[root@localhost ~]#
----




=== RHEL 8.x作業系統的程序

如果您的作業系統是* RHEL 8.x *：

.步驟
. 訂閱所需的儲存庫：
+
「Substime-manager reposs -啟用RHEL-8-for-x86_64、basos-rpms」

+
「Substime-manager reposs -啟用RHEL-8-for-x86_64：AppStream：rpms」

+
下列範例顯示此命令的執行：

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms
Repository 'rhel-8-for-x86_64-baseos-rpms' is enabled for this system.
Repository 'rhel-8-for-x86_64-appstream-rpms' is enabled for this system.
----
. 執行「yum repolist」命令。
+
新訂閱的儲存庫應會出現在清單中。





=== CentOS 7.x作業系統的程序

如果您的作業系統是* CentOS 7.x*：


NOTE: 下列範例顯示CentOS 7.6的儲存庫、可能無法用於其他CentOS版本。將基礎儲存庫用於您的CentOS版本。

.步驟
. 新增C7.6.1810 -基礎儲存庫。C7.6.1810 - Base Vault儲存庫包含ONTAP 資訊中心所需的kernel-devel套件。
. 將下列行新增至/etc/yum、repos.d/CentOS、Vault.repo。
+
[listing]
----
[C7.6.1810-base]
name=CentOS-7.6.1810 - Base
baseurl=http://vault.centos.org/7.6.1810/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1
----
. 執行「yum repolist」命令。
+
下列範例顯示此命令的執行。Centos-7.6.1810 -基礎儲存庫應出現在清單中。

+
[listing]
----
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: distro.ibiblio.org
 * extras: distro.ibiblio.org
 * updates: ewr.edge.kernel.org
C7.6.1810-base                                                   | 3.6 kB  00:00:00
(1/2): C7.6.1810-base/x86_64/group_gz                            | 166 kB  00:00:00
(2/2): C7.6.1810-base/x86_64/primary_db                          | 6.0 MB  00:00:04
repo id                                           repo name                                                                                                    status
C7.6.1810-base/x86_64                             CentOS-7.6.1810 - Base                                                                                       10,019
base/7/x86_64                                     CentOS-7 - Base                                                                                              10,097
extras/7/x86_64                                   CentOS-7 - Extras                                                                                               307
updates/7/x86_64                                  CentOS-7 - Updates                                                                                            1,010
repolist: 21,433
[root@localhost ~]#
----




== 下載「內化器」安裝套件

.步驟
. 請從ONTAP 「畫面資訊」頁面下載「媒體資訊器」安裝套件。
+
https://mysupport.netapp.com/site/products/all/details/ontap-mediator/downloads-tab["《資訊媒體》下載頁面ONTAP"^]

. 確認「媒體資訊器」安裝套件位於目標目錄：
+
《ls》

+
[listing]
----
[root@mediator-host ~]#ls
ontap-mediator
----
+
如果您所在的位置無法存取網際網路、則必須確保安裝程式能夠存取所需的套件。

. 如有必要、請將「內化器」安裝套件從下載目錄移至Linux媒體器主機上的安裝目錄。




== 安裝ONTAP 《不知道如何安裝》套件

.關於這項工作
* 從ONTAP 推出支援程式1.4開始、安全開機機制就會在UEFI系統上啟用。啟用「安全開機」時、您必須在安裝後採取其他步驟來登錄安全金鑰：
+
** 請遵循README檔案中的指示：「/opt/netapp/lib/ontap中介器/ontap中介器/SCST_mod_keys/README、module-Signing」來簽署SCST核心模組。
** 找到所需的金鑰：「/opt/netapp/lib/ontapp_moder_keys」


+

NOTE: 安裝後、系統輸出也會提供README檔案和主要位置。



.步驟
. 安裝媒體器安裝套件、並視需要回應提示：
+
「/ONTAP-中介 者」

+
安裝程序會繼續建立所需的帳戶、並安裝所需的套件。如果主機上已安裝舊版的「媒體資訊器」、系統會提示您確認是否要升級。



.安裝過程範例ONTAP ：安裝過程（主控台輸出）
====
[listing]
----
[root@scs000065018 ~]# ./ontap-mediator
ONTAP Mediator: Self Extracting Installer
ONTAP Mediator requires two user accounts. One for the service (netapp), and one for use by ONTAP to the mediator API (mediatoradmin).
Would you like to use the default account names: netapp + mediatoradmin? (Y(es)/n(o)): y
Enter ONTAP Mediator user account (mediatoradmin) password:
Re-Enter ONTAP Mediator user account (mediatoradmin) password:
Checking if SELinux is in enforcing mode
Checking for default Linux firewall
Linux firewall is running. Open ports 31784 and 3260? y(es)/n(o): y
success
success



Preparing for installation of ONTAP Mediator packages.
Do you wish to continue? Y(es)/n(o): y
+ Installing required packages.
Last metadata expiration check: 1:56:17 ago on Thu 07 Apr 2022 11:35:42 AM EDT.
Package openssl-1:1.1.1k-6.el8_5.x86_64 is already installed.
Package openssl-devel-1:1.1.1k-6.el8_5.x86_64 is already installed.

.
.
.
.

Dependencies resolved.
Nothing to do.
Complete!
OS package installations finished
+ Installing ONTAP Mediator. (Log: /tmp/ontap_mediator.5gmxnI/ontap-mediator/install_20220407133105.log)
    This step will take several minutes. Use the log file to view progress.
Sudo include verified
ONTAP Mediator logging enabled
+ Install successful. (Moving log to /opt/netapp/lib/ontap_mediator/log/install_20220407133105.log)
+ WARNING: This system supports UEFI
           Secure Boot (SB) is currently enabled on this system.
           The following action need be taken:
           Using the keys in /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys follow
           instructions in /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/README.module-signing
           to sign the SCST kernel module. Note that reboot will be needed.
     SCST will not start automatically when Secure Boot is enabled and not configured properly.
+ Note: ONTAP Mediator uses a kernel module compiled specifically for the current
        system OS. Using 'yum update' to upgrade the kernel may cause a service
        interruption.
    For more information, see /opt/netapp/lib/ontap_mediator/README
[root@scs000065018 ~]#
----
====


== 驗證安裝

.步驟
. 執行下列命令以檢視ONTAP 「資訊不全」服務的狀態：
+
.. RUN：「ystemctl STATUS ONTAP_ONI者」
+
[listing]
----
[root@scspr1915530002 ~]# systemctl status ontap_mediator

 ontap_mediator.service - ONTAP Mediator
Loaded: loaded (/etc/systemd/system/ontap_mediator.service; enabled; vendor preset: disabled)
Active: active (running) since Mon 2022-04-18 10:41:49 EDT; 1 weeks 0 days ago
Process: 286710 ExecStop=/bin/kill -s INT $MAINPID (code=exited, status=0/SUCCESS)
Main PID: 286712 (uwsgi)
Status: "uWSGI is ready"
Tasks: 3 (limit: 49473)
Memory: 139.2M
CGroup: /system.slice/ontap_mediator.service
      ├─286712 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      ├─286716 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      └─286717 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

[root@scspr1915530002 ~]#
----
.. RUN：「ystemctl STATUS SCIer-scst」
+
[listing]
----
[root@scspr1915530002 ~]# systemctl status mediator-scst
   Loaded: loaded (/etc/systemd/system/mediator-scst.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-04-18 10:41:47 EDT; 1 weeks 0 days ago
  Process: 286595 ExecStart=/etc/init.d/scst start (code=exited, status=0/SUCCESS)
 Main PID: 286662 (iscsi-scstd)
    Tasks: 1 (limit: 49473)
   Memory: 1.2M
   CGroup: /system.slice/mediator-scst.service
           └─286662 /usr/local/sbin/iscsi-scstd

[root@scspr1915530002 ~]#
----


. 確認ONTAP 使用的連接埠：「Netstat」
+
[listing]
----
[root@scspr1905507001 ~]# netstat -anlt | grep -E '3260|31784'

         tcp   0   0 0.0.0.0:31784   0.0.0.0:*      LISTEN

         tcp   0   0 0.0.0.0:3260    0.0.0.0:*      LISTEN

         tcp6  0   0 :::3260         :::*           LISTEN
----




== 結果

現在已安裝並執行此功能。ONTAP必須在ONTAP 不完整的儲存系統中執行進一步的組態、才能使用「內化器」功能：

* 若要在ONTAP 不實的IP組態中使用此功能、MetroCluster 請參閱 link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["從ONTAP 一套不實的IP組態設定「不實不作」MetroCluster 服務"^]
* 若要使用SnapMirror營運不中斷、請參閱 link:https://docs.netapp.com/us-en/ontap/smbc/smbc_install_confirm_ontap_cluster.html["安裝ONTAP 「支援中心服務」並確認ONTAP 「支援中心」組態"^]

