---
permalink: mediator/index.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: 若要安裝ONTAP 《支援程式》服務、您必須確保符合所有先決條件、取得安裝套件、並在主機上執行安裝程式。 
---
= 安裝或升級ONTAP 《不知道如何使用》服務
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要安裝ONTAP 《支援程式》服務、您必須確保符合所有先決條件、取得安裝套件、並在主機上執行安裝程式。此程序用於安裝或升級現有安裝。

.關於這項工作
* 從使用NetApp 9.7開始ONTAP 、您可以使用ONTAP 任何版本的《不知道》來監控MetroCluster 一個靜態IP組態。
* 從功能介紹9.8開始ONTAP 、您可以使用ONTAP 任何版本的《不知道》來監控SM與BC的關係。


.開始之前
您必須符合下列先決條件。

[cols="30,70"]
|===


| 中介版本 | 支援的Linux版本 


 a| 
1.5
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4、8.5
* CentOS：7.6、7.7、7.8、7.9




 a| 
1.4
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4、8.5
* CentOS：7.6、7.7、7.8、7.9




 a| 
1.3
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3
* CentOS：7.6、7.7、7.8、7.9




 a| 
1.2
 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、8.1
* CentOS：7.6、7.7、7.8%


|===

NOTE: 核心版本必須符合作業系統版本。

* 64位元實體安裝或虛擬機器
* 8 GB RAM
* 使用者：root存取權




== 升級主機作業系統、然後升級「媒體資訊器」

下表提供升級準則、適用於從RHEL/CentOS 7.6升級至較新版本的RHEL/CentOS版本、以及升級Medator版本。

[cols="20,20,60"]
|===


| 目標Linux版本 | 目標媒體器版本 | 升級附註 


 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、8.1
* CentOS：7.6、7.7、7.8%

 a| 
1.2
 a| 
* 升級必須依照下列順序執行：
+
.. 從RHEL/CentOS版本升級作業系統。
.. 重新啟動主機以套用核心模組變更。
.. 將媒體器從先前的版本升級至目前的版本。


* 適用於下列項目：MetroCluster
+
.. 儲存設備iscsi啟動器show命令會報告、在升級期間、與媒體服務的連線中斷。
.. 此作業系統將產生下列EMS事件：ONTAP
+
... 升級期間的cf.mccip.med.auso.stDisabled
... 當自動非計畫性切換重新啟用時、請參閱cf.mccip.med.auso.stEnabled








 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3
* CentOS：7.6、7.7、7.8、7.9

 a| 
1.3
 a| 
. 從RHEL/CentOS版本升級作業系統。
. 重新啟動主機以套用核心模組變更。
. 將媒體器從先前的版本升級至目前的版本。




 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4、8.5
* CentOS：7.6、7.7、7.8、7.9

 a| 
1.4
 a| 
. 從RHEL/CentOS版本升級作業系統。
. 重新啟動主機以套用核心模組變更。
. 將媒體器從先前的版本升級至目前的版本。




 a| 
* Red Hat Enterprise Linux：7.6、7.7、7.8、7.9、8.1、 8.2、8.3、8.4、8.5
* CentOS：7.6、7.7、7.8、7.9

 a| 
1.5
 a| 
. 從RHEL/CentOS版本升級作業系統。
. 重新啟動主機以套用核心模組變更。如果您未重新啟動主機、則會出現錯誤訊息、提示您執行重新開機。
. 將媒體器從先前的版本升級至目前的版本。


|===
以下列出安裝Red Hat Enterprise Linux或CentOS以及系統上相關儲存庫的最佳實務做法。安裝或設定不同的系統可能需要額外的步驟。

* 您必須根據Red Hat最佳實務做法來安裝Red Hat Enterprise Linux或CentOS。由於CentOS 8.x版本的生命週期結束支援、因此不建議使用CentOS 8.x的相容版本。
* 在ONTAP Red Hat Enterprise Linux或CentOS上安裝支援程式服務時、系統必須能夠存取適當的儲存庫、以便安裝程式存取及安裝所有必要的軟體相依性。
* 為了讓yum安裝程式在Red Hat Enterprise Linux儲存庫中找到相依軟體、您必須在Red Hat Enterprise Linux安裝期間或之後使用有效的Red Hat訂閱來註冊系統。
+
如需Red Hat訂購管理程式的相關資訊、請參閱Red Hat說明文件。

* 下列連接埠必須未使用、且可用於資訊管理器：
+
** 31784年
** 3260


* 如果使用協力廠商防火牆：請參閱 link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/concept_mediator_requirements.html#firewall-requirements-for-ontap-mediator["防火牆需求ONTAP"^]
* 如果Linux主機位於無法存取網際網路的位置、您必須確保所需的套件可在本機儲存庫中使用。
+
如果您在Linux環境中使用連結集合控制傳輸協定（LACP）、則必須正確設定核心、並確定「seyscll net.ipv4.conf.all.arp_ignore」設為「2」。

+
下列套件是ONTAP 由《不知道的》服務所要求的：

+
[cols="25,35,40"]
|===


| 所有RHEL/CentOS版本 | RHEL / CentOS 7.x的其他套件 | RHEL 8.x的其他套件 


 a| 
** OpenSSL
** OpenSSL
** kernel-devel
** 海灣合作委員會
** libselinux-utils
** 製造
** RedHat-lsb核心
** 修補程式
** bzip2.
** 熱36
** python36- devel
** Perl-Data-Dumper
** Perl-ExtUtils-MakeMaker..
** python3-pip

 a| 
** policycoreutils-python
** python36- pip

 a| 
** elfutils-libelf-devel
** policycoreutils-python公用程式


|===


該媒體夾安裝套件是一個自我解壓縮的tar檔案、其中包括：

* 一種RPM檔案、內含無法從支援版本儲存庫取得的所有相依性。
* 安裝指令碼。


建議使用有效的SSL認證、如本程序所述。



== 啟用儲存庫存取

|===


| 如果您的作業系統是... | 您必須提供這些儲存庫的存取權限... 


 a| 
RHEL 7.x
 a| 
RHEL-7-server選用-rpms



 a| 
CentOS 7.x
 a| 
C7.6.1810 -基礎儲存庫



 a| 
RHEL 8.x
 a| 
* RHEL-8-for-x86_64：basos-rpms
* RHEL-8-for-x86_64：AppStream：rpms


|===
啟用對上述儲存庫的存取、以便媒體資訊員在安裝程序期間存取所需的套件。請針對您的作業系統使用下列程序。

* 的程序 <<rhel7x,RHEL 7.x>> 作業系統：
* 的程序 <<rhel8x,RHEL 8.x>> 作業系統：
* 的程序 <<centos7x,CentOS 7.x>> 作業系統：




=== RHEL 7.x作業系統的程序

如果您的作業系統是* RHEL 7.x*：

.步驟
. 訂閱所需的儲存庫：
+
「Subscape-manager reposs -啟用RHEL-7-server選用-rpms」

+
下列範例顯示此命令的執行：

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-7-server-optional-rpms
Repository 'rhel-7-server-optional-rpms' is enabled for this system.
----
. 執行「yum repolist」命令。
+
下列範例顯示此命令的執行。清單中應會顯示「RHEL-7-server選擇性-rpms」儲存庫。

+
[listing]
----
[root@localhost ~]# yum repolist
Loaded plugins: product-id, search-disabled-repos, subscription-manager
rhel-7-server-optional-rpms | 3.2 kB  00:00:00
rhel-7-server-rpms | 3.5 kB  00:00:00
(1/3): rhel-7-server-optional-rpms/7Server/x86_64/group                                               |  26 kB  00:00:00
(2/3): rhel-7-server-optional-rpms/7Server/x86_64/updateinfo                                          | 2.5 MB  00:00:00
(3/3): rhel-7-server-optional-rpms/7Server/x86_64/primary_db                                          | 8.3 MB  00:00:01
repo id                                      repo name                                             status
rhel-7-server-optional-rpms/7Server/x86_64   Red Hat Enterprise Linux 7 Server - Optional (RPMs)   19,447
rhel-7-server-rpms/7Server/x86_64            Red Hat Enterprise Linux 7 Server (RPMs)              26,758
repolist: 46,205
[root@localhost ~]#
----




=== RHEL 8.x作業系統的程序

如果您的作業系統是* RHEL 8.x *：

.步驟
. 訂閱所需的儲存庫：
+
「Substime-manager reposs -啟用RHEL-8-for-x86_64、basos-rpms」

+
「Substime-manager reposs -啟用RHEL-8-for-x86_64：AppStream：rpms」

+
下列範例顯示此命令的執行：

+
[listing]
----
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-baseos-rpms
[root@localhost ~]# subscription-manager repos --enable rhel-8-for-x86_64-appstream-rpms
Repository 'rhel-8-for-x86_64-baseos-rpms' is enabled for this system.
Repository 'rhel-8-for-x86_64-appstream-rpms' is enabled for this system.
----
. 執行「yum repolist」命令。
+
新訂閱的儲存庫應會出現在清單中。





=== CentOS 7.x作業系統的程序

如果您的作業系統是* CentOS 7.x*：


NOTE: 下列範例顯示CentOS 7.6的儲存庫、可能無法用於其他CentOS版本。將基礎儲存庫用於您的CentOS版本。

.步驟
. 新增C7.6.1810 -基礎儲存庫。C7.6.1810 - Base Vault儲存庫包含ONTAP 資訊中心所需的kernel-devel套件。
. 將下列行新增至/etc/yum、repos.d/CentOS、Vault.repo。
+
[listing]
----
[C7.6.1810-base]
name=CentOS-7.6.1810 - Base
baseurl=http://vault.centos.org/7.6.1810/os/$basearch/
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled=1
----
. 執行「yum repolist」命令。
+
下列範例顯示此命令的執行。Centos-7.6.1810 -基礎儲存庫應出現在清單中。

+
[listing]
----
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: distro.ibiblio.org
 * extras: distro.ibiblio.org
 * updates: ewr.edge.kernel.org
C7.6.1810-base                                                   | 3.6 kB  00:00:00
(1/2): C7.6.1810-base/x86_64/group_gz                            | 166 kB  00:00:00
(2/2): C7.6.1810-base/x86_64/primary_db                          | 6.0 MB  00:00:04
repo id                                           repo name                                                                                                    status
C7.6.1810-base/x86_64                             CentOS-7.6.1810 - Base                                                                                       10,019
base/7/x86_64                                     CentOS-7 - Base                                                                                              10,097
extras/7/x86_64                                   CentOS-7 - Extras                                                                                               307
updates/7/x86_64                                  CentOS-7 - Updates                                                                                            1,010
repolist: 21,433
[root@localhost ~]#
----




== 下載「內化器」安裝套件

.步驟
. 請從ONTAP 「畫面資訊」頁面下載「媒體資訊器」安裝套件。
+
https://mysupport.netapp.com/site/products/all/details/ontap-mediator/downloads-tab["《資訊媒體》下載頁面ONTAP"^]

. 確認「內建器」安裝套件位於目前的工作目錄：
+
《ls》

+
[listing]
----
[root@mediator-host ~]#ls
ontap-mediator-1.5.0.tgz
----
+

NOTE: 針對1.4版及更早版本的資訊、安裝程式會命名為「」ONTAP `ontap-mediator`。

+
如果您所在的位置無法存取網際網路、則必須確保安裝程式能夠存取所需的套件。

. 如有必要、請將「內化器」安裝套件從下載目錄移至Linux媒體器主機上的安裝目錄。
. 解壓縮安裝程式套件： `tar xvfz ontap-mediator-1.5.0.tgz`
+
[listing]
----
[root@scs000099753 ~]# tar xvfz ontap-mediator-1.5.0.tgz
ontap-mediator-1.5.0/
ontap-mediator-1.5.0/ONTAP-Mediator-production.pub
ontap-mediator-1.5.0/tsa-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.5.0/tsa-prod-ONTAP-Mediator.pem
ontap-mediator-1.5.0/csc-prod-ONTAP-Mediator.pem
ontap-mediator-1.5.0/csc-prod-chain-ONTAP-Mediator.pem
ontap-mediator-1.5.0/ontap-mediator-1.5.0
ontap-mediator-1.5.0/ontap-mediator-1.5.0.sig.tsr
ontap-mediator-1.5.0/ontap-mediator-1.5.0.tsr
ontap-mediator-1.5.0/ontap-mediator-1.5.0.sig

----




== 驗證ONTAP 《不實程式碼簽章》

您應該在ONTAP 安裝「媒體資訊器」安裝套件之前、先確認「資訊媒體」程式碼簽章。

.開始之前
在驗證「中保證程式碼」簽名之前、您的系統必須符合下列要求。

* 適用於基本驗證的Openssl版本1.0.2至3.0
* 適用於時間戳記授權（TSA）作業的OpenSSL 1.1.0版或更新版本
* 用於OCSP驗證的公共網際網路存取



NOTE: 下載套件中包含下列檔案：

* `ONTAP-Mediator-development.pub` |用來驗證簽名的公開金鑰
* `csc-prod-chain-ONTAP-Mediator.pem` |公共認證CA信任鏈
* `csc-prod-ONTAP-Mediator.pem` |用於產生金鑰的憑證
* `ontap-mediator-1.5.0` | 1.5.0版的產品安裝執行檔
* `ontap-mediator-1.5.0.sig` | SHA-256會對安裝程式進行雜湊、然後使用CSC-Prod金鑰簽署RSA
* `ontap-mediator-1.5.0.sig.tsr` | OCPP使用的撤銷要求、以供安裝程式簽署
* `tsa-prod-ONTAP-Mediator.pem` |用於TSR的公共憑證
* `tsa-prod-chain-ONTAP-Mediator.pem` |用於TSR的公共憑證CA鏈結


.步驟
. 執行撤銷檢查 `csc-prod-ONTAP-Mediator.pem` 使用線上憑證狀態傳輸協定（OCSP）。
+
.. 尋找用來將憑證登錄為開發人員憑證的OCSP URL可能無法提供URI。
+
[listing]
----
openssl x509 -noout -ocsp_uri -in csc-prod-chain-ONTAP-Mediator.pem
----
.. 為憑證產生OCSP要求。
+
[listing]
----
openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem  -reqout req.der
----
.. 連線至OCSP管理程式以傳送OCSP要求： `openssl`
+
[listing]
----
openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem  -url ${ocsp_uri} -resp_text -respout resp.der
----


. 針對本機主機驗證其信任鏈結和到期日： `openssl verify`
+

NOTE: 。 `openssl` 路徑的版本必須有效 `cert.pem` （非自行簽署）。

+
[listing]
----
openssl verify -untrusted csc-prod-chain-ONTAP-Mediator.pem -CApath ${OPENSSLDIR} csc-prod-ONTAP-Mediator.pem  # Failure action: The Code-Signature-Check certificate has expired or is invalid. Download a newer version of the ONTAP Mediator.
openssl verify -untrusted tsa-prod-chain-ONTAP-Mediator.pem -CApath ${OPENSSLDIR} tsa-prod-ONTAP-Mediator.pem  # Failure action: The Time-Stamp certificate has expired or is invalid. Download a newer version of the ONTAP Mediator.
----
. 驗證 `ontap-mediator-1.5.0.sig.tsr` 和 `ontap-mediator-1.5.0.tsr` 使用相關憑證的檔案： `openssl ts -verify`
+

NOTE: `.tsr` 檔案包含與安裝程式和程式碼簽章相關的時間戳記回應。處理程序會確認時間戳記具有TSA的有效簽名、而且您的輸入檔尚未變更。驗證會在您的機器本機上執行。獨立而言、不需要存取TSA伺服器。

+
[listing]
----
openssl ts -verify -data ontap-mediator-1.5.0.sig -in ontap-mediator-1.5.0.sig.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -untrusted tsa-prod-ONTAP-Mediator.pem
openssl ts -verify -data ontap-mediator-1.5.0 -in ontap-mediator-1.5.0.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -untrusted tsa-prod-ONTAP-Mediator.pem
----
. 根據金鑰驗證簽名：  `openssl -dgst -verify`
+
[listing]
----
openssl dgst -sha256 -verify ONTAP-Mediator-production.pub -signature ontap-mediator-1.5.0.sig ontap-mediator-1.5.0
----


.驗證ONTAP 樣例：驗證樣碼簽章（主控台輸出）
[%collapsible]
====
[listing]
----
[root@scspa2695423001 ontap-mediator-1.5.0]# pwd
/root/ontap-mediator-1.5.0
[root@scspa2695423001 ontap-mediator-1.5.0]# ls -l
total 63660
-r--r--r-- 1 root root     8582 Oct 19 15:02 csc-prod-chain-ONTAP-Mediator.pem
-r--r--r-- 1 root root     2373 Oct 19 15:02 csc-prod-ONTAP-Mediator.pem
-r-xr-xr-- 1 root root 65132818 Oct 20 15:17 ontap-mediator-1.5.0
-rw-r--r-- 1 root root      384 Oct 20 15:17 ontap-mediator-1.5.0.sig
-rw-r--r-- 1 root root     5437 Oct 20 15:17 ontap-mediator-1.5.0.sig.tsr
-rw-r--r-- 1 root root     5436 Oct 20 15:17 ontap-mediator-1.5.0.tsr
-r--r--r-- 1 root root      625 Oct 19 15:02 ONTAP-Mediator-production.pub
-r--r--r-- 1 root root     3323 Oct 19 15:02 tsa-prod-chain-ONTAP-Mediator.pem
-r--r--r-- 1 root root     1740 Oct 19 15:02 tsa-prod-ONTAP-Mediator.pem
[root@scspa2695423001 ontap-mediator-1.5.0]#
[root@scspa2695423001 ontap-mediator-1.5.0]# /root/verify_ontap_mediator_signatures.sh
++ openssl version -d
++ cut -d '"' -f2
+ OPENSSLDIR=/etc/pki/tls
+ openssl version
OpenSSL 1.1.1k  FIPS 25 Mar 2021
++ openssl x509 -noout -ocsp_uri -in csc-prod-chain-ONTAP-Mediator.pem
+ ocsp_uri=http://ocsp.entrust.net
+ echo http://ocsp.entrust.net
http://ocsp.entrust.net
+ openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem -reqout req.der
+ openssl ocsp -issuer csc-prod-chain-ONTAP-Mediator.pem -CAfile csc-prod-chain-ONTAP-Mediator.pem -cert csc-prod-ONTAP-Mediator.pem -url http://ocsp.entrust.net -resp_text -respout resp.der
OCSP Response Data:
    OCSP Response Status: successful (0x0)
    Response Type: Basic OCSP Response
    Version: 1 (0x0)
    Responder Id: C = US, O = "Entrust, Inc.", CN = Entrust Extended Validation Code Signing CA - EVCS2
    Produced At: Oct 28 05:01:00 2022 GMT
    Responses:
    Certificate ID:
      Hash Algorithm: sha1
      Issuer Name Hash: 69FA640329AB84E27220FE0927647B8194B91F2A
      Issuer Key Hash: CE894F8251AA15A28462CA312361D261FBF8FE78
      Serial Number: 511A542B57522AEB7295A640DC6200E5
    Cert Status: good
    This Update: Oct 28 05:00:00 2022 GMT
    Next Update: Nov  4 04:59:59 2022 GMT

    Signature Algorithm: sha512WithRSAEncryption
         3c:1d:49:b0:93:62:37:3e:c7:38:e3:9f:9f:62:82:73:ed:f4:
         ea:00:6b:f1:01:cd:79:57:92:f1:9d:5d:85:9b:60:59:f8:6c:
         e6:f4:50:51:f3:4c:8a:51:dd:50:68:16:8f:20:24:7e:39:b0:
         44:94:8d:b0:61:da:b9:08:36:74:2d:44:55:62:fb:92:be:4a:
         e7:6c:8c:49:dd:0c:fd:d8:ce:20:08:0d:0f:5a:29:a3:19:03:
         9f:d3:df:41:f4:89:0f:73:18:3f:ac:bb:a7:a3:96:7d:c5:70:
         4c:57:cd:17:17:c6:8a:60:d1:37:c9:2d:81:07:2a:d7:a6:02:
         ee:ce:88:16:22:db:e3:43:64:1e:9b:0d:4d:31:66:fa:ab:a5:
         52:99:94:4a:4a:d0:52:c5:34:f5:18:c7:15:5b:ce:74:c2:fc:
         61:ea:55:aa:f1:2f:82:a3:6a:95:8d:7e:2b:38:49:4f:bf:b1:
         68:7b:1b:24:8b:1f:4d:c5:77:f0:71:af:9c:34:c8:7a:82:50:
         09:a2:19:6e:c6:30:4f:da:a2:79:08:f9:d0:ff:85:d9:2a:84:
         cf:0c:aa:75:8f:72:c9:a7:a2:83:e8:8b:cf:ed:0c:69:75:b6:
         2a:7b:6b:58:99:01:d8:34:ad:e1:89:25:27:1b:fa:d9:6d:32:
         97:3a:0b:0a:8e:a3:9e:e3:f4:e0:d6:1a:c9:b5:14:8c:3e:54:
         3b:37:17:1a:93:44:84:8b:4a:87:97:1e:76:43:3e:d3:ec:8b:
         7e:56:4a:3f:01:31:c0:e5:58:fb:50:ce:6f:b1:e7:35:f9:b7:
         a3:ef:6b:3b:21:95:37:a6:5b:8f:f0:15:18:36:65:89:a1:9c:
         9b:69:00:b4:b1:65:6a:bc:11:2d:d4:9b:b4:97:cc:cb:7a:0c:
         16:11:c1:75:58:7e:13:ab:56:3c:3f:93:5b:95:24:c6:54:52:
         1f:86:a9:16:ce:d9:ea:8b:3a:f3:4f:c4:8f:ad:de:e8:3e:3c:
         d2:51:51:ad:33:7f:d8:c5:33:24:26:f1:2d:9d:0e:9f:55:d0:
         68:bf:af:bd:68:4a:40:08:bc:92:a0:62:54:7d:16:7b:36:29:
         15:b1:cd:58:8e:fb:4a:f2:3e:94:8b:fe:56:95:cc:24:32:af:
         5f:71:99:18:ed:0c:64:94:f7:54:48:87:48:d0:6d:b3:42:04:
         96:03:73:a2:8e:8a:6a:b2:af:ee:56:19:a1:c6:35:12:59:ad:
         19:6a:fe:e0:f1:27:cc:96:4e:f0:4f:fb:6a:bd:ce:05:2c:aa:
         79:7c:df:02:5c:ca:53:7d:60:12:88:7c:ce:15:c7:d4:02:27:
         c1:ab:cf:71:30:1e:14:ba
WARNING: no nonce in response
Response verify OK
csc-prod-ONTAP-Mediator.pem: good
        This Update: Oct 28 05:00:00 2022 GMT
        Next Update: Nov  4 04:59:59 2022 GMT
+ openssl verify -untrusted csc-prod-chain-ONTAP-Mediator.pem -CApath /etc/pki/tls csc-prod-ONTAP-Mediator.pem
csc-prod-ONTAP-Mediator.pem: OK
+ openssl verify -untrusted tsa-prod-chain-ONTAP-Mediator.pem -CApath /etc/pki/tls tsa-prod-ONTAP-Mediator.pem
tsa-prod-ONTAP-Mediator.pem: OK
+ openssl ts -verify -data ontap-mediator-1.5.0.sig -in ontap-mediator-1.5.0.sig.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -untrusted tsa-prod-ONTAP-Mediator.pem
Using configuration from /etc/pki/tls/openssl.cnf
Verification: OK
+ openssl ts -verify -data ontap-mediator-1.5.0 -in ontap-mediator-1.5.0.tsr -CAfile tsa-prod-chain-ONTAP-Mediator.pem -untrusted tsa-prod-ONTAP-Mediator.pem
Using configuration from /etc/pki/tls/openssl.cnf
Verification: OK
+ openssl dgst -sha256 -verify ONTAP-Mediator-production.pub -signature ontap-mediator-1.5.0.sig ontap-mediator-1.5.0
Verified OK
[root@scspa2695423001 ontap-mediator-1.5.0]#

----
====


== 安裝ONTAP 《不知道如何安裝》套件

.關於這項工作
* 從ONTAP 推出支援程式1.4開始、安全開機機制就會在UEFI系統上啟用。啟用「安全開機」時、您必須在安裝後採取其他步驟來登錄安全金鑰：
+
** 請遵循README檔案中的指示：「/opt/netapp/lib/ontap中介器/ontap中介器/SCST_mod_keys/README、module-Signing」來簽署SCST核心模組。
** 找到所需的金鑰：「/opt/netapp/lib/ontapp_moder_keys」


+

NOTE: 安裝後、系統輸出也會提供README檔案和主要位置。



.步驟
. 執行安裝程式並視需要回應提示： `./ontap-mediator-1.5.0/ontap-mediator-1.5.0 -y`
+
[listing]
----
[root@scs000099753 ~]# ./ontap-mediator-1.5.0/ontap-mediator-1.5.0 -y
----
+
安裝程序會繼續建立所需的帳戶、並安裝所需的套件。如果主機上已安裝舊版的「媒體資訊器」、系統會提示您確認是否要升級。



.安裝過程範例ONTAP ：安裝過程（主控台輸出）
[%collapsible]
====
[listing]
----
[root@scs000099753 ~]# ./ontap-mediator-1.5.0/ontap-mediator-1.5.0 -y
ONTAP Mediator: Self Extracting Installer


+ Extracting the ONTAP Mediator installation/upgrade archive
+ Performing the ONTAP Mediator run-time code signature check
   Using openssl from the path: /usr/bin/openssl configured for CApath:/etc/pki/tls

+ Unpacking the ONTAP Mediator installer
ONTAP Mediator requires two user accounts. One for the service (netapp), and one for use by ONTAP to the mediator API (mediatoradmin).
Using default account names: netapp + mediatoradmin

Enter ONTAP Mediator user account (mediatoradmin) password:

Re-Enter ONTAP Mediator user account (mediatoradmin) password:

+ Checking if SELinux is in enforcing mode


+ Checking for default Linux firewall
success
success
success


###############################################################
Preparing for installation of ONTAP Mediator packages.


+ Installing required packages.


Last metadata expiration check: 0:25:24 ago on Fri 21 Oct 2022 04:00:13 PM EDT.
Package openssl-1:1.1.1k-4.el8.x86_64 is already installed.
Package gcc-8.4.1-1.el8.x86_64 is already installed.
Package python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64 is already installed.
Package libselinux-utils-2.9-5.el8.x86_64 is already installed.
Package perl-Data-Dumper-2.167-399.el8.x86_64 is already installed.
Package efibootmgr-16-1.el8.x86_64 is already installed.
Package mokutil-1:0.3.0-11.el8.x86_64 is already installed.
Package python3-pip-9.0.3-19.el8.noarch is already installed.
Package policycoreutils-python-utils-2.9-14.el8.noarch is already installed.
Dependencies resolved.
========================================================================================================================================================================================
 Package                                       Architecture            Version                                                  Repository                                         Size
========================================================================================================================================================================================
Installing:
 bzip2                                         x86_64                  1.0.6-26.el8                                             rhel-8-for-x86_64-baseos-rpms                      60 k
 elfutils-libelf-devel                         x86_64                  0.186-1.el8                                              rhel-8-for-x86_64-baseos-rpms                      60 k
 kernel-devel                                  x86_64                  4.18.0-348.el8                                           rhel-8-for-x86_64-baseos-rpms                      20 M
 make                                          x86_64                  1:4.2.1-11.el8                                           rhel-8-for-x86_64-baseos-rpms                     498 k
 openssl-devel                                 x86_64                  1:1.1.1k-7.el8_6                                         rhel-8-for-x86_64-baseos-rpms                     2.3 M
 patch                                         x86_64                  2.7.6-11.el8                                             rhel-8-for-x86_64-baseos-rpms                     138 k
 perl-ExtUtils-MakeMaker                       noarch                  1:7.34-1.el8                                             rhel-8-for-x86_64-appstream-rpms                  301 k
 python36-devel                                x86_64                  3.6.8-38.module+el8.5.0+12207+5c5719bc                   rhel-8-for-x86_64-appstream-rpms                   17 k
 redhat-lsb-core                               x86_64                  4.1-47.el8                                               rhel-8-for-x86_64-appstream-rpms                   45 k
Upgrading:
 cpp                                           x86_64                  8.5.0-10.1.el8_6                                         rhel-8-for-x86_64-appstream-rpms                   10 M
 elfutils-libelf                               x86_64                  0.186-1.el8                                              rhel-8-for-x86_64-baseos-rpms                     229 k
 elfutils-libs                                 x86_64                  0.186-1.el8                                              rhel-8-for-x86_64-baseos-rpms                     295 k
 gcc                                           x86_64                  8.5.0-10.1.el8_6                                         rhel-8-for-x86_64-appstream-rpms                   23 M
 libgcc                                        x86_64                  8.5.0-10.1.el8_6                                         rhel-8-for-x86_64-baseos-rpms                      80 k
 libgomp                                       x86_64                  8.5.0-10.1.el8_6                                         rhel-8-for-x86_64-baseos-rpms                     207 k
 libsemanage                                   x86_64                  2.9-8.el8                                                rhel-8-for-x86_64-baseos-rpms                     168 k
 mokutil                                       x86_64                  1:0.3.0-11.el8_6.1                                       rhel-8-for-x86_64-baseos-rpms                      46 k
 openssl                                       x86_64                  1:1.1.1k-7.el8_6                                         rhel-8-for-x86_64-baseos-rpms                     709 k
 openssl-libs                                  x86_64                  1:1.1.1k-7.el8_6                                         rhel-8-for-x86_64-baseos-rpms                     1.5 M
 platform-python-pip                           noarch                  9.0.3-22.el8                                             rhel-8-for-x86_64-baseos-rpms                     1.6 M
 policycoreutils                               x86_64                  2.9-19.el8                                               rhel-8-for-x86_64-baseos-rpms                     374 k
 policycoreutils-python-utils                  noarch                  2.9-19.el8                                               rhel-8-for-x86_64-baseos-rpms                     253 k
 python3-libsemanage                           x86_64                  2.9-8.el8                                                rhel-8-for-x86_64-baseos-rpms                     128 k
 python3-pip                                   noarch                  9.0.3-22.el8                                             rhel-8-for-x86_64-appstream-rpms                   20 k
 python3-policycoreutils                       noarch                  2.9-19.el8                                               rhel-8-for-x86_64-baseos-rpms                     2.2 M
 python36                                      x86_64                  3.6.8-38.module+el8.5.0+12207+5c5719bc                   rhel-8-for-x86_64-appstream-rpms                   19 k
Installing dependencies:
 annobin                                       x86_64                  10.29-3.el8                                              rhel-8-for-x86_64-appstream-rpms                  117 k
 at                                            x86_64                  3.1.20-11.el8                                            rhel-8-for-x86_64-baseos-rpms                      81 k
 bc                                            x86_64                  1.07.1-5.el8                                             rhel-8-for-x86_64-baseos-rpms                     129 k
 cups-client                                   x86_64                  1:2.2.6-38.el8                                           rhel-8-for-x86_64-appstream-rpms                  169 k
 dwz                                           x86_64                  0.12-10.el8                                              rhel-8-for-x86_64-appstream-rpms                  109 k
 ed                                            x86_64                  1.14.2-4.el8                                             rhel-8-for-x86_64-baseos-rpms                      82 k
 efi-srpm-macros                               noarch                  3-3.el8                                                  rhel-8-for-x86_64-appstream-rpms                   22 k
 esmtp                                         x86_64                  1.2-15.el8                                               EPEL-8                                             57 k
 ghc-srpm-macros                               noarch                  1.4.2-7.el8                                              rhel-8-for-x86_64-appstream-rpms                  9.4 k
 go-srpm-macros                                noarch                  2-17.el8                                                 rhel-8-for-x86_64-appstream-rpms                   13 k
 keyutils-libs-devel                           x86_64                  1.5.10-6.el8                                             rhel-8-for-x86_64-baseos-rpms                      48 k
 krb5-devel                                    x86_64                  1.18.2-14.el8                                            rhel-8-for-x86_64-baseos-rpms                     560 k
 libcom_err-devel                              x86_64                  1.45.6-2.el8                                             rhel-8-for-x86_64-baseos-rpms                      38 k
 libesmtp                                      x86_64                  1.0.6-18.el8                                             EPEL-8                                             70 k
 libkadm5                                      x86_64                  1.18.2-14.el8                                            rhel-8-for-x86_64-baseos-rpms                     187 k
 liblockfile                                   x86_64                  1.14-1.el8                                               rhel-8-for-x86_64-appstream-rpms                   32 k
 libselinux-devel                              x86_64                  2.9-5.el8                                                rhel-8-for-x86_64-baseos-rpms                     200 k
 libsepol-devel                                x86_64                  2.9-3.el8                                                rhel-8-for-x86_64-baseos-rpms                      87 k
 libverto-devel                                x86_64                  0.3.0-5.el8                                              rhel-8-for-x86_64-baseos-rpms                      18 k
 m4                                            x86_64                  1.4.18-7.el8                                             rhel-8-for-x86_64-baseos-rpms                     223 k
 mailx                                         x86_64                  12.5-29.el8                                              rhel-8-for-x86_64-baseos-rpms                     257 k
 ncurses-compat-libs                           x86_64                  6.1-9.20180224.el8                                       rhel-8-for-x86_64-baseos-rpms                     328 k
 ocaml-srpm-macros                             noarch                  5-4.el8                                                  rhel-8-for-x86_64-appstream-rpms                  9.5 k
 openblas-srpm-macros                          noarch                  2-2.el8                                                  rhel-8-for-x86_64-appstream-rpms                  8.0 k
 pcre2-devel                                   x86_64                  10.32-2.el8                                              rhel-8-for-x86_64-baseos-rpms                     605 k
 pcre2-utf16                                   x86_64                  10.32-2.el8                                              rhel-8-for-x86_64-baseos-rpms                     229 k
 pcre2-utf32                                   x86_64                  10.32-2.el8                                              rhel-8-for-x86_64-baseos-rpms                     220 k
 perl-CPAN-Meta-YAML                           noarch                  0.018-397.el8                                            rhel-8-for-x86_64-appstream-rpms                   34 k
 perl-ExtUtils-Command                         noarch                  1:7.34-1.el8                                             rhel-8-for-x86_64-appstream-rpms                   19 k
 perl-ExtUtils-Install                         noarch                  2.14-4.el8                                               rhel-8-for-x86_64-appstream-rpms                   46 k
 perl-ExtUtils-Manifest                        noarch                  1.70-395.el8                                             rhel-8-for-x86_64-appstream-rpms                   37 k
 perl-ExtUtils-ParseXS                         noarch                  1:3.35-2.el8                                             rhel-8-for-x86_64-appstream-rpms                   83 k
 perl-JSON-PP                                  noarch                  1:2.97.001-3.el8                                         rhel-8-for-x86_64-appstream-rpms                   68 k
 perl-Math-BigInt                              noarch                  1:1.9998.11-7.el8                                        rhel-8-for-x86_64-baseos-rpms                     196 k
 perl-Math-Complex                             noarch                  1.59-421.el8                                             rhel-8-for-x86_64-baseos-rpms                     109 k
 perl-Test-Harness                             noarch                  1:3.42-1.el8                                             rhel-8-for-x86_64-appstream-rpms                  279 k
 perl-devel                                    x86_64                  4:5.26.3-419.el8_4.1                                     rhel-8-for-x86_64-appstream-rpms                  599 k
 perl-srpm-macros                              noarch                  1-25.el8                                                 rhel-8-for-x86_64-appstream-rpms                   11 k
 perl-version                                  x86_64                  6:0.99.24-1.el8                                          rhel-8-for-x86_64-appstream-rpms                   67 k
 platform-python-devel                         x86_64                  3.6.8-41.el8                                             rhel-8-for-x86_64-appstream-rpms                  249 k
 python-rpm-macros                             noarch                  3-41.el8                                                 rhel-8-for-x86_64-appstream-rpms                   15 k
 python-srpm-macros                            noarch                  3-41.el8                                                 rhel-8-for-x86_64-appstream-rpms                   15 k
 python3-pyparsing                             noarch                  2.1.10-7.el8                                             rhel-8-for-x86_64-baseos-rpms                     142 k
 python3-rpm-generators                        noarch                  5-7.el8                                                  rhel-8-for-x86_64-appstream-rpms                   25 k
 python3-rpm-macros                            noarch                  3-41.el8                                                 rhel-8-for-x86_64-appstream-rpms                   14 k
 qt5-srpm-macros                               noarch                  5.15.2-1.el8                                             rhel-8-for-x86_64-appstream-rpms                   11 k
 redhat-lsb-submod-security                    x86_64                  4.1-47.el8                                               rhel-8-for-x86_64-appstream-rpms                   22 k
 redhat-rpm-config                             noarch                  125-1.el8                                                rhel-8-for-x86_64-appstream-rpms                   87 k
 rust-srpm-macros                              noarch                  5-2.el8                                                  rhel-8-for-x86_64-appstream-rpms                  9.3 k
 spax                                          x86_64                  1.5.3-13.el8                                             rhel-8-for-x86_64-baseos-rpms                     217 k
 systemtap-sdt-devel                           x86_64                  4.6-4.el8                                                rhel-8-for-x86_64-appstream-rpms                   86 k
 time                                          x86_64                  1.9-3.el8                                                rhel-8-for-x86_64-baseos-rpms                      54 k
 unzip                                         x86_64                  6.0-46.el8                                               rhel-8-for-x86_64-baseos-rpms                     196 k
 util-linux-user                               x86_64                  2.32.1-28.el8                                            rhel-8-for-x86_64-baseos-rpms                     100 k
 zip                                           x86_64                  3.0-23.el8                                               rhel-8-for-x86_64-baseos-rpms                     270 k
 zlib-devel                                    x86_64                  1.2.11-17.el8                                            rhel-8-for-x86_64-baseos-rpms                      58 k
Installing weak dependencies:
 perl-CPAN-Meta                                noarch                  2.150010-396.el8                                         rhel-8-for-x86_64-appstream-rpms                  191 k
 perl-CPAN-Meta-Requirements                   noarch                  2.140-396.el8                                            rhel-8-for-x86_64-appstream-rpms                   37 k
 perl-Encode-Locale                            noarch                  1.05-10.module+el8.3.0+6498+9eecfe51                     rhel-8-for-x86_64-appstream-rpms                   22 k
 perl-Time-HiRes                               x86_64                  4:1.9758-2.el8                                           rhel-8-for-x86_64-appstream-rpms                   61 k

Transaction Summary
========================================================================================================================================================================================
Install  69 Packages
Upgrade  17 Packages

Total download size: 72 M
Is this ok [y/N]: y
Downloading Packages:
(1/86): perl-ExtUtils-Install-2.14-4.el8.noarch.rpm                                                                                                     735 kB/s |  46 kB     00:00
(2/86): libesmtp-1.0.6-18.el8.x86_64.rpm                                                                                                                1.0 MB/s |  70 kB     00:00
(3/86): esmtp-1.2-15.el8.x86_64.rpm                                                                                                                     747 kB/s |  57 kB     00:00
(4/86): rust-srpm-macros-5-2.el8.noarch.rpm                                                                                                             308 kB/s | 9.3 kB     00:00
(5/86): perl-ExtUtils-Manifest-1.70-395.el8.noarch.rpm                                                                                                  781 kB/s |  37 kB     00:00
(6/86): perl-CPAN-Meta-2.150010-396.el8.noarch.rpm                                                                                                      2.7 MB/s | 191 kB     00:00
(7/86): ocaml-srpm-macros-5-4.el8.noarch.rpm                                                                                                            214 kB/s | 9.5 kB     00:00
(8/86): perl-JSON-PP-2.97.001-3.el8.noarch.rpm                                                                                                          1.2 MB/s |  68 kB     00:00
(9/86): perl-ExtUtils-MakeMaker-7.34-1.el8.noarch.rpm                                                                                                   5.8 MB/s | 301 kB     00:00
(10/86): ghc-srpm-macros-1.4.2-7.el8.noarch.rpm                                                                                                         317 kB/s | 9.4 kB     00:00
(11/86): perl-Test-Harness-3.42-1.el8.noarch.rpm                                                                                                        4.5 MB/s | 279 kB     00:00
(12/86): perl-ExtUtils-Command-7.34-1.el8.noarch.rpm                                                                                                    520 kB/s |  19 kB     00:00

...
                                                                                                         15 MB/s | 1.5 MB     00:00
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                    35 MB/s |  72 MB     00:02
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                1/1
  Running scriptlet: openssl-libs-1:1.1.1k-7.el8_6.x86_64                                                                                                                           1/1
  Upgrading        : openssl-libs-1:1.1.1k-7.el8_6.x86_64                                                                                                                         1/103
  Running scriptlet: openssl-libs-1:1.1.1k-7.el8_6.x86_64                                                                                                                         1/103
  Upgrading        : libgcc-8.5.0-10.1.el8_6.x86_64                                                                                                                               2/103
  Running scriptlet: libgcc-8.5.0-10.1.el8_6.x86_64                                                                                                                               2/103
  Upgrading        : elfutils-libelf-0.186-1.el8.x86_64                                                                                                                           3/103
  Installing       : perl-version-6:0.99.24-1.el8.x86_64                                                                                                                          4/103
  Installing       : perl-CPAN-Meta-Requirements-2.140-396.el8.noarch                                                                                                             5/103
  Upgrading        : libsemanage-2.9-8.el8.x86_64                                                                                                                                 6/103
  Installing       : zlib-devel-1.2.11-17.el8.x86_64                                                                                                                              7/103
  Installing       : python-srpm-macros-3-41.el8.noarch                                                                                                                           8/103
  Installing       : python-rpm-macros-3-41.el8.noarch                                                                                                                            9/103
  Installing       : python3-rpm-macros-3-41.el8.noarch                                                                                                                          10/103
  Installing       : perl-Time-HiRes-4:1.9758-2.el8.x86_64                                                                                                                       11/103
  Installing       : perl-ExtUtils-ParseXS-1:3.35-2.el8.noarch                                                                                                                   12/103
  Installing       : perl-Test-Harness-1:3.42-1.el8.noarch                                                                                                                       13/103
  Upgrading        : python3-libsemanage-2.9-8.el8.x86_64                                                                                                                        14/103
  Upgrading        : policycoreutils-2.9-19.el8.x86_64                                                                                                                           15/103
  Running scriptlet: policycoreutils-2.9-19.el8.x86_64                                                                                                                           15/103
  Upgrading        : python3-policycoreutils-2.9-19.el8.noarch                                                                                                                   16/103
  Installing       : dwz-0.12-10.el8.x86_64                                                                                                                                      17/103
  Installing       : ncurses-compat-libs-6.1-9.20180224.el8.x86_64                                                                                                               18/103
  Installing       : libesmtp-1.0.6-18.el8.x86_64                                                                                                                                19/103
  Installing       : mailx-12.5-29.el8.x86_64                                                                                                                                    20/103
  Installing       : libkadm5-1.18.2-14.el8.x86_64                                                                                                                               21/103
  Upgrading        : libgomp-8.5.0-10.1.el8_6.x86_64                                                                                                                             22/103
  Running scriptlet: libgomp-8.5.0-10.1.el8_6.x86_64                                                                                                                             22/103
  Upgrading        : platform-python-pip-9.0.3-22.el8.noarch                                                                                                                     23/103
  Upgrading        : python3-pip-9.0.3-22.el8.noarch                                                                                                                             24/103
  Upgrading        : python36-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64                                                                                                      25/103
  Running scriptlet: python36-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64                                                                                                      25/103
  Upgrading        : cpp-8.5.0-10.1.el8_6.x86_64                                                                                                                                 26/103
  Running scriptlet: cpp-8.5.0-10.1.el8_6.x86_64                                                                                                                                 26/103
  Upgrading        : gcc-8.5.0-10.1.el8_6.x86_64                                                                                                                                 27/103
  Running scriptlet: gcc-8.5.0-10.1.el8_6.x86_64                                                                                                                                 27/103
  Installing       : annobin-10.29-3.el8.x86_64                                                                                                                                  28/103
  Installing       : unzip-6.0-46.el8.x86_64                                                                                                                                     29/103
  Installing       : zip-3.0-23.el8.x86_64                                                                                                                                       30/103
  Installing       : perl-Math-Complex-1.59-421.el8.noarch                                                                                                                       31/103
  Installing       : perl-Math-BigInt-1:1.9998.11-7.el8.noarch                                                                                                                   32/103
  Installing       : perl-JSON-PP-1:2.97.001-3.el8.noarch                                                                                                                        33/103
  Installing       : make-1:4.2.1-11.el8.x86_64                                                                                                                                  34/103
  Running scriptlet: make-1:4.2.1-11.el8.x86_64                                                                                                                                  34/103
  Installing       : libcom_err-devel-1.45.6-2.el8.x86_64                                                                                                                        35/103
  Installing       : util-linux-user-2.32.1-28.el8.x86_64                                                                                                                        36/103
  Installing       : libsepol-devel-2.9-3.el8.x86_64                                                                                                                             37/103
  Installing       : pcre2-utf32-10.32-2.el8.x86_64                                                                                                                              38/103
  Installing       : pcre2-utf16-10.32-2.el8.x86_64                                                                                                                              39/103
  Installing       : pcre2-devel-10.32-2.el8.x86_64                                                                                                                              40/103
  Installing       : libselinux-devel-2.9-5.el8.x86_64                                                                                                                           41/103
  Installing       : patch-2.7.6-11.el8.x86_64                                                                                                                                   42/103
  Installing       : python3-pyparsing-2.1.10-7.el8.noarch                                                                                                                       43/103
  Installing       : systemtap-sdt-devel-4.6-4.el8.x86_64                                                                                                                        44/103
  Installing       : spax-1.5.3-13.el8.x86_64                                                                                                                                    45/103
  Running scriptlet: spax-1.5.3-13.el8.x86_64                                                                                                                                    45/103
  Installing       : m4-1.4.18-7.el8.x86_64                                                                                                                                      46/103
  Running scriptlet: m4-1.4.18-7.el8.x86_64                                                                                                                                      46/103
  Installing       : libverto-devel-0.3.0-5.el8.x86_64                                                                                                                           47/103
  Installing       : bc-1.07.1-5.el8.x86_64                                                                                                                                      48/103
  Running scriptlet: bc-1.07.1-5.el8.x86_64                                                                                                                                      48/103
  Installing       : at-3.1.20-11.el8.x86_64                                                                                                                                     49/103
  Running scriptlet: at-3.1.20-11.el8.x86_64                                                                                                                                     49/103
  Installing       : keyutils-libs-devel-1.5.10-6.el8.x86_64                                                                                                                     50/103
  Installing       : krb5-devel-1.18.2-14.el8.x86_64                                                                                                                             51/103
  Installing       : time-1.9-3.el8.x86_64                                                                                                                                       52/103
  Running scriptlet: time-1.9-3.el8.x86_64                                                                                                                                       52/103

  Upgrading        : policycoreutils-python-utils-2.9-19.el8.noarch                                                                                                              80/103
  Installing       : elfutils-libelf-devel-0.186-1.el8.x86_64                                                                                                                    81/103
  Upgrading        : elfutils-libs-0.186-1.el8.x86_64                                                                                                                            82/103
  Upgrading        : mokutil-1:0.3.0-11.el8_6.1.x86_64                                                                                                                           83/103
  Upgrading        : openssl-1:1.1.1k-7.el8_6.x86_64                                                                                                                             84/103
  Installing       : kernel-devel-4.18.0-348.el8.x86_64                                                                                                                          85/103
  Running scriptlet: kernel-devel-4.18.0-348.el8.x86_64

  ...
                                                                                                                       85/103
  Installing       : bzip2-1.0.6-26.el8.x86_64                                                                                                                                   86/103
  Cleanup          : policycoreutils-python-utils-2.9-14.el8.noarch                                                                                                              87/103
  Cleanup          : python3-policycoreutils-2.9-14.el8.noarch                                                                                                                   88/103
  Cleanup          : python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64                                                                                                        89/103
  Running scriptlet: python36-3.6.8-2.module+el8.1.0+3334+5cb623d7.x86_64                                                                                                        89/103
  Cleanup          : elfutils-libs-0.185-1.el8.x86_64                                                                                                                            90/103
  Cleanup          : openssl-1:1.1.1k-4.el8.x86_64                                                                                                                               91/103
  Cleanup          : python3-libsemanage-2.9-6.el8.x86_64                                                                                                                        92/103
  Running scriptlet: gcc-8.4.1-1.el8.x86_64                                                                                                                                      93/103
  Cleanup          : gcc-8.4.1-1.el8.x86_64                                                                                                                                      93/103
  Running scriptlet: policycoreutils-2.9-14.el8.x86_64                                                                                                                           94/103
  Cleanup          : policycoreutils-2.9-14.el8.x86_64                                                                                                                           94/103
  Cleanup          : mokutil-1:0.3.0-11.el8.x86_64                                                                                                                               95/103
  Cleanup          : python3-pip-9.0.3-19.el8.noarch                                                                                                                             96/103
  Cleanup          : platform-python-pip-9.0.3-19.el8.noarch                                                                                                                     97/103
  Cleanup          : openssl-libs-1:1.1.1k-4.el8.x86_64                                                                                                                          98/103
  Running scriptlet: openssl-libs-1:1.1.1k-4.el8.x86_64                                                                                                                          98/103
  Cleanup          : libsemanage-2.9-6.el8.x86_64                                                                                                                                99/103
  Running scriptlet: cpp-8.4.1-1.el8.x86_64                                                                                                                                     100/103
  Cleanup          : cpp-8.4.1-1.el8.x86_64                                                                                                                                     100/103
  Cleanup          : libgcc-8.5.0-3.el8.x86_64                                                                                                                                  101/103
  Running scriptlet: libgcc-8.5.0-3.el8.x86_64                                                                                                                                  101/103
  Running scriptlet: libgomp-8.4.1-1.el8.x86_64                                                                                                                                 102/103
  Cleanup          : libgomp-8.4.1-1.el8.x86_64                                                                                                                                 102/103
  Running scriptlet: libgomp-8.4.1-1.el8.x86_64                                                                                                                                 102/103
  Cleanup          : elfutils-libelf-0.185-1.el8.x86_64                                                                                                                         103/103
  Running scriptlet: elfutils-libelf-0.185-1.el8.x86_64                                                                                                                         103/103
  Verifying        : esmtp-1.2-15.el8.x86_64                                                                                                                                      1/103
  Verifying        : libesmtp-1.0.6-18.el8.x86_64

  ...

Upgraded:
  cpp-8.5.0-10.1.el8_6.x86_64                              elfutils-libelf-0.186-1.el8.x86_64     elfutils-libs-0.186-1.el8.x86_64          gcc-8.5.0-10.1.el8_6.x86_64
  libgcc-8.5.0-10.1.el8_6.x86_64                           libgomp-8.5.0-10.1.el8_6.x86_64        libsemanage-2.9-8.el8.x86_64              mokutil-1:0.3.0-11.el8_6.1.x86_64
  openssl-1:1.1.1k-7.el8_6.x86_64                          openssl-libs-1:1.1.1k-7.el8_6.x86_64   platform-python-pip-9.0.3-22.el8.noarch   policycoreutils-2.9-19.el8.x86_64
  policycoreutils-python-utils-2.9-19.el8.noarch           python3-libsemanage-2.9-8.el8.x86_64   python3-pip-9.0.3-22.el8.noarch           python3-policycoreutils-2.9-19.el8.noarch
  python36-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64
Installed:
  annobin-10.29-3.el8.x86_64                                        at-3.1.20-11.el8.x86_64                             bc-1.07.1-5.el8.x86_64
  bzip2-1.0.6-26.el8.x86_64                                         cups-client-1:2.2.6-38.el8.x86_64                   dwz-0.12-10.el8.x86_64
  ed-1.14.2-4.el8.x86_64                                            efi-srpm-macros-3-3.el8.noarch                      elfutils-libelf-devel-0.186-1.el8.x86_64
  esmtp-1.2-15.el8.x86_64                                           ghc-srpm-macros-1.4.2-7.el8.noarch                  go-srpm-macros-2-17.el8.noarch
  kernel-devel-4.18.0-348.el8.x86_64                                keyutils-libs-devel-1.5.10-6.el8.x86_64             krb5-devel-1.18.2-14.el8.x86_64
  libcom_err-devel-1.45.6-2.el8.x86_64                              libesmtp-1.0.6-18.el8.x86_64                        libkadm5-1.18.2-14.el8.x86_64
  liblockfile-1.14-1.el8.x86_64                                     libselinux-devel-2.9-5.el8.x86_64                   libsepol-devel-2.9-3.el8.x86_64
  libverto-devel-0.3.0-5.el8.x86_64                                 m4-1.4.18-7.el8.x86_64                              mailx-12.5-29.el8.x86_64
  make-1:4.2.1-11.el8.x86_64                                        ncurses-compat-libs-6.1-9.20180224.el8.x86_64       ocaml-srpm-macros-5-4.el8.noarch
  openblas-srpm-macros-2-2.el8.noarch                               openssl-devel-1:1.1.1k-7.el8_6.x86_64               patch-2.7.6-11.el8.x86_64
  pcre2-devel-10.32-2.el8.x86_64                                    pcre2-utf16-10.32-2.el8.x86_64                      pcre2-utf32-10.32-2.el8.x86_64
  perl-CPAN-Meta-2.150010-396.el8.noarch                            perl-CPAN-Meta-Requirements-2.140-396.el8.noarch    perl-CPAN-Meta-YAML-0.018-397.el8.noarch
  perl-Encode-Locale-1.05-10.module+el8.3.0+6498+9eecfe51.noarch    perl-ExtUtils-Command-1:7.34-1.el8.noarch           perl-ExtUtils-Install-2.14-4.el8.noarch
  perl-ExtUtils-MakeMaker-1:7.34-1.el8.noarch                       perl-ExtUtils-Manifest-1.70-395.el8.noarch          perl-ExtUtils-ParseXS-1:3.35-2.el8.noarch
  perl-JSON-PP-1:2.97.001-3.el8.noarch                              perl-Math-BigInt-1:1.9998.11-7.el8.noarch           perl-Math-Complex-1.59-421.el8.noarch
  perl-Test-Harness-1:3.42-1.el8.noarch                             perl-Time-HiRes-4:1.9758-2.el8.x86_64               perl-devel-4:5.26.3-419.el8_4.1.x86_64
  perl-srpm-macros-1-25.el8.noarch                                  perl-version-6:0.99.24-1.el8.x86_64                 platform-python-devel-3.6.8-41.el8.x86_64
  python-rpm-macros-3-41.el8.noarch                                 python-srpm-macros-3-41.el8.noarch                  python3-pyparsing-2.1.10-7.el8.noarch
  python3-rpm-generators-5-7.el8.noarch                             python3-rpm-macros-3-41.el8.noarch                  python36-devel-3.6.8-38.module+el8.5.0+12207+5c5719bc.x86_64
  qt5-srpm-macros-5.15.2-1.el8.noarch                               redhat-lsb-core-4.1-47.el8.x86_64                   redhat-lsb-submod-security-4.1-47.el8.x86_64
  redhat-rpm-config-125-1.el8.noarch                                rust-srpm-macros-5-2.el8.noarch                     spax-1.5.3-13.el8.x86_64
  systemtap-sdt-devel-4.6-4.el8.x86_64                              time-1.9-3.el8.x86_64                               unzip-6.0-46.el8.x86_64
  util-linux-user-2.32.1-28.el8.x86_64                              zip-3.0-23.el8.x86_64                               zlib-devel-1.2.11-17.el8.x86_64

Complete!
OS package installations finished
+ Installing ONTAP Mediator. (Log: /tmp/ontap_mediator.JixKGP/ontap-mediator-1.5.0/ontap-mediator-1.5.0/install_20221021155929.log)
    This step will take several minutes. Use the log file to view progress.
    Sudoer config verified
    ONTAP Mediator rsyslog and logging rotation enabled
+ Install successful. (Moving log to /opt/netapp/lib/ontap_mediator/log/install_20221021155929.log)
+ WARNING: This system supports UEFI
           Secure Boot (SB) is currently disabled on this system.
           If SB is enabled in the future, SCST will not work unless the following action is taken:
           Using the keys in /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys follow
           instructions in /opt/netapp/lib/ontap_mediator/ontap_mediator/SCST_mod_keys/README.module-signing
           to sign the SCST kernel module. Note that reboot will be needed.
     SCST will not start automatically when Secure Boot is enabled and not configured properly.
+ Note: ONTAP Mediator uses a kernel module compiled specifically for the current
        OS. Using 'yum update' to upgrade the kernel might cause service interruption.
    For more information, see /opt/netapp/lib/ontap_mediator/README
[root@scs000099753 ~]# cat /etc/redhat-release
Red Hat Enterprise Linux release 8.5 (Ootpa)
[root@scs000099753 ~]#

----
====


== 驗證安裝

.步驟
. 執行下列命令以檢視ONTAP 「資訊不全」服務的狀態：
+
.. RUN：「ystemctl STATUS ONTAP_ONI者」
+
[listing]
----
[root@scspr1915530002 ~]# systemctl status ontap_mediator

 ontap_mediator.service - ONTAP Mediator
Loaded: loaded (/etc/systemd/system/ontap_mediator.service; enabled; vendor preset: disabled)
Active: active (running) since Mon 2022-04-18 10:41:49 EDT; 1 weeks 0 days ago
Process: 286710 ExecStop=/bin/kill -s INT $MAINPID (code=exited, status=0/SUCCESS)
Main PID: 286712 (uwsgi)
Status: "uWSGI is ready"
Tasks: 3 (limit: 49473)
Memory: 139.2M
CGroup: /system.slice/ontap_mediator.service
      ├─286712 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      ├─286716 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini
      └─286717 /opt/netapp/lib/ontap_mediator/pyenv/bin/uwsgi --ini /opt/netapp/lib/ontap_mediator/uwsgi/ontap_mediator.ini

[root@scspr1915530002 ~]#
----
.. RUN：「ystemctl STATUS SCIer-scst」
+
[listing]
----
[root@scspr1915530002 ~]# systemctl status mediator-scst
   Loaded: loaded (/etc/systemd/system/mediator-scst.service; enabled; vendor preset: disabled)
   Active: active (running) since Mon 2022-04-18 10:41:47 EDT; 1 weeks 0 days ago
  Process: 286595 ExecStart=/etc/init.d/scst start (code=exited, status=0/SUCCESS)
 Main PID: 286662 (iscsi-scstd)
    Tasks: 1 (limit: 49473)
   Memory: 1.2M
   CGroup: /system.slice/mediator-scst.service
           └─286662 /usr/local/sbin/iscsi-scstd

[root@scspr1915530002 ~]#
----


. 確認ONTAP 使用的連接埠：「Netstat」
+
[listing]
----
[root@scspr1905507001 ~]# netstat -anlt | grep -E '3260|31784'

         tcp   0   0 0.0.0.0:31784   0.0.0.0:*      LISTEN

         tcp   0   0 0.0.0.0:3260    0.0.0.0:*      LISTEN

         tcp6  0   0 :::3260         :::*           LISTEN
----




== 結果

現在已安裝並執行此功能。ONTAP必須在ONTAP 不完整的儲存系統中執行進一步的組態、才能使用「內化器」功能：

* 若要在ONTAP 不實的IP組態中使用此功能、MetroCluster 請參閱 link:https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_configuring_the_ontap_mediator_service_from_a_metrocluster_ip_configuration.html["從ONTAP 一套不實的IP組態設定「不實不作」MetroCluster 服務"^]
* 若要使用SnapMirror營運不中斷、請參閱 link:https://docs.netapp.com/us-en/ontap/smbc/smbc_install_confirm_ontap_cluster.html["安裝ONTAP 「支援中心服務」並確認ONTAP 「支援中心」組態"^]

