---
permalink: mediator/mediator-overview-concept.html 
sidebar: sidebar 
keywords: ontap mediator service, install requirements, mediator requirements 
summary: ONTAP Mediator 提供數種 ONTAP 功能。 
---
= ONTAP Mediator 概述
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ONTAP Mediator 提供數種 ONTAP 功能：

* 為 HA 中繼資料提供持續且有圍籬的儲存區。
* 做為 ping Proxy 、以實現控制器的活力。
* 提供同步節點健全狀況查詢功能、以協助仲裁判斷。


ONTAP Mediator 提供兩種額外的系統附加服務：

* *`ontap_mediator.service`*
+
維護 REST API 伺服器以管理 ONAP 關係。

* *`mediator-scst.service`*
+
控制 iSCSI 模組（ SCST ）的啟動和關閉。





== 提供給系統管理員的工具

提供給系統管理員的工具：

* *`/usr/local/bin/mediator_change_password`*
+
提供目前 API 使用者名稱和密碼時、請設定新的 API 密碼。

* *`/usr/local/bin/mediator_change_user`*
+
提供目前 API 使用者名稱和密碼時、請設定新的 API 使用者名稱。

* *`/usr/local/bin/mediator_generate_support_bundle`*
+
產生本機的 tmz 檔案、其中包含與 NetApp 客戶支援部門通訊所需的所有實用支援資訊。  這包括應用程式組態、記錄和一些系統資訊。  套件會在本機磁碟上產生、並可視需要手動傳輸。  儲存位置： /opt/NetApp/data/support_bundles/

* *`/usr/local/bin/uninstall_ontap_mediator`*
+
移除 ONTAP Mediator 套件和 SCST 核心模組。這包括所有組態、記錄和信箱資料。

* *`/usr/local/bin/mediator_unlock_user`*
+
如果達到驗證重試限制、就會釋放 API 使用者帳戶的鎖定。  此功能用於防止暴力密碼推導。  它會提示使用者輸入正確的使用者名稱和密碼。

* *`/usr/local/bin/mediator_add_user`*
+
（僅支援）用於在安裝時新增 API 使用者。





== 特別注意事項

ONTAP Mediator 仰賴 SCST 來提供 iSCSI （請參閱 http://scst.sourceforge.net/index.html[]）。  此套件是專為核心而在安裝期間編譯的核心模組。任何核心更新都可能需要重新安裝 SCST 。  或者、先解除安裝、再重新安裝 ONTAP Mediator 、然後重新設定 ONTAP 關係。


NOTE: 伺服器作業系統核心的任何更新都應與 ONTAP 中的維護時段協調。
