---
permalink: mediator/mediator-overview-concept.html 
sidebar: sidebar 
keywords: ontap mediator, install requirements, mediator requirements 
summary: ONTAP Mediator 提供數種 ONTAP 功能。 
---
= 瞭解 ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
本文檔指的是ONTAP Mediator 的本機版本。有關ONTAP Cloud Mediator（從ONTAP 9.17.1 開始提供）的信息，請參閱link:../snapmirror-active-sync/index.html["SnapMirror主動同步文檔"] 。

ONTAP 調解器為 ONTAP 功能提供了多種功能：

* 為 HA 中繼資料提供持續且有圍籬的儲存區。
* 做為 ping Proxy 、以實現控制器的活力。
* 提供同步節點健全狀況查詢功能、以協助仲裁判斷。


ONTAP 調解器提供兩項額外的 systemctl 服務：

* *`ontap_mediator.service`*
+
維護用於管理 ONTAP 關係的 REST API 伺服器。

* *`mediator-scst.service`*
+
控制 iSCSI 模組（ SCST ）的啟動和關閉。





== 提供給系統管理員的工具

提供給系統管理員的工具：

* *`/usr/local/bin/mediator_change_password`*
+
提供目前 API 使用者名稱和密碼時、請設定新的 API 密碼。

* *`/usr/local/bin/mediator_change_user`*
+
提供目前 API 使用者名稱和密碼時、請設定新的 API 使用者名稱。

* *`/usr/local/bin/mediator_generate_support_bundle`*
+
產生本機的 tmz 檔案、其中包含與 NetApp 客戶支援部門通訊所需的所有實用支援資訊。  這包括應用程式組態、記錄和一些系統資訊。  套件會在本機磁碟上產生、並可視需要手動傳輸。  儲存位置： /opt/NetApp/data/support_bundles/

* *`/usr/local/bin/uninstall_ontap_mediator`*
+
移除 ONTAP Mediator 套件和 SCST 核心模組。這包括所有組態、記錄和信箱資料。

* *`/usr/local/bin/mediator_unlock_user`*
+
如果達到驗證重試限制、就會釋放 API 使用者帳戶的鎖定。此功能用於防止暴力密碼推導。它會提示使用者輸入正確的使用者名稱和密碼。

* *`/usr/local/bin/mediator_add_user`*
+
（僅支援）用於在安裝時新增 API 使用者。





== SCST 和核心更新

ONTAP Mediator 使用 SCST 為 MetroCluster IP 組態中的通訊提供 iSCSI 功能。SCST 套件是一個核心模組，會在安裝過程中編譯。核心更新後，您可能需要重新安裝 SCST。或者，您可以解除安裝 ONTAP Mediator，然後重新安裝並重新設定 ONTAP 關係。請參閱 link:https://scst.sourceforge.net/["SCST：適用於 Linux 的通用 SCSI 目標子系統"^] 以深入瞭解 SCST。


NOTE: 您應該將伺服器作業系統核心的任何更新與 ONTAP 中的維護視窗協調起來。



== 支援 HTTPS 和 iSCSI

從 ONTAP Mediator 1.12 版本開始，您可以設定使用 HTTPS 或 iSCSI 監控 MetroCluster IP 組態的 ONTAP Mediator。您可以選擇安裝同時支援 iSCSI 和 HTTPS 的 ONTAP Mediator，或僅安裝支援 HTTPS 的 ONTAP Mediator。如果安裝的 ONTAP Mediator 僅支援 HTTPS，則不會安裝 SCST 軟體套件。如需詳細資訊，請參閱 link:index.html#https-iscsi-installation["ONTAP Mediator 的 HTTPS 和 iSCSI 安裝選項"]。
