---
permalink: mediator/upgrade-host-os-mediator-task.html 
sidebar: sidebar 
keywords: mediator, new, release, update, install, 
summary: 在安裝程序中、您將先升級主機作業系統、然後再升級 ONTAP Mediator 。 
---
= 升級主機作業系統和 ONTAP Mediator
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要將主機作業系統 for ONTAP Mediator 升級至更新版本、您必須先解除安裝 ONTAP Mediator 。

.關於這項工作
當您使用 leapp-upgrade 工具將主機作業系統 for ONTAP Mediator 升級至較新的主要版本（例如從 7.x 升級至 8.x ）時、 您必須解除安裝 ONTAP Mediator 、因為此工具會嘗試偵測安裝在系統儲存庫中的任何 RPM 的新版本。

由於 .rpm 檔案是 ONTAP Mediator 安裝程式的一部分、因此會包含在該搜尋中。不過、由於 .rpm 檔案已在安裝程式中解壓縮、且未從已註冊的儲存庫下載、因此無法找到升級。在這種情況下、 leapp-upgrade 工具會解除安裝套件。

為了保留用於分類支援案例的日誌文件，您應該在升級作業系統之前備份這些文件，並在重新安裝 ONTAP Mediator 軟體包後恢復它們。安裝 ONTAPMediator 後，需要重新連線連接到該軟體包的 ONTAP 叢集。


NOTE: 應依序執行下列步驟。重新安裝 ONTAP Mediator 後，應立即停止 ontap_mediator，替換日誌文件，然後重新啟動它。這樣做是為了確保日誌不會遺失。

.步驟
. 備份記錄檔。
+
....
[rootmediator-host ~]# tar -czf ontap_mediator_file_backup.tgz -C /opt/netapp/lib/ontap_mediator ./log ./ontap_mediator/server_config/ontap_mediator.user_config.yaml
[rootmediator-host ~]# tar -tf ontap_mediator_file_backup.tgz
./log/
./log/ontap_mediator.log
./log/scstadmin.log
./log/ontap_mediator_stdout.log
./log/ontap_mediator_requests.log
./log/install_20230419134611.log
./log/scst.log
./log/ontap_mediator_syslog.log
./ontap_mediator/server_config/ontap_mediator.user_config.yaml
[rootmediator-host ~]#
....
. 使用 leapp-upgrade 工具執行升級。
+
....
[rootmediator-host ~]# leapp preupgrade --target 8.4
  ..<snip upgrade checks>..
  ..<fix issues found>..
[rootmediator-host ~]# leapp upgrade --target 8.4
  ..<snip upgrade>..
[rootmediator-host ~]# cat /etc/os-release | head -2
NAME="Red Hat Enterprise Linux"
VERSION="8.4 (Ootpa)"
[rootmediator-host ~]#
....
. 重新安裝 ONTAP Mediator 。
+

NOTE: 重新安裝 ONTAP Mediator 之後、請立即執行其餘步驟、以避免記錄檔遺失。

+
....
[rootmediator-host ~]# ontap-mediator-1.10/ontap-mediator-1.10

ONTAP Mediator: Self Extracting Installer

  ..<snip installation>..
[rootmediator-host ~]#
....
. 停止 ontap_mediator。
+
....
[rootmediator-host ~]# systemctl stop ontap_mediator
[rootmediator-host ~]#
....
. 取代記錄檔。
+
....
[rootmediator-host ~]# tar -xf ontap_mediator_log_backup.tgz -C /opt/netapp/lib/ontap_mediator
[rootmediator-host ~]#
....
. 啟動 ontap_mediator。
+
....
[rootmediator-host ~]# systemctl start ontap_mediator
[rootmediator-host ~]#
....
. 將所有 ONTAP 叢集重新連線至升級的 ONTAP Mediator
+
.MetroCluster over IP 程序
[%collapsible]
====
....
siteA::> metrocluster configuration-settings mediator show
Mediator IP     Port    Node                    Configuration Connection
                                                Status        Status
--------------- ------- ----------------------- ------------- -----------
172.31.40.122
                31784   siteA-node2             true          false
                        siteA-node1             true          false
                        siteB-node2             true          false
                        siteB-node2             true          false
siteA::> metrocluster configuration-settings mediator remove
Removing the mediator and disabling Automatic Unplanned Switchover. It may take a few minutes to complete.
Please enter the username for the mediator: mediatoradmin
Please enter the password for the mediator:
Confirm the mediator password:
Automatic Unplanned Switchover is disabled for all nodes...
Removing mediator mailboxes...
Successfully removed the mediator.

siteA::> metrocluster configuration-settings mediator add -mediator-address 172.31.40.122
Adding the mediator and enabling Automatic Unplanned Switchover. It may take a few minutes to complete.
Please enter the username for the mediator: mediatoradmin
Please enter the password for the mediator:
Confirm the mediator password:
Successfully added the mediator.

siteA::> metrocluster configuration-settings mediator show
Mediator IP     Port    Node                    Configuration Connection
                                                Status        Status
--------------- ------- ----------------------- ------------- -----------
172.31.40.122
                31784   siteA-node2             true          true
                        siteA-node1             true          true
                        siteB-node2             true          true
                        siteB-node2             true          true
siteA::>
....
====
+
.SnapMirror 主動同步程序
[%collapsible]
====
對於 SnapMirror 主動式同步、如果您在 /opt/NetApp 目錄外安裝 TLS 憑證、則不需要重新安裝。如果您使用的是預設產生的自我簽署憑證、或是將您的自訂憑證放入 /opt/NetApp 目錄、則您應該備份並還原它。

....
peer1::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
172.31.49.237    peer2            unreachable       true

peer1::> snapmirror mediator remove -mediator-address 172.31.49.237 -peer-cluster peer2

Info: [Job 39] 'mediator remove' job queued

peer1::> job show -id 39
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
39     mediator remove      peer1      peer1-node1    Success
     Description: Removing entry in mediator

peer1::> security certificate show -common-name ONTAPMediatorCA
Vserver    Serial Number   Certificate Name                       Type
---------- --------------- -------------------------------------- ------------
peer1
        4A790360081F41145E14C5D7CE721DC6C210007F
                        ONTAPMediatorCA                        server-ca
    Certificate Authority: ONTAP Mediator CA
        Expiration Date: Mon Apr 17 10:27:54 2073

peer1::> security certificate delete -common-name ONTAPMediatorCA *
1 entry was deleted.

 peer1::> security certificate install -type server-ca -vserver peer1

Please enter Certificate: Press <Enter> when done
  ..<snip ONTAP Mediator CA public key>..

You should keep a copy of the CA-signed digital certificate for future reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: 44786524464C5113D5EC966779D3002135EA4254

The certificate's generated name for reference: ONTAPMediatorCA

peer2::> security certificate delete -common-name ONTAPMediatorCA *
1 entry was deleted.

peer2::> security certificate install -type server-ca -vserver peer2

 Please enter Certificate: Press <Enter> when done
..<snip ONTAP Mediator CA public key>..


You should keep a copy of the CA-signed digital certificate for future reference.

The installed certificate's CA and serial number for reference:
CA: ONTAP Mediator CA
serial: 44786524464C5113D5EC966779D3002135EA4254

The certificate's generated name for reference: ONTAPMediatorCA

peer1::> snapmirror mediator add -mediator-address 172.31.49.237 -peer-cluster peer2 -username mediatoradmin

Notice: Enter the mediator password.

Enter the password:
Enter the password again:

Info: [Job: 43] 'mediator add' job queued

peer1::> job show -id 43
                            Owning
Job ID Name                 Vserver    Node           State
------ -------------------- ---------- -------------- ----------
43     mediator add         peer1      peer1-node2    Success
    Description: Creating a mediator entry

peer1::> snapmirror mediator show
Mediator Address Peer Cluster     Connection Status Quorum Status
---------------- ---------------- ----------------- -------------
172.31.49.237    peer2            connected         true

peer1::>

....
====


.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-delete.html["刪除安全性憑證"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-install.html["安全性憑證安裝"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-certificate-show.html["安全證書展示"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-add.html["SnapMirror 中介添加"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-mediator-remove.html["SnapMirror 中介器刪除"^]

