---
sidebar: sidebar 
permalink: data-protection/cloud-backup-using-cbs-task.html 
keywords: cloud, data, backup, back up, storage, volume, lun, connector, secret key, access key, bluexp back and recovery service, Cloud Backup service, CBS, restore data, protect volumes, ipspace, storagegrid, storage grid, archive, archival, archiving, cost, calculator, glacier, deep archive 
summary: 從 ONTAP 9.19.1 版本開始，System Manager 不再支援使用 NetApp Backup and Recovery 服務將資料備份到雲端。您必須使用 NetApp Console 設定 NetApp Backup and Recovery 服務，並建立 SnapMirror 與雲端目的地的關係。 
---
= 使用NetApp備份和恢復備份數據
:hardbreaks:
:toclevels: 1
:allow-uri-read: 
:toclevels: 1
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9.19.1 版本開始，System Manager 不再支援使用 NetApp Backup and Recovery 服務將資料備份到雲端。您必須使用 NetApp Console 設定 NetApp Backup and Recovery 服務，並建立 SnapMirror 與雲端目的地的關係。

備份和復原支援FlexVol讀寫磁碟區和資料保護 (DP) 磁碟區。從ONTAP 9.12.1 開始，備份和復原支援FlexGroup捲和SnapLock磁碟區。

詳細了解link:https://docs.netapp.com/us-en/data-services-backup-recovery/index.html["NetApp備份與復原"^] 。

.開始之前
您應該執行以下程序，以在 NetApp Console 中建立帳戶。對於服務帳戶，您需要將角色建立為「Account Admin」。

. link:https://docs.netapp.com/us-en/console-setup-admin/task-logging-in.html["在NetApp控制台中建立帳戶"^] 。
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-connectors.html["在NetApp控制台中建立控制台代理"^]與以下雲端提供者之一合作：
+
** Microsoft Azure
** Amazon Web Services（AWS）
** Google Cloud Platform（GCP）
** StorageGRID （ ONTAP 9.10.1 ）
+

NOTE: 從ONTAP 9.10.1 開始，您可以選擇StorageGRID作為雲端備份供應商，但前提是NetApp Console 部署在本機。控制台代理必須安裝在本機，並可透過NetApp控制台軟體即服務 (SaaS) 應用程式使用。



. link:https://docs.netapp.com/us-en/data-services-backup-recovery/concept-backup-to-cloud.html["在NetApp控制台中訂閱NetApp備份與復原"^]（需要適當的許可證）。
. link:https://docs.netapp.com/us-en/console-setup-admin/concept-identity-and-access-management.html["使用NetApp控制台產生存取金鑰和金鑰"^] 。




== 使用 NetApp Console 和 NetApp Backup and Recovery 來管理 ONTAP 備份

從 ONTAP 9.19.1 版本開始，System Manager 不再支援 NetApp Backup and Recovery。如需使用 NetApp Backup and Recovery 搭配 NetApp Console 的詳細資訊，請參閱link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["使用 NetApp Backup and Recovery 管理您的 ONTAP 系統備份"^]。



== 從備份檔案還原資料

只有在使用NetApp控制台時，您才可以執行備份管理作業，例如還原資料、更新關係和刪除關係。請參閱link:https://docs.netapp.com/us-en/data-services-backup-recovery/prev-ontap-backup-manage.html["從備份檔案還原資料"^]了解更多。
