---
permalink: data-protection/convert-volume-svm-replication-task.html 
sidebar: sidebar 
keywords: convert, volume, replication, relationships, svm 
summary: 您可以將磁碟區之間的複寫關係、轉換成擁有磁碟區的儲存虛擬機器（SVM）之間的複寫關係、前提是來源（根磁碟區除外）上的每個磁碟區都要複寫、 而且來源（包括根磁碟區）上的每個磁碟區都與目的地上的磁碟區名稱相同。 
---
= 將Volume複寫關係轉換成SVM複寫關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將磁碟區之間的複寫關係、轉換成擁有磁碟區的儲存虛擬機器（SVM）之間的複寫關係、前提是來源（根磁碟區除外）上的每個磁碟區都要複寫、 而且來源（包括根磁碟區）上的每個磁碟區都與目的地上的磁碟區名稱相同。

.關於這項工作
使用 `volume rename` SnapMirror 關係閒置時的命令、可視需要重新命名目的地磁碟區。

.步驟
. 從目的地SVM或目的地叢集執行下列命令、重新同步來源與目的地磁碟區：
+
`snapmirror resync -source-path _SVM:volume_ -destination-path _SVM:volume_ -type DP|XDP -schedule _schedule_ -policy _policy_`

+
如需完整的命令語法、請參閱手冊頁。

+
[NOTE]
====
雖然重新同步不需要基準傳輸、但這可能很耗時。您可能想要在非尖峰時間執行重新同步。

====
+
以下範例重新同步來源 Volume 之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA
----
. 如所述、在來源和目的地SVM之間建立SVM複寫關係 link:replicate-entire-svm-config-task.html["複寫SVM組態"]。
+
您必須使用 `-identity-preserve true` 的選項 `snapmirror create` 建立複寫關係時的命令。

. 停止目的地SVM：
+
`vserver stop -vserver _SVM_`

+
如需完整的命令語法、請參閱手冊頁。

+
下列範例會停止目的地 SVM `svm_backup`：

+
[listing]
----
cluster_dst::> vserver stop svm_backup
----
. 從目的地SVM或目的地叢集執行下列命令、重新同步來源和目的地SVM：
+
`snapmirror resync -source-path _SVM_: -destination-path _SVM_: -type DP|XDP -schedule _schedule_ -policy _policy_`

+
如需完整的命令語法、請參閱手冊頁。

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

雖然重新同步不需要基準傳輸、但這可能很耗時。您可能想要在非尖峰時間執行重新同步。

====
+
以下範例重新同步來源 SVM 之間的關係 `svm1` 以及目的地 SVM `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1: -destination-path svm_backup:
----

