---
permalink: data-protection/convert-snapmirror-version-flexible-task.html 
sidebar: sidebar 
keywords: convert, exist, dp-type, relationship, xdp 
summary: 您可以輕鬆地將現有的DP類型關係轉換成XDP、以善用靈活版本的SnapMirror。 
---
= 將現有的DP類型關係轉換為XDP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您要升級ONTAP 至更新版本的版本、則必須先將DP類型的關係轉換成XDP、然後再升級。不支援DP類型的關係。ONTAP您可以輕鬆地將現有的DP類型關係轉換成XDP、以善用靈活版本的SnapMirror。

.關於這項工作
* SnapMirror不會自動將現有的DP類型關係轉換為XDP。若要轉換關係、您必須中斷並刪除現有的關係、建立新的XDP關係、然後重新同步關係。如需背景資訊、請參閱 link:version-flexible-snapmirror-default-concept.html["XDP取代DP做為SnapMirror預設值"]。
* 規劃轉換時、您應該注意、XDP SnapMirror關係的背景準備和資料倉儲階段可能需要很長時間。SnapMirror關係報告長時間處於「準備」狀態、並不罕見。


[NOTE]
====
將SnapMirror關係類型從DP轉換為XDP之後、與空間相關的設定（例如自動調整大小和空間保證）將不再複寫到目的地。

====
.步驟
. 從目的地叢集、確定SnapMirror關係為DP類型、鏡射狀態為Snapmirror、關係狀態為閒置、關係健全：
+
執行此命令之前、您必須以必要的值取代尖括號中的變數。

+
[source, cli]
----
snapmirror show -destination-path <SVM:volume>
----
+
下列範例顯示的輸出 `snapmirror show` 命令：

+
[listing]
----
cluster_dst::>snapmirror show -destination-path svm_backup:volA_dst

Source Path: svm1:volA
Destination Path: svm_backup:volA_dst
Relationship Type: DP
SnapMirror Schedule: -
Tries Limit: -
Throttle (KB/sec): unlimited
Mirror State: Snapmirrored
Relationship Status: Idle
Transfer Snapshot: -
Snapshot Progress: -
Total Progress: -
Snapshot Checkpoint: -
Newest Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Newest Snapshot Timestamp: 06/27 10:00:55
Exported Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Exported Snapshot Timestamp: 06/27 10:00:55
Healthy: true
----
+
[NOTE]
====
您可能會發現保留的複本很有幫助 `snapmirror show` 命令輸出可追蹤現有的關聯設定。

====
. 從來源和目的地磁碟區、確保兩個磁碟區都有一個通用的Snapshot複本：
+
執行此命令之前、您必須以必要的值取代尖括號中的變數。

+
[source, cli]
----
volume snapshot show -vserver <SVM> -volume <volume>
----
+
下列範例顯示 `volume snapshot show` 來源和目的地磁碟區的輸出：

+
[listing]
----
cluster_src:> volume snapshot show -vserver vsm1 -volume volA
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm1 volA
weekly.2014-06-09_0736 valid 76KB 0% 28%
weekly.2014-06-16_1305 valid 80KB 0% 29%
daily.2014-06-26_0842 valid 76KB 0% 28%
hourly.2014-06-26_1205 valid 72KB 0% 27%
hourly.2014-06-26_1305 valid 72KB 0% 27%
hourly.2014-06-26_1405 valid 76KB 0% 28%
hourly.2014-06-26_1505 valid 72KB 0% 27%
hourly.2014-06-26_1605 valid 72KB 0% 27%
daily.2014-06-27_0921 valid 60KB 0% 24%
hourly.2014-06-27_0921 valid 76KB 0% 28%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
valid 44KB 0% 19%
11 entries were displayed.


cluster_dest:> volume snapshot show -vserver svm_backup -volume volA_dst
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm_backup volA_dst
weekly.2014-06-09_0736 valid 76KB 0% 30%
weekly.2014-06-16_1305 valid 80KB 0% 31%
daily.2014-06-26_0842 valid 76KB 0% 30%
hourly.2014-06-26_1205 valid 72KB 0% 29%
hourly.2014-06-26_1305 valid 72KB 0% 29%
hourly.2014-06-26_1405 valid 76KB 0% 30%
hourly.2014-06-26_1505 valid 72KB 0% 29%
hourly.2014-06-26_1605 valid 72KB 0% 29%
daily.2014-06-27_0921 valid 60KB 0% 25%
hourly.2014-06-27_0921 valid 76KB 0% 30%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
----
. 若要確保在轉換期間不會執行排程的更新、請停止現有的DP類型關係：
+
執行此命令之前、您必須以必要的值取代尖括號中的變數。

+
[source, cli]
----
snapmirror quiesce -source-path <SVM:volume> -destination-path <SVM:volume>
----
+
如需完整的命令語法、請參閱 link:https://docs.netapp.com/us-en/ontap-cli-9141//snapmirror-quiesce.html["手冊頁"^]。

+
[NOTE]
====
您必須從目的地SVM或目的地叢集執行此命令。

====
+
以下範例會暫停來源磁碟區之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----
. 打破現有的DP類型關係：
+
執行此命令之前、您必須以必要的值取代尖括號中的變數。

+
[source, cli]
----
snapmirror break -destination-path <SVM:volume>
----
+
如需完整的命令語法、請參閱 link:https://docs.netapp.com/us-en/ontap-cli-9141//snapmirror-break.html["手冊頁"^]。

+
[NOTE]
====
您必須從目的地SVM或目的地叢集執行此命令。

====
+
以下範例打破來源磁碟區之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror break -destination-path svm_backup:volA_dst
----
. 如果在目的地磁碟區上啟用了自動刪除Snapshot複本、請停用它：
+
[source, cli]
----
volume snapshot autodelete modify -vserver _SVM_ -volume _volume_ -enabled false
----
+
以下範例停用目的地磁碟區上的 Snapshot 複本自動刪除 `volA_dst`：

+
[listing]
----
cluster_dst::> volume snapshot autodelete modify -vserver svm_backup -volume volA_dst -enabled false
----
. 刪除現有的DP類型關係：
+
執行此命令之前、您必須以必要的值取代尖括號中的變數。

+
[source, cli]
----
snapmirror delete -destination-path <SVM:volume>
----
+
如需完整的命令語法、請參閱 link:https://docs.netapp.com/us-en/ontap-cli-9141//snapmirror-delete.html["手冊頁"^]。

+
[NOTE]
====
您必須從目的地SVM或目的地叢集執行此命令。

====
+
以下範例刪除來源磁碟區之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror delete -destination-path svm_backup:volA_dst
----
. 您可以使用從保留的輸出 `snapmirror show` 建立新 XDP 類型關係的命令：
+
執行此命令之前、您必須以必要的值取代尖括號中的變數。

+
[source, cli]
----
snapmirror create -source-path <SVM:volume> -destination-path <SVM:volume>  -type XDP -schedule <schedule> -policy <policy>
----
+
新關係必須使用相同的來源和目的地Volume。如需完整的命令語法、請參閱手冊頁。

+
[NOTE]
====
您必須從目的地SVM或目的地叢集執行此命令。

====
+
以下範例在來源磁碟區之間建立 SnapMirror DR 關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup` 使用預設值 `MirrorAllSnapshots` 原則：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst
-type XDP -schedule my_daily -policy MirrorAllSnapshots
----
. 重新同步來源與目的地磁碟區：
+
執行此命令之前、您必須以必要的值取代尖括號中的變數。

+
[source, cli]
----
snapmirror resync -source-path <SVM:volume> -destination-path <SVM:volume>
----
+
若要改善重新同步時間、您可以使用 `-quick-resync` 選項、但您應該注意儲存效率節約可能會損失。如需完整的命令語法、請參閱手冊頁： link:https://docs.netapp.com/us-en/ontap-cli-9141/snapmirror-resync.html#parameters.html["SnapMirror重新同步命令"^]。

+
[NOTE]
====
您必須從目的地SVM或目的地叢集執行此命令。雖然重新同步不需要基準傳輸、但這可能很耗時。您可能想要在非尖峰時間執行重新同步。

====
+
以下範例重新同步來源 Volume 之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. 如果停用自動刪除Snapshot複本、請重新啟用：
+
執行此命令之前、您必須以必要的值取代尖括號中的變數。

+
[source, cli]
----
volume snapshot autodelete modify -vserver <SVM> -volume <volume> -enabled true
----


.完成後
. 使用 `snapmirror show` 用於驗證 SnapMirror 關係是否已建立的命令。
. SnapMirror XDP 目的地 Volume 開始更新 SnapMirror 原則定義的 Snapshot 複本後、請使用的輸出 `snapmirror list-destinations` 來源叢集的命令、以顯示新的 SnapMirror XDP 關係。

