---
permalink: data-protection/convert-type-snapmirror-task.html 
sidebar: sidebar 
keywords: convert, snapmirror, relationship, asynchronous, synchronous, baseline, convert 
summary: 從 ONTAP 9 開始、支援 SnapMirror 同步。您可以將 SnapMirror 非同步關係轉換為 SnapMirror 同步關係、反之亦然、而無需執行基準傳輸。 
---
= 轉換 ONTAP SnapMirror 關聯的類型
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9 開始、支援 SnapMirror 同步。您可以將 SnapMirror 非同步關係轉換為 SnapMirror 同步關係、反之亦然、而無需執行基準傳輸。

.關於這項工作
您無法透過變更 SnapMirror 原則，將 SnapMirror 非同步關係轉換為 SnapMirror 同步關係，反之亦然。

.步驟
* * 將 SnapMirror 非同步關係轉換為 SnapMirror 同步關係 *
+
.. 從目的地叢集刪除 SnapMirror 非同步關係：
+
`snapmirror delete -destination-path <SVM:volume>`

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. 在來源叢集中，釋放 SnapMirror 關係而不刪除一般快照：
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. 從目的地叢集建立 SnapMirror 同步關係：
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM>:<destination_volume> -policy sync-mirror`

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. 重新同步 SnapMirror 同步關係：
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----


* * 將 SnapMirror 同步關係轉換為 SnapMirror 非同步關係 *
+
.. 從目的地叢集、請將現有的 SnapMirror 同步關係：
+
`snapmirror quiesce -destination-path <destination_SVM>:<destination_volume>`

+
[listing]
----
cluster2::> snapmirror quiesce -destination-path vs1_dr:vol1
----
.. 從目的地叢集刪除 SnapMirror 非同步關係：
+
`snapmirror delete -destination-path <SVM:volume>`

+
[listing]
----
cluster2::>snapmirror delete -destination-path vs1_dr:vol1
----
.. 在來源叢集中，釋放 SnapMirror 關係而不刪除一般快照：
+
`snapmirror release -relationship-info-only true -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster1::>snapmirror release -relationship-info-only true -destination-path vs1_dr:vol1
----
.. 從目的地叢集建立 SnapMirror 非同步關係：
+
`snapmirror create -source-path _src_SVM:src_volume_ -destination-path <destination_SVM:destination_volume> -policy MirrorAllSnapshots`

+
[listing]
----
cluster2::>snapmirror create -source-path vs1:vol1 -destination-path vs1_dr:vol1 -policy sync
----
.. 重新同步 SnapMirror 同步關係：
+
`snapmirror resync -destination-path <destination_SVM:destination_volume>`

+
[listing]
----
cluster2::>snapmirror resync -destination-path vs1_dr:vol1
----




.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror建立"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["SnapMirror刪除"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["SnapMirror靜止"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["SnapMirror版本"^]

