---
permalink: data-protection/convert-snapmirror-version-flexible-task.html 
sidebar: sidebar 
keywords: convert, exist, dp-type, relationship, xdp 
summary: 您可以輕鬆地將現有的DP類型關係轉換成XDP、以善用靈活版本的SnapMirror。 
---
= 將現有的 ONTAP SnapMirror DP 類型關係轉換為 XDP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您要升級ONTAP 至更新版本的版本、則必須先將DP類型的關係轉換成XDP、然後再升級。不支援DP類型的關係。ONTAP您可以輕鬆地將現有的DP類型關係轉換成XDP、以善用靈活版本的SnapMirror。

在升級ONTAP 至版本更新至版本更新ONTAP 之前、您必須先將現有的DP類型關係轉換成XDP、才能升級至版本更新。

.關於這項工作
* SnapMirror不會自動將現有的DP類型關係轉換為XDP。若要轉換關係、您必須中斷並刪除現有的關係、建立新的XDP關係、然後重新同步關係。
* 規劃轉換時、您應該注意、XDP SnapMirror關係的背景準備和資料倉儲階段可能需要很長時間。SnapMirror關係報告長時間處於「準備」狀態、並不罕見。


[NOTE]
====
將SnapMirror關係類型從DP轉換為XDP之後、與空間相關的設定（例如自動調整大小和空間保證）將不再複寫到目的地。

====
.步驟
. 從目的地叢集、確定SnapMirror關係為DP類型、鏡射狀態為Snapmirror、關係狀態為閒置、關係健全：
+
[source, cli]
----
snapmirror show -destination-path <SVM:volume>
----
+
下列範例顯示的輸出 `snapmirror show` 命令：

+
[listing]
----
cluster_dst::>snapmirror show -destination-path svm_backup:volA_dst

Source Path: svm1:volA
Destination Path: svm_backup:volA_dst
Relationship Type: DP
SnapMirror Schedule: -
Tries Limit: -
Throttle (KB/sec): unlimited
Mirror State: Snapmirrored
Relationship Status: Idle
Transfer Snapshot: -
Snapshot Progress: -
Total Progress: -
Snapshot Checkpoint: -
Newest Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Newest Snapshot Timestamp: 06/27 10:00:55
Exported Snapshot: snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
Exported Snapshot Timestamp: 06/27 10:00:55
Healthy: true
----
+
[NOTE]
====
您可能會發現保留命令輸出複本有助於 `snapmirror show`追蹤現有的關聯性設定。如link:https://docs.netapp.com/us-en/ontap-cli//snapmirror-show.html["指令參考資料ONTAP"^]需詳細 `snapmirror show`資訊，請參閱。

====
. 從來源和目的地磁碟區，確保兩個磁碟區都有通用的快照：
+
[source, cli]
----
volume snapshot show -vserver <SVM> -volume <volume>
----
+
下列範例顯示 `volume snapshot show` 來源和目的地磁碟區的輸出：

+
[listing]
----
cluster_src:> volume snapshot show -vserver vsm1 -volume volA
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm1 volA
weekly.2014-06-09_0736 valid 76KB 0% 28%
weekly.2014-06-16_1305 valid 80KB 0% 29%
daily.2014-06-26_0842 valid 76KB 0% 28%
hourly.2014-06-26_1205 valid 72KB 0% 27%
hourly.2014-06-26_1305 valid 72KB 0% 27%
hourly.2014-06-26_1405 valid 76KB 0% 28%
hourly.2014-06-26_1505 valid 72KB 0% 27%
hourly.2014-06-26_1605 valid 72KB 0% 27%
daily.2014-06-27_0921 valid 60KB 0% 24%
hourly.2014-06-27_0921 valid 76KB 0% 28%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
valid 44KB 0% 19%
11 entries were displayed.


cluster_dest:> volume snapshot show -vserver svm_backup -volume volA_dst
---Blocks---
Vserver Volume Snapshot State Size Total% Used%
-------- ------- ------------------------------- -------- -------- ------ -----
svm_backup volA_dst
weekly.2014-06-09_0736 valid 76KB 0% 30%
weekly.2014-06-16_1305 valid 80KB 0% 31%
daily.2014-06-26_0842 valid 76KB 0% 30%
hourly.2014-06-26_1205 valid 72KB 0% 29%
hourly.2014-06-26_1305 valid 72KB 0% 29%
hourly.2014-06-26_1405 valid 76KB 0% 30%
hourly.2014-06-26_1505 valid 72KB 0% 29%
hourly.2014-06-26_1605 valid 72KB 0% 29%
daily.2014-06-27_0921 valid 60KB 0% 25%
hourly.2014-06-27_0921 valid 76KB 0% 30%
snapmirror.10af643c-32d1-11e3-954b-123478563412_2147484682.2014-06-27_100026
----
. 若要確保在轉換期間不會執行排程的更新、請停止現有的DP類型關係：
+
[source, cli]
----
snapmirror quiesce -source-path <SVM:volume> -destination-path <SVM:volume>
----
+
[NOTE]
====
您必須從目的地SVM或目的地叢集執行此命令。

====
+
以下範例會暫停來源磁碟區之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["指令參考資料ONTAP"^]需詳細 `snapmirror quiesce`資訊，請參閱。

. 打破現有的DP類型關係：
+
[source, cli]
----
snapmirror break -destination-path <SVM:volume>
----
+
[NOTE]
====
您必須從目的地SVM或目的地叢集執行此命令。

====
+
以下範例打破來源磁碟區之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror break -destination-path svm_backup:volA_dst
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["指令參考資料ONTAP"^]需詳細 `snapmirror break`資訊，請參閱。

. 如果在目的地磁碟區上啟用自動刪除快照功能，請停用它：
+
[source, cli]
----
volume snapshot autodelete modify -vserver _SVM_ -volume _volume_ -enabled false
----
+
以下範例停用目的地磁碟區上的快照自動刪除 `volA_dst`：

+
[listing]
----
cluster_dst::> volume snapshot autodelete modify -vserver svm_backup -volume volA_dst -enabled false
----
. 刪除現有的DP類型關係：
+
[source, cli]
----
snapmirror delete -destination-path <SVM:volume>
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["指令參考資料ONTAP"^]需詳細 `snapmirror-delete`資訊，請參閱。

+
[NOTE]
====
您必須從目的地SVM或目的地叢集執行此命令。

====
+
以下範例刪除來源磁碟區之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror delete -destination-path svm_backup:volA_dst
----
. 在來源上釋放原始伺服器 SVM 災難恢復關係：
+
[source, cli]
----
snapmirror release -destination-path <SVM:volume> -relationship-info-only true
----
+
以下範例發佈 SVM 災難恢復關係：

+
[listing]
----
cluster_src::> snapmirror release -destination-path svm_backup:volA_dst -relationship-info-only true
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["指令參考資料ONTAP"^]需詳細 `snapmirror release`資訊，請參閱。

. 您可以使用從保留的輸出 `snapmirror show` 建立新 XDP 類型關係的命令：
+
[source, cli]
----
snapmirror create -source-path <SVM:volume> -destination-path <SVM:volume>  -type XDP -schedule <schedule> -policy <policy>
----
+
新關係必須使用相同的來源和目的地Volume。如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。

+
[NOTE]
====
您必須從目的地SVM或目的地叢集執行此命令。

====
+
以下範例在來源磁碟區之間建立 SnapMirror 災難恢復關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup` 使用預設值 `MirrorAllSnapshots` 原則：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1:volA -destination-path svm_backup:volA_dst
-type XDP -schedule my_daily -policy MirrorAllSnapshots
----
. 重新同步來源與目的地磁碟區：
+
[source, cli]
----
snapmirror resync -source-path <SVM:volume> -destination-path <SVM:volume>
----
+
若要改善重新同步時間，您可以使用此 `-quick-resync`選項，但您應該注意儲存效率的節約可能會遺失。如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html#parameters.html["指令參考資料ONTAP"^]需詳細 `snapmirror resync`資訊，請參閱。

+
[NOTE]
====
您必須從目的地SVM或目的地叢集執行此命令。雖然重新同步不需要基準傳輸、但這可能很耗時。您可能想要在非尖峰時間執行重新同步。

====
+
以下範例重新同步來源 Volume 之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. 如果您停用自動刪除快照功能，請重新啟用：
+
[source, cli]
----
volume snapshot autodelete modify -vserver <SVM> -volume <volume> -enabled true
----


.完成後
. 使用 `snapmirror show` 用於驗證 SnapMirror 關係是否已建立的命令。
. 一旦 SnapMirror XDP 目的地磁碟區開始依照 SnapMirror 原則定義更新快照，請使用來源叢集的命令輸出 `snapmirror list-destinations`來顯示新的 SnapMirror XDP 關係。


.DP 型關係的其他資訊
從 ONTAP 9.3 開始， XDP 模式是預設模式，在命令列或新的或現有指令碼中， DP 模式的任何調用都會自動轉換為 XDP 模式。

現有的關係不受影響。如果某個關係已經是DP類型、則會繼續是DP類型。從 ONTAP 9.5 開始，如果未指定資料保護模式或將 XDP 模式指定為關係類型，則 MirrorAndVault 是預設原則。下表顯示預期行為。

[cols="3*"]
|===


| 如果您指定... | 類型為... | 預設原則（如果您未指定原則）是... 


 a| 
DP
 a| 
XDP
 a| 
MirrorAllSnapshots（SnapMirror DR）



 a| 
什麼都沒有
 a| 
XDP
 a| 
MirrorAndVault（統一化複寫）



 a| 
XDP
 a| 
XDP
 a| 
MirrorAndVault（統一化複寫）

|===
如表所示，在不同情況下指派給 XDP 的預設原則，可確保轉換維持與先前類型的功能等效。當然、您可以視需要使用不同的原則、包括統一化複寫的原則：

[cols="3*"]
|===


| 如果您指定... | 政策是... | 結果是... 


 a| 
DP
 a| 
MirrorAllSnapshots
 a| 
SnapMirror災難恢復



 a| 
XDPDefault
 a| 
SnapVault



 a| 
MirrorAndVault
 a| 
統一化複寫



 a| 
XDP
 a| 
MirrorAllSnapshots
 a| 
SnapMirror災難恢復



 a| 
XDPDefault
 a| 
SnapVault



 a| 
MirrorAndVault
 a| 
統一化複寫

|===
轉換的唯一例外情況如下：

* SVM資料保護關係在ONTAP 更新版本的更新版本中、仍預設為DP模式。
+
從ONTAP SVM 9.4開始、SVM資料保護關係預設為XDP模式。

* 根Volume負載共享資料保護關係仍預設為DP模式。
* 在更新版本的版本中、資料保護關係仍預設為DP模式。SnapLock ONTAP
+
從ONTAP S廳9.5開始、SnapLock 資料保護關係預設為XDP模式。

* 如果您設定下列全叢集選項、DP的明確調用仍會繼續預設為DP模式：
+
[listing]
----
options replication.create_data_protection_rels.enable on
----
+
如果您未明確叫用DP、則會忽略此選項。



.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror建立"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["SnapMirror刪除"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["SnapMirror靜止"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["SnapMirror版本"^]

