---
permalink: data-protection/convert-volume-svm-replication-task.html 
sidebar: sidebar 
keywords: convert, volume, replication, relationships, svm 
summary: 您可以將磁碟區之間的複寫關係、轉換成擁有磁碟區的儲存虛擬機器（SVM）之間的複寫關係、前提是來源（根磁碟區除外）上的每個磁碟區都要複寫、 而且來源（包括根磁碟區）上的每個磁碟區都與目的地上的磁碟區名稱相同。 
---
= 將 ONTAP SnapMirror Volume DR 關係轉換為 SVM DR 關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以將磁碟區之間的複寫關係、轉換成擁有磁碟區的儲存虛擬機器（SVM）之間的複寫關係、前提是來源（根磁碟區除外）上的每個磁碟區都要複寫、 而且來源（包括根磁碟區）上的每個磁碟區都與目的地上的磁碟區名稱相同。

.關於這項工作
如有必要，請在 SnapMirror 關係閒置時使用 `volume rename`命令重新命名目的地 Volume 。如link:https://docs.netapp.com/us-en/ontap-cli/volume-rename.html["指令參考資料ONTAP"^]需詳細 `volume rename`資訊，請參閱。

.步驟
. 從目的地SVM或目的地叢集執行下列命令、重新同步來源與目的地磁碟區：
+
`snapmirror resync -source-path <SVM:volume> -destination-path <SVM:volume> -type DP|XDP -policy <policy>`

+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["指令參考資料ONTAP"^]需詳細 `snapmirror resync`資訊，請參閱。

+
[NOTE]
====
雖然重新同步不需要基準傳輸、但這可能很耗時。您可能想要在非尖峰時間執行重新同步。

====
+
以下範例重新同步來源 Volume 之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA
----
. 如所述、在來源和目的地SVM之間建立SVM複寫關係 link:replicate-entire-svm-config-task.html["複寫SVM組態"]。
+
您必須使用 `-identity-preserve true` 的選項 `snapmirror create` 建立複寫關係時的命令。

+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["指令參考資料ONTAP"^]需詳細 `snapmirror create`資訊，請參閱。

. 停止目的地SVM：
+
`vserver stop -vserver _SVM_`

+
如link:https://docs.netapp.com/us-en/ontap-cli/vserver-stop.html["指令參考資料ONTAP"^]需詳細 `vserver stop`資訊，請參閱。

+
下列範例會停止目的地 SVM `svm_backup`：

+
[listing]
----
cluster_dst::> vserver stop svm_backup
----
. 從目的地SVM或目的地叢集執行下列命令、重新同步來源和目的地SVM：
+
`snapmirror resync -source-path <SVM>: -destination-path <SVM>: -type DP|XDP -policy <policy>`

+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["指令參考資料ONTAP"^]需詳細 `snapmirror resync`資訊，請參閱。

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

雖然重新同步不需要基準傳輸、但這可能很耗時。您可能想要在非尖峰時間執行重新同步。

====
+
以下範例重新同步來源 SVM 之間的關係 `svm1` 以及目的地 SVM `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1: -destination-path svm_backup:
----


.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror建立"^]

