---
permalink: data-protection/create-smb-server-task.html 
sidebar: sidebar 
keywords: cifs, create, server 
summary: 如果來源SVM有SMB組態、而您選擇將idente-preserve設為假、則必須為目的地SVM建立SMB伺服器。某些SMB組態需要SMB伺服器、例如SnapMirror關係初始化期間的共用。 
---
= 僅限SMB：建立SMB伺服器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果來源 SVM 有 SMB 組態、您選擇設定 `identity-preserve` 至 `false`，您必須為目的地 SVM 建立 SMB 伺服器。某些SMB組態需要SMB伺服器、例如SnapMirror關係初始化期間的共用。

.步驟
. 使用啟動目的地 SVM `vserver start` 命令。
+
[listing]
----
destination_cluster::> vserver start -vserver dvs1
[Job 30] Job succeeded: DONE
----
. 確認目的地 SVM 位於中 `running` 狀態和子類型為 `dp-destination` 使用 `vserver show` 命令。
+
[listing]
----
destination_cluster::> vserver show
                                   Admin      Operational Root
Vserver  Type    Subtype           State      State       Volume     Aggregate
-------- ------- ----------       ---------- ----------- ---------- ----------
dvs1     data    dp-destination    running    running       -         -
----
. 使用建立 LIF `network interface create` 命令。
+
[listing]
----
destination_cluster::>network interface create -vserver dvs1 -lif NAS1 -role data -data-protocol cifs -home-node destination_cluster-01 -home-port a0a-101  -address 192.0.2.128 -netmask 255.255.255.128
----
. 使用建立航線 `network route create` 命令。
+
[listing]
----
destination_cluster::>network route create -vserver dvs1 -destination 0.0.0.0/0
-gateway 192.0.2.1
----
+
link:../networking/index.html["網路管理"]

. 使用設定 DNS `vserver services dns create` 命令。
+
[listing]
----
destination_cluster::>vserver services dns create -domains mydomain.example.com -vserver
dvs1 -name-servers 192.0.2.128 -state enabled
----
. 使用新增慣用的網域控制站 `vserver cifs domain preferred-dc add` 命令。
+
[listing]
----
destination_cluster::>vserver cifs domain preferred-dc add -vserver dvs1 -preferred-dc
192.0.2.128 -domain mydomain.example.com
----
. 使用建立 SMB 伺服器 `vserver cifs create` 命令。
+
[listing]
----
destination_cluster::>vserver cifs create -vserver dvs1 -domain mydomain.example.com
-cifs-server CIFS1
----
. 使用停止目的地 SVM `vserver stop` 命令。
+
[listing]
----
destination_cluster::> vserver stop -vserver dvs1
[Job 46] Job succeeded: DONE
----

