---
permalink: data-protection/create-load-sharing-mirror-task.html 
sidebar: sidebar 
keywords: create, initialize, load-sharing, mirror, relationship 
summary: 您應該為叢集中的每個根磁碟區建立負載共用鏡像（LSM）。您可以在任何節點上建立LSM、但不包括根磁碟區、例如HA配對中的合作夥伴節點、或最好是在不同的HA配對中。對於雙節點叢集、您應該在具有根磁碟區的節點合作夥伴上建立LSM。 
---
= 建立及初始化負載共用鏡射關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該為每個SVM根磁碟區建立負載共用鏡像（LSM）、以在叢集中提供NAS資料。您可以在任何節點上建立LSM、但不包括根磁碟區、例如HA配對中的合作夥伴節點、或最好是在不同的HA配對中。

LSM 不適用於單一 HA 叢集、因此應針對多個 HA 配對叢集進行設定、在具有根磁碟區的節點和不同 HA 配對的另一個節點之間設定 LSM 。

.關於這項工作
如果您在同一個節點上建立LSM、但該節點無法使用、則會發生單一故障點、而且您沒有第二個複本、無法確保用戶端仍可存取資料。但是、當您在含有根磁碟區的節點以外的節點上建立LSM、或是在不同的HA配對上建立LSM時、資料仍可在中斷時存取。

例如、在四節點叢集中、三個節點上有根磁碟區：

* 對於HA 1節點1上的根磁碟區、請在HA 2節點1或HA 2節點2上建立LSM。
* 對於HA 1節點2上的根磁碟區、請在HA 2節點1或HA 2節點2上建立LSM。
* 對於HA 2節點1上的根磁碟區、請在HA 1節點1或HA 1節點2上建立LSM。


.步驟
. 建立LSM的目的地Volume：
+
執行此命令之前、您必須以必要的值取代尖括號中的變數。

+
[source, cli]
----
volume create -vserver <SVM> -volume <volume> -aggregate <aggregate> -type DP -size <size>
----
+
目的地Volume的大小應與根Volume相同或更大。

+
最佳做法是使用後綴（例如）來命名根卷和目標卷 `_root` 和 `_m1`。

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例為根磁碟區建立負載共用鏡射磁碟區 `svm1_root` 在中 `cluster_src`：

+
[listing]
----
cluster_src:> volume create -vserver svm1 -volume svm1_m1 -aggregate aggr_1 -size 1gb -state online -type DP
----
. link:create-replication-job-schedule-task.html["建立複製工作排程"]。
. 在SVM根磁碟區與LSM目的地磁碟區之間建立負載共用鏡射關係：
+
執行此命令之前、您必須以必要的值取代尖括號中的變數。

+
[source, cli]
----
snapmirror create -source-path <SVM:volume> -destination-path <SVM:volume> -type LS -schedule <schedule>
----
+
如需完整的命令語法、請參閱手冊頁。

+
以下範例在根磁碟區之間建立負載共用鏡像關係 `svm1_root` 以及負載共用鏡射磁碟區 `svm1_m1`：

+
[listing]
----
cluster_src::> snapmirror create -source-path svm1:svm1_root -destination-path svm1:svm1_m1 -type LS -schedule hourly
----
+
負載共用鏡像的類型屬性會從變更 `DP` 至 `LS`。

. 初始化負載共用鏡像：
+
執行此命令之前、您必須以必要的值取代尖括號中的變數。

+
[source, cli]
----
snapmirror initialize-ls-set -source-path <SVM:volume>
----
+
初始化可能會很耗時。您可能想要在非尖峰時間執行基準傳輸。

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例初始化根磁碟區的負載共用鏡像 `svm1_root`：

+
[listing]
----
cluster_src::> snapmirror initialize-ls-set -source-path svm1:svm1_root
----

