---
permalink: data-protection/create-load-sharing-mirror-task.html 
sidebar: sidebar 
keywords: create, initialize, load-sharing, mirror, relationship 
summary: 您應該為叢集中的每個根磁碟區建立負載共用鏡像（LSM）。您可以在任何節點上建立LSM、但不包括根磁碟區、例如HA配對中的合作夥伴節點、或最好是在不同的HA配對中。對於雙節點叢集、您應該在具有根磁碟區的節點合作夥伴上建立LSM。 
---
= 建立及初始化負載共用鏡射關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您應該為每個SVM根磁碟區建立負載共用鏡像（LSM）、以在叢集中提供NAS資料。您可以在任何節點上建立LSM、但不包括根磁碟區、例如HA配對中的合作夥伴節點、或最好是在不同的HA配對中。對於雙節點叢集、您應該在具有SVM根磁碟區的節點合作夥伴上建立LSM。

.關於這項工作
如果您在同一個節點上建立LSM、但該節點無法使用、則會發生單一故障點、而且您沒有第二個複本、無法確保用戶端仍可存取資料。但是、當您在含有根磁碟區的節點以外的節點上建立LSM、或是在不同的HA配對上建立LSM時、資料仍可在中斷時存取。

例如、在四節點叢集中、三個節點上有根磁碟區：

* 對於HA 1節點1上的根磁碟區、請在HA 2節點1或HA 2節點2上建立LSM。
* 對於HA 1節點2上的根磁碟區、請在HA 2節點1或HA 2節點2上建立LSM。
* 對於HA 2節點1上的根磁碟區、請在HA 1節點1或HA 1節點2上建立LSM。


.步驟
. 建立LSM的目的地Volume：
+
「Volume create -vserver _svm_-volume -aggregate _gregate _-type DP -size size」

+
目的地Volume的大小應與根Volume相同或更大。

+
最佳做法是使用後置碼命名根和目的地Volume、例如「_root」和「_M1」。

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例會在叢集資源中建立根磁碟區「svm1_root（shvm1_root））的負載共享鏡像磁碟區：

+
[listing]
----
cluster_src:> volume create -vserver svm1 -volume svm1_m1 -aggregate aggr_1 -size 1gb -state online -type DP
----
. 建立複寫工作排程、如所述 link:create-replication-job-schedule-task.html["建立複寫工作排程"]。
. 在SVM根磁碟區與LSM目的地磁碟區之間建立負載共用鏡射關係：
+
「napmirror create -source-path _svm:volume？」（napmirror create -source-path _svm:volume）|叢集：//Svm/volume（/volume）- destination-path _svm:volume（SVM：Volume）|叢集：//Svm/volume（SVM / Volume）-鍵入ls -schedule（排程）_

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例在根磁碟區「svm1_root」和負載共用鏡像磁碟區「svm1_M1」之間建立負載共用鏡射關係：

+
[listing]
----
cluster_src::> snapmirror create -source-path svm1:svm1_root -destination-path svm1:svm1_m1 -type LS -schedule hourly
----
+
負載共享鏡像的類型屬性會從「DP」變更為「LS」。

. 初始化負載共用鏡像：
+
「napmirror initialize-ls-set -source-path _svm:volume」（napmirror initialize-ls-set -source-path _Svm:volume）|叢集：//Svm/volume」

+
初始化可能會很耗時。您可能想要在非尖峰時間執行基準傳輸。

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例可初始化根磁碟區「svm1_root（））的負載共享鏡像：

+
[listing]
----
cluster_src::> snapmirror initialize-ls-set -source-path svm1:svm1_root
----

