---
permalink: data-protection/create-custom-replication-policy-concept.html 
sidebar: sidebar 
keywords: create, custom, replication, policy 
summary: 如果關聯的預設原則不適用、您可以建立自訂複寫原則。例如、您可能想要壓縮網路傳輸中的資料、或是修改SnapMirror傳輸Snapshot複本的嘗試次數。 
---
= 建立自訂複寫原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果關聯的預設原則不適用、您可以建立自訂複寫原則。例如、您可能想要壓縮網路傳輸中的資料、或是修改SnapMirror傳輸Snapshot複本的嘗試次數。

您可以在建立複寫關聯時使用預設或自訂原則。對於自訂歸檔（先前SnapVault 稱為「Eshot」）或統一化複寫原則、您必須定義一或多個_Rules _、以決定在初始化與更新期間傳輸哪些Snapshot複本。您也可能想要定義在目的地上建立本機Snapshot複本的排程。

複寫原則的_policy類型_決定其支援的關係類型。下表顯示可用的原則類型。

[cols="2*"]
|===


| 原則類型 | 關係類型 


 a| 
非同步鏡射
 a| 
SnapMirror災難恢復



 a| 
保存庫
 a| 
SnapVault



 a| 
鏡射保存庫
 a| 
統一化複寫



 a| 
嚴格同步鏡射
 a| 
SnapMirror同步於StrictSync模式（支援從ONTAP 功能9.5開始）



 a| 
同步鏡射
 a| 
SnapMirror同步處於同步模式（ONTAP 支援從功能9.5開始）

|===
[TIP]
====
建立自訂複寫原則時、最好先建立預設原則之後的原則模型。

====
.步驟
. 建立自訂複寫原則：
+
「napmirror原則create -vserver _svm_-policy _policy _-type async-mirror | vVault | mirror - vVault | nstr嚴格 同步鏡射| sync-mirror -comment _comment _-tes_-tries _transfer-priority low | normal-is-network-coming_enabled true|fals'」

+
如需完整的命令語法、請參閱手冊頁。

+
從功能介紹9.5開始ONTAP 、您可以使用「常見的快照排程」參數、指定建立SnapMirror同步關係通用Snapshot複本排程的排程。根據預設、SnapMirror同步關係的常見Snapshot複本排程為一小時。您可以為SnapMirror同步關係的Snapshot複本排程指定30分鐘到2小時的值。

+
以下範例為SnapMirror DR建立自訂複寫原則、以啟用資料傳輸的網路壓縮：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_compressed -type async-mirror -comment “DR with network compression enabled” -is-network-compression-enabled true
----
+
下列範例建立SnapVault 一套適用於整個流程的自訂複寫原則：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_snapvault -type vault
----
+
下列範例建立統一化複寫的自訂複寫原則：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_unified -type mirror-vault
----
+
以下範例為StrictSync模式中的SnapMirror同步關係建立自訂複寫原則：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy my_strictsync -type strict-sync-mirror -common-snapshot-schedule my_sync_schedule
----


對於「'Vault'」和「mirirmirror-Vault'」原則類型、您必須定義規則、以決定在初始化和更新期間傳輸哪些Snapshot複本。

使用「napmirror policy show」命令來驗證SnapMirror原則是否已建立。如需完整的命令語法、請參閱手冊頁。
