---
permalink: data-protection/create-snapshot-policy-task.html 
sidebar: sidebar 
keywords: create, snapshot, policy 
summary: Snapshot原則會指定何時建立Snapshot複本、保留多少複本、以及如何命名這些複本。例如、系統可能每天在上午12：10建立一個Snapshot複本、保留兩個最近的複本、並將其命名為「每日時間戳記」。 Snapshot原則最多可包含五個工作排程。 
---
= 建立Snapshot原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Snapshot原則會指定何時建立Snapshot複本、保留多少複本、以及如何命名這些複本。例如、系統可能會在每天上午 12 ： 10 建立一個 Snapshot 複本、保留兩個最新的複本、並將其命名為「 daily 」.`_timestamp_`.`" Snapshot 原則最多可包含五個工作排程。

.關於這項工作
根據預設ONTAP 、將時間戳記附加至工作排程名稱、即可形成Snapshot複本的名稱：

[listing]
----
daily.2017-05-14_0013/              hourly.2017-05-15_1106/
daily.2017-05-15_0012/              hourly.2017-05-15_1206/
hourly.2017-05-15_1006/             hourly.2017-05-15_1306/
----
您可以視需要以首碼取代工作排程名稱。

。 `snapmirror-label` 選項適用於 SnapMirror 複寫。如需詳細資訊、請參閱 link:define-rule-policy-task.html["定義原則規則"]。

.步驟
. 建立Snapshot原則：
+
`volume snapshot policy create -vserver _SVM_ -policy _policy_name_ -enabled true|false -schedule1 _schedule1_name_ -count1 _copies_to_retain_ -prefix1 _snapshot_prefix_ -snapmirror-label1 _snapshot_label_ ... -schedule5 _schedule5_name_ -count5 _copies_to_retain_-prefix5 _snapshot_prefix_ -snapmirror-label5 _snapshot_label_`

+
以下範例建立名為的 Snapshot 原則 `snap_policy_daily` 在上執行 `daily` 排程。原則最多有五個 Snapshot 複本、每個副本都有名稱 `daily`.`_timestamp_` 和 SnapMirror 標籤 `daily`：

+
[listing]
----
cluster1::> volume snapshot policy create -vserver vs0 -policy snap_policy_daily -schedule1 daily -count1 5 -snapmirror-label1 daily
----

