---
permalink: data-protection/delete-volume-replication-relationship-task.html 
sidebar: sidebar 
keywords: delete, volume, replication, relationship, replicate, synchronous, snapmirror, quiese, pause 
summary: 您可以使用SnapMirror刪除和SnapMirror版本命令來刪除磁碟區複寫關係。然後您可以手動刪除不需要的目的地Volume。 
---
= 刪除與 ONTAP 的磁碟區複寫關係
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `snapmirror delete` 和 `snapmirror release` 用於刪除 Volume 複寫關係的命令。然後您可以手動刪除不需要的目的地Volume。

.關於這項工作
此命令會 `snapmirror release`從來源中刪除任何 SnapMirror 建立的快照。您可以使用 `-relationship-info-only`選項來保留快照。

.步驟
. 靜止複寫關係：
+
`snapmirror quiesce -destination-path <SVM:volume>|<cluster://SVM/volume>`

+
[listing]
----
cluster_dst::> snapmirror quiesce -destination-path svm_backup:volA_dst
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["指令參考資料ONTAP"^]需詳細 `snapmirror quiesce`資訊，請參閱。

. （選用）如果您需要將目的地磁碟區設為讀寫磁碟區、請中斷複寫關係。如果您打算刪除目的地Volume、或是不需要讀取/寫入磁碟區、可以跳過此步驟：
+
`snapmirror break -source-path <SVM:volume>|<cluster://SVM/volume>, …​ -destination-path <SVM:volume>|<cluster://SVM/volume>, …​`

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["指令參考資料ONTAP"^]需詳細 `snapmirror break`資訊，請參閱。

. 刪除複寫關係：
+
`snapmirror delete -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
[NOTE]
====
您必須從目的地叢集或目的地SVM執行此命令。

====
+
以下範例刪除來源磁碟區之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["指令參考資料ONTAP"^]需詳細 `snapmirror delete`資訊，請參閱。

. 來自來源SVM的版本複寫關係資訊：
+
`snapmirror release -source-path <SVM:volume>|<cluster://SVM/volume>, ... -destination-path <SVM:volume>|<cluster://SVM/volume>, ...`

+
[NOTE]
====
您必須從來源叢集或來源SVM執行此命令。

====
+
下列範例會從來源 SVM 發佈指定複寫關係的資訊 `svm1`：

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1:volA -destination-path svm_backup:volA_dst
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-release.html["指令參考資料ONTAP"^]需詳細 `snapmirror release`資訊，請參閱。


