---
permalink: data-protection/example-configure-vault-vault-cascade-task.html 
sidebar: sidebar 
keywords: example, configure, vault-vault, cascade 
summary: 範例將具體說明如何一次設定一個步驟的複寫關係。您可以使用範例中設定的資料保險箱串聯部署來保留超過 251 個標示為「每週」的快照。 
---
= 範例：設定資料保險箱串聯
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
範例將具體說明如何一次設定一個步驟的複寫關係。您可以使用範例中設定的資料保險箱串聯部署來保留超過 251 個標示為的快照 `my-weekly`。

.開始之前
* 來源與目的地叢集和SVM必須進行對等關係。
* 您必須執行ONTAP 的是版本不含更新版本的版本。早期ONTAP 版本的不支援保存庫-保存庫串聯。


.關於這項工作
範例假設如下：

* 您已在來源叢集上使用 SnapMirror 標籤， `my-weekly`和 `my-monthly`設定快照 `my-daily`。
* 您已設定在第二和第三目的地叢集上命名的目的地磁碟區 `volA`。
* 您已設定在第二和第三目的地叢集上命名的複寫工作排程 `my_snapvault`。


範例顯示如何根據兩個自訂原則建立複寫關係：

* 此 `snapvault_secondary`原則會在次要目的地叢集上保留 7 個每日， 52 個每週和 180 個每月快照。
* 會 `snapvault_tertiary policy`在第三個目的地叢集上保留 250 個每週快照。


.步驟
. 在次要目的地叢集上，建立 `snapvault_secondary`原則：
+
`cluster_secondary::> snapmirror policy create -policy snapvault_secondary -type vault -comment "Policy on secondary for vault to vault cascade" -vserver svm_secondary`

. 在次要目的地叢集上，定義 `my-daily`原則的規則：
+
`cluster_secondary::> snapmirror policy add-rule -policy snapvault_secondary -snapmirror-label my-daily -keep 7 -vserver svm_secondary`

. 在次要目的地叢集上，定義 `my-weekly`原則的規則：
+
`cluster_secondary::> snapmirror policy add-rule -policy snapvault_secondary -snapmirror-label my-weekly -keep 52 -vserver svm_secondary`

. 在次要目的地叢集上，定義 `my-monthly`原則的規則：
+
`cluster_secondary::> snapmirror policy add-rule -policy snapvault_secondary -snapmirror-label my-monthly -keep 180 -vserver svm_secondary`

. 在次要目的地叢集上、驗證原則：
+
`cluster_secondary::> snapmirror policy show snapvault_secondary -instance`

+
[listing]
----
                     Vserver: svm_secondary
      SnapMirror Policy Name: snapvault_secondary
      SnapMirror Policy Type: vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: false
                     Comment: Policy on secondary for vault to vault cascade
       Total Number of Rules: 3
                  Total Keep: 239
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              my-daily                7  false       0 -        -
                              my-weekly              52  false       0 -        -
                              my-monthly            180  false       0 -        -
----
. 在次要目的地叢集上、建立與來源叢集的關係：
+
`cluster_secondary::> snapmirror create -source-path svm_primary:volA -destination-path svm_secondary:volA -type XDP -schedule my_snapvault -policy snapvault_secondary`

. 在次要目的地叢集上、初始化與來源叢集的關係：
+
`cluster_secondary::> snapmirror initialize -source-path svm_primary:volA -destination-path svm_secondary:volA`

. 在第三個目的地叢集上，建立 `snapvault_tertiary`原則：
+
`cluster_tertiary::> snapmirror policy create -policy snapvault_tertiary -type vault -comment "Policy on tertiary for vault to vault cascade" -vserver svm_tertiary`

. 在第三個目的地叢集上，定義 `my-weekly`原則的規則：
+
`cluster_tertiary::> snapmirror policy add-rule -policy snapvault_tertiary -snapmirror-label my-weekly -keep 250 -vserver svm_tertiary`

. 在第三目的地叢集上、確認原則：
+
`cluster_tertiary::> snapmirror policy show snapvault_tertiary -instance`

+
[listing]
----
                     Vserver: svm_tertiary
      SnapMirror Policy Name: snapvault_tertiary
      SnapMirror Policy Type: vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: false
                     Comment: Policy on tertiary for vault to vault cascade
       Total Number of Rules: 1
                  Total Keep: 250
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              my-weekly             250  false       0 -        -
----
. 在第三個目的地叢集上、建立與第二個叢集的關係：
+
`cluster_tertiary::> snapmirror create -source-path svm_secondary:volA -destination-path svm_tertiary:volA -type XDP -schedule my_snapvault -policy snapvault_tertiary`

. 在第三個目的地叢集上、初始化與第二個叢集的關係：
+
`cluster_tertiary::> snapmirror initialize -source-path svm_secondary:volA -destination-path svm_tertiary:volA`


