---
permalink: data-protection/exclude-lifs-svm-replication-task.html 
sidebar: sidebar 
keywords: lifs, network, settings, svm, replication 
summary: 如果來源和目的地SVM位於不同的子網路中、您可以使用SnapMirror原則create命令的-discration-configs網路選項、從SVM複寫中排除LIF和相關的網路設定。 
---
= 從 ONTAP SnapMirror SVM 複寫中排除生命與相關網路設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果來源和目的地 SVM 位於不同的子網路、您可以使用 `-discard-configs network` 的選項 `snapmirror policy create` 從 SVM 複寫中排除生命與相關網路設定的命令。

.開始之前
來源與目的地叢集和SVM必須進行對等關係。

如需詳細資訊、請參閱 link:../peering/create-cluster-relationship-93-later-task.html["建立叢集對等關係"] 和 link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["建立SVM叢集間對等關係"]。

.關於這項工作
。 `-identity-preserve` 的選項 `snapmirror create` 命令必須設為 `true` 當您建立 SVM 複寫關係時。

.步驟
. 建立目的地SVM：
+
`vserver create -vserver _SVM_ -subtype dp-destination`

+
SVM名稱在來源叢集和目的地叢集之間必須是唯一的。

+
下列範例建立名為的目的地 SVM `svm_backup`：

+
[listing]
----
cluster_dst:> vserver create -vserver svm_backup -subtype dp-destination
----
. 從目的地叢集、使用建立 SVM 對等關係 `vserver peer create` 命令。
+
如需詳細資訊、請參閱 link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["建立SVM叢集間對等關係"]。

+
如link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-create.html["指令參考資料ONTAP"^]需詳細 `vserver peer create`資訊，請參閱。

. 建立工作排程：
+
`job schedule cron create -name _job_name_ -month _month_ -dayofweek _day_of_week_ -day _day_of_month_ -hour _hour_ -minute _minute_`

+
適用於 `-month`、 `-dayofweek`和 `-hour`，您可以指定 `all` 可分別在每月、每週的某一天和每小時運行作業。

+
[NOTE]
====
SVM SnapMirror 關係中 FlexVol Volume 的最低支援排程（ RPO ）為 15 分鐘。SVM SnapMirror 關係中 FlexGroup Volume 的最低支援排程（ RPO ）為 30 分鐘。

====
+
以下範例建立名為的工作排程 `my_weekly` 週六上午 3 ： 00 開始：

+
[listing]
----
cluster_dst::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. 建立自訂複寫原則：
+
`snapmirror policy create -vserver _SVM_ -policy _policy_ -type async-mirror|vault|mirror-vault -comment _comment_ -tries transfer_tries -transfer-priority low|normal -is-network-compression-enabled true|false -discard-configs network`

+
以下範例為SnapMirror DR建立自訂複寫原則、排除LIF：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_exclude_LIFs -type async-mirror -discard-configs network
----
+
下列範例會建立自訂的複寫原則、以利統一化複寫、不含lifs：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy unified_exclude_LIFs -type mirror-vault -discard-configs network
----
+
[NOTE]
====
考慮在來源叢集上建立相同的自訂 SnapMirror 原則、以供未來容錯移轉和容錯回復案例使用。

====
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-create.html["指令參考資料ONTAP"^]需詳細 `snapmirror policy create`資訊，請參閱。

. 從目的地SVM或目的地叢集、執行下列命令以建立複寫關係：
+
`snapmirror create -source-path _SVM_: -destination-path _SVM_: -type DP|XDP -schedule _schedule_ -policy _policy_ -identity-preserve true|false -discard-configs true|false`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱下列範例。

====
+
以下範例建立SnapMirror DR關係、排除LIF：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_weekly -policy DR_exclude_LIFs -identity-preserve true
----
+
以下範例建立SnapMirror統一化複寫關係、排除lifs：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_weekly -policy unified_exclude_LIFs -identity-preserve true -discard-configs true
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["指令參考資料ONTAP"^]需詳細 `snapmirror create`資訊，請參閱。

. 停止目的地SVM：
+
`vserver stop`

+
`_SVM name_`

+
下列範例會停止名為 SVM_backup 的目的地 SVM ：

+
[listing]
----
cluster_dst::> vserver stop -vserver svm_backup
----
. 從目的地SVM或目的地叢集初始化複寫關係：
+
`snapmirror initialize -source-path _SVM_: -destination-path _SVM_:`

+
以下範例初始化來源之間的關係、 `svm1` 以及目的地、 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path svm1: -destination-path svm_backup:
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["指令參考資料ONTAP"^]需詳細 `snapmirror initialize`資訊，請參閱。



.完成後
您必須在目的地SVM上設定網路和傳輸協定、以便在發生災難時存取資料。

.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-create.html["SnapMirror建立"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-initialize.html["SnapMirror初始化"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-policy-create.html["SnapMirror 策略創建"^]

