---
permalink: data-protection/exclude-lifs-svm-replication-task.html 
sidebar: sidebar 
keywords: lifs, network, settings, svm, replication 
summary: 如果來源和目的地SVM位於不同的子網路中、您可以使用SnapMirror原則create命令的-discration-configs網路選項、從SVM複寫中排除LIF和相關的網路設定。 
---
= 從SVM複寫中排除LIF及相關的網路設定
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果來源與目的地SVM位於不同的子網路中、您可以使用「snapmirror policy create」命令的「丟棄組態」選項、將LIF與相關的網路設定排除在SVM複寫中。

.您需要的產品
來源與目的地叢集和SVM必須進行對等關係。

如需詳細資訊、請參閱 link:../peering/create-cluster-relationship-93-later-task.html["建立叢集對等關係"] 和 link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["建立SVM叢集間對等關係"]。

.關於這項工作
建立SVM複寫關係時、必須將「napmirror create」命令的「idente-preserve」選項設為「true」。

如需完整的命令語法、請參閱手冊頁。

.步驟
. 建立目的地SVM：
+
「vserver create -vserver _Svm_-subtype dP-ditation...」

+
SVM名稱在來源叢集和目的地叢集之間必須是唯一的。

+
以下範例建立名為「shvm_backup」的目的地SVM：

+
[listing]
----
cluster_dst:> vserver create -vserver svm_backup -subtype dp-destination
----
. 從目的地叢集、使用「vserver對等點create」命令建立SVM對等關係。
+
如需詳細資訊、請參閱 link:../peering/create-intercluster-svm-peer-relationship-93-later-task.html["建立SVM叢集間對等關係"]。

. 建立工作排程：
+
作業排程cron create -name _job_name_-month _month_-dayofWeek _Day_of_Week _-Day _Day_of_month_-hour _hour _-minute _minute_

+
如果是月、日、小時、則可以分別指定「ALL」來執行每月、每週、每週、每小時的工作。

+
[NOTE]
====
SVM SnapMirror 關係中 FlexVol Volume 的最低支援排程（ RPO ）為 15 分鐘。SVM SnapMirror 關係中 FlexGroup Volume 的最低支援排程（ RPO ）為 30 分鐘。

====
+
以下範例會建立一個名為「my_fours'的工作排程、於週六上午3：00執行：

+
[listing]
----
cluster_dst::> job schedule cron create -name my_weekly -dayofweek "Saturday" -hour 3 -minute 0
----
. 建立自訂複寫原則：
+
「napmirror原則create -vserver _svm_-policy _policy_-type asal同步 鏡射| vVault | mirror vVault -comment _comment _-tras傳輸 嘗試次數-transfite-priority low | normal-is-network-com過程 中啟用的true|fis-disast-configs network」

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例為SnapMirror DR建立自訂複寫原則、排除LIF：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy DR_exclude_LIFs -type async-mirror -discard-configs network
----
+
下列範例會建立自訂的複寫原則、以利統一化複寫、不含lifs：

+
[listing]
----
cluster_dst::> snapmirror policy create -vserver svm1 -policy unified_exclude_LIFs -type mirror-vault -discard-configs network
----
. 從目的地SVM或目的地叢集、執行下列命令以建立複寫關係：
+
「napmirror create -source-path _svm_：-dite-path _svm_：-type dp | xDP - schedule _schedule_-policy _-identity-preserve true|fals'」

+
[NOTE]
====
您必須在"-source-path"和"-destination-path"選項的SVM名稱後面輸入一個分號（：）。請參閱下列範例。

====
+
以下範例建立SnapMirror DR關係、排除LIF：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy DR_exclude_LIFs -identity-preserve true
----
+
以下範例建立SnapMirror統一化複寫關係、排除lifs：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup: -type XDP -schedule my_daily -policy unified_exclude_LIFs -identity-preserve true
----
. 停止目的地SVM：
+
"Vserver stop（Vserver停止）"

+
「SVM名稱_」

+
下列範例會停止名為DV1的目的地SVM：

+
[listing]
----
cluster_dst::> vserver stop -vserver dvs1
----
. 從目的地SVM或目的地叢集初始化複寫關係：
+
「napmirror initialize -source-path _svm_：-destination-path _svm_：」

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例可初始化來源「svm1」與目的地「shvm_backup」之間的關係：

+
[listing]
----
cluster_dst::> snapmirror initialize -source-path svm1: -destination-path svm_backup:
----


.完成後
您必須在目的地SVM上設定網路和傳輸協定、以便在發生災難時存取資料。
