---
permalink: data-protection/install-snapmirror-cloud-license-task.html 
sidebar: sidebar 
keywords: install, snapmirror, cloud, license, asynchronous, replicate, replication, snapshot 
summary: SnapMirror Cloud從ONTAP 功能不中斷的9.8開始、提供從ONTAP 功能不同步複製到物件儲存端點的Snapshot複本。SnapMirror Cloud關係只能使用預先認證的協力廠商備份應用程式進行設定。若要設定ONTAP 物件儲存複寫功能、ONTAP 必須在設定複寫到物件儲存區端點的來源叢集上、同時提供SnapMirror和SnapMirror Cloud授權。 
---
= 安裝SnapMirror Cloud授權
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror Cloud從ONTAP 功能不中斷的9.8開始、提供從ONTAP 功能不同步複寫到物件儲存端點的非同步快照複寫功能。SnapMirror Cloud關係只能使用預先認證的協力廠商備份應用程式進行設定。若要設定ONTAP 物件儲存複寫功能、ONTAP 必須在設定複寫到物件儲存區端點的來源叢集上、同時提供SnapMirror和SnapMirror Cloud授權。

.關於這項工作
SnapMirror Cloud授權是單一執行個體叢集範圍的授權、這表示不需要在叢集中的每個節點上安裝。這是一種以期限為基礎的授權、可同時強制執行條款與備份容量。除了此終端使用者授權之外、SnapMirror Cloud還需要經過授權與核准的備份應用程式、才能設定ONTAP 及叫用用於複寫的SnapMirror API。SnapMirror Cloud終端使用者授權和授權應用程式都是使用SnapMirror Cloud複寫的必要條件。

SnapMirror Cloud授權是透過購買混合式雲端產品組合來取得、您可以以1 TB為單位購買1年或3年。混合雲產品組合包含SnapMirror Cloud授權。每個授權都有唯一的序號。混合雲產品組合的購買量取決於容量、混合雲產品組合的購買容量會套用至SnapMirror Cloud授權。

SnapMirror Cloud授權可透過ONTAP 下列方法安裝在叢集上：使用效益指令行或系統管理程式。

.步驟
. 從 NetApp 支援網站下載兩份適用於 SnapMirror Cloud 的 NetApp 授權檔案（NLF）。
+
https://mysupport.netapp.com/site/global/dashboard["NetApp支援"]

. 使用System Manager將SnapMirror Cloud NLF檔案上傳至叢集：
+
.. 按一下「*組態*>*授權*」。
.. 在*叢集設定*窗格中、按一下*授權*。
.. 在「*套件*」視窗中、按一下「*新增*」。
.. 在「*新增授權套件*」對話方塊中、按一下「*選擇檔案*」以選取您下載的NLF、然後按一下「*新增*」將檔案上傳至叢集。




.相關資訊
http://mysupport.netapp.com/licenses["NetApp軟體授權搜尋"]
