---
permalink: data-protection/make-destination-volume-writeable-task.html 
sidebar: sidebar 
keywords: destination, volume, writeable, write, serve data, snapmirror, quiesce, pause, abort, transfers 
summary: 您必須先將目的地Volume設定為可寫入、才能將資料從磁碟區提供給用戶端。您可以使用SnapMirror quiesce命令來停止排程的目的地傳輸、使用SnapMirror abort-command來停止進行中的傳輸、以及使用SnapMirror中斷命令來使目的地可寫入。 
---
= 使目的地Volume可寫入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須先將目的地Volume設定為可寫入、才能將資料從磁碟區提供給用戶端。您可以使用 `snapmirror quiesce` 停止排程傳輸至目的地的命令 `snapmirror abort` 命令以停止進行中的傳輸、以及 `snapmirror break` 可讓目的地寫入的命令。

.關於這項工作
您必須從目的地SVM或目的地叢集執行此工作。

.步驟
. 停止排程的目的地傳輸：
+
`snapmirror quiesce -source-path _SVM:volume|cluster://SVM/volume_, ... -destination-path _SVM:volume|cluster://SVM/volume_, ...`

+
如需完整的命令語法、請參閱手冊頁。

+
下列範例會停止來源磁碟區之間的排程傳輸 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. 停止持續傳輸至目的地：
+
`snapmirror abort -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
如需完整的命令語法、請參閱手冊頁。

+
[NOTE]
====
SnapMirror同步關係不需要執行此步驟（ONTAP 從支援的版本號為9.5開始）。

====
+
下列範例會停止來源磁碟區之間的持續傳輸 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. 打破SnapMirror DR關係：
+
`snapmirror break -source-path _SVM:volume_|_cluster://SVM/volume_, ... -destination-path _SVM:volume_|_cluster://SVM/volume_, ...`

+
如需完整的命令語法、請參閱手冊頁。

+
以下範例打破來源磁碟區之間的關係 `volA` 開啟 `svm1` 以及目的地Volume `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1:volA -destination-path svm_backup:volA_dst
----




== 其他方法可在ONTAP 不一樣的情況下執行

[cols="2"]
|===
| 若要執行這些工作... | 請參閱此內容... 


| 重新設計的System Manager（ONTAP 提供更新版本的更新版本） | link:https://docs.netapp.com/us-en/ontap/task_dp_serve_data_from_destination.html["從SnapMirror目的地提供資料"^] 


| System Manager Classic（ONTAP 適用於更新版本的更新版本） | link:https://docs.netapp.com/us-en/ontap-sm-classic/volume-disaster-recovery/index.html["Volume災難恢復總覽"^] 
|===