---
permalink: data-protection/make-svm-destination-volumes-writeable-task.html 
sidebar: sidebar 
keywords: make, svm, destination, volume, writable 
summary: 您必須先將SVM目的地磁碟區設為可寫入、才能將資料提供給用戶端。此程序與磁碟區複寫程序大致相同、但有一項例外。如果您在建立SVM複寫關係時設定-identity保留為true、則必須先停止來源SVM、再啟動目的地SVM。 
---
= 使SVM目的地磁碟區可寫入
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您必須先將SVM目的地磁碟區設為可寫入、才能將資料提供給用戶端。此程序與磁碟區複寫程序大致相同、但有一項例外。如果您已設定 `-identity-preserve true` 建立 SVM 複寫關係時、必須先停止來源 SVM 、然後再啟動目的地 SVM 。

.關於這項工作
如需完整的命令語法、請參閱手冊頁。

[NOTE]
====
在災難恢復案例中、您無法從來源SVM執行SnapMirror更新至災難恢復目的地SVM、因為您的來源SVM及其資料將無法存取、而且自上次重新同步後的更新可能損毀或毀損。

====
.步驟
. 從目的地SVM或目的地叢集停止排程傳輸至目的地：
+
`snapmirror quiesce -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
下列範例會停止來源 SVM 之間的排程傳輸 `svm1` 以及目的地 SVM `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror quiesce -source-path svm1: -destination-path svm_backup:
----
. 從目的地SVM或目的地叢集停止持續傳輸至目的地：
+
`snapmirror abort -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
下列範例會停止來源 SVM 之間的持續傳輸 `svm1` 以及目的地 SVM `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror abort -source-path svm1: -destination-path svm_backup:
----
. 從目的地SVM或目的地叢集、中斷複寫關係：
+
`snapmirror break -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
以下範例打破來源 SVM 之間的關係 `svm1` 以及目的地 SVM `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror break -source-path svm1: -destination-path svm_backup:
----
. 如果您已設定 `-identity-preserve true` 建立 SVM 複寫關係時、請停止來源 SVM ：
+
`vserver stop -vserver _SVM_`

+
下列範例會停止來源 SVM `svm1`：

+
[listing]
----
cluster_src::> vserver stop svm1
----
. 啟動目的地SVM：
+
`vserver start -vserver _SVM_`

+
下列範例會啟動目的地 SVM `svm_backup`：

+
[listing]
----
cluster_dst::> vserver start svm_backup
----


.完成後
如所述、設定SVM目的地磁碟區以進行資料存取 link:configure-destination-volume-data-access-concept.html["設定目的地Volume以進行資料存取"]。
