---
permalink: data-protection/manage-local-snapshot-copies-concept.html 
sidebar: sidebar 
keywords: manage, local, snapshot, copy, storage, performance overhead, copies, image, restore, flexvol, flexgroup 
summary: 快照是磁碟區的唯讀時間點映像。映像會佔用最少的儲存空間，而且效能成本也可忽略不計，因為它只會記錄自上次快照以來檔案的變更。 
---
= 瞭解如何管理本機 ONTAP 快照
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
_snapshot 是磁碟區的唯讀時間點映像。映像會佔用最少的儲存空間，而且效能成本也可忽略不計，因為它只會記錄自上次快照以來檔案的變更。

您可以使用快照來還原磁碟區的全部內容，或是恢復個別檔案或 LUN 。快照會儲存在磁碟區的目錄中。 `.snapshot`

在ONTAP 9.4 及更高版本中， FlexVol volume最多可包含 1023 個快照。在ONTAP 9.3 及更早版本中，一個磁碟區最多可包含 255 個快照。

[NOTE]
====
從 ONTAP 9.8 開始， FlexGroup 磁碟區可以包含 1023 個快照。如需更多資訊、請參閱 link:../flexgroup/protect-snapshot-copies-task.html["使用快照保護 FlexGroup 磁碟區"]。

====
ONTAP 快照有幾種常見類型：

* `sched_created`：根據預先定義的排程（例如，每小時、每天、每週或每月），由 ONTAP Snapshot 原則自動產生的 Snapshot。
* `sm_created`：由於 SnapMirror 複製傳輸（更新或初始化操作）而自動建立的快照。
* `application_created`：由主機級或資料庫級整合軟體（例如 SnapCenter 或 SnapDrive）產生的快照。
* `user_created`：管理員使用 ONTAP CLI 或 System Manager 手動觸發的快照。
* `sv_created`：在叢集作業期間自動建立的 Snapshot，例如 Storage Virtual Machine（SVM）DR 或特定保護工作流程。
* `luns_created`：建立快照以備份或擷取 LUN 或 NVMe 命名空間複本的狀態。

