---
permalink: data-protection/reactivate-original-source-svm-flexgroup-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, svm, flexgroup 
summary: 當您不再需要從目的地提供資料時、可以重新建立來源SVM與目的地SVM之間的原始資料保護關係。若要在使用FlexGroup 完SVM時重新啟動原始來源SVM、您需要執行一些其他步驟、包括刪除原始SVM DR關係、並在反轉關係之前釋出原始關係。您也需要釋出反轉的關係、並在停止排程傳輸之前重新建立原始關係。 
---
= 重新啟動 FlexGroup Volume 的原始 ONTAP SnapMirror 來源 SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您不再需要從目的地提供資料時、可以重新建立來源SVM與目的地SVM之間的原始資料保護關係。若要在使用FlexGroup 完SVM時重新啟動原始來源SVM、您需要執行一些其他步驟、包括刪除原始SVM DR關係、並在反轉關係之前釋出原始關係。您也需要釋出反轉的關係、並在停止排程傳輸之前重新建立原始關係。

.步驟
. 從原始目的地SVM或原始目的地叢集刪除原始SVM DR關係：
+
`snapmirror delete -source-path SVM: -destination-path SVM:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
以下範例刪除原始來源 SVM 、 svm1 和原始目的地 SVM 之間的原始關係、 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror delete -source-path svm1: -destination-path svm_backup:
----
. 從原始來源 SVM 或原始來源叢集，釋放原始關係，同時保持快照不變：
+
`snapmirror release -source-path SVM: -destination-path SVM: -relationship-info-only true`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
以下範例發佈原始來源 SVM 、 svm1 和原始目的地 SVM 之間的原始關係、 `svm_backup`。

+
[listing]
----
cluster_src::> snapmirror release -source-path svm1: -destination-path svm_backup: -relationship-info-only true
----
. 從原始來源SVM或原始來源叢集、使用與原始SVM DR關係相同的組態、原則及身分保留設定、建立反向SVM DR關係：
+
`snapmirror create -source-path SVM: -destination-path SVM:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
以下範例在您用來提供資料的 SVM 之間建立關係、 `svm_backup`和原始來源 SVM 、 `svm1`：

+
[listing]
----
cluster_src::> snapmirror create -source-path svm_backup: -destination-path svm1:
----
. 從原始來源SVM或原始來源叢集、執行下列命令以反轉資料保護關係：
+
`snapmirror resync -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
雖然重新同步不需要基準傳輸、但這可能很耗時。您可能想要在非尖峰時間執行重新同步。

+
[NOTE]
====
如果來源和目的地上不存在一般快照，則命令會失敗。用於 `snapmirror initialize`重新初始化關係。

====
+
以下範例反轉原始來源 SVM 之間的關係、 `svm1`以及您要從中提供資料的 SVM 、 `svm_backup`：

+
[listing]
----
cluster_src::> snapmirror resync -source-path svm_backup: -destination-path svm1:
----
. 當您準備重新建立對原始來源SVM的資料存取時、請停止原始目的地SVM、以中斷目前連線至原始目的地SVM的所有用戶端。
+
`vserver stop -vserver _SVM_`

+
下列範例會停止目前正在處理資料的原始目的地SVM：

+
[listing]
----
cluster_dst::> vserver stop svm_backup
----
. 使用驗證原始目的地 SVM 是否處於停止狀態 `vserver show` 命令。
+
[listing]
----
cluster_dst::> vserver show
                                  Admin      Operational Root
Vserver        Type    Subtype    State      State       Volume     Aggregate
--------       ------- ---------- ---------- ----------- ---------- ----------
svm_backup     data    default    stopped    stopped     rv         aggr1
----
. 從原始來源SVM或原始來源叢集、執行下列命令以執行反向關係的最終更新、將所有變更從原始目的地SVM傳輸至原始來源SVM：
+
`snapmirror update -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
以下範例更新了您用來提供資料的原始目的地 SVM 之間的關係,`svm_backup`和原始來源 SVM 、 `svm1`：

+
[listing]
----
cluster_src::> snapmirror update -source-path svm_backup: -destination-path svm1:
----
. 從原始來源SVM或原始來源叢集、執行下列命令停止針對反向關係所排程的傳輸：
+
`snapmirror quiesce -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
下列範例會停止您要從哪個 SVM 傳送資料、 `svm_backup`和原始 SVM 、 `svm1`：

+
[listing]
----
cluster_src::> snapmirror quiesce -source-path svm_backup: -destination-path svm1:
----
. 當完成最後的更新、且關係指出關係狀態為「靜止」時、請從原始來源SVM或原始來源叢集執行下列命令、以中斷反向關係：
+
`snapmirror break -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
以下範例打破了您用來提供資料的原始目的地 SVM 之間的關係、 `svm_backup`和原始來源 SVM 、 `svm1`：

+
[listing]
----
cluster_src::> snapmirror break -source-path svm_backup: -destination-path svm1:
----
. 如果原始來源SVM先前已停止、請從原始來源叢集啟動原始來源SVM：
+
`vserver start -vserver _SVM_`

+
下列範例會啟動原始來源SVM：

+
[listing]
----
cluster_src::> vserver start svm1
----
. 從原始來源SVM或原始來源叢集刪除反轉的SVM DR關係：
+
`snapmirror delete -source-path SVM: -destination-path SVM:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
以下範例刪除原始目的地 SVM 、 SVM_backup 與原始來源 SVM 之間的反向關係、 `svm1`：

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup: -destination-path svm1:
----
. 從原始目的地 SVM 或原始目的地叢集，釋放相反的關係，同時保持快照不變：
+
`snapmirror release -source-path SVM: -destination-path SVM: -relationship-info-only true`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
下列範例會釋出原始目的地SVM、SVM_Backup與原始來源SVM、svm1之間的反向關係：

+
[listing]
----
cluster_dst::> snapmirror release -source-path svm_backup: -destination-path svm1: -relationship-info-only true
----
. 從原始目的地SVM或原始目的地叢集、重新建立原始關係。使用與原始SVM DR關係相同的組態、原則和身分保留設定：
+
`snapmirror create -source-path SVM: -destination-path SVM:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
以下範例在原始來源 SVM 之間建立關係、 `svm1`和原始目的地 SVM 、 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror create -source-path svm1: -destination-path svm_backup:
----
. 從原始目的地SVM或原始目的地叢集重新建立原始資料保護關係：
+
`snapmirror resync -source-path _SVM_: -destination-path _SVM_:`

+
[NOTE]
====
您必須在中的 SVM 名稱後面輸入一個冒號（：） `-source-path` 和 `-destination-path` 選項：請參閱以下範例。

====
+
以下範例重新建立原始來源 SVM 之間的關係、 `svm1`和原始目的地 SVM 、 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1: -destination-path svm_backup:
----

