---
permalink: data-protection/reactivate-original-source-volume-task.html 
sidebar: sidebar 
keywords: reactivate, original, source, volume 
summary: 當您不再需要從目的地提供資料時、可以重新建立來源與目的地磁碟區之間的原始資料保護關係。 
---
= 使用 ONTAP 重新啟動原始來源 Volume
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您不再需要從目的地提供資料時、可以重新建立來源與目的地磁碟區之間的原始資料保護關係。

.關於這項工作
* 以下程序假設原始來源Volume中的基準線完整無缺。如果基準不完整、您必須先建立並初始化您要從中處理資料的磁碟區與原始來源磁碟區之間的關係、然後再執行程序。
* XDP SnapMirror關係的背景準備和資料倉儲階段可能需要很長時間。SnapMirror關係報告長時間處於「準備」狀態、並不罕見。


.步驟
. 反轉原始資料保護關係：
+
`snapmirror resync -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["指令參考資料ONTAP"^]需詳細 `snapmirror resync`資訊，請參閱。

+
[NOTE]
====
您必須從原始來源SVM或原始來源叢集執行此命令。雖然重新同步不需要基準傳輸、但這可能很耗時。您可能想要在非尖峰時間執行重新同步。如果來源和目的地上不存在通用Snapshot複本、則命令會失敗。使用 `snapmirror initialize` 以重新初始化關係。

====
+
以下範例反轉原始來源 Volume 之間的關係、 `volA` 開啟 `svm1`以及您要提供資料的磁碟區、 `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_src::> snapmirror resync -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 當您準備重新建立對原始來源的資料存取時、請停止對原始目的地Volume的存取。其中一種方法是停止原始目的地SVM：
+
`vserver stop -vserver _SVM_`

+
如link:https://docs.netapp.com/us-en/ontap-cli/vserver-stop.html["指令參考資料ONTAP"^]需詳細 `vserver stop`資訊，請參閱。

+
[NOTE]
====
您必須從原始目的地SVM或原始目的地叢集執行此命令。此命令會停止使用者對整個原始目的地SVM的存取。您可能想要使用其他方法停止存取原始目的地Volume。

====
+
下列範例會停止原始目的地SVM：

+
[listing]
----
cluster_dst::> vserver stop svm_backup
----
. 更新反轉的關係：
+
`snapmirror update -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-update.html["指令參考資料ONTAP"^]需詳細 `snapmirror update`資訊，請參閱。

+
[NOTE]
====
您必須從原始來源SVM或原始來源叢集執行此命令。

====
+
以下範例更新了您要從中提供資料的磁碟區之間的關係、 `volA_dst` 開啟 `svm_backup`和原始來源Volume、 `volA` 開啟 `svm1`：

+
[listing]
----
cluster_src::> snapmirror update -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 從原始來源SVM或原始來源叢集、停止針對反向關係進行排程傳輸：
+
`snapmirror quiesce -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-quiesce.html["指令參考資料ONTAP"^]需詳細 `snapmirror quiesce`資訊，請參閱。

+
[NOTE]
====
您必須從原始來源SVM或原始來源叢集執行此命令。

====
+
下列範例會停止在原始目的地Volume之間的排程傳輸、 `volA_dst` 開啟 `svm_backup`和原始來源Volume、 `volA` 開啟 `svm1`：

+
[listing]
----
cluster_src::> snapmirror quiesce -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 當完成最後的更新、且關係指出關係狀態為「靜止」時、請從原始來源SVM或原始來源叢集執行下列命令、以中斷反向關係：
+
`snapmirror break -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-break.html["指令參考資料ONTAP"^]需詳細 `snapmirror break`資訊，請參閱。

+
[NOTE]
====
您必須從原始來源SVM或來源叢集執行此命令。

====
+
下列範例打破了原始目的地Volume之間的關係、 `volA_dst` 開啟 `svm_backup`和原始來源Volume、 `volA` 開啟 `svm1`：

+
[listing]
----
cluster_scr::> snapmirror break -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 從原始來源SVM或原始來源叢集刪除反向的資料保護關係：
+
`snapmirror delete -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-delete.html["指令參考資料ONTAP"^]需詳細 `snapmirror delete`資訊，請參閱。

+
[NOTE]
====
您必須從原始來源SVM或原始來源叢集執行此命令。

====
+
以下範例刪除原始來源磁碟區之間的反向關係、 `volA` 開啟 `svm1`以及您要提供資料的磁碟區、 `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_src::> snapmirror delete -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 從原始目的地SVM或原始目的地叢集釋放反向關係。
+
`snapmirror release -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
[NOTE]
====
您必須從原始目的地SVM或原始目的地叢集執行此命令。

====
+
下列範例會在原始目的地Volume之間釋出相反的關係、 `volA_dst` 開啟 `svm_backup`和原始來源Volume、 `volA` 開啟 `svm1`：

+
[listing]
----
cluster_dst::> snapmirror release -source-path svm_backup:volA_dst -destination-path svm1:volA
----
. 從原始目的地重新建立原始資料保護關係：
+
`snapmirror resync -source-path _SVM:volume_ -destination-path _SVM:volume_`

+
如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-resync.html["指令參考資料ONTAP"^]需詳細 `snapmirror resync`資訊，請參閱。

+
以下範例重新建立原始來源磁碟區之間的關係、 `volA` 開啟 `svm1`和原始目的地 Volume 、 `volA_dst` 開啟 `svm_backup`：

+
[listing]
----
cluster_dst::> snapmirror resync -source-path svm1:volA -destination-path svm_backup:volA_dst
----
. 如有需要、請啟動原始目的地SVM：
+
`vserver start -vserver _SVM_`

+
如link:https://docs.netapp.com/us-en/ontap-cli/vserver-start.html["指令參考資料ONTAP"^]需詳細 `vserver start`資訊，請參閱。

+
下列範例會啟動原始目的地SVM：

+
[listing]
----
cluster_dst::> vserver start svm_backup
----


.完成後
使用 `snapmirror show`命令驗證是否已建立 SnapMirror 關係。如link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-show.html["指令參考資料ONTAP"^]需詳細 `snapmirror show`資訊，請參閱。
