---
permalink: data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html 
sidebar: sidebar 
keywords: snapmirror, synchronous, disaster, recovery 
summary: 從ONTAP 推出SnapMirror 9.5開始、所有FAS 包含AFF 至少16 GB記憶體的SnapMirror同步（SM-S）技術、都能在所有ONTAP Select 的SnapMirror平台和支援所有的不穩定平台上運作。SnapMirror同步技術是一種每節點授權功能、可在磁碟區層級提供同步資料複寫。 
---
= SnapMirror同步災難恢復基礎知識
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP 推出SnapMirror 9.5開始、所有FAS 包含AFF 至少16 GB記憶體的SnapMirror同步（SM-S）技術、都能在所有ONTAP Select 的SnapMirror平台和支援所有的不穩定平台上運作。SnapMirror同步技術是一種每節點授權功能、可在磁碟區層級提供同步資料複寫。

這項功能可滿足金融、醫療及其他管制產業的法規及國家要求、在需要零資料遺失的情況下進行同步複寫。

每個HA配對的SnapMirror同步複寫作業數量上限取決於控制器機型。

下表根據平台類型和ONTAP 版本列出每個HA配對所允許的SnapMirror同步作業數量。

|===


| 平台 | 發行版本早於2009年9月9日ONTAP | 部分9.9.1 ONTAP | 零點9.10.1 ONTAP | 版本9.11.2\ONTAP 9.12.1. ONTAP 


 a| 
AFF
 a| 
80
 a| 
160
 a| 
200
 a| 
400



 a| 
FAS
 a| 
40
 a| 
80
 a| 
80
 a| 
80



 a| 
ONTAP Select
 a| 
20
 a| 
40
 a| 
40
 a| 
40

|===


== 支援的功能

僅在AFF/ASA平台上支援不中斷營運的SnapMirror同步作業（Nn）ONTAP 。支援不中斷營運、可讓您在不排程停機時間的情況下執行許多常見的維護工作。支援的作業包括接管與恢復、以及在兩個叢集之間保留一個節點的磁碟區移動。

下列功能支援ONTAP SnapMirror同步技術（位於景點叢集中的所有節點均執行ONTAP 《支援》）：

* NFSv4.2
* NVMe / TCP


在支援支援NFSv3、FC及iSCSI的更新版本中ONTAP 、SnapMirror同步技術可在延遲不超過10毫秒的所有網路上支援NFSv3、FC及iSCSI傳輸協定。

SnapMirror Synchronous支援FabricPool 以無、Snapshot或Auto等分層原則、在不同步的情況下、於不同步集合體上支援來源和目的地磁碟區。無法將目的地Volume的FabricPool 目的地集合體設為All Tiering原則。

下列功能支援ONTAP SnapMirror同步技術（位於NetApp上）：

* 複寫應用程式建立的Snapshot複本如果Snapshot複本在「建立快照」作業時使用CLI或ONTAP Eshot API標記適當的標籤、SnapMirror同步會在靜止應用程式之後、複寫使用者建立的Snapshot複本或使用外部指令碼建立的Snapshot複本。使用Snapshot原則建立的排程Snapshot複本不會複寫。如需複寫應用程式建立的Snapshot複本的詳細資訊、請參閱知識庫文章： link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Protection_and_Security/SnapMirror/How_to_replicate_application_created_snapshots_with_SnapMirror_Synchronous["如何使用SnapMirror同步複寫應用程式建立的快照"^]。
* FC-NVMe
* 也支援LUN複製和NVMe命名空間複製LUN複本、以應用程式建立的Snapshot複本為後盾。


下列功能支援ONTAP SnapMirror同步技術（位於32個資料中心）、但前提是來源和目的地叢集中的所有節點都執行ONTAP 的是32個資料中心。9.6：

* SVM DR
+
** SnapMirror同步來源也可以是SVM DR來源、例如以SM-S作為單一連線的連出組態、以及以SVM DR作為另一個連線。
** SnapMirror同步來源不能是SVM DR目的地、因為SM-S不支援串聯DP來源。在目的地叢集中執行SVM DR反轉重新同步之前、您必須先釋出同步關係。
** SnapMirror同步目的地不能是SVM DR來源、因為SVM DR不支援複寫DP磁碟區。反轉同步來源的同步會導致SVM DR排除目的地叢集中的DP磁碟區。


* NFSv4.0和NFSv4.1
* SMB 2.0或更新版本
* 混合式傳輸協定存取（NFSv3和SMB）
* SnapMirror同步關係的主要磁碟區上的防毒軟體
* SnapMirror同步關係的主磁碟區硬式或軟式配額配額不會將配額規則複寫到目的地、因此配額資料庫不會複寫到目的地。
* SnapMirror同步關係主要磁碟區的FPolicy
* SnapMirror同步鏡射鏡射會從SnapMirror同步關係的目的地Volume串聯關係、必須是非同步SnapMirror關係。
* NAS的來源與目的地Volume之間的時間戳記同位元如果您已從ONTAP S還原9.5升級ONTAP 至還原9.6、則時間戳記只會複寫至來源Volume中的任何新檔案和修改檔案。來源Volume中現有檔案的時間戳記不會同步。
* 移除高中繼資料作業頻率限制
* 使用TLS 1.2加密技術、確保傳輸中的敏感資料安全無虞
* 複製自動刪除


從 ONTAP 9.13.1 開始、 NDMP 支援 SnapMirror 同步。來源叢集和目的地叢集都必須執行 ONTAP 9.13.1 或更新版本、才能搭配 SnapMirror 同步使用 NDMP 。如需詳細資訊、請參閱 xref:../tape-backup/transfer-data-ndmpcopy-task.html[使用 NDMP 複本傳輸資料]。



== 不支援的功能

下列功能不支援同步SnapMirror關係：

* 可防竄改的Snapshot複本
* 一致性群組
* 內部組態MetroCluster
* SFMoD
* SFCoD
* VVOL
* 同一個Volume或SVM不支援混合SAN和NVMe存取LUN和NVMe命名空間。
* 資料量SnapLock
* 資料量FlexGroup
* 資料量FlexCache
* SnapRestore
* DP_最佳化（DPO）系統
* 在目的地磁碟區上使用dump和SMtape進行磁帶備份或還原
* 磁帶型還原至來源Volume
* 來源磁碟區的處理量層（QoS下限）
* 在連出組態中、只有一種關係可以是SnapMirror同步關係；來源磁碟區的所有其他關係必須是非同步SnapMirror關係。
* 全域節流




== 操作模式

SnapMirror Synchronous有兩種作業模式、分別取決於所使用的SnapMirror原則類型：

* *同步模式*在同步模式下、應用程式I/O作業會平行傳送至主要和次要儲存系統。如果由於任何原因而未完成對二線儲存設備的寫入、則允許應用程式繼續寫入一線儲存設備。當錯誤情況得到修正時、SnapMirror同步技術會自動與二線儲存設備重新同步、並以同步模式從一線儲存設備恢復複寫至二線儲存設備。在同步模式中、RPO=0和RTO非常低、直到發生二線複寫故障、導致RPO和RTO無法確定、但等於修復導致二線複寫失敗並完成重新同步的問題所需時間。
* * StrictSync模式* SnapMirror Synchronous可選擇性地在StrictSync模式中運作。如果由於任何原因未完成對二線儲存設備的寫入、應用程式I/O就會失敗、因此可確保一線與二線儲存設備完全相同。只有在SnapMirror關係恢復為「不同步」狀態之後、應用程式I/O才會繼續進行。如果主儲存設備故障、則可在容錯移轉後、在二線儲存設備上恢復應用程式I/O、而不會遺失資料。在StrictSync模式中、RPO永遠為零、RTO極低。




== 關係狀態

SnapMirror同步關係的狀態在正常操作期間始終處於「不同步」狀態。如果SnapMirror傳輸因任何原因而失敗、目的地將不會與來源同步、並可進入「OutofSync」狀態。

對於SnapMirror同步關係、系統會以固定時間間隔自動檢查關係狀態（「insync」或「OutofSync」）。如果關係狀態為「OutofSync」、ONTAP 則會自動觸發自動重新同步程序、將關係恢復為「insync」狀態。只有在傳輸因任何作業（例如來源或目的地的非計畫性儲存容錯移轉或網路中斷）而失敗時、才會觸發自動重新同步。使用者啟動的作業、例如「napmirror quiesce」和「shnapmirror Break」、不會觸發自動重新同步。

如果StrictSync模式中SnapMirror同步關係的關係狀態變成「OutofSync」、則會停止對主要磁碟區的所有I/O作業。在同步模式中、SnapMirror同步關係的「OutofSync」狀態不會中斷主要磁碟區的作業、而主要磁碟區的I/O作業則是允許的。

.相關資訊
http://["NetApp技術報告4733：SnapMirror同步設定與最佳實務做法"^]
