---
permalink: data-protection/snapmirror-licensing-concept.html 
sidebar: sidebar 
keywords: snapmirror, licensing, snapvault, vault, mirror, relationship, replication, backup, back up, disaster recovery, dr 
summary: 從功能介紹9.3開始ONTAP 、授權已簡化、可在ONTAP 各個執行個體之間進行複寫。在版本支援的部分、SnapMirror授權可同時支援資料保存和鏡射關係。ONTAP使用者現在可以購買SnapMirror授權、以支援ONTAP 針對備份和災難恢復使用案例進行的功能性複寫。 
---
= SnapMirror授權總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從功能介紹9.3開始ONTAP 、授權已簡化、可在ONTAP 各個執行個體之間進行複寫。在版本支援的部分、SnapMirror授權可同時支援資料保存和鏡射關係。ONTAP您可以使用 SnapMirror 授權來支援備份和災難恢復使用案例的 ONTAP 複寫。

在 ONTAP 9.3 版本之前、需要另外一個 SnapVault 授權來設定 ONTAP 執行個體之間的 _Vault_ 關係、其中 DP 執行個體可以保留更多的 Snapshot 複本、以支援保留時間較長的備份使用案例、 此外、還需要 SnapMirror 授權來設定 ONTAP 執行個體之間的 _mirror 關係、每個 ONTAP 執行個體都會維護相同數量的 Snapshot 複本（即 _mirror _ 映像）、以支援災難恢復使用案例、使叢集容錯移轉成為可能。SnapMirror 和 SnapVault 授權繼續用於 ONTAP 8.x 和 9.x 版本、並受到支援。

雖然 SnapVault 授權持續運作且同時支援 ONTAP 8.x 與 9.x 版本、 SnapMirror 授權可用於取代 SnapVault 授權、並可用於鏡射與資料保險箱組態。

對於非同步複寫、ONTAP 從ONTAP 使用支援功能的支援功能支援功能的支援功能、一開始使用單一統一化複寫引擎來設定延伸資料保護模式（XDP）原則、其中SnapMirror授權可設定為鏡射原則、資料保存原則或鏡射保存原則。來源叢集和目的地叢集都需要SnapMirror授權。如果已安裝SnapMirror授權、則不需要使用此功能。SnapVaultSnapMirror 非同步永久授權包含在安裝在新 AFF 和 FAS 系統上的 ONTAP One 軟體套件中。

資料保護組態限制是由多項因素決定、包括ONTAP 您的版次、硬體平台和安裝的授權。如需詳細資訊、請參閱 https://hwu.netapp.com/["Hardware Universe"^]。



== SnapMirror同步授權

從ONTAP 支援SnapMirror 9.5開始、即支援SnapMirror同步關係。您需要下列授權才能建立SnapMirror同步關係：

* 來源叢集和目的地叢集都需要SnapMirror同步授權。
+
SnapMirror Synchronous 授權是的一部分 https://docs.netapp.com/us-en/ontap/system-admin/manage-licenses-concept.html["ONTAP 單一授權套件"]。

+
如果您的系統是在 2019 年 6 月之前隨 Premium 或 Flash 產品組合一起購買，您可以從 NetApp 支援網站下載 NetApp 主金鑰，以取得必要的 SnapMirror Synchronous 授權： https://mysupport.netapp.com/NOW/knowledge/docs/olio/guides/master_lickey/["主要授權金鑰"]。

* 來源叢集和目的地叢集都需要SnapMirror授權。




== SnapMirror Cloud授權

SnapMirror Cloud授權從ONTAP 功能不中斷的9.8開始、可將ONTAP Snapshot複本從功能不同步複寫到物件儲存端點。複寫目標可以使用內部部署物件存放區、S3和S3相容的公有雲物件儲存服務來設定。SnapMirror Cloud關係可從ONTAP 支援的對象儲存目標、從不完整的系統到預先符合資格的物件儲存目標、皆可獲得支援。

SnapMirror Cloud 不提供獨立授權。每ONTAP 個叢集只需要一份授權。除了 SnapMirror Cloud 授權之外、還需要非同步 SnapMirror 授權。

您需要下列授權才能建立SnapMirror雲端關係：

* SnapMirror 授權和 SnapMirror Cloud 授權、可直接複寫至物件儲存區端點。
* 在設定多重原則複寫工作流程（例如、磁碟對磁碟對雲端）時、所有ONTAP 的SnapMirror執行個體都需要SnapMirror授權、而SnapMirror Cloud授權則只有直接複寫到物件儲存端點的來源叢集才需要。


從 ONTAP 9.9.1 開始、您就可以了 https://docs.netapp.com/us-en/ontap/task_dp_back_up_to_cloud.html["使用 System Manager 進行 SnapMirror Cloud 複寫"]。

授權的SnapMirror Cloud第三方應用程式清單已發佈在NetApp網站上。

資料保護最佳化（ DPO ）授權不再銷售、而且目前平台不支援 DPO ；不過、如果您在支援的平台上安裝 DPO 授權、 NetApp 會持續提供支援、直到該平台的可用性結束為止。

ONTAP One 授權套件不隨附 DPO 、如果系統上安裝了 DPO 授權、您就無法升級至 ONTAP One 授權套件。

如需支援平台的相關資訊、請參閱 https://hwu.netapp.com/["Hardware Universe"^]。
