---
permalink: data-protection/snapmirror-synchronous-disaster-recovery-basics-concept.html 
sidebar: sidebar 
keywords: snapmirror, synchronous, disaster, recovery 
summary: 從ONTAP 推出SnapMirror 9.5開始、所有FAS 包含AFF 至少16 GB記憶體的SnapMirror同步（SM-S）技術、都能在所有ONTAP Select 的SnapMirror平台和支援所有的不穩定平台上運作。SnapMirror同步技術是一種每節點授權功能、可在磁碟區層級提供同步資料複寫。 
---
= SnapMirror同步災難恢復基礎知識
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP 推出SnapMirror 9.5開始、所有FAS 包含AFF 至少16 GB記憶體的SnapMirror同步（SM-S）技術、都能在所有ONTAP Select 的SnapMirror平台和支援所有的不穩定平台上運作。SnapMirror同步技術是一種每節點授權功能、可在磁碟區層級提供同步資料複寫。

這項功能可滿足金融、醫療及其他管制產業的法規及國家要求、在需要零資料遺失的情況下進行同步複寫。

每個HA配對的SnapMirror同步複寫作業數量上限取決於控制器機型。

|===


| 平台 | 早於發行版本的SnapMirror 9.9.1、每個HA配對所允許的SnapMirror同步作業數ONTAP | 在SnapMirror 9.9.1中、每個HA配對允許的SnapMirror同步作業數ONTAP | SnapMirror同步作業的數量ONTAP 、可在版本號為9、10.1的每個HA配對中執行 | SnapMirror同步作業的數量ONTAP 、每個HA配對均可在版本號之間執行 


 a| 
AFF
 a| 
80
 a| 
160
 a| 
200
 a| 
400



 a| 
FAS
 a| 
40
 a| 
80
 a| 
80
 a| 
80



 a| 
ONTAP Select
 a| 
20
 a| 
40
 a| 
40
 a| 
40

|===


== 支援的功能

下列功能支援ONTAP SnapMirror同步技術（位於SnapMirror 9.10.1中）；前提是來源與目的地叢集中的所有節點都執行ONTAP 的是《支援使用支援的功能》（英語）：

* NFSv4.2


在支援支援NFSv3、FC及iSCSI的更新版本中ONTAP 、SnapMirror同步技術可在延遲不超過10毫秒的所有網路上支援NFSv3、FC及iSCSI傳輸協定。

下列功能支援ONTAP SnapMirror同步技術（位於NetApp上）：

* 複寫應用程式建立的Snapshot只會複本Snapshot複本、其SnapMirror標籤符合與Sync或Strict Sync原則相關的規則。使用Snapshot原則建立的排程Snapshot複本不會複寫。
* FC-NVMe
* 也支援LUN複製和NVMe命名空間複製LUN複本、以應用程式建立的Snapshot複本為後盾。


下列功能支援ONTAP SnapMirror同步技術（位於32個資料中心）、但前提是來源和目的地叢集中的所有節點都執行ONTAP 的是32個資料中心。9.6：

* SVM DR
+
** SnapMirror同步來源也可以是SVM DR來源、例如以SM-S作為單一連線的連出組態、以及以SVM DR作為另一個連線。
** SnapMirror同步來源不能是SVM DR目的地、因為SM-S不支援串聯DP來源。在目的地叢集中執行SVM DR反轉重新同步之前、您必須先釋出同步關係。
** SnapMirror同步目的地不能是SVM DR來源、因為SVM DR不支援複寫DP磁碟區。反轉同步來源的同步會導致SVM DR排除目的地叢集中的DP磁碟區。


* NFSv4.0和NFSv4.1
* SMB 2.0或更新版本
* 混合式傳輸協定存取（NFSv3和SMB）
* SnapMirror同步關係的主要磁碟區上的防毒軟體
* SnapMirror同步關係的主磁碟區硬式或軟式配額配額不會將配額規則複寫到目的地、因此配額資料庫不會複寫到目的地。
* SnapMirror同步關係主要磁碟區的FPolicy
* SnapMirror同步鏡射鏡射會從SnapMirror同步關係的目的地Volume串聯關係、必須是非同步SnapMirror關係。
* NAS的來源與目的地Volume之間的時間戳記同位元如果您已從ONTAP S還原9.5升級ONTAP 至還原9.6、則時間戳記只會複寫至來源Volume中的任何新檔案和修改檔案。來源Volume中現有檔案的時間戳記不會同步。
* 移除高中繼資料作業頻率限制
* 使用TLS 1.2加密技術、確保傳輸中的敏感資料安全無虞
* 複製自動刪除




== 不支援的功能

下列功能不支援同步SnapMirror關係：

* MCC
* SFMoD
* SFCoD
* VVOL
* 混合式SAN與NAS存取SnapMirror同步關係的主要磁碟區、可用於NAS資料或SAN資料。不支援從SnapMirror同步關係的主要磁碟區存取SAN和NAS。
* 同一個Volume或SVM不支援混合SAN和NVMe存取LUN和NVMe命名空間。
* 資料量SnapLock
* 資料量FlexGroup
* 資料量FlexCache
* SnapRestore
* DP_最佳化（DPO）系統
* 在目的地磁碟區上使用dump和SMtape進行磁帶備份或還原
* 磁帶型還原至來源Volume
* 來源磁碟區的處理量層（QoS下限）
* 在連出組態中、只有一種關係可以是SnapMirror同步關係；來源磁碟區的所有其他關係必須是非同步SnapMirror關係。
* 全域節流




== 操作模式

SnapMirror Synchronous有兩種作業模式、分別取決於所使用的SnapMirror原則類型：

* *同步模式*在同步模式下、將I/O複寫至主要儲存設備、然後再複寫至次要儲存設備。然後將I/O寫入主儲存設備、並將確認函傳送至發出I/O的應用程式如果由於任何原因而未完成對二線儲存設備的寫入、則允許應用程式繼續寫入一線儲存設備。當錯誤情況得到修正時、SnapMirror同步技術會自動與二線儲存設備重新同步、並以同步模式從一線儲存設備恢復複寫至二線儲存設備。在同步模式中、RPO=0和RTO非常低、直到發生二線複寫故障、導致RPO和RTO無法確定、但等於修復導致二線複寫失敗並完成重新同步的問題所需時間。
* * StrictSync模式* SnapMirror Synchronous可選擇性地在StrictSync模式中運作。如果由於任何原因未完成對二線儲存設備的寫入、應用程式I/O就會失敗、因此可確保一線與二線儲存設備完全相同。只有在SnapMirror關係恢復為「不同步」狀態之後、應用程式I/O才會繼續進行。如果主儲存設備故障、則可在容錯移轉後、在二線儲存設備上恢復應用程式I/O、而不會遺失資料。在StrictSync模式中、RPO永遠為零、RTO極低。




== 關係狀態

SnapMirror同步關係的狀態在正常操作期間始終處於「不同步」狀態。如果SnapMirror傳輸因任何原因而失敗、目的地將不會與來源同步、並可進入「OutofSync」狀態。

對於SnapMirror同步關係、系統會以固定時間間隔自動檢查關係狀態（「insync」或「OutofSync」）。如果關係狀態為「OutofSync」、ONTAP 則會自動觸發自動重新同步程序、將關係恢復為「insync」狀態。只有在傳輸因任何作業（例如來源或目的地的非計畫性儲存容錯移轉或網路中斷）而失敗時、才會觸發自動重新同步。使用者啟動的作業、例如「napmirror quiesce」和「shnapmirror Break」、不會觸發自動重新同步。

如果StrictSync模式中SnapMirror同步關係的關係狀態變成「OutofSync」、則會停止對主要磁碟區的所有I/O作業。在同步模式中、SnapMirror同步關係的「OutofSync」狀態不會中斷主要磁碟區的作業、而主要磁碟區的I/O作業則是允許的。

http://www.netapp.com/us/media/tr-4733.pdf["NetApp技術報告4733：SnapMirror Synchronous for ONTAP NetApp 9.6"^]
