---
permalink: data-protection/snapmirror-unified-replication-concept.html 
sidebar: sidebar 
keywords: snapmirror, unified, replication 
summary: SnapMirror統一化複寫可讓您在同一個目的地磁碟區上設定災難恢復和歸檔。當統一化複寫適當時、它可協助您減少所需的二線儲存設備數量、限制基礎傳輸數量、以及減少網路流量。 
---
= SnapMirror統一化複寫基礎
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror _統一化複寫_可讓您在同一個目的地磁碟區上設定災難恢復與歸檔。當統一化複寫適當時、它可協助您減少所需的二線儲存設備數量、限制基礎傳輸數量、以及減少網路流量。



== 如何初始化統一化資料保護關係

與SnapMirror一樣、統一化資料保護會在您第一次叫用時執行基準傳輸。關係的SnapMirror原則定義了基礎的內容和任何更新。

預設統一資料保護原則下的基準傳輸 `MirrorAndVault` 製作來源 Volume 的 Snapshot 複本、然後將該複本及其參照的資料區塊傳輸至目的地 Volume 。如同保存庫歸檔、統一化資料保護功能不會在基準中包含舊的Snapshot複本。



== 如何更新統一化資料保護關係

在的每個更新中 `MirrorAndVault` 原則： SnapMirror 會建立來源 Volume 的 Snapshot 複本、並傳輸該 Snapshot 複本和自上次更新後所建立的任何 Snapshot 複本、前提是標籤必須符合 Snapshot 原則規則中定義的標籤。在的下列輸出中 `snapmirror policy show` 的命令 `MirrorAndVault` 原則請注意下列事項：

* `Create Snapshot` 為「 'true' 」、表示這一點 `MirrorAndVault` 當 SnapMirror 更新關係時建立 Snapshot 複本。
* `MirrorAndVault` 有 "`shm_Created （已建立） " 、 "daily" 和 "`eile" 等規則、表示 SnapMirror 建立的 Snapshot 複本和來源上具有相符標籤的 Snapshot 複本、都會在 SnapMirror 更新關係時傳輸。


[listing]
----
cluster_dst::> snapmirror policy show -policy MirrorAndVault -instance

                     Vserver: vs0
      SnapMirror Policy Name: MirrorAndVault
      SnapMirror Policy Type: mirror-vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: true
                     Comment: A unified SnapMirror synchronous and SnapVault policy for
                              mirroring the latest file system and daily and weekly snapshots.
       Total Number of Rules: 3
                  Total Keep: 59
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
----


== Unified7年政策

預先設定的 `Unified7year` 原則的運作方式與完全相同 `MirrorAndVault`，但第四條規則會每月傳輸 Snapshot 複本並保留七年。

[listing]
----

                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
                              monthly                84  false       0 -        -
----


== 避免可能的資料毀損

統一化複寫會限制基礎傳輸的內容、以供SnapMirror在初始化時建立Snapshot複本。每次更新時、SnapMirror都會建立另一個來源的Snapshot複本、並傳輸該Snapshot複本和任何新的Snapshot複本、這些複本的標籤與Snapshot原則規則中定義的標籤相符。

您可以在目的地上建立上次傳輸的Snapshot複本複本、避免更新的Snapshot複本毀損。無論來源上的保留規則為何、都會保留此「本機複本」、即使來源上不再提供SnapMirror原本傳輸的Snapshot、也會在目的地上提供該Snapshot複本。



== 何時使用統一化資料複寫

您需要權衡維護完整鏡像的優點、以及統一化複寫在減少二線儲存設備數量、限制基礎傳輸數量及減少網路流量方面所提供的優勢。

決定統一化複寫是否適當的關鍵因素、在於作用中檔案系統的變更率。例如、傳統鏡像可能更適合存放資料庫交易記錄每小時Snapshot複本的磁碟區。
