---
permalink: data-protection/snapmirror-unified-replication-concept.html 
sidebar: sidebar 
keywords: snapmirror, unified, replication 
summary: SnapMirror統一化複寫可讓您在同一個目的地磁碟區上設定災難恢復和歸檔。當統一化複寫適當時、它可協助您減少所需的二線儲存設備數量、限制基礎傳輸數量、以及減少網路流量。 
---
= SnapMirror統一化複寫基礎
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror _統一化複寫_可讓您在同一個目的地磁碟區上設定災難恢復與歸檔。當統一化複寫適當時、它可協助您減少所需的二線儲存設備數量、限制基礎傳輸數量、以及減少網路流量。



== 如何初始化統一化資料保護關係

與SnapMirror一樣、統一化資料保護會在您第一次叫用時執行基準傳輸。關係的SnapMirror原則定義了基礎的內容和任何更新。

根據預設統一資料保護原則進行的基準傳輸 `MirrorAndVault`會建立來源磁碟區的快照，然後將該複本及其參照的資料區塊傳輸至目的地磁碟區。與資料保險箱歸檔一樣，統一化資料保護也不包括基礎中較舊的快照。



== 如何更新統一化資料保護關係

在原則下的每個更新中， SnapMirror 都 `MirrorAndVault`會建立來源磁碟區的快照，並傳輸自上次更新後所建立的快照和任何快照，前提是它們的標籤必須符合快照原則規則中定義的標籤。在原則命令的 `MirrorAndVault`下列輸出中， `snapmirror policy show`請注意下列事項：

* `Create Snapshot`為「 'true' 」，表示 `MirrorAndVault`在 SnapMirror 更新關係時建立快照。
* `MirrorAndVault`有「 sim_Created 」，「 daily 」和「 'faily' 等規則，表示 SnapMirror 更新關係時，會同時傳輸 SnapMirror 建立的快照和來源上具有相符標籤的快照。


[listing]
----
cluster_dst::> snapmirror policy show -policy MirrorAndVault -instance

                     Vserver: vs0
      SnapMirror Policy Name: MirrorAndVault
      SnapMirror Policy Type: mirror-vault
                Policy Owner: cluster-admin
                 Tries Limit: 8
           Transfer Priority: normal
   Ignore accesstime Enabled: false
     Transfer Restartability: always
 Network Compression Enabled: false
             Create Snapshot: true
                     Comment: A unified SnapMirror synchronous and SnapVault policy for
                              mirroring the latest file system and daily and weekly snapshots.
       Total Number of Rules: 3
                  Total Keep: 59
                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
----


== Unified7年政策

預先設定的 `Unified7year`原則運作方式與完全相同， `MirrorAndVault`只是第四條規則會每月傳輸快照並保留 7 年。

[listing]
----

                       Rules: SnapMirror Label     Keep  Preserve Warn Schedule Prefix
                              ----------------     ----  -------- ---- -------- ------
                              sm_created              1  false       0 -        -
                              daily                   7  false       0 -        -
                              weekly                 52  false       0 -        -
                              monthly                84  false       0 -        -
----


== 避免可能的資料毀損

統一複寫會將基準傳輸的內容限制在初始化時由 SnapMirror 建立的快照上。在每次更新時， SnapMirror 會建立來源的另一個快照，並傳輸該快照和任何標籤符合快照原則規則中定義的標籤的新快照。

您可以在目的地上建立最後傳輸的快照複本，以防止更新的快照毀損。無論來源上的保留規則為何，此「本機複本」都會保留，因此即使來源上不再提供 SnapMirror 原本傳輸的快照，也可以在目的地上取得該快照的複本。



== 何時使用統一化資料複寫

您需要權衡維護完整鏡像的優點、以及統一化複寫在減少二線儲存設備數量、限制基礎傳輸數量及減少網路流量方面所提供的優勢。

決定統一化複寫是否適當的關鍵因素、在於作用中檔案系統的變更率。舉例來說，傳統鏡像可能更適合儲存資料庫交易記錄每小時快照的磁碟區。
