---
permalink: data-protection/version-flexible-snapmirror-default-concept.html 
sidebar: sidebar 
keywords: xdp, replace, dp, snapmirror, default, snap mirror, data protection, replication, replicate, snap lock, snaplock 
summary: SnapMirror ONTAP 延伸資料保護（XDP）模式從功能支援的9.3開始、將SnapMirror資料保護（DP）模式取代為SnapMirror預設模式。 
---
= XDP取代DP做為SnapMirror預設值
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
SnapMirror ONTAP 延伸資料保護（XDP）模式從功能支援的9.3開始、將SnapMirror資料保護（DP）模式取代為SnapMirror預設模式。

在升級ONTAP 至版本更新至版本更新ONTAP 之前、您必須先將現有的DP類型關係轉換成XDP、才能升級至版本更新。如需詳細資訊、請參閱 link:convert-snapmirror-version-flexible-task.html["將現有的DP類型關係轉換為XDP"]。

直到使用SnapMirror 9.3之前ONTAP 、在DP模式中叫用SnapMirror、而在XDP模式中叫用SnapMirror、使用不同的複寫引擎、並採用不同的版本相依方法：

* 在DP模式中叫用的SnapMirror使用_版本相依_複寫引擎、ONTAP 而在其中、必須在主要和次要儲存設備上使用相同的版本：
+
[listing]
----
cluster_dst::>  snapmirror create -type DP -source-path ... -destination-path ...
----
* 在XDP模式中叫用的SnapMirror使用_版本彈性_複寫引擎、可在ONTAP 一線和二線儲存設備上支援不同的版本：
+
[listing]
----
cluster_dst::>  snapmirror create -type XDP -source-path ... -destination-path ...
----


隨著效能提升、版本靈活的SnapMirror的顯著效益、超過了以版本相依模式取得的複寫處理量的小優勢。因此、從ONTAP 功能更新9.3開始、XDP模式已成為新的預設值、而在命令列或新的或現有指令碼中、DP模式的任何調用、都會自動轉換為XDP模式。

現有的關係不受影響。如果某個關係已經是DP類型、則會繼續是DP類型。從ONTAP 功能表9.5開始、當未指定資料保護模式或將XDP模式指定為關係類型時、MirrorAndVault是新的預設原則。下表顯示您可以預期的行為。

[cols="3*"]
|===


| 如果您指定... | 類型為... | 預設原則（如果您未指定原則）是... 


 a| 
DP
 a| 
XDP
 a| 
MirrorAllSnapshots（SnapMirror DR）



 a| 
什麼都沒有
 a| 
XDP
 a| 
MirrorAndVault（統一化複寫）



 a| 
XDP
 a| 
XDP
 a| 
MirrorAndVault（統一化複寫）

|===
如表所示、在不同情況下指派給XDP的預設原則可確保轉換作業維持舊類型的功能等效性。當然、您可以視需要使用不同的原則、包括統一化複寫的原則：

[cols="3*"]
|===


| 如果您指定... | 政策是... | 結果是... 


 a| 
DP
 a| 
MirrorAllSnapshots
 a| 
SnapMirror災難恢復



 a| 
XDPDefault
 a| 
SnapVault



 a| 
MirrorAndVault
 a| 
統一化複寫



 a| 
XDP
 a| 
MirrorAllSnapshots
 a| 
SnapMirror災難恢復



 a| 
XDPDefault
 a| 
SnapVault



 a| 
MirrorAndVault
 a| 
統一化複寫

|===
轉換的唯一例外情況如下：

* SVM資料保護關係在ONTAP 更新版本的更新版本中、仍預設為DP模式。
+
從ONTAP SVM 9.4開始、SVM資料保護關係預設為XDP模式。

* 根Volume負載共享資料保護關係仍預設為DP模式。
* 在更新版本的版本中、資料保護關係仍預設為DP模式。SnapLock ONTAP
+
從ONTAP S廳9.5開始、SnapLock 資料保護關係預設為XDP模式。

* 如果您設定下列全叢集選項、DP的明確調用仍會繼續預設為DP模式：
+
[listing]
----
options replication.create_data_protection_rels.enable on
----
+
如果您未明確叫用DP、則會忽略此選項。


