---
permalink: release-notes/index.html 
sidebar: sidebar 
keywords: release notes, new features, ontap 9, digital advisor 
summary: 瞭解 ONTAP 9 的新功能。 
---
= ONTAP 9 版本重點摘要
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
每個 ONTAP 9 資料管理軟體版本都提供全新且增強的功能、可改善 ONTAP 的功能、管理能力、效能和安全性。

除了這些重點摘要之外、您還可以針對最新 ONTAP 版本中推出的所有新功能和增強功能、找到全方位的每個版本涵蓋範圍。

* 深入瞭解 https://docs.netapp.com/us-en/ontap-metrocluster/releasenotes/mcc-new-features.html["全新增強的 ONTAP MetroCluster 功能"^]。
* 了解 https://docs.netapp.com/us-en/asa-r2/release-notes/whats-new-9171.html["適用於NetApp ASA r2 系統的全新增強型ONTAP軟體功能"^] 。
* 了解 https://docs.netapp.com/us-en/ontap-systems/whats-new.html["對AFF、 ASA和FAS系統以及支援的交換器的全新和增強支持"^] 。
* 瞭解的更新 https://docs.netapp.com/us-en/ontap-automation/whats_new.html["靜態API ONTAP"^]。


如需最新 ONTAP 9 版本中已知問題、限制和升級注意事項的詳細資訊、請參閱 https://library.netapp.com/ecm/ecm_download_file/ECMLP2492508["發行說明ONTAP"^]。您必須使用 NetApp 帳戶登入、或建立帳戶才能存取版本資訊。

若要升級至最新版的 ONTAP 、請參閱 xref:../upgrade/prepare.html[升級至最新版的 ONTAP] 和 xref:../upgrade/when-to-upgrade.html[我應該何時升級 ONTAP ？]



== ONTAP 9.17.1 亮點

ONTAP 9.17.1 在 AI 驅動的 SAN 自主勒索軟體防護方面提供了創新，並透過SnapMirror主動同步和一致性群組分層管理增加了 NVMe 前端主機支援。這些增強功能鞏固了 NetApp 在資料安全和網路彈性方面的領導地位，提高了ONTAP 的效能、可擴展性、效率和業務連續性。有關新功能和增強功能的完整列表，請參閱xref:whats-new-9171.adoc[ONTAP 9.17.1 的新增功能] 。

* xref:../anti-ransomware/index.html[支援具有自主勒索軟體防護功能的 SAN]
+
ARP 支援基於加密的異常檢測功能，可支援 SAN 卷，引入用於詳細熵統計的新命令，並統一了系統管理器中先前專注於 NAS 的勒索軟體防護訊息傳遞。可配置的偵測閾值和更確定性的快照保留功能為各種工作負載提供了更大的靈活性。

* xref:../system-admin/use-hsts-task.html[HTTP 嚴格傳輸安全性 (HSTS) 支持]
+
ONTAP 9.17.1 支援 Web 服務的 HTTP 嚴格傳輸安全，以便能夠在使用者瀏覽器和ONTAP之間實作安全的 HTTPS 通訊。

* xref:../networking/ipsec-prepare.html[透過鏈路聚合組進行 IPsec 硬體卸載]
+
ONTAP 9.17.1 支援鏈路聚合組的 IPsec 硬體卸載，擴展了ONTAP 9.16.1 中引入的硬體卸載支援。

* xref:../networking/ipsec-prepare.html[IPsec 後量子預共享密鑰支持]
+
ONTAP支援 IPsec 的後量子預共用金鑰，以防止未來潛在的量子電腦攻擊。

* xref:../encryption-at-rest/manage-keys-barbican-task.html[OpenStack Barbican 金鑰管理器支援]
+
ONTAP支援 OpenStack 的 Barbican 金鑰管理器用於NetApp磁碟區加密 (NVE) 金鑰。

* xref:../authentication/configure-jit-elevation-task.html[即時 (JIT) 權限提升支持]
+
ONTAP支援基於角色的存取控制 (RBAC) 的 JIT 權限提升。使用者可以請求臨時提升到已配置的角色，從而按需存取特權命令。叢集管理員可以設定哪些人可以存取 JIT 權限提升，以及何時允許存取以及允許存取多長時間。

* xref:../system-admin/configure-saml-authentication-task.html[支援 Entra IdP 和 IdP 群組支援 SAML 身份驗證]
+
ONTAP支援使用 Microsoft Entra 作為 SAML 身分提供者。此外，IdP 提供的群組資訊可以對應到ONTAP角色。

* xref:../nvme/support-limitations.html#features[SnapMirror主動同步支援透過 NVMe 進行主機訪問]
+
SnapMirror主動同步功能新增了對 VMware 工作負載的 NVMe 存取支持，支援 NVMe/TCP 和 NVMe/FC 主機訪問，適用於雙節點ONTAP叢集。 VMware

* xref:../snapmirror-active-sync/index.html[ONTAP Cloud Mediator 支援SnapMirror主動同步]
+
ONTAP Cloud Mediator 是ONTAP 9.17.1 中引入的新功能，支援SnapMirror主動同步關係。基於雲端的調解器（例如ONTAP Mediator）可充當SnapMirror主動同步關係的仲裁見證，確保透明的故障轉移，同時降低維護和管理第三個站點的操作複雜性。





== ONTAP 9.16.1 重點介紹

ONTAP 9 。 16.1 在安全管理，資料保護，網路， SAN 管理和儲存管理等領域提供全新且增強的功能。如需新功能與增強功能的完整清單，請參閱xref:whats-new-9161.adoc[ONTAP 9.16.1 的新功能]。

* xref:../multi-admin-verify/index.html#rule-protected-commands[多重管理驗證（ MAV ）增強功能]
+
ONTAP 9 。 16.1 在 MAV 架構中新增更多命令，以進一步保護免於惡意內部人員的攻擊。這些增強功能包括許多一致性群組（ CG ）， VScan 和自主勒索軟體保護（ ARP ）管理，以及 NVMe 組態命令。

* xref:../anti-ransomware/index.html[利用 AI 增強功能（ ARP/AI ）提供自主勒索軟體保護]
+
ARP 已升級為全新的 AI 功能，讓 IT 能夠偵測並回應勒索軟體攻擊，精確程度達 99% ，而且容易回收。由於 AI 受過全方位資料集的訓練，因此在 FlexVol 磁碟區上執行 ARP 不再需要學習一段時間，而且 ARP/AI 會立即以作用中模式啟動。ARP/AI 也推出自動更新功能，不受 ONTAP 升級影響，確保持續保護並抵禦最新威脅。

* 透過 TLS 1.3 的 NVMe / TCP
+
透過簡化的組態和比 IPSec 更好的效能，保護通訊協定層的 NVMe / TCP 「無線傳輸」。

* xref:../networking/ipsec-prepare.html[IPsec 硬體卸載支援新的網路卡]
+
ONTAP 9.16.1 在最新一代的 AFF A 系列和 AFF C 系列系統平台中，將 IPSec 硬體卸載功能運用在卸載卡上，可提供更高的「有線」加密效能。

* xref:../san-admin/enable-space-allocation.html[支援 NVMe 空間分配]
+
NVMe 命名空間現在支援空間釋放（也稱為「打洞」和「取消映射」）。當主機應用程式刪除資料時，空間釋放可協助精簡配置磁碟區和 NVMe 命名空間回收未使用的空間。這大大提高了整體儲存效率，特別是對於資料週轉率高的檔案系統。

* xref:../flexgroup/enable-adv-capacity-flexgroup-task.html[FlexGroup 磁碟區的進階容量平衡]
+
NetApp FlexGroup Volume 可選擇性地在多個後端組成磁碟區之間的單一檔案中等量資料，減少效能瓶頸，並在平衡後端組成磁碟區的容量時增加一致性。

* xref:../svm-migrate/index.html[SVM 資料移動性支援，可移轉 MetroCluster 組態]
+
ONTAP 支援下列 MetroCluster SVM 移轉：

+
** 在非 MetroCluster 組態和 MetroCluster IP 組態之間移轉 SVM
** 在兩個 MetroCluster IP 組態之間移轉 SVM
** 在 MetroCluster FC 組態和 MetroCluster IP 組態之間移轉 SVM






== ONTAP 9.15.1 重點介紹

ONTAP 9.15.1 在安全管理、資料保護和 NAS 工作負載支援等領域提供全新且增強的功能。如需新功能與增強功能的完整清單、請參閱 xref:whats-new-9151.adoc[ONTAP 9.15.1 的新功能]。

* https://www.netapp.com/data-storage/aff-a-series/["支援全新 AFF A 系列系統、專為 AI 打造的儲存設備"^]
+
ONTAP 9.15.1 支援全新的高效能 AFF A1K 、 AFF A90 和 AFF A70 系統、專為下一代商業工作負載所設計、例如 AI / ML 訓練和推論。這種新型系統的效能是現有 AFF A 系列產品的兩倍，並可「持續運作」提升儲存效率，而不會影響效能。

* xref:../smb-admin/windows-backup-symlinks.html[伺服器上的 Windows 備份應用程式和 Unix 風格的符號鏈接]
+
從 ONTAP 9.15.1 開始、您也可以選擇備份 symlink 本身、而非指向的資料。這可提供多項優點、包括改善備份應用程式的效能。您可以使用 ONTAP CLI 或 REST API 來啟用此功能。

* xref:../authentication/dynamic-authorization-overview.html[動態授權]
+
ONTAP 9.15.1 引進動態授權的初始架構、這項安全功能可判斷系統管理員帳戶所發出的命令是否應遭到拒絕、是否提示進行額外驗證、或是否允許繼續。判斷是根據使用者帳戶的信任分數、並考量時間、位置、 IP 位址、信任的裝置使用量、以及使用者的驗證和授權記錄等因素。

* xref:../multi-admin-verify/index.html#rule-protected-commands[擴大多管理驗證的影響範圍]
+
ONTAP 9.15.1 RC1 為 MAV 架構新增了超過一百個命令、以進一步保護免於惡意內部人員的攻擊。

* TLS 1.3 加密支援叢集對等關係等功能
+
ONTAP 9.15.1 針對 S3 儲存、 FlexCache 、 SnapMirror 和叢集對等加密、推出 TLS 1.3 加密支援。FabricPool 、 Microsoft Azure Page Blobs 儲存設備和 SnapMirror Cloud 等應用程式在 9.15.1 版中持續使用 TLS 1.2 。

* 支援 TLS 上的 SMTP 流量
+
透過支援 TLS 的電子郵件安全傳輸 AutoSupport 資料。

* xref:../snapmirror-active-sync/index.html[SnapMirror 主動同步適用於對稱的主動 / 主動式組態]
+
這項新功能可提供同步雙向複寫、以利業務持續運作和災難恢復。透過跨多個故障網域同時讀取及寫入資料、保護關鍵 SAN 工作負載的資料存取、實現不中斷的作業、並將災難或系統故障期間的停機時間降至最低。

* xref:../flexcache-writeback/flexcache-writeback-enable-task.html[FlexCache 回寫]
+
FlexCache 回寫功能可讓用戶端在本機寫入 FlexCache 磁碟區，相較於直接寫入原始磁碟區，可減少延遲並改善效能。新寫入的資料會以非同步方式複寫回原始磁碟區。

* xref:../nfs-rdma/index.html[NFSv3 over RDMA]
+
NFSv3 over RDMA 支援可透過 TCP 提供低延遲、高頻寬存取、協助您解決高效能需求。





== ONTAP 9.14.1 重點摘要

ONTAP 9.14.1 在 FabricPool 、反勒索軟體保護、 OAuth 等領域提供全新且增強的功能。如需新功能與增強功能的完整清單、請參閱 xref:whats-new-9141.adoc[ONTAP 9.14.1 的新功能]。

* xref:../volumes/determine-space-usage-volume-aggregate-concept.html[WAFL 保留減少]
+
ONTAP 9.14.1 將 WAFL 保留空間減少至 30 TB 以上、可立即增加 5% 的 FAS 和 Cloud Volumes ONTAP 系統可用空間。

* xref:../fabricpool/enable-disable-volume-cloud-write-task.html[FabricPool 增強功能]
+
FabricPool 提供更高的效益 xref:../fabricpool/enable-disable-aggressive-read-ahead-task.html[讀取效能] 並可直接寫入雲端、降低空間不足的風險、並將冷資料移至成本較低的儲存層、進而降低儲存成本。

* link:../authentication/oauth2-deploy-ontap.html["支援 OAuth 2.0"]
+
ONTAP 支援 OAuth 2.0 架構、可透過系統管理員進行設定。有了 OAuth 2.0 、您就能安全地存取自動化架構的 ONTAP 、而無需建立或將使用者 ID 和密碼公開給純文字指令碼和執行手冊。

* link:../anti-ransomware/manage-parameters-task.html["自主勒索軟體保護（ ARP ）增強功能"]
+
ARP 可讓您更有效地控制事件安全性、讓您調整建立警示的條件、並降低誤報的可能性。

* xref:../data-protection/create-delete-snapmirror-failover-test-task.html[SnapMirror 災難恢復在 System Manager 中進行演練]
+
System Manager 提供簡單的工作流程、可在遠端位置輕鬆測試災難恢復、並在測試後進行清理。此功能可讓測試更輕鬆、更頻繁、並提高恢復時間目標的信心。

* xref:../s3-config/index.html[S3 物件鎖定支援]
+
ONTAP S3 支援物件鎖定 API 命令、可讓您保護寫入 ONTAP S3 的資料、避免遭到刪除
使用標準 S3 API 命令、並確保重要資料在適當的時間內受到保護。

* xref:../assign-tags-cluster-task.html[叢集] 和 xref:../assign-tags-volumes-task.html[Volume] 標記
+
將中繼資料標記新增至磁碟區和叢集、這些標記會隨著資料從內部部署移至雲端並進行反轉。





== ONTAP 9.13.1 重點介紹

ONTAP 9.13.1 在防勒索軟體保護、一致性群組、服務品質、租戶容量管理等領域提供全新且增強的功能。如需新功能與增強功能的完整清單、請參閱 xref:whats-new-9131.adoc[ONTAP 9.13.1 的新功能]。

* 自主勒索軟體保護（ ARP ）增強功能：
+
** xref:../anti-ransomware/enable-default-task.adoc[自動啟用]
+
有了 ONTAP 9.13.1 、 ARP 在擁有足夠的學習資料後、就會自動從訓練模式移轉至正式作業模式、免除管理員在 30 天之後啟用的需求。

** xref:../anti-ransomware/use-cases-restrictions-concept.html#multi-admin-verification-with-volumes-protected-with-arp[多重管理驗證支援]
+
多重管理驗證支援 ARP 停用命令、確保沒有單一管理員可以停用 ARP 、將資料暴露於可能的勒索軟體攻擊之中。

** xref:../anti-ransomware/use-cases-restrictions-concept.html[FlexGroup 支援]
+
從 ONTAP 9.13.1 開始， ARP 支援 FlexGroup 磁碟區。ARP 可以監控並保護橫跨叢集中多個磁碟區和節點的 FlexGroup 磁碟區，甚至是最大的資料集都能使用 ARP 來保護。



* xref:../consistency-groups/index.html[系統管理程式中一致性群組的效能與容量監控]
+
效能與容量監控可針對每個一致性群組提供詳細資料、讓您在應用程式層級快速識別及報告潛在問題、而不只是在資料物件層級。

* xref:../volumes/manage-svm-capacity.html[租戶容量管理]
+
多租戶客戶和服務供應商可以設定每個 SVM 的容量限制、讓租戶能夠執行自助服務佈建、而不會有一個租戶在叢集上過度使用容量的風險。

* xref:../performance-admin/adaptive-policy-template-task.html[服務品質的天花板和地板]
+
ONTAP 9.13.1 可讓您將磁碟區、 LUN 或檔案等物件分組、並指派 QoS 上限（最大 IOPs ）或最低 IOPs （最低 IOPs ）、以改善應用程式效能期望。





== ONTAP 9.12.1 重點摘要

ONTAP 9.12.1 在安全強化、保留、效能等領域提供全新且增強的功能。如需新功能與增強功能的完整清單、請參閱 xref:whats-new-9121.adoc[ONTAP 9.12.1 的新功能]。

* xref:../snaplock/snapshot-lock-concept.html[防竄改快照]
+
有了 SnapLock 技術，您就可以保護快照，避免在來源或目的地上遭到刪除。

+
保護主要與次要儲存設備上的快照、避免勒索軟體攻擊者或惡意系統管理員刪除、進而保留更多恢復點。

* xref:../anti-ransomware/index.html[自主勒索軟體保護（ ARP ）增強功能]
+
根據主要儲存設備已完成的篩選模式、立即在次要儲存設備上啟用智慧型自主勒索軟體保護。

+
容錯移轉之後、立即識別二級儲存設備上可能發生的勒索軟體攻擊。系統會立即擷取開始受到影響的資料，並通知系統管理員，協助阻止攻擊並加強還原。

* xref:../nas-audit/plan-fpolicy-event-config-concept.html[FPolicy]
+
單鍵啟動 ONTAP FPolicy 可自動封鎖已知的惡意檔案簡化的啟動有助於防範使用一般已知副檔名的典型勒索軟體攻擊。

* xref:../system-admin/ontap-implements-audit-logging-concept.html[安全強化：防竄改保留記錄]
+
ONTAP 中的防竄改保留記錄可確保遭入侵的系統管理員帳戶不會隱藏惡意動作。如果系統不知情、就無法變更或刪除管理員和使用者歷程記錄。

+
記錄並稽核所有管理動作、無論來源為何、都能保證擷取所有影響資料的動作。每當系統稽核記錄遭到竄改、以任何方式通知系統管理員變更時、就會產生警示。

* xref:../authentication/setup-ssh-multifactor-authentication-task.html[安全強化：擴充的多因素驗證]
+
多重驗證（ MFA ） for CLI （ SSH ）支援 Yib金 鑰實體硬體權杖裝置、確保攻擊者無法使用遭竊的認證或遭入侵的用戶端系統來存取 ONTAP 系統。採用 System Manager 的 MFA 支援 Cisco Duo 。

* 檔案物件雙重性（多重傳輸協定存取）
+
檔案物件雙重性可讓原生 S3 傳輸協定讀取和寫入相同資料來源的存取權、而該資料來源已具有 NAS 傳輸協定存取權。您可以將儲存設備同時存取為檔案或來自相同資料來源的物件、不需要複製資料來搭配不同的傳輸協定（ S3 或 NAS ）使用、例如使用物件資料的分析。

* xref:../flexgroup/manage-flexgroup-rebalance-task.html[重新平衡FlexGroup]
+
如果 FlexGroup 成分變得不平衡、 FlexGroup 可以不中斷地從重新平衡和管理
CLI 、 REST API 和 System Manager 。為了達到最佳效能、 FlexGroup 中的成員應平均分配其使用的容量。

* 儲存容量增強功能
+
WAFL 空間保留空間已大幅減少，每個聚合最多可提供 40 TiB 更多可用容量。





== ONTAP 9.11.1 重點摘要

ONTAP 9.11.1 在安全性、保留、效能等方面提供全新且增強的功能。如需新功能與增強功能的完整清單、請參閱 xref:whats-new-9111.adoc[ONTAP 9.11.1 的新功能]。

* xref:../multi-admin-verify/index.html[多管理員驗證]
+
多重管理驗證（ MAV ）是業界首創的原生驗證方法，需要多項核准，才能執行敏感的管理工作，例如刪除快照或磁碟區。MAV 實作所需的核准可防止惡意攻擊和資料意外變更。

* xref:../anti-ransomware/index.html[增強的自主勒索軟體保護功能]
+
自主勒索軟體保護（ ARP ）利用機器學習功能、以更精細的方式偵測勒索軟體威脅、讓您能夠快速識別威脅、並在發生資料外洩時加速恢復。

* xref:../flexgroup/supported-unsupported-config-concept.html#features-supported-beginning-with-ontap-9-11-1[SnapLock Compliance for FlexGroup Volumes]
+
透過 WORM 檔案鎖定保護資料、保護電子設計自動化、媒體與娛樂等工作負載的多 PB 資料集、讓資料無法變更或刪除。

* xref:../flexgroup/fast-directory-delete-asynchronous-task.html[非同步目錄刪除]
+
使用 ONTAP 9.11.1 時、檔案刪除會發生在 ONTAP 系統的背景中、讓您輕鬆刪除大型目錄、同時消除對主機 I/O 的效能和延遲影響

* xref:../s3-config/index.html[S3 增強功能]
+
利用 ONTAP 簡化及擴充 S3 的物件資料管理功能、在儲存區層級提供額外的 API 端點和物件版本設定、讓物件的多個版本儲存在同一個儲存區中。

* System Manager增強功能
+
System Manager 支援進階功能、可最佳化儲存資源並改善稽核管理。這些更新包括管理和設定儲存集合體的增強功能、增強系統分析的可見度、以及 FAS 系統的硬體視覺化。





== ONTAP 9.10.1 重點摘要

ONTAP 9.10.1 在安全強化、效能分析、 NVMe 傳輸協定支援和物件儲存備份選項等領域提供全新且增強的功能。如需新功能與增強功能的完整清單、請參閱 xref:whats-new-9101.adoc[ONTAP 9.10.1 的新功能]。

* xref:../anti-ransomware/index.html[自主勒索軟體保護]
+
自動勒索軟體保護會自動建立磁碟區快照，並在偵測到異常活動時向管理員發出警示，讓您能夠快速偵測勒索軟體攻擊並更快地恢復。

* System Manager增強功能
+
System Manager 除了提供與 Active IQ 數位顧問（也稱為數位顧問）、 BlueXP  和憑證管理的新整合、還能自動下載磁碟、機櫃、服務處理器的韌體更新。這些增強功能可簡化管理並維持業務持續運作。

* xref:../concept_nas_file_system_analytics_overview.html[檔案系統分析增強功能]
+
檔案系統分析提供額外的遙測功能、可識別檔案共用中的重要檔案、目錄和使用者、讓您識別工作負載效能問題、以改善資源規劃和 QoS 實作。

* xref:../nvme/support-limitations.html[AFF 系統的 NVMe over TCP （ NVMe / TCP ）支援]
+
當您在現有的乙太網路上使用 NVMe / TCP 時、可在 AFF 系統上為企業 SAN 和現代工作負載達成高效能並降低 TCO 。

* xref:../nvme/support-limitations.html[NVMe over Fibre Channel （ NVMe / FC ）支援 NetApp FAS 系統]
+
在混合式陣列上使用 NVMe / FC 傳輸協定、即可統一移轉至 NVMe 。

* xref:../s3-snapmirror/index.html[物件儲存的原生混合雲備份]
+
您可以選擇物件儲存目標來保護 ONTAP S3 資料。使用 SnapMirror 複寫功能、將 StorageGRID 的內部部署儲存設備備份到 Amazon S3 的雲端、或是 NetApp AFF 和 FAS 系統上的另一個 ONTAP S3 儲存區。

* xref:../flexcache/global-file-locking-task.html[使用 FlexCache 進行全域檔案鎖定]
+
使用 FlexCache 進行全域檔案鎖定、以確保在原始伺服器的來源檔案更新期間、快取位置的檔案一致性。這項增強功能可針對需要增強鎖定的工作負載、在原始伺服器對快取關係中啟用專屬的檔案讀取鎖定。





== ONTAP 9.9.1 重點摘要

ONTAP 9.91.1 在儲存效率、多因素驗證、災難恢復等領域提供全新且增強的功能。如需新功能與增強功能的完整清單、請參閱 xref:whats-new-991.adoc[ONTAP 9.9.1 的新功能]。

* 增強的 CLI 遠端存取管理安全性
+
支援 SHA512 和 SSH A512 密碼雜湊功能、可保護系統管理員帳戶認證免受試圖取得系統存取權的惡意攻擊者攻擊。

* https://docs.netapp.com/us-en/ontap-metrocluster/install-ip/task_install_and_cable_the_mcc_components.html["MetroCluster IP 增強功能：支援 8 節點叢集"^]
+
新的上限是前一上限的兩倍、可支援 MetroCluster 組態、並可持續提供資料可用度。

* xref:../snapmirror-active-sync/index.html[SnapMirror 主動同步]
+
針對 NAS 工作負載的大型資料容器、提供更多複寫選項以進行備份和災難恢復。

* xref:../san-admin/storage-virtualization-vmware-copy-offload-concept.html[提高 SAN 效能]
+
為單一 LUN 應用程式（例如 VMware 資料存放區）提供高達四倍的 SAN 效能、讓您在 SAN 環境中達到高效能。

* xref:../task_cloud_backup_data_using_cbs.html[混合雲的全新物件儲存選項]
+
可將 StorageGRID 用作 NetApp Cloud Backup Service 的目的地、以簡化並自動化內部部署 ONTAP 資料的備份作業。



.後續步驟
* xref:../upgrade/prepare.html[升級至最新版的 ONTAP]
* xref:../upgrade/when-to-upgrade.html[我應該何時升級 ONTAP ？]

