---
permalink: fabricpool/attach-cloud-tier-aggregate-task.html 
sidebar: sidebar 
keywords: attaching, cloud, tier, aggregate 
summary: 將物件存放區設定為雲端層之後、您可以將其附加FabricPool 至物件存放區、以指定要使用的集合體。在更新版本的版本中、您也可以附加包含合格的等量組成物的集合體。ONTAP FlexGroup 
---
= 將雲端層附加至集合體
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將物件存放區設定為雲端層之後、您可以將其附加FabricPool 至物件存放區、以指定要使用的集合體。在更新版本的版本中、您也可以附加包含合格的等量組成物的集合體。ONTAP FlexGroup

當您使用ONTAP CLI來設定用於FabricPool 執行效能提升的Aggregate時、Aggregate必須已經存在。

[NOTE]
====
當您使用System Manager來設定適用於FabricPool 整個過程的Aggregate時、您可以建立Aggregate並將其設定FabricPool 為同時用於整個過程。

====
.步驟
. *選用*：若要查看磁碟區中有多少資料處於非使用中狀態、請依照中的步驟進行 link:determine-data-inactive-reporting-task.html["使用非作用中資料報告來判斷Volume中有多少資料處於非作用中狀態"]。
+
查看某個Volume中有多少資料處於非作用中狀態、有助於決定哪些Aggregate可用於FabricPool 哪些用途。

. 使用「儲存區Aggregate object-store attach」命令、將物件存放區附加至Aggregate。
+
如果Aggregate從未搭配FabricPool 使用、而且它包含現有的磁碟區、則會將預設的「僅快照」分層原則指派給磁碟區。

+
[listing]
----
cluster1::> storage aggregate object-store attach -aggregate myaggr
-object-store-name Amazon01B1
----
+
您可以使用「allow-flexgroup」「true」選項來附加包含FlexGroup 大量組成的集合體。

. 顯示物件存放區資訊、並使用「儲存區Aggregate object-store show」命令來驗證附加的物件存放區是否可用。
+
[listing]
----
cluster1::> storage aggregate object-store show

Aggregate    Object Store Name    Availability State
---------    -----------------    ------------------
myaggr       Amazon01B1           available
----

