---
permalink: fabricpool/commands-manage-aggregates-reference.html 
sidebar: sidebar 
keywords: commands, managing, aggregates, storage aggregate object-store config 
summary: 您可以使用儲存Aggregate object-store命令來管理物件存放區FabricPool 、以利執行。您可以使用儲存Aggregate命令來管理Aggregate for FabricPool the功能。您可以使用Volume命令來管理Volume FabricPool 以供使用。 
---
= 用於管理 FabricPool 資源的 ONTAP 指令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `storage aggregate object-store` 管理 FabricPool 物件存放區的命令。您可以使用 `storage aggregate` 用於管理 FabricPool 集合體的命令。您可以使用 `volume` 用於管理 FabricPool 磁碟區的命令。

|===


| 如果您想要... | 使用此命令： 


 a| 
定義物件存放區的組態、ONTAP 以便供物件庫存取
 a| 
`storage aggregate object-store config create`



 a| 
修改物件存放區組態屬性
 a| 
`storage aggregate object-store config modify`



 a| 
重新命名現有的物件存放區組態
 a| 
`storage aggregate object-store config rename`



 a| 
刪除物件存放區的組態
 a| 
`storage aggregate object-store config delete`



 a| 
顯示物件存放區組態清單
 a| 
`storage aggregate object-store config show`



 a| 
將第二個物件存放區附加到新FabricPool 的或現有的用作鏡像的物件存放區
 a| 
`storage aggregate object-store mirror` 使用 `-aggregate` 和 `-name` 管理權限層級中的參數



 a| 
從現有FabricPool 的鏡射中移除物件儲存鏡射
 a| 
`storage aggregate object-store unmirror` 使用 `-aggregate` 和 `-name` 管理權限層級中的參數



 a| 
監控FabricPool 鏡射重新同步狀態
 a| 
`storage aggregate object-store show-resync-status`



 a| 
顯示FabricPool 鏡射詳細資料
 a| 
`storage aggregate object-store show`



 a| 
升級物件存放區鏡射、以FabricPool 取代鏡射組態中的主要物件存放區
 a| 
`storage aggregate object-store modify` 使用 `-aggregate` 管理權限層級中的參數



 a| 
測試物件存放區的延遲和效能、而不將物件存放區附加至集合體
 a| 
`storage aggregate object-store profiler start` 使用 `-object-store-name` 和 `-node` 進階權限層級中的參數



 a| 
監控物件存放區檔案探查器狀態
 a| 
`storage aggregate object-store profiler show` 使用 `-object-store-name` 和 `-node` 進階權限層級中的參數



 a| 
物件存放區檔案程式執行時、請將其中止
 a| 
`storage aggregate object-store profiler abort` 使用 `-object-store-name` 和 `-node` 進階權限層級中的參數



 a| 
將物件存放區附加至Aggregate以使用FabricPool 物件
 a| 
`storage aggregate object-store attach`



 a| 
將物件存放區附加至包含FlexGroup 使用FabricPool 功能的功能區的集合體
 a| 
`storage aggregate object-store attach` 使用 `allow-flexgroup` `true`



 a| 
顯示附加至啟用FabricPool之Aggregate的物件存放區詳細資料
 a| 
`storage aggregate object-store show`



 a| 
顯示分層掃描所使用的Aggregate完整臨界值
 a| 
`storage aggregate object-store show` 使用 `-fields tiering-fullness-threshold` 進階權限層級中的參數



 a| 
顯示附加至啟用FabricPool之Aggregate的物件存放區空間使用率
 a| 
`storage aggregate object-store show-space`



 a| 
啟用非作用中的資料報告功能、以報告未用於FabricPool 支援的Aggregate
 a| 
`storage aggregate modify` 使用 `-is-inactive-data-reporting-enabled true` 參數



 a| 
顯示是否在Aggregate上啟用非作用中資料報告
 a| 
`storage aggregate show` 使用 `-fields is-inactive-data-reporting-enabled` 參數



 a| 
顯示有關集合體內使用者資料的冷量資訊
 a| 
`storage aggregate show-space` 使用 `-fields performance-tier-inactive-user-data,performance-tier-inactive-user-data-percent` 參數



 a| 
建立FabricPool 一個供使用的Volume、包括指定下列項目：

* 分層原則
* 分層最低冷卻期（適用於 `snapshot-only` 或 `auto` 分層原則）

 a| 
`volume create`

* 您可以使用 `-tiering-policy` 指定分層原則的參數。
* 您可以使用 `-tiering-minimum-cooling-days` 進階權限層級中的參數、可指定分層的最低冷卻週期。




 a| 
修改Volume以FabricPool 供使用、包括修改下列項目：

* 分層原則
* 分層最低冷卻期（適用於 `snapshot-only` 或 `auto` 分層原則）

 a| 
`volume modify`

* 您可以使用 `-tiering-policy` 指定分層原則的參數。
* 您可以使用 `-tiering-minimum-cooling-days` 進階權限層級中的參數、可指定分層的最低冷卻週期。




 a| 
顯示FabricPool 與Volume相關的資訊、包括：

* 分層最低冷卻週期
* 多少使用者資料是冷的

 a| 
`volume show`

* 您可以使用 `-fields tiering-minimum-cooling-days` 進階權限層級中的參數、可顯示分層的最低冷卻週期。
* 您可以使用 `-fields performance-tier-inactive-user-data,performance-tier-inactive-user-data-percent` 顯示冷的使用者資料量的參數。




 a| 
將Volume移入FabricPool 或移出
 a| 
`volume move start` 您可以使用 `-tiering-policy` 可選參數，用於指定卷的分層策略。



 a| 
修改恢復未參考空間的臨界值FabricPool （重組臨界值）以供參考
 a| 
`storage aggregate object-store modify` 使用 `-unreclaimed-space-threshold` 進階權限層級中的參數



 a| 
修改集合體在分層掃描開始分層資料以供FabricPool 使用之前的百分比已滿量臨界值

在本機層達到98%容量之前、將冷資料持續分層至雲端層。FabricPool
 a| 
`storage aggregate object-store modify` 使用 `-tiering-fullness-threshold` 進階權限層級中的參數



 a| 
顯示回收未參考空間以供FabricPool 參考的臨界值
 a| 
`storage aggregate object-store show` 或 `storage aggregate object-store show-space` 命令 `-unreclaimed-space-threshold` 進階權限層級中的參數

|===