---
permalink: fabricpool/create-volume-task.html 
sidebar: sidebar 
keywords: creating, volume, fabricpool, tiering, policy, policies, create, snap shot, snapshot, aggregate, flexgroup, cloud retrieval 
summary: 當您建立FabricPool 一個供使用的Volume時、您可以選擇指定分層原則。如果未指定分層原則、則建立的磁碟區會使用預設的純快照分層原則。對於具有純快照或自動分層原則的磁碟區、您也可以指定分層的最小冷卻週期。 
---
= 在啟用 FabricPool 的 ONTAP Aggregate 上建立磁碟區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以FabricPool 直接在啟用FabricPool的Aggregate中建立新磁碟區、或是將現有磁碟區從另一個Aggregate移至啟用FabricPool的Aggregate、藉此將磁碟區新增至支援功能。

當您建立FabricPool 一個供使用的Volume時、您可以選擇指定分層原則。如果未指定分層原則、則建立的磁碟區會使用預設值 `snapshot-only` 分層原則。適用於具有的 Volume `snapshot-only` 或 `auto` 分層原則、您也可以指定分層的最低冷卻週期。

.您需要的產品
* 設定要使用的 Volume `auto` 分層原則或指定分層最低冷卻週期需要 ONTAP 9.4 或更新版本。
* 使用本解決方法需要使用更新版本的版本。FlexGroup ONTAP
* 設定要使用的 Volume `all` 分層原則需要 ONTAP 9.6 或更新版本。
* 設定要使用的 Volume `-cloud-retrieval-policy` 參數需要 ONTAP 9.8 或更新版本。


.步驟
. 使用為 FabricPool 建立新的 Volume `volume create` 命令。
+
** 。 `-tiering-policy` 選用參數可讓您指定磁碟區的分層原則。
+
您可以指定下列分層原則之一：

+
*** `snapshot-only` （預設）
*** `auto`
*** `all`
*** `backup` （已過時）
*** `none`
+
link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["分層原則的類型FabricPool"]



** 。 `-cloud-retrieval-policy` 選用參數可讓具有進階權限層級的叢集管理員覆寫由分層原則控制的預設雲端移轉或擷取行為。
+
您可以指定下列其中一個雲端擷取原則：

+
*** `default`
+
分層原則會決定哪些資料會被拉回、因此雲端資料擷取不會有任何變更 `default` 雲端擷取原則。這表示這種行為與ONTAP 9.8之前版本相同：

+
**** 如果分層原則是 `none` 或 `snapshot-only`接著、「預設」表示任何用戶端導向的資料讀取都會從雲端層移至效能層。
**** 如果分層原則是 `auto`，則會拉出任何用戶端驅動的隨機讀取，但不會拉出連續讀取。
**** 如果分層原則是 `all` 然後、不會從雲端層擷取任何用戶端導向的資料。


*** `on-read`
+
所有用戶端導向的資料讀取都會從雲端層提取到效能層。

*** `never`
+
不會將用戶端導向的資料從雲端層提取到效能層

*** `promote`
+
**** 用於分層原則 `none`、所有雲端資料都會從雲端層移至效能層
**** 用於分層原則 `snapshot-only`、所有作用中的檔案系統資料都會從雲端層移至效能層。




** 。 `-tiering-minimum-cooling-days` 進階權限層級中的選用參數可讓您指定使用的磁碟區的分層最低冷卻期間 `snapshot-only` 或 `auto` 分層原則。
+
從功能表9.8開始ONTAP 、您可以指定2到183之間的值、以供分層的最低冷卻天數使用。如果您使用ONTAP 的是9.8之前的版本、則可在分層的最低冷卻天數中指定介於2到63之間的值。





.建立FabricPool 一套供參考的Volume範例
以下範例在啟用FabricPool的「myFabricPool」Aggregate中建立一個名為「myvol1」的Volume。分層原則設為 `auto` 而且分層最低冷卻時間設為 45 天：

[listing]
----
cluster1::*> volume create -vserver myVS -aggregate myFabricPool
-volume myvol1 -tiering-policy auto -tiering-minimum-cooling-days 45
----
.相關資訊
link:../flexgroup/index.html["資料區管理FlexGroup"]
