---
permalink: fabricpool/create-mirror-task.html 
sidebar: sidebar 
keywords: creating, fabricpool, mirror 
summary: 若要建立FabricPool 一個鏡射鏡、您可以將兩個物件存放區附加到單FabricPool 一的物件庫。您可以FabricPool 將第二個物件存放區附加到現有的單一物件存放區FabricPool 的物件保存區、或是建立新的單一物件存放FabricPool 區的更新組態、然後將第二個物件存放區附加到其中、藉此建立一個鏡射鏡射。您也可以在FabricPool 不完整的組態上建立鏡像MetroCluster 。 
---
= 建立 ONTAP FabricPool 鏡射
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要建立FabricPool 一個鏡射鏡、您可以將兩個物件存放區附加到單FabricPool 一的物件庫。您可以FabricPool 將第二個物件存放區附加到現有的單一物件存放區FabricPool 的物件保存區、或是建立新的單一物件存放FabricPool 區的更新組態、然後將第二個物件存放區附加到其中、藉此建立一個鏡射鏡射。您也可以在FabricPool 不完整的組態上建立鏡像MetroCluster 。

.您需要的產品
* 您必須已使用建立兩個物件存放區 `storage aggregate object-store config` 命令。
* 如果您要在FabricPool 不完整的組態上建立鏡像MetroCluster ：
+
** 您必須已經設定MetroCluster 並設定了這個功能
** 您必須已在所選叢集上建立物件存放區組態。
+
如果您是FabricPool 在雙叢集上建立MetroCluster 以供使用的物件鏡射、則必須在兩個叢集上建立物件儲存組態。

** 如果您不使用內部部署物件存放區進行MetroCluster 不完整的組態設定、則應確保存在下列其中一種情況：
+
*** 物件存放區位於不同的可用性區域
*** 物件存放區已設定為將物件複本保留在多個可用度區域中
+
link:setup-object-stores-mcc-task.html["設定物件存放區以FabricPool 供在MetroCluster 一個不確定的組態中使用"]







.關於這項工作
您用於FabricPool 鏡射的物件存放區必須與主要物件存放區不同。

建立FabricPool 一個鏡像的程序與MetroCluster 建立一個不同時適用於整個過程的不同時適用於整個過程的非MetroCluster組態相同。

.步驟
. 如果您不使用現有的 FabricPool 組態，請使用命令將物件存放區附加至本機層，以建立新的物件存放區 `storage aggregate object-store attach`。
+
此範例會將物件存放區附加至本機層，以建立新的 FabricPool 。

+
[listing]
----
cluster1::> storage aggregate object-store attach -aggregate aggr1 -name my-store-1
----
. 使用命令將第二個物件存放區附加至本機層 `storage aggregate object-store mirror`。
+
此範例將第二個物件存放區附加至本機層，以建立 FabricPool 鏡像。

+
[listing]
----
cluster1::> storage aggregate object-store mirror -aggregate aggr1 -name my-store-2
----

