---
permalink: fabricpool/enable-disable-aggressive-read-ahead-task.html 
sidebar: sidebar 
keywords: creating, volume, fabricpool, aggressive read ahead, enable, on prem, on premises, disable 
summary: 從 ONTAP 9.14.1 開始、您可以在 FabricPools 中啟用和停用主動式預先讀取模式、以支援媒體和娛樂、例如影片串流工作負載。 
---
= 在 FabricPool 中啟用 ONTAP Volume 以執行主動式讀取
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9 ． 14.1 開始，您可以在 FabricPools 中的磁碟區上啟用和停用主動式預先讀取模式。所有支援 FabricPool 的內部部署平台上的 ONTAP 9.14.1 均提供主動式預先讀取模式。此功能預設為停用。

當主動式預先讀取設為 _disabled_ 時， FabricPool 只會讀取用戶端應用程式所需的檔案區塊，而不需要讀取整個檔案。這可能會導致網路流量降低，尤其是大型 GB 和 TB 大小的檔案。在磁碟區上啟用主動式預先讀取會關閉此功能，而 FabricPool 會從物件存放區中預先讀取整個檔案，增加取得處理量並減少用戶端讀取檔案的延遲。依預設，當階層式資料依序讀取時，會保持冷態，不會寫入本機層。

積極的預先讀取功能可提高網路效率，以提升階層式資料的效能。

.關於這項工作
。 `aggressive-readahead-mode` 命令有兩個選項：

* `none`：預先讀取已停用。
* `file_prefetch`：系統會先將整個檔案讀取到用戶端應用程式的記憶體中。


.開始之前
* 您應該是叢集或 SVM 管理員。
* 您必須處於進階權限層級。




== 在磁碟區建立期間啟用主動式預先讀取模式

.步驟
. 將權限層級設為進階：
+
[source, cli]
----
set -privilege advanced
----
. 建立磁碟區並啟用主動式預先讀取模式：
+
[source, cli]
----
volume create -volume <volume name>  -aggressive-readahead-mode <none|file_prefetch>
----
+
以下範例建立一個名為 vol1 的 Volume 、其中啟用檔案預先擷取選項的主動式預先讀取功能：

+
[listing]
----
volume create -volume vol1 -aggressive-readahead-mode file_prefetch
----




== 停用主動預先讀取模式

.步驟
. 將權限層級設為進階：
+
[source, cli]
----
set -privilege advanced
----
. 停用主動式預先讀取模式：
+
[source, cli]
----
volume modify -volume <volume name>  -aggressive-readahead-mode none
----
+
以下範例修改名為 vol1 的磁碟區、以停用主動式預先讀取模式：

+
[listing]
----
volume modify -volume vol1 -aggressive-readahead-mode none
----




== 檢視磁碟區上的主動式預先讀取模式

.步驟
. 將權限層級設為進階：
+
[source, cli]
----
set -privilege advanced
----
. 檢視積極的預先讀取模式：
+
[source, cli]
----
volume show -fields aggressive-readahead-mode
----

