---
permalink: fabricpool/move-volume-task.html 
sidebar: sidebar 
keywords: aggregate, local tier, moving, volume, fabricpool, fabric pool, tiering, policy, policies, block, capacity, cold data, 
summary: 當您將Volume移至FabricPool 物件時、您可以選擇透過移動來指定或變更Volume的分層原則。從功能不活動的資料報告功能開始、當您移動非FabricPool Volume時、會使用熱圖來讀取可分層區塊、並將冷資料移至該目的地的容量層。ONTAP FabricPool FabricPool 
---
= 將磁碟區移至啟用 FabricPool 的 ONTAP 本機層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您將Volume移至FabricPool 物件時、您可以選擇透過移動來指定或變更Volume的分層原則。從功能不活動的資料報告功能開始、當您移動非FabricPool Volume時、會使用熱圖來讀取可分層區塊、並將冷資料移至該目的地的容量層。ONTAP FabricPool FabricPool


NOTE: 在 ONTAP 9.7 之前，系統管理員使用術語 _Aggregate _ 來描述 _ 本機層 _ 。無論您的 ONTAP 版本為何， ONTAP CLI 都會使用術語 _Aggregate 。若要深入瞭解本機階層，請參閱link:../disks-aggregates/index.html["磁碟和本機層"]。

.開始之前
您必須瞭解變更分層原則、可能會影響資料冷卻及移至雲端層所需的時間。

link:tiering-policies-concept.html#what-happens-to-the-tiering-policy-when-you-move-a-volume["當您移動磁碟區時、分層原則會發生什麼事"]

.關於這項工作
如果非 FabricPool 磁碟區已啟用非作用中資料報告功能，當您將具有分層原則的磁碟區或 `snapshot-only`移 `auto`至 FabricPool 時， FabricPool 會從熱圖檔案讀取溫度可控區塊，當非 FabricPool 磁碟區上的分層原則設為時 `auto`， FabricPool 會使用該溫度將冷資料直接移至 FabricPool 目的地上的容量層。

您不應該使用 `-tiering-policy` 如果您使用的是 ONTAP 9.8 、而您想要 FabricPools 使用非作用中的資料報告資訊、將資料直接移至容量層、則可在 Volume 上移動選項。使用此選項會導致FabricPools忽略溫度資料、改為遵循ONTAP 發行版本更新至版本更新版本的動作。

.步驟
. 使用 `volume move start` 將 Volume 移至 FabricPool 的命令。
+
。 `-tiering-policy` 選用參數可讓您指定磁碟區的分層原則。

+
您可以指定下列分層原則之一：

+
** `snapshot-only` （預設）
** `auto`
** `all`
** `none`
 +
link:tiering-policies-concept.html#types-of-fabricpool-tiering-policies["分層原則的類型FabricPool"]




.將Volume移至FabricPool 不全的範例
以下範例將「 VS1 」 SVM 的名為「 myvol2 」的磁碟區移至 FabricPool 啟用 FabricPool 的本機層。磁碟區已明確設定為使用 `none`分層原則：

[listing]
----
cluster1::> volume move start -vserver vs1 -volume myvol2
-destination-aggregate dest_FabricPool -tiering-policy none
----