---
permalink: fabricpool/move-volume-task.html 
sidebar: sidebar 
keywords: aggregate, local tier, moving, volume, fabricpool, fabric pool, tiering, policy, policies, block, capacity, cold data, 
summary: 請務必瞭解磁碟區移動如何與 FabricPool 搭配運作，因為本機層，附加雲端層和磁碟區（磁碟區分層原則）所發生的變更都會對功能造成重大影響。 
---
= 將磁碟區移至啟用 FabricPool 的 ONTAP 本機層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
A link:../volumes/move-volume-task.html["Volume搬移"] 是 ONTAP 在不中斷營運的情況下，將磁碟區從一個本機層（來源）移至另一個（目的地）的方式。雖然最常見的原因是硬體生命週期管理，叢集擴充和負載平衡，但由於各種原因，可以執行磁碟區移動。

請務必瞭解磁碟區移動如何與 FabricPool 搭配運作，因為本機層，附加雲端層和磁碟區（磁碟區分層原則）所發生的變更都會對功能造成重大影響。


NOTE: 在 ONTAP 9.7 之前，系統管理員使用術語 _Aggregate _ 來描述 _ 本機層 _ 。無論您的 ONTAP 版本為何， ONTAP CLI 都會使用術語 _Aggregate 。若要深入瞭解本機階層，請參閱link:../disks-aggregates/index.html["磁碟和本機層"]。



== 目的地本端層

如果 Volume Move 的目的地本端層沒有附加的雲端層，則儲存在雲端層的來源磁碟區上的資料會寫入目的地本端層的本端層。

從 ONTAP 9.8 開始，當磁碟區已啟用時link:determine-data-inactive-reporting-task.html["非作用中資料報告"]， FabricPool 會使用磁碟區的熱圖，立即將冷資料排入佇列，以便在寫入目的地本機層時立即開始分層。

在 ONTAP 9.8 之前，將磁碟區移至另一個本機層會重設本機層區塊的閒置期間。例如，使用自動磁碟區分層原則的磁碟區，若本機層上的資料已停用 20 天，但尚未分層，則在磁碟區移動後，資料的溫度將會重設為 0 天。



== 最佳化的 Volume 搬移

從 ONTAP 9.6 開始，如果 Volume Move 的目的地本端層使用與來源本端層相同的貯體，則儲存在該貯體中的來源 Volume 上的資料不會移回本端層。階層式資料會保持靜止，只有熱資料需要從一個本機層移至另一個層級。這項最佳化的 Volume 搬移可大幅提升網路效率。

例如，300TB 最佳化磁碟區移動意味著即使 300TB 冷資料從一個本地層移動到另一個本地層，也不會觸發對物件儲存的 300TB 讀取和 300TB 寫入。

未最佳化的 Volume 搬移會產生額外的網路和運算流量（讀取 / 取得和寫入 / 放置），增加對 ONTAP 叢集和物件存放區的需求，可能會在分層到公有物件存放區時增加成本。

[NOTE]
====
部分組態與最佳化的 Volume 移動不相容：

* 在磁碟區移動期間變更分層原則
* 使用不同加密金鑰的來源和目的地本機層
* FlexClone Volume
* FlexClone 父磁碟區
* MetroCluster （支援 ONTAP 9.8 及更新版本中最佳化的 Volume 搬移）
* 非同步的 FabricPool 鏡射貯體


====
如果 Volume Move 的目的地本端層有附加的雲端層，則儲存在雲端層的來源磁碟區上的資料會先寫入目的地本端層的本端層。如果此方法適用於磁碟區的分層原則，則會寫入目的地本機層的雲端層。

先將資料寫入本機層，可改善磁碟區移動的效能，並縮短轉換時間。如果在執行磁碟區移動時未指定磁碟區分層原則，則目的地磁碟區會使用來源磁碟區的分層原則。

如果在執行磁碟區移動時指定不同的分層原則，則會使用指定的分層原則建立目的地磁碟區，而且不會最佳化磁碟區移動。



=== Volume 中繼資料

無論磁碟區移動是否經過最佳化，ONTAP 都會儲存大量有關所有資料（包括本機資料和分層資料）的位置、儲存效率、權限、使用模式等的元資料。元資料始終保留在本地層，不會進行分層。當磁碟區從一個本機層移至另一個層時，也需要將此資訊移至目的地本機層。



=== 持續時間

磁碟區移動仍然需要時間才能完成，並且預期優化卷移動將花費與移動等量非分層資料大約相同的時間。

重要的是要理解 `volume move show`命令並不代表從雲層移動的資料的吞吐量，而是代表在本地更新的捲資料。


NOTE: 在 SVM DR 關係中，來源和目的地磁碟區必須使用相同的分層原則。

.步驟
. 使用 `volume move start`命令將磁碟區從來源本機層移至目的地本機層。


.移動 Volume 的範例
以下範例將名為 SVM 的 `vs1`磁碟區移 `myvol2`至 `dest_FabricPool`啟用 FabricPool 的本機層。

[listing]
----
cluster1::> volume move start -vserver vs1 -volume myvol2
-destination-aggregate dest_FabricPool
----