---
permalink: fabricpool/replace-existing-object-store-mirror-task.html 
sidebar: sidebar 
keywords: replacing, existing, object, store, fabricpool, mirror 
summary: 您可以使用FabricPool 鏡射技術、將一個物件存放區換成另一個物件存放區。新的物件存放區不需要使用與原始物件存放區相同的雲端供應商。 
---
= 以 ONTAP FabricPool 鏡像取代現有的物件存放區
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用FabricPool 鏡射技術、將一個物件存放區換成另一個物件存放區。新的物件存放區不需要使用與原始物件存放區相同的雲端供應商。

.關於這項工作
您可以使用使用不同雲端供應商的物件存放區來取代原始物件存放區。例如、您的原始物件存放區可能會使用AWS做為雲端供應商、但您可以將它取代為使用Azure做為雲端供應商的物件存放區、反之亦然。不過、新的物件存放區必須保留與原始物件相同的物件大小。

.步驟
. 使用將新的物件存放區新增至現有的 FabricPool 、以建立 FabricPool 鏡射 `storage aggregate object-store mirror` 命令。
+
[listing]
----
cluster1::> storage aggregate object-store mirror -aggregate aggr1 -object-store-name my-AZURE-store
----
. 使用監控鏡像重新同步狀態 `storage aggregate object-store show-resync-status` 命令。
+
[listing]
----
cluster1::> storage aggregate object-store show-resync-status -aggregate aggr1
----
+
[listing]
----
                                                  Complete
      Aggregate    Primary          Mirror        Percentage
      ---------    -----------      ----------    ----------
      aggr1        my-AWS-store     my-AZURE-store     40%
----
. 使用驗證鏡像是否同步 `storage aggregate object-store> show -fields mirror-type,is-mirror-degraded` 命令。
+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type,is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AWS-store        primary           -
               my-AZURE-store      mirror          false
----
. 使用將主要物件存放區與鏡射物件存放區交換 `storage aggregate object-store modify` 命令。
+
[listing]
----
cluster1::> storage aggregate object-store modify -aggregate aggr1 -object-store-name my-AZURE-store -mirror-type primary
----
. 使用顯示 FabricPool 鏡像的詳細資料 `storage aggregate object-store show -fields mirror-type,is-mirror-degraded` 命令。
+
此範例顯示FabricPool 有關鏡射的資訊、包括鏡射是否降級（非同步）。

+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type, is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AZURE-store      primary           -
               my-AWS-store        mirror          false
----
. 使用移除 FabricPool 鏡像 `storage aggregate object-store unmirror` 命令。
+
[listing]
----
cluster1::> storage aggregate object-store unmirror -aggregate aggr1
----
. 使用驗證 FabricPool 是否回到單一物件存放區組態中 `storage aggregate object-store show -fields mirror-type,is-mirror-degraded` 命令。
+
[listing]
----
cluster1::> storage aggregate object-store show -fields mirror-type,is-mirror-degraded
----
+
[listing]
----
aggregate      object-store-name mirror-type     is-mirror-degraded
-------------- ----------------- ------------- ------------------
aggr1          my-AZURE-store      primary           -
----


.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-mirror.html["儲存聚合物件儲存鏡像"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-modify.html["儲存聚合物件儲存修改"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-show-resync-status.html["儲存聚合物件儲存顯示重新同步狀態"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-show.html["儲存聚合物件儲存顯示"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-unmirror.html["儲存聚合物件儲存取消鏡像"^]

