---
permalink: fabricpool/setup-aws-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, aws, s3, cloud tier 
summary: 如果您執行的是 ONTAP 9.2 或更新版本、您可以將 Amazon S3 設定為 FabricPool 的雲端層級。如果您執行的是 ONTAP 9.5 或更新版本、您可以為 FabricPool 設定 Amazon 商業雲端服務（ C2S ）。 
---
= 將 Amazon S3 設定為雲端層級
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您執行的是 ONTAP 9.2 或更新版本、您可以將 Amazon S3 設定為 FabricPool 的雲端層級。如果您執行的是 ONTAP 9.5 或更新版本、您可以為 FabricPool 設定 Amazon 商業雲端服務（ C2S ）。

.搭配 FabricPool 使用 Amazon S3 的考量事項
* 您可能需要FabricPool 一個不必要的授權。
+
** 新訂購AFF 的功能不只提供10 TB的可用容量、FabricPool 更能使用功能。
+
如果您在 AFF 系統上需要額外容量、在非 AFF 系統上使用 Amazon S3 、或是從現有叢集升級、則需要 link:https://docs.netapp.com/us-en/ontap/fabricpool/install-license-aws-azure-ibm-task.html["不含授權FabricPool"]。

+
如果FabricPool 您是第一次為現有叢集訂購供應功能、FabricPool 則可取得10 TB可用容量的不含指令碼授權。



* 建議 ONTAP 用來連線 Amazon S3 物件伺服器的 LIF 位於 10 Gbps 連接埠上。
* 在支援下列Amazon S3儲存課程的支援對象包括：AFF FAS ONTAP Select FabricPool
+
** Amazon S3 Standard
** Amazon S3 Standard -非常用存取（標準- IA）
** Amazon S3 One Zone -不常用存取（單一區域- IA）
** Amazon S3智慧分層
** Amazon商業雲端服務
** 從 ONTAP 9.11.1 開始、 Amazon S3 Glacier 即時擷取（ FabricPool 不支援 Glacier Flexible Retrieval 或 Glacier Deep Archive ）
+
https://aws.amazon.com/s3/storage-classes/["Amazon Web Services 文件： Amazon S3 儲存課程"]



+
如需未列出的儲存類別資訊、請聯絡您的銷售代表。

* 在支援的基礎上、支援從通用SSD（gp2）和Amazon Elastic Block Store（EBS）的Througs Optimized HDD（ST1）Volume進行分層。Cloud Volumes ONTAP FabricPool


.步驟
. 使用指定 Amazon S3 組態資訊 `storage aggregate object-store config create` 命令 `-provider-type` `AWS_S3` 參數。
+
** 您可以使用 `-auth-type` `CAP` 取得 C2S 存取認證的參數。
+
當您使用時 `-auth-type` `CAP` 參數、您必須使用 `-cap-url` 指定完整 URL 以要求 C2S 存取的暫存認證的參數。

** 。 `storage aggregate object-store config create` 如果 ONTAP 無法使用提供的資訊存取 Amazon S3 、則命令會失敗。
** 您可以使用 `-access-key` 此參數可指定存取金鑰、以將要求授權給 Amazon S3 物件存放區。
** 您可以使用 `-secret-password` 此參數可指定密碼（秘密存取金鑰）、以驗證對 Amazon S3 物件存放區的要求。
** 如果 Amazon S3 密碼已變更、您應該立即更新儲存在 ONTAP 中的對應密碼。
+
如此一來、 ONTAP 就能在不中斷的情況下存取 Amazon S3 中的資料。

+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name my_aws_store -provider-type AWS_S3
-server s3.amazonaws.com -container-name my-aws-bucket
-access-key DXJRXHPXHYXA9X31X3JX
----
+
[listing]
----
cluster1::> storage aggregate object-store config create -object-store-name my_c2s_store -provider-type AWS_S3 -auth-type CAP -cap-url https://123.45.67.89/api/v1/credentials?agency=XYZ&mission=TESTACCT&role=S3FULLACCESS -server my-c2s-s3server-fqdn -container my-c2s-s3-bucket
----


. 使用顯示並驗證 Amazon S3 組態資訊 `storage aggregate object-store config show` 命令。
+
。 `storage aggregate object-store config modify` 命令可讓您修改 FabricPool 的 Amazon S3 組態資訊。


