---
permalink: fabricpool/setup-ontap-s3-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, ontap s3, cloud tier 
summary: 如果您執行ONTAP 的是版本不支援的版本、您可以將ONTAP S3設定為FabricPool 適用於該產品的雲端層。 
---
= 將ONTAP S3設定為雲端層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您執行ONTAP 的是版本不支援的版本、您可以將ONTAP S3設定為FabricPool 適用於該產品的雲端層。

.您需要的產品
您必須在ONTAP 遠端叢集上擁有該伺服器的名稱及其相關生命的IP位址。

[NOTE]
====
用戶端應用程式會將伺服器名稱用作完整網域名稱（ FQDN ）。在 ONTAP 之外，請確認 DNS 記錄指向正在使用的 SVM 資料生命。

====
本機叢集上必須有叢集間的LIF。

link:../s3-config/create-intercluster-lifs-remote-fabricpool-tiering-task.html["建立叢集間的生命體、以進行遠端FabricPool 分層"]

.關於這項工作
支援以更新版本的功能、在更新版本的更新版本中、啟用Ss3伺服器的負載平衡ONTAP 功能。ONTAP當伺服器的主機名稱解析為多個IP位址時ONTAP 、即可建立用戶端連線、並傳回所有IP位址（最多16個IP位址）。建立連線時、會以循環配置資源的方式來取用IP位址。

.程序
您可以使用ONTAP 支援功能的支援功能、將S3設定為FabricPool 適用於各種功能的雲端層ONTAP 、以供使用。ONTAP

[role="tabbed-block"]
====
.系統管理員
--
. 按一下「*儲存設備>層級>新增雲端層*」、然後選取ONTAP 「物件儲存區供應商」「S3」。
. 填寫要求的資訊。
. 如果您想要建立雲端鏡射、請按一下*「Add as FabricPool Swirror *（*新增為鏡射*）」。


利用這個鏡射技術、您可以順暢地更換資料儲存區、並確保在發生災難時能夠取得您的資料。FabricPool

--
.CLI
--
. 將S3伺服器和LIF的項目新增至DNS伺服器。
+
|===


| 選項 | 說明 


 a| 
*如果您使用外部DNS伺服器*
 a| 
將S3伺服器名稱和IP位址提供給DNS伺服器管理員。



 a| 
*如果您使用本機系統的DNS主機表*
 a| 
輸入下列命令：

`dns host create -vserver svm_name -address ip_address -hostname s3_server_name`

|===
. 使用指定 ONTAP S3 組態資訊 `storage aggregate object-store config create` 命令 `-provider-type` `ONTAP_S3` 參數。
+
** 。 `storage aggregate object-store config create` 如果本機 ONTAP 系統無法使用所提供的資訊存取 ONTAP S3 伺服器、則命令會失敗。
** 您可以使用 `-access-key` 指定存取金鑰以授權 ONTAP S3 伺服器的要求。
** 您可以使用 `-secret-password` 指定密碼（秘密存取金鑰）以驗證 ONTAP S3 伺服器的要求。
** 如果ONTAP 變更了「S3伺服器密碼」、您應該立即更新儲存在本機ONTAP 版的BIOS系統中的對應密碼。
+
如此一來、ONTAP 即可在不中斷的情況下、存取位於現象中心S3物件儲存區的資料。

** 將參數設定 `-is-certificate-validation-enabled`為 `false`停用 ONTAP S3 的憑證檢查。使用(`-is-certificate-validation-enabled true`第三方憑證授權單位的簽署憑證是建議的最佳做法。


+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name myS3 -provider-type ONTAP_S3 -server myS3server
-container-name myS3container -access-key myS3key
-secret-password myS3pass
----
. 使用顯示和驗證 ONTAP S3 組態資訊 `storage aggregate object-store config show` 命令。
+
。 `storage aggregate object-store config modify` 命令可讓您修改 `ONTAP_S3` FabricPool 組態資訊。



--
====