---
permalink: fabricpool/setup-ibm-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, ibm cloud, object storage, cloud tier 
summary: 如果您執行ONTAP 的是版本不符合要求的9.5或更新版本、可以將IBM Cloud Object Storage設定為FabricPool 適用的雲端層。 
---
= 將IBM Cloud Object Storage設定為雲端層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您執行ONTAP 的是版本不符合要求的9.5或更新版本、可以將IBM Cloud Object Storage設定為FabricPool 適用的雲端層。

.搭配FabricPool 使用IBM Cloud Object Storage的考量事項
* 您可能需要FabricPool 一個不必要的授權。
+
新訂購AFF 的功能不只提供10 TB的可用容量、FabricPool 更能使用功能。如果您在 AFF 系統上需要額外容量、在非 AFF 系統上使用 IBM 雲端物件儲存設備、或是從現有叢集升級、則需要link:../fabricpool/install-license-aws-azure-ibm-task.html["不含授權FabricPool"]。

+
如果FabricPool 您是第一次為現有叢集訂購供應功能、FabricPool 則可取得10 TB可用容量的不含指令碼授權。

* 建議ONTAP 將用於連接IBM Cloud物件伺服器的LIF放在10 Gbps連接埠上。


.步驟
. 使用指定 IBM Cloud Object Storage 組態資訊 `storage aggregate object-store config create` 命令 `-provider-type` `IBM_COS` 參數。
+
** 。 `storage aggregate object-store config create` 如果 ONTAP 無法使用提供的資訊存取 IBM Cloud Object Storage 、則命令會失敗。
** 您可以使用 `-access-key` 此參數可指定存取金鑰、以將要求授權給 IBM Cloud Object Storage 物件存放區。
** 您可以使用 `-secret-password` 此參數可指定密碼（秘密存取金鑰）、以驗證對 IBM Cloud Object Storage 物件儲存區的要求。
** 如果IBM Cloud Object Storage密碼已變更、您應該ONTAP 立即更新儲存在BIOS中的對應密碼。
+
如此一來、即可讓支援中心在不中斷的情況下存取IBM Cloud Object Storage中的資料。ONTAP



+
[listing]
----
storage aggregate object-store config create
-object-store-name MyIBM -provider-type IBM_COS
-server s3.us-east.objectstorage.softlayer.net
-container-name my-ibm-cos-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. 使用顯示及驗證 IBM Cloud Object Storage 組態資訊 `storage aggregate object-store config show` 命令。
+
。 `storage aggregate object-store config modify` 命令可讓您修改 FabricPool 的 IBM 雲端物件儲存組態資訊。


