---
permalink: fabricpool/setup-azure-blob-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, azure blob storage, cloud, cloud tier 
summary: 如果您執行ONTAP 的是S得9.4或更新版本、您可以設定Azure Blob Storage for the Cloud做FabricPool 為供使用的雲端層。 
---
= 設定Azure Blob Storage做為雲端層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您執行ONTAP 的是S得9.4或更新版本、您可以設定Azure Blob Storage for the Cloud做FabricPool 為供使用的雲端層。

.搭配FabricPool 使用Microsoft Azure Blob儲存設備的考量事項
* 您可能需要FabricPool 一個不必要的授權。
+
新訂購AFF 的功能不只提供10 TB的可用容量、FabricPool 更能使用功能。如果AFF 您需要更多的功能來支援整個系統、如果您在非AFF系統上使用Azure Blob Storage、或是從現有的叢集升級、則需要FabricPool 一份不含任何功能的授權。

+
如果FabricPool 您是第一次為現有叢集訂購供應功能、FabricPool 則可取得10 TB可用容量的不含指令碼授權。

* 如果您搭配使用Azure Blob Storage搭配使用、則不需要取得此功能的證書。FabricPool Cloud Volumes ONTAP
* 用來連接Azure Blob儲存物件伺服器的LIF ONTAP 必須位於10 Gbps連接埠上。
* 目前不支援Azure Stack（內部部署Azure服務）FabricPool 。
* 在Microsoft Azure Blob Storage的帳戶層級、FabricPool 不支援熱儲存層和冷儲存層。
+
不支援Blob層級分層。FabricPool也不支援分層至Azure的歸檔儲存層。



目前不支援Azure Stack（內部部署Azure服務）FabricPool 。

.步驟
. 使用「sorage Aggregate object-store config create」命令搭配「供應商類型」「Azure _Cloud」參數、指定Azure Blob儲存組態資訊。
+
** 如果無法使用提供的資訊存取Azure Blob Storage、則「儲存Aggregate object-store config create」命令會失敗ONTAP 。
** 您可以使用「-azure-account」參數來指定Azure Blob Storage帳戶。
** 您可以使用「-azure-Private金鑰」參數來指定存取金鑰、以驗證Azure Blob Storage的要求。
** 如果Azure Blob儲存設備密碼已變更、您應ONTAP 立即更新儲存在BIOS中的對應密碼。
+
如此一來、即可讓支援中心在不中斷的情況下存取Azure Blob Storage中的資料。ONTAP



+
[listing]
----
cluster1::> storage aggregate object-store config create
-object-store-name MyAzure -provider-type Azure_Cloud
-server blob.core.windows.net -container-name myAzureContainer
-azure-account myAzureAcct -azure-private-key myAzureKey
----
. 使用「儲存Aggregate object-store config show」命令來顯示及驗證Azure Blob儲存設備組態資訊。
+
「儲存Aggregate object-store config modify」命令可讓您修改Azure Blob儲存設備組態資訊FabricPool 、以供參考。


