---
permalink: fabricpool/setup-google-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting up, google cloud storage, cloud tier 
summary: 如果您執行ONTAP 的是32個以上版本的版本、您可以將Google Cloud Storage設定為FabricPool 適用的雲端層。 
---
= 將 Google Cloud Storage 設定為 ONTAP FabricPool 雲端層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您執行ONTAP 的是32個以上版本的版本、您可以將Google Cloud Storage設定為FabricPool 適用的雲端層。



== 搭配FabricPool 使用Google Cloud Storage的其他考量事項

* 分層至 Google Cloud Storage 時需要 A link:https://bluexp.netapp.com/cloud-tiering["BlueXP 分層授權"]。
* 建議ONTAP 將用於連接Google Cloud Storage物件伺服器的LIF放在10 Gbps連接埠上。
* 在支援下列Google Cloud Object儲存課程的支援對象包括：AFF FAS ONTAP Select FabricPool
+
** Google Cloud Multi-Regional
** Google Cloud區域
** Google Cloud Nearline
** Google Cloud Coldline
+
https://cloud.google.com/storage/docs/storage-classes["Google Cloud：儲存類別"^]





.步驟
. 使用指定 Google Cloud Storage 組態資訊 `storage aggregate object-store config create` 命令 `-provider-type` `GoogleCloud` 參數。
+
** 。 `storage aggregate object-store config create` 如果 ONTAP 無法使用所提供的資訊存取 Google Cloud Storage 、則命令會失敗。
** 您可以使用 `-access-key` 此參數可指定存取金鑰、以將要求授權給 Google Cloud Storage 物件儲存區。
** 如果Google Cloud Storage密碼已變更、您應該ONTAP 立即更新儲存在BIOS中的對應密碼。
+
如此一來、即可讓支援中心在不中斷的情況下存取Google Cloud Storage中的資料。ONTAP



+
[listing]
----
storage aggregate object-store config create my_gcp_store_1 -provider-type GoogleCloud  -container-name my-gcp-bucket1 -access-key GOOGAUZZUV2USCFGHGQ511I8
----
. 使用顯示和驗證 Google Cloud Storage 組態資訊 `storage aggregate object-store config show` 命令。
+
。 `storage aggregate object-store config modify` 命令可讓您修改 FabricPool 的 Google 雲端儲存組態資訊。



.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-create.html["儲存聚合物件儲存配置創建"^]
* link:https://docs.netapp.com/us-en/ontap-cli/snapmirror-object-store-config-modify.html["儲存聚合物件儲存配置修改"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-aggregate-object-store-config-show.html["儲存聚合物件儲存配置顯示"^]

