---
permalink: fabricpool/setup-alibaba-object-storage-cloud-tier-task.html 
sidebar: sidebar 
keywords: setting, up, alibaba cloud object, storage, cloud tier 
summary: 如果您執行ONTAP 的是32個以上版本的版本、您可以將Alibaba Cloud Object Storage設定為FabricPool 適用於此功能的雲端層。 
---
= 設定Alibaba雲端物件儲存為雲端層
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果您執行ONTAP 的是32個以上版本的版本、您可以將Alibaba Cloud Object Storage設定為FabricPool 適用於此功能的雲端層。

.搭配FabricPool 使用Alibaba Cloud Object Storage的考量事項
* 您可能需要FabricPool 一個不必要的授權。
+
新訂購AFF 的功能不只提供10 TB的可用容量、FabricPool 更能使用功能。如果AFF 您需要更多的功能來支援整個系統、如果您在非AFF系統上使用Alibaba Cloud Object Storage、或是從現有的叢集升級、則需要FabricPool 使用一套不中斷的授權。

* 在支援下列Alibaba物件儲存服務課程的支援對象系統和功能區上：AFF FAS ONTAP Select FabricPool
+
** Alibaba物件儲存服務標準
** Alibaba物件儲存服務不常存取
+
https://www.alibabacloud.com/help/doc-detail/51374.htm["Alibaba Cloud：儲存課程簡介"]





請聯絡您的NetApp銷售代表、以取得未列出的儲存類別相關資訊。

.步驟
. 使用指定 Alibaba Cloud Object Storage 組態資訊 `storage aggregate object-store config create` 命令 `-provider-type` `AliCloud` 參數。
+
** 。 `storage aggregate object-store config create` 如果 ONTAP 無法使用所提供的資訊存取 Alibaba 雲端物件儲存設備、則命令會失敗。
** 您可以使用 `-access-key` 此參數可指定存取金鑰、以授權對 Alibaba Cloud Object Storage 物件儲存區的要求。
** 如果Alibaba Cloud Object Storage密碼已變更、您應該ONTAP 立即更新儲存在效益管理系統中的對應密碼。
+
這樣做可ONTAP 讓支援中心在不中斷的情況下存取Alibaba Cloud Object Storage中的資料。



+
[listing]
----
storage aggregate object-store config create my_ali_oss_store_1
-provider-type AliCloud -server oss-us-east-1.aliyuncs.com
-container-name my-ali-oss-bucket -access-key DXJRXHPXHYXA9X31X3JX
----
. 使用顯示並驗證 Alibaba Cloud Object Storage 組態資訊 `storage aggregate object-store config show` 命令。
+
。 `storage aggregate object-store config modify` 命令可讓您修改 FabricPool 的 Alibaba 雲端物件儲存組態資訊。


