---
permalink: fabricpool/tiering-policies-concept.html 
sidebar: sidebar 
keywords: understanding, fabricpool, tiering, policies, types, modify, volume, clone, cloud migration 
summary: 利用此類分層原則、您可以在資料變熱或變冷時、在不同階層之間有效率地搬移資料。FabricPool瞭解分層原則有助於選擇符合儲存管理需求的正確原則。 
---
= 關於FabricPool 分層原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
利用此類分層原則、您可以在資料變熱或變冷時、在不同階層之間有效率地搬移資料。FabricPool瞭解分層原則有助於選擇符合儲存管理需求的正確原則。



== 分層原則的類型FabricPool

根據熱（作用中）或冷（非作用中）的Volume「'Temperat'」（Volume「溫度」）、將資料區塊移至雲端層的時機或時機取決於該使用者資料區塊。FabricPool FabricPool經常存取時、Volume「'Temperature」會增加、而非存取時則會減少。有些分層原則具有相關的分層最低冷卻時間、可設定FabricPool 使用者資料在某個部分中必須保持非作用中狀態的時間、以便將資料視為「冷」並移至雲端層。

在Volume層級指定了分層原則。FabricPool共有四種選項可供選擇：

* 「純快照」分層原則（預設）會將未與作用中檔案系統相關聯之Volume Snapshot複本的使用者資料區塊移至雲端層。
+
分層的最低冷卻時間為2天。您可以在「Volume create」和「Volume modify」命令的進階權限層級中、使用「分層最小冷卻天數」參數來修改分層最小冷卻期間的預設設定。有效值為2至183天、使用ONTAP NetApp 9.8及更新版本。如果您使用ONTAP 的版本早於9.8、有效值為2至63天。

* 「自動」分層原則僅支援ONTAP 於更新版本的版本中使用、可將Snapshot複本和作用中檔案系統中的冷使用者資料區塊移至雲端層。
+
預設的分層最低冷卻時間為31天、適用於作用中檔案系統和Snapshot複本的整個磁碟區。

+
您可以在「Volume create」和「Volume modify」命令的進階權限層級中、使用「分層最小冷卻天數」參數來修改分層最小冷卻期間的預設設定。有效值為2至183天。

* 「All（全部）」分層原則僅支援ONTAP 於支援的版本僅適用於支援的版本9.6及更新版本、可將作用中檔案系統和Snapshot複本中的所有使用者資料區塊移至雲端層。它取代了「備份」分層原則。
+
分層最短冷卻時間不適用、因為資料會在分層掃描執行時立即移動雲端層、而且您無法修改設定。

* 「無」分層原則會將磁碟區的資料保留在效能層、使其無法移至雲端層。
+
分層最低散熱週期不適用、因為資料永遠不會移至雲端層、而且您無法修改設定。



「volume show」命令輸出顯示磁碟區的分層原則。從未使用FabricPool 過的磁碟區會在輸出中顯示「無」分層原則。



== 當您修改FabricPool 完一份Volume的分層原則時、會發生什麼情況

您可以執行「Volume modify」（磁碟區修改）作業來修改磁碟區的分層原則。您必須瞭解變更分層原則、可能會影響資料冷卻及移至雲端層所需的時間。

* 如果將分層原則從「僅快照」或「無」變更為「自動」、ONTAP 即使使用者的資料區塊先前不符合雲端層資格、也會導致執行中檔案系統中的使用者資料區塊傳送到雲端層。
* 將分層原則從另一個原則變更為「ALL」、會導致ONTAP 下次執行分層掃描時、將作用中檔案系統和Snapshot複本中的所有使用者區塊移至雲端層。
+
不允許將區塊移回效能層。

* 將分層原則從「自動」變更為「僅快照」或「無」、並不會導致已移至雲端層的作用中檔案系統區塊移回效能層。
+
需要磁碟區讀取、才能將資料移回效能層。

* 每當您變更磁碟區的分層原則時、分層的最小冷卻期間會重設為原則的預設值。




== 當您移動磁碟區時、分層原則會發生什麼事

* 除非您明確指定不同的分層原則、否則當磁碟區移入和移出啟用FabricPool的Aggregate時、就會保留其原始分層原則。
+
不過、分層原則只有在磁碟區位於啟用FabricPool的Aggregate中時才會生效。

* 除非您為目的地指定不同的分層原則、否則Volume的「分層最低-冷卻天數」參數的現有值會隨著Volume一起移動。
+
如果您指定不同的分層原則、則該磁碟區會使用該原則的預設分層最小冷卻期間。無論目的地FabricPool 是否為不實、都會發生這種情況。

* 您可以跨集合體移動磁碟區、同時修改分層原則。
* 在「Volume Move」（Volume Move）作業涉及「自動」分層政策時、您應該特別注意。
+
假設來源與目的地均為啟用FabricPool的Aggregate、下表摘要說明「Volume Move」作業的結果、其中涉及與「自動」相關的原則變更：

+
|===


| 當您移動具有分層原則的磁碟區時... | 您也可以透過移至...來變更分層原則。 | 然後在磁碟區移動之後... 


 a| 
全部
 a| 
「自動」
 a| 
所有資料都會移至效能層級。



 a| 
僅使用「napshot」、「nONE」或「自動」
 a| 
「自動」
 a| 
資料區塊會移至目的地的同一層、如同先前位於來源。



 a| 
「自動」或「全部」
 a| 
「純快照」
 a| 
所有資料都會移至效能層級。



 a| 
「自動」
 a| 
全部
 a| 
所有使用者資料都會移至雲端層。



 a| 
「純快照」、「自動」或「全部」
 a| 
無
 a| 
所有資料都保留在效能層級。

|===




== 當您複製磁碟區時、分層原則會發生什麼變化

* 從ONTAP 功能性的問題9.8開始、複製磁碟區一律會從父磁碟區繼承分層原則和雲端擷取原則。
+
在版本低於ONTAP 發行版的版本中、複本會繼承父版本的分層原則、但父版本具有「ALL」分層原則時除外。

* 如果父磁碟區具有「Never」雲端擷取原則、則其實體磁碟區必須具有「Never」雲端擷取原則或「all」分層原則、以及對應的雲端擷取原則「Default」。
* 除非父Volume雲端擷取原則具有「Never」（永不）的雲端擷取原則、否則無法將其變更為「Never」（永不）。


當您複製磁碟區時、請謹記下列最佳實務做法：

* 複本的「分層原則」選項和「分層最低冷卻天數」選項、只會控制複本特有之區塊的分層行為。因此、我們建議在父FlexVol 級不知道上使用分層設定、以移動相同數量的資料、或移動的資料量少於任何複本
* 父FlexVol 實體上的雲端擷取原則應移動相同數量的資料、或移動的資料應大於任何實體複本的擷取原則




== 分層原則如何與雲端移轉搭配運作

利用分層原則來控制實體雲端資料擷取、根據讀取模式從雲端層擷取資料至效能層。FabricPool讀取模式可以是連續的或隨機的。

下表列出各原則的分層原則和雲端資料擷取規則。

|===


| 分層原則 | 擷取行為 


 a| 
無
 a| 
連續和隨機讀取



 a| 
純快照
 a| 
連續和隨機讀取



 a| 
自動
 a| 
隨機讀取



 a| 
全部
 a| 
無資料擷取

|===
從ONTAP 功能不完整的9.8開始、雲端移轉控制「雲端擷取原則」選項會覆寫分層原則所控制的預設雲端移轉或擷取行為。

下表列出支援的雲端擷取原則及其擷取行為。

|===


| 雲端擷取原則 | 擷取行為 


 a| 
預設
 a| 
分層原則決定哪些資料應該取回、因此雲端資料擷取不會有「預設」、「雲端擷取原則」的變更。無論託管的Aggregate類型為何、此原則都是任何Volume的預設值。



 a| 
讀取時
 a| 
所有用戶端導向的資料讀取都會從雲端層移至效能層。



 a| 
永不
 a| 
不會將用戶端導向的資料從雲端層提取到效能層



 a| 
促銷
 a| 
* 對於分層原則「無、」、所有雲端資料都會從雲端層提取到效能層
* 若為分層原則、會擷取「僅限快照」的主動式檔案管理系統資料。


|===