---
permalink: fabricpool/tiering-policies-concept.html 
sidebar: sidebar 
keywords: understanding, fabricpool, tiering, policies, types, modify, volume, clone, cloud migration 
summary: 利用此類分層原則、您可以在資料變熱或變冷時、在不同階層之間有效率地搬移資料。FabricPool瞭解分層原則有助於選擇符合儲存管理需求的正確原則。 
---
= 關於 ONTAP 中的 FabricPool 分層原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
利用此類分層原則、您可以在資料變熱或變冷時、在不同階層之間有效率地搬移資料。FabricPool瞭解分層原則有助於選擇符合儲存管理需求的正確原則。



== 分層原則的類型FabricPool

根據熱（作用中）或冷（非作用中）的Volume「'Temperat'」（Volume「溫度」）、將資料區塊移至雲端層的時機或時機取決於該使用者資料區塊。FabricPool FabricPool經常存取時、Volume「'Temperature」會增加、而非存取時則會減少。有些分層原則具有相關的分層最低冷卻時間、可設定FabricPool 使用者資料在某個部分中必須保持非作用中狀態的時間、以便將資料視為「冷」並移至雲端層。

當區塊被識別為冷區後、就會標示為符合分層的資格。  每日背景分層掃描會尋找冷區塊。當從同一個磁碟區收集足夠的 4KB 區塊時、這些區塊會串連成一個 4 MB 物件、並根據磁碟區分層原則移至雲端層。

[NOTE]
====
使用的磁碟區中的資料 `all` 分層原則會立即標記為冷、並儘快開始分層至雲端層。它不需要等待每日分層掃描執行。

====
您可以使用[`volume object-store tiering show`命令來檢視 FabricPool Volume 的分層狀態。深入瞭解 ONTAP 命令參照中的連結： https://docs 。 NetApp 。 ONTAP - CLI/volume-object-store-tiering-show.html[`volume object-store tiering show`^] 命令。

在Volume層級指定了分層原則。FabricPool共有四種選項可供選擇：

* 。 `snapshot-only` 分層原則（預設）會將與作用中檔案系統無關的 Volume Snapshot 複本使用者資料區塊移至雲端層。
+
分層的最低冷卻時間為2天。您可以使用修改分層最低冷卻期間的預設設定 `-tiering-minimum-cooling-days` 的進階權限層級中的參數 `volume create` 和 `volume modify` 命令。有效值為2至183天、使用ONTAP NetApp 9.8及更新版本。如果您使用ONTAP 的版本早於9.8、有效值為2至63天。

* 。 `auto` 分層原則僅在 ONTAP 9.4 及更新版本上受支援、可將 Snapshot 複本和作用中檔案系統中的冷使用者資料區塊移至雲端層。
+
預設的分層最低冷卻時間為31天、適用於作用中檔案系統和Snapshot複本的整個磁碟區。

+
您可以使用修改分層最低冷卻期間的預設設定 `-tiering-minimum-cooling-days` 的進階權限層級中的參數 `volume create` 和 `volume modify` 命令。有效值為2至183天。

* 。 `all` 僅 ONTAP 9.6 及更新版本支援分層原則、可將作用中檔案系統和 Snapshot 複本中的所有使用者資料區塊移至雲端層。它取代了 `backup` 分層原則。
+
。 `all` 磁碟區分層原則不應用於具有正常用戶端流量的讀取 / 寫入磁碟區。

+
分層最低冷卻週期不適用、因為資料會在分層掃描執行後立即移至雲端層、而且您無法修改設定。

* 。 `none` 分層原則可將磁碟區的資料保留在效能層、不會冷移至雲端層。
+
將分層原則設為 `none` 防止新的分層。先前移至雲端層的 Volume 資料會保留在雲端層、直到變熱為止、並自動移回本機層為止。

+
分層最低散熱週期不適用、因為資料永遠不會移至雲端層、而且您無法修改設定。

+
當磁碟區中的冷區塊設為分層原則時 `none` 讀取後、會變熱並寫入本機層。



。 `volume show` 命令輸出會顯示磁碟區的分層原則。FabricPool 從未使用過的 Volume 會顯示 `none` 輸出中的分層原則。



== 當您修改FabricPool 完一份Volume的分層原則時、會發生什麼情況

您可以執行來修改磁碟區的分層原則 `volume modify` 營運。您必須瞭解變更分層原則、可能會影響資料冷卻及移至雲端層所需的時間。

* 變更分層原則 `snapshot-only` 或 `none` 至 `auto` 讓 ONTAP 將已冷卻的作用中檔案系統中的使用者資料區塊傳送至雲端層、即使這些使用者資料區塊先前不符合雲端層的資格。
* 將分層原則變更為 `all` 從另一個原則、 ONTAP 會盡快將作用中檔案系統和 Snapshot 複本中的所有使用者區塊移至雲端。在 ONTAP 9.8 之前、區塊需要等到下一次分層掃描執行。
+
不允許將區塊移回效能層。

* 變更分層原則 `auto` 至 `snapshot-only` 或 `none` 不會將已移至雲端層的作用中檔案系統區塊移回效能層。
+
需要磁碟區讀取、才能將資料移回效能層。

* 每當您變更磁碟區的分層原則時、分層的最小冷卻期間會重設為原則的預設值。




== 當您移動磁碟區時、分層原則會發生什麼事

* 除非您明確指定不同的分層原則、否則當磁碟區移入和移出啟用FabricPool的Aggregate時、就會保留其原始分層原則。
+
不過、分層原則只有在磁碟區位於啟用FabricPool的Aggregate中時才會生效。

* 的現有值 `-tiering-minimum-cooling-days` 除非您為目的地指定不同的分層原則、否則 Volume 的參數會隨著 Volume 一起移動。
+
如果您指定不同的分層原則、則該磁碟區會使用該原則的預設分層最小冷卻期間。無論目的地FabricPool 是否為不實、都會發生這種情況。

* 您可以跨集合體移動磁碟區、同時修改分層原則。
* 您應該特別注意 `volume move` 操作涉及 `auto` 分層原則。
+
假設來源和目的地都是啟用 FabricPool 的集合體、下表摘要說明的結果 `volume move` 涉及相關原則變更的作業 `auto`：

+
|===


| 當您移動具有分層原則的磁碟區時... | 您也可以透過移至...來變更分層原則。 | 然後在磁碟區移動之後... 


 a| 
`all`
 a| 
`auto`
 a| 
所有資料都會移至效能層級。



 a| 
`snapshot-only`、 `none`或 `auto`
 a| 
`auto`
 a| 
資料區塊會移至目的地的同一層、如同先前位於來源。



 a| 
`auto` 或 `all`
 a| 
`snapshot-only`
 a| 
所有資料都會移至效能層級。



 a| 
`auto`
 a| 
`all`
 a| 
所有使用者資料都會移至雲端層。



 a| 
`snapshot-only`,`auto` 或 `all`
 a| 
`none`
 a| 
所有資料都保留在效能層級。

|===




== 當您複製磁碟區時、分層原則會發生什麼變化

* 從ONTAP 功能性的問題9.8開始、複製磁碟區一律會從父磁碟區繼承分層原則和雲端擷取原則。
+
在早於 ONTAP 9.8 的版本中、除非父實體具有、否則複本會從父實體繼承分層原則 `all` 分層原則。

* 如果父磁碟區有 `never` 雲端擷取原則、其複製磁碟區必須具有 `never` 雲端擷取原則或 `all` 分層原則、以及對應的雲端擷取原則 `default`。
* 無法將父 Volume 雲端擷取原則變更為 `never` 除非所有的複本磁碟區都有雲端擷取原則 `never`。


當您複製磁碟區時、請謹記下列最佳實務做法：

* 。 `-tiering-policy` 選項與 `tiering-minimum-cooling-days` 複製選項只會控制複製特有之區塊的分層行為。因此、我們建議在父FlexVol 級不知道上使用分層設定、以移動相同數量的資料、或移動的資料量少於任何複本
* 父FlexVol 實體上的雲端擷取原則應移動相同數量的資料、或移動的資料應大於任何實體複本的擷取原則




== 分層原則如何與雲端移轉搭配運作

利用分層原則來控制實體雲端資料擷取、根據讀取模式從雲端層擷取資料至效能層。FabricPool讀取模式可以是連續的或隨機的。

下表列出各原則的分層原則和雲端資料擷取規則。

|===


| 分層原則 | 擷取行為 


 a| 
無
 a| 
連續和隨機讀取



 a| 
純快照
 a| 
連續和隨機讀取



 a| 
自動
 a| 
隨機讀取



 a| 
全部
 a| 
無資料擷取

|===
從 ONTAP 9.8 開始、就是雲端移轉控制 `cloud-retrieval-policy` 選項會覆寫由分層原則控制的預設雲端移轉或擷取行為。

下表列出支援的雲端擷取原則及其擷取行為。

|===


| 雲端擷取原則 | 擷取行為 


 a| 
預設
 a| 
分層原則會決定應將哪些資料取回、因此雲端資料擷取不會有「預設」的變更,`" `cloud-retrieval-policy`。無論託管的Aggregate類型為何、此原則都是任何Volume的預設值。



 a| 
讀取時
 a| 
所有用戶端導向的資料讀取都會從雲端層移至效能層。



 a| 
永不
 a| 
不會將用戶端導向的資料從雲端層提取到效能層



 a| 
促銷
 a| 
* 對於分層原則「無、」、所有雲端資料都會從雲端層提取到效能層
* 若為分層原則、會擷取「僅限快照」的主動式檔案管理系統資料。


|===
如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。
