---
permalink: fabricpool/tiering-policies-concept.html 
sidebar: sidebar 
keywords: understanding, fabricpool, tiering, policies, types, modify, volume, clone, cloud migration 
summary: 利用此類分層原則、您可以在資料變熱或變冷時、在不同階層之間有效率地搬移資料。FabricPool瞭解分層原則有助於選擇符合儲存管理需求的正確原則。 
---
= FabricPool 磁碟區分層原則
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
FabricPool 磁碟區分層原則決定磁碟區中哪些資料符合分層條件，而分層最低冷卻天數參數則決定何時將資料視為非使用中且符合分層條件。

[NOTE]
====
存取控制清單 (ACL)、目錄結構和中繼資料永遠不會分層，始終保留在本機層。

====
每日後台分層掃描會尋找冷資料塊。當從同一磁碟區收集到足夠多的 4KB 資料區塊後，這些資料區塊會合併成一個 4MB 的物件，並根據磁碟區分層原則移至雲端層。

了解分層原則的運作方式，有助於您選擇符合儲存管理需求的原則。



[[volume-tiering-policy-options]]
== Volume 分層原則選項

預設情況下，磁碟區會使用 None 磁碟區分層原則。唯一的例外是在 FabricPool 彙總空間上新建立的 FlexVol 磁碟區，其使用 Snapshot-Only 磁碟區分層原則。

您可以使用 `volume object-store tiering show`命令來檢視 FabricPool Volume 的分層狀態。如link:https://docs.netapp.com/us-en/ontap-cli//volume-object-store-tiering-show.html["指令參考資料ONTAP"^]需詳細 `volume object-store tiering show`資訊，請參閱。

在Volume層級指定了分層原則。FabricPool共有四種選項可供選擇：



[[snapshot-only]]
=== 僅快照

The `snapshot-only` 分層原則會對不再與作用中檔案系統關聯的快照資料進行分層。預設情況下，快照需要兩天不活動才能符合分層條件。大多數資料保護排程按小時或按天執行，並在分層之前先在本機讀取資料。

您可以在  `volume create` 與  `volume modify` 命令的進階權限等級中，使用  `-tiering-minimum-cooling-days` 參數修改分層最小冷卻期的預設設定。使用 ONTAP 9.8 及更新版本時，有效值為 2 到 183 天。如果您使用的是早於 9.8 的 ONTAP 版本，則有效值為 2 到 63 天。

讀取時，與快照複本相關聯的冷區塊會保持冷狀態，不會寫回本機層。



[[auto]]
=== 自動

The `auto` 分層策略會將磁碟區中的所有冷資料（包括快照和使用中的檔案系統）分層到雲端層。預設的最低分層冷卻期為 31 天，適用於整個磁碟區，包括使用中的檔案系統和快照。

您可以使用修改分層最低冷卻期間的預設設定 `-tiering-minimum-cooling-days` 的進階權限層級中的參數 `volume create` 和 `volume modify` 命令。有效值為2至183天。

當隨機讀取時，分層原則設定為「自動」的磁碟區中的冷區塊將變為熱區塊並寫回本機層。

當按順序讀取時，分層原則設定為「自動」的磁碟區中的冷資料區塊將保持冷狀態，並保留在雲端層中。它們不會寫回本機層。



[[all]]
=== 全部

The `all`分層策略會立即將磁碟區中的所有資料標記為冷資料，並儘快將其分層至雲端層。使用 `all`分層策略的磁碟區中，無需等待 48 小時即可將新資料區塊變為冷資料。

分層最低冷卻週期不適用、因為資料會在分層掃描執行後立即移至雲端層、而且您無法修改設定。

當磁碟區中分層原則設定為「全部」的冷資料區塊被讀取時，它們將保持冷狀態並保留在雲端層中。它們不會寫回本機層。

[NOTE]
====
。 `all` 磁碟區分層原則不應用於具有正常用戶端流量的讀取 / 寫入磁碟區。

物件儲存不像檔案或區塊儲存那樣具有交易性。使用「全部」分層原則對儲存在磁碟區中作為物件的檔案進行變更，可能會導致建立新物件、現有物件碎片化、讀取效能下降以及儲存效率降低。

====


[[none]]
=== 無

The `none` 分層策略將磁碟區的資料保留在效能層，但不會對資料進行分層。

將分層原則設為 `none` 防止新的分層。先前移至雲端層的 Volume 資料會保留在雲端層、直到變熱為止、並自動移回本機層為止。

分層最低散熱週期不適用、因為資料永遠不會移至雲端層、而且您無法修改設定。

當磁碟區中的冷區塊設為分層原則時 `none` 讀取後、會變熱並寫入本機層。

。 `volume show` 命令輸出會顯示磁碟區的分層原則。FabricPool 從未使用過的 Volume 會顯示 `none` 輸出中的分層原則。


NOTE: 在 SVM DR 關係中，來源和目的地磁碟區不需要使用 FabricPool 集合體，但它們必須使用相同的分層原則。



[[what-happens-when-you-modify-a-volume-tiering-policy]]
== 修改磁碟區分層原則時會發生什麼情況？

您可以執行來修改磁碟區的分層原則 `volume modify` 營運。您必須瞭解變更分層原則、可能會影響資料冷卻及移至雲端層所需的時間。

* 變更分層原則 `snapshot-only` 或 `none` 至 `auto` 讓 ONTAP 將已冷卻的作用中檔案系統中的使用者資料區塊傳送至雲端層、即使這些使用者資料區塊先前不符合雲端層的資格。
* 將分層原則從另一個原則變更為 `all`，會導致 ONTAP 盡快將作用中檔案系統和快照中的所有使用者區塊移至雲端。在 ONTAP 9.8 之前、區塊需要等到下一次分層掃描執行。
+
不允許將區塊移回效能層。

* 變更分層原則 `auto` 至 `snapshot-only` 或 `none` 不會將已移至雲端層的作用中檔案系統區塊移回效能層。
+
需要磁碟區讀取、才能將資料移回效能層。

* 每當您變更磁碟區的分層原則時、分層的最小冷卻期間會重設為原則的預設值。




[[what-happens-to-the-tiering-policy-when-you-move-a-volume]]
== 當您移動磁碟區時、分層原則會發生什麼事

* 除非您明確指定不同的分層原則、否則當磁碟區移入和移出啟用FabricPool的Aggregate時、就會保留其原始分層原則。
+
不過、分層原則只有在磁碟區位於啟用FabricPool的Aggregate中時才會生效。

* 的現有值 `-tiering-minimum-cooling-days` 除非您為目的地指定不同的分層原則、否則 Volume 的參數會隨著 Volume 一起移動。
+
如果您指定不同的分層原則、則該磁碟區會使用該原則的預設分層最小冷卻期間。無論目的地FabricPool 是否為不實、都會發生這種情況。

* 您可以跨集合體移動磁碟區、同時修改分層原則。
* 您應該特別注意 `volume move` 操作涉及 `auto` 分層原則。
+
假設來源和目的地都是啟用 FabricPool 的集合體、下表摘要說明的結果 `volume move` 涉及相關原則變更的作業 `auto`：

+
|===


| 當您移動具有分層原則的磁碟區時... | 您也可以透過移至...來變更分層原則。 | 然後在磁碟區移動之後... 


 a| 
`all`
 a| 
`auto`
 a| 
所有資料都會移至效能層級。



 a| 
`snapshot-only`、 `none`或 `auto`
 a| 
`auto`
 a| 
資料區塊會移至目的地的同一層、如同先前位於來源。



 a| 
`auto` 或 `all`
 a| 
`snapshot-only`
 a| 
所有資料都會移至效能層級。



 a| 
`auto`
 a| 
`all`
 a| 
所有使用者資料都會移至雲端層。



 a| 
`snapshot-only`,`auto` 或 `all`
 a| 
`none`
 a| 
所有資料都保留在效能層級。

|===




[[what-happens-to-the-tiering-policy-when-you-clone-a-volume]]
== 當您複製磁碟區時、分層原則會發生什麼變化

* 從ONTAP 功能性的問題9.8開始、複製磁碟區一律會從父磁碟區繼承分層原則和雲端擷取原則。
+
在早於 ONTAP 9.8 的版本中、除非父實體具有、否則複本會從父實體繼承分層原則 `all` 分層原則。

* 如果父磁碟區有 `never` 雲端擷取原則、其複製磁碟區必須具有 `never` 雲端擷取原則或 `all` 分層原則、以及對應的雲端擷取原則 `default`。
* 無法將父 Volume 雲端擷取原則變更為 `never` 除非所有的複本磁碟區都有雲端擷取原則 `never`。


當您複製磁碟區時、請謹記下列最佳實務做法：

* 。 `-tiering-policy` 選項與 `tiering-minimum-cooling-days` 複製選項只會控制複製特有之區塊的分層行為。因此、我們建議在父FlexVol 級不知道上使用分層設定、以移動相同數量的資料、或移動的資料量少於任何複本
* 父FlexVol 實體上的雲端擷取原則應移動相同數量的資料、或移動的資料應大於任何實體複本的擷取原則




[[how-cloud-retrieval-policies-work-with-tiering-policies]]
== 雲端擷取原則如何與分層原則搭配運作

FabricPool 雲端資料擷取由擷取原則控制，這些原則決定何時將資料寫回本機層。讀取模式可以是連續的，也可以是隨機的。

下表列出 Volume 分層原則及每種原則的預設擷取行為。

|===


| 分層原則 | 預設擷取行為 


 a| 
無
 a| 
連續和隨機讀取



 a| 
純快照
 a| 
連續和隨機讀取



 a| 
自動
 a| 
隨機讀取



 a| 
全部
 a| 
無資料擷取

|===
從 ONTAP 9.8 開始、就是雲端移轉控制 `cloud-retrieval-policy` 選項會覆寫由分層原則控制的預設雲端移轉或擷取行為。

下表列出支援的雲端擷取原則及其擷取行為。

|===


| 雲端擷取原則 | 擷取行為 


 a| 
預設
 a| 
讀取 Volume 中的冷資料區塊時，它們會使用 Volume 分層原則的預設行為。無論託管彙總類型為何，此原則都是任何 Volume 的預設值。



 a| 
讀取時
 a| 
當雲端擷取原則設定為「`On-Read`」的 Volume 中的冷塊被隨機或連續地讀取時，這些冷塊將變為熱塊並寫入本機層。

使用連續讀取的應用程式會透過將 Volume 雲端擷取原則設為「`On-Read`」來觸發寫回本機分層。這對於需要從先前的冷資料（現在正由作用中工作負載讀取）中獲得本機分層效能的應用程式而言相當有益。



 a| 
永不
 a| 
當雲端擷取原則設定為「`Never`」的 Volume 中的冷資料區塊被讀取時，它們將保持冷狀態並保留在雲端分層中。它們不會被寫回本機分層。

將雲端擷取原則設定為「`Never`」與「全部」分層原則類似，因為不允許資料傳回本機分層，但與「全部」分層原則不同的是，它會繼續使用 Volume 的分層最小冷卻天數設定，而不是盡快進行分層。

例如，使用 Auto 分層原則預設設定的 Volume，在資料閒置 31 天後才會將其標記為冷資料。31 天後，閒置資料將分層至物件儲存，且由於該 Volume 的雲端擷取原則已設定為「`Never」`，讀取時不會返回。



 a| 
促銷
 a| 
* 對於分層原則「`none`」，所有分層資料都會寫回本機分層。
* 對於分層原則「`snapshot-only,`」，分層的非快照資料會寫回本機層。


|===
.修改雲端擷取原則的範例
以下範例將 Volume 的分層原則變更為 `none`，並將擷取原則變更為 `promote`：

[listing]
----
set -privilege advanced

volume modify -vserver vs1 -volume myvol -tiering-policy none -cloud-retrieval-policy promote
----