---
permalink: nfs-config/additional-information-reference.html 
sidebar: sidebar 
keywords: additional, information, nfs, configuration, networking, san protocol, root volume, protection 
summary: 成功測試NFS用戶端存取之後、您可以執行其他NFS組態或新增SAN存取。傳輸協定存取完成時、您應該保護儲存虛擬機器（SVM）的根磁碟區。 
---
= 何處可找到其他資訊
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
成功測試NFS用戶端存取之後、您可以執行其他NFS組態或新增SAN存取。傳輸協定存取完成時、您應該保護儲存虛擬機器（SVM）的根磁碟區。



== NFS 組態

您可以使用下列資訊和技術報告進一步設定NFS存取：

* link:../nfs-admin/index.html["NFS管理"]
+
說明如何使用NFS設定及管理檔案存取。

* http://www.netapp.com/us/media/tr-4067.pdf["NetApp技術報告4067：NFS最佳實務與實作指南"^]
+
提供NFSv3和NFSv3作業指南、並概述ONTAP 以NFSv3為焦點的作業系統。

* http://www.netapp.com/us/media/tr-4073.pdf["NetApp技術報告4073：安全統一化驗證"]
+
說明如何設定ONTAP 搭配UNIX型Kerberos第5版（krb5）伺服器使用的功能、以進行NFS儲存驗證、以及將Windows Server Active Directory（AD）設定為Kdc和輕量型目錄存取傳輸協定（LDAP）身分識別供應商。

* http://www.netapp.com/us/media/tr-3580.pdf["NetApp技術報告3580：NFSv4增強功能與最佳實務做法指南Data ONTAP -實作"]
+
說明在掛接到執行ONTAP 此功能的系統上、在AIX、Linux或Solaris用戶端上實作NFSv4元件時應遵循的最佳實務做法。





== 網路組態

您可以使用下列資訊與技術報告、進一步設定網路功能與名稱服務：

* link:../nfs-admin/index.html["NFS管理"]
+
說明如何設定及管理ONTAP 靜態網路。

* http://www.netapp.com/us/media/tr-4182.pdf["NetApp技術報告4182：乙太網路儲存設計考量與叢集Data ONTAP 式的最佳實務做法"]
+
說明ONTAP 實作的環節、並提供常見的網路部署情境和最佳實務建議。

* https://www.netapp.com/pdf.html?item=/media/16328-tr-4668pdf.pdf["NetApp技術報告4668：名稱服務最佳實務做法指南"^]
+
說明如何設定LDAP、NIS、DNS及本機檔案組態以進行驗證。





== SAN傳輸協定組態

如果您想要提供或修改SAN對新SVM的存取、可以使用FC或iSCSI組態資訊、此資訊適用於多個主機作業系統。



== 根Volume保護

在SVM上設定傳輸協定之後、您應確保其根Volume受到保護：

* link:../data-protection/index.html["資料保護"]
+
說明如何建立負載共用鏡像來保護SVM根磁碟區、這是NetApp啟用NAS的SVM最佳實務做法。同時也說明如何從負載共用鏡像中提升SVM根磁碟區、以快速從磁碟區故障或損失中恢復。


