---
permalink: nfs-config/assess-networking-requirements-task.html 
sidebar: sidebar 
keywords: assess, networking, requirements 
summary: 將NFS儲存設備提供給用戶端之前、您必須先確認網路設定正確、以符合NFS資源配置需求。 
---
= 評估 ONTAP NFS 網路配置需求
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
將NFS儲存設備提供給用戶端之前、您必須先確認網路設定正確、以符合NFS資源配置需求。

.開始之前
必須設定下列叢集網路物件：

* 實體與邏輯連接埠
* 廣播網域
* 子網路（如有需要）
* IPspaces（視需要而定、除了預設IPspace）
* 容錯移轉群組（視需要、以及每個廣播網域的預設容錯移轉群組）
* 外部防火牆


.步驟
. 顯示可用的實體和虛擬連接埠：
+
`network port show`

+
** 如果可能、您應該使用資料網路速度最高的連接埠。
** 資料網路中的所有元件必須具有相同的MTU設定、才能獲得最佳效能。
** 如link:https://docs.netapp.com/us-en/ontap-cli/network-port-show.html["指令參考資料ONTAP"^]需詳細 `network port show`資訊，請參閱。


. 如果您打算使用子網路名稱來配置LIF的IP位址和網路遮罩值、請確認該子網路存在且有足夠的可用位址：+
+
`network subnet show`

+
如link:https://docs.netapp.com/us-en/ontap-cli/network-subnet-show.html["指令參考資料ONTAP"^]需詳細 `network subnet show`資訊，請參閱。

+
子網路包含屬於同一第3層子網路的IP位址集區。子網路是使用建立的 `network subnet create` 命令。

+
如link:https://docs.netapp.com/us-en/ontap-cli/network-subnet-create.html["指令參考資料ONTAP"^]需詳細 `network subnet create`資訊，請參閱。

. 顯示可用的IPspaces：
+
`network ipspace show`

+
您可以使用預設IPspace或自訂IPspace。

+
如link:https://docs.netapp.com/us-en/ontap-cli/network-ipspace-show.html["指令參考資料ONTAP"^]需詳細 `network ipspace show`資訊，請參閱。

. 如果您要使用IPv6位址、請確認叢集上已啟用IPv6：
+
`network options ipv6 show`

+
如有需要、您可以使用啟用 IPv6 `network options ipv6 modify` 命令。

+
深入瞭解 `network options ipv6 show`及 `network options ipv6 modify` link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=network+options+ipv6["指令參考資料ONTAP"^]。


