---
permalink: nfs-config/comparison-exports-7-mode-concept.html 
sidebar: sidebar 
keywords: comparison, exports, 7-mode ontap 
summary: 以功能為基礎的匯出ONTAP 是以不同於7-Mode環境的方式定義和使用。 
---
= 了解 7-模式和 ONTAP NFS 導出的比較
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
以功能為基礎的匯出ONTAP 是以不同於7-Mode環境的方式定義和使用。

|===


| 差異領域 | 7-Mode | ONTAP 


 a| 
如何定義匯出
 a| 
匯出是在中定義的 `/etc/exports` 檔案：
 a| 
匯出是透過在SVM中建立匯出原則來定義。SVM可包含多個匯出原則。



 a| 
匯出範圍
 a| 
* 匯出會套用至指定的檔案路徑或qtree。
* 您必須在中建立個別項目 `/etc/exports` 針對每個檔案路徑或 qtree 。
* 只有在中定義匯出時、匯出才會持續進行 `/etc/exports` 檔案：

 a| 
* 匯出原則適用於整個Volume、包括Volume中包含的所有檔案路徑和qtree。
* 如果需要、匯出原則可套用至多個Volume。
* 所有匯出原則都會在系統重新啟動時持續執行。




 a| 
隔離（指定特定用戶端對相同資源的不同存取）
 a| 
若要為特定用戶端提供對單一匯出資源的不同存取權、您必須在中列出每個用戶端及其允許的存取權 `/etc/exports` 檔案：
 a| 
匯出原則是由許多個別的匯出規則所組成。每個匯出規則都會定義資源的特定存取權限、並列出擁有這些權限的用戶端。若要為特定用戶端指定不同的存取權限、您必須為每組特定的存取權限建立匯出規則、列出具有這些權限的用戶端、然後將規則新增至匯出原則。



 a| 
名稱別名
 a| 
定義匯出時、您可以選擇讓匯出名稱與檔案路徑名稱不同。您應該使用 `-actual` 在中定義此類匯出時的參數 `/etc/exports` 檔案：
 a| 
您可以選擇讓匯出的Volume名稱不同於實際的Volume名稱。若要這麼做、您必須在SVM命名空間內以自訂的交會路徑名稱來掛載磁碟區。


NOTE: 根據預設、磁碟區會以其Volume名稱掛載。若要自訂磁碟區的交會路徑名稱、您需要卸載、重新命名、然後重新掛載。

|===