---
permalink: nfs-config/configure-dns-host-name-resolution-task.html 
sidebar: sidebar 
keywords: enabling, dns, host-name, resolution, enable, host, name, resolve, automatic configuration validation 
summary: 您可以使用vserver services name-service DNS命令在SVM上啟用DNS、並將其設定為使用DNS進行主機名稱解析。使用外部DNS伺服器解析主機名稱。 
---
= 為 ONTAP NFS SVM 主機名稱解析啟用 DNS
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `vserver services name-service dns` 命令在 SVM 上啟用 DNS 、並將其設定為使用 DNS 進行主機名稱解析。使用外部DNS伺服器解析主機名稱。

.開始之前
站台範圍的DNS伺服器必須可供主機名稱查詢。

您應該設定多個DNS伺服器、以避免單點故障。。 `vserver services name-service dns create` 如果只輸入一個 DNS 伺服器名稱、命令會發出警告。

.關於這項工作
深入瞭解 link:../networking/configure_dynamic_dns_services.html["在 SVM 上設定動態 DNS"]。

.步驟
. 在SVM上啟用DNS：
+
`vserver services name-service dns create -vserver _vserver_name_ -domains _domain_name_ -name-servers _ip_addresses_ -state enabled`

+
下列命令可啟用SVM VS1上的外部DNS伺服器：

+
[listing]
----
vserver services name-service dns create -vserver vs1.example.com -domains example.com -name-servers 192.0.2.201,192.0.2.202 -state enabled
----
+
[NOTE]
====
。 `vserver services name-service dns create` 如果 ONTAP 無法連絡名稱伺服器、命令會執行自動組態驗證、並回報錯誤訊息。

====
. 使用顯示 DNS 網域組態 `vserver services name-service dns show` 命令。
+
下列命令會顯示叢集中所有SVM的DNS組態：

+
[listing]
----
vserver services name-service dns show
                                             Name
Vserver           State     Domains             Servers
----------------- --------- ------------------- -------------
cluster1          enabled   example.com         192.0.2.201,
                                                192.0.2.202
vs1.example.com   enabled   example.com         192.0.2.201,
                                                192.0.2.202
----
+
下列命令會顯示SVM VS1的詳細DNS組態資訊：

+
[listing]
----
vserver services name-service dns show -vserver vs1.example.com
               Vserver: vs1.example.com
               Domains: example.com
          Name Servers: 192.0.2.201, 192.0.2.202
    Enable/Disable DNS: enabled
        Timeout (secs): 2
      Maximum Attempts: 1
----
. 使用驗證名稱伺服器的狀態 `vserver services name-service dns check` 命令。
+
[listing]
----
vserver services name-service dns check -vserver vs1.example.com

Vserver           Name Server     Status       Status Details
----------------  -------------   ----------   --------------------------
vs1.example.com   10.0.0.50         up         Response time (msec): 2
vs1.example.com   10.0.0.51         up         Response time (msec): 2
----

