---
permalink: nfs-config/create-svms-data-access-task.html 
sidebar: sidebar 
keywords: create, svm 
summary: 如果叢集中沒有至少一個SVM來提供NFS用戶端的資料存取、則必須建立一個SVM。 
---
= 建立SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果叢集中沒有至少一個SVM來提供NFS用戶端的資料存取、則必須建立一個SVM。

.開始之前
* 從 ONTAP 9.13.1 開始、您可以設定儲存 VM 的最大容量。您也可以在 SVM 接近臨界值容量層級時設定警示。如需詳細資訊、請參閱 xref:../system-admin/manage-svm-capacity.html[管理 SVM 容量]。


.步驟
. 建立SVM：
+
`vserver create -vserver _vserver_name_ -rootvolume _root_volume_name_ -aggregate _aggregate_name_ -rootvolume-security-style unix -language C.UTF-8 -ipspace _ipspace_name_`

+
** 使用的 UNIX 設定 `-rootvolume-security-style` 選項。
** 使用預設的 C.UTF-8 `-language` 選項。
** 。 `ipspace` 設定為選用項目。


. 驗證新建立的SVM的組態和狀態：
+
`vserver show -vserver _vserver_name_`

+
。 `Allowed Protocols` 欄位必須包含 NFS 。您可以稍後再編輯此清單。

+
。 `Vserver Operational State` 欄位必須顯示 `running` 州/省。如果顯示 `initializing` 狀態、表示有些中繼作業（例如建立根磁碟區）失敗、您必須刪除 SVM 並重新建立它。



.範例
下列命令會在IPspace ipspaceA中建立SVM以供資料存取：

[listing]
----
cluster1::> vserver create -vserver vs1.example.com -rootvolume root_vs1 -aggregate aggr1
-rootvolume-security-style unix -language C.UTF-8 -ipspace ipspaceA

[Job 2059] Job succeeded:
Vserver creation completed
----
下列命令顯示 SVM 是以 1 GB 的根磁碟區所建立、而且是自動啟動且位於中 `running` 州/省。根磁碟區具有預設的匯出原則、不含任何規則、因此根磁碟區在建立時不會匯出。

[listing]
----
cluster1::> vserver show -vserver vs1.example.com
                                    Vserver: vs1.example.com
                               Vserver Type: data
                            Vserver Subtype: default
                               Vserver UUID: b8375669-19b0-11e5-b9d1-00a0983d9736
                                Root Volume: root_vs1
                                  Aggregate: aggr1
                                 NIS Domain: -
                 Root Volume Security Style: unix
                                LDAP Client: -
               Default Volume Language Code: C.UTF-8
                            Snapshot Policy: default
                                    Comment:
                               Quota Policy: default
                List of Aggregates Assigned: -
 Limit on Maximum Number of Volumes allowed: unlimited
                        Vserver Admin State: running
                  Vserver Operational State: running
   Vserver Operational State Stopped Reason: -
                          Allowed Protocols: nfs, cifs, fcp, iscsi, ndmp
                       Disallowed Protocols: -
                           QoS Policy Group: -
                                Config Lock: false
                               IPspace Name: ipspaceA
----

NOTE: 從 ONTAP 9.13.1 開始、您可以設定調適性 QoS 原則群組範本、將處理量下限套用至 SVM 中的磁碟區。您只能在建立 SVM 之後套用此原則。若要深入瞭解此程序、請參閱 xref:../performance-admin/adaptive-policy-template-task.html[設定調適性原則群組範本]。
