---
permalink: nfs-config/examples-export-policies-concept.html 
sidebar: sidebar 
keywords: examples, ontap, export, policies, implementation, 7-mode 
summary: 您可以檢閱範例匯出原則、進一步瞭解匯出原則在ONTAP 功能方面的運作方式。 
---
= 示例：不實匯出原則ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以檢閱範例匯出原則、進一步瞭解匯出原則在ONTAP 功能方面的運作方式。



== 7-Mode匯出的實作範例ONTAP

下列範例顯示的 7-Mode 匯出與中所顯示的相同 `/etc/export` 檔案：

[listing]
----
/vol/vol1 -sec=sys,ro=@readonly_netgroup,rw=@readwrite_netgroup1:
@readwrite_netgroup2:@rootaccess_netgroup,root=@rootaccess_netgroup
----
若要將此匯出重新產生為叢集匯出原則、您必須建立具有三個匯出規則的匯出原則、然後將匯出原則指派給Volume vol1。

|===
| 規則 | 元素 | 價值 


 a| 
規則1.
 a| 
`-clientmatch` （用戶端規格）
 a| 
`@readonly_netgroup`



 a| 
`-ruleindex`（出口規則在規則清單中的位置）
 a| 
`1`



 a| 
`-protocol`
 a| 
`nfs`



 a| 
`-rorule`（允許唯讀存取）
 a| 
`sys` （使用驗證的用戶端）



 a| 
`-rwrule`（允許讀寫存取）
 a| 
`never`



 a| 
`-superuser`（允許超級使用者存取）
 a| 
`none`（根目錄 _ 分段 _ 至安納）



 a| 
第2條
 a| 
`-clientmatch`
 a| 
`@rootaccess_netgroup`



 a| 
`-ruleindex`
 a| 
`2`



 a| 
`-protocol`
 a| 
`nfs`



 a| 
`-rorule`
 a| 
`sys`



 a| 
`-rwrule`
 a| 
`sys`



 a| 
`-superuser`
 a| 
`sys`



 a| 
第 3 條
 a| 
`-clientmatch`
 a| 
`@readwrite_netgroup1,@readwrite_netgroup2`



 a| 
`-ruleindex`
 a| 
`3`



 a| 
`-protocol`
 a| 
`nfs`



 a| 
`-rorule`
 a| 
`sys`



 a| 
`-rwrule`
 a| 
`sys`



 a| 
`-superuser`
 a| 
`none`

|===
. 建立名為exp_vol1的匯出原則：
+
`vserver export-policy create -vserver NewSVM -policyname exp_vol1`

. 在base命令中建立三個具有下列參數的規則：
+
** 基本命令：
 +
`vserver export-policy rule create -vserver NewSVM -policyname exp_vol1`
** 規則參數：
 +
`-clientmatch @readonly_netgroup -ruleindex 1 -protocol nfs -rorule sys -rwrule never -superuser none`
 +
 `-clientmatch @rootaccess_netgroup -ruleindex 2 -protocol nfs -rorule sys -rwrule sys -superuser sys`
 +
 `-clientmatch @readwrite_netgroup1,@readwrite_netgroup2 -ruleindex 3 -protocol nfs -rorule sys -rwrule sys -superuser none`


. 將原則指派給Volume vol1：
+
`volume modify -vserver NewSVM -volume vol1 -policy exp_vol1`





== 7-Mode匯出的整合範例

以下範例顯示 7-Mode `/etc/export` 每 10 個 qtree 包含一行的檔案：

[listing]
----

/vol/vol1/q_1472 -sec=sys,rw=host1519s,root=host1519s
/vol/vol1/q_1471 -sec=sys,rw=host1519s,root=host1519s
/vol/vol1/q_1473 -sec=sys,rw=host1519s,root=host1519s
/vol/vol1/q_1570 -sec=sys,rw=host1519s,root=host1519s
/vol/vol1/q_1571 -sec=sys,rw=host1519s,root=host1519s
/vol/vol1/q_2237 -sec=sys,rw=host2057s,root=host2057s
/vol/vol1/q_2238 -sec=sys,rw=host2057s,root=host2057s
/vol/vol1/q_2239 -sec=sys,rw=host2057s,root=host2057s
/vol/vol1/q_2240 -sec=sys,rw=host2057s,root=host2057s
/vol/vol1/q_2241 -sec=sys,rw=host2057s,root=host2057s
----
在 ONTAP 中、每個 qtree 都需要兩個原則之一：一個原則包含規則 `-clientmatch host1519s`或具有規則的規則 `-clientmatch host2057s`。

. 建立兩個匯出原則、稱為exp_vol1q1和exp_vol1q2：
+
** `vserver export-policy create -vserver NewSVM -policyname exp_vol1q1`
** `vserver export-policy create -vserver NewSVM -policyname exp_vol1q2`


. 為每個原則建立規則：
+
** `vserver export-policy rule create -vserver NewSVM -policyname exp_vol1q1 -clientmatch host1519s -rwrule sys -superuser sys`
** `vserver export-policy rule create -vserver NewSVM -policyname exp_vol1q2 -clientmatch host1519s -rwrule sys -superuser sys`


. 將原則套用至qtree：
+
** `volume qtree modify -vserver NewSVM -qtree-path /vol/vol1/q_1472 -export-policy exp_vol1q1`
** [接下來的4個qtree ...]
** `volume qtree modify -vserver NewSVM -qtree-path /vol/vol1/q_2237 -export-policy exp_vol1q2`
** [接下來的4個qtree ...]




如果您稍後需要為這些主機新增其他qtree、則會使用相同的匯出原則。
