---
permalink: nfs-config/load-local-unix-users-uri-task.html 
sidebar: sidebar 
keywords: load, local, unix, users, uri 
summary: 除了在SVM中手動建立個別的本機UNIX使用者之外、您也可以透過統一的資源識別元（URI）（Vserver服務名稱服務UNIX使用者負載來源URI）、將本機UNIX使用者的清單載入SVM、藉此簡化工作。 
---
= 從URI載入本機UNIX使用者
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
除了在 SVM 中手動建立個別的本機 UNIX 使用者之外、您也可以從統一的資源識別元（ URI ）將本機 UNIX 使用者清單載入 SVM 、以簡化工作。 (`vserver services name-service unix-user load-from-uri`）。

.步驟
. 建立包含您要載入之本機UNIX使用者清單的檔案。
+
檔案必須包含 UNIX 中的使用者資訊 `/etc/passwd` 格式：

+
`_user_name: password: user_ID: group_ID: full_name_`

+
命令會捨棄的值 `_password_` 欄位和之後欄位的值 `_full_name_` 欄位 (`_home_directory_` 和 `_shell_`）。

+
支援的檔案大小上限為2.5 MB。

. 確認清單中沒有任何重複資訊。
+
如果清單包含重複的項目、則載入清單時會失敗並顯示錯誤訊息。

. 將檔案複製到伺服器。
+
儲存系統必須透過HTTP、HTTPS、FTP或FTPS連線至伺服器。

. 判斷檔案的URI是什麼。
+
URI是您提供給儲存系統的位址、用以指出檔案所在位置。

. 從URI將包含本機UNIX使用者清單的檔案載入SVM：
+
`vserver services name-service unix-user load-from-uri -vserver _vserver_name_ -uri {ftp|http|ftps|https}://_uri_ -overwrite {true|false}`

+
`-overwrite` {`true` `false`} 指定是否覆寫項目。預設值為 `false`。



.範例
下列命令會從 URI 載入本機 UNIX 使用者清單 `+ftp://ftp.example.com/passwd+` 進入名為 VS1 的 SVM 。SVM上的現有使用者不會被URI的資訊覆寫。

[listing]
----
node::> vserver services name-service unix-user load-from-uri -vserver vs1
-uri ftp://ftp.example.com/passwd -overwrite false
----