---
permalink: nfs-config/load-local-unix-groups-uri-task.html 
sidebar: sidebar 
keywords: load, local, unix, groups, uri 
summary: 除了手動建立個別的本機UNIX群組之外、您也可以使用vserver服務名稱服務UNIX群組負載來源URI命令、從統一的資源識別元（URI）將本機UNIX群組清單載入SVM。 
---
= 從 ONTAP NFS SVM 上的 URI 載入本機 UNIX 群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
除了手動建立個別的本機 UNIX 群組之外、您也可以使用、從統一的資源識別元（ URI ）將本機 UNIX 群組清單載入 SVM `vserver services name-service unix-group load-from-uri` 命令。

.步驟
. 建立包含您要載入之本機UNIX群組清單的檔案。
+
檔案必須包含 UNIX 中的群組資訊 `/etc/group` 格式：

+
`_group_name: password: group_ID: comma_separated_list_of_users_`

+
命令會捨棄的值 `_password_` 欄位。

+
支援的檔案大小上限為 1 MB 。

+
群組檔案中每一行的長度上限為32、768個字元。

. 確認清單中沒有任何重複資訊。
+
清單不得包含重複的項目、否則載入清單將會失敗。如果 SVM 中已有項目、您必須設定 `-overwrite` 參數至 `true` 以新檔案覆寫所有現有項目、或確保新檔案不包含任何重複現有項目的項目。

. 將檔案複製到伺服器。
+
儲存系統必須透過HTTP、HTTPS、FTP或FTPS連線至伺服器。

. 判斷檔案的URI是什麼。
+
URI是您提供給儲存系統的位址、用以指出檔案所在位置。

. 從URI將包含本機UNIX群組清單的檔案載入SVM：
+
`vserver services name-service unix-group load-from-uri -vserver _vserver_name_ -uri {ftp|http|ftps|https}://_uri_ -overwrite {true|false}`

+
`-overwrite`  `true` `false`} 指定是否覆寫項目。預設值為 `false`。如果您將此參數指定為 `true`， ONTAP 會將指定 SVM 的整個現有本機 UNIX 群組資料庫，取代為您所載入檔案的項目。



.範例
下列命令會從 URI 載入本機 UNIX 群組清單 `+ftp://ftp.example.com/group+` 進入名為 VS1 的 SVM 。SVM上的現有群組不會被URI的資訊覆寫。

[listing]
----
vs1::> vserver services name-service unix-group load-from-uri -vserver vs1
-uri ftp://ftp.example.com/group -overwrite false
----