---
permalink: nfs-config/load-netgroups-svms-task.html 
sidebar: sidebar 
keywords: load, netgroups, svms 
summary: 您可以在匯出原則規則中使用符合用戶端的方法之一、就是使用netGroups中列出的主機。您可以將網路群組從統一的資源識別元（URI）載入SVM、以取代使用儲存在外部名稱伺服器（Vserver服務名稱服務netgroup負載）中的網路群組。 
---
= 將網路群組載入SVM
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在匯出原則規則中使用符合用戶端的方法之一、就是使用netGroups中列出的主機。您可以將網路群組從統一資源識別元（URI）載入SVM、以取代使用儲存在外部名稱伺服器（「vserver services name-service netgroup loads」）中的網路群組。

.您需要的產品
Netgroup檔案在載入SVM之前、必須符合下列要求：

* 檔案必須使用與NIS相同的適當netgroup文字檔格式。
+
此功能可在載入netgroup文字檔格式之前檢查其內容。ONTAP如果檔案包含錯誤、則不會載入、並會顯示訊息、指出您必須在檔案中執行的修正。更正錯誤後、您可以將netgroup檔案重新載入指定的SVM。

* netgroup檔案中主機名稱中的任何字母字元都應為小寫。
* 支援的檔案大小上限為5 MB。
* 巢狀網路群組支援的最大層級為1000。
* 在netgroup檔案中定義主機名稱時、只能使用主要DNS主機名稱。
+
為了避免匯出存取問題、不應使用DNS CNAME/或循環配置資源記錄來定義主機名稱。

* netgroup檔案中三個群組的使用者和網域部分應保持空白、因為ONTAP 無法支援它們。
+
僅支援主機/IP部分。



.關於這項工作
支援各主機的netgroup搜尋本機netgroup檔案。ONTAP載入netgroup檔案後ONTAP 、Syname會自動建立netgroup .byhost對應、以啟用逐主機的netgroup搜尋。這可大幅加速本機netgroup搜尋、以處理匯出原則規則來評估用戶端存取。

.步驟
. 從URI將網路群組載入SVM：
+
「Vserver services name-service netgroup load -vserver _vserver_name_-source｛ftp | http | ftps| https｝：//_uni_」

+
載入netgroup檔案並建置netgroup。byhost對應可能需要數分鐘的時間。

+
如果要更新netgroup、您可以編輯該檔案、然後將更新的netgroup檔案載入SVM。



.範例
下列命令會從HTTP URL h+http://intranet/downloads/corp-netgroup+`:將netgroup定義載入名為VS1的SVM

[listing]
----
vs1::> vserver services name-service netgroup load -vserver vs1
-source http://intranet/downloads/corp-netgroup
----