---
permalink: nfs-config/load-local-unix-groups-uri-task.html 
sidebar: sidebar 
keywords: load, local, unix, groups, uri 
summary: 除了手動建立個別的本機UNIX群組之外、您也可以使用vserver服務名稱服務UNIX群組負載來源URI命令、從統一的資源識別元（URI）將本機UNIX群組清單載入SVM。 
---
= 從URI載入本機UNIX群組
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
除了手動建立個別的本機UNIX群組、您也可以使用「vserver services name-service unix-group load-from -uri」命令、從統一的資源識別元（URI）將本機UNIX群組清單載入SVM。

.步驟
. 建立包含您要載入之本機UNIX群組清單的檔案。
+
檔案必須包含UNIX「/etc/group」格式的群組資訊：

+
`_group名稱：密碼：group ID：Comma_separed_list_of_user_`

+
命令會捨棄「_password_」欄位的值。

+
支援的檔案大小上限為1 MB。

+
群組檔案中每一行的長度上限為32、768個字元。

. 確認清單中沒有任何重複資訊。
+
清單不得包含重複的項目、否則載入清單將會失敗。如果SVM中已經有項目存在、您必須將「-Overwrite」參數設為「true」、以新檔案覆寫所有現有項目、或是確保新檔案中沒有任何複製現有項目的項目。

. 將檔案複製到伺服器。
+
儲存系統必須透過HTTP、HTTPS、FTP或FTPS連線至伺服器。

. 判斷檔案的URI是什麼。
+
URI是您提供給儲存系統的位址、用以指出檔案所在位置。

. 從URI將包含本機UNIX群組清單的檔案載入SVM：
+
「Vserver服務名稱服務unix-group load-from -uri -vserver _vserver_name_-uri｛ftp.http | ftps| https｝：//_uri_-ovwrite｛true|假｝」

+
'-`Overwrite’{'true'|'假'}指定是否覆寫項目。預設值為「假」。如果您將此參數指定為「true」、ONTAP 則由正在載入的檔案中的項目取代指定SVM的整個現有本機UNIX群組資料庫。



.範例
下列命令會將URI `+ftp://ftp.example.com/group+`的本機UNIX群組清單載入名為VS1的SVM。SVM上的現有群組不會被URI的資訊覆寫。

[listing]
----
vs1::> vserver services name-service unix-group load-from-uri -vserver vs1
-uri ftp://ftp.example.com/group -overwrite false
----