---
permalink: nfs-config/verify-protocol-enabled-svm-task.html 
sidebar: sidebar 
keywords: verify, nfs, protocol, enabled, svm 
summary: 在SVM上設定及使用NFS之前、您必須先確認已啟用該傳輸協定。 
---
= 驗證 ONTAP SVM 上 NFS 協定的啟用情況
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在SVM上設定及使用NFS之前、您必須先確認已啟用該傳輸協定。

.關於這項工作
這通常是在 SVM 設定期間完成、但如果您在設定期間未啟用傳輸協定、您可以稍後使用加以啟用 `vserver add-protocols` 命令。

[NOTE]
====
一旦建立LIF、您就無法從其新增或移除通訊協定。

====
您也可以使用停用 SVM 上的通訊協定 `vserver remove-protocols` 命令。

.步驟
. 檢查SVM目前啟用和停用的傳輸協定：
+
`vserver show -vserver _vserver_name_ -protocols`

+
您也可以使用 `vserver show-protocols` 用於檢視叢集中所有 SVM 上目前啟用的通訊協定的命令。

. 如有必要、請啟用或停用傳輸協定：
+
** 若要啟用 NFS 傳輸協定：
 +
`vserver add-protocols -vserver _vserver_name_ -protocols nfs`
** 若要停用通訊協定：
 +
`vserver remove-protocols -vserver    _vserver_name_ -protocols _protocol_name_[,_protocol_name_,...]`


. 確認已啟用和停用的傳輸協定已正確更新：
+
`vserver show -vserver _vserver_name_ -protocols`



.範例
下列命令顯示名為VS1的SVM上目前啟用和停用（允許和不允許）的傳輸協定：

[listing]
----
vs1::> vserver show -vserver vs1.example.com -protocols
Vserver           Allowed Protocols         Disallowed Protocols
-----------       ----------------------    -----------------------
vs1.example.com   nfs                       cifs, fcp, iscsi, ndmp
----
下列命令可新增以允許透過 NFS 存取 `nfs` 到名為 VS1 的 SVM 上已啟用的通訊協定清單：

[listing]
----
vs1::> vserver add-protocols -vserver vs1.example.com -protocols nfs
----