---
permalink: system-admin/access-cluster-telnet-task.html 
sidebar: sidebar 
keywords: access, cluster, telnet, administrative, tasks, disable, default 
summary: 您可以向叢集發出遠端登入要求、以執行管理工作。預設會停用Telnet。 
---
= 使用Telnet存取叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以向叢集發出遠端登入要求、以執行管理工作。預設會停用Telnet。

Telnet 和 RSH 不是安全的通訊協定；您應該考慮使用 SSH 來存取叢集。SSH提供安全的遠端Shell和互動式網路工作階段。如需詳細資訊、請 link:./access-cluster-ssh-task.html["使用 SSH 存取叢集"]參閱。

.開始之前
在使用Telnet存取叢集之前、必須符合下列條件：

* 您必須擁有一個叢集本機使用者帳戶、並設定為使用遠端登入作為存取方法。
+
。 `-application` 的參數 `security login` 命令會指定使用者帳戶的存取方法。如需詳細資訊、請參閱 `security login` 手冊頁。



.關於這項工作
* 支援每個節點最多50個並行的遠端登入工作階段。ONTAP
+
如果叢集管理LIF位於節點上、則會與節點管理LIF共用此限制。

+
如果傳入連線速度高於每秒10次、服務會暫時停用60秒。

* 如果您想ONTAP 要從Windows主機存取此功能、可以使用第三方公用程式、例如Putty。
* rsh 命令需要進階權限。


[role="tabbed-block"]
====
.ONTAP 9 。 10.1 或更新版本
--
.步驟
. 確認已啟用 Telnet 安全性傳輸協定：
+
`security protocol show`

+
.. 如果已啟用 Telnet 安全性通訊協定、請繼續下一步。
.. 如果未啟用 Telnet 安全性通訊協定、請使用下列命令加以啟用：
+
`security protocol modify -application telnet -enabled true`



. 確認管理階層中存在該 `management-telnet-server` 服務：
+
`network interface show -services management-telnet-server`

+
.. 如果 `management-telnet-server` 服務存在、請繼續下一步。
.. 如果 `management-telnet-server` 服務不存在、請使用下列命令來新增服務：
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-telnet-server`





--
.ONTAP 9 9 或更早版本
--
.開始之前
在使用Telnet存取叢集之前、必須符合下列條件：

* 叢集或節點管理生命里所使用的管理防火牆原則中、必須已啟用遠端登入、以便透過防火牆來處理遠端登入要求。
+
預設會停用Telnet。 `system services firewall policy show`含有 `-service telnet`參數的命令會顯示是否已在防火牆原則中啟用 Telnet 。有關更多信息，請參見 `system services firewall policy`手冊頁。

* 如果您使用IPv6連線、則必須在叢集上設定並啟用IPv6、而且防火牆原則必須已設定IPv6位址。
+
此 `network options ipv6 show`命令會顯示是否已啟用 IPv6 。 `system services firewall policy show`命令會顯示防火牆原則。



.步驟
. 從管理主機輸入下列命令：
+
`telnet hostname_or_IP`

+
`hostname_or_IP`是叢集管理 LIF 或節點管理 LIF 的主機名稱或 IP 位址。建議使用叢集管理LIF。您可以使用IPv4或IPv6位址。



--
====
.Telnet要求範例
下列範例顯示已設定 Telnet 存取的使用者「 Joe 」如何發出 Telnet 要求、以存取叢集管理 LIF 為 10.72.137.28 的叢集：

[listing]
----

admin_host$ telnet 10.72.137.28

Data ONTAP
login: joe
Password:

cluster1::>

----