---
permalink: system-admin/access-cluster-rsh-task.html 
sidebar: sidebar 
keywords: access, cluster, rsh, cluster, administrative, task, secure, protocol 
summary: 您可以向叢集發出RSHE要求以執行管理工作。rsh並非安全傳輸協定、預設為停用。 
---
= 使用RSH存取叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以向叢集發出RSHE要求以執行管理工作。rsh並非安全傳輸協定、預設為停用。

.您需要的產品
您必須符合下列條件、才能使用RSH存取叢集：

* 您必須擁有一個叢集本機使用者帳戶、並將其設定為使用RSH作為存取方法。
+
。 `-application` 的參數 `security login` 命令會指定使用者帳戶的存取方法。如需詳細資訊、請參閱 `security login` 手冊頁。



.關於這項工作
* rsh不是安全的傳輸協定。
+
您應該考慮使用SSH來存取叢集。SSH提供安全的遠端Shell和互動式網路工作階段。

* 支援每個節點最多50個並行的RSH工作階段。ONTAP
+
如果叢集管理LIF位於節點上、則會與節點管理LIF共用此限制。

+
如果傳入連線速度高於每秒10次、服務會暫時停用60秒。

* rsh 命令需要進階權限。


.步驟
. 確認已啟用 RSH 安全性通訊協定：
+
`security protocol show`

+
.. 如果啟用了 RSH 安全性通訊協定、請繼續下一步。
.. 如果未啟用 RSH 安全性通訊協定、請使用下列命令加以啟用：
+
`security protocol modify -application rsh -enabled true`



. 確認管理階層中存在該 `management-rsh-server` 服務：
+
`network interface show -services management-rsh-server`

+
.. 如果 `management-rsh-server` 服務存在、請繼續下一步。
.. 如果 `management-rsh-server` 服務不存在、請使用下列命令來新增服務：
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-rsh-server`





.RSH申請範例
下列範例顯示已設定 RSH 存取權限的使用者「 Joe 」如何發出 RSHE 要求來執行 `cluster show` 命令：

[listing]
----

admin_host$ rsh 10.72.137.28 -l joe:password cluster show

Node                  Health  Eligibility
--------------------- ------- ------------
node1                 true    true
node2                 true    true
2 entries were displayed.

admin_host$
----