---
permalink: system-admin/access-cluster-rsh-task.html 
sidebar: sidebar 
keywords: access, cluster, rsh, cluster, administrative, task, secure, protocol 
summary: 您可以向叢集發出RSHE要求以執行管理工作。rsh並非安全傳輸協定、預設為停用。 
---
= 使用RSH存取叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以向叢集發出RSHE要求以執行管理工作。rsh並非安全傳輸協定、預設為停用。

.您需要的產品
您必須符合下列條件、才能使用RSH存取叢集：

* 您必須擁有一個叢集本機使用者帳戶、並將其設定為使用RSH作為存取方法。
+
。 `-application` 的參數 `security login` 命令會指定使用者帳戶的存取方法。如需詳細資訊、請參閱 `security login` 手冊頁。

* Rsh必須已在叢集或節點管理生命體所使用的管理防火牆原則中啟用、以便讓RSHH要求能夠通過防火牆。
+
依預設、 RSH 會停用。。 `system services firewall policy show` 命令 `-service rsh` 參數顯示是否已在防火牆原則中啟用 RSH 。如需詳細資訊、請參閱 `system services firewall policy` 手冊頁。

* 如果您使用IPv6連線、則必須在叢集上設定並啟用IPv6、而且防火牆原則必須已設定IPv6位址。
+
。 `network options ipv6 show` 命令會顯示是否已啟用 IPv6 。。 `system services firewall policy show` 命令會顯示防火牆原則。



.關於這項工作
* rsh不是安全的傳輸協定。
+
您應該考慮使用SSH來存取叢集。SSH提供安全的遠端Shell和互動式網路工作階段。

* 支援每個節點最多50個並行的RSH工作階段。ONTAP
+
如果叢集管理LIF位於節點上、則會與節點管理LIF共用此限制。

+
如果傳入連線速度高於每秒10次、服務會暫時停用60秒。



.步驟
. 從管理主機輸入下列命令：
+
`*rsh _hostname_or_IP_ -l _username:passwordcommand_*`

+
`_hostname_or_IP_` 是叢集管理 LIF 或節點管理 LIF 的主機名稱或 IP 位址。建議使用叢集管理LIF。您可以使用IPv4或IPv6位址。

+
`_command_` 是您要透過 RSH 執行的命令。



.RSH申請範例
下列範例顯示已設定 RSH 存取權限的使用者「 Joe 」如何發出 RSHE 要求來執行 `cluster show` 命令：

[listing]
----

admin_host$ rsh 10.72.137.28 -l joe:password cluster show

Node                  Health  Eligibility
--------------------- ------- ------------
node1                 true    true
node2                 true    true
2 entries were displayed.

admin_host$
----