---
permalink: system-admin/accounts-access-sp-concept.html 
sidebar: sidebar 
keywords: account, access, sp, cluster, user, cli, node 
summary: 當您嘗試存取 SP 時，系統會提示您輸入認證資料。使用服務處理器應用程式類型建立的叢集使用者帳戶可以存取叢集中任何節點上的 SP CLI。SP 使用者帳戶由 ONTAP 管理，並透過密碼進行驗證。從 ONTAP 9.15.1 開始，SP 使用者帳戶可以選擇使用雙重驗證，並將公開金鑰作為第二種身分驗證方法。從 ONTAP 9.9.1 開始，SP 使用者帳戶必須具有管理員角色。 
---
= 使用叢集使用者帳戶存取 ONTAP 服務處理器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
嘗試存取 SP 時，系統會提示您輸入認證資料。使用 `service-processor`應用程式類型建立的叢集使用者帳戶可以存取叢集中任何節點上的 SP CLI。SP 使用者帳戶由 ONTAP 管理，並透過密碼進行驗證。從 ONTAP 9.15.1 開始，SP 使用者帳戶可以選擇使用雙重驗證，並將公開金鑰作為第二種身分驗證方法。從 ONTAP 9.9.1 開始，SP 使用者帳戶必須具有 `admin`角色。

用於存取 SP 的使用者帳戶是從 ONTAP 進行管理，而不是從 SP CLI 進行管理。如果建立叢集使用者帳戶時，將  `security login create` 命令的  `-application` 參數設定為  `service-processor`，且將  `-authmethod` 參數設定為  `password`，則該帳戶即可存取 SP。從 ONTAP 9.15.1 開始，您可以選擇性地為 SP 帳戶設定雙重驗證，方法是使用  `security login modify` 命令將第二個身分驗證方法設定為  `publickey`，然後使用  `security login publickey create` 命令將公開金鑰與其建立關聯。

您必須指定 `-role` 建立 SP 使用者帳戶時的參數。

* 在 ONTAP 9.9.1 及更新版本中、您必須指定 `admin` 適用於 `-role` 參數、以及帳戶的任何修改都需要 `admin` 角色：基於安全考量、不再允許其他角色。
+
** 如果您要升級ONTAP 至版本不含更新版本的版本、請參閱 link:../upgrade/sp-user-accounts-change-concept.html["可存取服務處理器的使用者帳戶變更"]。
** 如果您要回復ONTAP 到版本不含更新版本的版本、請參閱 link:../revert/verify-sp-user-accounts-task.html["驗證可存取服務處理器的使用者帳戶"]。


* 在 ONTAP 9.8 和更早版本中、任何角色都可以存取 SP 、但是 `admin` 建議使用。


依預設、名為「 admin 」的叢集使用者帳戶會包含 `service-processor` 應用程式類型、並可存取 SP 。

無法使用保留給系統的名稱（例如「root」和「naroot」）建立使用者帳戶。ONTAP您無法使用系統保留名稱來存取叢集或SP。

您可以使用顯示目前的 SP 使用者帳戶 `-application service-processor` 的參數 `security login show` 命令。

如需 ONTAP 命令參考中連結：https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html[`security login modify`^]、連結：https://docs.netapp.com/us-en/ontap-cli/security-login-publickey-create.html[`security login publickey create`^] 和連結：https://docs.netapp.com/us-en/ontap-cli/security-login-show.html[`security login show`^] 的詳細資訊，請參閱 ONTAP 命令參考。
