---
permalink: system-admin/accounts-access-sp-concept.html 
sidebar: sidebar 
keywords: account, access, sp, cluster, user, cli, node 
summary: 當您嘗試存取SP時、系統會提示您提供認證資料。使用服務處理器應用程式類型建立的叢集使用者帳戶、可存取叢集任何節點上的SP CLI。SP使用者帳戶是從ONTAP 無法驗證的地方管理、並由密碼驗證。從0到9：9.1開始ONTAP 、SP使用者帳戶必須具備管理員角色。 
---
= 使用叢集使用者帳戶存取 ONTAP 服務處理器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當您嘗試存取SP時、系統會提示您提供認證資料。使用建立的叢集使用者帳戶 `service-processor` 應用程式類型可存取叢集任何節點上的 SP CLI 。SP使用者帳戶是從ONTAP 無法驗證的地方管理、並由密碼驗證。從 ONTAP 9.9.1 開始、 SP 使用者帳戶必須具有 `admin` 角色：

存取SP的使用者帳戶是透過ONTAP 不使用SP CLI的功能來管理、叢集使用者帳戶如果是使用建立 SP 、則可以存取 SP `-application` 的參數 `security login create` 命令設為 `service-processor` 和 `-authmethod` 參數設為 `password`。SP僅支援密碼驗證。

您必須指定 `-role` 建立 SP 使用者帳戶時的參數。

* 在 ONTAP 9.9.1 及更新版本中、您必須指定 `admin` 適用於 `-role` 參數、以及帳戶的任何修改都需要 `admin` 角色：基於安全考量、不再允許其他角色。
+
** 如果您要升級ONTAP 至版本不含更新版本的版本、請參閱 link:../upgrade/sp-user-accounts-change-concept.html["可存取服務處理器的使用者帳戶變更"]。
** 如果您要回復ONTAP 到版本不含更新版本的版本、請參閱 link:../revert/verify-sp-user-accounts-task.html["驗證可存取服務處理器的使用者帳戶"]。


* 在 ONTAP 9.8 和更早版本中、任何角色都可以存取 SP 、但是 `admin` 建議使用。


依預設、名為「 admin 」的叢集使用者帳戶會包含 `service-processor` 應用程式類型、並可存取 SP 。

無法使用保留給系統的名稱（例如「root」和「naroot」）建立使用者帳戶。ONTAP您無法使用系統保留名稱來存取叢集或SP。

您可以使用顯示目前的 SP 使用者帳戶 `-application service-processor` 的參數 `security login show` 命令。
