---
permalink: system-admin/autosupport-creates-sends-event-messages-concept.html 
sidebar: sidebar 
keywords: autosupport, event, triggered, messages, ems, data, example 
summary: 當EMS處理觸發事件時、會建立事件觸發的功能性訊息。AutoSupport AutoSupport事件觸發AutoSupport 的消息可警示收件者需要採取修正行動的問題、並僅包含與問題相關的資訊。您可以自訂要納入哪些內容、以及接收訊息的人員。 
---
= 如何建立及傳送事件觸發的訊息AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當EMS處理觸發事件時、會建立事件觸發的功能性訊息。AutoSupport AutoSupport事件觸發AutoSupport 的消息可警示收件者需要採取修正行動的問題、並僅包含與問題相關的資訊。您可以自訂要納入哪些內容、以及接收訊息的人員。

使用下列程序來建立及傳送事件觸發的功能性訊息：AutoSupport AutoSupport

. 當EMS處理觸發事件時、EMS會傳送AutoSupport EISO要求。
+
觸發事件是指EMS事件、AutoSupport 其名稱以「呼叫首頁」開頭、名稱以「不知道目的地」開頭。

. 建立事件觸發的消息。AutoSupport AutoSupport
+
從與觸發程序相關的子系統收集基本資訊和疑難排解資訊、以建立訊息、其中僅包含與觸發事件相關的資訊。AutoSupport

+
每個觸發程序都會有一組預設的子系統。不過、您可以使用「系統節點AutoSupport 的現象修改」命令、選擇將其他子系統與觸發程式建立關聯。

. 支援部門會將事件觸發的支援資訊傳送給「系統節點更新」命令所定義的收件者、並提供「收件者」、「附註目標」、「合作夥伴地址」及「支援」等參數。AutoSupport AutoSupport AutoSupport
+
您可以AutoSupport 使用AutoSupport 「System Node of the ftragger modify」命令搭配「To」和「note-To」參數、針對特定觸發事件啟用和停用提供支援資訊。



.針對特定事件傳送的資料範例
「儲存櫃PSU故障」的EMS事件會觸發一則訊息、其中包含來自Mandatory、記錄檔、儲存設備、RAID、HA、 平台及網路子系統、以及疑難排解必備、記錄檔及儲存子系統中的資料。

您決定要在AutoSupport 任何針對未來「儲存櫃PSU故障」事件所傳送的資訊中、納入NFS的相關資料。您可以輸入下列命令、針對「CallHome.shlf.ps.fault」事件啟用NFS的疑難排解層級資料：

[listing]
----

        cluster1::\>
        system node autosupport trigger modify -node node1 -autosupport-message shlf.ps.fault -troubleshooting-additional nfs
----
請注意、當您使用「系統節點AutoSupport 列舉」命令時、或AutoSupport 當CLI中有由指令碼和EMS事件參照時、「呼叫首頁」字首會從「呼叫首頁.shlf.ps.fault」事件中捨棄。
