---
permalink: system-admin/commands-manage-config-backup-files-reference.html 
sidebar: sidebar 
keywords: command, manage, configuration, backup, file 
summary: 您可以使用系統組態備份命令來管理叢集和節點組態備份檔案。 
---
= 用於管理組態備份檔案的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `system configuration backup` 用於管理叢集和節點組態備份檔案的命令。

這些命令可在進階權限層級使用。

|===
| 如果您想要... | 使用此命令... 


 a| 
建立新的節點或叢集組態備份檔案
 a| 
`system configuration backup create`



 a| 
將組態備份檔案從節點複製到叢集中的另一個節點
 a| 
`system configuration backup copy`



 a| 
將組態備份檔案從叢集中的節點上傳至遠端URL（FTP、HTTP、HTTPS、TFTP或FTPS）
 a| 
`system configuration backup upload`

當您在遠端 URL 中使用 HTTPS 時、請使用 `-validate-certification` 啟用或停用數位憑證驗證的選項。預設會停用憑證驗證。

[NOTE]
====
您要上傳組態備份檔案的Web伺服器必須已啟用HTTP和POST作業的HTTPS作業。某些Web伺服器可能需要安裝額外的模組。如需詳細資訊、請參閱Web伺服器的文件。支援的URL格式因ONTAP 發行版本而異。如需更多關於系統組態命令的資訊，請參閱 https://docs.netapp.com/us-en/ontap-cli/["“ ONTAP 命令參考"^]。

====


 a| 
從遠端URL下載組態備份檔案至叢集中的節點、並在指定時驗證數位憑證
 a| 
`system configuration backup download`

當您在遠端 URL 中使用 HTTPS 時、請使用 `-validate-certification` 啟用或停用數位憑證驗證的選項。預設會停用憑證驗證。



 a| 
在叢集中的節點上重新命名組態備份檔案
 a| 
`system configuration backup rename`



 a| 
檢視叢集中一或多個節點的節點和叢集組態備份檔案
 a| 
`system configuration backup show`



 a| 
刪除節點上的組態備份檔案
 a| 
`system configuration backup delete`

[NOTE]
====
此命令僅會刪除指定節點上的組態備份檔案。如果組態備份檔案也存在於叢集中的其他節點上、則會保留在這些節點上。

====
|===