---
permalink: system-admin/commands-manage-autosupport-reference.html 
sidebar: sidebar 
keywords: command, manage, autosupport, node, message, send, resend, cancel, configure, display, information 
summary: 您可以使用系統節點AutoSupport 的指令來變更或檢視AutoSupport 功能不全的組態、顯示先前AutoSupport 的資訊、以及傳送、重新傳送或取消AutoSupport 一個功能不全的訊息。 
---
= 管理AutoSupport 功能的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「系統節點AutoSupport 列舉」命令來變更或檢視AutoSupport 功能表、顯示有關先前AutoSupport 版本資訊的資訊、以及傳送、重新傳送或取消AutoSupport 某個功能表訊息。



== 設定AutoSupport 功能

|===
| 如果您想要... | 使用此命令... 


 a| 
控制AutoSupport 是否傳送任何不實訊息
 a| 
使用「-state」參數的「System Node AutoSupport 配合使用」



 a| 
控制AutoSupport 是否將不實訊息傳送至技術支援
 a| 
使用「-supports」參數「System Node AutoSupport 」進行「系統節點修改」



 a| 
設定AutoSupport 功能不完善或修改AutoSupport 功能不完善的組態
 a| 
系統節點AutoSupport 的功能不受限制



 a| 
針對AutoSupport 個別觸發事件、啟用並停用內部支援組織的資訊不整合、並指定要納入回應個別觸發事件之訊息的子系統報告
 a| 
系統節點AutoSupport 不受觸發器的限制

|===


== 顯示AutoSupport 有關此功能的資訊

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示AutoSupport 此功能的組態
 a| 
「系統節點AutoSupport 不顯示」搭配「節點」參數



 a| 
檢視接收AutoSupport 到不實訊息的所有位址和URL摘要
 a| 
「顯示系統節點AutoSupport 的目的地」



 a| 
針對AutoSupport 個別觸發事件、顯示哪些資訊會傳送給您的內部支援組織
 a| 
「系統節點AutoSupport 的不全觸發顯示」



 a| 
顯示AutoSupport 錶板配置狀態、以及傳送至不同目的地
 a| 
「系統節點AutoSupport 不全檢查顯示」



 a| 
顯示AutoSupport 詳細的資訊、包括設定的資訊、以及傳送到不同目的地的資訊
 a| 
「系統節點AutoSupport 不完整檢查顯示詳細資料」

|===


== 顯示關於過去AutoSupport 的資訊

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示50 AutoSupport 則最新版的一或多則新聞資訊
 a| 
「系統節點AutoSupport 的不全歷史記錄顯示」



 a| 
顯示AutoSupport 最近產生的資訊、以將核心傾印或效能歸檔檔案上傳至技術支援網站或指定的URI
 a| 
「系統節點AutoSupport 的不完整歷史記錄顯示上傳詳細資料」



 a| 
檢視AutoSupport 資訊資訊、包括針對訊息收集的每個檔案名稱和大小、以及任何錯誤
 a| 
「系統節點AutoSupport 資訊清單顯示」

|===


== 傳送、重新傳送或取消AutoSupport 等字訊息

|===
| 如果您想要... | 使用此命令... 


 a| 
重新傳輸以AutoSupport 其自身的不一致編號識別的本機儲存的不一致訊息AutoSupport

[NOTE]
====
如果您重新傳送AutoSupport 一個消息、且支援部門已收到該訊息、則支援系統不會建立重複的案例。另一方面、如果支援部門未收到該訊息、AutoSupport 則當必要時、該系統會分析訊息並建立案例。

==== a| 
'系統節點AutoSupport 的不全歷史記錄重新傳輸'



 a| 
產生AutoSupport 並傳送一個資訊不全的訊息、例如用於測試目的
 a| 
《系統節點AutoSupport 叫用》

[NOTE]
====
使用「-force」參數傳送訊息、即使AutoSupport 停用了功能。使用「-Uri'」參數將訊息傳送到您指定的目的地、而非設定的目的地。

====


 a| 
取消AutoSupport 訊息
 a| 
「系統節點AutoSupport 的不全歷史記錄取消」

|===
.相關資訊
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令數ONTAP"^]
