---
permalink: system-admin/commands-manage-job-schedules-reference.html 
sidebar: sidebar 
keywords: command, manage, job, schedule, volume, snapshot, copy, cron, interval 
summary: 許多工作（例如Volume Snapshot複本）可設定為在指定的排程上執行。在特定時間執行的排程稱為cron排程（類似於UNIX cron排程）。以時間間隔執行的排程稱為時間間隔排程。您可以使用工作排程命令來管理工作排程。 
---
= 管理工作排程的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
許多工作（例如 Volume Snapshot 複本）都可以設定為在指定的排程上執行。在特定時間執行的排程稱為 _cron 排程（類似 UNIX ） `cron` 排程）。每隔一段時間執行的排程稱為「_interval_排程」。您可以使用 `job schedule` 管理工作排程的命令。

工作排程不會調整為手動變更叢集日期和時間。這些工作會根據目前建立工作的叢集時間或最近執行工作的時間來排程執行。因此、如果您手動變更叢集日期或時間、則應使用 `job show` 和 `job history show` 用於驗證所有排程工作是否已根據您的需求排入佇列並完成的命令。

如果叢集是MetroCluster 支援功能的一部分、則兩個叢集上的工作排程必須相同。因此、如果您建立、修改或刪除工作排程、則必須在遠端叢集上執行相同的作業。

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示所有排程的相關資訊
 a| 
`job schedule show`



 a| 
依排程顯示工作清單
 a| 
`job schedule show-jobs`



 a| 
顯示有關cron排程的資訊
 a| 
`job schedule cron show`



 a| 
顯示有關時間間隔排程的資訊
 a| 
`job schedule interval show`



 a| 
建立cron排程1^
 a| 
`job schedule cron create`



 a| 
建立時間間隔排程
 a| 
`job schedule interval create`

您必須至少指定下列其中一個參數： `-days`、 `-hours`、 `-minutes`或 `-seconds`。



 a| 
修改cron排程
 a| 
`job schedule cron modify`



 a| 
修改時間間隔排程
 a| 
`job schedule interval modify`



 a| 
刪除排程
 a| 
`job schedule delete`



 a| 
刪除cron排程
 a| 
`job schedule cron delete`



 a| 
刪除時間間隔排程
 a| 
`job schedule interval delete`

|===
使用建立工作排程時、從 ONTAP 9.10.1 開始、共 ^1^1 `job schedule cron create` 命令、您可以將虛擬伺服器納入工作排程。

.相關資訊
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令數ONTAP"^]
