---
permalink: system-admin/commands-manage-node-remotely-reference.html 
sidebar: sidebar 
keywords: command, manage, node, remotely, sp, cli, cluster 
summary: 您可以存取節點的SP並執行SP CLI命令、以執行節點管理工作、藉此從遠端管理節點。對於多項常用的遠端節點管理工作、您也可以使用ONTAP 叢集中其他節點的指令執行。有些SP命令是平台專屬的、可能無法在您的平台上使用。 
---
= 用於遠端節點管理的 ONTAP 命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以存取節點的SP並執行SP CLI命令、以執行節點管理工作、藉此從遠端管理節點。對於多項常用的遠端節點管理工作、您也可以使用ONTAP 叢集中其他節點的指令執行。有些SP命令是平台專屬的、可能無法在您的平台上使用。

|===
| 如果您想要... | 使用此SP命令... | 使用此 BMC 命令 ... | 或此ONTAP 指令... 


 a| 
顯示指定SP命令的可用SP命令或子命令
 a| 
`help` [`command`]
 a| 
 a| 



 a| 
顯示SP CLI的目前權限等級
 a| 
`priv show`
 a| 
 a| 



 a| 
設定權限層級、以存取SP CLI的指定模式
 a| 
`priv set` {`admin` | `advanced` | `diag`}
 a| 
 a| 



 a| 
顯示系統日期與時間
 a| 
`date`
 a| 
 a| 
`date`



 a| 
顯示SP記錄的事件
 a| 
`events` {`all` | `info` | `newest` `number` | `oldest number` | `search keyword`}
 a| 
 a| 



 a| 
顯示SP狀態和網路組態資訊
 a| 
`sp status` [`-v` | `-d`]

。 `-v` 選項以詳細格式顯示 SP 統計資料。。 `-d` 選項會將 SP 偵錯記錄新增至顯示器。
 a| 
`bmc status` [`-v` | `-d`]

。 `-v` 選項以詳細格式顯示 SP 統計資料。。 `-d` 選項會將 SP 偵錯記錄新增至顯示器。
 a| 
`system service-processor show`



 a| 
顯示過去1、5和15分鐘內SP已啟動的時間長度、以及執行佇列中的平均工作數
 a| 
`sp uptime`
 a| 
`bmc uptime`
 a| 



 a| 
顯示系統主控台記錄
 a| 
`system log`
 a| 
 a| 



 a| 
顯示SP記錄歸檔或歸檔中的檔案
 a| 
`sp log history show` [`-archive` {`latest` |{`all` | `archive-name`}] [`-dump` {`all` | `file-name`}]
 a| 
`bmc log history show` [`-archive` {`latest` |{`all` | `archive-name`}] [`-dump` {`all` | `file-name`}]
 a| 



 a| 
顯示節點控制器的電源狀態
 a| 
`system power status`
 a| 
 a| 
`system node power show`



 a| 
顯示電池資訊
 a| 
`system battery show`
 a| 
 a| 



 a| 
顯示ACP資訊或擴充器感測器的狀態
 a| 
`system acp` [`show` | `sensors show`]
 a| 
 a| 



 a| 
列出所有系統FRU及其ID
 a| 
`system fru list`
 a| 
 a| 



 a| 
顯示指定FRU的產品資訊
 a| 
`system fru show` `fru_id`
 a| 
 a| 



 a| 
顯示FRU資料歷程記錄
 a| 
`system fru log show` （進階權限層級）
 a| 
 a| 



 a| 
顯示環境感測器的狀態、包括其狀態和目前值
 a| 
`system sensors` 或 `system sensors show`
 a| 
 a| 
`system node environment sensors show`



 a| 
顯示指定感測器的狀態和詳細資料
 a| 
`system sensors get` `sensor_name`

您可以取得 `sensor_name` 使用 `system sensors` 或 `system sensors show` 命令。
 a| 
 a| 



 a| 
顯示SP韌體版本資訊
 a| 
`version`
 a| 
 a| 
`system service-processor image show`



 a| 
顯示SP命令歷程記錄
 a| 
`sp log audit` （進階權限層級）
 a| 
`bmc log audit`
 a| 



 a| 
顯示SP偵錯資訊
 a| 
`sp log debug` （進階權限層級）
 a| 
`bmc log debug` （進階權限層級）
 a| 



 a| 
顯示SP訊息檔案
 a| 
`sp log messages` （進階權限層級）
 a| 
`bmc log messages` （進階權限層級）
 a| 



 a| 
顯示在監視器重設事件上收集系統鑑識的設定、顯示在監視器重設事件期間收集的系統鑑識資訊、或清除收集的系統鑑識資訊
 a| 
`system forensics` [`show` | `log dump` | `log clear`]
 a| 
 a| 



 a| 
登入系統主控台
 a| 
`system console`
 a| 
 a| 
`system node run-console`



 a| 
您應該按Ctrl-D結束系統主控台工作階段。



 a| 
開啟或關閉節點、或執行電源循環（關閉電源然後重新開啟）
 a| 
`system power` `on`
 a| 
 a| 
`system node power on` （進階權限層級）



 a| 
`system power` `off`
 a| 
 a| 



 a| 
`system power` `cycle`
 a| 
 a| 



 a| 
待機電源會持續開啟、讓SP不中斷運作。在關機後再開機之前、會短暫暫停。

[NOTE]
====
使用這些命令來關閉或重新啟動節點、可能會導致節點關機不正確（也稱為 _ 不正常關機 _ ）、無法取代使用 ONTAP 的正常關機 `system node halt` 命令。

====


 a| 
建立核心傾印並重設節點
 a| 
`system core` [`-f`]

。 `-f` 選項會強制建立核心傾印並重設節點。
 a| 
 a| 
`system node coredump trigger`

（進階權限層級）



 a| 
這些命令的作用與按下節點上的「不可遮罩的中斷」（NMI）按鈕相同、導致節點不正常關機、並在停止節點時強制傾印核心檔案。當節點上的 ONTAP 掛起或不回應命令時、這些命令很有用、例如 `system node shutdown`。產生的核心傾印檔案會顯示在的輸出中 `system node coredump show` 命令。只要節點的輸入電源不中斷、SP就會維持運作。



 a| 
使用選擇性指定的BIOS韌體映像（主要、備份或目前）重新開機節點、以從節點開機裝置的毀損映像等問題中恢復
 a| 
`system reset` {`primary` | `backup` | `current`}
 a| 
 a| 
`system node reset` 使用 `-firmware` {`primary` | `backup` | `current`} 參數（進階權限等級）

`system node reset`



 a| 
[NOTE]
====
此作業會導致節點不正常關機。

====
如果未指定BIOS韌體映像、則會使用目前映像進行重新開機。只要節點的輸入電源不中斷、SP就會維持運作。



 a| 
顯示電池韌體自動更新的狀態、或在下次SP開機時啟用或停用電池韌體自動更新
 a| 
`system battery auto_update` [`status` | `enable` | `disable`]

（進階權限層級）
 a| 
 a| 



 a| 
將目前的電池韌體映像與指定的韌體映像進行比較
 a| 
`system battery verify` [`image_URL`]

（進階權限層級）

如果 `image_URL` 未指定、則會使用預設電池韌體映像進行比較。
 a| 
 a| 



 a| 
從指定位置的映像更新電池韌體
 a| 
`system battery flash` `image_URL`

（進階權限層級）

如果自動電池韌體升級程序因故失敗、請使用此命令。
 a| 
 a| 



 a| 
使用指定位置的映像更新SP韌體
 a| 
`sp update` `image_URL image_URL` 不得超過 200 個字元。
 a| 
`bmc update` `image_URL image_URL` 不得超過 200 個字元。
 a| 
`system service-processor image update`



 a| 
重新啟動SP
 a| 
`sp reboot`
 a| 
 a| 
`system service-processor reboot-sp`



 a| 
清除NVRAM Flash內容
 a| 
`system nvram flash clear` （進階權限層級）

當控制器電源關閉時、無法啟動此命令 (`system power off`）。
 a| 
 a| 



 a| 
結束SP CLI
 a| 
`exit`
 a| 
 a| 

|===
如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。
