---
permalink: system-admin/commands-monitor-health-system-reference.html 
sidebar: sidebar 
keywords: command, monitor, health, system, display, status, cli, software, version, switches, alert 
summary: 您可以使用系統健全狀況命令來顯示有關系統資源健全狀況的資訊、回應警示、以及設定未來警示。使用CLI命令可讓您深入檢視設定健全狀況監控的方式資訊。命令的手冊頁包含更多資訊。 
---
= 用於監控系統健全狀況的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「系統健全狀況」命令來顯示有關系統資源健全狀況的資訊、回應警示、以及設定未來警示。使用CLI命令可讓您深入檢視設定健全狀況監控的方式資訊。命令的手冊頁包含更多資訊。



== 顯示系統健全狀況的狀態

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示系統的健全狀況狀態、反映個別健全狀況監視器的整體狀態
 a| 
「System health Status show」（系統健全狀況顯示）



 a| 
顯示子系統的健全狀況狀態、以便進行健全狀況監控
 a| 
「顯示系統健全狀況子系統」

|===


== 顯示節點連線狀態

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示從節點連線至儲存櫃的詳細資料、包括連接埠資訊、HBA連接埠速度、I/O處理量、以及每秒I/O作業速率
 a| 
「儲存櫃顯示連線能力」

使用「-instance」參數顯示每個機櫃的詳細資訊。



 a| 
顯示磁碟機和陣列LUN的相關資訊、包括可用空間、機櫃和機櫃編號、以及擁有節點名稱
 a| 
「磁碟展示」

使用「-instance」參數顯示每個磁碟機的詳細資訊。



 a| 
顯示儲存櫃連接埠的詳細資訊、包括連接埠類型、速度和狀態
 a| 
「展示連接埠」

使用「-instance」參數來顯示每個介面卡的詳細資訊。

|===


== 管理叢集和管理網路交換器的探索

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示叢集監控的交換器
 a| 
「系統叢集交換器顯示」



 a| 
顯示叢集目前監控的交換器、包括您刪除的交換器（如命令輸出中的「原因」欄所示）、以及網路存取叢集和管理網路交換器所需的組態資訊。

此命令可在進階權限層級使用。
 a| 
「系統叢集交換器show-all」



 a| 
設定探索未探索到的交換器
 a| 
「系統叢集交換器建立」



 a| 
修改叢集監控的交換器相關資訊（例如、裝置名稱、IP位址、SNMP版本和社群字串）
 a| 
「系統叢集交換器修改」



 a| 
停用交換器監控
 a| 
「系統叢集交換器修改-停用監控」



 a| 
顯示健全狀況監視器輪詢切換以收集資訊的時間間隔
 a| 
「系統叢集交換器輪詢時間間隔顯示」



 a| 
修改健全狀況監視器輪詢切換以收集資訊的時間間隔。

此命令可在進階權限層級使用。
 a| 
「系統叢集交換器輪詢時間間隔修改」



 a| 
停用探索及監控交換器、並刪除交換器組態資訊
 a| 
「系統叢集交換器刪除」



 a| 
永久移除儲存在資料庫中的交換器組態資訊（如此會重新啟用交換器的自動探索）
 a| 
「系統叢集交換器刪除強制」



 a| 
啟用自動記錄功能、以AutoSupport 利發送資訊。

此命令可在進階權限層級使用。
 a| 
「系統叢集交換器記錄」

|===


== 回應產生的警示

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示已產生警示的相關資訊、例如觸發警示的資源和節點、以及警示的嚴重性和可能原因
 a| 
「系統健全狀況警示顯示」



 a| 
顯示每個產生警示的相關資訊
 a| 
「系統健全狀況警示顯示-instance」



 a| 
表示有人正在處理警示
 a| 
'系統健全狀況警示修改'



 a| 
確認警示
 a| 
「系統健全狀況警示修改-Acknowledge」



 a| 
隱藏後續警示、使其不影響子系統的健全狀況
 a| 
'系統健全狀況警示修改-suppress'



 a| 
刪除未自動清除的警示
 a| 
刪除系統健全狀況警示



 a| 
顯示AutoSupport 上週觸發警示的有關資訊、例如、判斷警示是否觸發AutoSupport 了一個故障訊息
 a| 
「系統健全AutoSupport 狀況不受歷史影響」

|===


== 設定未來警示

|===
| 如果您想要... | 使用此命令... 


 a| 
啟用或停用控制特定資源狀態是否發出特定警示的原則
 a| 
《系統健全狀況原則定義修改》

|===


== 顯示如何設定健全狀況監控的相關資訊

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示健全狀況監視器的相關資訊、例如其節點、名稱、子系統和狀態
 a| 
「System health config show」

[NOTE]
====
使用「-instance」參數顯示每個健全狀況監視器的詳細資訊。

====


 a| 
顯示健全狀況監視器可能產生之警示的相關資訊
 a| 
「系統健全狀況警示定義顯示」

[NOTE]
====
使用「-instance」參數顯示每個警示定義的詳細資訊。

====


 a| 
顯示有關健全狀況監視原則的資訊、以決定何時發出警示
 a| 
「系統健全狀況原則定義顯示」

[NOTE]
====
使用"-instance"參數顯示每個原則的詳細資訊。使用其他參數來篩選警示清單、例如依原則狀態（已啟用或未啟用）、健全狀況監視器、警示等。

====
|===


== 次要版本之間的降級軟體版本

將叢集從Data ONTAP 停止執行至Data ONTAP 停止執行8.2時ONTAP 、會清除刪除的交換器記錄。如果自動發現的交換器不支援健全狀況監控、也會將「model」欄設為「other」。

|===
| 如果您想要... | 使用此命令... 


 a| 
降級軟體版本命令
 a| 
「系統叢集交換器準備降級」

|===