---
permalink: system-admin/commands-manage-jobs-reference.html 
sidebar: sidebar 
keywords: command, manage, jobs, queue, cluster, resources 
summary: 工作會放入工作佇列、並在資源可用時於背景執行。如果工作佔用過多的叢集資源、您可以將其停止或暫停、直到叢集需求減少為止。您也可以監控及重新啟動工作。 
---
= 管理工作的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
工作會放入工作佇列、並在資源可用時於背景執行。如果工作佔用過多的叢集資源、您可以將其停止或暫停、直到叢集需求減少為止。您也可以監控及重新啟動工作。

當您輸入命令以叫用工作時、通常會通知您工作已排入佇列、然後返回CLI命令提示字元。不過、有些命令會回報工作進度、而且在工作完成之前、不會返回CLI命令提示字元。在這些情況下、您可以按Ctrl-C將工作移至背景。

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示所有工作的相關資訊
 a| 
「工作展示」



 a| 
顯示每個節點的工作相關資訊
 a| 
「按節點顯示工作」



 a| 
顯示有關叢集關聯工作的資訊
 a| 
「工作展示叢集」



 a| 
顯示已完成工作的相關資訊
 a| 
「工作表現已完成」



 a| 
顯示有關工作記錄的資訊
 a| 
「工作歷史展」

叢集中每個節點最多可儲存25、000筆工作記錄。因此、嘗試顯示完整的工作記錄可能需要很長時間。為了避免可能需要長時間等待、您應該依節點、儲存虛擬機器（SVM）或記錄ID來顯示工作。



 a| 
顯示私有工作清單
 a| 
「工作私人展」（進階權限等級）



 a| 
顯示已完成私有工作的相關資訊
 a| 
「工作私人展示已完成」（進階權限層級）



 a| 
顯示工作管理員初始化狀態的相關資訊
 a| 
「jobinitstate show」（進階權限層級）



 a| 
監控工作進度
 a| 
「工作觀察進度」



 a| 
監控私有工作的進度
 a| 
「工作私人監看進度」（進階權限層級）



 a| 
暫停工作
 a| 
作業暫停



 a| 
暫停私有工作
 a| 
「工作私人暫停」（進階權限層級）



 a| 
恢復暫停的工作
 a| 
《求職簡歷》



 a| 
恢復暫停的私有工作
 a| 
「工作私人簡歷」（進階權限層級）



 a| 
停止工作
 a| 
作業停止



 a| 
停止私有工作
 a| 
「工作私人停機」（進階權限層級）



 a| 
刪除工作
 a| 
作業刪除



 a| 
刪除私有工作
 a| 
「職務私人刪除」（進階權限層級）



 a| 
將叢集關聯的工作與擁有該工作的不可用節點解除關聯、以便其他節點可以取得該工作的擁有權
 a| 
「求職」（進階權限等級）

|===
[NOTE]
====
您可以使用「EVENT log show」命令來判斷已完成工作的結果。

====
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令數ONTAP"^]
