---
permalink: system-admin/commands-monitor-health-system-reference.html 
sidebar: sidebar 
keywords: command, monitor, health, system, display, status, cli, software, version, switches, alert 
summary: 您可以使用系統健全狀況命令來顯示有關系統資源健全狀況的資訊、回應警示、以及設定未來警示。使用CLI命令可讓您深入檢視設定健全狀況監控的方式資訊。命令的手冊頁包含更多資訊。 
---
= 用於監控系統健全狀況的命令
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `system health`命令來顯示系統資源健全狀況的相關資訊，回應警示，以及設定未來的警示。使用CLI命令可讓您深入檢視設定健全狀況監控的方式資訊。如link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=system+health["指令參考資料ONTAP"^]需詳細 `system health`資訊，請參閱。



== 顯示系統健全狀況的狀態

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示系統的健全狀況狀態、反映個別健全狀況監視器的整體狀態
 a| 
`system health status show`



 a| 
顯示子系統的健全狀況狀態、以便進行健全狀況監控
 a| 
`system health subsystem show`

|===


== 顯示節點連線狀態

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示從節點連線至儲存櫃的詳細資料、包括連接埠資訊、HBA連接埠速度、I/O處理量、以及每秒I/O作業速率
 a| 
`storage shelf show -connectivity`

使用 `-instance` 顯示每個機櫃詳細資訊的參數。



 a| 
顯示磁碟機和陣列LUN的相關資訊、包括可用空間、機櫃和機櫃編號、以及擁有節點名稱
 a| 
`storage disk show`

使用 `-instance` 參數顯示每個磁碟機的詳細資訊。



 a| 
顯示儲存櫃連接埠的詳細資訊、包括連接埠類型、速度和狀態
 a| 
`storage port show`

使用 `-instance` 參數以顯示每個介面卡的詳細資訊。

|===


== 管理叢集、儲存設備及管理網路交換器的探索

[cols="3*"]
|===
| 如果您想要... | 使用此命令..（更新版本：ONTAP | 使用此命令..（更新版本：9.7）ONTAP 


 a| 
顯示叢集監控的交換器
 a| 
`system switch ethernet show`
 a| 
`system cluster-switch show`



 a| 
顯示叢集目前監控的交換器、包括您刪除的交換器（如命令輸出中的「原因」欄所示）、以及網路存取叢集和管理網路交換器所需的組態資訊。

此命令可在進階權限層級使用。
 a| 
`system switch ethernet show-all`
 a| 
`system cluster-switch show-all`



 a| 
設定探索未探索到的交換器
 a| 
`system switch ethernet create`
 a| 
`system cluster-switch create`



 a| 
修改叢集監控的交換器相關資訊（例如、裝置名稱、IP位址、SNMP版本和社群字串）
 a| 
`system switch ethernet modify`
 a| 
`system cluster-switch modify`



 a| 
停用交換器監控
 a| 
`system switch ethernet modify -disable-monitoring`
 a| 
`system cluster-switch modify -disable-monitoring`



 a| 
停用探索及監控交換器、並刪除交換器組態資訊
 a| 
`system switch ethernet delete`
 a| 
`system cluster-switch delete`



 a| 
永久移除儲存在資料庫中的交換器組態資訊（如此會重新啟用交換器的自動探索）
 a| 
`system switch ethernet delete -force`
 a| 
`system cluster-switch delete -force`



 a| 
啟用自動記錄功能、以AutoSupport 利發送資訊。
 a| 
`system switch ethernet log`
 a| 
`system cluster-switch log`

|===


== 回應產生的警示

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示已產生警示的相關資訊、例如觸發警示的資源和節點、以及警示的嚴重性和可能原因
 a| 
`system health alert show`



 a| 
顯示每個產生警示的相關資訊
 a| 
`system health alert show -instance`



 a| 
表示有人正在處理警示
 a| 
`system health alert modify`



 a| 
確認警示
 a| 
`system health alert modify -acknowledge`



 a| 
隱藏後續警示、使其不影響子系統的健全狀況
 a| 
`system health alert modify -suppress`



 a| 
刪除未自動清除的警示
 a| 
`system health alert delete`



 a| 
顯示AutoSupport 上週觸發警示的有關資訊、例如、判斷警示是否觸發AutoSupport 了一個故障訊息
 a| 
`system health autosupport trigger history show`

|===


== 設定未來警示

|===
| 如果您想要... | 使用此命令... 


 a| 
啟用或停用控制特定資源狀態是否發出特定警示的原則
 a| 
`system health policy definition modify`

|===


== 顯示如何設定健全狀況監控的相關資訊

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示健全狀況監視器的相關資訊、例如其節點、名稱、子系統和狀態
 a| 
`system health config show`

[NOTE]
====
使用 `-instance` 顯示每個健全狀況監視器的詳細資訊的參數。

====


 a| 
顯示健全狀況監視器可能產生之警示的相關資訊
 a| 
`system health alert definition show`

[NOTE]
====
使用 `-instance` 顯示每個警示定義的詳細資訊的參數。

====


 a| 
顯示有關健全狀況監視原則的資訊、以決定何時發出警示
 a| 
`system health policy definition show`

[NOTE]
====
使用 `-instance` 參數以顯示每個原則的詳細資訊。使用其他參數來篩選警示清單、例如依原則狀態（已啟用或未啟用）、健全狀況監視器、警示等。

====
|===
如需有關本程序中所述命令link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]的詳細資訊，請參閱。
