---
permalink: system-admin/configure-saml-authentication-task.html 
sidebar: sidebar 
keywords: tdp, ldap, identity, provider, saml, security, assertion, markup, lanaguage, active, directory 
summary: 從ONTAP 推出支援支援功能的支援功能9.3開始、您可以設定網路服務的安全聲明標記語言（SAML）驗證。設定並啟用SAML驗證時、使用者會由外部身分識別供應商（IDP）進行驗證、而非由Active Directory和LDAP等目錄服務供應商進行驗證。 
---
= 設定SAML驗證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從ONTAP 推出支援支援功能的支援功能9.3開始、您可以設定網路服務的安全聲明標記語言（SAML）驗證。設定並啟用SAML驗證時、使用者會由外部身分識別供應商（IDP）進行驗證、而非由Active Directory和LDAP等目錄服務供應商進行驗證。

.您需要的產品
* 您必須已設定SAML驗證的IDP。
* 您必須擁有IDP URI。


.關於這項工作
* SAML 驗證僅適用於 `http` 和 `ontapi` 應用程式：
+
。 `http` 和 `ontapi` 應用程式由下列 Web 服務使用：服務處理器基礎架構、 ONTAP API 或系統管理員。

* SAML驗證僅適用於存取管理SVM。


.步驟
. 建立SAML組態、ONTAP 以便讓整個程序能夠存取IDP中繼資料：
+
`*security saml-sp create -idp-uri _idp_uri_ -sp-host _ontap_host_name_*`

+
`idp_uri` 是 IDP 主機的 FTP 或 HTTP 位址、可從其中下載 IDP 中繼資料。

+
`ontap_host_name` 是 SAML 服務供應商主機的主機名稱或 IP 位址、在此情況下為 ONTAP 系統。根據預設、會使用叢集管理LIF的IP位址。

+
您可以選擇性地提供ONTAP 伺服器的驗證資訊。根據預設ONTAP 、會使用「驗證」Web伺服器憑證資訊。

+
[listing]
----
cluster_12::> security saml-sp create -idp-uri https://scspr0235321001.gdl.englab.netapp.com/idp/shibboleth -verify-metadata-server false

Warning: This restarts the web server. Any HTTP/S connections that are active
         will be disrupted.
Do you want to continue? {y|n}: y
[Job 179] Job succeeded: Access the SAML SP metadata using the URL:
https://10.63.56.150/saml-sp/Metadata

Configure the IdP and Data ONTAP users for the same directory server domain to ensure that users are the same for different authentication methods. See the "security login show" command for the Data ONTAP user configuration.
----
+
畫面ONTAP 會顯示存取主機中繼資料的URL。

. 在IDP主機上、使用ONTAP 不受支援的中繼資料來設定IDP。
+
如需設定IDP的詳細資訊、請參閱IDP文件。

. 啟用SAML組態：
+
`*security saml-sp modify -is-enabled true*`

+
存取的任何現有使用者 `http` 或 `ontapi` 應用程式會自動設定以進行 SAML 驗證。

. 如果您想要為建立使用者 `http` 或 `ontapi` 設定 SAML 之後的應用程式、請將 SAML 指定為新使用者的驗證方法。
+
.. 使用 SAML 驗證為新使用者建立登入方法：
+
`*security login create -user-or-group-name _user_name_ -application [http | ontapi] -authentication-method saml -vserver _svm_name_*`
+
[listing]
----
cluster_12::> security login create -user-or-group-name admin1 -application http -authentication-method saml -vserver  cluster_12
----
.. 確認已建立使用者項目：
+
`*security login show*`

+
[listing]
----
cluster_12::> security login show

Vserver: cluster_12
                                                                 Second
User/Group                 Authentication                 Acct   Authentication
Name           Application Method        Role Name        Locked Method
-------------- ----------- ------------- ---------------- ------ --------------
admin          console     password      admin            no     none
admin          http        password      admin            no     none
admin          http        saml          admin            -      none
admin          ontapi      password      admin            no     none
admin          ontapi      saml          admin            -      none
admin          service-processor
                           password      admin            no     none
admin          ssh         password      admin            no     none
admin1         http        password      backup           no     none
**admin1         http        saml          backup           -      none**
----




.相關資訊
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令數ONTAP"^]
