---
permalink: system-admin/configure-discovery-cluster-management-switches-task.html 
sidebar: sidebar 
keywords: configuring, discovery, cluster, management, network, switches, cisco, discovery, protocol, cdp, switch, health 
summary: 叢集交換器健全狀況監視器會自動嘗試使用Cisco探索傳輸協定（CDP）來探索叢集和管理網路交換器。如果健全狀況監視器無法自動探索交換器、或您不想使用CDP進行自動探索、則必須設定健全狀況監視器。 
---
= 設定 ONTAP 叢集和管理網路交換器的探索
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
叢集交換器健全狀況監視器會自動嘗試使用Cisco探索傳輸協定（CDP）來探索叢集和管理網路交換器。如果健全狀況監視器無法自動探索交換器、或您不想使用CDP進行自動探索、則必須設定健全狀況監視器。

.關於這項工作
。 `system cluster-switch show` 命令會列出健全狀況監視器探索到的交換器。如果您在該清單中沒有看到您預期看到的交換器、則健全狀況監視器將無法自動探索它。

.步驟
. 如果您要使用CDP進行自動探索、請執行下列動作：
+
.. 確定交換器上已啟用Cisco探索傳輸協定（CDP）。
+
請參閱交換器文件以取得相關指示。

.. 在叢集中的每個節點上執行下列命令、以驗證CDP是否已啟用或停用：
+
`*run -node _node_name_ -command options cdpd.enable*`

+
如果已啟用CDP、請前往步驟d如果停用CDP、請前往步驟C

.. 執行下列命令以啟用CDP：
+
`*run -node _node_name_ -command options cdpd.enable on*`

+
請等待五分鐘、然後再繼續下一步。

.. 使用 `system cluster-switch show` 命令來驗證 ONTAP 現在是否可以自動探索交換器。


. 如果健全狀況監視器無法自動探索交換器、請使用 `system cluster-switch create` 設定交換器探索的命令：
+
[listing]
----
cluster1::> system cluster-switch create -device switch1 -address 192.0.2.250 -snmp-version SNMPv2c -community cshm1! -model NX5020 -type cluster-network
----
+
請等待五分鐘、然後再繼續下一步。

. 使用 `system cluster-switch show` 命令來驗證 ONTAP 是否能探索您新增資訊的交換器。


.完成後
確認健全狀況監視器可以監控您的交換器。
