---
permalink: system-admin/create-banner-task.html 
sidebar: sidebar 
keywords: create, banner, svm, access, cluster, ssh, session 
summary: 您可以建立橫幅，向嘗試在主控台或 SSH 工作階段中存取叢集或 SVM 的人顯示訊息。 
---
= 建立 ONTAP 登入橫幅
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以建立橫幅、向嘗試存取叢集或SVM的人顯示訊息。橫幅會顯示在主控台工作階段（僅限叢集存取）或SSH工作階段（用於叢集或SVM存取）中、然後才會提示使用者進行驗證。

.步驟
. 使用 `security login banner modify` 建立叢集或 SVM 橫幅的命令：
+
|===
| 如果您想要... | 然後... 


 a| 
指定單一行的訊息
 a| 
使用 `-message`「」[.code]``<text>``參數來指定文字。



 a| 
在訊息中加入新行（也稱為行尾）
 a| 
請使用命令而不使用 `-message` 或 `-uri` 用於啟動互動模式以編輯橫幅的參數。



 a| 
從橫幅使用的位置上傳內容
 a| 
使用 `-uri` 指定內容 FTP 或 HTTP 位置的參數。

|===
+
橫幅的大小上限為2、048位元組、包括換行字元。

+
使用建立的橫幅 `-uri` 參數為靜態。系統不會自動重新整理以反映來源內容的後續變更。

+
針對叢集建立的橫幅也會針對所有沒有現有橫幅的SVM顯示。任何後續建立的SVM橫幅都會覆寫該SVM的叢集層級橫幅。指定 `-message` 雙引號內有連字號的參數 (`"-"`）對於 SVM 、 SVM 會將 SVM 重設為使用叢集層級橫幅。

. 使用顯示橫幅、確認已建立橫幅 `security login banner show` 命令。
+
指定 `-message` 含有空白字串的參數 (`""`）顯示沒有內容的橫幅。

+
指定 `-message` 參數 `"-"` 顯示未設定橫幅的所有（管理或資料） SVM 。



.建立橫幅廣告的範例
以下範例使用非互動模式來建立「叢集1」叢集的橫幅：

[listing]
----
cluster1::> security login banner modify -message "Authorized users only!"

cluster1::>
----
以下範例使用互動模式來建立 SVM 的橫幅 `svm1`：

[listing]
----
cluster1::> security login banner modify -vserver svm1

Enter the message of the day for Vserver "svm1".
Max size: 2048. Enter a blank line to terminate input. Press Ctrl-C to abort.
0        1         2         3         4         5         6         7         8
12345678901234567890123456789012345678901234567890123456789012345678901234567890
The svm1 SVM is reserved for authorized users only!


cluster1::>
----
下列範例顯示已建立的橫幅廣告：

[listing]
----
cluster1::> security login banner show
Vserver: cluster1
Message
-----------------------------------------------------------------------------
Authorized users only!

Vserver: svm1
Message
-----------------------------------------------------------------------------
The svm1 SVM is reserved for authorized users only!

2 entries were displayed.

cluster1::>
----
.相關資訊
* xref:manage-banner-reference.adoc[管理橫幅]
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-banner-modify.html["修改安全登入橫幅"^]
* link:https://docs.netapp.com/us-en/ontap-cli/security-login-banner-show.html["安全登入橫幅展示"^]

