---
permalink: system-admin/enable-telnet-rsh-access-cluster-task.html 
sidebar: sidebar 
keywords: enable, telnet, rsh, access, cluster, mgmt, management, service, policy 
summary: 最佳安全性做法是預設停用 Telnet 和 RSH 。若要讓叢集能夠接受 Telnet 或 RSH 要求、您必須在預設管理服務原則中啟用該服務。 
---
= 啟用對叢集的遠端登入或RSH存取
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
最佳安全性做法是預設停用 Telnet 和 RSH 。若要讓叢集能夠接受 Telnet 或 RSH 要求、您必須在預設管理服務原則中啟用該服務。

.關於這項工作
* rsh不是安全的傳輸協定。
+
您應該考慮使用SSH來存取叢集。SSH提供安全的遠端Shell和互動式網路工作階段。

* 支援每個節點最多50個並行的RSH工作階段。ONTAP
+
如果叢集管理LIF位於節點上、則會與節點管理LIF共用此限制。

+
如果傳入連線速度高於每秒10次、服務會暫時停用60秒。

* rsh 命令需要進階權限。


.步驟
. 確認已啟用 RSH 或 Telnet 安全性通訊協定：
+
`security protocol show`

+
.. 如果啟用了 RSH 或 Telnet 安全性通訊協定、請繼續下一步。
.. 如果未啟用 RSH 或 Telnet 安全性通訊協定、請使用下列命令加以啟用：
+
`security protocol modify -application <rsh/telnet> -enabled true`



. 確認 `management-rsh-server` 或 `management-telnet-server` 服務存在於管理階層中：
+
`network interface show -services management-rsh-server`

+
或

+
`network interface show -services management-telnet-server`

+
.. 如果 `management-rsh-server` 或 `management-telnet-server` 服務存在、請繼續下一步。
.. 如果 `management-rsh-server` 或 `management-telnet-server` 服務不存在、請使用下列命令加以新增：
+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-rsh-server`

+
`network interface service-policy add-service -vserver cluster1 -policy default-management -service management-telnet-server`




