---
permalink: system-admin/find-config-recover-cluster-task.html 
sidebar: sidebar 
keywords: cluster, configuration, recover, node, backup, file 
summary: 您可以使用叢集中節點或叢集組態備份檔案的組態來還原叢集。 
---
= 找到 ONTAP 叢集組態備份檔案以還原叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用叢集中節點或叢集組態備份檔案的組態來還原叢集。

.步驟
. 選擇要恢復叢集的組態類型。
+
** 叢集中的節點
+
如果叢集由多個節點組成、而其中一個節點在叢集處於所需組態時具有叢集組態、則您可以使用儲存在該節點上的組態來還原叢集。

+
在大多數情況下、包含複寫環的節點、以及最新的交易ID、是還原叢集組態的最佳節點。。 `cluster ring show` 進階權限層級的命令可讓您檢視叢集中每個節點上可用的複寫環清單。

** 叢集組態備份檔案
+
如果您無法識別具有正確叢集組態的節點、或叢集是由單一節點所組成、則可以使用叢集組態備份檔案來還原叢集。

+
如果您從組態備份檔案中還原叢集、則自備份後所做的任何組態變更都將遺失。您必須在恢復後解決組態備份檔案與目前組態之間的任何差異。請參閱知識庫文章 link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_Configuration_Backup_Resolution_Guide["《組態備份解決方案指南》ONTAP"] 以取得疑難排解指引。



. 如果您選擇使用叢集組態備份檔案、請將檔案提供給您打算用來還原叢集的節點。
+
|===
| 如果組態備份檔案位於... | 然後... 


 a| 
位於遠端URL
 a| 
使用 `system configuration backup download` 進階權限層級的命令、將其下載至還原節點。



 a| 
在叢集中的節點上
 a| 
.. 使用 `system configuration backup show` 進階權限層級的命令、可尋找叢集組態備份檔案、該檔案是在叢集處於所需組態時建立的。
.. 如果叢集組態備份檔案未位於您打算用來恢復叢集的節點上、請使用 `system configuration backup copy` 命令將其複製到恢復節點。


|===


如link:https://docs.netapp.com/us-en/ontap-cli/cluster-ring-show.html["指令參考資料ONTAP"^]需詳細 `cluster ring show`資訊，請參閱。
