---
permalink: system-admin/health-monitors-concept.html 
sidebar: sidebar 
keywords: available, cluster, health, monitors, errors, detect, events, alerts, delete 
summary: 有多個健全狀況監視器可監控叢集的不同部分。健全狀況監視器可ONTAP 偵測事件、傳送警示給您、並在清除事件時刪除事件、協助您從錯誤中恢復。 
---
= 瞭解可用的 ONTAP 叢集健全狀況監視器
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
有多個健全狀況監視器可監控叢集的不同部分。健全狀況監視器可ONTAP 偵測事件、傳送警示給您、並在清除事件時刪除事件、協助您從錯誤中恢復。

|===
| 健全狀況監視器名稱（識別碼） | 子系統名稱（識別碼） | 目的 


 a| 
乙太網路交換器
 a| 
交換器（交換器健全狀況）
 a| 
ONTAP 乙太網路交換器健全狀況監視器（ CSHM ）可監控叢集和儲存網路交換器的狀態，同時收集記錄以供分析。根據預設， CSHM 會每 5 分鐘透過 SNMPv2c 輪詢每個交換器，以更新資源表，其中包含支援性，監控狀態，溫度感測器， CPU 使用率，介面組態和連線，叢集交換器備援，以及風扇和電源供應器作業等資訊。此外，如果已設定， CSHM 會每小時透過 SSH/SCP 收集記錄，並透過 AutoSupport 傳送以供進一步分析。CSHM 也可根據要求，使用 SSH/SCP 執行更詳細的技術支援記錄收集。

如需詳細資訊、請參閱 link:https://docs.netapp.com/us-en/ontap-systems-switches/switch-cshm/config-overview.html["交換器健全狀況監控"^] 。



 a| 
支援的架構MetroCluster
 a| 
交換器
 a| 
監控MetroCluster 支援此功能的後端架構拓撲、並偵測錯誤的組態、例如不正確的佈線和分區、以及ISL故障。



 a| 
系統健全狀況MetroCluster
 a| 
互連、RAID和儲存設備
 a| 
監控FC-VI介面卡、FC啟動器介面卡、左後集合體和磁碟、以及叢集間連接埠



 a| 
節點連線（節點連線）
 a| 
CIFS不中斷營運（CIF-NDO）
 a| 
監控SMB連線、以確保不中斷營運至Hyper-V應用程式。



 a| 
儲存設備（SAS連線）
 a| 
在節點層級監控磁碟櫃、磁碟和介面卡、以取得適當的路徑和連線。



 a| 
系統
 a| 
不適用
 a| 
彙總來自其他健全狀況監視器的資訊。



 a| 
系統連線（系統連線）
 a| 
儲存設備（SAS連線）
 a| 
監控叢集層級的磁碟櫃、以取得通往兩個HA叢集節點的適當路徑。

|===