---
permalink: system-admin/install-ca-signed-server-certificate-cluster-task.html 
sidebar: sidebar 
keywords: install, ca, signed, server, certificate, cluster, ssl, svm, sotrage, virtual, machine, administrator 
summary: 若要讓SSL伺服器將叢集或儲存虛擬機器（SVM）驗證為SSL用戶端、請在叢集或SVM上安裝具有用戶端類型的數位憑證。然後將用戶端CA憑證提供給SSL伺服器管理員、以便在伺服器上安裝。 
---
= 為叢集安裝CA簽署的伺服器憑證
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要讓SSL伺服器將叢集或儲存虛擬機器（SVM）驗證為SSL用戶端、請在叢集或SVM上安裝具有用戶端類型的數位憑證。然後將用戶端CA憑證提供給SSL伺服器管理員、以便在伺服器上安裝。

.您需要的產品
您必須已在叢集上安裝 SSL 伺服器的根憑證、或是在上安裝 SVM `server-ca` 憑證類型。

.步驟
. 若要使用自我簽署的數位憑證進行用戶端驗證、請使用 `security certificate create` 命令 `type client` 參數。
. 若要使用CA簽署的數位憑證進行用戶端驗證、請完成下列步驟：
+
.. 使用安全性憑證產生數位憑證簽署要求（ CSR ） `generate-csr` 命令。
+
包含憑證要求和私密金鑰的CSR輸出會顯示出來、並提醒您將輸出複製到檔案、以供日後參考。ONTAP

.. 將CSR輸出的憑證要求以電子形式（例如電子郵件）傳送至信任的CA進行簽署。
+
您應該保留一份私密金鑰和CA簽署憑證的複本、以供日後參考。

+
在處理您的要求之後、CA會將簽署的數位憑證傳送給您。

.. 使用安裝 CA 簽署的憑證 `security certificate install` 命令 `-type client` 參數。
.. 在系統提示時輸入憑證和私密金鑰、然後按* Enter *。
.. 在出現提示時輸入任何其他根或中繼憑證、然後按* Enter *。
+
如果從信任的根CA開始且以核發給您的SSL憑證結束的憑證鏈結遺失中繼憑證、您可以在叢集或SVM上安裝中繼憑證。中繼憑證是由信任的根所核發的次要憑證、專門用於發行終端實體伺服器憑證。結果是憑證鏈結從信任的根CA開始、經過中繼憑證、最後以核發給您的SSL憑證結束。



. 提供 `client-ca` 將叢集或 SVM 的憑證交給 SSL 伺服器的管理員、以便在伺服器上安裝。
+
的安全性憑證 show 命令 `-instance` 和 `-type client-ca` 參數會顯示 `client-ca` 憑證資訊。


