---
permalink: system-admin/license-types-licensed-method-concept.html 
sidebar: sidebar 
keywords: license, types, method, cluster, manage, install, add, nlf 
summary: 瞭解授權類型和授權方法、有助於管理叢集中的授權。 
---
= 授權類型與授權方法
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
瞭解授權類型和授權方法、有助於管理叢集中的授權。



== 授權類型

一個套件可以在叢集中安裝下列一或多個授權類型。。 `system license show` 命令會顯示套件的已安裝授權類型。

* 標準授權 (`license`）
+
標準授權是節點鎖定的授權。它是針對具有特定系統序號（也稱為_Controller序號_）的節點發出的。標準授權僅適用於序號相符的節點。

+
安裝標準的節點鎖定授權可讓節點享有授權功能。若要讓叢集使用授權功能、至少必須授權一個節點才能使用此功能。在沒有功能應有權利的節點上使用授權功能可能會違反法規。

* 站台授權 (`site`）
+
站台授權不會繫結至特定的系統序號。當您安裝站台授權時、叢集中的所有節點都有權使用授權功能。。 `system license show` 命令會以叢集序號顯示站台授權。

+
如果您的叢集擁有站台授權、而您從叢集移除節點、則節點不會隨附站台授權、也不再有權使用授權功能。如果您將節點新增至具有站台授權的叢集、則節點會自動獲得站台授權所授予的功能。

* 評估授權 (`demo`）
+
評估版授權是一種在一段時間後過期的暫用授權（如所示） `system license show` 命令）。它可讓您在不購買授權的情況下、嘗試特定的軟體功能。這是全叢集的授權、並未繫結至節點的特定序號。

+
如果叢集具有套件的評估授權、而您從叢集移除節點、則節點不會隨附評估授權。





== 授權方法

您可以同時安裝叢集範圍的授權（ `site` 或 `demo` 類型）和節點鎖定的授權（ `license` 類型）。因此、安裝的套件在叢集中可以有多種授權類型。但是、對於叢集而言、套件只有一個_licensed方法。。 `licensed method` 的欄位 `system license status show` 命令會顯示套件使用的權利。此命令會決定授權方法、如下所示：

* 如果套件在叢集中只安裝一種授權類型、則安裝的授權類型為授權方法。
* 如果套件在叢集中未安裝任何授權、則授權方法為 `none`。
* 如果某個套件在叢集中安裝了多種授權類型、則授權方法會依照授權類型的下列優先順序來決定 --`site`、 `license`和 `demo`。
+
例如：

+
** 如果您擁有站台授權、標準授權和套件評估授權、叢集中套件的授權方法就是 `site`。
** 如果您擁有套件的標準授權和評估授權、叢集中套件的授權方法就是 `license`。
** 如果您只有套件的試用版授權、叢集中套件的授權方法就是 `demo`。



