---
permalink: system-admin/manage-core-dumps-concept.html 
sidebar: sidebar 
keywords: manage, core, dump, cluster, administrator, node, panic, configure, attributes, save, display, segment, upload, delete 
summary: 當節點出現問題時、會發生核心傾印、系統會建立核心傾印檔案、以便技術支援人員疑難排解問題。您可以設定或顯示核心傾印屬性。您也可以儲存、顯示、區段、上傳或刪除核心傾印檔案。 
---
= 管理核心傾印（僅限叢集管理員）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當節點出現問題時、會發生核心傾印、系統會建立核心傾印檔案、以便技術支援人員疑難排解問題。您可以設定或顯示核心傾印屬性。您也可以儲存、顯示、區段、上傳或刪除核心傾印檔案。

您可以使用下列方法來管理核心傾印：

* 設定核心傾印並顯示組態設定
* 顯示核心傾印的基本資訊、狀態和屬性
+
核心傾印檔案和報告會儲存在中 `/mroot/etc/crash/` 節點目錄。您可以使用來顯示目錄內容 `system node coredump` 命令或 Web 瀏覽器。

* 儲存核心傾印內容、並將儲存的檔案上傳至指定位置或技術支援
+
此功能可防止您在接管、集合體重新配置或還原期間、開始儲存核心傾印檔案。ONTAP

* 刪除不再需要的核心傾印檔案




== 管理核心傾印的命令

您可以使用 `system node coredump config` 管理核心傾印組態的命令 `system node coredump` 管理核心傾印檔案的命令、以及 `system node coredump reports` 管理應用程式核心報告的命令。

|===
| 如果您想要... | 使用此命令... 


 a| 
設定核心傾印
 a| 
`system node coredump config modify`



 a| 
顯示核心傾印的組態設定
 a| 
`system node coredump config show`



 a| 
顯示核心傾印的基本資訊
 a| 
`system node coredump show`



 a| 
重新開機節點時、手動觸發核心傾印
 a| 
`system node reboot` 兩者兼具 `-dump` 和 `-skip-lif-migration-before-reboot` 參數

[NOTE]
====
連結： https://docs.netapp.com/us-en/ontap-cli-9141//system-node-reboot.html#parameters[`skip-lif-migration-before-reboot`] 參數指定在重新開機之前略過 LIF 移轉。

====


 a| 
當您關閉節點時、手動觸發核心傾印
 a| 
`system node halt` 兩者兼具 `-dump` 和 `-skip-lif-migration-before-shutdown` 參數

[NOTE]
====
連結： https://docs.netapp.com/us-en/ontap-cli-9141/system-node-halt.html#parameters[`skip-lif-migration-before-shutdown`] 參數指定在關機之前略過 LIF 移轉。

====


 a| 
儲存指定的核心傾印
 a| 
`system node coredump save`



 a| 
儲存指定節點上所有未儲存的核心傾印
 a| 
`system node coredump save-all`



 a| 
使用AutoSupport 您指定的核心傾印檔案來產生及傳送一個不確定的訊息
 a| 
`system node autosupport invoke-core-upload`

[NOTE]
====
。 `-uri` 選用參數會指定 AutoSupport 訊息的替代目的地。

====


 a| 
顯示核心傾印的狀態資訊
 a| 
`system node coredump status`



 a| 
刪除指定的核心傾印
 a| 
`system node coredump delete`



 a| 
刪除節點上所有未儲存的核心傾印或所有已儲存的核心檔案
 a| 
`system node coredump delete-all`



 a| 
顯示應用程式核心傾印報告
 a| 
`system node coredump reports show`



 a| 
刪除應用程式核心傾印報告
 a| 
`system node coredump reports delete`

|===
.相關資訊
link:https://docs.netapp.com/us-en/ontap/concepts/manual-pages.html["指令數ONTAP"^]
