---
permalink: system-admin/manage-cluster-time-concept.html 
sidebar: sidebar 
keywords: manage, cluster, time, administrator, ntp, network, time, protocol, zone 
summary: 雖然 ONTAP 可讓您手動設定叢集上的時區，日期和時間，但您仍應設定 NTP 伺服器來同步叢集時間。 
---
= 管理 ONTAP 叢集時間（僅限叢集管理員）
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
當叢集時間不準確時、可能會發生問題。雖然利用此功能、您可以手動設定叢集上的時區、日期和時間、但您應該設定網路時間傳輸協定（NTP）伺服器、以同步叢集時間。ONTAP

從使用S25 9.5開始ONTAP 、您可以使用對稱驗證來設定NTP伺服器。

NTP一律啟用。不過、叢集仍需要進行組態、才能與外部時間來源同步。利用支援功能、您可以透過下列方式管理叢集的NTP組態：ONTAP

* 您最多可以將 10 個外部 NTP 伺服器與叢集建立關聯 (`cluster time-service ntp server create`）。
+
** 為了提供備援和時間服務品質、您應將至少三部外部NTP伺服器與叢集建立關聯。
** 您可以使用NTP伺服器的IPv4或IPv6位址或完整主機名稱來指定NTP伺服器。
** 您可以手動指定要使用的NTP版本（v3或v4）。
+
根據預設、ONTAP 支援特定外部NTP伺服器的NTP版本會自動選取。

+
如果您指定的NTP版本不支援NTP伺服器、則無法進行時間交換。

** 在進階權限層級、您可以指定與叢集相關聯的外部NTP伺服器、作為修正及調整叢集時間的主要時間來源。


* 您可以顯示與叢集相關聯的 NTP 伺服器 (`cluster time-service ntp server show`）。
* 您可以修改叢集的 NTP 組態 (`cluster time-service ntp server modify`）。
* 您可以取消叢集與外部 NTP 伺服器的關聯 (`cluster time-service ntp server delete`）。
* 在進階權限層級、您可以清除所有外部 NTP 伺服器與叢集的關聯、以重設組態 (`cluster time-service ntp server reset`）。


加入叢集的節點會自動採用叢集的NTP組態。

除了使用NTP之外、ONTAP 利用此功能、您還可以手動管理叢集時間。當您需要修正錯誤時間時（例如、重新開機後節點的時間已大不正確）、這項功能很有幫助。在這種情況下、您可以指定叢集的大約時間、直到NTP可以與外部時間伺服器同步為止。您手動設定的時間會在叢集中的所有節點上生效。

您可以使用下列方式手動管理叢集時間：

* 您可以設定或修改叢集上的時區、日期和時間 (`cluster date modify`）。
* 您可以顯示叢集目前的時區、日期和時間設定 (`cluster date show`）。


[NOTE]
====
工作排程不會調整為手動叢集日期和時間變更。這些工作會根據目前建立工作的叢集時間或最近執行工作的時間來排程執行。因此、如果您手動變更叢集日期或時間、則必須使用 `job show` 和 `job history show` 用於驗證所有排程工作是否已根據您的需求排入佇列並完成的命令。

====


== 管理叢集時間的命令

您可以使用 `cluster time-service ntp server` 用於管理叢集 NTP 伺服器的命令。您可以使用 `cluster date` 手動管理叢集時間的命令。

從使用S25 9.5開始ONTAP 、您可以使用對稱驗證來設定NTP伺服器。

下列命令可讓您管理叢集的NTP伺服器：

|===
| 如果您想要... | 使用此命令... 


 a| 
將叢集與外部NTP伺服器建立關聯、而不進行對稱驗證
 a| 
`cluster time-service ntp server create -server server_name`



 a| 
將叢集與外部NTP伺服器建立關聯、使其具有ONTAP 可在版次9.5或更新版本中使用的對稱驗證
 a| 
`cluster time-service ntp server create -server server_ip_address -key-id key_id`

[NOTE]
====
。 `key_id` 必須參考現有的共用金鑰、該金鑰設定為「叢集時間服務 NTP 金鑰」。

====


 a| 
啟用現有NTP伺服器的對稱驗證您可以修改現有NTP伺服器、藉由新增所需的金鑰ID來啟用驗證。

提供版本僅適用於S9.5或更新版本ONTAP
 a| 
`cluster time-service ntp server modify -server server_name -key-id key_id`



 a| 
停用對稱驗證
 a| 
`cluster time-service ntp server modify -server server_name -is-authentication-enabled false`



 a| 
設定共用的NTP金鑰
 a| 
`cluster time-service ntp key create -id shared_key_id -type shared_key_type -value shared_key_value`

[NOTE]
====
共用金鑰是由ID所指。節點和NTP伺服器上的ID、其類型和值必須相同

====


 a| 
顯示與叢集相關聯之NTP伺服器的相關資訊
 a| 
`cluster time-service ntp server show`



 a| 
修改與叢集相關聯的外部NTP伺服器組態
 a| 
`cluster time-service ntp server modify`



 a| 
將NTP伺服器與叢集取消關聯
 a| 
`cluster time-service ntp server delete`



 a| 
清除所有外部NTP伺服器與叢集的關聯、以重設組態
 a| 
`cluster time-service ntp server reset`

[NOTE]
====
此命令需要進階權限層級。

====
|===
下列命令可讓您手動管理叢集時間：

|===
| 如果您想要... | 使用此命令... 


 a| 
設定或修改時區、日期和時間
 a| 
`cluster date modify`



 a| 
顯示叢集的時區、日期和時間設定
 a| 
`cluster date show`

|===
.相關資訊
link:../concepts/manual-pages.html["指令參考資料ONTAP"]
