---
permalink: system-admin/manage-access-web-services-concept.html 
sidebar: sidebar 
keywords: 'manage, access, web, service, http, https, cluster, administrator, web, protocol, engine, ssl, role, api, ontapi, disco, supdiag, sysmgr, fw, bmc, docs, "docs_api", fud, ontapmsg, portal, rest, saml, backup, back up, security, csrf' 
summary: Web服務是使用者可以使用HTTP或HTTPS存取的應用程式。叢集管理員可以設定Web傳輸協定引擎、設定SSL、啟用Web服務、以及讓角色的使用者存取Web服務。 
---
= 管理Web服務的存取概觀
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Web服務是使用者可以使用HTTP或HTTPS存取的應用程式。叢集管理員可以設定Web傳輸協定引擎、設定SSL、啟用Web服務、以及讓角色的使用者存取Web服務。

從支援下列Web服務的支援範圍ONTAP 起、從功能支援的9.6開始：

* 服務處理器基礎架構（「pi」）
+
此服務可透過叢集管理LIF或節點管理LIF、讓節點的記錄檔、核心傾印檔和MIBA檔案可供HTTP或HTTPS存取。預設設定為「啟用」。

+
當您要求存取節點的記錄檔或核心傾印檔時、「_pi」Web服務會自動從節點建立掛載點、並將其建立至檔案所在的另一個節點根Volume。您不需要手動建立掛載點。」

* 地區API（「ontapi」ONTAP ）
+
這項服務可讓您執行ONTAP IsyAPI、以遠端程式執行管理功能。預設設定為「啟用」。

+
某些外部管理工具可能需要此服務。例如、如果您使用System Manager、則應保持啟用此服務。

* 韓國發現（《舊金山》）Data ONTAP
+
此服務可讓隨裝即用的管理應用程式在網路中探索叢集。預設設定為「啟用」。

* 支援診斷（「supdiag」）
+
此服務可控制系統上的權限環境存取、以協助進行問題分析和解決問題。預設設定為「停用」。您只能在技術支援人員的指示下啟用此服務。

* 系統管理程式（「ssmgr」）
+
此服務可控制系統管理員的可用度、ONTAP 而此功能隨附於本服務。預設設定為「啟用」。此服務僅在叢集上受支援。

* 韌體基礎板管理控制器（BMC）更新（「FW_BMC」）
+
此服務可讓您下載BMC韌體檔案。預設設定為「啟用」。

* 文件（「ocs」ONTAP ）
+
此服務可讓您存取ONTAP 有關的資料。預設設定為「啟用」。

* REST風格的API（「ocs_API」ONTAP ）
+
此服務可讓您存取ONTAP 「REST風格的API」文件。預設設定為「啟用」。

* 檔案上傳與下載（「fud」）
+
此服務提供檔案上傳與下載。預設設定為「啟用」。

* 消息傳送（'ontapmsg'）ONTAP
+
此服務支援發佈及訂閱介面、可讓您訂閱活動。預設設定為「啟用」。

* 資訊入口網站（「入口網站」ONTAP ）
+
此服務會將閘道實作至虛擬伺服器。預設設定為「啟用」。

* REST風格的介面（「REST」ONTAP ）
+
此服務支援RESTful介面、可用於遠端管理叢集基礎架構的所有元素。預設設定為「啟用」。

* 安全聲明標記語言（SAML）服務供應商支援（「shaml」）
+
此服務提供資源來支援SAML服務供應商。預設設定為「啟用」。

* SAML服務供應商（「shamam-sp」）
+
此服務可為服務供應商提供SP中繼資料和聲明使用者服務等服務。預設設定為「啟用」。



從支援下列附加服務的支援範圍ONTAP 起、從支援使用者支援的範圍開始：

* 組態備份檔案（「備份」）
+
此服務可讓您下載組態備份檔案。預設設定為「啟用」。

* 支援安全（「安全性」ONTAP ）
+
此服務支援CSRF權杖管理、以加強驗證。預設設定為「啟用」。


