---
permalink: system-admin/manage-access-web-services-concept.html 
sidebar: sidebar 
keywords: 'manage, access, web, service, http, https, cluster, administrator, web, protocol, engine, ssl, role, api, ontapi, disco, supdiag, sysmgr, fw, bmc, docs, "docs_api", fud, ontapmsg, portal, rest, saml, backup, back up, security, csrf' 
summary: Web服務是使用者可以使用HTTP或HTTPS存取的應用程式。叢集管理員可以設定Web傳輸協定引擎、設定SSL、啟用Web服務、以及讓角色的使用者存取Web服務。 
---
= 管理Web服務的存取概觀
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Web服務是使用者可以使用HTTP或HTTPS存取的應用程式。叢集管理員可以設定Web傳輸協定引擎、設定SSL、啟用Web服務、以及讓角色的使用者存取Web服務。

從支援下列Web服務的支援範圍ONTAP 起、從功能支援的9.6開始：

* 服務處理器基礎架構 (`spi`）
+
此服務可透過叢集管理LIF或節點管理LIF、讓節點的記錄檔、核心傾印檔和MIBA檔案可供HTTP或HTTPS存取。預設設定為 `enabled`。

+
在要求存取節點的記錄檔或核心傾印檔案時 `spi` Web 服務會自動從節點建立掛載點、並將檔案存放在另一個節點的根磁碟區。您不需要手動建立掛載點。」

* ONTAP API (`ontapi`）
+
這項服務可讓您執行ONTAP IsyAPI、以遠端程式執行管理功能。預設設定為 `enabled`。

+
某些外部管理工具可能需要此服務。例如、如果您使用System Manager、則應保持啟用此服務。

* Data ONTAP 探索 (`disco`）
+
此服務可讓隨裝即用的管理應用程式在網路中探索叢集。預設設定為 `enabled`。

* 支援診斷 (`supdiag`）
+
此服務可控制系統上的權限環境存取、以協助進行問題分析和解決問題。預設設定為 `disabled`。您只能在技術支援人員的指示下啟用此服務。

* 系統管理員 (`sysmgr`）
+
此服務可控制系統管理員的可用度、ONTAP 而此功能隨附於本服務。預設設定為 `enabled`。此服務僅在叢集上受支援。

* 韌體基礎板管理控制器（ BMC ）更新 (`FW_BMC`）
+
此服務可讓您下載BMC韌體檔案。預設設定為 `enabled`。

* 資訊文件ONTAP (`docs`）
+
此服務可讓您存取ONTAP 有關的資料。預設設定為 `enabled`。

* ONTAP RESTful API (`docs_api`）
+
此服務可讓您存取ONTAP 「REST風格的API」文件。預設設定為 `enabled`。

* 檔案上傳與下載 (`fud`）
+
此服務提供檔案上傳與下載。預設設定為 `enabled`。

* ONTAP 訊息 (`ontapmsg`）
+
此服務支援發佈及訂閱介面、可讓您訂閱活動。預設設定為 `enabled`。

* ONTAP 入口網站 (`portal`）
+
此服務會將閘道實作至虛擬伺服器。預設設定為 `enabled`。

* ONTAP REST 風格的介面 (`rest`）
+
此服務支援RESTful介面、可用於遠端管理叢集基礎架構的所有元素。預設設定為 `enabled`。

* 安全聲明標記語言（ SAML ）服務供應商支援 (`saml`）
+
此服務提供資源來支援SAML服務供應商。預設設定為 `enabled`。

* SAML 服務供應商 (`saml-sp`）
+
此服務可為服務供應商提供SP中繼資料和聲明使用者服務等服務。預設設定為 `enabled`。



從支援下列附加服務的支援範圍ONTAP 起、從支援使用者支援的範圍開始：

* 組態備份檔案 (`backups`）
+
此服務可讓您下載組態備份檔案。預設設定為 `enabled`。

* ONTAP 安全性 (`security`）
+
此服務支援CSRF權杖管理、以加強驗證。預設設定為 `enabled`。


