---
permalink: system-admin/manage-web-protocol-engine-concept.html 
sidebar: sidebar 
keywords: manage, web, protocol, engine, ssl, access, configuration, settings 
summary: 您可以在叢集上設定Web傳輸協定引擎、以控制是否允許Web存取、以及可以使用哪些SSL版本。您也可以顯示Web傳輸協定引擎的組態設定。 
---
= 管理Web傳輸協定引擎
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在叢集上設定Web傳輸協定引擎、以控制是否允許Web存取、以及可以使用哪些SSL版本。您也可以顯示Web傳輸協定引擎的組態設定。

您可以透過下列方式、在叢集層級管理Web傳輸協定引擎：

* 您可以使用指定遠端用戶端是否可以使用 HTTP 或 HTTPS 來存取 Web 服務內容 `system services web modify` 命令 `-external` 參數。
* 您可以使用來指定是否應使用 SSLv3 來進行安全的 Web 存取 `security config modify` 命令 `-supported-protocol` 參數。
根據預設、SSLv3會停用。傳輸層安全性1.0（TLSv1.0）已啟用、可視需要停用。
* 您可以針對整個叢集的控制面板Web服務介面、啟用聯邦資訊處理標準（FIPS）140-2法規遵循模式。
+
[NOTE]
====
預設會停用FIPS 140-2相容模式。

====
+
** *當FIPS 140-2相容模式停用時*
您可以透過設定來啟用 FIPS 140-2 規範模式 `is-fips-enabled` 參數至 `true` 適用於 `security config modify` 命令、然後使用 `security config show` 確認線上狀態的命令。
** *啟用FIPS 140-2規範模式時*
+
*** 從SESS9.11.1開始ONTAP 、TLSv1、TLSv1.1和SSLv3會停用、而且只有TSLv1.2和TSLv1.3會維持啟用狀態。它會影響ONTAP 到其他內部和外部的系統和通訊、而這些系統和通訊則是來自於19。如果您啟用FIPS 140-2規範模式、然後停用、則TLSv1、TLSv1.1及SSLv3會維持停用狀態。視先前的組態而定、TLSv1.2或TLSSv1.3仍會保持啟用狀態。
*** 對於9.11.1之前的ONTAP 版本、TLSv1和SSLv3都會停用、只有TLSv1.1和TLSv1.2會維持啟用狀態。啟用FIPS 140-2相容模式時、無法同時啟用TLSv1和SSLv3。ONTAP如果您啟用FIPS 140-2規範模式、然後停用該模式、則TLSv1和SSLv3仍會維持停用狀態、但根據先前的組態、TLSv1.2或同時啟用TLSv1.1和TLSv1.2。




* 您可以使用顯示叢集整體安全性的組態 `system security config show` 命令。


如果啟用防火牆、則必須設定用於Web服務的邏輯介面（LIF）防火牆原則、以允許HTTP或HTTPS存取。

如果您使用HTTPS進行Web服務存取、則提供Web服務的叢集或儲存虛擬機器（SVM）的SSL也必須啟用、而且您必須提供叢集或SVM的數位憑證。

在「樣」組態中、您對叢集上的Web傳輸協定引擎所做的設定變更不會複寫到合作夥伴叢集上。MetroCluster
