---
permalink: system-admin/manage-motd-reference.html 
sidebar: sidebar 
keywords: manage, motd, message, day, cluster, svm, administrator 
summary: 您可以在叢集或SVM層級管理當天訊息（MOTD）。根據預設、為叢集設定的MOTD也會針對所有SVM啟用。此外、也可針對每個SVM設定SVM層級的MOTD。叢集管理員可針對每個SVM啟用或停用叢集層級的MOTD。 
---
= 管理MOTD
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以在叢集或SVM層級管理當天訊息（MOTD）。根據預設、為叢集設定的MOTD也會針對所有SVM啟用。此外、也可針對每個SVM設定SVM層級的MOTD。叢集管理員可針對每個SVM啟用或停用叢集層級的MOTD。

如需可用於動態產生 MOTD 內容的轉義序列清單、請參閱 link:https://docs.netapp.com/us-en/ontap-cli//security-login-motd-modify.html#parameters["命令參考資料"]。

.選擇
* 在叢集層級管理MOTD：
+
|===
| 如果您想要... | 然後... 


 a| 
如果沒有現有的MOTD、請為所有登入建立MOTD
 a| 
設定叢集層級的MOTD：

`*security login motd modify -vserver _cluster_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`



 a| 
如果未設定SVM層級的MOTD、請變更所有登入的MOTD
 a| 
修改叢集層級的MOTD：

`*security login motd modify -vserver _cluster_name_ { [-message "_text_"] } | [-uri ftp_or_http_addr] }*`



 a| 
若未設定SVM層級的MOTD、請移除所有登入的MOTD
 a| 
將叢集層級的 MOTD 設定為空白字串 (`""`）：

`*security login motd modify -vserver _cluster_name_ -message ""*`



 a| 
讓每個SVM都顯示叢集層級的MOTD、而非使用SVM層級的MOTD
 a| 
設定叢集層級的MOTD、然後在啟用叢集層級MOTD的情況下、將所有SVM層級的MOTD設為空白字串：

.. `*security login motd modify -vserver _cluster_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`
.. `*security login motd modify { -vserver !"_cluster_name_" } -message "" -is-cluster-message-enabled true*`




 a| 
僅針對選取的SVM顯示MOTD、不使用叢集層級的MOTD
 a| 
將叢集層級的MOTD設為空白字串、然後為選取的SVM設定SVM層級的MOTD：

.. `*security login motd modify -vserver _cluster_name_ -message ""*`
.. `*security login motd modify -vserver _svm_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`
+
您可以視需要為每個SVM重複此步驟。





 a| 
針對所有（資料與管理）SVM、使用相同的SVM層級MOTD
 a| 
將叢集和所有SVM設定為使用相同的MOTD：

`*security login motd modify _-vserver_ * { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`

[NOTE]
====
如果您使用互動模式、CLI會提示您個別輸入叢集和每個SVM的MOTD。當系統提示您時、您可以將相同的MOTD貼到每個執行個體中。

====


 a| 
讓所有SVM都可選用叢集層級的MOTD、但不要在叢集登入時顯示MOTD
 a| 
設定叢集層級的MOTD、但停用叢集的顯示：

`*security login motd modify -vserver _cluster_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] } -is-cluster-message-enabled false*`



 a| 
當只有部分SVM同時具有叢集層級和SVM層級的MOTD時、請移除叢集層級和SVM層級的所有MOTD
 a| 
將叢集和所有SVM設定為使用MOTD的空白字串：

`*security login motd modify -vserver * -message ""*`



 a| 
只有當其他SVM使用空字串、以及叢集層級使用不同的MOTD時、才可針對具有非空字串的SVM修改MOTD
 a| 
使用延伸查詢可選擇性修改MOTD：

`*security login motd modify { -vserver !"_cluster_name_" -message !"" } { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`



 a| 
在單一或多行訊息的任何位置顯示所有包含特定文字（例如「1月」、後面接著「2015」）的MOTD、即使文字分成不同的行
 a| 
使用查詢顯示MOTD：

`*security login motd show -message *"January"\***"2015"**`



 a| 
以互動方式建立包含多個和連續新行（也稱為行尾或EOLS）的MOTD。
 a| 
在互動模式中、按下空格鍵、然後按Enter鍵以建立空白行、而不終止MOTD的輸入。

|===
* 在SVM層級管理MOTD：
+
指定 `-vserver _svm_name_` 在 SVM 內容中不需要。

+
|===
| 如果您想要... | 然後... 


 a| 
當SVM已經有現有的SVM層級MOTD時、請使用不同的SVM層級MOTD
 a| 
修改SVM層級的MOTD：

`*security login motd modify -vserver _svm_name_ { [-message "_text_"] | [-uri _ftp_or_http_addr_] }*`



 a| 
當SVM已經有SVM層級的MOTD時、只能使用SVM的叢集層級MOTD
 a| 
將SVM層級MOTD設為空白字串、然後讓叢集管理員啟用SVM的叢集層級MOTD：

.. `*security login motd modify -vserver _svm_name_ -message ""*`
.. （適用於叢集管理員） `*security login motd modify -vserver _svm_name_ -is-cluster-message-enabled true*`




 a| 
當SVM目前同時顯示叢集層級和SVM層級的MOTD時、SVM不會顯示任何MOTD
 a| 
將SVM層級MOTD設為空白字串、然後讓叢集管理員停用SVM的叢集層級MOTD：

.. `*security login motd modify -vserver _svm_name_ -message ""*`
.. （適用於叢集管理員） `*security login motd modify -vserver _svm_name_ -is-cluster-message-enabled false*`


|===

