---
permalink: system-admin/manage-jobs-schedules.html 
sidebar: sidebar 
keywords: job, categories, server, cluster, affiliated, private, commands, managing, show jobs, job schedule, stop a job, delete a job, pause a job, display private jobs, modify, cron, interval, delete, interval schedule, manage jobs and schedule, manage jobs, manage schedule 
summary: 工作會放入工作佇列、並在資源可用時於背景執行。如果工作佔用過多的叢集資源、您可以將其停止或暫停、直到叢集需求減少為止。您也可以監控及重新啟動工作。 
---
= 管理工作和排程
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
工作會放入工作佇列、並在資源可用時於背景執行。如果工作佔用過多的叢集資源、您可以將其停止或暫停、直到叢集需求減少為止。您也可以監控及重新啟動工作。



== 工作類別

您可以管理三類工作：伺服器關聯、叢集關聯及私有。

工作可分為下列任一類別：

* *伺服器相關工作*
+
管理架構會將這些工作排入要執行的特定節點佇列。

* *叢集相關工作*
+
管理架構會將這些工作排入要執行之叢集中任何節點的佇列。

* *私有工作*
+
這些工作是專屬於某個節點、不使用複寫資料庫（RDB）或任何其他叢集機制。管理私有工作的命令需要進階權限層級或更高。





== 管理工作的命令

當您輸入命令以叫用工作時、通常會通知您工作已排入佇列、然後返回CLI命令提示字元。不過、有些命令會回報工作進度、而且在工作完成之前、不會返回CLI命令提示字元。在這些情況下、您可以按Ctrl-C將工作移至背景。

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示所有工作的相關資訊
 a| 
`job show`



 a| 
顯示每個節點的工作相關資訊
 a| 
`job show bynode`



 a| 
顯示有關叢集關聯工作的資訊
 a| 
`job show-cluster`



 a| 
顯示已完成工作的相關資訊
 a| 
`job show-completed`



 a| 
顯示有關工作記錄的資訊
 a| 
`job history show`

叢集中每個節點最多可儲存25、000筆工作記錄。因此、嘗試顯示完整的工作記錄可能需要很長時間。為了避免可能需要長時間等待、您應該依節點、儲存虛擬機器（SVM）或記錄ID來顯示工作。



 a| 
顯示私有工作清單
 a| 
`job private show` （進階權限層級）



 a| 
顯示已完成私有工作的相關資訊
 a| 
`job private show-completed` （進階權限層級）



 a| 
顯示工作管理員初始化狀態的相關資訊
 a| 
`job initstate show` （進階權限層級）



 a| 
監控工作進度
 a| 
`job watch-progress`



 a| 
監控私有工作的進度
 a| 
`job private watch-progress` （進階權限層級）



 a| 
暫停工作
 a| 
`job pause`



 a| 
暫停私有工作
 a| 
`job private pause` （進階權限層級）



 a| 
恢復暫停的工作
 a| 
`job resume`



 a| 
恢復暫停的私有工作
 a| 
`job private resume` （進階權限層級）



 a| 
停止工作
 a| 
`job stop`



 a| 
停止私有工作
 a| 
`job private stop` （進階權限層級）



 a| 
刪除工作
 a| 
`job delete`



 a| 
刪除私有工作
 a| 
`job private delete` （進階權限層級）



 a| 
將叢集關聯的工作與擁有該工作的不可用節點解除關聯、以便其他節點可以取得該工作的擁有權
 a| 
`job unclaim` （進階權限層級）

|===
[NOTE]
====
您可以使用 `event log show` 命令來判斷已完成工作的結果。

====
.相關資訊
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令數ONTAP"^]



== 管理工作排程的命令

許多工作（例如 Volume Snapshot 複本）都可以設定為在指定的排程上執行。在特定時間執行的排程稱為 _cron 排程（類似 UNIX ） `cron` 排程）。每隔一段時間執行的排程稱為「_interval_排程」。您可以使用 `job schedule` 管理工作排程的命令。

工作排程不會調整為手動變更叢集日期和時間。這些工作會根據目前建立工作的叢集時間或最近執行工作的時間來排程執行。因此、如果您手動變更叢集日期或時間、則應使用 `job show` 和 `job history show` 用於驗證所有排程工作是否已根據您的需求排入佇列並完成的命令。

如果叢集是MetroCluster 支援功能的一部分、則兩個叢集上的工作排程必須相同。因此、如果您建立、修改或刪除工作排程、則必須在遠端叢集上執行相同的作業。

|===
| 如果您想要... | 使用此命令... 


 a| 
顯示所有排程的相關資訊
 a| 
`job schedule show`



 a| 
依排程顯示工作清單
 a| 
`job schedule show-jobs`



 a| 
顯示有關cron排程的資訊
 a| 
`job schedule cron show`



 a| 
顯示有關時間間隔排程的資訊
 a| 
`job schedule interval show`



 a| 
建立cron排程
 a| 
`job schedule cron create`

從 ONTAP 9.10.1 開始、您可以在工作排程中加入 SVM 。



 a| 
建立時間間隔排程
 a| 
`job schedule interval create`

您必須至少指定下列其中一個參數： `-days`、 `-hours`、 `-minutes`或 `-seconds`。



 a| 
修改cron排程
 a| 
`job schedule cron modify`



 a| 
修改時間間隔排程
 a| 
`job schedule interval modify`



 a| 
刪除排程
 a| 
`job schedule delete`



 a| 
刪除cron排程
 a| 
`job schedule cron delete`



 a| 
刪除時間間隔排程
 a| 
`job schedule interval delete`

|===
.相關資訊
http://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr/GUID-5CB10C70-AC11-41C0-8C16-B4D0DF916E9B.html["指令數ONTAP"^]
