---
permalink: system-admin/methods-manage-sp-bmc-firmware-updates-concept.html 
sidebar: sidebar 
keywords: methods, manage, sp, bmc, firmware, update, image, baseline, download 
summary: 包含一個稱為基礎映像的SP韌體映像。ONTAP如果隨後有新版的SP韌體可供使用、您可以選擇下載該韌體、並將SP韌體更新至下載的版本、而不需升級ONTAP 此版本的更新。 
---
= 管理 ONTAP SP / BMC 韌體更新
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
包含一個稱為「_baseline image_」的SP韌體映像。ONTAP如果隨後有新版的SP韌體可供使用、您可以選擇下載該韌體、並將SP韌體更新至下載的版本、而不需升級ONTAP 此版本的更新。

[NOTE]
====
本主題同時適用於SP和BMC。

====
支援下列管理SP韌體更新的方法：ONTAP

* SP自動更新功能預設為啟用、可在下列情況下自動更新SP韌體：
+
** 當您升級ONTAP 至新版的更新版本時
+
只要與之搭售的SP韌體版本比節點上執行的SP版本更新、即可自動包含SP韌體更新程序。ONTAP ONTAP

+
[NOTE]
====
ONTAP偵測到失敗的SP自動更新並觸發糾正措施以重試SP自動更新最多三次。如果三次重試都失敗，請參閱link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Health_Monitor_SPAutoUpgradeFailedMajorAlert__SP_upgrade_fails_-_AutoSupport_Message["NetApp知識庫：健康監視器 SPAutoUpgradeFailedMajorAlert SP升級失敗 - AutoSupport訊息"^]。

====
** 當您從 NetApp 支援網站下載 SP 韌體版本，且下載的版本比目前執行的 SP 版本新時
** 當您降級ONTAP 或回復至舊版的版本時
+
SP韌體會自動更新為ONTAP 支援的最新相容版本、由還原或降級至的版本支援。不需要手動更新SP韌體。



+
您可以選擇使用停用 SP 自動更新功能 `system service-processor image modify` 命令。不過、建議您保留啟用此功能的狀態。停用此功能可能會導致ONTAP 不佳或不合格的結合、使不佳的影像與SP韌體映像無法搭配使用。

* ONTAP 可讓您手動觸發 SP 更新、並使用指定更新的執行方式 `system service-processor image update` 命令。
+
您可以指定下列選項：

+
** 要使用的 SP 韌體套件 (`-package`）
+
您可以指定套件檔案名稱、將SP韌體更新至下載的套件。進步 `system image package show` 命令會顯示節點上可用的所有套件檔案（包括 SP 韌體套件的檔案）。

** 是否使用基礎 SP 韌體套件進行 SP 更新 (`-baseline`）
+
您可以將SP韌體更新至目前執行版本ONTAP 的BIOS所隨附的基礎版本。



+
[NOTE]
====
如果您使用一些更進階的更新選項或參數、則BMC的組態設定可能會暫時清除。重新開機後ONTAP 、恢復BMC組態最多可能需要10分鐘。

====
* ONTAP 可讓您使用顯示從 ONTAP 觸發的最新 SP 韌體更新狀態 `system service-processor image update-progress show` 命令。


更新SP韌體時、任何現有的SP連線都會終止。無論是自動或手動觸發SP韌體更新、都會發生這種情況。

.相關資訊
https://mysupport.netapp.com/site/downloads/firmware/system-firmware-diagnostics["NetApp下載：系統韌體與診斷"^]
