---
permalink: system-admin/ontap-implements-audit-logging-concept.html 
sidebar: sidebar 
keywords: ontap, implement, audit, logging, management, autosupport, ems, messages, log, cli, web, browser 
summary: 稽核日誌中記錄的管理活動會包含在標準AutoSupport 版的功能表報告中、而EMS訊息中也會包含某些記錄活動。您也可以將稽核記錄轉送到指定的目的地、並使用CLI或Web瀏覽器來顯示稽核記錄檔。 
---
= 如何執行稽核記錄ONTAP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
稽核日誌中記錄的管理活動會包含在標準AutoSupport 版的功能表報告中、而EMS訊息中也會包含某些記錄活動。您也可以將稽核記錄轉送到指定的目的地、並使用CLI或Web瀏覽器來顯示稽核記錄檔。

系統會記錄叢集上執行的管理活動、例如發出的要求、觸發要求的使用者、使用者的存取方法、以及要求的時間。ONTAP

管理活動可以是下列其中一種類型：

* 設定要求、通常適用於非顯示命令或作業
+
** 例如、當您執行「create」、「modify」或「刪除」命令時、就會發出這些要求。
** 預設會記錄設定要求。


* Get要求、可擷取資訊並在管理介面中顯示
+
** 例如、當您執行「show」命令時、就會發出這些要求。
** 根據預設、不會記錄Get要求、但您可以使用「安全稽核修改」命令來控制是否ONTAP 將從動作介面（`-cliget'）或ONTAP 從動作介面API（`-ontapiget'）傳送的Get要求記錄在檔案中。




此功能可將管理活動記錄在節點的「/mroot/etc/log/mlog/Audit記錄檔」中。ONTAP這裏記錄了三個Shell中用於CLI命令的命令（即clusterShell、nodesell和非交互式系統Shell（不記錄交互式系統Shell命令）以及API命令。稽核記錄包含時間戳記、可顯示叢集中的所有節點是否都同步時間。

「稽核記錄」檔案是AutoSupport 由「不行」工具傳送給指定的收件者。您也可以將內容安全地轉送到您指定的外部目的地、例如Splunk或syslog伺服器。

「稽核記錄」檔案會每日循環。當檔案大小達到100 MB時、也會進行旋轉、並保留先前的48個複本（最多總共49個檔案）。稽核檔案執行每日旋轉時、不會產生任何EMS訊息。如果稽核檔案因為超過檔案大小限制而旋轉、則會產生EMS訊息。

您可以使用「安全稽核記錄show」命令來顯示個別節點的稽核項目、或是從叢集中的多個節點合併。您也可以使用網頁瀏覽器、在單一節點上顯示「/mroot/etc/log/mlog」目錄的內容。
