---
permalink: system-admin/positional-parameters-concept.html 
sidebar: sidebar 
keywords: understand, positional, parameters, cli, command, input, query 
summary: 您可以利用ONTAP 資訊中心的位置參數功能來提高命令輸入的效率。您可以查詢命令以識別命令的位置參數。 
---
= 關於位置參數
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以利用ONTAP 資訊中心的位置參數功能來提高命令輸入的效率。您可以查詢命令以識別命令的位置參數。



== 什麼是位置參數

* 位置參數是一個參數、在指定參數值之前、不需要指定參數名稱。
* 位置參數可以與命令輸入中的非位置參數互連、只要它在同一個命令中觀察其相對順序與其他位置參數、如所示 `*_command_name ?_*` 輸出。
* 位置參數可以是命令的必要或選用參數。
* 參數可以是一個命令的位置、但不能是另一個命令的位置。


[NOTE]
====
不建議在指令碼中使用位置參數功能、尤其是當指令的位置參數為選用、或是在指令碼之前列出選用參數時。

====


== 識別位置參數

您可以在中識別位置參數 `*_command_name ?_*` 命令輸出。位置參數的參數名稱前後有方括弧、格式如下：

* [`_-parameter_name_`] `_parameter_value_` 顯示位置所需的參數。
* [[`_-parameter_name_`] `_parameter_value_`] 顯示位置的選用參數。


例如、當顯示為中的下列項目時 `*_command_name ?_*` 輸出時、參數是其所顯示命令的位置：

* `[-lif] <lif-name>`
* `[[-lif] <lif-name>]`


但是、當顯示為下列項目時、參數會與顯示於中的命令非位置：

* `-lif <lif-name>`
* `[-lif <lif-name>]`




== 使用位置參數的範例

在下列範例中、 `*_volume create ?_*` 輸出顯示命令的位置為三個參數： `-volume`、 `-aggregate`和 `-size`。

[listing]
----
cluster1::> volume create ?
   -vserver <vserver name>                Vserver Name
   [-volume] <volume name>                Volume Name
   [-aggregate] <aggregate name>          Aggregate Name
  [[-size] {<integer>[KB|MB|GB|TB|PB]}]   Volume Size
  [ -state {online|restricted|offline|force-online|force-offline|mixed} ]
                                          Volume State (default: online)
  [ -type {RW|DP|DC} ]                    Volume Type (default: RW)
  [ -policy <text> ]                      Export Policy
  [ -user <user name> ]                   User ID
  ...
  [ -space-guarantee|-s {none|volume} ]   Space Guarantee Style (default: volume)
  [ -percent-snapshot-space <percent> ]   Space Reserved for Snapshot Copies
  ...
----
在下列範例中、 `volume create` 命令是在不使用位置參數功能的情況下指定的：

`cluster1::> volume create -vserver svm1 -volume vol1 -aggregate *aggr1 -size 1g* -percent-snapshot-space 0`

下列範例使用位置參數功能來提高命令輸入的效率。位置參數會與中的非位置參數互置 `volume create` 命令和位置參數值是在沒有參數名稱的情況下指定的。位置參數的指定順序與所指示的順序相同 `*volume create ?*` 輸出。也就是的價值 `-volume` 在的之前指定 `-aggregate`，而這又是在的之前指定的 `-size`。

`cluster1::> volume create *vol2* *aggr1* *1g* -vserver svm1 -percent-snapshot-space 0`

`cluster1::> volume create -vserver svm1 *vol3* -snapshot-policy default *aggr1* -nvfail off *1g* -space-guarantee none`
