---
permalink: system-admin/remove-nodes-cluster-concept.html 
sidebar: sidebar 
keywords: remove, node, cluster, failover, partner, erase, inaccessible 
summary: 您可以從叢集移除不需要的節點、一次移除一個節點。移除節點之後、您也必須移除其容錯移轉合作夥伴。如果您要移除節點、則其資料將無法存取或遭到清除。 
---
= 從 ONTAP 叢集移除節點
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以從叢集移除不需要的節點、一次移除一個節點。移除節點之後、您也必須移除其容錯移轉合作夥伴。如果您要移除節點、則其資料將無法存取或遭到清除。

.開始之前
從叢集中移除節點之前，必須滿足以下條件：

* 叢集中有一半以上的節點必須健全。
* 所有資料、磁碟區和非根聚合都必須從節點中遷移或刪除。
+
** 您要移除之節點上的所有資料都必須已清空。這可能包括link:../encryption-at-rest/secure-purge-data-encrypted-volume-concept.html["從加密磁碟區清除資料"]。
** 所有非根磁碟區都已存在 link:../volumes/move-volume-task.html["已移動"] 來自節點擁有的Aggregate。
** 所有非根集合體都已存在 link:../disks-aggregates/commands-manage-aggregates-reference.html["已刪除"] 從節點。


* 所有的生命和 VLAN 都已重新定位或從節點移除。
+
** 資料生命之年 link:../networking/delete_a_lif.html["已刪除"] 或 link:../networking/migrate_a_lif.html["重新定位"] 從節點。
** 叢集管理生命 link:../networking/migrate_a_lif.html["重新定位"] 從節點和主連接埠變更。
** 所有叢集間的生命都是link:../networking/delete_a_lif.html["已移除"]。當您移除叢集間的lifs時、會顯示可忽略的警告。
** 節點上的所有VLAN都是如此 link:../networking/configure_vlans_over_physical_ports.html#delete-a-vlan["已刪除"]。


* 節點未參與任何容錯移轉關係。
+
** 儲存設備容錯移轉 link:../high-availability/ha_commands_for_enabling_and_disabling_storage_failover.html["已停用"] 用於節點。
** 所有LIF容錯移轉規則都已達到 link:../networking/commands_for_managing_failover_groups_and_policies.html["已修改"] 移除節點上的連接埠。


* 如果節點擁有聯邦資訊處理標準（FIPS）磁碟或自我加密磁碟（SED）、 link:../encryption-at-rest/return-seds-unprotected-mode-task.html["磁碟加密已移除"] 將磁碟恢復為無保護模式。
+
** 您可能也想要 link:../encryption-at-rest/sanitize-fips-drive-sed-task.html["清除FIPS磁碟機或SED"]。


* 如果要移除節點上的 LUN ，則應link:../san-admin/modify-slm-reporting-nodes-task.html["修改「選擇性LUN對應（SLM)報告節點」清單"]在移除節點之前先移除。
+
如果您未將節點及其HA合作夥伴從「SLM-報告節點」清單中移除、即使將包含LUN的磁碟區移至另一個節點、先前在節點上的LUN存取仍可能遺失。



建議您發出AutoSupport 一份資訊消息、通知NetApp技術支援部門正在移除節點。


IMPORTANT: 請勿執行如，，等作業 `cluster remove-node`， `cluster unjoin`以及 `node rename`正在進行自動化 ONTAP 升級時。

.關於這項工作
* 如果您執行的是混合版本叢集、您可以使用ONTAP 以《更新版本》9.3開頭的進階權限命令之一、移除最後一個低版本節點：
+
** ONTAP 9.3 ： `cluster unjoin -skip-last-low-version-node-check`
** ONTAP 9.4 及更新版本： `cluster remove-node -skip-last-low-version-node-check`


* 如果從四節點叢集中移除兩個節點，則剩餘兩個節點上的叢集 HA 將自動啟用。


[NOTE]
====
在將節點從叢集中移除之前，必須使連接到該節點的所有磁碟上的所有系統和使用者資料對使用者無法存取。

如果節點被錯誤地從叢集中移除，請聯絡 NetApp 支援以取得恢復選項的協助。

====
[[disable-ha]]
.步驟
. 將權限層級變更為進階：
+
[source, cli]
----
set -privilege advanced
----
. 識別叢集中具有 epsilon 的節點：
+
[source, cli]
----
cluster show
----
+
在以下範例中、「node0」目前持有 epsilon：

+
[listing]
----
cluster::*>
Node                 Health  Eligibility  Epsilon
-------------------- ------- ------------ ------------
node0                true    true         true
node1                true    true         false
node2                true    true         false
node3                true    true         false
----
. [[epsilon-true]]如果您要移除的節點包含 epsilon：
+
.. 將 epsilon 從要移除的節點中移出：
+
[source, cli]
----
cluster modify -node <name_of_node_to_be_removed> -epsilon false
----
.. 將 epsilon 移到您不會刪除的節點：
+
[source, cli]
----
cluster modify -node <node_name> -epsilon true
----


. 識別目前的主節點：
+
[source, cli]
----
cluster ring show
----
+
主節點是保存諸如，， `vldb`， `vifmgr` `bcomd`和 `crs`等處理程序的節點 `mgmt`。

. 如果要移除的節點是目前的主節點，請啟用叢集中的另一個節點以選舉為主節點：
+
.. 使目前的主節點不符合參加叢集的資格：
+
[source, cli]
----
cluster modify -node <node_name> -eligibility false
----
+
該節點會被標記為不健康，直到其恢復資格。當主節點失去資格時，叢集仲裁會從剩餘節點中選出一個作為新的主節點。

+
[NOTE]
====
如果您在 HA 對中的第一個節點上執行此步驟，則只需將該節點標記為不符合條件。請勿修改 HA 夥伴的狀態。

如果選擇合作夥伴節點作為新的主節點，您需要在將其設為不符合資格之前驗證它是否持有 epsilon。如果合作夥伴節點持有 epsilon，您需要在將其設為不符合資格之前，將 epsilon 移至叢集中剩餘的其他節點。當您重複這些步驟以移除合作夥伴節點時，您需要執行此操作。

====
.. 讓先前的主節點符合資格再次參與叢集：
+
[source, cli]
----
cluster modify -node <node_name> -eligibility true
----


. 登入您不會從叢集中移除之節點上的遠端節點管理 LIF 或叢集管理 LIF。
. 從叢集中移除節點：
+
|===
| 此版本... ONTAP | 使用此命令... 


 a| 
ONTAP 9.3
 a| 
[source, cli]
----
cluster unjoin
----


 a| 
更新版本ONTAP
 a| 
使用節點名稱：

[source, cli]
----
cluster remove-node -node <node_name>
----
使用節點 IP ：

[source, cli]
----
cluster remove-node -cluster_ip <node_ip>
----
|===
+
如果您有混合版本的叢集、而且要移除最後一個較低版本的節點、請使用 `-skip-last-low-version-node-check` 參數。

+
系統會通知您下列事項：

+
** 您也必須從叢集移除節點的容錯移轉合作夥伴。
** 節點被移除後，在它重新加入叢集之前，必須使用啟動選單選項 *(4) Clean configuration and initialize all disks* 或選項 *(9) Configure Advanced Drive Partitioning* 來擦除節點的配置並初始化所有磁碟。
+
如果您在移除節點之前必須處理的條件、就會產生故障訊息。例如、此訊息可能表示節點具有必須移除的共用資源、或節點位於叢集HA組態或必須停用的儲存容錯移轉組態中。

+
如果節點是仲裁主機、叢集將會短暫遺失、然後返回仲裁。此仲裁損失是暫時性的、不會影響任何資料作業。



. 如果失敗訊息指出錯誤情況、請解決這些情況、然後重新執行 `cluster remove-node` 或 `cluster unjoin` 命令。
+
節點從叢集中成功移除後會自動重新開機。

. 如果您要重新規劃節點的用途、請清除節點組態並初始化所有磁碟：
+
.. 在開機程序期間、當系統提示時、按Ctrl-C可顯示開機功能表。
.. 選擇開機選單選項 *(4) Clean configuration and initialize all disks*。


. [[return-admin]]返回管理員權限等級：
+
[source, cli]
----
set -privilege admin
----
. 重複步驟 <<disable-ha,1.>> 至 <<return-admin,9>>，從叢集中移除容錯移轉合作夥伴。


.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/cluster-remove-node.html["叢集移除節點"^]

