---
permalink: system-admin/restore-cluster-config-from-existing-task.html 
sidebar: sidebar 
keywords: restore, cluster, configuration, existing, configuration, failure, recovering, node, rejoin, cluster 
summary: 若要在叢集故障後從現有組態還原叢集組態、請使用您選擇的叢集組態重新建立叢集、並將其提供給恢復節點、然後將每個額外節點重新加入新叢集。 
---
= 使用 ONTAP 叢集組態備份檔案還原叢集
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
若要在叢集故障後從現有組態還原叢集組態、請使用您選擇的叢集組態重新建立叢集、並將其提供給恢復節點、然後將每個額外節點重新加入新叢集。

.關於這項工作
您只能執行此工作、從導致叢集組態遺失的災難中恢復。

[NOTE]
====
如果您是從組態備份檔案重新建立叢集、則必須聯絡技術支援部門、以解決組態備份檔案與叢集中現有組態之間的任何差異。

如果您從配置備份檔案還原集群，則自備份以來所做的任何設定變更都會遺失。還原後，您必須解決配置備份檔案和目前配置之間的任何差異。查看link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/ONTAP_Configuration_Backup_Resolution_Guide["NetApp知識庫： ONTAP設定備份解決指南"^]以獲得故障排除指導。

====
.步驟
. 停用每個HA配對的儲存容錯移轉：
+
`*storage failover modify -node _node_name_ -enabled false*`

+
您只需針對每個HA配對停用一次儲存容錯移轉。當您停用節點的儲存容錯移轉時、節點的合作夥伴也會停用儲存容錯移轉。

. 停止每個節點（恢復節點除外）：
+
`*system node halt -node _node_name_ -reason "text"*`

+
[listing]
----
cluster1::*> system node halt -node node0 -reason "recovering cluster"

Warning: Are you sure you want to halt the node? {y|n}: y
----
. 將權限層級設為進階：
+
`*set -privilege advanced*`

. 在恢復節點上、使用 `*system configuration recovery cluster recreate*` 用於重新建立叢集的命令。
+
此範例使用儲存在恢復節點上的組態資訊重新建立叢集：

+
[listing]
----
cluster1::*> configuration recovery cluster recreate -from node

Warning: This command will destroy your existing cluster. It will
         rebuild a new single-node cluster consisting of this node
         and its current configuration. This feature should only be
         used to recover from a disaster. Do not perform any other
         recovery operations while this operation is in progress.
Do you want to continue? {y|n}: y
----
+
在恢復節點上建立新的叢集。

. 如果您是從組態備份檔案重新建立叢集、請確認叢集還原仍在進行中：
+
`*system configuration recovery cluster show*`

+
如果您是從正常節點重新建立叢集、則不需要驗證叢集還原狀態。

+
[listing]
----
cluster1::*> system configuration recovery cluster show
 Recovery Status: in-progress
 Is Recovery Status Persisted: false
----
. 引導需要重新加入重新建立叢集的每個節點。
+
您必須一次重新啟動一個節點。

. 針對需要加入重新建立叢集的每個節點、執行下列步驟：
+
.. 從重新建立的叢集上健全的節點、重新加入目標節點：
+
`*system configuration recovery cluster rejoin -node _node_name_*`

+
此範例將「'node2'」目標節點重新加入重新建立的叢集：

+
[listing]
----
cluster1::*> system configuration recovery cluster rejoin -node node2

Warning: This command will rejoin node "node2" into the local
         cluster, potentially overwriting critical cluster
         configuration files. This command should only be used
         to recover from a disaster. Do not perform any other
         recovery operations while this operation is in progress.
         This command will cause node "node2" to reboot.
Do you want to continue? {y|n}: y
----
+
目標節點會重新開機、然後加入叢集。

.. 驗證目標節點是否正常、並已與叢集中的其他節點形成仲裁：
+
`*cluster show -eligibility true*`

+
目標節點必須重新加入重新建立的叢集、才能重新加入其他節點。

+
[listing]
----
cluster1::*> cluster show -eligibility true
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node0                true    true          false
node1                true    true          false
2 entries were displayed.
----


. 如果您是從組態備份檔案重新建立叢集、請將恢復狀態設為「完成」：
+
`*system configuration recovery cluster modify -recovery-status complete*`

. 返回管理權限層級：
+
`*set -privilege admin*`

. 如果叢集僅包含兩個節點、請使用 `*cluster ha modify*` 命令以重新啟用叢集 HA 。
. 使用 `*storage failover modify*` 為每個 HA 配對重新啟用儲存容錯移轉的命令。


.完成後
如果叢集具有SnapMirror對等關係、您也需要重新建立這些關係。如需詳細資訊、請參閱 link:../data-protection/index.html["資料保護"]。

.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/["指令參考資料ONTAP"^]
* link:https://docs.netapp.com/us-en/ontap-cli/storage-failover-modify.html["儲存故障轉移修改"^]

