---
permalink: system-admin/setup-autosupport-task.html 
sidebar: sidebar 
keywords: autosupport, set up autosupport, technical support 
summary: 設定 ONTAP 叢集、將 AutoSupport 訊息傳送給 NetApp 技術支援部門、並將電子郵件複本傳送給內部支援組織。 
---
= 設定AutoSupport 功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以設定 ONTAP 叢集、將 AutoSupport 訊息傳送給 NetApp 技術支援部門、並將電子郵件複本傳送給內部支援組織。在此過程中、您也可以在正式作業環境中使用組態之前、先測試組態。

.關於這項工作
從 ONTAP 9.5 開始、您可以同時為叢集的所有節點啟用和設定 AutoSupport 。當新節點加入叢集時、節點會自動繼承相同的 AutoSupport 組態。為支援此功能、請參閱 CLI 命令的範圍 `system node autosupport modify` 為叢集層級。。 `-node` 為了回溯相容性而保留命令選項、但會忽略該選項。


NOTE: 在 ONTAP 9.4 及更早版本中、命令 `system node autosupport modify` 專屬於每個節點。如果叢集執行的是 ONTAP 9.4 或更早版本、則需要在叢集中的每個節點上啟用和設定 AutoSupport 。

.開始之前
將 AutoSupport 訊息傳送至 NetApp 的建議傳輸組態是 HTTPS （ HTTP 搭配 TLS ）。此選項提供最強大的功能和最佳安全性。

檢閱 link:requirements-autosupport-reference.html["準備使用 AutoSupport"] 如需更多資訊、請在設定 ONTAP 叢集之前先參閱。

.步驟
. 確保AutoSupport 啟用了功能：
+
[listing]
----
system node autosupport modify -state enable
----
. 如果您想要 NetApp 技術支援人員接收 AutoSupport 訊息、請使用下列命令：
+
[listing]
----
system node autosupport modify -support enable
----
+
如果您想要啟用AutoSupport 支援以搭配AutoSupport 使用的功能、或是想要將核心傾印和效能歸檔檔案等大型檔案上傳至技術支援或指定的URL、則必須啟用此選項。

+

NOTE: AutoSupport OnDemand 預設為啟用，設定為使用 HTTPS 傳輸通訊協定傳送訊息給技術支援時，功能正常。

. 如果您啟用 NetApp 技術支援來接收 AutoSupport 訊息，請指定這些訊息要使用的傳輸通訊協定。
+
您可以從下列選項中選擇：

+
|===


| 如果您想要... | 然後設定的下列參數 `system node autosupport modify` 命令 ... 


 a| 
使用預設的HTTPS傳輸協定
 a| 
.. 設定 `-transport` 至 `https`。
.. 如果您使用 Proxy 、請設定 `-proxy-url` 到您 Proxy 的 URL 。
此組態可支援AutoSupport 透過不必要的功能進行通訊、以及上傳大型檔案。




 a| 
使用SMTP
 a| 
設定 `-transport` 至 `smtp`。

此組態不支援AutoSupport 以「根據需求」或上傳大型檔案。

|===
. 如果您想要內部支援組織或支援合作夥AutoSupport 伴接收到各種消息、請執行下列動作：
+
.. 設定的下列參數來識別組織中的收件者 `system node autosupport modify` 命令：
+
|===


| 設定此參數... | 對此... 


 a| 
`-to`
 a| 
內部支援組織最多五個以逗號分隔的個別電子郵件地址或通訊群組清單、可接收關鍵AutoSupport 的消息



 a| 
`-noteto`
 a| 
內部支援組織最多五個以逗號分隔的個別電子郵件地址或通訊群組清單、將會收到AutoSupport 專為行動電話和其他行動裝置所設計的關鍵字版資訊



 a| 
`-partner-address`
 a| 
支援合作夥伴組織中最多五個以逗號分隔的個別電子郵件地址或通訊群組清單、將會接收所有AutoSupport 的消息

|===
.. 使用列出目的地、檢查位址是否正確設定 `system node autosupport destinations show` 命令。


. 如果您在上一步中為內部支援組織設定收件者位址，或是選擇 SMTP 傳輸訊息給技術支援，請設定命令的下列參數來設定 SMTP `system node autosupport modify` ：
+
** 設定 `-mail-hosts` 至一或多個郵件主機、以逗號分隔。
+
您最多可以設定五個。

+
您可以在郵件主機名稱之後指定一個冒號和連接埠編號、為每個郵件主機設定連接埠值：例如、 `mymailhost.example.com:5678`，其中 5678 是郵件主機的連接埠。

** 設定 `-from` 傳送 AutoSupport 訊息的電子郵件地址。


. 設定DNS。
. 或者、如果您想要變更特定設定、請新增命令選項：
+
|===


| 如果您想要執行此動作... | 然後設定的下列參數 `system node autosupport modify` 命令 ... 


 a| 
移除、遮罩或編碼訊息中的敏感資料、以隱藏私有資料
 a| 
設定 `-remove-private-data` 至 `true`。如果您從變更 `false` 至 `true`，所有 AutoSupport 歷史記錄和所有相關文件都將被刪除。



 a| 
停止以週期AutoSupport 性的資訊訊息傳送效能資料
 a| 
設定 `-perf` 至 `false`。

|===
. 如果您使用 SMTP 將 AutoSupport 訊息傳送至 NetApp 、您可以選擇性地啟用 TLS 以改善安全性。
+
.. 顯示新參數的可用值：
+
[listing]
----
cluster1::> system node autosupport modify -smtp-encryption ?
----
.. 啟用 TLS 以傳輸 SMTP 訊息：
+
[listing]
----
cluster1::> system node autosupport modify -smtp-encryption start_tls
----
.. 顯示目前的組態：
+
[listing]
----
cluster1::> system node autosupport show -fields smtp-encryption
----


. 使用檢查整體組態 `system node autosupport show` 命令 `-node` 參數。
. 使用驗證 AutoSupport 作業 `system node autosupport check show` 命令。
+
如果回報有任何問題、請使用 `system node autosupport check show-details` 命令以檢視更多資訊。

. 測試AutoSupport 正在傳送和接收的不實訊息：
+
.. 使用 `system node autosupport invoke` 命令 `-type` 參數設為 `test`：
+
[listing]
----
cluster1::> system node autosupport invoke -type test -node node1
----
.. 確認NetApp正在接收AutoSupport 您的資訊：
+
[listing]
----
system node autosupport history show -node local
----
+
最新傳出的 AutoSupport 訊息狀態最終應變更為 `sent-successful` 適用於所有適當的傳輸協定目的地。

.. 您也可以選擇查看您為設定的任何地址的電子郵件、確認 AutoSupport 訊息已傳送至您的內部支援組織或支援合作夥伴 `-to`、 `-noteto`或 `-partner-address`  的參數 `system node autosupport modify` 命令。



