---
permalink: system-admin/setup-autosupport-task.html 
sidebar: sidebar 
keywords: set, up, autosupport, technical, support, organization, internal, configuration, test 
summary: 您可以控制AutoSupport 是否及如何將資訊傳送至技術支援部門和內部支援組織、然後測試組態是否正確。 
---
= 設定AutoSupport 功能
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以控制AutoSupport 是否及如何將資訊傳送至技術支援部門和內部支援組織、然後測試組態是否正確。

.關於這項工作
在發行版的更新版本中、您可以同時在叢集的所有節點上啟用及修改其組態。ONTAP AutoSupport當新節點加入叢集時、節點AutoSupport 會自動繼承叢集組態。您不需要個別更新每個節點上的組態。

[NOTE]
====
從 ONTAP 9.5 開始、就是的範圍 `system node autosupport modify` 命令適用於整個叢集。AutoSupport 組態會在叢集中的所有節點上修改、即使在 `-node` 已指定選項。此選項會被忽略、但會保留此選項、以供CLI向後相容。

在 ONTAP 9.4 及更早版本中、的範圍是 `system node autosupport modify` 命令是特定於節點的。應該在叢集中的每個節點上修改此組態。AutoSupport

====
根據預設、AutoSupport 每個節點上都會啟用支援功能、以便使用HTTPS傳輸傳輸傳輸協定將訊息傳送給技術支援。

您必須搭配使用 HTTPS 搭配 TLSv1.2 或安全 SMTP 、才能交付 AutoSupport 訊息、以提供最佳安全性、並支援所有最新的 AutoSupport 功能。

.步驟
. 確保AutoSupport 啟用了功能：
+
[listing]
----
system node autosupport modify -state enable
----
. 如果您想要技術支援部門接收AutoSupport 到資訊不全、請使用下列命令：
+
[listing]
----
system node autosupport modify -support enable
----
+
如果您想要啟用AutoSupport 支援以搭配AutoSupport 使用的功能、或是想要將核心傾印和效能歸檔檔案等大型檔案上傳至技術支援或指定的URL、則必須啟用此選項。

. 如果技術支援已啟用接收AutoSupport 功能不全的訊息、請指定訊息所使用的傳輸傳輸傳輸協定。
+
您可以從下列選項中選擇：

+
|===


| 如果您想要... | 然後設定的下列參數 `system node autosupport modify` 命令 ... 


 a| 
使用預設的HTTPS傳輸協定
 a| 
.. 設定 `-transport` 至 `https`。
.. 如果您使用 Proxy 、請設定 `-proxy-url` 到您 Proxy 的 URL 。
此組態可支援AutoSupport 透過不必要的功能進行通訊、以及上傳大型檔案。




 a| 
使用SMTP
 a| 
設定 `-transport` 至 `smtp`。

此組態不支援AutoSupport 以「根據需求」或上傳大型檔案。

|===
. 如果您想要內部支援組織或支援合作夥AutoSupport 伴接收到各種消息、請執行下列動作：
+
.. 設定的下列參數來識別組織中的收件者 `system node autosupport modify` 命令：
+
|===


| 設定此參數... | 對此... 


 a| 
`-to`
 a| 
內部支援組織最多五個以逗號分隔的個別電子郵件地址或通訊群組清單、可接收關鍵AutoSupport 的消息



 a| 
`-noteto`
 a| 
內部支援組織最多五個以逗號分隔的個別電子郵件地址或通訊群組清單、將會收到AutoSupport 專為行動電話和其他行動裝置所設計的關鍵字版資訊



 a| 
`-partner-address`
 a| 
支援合作夥伴組織中最多五個以逗號分隔的個別電子郵件地址或通訊群組清單、將會接收所有AutoSupport 的消息

|===
.. 使用列出目的地、檢查位址是否正確設定 `system node autosupport destinations show` 命令。


. 如果您要傳送訊息給內部支援組織、或是選擇 SMTP 傳輸訊息給技術支援、請設定的下列參數來設定 SMTP `system node autosupport modify` 命令：
+
** 設定 `-mail-hosts` 至一或多個郵件主機、以逗號分隔。
+
您最多可以設定五個。

+
您可以在郵件主機名稱之後指定一個冒號和連接埠編號、為每個郵件主機設定連接埠值：例如、 `mymailhost.example.com:5678`，其中 5678 是郵件主機的連接埠。

** 設定 `-from` 傳送 AutoSupport 訊息的電子郵件地址。


. 設定DNS。
. 或者、如果您想要變更特定設定、請新增命令選項：
+
|===


| 如果您想要執行此動作... | 然後設定的下列參數 `system node autosupport modify` 命令 ... 


 a| 
移除、遮罩或編碼訊息中的敏感資料、以隱藏私有資料
 a| 
設定 `-remove-private-data` 至 `true`。如果您從變更 `false` 至 `true`，所有 AutoSupport 歷史記錄和所有相關文件都將被刪除。



 a| 
停止以週期AutoSupport 性的資訊訊息傳送效能資料
 a| 
設定 `-perf` 至 `false`。

|===
. 使用檢查整體組態 `system node autosupport show` 命令 `-node` 參數。
. 使用驗證 AutoSupport 作業 `system node autosupport check show` 命令。
+
如果回報有任何問題、請使用 `system node autosupport check show-details` 命令以檢視更多資訊。

. 測試AutoSupport 正在傳送和接收的不實訊息：
+
.. 使用 `system node autosupport invoke` 命令 `-type` 參數設為 `test`。
+
[listing]
----
cluster1::> system node autosupport invoke -type test -node node1
----
.. 確認NetApp正在接收AutoSupport 您的資訊：
+
系統節點AutoSupport 的不正常歷程顯示節點為本機節點

+
最新傳出的 AutoSupport 訊息狀態最終應變更為 `sent-successful` 適用於所有適當的傳輸協定目的地。

.. 您也可以選擇檢查您為設定的任何地址的電子郵件、確定 AutoSupport 訊息已傳送至您的內部支援組織或支援合作夥伴 `-to`、 `-noteto`或 `-partner-address`  的參數 `system node autosupport modify` 命令。



