---
permalink: system-admin/ssh-login-security-concept.html 
sidebar: sidebar 
keywords: ssh, login, security, information, view, changes, privileges, unsuccessful, attempts, previous, successful, restrictions, considerations 
summary: 從功能表9.5開始ONTAP 、您可以檢視上次成功登入後、先前登入、登入失敗、以及權限變更等資訊。 
---
= ONTAP SSH 登入安全性
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從功能表9.5開始ONTAP 、您可以檢視上次成功登入後、先前登入、登入失敗、以及權限變更等資訊。

當您以SSH管理員使用者身分成功登入時、會顯示安全性相關資訊。您會收到下列情況的警示：

* 您的帳戶名稱上次登入的時間。
* 自上次成功登入以來、嘗試登入失敗的次數。
* 角色自上次登入後是否有所變更（例如、如果管理員帳戶的角色從「admin」變更為「備份」）。
* 自上次登入後、是否已修改角色的新增、修改或刪除功能。


[NOTE]
====
如果顯示的任何資訊可疑、請立即聯絡您的安全部門。

====
若要在登入時取得此資訊、必須符合下列先決條件：

* 您的SSH使用者帳戶必須以ONTAP 功能不均的形式配置。
* 您必須建立SSH安全登入。
* 您的登入嘗試必須成功。




== SSH登入安全性的限制和其他考量

下列限制與考量事項適用於SSH登入安全資訊：

* 此資訊僅適用於SSH型登入。
* 對於群組型管理帳戶（例如LDAP/NIS和AD帳戶）、如果使用者所屬的群組被配置為ONTAP 位於Sof the SView的管理帳戶、則使用者可以檢視SSH登入資訊。
+
不過、這些使用者無法顯示使用者帳戶角色變更的警示。此外、屬於AD群組的使用者ONTAP 若已在無法檢視上次登入後發生的不成功登入嘗試次數、則會被配置為在無法執行的系統管理帳戶。

* 當使用者帳戶從ONTAP 下列項目刪除時、系統會刪除為使用者維護的資訊：
* 除了SSH之外、不會顯示連線至應用程式的資訊。




== SSH登入安全資訊範例

下列範例示範登入後顯示的資訊類型。

* 此訊息會在每次成功登入後顯示：
+
[listing]
----

Last Login : 7/19/2018 06:11:32
----
* 如果自上次成功登入後嘗試登入失敗、則會顯示下列訊息：
+
[listing]
----

Last Login : 4/12/2018 08:21:26
Unsuccessful login attempts since last login - 5
----
* 如果嘗試登入失敗、且自上次成功登入後您的權限已修改、則會顯示下列訊息：
+
[listing]
----

Last Login : 8/22/2018 20:08:21
Unsuccessful login attempts since last login - 3
Your privileges have changed since last login
----

