---
permalink: system-admin/start-stop-storage-system-concept.html 
sidebar: sidebar 
keywords: start, stop, node, cli, ontap, troubleshoot, sp, reboot, system, boot, compactflash, shut down, shutdown,  unresponsive, shut, down, node, unresponsive, support, personnel, direct, troubleshoot 
summary: 基於維護或疑難排解的理由、您可能需要啟動或停止節點。您可以從ONTAP 支援的CLI、開機環境提示字元或SP CLI執行此動作。 
---
= 啟動或停止節點總覽
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
基於維護或疑難排解的理由、您可能需要啟動或停止節點。您可以從ONTAP 支援的CLI、開機環境提示字元或SP CLI執行此動作。

使用 SP CLI 命令 `system power off` 或 `system power cycle` 若要關閉或重新啟動節點、可能會導致節點關機不正確（也稱為 _ 不正常關機 _ ）、無法取代使用 ONTAP 的正常關機 `system node halt` 命令。



== 在系統提示下重新啟動節點

您可以在系統提示字元中、以正常模式重新開機節點。節點已設定為從開機裝置（例如PC compactflash卡）開機。

.步驟
. 如果叢集包含四個或更多節點、請確認要重新開機的節點未保留epsilon：
+
.. 將權限層級設為進階：
+
`*set -privilege advanced*`

.. 判斷哪個節點擁有epsilon：
+
`*cluster show*`

+
以下範例顯示「'node1'」擁有epsilon：

+
[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          true
node2                true    true          false
node3                true    true          false
node4                true    true          false
4 entries were displayed.
----
.. 如果要重新開機的節點保留了epsilon、請從節點移除epsilon：
+
`*cluster modify -node _node_name_ -epsilon false*`

.. 將epsilon指派給另一個將維持正常運作的節點：
+
`*cluster modify -node _node_name_ -epsilon true*`

.. 返回管理權限層級：
+
`*set -privilege admin*`



. 使用 `system node reboot` 命令重新啟動節點。
+
如果您未指定 `-skip-lif-migration` 參數時、命令會嘗試在重新開機之前、將資料和叢集管理同步移轉至另一個節點。如果LIF移轉失敗或逾時、重新開機程序便會中止、ONTAP 而導致錯誤顯示LIF移轉失敗。

+
[listing]
----
cluster1::> system node reboot -node node1 -reason "software upgrade"
----
+
節點會開始重新開機程序。出現此畫面的功能登入提示、表示重新開機程序已完成。ONTAP





== 在ONTAP 開機環境提示字元中開機

當您處於節點的開機環境提示時、可以開機目前版本或ONTAP 是發行的支援版本。

.步驟
. 使用從儲存系統提示存取開機環境提示 `system node halt` 命令。
+
儲存系統主控台會顯示開機環境提示字元。

. 在開機環境提示字元中、輸入下列其中一個命令：
+
|===
| 若要開機... | 輸入... 


 a| 
目前發行ONTAP 的
 a| 
`boot_ontap`



 a| 
從開機裝置獲得的鏡像ONTAP
 a| 
`boot_primary`



 a| 
來自開機裝置的支援鏡像ONTAP
 a| 
`boot_backup`

|===
+
如果您不確定要使用哪一個映像、您應該使用 `boot_ontap` 在第一個執行個體中。





== 關閉節點

如果某個節點沒有回應、或是支援人員引導您進行疑難排解、您可以關閉該節點。

.步驟
. 如果叢集包含四個或更多節點、請確認要關閉的節點未保留epsilon：
+
.. 將權限層級設為進階：
+
`*set -privilege advanced*`

.. 判斷哪個節點擁有epsilon：
+
`*cluster show*`

+
以下範例顯示「'node1'」擁有epsilon：

+
[listing]
----
cluster1::*> cluster show
Node                 Health  Eligibility   Epsilon
-------------------- ------- ------------  ------------
node1                true    true          true
node2                true    true          false
node3                true    true          false
node4                true    true          false
4 entries were displayed.
----
.. 如果要關閉的節點保留了epsilon、請從節點移除epsilon：
+
`*cluster modify -node _node_name_ -epsilon false*`

.. 將epsilon指派給另一個將維持正常運作的節點：
+
`*cluster modify -node _node_name_ -epsilon true*`

.. 返回管理權限層級：
+
`*set -privilege admin*`



. 使用 `system node halt` 關閉節點的命令。
+
如果您未指定 `-skip-lif-migration` 參數時、命令會嘗試在關機之前、同步將資料和叢集管理移轉至另一個節點。如果LIF移轉失敗或逾時、關機程序便會中止、ONTAP 而導致錯誤顯示LIF移轉失敗。

+
您可以使用這兩種方式、在關機時手動觸發核心傾印 `-dump` 參數。

+
下列範例會關閉名為「'node1'」的節點、以進行硬體維護：

+
[listing]
----
cluster1::> system node halt -node node1 -reason 'hardware maintenance'
----

