---
permalink: system-admin/troubleshoot-autosupport-messages-not-received-task.html 
sidebar: sidebar 
keywords: troubleshoot, autosupport, messagem receive, deliver, generate 
summary: 如果系統未傳送AutoSupport 此資訊、您可以判斷AutoSupport 這是因為無法產生訊息、還是無法傳送訊息。 
---
= 疑難排解AutoSupport 未收到訊息時的問題
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
如果系統未傳送AutoSupport 此資訊、您可以判斷AutoSupport 這是因為無法產生訊息、還是無法傳送訊息。

.步驟
. 使用「System Node AutoSupport of the history show」命令檢查訊息的傳送狀態。
. 讀取狀態。
+
[cols="25,75"]
|===
| 此狀態 | 方法 


 a| 
正在初始化
 a| 
收集程序正在開始。如果此狀態是暫時性的、一切都很好。但是、如果此狀態持續存在、則會發生問題。



 a| 
集合失敗
 a| 
無法在假脫機目錄中建立不含任何功能的內容。AutoSupport AutoSupport您可以輸入「系統節點的資訊記錄show -detail」命令來檢視AutoSupport 哪些資訊。AutoSupport



 a| 
收集進行中
 a| 
正在收集的是一些不含知識的內容。AutoSupport AutoSupport您可以輸入「系統節點資訊清單show」命令來檢視AutoSupport 哪些內容是由哪個部分收集AutoSupport 而來。



 a| 
已佇列
 a| 
系統會排入佇列以供傳送、但尚未傳送。AutoSupport



 a| 
傳輸
 a| 
目前正在傳送訊息。AutoSupport



 a| 
已成功傳送
 a| 
成功傳達訊息。AutoSupport您可以輸入「系統節點的資訊畫面記錄show -fulfit'命令、瞭AutoSupport 解哪些地方是由資訊提供的。AutoSupport



 a| 
忽略
 a| 
不提供訊息的目的地。AutoSupport您可以輸入「系統節點AutoSupport 資訊show -fulfit'命令來檢視交付詳細資料。



 a| 
重新佇列
 a| 
嘗試傳送訊息、但嘗試失敗。AutoSupport因此AutoSupport 、將訊息放回傳送佇列中、以便再次嘗試傳送。您可以輸入「系統節點AutoSupport 資訊歷史展示」命令來檢視錯誤。



 a| 
傳輸失敗
 a| 
無法以指定次數傳送訊息、並停止嘗試傳送訊息。AutoSupport您可以輸入「系統節點AutoSupport 資訊歷史展示」命令來檢視錯誤。



 a| 
隨需忽略
 a| 
雖然成功處理了這個消息、但《不再是我的選擇了。AutoSupport AutoSupport

|===
. 執行下列其中一項動作：
+
|===
| 以取得此狀態 | 請這麼做 


 a| 
初始化或收集失敗
 a| 
聯絡NetApp支援部門、因為AutoSupport 無法產生訊息。請提及下列知識庫文章：

link:https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/AutoSupport_is_failing_to_deliver%3A_status_is_stuck_in_initializing["無法提供：狀態卡在初始化中AutoSupport"^]



 a| 
忽略、重新佇列或傳輸失敗
 a| 
檢查目的地是否已正確設定為使用SMTP、HTTP或HTTPS、因為AutoSupport 無法傳送訊息。

|===

