---
permalink: system-admin/types-autosupport-messages-reference.html 
sidebar: sidebar 
keywords: active, iq, autosupport, messages, content, support, subsystems 
summary: 支援子系統的狀態資訊包含在內。AutoSupport瞭解AutoSupport 包含哪些資訊可協助您解讀或回覆您在電子郵件中收到的訊息、或是Active IQ 在本網站上檢視（先前稱為「我AutoSupport 的」）。 
---
= 各種類型的消息及其內容AutoSupport
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
支援子系統的狀態資訊包含在內。AutoSupport瞭解AutoSupport 包含哪些資訊可協助您解讀或回覆您在電子郵件中收到的訊息、或是Active IQ 在本網站上檢視（先前稱為「我AutoSupport 的」）。

|===
| 訊息類型 | 訊息所包含的資料類型 


 a| 
事件觸發
 a| 
包含事件發生所在特定子系統相關內容敏感資料的檔案



 a| 
每日
 a| 
記錄檔



 a| 
效能
 a| 
過去24小時內取樣的效能資料



 a| 
每週
 a| 
組態與狀態資料



 a| 
觸發於「系統節點AutoSupport 叫用」命令
 a| 
取決於在「-type（類型）參數中指定的值：

* 「測試」會傳送使用者觸發的訊息、其中包含一些基本資料。
+
此訊息也會使用「收件者」選項、從技術支援部門觸發自動電子郵件回應、以確認AutoSupport 是否收到任何指定的電子郵件地址。

* 效能是傳送效能資料的最佳選擇。
* 「All」（全部）會傳送使用者觸發的訊息、內含一組類似每週訊息的完整資料、包括每個子系統的疑難排解資料。
+
技術支援部門通常會要求提供此訊息。





 a| 
由「系統節點AutoSupport 無法叫用核心上傳」命令觸發
 a| 
節點的核心傾印檔案



 a| 
由「系統節點AutoSupport flexote-Performance archive」命令觸發
 a| 
效能歸檔檔案的指定時間段



 a| 
由AutoSupport NetApp按需觸發
 a| 
根據需求、可索取新訊息或過去訊息：AutoSupport

* 根據AutoSupport 蒐集的類型、新訊息可以是「測試」、「全部」或「效能」。
* 過去的訊息取決於重新傳送的訊息類型。


支援中心可要求新訊息、將下列檔案上傳至NetApp支援網站：AutoSupport http://["mysupport.netapp.com"]：

* 核心傾印
* 效能歸檔


|===