---
permalink: system-admin/upload-core-dump-files-task.html 
sidebar: sidebar 
keywords: upload, core, dump, file, autosupport, device, send, messages, email 
summary: 儲存核心傾印檔案時、會產生事件訊息。如果啟用此功能並將其設定為傳送訊息給NetApp支援部門、則會傳輸一則消息、並傳送自動電子郵件確認訊息給您。AutoSupport AutoSupport 
---
= 上傳 ONTAP AutoSupport 核心傾印檔案
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
儲存核心傾印檔案時、會產生事件訊息。如果啟用此功能並將其設定為傳送訊息給NetApp支援部門、則會傳輸一則消息、並傳送自動電子郵件確認訊息給您。AutoSupport AutoSupport

.您需要的產品
* 您必須使用AutoSupport 下列設定來設定不必要功能：
+
** 節點上啟用了支援。AutoSupport
** 將支援功能設定為傳送訊息給技術支援。AutoSupport
** 將支援使用HTTP或HTTPS傳輸傳輸傳輸傳輸協定。AutoSupport
+
傳送內含大型檔案（例如核心傾印檔案）的訊息時、不支援該SMTP傳輸傳輸傳輸傳輸傳輸協定。





.關於這項工作
您也可以使用透過 AutoSupport 服務透過 HTTPS 上傳核心傾印檔案 `system node autosupport invoke-core-upload` 命令、如果 NetApp 支援部門要求的話。

https://kb.netapp.com/Advice_and_Troubleshooting/Miscellaneous/How_to_upload_a_file_to_NetApp["如何將檔案上傳至NetApp"^]

.步驟
. 使用檢視節點的核心傾印檔案 `system node coredump show` 命令。
+
在下列範例中、會顯示本機節點的核心傾印檔案：

+
[listing]
----
cluster1::> system node coredump show -node local
Node:Type Core Name Saved Panic Time
--------- ------------------------------------------- ----- -----------------
node:kernel
core.4073000068.2013-09-11.15_05_01.nz true 9/11/2013 15:05:01
----
. 產生 AutoSupport 訊息、並使用上傳核心傾印檔案 `system node autosupport invoke-core-upload` 命令。
+
在下列範例中，會產生一則 AutoSupport 訊息並傳送至預設位置（即技術支援部門），同時將核心傾印檔案上傳至預設位置（即 NetApp 支援網站）：

+
[listing]
----
cluster1::> system node autosupport invoke-core-upload -core-filename
core.4073000068.2013-09-11.15_05_01.nz -node local
----
+
在下列範例中AutoSupport 、會產生一個SURIING訊息並傳送至URI中指定的位置、核心傾印檔案會上傳至URI：

+
[listing]
----
cluster1::> system node autosupport invoke-core-upload -uri https//files.company.com -core-filename
core.4073000068.2013-09-11.15_05_01.nz -node local
----

