---
permalink: system-admin/when-where-autosupport-messages-sent-concept.html 
sidebar: sidebar 
keywords: active, iq, digital advisor, active iq, autosupport, messages, email, manual, scheduled, event, triggered 
summary: 根據訊息類型、將訊息傳送給不同的收件者。AutoSupport瞭解 AutoSupport 傳送訊息的時間和地點、可協助您瞭解透過電子郵件收到的訊息、或是在數位顧問網站上檢視。 
---
= 瞭解 ONTAP AutoSupport 訊息的傳送時間和位置
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
根據訊息類型、將訊息傳送給不同的收件者。AutoSupport瞭解 AutoSupport 傳送訊息的時間和地點、可協助您瞭解透過電子郵件收到的訊息、或是在數位顧問網站上檢視。

除非另有指定、否則下表中的設定是的參數 `system node autosupport modify` 命令。



== 事件觸發的訊息

當系統發生需要採取修正行動的事件時AutoSupport 、則會自動傳送事件觸發的訊息。

|===
| 訊息傳送時 | 訊息傳送位置 


 a| 
回應EMS中的觸發事件AutoSupport
 a| 
中指定的位址 `-to` 和 `-noteto`。（僅會傳送影響服務的重大事件。）

中指定的位址 `-partner-address`

技術支援、如果 `-support` 設為 `enable`

|===


== 排程的訊息

自動定期傳送數則訊息。AutoSupport

|===
| 訊息傳送時 | 訊息傳送位置 


 a| 
每日（依預設、於上午12：00之間傳送和上午1：00作為記錄訊息）
 a| 
中指定的位址 `-partner-address`

技術支援、如果 `-support` 設為 `enable`



 a| 
每日（依預設、於上午12：00之間傳送和上午1：00效能訊息） `-perf` 參數設定為 `true`
 a| 
合作夥伴地址中指定的地址

技術支援、如果 `-support` 設為 `enable`



 a| 
每週（依預設、星期日的傳送時間為上午12：00和上午1：00）
 a| 
中指定的位址 `-partner-address`

技術支援、如果 `-support` 設為 `enable`

|===


== 手動觸發的訊息

您可以手動初始化AutoSupport 或重新傳送一個消息。

|===
| 訊息傳送時 | 訊息傳送位置 


 a| 
您可以使用手動初始化訊息 `system node autosupport invoke` 命令
 a| 
如果使用指定 URI `-uri` 中的參數 `system node autosupport invoke` 命令會將訊息傳送至該 URI 。

如果 `-uri` 如果省略、訊息會傳送至中指定的位址 `-to` 和 `-partner-address`。此訊息也會傳送給技術支援人員、如果有的話 `-support` 設為 `enable`。



 a| 
您可以使用手動初始化訊息 `system node autosupport invoke-core-upload` 命令
 a| 
如果使用指定 URI `-uri` 中的參數 `system node autosupport invoke-core-upload` 命令會將訊息傳送至該 URI 、核心傾印檔案會上傳至 URI 。

如果 `-uri` 在中省略 `system node autosupport invoke-core-upload` 命令會將訊息傳送給技術支援人員、核心傾印檔案會上傳至技術支援網站。

這兩種情況都需要這樣做 `-support` 設為 `enable` 和 `-transport` 設為 `https` 或 `http`。

由於核心傾印檔案太大、因此訊息不會傳送至中指定的位址 `-to` 和 `-partner-addresses` 參數。



 a| 
您可以使用手動初始化訊息 `system node autosupport invoke-performance-archive` 命令
 a| 
如果使用指定 URI `-uri` 中的參數 `system node autosupport invoke-performance-archive` 命令會將訊息傳送至該 URI 、效能封存檔案會上傳至 URI 。

如果 `-uri` 在中省略 `system node autosupport invoke-performance-archive`、訊息會傳送給技術支援、效能歸檔檔案會上傳至技術支援網站。

這兩種情況都需要這樣做 `-support` 設為 `enable` 和 `-transport` 設為 `https` 或 `http`。

由於效能歸檔檔案的大小很大、因此訊息不會傳送至中指定的位址 `-to` 和 `-partner-addresses` 參數。



 a| 
您可以使用手動重新傳送過去的訊息 `system node autosupport history retransmit` 命令
 a| 
僅限您在中指定的 URI `-uri` 的參數 `system node autosupport history retransmit` 命令

|===


== 由技術支援所觸發的訊息

技術支援人員AutoSupport 可以使用AutoSupport 「支援不受需求」功能、向支援中心索取訊息。

|===
| 訊息傳送時 | 訊息傳送位置 


 a| 
當獲取交付指示以產生新的資訊提供訊息時AutoSupport AutoSupport
 a| 
中指定的位址 `-partner-address`

技術支援、如果 `-support` 設為 `enable` 和 `-transport` 設為 `https`



 a| 
當獲得傳遞指示以重新傳送過去的消息時AutoSupport AutoSupport
 a| 
技術支援、如果 `-support` 設為 `enable` 和 `-transport` 設為 `https`



 a| 
當您取得交付指示、以產生新的資訊檔來上傳核心傾印或效能歸檔檔案時AutoSupport AutoSupport
 a| 
技術支援、如果 `-support` 設為 `enable` 和 `-transport` 設為 `https`。核心傾印或效能歸檔檔案會上傳至技術支援網站。

|===