---
permalink: authentication/config-worksheets-reference.html 
sidebar: sidebar 
keywords: worksheets, administrator authentication, rbac configuration 
summary: 在建立登入帳戶及設定角色型存取控制（RBAC）之前、您應該先收集組態工作表中每個項目的資訊。 
---
= 系統管理員驗證和RBAC組態工作表
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
在建立登入帳戶及設定角色型存取控制（RBAC）之前、您應該先收集組態工作表中每個項目的資訊。



== 建立或修改登入帳戶

您可以使用提供這些值 `security login create` 命令：當您啟用登入帳戶以存取儲存虛擬機器（ SVM ）時。您可以使用提供相同的值 `security login modify` 命令：修改帳戶存取 SVM 的方式。

[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
帳戶存取的SVM名稱。預設值為叢集的管理SVM名稱。
 a| 



 a| 
`-user-or-group-name`
 a| 
帳戶的使用者名稱或群組名稱。指定群組名稱可讓您存取群組中的每個使用者。您可以將使用者名稱或群組名稱與多個應用程式建立關聯。
 a| 



 a| 
`-application`
 a| 
用於存取SVM的應用程式：

* `http`
* `ontapi`
* `snmp`
* `ssh`

 a| 



 a| 
`-authmethod`
 a| 
用於驗證帳戶的方法：

* `cert` 用於 SSL 憑證驗證
* `domain` 用於 Active Directory 驗證
* `nsswitch` 用於 LDAP 或 NIS 驗證
* `password` 用於使用者密碼驗證
* `publickey` 用於公開金鑰驗證
* `community` 適用於 SNMP 社群字串
* `usm` 適用於 SNMP 使用者安全模式
* `saml` 用於安全聲明標記語言（ SAML ）驗證

 a| 



 a| 
`-remote-switch-ipaddress`
 a| 
遠端交換器的IP位址。遠端交換器可以是由叢集交換器健全狀況監控器（CSHM）監控的叢集交換器、或MetroCluster 是由不健全狀況監控器（MCC-HM）監控的光纖通道（FC）交換器。此選項僅適用於應用程式 `snmp` 驗證方法是 `usm`。
 a| 



 a| 
`-role`
 a| 
指派給帳戶的存取控制角色：

* 對於叢集（ admin SVM ）、預設值為 `admin`。
* 對於資料 SVM 、預設值為 `vsadmin`。

 a| 



 a| 
`-comment`
 a| 
（選用）帳戶的說明文字。您應該以雙引號（"）括住文字。
 a| 



 a| 
`-is-ns-switch-group`
 a| 
帳戶是 LDAP 群組帳戶還是 NIS 群組帳戶 (`yes` 或 `no`）。
 a| 



 a| 
`-second-authentication-method`
 a| 
第二種驗證方法、適用於* ONTAP 《支援*》9.3 *的多因素驗證：

* `none` 如果不使用多因素驗證、則為預設值
* `publickey` 用於公開金鑰驗證 `authmethod` 為密碼或 nsswitch
* `password` 用於使用者密碼驗證 `authmethod` 為公開金鑰
* `nsswitch` 驗證方法為 publickey 時用於使用者密碼驗證
+
[NOTE]
====
從支援NS9.4開始ONTAP 、即可支援nsswitch。

====


驗證順序一律是公開金鑰、然後是密碼。
 a| 



 a| 
`-is-ldap-fastbind`
 a| 
從「支援支援支援」9.11.1開始ONTAP 、設定為「真」時、會啟用LDAP快速連結以進行Nsswitch驗證；預設值為「假」。若要使用 LDAP 快速繫結、請使用 `-authentication-method` 值必須設定為 `nsswitch`。 link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["瞭解適用於Nsswitch驗證的LDAP fastbind。"]
 a| 

|===


== 定義自訂角色

您可以使用提供這些值 `security login role create` 命令：定義自訂角色。

[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
（選用）與角色相關聯的SVM名稱。
 a| 



 a| 
`-role`
 a| 
角色名稱。
 a| 



 a| 
`-cmddirname`
 a| 
角色提供存取權的命令或命令目錄。您應該以雙引號（"）括住命令子目錄名稱。例如、 `"volume snapshot"`。您必須輸入 `DEFAULT` 指定所有命令目錄。
 a| 



 a| 
`-access`
 a| 
（選用）角色的存取層級。對於命令目錄：

* `none` （自訂角色的預設值）會拒絕存取命令目錄中的命令
* `readonly` 授予存取權 `show` 命令目錄及其子目錄中的命令
* `all` 授予對命令目錄及其子目錄中所有命令的存取權


用於 _nonnonnalin 命令 _ （不以結尾的命令） `create`、 `modify`、 `delete`或 `show`）：

* `none` （自訂角色的預設值）拒絕存取命令
* `readonly` 不適用
* `all` 授予對命令的存取權


若要授與或拒絕內部命令的存取權、您必須指定命令目錄。
 a| 



 a| 
`-query`
 a| 
（選用）用於篩選存取層級的查詢物件、其格式為命令的有效選項或命令目錄中的命令的有效選項。您應該以雙引號（"）括住查詢物件。例如、如果命令目錄為 `volume`，查詢物件 `"-aggr aggr0"` 將啟用的存取 `aggr0` 僅 Aggregate 。
 a| 

|===


== 將公開金鑰與使用者帳戶建立關聯

您可以使用提供這些值 `security login publickey create` 命令：將 SSH 公開金鑰與使用者帳戶建立關聯。

[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
（選用）帳戶存取的SVM名稱。
 a| 



 a| 
`-username`
 a| 
帳戶的使用者名稱。預設值、 `admin`，這是叢集管理員的預設名稱。
 a| 



 a| 
`-index`
 a| 
公開金鑰的索引編號。如果金鑰是為帳戶建立的第一個金鑰、則預設值為0；否則、預設值大於該帳戶現有的最高索引編號。
 a| 



 a| 
`-publickey`
 a| 
OpenSSH公開金鑰。您應該以雙引號（"）括住金鑰。
 a| 



 a| 
`-role`
 a| 
指派給帳戶的存取控制角色。
 a| 



 a| 
`-comment`
 a| 
（選用）公開金鑰的說明文字。您應該以雙引號（"）括住文字。
 a| 



 a| 
`-x509-certificate`
 a| 
（選用）從 ONTAP 9.13.1 開始、可讓您管理與 SSH 公開金鑰的 X.509 憑證關聯。

當您將 X.509 憑證與 SSH 公開金鑰建立關聯時、 ONTAP 會在 SSH 登入時檢查此憑證是否有效。如果已過期或遭撤銷、則不允許登入、並停用相關的 SSH 公開金鑰。可能值：

* `install`：安裝指定的 PEM 編碼的 X.509 憑證、並將其與 SSH 公開金鑰建立關聯。包含您要安裝之憑證的完整文字。
* `modify`：使用指定的證書更新現有的 PEM 編碼的 X.509 證書，並將其與 SSH 公共密鑰相關聯。包含新憑證的完整文字。
* `delete`：移除現有的 X.509 憑證與 SSH 公開金鑰的關聯。

 a| 

|===


== 安裝CA簽署的伺服器數位憑證

您可以使用提供這些值 `security certificate generate-csr` 命令：當您產生數位憑證簽署要求（ CSR ）、以用於將 SVM 驗證為 SSL 伺服器時。

[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-common-name`
 a| 
憑證的名稱、可以是完整網域名稱（FQDN）或自訂通用名稱。
 a| 



 a| 
`-size`
 a| 
私密金鑰中的位元數。價值越高、金鑰就越安全。預設值為 `2048`。可能的值包括 `512`、 `1024`、 `1536`和 `2048`。
 a| 



 a| 
`-country`
 a| 
SVM所在國家/地區、以兩個字母的代碼表示。預設值為 `US`。請參閱手冊頁以取得代碼清單。
 a| 



 a| 
`-state`
 a| 
SVM的州或省。
 a| 



 a| 
`-locality`
 a| 
SVM的位置。
 a| 



 a| 
`-organization`
 a| 
SVM的組織。
 a| 



 a| 
`-unit`
 a| 
SVM組織中的單位。
 a| 



 a| 
`-email-addr`
 a| 
SVM聯絡人管理員的電子郵件地址。
 a| 



 a| 
`-hash-function`
 a| 
用於簽署憑證的密碼編譯雜湊功能。預設值為 `SHA256`。可能的值包括 `SHA1`、 `SHA256`和 `MD5`。
 a| 

|===
您可以使用提供這些值 `security certificate install` 當您安裝CA簽署的數位憑證以用於驗證叢集或SVM為SSL伺服器時、命令。下表僅顯示與帳戶組態相關的選項。

[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
要安裝憑證的SVM名稱。
 a| 



 a| 
`-type`
 a| 
憑證類型：

* `server` 適用於伺服器憑證和中繼憑證
* `client-ca` 用於 SSL 用戶端根 CA 的公開金鑰憑證
* `server-ca` 用於 ONTAP 為用戶端之 SSL 伺服器根 CA 的公開金鑰憑證
* `client` 適用於自我簽署或 CA 簽署的數位憑證、以及 ONTAP 做為 SSL 用戶端的私密金鑰

 a| 

|===


== 設定Active Directory網域控制器存取

您可以使用提供這些值 `security login domain-tunnel create` 命令：當您已為資料 SVM 設定 SMB 伺服器、並且想要將 SVM 設定為閘道或 _tunnel_ 、以便 Active Directory 網域控制器存取叢集時。

[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
已設定SMB伺服器的SVM名稱。
 a| 

|===
您可以使用提供這些值 `vserver active-directory create` 當您尚未設定 SMB 伺服器且想要在 Active Directory 網域上建立 SVM 電腦帳戶時的命令。

[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
您要為其建立Active Directory電腦帳戶的SVM名稱。
 a| 



 a| 
`-account-name`
 a| 
電腦帳戶的NetBios名稱。
 a| 



 a| 
`-domain`
 a| 
完整網域名稱（FQDN）。
 a| 



 a| 
`-ou`
 a| 
網域中的組織單位。預設值為 `CN=Computers`。將此值附加到網域名稱、以產生Active Directory辨別名稱。ONTAP
 a| 

|===


== 設定LDAP或NIS伺服器存取

您可以使用提供這些值 `vserver services name-service ldap client create` 為 SVM 建立 LDAP 用戶端組態時的命令。

[NOTE]
====
從 ONTAP 9.2 開始 `-ldap-servers` 欄位會取代 `-servers` 欄位。此新欄位可以使用主機名稱或IP位址做為LDAP伺服器的值。

====
下表僅顯示與帳戶組態相關的選項：

[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
用戶端組態的SVM名稱。
 a| 



 a| 
`-client-config`
 a| 
用戶端組態的名稱。
 a| 



 a| 
`-servers`
 a| 
*《S169.0、9.1*》：用戶端連線之LDAP伺服器的IP位址清單（以英文分隔）ONTAP 。
 a| 



 a| 
`-ldap-servers`
 a| 
*《S122*》：用戶端所連接之LDAP伺服器的IP位址和主機名稱清單、以逗號分隔。ONTAP
 a| 



 a| 
`-schema`
 a| 
用戶端用來進行LDAP查詢的架構。
 a| 



 a| 
`-use-start-tls`
 a| 
用戶端是否使用 Start TLS 來加密與 LDAP 伺服器的通訊 (`true` 或 `false`）。

[NOTE]
====
只有資料SVM存取才支援Start TLS。不支援存取管理SVM。

==== a| 

|===
您可以使用提供這些值 `vserver services name-service ldap create` 將 LDAP 用戶端組態與 SVM 建立關聯時的命令。

[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
要與用戶端組態建立關聯的SVM名稱。
 a| 



 a| 
`-client-config`
 a| 
用戶端組態的名稱。
 a| 



 a| 
`-client-enabled`
 a| 
SVM 是否可以使用 LDAP 用戶端組態 (`true` 或 `false`）。
 a| 

|===
您可以使用提供這些值 `vserver services name-service nis-domain create` 在 SVM 上建立 NIS 網域組態時的命令。

[NOTE]
====
從 ONTAP 9.2 開始 `-nis-servers` 欄位會取代 `-servers` 欄位。這個新欄位可以使用主機名稱或 IP 位址做為 NIS 伺服器的值。

====
[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
要在其中建立網域組態的SVM名稱。
 a| 



 a| 
`-domain`
 a| 
網域名稱。
 a| 



 a| 
`-active`
 a| 
網域是否為作用中 (`true` 或 `false`）。
 a| 



 a| 
`-servers`
 a| 
*《S169.0、9.1*：網域組態所使用之NIS伺服器的IP位址清單》。ONTAP
 a| 



 a| 
`-nis-servers`
 a| 
*《S122*》：網域組態所使用之NIS伺服器的IP位址和主機名稱清單、以英文分隔。ONTAP
 a| 

|===
您可以使用提供這些值 `vserver services name-service ns-switch create` 命令：指定名稱服務來源的查詢順序。

[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-vserver`
 a| 
要設定名稱服務查詢順序的SVM名稱。
 a| 



 a| 
`-database`
 a| 
名稱服務資料庫：

* `hosts` 適用於檔案和 DNS 名稱服務
* `group` 適用於檔案、 LDAP 和 NIS 名稱服務
* `passwd` 適用於檔案、 LDAP 和 NIS 名稱服務
* `netgroup` 適用於檔案、 LDAP 和 NIS 名稱服務
* `namemap` 適用於檔案和 LDAP 名稱服務

 a| 



 a| 
`-sources`
 a| 
查詢名稱服務來源的順序（在以逗號分隔的清單中）：

* `files`
* `dns`
* `ldap`
* `nis`

 a| 

|===


== 設定SAML存取

從 ONTAP 9.3 開始、您可以將這些值提供給 `security saml-sp create` 用於設定 SAML 驗證的命令。

[cols="3*"]
|===


| 欄位 | 說明 | 您的價值 


 a| 
`-idp-uri`
 a| 
身分識別供應商（IDP）主機的FTP位址或HTTP位址、可從該主機下載IDP中繼資料。
 a| 



 a| 
`-sp-host`
 a| 
SAML服務供應商主機ONTAP （亦即系統）的主機名稱或IP位址。根據預設、會使用叢集管理LIF的IP位址。
 a| 



 a| 
`-cert-ca` 和 `-cert-serial`或 `-cert-common-name`
 a| 
服務供應商主機ONTAP 的伺服器認證詳細資料（不知系統如何）。您可以輸入服務供應商的憑證發行憑證授權單位（CA）和憑證序號、或是伺服器憑證一般名稱。
 a| 



 a| 
`-verify-metadata-server`
 a| 
IDP 中繼資料伺服器的身分識別是否必須驗證  `true` 或 `false`）。最佳實務做法是永遠將此值設為 `true`。
 a| 

|===