---
permalink: authentication/dynamic-authorization-overview.html 
sidebar: sidebar 
keywords: dynamic, authorization, framework, security, login, ssh 
summary: 設定動態授權架構、以提高 SSH 登入的安全性、並限制在可疑情況下執行某些命令。 
---
= 瞭解 ONTAP 動態授權
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
從 ONTAP 9.15.1 開始、系統管理員可以設定並啟用動態授權、以提高遠端存取 ONTAP 的安全性、同時降低惡意攻擊者可能造成的潛在損害。有了 ONTAP 9.15.1 、動態授權提供了一個初始架構、可將安全分數指派給使用者、如果他們的活動看起來可疑、則可透過額外的授權檢查來挑戰他們、或是完全拒絕作業。系統管理員可以建立規則、指派信任分數、以及限制命令、以決定何時允許或拒絕使用者的特定活動。系統管理員可以在整個叢集範圍內啟用動態授權、或是為個別的儲存 VM 啟用授權。



== 動態授權的運作方式

動態授權使用信任評分系統、根據授權原則、將不同的信任等級指派給使用者。根據使用者的信任層級、可以允許或拒絕他們執行的活動、也可以提示使用者進行進一步驗證。

請參閱link:configure-dynamic-authorization.html["自訂動態授權"]以深入瞭解如何設定準則分數權重和其他動態授權屬性。



=== 信任的裝置

使用動態授權時、受信任裝置的定義是使用者使用公開金鑰驗證作為驗證方法之一來登入 ONTAP 的裝置。裝置受信任、因為只有該使用者擁有對應的私密金鑰。



=== 動態授權範例

以嘗試刪除磁碟區的三個不同使用者為例。當他們嘗試執行作業時、會檢查每位使用者的風險等級：

* 第一位使用者從信任的裝置登入時、先前的驗證失敗次數極少、這使得她的風險等級偏低；無需額外驗證即可執行此作業。
* 第二位使用者從信任的裝置登入時、其先前的驗證失敗百分比適中、因此風險等級較為溫和；在允許操作之前、系統會提示她進行額外驗證。
* 第三位使用者從不受信任的裝置登入時、其先前的驗證失敗率很高、因此風險等級很高；不允許此作業。


.下一步
* link:enable-disable-dynamic-authorization.html["啟用或停用動態授權"]
* link:configure-dynamic-authorization.html["自訂動態授權"]

