---
permalink: authentication/enable-ssh-public-key-accounts-task.html 
sidebar: sidebar 
keywords: enable, ssh, public key, accounts 
summary: 您可以使用安全登入create命令、讓系統管理員帳戶使用SSH公開金鑰來存取管理或資料SVM。 
---
= 啟用SSH公開金鑰帳戶
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `security login create` 命令可讓系統管理員帳戶使用 SSH 公開金鑰存取管理或資料 SVM 。

.您需要的產品
您必須是叢集管理員才能執行此工作。

.關於這項工作
* 您必須先將公開金鑰與帳戶建立關聯、帳戶才能存取SVM。
+
xref:manage-public-key-authentication-concept.adoc[將公開金鑰與使用者帳戶建立關聯]

+
您可以在啟用帳戶存取之前或之後執行此工作。

* 如果您不確定要指派給登入帳戶的存取控制角色、可以使用 `security login modify` 命令以稍後新增角色。


如果您想在叢集上啟用FIPS模式、則必須使用支援的金鑰類型來重新設定現有SSH公開金鑰帳戶、而不需要支援的金鑰演算法。  在您啟用FIPS之前、應先重新設定帳戶、否則系統管理員驗證將會失敗。

下表指出ONTAP 支援哪些主機金鑰類型演算法來進行支援以利執行支援的SSH連線。  這些金鑰類型不適用於設定SSH公用驗證。

[cols="30,30,30"]
|===


| 發行版ONTAP | FIPS模式支援的金鑰類型 | 非FIPS模式支援的金鑰類型 


 a| 
9.11.1 及更新版本
 a| 
ECDSA-SHA2-nistp256
 a| 
ECDSA-SHA2-nistp256 +
RSA-SHA2-512 +
RSA-SHA2-256 +
SSH-ed25519 +
SSH-DSS +
SSH-RSA



 a| 
9.10.1及更早版本
 a| 
ECDSA-SHA2-nistp256 +
SSH-ed25519.
 a| 
ECDSA-SHA2-nistp256 +
SSH-ed25519 +
SSH-DSS +
SSH-RSA

|===

NOTE: 9.11.1中移除SSH-ed25519主機金鑰演算法支援

如需詳細資訊、請參閱 link:../networking/configure_network_security_using_federal_information_processing_standards_@fips@.html["使用FIPS設定網路安全性"]。

.步驟
. 允許本機系統管理員帳戶使用SSH公開金鑰存取SVM：
+
`security login create -vserver _SVM_name_ -user-or-group-name user_or_group_name -application _application_ -authmethod _authentication_method_ -role _role_ -comment _comment_`

+
如需完整的命令語法、請參閱 link:config-worksheets-reference.html["工作表"]。

+
下列命令可啟用 SVM 管理員帳戶 `svmadmin1` 使用預先定義的 `vsadmin-volume` 存取 SVM 的角色``engData1`` 使用 SSH 公開金鑰：

+
[listing]
----
cluster1::>security login create -vserver engData1 -user-or-group-name svmadmin1 -application ssh -authmethod publickey -role vsadmin-volume
----


.完成後
如果您尚未將公開金鑰與系統管理員帳戶建立關聯、則必須先建立公開金鑰、帳戶才能存取SVM。

xref:manage-public-key-authentication-concept.adoc[將公開金鑰與使用者帳戶建立關聯]
