---
permalink: authentication/grant-access-active-directory-users-groups-task.html 
sidebar: sidebar 
keywords: enable, active directory, account access 
summary: 您可以使用安全性登入create命令、讓Active Directory（AD）使用者或群組帳戶能夠存取管理或資料SVM。AD群組中的任何使用者都可以使用指派給群組的角色來存取SVM。 
---
= 啟用Active Directory帳戶存取
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「安全登入create」命令、讓Active Directory（AD）使用者或群組帳戶能夠存取管理或資料SVM。AD群組中的任何使用者都可以使用指派給群組的角色來存取SVM。

.您需要的是 #8217 ；需要的是什麼
* 叢集時間必須在AD網域控制器上的時間後五分鐘內同步處理。
* 您必須是叢集管理員才能執行此工作。


.關於這項工作
* 您必須先設定AD網域控制器存取叢集或SVM、帳戶才能存取SVM。
+
xref:enable-ad-users-groups-access-cluster-svm-task.adoc[設定Active Directory網域控制器存取]

+
您可以在啟用帳戶存取之前或之後執行此工作。

* 如果您不確定要指派給登入帳戶的存取控制角色、可以使用「安全登入修改」命令稍後新增角色。
+
xref:modify-role-assigned-administrator-task.adoc[修改指派給系統管理員的角色]



[NOTE]
====
只有「SHU」和「ontapi」應用程式才支援AD群組帳戶存取。

====
.步驟
. 啟用AD使用者或群組管理員帳戶以存取SVM：
+
「安全性登入建立-vserver Svm_name -user-or group名稱user_or group名稱-applicationer -authmethod網域-role -comment comment」

+
如需完整的命令語法、請參閱 link:config-worksheets-reference.html["工作表"]。

+
link:config-worksheets-reference.html["建立或修改登入帳戶"]

+
下列命令可讓AD叢集管理員帳戶「DOMAIN1\guest1」（具有預先定義的「備份」角色）存取管理SVM「engCluster」（管理SVM）。

+
[listing]
----
cluster1::>security login create -vserver engCluster -user-or-group-name DOMAIN1\guest1 -application ssh -authmethod domain -role backup
----
+
下列命令可讓AD群組帳戶「DOMAIN1\adgroup」中的SVM系統管理員帳戶、使用預先定義的「vsadmin-volume」角色來存取SVM「engData」。

+
[listing]
----
cluster1::>security login create -vserver engData -user-or-group-name DOMAIN1\adgroup -application ssh -authmethod domain -role vsadmin-volume
----


如果您尚未設定AD網域控制器對叢集或SVM的存取、則必須先設定、帳戶才能存取SVM。

xref:enable-ad-users-groups-access-cluster-svm-task.adoc[設定Active Directory網域控制器存取]
