---
permalink: authentication/grant-access-active-directory-users-groups-task.html 
sidebar: sidebar 
keywords: enable, active directory, account access 
summary: 您可以使用安全性登入create命令、讓Active Directory（AD）使用者或群組帳戶能夠存取管理或資料SVM。AD群組中的任何使用者都可以使用指派給群組的角色來存取SVM。 
---
= 啟用Active Directory帳戶存取
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用「安全登入create」命令、讓Active Directory（AD）使用者或群組帳戶能夠存取管理或資料SVM。AD群組中的任何使用者都可以使用指派給群組的角色來存取SVM。

.您需要的產品
* 叢集時間必須在AD網域控制器上的時間後五分鐘內同步處理。
* 您必須是叢集管理員才能執行此工作。


.關於這項工作
* 您必須先設定AD網域控制器存取叢集或SVM、帳戶才能存取SVM。
+
xref:enable-ad-users-groups-access-cluster-svm-task.adoc[設定Active Directory網域控制器存取]

+
您可以在啟用帳戶存取之前或之後執行此工作。

* 從 ONTAP 9.13.1 開始、您可以使用 SSH 公開金鑰做為主要或次要驗證方法、並提供 AD 使用者密碼。
* 從功能性的版本起、您就可以開始使用ONTAP link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["用於nsswitch驗證的LDAP快速連結"] 如果AD LDAP伺服器支援此功能、
* 如果您不確定要指派給登入帳戶的存取控制角色、可以使用「安全登入修改」命令稍後新增角色。
+
xref:modify-role-assigned-administrator-task.adoc[修改指派給系統管理員的角色]



[NOTE]
====
僅支援 AD 群組帳戶存取 `SSH` 和 `ontapi` 應用程式：SSH 公開金鑰驗證通常用於多因素驗證、因此不支援 AD 群組。

====
.步驟
. 啟用AD使用者或群組管理員帳戶以存取SVM：
+
* 針對 AD 使用者： *

+
[cols="1,1,1,4"]
|===
| 版本ONTAP | 主要驗證 | 次要驗證 | 命令 


| 9.13.1 及更新版本 | 公開金鑰 | 無  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method publickey -role <role>
----


| 9.13.1 及更新版本 | 網域 | 公開金鑰  a| 
* 適用於新使用者 *

[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method domain -second-authentication-method publickey -role <role>
----
* 適用於現有使用者 *

[listing]
----
security login modify -vserver <svm_name> -user-or-group-name <user_name> -application ssh -authentication-method domain -second-authentication-method publickey -role <role>
----


| 9.0 及更新版本 | 網域 | 無  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application <application> -authentication-method domain -role <role> -comment <comment> [-is-ldap-fastbind true]
----
|===
+
* 對於 AD 群組： *

+
[cols="1,1,1,4"]
|===
| 版本ONTAP | 主要驗證 | 次要驗證 | 命令 


| 9.0 及更新版本 | 網域 | 無  a| 
[listing]
----
security login create -vserver <svm_name> -user-or-group-name <user_name> -application <application> -authentication-method domain -role <role> -comment <comment> [-is-ldap-fastbind true]
----
|===
+
如需完整的命令語法、請參閱 link:config-worksheets-reference.html["系統管理員驗證和 RBAC 組態工作表"]



.完成後
如果您尚未設定AD網域控制器對叢集或SVM的存取、則必須先設定、帳戶才能存取SVM。

xref:enable-ad-users-groups-access-cluster-svm-task.adoc[設定Active Directory網域控制器存取]
