---
permalink: authentication/grant-access-nis-ldap-user-accounts-task.html 
sidebar: sidebar 
keywords: enable, ldap, nis, account access 
summary: 您可以使用安全性登入create命令、讓LDAP或NIS使用者帳戶能夠存取管理或資料SVM。如果您尚未設定LDAP或NIS伺服器存取SVM、則必須先設定、帳戶才能存取SVM。 
---
= 啟用 LDAP 或 NIS ONTAP 帳戶存取
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
您可以使用 `security login create`命令來啟用 LDAP 或 NIS 使用者帳戶，以存取管理或資料 SVM 。如果您尚未設定LDAP或NIS伺服器存取SVM、則必須先設定、帳戶才能存取SVM。

.關於這項工作
* 不支援群組帳戶。
* 您必須先設定LDAP或NIS伺服器存取SVM、帳戶才能存取SVM。
+
xref:enable-nis-ldap-users-access-cluster-task.adoc[設定LDAP或NIS伺服器存取]

+
您可以在啟用帳戶存取之前或之後執行此工作。

* 如果您不確定要指派給登入帳戶的存取控制角色，可以使用 `security login modify`命令稍後再新增該角色。
+
如link:https://docs.netapp.com/us-en/ontap-cli/security-login-modify.html["指令參考資料ONTAP"^]需詳細 `security login modify`資訊，請參閱。

+
xref:modify-role-assigned-administrator-task.adoc[修改指派給系統管理員的角色]

* 從ONTAP 功能支援的版本為2、9.4開始、透過LDAP或NIS伺服器、遠端使用者可支援多因素驗證（MFA）。
* 從 ONTAP 9.11.1 開始，如果 LDAP 伺服器支援，您可以使用link:../nfs-admin/ldap-fast-bind-nsswitch-authentication-task.html["使用 LDAP 快速綁定對 ONTAP NFS SVM 進行 nsswitch 驗證"]。
* 由於已知的 LDAP 問題、您不應使用 `':'` （結腸） LDAP 使用者帳戶資訊任何欄位中的字元（例如、 `gecos`、 `userPassword`等）。否則、該使用者的查詢作業將會失敗。


.開始之前
您必須是叢集管理員才能執行此工作。

.步驟
. 啟用LDAP或NIS使用者或群組帳戶以存取SVM：
+
`security login create -vserver SVM_name -user-or-group-name user_name -application application -authmethod nsswitch -role role -comment comment -is-ns-switch-group yes|no [-is-ldap-fastbind true]`

+
link:config-worksheets-reference.html["建立或修改登入帳戶"]

+
下列命令可啟用 LDAP 或 NIS 叢集管理員帳戶 `guest2` 使用預先定義的 `backup` 存取管理 SVM 的角色``engCluster``。

+
[listing]
----
cluster1::>security login create -vserver engCluster -user-or-group-name guest2 -application ssh -authmethod nsswitch -role backup
----
+
如link:https://docs.netapp.com/us-en/ontap-cli/security-login-create.html["指令參考資料ONTAP"^]需詳細 `security login create`資訊，請參閱。

. 為LDAP或NIS使用者啟用MFA登入：
+
`security login modify -user-or-group-name rem_usr1 -application ssh -authentication-method nsswitch -role admin -is-ns-switch-group no -second-authentication-method publickey`

+
驗證方法可以指定為 `publickey` 和第二種驗證方法 `nsswitch`。

+
下列範例顯示正在啟用MFA驗證：

+
[listing]
----
cluster-1::*> security login modify -user-or-group-name rem_usr2 -application ssh -authentication-method nsswitch -vserver
cluster-1 -second-authentication-method publickey"
----


.完成後
如果您尚未設定LDAP或NIS伺服器存取SVM、則必須先設定、帳戶才能存取SVM。

xref:enable-nis-ldap-users-access-cluster-task.adoc[設定LDAP或NIS伺服器存取]

.相關資訊
* link:https://docs.netapp.com/us-en/ontap-cli/search.html?q=security+login["安全登入"^]

